### ISSUE TITLE
preproc_batch_tops.csh produces wrong baseline_table.dat

### ISSUE THREAD

**Issue by Xiaohua-Eric-Xu** [gmtsar/gmtsar#1]

**Comment by Xiaohua-Eric-Xu** [comment]
For now, one ca use get_baseline_table.csh to re-create the baseline_table.dat with correct file names, after running preproc_batch_tops.csh with mode = 2.

**Comment by Mieszko-Fydrych** [comment]
When "get_baseline_table.csh" is run, no baseline_table file is generated. I tried moving the file back from the F1 directory to F1/raw and running it again, but the file doesn't change. I also tried rerunning the preproc_batch_tops.csh with mode=2. Instead, all the terminal output I get it:

Usage: get_baseline_table.csh prmlist master_prm

     product: baseline_table.dat

**Comment by Xiaohua-Eric-Xu** [comment]
You need to feed inputs to this script.
e.g. 
get_baseline_table.csh list_of_your_PRMS.txt S1_20180926_ALL_F1.PRM

in list_of_your_PRMS.txt, 
S1_20180926_ALL_F1.PRM
S1_20181008_ALL_F1.PRM
S1_20181020_ALL_F1.PRM 
...
...

**Comment by Xiaohua-Eric-Xu** [comment]
made a fix (not tested) to master branch e677ddc2804bb0440054cdf3a2b449887d1b6df4
