### ISSUE TITLE
Rank deficiency of matrix in SBAS

### ISSUE THREAD

**Issue by yosukeaoki** [gmtsar/gmtsar#10]
Dear GMTSAR user, 

I am working on SBAS with GMTSAR, but I feel puzzled because I am informed that the matrix is rank-deficient. 

Pre-processing and alignment of SAR images and making interferograms seem to have worked fine, but when I run SBAS like 
% sbas intf.tab scene.tab 10 5 2710 2520
then I get the screen output as below, informing that the matrix is rank-deficient. 

I believe that the matrix is define regardless of the data (interferogram in this case), so this matrix deficiency might indicate that my scene.tab and intf.tab (see attached) might be wrong. However, I cannot see how I am wrong. 

Could you inform me of how I went wrong and how I can fix it?

Best Regards,
Yosuke Aoki 
Earthquake Research Institute, UTokyo

--------------------
setting smoothing to   0.000 
setting radar wavelength to   0.236 m 
setting radar incidence angle to  37.000 degree 
setting range to 866000.000 m 
Memory Allocation Successful...
read table file ...
number of SAR scenes is 5 
number of interferograms is 10 
read phase and correlation grids ...
0.000000 0.000102 0.000000 -22.023777
fill the G matrix ...
run least-squares problem over 2710 by 2520 pixel (0) ...
matrix is rank-deficient: 4

write output ...
--------------------

[intf.tab.zip](https://github.com/gmtsar/gmtsar/files/3882251/intf.tab.zip)
[scene.tab.zip](https://github.com/gmtsar/gmtsar/files/3882252/scene.tab.zip)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Yosuke,

The rank-deficiency is a numerical estimate from the dgelsy program.  

in sbas_utils.c:
                dgelsy_(&m, &n, &nrhs, G, &lda, d, &ldb, jpvt, &rcond, &rank, work, &lwork, &info);

                if (info != 0)
                    printf("warning! input has an illegal value\n");
                if (j == 0 && k == 0) {
                    if (rank == n) {
                        printf("matrix is full rank: %lld\n\n", rank);
                    }   
                    else if (rank < n) {
                        printf("matrix is rank-deficient: %lld\n\n", rank);
                        if (rank == 0) {
                            printf("WARNING: rank is zero. Check scene.tab and intf.tab for "
                                   "possible duplicates.\n\n");
                            for (i = 0; i < N; i++) {
                                for (p = 0; p < S - 1; p++) {
                                    printf("%.2f ", G[i + S * p]);
                                }   
                                printf("\n");
                            }   
                        }   
                    }   
                } 

Note that this step already has the G matrix weighted by the coherence and has the smoothing in it. So the deficiency here is not really an estimate on whether the whole problem set is robust (estimates will vary from pixel to pixel). Unless it has a very big rank-deficiency, I would not worry too much. A better way would be just checking the results directly.

Xiaohua(Eric)

**Comment by yosukeaoki** [comment]
Thanks Eric, I now understand how it works. I am actually getting odd velocities from ALOS-2 interferograms, but I think it is due to the data (interferograms) themselves.

**Comment by Xiaohua-Eric-Xu** [comment]
Also, you may not want to turn on the -atm option for ALOS-2 if your acquisitions are far apart in time. The -atm option in the sbas code [Tymofyeyeva and Fialko 2015] is optimal when you have dense and regular acquisitions.
