### ISSUE TITLE
preproc_batch_tops.csh data.in dem.grd 1

### ISSUE THREAD

**Issue by neda2133** [gmtsar/gmtsar#100]
Hello dear all

I am trying to conduct some SBAS ground deformation processing with Sentinel 1 datasets

I am receiving the below errors when I am running preproc_batch_tops.
it all stems from the XML file which is present in the raw folder.
please help me.
regards

errors:
Couldn't open tiff file: 
 s1a-iw2-slc-vv-20180410t140908-20180410t140933-021406-024da4-005.tiff 
 Couldn't open xml file: 
 S1_20180410_ALL_F2.PRM 
cp: cannot stat 'S1_20180410_ALL_F2.PRM': No such file or directory
 Can't open  junk1 
cat: junk1: No such file or directory
cat: junk2: No such file or directory
rm: cannot remove 'junk1': No such file or directory
rm: cannot remove 'junk2': No such file or directory
Reading in 4716 lines of info from XML...
Writing 16 lines for orbit...
TIFFOpen: s1a-iw2-slc-vv-20180504t140909-20180504t140934-021756-0258a2-005.tiff: No such file or directory.

**Comment by rofiaini** [comment]
Hi, What is the solution if you face a problem like the one above?

**Comment by Xiaohua-Eric-Xu** [comment]
Likely a broken link or permission issue I believe.
