### ISSUE TITLE
DEM generate

### ISSUE THREAD

**Issue by zahraforoodi** [gmtsar/gmtsar#1004]
Hello
I want to download Dem from https://topex.ucsd.edu/gmtsar/demgen/statcheck/
but  I encountered with Query could not be completed successfully.
ID: 1731255214.5.113.189.227

**Comment by Xiaohua-Eric-Xu** [comment]
The site is currently down. Try running make_dem.csh in the GMTSAR package to download DEM directly from U-Hawaii GMT server.

**Comment by xinchao131** [comment]
http://download.aviso.altimetry.fr 这个在ubuntu20.04火狐浏览器打不开啊
