### ISSUE TITLE
[Bug]: Why every time when I do iono correction plus region_cut, these appears?

### ISSUE THREAD

**Issue by HollyleafSTK** [gmtsar/gmtsar#1007]
1.
![image](https://github.com/user-attachments/assets/94b38813-c705-4596-adfe-4e8d84b1c4bb)
Why every time when I do iono correction plus region_cut, these appears?
And if I didn't put them together(only do iono or only do region_cut), they'd finished in half a day.

2.
![image](https://github.com/user-attachments/assets/b5afcf2d-e56e-4306-bbc6-1102015feb93)
Also I saw some error when region_cut, all about kml files, others are fine.

**Comment by Xiaohua-Eric-Xu** [comment]
1) The top error may lead to the later errors.
2) The top error is from this step (see attached). This is mainly for ALOS-2 ScanSAR data whose starting range may have a slight change that causes discontinuities across subswaths. But I am not exactly sure what gets you that error if the things were done automatically. 

![image](https://github.com/user-attachments/assets/47db62b1-7ba9-4b10-b3a9-a12a13bd3486)

**Comment by HollyleafSTK** [comment]
> 2. The top error is from this step (see attached). This is mainly for ALOS-2 ScanSAR data whose starting range may have a slight change that causes discontinuities across subswaths. But I am not exactly sure what gets you that error if the things were done automatically.

Yeah that's also mine suspect.
