### ISSUE TITLE
[Help]: Does anyone have any idea why doing SSM here would have such huge number of rad as result? Or any suggestion for doing SSM for iono correction here?

### ISSUE THREAD

**Issue by HollyleafSTK** [gmtsar/gmtsar#1009]
Data from ALOS2 WD1 (14MHz bandwidth)
The unwrapped of all subbands (High > Original/Central > Low):
![image](https://github.com/user-attachments/assets/b20d6a68-2e82-4150-90a7-fd4fe73036be)
Then here's how it be like after it corrected:
![image](https://github.com/user-attachments/assets/feceb258-8f8c-44c5-ade9-f5a9ff1f3866)
![image](https://github.com/user-attachments/assets/4b9751ce-8d00-4152-bd59-4ee6c0a72da0)
(11/21 comment: I suspect it didn't use subset files in some steps? The dark block area seems like the area I select for subset. Also in log those errors (grdcut [ERROR]: Requested subset is entirely to the left or to the right of the current data region) by this are inside snaphu.csh or snaphu_interp.csh. I do need an advice on how to fix it.)

Also corrected wrapped phase appears like this as result:
![image](https://github.com/user-attachments/assets/7c1bc5e9-2e13-4e83-8b02-53720920c7d6)
Here's an uncorrected one and yes there's iono-effect on it: (same data set, but cut region is a bit different, just to show)
![image](https://github.com/user-attachments/assets/0e89d962-83fb-4108-913e-c75ceae319f6)
Here's some related setting which some of these I'd took these issue comments and advices on GMTSAR Github here as references:
![image](https://github.com/user-attachments/assets/a3636ae3-49f0-4607-a030-8e5eaa16e144)

Also before I start use GMTSAR, I use SNAP doing a set of ALOS2 SM3 images, also have same issues. (wether filtered, ESD, or not)
Except adding the SSM process, other process/workflow are same as usual DInSAR process, do I miss something for doing SSM here in GMTSAR or in SNAP?

Also, if I didn't subset I'd get a fragmented unwrapped result, if I did subset I'd get a relative good results (for subbands only) but either these issue above appears or got a very huge number of phase on iono corrected interferogram.

Or do I just give up "p2p_ALOS2_SCAN_Frame.csh", and run all steps one by one?

11/22 comment: I remove mask_water but same error messages still appear.

22/26 comment: Seems like every error start from here:
![image](https://github.com/user-attachments/assets/ed3b7888-d92f-46e0-8b02-140ab6157b40)
Also I suspect there must be some coregistration issues here, whether cut or not, but I found no available change in the config:
![image](https://github.com/user-attachments/assets/1aa187da-b5b7-4fe9-bf35-65aadadc8ec7)
![image](https://github.com/user-attachments/assets/baeb0421-d9f6-4bbf-9b66-67eb7aadb7b8)
Btw, for cutting I'm sure the order is either west/east/south/north or left/right/down/top (for radar coordinate), is this correct?

**Comment by Xiaohua-Eric-Xu** [comment]
This looks like a problem from your prior post where an error occurred when running correct_merge_offset.csh. I am not sure yet what's causing the problem. You probably need to provide more details on what you did to estimate ionospheric phase. 

But do note that ramps could be also from orbit error.

**Comment by HollyleafSTK** [comment]
Thanks professor for commenting my issues!
I'd edit the first set of images which has same cut region as others here.

1. Here's the detail:
For doing ionospheric correction (SSM method) setting, I assume that I only need to edit these config setting:
![image](https://github.com/user-attachments/assets/36e438c6-230f-4973-b218-6601c1f34e8a)
Bascially I just enable the SSM process by setting it to 1 and the skip one to 0.
As for the rest of setting, I'm little bit confusing on what I should base on (I'm currently using ALOS2 WD1 with 14MHz bandwidth) while setting those RA filting and downsampling, so I'd dig the net and found that you'd gave an sugesstion on issue #733 (https://github.com/gmtsar/gmtsar/issues/733), so that I just set them for 0.5/0.5/2. (And after trying this one, I'd also upscale the number by this setting, such as 1/1/4 and others, but end up even couldn't genatate unwrapped map for the corrected map only left with errors like in the main post)
But as you see clearly the result also incorrect, order of magnitude for the number on the colorbar in the unwraped map imply that there are 300+ phases exist there. But yeah first this is the corrected one also shouldn't had similar pattern as the uncorrected one, plus either ionosphere wouldn't cause such huge number of phase error here.

2. Here is the config file for doing DInSAR+SSM:
[config_alo_D-iono.txt](https://github.com/user-attachments/files/17930303/config_alo_D-iono.txt)
Additionally I found the decimation setting now there's only "dec_factor = 2" in the newest version, I assume this would just be ok for ALOS2 WD1 images?

3. Last I wanna commenting about on my previous posts, I found after I do region_cut, the discontinuing issue just gone and never happen again. So I suppose it depend on how you cut the images instead of ESD or multilooks stuffs. Things would be tricky for me that I'd also need to do the image set of ascending orbit, where the coastline is not as parallel as in radar coordinate.
Also while I apply region_cut Idk why also errors appear, though I end up finding that'd only affect those kml files in the merge folder, though which won't be an issue since that could be transform by grd files in GIS apps.

And again, very thanks for reviewing my issues!

**Comment by HollyleafSTK** [comment]
> But do note that ramps could be also from orbit error.

Btw, I know unlike Sentinel 1 series, for ALOS2 either SM3 or WD1 product already has oribit informations within, also could be a reason why coregistration issues I'd mention in the main post. (Need to say that for each subband the unwrapped result look "fine" in both meanings, while didn't or haven't do SSM)
Is there any method to fix or at least check if is by orbit issues? Or I need to use other dates?

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what's the best way of checking whether the orbit product is precise or not. Maybe it is enlisted in the LED file but one has to check the handbook to be able to read it out I guess.
