### ISSUE TITLE
[Help]: create_frame_tops.csh 

### ISSUE THREAD

**Issue by charanchaganti93** [gmtsar/gmtsar#103]
I wanted to mosaic two files for which I have SAFE files using create_frame_tops.csh but this is the error that I got. details of the files are given below. Please guide 

**SAFE_Filelist:**
/home/ubuntu/Desktop/S1A_IW_SLC__1SDV_20170112T001858_20170112T001928_014791_018173_380C.SAFE
/home/ubuntu/Desktop/S1A_IW_SLC__1SDV_20170112T001926_20170112T001954_014791_018173_0639.SAFE
**two_pins.llt:**
28.40 84.60
26.37 84.31

**ERROR:**
create_frame_tops.csh SAFE_filelist S1A_OPER_AUX_POEORB_OPOD_20170112T121426_V20161222T225943_20161224T005943.EOF two_pins.llt 1
Combining vv data...

Working on subswath 1 ...
Reading in 5023 lines of info from XML...
Writing 17 lines for orbit...
NO orbit coverage in the selected file...
interpolation point outside of data constraints, 951497.805479 0.000000 0.000000
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: line 1: syntax error at or near )
interpolation point outside of data constraints, 951497.805479 0.000000 0.000000
interpolation point outside of data constraints, 951497.805479 0.000000 0.000000
awk: line 1: syntax error at or near )
Working on bursts covering  (28.40 84.60) -  (26.37 84.31)...

Usage: assemble_tops azi_1 azi_2 name_stem1 name_stem2 ... output_stem

Example: assemble_tops 1685 9732 s1a-iw1-slc-vv-20150706t135900-20150706t135925-006691-008f28-001 s1a-iw1-slc-vv-20150706t135925-20150706t135950-006691-008f28-001 s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001

Output:s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.xml s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.tiff

Note: output files are bursts that covers area between azi_1 and azi_2, set them to 0s to output all bursts
 Error: Incorrect input... 
 
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
mv: cannot stat 'new.xml': No such file or directory
mv: cannot stat 'new.tiff': No such file or directory

Working on subswath 2 ...
Reading in 5037 lines of info from XML...
Writing 17 lines for orbit...
NO orbit coverage in the selected file...
interpolation point outside of data constraints, 951498.761313 0.000000 0.000000
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: line 1: syntax error at or near )
interpolation point outside of data constraints, 951498.761313 0.000000 0.000000
interpolation point outside of data constraints, 951498.761313 0.000000 0.000000
awk: line 1: syntax error at or near )
Working on bursts covering  (28.40 84.60) -  (26.37 84.31) ...

Usage: assemble_tops azi_1 azi_2 name_stem1 name_stem2 ... output_stem

Example: assemble_tops 1685 9732 s1a-iw1-slc-vv-20150706t135900-20150706t135925-006691-008f28-001 s1a-iw1-slc-vv-20150706t135925-20150706t135950-006691-008f28-001 s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001

Output:s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.xml s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.tiff

Note: output files are bursts that covers area between azi_1 and azi_2, set them to 0s to output all bursts
 Error: Incorrect input... 
 
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
mv: cannot stat 'new.xml': No such file or directory
mv: cannot stat 'new.tiff': No such file or directory

Working on subswath 3 ...
Reading in 5051 lines of info from XML...
Writing 17 lines for orbit...
NO orbit coverage in the selected file...
interpolation point outside of data constraints, 951499.723313 0.000000 0.000000
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
interpolation point outside of data constraints, 951499.723313 0.000000 0.000000
awk: line 1: syntax error at or near )
interpolation point outside of data constraints, 951499.723313 0.000000 0.000000
awk: line 1: syntax error at or near )
Working on bursts covering  (28.40 84.60) -  (26.37 84.31) ...

Usage: assemble_tops azi_1 azi_2 name_stem1 name_stem2 ... output_stem

Example: assemble_tops 1685 9732 s1a-iw1-slc-vv-20150706t135900-20150706t135925-006691-008f28-001 s1a-iw1-slc-vv-20150706t135925-20150706t135950-006691-008f28-001 s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001

Output:s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.xml s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.tiff

Note: output files are bursts that covers area between azi_1 and azi_2, set them to 0s to output all bursts
 Error: Incorrect input... 
 
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
mv: cannot stat 'new.xml': No such file or directory
mv: cannot stat 'new.tiff': No such file or directory

Editing name of the new file...
ls: No match.
gmtinfo [ERROR]: No input data found!
ls: No match.
gmtinfo [ERROR]: No input data found!
ls: No match.
gmtinfo [ERROR]: No input data found!

**Comment by Xiaohua-Eric-Xu** [comment]
I think you selected a wrong orbit file. The name of the orbit file spans 20161222-20161224 while you data is 20170112.

**Comment by charanchaganti93** [comment]
Got this error even with correct orbit 
I think make_s1a_tops didn't work

Thanks 
Charan

root@GSDLBPreT3610:/home/ubuntu/Desktop# create_frame_tops.csh SAFE_filelist S1A_OPER_AUX_POEORB_OPOD_20170201T121351_V20170111T225942_20170113T005942.EOF two_pins.ll 1
Combining vv data...

Working on subswath 1 ...
Reading in 5023 lines of info from XML...
Writing 17 lines for orbit...
Writing 59 lines of precise orbit for the LED file...
interpolation point outside of data constraints, 956225.172449 951262.000000 951842.000000
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: line 1: syntax error at or near )
awk: line 1: syntax error at or near )
Working on bursts covering  (28.40 84.60) -  (26.37 84.31)...

Usage: assemble_tops azi_1 azi_2 name_stem1 name_stem2 ... output_stem

Example: assemble_tops 1685 9732 s1a-iw1-slc-vv-20150706t135900-20150706t135925-006691-008f28-001 s1a-iw1-slc-vv-20150706t135925-20150706t135950-006691-008f28-001 s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001

Output:s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.xml s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.tiff


Note: output files are bursts that covers area between azi_1 and azi_2, set them to 0s to output all bursts
 Error: Incorrect input... 
 
interpolation point outside of data constraints, 956225.172449 951262.000000 951842.000000
interpolation point outside of data constraints, 956291.168118 951262.000000 951842.000000
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
mv: cannot stat 'new.xml': No such file or directory
mv: cannot stat 'new.tiff': No such file or directory

Working on subswath 2 ...
Reading in 5037 lines of info from XML...
Writing 17 lines for orbit...
Writing 59 lines of precise orbit for the LED file...
interpolation point outside of data constraints, 956213.978039 951262.000000 951842.000000
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: line 1: syntax error at or near )
awk: line 1: syntax error at or near )
Working on bursts covering  (28.40 84.60) -  (26.37 84.31) ...

Usage: assemble_tops azi_1 azi_2 name_stem1 name_stem2 ... output_stem

Example: assemble_tops 1685 9732 s1a-iw1-slc-vv-20150706t135900-20150706t135925-006691-008f28-001 s1a-iw1-slc-vv-20150706t135925-20150706t135950-006691-008f28-001 s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001

Output:s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.xml s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.tiff


Note: output files are bursts that covers area between azi_1 and azi_2, set them to 0s to output all bursts
 Error: Incorrect input... 
 
grep: new.xml: No such file or directory
interpolation point outside of data constraints, 956279.457100 951262.000000 951842.000000
interpolation point outside of data constraints, 956213.978039 951262.000000 951842.000000
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
mv: cannot stat 'new.xml': No such file or directory
mv: cannot stat 'new.tiff': No such file or directory

Working on subswath 3 ...
Reading in 5051 lines of info from XML...
Writing 17 lines for orbit...
Writing 58 lines of precise orbit for the LED file...
interpolation point outside of data constraints, 956202.795767 951272.000000 951842.000000
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: line 1: syntax error at or near )
awk: line 1: syntax error at or near )
Working on bursts covering  (28.40 84.60) -  (26.37 84.31) ...

Usage: assemble_tops azi_1 azi_2 name_stem1 name_stem2 ... output_stem

Example: assemble_tops 1685 9732 s1a-iw1-slc-vv-20150706t135900-20150706t135925-006691-008f28-001 s1a-iw1-slc-vv-20150706t135925-20150706t135950-006691-008f28-001 s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001

Output:s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.xml s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.tiff


Note: output files are bursts that covers area between azi_1 and azi_2, set them to 0s to output all bursts
 Error: Incorrect input... 
 
grep: new.xml: No such file or directory
interpolation point outside of data constraints, 956267.760651 951272.000000 951842.000000
interpolation point outside of data constraints, 956202.795767 951272.000000 951842.000000
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
mv: cannot stat 'new.xml': No such file or directory
mv: cannot stat 'new.tiff': No such file or directory

Editing name of the new file...
ls: No match.
gmtinfo [ERROR]: No input data found!
ls: No match.
gmtinfo [ERROR]: No input data found!
ls: No match.
gmtinfo [ERROR]: No input data found!

**Comment by Xiaohua-Eric-Xu** [comment]
The key error is this line here.
```
interpolation point outside of data constraints, 956225.172449 951262.000000 951842.000000
```
Did you put correct numbers in pins.ll? It needs input as longitude latitude. Maybe you flipped the columns? This line below indicates you are looking at an area where no InSAR observations exist.
```
Working on bursts covering (28.40 84.60) - (26.37 84.31)...
```

**Comment by charanchaganti93** [comment]
Thank you so much it worked
