### ISSUE TITLE
Problem in sbas

### ISSUE THREAD

**Issue by ghazalehmatin1371** [gmtsar/gmtsar#109]
We have run sbas but the gmtsar view an error that after reading phase files the sbas was killed. We assume it is RAM error. We have 182interferogram,59scene,xdim=31.73,ydim=60.98.
We are wondering how much of RAM is required for running sbas?

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @ghazalehmatin1371 
xdim and ydim should be the dimension of the grid, not the coordinates. RAM should be largely, N_intf*xdim*ydim*4*2(*2 if -atm is specified)+N_scenes*xdim*ydim*4+Some_extra Bytes.
Xiaohua(Eric)
