### ISSUE TITLE
Some file name length is limited, e.g. make_s1a_tops.c tmp_str 

### ISSUE THREAD

**Issue by Xiaohua-Eric-Xu** [gmtsar/gmtsar#11]
This usually fails some codes when you have a "path+name" being 200+ characters long

**Comment by Xiaohua-Eric-Xu** [comment]
Now fixed with commit cb33cb4 on Feb 19, 2020.

**Comment by Xiaohua-Eric-Xu** [comment]
Now fixed for make_s1a_tops.c
cb33cb48a97fb7d511b95a8c589f15fe8115594c

**Comment by KsanaGSI** [comment]
I am new in GMTSAR. How can I make an updates?
I try this command unfortunately:
svn checkout svn://gmtserver.soest.hawaii.edu/GMT5SAR/trunk GMT5SAR
svn: E170013: Unable to connect to a repository at URL 'svn://gmtserver.soest.hawaii.edu/GMT5SAR/trunk'
