### ISSUE TITLE
[Help]: Segmentation fault core dumped error

### ISSUE THREAD

**Issue by ghazalehmatin1371** [gmtsar/gmtsar#112]
Dear Eric. We have run sbas code in gmtsar but we encounter an error “Segmentation fault core dumped”. I should note that we have 59 scene and 182 interferogram. The ram of system is 70gig with onboard GPU. We are wondering if it is possible that we have done
![IMG_20210306_143731](https://user-images.githubusercontent.com/78797020/110204973-3d5d2300-7e8b-11eb-8038-50512667e884.jpg)
 some mistakes in code in previous processes and the error is not related to amount of RAM, or it is just a RAM error and we should decrease the number of scene. 
[intf.txt](https://github.com/gmtsar/gmtsar/files/6095187/intf.txt)
[scene.txt](https://github.com/gmtsar/gmtsar/file

s/6095188/scene.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Do you have enough memory to run this many interferograms?

**Comment by arminfarshbaf** [comment]
We reduced the size of database and finally managed to resolve our problems.
Thanks Xiaohua for your comments. They helped us a lot.

**Comment by m0080782** [comment]
> We reduced the size of database and finally managed to resolve our problems. Thanks Xiaohua for your comments. They helped us a lot.

which database do you mean? is it local c or anything else?

**Comment by arminfarshbaf** [comment]
No, we just reduced the interferograms and scenes considerably to fix the problem. However, I think the main problem wasn't inadequate RAM but it was probably because of inconsistency between the GMT version and LINUX version. However, I didn't verify this and I'm not 100% positive.

**Comment by Xiaohua-Eric-Xu** [comment]
The newer version of sbas and sbas_parallel (currently in the master branch) both have options of -mmap to use disk space for storage of grids (temporarily used as memory) and reduce the usage of memory. They also output the required amount of memory at the malloc stage.
