### ISSUE TITLE
[Help]: Can't run ERS-ENVISAT and SENT1 demo script -

### ISSUE THREAD

**Issue by gg-bb** [gmtsar/gmtsar#117]
Good evening,

Any help would be appreciated, 

**Describe the problem you met**

I  tried to run  ERS-Envisat and Sentinel1 demos to test my GMTSAR installation (following the tutorial from scratch, I also downloaded the orbits and updated my PATH). To run the demos I applied the "Readme" instructions:
in the folder I run the command:

(ERS-Hector mine EQ folder) > p2p_ERS.csh e2_127_2907_23027 e2_127_2907_23528 config.ers.txt

All of them failed just before the align.csh step ends with the following error message **Segmentation fault (core dumped)**
There is no additional error messages. I tried to reinstall twice (gmt and gmt5sar) and still the same error happen. 

Thank you

**OS and software version**
OS: Ubuntu 20.04.2 LTS
GMTSAR version: last version (gmt 6)

**screen capture**
"  
...
align.csh
correlate master and aligned to find offset parameters
 setting xsearch to 128
 setting nx_corr to 256
 setting ysearch to 256
 setting ny_corr to 512
 setting nx to 20
 setting ny to 50
 6144 50400 6144 50400 10 -128 0.000000
 locations  n 1000 nx 6144 nyl 50 nxl 20 x_inc 233 y_inc 958
 elapsed time: 12208.713530 
align.csh
refocus aligned
Computing range reference function.
Processing patch 1
Processing Elapsed Time: 0 min 0.07 sec
Range Compression
Processing Elapsed Time: 0 min 19.45 sec
Azimuthal Transform
Processing Elapsed Time: 0 min 27.50 sec
Range Migration
Processing Elapsed Time: 0 min 28.24 sec
Azimuthal Compression
Processing Elapsed Time: 0 min 45.07 sec
apply azimuth-dependent azimuth shift 
**Segmentation fault (core dumped)
Segmentation fault (core dumped)**
ALIGN.CSH - END

clean up topo/ folder
"

**Comment by Xiaohua-Eric-Xu** [comment]
This is very strange. Could you attach a complete log? Not sure why the focusing was successful but re-focusing failed. Also, could you attach the prm files after alignment, i.e. with affine transformation parameters?

**Comment by gg-bb** [comment]
Thank You Eric for your help,

Please find the requested files (ERS_Hector mine):
-screen log
-prm files (found in the intf/date1_date2 rep; *23528.PRM seems wrong at the end of the file)

Beside, I have tried to run gmt command independently and it show strange messages. For instance, when I type 'gmt' in my terminal, it prints:
"...
free():invalid pointer
Abandon (core dumped)
"
Is it a gmt 6.0.0 installation issue?

Best regards.
GB

[p2p_ERS_ScreenLog.txt](https://github.com/gmtsar/gmtsar/files/6267130/p2p_ERS_ScreenLog.txt)

[e2_127_2907_23528 .PRM.txt](https://github.com/gmtsar/gmtsar/files/6267141/e2_127_2907_23528.PRM.txt)

[e2_127_2907_23027.PRM.txt](https://github.com/gmtsar/gmtsar/files/6267144/e2_127_2907_23027.PRM.txt)

**Comment by gg-bb** [comment]
Edit:
I just reinstalled gmt and gmtSAR (master branch) and the problem remains...

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure how, but all the affine transformation parameters are not correctly estimated.
```
rshift =  -nan 
sub_int_r =  -nan 
stretch_r =  inf 
a_stretch_r =  -nan 
ashift =  -nan 
sub_int_a =  -nan 
stretch_a =  inf 
a_stretch_a =  -nan 
```
If you run SAT_baseline on the original PRM files in the raw folder. What pops out?

**Comment by gg-bb** [comment]
Here the result:

> SAT_baseline e2_127_2907_23027.PRM  e2_127_2907_23528.PRM

using command line
SC_identity = 2 
......master LED file e2_127_2907_23027.LED 
.........aligned LED file e2_127_2907_23528.LED 
lon_tie_point =  -116.254433
lat_tie_point =  35.111041
SC_vel              = 7109.950403000000 
SC_height           = 788240.407598576508 
SC_height_start     = 788159.114875628613 
SC_height_end       = 788321.892348724417 
earth_radius        = 6371444.277831000276 
rshift              = 7 
sub_int_r           = 0.0 
ashift              = -40
sub_int_a           = 0.0 
B_parallel          = -27.394096309865 
B_perpendicular     = -16.039642387454 
baseline_start      = 31.744395419531 
baseline_center     = 34.557014050566 
baseline_end        = 37.476722992519 
alpha_start         = 144.209345109633 
alpha_center        = 147.784367011243 
alpha_end           = 150.809463554441 
B_offset_start      = -164.650263739715 
B_offset_center     = -164.138038816478 
B_offset_end        = -163.616993845698

**Comment by Xiaohua-Eric-Xu** [comment]
Do you have the freq_xcorr.dat file in the SLC folder? How does it look like?

**Comment by gg-bb** [comment]
I solved the problem!!
I have added: 
"export LC_ALL=C.UTF-8"
At the end of my .bashrc file and everything seems to work so far.

awk command wasn't processing the xcorr output as float numbers but as string instead (because of the comma in float number, ie 12,5 isn't read as a number).

Thanks for your help!

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, that's really strange. I don't remember outputting any comma in the code. Any idea on that?

**Comment by gg-bb** [comment]
My LC_ALL variable wasn't defined in my Ubuntu version (do not know why) and that was the source of the problem. As far as I investigate, I found the problem when trying to run manually the following "fitoffset.csh" commands : 

l36 > awk '{ if ($5 > '$SNR') printf("%f %f %f \n",$1,$3,$2); }' < $3 > r.xyz
l37 > awk '{ if ($5 > '$SNR') printf("%f %f %f \n",$1,$3,$4); }' < $3 > a.xyz
...
l58 > ( gmt trend2d r.xyz -Fxyz -N"$rng_p"r -V >  /dev/null ) |& grep oefficients | awk -F":" '{print $NF, 0, 0, 0'} > rm.coef
l59 > ( gmt trend2d a.xyz -Fxyz -N"$azi_p"r -V >  /dev/null ) |& grep oefficients | awk -F":" '{print $NF, 0 ,0, 0'} > am.coef

I think that the awk commands used to create r.xyz and a.xyz from xcorr_output.dat change the number format some how, and lead gmt trend2d to fail

I could manually solve the problem by adding LC_ALL=C in front of the line 36 and 37:
l36 > LC_ALL=C awk '{ if ($5 > '$SNR') printf("%f %f %f \n",$1,$3,$2); }' < $3 > r.xyz ...

And that lead me to define my LC_ALL variable in my .bashrc file

**Comment by dsandwell** [comment]
Hi All,

The problem may be in fitoffset.csh where there are several awk commands.  

1) Is this the ERS Hector example?

2) Looks like UBUNTU 20

Maybe we can add something to every script that uses awk to prevent this issue.

Thanks,

david


> On Apr 7, 2021, at 10:07 AM, Xiaohua(Eric) Xu ***@***.***> wrote:
> 
> 
> Hmmm, that's really strange. I don't remember outputting any comma in the code. Any idea on that?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by Xiaohua-Eric-Xu** [comment]
@PaulWessel recommended using gawk I think a while ago. Could this be the case?

**Comment by PaulWessel** [comment]
It could be, but the mention of commas in numbers is probably indicative of a LC_* setting issue selecting European formatting.
