### ISSUE TITLE
grdview gmt 

### ISSUE THREAD

**Issue by neda2133** [gmtsar/gmtsar#118]
hi dear all.
 
![vel_ll](https://user-images.githubusercontent.com/73532419/114280695-c4d02000-9a4f-11eb-8e49-3fa929d88a87.png)
 
i created mean velocity map . how can i plot   mean velocity map with grdview gmt?
regards
neda

**Comment by Xiaohua-Eric-Xu** [comment]
Here's the grdview documentation. http://gmt.soest.hawaii.edu/doc/latest/grdview.html
You could also try grdimage with -JM6i -Baf.

**Comment by neda2133** [comment]
> Here's the grdview documentation. http://gmt.soest.hawaii.edu/doc/latest/grdview.html
> You could also try grdimage with -JM6i -Baf.

hi dear Eric
what do you mean by  grdimage with -JM6i -Baf.? what is the complete script?  thank you for guiding me further. 
regards

**Comment by Xiaohua-Eric-Xu** [comment]
Sorry I missed your question. You could look at 1) geocode.csh or 2) grd2kml.csh for the plotting. In both, grdimage is used.
