### ISSUE TITLE
[Help]: How to compile abas_parallel on Ubuntu?

### ISSUE THREAD

**Issue by Twcumtb** [gmtsar/gmtsar#119]
Hi Xiaohua,
   I found an exciting new feature that sbas can run in parallel with sbas_parallel, which supports doing time series analysis with a larger area. But looks that you only provide the configuration on Mac. How to compile this on Ubuntu?
Thank you.

**Comment by wojmil** [comment]
Hi Twcumtb,

try with these build flags:

_gcc -fopenmp -w sbas_parallel.c -I/usr/local/include/gmt -I/usr/local/GMTSAR/gmtsar -I/usr/local/include -L/usr/local/GMTSAR/gmtsar -lgmtsar -llapack -L/usr/local/lib -lgmt -L/usr/local/lib -ltiff -lm -o sbas_parallel_

Wojtek

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Twcumtb and wojmil,
You probably need to first find a c-compiler that support openMP. Then use it to compile as what wojmil mentioned. The default c complier on Mac does not do that, but I am not sure which c compiler Ubuntu uses.
Also, the efficiency may not scale linearly with more cores due to the IO and other computations. And the code is not well tested yet, so do get us some feedback if you got any when using it.
Cheers,
Xiaohua(Eric)

**Comment by wojmil** [comment]
Hi Eric,

indeed, I used gcc version 10 to compile sbas_parallel. I tested it on: 
1) Debian 10 (buster) with 32 cores, 
2) Ubuntu server 20.04 LTS with 64 cores 
3) CentOS Linux release 7.9.2009 with over 1000 cores. 
In each case, the calculations ran smoothly. I also compared the sbas parallel results with the sbas results without the "parallel" option. They seem to coincide. 

I guess what I am going to write is obvious. But if you want to (Twcumtb) use sbas for a really large area then you need to remember about memory too ... a lot of memory. 

Wojtek

**Comment by MinervaLee0429** [comment]
@wojmil Dear Professor, I could not find the instructions for installing sbas_parallel in centos system, so I would like to ask you what should be done? Thank you for your generous reply.

**Comment by Xiaohua-Eric-Xu** [comment]
You could us yum to install all the dependencies. However, if you are using older version of CentOS, try what's suggested here: https://github.com/gmtsar/gmtsar/wiki/Installing-GMTSAR-on-CentOS7-or-other-old-systems.

**Comment by MinervaLee0429** [comment]
@Xiaohua-Eric-Xu Thank you for your generous reply, professor, we followed the tutorial you mentioned when installing sbas_parallel. Just now I got the answer, according to another expert's explanation, sbas_parallel is written using openmp, so it cannot run across nodes in the supercomputer, so now we are trying other things.

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, in order to make things easier to do we picked openmp, but it clearly comes with a cost.
