### ISSUE TITLE
stack smash error when organize_file_tops_linux.csh runs on ubuntu (SAT_llt2rat)

### ISSUE THREAD

**Issue by Xiaohua-Eric-Xu** [gmtsar/gmtsar#12]
Found on ubuntu 16.0, 18.0, etc.  Unable to reproduce on Mac

From Quanwen Li:

Saving to:
‘S1A_OPER_AUX_POEORB_OPOD_20180311T120551_V20180218T225942_20180220T005942.E
OF’
S1A_OPER_AUX_POEORB_OPOD_2018031 100%
[=========================================================>] 4.21M 931KB/s
in 4.6s
2020-01-24 15:01:16 (931 KB/s) -
‘S1A_OPER_AUX_POEORB_OPOD_20180311T120551_V20180218T225942_20180220T005942.E
OF’ saved [4409491/4409491]
Reading in 5053 lines of info from XML...
Writing 17 lines for orbit...
Writing 58 lines of precise orbit for the LED file...
*** stack smashing detected ***: SAT_llt2rat terminated
*** stack smashing detected ***: SAT_llt2rat terminated
Reading in 5053 lines of info from XML...
Writing 17 lines for orbit...
Writing 58 lines of precise orbit for the LED file...
*** stack smashing detected ***: SAT_llt2rat terminated
*** stack smashing detected ***: SAT_llt2rat terminated

**Comment by Xiaohua-Eric-Xu** [comment]
Not exactly sure, but here is a temporary fix.

go to your GMTSAR folder, edit config.mk
75 CFLAGS          =  -O2 -Wall -m64 -fPIC -fno-strict-aliasing -std=c99 
at the end attach -fno-stack-protector
75 CFLAGS          =  -O2 -Wall -m64 -fPIC -fno-strict-aliasing -std=c99 -fno-stack-protector

recompile the code (make spotless first) and then the error should be gone.

**Comment by Xiaohua-Eric-Xu** [comment]
Found issue with goldop function where computed position exceeding orbit array boundary in SAT_llt2rat.

**Comment by Xiaohua-Eric-Xu** [comment]
A new fix to avoid this situation is implemented.
e2e1653df4c361b7c42a746ea2c361005df8101b

**Comment by khakim** [comment]
I got this problem, but how to recompile the code (make spotless) and reinstall?

is the following ordered command true: (after editing config.mk)
- make
- make install

**Comment by Xiaohua-Eric-Xu** [comment]
That's right, after ./configure and config.mk is produced, edit it and change that line mentioned above, then make and make install.

**Comment by khakim** [comment]
Ok thank so much for the solution. it works.

**Comment by khakim** [comment]
I am preparing input parameters for SBAS in GMTSAR and we need x_min (minimum range), x_max (maximum range) and incidence angle. And I tried to follow this link http://gmt.soest.hawaii.edu/boards/6/topics/7951, but I don't know how to find information the x_min, x_max, and incidence angle. Please, let me know in which file we get these parameters?

**Comment by Xiaohua-Eric-Xu** [comment]
If you do a `gmt grdinfo -I-` on one of your phasefilt.grd, the range information will pop up.

**Comment by khakim** [comment]
Thanks for your help. I can find the range information, but not for incidence angle.

**Comment by Xiaohua-Eric-Xu** [comment]
The incidence angle is a rough estimate and is only used for DEM error correction. Usually, we use the average of a scene, for example, 3 subswaths of TOPS data, the angle is roughly 37-38. It does not have to be very accurate.

**Comment by khakim** [comment]
Ok thanks.
By the way, I read the discussion about a topic  in this link http://gmt.soest.hawaii.edu/boards/6/topics/8462?r=8470#message-8470.
How do you set "quiet" region to 0?

**Comment by nicunecula** [comment]
Hi Eric,
I am using gmtsar version 6.0 on Ubuntu 20.04 and I am getting a similar error like the one you posted. Can you help me with that and suggest me what should I do?
I tried the changes you mentioned but I am still getting the same error:


Saving to: ‘S1A_OPER_AUX_POEORB_OPOD_20171118T121937_V20171028T225942_20171030T005942.EOF’

S1A_OPER_AUX_POEORB_OPOD_2 100%[=====================================>]   4,21M   822KB/s    in 6,2s    

2020-08-28 21:14:03 (698 KB/s) - ‘S1A_OPER_AUX_POEORB_OPOD_20171118T121937_V20171028T225942_20171030T005942.EOF’ saved [4409546/4409546]

Reading in 4903 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
*** stack smashing detected ***: terminated
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: line 1: syntax error at or near )
Reading in 4903 lines of info from XML...
*** stack smashing detected ***: terminated
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
*** stack smashing detected ***: terminated
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: line 1: syntax error at or near )

SKIP 20171029, as it does not have enough scenes ...

**Comment by Xiaohua-Eric-Xu** [comment]
Are you sure that your system is still complaining after turning on the no-stack-protector flag? This sounds strange.
You could also try to update the code https://github.com/gmtsar/gmtsar/commit/e2e1653df4c361b7c42a746ea2c361005df8101b

**Comment by nicunecula** [comment]
I compiled again from the very beginning with the no-stack-protector flag and I am not getting that message anymore.
Thank you!

**Comment by KamogeloBaloyi** [comment]
I used -z muldefs and the solution #12 together and it worked.Thank you very much!!!
