### ISSUE TITLE
[Help]: sbas running 

### ISSUE THREAD

**Issue by charanchaganti93** [gmtsar/gmtsar#124]
sbas intf.tab scene.tab 122 67 8530 6534 -range 8485288 -incidence 40 -wavelength 0.0554658 -smooth 5.0 -rms -dem

This is the command we entered for running sbas although the 122 interferograms are selected deleting the faulty ones i.e. we got 125 in total but for two of the subswaths 3 could not be generated so I deleted them and run sbas

But we got this error 
![Screenshot_20210428_204525](https://user-images.githubusercontent.com/71376959/116429437-83b77880-a863-11eb-9bfe-1d2d3e109ef9.jpg)

Please help

**Comment by Xiaohua-Eric-Xu** [comment]
Make sure you have enough RAM to run the sbas code. It reads in all the input data to memory.

**Comment by dhy158** [comment]
> 
> 
> Make sure you have enough RAM to run the sbas code. It reads in all the input data to memory.

Sir, How much memory do I need for 116 scenes, 258 interferograms

**Comment by Xiaohua-Eric-Xu** [comment]
For your case, it should be (8556*6531*258*4)/1024^3 + etc > 56GB RAM. If you turn on -atm option, it'll double. I suggest you downsample your interferograms. e.g `gmt grdsample unwrap.grd -I32/8 -Gunwrap_dsamp.grd`

**Comment by dhy158** [comment]
> 
> 
> For your case, it should be (8556_6531_258*4)/1024^3 + etc > 56GB RAM. If you turn on -atm option, it'll double. I suggest you downsample your interferograms. e.g `gmt grdsample unwrap.grd -I32/8 -Gunwrap_dsamp.grd`

Thank your reply, Prof Xu,
In my case, I try to extract landside deformation. If I downsample my interferograms, i'm afraid that the final result get nothing because of the low resolution of S1. 
Like you said, I need memory > 56GB RAM. My compute memory is larger than it, Why it is not enough still? What is the best solution without adding new physical memory?
Thanks again for your reading.

**Comment by Xiaohua-Eric-Xu** [comment]
Usually for landslide, the area should be very small. Could you cut your interferograms? e.g. with grdcut?

**Comment by dhy158** [comment]
> 
> 
> Usually for landslide, the area should be very small. Could you cut your interferograms? e.g. with grdcut?
I think so, but my extract area is large(by the Jinsha River), cut option is not easy to implement.

**Comment by Xiaohua-Eric-Xu** [comment]
Are you doing this with detection purpose? InSAR time-series's suppose to work well only for slow landslides. Not sure how this could be done in a wise way. Maybe STAMPS?

**Comment by dhy158** [comment]
> 
> 
> Are you doing this with detection purpose? 
Yes, I try to use gmtsar sbas to do it, you mean this method is not proper?

**Comment by Xiaohua-Eric-Xu** [comment]
I think you need to largely know what you are looking at. Most small-scale landslides have very sharp deformation that'll decorrelate the image. You could give it a try, but I am not sure it'll work.

**Comment by dhy158** [comment]
Unfortunately, my area is poor coherence, there is a lot of vegetation cover. I will think again, or try another method.

**Comment by Xiaohua-Eric-Xu** [comment]
Then persistent scatter might be the way to go.

**Comment by dhy158** [comment]
There are a few PS points in the vegetation coverage area, how do i do in PSInSAR
