### ISSUE TITLE
[Help]: SBAS error

### ISSUE THREAD

**Issue by jmm688** [gmtsar/gmtsar#126]
Hello!

I've been working on the GMTSAR Sentinel-1 TOPS Time Series example and ran into a few errors when trying to run the sbas.txt file.

I have already successfully run the README:
1) prep.txt
2)proc.txt

However, when I run the sbas.txt I get this result in the terminal...
rm: SBAS: is a directory
mkdir: SBAS: File exists

compute RMS misfit
compute DEM error

setting smoothing to   0.000 
setting radar wavelength to   0.055 m 
setting radar incidence angle to  30.000 degree 
setting range to 800184.946 m 
Memory Allocation Successful...
read table file ...
number of SAR scenes is 5 
number of interferograms is 9 
read phase and correlation grids ...
 dimension don't match! ../intf_all/2015020_2015068/corr.grd 
ln: ./trans.dat: File exists
proj_ra2ll.csh
grd2xyz [ERROR]: Cannot find file vel.grd
grd2xyz [ERROR]: Cannot find file vel.grd
grd2xyz [ERROR]: File vel.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
gmtinfo [ERROR]: No input data found!
surface [ERROR]: Must specify -R option
surface [INFORMATION]: Provides 5, expects 3-column binary data
surface [ERROR]: Must specify -R option
surface [INFORMATION]: Provides 5, expects 3-column binary data
grdtrack [ERROR]: Cannot find file raln.grd
grdtrack [ERROR]: Cannot find file ralt.grd
grdtrack [ERROR]: Must specify -G at least once
gmtconvert [WARNING]: File <stdin> is empty!
gmtconvert [WARNING]: No data records provided
ls: No match.
Sampling in geocoordinates with deault (60 meter) pixel size ...
gmtinfo [ERROR]: No input data found!
range: Subscript out of range.
gmtmath [ERROR]: Operation "DIV" requires 2 operands
lgmtmath [ERROR]: Operation "MUL" requires 2 operands
gmtinfo [ERROR]: No input data found!
blockmedian [ERROR]: Unable to decode  as a floating point number
blockmedian [ERROR]: Option -I parsing failure.  Correct syntax:
	-I Specify increment(s) and optionally append units or flags.
	   Full syntax is <xinc>[d|m|s|e|f|k|M|n|u][+e|n][/<yinc>[d|m|s|e|f|k|M|n|u][+e|n]]]
	   For geographic regions in degrees you can optionally append units from this list:
	   (d)egree [Default], (m)inute, (s)econd, m(e)ter, (f)oot, (k)ilometer, (M)ile, (n)autical mile, s(u)rvey foot.
	   Append +e to adjust the region to fit increments [Adjust increment to fit domain].
	   Alternatively, specify number of nodes by appending +n. Then, the increments
	   are calculated from the given domain and node-registration settings
	   (see Appendix B for details).  Note: If -R<grdfile> was used then -I
	   (and -R and maybe -r) have been set; use -I to override those increments.
blockmedian [ERROR]: Must specify -R option
blockmedian [ERROR]: Option -I: Must specify positive increment(s)
blockmedian [INFORMATION]: Provides 3, expects 3-column binary data
xyz2grd [ERROR]: Unable to decode  as a floating point number
xyz2grd [ERROR]: Option -I parsing failure.  Correct syntax:
	-I Specify increment(s) and optionally append units or flags.
	   Full syntax is <xinc>[d|m|s|e|f|k|M|n|u][+e|n][/<yinc>[d|m|s|e|f|k|M|n|u][+e|n]]]
	   For geographic regions in degrees you can optionally append units from this list:
	   (d)egree [Default], (m)inute, (s)econd, m(e)ter, (f)oot, (k)ilometer, (M)ile, (n)autical mile, s(u)rvey foot.
	   Append +e to adjust the region to fit increments [Adjust increment to fit domain].
	   Alternatively, specify number of nodes by appending +n. Then, the increments
	   are calculated from the given domain and node-registration settings
	   (see Appendix B for details).  Note: If -R<grdfile> was used then -I
	   (and -R and maybe -r) have been set; use -I to override those increments.
xyz2grd [ERROR]: Must specify -R option
xyz2grd [ERROR]: Option -I: Must specify positive increment(s)
grd2cpt [ERROR]: Cannot find file vel_ll.grd
grdinfo [ERROR]: Cannot find file vel_ll.grd
grdinfo [ERROR]: Must specify one or more input files
gmtmath [ERROR]: Operation "INV" requires 1 operands
grdimage [ERROR]: Cannot find file vel_ll.grd
Make vel_ll.kml and vel_ll.png
psconvert [INFORMATION]: Processing vel_ll.ps...
psconvert [INFORMATION]: Find HiResBoundingBox ...
psconvert [ERROR]: The file vel_ll.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.

I looked into the dimensions error and found this:

**unwrap**
gmt grdinfo -C ../intf_all/2015068_2015092/unwrap.grd.
0	21568	0	5484	-4.6184387207	8.13578987122	16	4	1348	1371	1	0

**Correlation**
gmt grdinfo -C corr.grd                     
0	21568	0	5484	0.00439857272431	0.98726695776	16	4	1348	1371	1	0

**OS and software version**
OS: MacOS Catalina 10.15.6
GMTSAR version: 6.0

Any help would be greatly appreciated,
Cheers!

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, what is the dimension of input in your sbas command? i.e. in the sbas.txt you ran. Do they match your unwrap.grd and corr.grd?

**Comment by jmm688** [comment]
hmm, I'm using the README_sbas.txt  : 

set xdim = `gmt grdinfo -C ../intf_all/2015068_2015092/unwrap.grd | awk '{print $10}'`
set ydim = `gmt grdinfo -C ../intf_all/2015068_2015092/unwrap.grd | awk '{print $11}'`

where:
xdim = 1348 
ydim = 1371

when I check the  xdim and ydim of corr.grid these are the exact same values.

**Comment by Xiaohua-Eric-Xu** [comment]
Then is this specific file different from the rest?
../intf_all/2015020_2015068/corr.grd

**Comment by jmm688** [comment]
I checked the x and y and they are all the same. Just in case I didn't answer your question, I've attached a .txt file with the grdinfo
[gmt_grdinfo.txt](https://github.com/gmtsar/gmtsar/files/6417401/gmt_grdinfo.txt)

**Comment by jmm688** [comment]
There is a copy and paste mistake in the .txt file, but in the terminal:

/unwrap.grd | awk '{print $10}' 
/corr.grd | awk '{print $10}'
are always 1348

and

/corr.grd | awk '{print $11}'
/unwrap.grd | awk '{print $11}'
are always 1371

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, I don't know. The error is indicating a mismatch in dimensions. The error is associated with the following lines in sbas.c
```
273         xin = CC->header->n_columns;
274         yin = CC->header->n_rows;
275         if (xin != xdim || yin != ydim)
276             die("dimension don't match!", cfile[i]);
```
So it has to be the n_columns or n_rows not matching the xdim or ydim.

**Comment by jmm688** [comment]
Ok, so I finally got it to work...

from
set xdim = gmt grdinfo -C ../intf_all/2015068_2015092/unwrap.grd | awk '{print $10}'
set ydim = gmt grdinfo -C ../intf_all/2015068_2015092/unwrap.grd | awk '{print $11}'

instead of using $xdim $ydim in the README file..... I replaced it with the actual integer values 1348 and 1371 respectively. 

I don't know why this worked? I am still pretty new to bash.

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what went wrong. Your commands look correct to me.
