### ISSUE TITLE
[Help]: Unwrapping problem

### ISSUE THREAD

**Issue by duzihao-123** [gmtsar/gmtsar#131]
Hello,Eric,I have some questions about unwrapping want to ask you and get your some suggestions.
I found that the range of the interference images in the F1, F2, and F3 files is about 20000, and the azimuth is about 12000, so I run snaphu_interp.csh 0.10 40 0/60000/0/12000 in the merge file, and it always makes an error. When it is adjusted to snaphu_interp.csh 0.10 40 0/30000/0/12000, it can run through, so what is the reason? what does that 40 mean and how can I unwrap all the images of my three strips?

**Comment by Xiaohua-Eric-Xu** [comment]
Did you merge the interferograms together first? p2p_S1_TOPS_Frame.csh should do all these automatically.

**Comment by duzihao-123** [comment]
> Did you merge the interferograms together first? p2p_S1_TOPS_Frame.csh should do all these automatically.

Hello，Eric，I merged the interferograms use command "merge_batch.csh merge_list batch_tops.config",is there any mistake?

**Comment by Xiaohua-Eric-Xu** [comment]
If you run a `gmt grdinfo` on your phasefilt.grd, what's the information pops out?

**Comment by Xiaohua-Eric-Xu** [comment]
Also when your snaphu.csh fails, any log file I could look at?

**Comment by duzihao-123** [comment]
> If you run a `gmt grdinfo` on your phasefilt.grd, what's the information pops out?

when i run  `gmt grdinfo` on my merge file it shows:

gmt grdinfo [core] 6.0.0 [64-bit] - Extract information from grids

usage: gmt grdinfo <grid> [-C[n|t]] [-D[<offx>[/<offy>][+i]] [-F] [-I[<dx>[/<dy>]|b|i|r]] [-L[a|0|1|2|p]] [-M]
	[-R<west>/<east>/<south>/<north>[+r]] [-T[<dz>][+a[<alpha>]][+s]] [-V[<level>]] [-f[i|o]<info>]
	[-ho[<nrecs>][+c][+d][+r<remark>][+t<title>]] [-o<cols>[,...][t[<word>]]] [--PAR=<value>]

	<grid> may be one or more grid files.

	OPTIONS:
	-C Format report in fields on a single line using the format
	   <file w e s n z0 z1 dx dy n_columns n_rows [x0 y0 x1 y1] [med L1scale] [mean std rms] [n_nan] [mode LMSscale]>,
	   where -M adds [x0 y0 x1 y1] and [n_nan], -L1 adds [median L1scale], -L2 adds [mean std rms],
	   and -Lp adds [mode LMSscale]).
	   Use -Ct to place <file> at the end of the output record, or -Cn to write only numerical columns.
	-D Report tiles using tile size set in -I. Optionally, extend each tile region by <offx>/<offy>.
	   Append +i to only report tiles if the subregion has data (limited to one input grid).
	   If no grid is given then -R must be given and we tile based on the given region.
	-F Report domain in world mapping format [Default is generic].
	-I Return textstring -Rw/e/s/n to nearest multiple of dx/dy.
	   If -C is set then rounding off will occur but no -R string is issued.
	   If no argument is given then the -I<xinc>/<yinc> string is issued.
	   If -Ib is given then the grid's bounding box polygon is issued.
	   If -Ii is given then the original img2grd -R string is issued, if available.
	     If the grid is not an img grid then the regular -R string is issued.
	   If -Ir is given then the grid's -R string is issued.
	-L Set report mode:
	   -L0 reports range of data by actually reading them (not from header).
	   -L1 reports median and L1 scale (MAD w.r.t. median) of data set.
	   -L[2] reports mean, standard deviation, and rms of data set.
	   -Lp reports mode (lms) and LMS-scale (MAD w.r.t. mode) of data set.
	   -La all of the above.
	   If grid is geographic then we report area-weighted statistics.
	-M Search for the global min and max locations (x0,y0) and (x1,y1).
	-R Specify the min/max coordinates of your data region in user units.
	   Use dd:mm[:ss] for regions given in arc degrees, minutes [and seconds].
	   Use -R<xmin/xmax/ymin/ymax>+<unit> for regions given in projected coordinates.
	     with <unit> selected from e|f|k|M|n|u.
	   Use [yyy[-mm[-dd]]]T[hh[:mm[:ss[.xxx]]]] format for time axes.
	   Append +r if -R specifies the coordinates of the lower left and
	     upper right corners of a rectangular area.
	   Use -R<gridfile> to use its limits (and increments if applicable).
	   Use -Rg and -Rd as shorthands for -R0/360/-90/90 and -R-180/180/-90/90.
	   Derive region from closed polygons from the Digital Chart of the World (DCW):
	     Append a comma-separated list of ISO 3166 codes for countries to set region, i.e.,
	     <code1>,<code2>,... etc., using the 2-character ISO country codes (see pscoast -E+l for list).
	     To select a state of a country (if available), append .state, e.g, US.TX for Texas.
	     To select a whole continent, give =AF|AN|AS|EU|OC|NA|SA as <code>.
	     Use +r to modify the region from polygon(s): Append <inc>, <xinc>/<yinc>, or <winc>/<einc>/<sinc>/<ninc>
	     to round region to these multiples; use +R to extend region by those increments instead [0].
	   Or use -R<code><x0>/<y0>/<n_columns>/<n_rows> for origin and grid dimensions, where
	     <code> is a 2-char combo from [T|M|B][L|C|R] (top/middle/bottom/left/center/right)
	     and grid spacing must be specified via -I<dx>[/<dy>] (also see -r).
	-T Print global -Tzmin/zmax[/dz] (in rounded multiples of dz, if given).
	   Append +a[<alpha>] to trim grid range by excluding the two <alpha>/2 tails [2 %].
	     Note: +a is limited to a single grid.  Give <alpha> in percent.
	   Append +s to force a symmetrical range about zero.
	-V Change the verbosity level (currently v).
	   Choose among 6 levels; each level adds more messages:
	     q - Quiet, not even fatal error messages.
	     n - Normal verbosity: only error messages.
	     c - Also produce compatibility warnings [Default when no -V is used].
	     v - Verbose progress messages [Default when -V is used].
	     l - Long verbose progress messages.
	     d - Debugging messages.
	-f Special formatting of input/output columns (time or geographical).
	   Specify i(nput) or o(utput) [Default is both input and output].
	   Give one or more columns (or column ranges) separated by commas.
	   Append T (Calendar format), t (time relative to TIME_EPOCH),
	   f (floating point), x (longitude), y (latitude) to each item.
	   -f[i|o]g means -f[i|o]0x,1y (geographic coordinates).
	   -f[i|o]c means -f[i|o]0-1f (Cartesian coordinates).
	   -fp[<unit>] means input x,y are in projected coordinates.
	-h[i][<n>][+c][+d][+r<remark>][+t<title>] Input/output file has [0] Header record(s) [OFF]
	   Optionally, append i for input only and/or number of header records [0].
	     -hi turns off the writing of all headers on output.
	   Append +c to add header record with column information [none].
	   Append +d to delete headers before adding new ones [Default will append headers].
	   Append +r to add a <remark> comment to the output [none].
	   Append +t to add a <title> comment to the output [none].
	     (these strings may contain \n to indicate line-breaks)
	   For binary files, <n> is considered to mean number of bytes.
	-o Set alternate output column order [Default writes all columns in order].
	   Append list of columns; t[<word>] = trailing text; use <word> for writing a single word from the text.
	   Use -on for numerical output only.
	-^ (or -) Print short synopsis message.
	-+ (or +) Print longer synopsis message.
	-? (or no arguments) Print this usage message.
	--PAR=<value> Temporarily override GMT default setting(s) (repeatable).
	(See gmt.conf man page for GMT default parameters).

**Comment by duzihao-123** [comment]
> Also when your snaphu.csh fails, any log file I could look at?

when i run 'snaphu_interp.csh 0.10 40 100/60000/100/12000' it shows:
Setting search radius to be 300 ...
Reading in original grid...
Interpolating to nearest neighbour...
Working on line 5950 ...
  195415772 number of searches used ...
WRITING GRID IMAGE: Width x Heihgt = 7488 x 5950...
unwrapping phase with snaphu - higher threshold for faster unwrapping 

snaphu v1.4.2
32 parameters input from file snaphu.conf.brief (297 lines total)
Reading wrapped phase from file phase.in
No weight file specified.  Assuming uniform weights
Reading correlation data from file corr.in
Calculating deformation-mode cost parameters
Building range cost arrays
Building azimuth cost arrays
Killed
xyz2grd [ERROR]: Error for input file: No such file (unwrap.out)
grdmath [ERROR]: Syntax error: tmp.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdgradient [ERROR]: Error for input file: No such file (unwrap.grd)
grdgradient [ERROR]: Syntax error: Must specify input file
grdinfo [ERROR]: Error for input file: No such file (unwrap.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
makecpt [ERROR]: Syntax error -T: Must specify valid min[/max[/inc[<unit>|+n]]] option
grdinfo [ERROR]: Error for input file: No such file (unwrap.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdinfo [ERROR]: Error for input file: No such file (unwrap.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdimage [ERROR]: Error for input file: No such file (unwrap.grd)
grdimage [ERROR]: Syntax error -I: Requires a valid grid file or a constant
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
grdimage [ERROR]: Syntax error -I option: Must specify intensity file, value, or modifiers
psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Runwrap.grd
psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
Unwrapped phase map: unwrap.pdf
Why does this error occur?
Is my merged interferogram not big enough?

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, the log says "Killed". But I am not sure what killed your program. Do you have enough memory to unwrap a 7488 x 5950 grid? Also did get corr.grd in your folder. Also, please run `gmt grdinfo phasefilt.grd`.

**Comment by duzihao-123** [comment]
Hello，Eric，I'm sorry to reply you so late. I have 500G of disk space, and I only have 2G of running memory. When I run 'gmt grdinfo phasefilt.grd' it shows:
phasefilt.grd: Title: merged grid
phasefilt.grd: Command: 
phasefilt.grd: Remark: 
phasefilt.grd: Pixel node registration used [Cartesian grid]
phasefilt.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
phasefilt.grd: x_min: 0 x_max: 68456 x_inc: 8 name:  n_columns: 8557
phasefilt.grd: y_min: 0 y_max: 13068 y_inc: 2 name:  n_rows: 6534
phasefilt.grd: z_min: -3.14159250259 z_max: 3.14159250259 name: z
phasefilt.grd: scale_factor: 1 add_offset: 0
phasefilt.grd: format: netCDF-4 chunk_size: 130,129 shuffle: on deflation_level: 3
