### ISSUE TITLE
Errror  When I  run csh organize_files_tops_linux.csh -- "as it does not have enough scenes "

### ISSUE THREAD

**Issue by zhiqiang513** [gmtsar/gmtsar#133]
Hello . 
when i finished the first step of organize_files_tops_linux.csh with mode 1  ,i get all orbits files.
then i try to run it with mode 2 , but something wrong , the terminal display "SKIP 20180411, ,and no result in my files ..."  i find that the csh skip all my  safe files .

**Comment by Xiaohua-Eric-Xu** [comment]
When you run mode 1, it'll also tell you which dates will get organized. Your input filelist need to have file names in chronological order.

**Comment by zhiqiang513** [comment]
> When you run mode 1, it'll also tell you which dates will get organized. Your input filelist need to have file names in chronological order.

- You mean SAFE _filelist?  I check it .file names were listed chronologically  And run mode 2 shows that EOF is matched to its same time SAFE file .So I guess that maybe not the chronological issue.the process deal with each safe but every file is processed with result of SkIP ![image](https://user-images.githubusercontent.com/82689775/117603607-220ddd00-b186-11eb-960d-ffb2934e2405.jpeg)![image](https://user-images.githubusercontent.com/82689775/117603606-220ddd00-b186-11eb-860e-8beb2a11923d.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
It says "stack smashing detected". Please refer to this issue https://github.com/gmtsar/gmtsar/issues/12. Either turn on the no-stack-protector flag or update to the newest GMTSAR. The code should be fine but we are not sure why some Ubuntu systems complain about this.

**Comment by zhiqiang513** [comment]
> It says "stack smashing detected". Please refer to this issue https://github.com/gmtsar/gmtsar/issues/12. Either turn on the no-stack-protector flag or update to the newest GMTSAR. The code should be fine but we are not sure why some Ubuntu systems complain about this.

I check the config.mk and turn out that the code have been changed ,so I thinks the GMTSAT is the newest .if not,How can i know  whether the GMTSAR is newest. and  you said turn on the no-stack-protectors flag ,what do you mean? sorry  i m not good at the linux and GMTSAR.  Besides  I do the two changes you mentioned in issue#12 ,unfortunately .it still complain about this issue,but something new When I finished mode 2  again ,ONE new folder called FXXX_FXXX is created  just like what "sentinel time series guidelines " mentioned ,and  the content is about the last SAFE file .so i think it just  processes the last SAFE file.

**Comment by Xiaohua-Eric-Xu** [comment]
I think you need to `make clean` or `make spotless` first. When you compile the code, the flags will show up as it compiles each module.

**Comment by guohaojia2020** [comment]
> > I think you need to `make clean` or `make spotless` first. When you compile the code, the flags will show up as it compiles each module.
> 
> Thank you for helping 。It works.I reinstall the GMTSAR and edit the config.mk before make and make install 。

Hello, I meet the same issue,please tell me how you solve it?

**Comment by guohaojia2020** [comment]
OK！thanks for your reply,I Wil try it. My issue is after i run the csh in mode1and2，I can only get precious orbit without final data and direction named FxxxFxxx。Can you speak chinese？Can I talk about my issue in chinese? Because my English is poor.

**Comment by zhiqiang513** [comment]
可以加我QQ：1193594011

**Comment by sase1988** [comment]
Hello, I am experiencing this problem in Ubuntu 20.04, and have already tried all the workarounds suggested in the forum (adding the fno-stack protector to line 75 of config.mk worked for me in Ubuntu 18.04, but not here).

I notice I get an error "interpolation point outside of data constraints...." I enlose a screenshot

Thank you

![Captura de pantalla de 2021-06-29 13-00-48](https://user-images.githubusercontent.com/36776334/123830826-0eefd180-d8da-11eb-82d7-07a04c0f363b.png)

**Comment by guohaojia2020** [comment]
It is recommended that you check whether the clipping points are within the image range-------- 原始邮件 --------发件人： sase1988 ***@***.***>日期： 2021年6月30日周三 00:01收件人： gmtsar/gmtsar ***@***.***>抄送： guohaojia2020 ***@***.***>, Comment ***@***.***>主    题： Re: [gmtsar/gmtsar] Errror  When I  run csh organize_files_tops_linux.csh -- "as it does not have enough scenes " (#133)
Hello, I am experiencing this problem in Ubuntu 20.04, and have already tried all the workarounds suggested in the forum (adding the fno-stack protector to line 75 of config.mk worked for me in Ubuntu 18.04, but not here).
I notice I get an error "interpolation point outside of data constraints...." I enlose a screenshot
Thank you

**Comment by sase1988** [comment]
Hello, guohaojia2020 

Indeed they are, I saw the problem you were having, but you did not get same interpolation point error as I am getting, so I suspect the problem is another

Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
Hi I am not sure. The file popped out on terminal looks correct to me. Feels like error occurred at this line
`117         set tmpazi = `echo $pin1 | awk '{print $1,$2,0}' | SAT_llt2rat tmp2.PRM 1 | awk '{printf("%d",$2+0.5)}'``

**Comment by sase1988** [comment]
Let me try it and will let you know. Thank you

**Comment by sase1988** [comment]
Yes. Exactly the same issue. I forgot to export the LC_ALL variable permanently
Thank you

Santiago
