### ISSUE TITLE
[Help]: Error run intf_tops_parallel.csh intf.in batch_tops.config 6

### ISSUE THREAD

**Issue by zhiqiang513** [gmtsar/gmtsar#134]
Hello Mr Xu:
     sorry for bothering you again.
     So when I  run  code <intf_tops_parallel.csh intf.in batch_tops.config 6>, something wrong, the process keeps going ,but sometimes the terminal displays lots of Errors .(I copy the information below) I think it just pass the generation of this interferogram and go on next one.  after finishing this part I check the  intf_all . it generated the correct number of the interferogram ,but some folders has less files in it .I think the correct files number should be 52  .the wrong files number is 23, 29files are not generated, is this issue  related to the error mentioned before?  I check the logs .but seems that difference  is not obvious  .
[Terminal display.log](https://github.com/gmtsar/gmtsar/files/6452856/Terminal.display.log)
[intf_20170323_20170416.log](https://github.com/gmtsar/gmtsar/files/6452855/intf_20170323_20170416.log)
[intf_20170311_20170323.log](https://github.com/gmtsar/gmtsar/files/6452854/intf_20170311_20170323.log)
[intf_20170311_20170404.log](https://github.com/gmtsar/gmtsar/files/6452853/intf_20170311_20170404.log)

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, it says "Killed" again. On what kind of a machine are you running these? How many cores, how much RAM, enough disk space?

**Comment by zhiqiang513** [comment]
> Hmmm, it says "Killed" again. On what kind of a machine are you running these? How many cores, how much RAM, enough disk space?
Sorry for my late reply .I run this in virtual machine in my laptop（mobile workstation）,I give the Ubuntu RAM 4G  disk space 2T  so is it the hardware issue?But why just some interfero can not be generated？and from  what I saw,the process keep going when a specific interferogram is not generated.and the next interferogram can be generated.

**Comment by zhiqiang513** [comment]
So I check the performance RAM 4GB core 8  disk 200GB But I process data on external mobile drive it is 2T ![image](https://user-images.githubusercontent.com/82689775/117748291-4d560200-b242-11eb-9811-e123822b8c21.jpeg)![image](https://user-images.githubusercontent.com/82689775/117748312-55ae3d00-b242-11eb-9f17-c5a8ca3d7837.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
Try running it sequentially with intf_tops.csh or cut the threads to 3. I suspect you do not have enough RAM to process 6 interferograms at the same time.

**Comment by zhiqiang513** [comment]
> Try running it sequentially with intf_tops.csh or cut the threads to 3. I suspect you do not have enough RAM to process 6 interferograms at the same time.

sorry for late reply.It works after I change the threshold 3。

**Comment by Xiaohua-Eric-Xu** [comment]
The number is not a threshold. It is the number of threads you specify for use of GNU_parallel.

**Comment by zhiqiang513** [comment]
👌。thank you for your explanation.

**Comment by zhiqiang513** [comment]
> The number is not a threshold. It is the number of threads you specify for use of GNU_parallel
Hello Mr Xu
I got a question. I check my csh folder. create_merge_input.csh not exists。so I go to GitHub and find your script but how can I get this csh running in my computer ? I try to create a file with csh suffix and copy the script rename it same as create_merge_input.csh. But I find I can only run this code with prefix csh  only in /GMTSAR/gmtsar/csh. When I run it in data folder It show s no command .So I am confused  how can i make this code running in any folder? So sorry for bothering you about this question. I think it's the basic knowledge about Linux but I really can't figure out

**Comment by Xiaohua-Eric-Xu** [comment]
You probably need to put it to GMTSAR/bin and run `chmod +x your_script` to make it an executable.

**Comment by zhiqiang513** [comment]
Thank you for telling me. I have succeeded after seeing  your reply in another  help issue !
