### ISSUE TITLE
please help 

### ISSUE THREAD

**Issue by neda2133** [gmtsar/gmtsar#135]
Hello Dears
  How can I change the color of the mean los velocity  map in gmtsar ?
regards

**Comment by Xiaohua-Eric-Xu** [comment]
Simply plot it again with GMT choosing a different colortable. When you get the results from GMTSAR, they come in format of .grd, .kml, .png-s. The .grd files could be read and plotted with GMT. If you are familiar with Matlab or Python, you could use their netcdf libraries to read and plot them, e.g.`ncread`.
