### ISSUE TITLE
[Help]: create intf.tab file

### ISSUE THREAD

**Issue by duzihao-123** [gmtsar/gmtsar#136]
Hello, Eric, I am sorry to bother you again.
I don't know how to get the difference in perpendicular baseline(secondary-reference) When I was creating intf.tab file, and I typed 'prep_sbas.csh' after downloading the 'prep_sbas.csh' from github, it showed 'command not found' again, so what should I do after copying the downloaded 'prep_sbas.csh' to '/usr/local/GMTSAR/gmtsar/csh' or how can I get the difference in perpendicular baseline.

**Comment by Xiaohua-Eric-Xu** [comment]
You need to put `prep_sbas.csh` in to your /usr/local/GMTSAR/bin/. Also, the perpendicular info is stored in a file called baseline_table.dat. The script is only reading in that info and create intf.tab and scene.tab needed by `sbas`. If you could not find that file, then generate one with `get_baseline_table.csh`

**Comment by duzihao-123** [comment]
> You need to put `prep_sbas.csh` in to your /usr/local/GMTSAR/bin/. Also, the perpendicular info is stored in a file called baseline_table.dat. The script is only reading in that info and create intf.tab and scene.tab needed by `sbas`. If you could not find that file, then generate one with `get_baseline_table.csh`

Well, it worked after I moved it to the /usr/local/GMTSAR/bin/,thank you for your suggestion!

**Comment by duzihao-123** [comment]
> You need to put `prep_sbas.csh` in to your /usr/local/GMTSAR/bin/. Also, the perpendicular info is stored in a file called baseline_table.dat. The script is only reading in that info and create intf.tab and scene.tab needed by `sbas`. If you could not find that file, then generate one with `get_baseline_table.csh`

Well, I get the result 'dimension not much' when running sbas.
I checked the corr.grd file and the unwrap.grd file, the size is indeed different, because I do not have enough memory to run the entire merge image. So if I want to run sbas,  I have to make these two files exactly the same and I need to cut the research area to a small point when I run intf_tops.csh, right? Is there any other way to run sbas ？

**Comment by Xiaohua-Eric-Xu** [comment]
Sorry for the late response. Yes you could use `gmt grdcut` to do so.
