### ISSUE TITLE
[Help]: Sentinel 1 orbit files download link

### ISSUE THREAD

**Issue by gg-bb** [gmtsar/gmtsar#137]
Good morning every one,
Is the following link to download S1 orbits files still valid (it failed for me) ?
https://qc.sentinel1.eo.esa.int/aux_poeorb/

Is there any other way to download it?
Many thanks for your help
Have a nice day
GB

**Comment by zhiqiang513** [comment]
http://step.esa.int/auxdata/orbits/Sentinel-1/POEORB/S1A/2017/03/  try this one

**Comment by gg-bb** [comment]
Ok, it works, 
thank you for your help
GB

**Comment by Xiaohua-Eric-Xu** [comment]
Or here. https://s1qc.asf.alaska.edu/

**Comment by gg-bb** [comment]
Thank your Eric for your help
GB
