### ISSUE TITLE
[Help]: how to get some continues bursts from one s1 image?

### ISSUE THREAD

**Issue by insar-dev** [gmtsar/gmtsar#138]
Dear all，
           how to get some continues bursts from one s1 data? 
Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
Please be more specific with your question. Are you asking how to re-assemble the data?

**Comment by insar-dev** [comment]
i want to  use part of the image.  for example, use burst from 2 to 7.
![image](https://user-images.githubusercontent.com/1676595/118082023-0eb17a80-b3ef-11eb-8639-239c3467ffb3.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Here are two ways
1) pre-process the whole image, then use cut_slc or specify region_cut when running p2p_processing.csh
2) use assemble_tops/create_frame_tops.csh/organize_files_tops[_linux].csh to re-assemble the data.
