### ISSUE TITLE
[Help]: the parameter <intflist> in create_merge_input.csh

### ISSUE THREAD

**Issue by zhiqiang513** [gmtsar/gmtsar#139]
Dear all：
Could someone explain the parameter intflist for me ?  I see the usage of this csh ,and understand that the intflist should be the directory of inteferogram ,but i m still confused. so please look at the explanation below  from guideline 
<<This command is called ​ create_merge_input.csh ​ and needs a list of interferogram directories in the​ intf_all​ directory of ​ F1​ (intflist), a path to the F* directories, and a chosen mode number>>
I can see the parameter intflist should be a file ,but where is it?  it is generated by me?  and  it just include the F1s`interferograms? if i want merge three bursts and I  try to generate a file which include the folder name under intf_all  and make it as the first parameter but do not work. and  the usage example <create_merge_input.csh intflist .. 0>             the second parameter is the mode  or is the F*directories? what does F*directories mean?   the example is too general to get the deep understand.

**Comment by Xiaohua-Eric-Xu** [comment]
your intflist should contain something like below, basically every pair of interferograms you would like to merge, and yes, generated by users.
```
2015136_2015148
2015148_2015160
...
```
the second paramter is a path to your F1/F2/F3 directories. If you are running this in the merge folder, then put `..`.
the third parameter is, as described by the usage, 
```
mode 0 is merging all 3 subswaths, mode 1 is for F1/F2, mode 2 is for F2/F3
```

**Comment by zhiqiang513** [comment]
It works! I wanna know  is that format correct? ![image](https://user-images.githubusercontent.com/82689775/118102916-f00dac80-b40b-11eb-8d36-2e200eefe990.jpeg) I  correct the the first line.Make sure that is the line with master image as master image. (20171130 is my master image) after I run merge_batch.csh the result shows this ![image](https://user-images.githubusercontent.com/82689775/118103699-c4d78d00-b40c-11eb-96bf-06f1611f7b24.jpeg) what is the supermaster? I don't think I chose it before.  and why no such file or directory when search the every interferogram file in merge_list

**Comment by duzihao-123** [comment]
Hello, zhiqiang, you can change your path '/media/yangzhiqiang/externalfile/des/' to '../' just like what I did in #122

**Comment by zhiqiang513** [comment]
> Hello, zhiqiang, you can change your path '/media/yangzhiqiang/externalfile/des/' to '../' just like what I did in #122

Thank you !  I change the dir     make it running   and   find that you have mentioned the solution in #122 !

**Comment by zhiqiang513** [comment]
> > Hello, zhiqiang, you can change your path '/media/yangzhiqiang/externalfile/des/' to '../' just like what I did in #122
> 
> Thank you ! I change the dir make it running and find that you have mentioned the solution in #122 !

**Comment by zhiqiang513** [comment]
> Hello, zhiqiang, you can change your path '/media/yangzhiqiang/externalfile/des/' to '../' just like what I did in #122 
could you mind show me what you got after running  merge_intf.csh I think maybe my result is not right 
![image](https://user-images.githubusercontent.com/82689775/118153845-ea828780-b448-11eb-948c-322a27649145.png) 
This is one of merged inteferogram I think it is not whole thing  after i running the unwrap_parallel.csh intflist 3   terminal shows :



Working on line 2947 ...
xyz2grd [ERROR]: Cannot find file unwrap.out
grdmath [ERROR]: tmp.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdmath [INFORMATION]: Enable all available threads (up to 8)
grdmath [INFORMATION]: Perform reverse Polish notation calculations on grids
grdmath [ERROR]: unwrap.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdgradient [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
makecpt [ERROR]: Option T: Must specify valid min[/max[/inc[<unit>|+n]]] option
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdimage [ERROR]: Cannot find file unwrap.grd
grdimage [ERROR]: Option -I: Must specify intensity file, value, or modifiers
psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append +r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Runwrap.grd
psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
grdmath [INFORMATION]: Enable all available threads (up to 8)
grdmath [INFORMATION]: Perform reverse Polish notation calculations on grids
grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: corr_patch.grd grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: Reading grid from file corr_patch.grd
grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: Set boundary condition for all edges: natural
grdmath [INFORMATION]: Set boundary condition for left   edge: natural
grdmath [INFORMATION]: Set boundary condition for right  edge: natural
grdmath [INFORMATION]: Set boundary condition for bottom edge: natural
grdmath [INFORMATION]: Set boundary condition for top    edge: natural
mask_def_patch.grd grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: Reading grid from file mask_def_patch.grd
grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: Set boundary condition for all edges: natural
grdmath [INFORMATION]: Set boundary condition for left   edge: natural
grdmath [INFORMATION]: Set boundary condition for right  edge: natural
grdmath [INFORMATION]: Set boundary condition for bottom edge: natural
grdmath [INFORMATION]: Set boundary condition for top    edge: natural
MUL = corr_patch.grdgrdmath [INFORMATION]: Writing grid to file corr_patch.grd

Working on line 2947 ...
xyz2grd [ERROR]: Cannot find file unwrap.out
grdmath [ERROR]: tmp.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdmath [INFORMATION]: Enable all available threads (up to 8)
grdmath [INFORMATION]: Perform reverse Polish notation calculations on grids
grdmath [ERROR]: unwrap.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdgradient [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
makecpt [ERROR]: Option T: Must specify valid min[/max[/inc[<unit>|+n]]] option
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdimage [ERROR]: Cannot find file unwrap.grd
grdimage [ERROR]: Option -I: Must specify intensity file, value, or modifiers
psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append +r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Runwrap.grd
psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.

So  have you ever met this before?  what shoule I  do？

**Comment by Xiaohua-Eric-Xu** [comment]
Where's your log of snaphu? Did it got killed? I think I mentioned that phase unwrapping requires some RAM (e.g. for a 5000x5000 grid, give it 6-8GB RAM)
