### ISSUE TITLE
Intf.in Wrong file names listed

### ISSUE THREAD

**Issue by Mieszko-Fydrych** [gmtsar/gmtsar#14]
When running "select_pairs.csh baseline_table.dat 50 100" in my F1/F2/F3 directories, I can successfully generate an intf.in file, but rather than having the expected structure, I see the following structure:

s1b-iw1-slc-vv-20180926t172407-20180926t172413-012889-017cd5-004:s1a-iw1-slc-vv-20181107t172449-20181107t172455-024485-02af4c-004
s1a-iw1-slc-vv-20181002t172449-20181002t172455-023960-029dde-004:s1b-iw1-slc-vv-20181113t172408-20181113t172413-013589-019281-004
s1b-iw1-slc-vv-20180809t172405-20180809t172411-012189-01673f-004:s1b-iw1-slc-vv-20180926t172407-20180926t172413-012889-017cd5-004

Where did I go wrong?

Regards,
Mieszko

**Comment by Xiaohua-Eric-Xu** [comment]
Please refer to #1 
You can use the script to reproduce baseline_table.dat and then run select_pairs.csh
