### ISSUE TITLE
[Help]:  error when running merge_batch.csh and  unwrap_parallel.csh

### ISSUE THREAD

**Issue by zhiqiang513** [gmtsar/gmtsar#140]
Hello Mr Xu:
Could you mind  check this result (after running merge_batch.csh)for me
I think something missed  in merged interferograms folders
 ![image](https://user-images.githubusercontent.com/82689775/118156526-09cee400-b44c-11eb-9739-121a44f1b915.jpeg)
- - and when I ignore this  and running unwrap_parallel.csh with thread 3 The terminals shows 

Working on line 2947 ...
xyz2grd [ERROR]: Cannot find file unwrap.out
grdmath [ERROR]: tmp.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdmath [INFORMATION]: Enable all available threads (up to 8)
grdmath [INFORMATION]: Perform reverse Polish notation calculations on grids
grdmath [ERROR]: unwrap.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdgradient [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
makecpt [ERROR]: Option T: Must specify valid min[/max[/inc[<unit>|+n]]] option
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdimage [ERROR]: Cannot find file unwrap.grd
grdimage [ERROR]: Option -I: Must specify intensity file, value, or modifiers
psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append +r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Runwrap.grd
psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
grdmath [INFORMATION]: Enable all available threads (up to 8)
grdmath [INFORMATION]: Perform reverse Polish notation calculations on grids
grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: corr_patch.grd grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: Reading grid from file corr_patch.grd
grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: Set boundary condition for all edges: natural
grdmath [INFORMATION]: Set boundary condition for left   edge: natural
grdmath [INFORMATION]: Set boundary condition for right  edge: natural
grdmath [INFORMATION]: Set boundary condition for bottom edge: natural
grdmath [INFORMATION]: Set boundary condition for top    edge: natural
mask_def_patch.grd grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: Reading grid from file mask_def_patch.grd
grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: Set boundary condition for all edges: natural
grdmath [INFORMATION]: Set boundary condition for left   edge: natural
grdmath [INFORMATION]: Set boundary condition for right  edge: natural
grdmath [INFORMATION]: Set boundary condition for bottom edge: natural
grdmath [INFORMATION]: Set boundary condition for top    edge: natural
MUL = corr_patch.grdgrdmath [INFORMATION]: Writing grid to file corr_patch.grd

Working on line 2947 ...
xyz2grd [ERROR]: Cannot find file unwrap.out
grdmath [ERROR]: tmp.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdmath [INFORMATION]: Enable all available threads (up to 8)
grdmath [INFORMATION]: Perform reverse Polish notation calculations on grids
grdmath [ERROR]: unwrap.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdgradient [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
makecpt [ERROR]: Option T: Must specify valid min[/max[/inc[<unit>|+n]]] option
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdimage [ERROR]: Cannot find file unwrap.grd
grdimage [ERROR]: Option -I: Must specify intensity file, value, or modifiers
psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append +r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Runwrap.grd
psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
Is it not correct? What should I do?

**Comment by zhiqiang513** [comment]
[result.zip](https://github.com/gmtsar/gmtsar/files/6473866/result.zip)
and this is some logs . different  interferogram generates different log

**Comment by Xiaohua-Eric-Xu** [comment]
How many threads did you use? Do you have enough RAM to do that? (They all say killed)

**Comment by zhiqiang513** [comment]
> How many threads did you use? Do you have enough RAM to do that? (They all say killed)

I used 3 same as the threads I used to generated interferogram .So You mean This maybe the hardware issue ? I will try this process again with less threads.Thank you for your reply！

**Comment by Xiaohua-Eric-Xu** [comment]
Phase unwrapping costs much more memory than producing interferograms. For a 5000x5000 grid, it may take 6-8 GB, I think.

**Comment by zhiqiang513** [comment]
> Phase unwrapping costs much more memory than producing interferograms. For a 5000x5000 grid, it may take 6-8 GB, I think.

I change RAM to 16G  cores 16 threads3  and re run unwrap_parallel .Last time I run it ,terminal can give me feedback about process but this time I run it with no thing showed on panel. I check the folder finding the log is keep input thing .maybe it is running 
So another question !does unwrap cost much time ? I think my region is not too big . The whole day Process is working on unwrapping but still work on the 1-3 interferograms .is it normal? By the way The region I wanna research is  very poor coherent  because of the mountains and vegetation.
![image](https://user-images.githubusercontent.com/82689775/118242456-f1081200-b4cf-11eb-8579-13ba3afca8b3.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
Oh, that's a tough question. Phase unwrapping is really non-linear (at least for SNAPHU). If the coherence is really good, sometimes it'll finish within a few minutes. For some really bad ones, it could take up to a day or two. It also scales with the size of the grid.

**Comment by zhiqiang513** [comment]
> Oh, that's a tough question. Phase unwrapping is really non-linear (at least for SNAPHU). If the coherence is really good, sometimes it'll finish within a few minutes. For some really bad ones, it could take up to a day or two. It also scales with the size of the grid.
I check the corr file ,the region is really bad coherent .Last night I try to running unwrap individually and use snaphu with limited range which is a random area because of I don't know how to get the interesting area range .It finished within a few minutes, so I wanna know how can I get the specific area range numbers and make it as the parameters of snaphu .and if I running parallel unwrap where can i put this parameters just like snaphu .I running unwrap with a  mask to cover bad area so if it is possible that i change the threshold to enlarge the bad area and make unwrap running fast

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, snaphu.csh has an input parameter where you could put in range/azimuth boundaries for unwrapping. To get your AOI, you could try this.
1) find your area coordinates, i.e. long, lat, elevation.
2) use SAT_llt2rat to project them into radar coordinates.
3) use those coordinates to figure out the boundaries for snaphu.sch.
You could always run landmask.csh first (with the boundaries from phasefilt.grd) to create a landmask and get rid of wet area. Also tuning up the coherence threshold will help as well.

**Comment by zhiqiang513** [comment]
OK，I will try this

**Comment by Gigi-gugu** [comment]
> Hi, snaphu.csh has an input parameter where you could put in range/azimuth boundaries for unwrapping. To get your AOI, you could try this.
> 
>     1. find your area coordinates, i.e. long, lat, elevation.
> 
>     2. use SAT_llt2rat to project them into radar coordinates.
> 
>     3. use those coordinates to figure out the boundaries for snaphu.sch.
>        You could always run landmask.csh first (with the boundaries from phasefilt.grd) to create a landmask and get rid of wet area. Also tuning up the coherence threshold will help as well.

Hello, Professor Eric

Recently, I often watch gmtsar's issues. I want to ask a question: how to accurately use the longitude and latitude of AOI to convert to range/azimuth in Google maps, rather than determine the range/azimuth of AOI through eye view unwrap.pdf. I don't think it can be accurately cut according to the longitude and latitude of AOI. Can you tell me how to use sat_llt2rat?

By the way, unwrap.pdf is generated after merging IW.

Thank you in advance.

**Comment by Xiaohua-Eric-Xu** [comment]
1) drop a pin (or a few pins) on Google Maps and get the lon lat,
2) run `gmt grdtrack -Gdem.grd` over your lon lat to get the height above ellipsoid.
3) run SAT_llt2rat to get range and azimuth of the pin or pins.

**Comment by Xiaohua-Eric-Xu** [comment]
For 3. you need to use the PRM file in the merge directory or the one after merging.

**Comment by Gigi-gugu** [comment]
> For 3. you need to use the PRM file in the merge directory or the one after merging.

Thank you. I'll try it
