### ISSUE TITLE
[Help]: running sbas 

### ISSUE THREAD

**Issue by duzihao-123** [gmtsar/gmtsar#143]
Hello,Eric, I met some trouble again.
I get the result 'dimension not match' when running sbas.
I checked the corr.grd file and the unwrap.grd file, the size is indeed different, because I do not have enough memory to run the entire merge image. So if I want to run sbas, I have to make these two files exactly the same and I need to cut the research area to a small point when I run intf_tops.csh, right? Is there any other way to run sbas ？By the way, how can I cut the corr.grd file to match the unwrap.grd file. In addition, When I run intf_tops.csh in the F1 folder, I set the region cut option in the config file to 10000/21624/2000/10000, but got the result of 'wrong range' , I checked the topo_ra file, the size is x: 0-21624, y: 0-12192, so where is the problem?

**Comment by Xiaohua-Eric-Xu** [comment]
You probably need to either downsample your images or cut to a small area if you don't have enough RAM. to cut, run `gmt grdcut corr.grd -Runwrap_cut.grd -Gcorr_cut.grd`, then they'll match exactly. Or you could us `grdsample` as well.

**Comment by duzihao-123** [comment]
> You probably need to either downsample your images or cut to a small area if you don't have enough RAM. to cut, run `gmt grdcut corr.grd -Runwrap_cut.grd -Gcorr_cut.grd`, then they'll match exactly. Or you could us `grdsample` as well.

I successfully cut corr.grd file according to your command, and then ran sbas, it worked.
Thank you very much for your reply

**Comment by zhiqiang513** [comment]
Hi zihao，can i take a look at your sbas result and do you mind telling me about your sanphu threshold? Is it 0.1 ?

**Comment by duzihao-123** [comment]
> Hi zihao，can i take a look at your sbas result and do you mind telling me about your sanphu threshold? Is it 0.1 ?

My snaphu threshold is 0.1
