### ISSUE TITLE
[Bug]: why master data is larger than theoretical value?

### ISSUE THREAD

**Issue by insar-dev** [gmtsar/gmtsar#144]
**Describe the bug**

after running preproc_batch_tops_esd.csh, i found that master data is larger than theoretical value; 
for example, in  master prm, nrows = 5480, bytes_per_line = 87808, so theoretical value should be 5480*87808 = 481,187,840.
but the actual value is 481,363,456. 
so is there an error there?

![image](https://user-images.githubusercontent.com/1676595/118249615-2e709d80-b4d8-11eb-8ec6-e045f91cfb46.png)

![image](https://user-images.githubusercontent.com/1676595/118249797-59f38800-b4d8-11eb-9786-d255c1d30b7e.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, Not really. The resampled data (aligned image) has line number kept as multiples of 4 (if I remember right, for topography or something), while the master image kept intact. This does not affect later processing. @dsandwell may have a better answer.

**Comment by insar-dev** [comment]
thanks for you reply.
