### ISSUE TITLE
[Help]: organize_files_tops_linux.csh skip all my files

### ISSUE THREAD

**Issue by guohaojia2020** [gmtsar/gmtsar#145]
Hello, I'm calling "organize_ files_ tops_ linux.csh SAFE_ Filelist.. / reframed / pins. Ll 1 "during the operation, all my files appear:

S1A_ OPER_ AUX_ POEORB 100%[===================>] 4.21M 1.03MB/s in 4.1s

2021-05-18 21:12:47 (1.03 MB/s) - ‘S1A_ OPER_ AUX_ POEORB_ OPOD_ 20190321T120739_ V20190228T225942_ 20190302T005942.EOF’ saved [4409837/4409837]

Reading in 5750 lines of info from XML...

Writing 17 lines for orbit...

Writing 53 lines of precise orbit for the LED file...

Usage: shift_ aline_ PRM.csh file.PRM num_ lines

Example: shift_ aline_ PRM.csh IMG-HH-ALPSRP049040660-H1.0__ A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.

awk: line 1: syntax error at or near )

Reading in 5750 lines of info from XML...

Writing 17 lines for orbit...

Writing 53 lines of precise orbit for the LED file...

Usage: shift_ aline_ PRM.csh file.PRM num_ lines

Example: shift_ aline_ PRM.csh IMG-HH-ALPSRP049040660-H1.0__ A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.

awk: line 1: syntax error at or near )

SKIP 20190301, as it does not have enough scenes ...

Then I refer to the solution given by you in the previous problem#12, modify config.mk and reload gmtsar, but it's still like this, so I downloaded the virtual machine provided by you, but the situation is still unchanged. What should I do

**Comment by Xiaohua-Eric-Xu** [comment]
What's in your pins.ll? This could only happen when SAT_llt2rat could not calculate valid numbers based on the input of your geo-coordinates.

**Comment by guohaojia2020** [comment]
![Pin1](https://user-images.githubusercontent.com/78332517/118901577-37cd9000-b946-11eb-9154-d31cf870b160.jpg)
![Pin2](https://user-images.githubusercontent.com/78332517/118901579-38febd00-b946-11eb-9fc5-03e4df4342cc.jpg)
![pinsll](https://user-images.githubusercontent.com/78332517/118901580-39975380-b946-11eb-9a4e-021febbf2dc4.jpg)
Thanks for your reply.This is the distribution of the coordinates I input and the content of the pin.ll file. My image is ascending orbit

**Comment by guohaojia2020** [comment]
![bug](https://user-images.githubusercontent.com/78332517/118906439-651f3b80-b950-11eb-9fda-420dd513c28f.jpg)
well,it works after I change  the encoding of pin.ll .But my last image was wrong,others are good

**Comment by cxinlong** [comment]
> ![bug](https://user-images.githubusercontent.com/78332517/118906439-651f3b80-b950-11eb-9fda-420dd513c28f.jpg) well,it works after I change the encoding of pin.ll .But my last image was wrong,others are good

Hello, I have the same problem as you. How did you solve it? How do I modify the encoding of pins.ll? @guohaojia2020

**Comment by guohaojia2020** [comment]
> > ![bug](https://user-images.githubusercontent.com/78332517/118906439-651f3b80-b950-11eb-9fda-420dd513c28f.jpg) well,it works after I change the encoding of pin.ll .But my last image was wrong,others are good
> 
> Hello, I have the same problem as you. How did you solve it? How do I modify the encoding of pins.ll? @guohaojia2020

I adjusted the format of the data in the file pin.ll, such as spaces。

**Comment by cxinlong** [comment]
Thank you for your answer! Sorry, I didn't catch your meaning. Can you be more specific? What Spaces to adjust? @guohaojia2020

**Comment by guohaojia2020** [comment]
> Thank you for your answer! Sorry, I didn't catch your meaning. Can you be more specific? What Spaces to adjust? @guohaojia2020

![pin ll](https://user-images.githubusercontent.com/78332517/221496793-0999bb44-9062-4d83-9cf4-f11e5ae2c7eb.png)
Like this, especially the encoding format in the red box.

**Comment by cxinlong** [comment]
Thank you very much. Is the encoding format to be changed to LLVM IR?

**Comment by guohaojia2020** [comment]
yes

**Comment by cxinlong** [comment]
My format is LLVM IR, but still skip all my images. I'll try again to solve the problem, thank you!

**Comment by guohaojia2020** [comment]
you can change the order of first line and second-------- 原始邮件 --------发件人： cxinlong ***@***.***>日期： 2023年2月27日周一 15:26收件人： gmtsar/gmtsar ***@***.***>抄送： guohaojia2020 ***@***.***>, Comment ***@***.***>主    题： Re: [gmtsar/gmtsar] [Help]: organize_files_tops_linux.csh skip all my files (#145)
My format is LLVM IR, but still skip all my images. I'll try again to solve the problem, thank you!

**Comment by cxinlong** [comment]
Thank you for our advice.When I switched the first and second lines.The first step of organize_file_tops_linux.csh works,but the second step reports an error as following.
![2023-02-27 16-37-42 的屏幕截图](https://user-images.githubusercontent.com/118950056/221515089-8dcf673b-cc2e-4bf9-af9f-d02b3ecd617b.png)
