### ISSUE TITLE
mean velocity map

### ISSUE THREAD

**Issue by neda2133** [gmtsar/gmtsar#146]
Hello Dears.
I'm trying to get mean velocity map  but there is a problem. My results are as follows:

![image](https://user-images.githubusercontent.com/73532419/118764629-0e9df880-b88f-11eb-8e7a-718ae7b32680.png)

![image](https://user-images.githubusercontent.com/73532419/118764661-1e1d4180-b88f-11eb-8d05-075965ed4a55.png)

![image](https://user-images.githubusercontent.com/73532419/118766286-79503380-b891-11eb-94de-20a4089f873b.png)

I think this is due to the unwrapping  phase step, but I do not know exactly.
I do not see any color change around the fault.
Please tell me what is the solution?
What should be the value of  threshold_snaphu in batch_top.confhg?and how much can it be changed?
 Please help me
regards

**Comment by Xiaohua-Eric-Xu** [comment]
How many interferograms did you use (is atmospheric noise properly dealt with)? Did you pin down a position? Any GNSS used? How fast generally is the fault moving? Locking depth? Any creep? You need to describe your processing in details (we can't find problem just by looking at a few images/results).
