### ISSUE TITLE
how can merge band 1 and band 2 ?

### ISSUE THREAD

**Issue by neda2133** [gmtsar/gmtsar#147]
Excuse me,
 I have another question

How can I merge subswaths 1 and 2 together?
Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
What do you mean by band1 and band2? Which satellite? You meant raw data or SLC, or processed interferograms?

**Comment by neda2133** [comment]
> What do you mean by band1 and band2? Which satellite? You meant raw data or SLC, or processed interferograms?

Hi Eric
I mean merging the sentinel bands to get the Mean  velcity map using the SBAS method

**Comment by neda2133** [comment]
> What do you mean by band1 and band2? Which satellite? You meant raw data or SLC, or processed interferograms?

Hi Eric
sorry I mean merging the sentinel1 subswaths to get the Mean velcity map using the SBAS method,

**Comment by Xiaohua-Eric-Xu** [comment]
What's in your merge_list?

**Comment by neda2133** [comment]
> What's in your merg

**Comment by Xiaohua-Eric-Xu** [comment]
Were you able to fix the problem?

**Comment by neda2133** [comment]
> What's in your merge_list?
hi
 merge_list is : 

../F1/intf_all/2018075_2018099/:S1_20180317_ALL_F1.PRM:S1_20180410_ALL_F1.PRM,../F2/intf_all/2018075_2018099/:S1_20180317_ALL_F2.PRM:S1_20180410_ALL_F2.PRM
../F1/intf_all/2018075_2018123/:S1_20180317_ALL_F1.PRM:S1_20180504_ALL_F1.PRM,../F2/intf_all/2018075_2018123/:S1_20180317_ALL_F2.PRM:S1_20180504_ALL_F2.PRM
../F1/intf_all/2018075_2018159/:S1_20180317_ALL_F1.PRM:S1_20180609_ALL_F1.PRM,../F2/intf_all/2018075_2018159/:S1_20180317_ALL_F2.PRM:S1_20180609_ALL_F2.PRM
../F1/intf_all/2018075_2018183/:S1_20180317_ALL_F1.PRM:S1_20180703_ALL_F1.PRM,../F2/intf_all/2018075_2018183/:S1_20180317_ALL_F2.PRM:S1_20180703_ALL_F2.PRM
../F1/intf_all/2018075_2018219/:S1_20180317_ALL_F1.PRM:S1_20180808_ALL_F1.PRM,../F2/intf_all/2018075_2018219/:S1_20180317_ALL_F2.PRM:S1_20180808_ALL_F2.PRM
../F1/intf_all/2018099_2018123/:S1_20180410_ALL_F1.PRM:S1_20180504_ALL_F1.PRM,../F2/intf_all/2018099_2018123/:S1_20180410_ALL_F2.PRM:S1_20180504_ALL_F2.PRM
../F1/intf_all/2018099_2018159/:S1_20180410_ALL_F1.PRM:S1_20180609_ALL_F1.PRM,../F2/intf_all/2018099_2018159/:S1_20180410_ALL_F2.PRM:S1_20180609_ALL_F2.PRM
../F1/intf_all/2018099_2018183/:S1_20180410_ALL_F1.PRM:S1_20180703_ALL_F1.PRM,../F2/intf_all/2018099_2018183/:S1_20180410_ALL_F2.PRM:S1_20180703_ALL_F2.PRM
../F1/intf_all/2018099_2018243/:S1_20180410_ALL_F1.PRM:S1_20180901_ALL_F1.PRM,../F2/intf_all/2018099_2018243/:S1_20180410_ALL_F2.PRM:S1_20180901_ALL_F2.PRM
../F1/intf_all/2018123_2018159/:S1_20180504_ALL_F1.PRM:S1_20180609_ALL_F1.PRM,../F2/intf_all/2018123_2018159/:S1_20180504_ALL_F2.PRM:S1_20180609_ALL_F2.PRM
../F1/intf_all/2018123_2018183/:S1_20180504_ALL_F1.PRM:S1_20180703_ALL_F1.PRM,../F2/intf_all/2018123_2018183/:S1_20180504_ALL_F2.PRM:S1_20180703_ALL_F2.PRM
../F1/intf_all/2018123_2018219/:S1_20180504_ALL_F1.PRM:S1_20180808_ALL_F1.PRM,../F2/intf_all/2018123_2018219/:S1_20180504_ALL_F2.PRM:S1_20180808_ALL_F2.PRM
../F1/intf_all/2018123_2018243/:S1_20180504_ALL_F1.PRM:S1_20180901_ALL_F1.PRM,../F2/intf_all/
2018123_2018243/:S1_20180504_ALL_F2.PRM:S1_20180901_ALL_F2.PRM
../F1/intf_all/2018159_2018183/:S1_20180609_ALL_F1.PRM:S1_20180703_ALL_F1.PRM,../F2/intf_all/2018159_2018183/:S1_20180609_ALL_F2.PRM:S1_20180703_ALL_F2.PRM
../F1/intf_all/2018159_2018219/:S1_20180609_ALL_F1.PRM:S1_20180808_ALL_F1.PRM,../F2/intf_all/2018159_2018219/:S1_20180609_ALL_F2.PRM:S1_20180808_ALL_F2.PRM
../F1/intf_all/2018159_2018243/:S1_20180609_ALL_F1.PRM:S1_20180901_ALL_F1.PRM,../F2/intf_all/2018159_2018243/:S1_20180609_ALL_F2.PRM:S1_20180901_ALL_F2.PRM
../F1/intf_all/2018159_2018279/:S1_20180609_ALL_F1.PRM:S1_20181007_ALL_F1.PRM,../F2/intf_all/2018159_2018279/:S1_20180609_ALL_F2.PRM:S1_20181007_ALL_F2.PRM
../F1/intf_all/2018183_2018219/:S1_20180703_ALL_F1.PRM:S1_20180808_ALL_F1.PRM,../F2/intf_all/2018183_2018219/:S1_20180703_ALL_F2.PRM:S1_20180808_ALL_F2.PRM
../F1/intf_all/2018183_2018243/:S1_20180703_ALL_F1.PRM:S1_20180901_ALL_F1.PRM,../F2/intf_all/2018183_2018243/:S1_20180703_ALL_F2.PRM:S1_20180901_ALL_F2.PRM
../F1/intf_all/2018183_2018279/:S1_20180703_ALL_F1.PRM:S1_20181007_ALL_F1.PRM,../F2/intf_all/2018183_2018279/:S1_20180703_ALL_F2.PRM:S1_20181007_ALL_F2.PRM
../F1/intf_all/2018183_2018315/:S1_20180703_ALL_F1.PRM:S1_20181112_ALL_F1.PRM,../F2/intf_all/2018183_2018315/:S1_20180703_ALL_F2.PRM:S1_20181112_ALL_F2.PRM
../F1/intf_all/2018219_2018243/:S1_20180808_ALL_F1.PRM:S1_20180901_ALL_F1.PRM,../F2/intf_all/2018219_2018243/:S1_20180808_ALL_F2.PRM:S1_20180901_ALL_F2.PRM
../F1/intf_all/2018219_2018279/:S1_20180808_ALL_F1.PRM:S1_20181007_ALL_F1.PRM,../F2/intf_all/2018219_2018279/:S1_20180808_ALL_F2.PRM:S1_20181007_ALL_F2.PRM
../F1/intf_all/2018219_2018315/:S1_20180808_ALL_F1.PRM:S1_20181112_ALL_F1.PRM,../F2/intf_all/
2018219_2018315/S1_20180808_ALL_F2.PRM:S1_20181112_ALL_F2.PRM
../F1/intf_all/2018219_2018339/:S1_20180808_ALL_F1.PRM:S1_20181206_ALL_F1.PRM,../F2/intf_all/2018219_2018339/:S1_20180808_ALL_F2.PRM:S1_20181206_ALL_F2.PRM
../F1/intf_all/2018243_2018279/:S1_20180901_ALL_F1.PRM:S1_20181007_ALL_F1.PRM,../F2/intf_all/2018243_2018279/:S1_20180901_ALL_F2.PRM:S1_20181007_ALL_F2.PRM
../F1/intf_all/2018243_2018315/:S1_20180901_ALL_F1.PRM:S1_20181112_ALL_F1.PRM,../F2/intf_all/2018243_2018315/:S1_20180901_ALL_F2.PRM:S1_20181112_ALL_F2.PRM
../F1/intf_all/2018243_2018339/:S1_20180901_ALL_F1.PRM:S1_20181206_ALL_F1.PRM,../F2/intf_all/2018243_2018339/:S1_20180901_ALL_F2.PRM:S1_20181206_ALL_F2.PRM
../F1/intf_all/2018279_2018315/:S1_20181007_ALL_F1.PRM:S1_20181112_ALL_F1.PRM,../F2/intf_all/2018279_2018315/:S1_20181007_ALL_F2.PRM:S1_20181112_ALL_F2.PRM
../F1/intf_all/2018279_2018339/:S1_20181007_ALL_F1.PRM:S1_20181206_ALL_F1.PRM,../F2/intf_all/
2018279_2018339/S1_20181007_ALL_F2.PRM:S1_20181206_ALL_F2.PRM
../F1/intf_all/2018315_2018339/:S1_20181112_ALL_F1.PRM:S1_20181206_ALL_F1.PRM,../F2/intf_all/2018315_2018339/:S1_20181112_ALL_F2.PRM:S1_20181206_ALL_F2.PRM

**Comment by Xiaohua-Eric-Xu** [comment]
Something wrong happened to this line below
```
../F1/intf_all/2018123_2018243/:S1_20180504_ALL_F1.PRM:S1_20180901_ALL_F1.PRM,../F2/intf_all/
2018123_2018243/:S1_20180504_ALL_F2.PRM:S1_20180901_ALL_F2.PRM
```
This should be in one line.

**Comment by neda2133** [comment]
> Were you able to fix the problem?

Not yet . Thank you for your help

**Comment by neda2133** [comment]
> Something wrong happened to this line below
> 
> ```
> ../F1/intf_all/2018123_2018243/:S1_20180504_ALL_F1.PRM:S1_20180901_ALL_F1.PRM,../F2/intf_all/
> 2018123_2018243/:S1_20180504_ALL_F2.PRM:S1_20180901_ALL_F2.PRM
> ```
> 
> This should be in one line.

sorry , What is wrong with it?

**Comment by Xiaohua-Eric-Xu** [comment]
Well, you need to put these in one line. If you break in the middle, the script will consider them as two records.
p.s. your error says it's trying to find a file named `../../F2/intf_all/`, but it is a directory.

**Comment by neda2133** [comment]
> Well, you need to put these in one line. If you break in the middle, the script will consider them as two records.
> p.s. your error says it's trying to find a file named

Excuse me, how do I put them on a line?
Could this error be due to low system memory?

**Comment by neda2133** [comment]
> Well, you need to put these in one line. If you break in the middle, the script will consider them as two records.
> p.s. your error says it's trying to find a file named `../../F2/intf_all/`, but it is a directory.

![image](https://user-images.githubusercontent.com/73532419/119443168-5c5aab00-bd3e-11eb-900a-f2348e34412c.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Could you send your merge_list file?

**Comment by neda2133** [comment]
> Could you send your merge_list file?

Hi Eric
The problem was solved
thanks 
regards
