### ISSUE TITLE
[Help]: The Displacements of master_image NAN  

### ISSUE THREAD

**Issue by Mohamed-Elashquer** [gmtsar/gmtsar#148]
Dear,All

When i make the Displacements from InSAR LOS in Time Seriers,  the Value of Displacement of master_image is NAN 
i think the true value will be Zero.

regards

**Comment by Xiaohua-Eric-Xu** [comment]
Is this a bug report? :)

**Comment by Mohamed-Elashquer** [comment]
excuse me, Xiaohua

 how i can how can solve this problem?

**Comment by Xiaohua-Eric-Xu** [comment]
Well, you need to provide more details. Basically, how to reproduce what you got. Any screenshots? processing logs?

**Comment by Mohamed-Elashquer** [comment]
this is LOS_InSAR.disp

![Screenshot from 2021-05-25 11-14-03](https://user-images.githubusercontent.com/71747034/119429847-a8abe800-bd4a-11eb-8ea4-fb91a20d8782.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, How did you get this table? Is this NaN from disp_????.grd. Is this a printing/extraction problem or is the value stored inside the disp_????.grd NaN.

**Comment by Mohamed-Elashquer** [comment]
this the disp_2017314.grd
![Screenshot from 2021-05-25 11-24-30](https://user-images.githubusercontent.com/71747034/119430578-fe34c480-bd4b-11eb-845a-e8ec8c63e1a2.png)

**Comment by Mohamed-Elashquer** [comment]
and this after converted
![Screenshot from 2021-05-25 11-22-58](https://user-images.githubusercontent.com/71747034/119430631-14428500-bd4c-11eb-857c-e2d294878cef.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I mean, how did you extract the value? grdtrack? The grid looks really small, suspecting they are all zeros? If you run grdinfo on both disp_2017314.grd and disp_2017314_ll.grd what does the terminal outputs? 

p.s. what's the sbas command you ran? what do you intf.tab and scene.tab look like?

**Comment by Xiaohua-Eric-Xu** [comment]
So this grid is a 0 grid, which I suppose should be the start of your time-series. However, I noticed that you have acquisitions from dates that are earlier than this. So what's in your scene.tab? Are the listed dates in the correct order?
Also, following the previous questions, which step produced NaN? sbas? proj_ra2ll.csh? or when you extract the data?

**Comment by Mohamed-Elashquer** [comment]
this is the scene.tab 
![Uploading Screenshot from 2021-05-25 12-59-50.png…]()

**Comment by Mohamed-Elashquer** [comment]
![Screenshot from 2021-05-25 12-59-50](https://user-images.githubusercontent.com/71747034/119437486-2aa30d80-bd59-11eb-8d68-c8f984e4e3ec.png)

**Comment by Mohamed-Elashquer** [comment]
this is the scene.tab

**Comment by Mohamed-Elashquer** [comment]
this is the scene.tab
![Screenshot from 2021-05-25 12-59-50](https://user-images.githubusercontent.com/71747034/119437554-56be8e80-bd59-11eb-8dbb-f75003107ad6.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Do you mind putting things in the time order and try your sbas again? The code read in the dates and thinks the first one is the start.

**Comment by Mohamed-Elashquer** [comment]
i think the first image in the scene.tab is the master image

**Comment by Xiaohua-Eric-Xu** [comment]
That is the case for coregistration/merging steps. For sbas, I think one needs to create a scene.tab that has the records in the right chronologic order.

**Comment by Mohamed-Elashquer** [comment]
this is the chart of the Displacements from InSAR LOS in Time Series after replace the value of masterimage from NAN to Zero
![Uploading Screenshot from 2021-05-25 13-09-55.png…]()

**Comment by Mohamed-Elashquer** [comment]
i used the command 
prep_sbas.csh intf.in baseline_table.dat ../merge unwrap.grd corr.grd
to Prepare the  scene.tab ​ file and the ​ intf.tab​ file automatically

**Comment by Mohamed-Elashquer** [comment]
this is the chart of the Displacements from InSAR LOS in Time Series after replace the value of masterimage from NAN to Zero
![Screenshot from 2021-05-25 13-09-55](https://user-images.githubusercontent.com/71747034/119438379-047e6d00-bd5b-11eb-8780-6b4a252ff2de.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Yeah, I know. The time-series documents did not state it and we'll try to fix that. 

If you keep the current scene.tab, it may not fail the least square solver, but the Green's matrix won't be correctly reflecting the connections among interferograms.

**Comment by Mohamed-Elashquer** [comment]
so what can i do to solve it?

**Comment by Xiaohua-Eric-Xu** [comment]
> Do you mind putting things in the time order and try your sbas again?

As above. Please change your scene.tab so it's in the time order, then re-run your sbas command.

**Comment by Mohamed-Elashquer** [comment]
ok i will do that,
 thank you

**Comment by Xiaohua-Eric-Xu** [comment]
Let me know if that does not fix the problem.

**Comment by Mohamed-Elashquer** [comment]
ok, this the scene.tab after change the master image according the time order
i will do SBAS step again
but it will take more than one day
when it will finish i will send you
thank you
![Screenshot from 2021-05-25 13-42-11](https://user-images.githubusercontent.com/71747034/119440574-84a6d180-bd5f-11eb-9b61-7dc51ec1d991.png)

**Comment by Mohamed-Elashquer** [comment]
Dear Xiaohua
this is SBAS
![Screenshot from 2021-05-26 09-07-40](https://user-images.githubusercontent.com/71747034/119585763-53351100-be06-11eb-8da2-c035736a88eb.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Looks OK to me, but why all of them does not have enough connections (interferometric pairs) to make an atmospheric correction? 
Do you have a new time-series plot? Do you still get NaN for 2017314?

**Comment by Mohamed-Elashquer** [comment]
that is the Displacements from InSAR LOS in Time Seriers after change scene.tab, which  the master image according the time order
the Value of Displacement of first scene is NAN and the master image is 50.1706657731

**Comment by Mohamed-Elashquer** [comment]
that is the Displacements from InSAR LOS in Time Seriers after change scene.tab, which  the master image according the time order
the Value of Displacement of first scene is NAN and the master image is 50.1706657731

**Comment by Mohamed-Elashquer** [comment]
that is the Displacements from InSAR LOS in Time Seriers after change scene.tab, which  the master image according the time order
the Value of Displacement of first scene is NAN and the master image is 50.1706657731
![Screenshot from 2021-05-26 09-41-10](https://user-images.githubusercontent.com/71747034/119586275-5381dc00-be07-11eb-9461-ec368802ab58.png)

**Comment by Xiaohua-Eric-Xu** [comment]
The time-series looks OK. Strangely, now your first date becomes NaN. If you plot your disp_2015127.grd with grdimage or matlab/python, do you inspect any nans? I usually use `ncview` to do this. It might be available through `apt-get`, and is definitely available through `homebrew`

**Comment by Mohamed-Elashquer** [comment]
OK, the all values equal zeros
![Screenshot from 2021-05-26 09-52-45](https://user-images.githubusercontent.com/71747034/119586775-4ca79900-be08-11eb-94f4-014c3da1d214.png)
![Screenshot from 2021-05-26 09-52-53](https://user-images.githubusercontent.com/71747034/119586783-4f09f300-be08-11eb-8855-52cb12295135.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, so maybe your data extraction script somehow converted it to NaN? p.s. is your new time-series different from before?

**Comment by Mohamed-Elashquer** [comment]
yes, completely different 
![Screenshot from 2021-05-26 10-00-56](https://user-images.githubusercontent.com/71747034/119587357-85943d80-be09-11eb-9a4b-21b8a7507394.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Yes. the reference date is changed, but may not be just an offset in the time-series. Basically the former scene.tab shifted the reference dates before 2017314 by one acquisition interval.

**Comment by Mohamed-Elashquer** [comment]
I used command proj_ra2ll.csh trans.dat vel.grd vel_ll.grd to 
to transform radar coordinates into lat/long coordinates for velocity grid file, 
After that i used command" gmt grdtrack GNSS.llh -G../SBAS/vel_ll.grd > LOS_InSAR.vel"
to get velocity at the specific  point from vel_ll.grd the value of velocity not equal to  "gmt grdtrack GNSS.rahll -G../SBAS/vel.grd > LOS_InSAR.vel" at the same point but in radar coordinates before  proj_ra2ll.csh

**Comment by Mohamed-Elashquer** [comment]
I think the problem in gauss_200 is not coincide with vel.grd to transform process 
![Uploading 190605336_175534224507220_7947012286507757220_n.png…]()

**Comment by Mohamed-Elashquer** [comment]
I think the problem in gauss_200 is not coincide with vel.grd to transform process
![190605336_175534224507220_7947012286507757220_n](https://user-images.githubusercontent.com/71747034/119598139-58ea2100-be1d-11eb-8726-6f18ec887fba.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Here's how you could roughly compute what gauss_xxx to use for proj_ra2ll.csh. Divide xxx by 4 should be roughly the sampling after geocoding. e.g. for 200 m wavelength the sampling afterwards will be around 50 m.

**Comment by Mohamed-Elashquer** [comment]
I think the problem in gauss_200 is not coincide with vel.grd for  command proj_ra2ll.csh trans.dat vel.grd vel_ll.grd tto transform radar coordinates into lat/long coordinates for velocity grid file
![190605336_175534224507220_7947012286507757220_n](https://user-images.githubusercontent.com/71747034/119598319-b1212300-be1d-11eb-8d09-7c170d496b8e.png)

**Comment by Mohamed-Elashquer** [comment]
> Here's how you could roughly compute what gauss_xxx to use for proj_ra2ll.csh. Divide xxx by 4 should be roughly the sampling after geocoding. e.g. for 200 m wavelength the sampling afterwards will be around 50 m.

excuse me , can you explain more

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what's your question. Though you are asking whether it's the geocoding sampling interval produced the problem.

**Comment by Mohamed-Elashquer** [comment]
I think the problem in gauss_200 is not coincide with vel.grd for command proj_ra2ll.csh trans.dat vel.grd vel_ll.grd tto transform radar coordinates into lat/long coordinates for velocity grid file

how to get gauss_xxx coincide with vel.grd ?

**Comment by Xiaohua-Eric-Xu** [comment]
The only useful info taken by proj_ra2ll.csh is the xxx number in the file name. So you could create a file named gauss_xxx and put it to the folder where you want to run proj_ra2ll.csh. It's probably not the best design.
e.g. to geocode at 400 m wavelength (i.e. ~100m sampling), you could create a file named gauss_400. But make sure that's the only gauss_xxx file there.
