### ISSUE TITLE
[Help]: SBAS problem

### ISSUE THREAD

**Issue by EnCheng-Li** [gmtsar/gmtsar#149]
Dear all,
1. I tried to run SBAS. Here is my code.
![image](https://user-images.githubusercontent.com/74343146/119658917-3fb69400-be60-11eb-80fc-f0c425582b2f.png)

I got vel_ll.grd (converting to .png) like this, I thought the result was wrong because I got some InSAR points on the sea.

(1) vel_ll
![image](https://user-images.githubusercontent.com/74343146/119659726-06325880-be61-11eb-98b3-fe99a1a5cce5.png)

(2) one of my unwrap.grd in the intf_all folder
![image](https://user-images.githubusercontent.com/74343146/119659877-32e67000-be61-11eb-9933-367e7b64d63e.png)

(3) one of my corr.grd in the intf_all folder
![image](https://user-images.githubusercontent.com/74343146/119660134-7a6cfc00-be61-11eb-9901-6ea47002f00e.png)

2. WARNING from proj_ra2ll.csh. How can I solve that? 
![image](https://user-images.githubusercontent.com/74343146/119660510-ecdddc00-be61-11eb-8f11-a27eab7bfbca.png)

Is there any suggestion for me?  Thank you.

OS: Ubuntu 18.04 LTS
GMTSAR version:  5.6

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Encheng,
You probably need to create a landmask before you run snaphu.csh. To do that, you could either specify mask_water in your config file/or switch_land in some version of gmtsar. Or you could create one using landmask.csh and put/link the generated landmask_ra.grd in your folder to run snaphu.csh.
Xiaohua(Eric)

**Comment by EnCheng-Li** [comment]
Hi Eric,
Thank you for your suggestions.
I created intf.tab for sbas.
![image](https://user-images.githubusercontent.com/74343146/119760474-a5e0fc80-bedc-11eb-926e-88521a8205e3.png)

unwrap.grd and corr.grd were used to run sbas.
unwrap.grd contained data on the sea but corr.grd didn't.
Is it right or not?
Or I should use unwrap.grd to run sbas?
![image](https://user-images.githubusercontent.com/74343146/119761083-c2316900-bedd-11eb-9d76-2e2ef1bc06af.png)

**Comment by Xiaohua-Eric-Xu** [comment]
This is because sbas will consider a pixel/column incomplete when any of the interferogram at that pixel is nan. You could unwrap with a low coherence threshold, e.g. 0.0001, to retain more pixels, or create a common mask based on stacked coherence and name it mask_def.grd. Then snaphu.csh will read that in to mask data.

**Comment by EnCheng-Li** [comment]
Hi Eric,
Thank you for your suggestion.
I tried to use landmask and set switch_land = 1 and left region_cut blank.
Then I got some error as attached. 
How can I solve this? Thank you.

![image](https://user-images.githubusercontent.com/74343146/119871716-4f63d480-bf55-11eb-9ff2-41d1aaa11cba.png)

**Comment by Xiaohua-Eric-Xu** [comment]
What's the command you ran?

**Comment by EnCheng-Li** [comment]
I ran intf_tops.csh.

**Comment by Xiaohua-Eric-Xu** [comment]
If you just run the following command in one of your interferogram folder (with trans.dat in it), what'll show up?
```
landmask.csh `gmt grdinfo phase.grd -I- | cut -c3-20`
```

**Comment by EnCheng-Li** [comment]
It works well as attached.
![image](https://user-images.githubusercontent.com/74343146/119919922-01bf8a00-bf9e-11eb-922a-02fb094cfa3a.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Did you get a landmask_ra.grd?

**Comment by EnCheng-Li** [comment]
Yes, I got a landmask_ra.grd.

**Comment by Xiaohua-Eric-Xu** [comment]
Then if you put that into the folder where you are gonna run snaphu.csh, it should be able to apply the masking. I am not sure why intf_tops.csh gave you an error as it looks like something popped out when landmask.csh was running.

**Comment by EnCheng-Li** [comment]
Hi Eric,
Thank you for your suggestion.
