### ISSUE TITLE
SBAS aps 

### ISSUE THREAD

**Issue by simonst7** [gmtsar/gmtsar#15]
Dear all
I have a problem with my results with ALOS data. I processed 10 interferograms with 1yr temporal baseline in a desert with ocean to the west. i made the batch processing for Level 0 data Alos (2008-2011), then i ran sbas with atm 5 iterations, but my results are wrong in some cm deformation( interseismic periods have a small deformación) , i think the atmospheric delay Is greater than deformation, but my aps results Is 0 in z. I dont understsnd, Could be also some ionospheric delay, or the large temporal baseline in sbas not working?. Thank
Simon

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Simon,
The SBAS program has a built-in symmetry threshold (if I remember right) for atmospheric phase estimation. This was designed for satellites with more regular acquisitions like Sentinel where you could maintain seasonal deformation even after taking out turbulent atmospheric component. This is probably the reason why all your aps grids are zeros.  You can probably change this by modifying sbas_utils.c at line 712&723. For now, it's acceptable if the two scenes are 5 days off.
712     if (hit[n * S + j] == 1 && fabs((time[n] - time[i]) - (time[j] - time[n])) < 5)
change 5 to a larger number if you really want this though I would not recommend it.

Xiaohua(Eric)

**Comment by simonst7** [comment]
Thank Eric, i supposed that problem, is there any way to calculate atmospherics delays between scenes with large temporal acquisition? Because you not recommend the change sbas_utils.c, My problem  is the little data ALOS to the study area,  i have only small perpendicular baseline between scenes in 1 yr or more.
Simon

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Simon,
If you are only interested in the deformation velocity, stacking might be a better option. 
We do have an ionosphere correction module, but it requires some tuning for the dataset in order to use it. 
Another alternative is to look for atmospheric models.
Xiaohua(Eric)

**Comment by simonst7** [comment]
I understsnd, thank Eric for you support. I Will try that solution
