### ISSUE TITLE
[Help]: How to evaluate the troposphere phase?

### ISSUE THREAD

**Issue by zhiqiang513** [gmtsar/gmtsar#150]
Hi Mr Xu 
Could you mind telling me how can I remove the tropospheric phase? Is there a way to evaluate the tropospheric phase and remove it .I check the official website and get a example talking about how to evaluate the ionospheric phase.So I am thinking whether there is a method about removing this?

**Comment by Xiaohua-Eric-Xu** [comment]
There are a number of ways dealing with tropospheric noise. 0) the simplest way is to smooth your time-series. 1) apply phase screens generated from weather model and GNSS, e.g. GACOS. 2) Fit your interferogram to topography to mitigate the layered water vapor. 3) Run iterative mitigation with our sbas code, which uses common-scene stacking. etc. etc....

**Comment by zhiqiang513** [comment]
Thanks！I have heard about the gacos which someone has used it when dealing with Ps.  He use gacos by code in matlab for removing noise ,so if I want use gacos ,should I make a code by myself. By the way ,I am dealing with a pair slc , is that ok just run csh in sbas  just like you mentioned ?

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, What do you mean you are dealing with a pair slc and run csh in sbas? I am confused.

**Comment by zhiqiang513** [comment]
I mean I am working on getting displacement caused by earthquake and I just use two slc to get interferogram，so if I want remove the tropospheric noise in this interferogram.should I run the sbas code you mentioned?

**Comment by Xiaohua-Eric-Xu** [comment]
For a pair, probably you need to depend on the weather model. p.s. compared to the a very strong earthquake signal, usually one could choose to ignore the troposphere noise.
