### ISSUE TITLE
[Help]: align in Ubuntu 20.04

### ISSUE THREAD

**Issue by sase1988** [gmtsar/gmtsar#151]
Hello. I've been using align_ALOS_SLC.csh to coregister SAOCOM images and everything went well when I used Ubuntu 18.04 Bionic. However, this has stopped working in Ubuntu 20, where I installed GMTSAR 6. The processing seems to run Ok, even the ashift and rshif are computed, but the output slave has no shift nor stretch applied in its PRM, and when trying to visualize the amplitude image it is all made of zeros. 

I would like to know whether this is an issue with the alignment or with another part of the processing chain.
Thank you in advance

OS: Ubuntu 20.04.2 LTS
GMTSAR version: 6.0

You can download the sample SAOCOM data read to GMTSAR here:  https://drive.google.com/drive/folders/1f6g7bNHbh9l8X-vjHgvfrrFm_pKv7Rsk?usp=sharing

![align](https://user-images.githubusercontent.com/36776334/119856167-e5ade100-bee8-11eb-86ae-6513ef25d730.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Here's a few things to check whether it is an alignment issue. 
1) check the shift/stretch parameters in your aligned.PRM file, inspect for strange numbers.
2) run slc2amp.csh on your aligned image, and check whether the resampled amplitude image look OK to you (this tells whether it put zeros or what in to your aligned image)
3) by the way, how do you know that ashift and rshif are computed, but the output slave has no shift nor stretch applied?
This'll require some test but I am currently on a travel.

**Comment by sase1988** [comment]
Hi Eric:

1. In the aligned .PRM file ashift and rshif are 0, and strech parameters are set to inf or nan:
`rshift  		= 0 
ashift  	 	= 0 
stretch_r   		= inf 
stretch_a   		= inf 
a_stretch_r   	= -nan 
a_stretch_a   	= -nan `

2. Indeed the aligned amplitude image that I generate with slc2amp.csh is all zeros
3. I see it when I start running the align process as in the screenshot, this line: `4733 26638 4733 26641 **-116 -22** 0.000000
`. Moreover, when running SAT_baseline I also get the ashift and rshift in the output:

`SAT_baseline SAO1A_20210102_VV.PRM SAO1A_20210408_VV.PRM
using command line
SC_identity = 20 
......master LED file SAO1A_20210102_VV.LED 
.........aligned LED file SAO1A_20210408_VV.LED 
hahahah
lon_tie_point =  -57.148604
lat_tie_point =  -37.779432
SC_vel              = 7268.954213000000 
SC_height           = 637792.443536744453 
SC_height_start     = 637818.153518126346 
SC_height_end       = 637766.347582262009 
earth_radius        = 6370062.456756000407 
**rshift              = -116** 
sub_int_r           = 0.0 
**ashift              = -22**
sub_int_a           = 0.0 
B_parallel          = 327.689683935403 
B_perpendicular     = 869.981834490525 
baseline_start      = 929.649891787862 
baseline_center     = 929.002926402238 
baseline_end        = 928.302436086936 
alpha_start         = 3.496017299008 
alpha_center        = 3.495344046009 
alpha_end           = 3.494624869927 
B_offset_start      = -42.750238403374 
B_offset_center     = -47.371101240224 
B_offset_end        = -51.998909831496`

**Comment by sase1988** [comment]
Hi Eric,

I am still having problems with align in Ubuntu 20, maybe it is something related to the resampling step? I tried it this time with branch 6.1 of GMTSAR. 

If you have any clue on what could be wrong, please let me know. I do not understand why this works ok in Ubuntu 18 and not in 20

Best
Santiago

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Santiago,
The shift paramters are computed with fitoffset.csh on freq_xcorr.dat output from xcorr. Sometimes the awk does funny things https://github.com/gmtsar/gmtsar/issues/117 and I am not sure whether this is the case for you.
Cheers,
Xiaohua(Eric)

**Comment by sase1988** [comment]
Indeed this is happening? But was there a solution to [#117](https://github.com/gmtsar/gmtsar/issues/117)?

**Comment by sase1988** [comment]
Indeed, the problem was that!! Now fitoffset.csh gives the outputs correctly
Thank you
