### ISSUE TITLE
[Solution]There are two gaps while processing S1B and S1A images by GMTSAR.

### ISSUE THREAD

**Issue by mzlyu** [gmtsar/gmtsar#153]
When I use GMTSAR to process the images of S1A and S1B, there are two gaps in the result.
The solution is as follows.
First, you need to update your gmtsar code to the latest master branch.
Then, manually merge_swath in the merge folder, using three previously prepared input files. You need to debug the values of n1 and n2 until there is no gap.

**Comment by insar-dev** [comment]
hi,
could you give me one image name for testing gap?
i have not met such data before.
thank you.

**Comment by mzlyu** [comment]
> hi,
> could you give me one image name for testing gap?
> i have not met such data before.
> thank you.

Hi,
Maybe crevice? GMTSAR divides the images into three parts for processing, and then stitches the three parts together before phase unwrapping. If the two images are not from the same satellite, the stitching process may be a bit flawed.

**Comment by insar-dev** [comment]
i thought it was from the same satellite.

**Comment by Xiaohua-Eric-Xu** [comment]
One will need to update the code to the master branch in order to do this.
