### ISSUE TITLE
sbas 

### ISSUE THREAD

**Issue by neda2133** [gmtsar/gmtsar#155]
Hello Dears
I  process  sbas time series for 3 years. 
But the velocity map is not generated 
when i run 
 sbas intf.tab scene.tab 82 33 2723 6094 -smooth 5.0 -wavelength 0.0554658 -incidence 34.231 -range 799137.543447 -rms -dem -atm 1

 gives the following error:
![image](https://user-images.githubusercontent.com/73532419/120636004-5c675300-c482-11eb-89da-2903c3223707.png)

please help.
regards

**Comment by Xiaohua-Eric-Xu** [comment]
Make sure you have enough RAM to run the program.

**Comment by neda2133** [comment]
> Make sure you have enough RAM to run the program.

i have 178G free for processing

**Comment by Xiaohua-Eric-Xu** [comment]
If you do this, what does it show you on the terminal? 
```
free -g
```

**Comment by neda2133** [comment]
> `free -g`

Shows this:
![image](https://user-images.githubusercontent.com/73532419/120693632-7d4d9980-c4be-11eb-9e45-1a364eaa2207.png)

**Comment by Xiaohua-Eric-Xu** [comment]
So you have about 11G RAM to use, which I believe is not enough for reading in that many interferograms. Either downsample your images or install more memory.

**Comment by neda2133** [comment]
> So you have about 11G RAM to use, which I believe is not enough for reading in that many interferograms. Either downsample your images or install more memory.

Thank you very much dear Eric
I will try this
