### ISSUE TITLE
prep_data_linex.csh issue

### ISSUE THREAD

**Issue by CFEgildan71** [gmtsar/gmtsar#156]
Hello Erik

I have been working well since 1 year ago using prep_data_linux.csh file to download the orbit files for sentinel 1 using the same folder structure as the examples we can download from GMTSAR web page. Now I am trying to use it but I get an error that after analyzing some time, I don't know what about is.

![Screenshot from 2021-06-06 19-15-04](https://user-images.githubusercontent.com/38848954/120944736-b6bf1880-c6fb-11eb-85e0-af156c43be54.png)

I got the same issue using either prep_data_linux.csh or prep_data_ubuntu.csh due to they are the same script.

Could you help me to understand where the issue is? and why I hadn't this issue processing before?.

Thank you.
Daniel.

**Comment by Xiaohua-Eric-Xu** [comment]
Could this be the case? https://github.com/gmtsar/gmtsar/issues/141 
i.e. duplicates in the records.

**Comment by CFEgildan71** [comment]
Thank you Erick.

After trying that python script, I noticed that all Sentinel-1/B registers were eliminated from the orbit list. I fixed that problem basing the search on the first and the last 2 columns.

Here is my modified version of that script.

Thank you very much.

[removeDuplicates.py.txt](https://github.com/gmtsar/gmtsar/files/6626267/removeDuplicates.py.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Thanks! I made a recent fix to the code so as to handle these duplicates. If you update the code, the error should be gone. :)
5def80d908bcdcea08da19839c46ff76547a1641
d080a4abb8bf2a712f42dda0cedc8444d57bd18a
