### ISSUE TITLE
SBAS running

### ISSUE THREAD

**Issue by charanchaganti93** [gmtsar/gmtsar#157]
While running SBAS, we got the following error, please suggest
![sbas error](https://user-images.githubusercontent.com/71376959/121527860-812a7000-ca18-11eb-9053-c7ebbbd17617.JPG)

**Comment by Xiaohua-Eric-Xu** [comment]
Looks like you were not able to read in the data. How much RAM do you have?

**Comment by charanchaganti93** [comment]
16 GB it is
I have reduced the number of interferograms and tried again 
But the result is same
![Sbas error](https://user-images.githubusercontent.com/71376959/122026330-b99ac700-cde7-11eb-9340-9647db8c19fc.JPG)

**Comment by Xiaohua-Eric-Xu** [comment]
You need 8530x6534x(52*4+31)/1024^3 + eps = 12.4GB which is roughly on the verge.

**Comment by mobigroup** [comment]
> You need 8530x6534x(52*4+31)/1024^3 + eps = 12.4GB which is roughly on the verge.

@Xiaohua-Eric-Xu Maybe could you add the required RAM estimation to the output? It'd be very helpful for debugging.

**Comment by Xiaohua-Eric-Xu** [comment]
That's a good idea. I'll write something in the code.
