### ISSUE TITLE
[Help]: unwrap_intf.csh can't be found

### ISSUE THREAD

**Issue by dhy158** [gmtsar/gmtsar#158]
Dear Sir or Madam
I can't find unwrap_intf.csh in my $PATH, there is a example script of unwrap_intf.csh in document"sentinel_time_series_3"
___________________________________
#!/bin/csh -f
# intflist contains a list of all date1_date2
directories.
cd $1
snaphu_interp.csh 0.10 0
cd ..
___________________________________
this is all of unwrap_intf.csh?

**OS and software version**
If applicable, what operating system and software version you are using?
OS:Ubuntu 18
GMTSAR version:5.4

**Comment by Xiaohua-Eric-Xu** [comment]
You could simply create one and put to your $PATH if you want.

**Comment by dhy158** [comment]
> 
> 
> You could simply create one and put to your $PATH if you want.

Thanks Sir. A new problem is that my system can not find command unwrap_intf.csh  that I created in my merge directory. What can i do?

**Comment by Xiaohua-Eric-Xu** [comment]
You could 1) chmod +x unwrap_intf.csh 2) mv unwrap_intf.csh /usr/local/GMTSAR/bin

**Comment by misha0402** [comment]
when i tried using 'mv unwrap_intf.csh /usr/local/GMTSAR/bin'
I got following error:

'/usr/local/GMTSAR/bin/unwrap_intf.csh': Permission denied

**Comment by Xiaohua-Eric-Xu** [comment]
you need to `sudo` I think.
