### ISSUE TITLE
preproc_batch_tops_esd.csh data.in dem.grd 2

### ISSUE THREAD

**Issue by neda2133** [gmtsar/gmtsar#159]
hi dear all.
 I am processing the time series of SBAS when i run:    preproc_batch_tops_esd.csh data.in dem.grd 2

 I receive the following:

![image](https://user-images.githubusercontent.com/73532419/122681592-3b388d80-d20a-11eb-902b-91534a005efb.png)

and data.in is :

![image](https://user-images.githubusercontent.com/73532419/122681844-8b641f80-d20b-11eb-9c49-d70f06986018.png)

but If I run Without  esd, the processing will be done
 means if run:   preproc_batch_tops.csh data.in dem.grd 2

What is the reason?

Thanks for guiding me

**Comment by Xiaohua-Eric-Xu** [comment]
Did you specify ESD mode?

**Comment by neda2133** [comment]
> Did you specify ESD mode?

Yes, I chose mode 2

**Comment by Xiaohua-Eric-Xu** [comment]
What exact command did you run? `preproc_batch_tops_esd.csh data.in dem.grd 2`?

**Comment by neda2133** [comment]
> What exact command did you run? `preproc_batch_tops_esd.csh data.in dem.grd 2`?

Yes, I executed the same command

**Comment by Xiaohua-Eric-Xu** [comment]
Well, you need another mode parameter to tell the script the ESD_Mode. e.g.
`preproc_batch_tops_esd.csh data.in dem.grd 2 1`
