### ISSUE TITLE
Unwrapping Errors

### ISSUE THREAD

**Issue by Mieszko-Fydrych** [gmtsar/gmtsar#16]
Hello,

After merging the subswaths and sacking the coherence and masking water surfaces, I tried unwrapped using the script unwrap_intf.csh. 
![unwrap_error](https://user-images.githubusercontent.com/61254441/75280159-e97d2000-57da-11ea-8cb2-6718a43a0d25.PNG)

I checked the forums for similar issues, but those solutions did not work for me. 
For reference, my unwrap_intf.csh script is as follows:

#!/bin/csh -f
# intflist contains a list of all date1_date2 directories.
foreach line (`awk '{print $1}' intflist`)
  cd $line
  ln -s ../mask_def.grd
  snaphu_interp.csh 0.001 0/8618/0/1839
  cd ..
end

What am I doing wrong?
Thanks,
Mieszko

**Comment by Xiaohua-Eric-Xu** [comment]
Hi mieszko,
Here is a normal output when you run snaphu_interp.csh. Seems your snaphu.conf.brief is missing.

Setting search radius to be 300 ...
Reading in original grid...
Interpolating to nearest neighbour...
  70304209 number of searches used ...
WRITING GRID IMAGE: Width x Heihgt = 3134 x 2742...
unwrapping phase with snaphu - higher threshold for faster unwrapping 

snaphu v2.0.1
32 parameters input from file /usr/local/GMTSAR/share/gmtsar/snaphu/config/snaphu.conf.brief (297 lines total)
Reading wrapped phase from file phase.in
No weight file specified.  Assuming uniform weights
Reading correlation data from file corr.in
Calculating smooth-solution cost parameters
Building range cost arrays
Building azimuth cost arrays
Initializing flows with MST algorithm
Running approximate minimum spanning tree solver
Running nonlinear network flow optimizer
Maximum flow on network: 6
Number of nodes in network: 8587554
Flow increment: 1  (Total improvements: 0)
Found 1 valid set(s) of connected pixels
Source 0 row, col = -2, -2
Treesize: 8587554    Pivots: 585041      Improvements: 2682       
Maximum flow on network: 1
Total solution cost: 9345905
Integrating phase
Writing output to file unwrap.out
Program snaphu done
Elapsed processor time:   0:01:15.19
Elapsed wall clock time:  0:01:16
Unwrapped phase map: unwrap.pdf

Cheers,
Xiaohua(Eric)

**Comment by Mieszko-Fydrych** [comment]
Hi Eric,

I just re-installed snaphu and ran the script again but got the same errors. Is the snaphu.conf.brief file part of the snaphu installation or generated as part of the GMTSAR process?

Thanks,
Mieszko

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Mieszko,
Should be located here
/usr/local/GMTSAR/share/gmtsar/snaphu/config/snaphu.conf.brief
I think you can also find it at GMTSAR/gmtsar/csh
Cheers,
Xiaohua(Eric)

**Comment by Mieszko-Fydrych** [comment]
Hi again,

When I check that file path, the file is there. However, the script still does not find it. Do I need to include the path to the file somewhere?

Thanks,
Mieszko

**Comment by Xiaohua-Eric-Xu** [comment]
I think your installation is fine. After a second look. I think this line is where the bug is.

snaphu_interp.csh 0.001 0/8618/0/1839

Where the usage says
snaphu_interp.csh correlation_threshold **maximum_discontinuity** [<rng0>/<rngf>/<azi0>/<azif>]

You probably need to change it to
snaphu_interp.csh 0.001 0 0/8618/0/1839

**Comment by Mieszko-Fydrych** [comment]
Hey Eric,

That was the solution! Thank you so much. I do get some warnings, such as: 

grdcut: Warning: (e - x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
grdcut: Warning: e reset from 8618 to 8616

But it doesn't seem to be causing any issues.

Thanks again,
Mieszko

**Comment by Xiaohua-Eric-Xu** [comment]
You can leave the rng0/rngf/azi0/azif blank to avoid this. The program will determine the proper range and azimuth.
