### ISSUE TITLE
vel_ll.grd file

### ISSUE THREAD

**Issue by charanchaganti93** [gmtsar/gmtsar#161]
Hello,

Below text is the output of grdinfo of vel_ll.grd file

if we see the z values here it ranges from -5000 to 2000 which should not be the case

Kindly suggest where it could have been wrong

Thanks

vel_ll.grd: Title: z
vel_ll.grd: Command: xyz2grd llpb -R83.25/86/27.1291666667/29.1 -I2s/1.5s -r -fg -Gvel_ll.grd -bi3f
vel_ll.grd: Remark: 
vel_ll.grd: Pixel node registration used [Geographic grid]
vel_ll.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
vel_ll.grd: x_min: 83.25 x_max: 86 x_inc: 0.000555555555556 (2 sec) name: longitude n_columns: 4950
vel_ll.grd: y_min: 27.1291666662 y_max: 29.0999999995 y_inc: 0.00041666666666 name: latitude n_rows: 4730
vel_ll.grd: z_min: -5725.85595703 z_max: 2432.17504883 name: z
vel_ll.grd: scale_factor: 1 add_offset: 0
vel_ll.grd: format: netCDF-4 chunk_size: 131,132 shuffle: on deflation_level: 3

**Comment by Xiaohua-Eric-Xu** [comment]
Hummm, do you have a map plotted? Also, you need to check that the input should be phase not LOS displacements.

**Comment by charanchaganti93** [comment]
![vel_ll](https://user-images.githubusercontent.com/71376959/128840160-3b1585d8-f933-4e64-bbc3-d9898563fa4e.png)
The results in the map seems to be fie but the values are not matching at all. What do you mean by we should give input as phase is it for the proj_ra2ll.csh command  
please help

**Comment by charanchaganti93** [comment]
Thank you so much for your quick response

sbas intf_2.tab scene_test.tab 21 41 8530 6534 -range 885288 -incidence 40 -wavelength 0.554658 -smooth 5.0 -rms -dem

[intf_2 (copy).txt](https://github.com/gmtsar/gmtsar/files/6963576/intf_2.copy.txt)
[scene_test (copy).txt](https://github.com/gmtsar/gmtsar/files/6963577/scene_test.copy.txt)
[S1_20190408_ALL_F2 (copy).txt](https://github.com/gmtsar/gmtsar/files/6963593/S1_20190408_ALL_F2.copy.txt)

also attaching the master prm for your reference 

I have considered only 20 images from a stack of 120 unwrapped (which were merged using all the three sub swaths) and master image is not one of these 20 images. Could that be a problem

**Comment by Xiaohua-Eric-Xu** [comment]
Haven't checked the files, but your `-wavelength 0.554658` seems strange. The unit is in meters and you probably want to change it to 0.0554658.

**Comment by Xiaohua-Eric-Xu** [comment]
Other files look OK. I do suggest 
1) make more connections among your scenes, i.e. produce more interferograms, thus the -atm option could mitigate atmospheric artifacts.
2) if you are interested in localized deformation (e.g. a geothermal field), consider de-trending your data with `gmt grdtrend -N3r you_phase.grd -Dyour_phase_detrended.grd`

**Comment by charanchaganti93** [comment]
Thank you for pointing out that mistake, wavelength value entered in the command must have been a typo. I will correct it and run again. 

Considering your suggestion, as I said I already have 120 interferograms generated from 67 images but to run sbas we needed an HPC, my RAM was not sufficient to perform sbas for so many interferograms. That's why I had to cut down the number to just 20 for which my PC could run sbas.

And for this geothermal field what is the input grid that we should be giving. Will I be able to mark the fault boundary and the fault slip rate using this geo thermal field
