### ISSUE TITLE
[Bug]: why not do use fix_prm ?

### ISSUE THREAD

**Issue by insar-dev** [gmtsar/gmtsar#162]
**Describe the bug**
   in merge_swath.c, i see the USAGE says :
![image](https://user-images.githubusercontent.com/1676595/124423728-57a30100-dd98-11eb-8aee-8eedca40eb66.png)

so i think the aligned prm shoud be to fix, but it is commented:
![image](https://user-images.githubusercontent.com/1676595/124423937-b8323e00-dd98-11eb-8d56-987974eb2bae.png)

if it is not fixed, the clock_start is corrected? 

thank you.

**Screenshots**

**System and software version:**
 - GMTSAR version: last in github

**Comment by insar-dev** [comment]
i try to modify code to merge aligned slc swaths

**Comment by Xiaohua-Eric-Xu** [comment]
I think there was a reason that I commented them out, but I don't remember exactly why. 
It may affect batch processing, but I maybe wrong.
