### ISSUE TITLE
[Help]: Corr.grd  problem

### ISSUE THREAD

**Issue by nubati** [gmtsar/gmtsar#163]
Hello everyone!

I am new in SBAS with GMTSAR, 

currently, I am going to process the SBAS using GMTSAR, however I got this problem 

`sbas: File /media/ccc/TES/download/SLC/raw_orig/intf_all/2019330_2019354/corr.grd not found
[Session sbas (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  /media/ccc/TES/download/SLC/raw_orig/intf_all/2019330_2019354/corr.grd `

I don't know what's going on there, I have been tried for twice to re-create the interferogram, but it was similar.

Anyone knows how to solve this?

Thank you in advance.

![Screenshot from 2021-07-10 16-45-17](https://user-images.githubusercontent.com/87225459/125157747-37f84800-e19f-11eb-8880-b9b86f2580cd.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, you probably need to check whether the corr.grd exist in your specified path.

**Comment by nubati** [comment]
Hi Eric!

Thanks for your comment. I have been changed my path and renew it. However i got the same result,
Attached my intf folder, intf.tab file, and the result.

![image](https://user-images.githubusercontent.com/87225459/125202521-893f2f00-e2a6-11eb-8dbf-16d3bd3065cf.png)

![image](https://user-images.githubusercontent.com/87225459/125202490-6876d980-e2a6-11eb-8132-7d1676248d87.png)

![image](https://user-images.githubusercontent.com/87225459/125202604-e1763100-e2a6-11eb-9f9d-2fd76af7e9dd.png)

**Comment by Xiaohua-Eric-Xu** [comment]
A few things to check here
1) Is there unwrap.grd and corr.grd inside 2019318_2019330? This is not the first record in your intf.tab, so maybe it did not produce the correct files?
2) Why there's a 2020013_ folder? This does not look correct to me.
3) Are the records in your scene.tab in the chronological order?
Xiaohua(Eric)

**Comment by nubati** [comment]
Hi Eric!

Thanks for your time,

1. the unwrap and corr.grd have been inside the folder (attached fig.1).
2. I just reproduced the ifg formation, and currently the 2020013_ deleted (attached fig. 2).
3. attached the scene.tab of mine (Fig. 3)

although I was reproduced the ifgs, however the problem is still the same (attached fig. 4)

![image](https://user-images.githubusercontent.com/87225459/125307944-16e05480-e363-11eb-8ec4-dedbe61a64c7.png)
![image](https://user-images.githubusercontent.com/87225459/125319737-9d019880-e36d-11eb-8e36-f9601393192f.png)
![image](https://user-images.githubusercontent.com/87225459/125319902-c6222900-e36d-11eb-8c38-6798708f6409.png)
![image](https://user-images.githubusercontent.com/87225459/125320290-25803900-e36e-11eb-8ea6-195b2ab0f320.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi I think the first column of your scene.tab needs to be in yyyyddd format, not yyyymmdd. sbas use that as a reference to find the pair listed in your intf.tab

**Comment by nubati** [comment]
Hi Eric!
oh I got it, let me try it.

**Comment by nubati** [comment]
Hi Eric!
Thanks for your advice! the problem is solved. 
I found some of my mistakes:
1. In the inft.tab. I was wrong to write the sentinel date started 2019318. I was using "_" mark, while it should be no mark (the rectangle on the fig. 1)
2. As you said about the format date of the scene.tab, I have changed the format date, so it was clear and okay then.

and the result is like Figure 2. It stop on the "write output...", however I didn't found any result then, is there any problem there?

![image](https://user-images.githubusercontent.com/87225459/125340947-a434a080-e385-11eb-91a5-c601cdd96f27.png)
![image](https://user-images.githubusercontent.com/87225459/125341157-e2ca5b00-e385-11eb-8d14-a73c8a00610e.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You should be getting a vel.grd which is the linear regressed velocity, and disp_yyyyddd.grd-s that are displacements grids.

**Comment by nubati** [comment]
I got it. Thank you so much!

 BTW is there any related reference regarding the SBAS parameters in GMTSAR ?

**Comment by Xiaohua-Eric-Xu** [comment]
Coherence Based SBAS:
Tong, X. and Schmidt, D., 2016. Active movement of the Cascade landslide complex in
Washington from a coherence-based InSAR time series method. Remote Sensing of
Environment, 186, pp.405-415.

Common Scene Stacking for correcting atmospheric artifact:
Tymofyeyeva, E. and Fialko, Y., 2015. Mitigation of atmospheric phase delays in InSAR data, with
application to the eastern California shear zone. Journal of Geophysical Research: Solid Earth,
120(8), pp.5952-5963.

Combining the two and with regard to Sentinel TOPS data:
Xu, X., Sandwell, D. T., Tymofyeyeva, E., González-Ortega, A., & Tong, X. (2017). Tectonic and
anthropogenic deformation at the Cerro Prieto geothermal step-over revealed by Sentinel-1A
InSAR. IEEE Transactions on Geoscience and Remote Sensing, 55(9), 5284-5292.

**Comment by nubati** [comment]
Hi Eric! Thanks for your references. 

and I would like to ask, how to create like this figure in GMTSAR? I mean how to get each velocity from the location in interest? 

![image](https://user-images.githubusercontent.com/87225459/125486410-08864fac-0285-4578-b081-bce8f911a84c.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Nubati,
For a given point on the Earth (lon lat elevation). Use SAT_llt2rat to compute range and azimuth, use grdtrack to extract the point from your disp_yyyyddd.grd-s and then you could plot them. You could run SBAS with or without -atm to form the time-series above.
Xiaohua(Eric)

**Comment by nubati** [comment]
Hi Eric! 
How are you?
Sorry for always give questions..

I have finished my SBAS, and I found vel.grd, disp_yyyyddd.grd, etc..
I was trying to open the vel.grd and I found very big range either the vel and disp _yyyyddd.grd (attached the figure). Is there any problem with that?

Thank you

![image](https://user-images.githubusercontent.com/87225459/125806540-e47968a0-ab0f-4de8-95ed-2a0676663ea7.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure. What if you run `gmt grdinfo` on them. Or directly plot them with `gmt grdimage`?

**Comment by nubati** [comment]
this is the gmt grdinfo
![image](https://user-images.githubusercontent.com/87225459/125844485-ca39851b-ef05-4485-be8e-c90c2b9b6e64.png)

**Comment by Xiaohua-Eric-Xu** [comment]
A few questions:
1) did you pin a zero point among your interferograms?
2) check your scene.tab and intf.tab 
3) the -atm works best with 3-5 iterations
