### ISSUE TITLE
[Help]: Where can I check the s1 registration accuracy?

### ISSUE THREAD

**Issue by insar-dev** [gmtsar/gmtsar#164]
hi, Where can I check the s1 registration accuracy?thank you.

**Comment by Xiaohua-Eric-Xu** [comment]
Well, what specific parameter do you mean by registration accuracy? The accuracy is largely determined by the accuracy of orbits. For Sentinel-1, the precise orbit product is 2-3cm cross track, ~5cm along track.

**Comment by insar-dev** [comment]
Thank you for your reply @Xiaohua-Eric-Xu .
i want to know  the accuracy estimate of the offset of the master and slave images.
