### ISSUE TITLE
Ubuntu 21.04 installation error

### ISSUE THREAD

**Issue by CFEgildan71** [gmtsar/gmtsar#165]
Hello.

I'm trying to install GMTSAR on Ubunu 21.04, but after a week trying, I had not  success. GMT installation went well,  the problem is when I run make and make install on GMTSAR, I get a lot of warnings and some errors that I don't understand why, I'm following step by step the instructions, but I don't get success. Before to update from Ubuntu 20.04 to 21.04, GMTSAR, I hadn't any problem to install it, but now, I couldn't. 

It is possible GMTSAR is not compatible to Ubuntu 21.04?

No script files after installation in /usr/local/GMTSAR/bin/ 
![Screenshot from 2021-07-15 15-17-25](https://user-images.githubusercontent.com/38848954/125852025-c850b2ab-8431-4cbe-b4fb-64591c2b24ba.png)

![Screenshot from 2021-07-15 15-17-36](https://user-images.githubusercontent.com/38848954/125852028-7ac18cc3-b313-4b7d-9efd-47301bfa36c6.png)

**System and software version:**
 - OS: Ubuntu 21.04
 - GMTSAR version: lastest version 6.1 I guess

I attached the terminal log file to see the warnings and errors:
 
[log.txt](https://github.com/gmtsar/gmtsar/files/6825999/log.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
The warnings are OK. I think it started from these lines here
```
gcc -m64 -s -Wl,-rpath,/usr/lib/x86_64-linux-gnu bperp.o -L/usr/local/GMTSAR/gmtsar -lgmtsar -L/usr/lib/x86_64-linux-gnu -lgmt -llapack -lblas -lm   -L/usr/local/lib -ltiff -lm -o bperp
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x30): multiple definition of `debug'; bperp.o:(.bss+0x30): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x0): multiple definition of `SAR_mode'; bperp.o:(.bss+0x0): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x8): multiple definition of `forced_slope'; bperp.o:(.bss+0x8): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x10): multiple definition of `quiet_flag'; bperp.o:(.bss+0x10): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x14): multiple definition of `nodata'; bperp.o:(.bss+0x14): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x18): multiple definition of `sio_flag'; bperp.o:(.bss+0x18): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x1c): multiple definition of `roi_flag'; bperp.o:(.bss+0x1c): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x20): multiple definition of `dopp'; bperp.o:(.bss+0x20): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x24): multiple definition of `force_slope'; bperp.o:(.bss+0x24): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x28): multiple definition of `quad_pol'; bperp.o:(.bss+0x28): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x2c): multiple definition of `swap'; bperp.o:(.bss+0x2c): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(sio_struct.o):(.bss+0x34): multiple definition of `verbose'; bperp.o:(.bss+0x34): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(utils.o):(.bss+0x30): multiple definition of `debug'; bperp.o:(.bss+0x30): first defined here
/usr/bin/ld: /usr/local/GMTSAR/gmtsar/libgmtsar.a(utils.o):(.bss+0x34): multiple definition of `verbose'; bperp.o:(.bss+0x34): first defined here
```

**Comment by Xiaohua-Eric-Xu** [comment]
Also, unfortunately, we haven't tested Ubuntu 21.04 yet. The instruction is only for 20.04. I think I saw this before but forgot how I fixed it...

**Comment by Xiaohua-Eric-Xu** [comment]
Could you try a different C complier. You could change in config.mk.

**Comment by Xiaohua-Eric-Xu** [comment]
OK, I upgraded my Ubuntu virtual system to 21.04 and here's a temporary solution. 
```
autoconf
./configure --with-orbits-dir=/usr/local/orbits
```
now edit your config.mk file and add `-z muldefs` to your `CFLAGS` and `LDFLAGS`
```
make
make install
```
Maybe we should really fix these in the codes.

**Comment by Xiaohua-Eric-Xu** [comment]
![image](https://user-images.githubusercontent.com/16844111/125865682-392c4bdb-53bd-4bc3-9391-744b80c56ef8.png)

**Comment by CFEgildan71** [comment]
Hi @Xiaohua-Eric-Xu

I did what you said and the bug is fixed now, I finished the installation successfully.

Thank you so much!.

**Comment by Xiaohua-Eric-Xu** [comment]
Great!
