### ISSUE TITLE
[Help]: Output results representation

### ISSUE THREAD

**Issue by Zeeshan-Ali1992** [gmtsar/gmtsar#166]
I am working on GMTSAR. I have followed all the steps. Now i have results in the format of .grd. But i want to see the monthly deformation and also the overall deformation in the area. Basically as i have made the pairs for the SBAS i just want to see the deformation according to those pairs. So which software can be used for the visualization of the results of .grd and also the vel_ll.grd? Does the vel_ll.grd shows us the overall deformation from the 1st image to last image or it shows the time series deformation?
I will be thankful for your detail answers.
Regards
Ali
![Outputs](https://user-images.githubusercontent.com/76717101/126132142-6c40d48c-3aff-4d2d-bc14-a2bd0b628342.JPG)

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, vel_ll.grd is the final velocity grid derived by linearly regressing the solved time-series. You could also try the new time-series extraction script.

**Comment by Zeeshan-Ali1992** [comment]
Thanks for your response. So the Vel_ll.grd is the completed 1 time velocity of the whole time period. So as we have the pairs and i want to find the subsidence on the bases of those dates of the images. So how we can get the time series either from the disp_"Dates of the images".grd can give us the step by step difference of deformation?

**Comment by Xiaohua-Eric-Xu** [comment]
Are you asking for incremental deformation between the dates? You could use `gmt grdmath disp_day2.grd disp_day2.grd SUB = disp_12.grd`

**Comment by Zeeshan-Ali1992** [comment]
Thanks for your response. I have done that and i got new file with grd format. Which will show the land subsidence within the 2 images right? Secondly how we can convert the .grd to .tif, so that we can save our deformation output in tiff format to open it in Arcmap.

**Comment by Xiaohua-Eric-Xu** [comment]
You could use gmt2geotiff.csh , which is mostly plotting with GMT and then convert with psconvert.

**Comment by Zeeshan-Ali1992** [comment]
I have used "gmt grd2xyz vel_ll.grd" But it just show me the xy and z data on interface but couldn't save it in .txt file in same SBAS folder. Do we need to use some other script to save vel_ll.grd to vel_ll.txt?

**Comment by Xiaohua-Eric-Xu** [comment]
You could redirect your output with `>`, e.g. `gmt grd2xyz vel_ll.grd > xyz.dat`

**Comment by Zeeshan-Ali1992** [comment]
Thank you so much for your help.

**Comment by Zeeshan-Ali1992** [comment]
I have small question regarding baseline plot. How we can develop the baseline plot according to our pairs for interferograms in SBAS?

**Comment by Xiaohua-Eric-Xu** [comment]
Isn't something generated when you run select_pairs.csh?

**Comment by Zeeshan-Ali1992** [comment]
No its not working on that csh. How we can develop the plot after doing the processing step?

**Comment by Xiaohua-Eric-Xu** [comment]
Well, select_pairs.csh will reproduce baseline.ps.

**Comment by Zeeshan-Ali1992** [comment]
No i am talking about the table of pairs generation. I have attached 1 picture from other paper for your information.
![Image_1626937275417](https://user-images.githubusercontent.com/76717101/127597220-a59f9e27-83f9-4dfd-bc8b-dca584934e26.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
Well, if you are unhappy about the default plot (baseline.ps), all the needed info to produce a plot like above, are in intf.in and baseline_table.dat. The second file has all baselines information and the first contains all interferometric pairs.

**Comment by Zeeshan-Ali1992** [comment]
Yes. Those both files have the required information to make the pairs baseline table. Can you please help me out to use the csh for it to make this pairs plot output. Your help will be highly appreciated.

**Comment by Xiaohua-Eric-Xu** [comment]
if you run `select_pairs.csh baseline_table.dat 90 150` (two parameters are temporal_threshold baseline_threshold), the baseline.ps should have the pairs plotted.
![image](https://user-images.githubusercontent.com/16844111/127758859-e35a8821-c75c-4896-a69c-cf377c49766b.png)

**Comment by Zeeshan-Ali1992** [comment]
I have got the output of Vel.grd and i have changed it to geographic coordinate and the new file is vel_ll.grd. So now my question is that this output is shown in complete data land subsidence and up welling (vertical change). right? Secondly i have got a results for 6 months data so the output is only for this specific time period or its averaged for 1 year land subsidence in mm?  Like usually we are mentioning that we have land subsidence of mm/ yr in this area. Your explanation in this regard will be highly appreciated.

**Comment by Xiaohua-Eric-Xu** [comment]
It is still deformation in Line-of-sight. You could interpret them as vertical motions. The velocity has the unit of mm/yr. You could consider it as a derived velocity by linear regressing the time-series. 6 month will give larger uncertainties of course (than a time-series that spans several years).
