### ISSUE TITLE
[Help]: SBAS question about incidence angle

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#167]
Dear Sir or Madam:
I run sbas intf.tab scene.tab 3 3 24610 13078 -smooth 1.0 -wavelength 0.0554658 -incidence 30 -range 875768 -rms -dem.
I want to konw how to set the incidence.Is it means incidence angle?
But there are 3 different incidence angles in different IW*.
What should i set if i run SBAS with unwrap and corr from iw2 and iw3.
The incidence angle is 41 in iw2 and 45 in iw3. 
May i should run  -incidence 43.....................
Thanks for your answer.Expecting。。。

**Comment by Xiaohua-Eric-Xu** [comment]
Just taking the mean value should be OK. This is a rough number to be used for DEM error estimate. If you are solving for deformation time-series, the number does not have to be very accurate.

**Comment by swjiaotong-jyliu** [comment]
Thanks for your advice! the problem is solved.。^_^.

**Comment by Xiaohua-Eric-Xu** [comment]
Cheers!
