### ISSUE TITLE
Bugs: Ionospheric correction on sample InSAR data 

### ISSUE THREAD

**Issue by rinosalman** [gmtsar/gmtsar#17]
Hi Xiaohua,

I ran ionospheric correction on sample InSAR data downloaded from here https://topex.ucsd.edu/gmtsar/downloads/

The p2p_processing.csh failed to generate SLCH, SLCL, params1, and params2 (lines 335-350). 

Best,
Rino

**Comment by Xiaohua-Eric-Xu** [comment]
Found the bug that it's related to the lines I added for fbd-fbs interferograms. fixing it now

**Comment by Xiaohua-Eric-Xu** [comment]
Fixed in the recent master commit. 
https://github.com/gmtsar/gmtsar/commit/18492195468d43d8041c4562af8c66967f72f64c

**Comment by Xiaohua-Eric-Xu** [comment]
A further fix is made to p2p_processing in order to include topo correction in band-passed interferograms. b1236bf2071f67237ca986914b3ca2ad7c90a2a7
