### ISSUE TITLE
[Help]: preproc_batch_tops_esd.csh is failed

### ISSUE THREAD

**Issue by sase1997** [gmtsar/gmtsar#170]
When I run    preproc_batch_tops_esd.csh data.in dem.grd 2   
ERROR happened.

![sendpix1](https://user-images.githubusercontent.com/88028559/127133508-f600da85-3174-43cb-8d2e-c2b2c528057d.jpg)

ERROR: Caught signal number 11 (Segmentation fault) at
/usr/lib/x86_64-linux-gnu/libgmt.so.5(grd_ADD+0x83)[0x7f0c8b81cc23]
[0x8]

How can I slove it?

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, seems like an error with greenspline. I am not sure. Could you try a different ESD mode? e.g.`preproc_batch_tops_esd.csh data.in dem.grd 2 1`

**Comment by sase1997** [comment]
It doesn't work!
![sendpix0](https://user-images.githubusercontent.com/88028559/127253193-d2de865e-cbc2-4096-8ce0-8a906bb88f66.jpg)

Before this,I run    preproc_batch_tops_esd.csh data.in dem.grd 1    successfully!

Besides,I run command   preproc_batch_tops.csh 1 or 2 successfully!

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, strange, which version of GMTSAR did you install? My current shows a different Usage:
```
xix016% preproc_batch_tops_esd.csh

Usage: preproc_tops_batch.csh data.in dem.grd mode esd_mode
  preprocess and align a set of tops images in data.in, precise orbits required

  format of data.in:
    image_name:orbit_name
...

```

**Comment by sase1997** [comment]
![sendpix1](https://user-images.githubusercontent.com/88028559/127258900-af8b5fcb-0976-4c76-bbe4-4919d43e0409.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, you have gmtsar 5.7 or earlier I guess. Though this may not be the cause of the problem, but it's better to update the software.

**Comment by sase1997** [comment]
OK! Thanks very much!
Can the GMTSAR be directly updated by instructions or should it be reinstalled?

**Comment by Xiaohua-Eric-Xu** [comment]
Since you are using ubuntu (looks like), and have gmt5 installed (I think). Maybe it's a good time to consider whether to move forward to gmt6, and then gmtsar 6.1. If not, you could try gmtsar 5.8. But these earlier versions won't be maintained in the future.

**Comment by Xiaohua-Eric-Xu** [comment]
As for the error you met, it could be that your area are with low coherence (I am guessing) and spectral_diversity is not outputting enough high coherence points (>0.7) to do a smooth interpolation with mode=2. 
```
  esd_mode:
    0 for average, 1 for median, 2 for interpolation
```

**Comment by sase1997** [comment]
OK!Thank you very much for your professional advice! 
Learn from you!
