### ISSUE TITLE
Unwrapping jumps

### ISSUE THREAD

**Issue by esrivas17** [gmtsar/gmtsar#171]
Dear GMTSAR developers,

I wonder how I can correct my unwrapping phase. This is the case of a Mw 7.8 Earthquake.
I used the `snaphu_interp.csh` script with 0.02 as coherence threshold and 70 as maximum_discontinuity.
Im getting jumps near to the area of biggest deformation

I also got two profiles with ncview so you can see the jumps which are located towards the coastline.

![image](https://user-images.githubusercontent.com/45095410/127555840-21fe2ec7-d0ed-4f44-9e2c-494e3d8cedcf.png)
![image](https://user-images.githubusercontent.com/45095410/127555996-0ffb4054-f3b2-4d18-a496-87e7c3a6f19d.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Erik,
Here's what you could try. 
1) set mask_water or switch_land to zero, thus your wet region will have some pixels left based on the coherence threshold (e.g. 0.1)
2) set the near_interp = 1, so the phase will be interpolated.
3) run the processing with starting stage = 5.
4) after that, use the landmask to mask the wet part.
This will allow the phase to change along the coastline.
Cheers,
Xiaohua(Eric)

**Comment by esrivas17** [comment]
Hi Xiaohua,

I used `snaphu_interp.csh` because I get errors when I use `p2p_S1_TOPS_Frame.csh`.
I used the latter anyway and I attach the errors I got, not sure if there is a conflict with the GMT and GMTSAR versions.
I'm using GMT version 6.1 and GMTSAR version 6
I attach also the config file
[log.txt](https://github.com/gmtsar/gmtsar/files/6907654/log.txt)
[config.s1.txt](https://github.com/gmtsar/gmtsar/files/6907655/config.s1.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
If you already have interferogram produce in F1/2/3 and merged them. Then
1) go to your merge folder.
2) mv the landmask_ra.grd to another folder 
3) run `snaphu_interp.csh 0.1 0`
4) use the old landmask_ra.grd to mask the ocean.
Cheers,
Xiaohua(Eric)

**Comment by esrivas17** [comment]
Thanks Xiaohua,
it worked.
