### ISSUE TITLE
[Help]: preproc_batch_tops.csh data.in dem.grd 2

### ISSUE THREAD

**Issue by 501756347** [gmtsar/gmtsar#172]
HI Xiaohua,

I have a problem processing Sentinel-1A/B images in "preproc_batch_tops.csh data.in dem.grd 2". During the this step, I got some part of messages like this ：
 blockmedian [WARNING]: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
blockmedian (gmtapi_init_grdheader): Please select compatible -R and -I values
blockmedian [WARNING]: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
blockmedian (gmtapi_init_grdheader): Please select compatible -R and -I values
[1] 35954
[2] 35955
surface [WARNING]: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
surface (gmtapi_init_grdheader): Please select compatible -R and -I values
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [WARNING]: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
surface (gmtapi_init_grdheader): Please select compatible -R and -I values
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
but not all will have this problem ,only some have this error.
Could you let me know how to deal with this problem? Look forward to your reply.
Best
Liu

**Comment by 501756347** [comment]
![sendpix0](https://user-images.githubusercontent.com/73731090/127803784-bcaf6355-20d3-450d-8cfb-66cc7e366685.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi sorry for the late response, were you able to produce PRM LED and SLC files properly? Looks like complains from GMT, but those are warnings.

**Comment by 501756347** [comment]
> Hi sorry for the late response, were you able to produce PRM LED and SLC files properly? Looks like complains from GMT, but those are warnings.

oh，thanks ,it can produce PRM LED and SLC files，and I encounter another problem for： unwrap_parallel.csh intflist 6
During the unwrapping process, the terminal will appear: directories.: Command not found.
If I perform area cropping, the final size of corr.grd and unwrap.grd will be different, and dimension don't match will appear when running the SBAS program!
![image](https://user-images.githubusercontent.com/73731090/128799314-96d5a58c-06c9-41d7-97de-9c30525b7f46.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Well, if you read the script, it requires you to write a simple shell to execute snaphu[_interp].csh. There is a section in this document that tells how to do it. http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_3.pdf
For the dimension mismatch, simply crop your corr.grd with the same region parameters with `gmt grdcut`.

**Comment by 501756347** [comment]
> Well, if you read the script, it requires you to write a simple shell to execute snaphu[_interp].csh. There is a section in this document that tells how to do it. http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_3.pdf
> For the dimension mismatch, simply crop your corr.grd with the same region parameters with `gmt grdcut`.

Thank you very much for your help, but I have configured the script and placed it in the bin directory of gmtsar. It seems that it can be unwrapped, but such a prompt will appear in the terminal
![image](https://user-images.githubusercontent.com/73731090/128799981-70ddfa30-ddb6-4b60-ac48-41e6c53b52d9.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, you probably want to move your directories to the upper line. Without a #, the script will execute it as a command.
Also, you may want to redirect the terminal output to a file so your terminal won't keep popping random things. e.g.
`snaphu_interp.csh ... >& log_unwrap `

**Comment by 501756347** [comment]
I put [gmt grdcut] into the loop and executed it together，thank you very much for your help .

**Comment by 501756347** [comment]
> Hi, you probably want to move your directories to the upper line. Without a #, the script will execute it as a command.
> Also, you may want to redirect the terminal output to a file so your terminal won't keep popping random things. e.g.
> `snaphu_interp.csh ... >& log_unwrap `

I put [gmt grdcut] into the loop and executed it together，thank you very much for your help .
