### ISSUE TITLE
[Help]: intf don`t finish

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#173]
HI Xiaohua,
I have a problem processing Sentinel-1A/B images in "intf_tops.csh intf.in batch_tops.config". During the this step, I got some part of messages like this ：
INTF.CSH, FILTER.CSH - START
intf.csh
running phasediff...
reading topo topo_ra.grd
 The dimensions of azimuth do not match  
filter.csh
gauss_50 1 1 (1 2)
making amplitudes...
filtering interferogram...
conv: File real.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real.grd=bf 
conv: File real_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real_tmp.grd=bf 
conv: File imag.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag.grd=bf 
conv: File imag_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag_tmp.grd=bf 
making amplitude...
grdmath: Syntax error: realfilt.grd is not a number, operator or file name
grdmath: Syntax error: amp.grd is not a number, operator or file name
grdinfo: Error for input file: No such file (display_amp.grd)
grdinfo: Syntax error: Must specify one or more input files
grd2cpt: Error for input file: No such file (display_amp.grd)
grd2cpt: Syntax error -L option: Cannot decode limits
grd2cpt: Syntax error -L option: min_limit must be less than max_limit.
grdimage: Error for input file: No such file (display_amp.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
psscale: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale: Offending option display_amp.grd
psconvert: Error: The file display_amp.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making correlation...
grdmath: grid files not of same size!
grdmath: Syntax error: tmp.grd is not a number, operator or file name
grdmath: Syntax error: amp.grd is not a number, operator or file name
conv: File tmp2.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  tmp2.grd=bf 
grdimage: Error for input file: No such file (corr.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
psscale: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale: Offending option corr.grd
psconvert: Error: The file corr.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making phase...
grdmath: Syntax error: imagfilt.grd is not a number, operator or file name
grdimage: Error for input file: No such file (phase.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
psscale: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale: Offending option phase.grd
psconvert: Error: The file phase.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
filtering phase...
phasefilt: File imagfilt.grd not found
[Session phasefilt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 error reading file imagfilt.grd 
grdinfo: Error for input file: No such file (mask.grd)
grdinfo: Syntax error: Must specify one or more input files
grdedit: Error for input file: No such file (filtphase.grd)
grdmath: Syntax error: filtphase.grd is not a number, operator or file name
grdimage: Error for input file: No such file (phasefilt.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
psscale: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale: Offending option phasefilt.grd
psconvert: Error: The file phasefilt.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
mv: 无法获取"mask.grd" 的文件状态(stat): 没有那个文件或目录
grdmath: Syntax error: tmp.grd is not a number, operator or file name

Could you let me know how to deal with this problem? Look forward to your reply.
Thanks.

**Comment by swjiaotong-jyliu** [comment]
Add：
I try to replace dem
But the problem is not solved

**Comment by swjiaotong-jyliu** [comment]
Thanks，i used gmt grdinfo topo_ra.grd
topo_ra.grd: x_min: 0 x_max: 21660 x_inc: 2 name: x n_columns: 10830
topo_ra.grd: y_min: 0 y_max: 12192 y_inc: 2 name: y n_rows: 6096
topo_ra.grd: z_min: -608.986022949 z_max: 8.56679058075 name: z
It looks like right.

**Comment by swjiaotong-jyliu** [comment]
And
I run stage = 1
DEM2TOPOPHASE.CSH - START
USER SHOULD PROVIDE DEM FILE
 range decimation is:  2
blockmedian: Provides 3, expects 3-column binary data
blockmedian: Processing input table data
blockmedian: W: 0 E: 21660 S: 0 N: 12192 n_columns: 10830 n_rows: 6096
blockmedian: Input 3 columns via binary records using format ddd
blockmedian: Output 3 columns via binary records using format ddd
blockmedian: N read: 21044171 N used: 20955753 outside_area: 88418 N cells filled: 20955654
surface: Provides 3, expects 3-column binary data
surface: Grid domain: W: -690 E: 22350 S: -48 N: 12240 n_columns: 11520 n_rows: 6144 [pixel registration]
surface: Processing input table data
surface: Input 3 columns via binary records using format ddd
surface: Minimum value of your dataset x,y,z at: surface: 12946.5644531 11958.8574219 -621.626037598
surface: Maximum value of your dataset x,y,z at: surface: 26.2313022614 10.359670639 8.65964221954
surface: LS plane determined: z = 4.55842 + (-0.00603043 * col) + (-0.0880128 * row)
surface: Grid	Mode	Iteration	Max Change	Conv Limit	Total Iterations
surface:  768	D	      24	5.39993715265e-07	5.73671043989e-07	        24
surface:  256	I	      41	1.26761990458e-06	1.72101313197e-06	        65
surface:  256	D	      38	1.36336158998e-06	1.72101313197e-06	       103
surface:  128	I	      30	3.30883262106e-06	3.44202626394e-06	       133
surface:  128	D	     214	3.38734080242e-06	3.44202626394e-06	       347
surface:   64	I	      29	6.33426985466e-06	6.88405252787e-06	       376
surface:   64	D	     590	6.83212661463e-06	6.88405252787e-06	       966
surface:   32	I	      28	9.85756384897e-06	1.37681050557e-05	       994
surface:   32	D	    1736	1.3756165247e-05	1.37681050557e-05	      2730
surface:   16	I	      28	2.0582547361e-05	2.75362101115e-05	      2758
surface:   16	D	    3386	2.74510558154e-05	2.75362101115e-05	      6144
surface:    8	I	      26	4.64959917217e-05	5.5072420223e-05	      6170
surface:    8	D	    6405	5.50246609876e-05	5.5072420223e-05	     12575
surface:    4	I	      23	0.000101629080167	0.000110144840446	     12598
surface:    4	D	    1621	0.000110049321983	0.000110144840446	     14219
surface:    2	I	      22	0.000171630373528	0.000220289680892	     14241
surface:    2	D	    1453	0.000219608446531	0.000220289680892	     15694
surface:    1	I	      21	0.000396933535456	0.000440579361784	     15715
surface:    1	D	    1000	0.00048367167206	0.000440579361784	     16715
surface: Fit info: N data points  N nodes	mean error	rms error	curvature
surface: 	20955654	70796545	-2.40088932624e-06	0.0545727847575	7636916.59953
grd2cpt: Processing input grid(s)
grd2cpt: Mean and S.D. of data are -300.506095352 156.173222364
grdimage: Allocates memory and read data file topo_ra.grd
grdimage: Evaluate image pixel colors
grdimage: Creating 8-bit grayshade image
Topo range/azimuth map: topo_ra.pdf
DEM2TOPOPHASE.CSH - END
NO TOPOPHASE SHIFT

**Comment by swjiaotong-jyliu** [comment]
Maybe i know what's wrong.
At _preproc_batch_tops.csh data.in dem.grd 1_.
I don`t put dem.grd in F*/raw.
Thanks.
I am trying to do timeseries in North China Plain.
Thanks.

**Comment by Xiaohua-Eric-Xu** [comment]
Good luck!

**Comment by dhy158** [comment]
> Maybe i know what's wrong. At _preproc_batch_tops.csh data.in dem.grd 1_. I don`t put dem.grd in F*/raw. Thanks. I am trying to do timeseries in North China Plain. Thanks.
Hi, Xiaohua and jyliu. I think I meet the same problem as your say. My problem is "cannot find file real.grd" in F*, but I had run true preproc scripts. After troubleshoot problems, I find the problem was intf_tops.csh and filter.csh inside. When turn to stage 2 using intf_tops.csh , the error "cannot find file real.grd" is show. I want to know when the file real.grd was generated. I checked filter.csh script, this file  seems to come out of nowhere.
Explain that I have processed a lot of images with GMTSAR, and I have never encountered this problem.

**Comment by dhy158** [comment]
Hi, Xiaohua and jyliu. I think I meet the same problem as your say. My problem is "cannot find file real.grd" in F*, but I had run true preproc scripts. After troubleshoot problems, I find the problem was intf_tops.csh and filter.csh inside. When turn to stage 2 using intf_tops.csh , the error "cannot find file real.grd" is show. I want to know when the file real.grd was generated. I checked filter.csh script, this file seems to come out of nowhere.
Explain that I have processed a lot of images with GMTSAR, and I have never encountered this problem.

**Comment by Xiaohua-Eric-Xu** [comment]
> I want to know when the file real.grd was generated.

It is produced with `phasediff`, which is called by `intf.csh`. The error above is from topo_ra.grd having a different size from the data (which I think is likely from the `dem2topo_ra.csh` step).

**Comment by dhy158** [comment]
> > I want to know when the file real.grd was generated.
> 
> It is produced with `phasediff`, which is called by `intf.csh`. The error above is from topo_ra.grd having a different size from the data (which I think is likely from the `dem2topo_ra.csh` step).

Thanks your apply. I didn't see any related errors about dem file so that I don't think it was a matter with dem. I used create_frame scripts to paste two frames, and the range in two_pins.ll consistent with dem.grd(my dem.grd rang is 100E to 103E, 28N to 31N. my two_pins.ll is 
102.4 28.8
102.2 30.1.) 
After your reminder, I checked the coverage of the imaging and the extent of DEM. The problem is that DEM does not have the right range. the longitude rang of image is bigger than DEM file.
By the way, is there have a method to get range of pasted images？

**Comment by Xiaohua-Eric-Xu** [comment]
Could you attach the error log from your processing? I need to see it as you seem to indicate that yours are different from what posted above by **swjiaotong-jyliu** .

**Comment by dhy158** [comment]
I have reprocessed and  my previous log file is attached.
[log.txt](https://github.com/gmtsar/gmtsar/files/9944753/log.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Could you share your one.in and batch_tops.config?

**Comment by dhy158** [comment]
Ok, I uploaded my one.in and batch_tops.config.
[batch_tops_config.txt](https://github.com/gmtsar/gmtsar/files/9944779/batch_tops_config.txt)
[one_in.txt](https://github.com/gmtsar/gmtsar/files/9944780/one_in.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Here are a couple of things to check:
1) go to your topo directory and run `gmt grdinfo topo_ra.grd` and check the dimension of the file.
2) go to your raw directory and run `grep num_rng_bins *ALL*PRM` and `grep num_lines *ALL*PRM` and see whether these two numbers match your topo_ra.grd. The master image is intact so does not need to match perfectly in azimuth.

**Comment by dhy158** [comment]
Sir, I used new dem.grd to reprocess, but still  cannot generate true corr.grd and phase.grd.
my topo_ra.grd information in F2 is :
gmt grdinfo topo_ra.grd 
topo_ra.grd: Title: Produced by grdmath
topo_ra.grd: Command: grdmath pixel.grd FLIPUD = topo_ra.grd
topo_ra.grd: Remark: 
topo_ra.grd: Pixel node registration used [Cartesian grid]
topo_ra.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
topo_ra.grd: x_min: 0 x_max: 24960 x_inc: 2 name: x n_columns: 12480
topo_ra.grd: y_min: 0 y_max: 12188 y_inc: 2 name: y n_rows: 6094
topo_ra.grd: v_min: 1235.83337402 v_max: 7131.13769531 name: z
topo_ra.grd: scale_factor: 1 add_offset: 0
topo_ra.grd: format: netCDF-4 chunk_size: 129,130 shuffle: on deflation_level: 3

[num_lines.txt](https://github.com/gmtsar/gmtsar/files/9945114/num_lines.txt)
[num_rng_bins.txt](https://github.com/gmtsar/gmtsar/files/9945115/num_rng_bins.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure why but there are quite a few that have different num_rng_bins from the rest.
```
S1_20200520_ALL_F2.PRM:num_rng_bins		= 24960 
S1_20200601_ALL_F2.PRM:num_rng_bins		= 24960 
S1_20200613_ALL_F2.PRM:num_rng_bins		= 24960 
S1_20200625_ALL_F2.PRM:num_rng_bins		= 24960 
S1_20200707_ALL_F2.PRM:num_rng_bins		= 24960 
S1_20200719_ALL_F2.PRM:num_rng_bins		= 24960 
```
