### ISSUE TITLE
[Bug]: Incomplete document sentinel_time_series_3.pdf

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#175]
See page 25 of https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_3.pdf

> -incidence 40

"incidence" value is not described. What is it here and why it's equal to "40"? "sbas" command prints some info about it:

>   -incidence theta     --  incidence angle of the radar wave (degree) default=37 

But there is no answer for the value above (40). It's not a constant for a whole image, maybe sbas applicable only for small areas and "incidence" here is measured for the area center?

> Range = ({[(speed of light) / (rng_samp_rate) / 2] * ((x_min+x_max)/2)} /2 ) + near_range
> Range = ({[(3e8) / (64345238.125714) / 2]*36995.5895372} / 2 ) + 845000

"near_range" is not described. What is it and why it's equal to "845000"?

**Comment by mobigroup** [comment]
Also, in the same document we see:
> 5. Choosing Master/Reference Image and Aligning
a. Selecting a Reference Image from a Baseline Plot
b. Aligning Secondary Images to Reference Image
vi. Repeat steps 5a and 5b for directories F2 and F3, changing iw1 to iw2/iw3 in the links of step 5a(i).

But do we really need to select DIFFERENT masters for F1, F2, F3?.. Usually, the baselines are the same for sub swaths and so the same master should be selected. And later we have this instruction:

> 6. Running Interferograms -- Let’s see those fringes!
a. Preparing List of Interferograms
Copy the intf.in file from the F1 directory to the F2 and F3 directories (this overwrites the intf.in files created by step (ii), and ensures you have the same number of interferograms in each subswath)

I think this processing with manipulation by 3 different master images and aligning and mixing them looks weird. That's hard to check all the processing codes but probably we need to use the same master for all the sub swaths.

**Comment by mobigroup** [comment]
> 6. Running Interferograms -- Let’s see those fringes!
a. Preparing List of Interferograms
v. Edit the batch_tops.config file in each directory to ensure that the master image
name is set to the appropriate F1, F2 or F3 folder, e.g.: master_image = S1_20180508_ALL_F2 (for F2 processing)

Maybe is it the hint that we actually need to have just one master for all the sub swaths?

**Comment by mobigroup** [comment]
On page 17 of the document:
> IF1_Swath1_Path:master.PRM:repeat.PRM,IF1_Swath2_Path:master.PRM:repea t.PRM,IF1_Swath3_Path:master.PRM:repeat.PRM
...
For example, in our example case, the first line could read:
../F1/intf_all/2018127_2018133/:S1_20180508_ALL_F1.PRM:S1_20180514_A
LL_F1.PRM
../F2/intf_all/2018127_2018133/:S1_20180508_ALL_F2.P
,
RM:S1_20180514_ALL_F2.PRM
../F3/intf_all/2018127_2018133/:S1_2
0180508_ALL_F3.PRM:S1_20180514_ALL_F3.PRM

Here the same master image  (20180508) used although it's required to use different ones as specified above (sea 5.b.vi to repeat master selection for the each sub swath independently).

**Comment by mobigroup** [comment]
> 6. Running Interferograms -- Let’s see those fringes!
b. Run One Interferogram to Test Settings
ii. Generate your test interferogram and necessary run files
> ii 2. Once that finishes, edit batch_tops.config again and set proc_stage = 2, which will enable a full run of all interferograms, and will skip making the topo_ra file which has already been created in step 6(b)(ii)(1) above. Move to section 6(c) below.

Is it recommended for optimization only or is it mandatory? Usually, that's more easy to run the full processing for F1-3 instead of checking all the sub swaths to detect any previous changes in them.

**Comment by mobigroup** [comment]
> 7. Merging Across Subswaths
...
If we interpret this briefly for clarity:
IF1_Swath1_Path:master.PRM:repeat.PRM,IF1_Swath2_Path:master.PRM:repeat.PRM,IF1_Swath3_Path:master.PRM:repeat.PRM

Does it mean (IF1, IF2, IF3 instead of IF1 always):
IF1_Swath1_Path:master.PRM:repeat.PRM,IF2_Swath2_Path:master.PRM:repeat.PRM,IF3_Swath3_Path:master.PRM:repeat.PRM

How about the case when only one sub swath is needed? Is it correct to write as:
IF2_Swath2_Path:master.PRM:repeat.PRM

**Comment by mobigroup** [comment]
There is no documented way for the case when we need just one sub swath and merging is useless. In the documents we see "7. Merging Across Subswaths" but it doesn't work for a single sub swath with well prepared merge_list:
```
Merging START
 Incorrect input filelist, should contain 2 or 3 files
  
 Incorrect input filelist, should contain 2 or 3 files
  
 Incorrect input filelist, should contain 2 or 3 files
```

```
head merge_list
../F2/intf_all/2021091_2021115/:S1_20210402_ALL_F2.PRM:S1_20210426_ALL_F2.PRM
../F2/intf_all/2021019_2021055/:S1_20210120_ALL_F2.PRM:S1_20210225_ALL_F2.PRM
../F2/intf_all/2021019_2021043/:S1_20210120_ALL_F2.PRM:S1_20210213_ALL_F2.PRM
../F2/intf_all/2021067_2021079/:S1_20210309_ALL_F2.PRM:S1_20210321_ALL_F2.PRM
../F2/intf_all/2021187_2021199/:S1_20210707_ALL_F2.PRM:S1_20210719_ALL_F2.PRM
../F2/intf_all/2021163_2021199/:S1_20210613_ALL_F2.PRM:S1_20210719_ALL_F2.PRM
../F2/intf_all/2021151_2021187/:S1_20210601_ALL_F2.PRM:S1_20210707_ALL_F2.PRM
../F2/intf_all/2021103_2021127/:S1_20210414_ALL_F2.PRM:S1_20210508_ALL_F2.PRM
../F2/intf_all/2021055_2021067/:S1_20210225_ALL_F2.PRM:S1_20210309_ALL_F2.PRM
../F2/intf_all/2021163_2021175/:S1_20210613_ALL_F2.PRM:S1_20210625_ALL_F2.PRM
```

Probably, we need to copy some files into the "merge" directory to continue the processing but how to do it?

**Comment by mobigroup** [comment]
> 7. Merging Across Subswaths
a. Prepare the merge_list input file
...
Type create_merge_input.csh into the command line to see the example and usage. We run a command that looks like this:
create_merge_input.csh intflist .. 2 > merge_list

But how to create the intflist? There are also some occasional subdirectories inside... I can suggest this script to resolve the issue:
```
find ../F1/intf_all/ -mindepth 1 -maxdepth 1 -name '*' -type d | sed -s 's|^../F1/intf_all/||g' > intflist                                                    
```

**Comment by mobigroup** [comment]
> 7. Merging Across Subswaths
a. Prepare the merge_list input file
ii. Place a line which includes the master image as the master (first) of the pair of images, as the first line in the merge_list. Make sure to do this, as it will ensure that all images are processed with the same coordinates and are the same final grid size.

Is it means just the lines reordering or the 1st line is different and includes masters pairs only without file path? I suppose for master S1_20210402_ALL_F2 it should be like to (while it doesn't work for a single sub swath...): 
```
head merge_list
../F2/intf_all/2021091_2021115/:S1_20210402_ALL_F2.PRM:S1_20210426_ALL_F2.PRM
../F2/intf_all/2021019_2021055/:S1_20210120_ALL_F2.PRM:S1_20210225_ALL_F2.PRM
../F2/intf_all/2021019_2021043/:S1_20210120_ALL_F2.PRM:S1_20210213_ALL_F2.PRM
../F2/intf_all/2021067_2021079/:S1_20210309_ALL_F2.PRM:S1_20210321_ALL_F2.PRM
../F2/intf_all/2021187_2021199/:S1_20210707_ALL_F2.PRM:S1_20210719_ALL_F2.PRM
```

**Comment by mobigroup** [comment]
Maybe for one sub swath (F2, for the example) just making symlinks from the "merge" directory to all subdirectories in F2/intf_all/ will be enough.

**Comment by mobigroup** [comment]
> a. Unwrapping in Regions of Good Coherence
i. Unwrap the phase for each interferogram
1. In the merge directory, first make a list of interferogram directories to feed to the script:
ls -d 201* > intflist

It doesn't work for years 2020 and 2021 :) Also, we already have the list in file "intflist" because it's required above.

**Comment by mobigroup** [comment]
See script below to detect files required for a single sub swath unwrapping:
```
# cat /mnt/merge/test.sh 
rm -fr 2021007_2021019
mkdir 2021007_2021019
for file in corr.grd mask.grd phase.grd phasefilt.grd
do
	cp “/mnt/GMTSAR/asc/F2/intf_all/2021007_2021019/$file” 2021007_2021019
done
unwrap_intf.csh 2021007_2021019/
```
It works and the directory is filled by some additional files after that:
```
# ls 2021007_2021019 -1
conncomp.grd
corr.grd
gmt.history
mask2_patch.grd
mask.grd
phasefilt.grd
phasefilt_interp.grd
phase.grd
unwrap.cpt
unwrap.grd
unwrap.pdf
```

**Comment by mobigroup** [comment]
In "sbas" script we can find the near range definition:
```
  -range rng           --  range distance from the radar to the center of the interferogram (m) default=866000 
```
 and so it should be included in supemaster.PRM:
```
$ grep near_range supermaster.PRM | tr -d ' \t'
near_range=845450.236362
```
See also discussion here: [few doubts in sbas processing](http://gmt.soest.hawaii.edu/boards/6/topics/7951)

**Comment by mobigroup** [comment]
That's documented incorrect sometimes so see below the incidence angle calculation for SBAS processing.
```
$ sbas
...
-incidence theta     --  incidence angle of the radar wave (degree) default=37
...
```
1. Use our area of interest central coordinates to call GMTSAR SAT_look tool:
```
echo 48.07535857 38.05809494 1236.3561 | SAT_look S1_20210108_ALL_F2.PRM
48.075359 38.058095 843.528042 -0.604802 -0.109063 0.788873
```
2. Calculate the angle in degrees from the projected look vector components (the script below is valid Python code):
``` 
look_E, look_N, look_U = -0.604802, -0.109063, 0.788873
round(math.atan2(math.sqrt(look_E**2 + look_N**2),look_U)*180/math.pi,2)
37.92
```
Ok, the result "37.92" is very close to the "sbas" tool default value "37".

**Comment by Xiaohua-Eric-Xu** [comment]
Please continue if you have more questions/suggestions within this thread. We'll try to address them in the document.

**Comment by mobigroup** [comment]
Ok, thanks. I try to mention here every point to reproduce the document. GMTSAR SBAS processing is great but it’s hard to setup from scratch. Anyway, today that's easier than some years ago and I have no unresolving issues with GMTSAR scripts!

**Comment by mobigroup** [comment]
Yeah, I think that's all required to reproduce the document. See the resulting Mean Line-Of-Sight velocity from SBAS (mm/yr) below:

<img width="1280" alt="Screenshot 2021-08-17 at 17 04 47" src="https://user-images.githubusercontent.com/7342379/129706827-ecd5c917-b030-46f4-b3d3-01d9128e34ea.png">

**Comment by mobigroup** [comment]
On the picture above empty areas look strange because we have relatively high correlation stack values everywhere but I think that’s not related to the processing pipeline. Unfortunately, with bad coherence processing approach (masked low correlation areas on stack of results) the full coverage map producing but with large unreal values. Not sure if this way applicable on land with some rivers on it. The area is tectonically active and it can influence to the results.

**Comment by Nitheshnirmal** [comment]
> 

I have the same problem.
