### ISSUE TITLE
[Feature]: To document a set of ways to open GRD files

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#176]
It'd be nice to document more ways to operate on GRD files. Because GRD files are just NetCDF ones, we are able to open them directly in QGIS as simple as GeoTIFF files, use Python Xarray library, use GDAL tools (gdalinfo, gralwarp, and so on), use any of NetCDF processors like to tools from netcdf-bin, nco, cdo debian packages  to manipulate them.

**Comment by Xiaohua-Eric-Xu** [comment]
I personally use `ncview`.
