### ISSUE TITLE
[Feature]: Enhance documented automated download method using ASF API

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#177]
As documented in https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_3.pdf we need some script to download scenes from ASF (Alaska Satellite Facility). Fortunately, today ASF itself provides Python script for bulk downloading.

**Comment by Xiaohua-Eric-Xu** [comment]
I believe you could find some users' package from gmtsar/user-contributions.

**Comment by Xiaohua-Eric-Xu** [comment]
Yeah, maybe I am just a bit too outdated. I am still using a forloop with wget. [facepalm]

**Comment by mobigroup** [comment]
No problem, your esoteric script language is one of my reasons to use GMTSAR:)
