### ISSUE TITLE
[Bug]: Incomplete installation instructions on Wiki

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#179]
See https://github.com/gmtsar/gmtsar/wiki/GMTSAR-Wiki-Page
The installation commands are incomplete because "imagemagick" package required ("gs" utility, as minimum) for intf_tops.csh script and maybe some others. So we need to add
```
sudo apt install -y imagemagick                                                                                                                                    
```
where "apt install -y" (or aptitude install -y) allows automatic installation without some user prompt required.

**Comment by Xiaohua-Eric-Xu** [comment]
Yes. I believe that is required for GMT.

**Comment by Xiaohua-Eric-Xu** [comment]
I added this to the wiki:
The libraries below may require other libraries; use `sudo apt[-get] install -y` to automatically select `yes`.
