### ISSUE TITLE
[Bug]: Error "hermite: interpolation not in center interval" from preproc_batch_tops.csh for 12 lines of precise orbit

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#180]
With GMTSAR branch 6.1 on Debian 10 the command below for sub swaths F1 and F2 processed without errors but for F2 produced hermite errors with 12 orbit records:
```
preproc_batch_tops.csh data.in dem.grd 2
...
Reading in range and azimuth shifts table...                                                                                                                  
Working on burst  #1 #2                                                                                                                                       
number of points clipped to short int 0.                                                                                                                      
Reading in 5422 lines of info from XML...                                                                                                                     
Writing 17 lines for orbit...                                                                                                                                 
Writing SLC..Image Size: 25664 X 2796...                                                                                                                      
Writing 12 lines of precise orbit for the LED file...                                                                                                         
Successfully opened junk1.                                                                                                                                    
Reading in 5422 lines of info from XML...                                                                                                                     
Writing 17 lines for orbit...                                                                                                                                 
Writing 12 lines of precise orbit for the LED file...                                                                                                         
Shifting the master PRM by 0 lines...                                                                                                                         
Successfully opened junk1.PRM.                                                                                                                                
Successfully opened junk2.PRM.                                                                                                                                
hermite: interpolation not in center interval                                                                                                                 
hermite: interpolation not in center interval                                                                                                                 
hermite: interpolation not in center interval                                                                                                                 
hermite: interpolation not in center interval   
...
```

There are 17-18 lines for F1 and F3:
```
grep "LED file" preproc_batch_tops.log | sort| uniq 
Writing 17 lines of precise orbit for the LED file...
Writing 18 lines of precise orbit for the LED file...
```
and only 12 lines for F2:
```
grep "LED file" preproc_batch_tops.log | sort| uniq 
Writing 12 lines of precise orbit for the LED file...
```

Anyway, that should be enough. As discussed in ticket #22 "However, to do Hermite interpolation, you need 7 records at least." but we have much more above. Also, the difference in available orbit records between F1,F3 and F2 looks strange for me. In addition, I can't miss F2 because I need only it one actually.

**Comment by dsandwell** [comment]
Check that the orbit file spans the image file times.  I believe this is on the edge and one of the subswaths is longer. 
I Saw your other messages about the time series documentation.  We can clarify that the master should be the same for all three sub swaths, etc.


> On Aug 15, 2021, at 7:49 AM, Alexey Pechnikov ***@***.***> wrote:
> 
> 
> With GMTSAR branch 6.1 on Debian 10 the command below for sub swaths F1 and F2 processed without errors but for F2 produced hermite errors with 12 orbit records:
> 
> preproc_batch_tops.csh data.in dem.grd 2
> ...
> Reading in range and azimuth shifts table...                                                                                                                  
> Working on burst  #1 #2                                                                                                                                       
> number of points clipped to short int 0.                                                                                                                      
> Reading in 5422 lines of info from XML...                                                                                                                     
> Writing 17 lines for orbit...                                                                                                                                 
> Writing SLC..Image Size: 25664 X 2796...                                                                                                                      
> Writing 12 lines of precise orbit for the LED file...                                                                                                         
> Successfully opened junk1.                                                                                                                                    
> Reading in 5422 lines of info from XML...                                                                                                                     
> Writing 17 lines for orbit...                                                                                                                                 
> Writing 12 lines of precise orbit for the LED file...                                                                                                         
> Shifting the master PRM by 0 lines...                                                                                                                         
> Successfully opened junk1.PRM.                                                                                                                                
> Successfully opened junk2.PRM.                                                                                                                                
> hermite: interpolation not in center interval                                                                                                                 
> hermite: interpolation not in center interval                                                                                                                 
> hermite: interpolation not in center interval                                                                                                                 
> hermite: interpolation not in center interval   
> ...
> 
> There are 17-18 lines for F1 and F3:
> 
> grep "LED file" preproc_batch_tops.log | sort| uniq 
> Writing 17 lines of precise orbit for the LED file...
> Writing 18 lines of precise orbit for the LED file...
> 
> and only 12 lines for F2:
> 
> grep "LED file" preproc_batch_tops.log | sort| uniq 
> Writing 12 lines of precise orbit for the LED file...
> 
> Anyway, that should be enough. As discussed in ticket #22 "However, to do Hermite interpolation, you need 7 records at least." but we have much more above. Also, the difference in available orbit records between F1,F3 and F2 looks strange for me. In addition, I can't miss F2 because I need only it one actually.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by mobigroup** [comment]
Thanks, that's so interesting idea! I'll check it of course.

**Comment by mobigroup** [comment]
Yes, the selected area is located on left edge of the F2 (close to F3). With a little bit larger area (extended to F1) the issue fixed. So the recipe is easy and we don't need to process a large pinned area instead.

On increased pinned area from "48.1 37.9 48.0 38.15" (in the case above) to "48.1 37.9 48.0 38.2" (only one coordinate changed from 38.15 to 38.2) for F2 we have a lot of orbits now:
```
grep "LED file" preproc_batch_tops.log | sort| uniq                                                                      
Writing 17 lines of precise orbit for the LED file...
Writing 18 lines of precise orbit for the LED file...
Writing 23 lines of precise orbit for the LED file...
Writing 24 lines of precise orbit for the LED file...
```
without hermite errors.

**Comment by mobigroup** [comment]
The solution is founded and described above.
