### ISSUE TITLE
[Bug]: SAT_look returns different elevation

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#183]
The utility returns the input lat, lon and different elevation value (output 1088.206383 vs input 1481):
```
echo 48.075 38.058 1481 | SAT_look S1_20210108_ALL_F2.PRM
48.075000 38.058000 1088.206383 -0.604911 -0.109079 0.788787
```

**Comment by Xiaohua-Eric-Xu** [comment]
Well, it is not a bug first. The elevation is replaced with a number that's a height above the reference radius (you can find this in PRM files).

**Comment by mobigroup** [comment]
Ah, nice, that can be useful for some cases. Would be great to note it in the SAT_look help output.

**Comment by Xiaohua-Eric-Xu** [comment]
Added a description 1fd1563389d9e6293875639aa9a1e3e3a12553c1
