### ISSUE TITLE
[Bug]: SAT_look return different results for sub swaths tops/master.PRM

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#186]
```
$ cd /mnt/GMTSAR/asc/F1/topo && echo 48.050000 38.050000 1542.20397949219 | SAT_look master.PRM
48.050000 38.050000 1161.508600 -0.603019 -0.108981 0.790247

$ cd /mnt/GMTSAR/asc/F2/topo && echo 48.050000 38.050000 1542.20397949219 | SAT_look master.PRM
48.050000 38.050000 1152.312381 -0.603019 -0.108981 0.790247

$ cd /mnt/GMTSAR/asc/F3/topo && echo 48.050000 38.050000 1542.20397949219 | SAT_look master.PRM
48.050000 38.050000 1143.383570 -0.603019 -0.108981 0.790247
```

Why does it return 3 different values ~1161, 1152, 1143 for the exactly same point (and the same master image)? As I see "earth_radius" and other parameters are different for sub swaths... these are very interesting differences.

**Comment by Xiaohua-Eric-Xu** [comment]
Like I mentioned in earlier issues, the new elevation is with regard to the reference radius in the PRM file. The reference radius is based on the local value of the data. The 3 subswaths apparently cover different part of the earth surface and thus their reference radius will be different. You could easily do triangulation with (SC_height + earth_radius), (elevation + earth_radius) the range of the pixel. The three should be consistent.

**Comment by mobigroup** [comment]
Thanks, got it.
