### ISSUE TITLE
[Feature]: Note way DEM downloading in command-line vs web service

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#187]
The recommended way to obtain DEM is this service usage: https://topex.ucsd.edu/gmtsar/demgen/
Instead of it we are able to use "elevation" Python package for console SRTM1 and SRTM3 DEM downloading:
```
python3 -m pip install elevation                                                                                                                  
eio selfcheck
eio --product SRTM3 clip -o /mnt/dem.tif --bounds 46.4 37.3 49.9 39.6
gdal_translate -of NetCDF -ot Float32 -co FORMAT=NC4C -co COMPRESS=DEFLATE -co ZLEVEL=3 /mnt/dem.tif /mnt/dem.grd
```

gdal_translate produces NetCDF recognised by GMT tools. Lets compare the original web DEM:
```
# gmt grdinfo dem.grd
dem.grd: Title: Produced by grdmath
dem.grd: Command: grdmath dem_ortho.grd egm96.grd ADD = dem.grd
dem.grd: Remark: 
dem.grd: Gridline node registration used [Geographic grid]
dem.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
dem.grd: x_min: 46.4 x_max: 49.9 x_inc: 0.000833333333333 name: longitude [degrees_east] n_columns: 4201
dem.grd: y_min: 37.3 y_max: 39.6 y_inc: 0.000833333333333 name: latitude [degrees_north] n_rows: 2761
dem.grd: z_min: -109.568283081 z_max: 4750.48828125 name: z
dem.grd: scale_factor: 1 add_offset: 0
dem.grd: format: netCDF-4 chunk_size: 132,132 shuffle: on deflation_level: 3
```
and the console-produced one:
```
gmt grdinfo /mnt/dem.grd
/mnt/dem.grd: Title: GDAL Band Number 1
/mnt/dem.grd: Command: Wed Aug 18 06:33:53 2021: GDAL CreateCopy( /mnt/dem.grd, ... )
/mnt/dem.grd: Remark: 
/mnt/dem.grd: Pixel node registration used [Geographic grid]
/mnt/dem.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
/mnt/dem.grd: x_min: 46.4004166667 x_max: 49.8995833333 x_inc: 0.000833134920635 name: longitude [degrees_east] n_columns: 4200
/mnt/dem.grd: y_min: 37.3 y_max: 39.6 y_inc: 0.000833333333333 name: latitude [degrees_north] n_rows: 2760
/mnt/dem.grd: z_min: 0 z_max: 0 name: GDAL Band Number 1
/mnt/dem.grd: scale_factor: 1 add_offset: 0
/mnt/dem.grd: format: netCDF-4 chunk_size: 4200,1 shuffle: on deflation_level: 3
```

**Comment by Xiaohua-Eric-Xu** [comment]
We tend not to hard-code these into the scripts as these are really user choices. One could choose to get DEM from DLR or NASA or JAXA or our free service https://topex.ucsd.edu/gmtsar/demgen/. You may also note that the console produced one has 0 z_min and z_max, which means it's a flat zero plane.

**Comment by mobigroup** [comment]
> You may also note that the console produced one has 0 z_min and z_max, which means it's a flat zero plane.

It just means grdinfo reads the statistics from tags but doesn’t calculate it. “gdalinfo -stats” returns the correct z interval here.

**Comment by mobigroup** [comment]
Sure, there is no the silver bullet although this way is helpful as part of an automatic pipeline.

**Comment by Xiaohua-Eric-Xu** [comment]
Many users could automate the process with some scripting, as most core modules are already there. e.g. https://github.com/gmtsar/user-contributions/tree/main/automate-gmtsar . Usually DEM is not of much difficulty to get and for a certain area, you only need to generate once for the entire stack of data. You may also note that the new GMT allows you to get DEM from their server as well http://gmt.soest.hawaii.edu/doc/latest/datasets.html. But one probably need to convert it to above ellipsoid.

**Comment by mobigroup** [comment]
Could you specify the DEM version used on your DEM web service? I see some differences in about 30 m for z values between the same SRTM3 DEMs (where Python extractor uses SRTM 90m Digital Elevation Database v4.1). The service (https://topex.ucsd.edu/gmtsar/demgen/) returns DEM with z statistics below:
```
    STATISTICS_MAXIMUM=4750.48828125
    STATISTICS_MEAN=908.10375243864
    STATISTICS_MINIMUM=-109.56828308105
```
and see the same statistics for the Python DEM extractor: 
```
    STATISTICS_MAXIMUM=4788
    STATISTICS_MEAN=938.87518478266
    STATISTICS_MINIMUM=-74
```
The Python DEM:
```
$ gdalinfo -stats /mnt/dem.grd
...
Corner Coordinates:
Upper Left  (  46.4000000,  39.6000000) ( 46d24' 0.00"E, 39d36' 0.00"N)
Lower Left  (  46.4000000,  37.3000000) ( 46d24' 0.00"E, 37d18' 0.00"N)
Upper Right (  49.9000000,  39.6000000) ( 49d54' 0.00"E, 39d36' 0.00"N)
Lower Right (  49.9000000,  37.3000000) ( 49d54' 0.00"E, 37d18' 0.00"N)
Center      (  48.1500000,  38.4500000) ( 48d 9' 0.00"E, 38d27' 0.00"N)
Band 1 Block=4200x1 Type=Float32, ColorInterp=Undefined
  Minimum=-74.000, Maximum=4788.000, Mean=938.875, StdDev=878.661
  NoData Value=nan
  Metadata:
    grid_mapping=crs
    long_name=GDAL Band Number 1
    NETCDF_VARNAME=Band1
    STATISTICS_MAXIMUM=4788
    STATISTICS_MEAN=938.87518478266
    STATISTICS_MINIMUM=-74
    STATISTICS_STDDEV=878.66059852403
    STATISTICS_VALID_PERCENT=100
    _FillValue=nan
```

Web DEM:
```
Corner Coordinates:
Upper Left  (  46.3995833,  39.6004167) 
Lower Left  (  46.3995833,  37.2995833) 
Upper Right (  49.9004167,  39.6004167) 
Lower Right (  49.9004167,  37.2995833) 
Center      (  48.1500000,  38.4500000) 
Band 1 Block=4201x1 Type=Float32, ColorInterp=Undefined
  Min=-109.568 Max=4750.488 
  Minimum=-109.568, Maximum=4750.488, Mean=908.104, StdDev=877.880
  NoData Value=nan
  Metadata:
    actual_range={-109.5682830810547,4750.48828125}
    long_name=z
    NETCDF_VARNAME=z
    STATISTICS_MAXIMUM=4750.48828125
    STATISTICS_MEAN=908.10375243864
    STATISTICS_MINIMUM=-109.56828308105
    STATISTICS_STDDEV=877.87977251598
    _FillValue=nan
```

**Comment by Xiaohua-Eric-Xu** [comment]
I suspect that you got DEM above geoid, right? For the software we need DEM above ellipsoid. There was a EGM96 grid added as you may have seen.

**Comment by mobigroup** [comment]
Thanks for the notice, but EGM96 correction ~10 m for the area when we have much larger difference:

SRTM3 from https://topex.ucsd.edu/gmtsar/demgen/
```
gdallocationinfo -geoloc -valonly dem.grd 48.0561 38.0700
1562.22106933594
```
EGM96 15 min geoid model
```
gdallocationinfo -geoloc -valonly egm96-15.tif 48.0561 38.0700
13.0480003356934
```
ALOS DEM 30m
```
gdallocationinfo -wgs84 -valonly ALOS.DSM.30m.32639.nc 48.0561 38.0700
1599
```
SRTM 90m Digital Elevation Database v4.1
```
gdallocationinfo -geoloc -valonly dem.tif 48.0561 38.0700
1597
```

And it's not related to GDAL tools because with GMT we still have almost the same elevation on dem.grd:
```
echo "48.0561 38.0700" > track.xy && gmt grdtrack track.xy -Gdem.grd -h
48.0561	38.07	1560.48173199
```

**Comment by Xiaohua-Eric-Xu** [comment]
Not sure
```
xix016% echo 48.0561 38.0700 | gmt grdtrack -G/palsar/DEM/SRTM1/geoid.egm96.grd
48.0561	38.07	-37.7790307757
```

**Comment by mobigroup** [comment]
Ok, please check https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html
For the coordinates "48.0561,38.0700,1597"  (SRTM 90m height) and geoid EGM96-5 we have:
|Latitude	|Longitude	|Ellps Height (m)	|Geoid Height (m)	|Ortho Height (m)|
---------|-------------|------------------|------------------|-----------------|
|	48.0561	|38.07	|1597	|20.68	|1576.32|

The difference is larger but it's still too small.

**Comment by Xiaohua-Eric-Xu** [comment]
You caught this bug!! Thanks a lot!!!
I think I find out why. This EMG96 file from our site got re-generated March this year (Maybe there was some mistake made running GMT). And looks like it got swapped somehow. Do you mind to give it another try through our site?
![image](https://user-images.githubusercontent.com/16844111/130124638-2fa3e2b2-a289-4398-b070-648cbecfec43.png)

**Comment by mobigroup** [comment]
Ok, nice! On the pictures we see coordinates in range [0,360] on upper picture and in range[-180,180] on the bottom one.
```
# SRTM3 from https://topex.ucsd.edu/gmtsar/demgen/
gdallocationinfo -geoloc -valonly dem.grd 48.0561 38.0700
1612.90356445312

# EGM96 15 min geoid model
gdallocationinfo -geoloc -valonly egm96-15.tif 48.0561 38.0700
13.0480003356934

# SRTM 90m Digital Elevation Database v4.1
gdallocationinfo -geoloc -valonly dem.tif 48.0561 38.0700
1597

# ALOS DEM 30m
gdallocationinfo -wgs84 -valonly ALOS.DSM.30m.32639.nc 48.0561 38.0700
1599
```
Check the differences:
1612.90356445312-13.0480003356934-1597=2,9 (webbem-EGM96-SRTM3)
1612.90356445312-13.0480003356934-1599=0,9 (webbem-EGM96-ALOS)

Yes, that's correct now. The small differences related to different approaches to calculate pixel coordinates on a grid by GMT and GDAL.

**Comment by mobigroup** [comment]
See the residuals between SRTM3 v4.1 plus EGM96 15 min minus your web dem.grd (on the same grid):
```
float((srtm3+egm96-webdem).max()), float((srtm3+egm96-webdem).min())
(194.92997673360514, -258.07740645257627)
```
<img width="641" alt="image" src="https://user-images.githubusercontent.com/7342379/130201933-93b5e115-2164-4c98-8f9b-a7956cb4569d.png">

I think you still use older SRTM3 version with the artefacts visible on the picture above.

**Comment by Xiaohua-Eric-Xu** [comment]
@dsandwell maybe we could update the SRTM on /palsar?
