### ISSUE TITLE
[Feature]: document selection of baselines for select_pairs.csh

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#188]
How about some ways to estimate the results correctness using the calculations with different parameters? Probably we have more accurate results for more pairs... it’s not documented although it looks obvious. For my tests the changes amplitude smaller for more pairs and it looks correct. But will be better to use 150 m perpendicular baseline and 90 days temporal one then 120 m and 50 days? Some publications offer good results for perpendicular baseline 150-200 m and temporal baseline up to 3 months (and even more for some areas). But maybe sometimes larger baselines values produce wrong results? How to estimate the right values? How to check the results to be sure the results are correct? It’d be great to know some practical recipes!

**Comment by mobigroup** [comment]
The same questions would be asked about decimation and pinned area size influence to the results accuracy.

**Comment by Xiaohua-Eric-Xu** [comment]
This is a user choice. I could not convince others that my way is the best. If you find out the optimal way of selecting these numbers, you should publish a paper on that.

**Comment by mobigroup** [comment]
Eric, maybe do you have some suggestions how to compare different results? Or maybe just some ideas about parameters sets and their order to check? Actually, how could we apply grid search method for GMTSAR parameters optimization?

**Comment by Xiaohua-Eric-Xu** [comment]
I do not suggest to do grid search on these parameters, especially considering that you need to define what is good first. One critical comparison to make is to the GNSS data. Usually this is the ground truth to tell whether what you did is valid. However, we've seen cases where GNSS data match the trend but having different seasonal.  Or sometimes the trend does not match well either.

**Comment by mobigroup** [comment]
Ok, understand, but how about many areas without GNSS data? That’s a common case I think.

**Comment by Xiaohua-Eric-Xu** [comment]
I don't think there's an easy answer to that. How do you know what you measured is the truth? Considering all those noise terms, troposphere, ionosphere, phase ambiguity, decorrelation, ......

**Comment by mobigroup** [comment]
We've found the way in #194
