### ISSUE TITLE
[Bug]: SBAS velocity map values are too different for different master images

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#189]
There is a huge difference between velocity map calculated by masters 20210402 and 20210601 marked on the baseline below:

![baseline small](https://user-images.githubusercontent.com/7342379/129876959-ef5de51b-8d2b-46f8-83ab-bd5ed39eefc8.jpg)

I've checked velocity maps for two points around a dam and the values are [21, -16] for 20210402 master image and [1, -33] for 20210601 master image. Please pay attention 1-21=-20 and -33-(-16)=-17 so the changes are almost equal but absolute values are different.

Also, the cumulative map of all disp_*_ll.grd images have total displacement [265, -127] for the same points for the 20210601 master image. See below the displacement series for the points:

<img width="819" alt="image" src="https://user-images.githubusercontent.com/7342379/129881118-365b3483-01d1-4f82-af76-e740cad420d4.png">

Note: there are monthly or even weekly earthquakes M2-M3 around the area. Stacked correlation map values are in range 0.4-0.6 for the points. I'm not sure if it's a real SMTSAR processing bug but the both master image dates look ok and the difference is strange I think.

**Comment by Xiaohua-Eric-Xu** [comment]
What's the sbas command you ran for each case. The second one seems having stronger smoothness.

**Comment by Xiaohua-Eric-Xu** [comment]
Please send your intf.tab and scene.tabs, together with the commands you ran for sbas.

**Comment by mobigroup** [comment]
The results above obtained without atmosphere correction (-atm 0) and for now I've got different results with the correction (-atm 3):
```
sbas intf.tab scene.tab 91 17 3208 2070 -range 875364 -incidence 37.777 -wavelength 0.0554658 -rms -dem -atm 3 -smooth 5.0
```
[scene.tab.txt](https://github.com/gmtsar/gmtsar/files/7011822/scene.tab.txt)
[intf.tab.txt](https://github.com/gmtsar/gmtsar/files/7011823/intf.tab.txt)
The velocity map is very sparse here:
![vel_ll](https://user-images.githubusercontent.com/7342379/130010965-0bbb5249-e2d9-40b0-825e-ca8dec575bf5.png)

If it's helpful I can recalculate the results above.

**Comment by mobigroup** [comment]
With the atm correction I see new output in SBAS script log:
```
Applying atmospheric phase screen to original unwrapped phase...                                                                                              
Setting smoothing parameter to 5.000000...                                                                                                                    
Memory Allocation Successful...                                                                                                                               
read table file ...                                                                                                                                           
read phase and correlation grids ...                                                                                                                          
5.000000 0.000422 0.000000 -37.924999                                                                                                                         
fill the G matrix ...                                                                                                                                         
run least-squares problem over 3208 by 2070 pixel (0) ...                                                                                                     
matrix is full rank: 17                                                                                                                                       
                                                                                                                                                              
fill the G matrix ...                                                                                                                                         
run least-squares problem over 3208 by 2070 pixel (0) ...                                                                                                     
matrix is full rank: 17                                                                                                                                       
                                                                                                                                                              
fill the G matrix ...                                                                                                                                         
run least-squares problem over 3208 by 2070 pixel (0) ...                                                                                                     
matrix is rank-deficient: 7                                                                                                                                   
                                                                                                                                                              
fill the G matrix ...                                                                                                                                         
run least-squares problem over 3208 by 2070 pixel (13) ...                                                                                                    
matrix is rank-deficient: 16     
```

Before (with -atm=0) it usually was "matrix is rank-deficient: 16". This message is unpredictable for me as it looks as random choice between "matrix is full rank: 17 " and "matrix is rank-deficient: 16".

**Comment by Xiaohua-Eric-Xu** [comment]
The -atm uses a common scene stacking method from Tymofyeyeva & Fialko 2015, implemented here with Xu et al., 2017. The methods sort of acts as a median filter (not exactly) that absorbs turbulent component in the time-series. It works well when you have dense sampling long time-series, not as well around at the ends (beginning or end of the time series, as the constraints are one sided).

**Comment by mobigroup** [comment]
Thanks, I checked the paper and with the selected baseline parameters we have a lot of triangles for the estimation:
![baseline (4)](https://user-images.githubusercontent.com/7342379/130011890-3ab9c50b-985e-4895-90c0-e10c9f5641fb.jpg)

**Comment by mobigroup** [comment]
Also, the SBAS command is the same for the cases with masters 20210402 and 20210601 above. The only difference is the master image selection.

**Comment by mobigroup** [comment]
Probably unwrapping is unstable due to high noise levels:
![phasefilt_unwrap](https://user-images.githubusercontent.com/7342379/130033448-a2c95bef-4cbf-4d8a-a93f-fbd9e145cd6c.jpg)

See below the best one interferogram from the series:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/7342379/130046036-5c87322b-deb6-420c-9fdb-2eda295557ec.png">

Here is wooded slope on the right. Unfortunately, I can't minimise the processing area because there are not enough orbits in this case.

**Comment by mobigroup** [comment]
Maybe the full series will be more informative, see below. The unwrapping results (here DEFOMAX=3 although it look similar to DEFOMAX=0... so I think we already have the issue before on the filtered interferograms) looks better but filtered phase images are too noisy:
![phasefilt_grid small](https://user-images.githubusercontent.com/7342379/130077117-6acc8b36-dae8-4858-92a3-1bd901a3ffb2.jpg)
![unwrap_grid small](https://user-images.githubusercontent.com/7342379/130077127-ca9804c2-ceed-429e-8c19-8d46ee9eb94c.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
I am suspecting phase unwrapping. Theoretically there should be only very small difference between the interferograms, 1e-2mm-ish, from the phase closure test we did. I assume that by choosing a different master image, this could be the difference you are expecting. If this is the cause of shifting a few residues and then unwrapping gets you slightly different result, then yes, maybe it is from phase unwrapping.

**Comment by Xiaohua-Eric-Xu** [comment]
However, the time-series you posted look dramatically different. I think it could be from ambiguities in unwrapped phase (e.g. 2pi shift of the entire scene). If you pin a position to zero in the map, it may help get rid of those ambiguities.

**Comment by mobigroup** [comment]
> If you pin a position to zero in the map, it may help get rid of those ambiguities.

Sorry, I don't understand. Could you explain how to do it?

**Comment by Xiaohua-Eric-Xu** [comment]
1) grdcut a small area (to be pinned) from your unwrapped phase.
2) grdinfo that file (-L2) to get mean value.
3) grdmath to subtract the value from the the unwrapped phase.
4) repeat for all unwrapped phase grids.

**Comment by mobigroup** [comment]
Ah, you mean we need to define a persistent point for all the interferogram pairs. Maybe do you have some idea how to find it?

**Comment by Xiaohua-Eric-Xu** [comment]
I don't remember whether they were discussed in these earlier papers. Probably they did. 
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=1166596
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2002JB002267
Sometimes people select GCPs similar to what is done for optical images.

**Comment by mobigroup** [comment]
Thanks, as I see this way supposes small displacements for just millimeters per year. Maybe we are able to adopt the persistent scatters method for our requirements.

I'm still not sure that I understand correct your idea about pinning a position to zero in the map. Does it mean we suppose zero movements for the pinned area and so we detecting only relative movements around this point? I think that'd be better to exclude influence of edge areas... but unwapping with mask still ignores the mask. I've selected even very sparse mask for the test (marked as red areas on the picture below):
<img width="1280" alt="Screenshot 2021-08-21 at 14 07 08" src="https://user-images.githubusercontent.com/7342379/130314423-7dce58c9-8386-4e25-9f1e-8f1065389145.png">
but for this filtered phase:
<img width="523" alt="Screenshot 2021-08-21 at 14 56 54" src="https://user-images.githubusercontent.com/7342379/130314994-e40fdca6-8932-4a67-a3e7-5a7e52dc20c5.png">
we still have very large unwrap phase values so the edge anomalies calculated too:
<img width="592" alt="Screenshot 2021-08-21 at 14 55 01" src="https://user-images.githubusercontent.com/7342379/130315000-b10f2813-a5a9-4da0-9a8c-6ce583257ae6.png">

Is there any way to fix it? Sure, we need some way to exclude low-coherence areas but we can't do it by the defined mask...

**Comment by mobigroup** [comment]
Ok, I've found the issue, see #193

**Comment by mobigroup** [comment]
For now, the mask applied:
![2D4BDD49-E910-4B0E-97C3-563EEA043D70](https://user-images.githubusercontent.com/7342379/130317272-fad7d9eb-0de3-4b4c-993b-5e73c5cb85bc.jpeg)
And we still see too large unwrapped range [-4, 16] although on the phase image above for the masked area we can see just a few phase circles. Looks as snaphu accounting too small noisy pixels…

**Comment by Xiaohua-Eric-Xu** [comment]
The pin means your measurement is referenced from that position. In other words, the motion is relative to that point.

**Comment by mobigroup** [comment]
Thanks, now I see how it's related to phase unwrapping but not SBAS.
