### ISSUE TITLE
ERS_SLC or ENVI_SLC for SBAS 

### ISSUE THREAD

**Issue by simonst7** [gmtsar/gmtsar#19]
Dear Xiaohua(Eric):
 I want to process ENVI_SLC and ERS_SLC for interseismic periods in Mejillones Peninsula, Chile, with time-series SBAS method. In GMTSAR there is only the option to make Sentinel 1, ALOS_SLC, ENVI or ERS, but for SLCs not working. How do I make this possible?

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Simonst7,
I attached an email reply to a similar problem. I believe it's the one you are dealing with. Before alignment, you could use ENVI_pre_process/envi_slc_decode to get the data extracted. And after alignment, you can use intf_tops.csh to produce interferograms or produce topo_ra.grd and then just repeatedly call p2p_processing from step 4.
Cheers,
Xiaohua(Eric)


Hi Koorosh,

We are kind of slow on this as most people turned to Sentinel-1 these days.

The coregistration of SLC product is fairly simple in GMTSAR. Mainly it follows the following steps. 

A) imagine you have two images $master and $slave

1) xcorr to get the shift parameters
xcorr $master.PRM $slave.PRM -xsearch 128 -ysearch 128 -nx 20 -ny 50

2) get coregistration parameters from the xcorr results (you can use different number of parameters, the default is 2,2, chose 3 3 for a better coregistration)
fitoffset.csh 2 2 freq_xcorr.dat 18 >> $slave.PRM

3) resample the slave image to perform coregistration
resamp $master.PRM $slave.PRM $slave.PRMresamp $slave.SLCresamp 4

4) rename the files before the next step (interferometry)
rm $slave.SLC
mv $slave.SLCresamp $slave.SLC
cp $slave.PRMresamp $slave.PRM


B) For ENVISAT, sometimes the baseline is too big and you have to perform secondary alignment just like for ALOS data. You could simply achieve this with performing the steps above 
First, between $master and $secondary_master and then between $secondary_master and $slave. After that, perform interferometry between $secondary_master and $slave

You can always perform B) to achieve a better coherence. 

Cheers,
Xiaohua(Eric)

On Mar 21, 2020, at 8:43 PM, Koorosh Parsa <nghayour@gmail.com> wrote:

Dear  Xiaohua Xu,
Greetings from Koorosh.
I hope you are doing well.
Thank you very much for providing the nice software of GMTSAR.
 
I preprocessed ENVISAT SLC's using pre_proc_batch.csh ENVI_SLC data.in batch.config command. 
The process created .LED, .PRM, .SLC files for all images along with baseline information files.
I encountered an issue trying to align those images using align_batch.csh ENVI align.in command. As there is no ENVI_SLC option for align_batch.csh, 
I used ENVI as SAT. Error is pasted below. The same error repeats for all images. 
In the SLC folder, I do not see any SLC files (SLC files from /raw are not copied to /SLC) and the links to raw files appears broken as there are no raw files available in /raw. 

clean up SLC/ folder

START ALIGN A STACK OF IMAGES

Align ASA_IMS_1PNESA20040429_052253_000000182026_00234_11310_0000 to ASA_IMS_1PNESA20031211_052255_000000182022_00234_09306_0000 via ASA_IMS_1PNESA20031211_052255_000000182022_00234_09306_0000 - START
focussing master
Can't open file ASA_IMS_1PNESA20031211_052255_000000182022_00234_09306_0000.SLC
align.csh
focusing slave
Can't open file ASA_IMS_1PNESA20040429_052253_000000182026_00234_11310_0000.SLC
align.csh
correlate master and slave to find offset parameters
 setting xsearch to 64
 setting nx_corr to 128
 setting ysearch to 64
 setting ny_corr to 128
 Cannot open SLC_file ASA_IMS_1PNESA20031211_052255_000000182022_00234_09306_0000.SLC 
mv: cannot stat 'ASA_IMS_1PNESA20040429_052253_000000182026_00234_11310_0000.SLC': No such file or directory
freq_xcorr.dat: No such file or directory.
freq_xcorr.dat: No such file or directory.
wc: freq_xcorr.dat: No such file or directory
wc: r.xyz: No such file or directory
mv: cannot stat 'freq_xcorr.dat': No such file or directory
align.csh
refocus slave
Can't open file ASA_IMS_1PNESA20040429_052253_000000182026_00234_11310_0000.SLC
rm: No match.
rm: No match.
Align ASA_IMS_1PNESA20040429_052253_000000182026_00234_11310_0000 to ASA_IMS_1PNESA20031211_052255_000000182022_00234_09306_0000 via ASA_IMS_1PNESA20031211_052255_000000182022_00234_09306_0000 - END

I know a person already asked about the above-mentioned problem in the GMTSAR forum
and you answered:
"The align_batch.csh code currently only works with raw data. There are similar code for ALOS_SLC in the distribution, but we haven't put together everything and create a final script. If you want to create a batch script for ENVI_SLC, the align_batch_ALOS_SLC.csh might be the one to follow."
But I couldn't modified align_ALOS_SLC.csh.
Could you send me the modified align_ALOS_SLC.csh to align ENVISAT SLC's.

Best rgards.
Koorosh

**Comment by simonst7** [comment]
Thank Xiaohua!, I'll try that solution
