### ISSUE TITLE
[Bug]: SBAS processing ignores dec_factor = 1

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#192]
This configuration in batch_tops.config produces the same results as with "dec_factor = 2" on the pipeline from sentinel_time_series_3.pdf:
```
# decimation of images.                                                                                                                                       
# decimation control the size of the amplitude and phase images. It is either 1 or 2.                                                                         
# Set the decimation to be 1 if you want higher resolution images.                                                                                            
# Set the decimation to be 2 if you want images with smaller file size.                                                                                       
#                                                                                                                                                            
dec_factor = 1                                                                                                                                                
# for tops processing, to force the decimation factor                                                                                                         
# recommended range decimation to be 8, azimuth decimation to be 2                                                                                            
range_dec = 8                                                                                                                                                 
azimuth_dec = 2 
```

**Comment by mobigroup** [comment]
SBAS command options are the same (see xdim and ydim) for "dec_factor = 1" and "dec_factor = 2":
```
sbas intf.tab scene.tab 58 17 3208 2068 -range 875364 -incidence 37.777 -wavelength 0.0554658 -rms -dem -atm 3 -smooth 5.0
```

**Comment by Xiaohua-Eric-Xu** [comment]
When you are about to run `sbas`, we assume you have reached the stage where you have a stack of coregistered, decimated, filtered, unwrapped phase/coherence grids. Then why the dec_factor an issue for `sbas`? 
The dec_factor will compute decimation based on the filter_wavelength. However, if range_dec and azimuth_dec is specified, they'll overwrite the computed decimation. This is mainly to force a fixed decimation when you have multiple subswaths data, as you know, the range pixel size changes with range.

**Comment by mobigroup** [comment]
Maybe my explanation is bad. I mean with the defined decimation for the entire processing we have the same results. The logged SBAS command shows the grid sizes are the same with and without decimation. By other words, the option “dec_factor = 1” ignored completely and we can’t get a higher resolution images with it. We always need to define instead
range_dec = 1
azimuth_dec = 1

**Comment by Xiaohua-Eric-Xu** [comment]
Well, it depends whether you want to do things at full resolution. Setting them to 1 will costs much longer to process.

**Comment by Xiaohua-Eric-Xu** [comment]
For a large scale analysis, I usually use 16/4.

**Comment by mobigroup** [comment]
By this way, we need to exclude the option “dec_factor” because it’s no-op, right? We can change it but no effect.

**Comment by mobigroup** [comment]
Also,

> For a large scale analysis, I usually use 16/4.

And you have very different unwrapped phase values, right? That’s very hard to interpret the results for different decimations.

**Comment by Xiaohua-Eric-Xu** [comment]
> By this way, we need to exclude the option “dec_factor” because it’s no-op, right? We can change it but no effect.

If you don't specify range_dec and azimuth_dec, it'll take effect. Try one of our ERS or ALOS examples.

**Comment by Xiaohua-Eric-Xu** [comment]
> And you have very different unwrapped phase values, right? That’s very hard to interpret the results for different decimations.

Not really. I think you misunderstood something here. Phase unwrapping is only adding or subtracting multiple 2pis to the pixels. If you add or subtract 2pi from the solution, it is still a valid solution. This is also a reason why people think InSAR is a relative measurement.

**Comment by mobigroup** [comment]
Adding but not multiplication of course. Changing decimation range 8 times is equal to multiplication the unwrapped phase by coefficient 1/2 in other ticket. How do you think it’s related to theory? Relative unwrapped phase difference between to points should be constant by the theory but snaphu differences are not constant.

**Comment by mobigroup** [comment]
> If you don't specify range_dec and azimuth_dec, it'll take effect. Try one of our ERS or ALOS examples.

Oh, thanks. This dependence is not intuitive for me because the option looks as a way to disable decimation by a single parameter instead of changing the both ange_dec and azimuth_dec... de-facto, we need to change 3 parameters instead of two (disable range_dec and azimuth_dec and change dec_factor too).
