### ISSUE TITLE
[Bug]: snaphu_interp.csh does not actually check for mask_def.grd (and landmask_ra.grd too)

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#193]
See the code:
```
cat snaphu_interp.csh
...
#
# create landmask
#
if (-e landmask_ra.grd) then
...
#
# user defined mask.
#
if (-e mask_def.grd) then
...
```
It doesn't work as expected because:
```
man [
     -e file       True if file exists (regardless of type).

     -f file       True if file exists and is a regular file.
```
So "-e" returns ok for broken links! It should be used -"f" flag instead. When I've linked the mask from directory above but my processing directory is linked to "merge" from "F2" the mask file link is broken but snaphu_interp.csh does not detect the issue and continue processing without mask. This behaviour is hard to detect.

**Comment by mobigroup** [comment]
That'd be nice to break the script execution with an error for the case when the mask file exists but it's not readable. Also, that's better to revert the checks:
```
if (-e landmask_ra.grd) then
  if ($#argv == 3 ) then.
...
```
because the file must exists when we defined it in the script arguments. For now the script executes anyway with unpredictable results.

**Comment by mobigroup** [comment]
I mean this code instead:
```
if ($#argv == 3 ) then
    if (-f mask_def.grd) then
         ...ok...
    else
         ...fail....
    endif
endif
```
By this way we don't allow undefined behaviour in the processing.

**Comment by Xiaohua-Eric-Xu** [comment]
I could change it to `-f`. For the failure cases, what if the user does not want to use landmask?

**Comment by mobigroup** [comment]
There are some different ways for optional arguments processing:

1. Use placeholder like to “none”

scriptname … none mask.grd

2. Use named arguments like to 

scriptname … -mask mask.grd

3. Use environment variables like to

GMTSAR_LANDMASK= GMTSAR_MASK=mask.grd scriptname …

All the ways are good enough for users and debugging and they are very common.
