### ISSUE TITLE
[Bug]: nearest_grid is much slowly than snaphu

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#198]
This command requires ~30 minutes to complete
```
nearest_grid phase_tmp.grd tmp.grd 300
```
when snaphu requires just 2 minutes. Is it just a grid nearest neighbourhood interpolation utility? I use it for subswaths F23 when F3 (right on the picture below) is almost fully cropped by landmask. For the separate sub swath F2 (left on the picture below) without ocean area there is no the problem.

![unwrap_12pct](https://user-images.githubusercontent.com/7342379/130671601-a7403959-eda7-4a05-8888-9a0e7b2f1ffb.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
I think we need a description here in the document. The nearest_grid.c works really fast under certain cases, but is slow when there is large vacant areas in the map. In that case, the grid_data in MATLAB actually runs faster.

**Comment by mobigroup** [comment]
Yes, I see. How about the fast GDAL alternative gdal_fillnodata.py (using inverse distance weighting)? See https://gdal.org/programs/gdal_fillnodata.html and [GDALFillNodata()](https://gdal.org/api/gdal_alg.html#_CPPv414GDALFillNodata15GDALRasterBandH15GDALRasterBandHdiiPPc16GDALProgressFuncPv)
For now, my calculation on a cloud host 64 GB RAM + fast local SSD drive + 8 cores recent AMD processor for a part or two subswaths F23 continues a whole night and it's not completed... I think that's an unacceptable problem due to just the nearest interpolation tool.

**Comment by Xiaohua-Eric-Xu** [comment]
I am not familiar with gdal. I used gdal_grid once with the near neighbor option, but it took 20 hours to interpolate an interferogram and 5 mins for unwrapping afterwards (maybe I did not chose the right option). If you area looks like the attache below (coherence loss), the nearest_grid.c should be quite fast. But if you are interpolating through water (large no data area), it'll be very slow.
![image](https://user-images.githubusercontent.com/16844111/130720834-66ae270b-7417-455f-a8bb-c44fe7d68988.png)

**Comment by Xiaohua-Eric-Xu** [comment]
One way of speeding  up is to intentionally leave some pixels in water to let the interpolation improvise. It'll unwrap slightly slower, but interpolation will run faster for nearest_grid.

**Comment by mobigroup** [comment]
> I used gdal_grid once with the near neighbor option, but it took 20 hours

GDAL is very fast actually but gdal_grid tool is sparse points cloud interpolator instead of grid-based one. We could use gdal_fillnodata.py for the grids filling:
```
$ time gdal_fillnodata.py -md 300 phase_tmp.grd -of NetCDF -co FORMAT=NC4C -co COMPRESS=DEFLATE -co ZLEVEL=3 tmp.grd 
0...10...20...30...40...50...60...70...80...90...100 - done.

real	0m11.603s
user	0m11.131s
sys	0m0.354s
```

How could we fix required coordinates for GMT tools?
```
ncdump -h tmp.grd 
netcdf tmp {
dimensions:
	x = 6081 ;
	y = 3178 ;
variables:
	float Band1(y, x) ;
		Band1:long_name = "GDAL Band Number 1" ;
		Band1:_FillValue = NaNf ;

// global attributes:
		:Conventions = "CF-1.5" ;
		:GDAL = "GDAL 3.3.1, released 2021/06/28" ;
		:history = "Wed Aug 25 10:52:28 2021: GDAL Create( tmp.grd, ... )" ;
}
```

ncrename -v Band1,z tmp.grd

**Comment by Xiaohua-Eric-Xu** [comment]
Coordinates? How about `grdedit`.

**Comment by mobigroup** [comment]
By this way it can't add the coordinates:
```
gmt grdedit tmp.grd -A -R0/48648/0/6356
grdedit [WARNING]: "y", NetCDF: Variable not found
	If something bad happens later, try importing via GDAL.
grdedit [WARNING]: "x", NetCDF: Variable not found
	If something bad happens later, try importing via GDAL.
grdedit [WARNING]: "y", NetCDF: Variable not found
	If something bad happens later, try importing via GDAL.
grdedit [WARNING]: "x", NetCDF: Variable not found
	If something bad happens later, try importing via GDAL.
```

**Comment by mobigroup** [comment]
GDAL-based script requires ~30 seconds instead of ~30 minutes for grid 6081*3178 on the same hardware. Could  we replace nearest_grid utility by GDAL based solution? Actually, dependency to GDAL is common for every geospatial project and so it's not a problem I think.

**Comment by mobigroup** [comment]
I think that's possible to add the required optimization to nearest_grid.c:
1. split input raster to search_radius*search_radius square cells,
2. calculate a count of non empty pixels for the each cell,
3. drop all the cells with zero count connected only to zero count cells,
4. calculate the interpolation as before excluding pixels in the excluded cells.

But the code looks strange. Actually, we could fill empty pixels iteratively (make mask of empty pixels and fill every pixel connected to non-empty previous by iteration direction, delete the filled pixels from the empty mask and repeat with swapping between 4 iteration directions). Of course GDAL-based solution is easier, see my fork of GMTSAR repository: https://github.com/mobigroup/gmtsar/blob/master/gmtsar/csh/nearest_grid.sh

**Comment by dsandwell** [comment]
Please look at this paper and see if the GDAL has this algorithm.  

https://ieeexplore.ieee.org/document/4781798

We tested GDAL years ago and their algorithm did not achieve the same result.  The issue is when a pixel is in the ocean far from the coastline.  Then the algorithm must find the nearest coastline which could be 1000 pixels away.  

> On Aug 24, 2021, at 10:30 PM, Alexey Pechnikov ***@***.***> wrote:
> 
> 
> GDAL-based script requires ~30 seconds instead of ~30 minutes for grid 6081*3178 on the same hardware. Could we replace nearest_grid utility by GDAL based solution? Actually, dependency to GDAL is common for every geospatial project and so it's not a problem I think.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by mobigroup** [comment]
@dsandwell 
> We tested GDAL years ago and their algorithm did not achieve the same result.  The issue is when a pixel is in the ocean far from the coastline.  Then the algorithm must find the nearest coastline which could be 1000 pixels away.

This is the essence of the nearest neighbourhood search to find the nearest neighbourhoods. Your tool uses by default 300 pixels maximum distance to limit search distance and that's the same as GDAL allows. Sure, GDAL provides much more options in addition to the maximum search distance. Do you need something more? By my today's tests the GDAL based script returns the same output as the nearest_grid tool but tens times faster. Maybe did you use some different GDAL tool (as I remember Erik mentioned gdal_grid which is not useful here vector to raster data conversion tool). 

By the way, GDAL allows us download DEM and all other rasters from Google Earth Engine cloud store and many others so we can't replace GDAL by GMT tool for cloud processing (as for me there is no ability to process interferogram stacks locally). GDAL works on terabyte-scale rasters like to some available on Google Earth Engine, see repository https://github.com/mobigroup/geo-earthengine Even the whole planet OpenStreetMap dump can be easy processed by GDAL, see https://github.com/mobigroup/bigquery-openstreetmap

Also, we can use Python + Xarray extension to read NetCDF files and use the nearest neighbourhood lookup from the box with parallelisation by Dask extension, see http://xarray.pydata.org/en/stable/user-guide/indexing.html#nearest-neighbor-lookups It works great too although binary GDAL functions use less RAM. Xarray for 2D/3D/4D data processing plus VTK based visualization are used in https://github.com/mobigroup/ParaView-plugins Python Xarray+Dask+ GDAL Python binding based solution is the best one for pure Python geospatial coding on terabyte-scale datasets (and like to SBAS processing on a big stack of interferograms).

**Comment by Xiaohua-Eric-Xu** [comment]
The 300 was put there so when users get into your scenario, it'll finish within a reasonable amount of time. I myself usually interpolate the entire scene. Your case is one that's really slow for the code. I compared it with MATLAB grid_data, sometimes it's faster (lots of data with scattered cells to be interpolated) and sometimes it's slower (large area with no data). They produce the same results (not really on the mirror nodes that has same distance). See attached comparison between nearest_grid.c (left) and gdal_fillnodata.py (right). Something isn't right.

Many of your suggestions are great, but it takes more than just changing the script. Many advanced users only call the core modules in GMTSAR and have their own flow, which is strongly suggested.  

![image](https://user-images.githubusercontent.com/16844111/130830728-75a0d4c4-67cd-47f6-9bde-99e8a3949185.png)

**Comment by mobigroup** [comment]
Here are 3 TELEGRAM_ and 5 GMTSAR_ environment variables above and all others used in the script only (and exported just for testing purposes). There is a big advantage for exported variables in many linux shells (like to bash but not csh) - we can easy load them into a process and sub processes:

. scriptname
echo $VARNAME

We don’t need to parse the file manually to extract the values and we can redefine them at any time in any script if needed.

Anyway, I understand that my scripts use different conception and even different shell language so the complexity increasing and that’s not so good. The solution could be based on excluding excessive csh scripts calls from bash scripts and using your C based tools directly. Maybe would you suggest how to organize in repository my scripts like to the pipeline processing ones and some basic scripts like to the nearest neighborhood interpolator? After that you would include them or not in the main repository as you prefer.

**Comment by mobigroup** [comment]
Please see commit https://github.com/mobigroup/gmtsar/commit/3b509e238e22d548fc163c1cb867bc2a25828419 as illustration how it could be. We need a "py" scripts directory, "sh" scripts directory, and "testdata" directory to store test datasets (all the names here are just for example). For the installation time we are able to check all the python scripts by single command like to
```
pytest *py
```
We can do the same for shell scripts too, for an example:
```
find . -name '*.sh' -print0 | xargs -0 -I {} -n 1 -P 8 env SELFTEST=1 sh "{}"
```
to run all the tests simultaneously using 8 cores (where all the shell scripts check SELFTEST env variable to launch self tests).

Yes, it will increase the repository size but to be honest I don't know how to maintain large and complex codebase without tests. Since you suggested to add the "py" directory maybe you are ready to add the "testdata" place too :)

**Comment by mobigroup** [comment]
See also https://github.com/mobigroup/gmtsar/commit/a19e30932266870bdc1d0d09a1083fbcd43e6037 for the scripts to automate SBAS processing. The solution can process subswath combinations like to F2 or F23 or F123 from any step on cloud host and send results to Telegram messenger.
<img width="563" alt="image" src="https://user-images.githubusercontent.com/7342379/131226625-25eec29d-4f96-4451-bc3a-78bda00ccc50.png">
