### ISSUE TITLE
[Help]: Some questions about D-InSAR process

### ISSUE THREAD

**Issue by ZhiQiangYang513** [gmtsar/gmtsar#199]
Hi Professor Xu , I am trying to use GMTSAR to detect the Landslide 2020814 HaiTI. I download the sample-S1_Ridgecrest_EQ from the offical web, In read-me file,  you mention two csh to process D-InSAR, the csh 1>p2p_S1_TOPS_Frame.csh  2>p2p_processing.csh,So could you mind telling me what difference between this two csh.  From the usage information, I know the first deals with whole scene, the second deals with subswath, am I right? . Besides ,I am trying to process D-InSAR step by step, for example, I run the pre_proc.csh firstly, align.csh and dem2topo_ra.csh....,but it fails. When I run pre_proc.csh,it tells me missing the dem.grd,even I put the DEM in right folder.So is it right if I run step by step? And I run the p2p_S1_TOPS_Frame.csh ,get the interferograms,but it is about a whole scene. next,I run p2p_processing.csh----<p2p_processing.csh s1a-iw2-slc-vv-20210803t104735-20210803t104801-039064-049bf3-005 s1a-iw2-slc-vv-20210815t104736-20210815t104801-039239-04a1ea-005 config.tops.txt >& log.txt>,I  input it on terminal and run,It finishs quickly without result. by the way I run it in the folder F2 which is generated by runnig p2p_S1_TOPS_Frame.csh .is it right running p2p_S1_TOPS_Frame.csh firstly then running p2p_processing.csh in the specific subswath folder?

**Comment by Xiaohua-Eric-Xu** [comment]
If you read the p2p_S1_TOPS_Frame.csh, it calls p2p_processing.csh inside to process each subswath of data. 

For TOPS data, you need to use align_tops[_esd].csh. The dem.grd needs to be linked to the raw folder so pre_proc.csh (which calls align_tops[_esd].csh) will work. 

I think you were redirecting the results to the log file right? What does the log file say?

Yes, you could do that, but usually if you are running a subswath, I believe you want more than just an interferogram.

**Comment by ZhiQiangYang513** [comment]
Hi Professor Xu , I am wondering what  tmp2# means  in align_tops_esd.csh  line 94?  should it be tmp2?

**Comment by Xiaohua-Eric-Xu** [comment]
The hashtag is just misplaced from the line below. Should not affect processing I think. (fixed 85cc96afa28df1f5c5ef593fed43ad6bb8d30a80)

**Comment by ZhiQiangYang513** [comment]
Hi , Professor, I find in config_tops.txt, there are no parameter  spec_div and spec_mode which are used in p2p_processing.csh . So  I think  these two parameters are used to determine whether do registration with esd , why  missing it in config_tops.txt. Besides ,could you mind telling me the difference among three mode  in  align_tops_esd.csh
