### ISSUE TITLE
SBAS problem

### ISSUE THREAD

**Issue by annisa3** [gmtsar/gmtsar#2]
I got some problem when I run SBAS in GMTSAR. Here is a command I use `sbas intf.tab scene.tab 33 16 24452 16212 -wavelength 0.0554658 -rms -dem` and the result I got is

compute RMS misfit
compute DEM error

setting smoothing to 0.000
setting radar wavelength to 0.055 m
setting radar incidence angle to 37.000 degree
setting range to 866000.000 m
memory allocation! phi

**Comment by Xiaohua-Eric-Xu** [comment]
Looks like you ran SBAS with almost full resolution image. Please make sure you have enough memory to do so or downsample the data.

**Comment by annisa3** [comment]
> Looks like you ran SBAS with almost full resolution image. Please make sure you have enough memory to do so or downsample the data.

I tried to cut the region using region_cut in batch_tops.config but it ended up with corr.grd and unwrap.grd have different dimension. Do you know how to fix this problem?

**Comment by Xiaohua-Eric-Xu** [comment]
What command did you use? intf_tops.csh should cut at SLC level.
p.s. You can always cut your grid using `gmt grdcut`.

**Comment by nazly1392** [comment]
How can I fix the mask in my images?

**Comment by Xiaohua-Eric-Xu** [comment]
Could you be more specific on your question?
