### ISSUE TITLE
Merge frames ERS/ENVISAT

### ISSUE THREAD

**Issue by simonst7** [gmtsar/gmtsar#20]
HI Xiaohua,
 I have a question about the merge frames of one track. I attached a screenshot of two frame phases, but this don't match totally. I processed each frame in the same parameters. Do you know anything for a better match? or any script to make one interferogram of two frames in one process with these satellites.
Thank you,
Simon 
![Antofagasta1995](https://user-images.githubusercontent.com/53209067/79090375-73476500-7d17-11ea-9622-768623227d48.png)

**Comment by dsandwell** [comment]
Hi Simon,

There are two ways to merge these frames.  

1) If the relevant parameters in the PRM files of the master for each frame are the same they will match.  This includes the Doppler fd1 and the near_range.  PLease send the 4 PRM files and I can look for inconsistencies.

2) You can merge the two frames as raw data.  There is an example on the downloads area roe Envisat data for the El Major Cucupah earthquake.

Matt Wei could probably provide details.

David


> On Apr 12, 2020, at 8:45 PM, simonst7 <notifications@github.com> wrote:
> 
> 
> HI Xiaohua,
> I have a question about the merge frames of one track. I attached a screenshot of two frame phases, but this don't match totally. I processed each frame in the same parameters. Do you know anything for a better match? or any script to make one interferogram of two frames in one process with these satellites.
> Thank you,
> Simon
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by simonst7** [comment]
Hi David,
Thank for your response, 
1) How set Doppler fd1 and near range in a correct number, I have fd1 by default (0). These are my PRM files
[SAR_IMS_1PNESA19920508_144306_00000017C084_00096_04249_0000.txt](https://github.com/gmtsar/gmtsar/files/4471465/SAR_IMS_1PNESA19920508_144306_00000017C084_00096_04249_0000.txt)
[SAR_IMS_1PNESA19920508_144322_00000017C084_00096_04249_0000.txt](https://github.com/gmtsar/gmtsar/files/4471467/SAR_IMS_1PNESA19920508_144322_00000017C084_00096_04249_0000.txt)
[SAR_IMS_1PNESA19951009_144327_00000017A005_00096_02455_0000.txt](https://github.com/gmtsar/gmtsar/files/4471469/SAR_IMS_1PNESA19951009_144327_00000017A005_00096_02455_0000.txt)
[SAR_IMS_1PNESA19951009_144342_00000017A005_00096_02455_0000.txt](https://github.com/gmtsar/gmtsar/files/4471470/SAR_IMS_1PNESA19951009_144342_00000017A005_00096_02455_0000.txt)

2) I processed the Major-Cupacah earthquake, but this only has two files (master-slave in one frame) or is another example?
![major-cupacah](https://user-images.githubusercontent.com/53209067/79152799-d62e1000-7d9a-11ea-9b02-774a321a00d2.png)

I'm working with ERS SLC data, I need raw data to merge? 
thank you, David

**Comment by dsandwell** [comment]
Hi Simon,

I did not see that you are working with already-focussed SLC data.  We have only done this with raw unfocussed SLC data.  When you focus the raw data, the you set the near range and Doppler and that provides all the geometry and phase information to make everything match.  

Now I’m adding Anders to this e-mail because he works with Envisat SLC.

David


> On Apr 13, 2020, at 12:35 PM, simonst7 <notifications@github.com> wrote:
> 
> 
> Hi David,
> Thank for your response,
> 
> 	• How set Doppler fd1 and near range in a correct number, I have fd1 by default (0). These are my PRM files
> SAR_IMS_1PNESA19920508_144306_00000017C084_00096_04249_0000.txt
> SAR_IMS_1PNESA19920508_144322_00000017C084_00096_04249_0000.txt
> SAR_IMS_1PNESA19951009_144327_00000017A005_00096_02455_0000.txt
> SAR_IMS_1PNESA19951009_144342_00000017A005_00096_02455_0000.txt
> 
> 	• I processed the Major-Cupacah earthquake, but this only has two files (master-slave in one frame) or is another example?
> 
> 
> I'm working with ERS SLC data, I need raw data to merge?
> thank you, David
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by simonst7** [comment]
Thanks David
I understand I tried to download raw data in ERS in ESA portal, but the level 0 is with E1 - E2 extension, do you know how to find ldr. and dat. files ?. 
Thank you, I'll wait for Anders answer.
