### ISSUE TITLE
[Feature]: Example S1A_Stack_CPGF_T173.tar.gz

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#202]
For now, it works right from the box, thanks. I remember it was a challenge to run some examples years ago. Could you provide some information about the example? Some results obtained but I have no any way to validate them. SBAS velocity range is [-129, 121] mm/year - is it correct results? This is the velocity map below:
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/7342379/131206488-e8226c00-abb8-4e99-9cec-ebfdbf569cb4.png">

The marked (black ellipse) area on the picture looks as atmosphere influence, is it so?
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/7342379/131206547-7e356ef3-e38d-43d2-9812-5c1d084cd3e3.png">

By some reasons ionosphere correction is almost excluded (there is only one example for it) - maybe is it useless or too complex to use or produces unstable results or something more?

**Comment by Xiaohua-Eric-Xu** [comment]
This paper has more details on what you got.
https://ieeexplore.ieee.org/abstract/document/7938636
