### ISSUE TITLE
[Help]: question about snaphu

### ISSUE THREAD

**Issue by sunzhe-96** [gmtsar/gmtsar#204]
Dear all
    Hello,Eric,After watching the source code of snaphu, I found that there is no process of constructing Delaunay triangulation after reading the high-coherence point file when using the MCF unwrapping method. I would like to ask how this is going on. If I want to build Delaunay triangulation with high-coherence points  is visualized, how to write code, I hope to get your advice.

**Comment by Xiaohua-Eric-Xu** [comment]
Are you talking about unwrapping an image or just the persistent scatters? I believe StaMPS has that function.

**Comment by sunzhe-96** [comment]
> Are you talking about unwrapping an image or just the persistent scatters? I believe StaMPS has that function.

Thanks for your reply and I think my focus is on the network construction part of  unwrapping an image.  Does the MCF method in the unwrapping process establish a network for the wrapped phase points with high coherence, and then estimate the cost, and finally get the unwrapping phase? If I want to build a network, is this network a delaunay triangulation? and can this network be displayed? I hope to get your advice.

**Comment by Xiaohua-Eric-Xu** [comment]
The MCF function is defined in Chen and Zebker 2002 paper, or their 2001 paper, I don't remember exactly. I am not sure how it does the construction, but feels they are doing a minimum spanning tree initialization rather than minimum cost flow. I believe MCF is not the default and needs to be turned on for usage.

**Comment by sunzhe-96** [comment]
> The MCF function is defined in Chen and Zebker 2002 paper, or their 2001 paper, I don't remember exactly. I am not sure how it does the construction, but feels they are doing a minimum spanning tree initialization rather than minimum cost flow. I believe MCF is not the default and needs to be turned on for usage.

Thank you very much, I will read the paper you recommend.
