### ISSUE TITLE
[Help]: make_a_offset.csh problem

### ISSUE THREAD

**Issue by 674111501** [gmtsar/gmtsar#206]
Hi,Mr. Xu
I want to get the result of pixel offset tracking with GMTSAR. But I don't know how to do with it. 
When I trying to run the make_a_offset.csh,there is a problem what is shown by the picture.And I don't know what make the problem happen.Hope you for your response.
![屏幕截图 2021-09-01 100831](https://user-images.githubusercontent.com/69631148/131600161-231385c1-7b39-4d63-8122-5d65130380b6.png)

The command line is "make_a_offset.csh S1_20180901_ALL_F3.PRM S1_20190827_ALL_F3.PRM 4 6 16 16 1".

The datafile is so big that I can't give you all of them.

**Comment by 674111501** [comment]
I can't give you the datafile because I can't upload it.

**Comment by Xiaohua-Eric-Xu** [comment]
Yeah. The script was written a while ago and was not used a lot. If you look inside, what it does is to compute pixel offsets using `xcorr`. All other parts are just for plotting or geocoding. If you have the freq_xcorr.dat produced. Just use that file.
