### ISSUE TITLE
A small problem about computer memory in intf_tops.csh

### ISSUE THREAD

**Issue by 501756347** [gmtsar/gmtsar#207]
HI Xiaohua,
Due to limited memory, I would like to ask whether the real_tmp.grd and image_tmp.grd generated by intf_tops.csh can be deleted. If they are not deleted, the three subswaths will occupy too much memory after being generated.
 Look forward to your reply.
Best
Liu
![sendpix0](https://user-images.githubusercontent.com/73731090/132096764-742abdcb-4d59-4fdf-b730-abc5c247cc88.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
Yeah, they should be deleted after running filter.csh. Maybe we forgot to delete them in the script. Fixed here: 3df310e0db4b355a5d27be5545ed11bdec4c1579

**Comment by 501756347** [comment]
> Yeah, they should be deleted after running filter.csh. Maybe we forgot to delete them in the script. Fixed here: [3df310e](https://github.com/gmtsar/gmtsar/commit/3df310e0db4b355a5d27be5545ed11bdec4c1579)

thanks for your help!!!

**Comment by dsandwell** [comment]
They can be deleted eventually.  However if you are limited on disk space there could be other problems later.  I suggest that you get another disk for this processing.


> On Sep 4, 2021, at 6:52 AM, 501756347 ***@***.***> wrote:
> 
> 
> Due to limited memory, I would like to ask whether the real_tmp.grd and image_tmp.grd generated by intf_tops.csh can be deleted. If they are not deleted, the three subswaths will occupy too much memory after being generated.
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037
