### ISSUE TITLE
[Help]: snaphu.csh grdsample [WARNING]

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#209]
For decimation 8/2 there is the warning:
```
./snaphu.csh 0.1 0
grdsample [WARNING]: Output sampling interval in x exceeds input interval and may lead to aliasing.
```
Could you explain has it meaning or not?

**Comment by Xiaohua-Eric-Xu** [comment]
This is sampling the landmask grid to your grid in radar coordinates. The landmask grid has coarser sampling than your phase grid so will give this warning.
