### ISSUE TITLE
[Help]: phasefilt.grd includes lots of pixel-scale outliers

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#210]
Please see phasefilt.grd below:
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/7342379/132333109-cfcb3368-4ed6-4754-94e1-39aad4dea024.png">
For the first look it's just a low-coherency area. But here are multiple 1+ pixel size outliers which should be filtered. We can easy highlight the problem on the zoomed picture:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/7342379/132333250-0e3e9a9d-a2a3-46d3-844d-31e5a5be6670.png">
The phasefilt.grd is actually not filtered with spatial scale filter_wavelength=200 m.

**Comment by mobigroup** [comment]
Let's compare to well-correlated area on the similar zoom:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/7342379/132335446-0e56f92a-39cf-41dd-bbd1-06c7708f67c1.png">

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what you mean with this post here. Is this a bug?

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu For me it looks strange for filtered image. Maybe you do you understand how is it possible for low coherent areas? I see a set of issues for low coherent areas but I still can’t find the source of them.

**Comment by Xiaohua-Eric-Xu** [comment]
If you are looking at a filtered solution at low coherence areas, the results are probably meaningless. Also, one problem in your image is that the phase is wrapped phase. And from sharp red to sharp blue, it's actually a small change.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Maybe that’s the key… How the filtering works? Does it use coherency weighted filtering or masking? Otherwise, we have broken phase values around low correlation areas and the buffer is proportional to wavelength. Why wavelength is equal to 200 m by default and how did you test it? I’m looking for a fix for low correlation areas which probably was out of scope of your research.

**Comment by Xiaohua-Eric-Xu** [comment]
The filter was applied to real and imaginary parts separately. Coherence is not used in weighing the filter. There is a program in GMTSAR called pscatter, that weights the SLC using the dispersion coefficient, though, if that's what you are looking for. Also for low coherence areas, you could try persistent scatter.
