### ISSUE TITLE
[Bug]: bad stitching for subswaths

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#211]
This is the area on the border between F23 subswaths:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/7342379/132335830-11570bd9-2124-4350-b84a-072abfa69d21.png">
For me that doesn't look correct and here are vertical and horizontal offsets in some pixels.

**Comment by mobigroup** [comment]
This is GAMMA software output for area between F23:
<img width="849" alt="image" src="https://user-images.githubusercontent.com/7342379/132336584-88680a7a-9a44-4961-9c31-a4825bff6b68.png">
and GMTSAR output:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/7342379/132336610-c962e4ce-2525-4bbd-8777-edfffe5ef672.png">
Also, I see here lots of vertical stripes:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/7342379/132336981-5e71aa80-bc78-4321-918e-543105d7235d.png">

**Comment by mobigroup** [comment]
The phase image doesn't look good even for separate F2 subswath:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/7342379/132337279-bfde492d-050b-4162-a914-c80c702140e0.png">
and realfilt.grd:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/7342379/132337556-e0eca5fe-5b6b-4643-ba4e-3ba1c79b0faa.png">
and imagfilt.grd:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/7342379/132337681-31f6cf75-ed5f-4132-b39b-19cccc7d3ad5.png">

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu @bjmarfito It looks as the second problem resulting the snaphu unwrapping issues.

**Comment by bjmarfito** [comment]
You're probably right @mobigroup. Some of the unwrapping errors are caused by stitching errors.

**Comment by bjmarfito** [comment]
You could probably start looking at merge_unwrap_geocode_tops.csh regarding this issue @mobigroup.

**Comment by mobigroup** [comment]
@bjmarfito there are no the stitches on Gamma products and I hope we can exclude them too. I suppose that’s related to decimation. I didn’t check the GMTSAR realization yet but simple decimation doesn’t work almost always and we need to filter a raster first (by gaussian filter usually) what is equal to make decimation in spectrum domain.

**Comment by bjmarfito** [comment]
I've missed your comment @mobigroup that even on a single subswath misalignment exists.

**Comment by Xiaohua-Eric-Xu** [comment]
The vertical stripes in each subswaths you see are probably from the Goldstein filter, which is known to alter the phase. At swath boundaries, when you have noise, I am not sure what that filter does. At areas with higher coherence, such problem should not occur.
