### ISSUE TITLE
[Feature]: snaphu.csh commented lines to detrend

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#212]
Could you explain why this code is commented for now? Is it safe and applicable to modern satellites like to Sentinel-1?
```
#
# detrend the unwrapped if DEFOMAX = 0 for interseismic
#
#if ($2 == 0) then
#  gmt grdtrend tmp.grd -N3r -Dunwrap.grd
#else
  mv tmp.grd unwrap.grd
#endif
#
```

**Comment by Xiaohua-Eric-Xu** [comment]
It's OK to detrend if your target is for a small area. But when one looks for larger area, the detrending has to be done carefully excluding the actively deforming region. We decided to leave it to the users to choose whether to detrend or not. It'' be just a simple one line command with GMT.
