### ISSUE TITLE
[Bug]: strong topographic phase

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#213]
See below unwrapped phase comparison between Gamma ASF results with output resolution 40 m (left) and GMTSAR decimation 8/2 with wavelength 400m with output resolution ~100m (right):
![compare_phase](https://user-images.githubusercontent.com/7342379/132550126-bfec8ad8-ccd2-4084-9988-2dc2bf155b31.jpg)
The problem is that the GMTSAR phase is topographic phase here. This area is steep slope from mountains to a coastline. Also, Gamma returns much higher correlation for low-coherence areas (left) and GMTSAR correlation is low (right):
![compare_corr](https://user-images.githubusercontent.com/7342379/132551194-ce388500-f696-4a5c-aa81-418a587e8764.jpg)
At any scale (decimation) and even wavelength we still have the strong influence of the topographic phase. snaphu results are damaged by it and we see here abnormal untapped phase values and it's not related to constant unwrapping shift. 
Gamma uses Copernicus DEM and I've obtained it with egm correction for GMTSAR test too. Actually, the results the same as for SRTM and ALOS dems. FYI, by some reason here are large differences 100-200 m between Sentinel-1 GCP values and the DEM values. If we believe to the GCP it could potentially produce altitude ambiguity. Ok, the perpendicular baseline is about 30 m for the pair and so altitude of ambiguity is about 300 m for Sentinel-1 radar. For the set of fringes on the phase picture above the DEM error should be equal to some kilometres which is nonsense. Even closed fringe on Gamma phase corresponds to unclosed one on GMTSAR phase. I think it's masked by topographic phase here:
![image](https://user-images.githubusercontent.com/7342379/132553684-52ea0b3e-a804-46b8-84ac-a131cd9cd67c.jpeg)

@Xiaohua-Eric-Xu @bjmarfito GMTSAR basics are hard to rewrite and I'm not sure how to check all the steps up to the phase difference processing.

**Comment by Xiaohua-Eric-Xu** [comment]
For the topographic phase you are seeing. I am not sure they are actually different as there are a lot of noise in the left image, potentially because of a very small multi-look factor you selected?
For coherence, you need to make sure what you are comparing. I believe the coherence formula is different.

**Comment by mobigroup** [comment]
I’ve tried other output resolution for Gamma on ASF with similar results. Please let me explain the idea - Gamma filters return noise for low coherent areas and snaphu ignores them. GMTSAR filters return unreliable fringes which produce snaphu unwrapping fails. I think the topographic phase exists for Gamma too while it’s not highlighted and it’s not a problem for unwrapping. It’d be great to exclude the border effects between areas with high and low coherency for GMTSAR processing to check.

**Comment by Xiaohua-Eric-Xu** [comment]
I don't think snaphu could ignore any pixels. If you change the coherence input for SNAPHU, it does not changes much on the output I think. However, in GMTSAR, you should be able to easily replace them with zeros (snaphu does not take in NaNs) by masking with coherence values. e.g. `snaphu.csh 0.1 0` will get rid of anything with coherence lower than 0.1.

**Comment by Xiaohua-Eric-Xu** [comment]
Also, it feels to me like the Gamma result here is without the Goldstein filter.

**Comment by mobigroup** [comment]
snaphu for a noise-only region returns a constant value as I see. Yes, I know about the masking but it’s not helpful for the case because the low to high coherency edges can’t be excluded by masking:
![AC033648-F4D8-4477-906A-F412D058AEB7](https://user-images.githubusercontent.com/7342379/132572401-74030c87-ad09-4d6e-b153-1d0dc8ba6540.jpeg)
I think here should be some vertical closed fringes at the right side of the picture and so coastline area is stable.
Hmm, maybe be because Gamma has as adaptive as Goldstein filters. Is it possible to use adaptive filter for GMTSAR to check? As I remember it was noticed in some documents.

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what specific adaptive filters you meant. The filtering was done with a 2 dimensional convolutional filter using GMT, you could replace those lines I think with adaptive filters, which should be an option in GMT as well. In the script itself, there is no configuration part to swap filters other than the filter_wavelength.

**Comment by mobigroup** [comment]
Actually, I 'm not sure if I understand the realization. For gaussian filter we need to use 4 sigma window so minimal filter size is 9x9 pixels (central point plus 4+ radial points at all directions). That's truth for gauss_200 with size 21x11. But for parameter wavelength=50m we have it too small:
```
$ cat gauss_50 
5 3
        9.8383611497248849e-02  2.4640286869807282e-01  3.3462117974829952e-01  2.4640286869807282e-01  9.8383611497248849e-02
        2.9401489640091688e-01  7.3636363628690771e-01  1.0000000000000000e+00  7.3636363628690771e-01  2.9401489640091688e-01
        9.8383611497248849e-02  2.4640286869807282e-01  3.3462117974829952e-01  2.4640286869807282e-01  9.8383611497248849e-02
```
Sure, with Sentinel-1 IW pixel spacing 2.3x14.1 m there are enough pixels for the correct gaussian filter size. Could you explain?

**Comment by mobigroup** [comment]
See the illustration below why it's important. Here the left plot built for wavelength=200 m and the right for wavelength=50 m. Sorry, the right one is a bit larger for azimuth axis (I've just resolved the task to produce not cropped interferograms for SBAS pipeline), be careful to compare.
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/7342379/132639009-37200d83-4b62-431f-88d8-65ec2e2455a2.png">
The right plot looks much better because there are no accidentional topography determined fringes on it. We see here just noice pattern for low coherent areas as it's supposed.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu I think that's easy to see the topographic phase on the picture below:
<img width="984" alt="image" src="https://user-images.githubusercontent.com/7342379/132949237-985cfd1b-2526-41c6-a865-eed1f144fdd9.png">
Here all the 3 plots are centered simultaneously. Maybe do you have some ideas how to resolve that?

**Comment by Xiaohua-Eric-Xu** [comment]
Were you using make_gaussian_filter to generate them? They need to be interpreted with the input decimation. GMTSAR for now does a two step filtering (essentially we could change this to one step now. this was some remaining codes from before that we haven't got chance to change).

**Comment by mobigroup** [comment]
That's the standalone SBAS processing with gaussian filter with wavelengths 200 and 50 meters. Yes, I think it could be helpful to remove additional filters.

**Comment by dsandwell** [comment]
The two-step filter saves a large amount of computer time.  You should make the comparison before going to a single-step filter.  Also I have been reading about the possible time savings on the transformation from radar to lon, lat coordinates.  This depends on the topography of the area.  If it is flat, then the proposed speed-ups may work but if there is layover or foreshortening from rugged topography then the GMT codes will provide superior results.  Do you want the correct answer or a fast answer?


> On Sep 12, 2021, at 7:12 PM, Alexey Pechnikov ***@***.***> wrote:
> 
> 
> That's the standalone SBAS processing with gaussian filter with wavelengths 200 and 50 meters. Yes, I think it could be helpful to remove additional filters.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by mobigroup** [comment]
@dsandwell There is no magic in GMT. It's just smoothing the result using decimation with median filtering which we can perform much faster. Sure, we can save processing time due to many steps of decimation plus filtering but why don't do it by faster? Actually, I didn't check GMT sources while I suppose it doesn't use some kind of z-curve for spatial indexing and the recent sorting algorithms for median filtering and that's the reason for long processing time.

**Comment by mobigroup** [comment]
I've added Jupyter notebook to test the matrix transforms and median filtering using 5x5 pixels window https://github.com/mobigroup/gmtsar/blob/master/gmtsar/notebooks/trans_ra2ll_intf_ra2ll.ipynb (all the plots interactive here):
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/7342379/133032562-751cbc73-ae2d-4ed3-95ca-0a4a70420489.png">

**Comment by mobigroup** [comment]
@dsandwell 
> the GMT codes will provide superior results

But we need to check GMT code first to be sure how it works. I've opened GMT code in process of rewriting fitoffset.csh and I see that: https://github.com/GenericMappingTools/gmt/pull/5770/files That's more easy to write Python code to produce the same results than to validate all GMT codes.
