### ISSUE TITLE
[Feature request]: faster coordinates processing 

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#215]
The coordinates processing looks very complicated and slow. For example, for 20 m DEM resolution we have trans.dat size about 2 GB. Why are used all the operations like to polynomial interpolation, median filtering, etc. when the coordinates grid is 3 times more detailed than default output grids (60 m)? And for any grid resolution that should be enough to calculate the transform grid once. I think we just need to define lat,lon coordinate index for every point of radar coordinates grid and vice versa. So for any subset of radar or latlon grid we can easy select the required points by the index. There is no reason to do the direct and inverse transforms every time from scratch by irregular points regridding. As estimation, for the 2GB trans.dat the mask-used reordering requires about 1 s instead of 1 minute for the proj_ra2ll.csh or proj_ll2ra.csh tools. Additional filtering on the grid is not processing power consuming.

**Comment by mobigroup** [comment]
By the way, SAT_llt2rat returns different coordinates order:
```
$ SAT_llt2rat
 Usage: SAT_llt2rat master.PRM prec [-bo[s|d]] < inputfile > outputfile  
...
             outputfile   -  range, azimuth, lon, lat, elevation [ASCII default] 
...
 ```

But real output is range, azimuth, elevation , lon, lat. See the code:

```
        /* read the llt points and convert to xyz.  */
        while (scanf(" %lf %lf %lf ", &rln, &rlt, &rht) == 3) {
                rp[0] = rlt;
                rp[1] = rln;
                rp[2] = rht;
...
                /* compute the topography due to the difference between the local radius and
                 * center radius */
                rp[2] =
...
                        dd[0] = xt[0];
                        dd[1] = xt[1];
                        dd[2] = rp[2];
                        dd[3] = rp[1];
                        dd[4] = rp[0];
                        fwrite(dd, sizeof(double), 5, stdout);
```
"rp[2]" is topography as it described in the code comments and it's 3rd output value.

**Comment by mobigroup** [comment]
The index could be added easily in SAT_llt2rat.c but it'll brake your csh scripts (we are able to convert float index into integer values):
```
$ git diff SAT_llt2rat.c
diff --git a/gmtsar/SAT_llt2rat.c b/gmtsar/SAT_llt2rat.c
index 4e5f6c5..b4bc24d 100644
--- a/gmtsar/SAT_llt2rat.c
+++ b/gmtsar/SAT_llt2rat.c
@@ -68,7 +68,7 @@ char *USAGE = " \n Usage: "
               "             precise      -  (0) standard back geocoding, (1) - "
               "polynomial refinenent (slower) \n"
               "             inputfile    -  lon, lat, elevation [ASCII] \n"
-              "             outputfile   -  range, azimuth, lon, lat, elevation [ASCII "
+              "             outputfile   -  range, azimuth, elevation, lon, lat, index [ASCII "
               "default] \n"
               "             -bos or -bod -  binary single or double precision output \n"
               " \n"
@@ -92,8 +92,8 @@ int main(int argc, char **argv) {
 	double xp[3];
 	double xt[3];
 	double rp[3];
-	double dd[5]; /* dummy for output  double precision */
-	float ds[5];  /* dummy for output  single precision */
+	double dd[6]; /* dummy for output  double precision */
+	float ds[6];  /* dummy for output  single precision */
 	double r0, rf, a0, af;
 	double fll, rdd, daa, drr, dopc;
 	double dt, dtt, xs, ys, zs;
@@ -109,6 +109,7 @@ int main(int argc, char **argv) {
 	double rsr;
 	FILE *ldrfile = NULL;
 	int calorb_alos(struct SAT_ORB *, double **orb_pos, double ts, double t1, int nrec);
+	long idx = -1; /* input lines index */
 
 	/* Make sure usage is correct and files can be opened  */
 
@@ -212,6 +213,8 @@ int main(int argc, char **argv) {
 	/* read the llt points and convert to xyz.  */
 
 	while (scanf(" %lf %lf %lf ", &rln, &rlt, &rht) == 3) {
+		// input lines counter
+		idx++;
 		rp[0] = rlt;
 		rp[1] = rln;
 		rp[2] = rht;
@@ -280,7 +283,7 @@ int main(int argc, char **argv) {
 			continue;
 
 		if (otype == 1) {
-			fprintf(stdout, "%.9f %.9f %.9f %.9f %.9f \n", xt[0], xt[1], rp[2], rp[1], rp[0]);
+			fprintf(stdout, "%.9f %.9f %.9f %.9f %.9f %l\n", xt[0], xt[1], rp[2], rp[1], rp[0], idx);
 		}
 		else if (otype == 2) {
 			ds[0] = (float)xt[0];
@@ -288,7 +291,8 @@ int main(int argc, char **argv) {
 			ds[2] = (float)rp[2];
 			ds[3] = (float)rp[1];
 			ds[4] = (float)rp[0];
-			fwrite(ds, sizeof(float), 5, stdout);
+			ds[5] = (float)idx;
+			fwrite(ds, sizeof(float), 6, stdout);
 		}
 		else if (otype == 3) {
 			dd[0] = xt[0];
@@ -296,7 +300,8 @@ int main(int argc, char **argv) {
 			dd[2] = rp[2];
 			dd[3] = rp[1];
 			dd[4] = rp[0];
-			fwrite(dd, sizeof(double), 5, stdout);
+			dd[5] = (double)idx;
+			fwrite(dd, sizeof(double), 6, stdout);
 		}
 	}
```
Without the index we need to do expensive regridding operation every time to find corresponding latlon grid cell for radar coordinates.

**Comment by mobigroup** [comment]
Ok, I've built the transformations for comfortable interactive work. FYI, that's requires about 1 minute for a single interferogram transform by proj_ra2ll.csh. With pixel-wise radar to geographic transform mask intf_ra2ll.grd we are able to produce interferogram in 0.1 s on a single core:
```
intf = xr.open_dataarray('asc/F2/intf_all/2021007_2021019/phasefilt.grd')
intf_ra2ll = xr.open_dataarray('asc/topo/intf_ra2ll.grd')
intf_ll = xr.DataArray(np.where(intf_ra2ll>=0, intf.values.reshape(-1)[intf_ra2ll], np.nan), coords=intf_ra2ll.coords)
```
<img width="985" alt="image" src="https://user-images.githubusercontent.com/7342379/132939282-e17b824e-3758-4c06-bf50-e4d3ae60d34f.png">

By the same way that's possible to transform trans.dat elevation into geographic coordinates in 0.25 s on a single core: 
```
trans = np.fromfile('asc/topo/trans.dat', dtype=np.float64).reshape([-1,5])
trans_ra2ll = xr.open_dataarray('asc/topo/trans_ra2ll.grd')
topo_ll = xr.DataArray(np.where(trans_ra2ll>=0, trans[:,2][trans_ra2ll], np.nan), coords=trans_ra2ll.coords)
```
<img width="985" alt="image" src="https://user-images.githubusercontent.com/7342379/132939346-0c5beb1d-f5bc-4458-a415-2d77e2013783.png">

Sure, that's very easy to utilise all cores to transform ~100 interferograms per second on 8 core host.

Here we have projected interferograms exactly on the DEM grid. There is interesting point when DEM pixel includes multiple interferogram pixels. For the current test we use only one nearest pixel on interferogram for every DEM pixel. For DEM resolution ~20 m and decimation 4/1 or more that's enough. For case when we want to have less decimation with the same DEM resolution that's required to use some kind of aggregation for all interferogram pixels for a single DEM pixel. It can be done by using a stack of the same pixel-wise transforms for nearest 1st, 2nd, 3rd, etc. pixels and aggregation the stack results by any way which is relatively cheap raster operation.

I'll share all the codes in my repository soon. For today, we can use Jupyter Python notebooks to read all the interferograms and run snaphu in tiled or single-tile mode and visualize all the results in radar and geographic coordinates by fast and easy way.
<img width="671" alt="image" src="https://user-images.githubusercontent.com/7342379/132939700-ecf65a79-69c2-44b8-b82d-16cf80df89b9.png">

**Comment by mobigroup** [comment]
This is the interactive interferogram on Google Satellite map in Jupyter notebook: 
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/7342379/132946126-36f9c4a0-e50d-45e1-8aed-16f16652ecb9.png">
And animated interferogram series:
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/7342379/132946220-91a7423b-4698-4001-8992-20a88914ecb5.png">
I hope that's understandable now why fast interactive processing is valuable.

**Comment by mobigroup** [comment]
The command line scripts added:
https://github.com/mobigroup/gmtsar/blob/master/gmtsar/py/trans_ra2ll.py
https://github.com/mobigroup/gmtsar/blob/master/gmtsar/py/intf_ra2ll.py
Also, the intf_ra2ll.py module includes Dask parallel and lazy processing intf_ra2ll() function too:
```
intf_ra2ll_matrix = xr.open_dataarray('asc/topo/intf_ra2ll.grd', chunks={'y':1e6,'x':1e6}).persist()
intf_ra2ll(phasefilts, intf_ra2ll_matrix)
```
In just ~1 millisecond the function returns Dask wrapper which will be computed later on demand on multiple cores or distributed cluster for required only one or multiple interferograms.

P.S. trans_ra2ll.py is needed only because the DEM grid index is missed in trans.dat

**Comment by Xiaohua-Eric-Xu** [comment]
Well, I think once you have raln.grd and ralt.grd, which is basically two look-up-tables, the transform should be very quick (see proj_ra2ll.csh for details). All prior stages, especially computing trans.dat, is time-consuming.

**Comment by mobigroup** [comment]
By some reason raln.grd and ralt.grd sizes are too small grids. For phase grid 3208x 2068 the grids are  1533x 131. Why do you use this additional decimation here?
```
gmt grdinfo phasefilt.grd 
...
phasefilt.grd: x_min: 0 x_max: 25664 x_inc: 8 name: x n_columns: 3208
phasefilt.grd: y_min: 0 y_max: 4136 y_inc: 2 name: y n_rows: 2068
...

gmt grdinfo raln.grd
...
raln.grd: x_min: 720 x_max: 25232 x_inc: 16 name: x n_columns: 1533
raln.grd: y_min: 0 y_max: 4160 y_inc: 32 name: y n_rows: 131
...

gmt grdinfo ralt.grd
...
ralt.grd: x_min: 720 x_max: 25232 x_inc: 16 name: x n_columns: 1533
ralt.grd: y_min: 0 y_max: 4160 y_inc: 32 name: y n_rows: 131
...
```

Also, if you mean the command below as the transform it's still slow too:
```
time gmt grdtrack rap -nl -bi3f -bo5f -Graln.grd -Gralt.grd | gmt gmtconvert -bi5f -bo3f -o3,4,2 > llp

real	0m7.190s
```
Let's compare to just a small fraction of a second for the matrix-based transform above. Even this command is ~10 times slowly than the complete conversion above:
```
time gmt gmtinfo llp -I25s/20s -bi3f 
-R47.7638888889/48.8611111111/37.8111111111/38.4611111111
real	0m1.530s
```
plus
```
time gmt blockmedian llp -R47.7638888889/48.8611111111/37.8111111111/38.4611111111 -bi3f -bo3f -I2.5s/2s -r -V > llpb
real	0m3.847s
```
and
```
time gmt xyz2grd llpb -R47.7638888889/48.8611111111/37.8111111111/38.4611111111 -I2.5s/2s  -r -fg -Gphasefilt_ll.grd -bi3f
real	0m0.789s
```
I think the GMT based approach can't be used for interactive work. Even more, GMT uses all 4 cores for the processing:
```
gmt

	GMT - The Generic Mapping Tools, Version 6.2.0 [64-bit] [4 cores]
...
```
when the Python version uses single core for a single raster and can process rasters in parallel on all the cores so it's actually 4 times more faster than just ~0.1 s per processing. And the produced grid is pixel-wise accurate instead of the GMT based one (I suppose for the full grid it will be even much slower).

**Comment by Xiaohua-Eric-Xu** [comment]
Well, the decimation is determined based on your filter wavelength (1/4). I guess the question should be what's the point of over sampling. For 200m filter, you'll get ~50m sampling afterwards. The results in radar coordinates are set around 1/8 so pixels after geocoding are less likely NaNs due to topographic changes.

**Comment by mobigroup** [comment]
Hmm, I think it's just hide some potential problems. Regular grid regridding is very fast operation by GDAL and many other tools and so it's not a problem. When we have the way to produce the output in geographic coordinates output on the DEM grid very fast do you have some more reasons for all the decimations?

**Comment by mobigroup** [comment]
By my opinion, gaussian filtering without original spectrum visualisation is not a safe operation. For the example, I still don'ts understand why and where we see so strong topographic phase... with all the processing step spectrums the answer should be obvious.

**Comment by Xiaohua-Eric-Xu** [comment]
I don't really understand what you mean by "hide some potential problems". You could manually set the output to the full potential of the radar image (e.g. a few meters sampling), but what's the point of doing that when the filter you set could not allow you to resolve changes at such small scale? 
My personal experience creating a 10-m grid over 100x70km region takes a few minutes once you have the projection grid calculated. 
We do have geocode_slc.c modules where you could do interferometry really quickly after geocoding the SLC.

**Comment by Xiaohua-Eric-Xu** [comment]
> By my opinion, gaussian filtering without original spectrum visualisation is not a safe operation. For the example, I still don't understand why we see so strong topographic phase for low-coherent areas... with all the processing step spectrums the answer should be obvious.

Have you thought about topographically correlated atmospheric noise? Also I think topographic fringes not only occur at low coherence regions. These two I believe are irrelevant.

**Comment by Xiaohua-Eric-Xu** [comment]
![image](https://user-images.githubusercontent.com/16844111/133019480-5669b371-9c9b-4bbd-a1a3-0d56079c280b.png)
These are a few examples from this paper below (see d and e): https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2020JB021406?af=R

**Comment by mobigroup** [comment]
> Have you thought about topographically correlated atmospheric noise?

yes, that’s the right point but I don’t know how to check it for now. Sure, there is a high probability of atmospheric disturbances for the area between high mountains and sea surface.

**Comment by Xiaohua-Eric-Xu** [comment]
You could try the GACOS product, but sometimes it matches and sometimes not. I usually just remove anything that's correlated to topography if I am looking for small deformation signals.

**Comment by mobigroup** [comment]
> My personal experience creating a 10-m grid over 100x70km region takes a few minutes once you have the projection grid calculated.

ah, ok, if it looks fast enough for you :) I hope I’ll be ready soon to show my interactive notebooks to compare and maybe you’d understand me.

**Comment by mobigroup** [comment]
> You could try the GACOS product, but sometimes it matches and sometimes not.

thanks, I didn’t know about it.

> I usually just remove anything that's correlated to topography if I am looking for small deformation signals.

Please explain a bit. Maybe do you use correlation estimation for spatial spectrums of the topography and interferograms or just visual estimation? How do you remove the topography effect without some damage for phase unwrapping accuracy?
