### ISSUE TITLE
[Help]: question about sbas code

### ISSUE THREAD

**Issue by sunzhe-96** [gmtsar/gmtsar#216]
Dear all
Hello,Eric,After selecting the high coherence points in the sbas.c you wrote, whether a network is established for deformation estimation, or they are settled in isolation.

**Comment by Xiaohua-Eric-Xu** [comment]
Could you explain a bit more on what you meant by the two?
1) a network is established for deformation estimation
2) they are settled in isolation

**Comment by sunzhe-96** [comment]
> Could you explain a bit more on what you meant by the two?
> 
> 1. a network is established for deformation estimation
> 2. they are settled in isolation

I would like to ask how the sbas code you implemented calculates the deformation on the time series. Is it to extract the high coherence points in the unwrapping graph and directly calculate the time series of each point?

**Comment by Xiaohua-Eric-Xu** [comment]
If you take a look at the Usage of the code. It takes in unwrapped interferograms. Thus what it does is basically what's described in Berardino et al., 2002 or Schmidt & Burgmann 2003. The extra flavors are the coherence-based part by Xiaopeng Tong and the atmospheric part I implemented based on Tymofyeyeva & Fialko 2015. 

What you described is more likely what StaMPS deos called 3-D unwrapping.

**Comment by sunzhe-96** [comment]
> If you take a look at the Usage of the code. It takes in unwrapped interferograms. Thus what it does is basically what's described in Berardino et al., 2002 or Schmidt & Burgmann 2003. The extra flavors are the coherence-based part by Xiaopeng Tong and the atmospheric part I implemented based on Tymofyeyeva & Fialko 2015.
> 
> What you described is more likely what StaMPS deos called 3-D unwrapping.

Thank you so much for your answer! Obviously I don’t know much about the principle of sbas, I will go to see the paper you recommend.

**Comment by sunzhe-96** [comment]
> If you take a look at the Usage of the code. It takes in unwrapped interferograms. Thus what it does is basically what's described in Berardino et al., 2002 or Schmidt & Burgmann 2003. The extra flavors are the coherence-based part by Xiaopeng Tong and the atmospheric part I implemented based on Tymofyeyeva & Fialko 2015.
> 
> What you described is more likely what StaMPS deos called 3-D unwrapping.

Hello,Eric,I would like to ask whether the interference part of gmtsar has the pure geometric co-registration part you implemented in Xiaohua Xu et al. 2016

**Comment by Xiaohua-Eric-Xu** [comment]
The paper was about geometric coregistration done for TOPS data. There is a aling_SAT.csh that sort of does similar coregistration for other satellites.

**Comment by sunzhe-96** [comment]
> The paper was about geometric coregistration done for TOPS data. There is a aling_SAT.csh that sort of does similar coregistration for other satellites.

Thank you so much for your reply!
