### ISSUE TITLE
Stacking Coherence Grids problem

### ISSUE THREAD

**Issue by dhy158** [gmtsar/gmtsar#217]
**Describe the problem you met**
Dear Sir or Madam,
When I did merge job, I have to create a ​corr_stack.grd​ file because my area is regions of poor coherence. I used script stack_corr.csh to create corr_stack.grd.  I used ncview to take a look at it, I found my subwath 3 have some wrongs. Screenshot is follewed, I don't know why I got this result. I checked my three subwath interferograms, it looks all right.

**OS and software version**
If applicable, what operating system and software version you are using?
OS:Ubuntu 20
GMTSAR version:6.1

**Log file**

merge_batch.csh merge.in batch_tops.config
ls 201*/corr.grd > corr_list
stack.csh corr_list 1 corr_stack.grd std.grd
ncview corr_stack.grd

**Screenshot**

this is screenshot of corr_stack.grd
![question](https://user-images.githubusercontent.com/78248213/132978259-b3fe3cc9-a6f2-461e-ad8e-315e04cc9d3d.png)
…]()
this a merged corr,grd
![1](https://user-images.githubusercontent.com/78248213/132978823-fda4f187-2da9-4ed8-b4e4-6f0a6a460b03.png)

**Comment by dhy158** [comment]
I had solved this problem,because my SAR data have 2021year , I used (ls 201*/corr.grd > corr_list).

**Comment by Xiaohua-Eric-Xu** [comment]
Great!
