### ISSUE TITLE
[Help]: Generate DEM files for use with GMTSAR - Not working

### ISSUE THREAD

**Issue by lumirinc** [gmtsar/gmtsar#219]
Since this morning I am trying to download DEM for my study site from https://topex.ucsd.edu/gmtsar/demgen/. However, after submitting the request it keeps processing. I am trying since morning and it seems there's some problem with the website. It's been more than 5 hour until not I unable to download DEM for my study site.

**Comment by lumirinc** [comment]
Today above mentioned site is working fine. I think the problem was with website.

**Comment by Xiaohua-Eric-Xu** [comment]
I think our server was down for a moment.
