### ISSUE TITLE
preproc_batch_tops.csh data.in dem.grd 1 problem

### ISSUE THREAD

**Issue by jiang1880023** [gmtsar/gmtsar#22]
HI Xiaohua,

I have a problem processing Sentinel-1B images in "preproc_batch_tops.csh data.in dem.grd 1". During the this step, I got like this ：

"Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 6 lines of precise orbit for the LED file...
Successfully opened junk1 
hermite: interpolation not in center interval
hermite: interpolation not in center interval
hermite: interpolation not in center interval". 

I checked my EOF, they do cover the images.

data.in:
s1b-iw1-slc-vv-20190808t220938-20190808t220941-017500-020e97-004:S1B_OPER_AUX_POEORB_OPOD_20190828T110923_V20190807T225942_20190809T005942.EOF
s1b-iw1-slc-vv-20191019t220941-20191019t220943-018550-022f3e-004:S1B_OPER_AUX_POEORB_OPOD_20191108T110545_V20191018T225942_20191020T005942.EOF

"organize_files_tops_linux.csh SAFE_filelist pins.ll 1"  failed after I changed the oreder of lon and lat in the pins.ll file, so I guess the original one is correct.

original pins.ll:
120.58 49.24
120.45 49.18

Could you let me know how to deal with this problem? Look forward to your reply. 

Best
Jiang

![图片](https://user-images.githubusercontent.com/65638654/82401573-bd490680-9a8c-11ea-8236-c1d38983538f.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Jiang,

My suspicion is that you only extracted one burst to process, and you are not using the most up to date version in the master. 

Before the fix below, in case there's only one burst (~20 km), the extracted precise orbit will only have 6 records. However, to do Hermite interpolation, you need 7 records at least. 
e8ba48f545803ab6cc9780b5f3f74252c9d53f56

You could fix this either by extracting one more burst with organize_file_tops.csh or update and recompile the code.

Cheers,
Xiaohua(Eric)

**Comment by jiang1880023** [comment]
> Hi Jiang,
> 
> My suspicion is that you only extracted one burst to process, and you are not using the most up to date version in the master.
> 
> Before the fix below, in case there's only one burst (~20 km), the extracted precise orbit will only have 6 records. However, to do Hermite interpolation, you need 7 records at least.
> [e8ba48f](https://github.com/gmtsar/gmtsar/commit/e8ba48f545803ab6cc9780b5f3f74252c9d53f56)
> 
> You could fix this either by extracting one more burst with organize_file_tops.csh or update and recompile the code.
> 
> Cheers,
> Xiaohua(Eric)

Hi Xiaohua,

I really appreciate your help.I updated the code and it worked in "preproc_batch_tops.csh data.in dem.grd 1". But the error "hermite: interpolation not in center interval" still occurred in "preproc_batch_tops.csh data.in dem.grd 2".Is that still not suitable for very small AOI？

Anyway, I expanded the AOI to get 5 bursts and the problem solved.

Thanks,
Jiang

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Jiang,
Could you attach your log? How many records did it generate for your LED files.
Xiaohua(Eric)

**Comment by jiang1880023** [comment]
Hi Xiaohua,

Thanks for your fast response.
I just built a new file and tried "preproc_batch_tops.csh data.in dem.grd 2" with the small AOI,and no bug occurred. I guess the problem is because I didn't make the original file clean.

Thanks,
Jiang
