### ISSUE TITLE
[Bug]: Some problems with example S1A_Stack_CPGF_T173.tar.gz

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#224]
This is the output produced by upstream GMTSAR below:

![image](https://user-images.githubusercontent.com/7342379/133916252-8827535c-14ff-4590-890c-4e4bf00afbd1.jpeg)

Here we have some horizontal stripes (marked by black ellipses) and some images probably include strong atmospheric noise (marked by black circles). Is here a burst-processing problem? Should we use ionospheric correction for the example? This is provided example but it looks so bad...  Maybe do you mean GMTSAR is not suitable for this case? Please provide some explanation.

**Comment by mobigroup** [comment]
Also, see README_prep.txt:
```
preproc_batch_tops.csh data.in dem.grd 2                                                                                                                      
#preproc_batch_tops_esd.csh data.in dem.grd 2  
```
Here for preproc_batch_tops_esd.csh argument "esd_mode" missed.

**Comment by mobigroup** [comment]
ESD processing is not too helpful because it resolves some issues and create the same new ones on other images:
![image](https://user-images.githubusercontent.com/7342379/133918598-dd5ff52e-66f2-4ad5-ac8d-3cfdfd24d492.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, we carefully selected a bad case (almost the worst but not there yet) so users know what to expect when they just pick a random area and start their time-series analysis. The example is from early data where orbit was not as good as today's I think. If you question about the discontinuity, you could use spectral_diversity to get the double differenced phase at the burst overlap region, i.e. ddphase(file). Then you could tell me whether this could be corrected with ESD or BESD or other approaches. The earlier paper (Xu et al., 2017), in which we used these data, sort of proved that these artifact could be absorbed by the atm-screen and can be removed with later time-series analysis.

**Comment by mobigroup** [comment]
That’s interesting case because I see we might use ESD to just some images for the better results. It’d be interesting to merge the different alignment techniques together I think.

**Comment by Xiaohua-Eric-Xu** [comment]
Merging different techniques together?

**Comment by mobigroup** [comment]
I mean we could use ESD alignment for some of images only.

**Comment by Xiaohua-Eric-Xu** [comment]
That's tricky. ESD sometimes work well. Sometimes it does not. 
Wang, K., Xu, X., & Fialko, Y. (2017). Improving burst alignment in TOPS interferometry with bivariate enhanced spectral diversity. IEEE Geoscience and Remote Sensing Letters, 14(12), 2423-2427.

**Comment by mobigroup** [comment]
Yes, I see on the results but I didn't check the source codes yet.
