### ISSUE TITLE
[Bug]: output DEM incorrect for dem2topo_ra.csh

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#225]
This is the topo_ra.grd produced by dem2topo_ra.csh for example S1A_Stack_CPGF_T173:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/7342379/133920141-6b899a66-b13e-4915-a210-12f59ffffcea.png">
Let's compare to the original dem.grd:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/7342379/133920247-849dcec1-83b2-4df8-b392-6e5a28826d83.png">
Here GMT surface tool results are not physical correct. Actually, that's first time when I see  cubic interpolation applied to DEM processing. Especially, using iterative tension surface without control to 1st derivative continuity... There are a lot of publications about DEM interpolation, just for the example: https://sci-hub.se/10.3846/20296991.2013.859821 (use "Save" button if it can't be viewed online). Even natural neighbourhood is much better than GMT surface results.

**Comment by mobigroup** [comment]
Here I’ve found exactly the same results for tension surfaces with and without barriers: [COMPARISONS BETWEEN DIFFERENT INTERPOLATION TECHNIQUES](https://d-nb.info/1144994764/34).  See breaks on RMS plots for tension approximators - we have the corresponding peaks on the 3d DEM plot above.

**Comment by mobigroup** [comment]
Let's compare GMT produced DEM:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/7342379/134146779-0e6a03ae-afa0-47e6-a428-8ff595068ff9.png">

and the natural neighborhood result:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/7342379/134146892-bbb6897e-508f-4c55-881a-60a1a2a0e794.png">

I suppose GMT surface tool is used here to remove subpixel noise which we can perform much more accurate by gaussian filter for small sigma parameter like to 0.5-1 pixel size.

**Comment by mobigroup** [comment]
And the GMT result:

<img width="1280" alt="Screenshot 2021-09-21 at 17 02 06" src="https://user-images.githubusercontent.com/7342379/134152169-6f4d0d05-83ab-457d-886b-52ff448da538.png">

vs gaussian filtering with parameter sigma=1 plus natural neighbourhood interpolation:

<img width="1280" alt="Screenshot 2021-09-21 at 17 00 12" src="https://user-images.githubusercontent.com/7342379/134152186-7b9be615-ee59-494c-aa5d-96a902fa17e4.png">

**Comment by mobigroup** [comment]
The left picture below is processed on original topo_ra and the right one on "a piecewise cubic, continuously differentiable (C1), and approximately curvature-minimizing polynomial surface":

![image](https://user-images.githubusercontent.com/7342379/134306330-bb9a6a18-f3db-4a8a-99c8-ce041172b0c7.jpeg)

Here black circles mark mountains areas with significant output quality change. All the codes to produce the topo_ra committed in my repo.

**Comment by Xiaohua-Eric-Xu** [comment]
The first map looks like `gmt surface` ran on a very coarse grid. I am not sure what's causing that as this is the first time I saw a topo map like this (usually one could hardly tell the difference in panel view). I need to discuss with David and potentially Paul on what to do. Thanks for sending this. Very important!

**Comment by mobigroup** [comment]
This is your own example DEM from S1A_Stack_CPGF_T173.tar.gz archive. I think you will be surprised reading GMT sources as internal processing changes sometimes by weird reasons with links to very obsolete and incorrect papers. It could work very different when you were preparing the example… I use Python SciPy  interpolators, see https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html and the smooth cubic one produces the best results while the linear is great too. When we refer to theoretical basics, any kind of natural neighborhood (NN) interpretation is correct because pixels intensity is proportional to the pixel area and all NN methods using area-based weighting. And the cubic method with 1st derivative continuity control is more sophisticated while its advantages for numerical calculations are still easy to understand.

**Comment by Xiaohua-Eric-Xu** [comment]
I finally got some time to work on this. So I tuned the tension from surface to 0.1 (3dbfa27bc1537ea629dd706c52107a34740481a9) and the resulting topography changes are as following
left old vs right new
![image](https://user-images.githubusercontent.com/16844111/148124983-f7d8e63a-4628-4a69-8b08-f9a6b51f7066.png)
It does show slightly less strong topographic phase
left old vs right new
![image](https://user-images.githubusercontent.com/16844111/148126976-32811f7b-91d7-43b7-9085-df58e908ecf3.png)

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Nice, it looks significantly better. I think the tension value is ok here while for my python fork I use a modern approach based on derivative smoothness controlling approximation (it’s not available in GMT).
