### ISSUE TITLE
[Bug]: SAT_llt2rat returns incomplete output

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#226]
When we have a set of points where first point(s) coordinates are outside of the image then the next points are missed in the output:
```
$echo -e 0 0 0\n-115.81416667 33.18083333 -36.92949295 | SAT_llt2rat master.PRM 1
interpolation point outside of data constraints, 7999553.274366 7998144.000000 7998374.000000

$ echo -e -115.81416667 33.18083333 -36.92949295 | SAT_llt2rat master.PRM 1
29228.422146840 -3052.108106717 -571.515833645 -115.814166670 33.180833330
```
There is same issue for binary output too:
```
$ echo -e 0 0 0\n-115.81416667 33.18083333 -36.92949295 | SAT_llt2rat master.PRM 1 -bod |wc
interpolation point outside of data constraints, 7999553.274366 7998144.000000 7998374.000000
       0       0       0
$ echo -e 0 0 0\n-115.81416667 33.18083333 -36.92949295 | SAT_llt2rat master.PRM 1 -bos |wc
interpolation point outside of data constraints, 7999553.274366 7998144.000000 7998374.000000
       0       0       0
```

So for big DEM with points outside of the area we have empty SAT_llt2rat  results. It'd be better to just ignore the points outside of the area or return informative error about the entire processing fail.

And sometimes it can't produce output for valid points in binary mode:

```
$ echo -115.81416667 33.18083333 -36.92949295 | SAT_llt2rat master.PRM 1 | wc
       1       5      76
$ echo -115.81416667 33.18083333 -36.92949295 | SAT_llt2rat master.PRM 1 -bod | wc
       0       0       0
```

**Comment by mobigroup** [comment]
Hmm, I don't understand it:

```
$ wc -l dem.dat
 18440641 dem.dat
$ cat dem.dat | SAT_llt2rat master.PRM 1 -bod | wc
  213530 1007236 38503280
$ head -n1000 dem.dat | SAT_llt2rat master.PRM 1 -bod | wc
       0       0       0
$ head -n1000000 dem.dat | SAT_llt2rat master.PRM 1 -bod | wc
       0       0       0
```

It doesn't return results for 1 or 1k or 1M records and returns incomplete results for 18M records. For 18M records 5*4 bytes each the outputs size is just about 38 Mb.

**Comment by Xiaohua-Eric-Xu** [comment]
The Hermite interpolation in the code uses 6 or 7 records to do calculation. Thus you need a long enough orbit . If you are sort of on the edge, you could use extend_orbit, but it may give you artificial ramps at the boundary in your interferogram. This is a tough choice as some satellites comes with orbit product that has the same length as the image, and we could not perform normal orbit calculation with such short orbit. For TOPS, just use ext_orb_s1a to get long enough orbit.

**Comment by mobigroup** [comment]
That’s strange because the ascii and the binary outputs are not consistent.How could it be related to the orbits?.. For now, I’m cropping DEM by frame extent using reference points in xml files. This processing is ~10 times faster with the same results.

**Comment by Xiaohua-Eric-Xu** [comment]
> That’s strange because the ascii and the binary outputs are not consistent.How could it be related to the orbits?.. 
I am not sure I get what you meant...

**Comment by mobigroup** [comment]
There are the examples above when we have ascii output but binary output is empty:
```
$ echo -115.81416667 33.18083333 -36.92949295 | SAT_llt2rat master.PRM 1 | wc
       1       5      76
$ echo -115.81416667 33.18083333 -36.92949295 | SAT_llt2rat master.PRM 1 -bod | wc
       0       0       0
```

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what happened.
```
% echo -73.913828 18.108643 0 | SAT_llt2rat IMG-HH-ALOS2355610350-201223-FBDR1.1__A.PRM 1 | wc 
       1       5      73
% echo -73.913828 18.108643 0 | SAT_llt2rat IMG-HH-ALOS2355610350-201223-FBDR1.1__A.PRM 1 -bod | wc
       0       1      40
```

**Comment by mobigroup** [comment]
Please try to process full DEM in binary and ascii modes and count the output records (use "wc" to calculate ascii records and file size divided by fixed record size for binary mode).

**Comment by Xiaohua-Eric-Xu** [comment]
In the code, otype = 2 for -bos, and otype = 3 for -bod. This was built-in to save later computation time. 
```
279         if ((xt[0] < r0 || xt[0] > rf || xt[1] < a0 || xt[1] > af) && (otype > 1))
280             continue;
```

**Comment by mobigroup** [comment]
That's great but why is it applied for binary mode only? :) The results are different for different modes and so the utility testing is too complicated.

**Comment by Xiaohua-Eric-Xu** [comment]
Not really complicated... Binary is for production. ASCII is for scripting, e.g. to determine whether a pin you selected is associated with which specific burst of data...

**Comment by mobigroup** [comment]
Hmm, I'm not sure about other satellites but for Sentinel-1 we have the reference points (with rad plus WGS84 coordinates) in xml files:
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/7342379/134624792-81885dfa-72e0-4068-8dd7-1eadaa4b6954.png">

**Comment by Xiaohua-Eric-Xu** [comment]
> Hmm, I'm not sure about other satellites but for Sentinel-1 we have the reference points (with rad plus WGS84 coordinates) in xml files:

What do you really mean?

**Comment by mobigroup** [comment]
For every Sentinel-1 image we have a set of reference points like to:
```
$ tail -n 20 s1a-iw1-slc-vv-20150121t134413-20150121t134424-004270-005317-001.xml | head
      <geolocationGridPoint>
        <azimuthTime>2015-01-21T13:44:24.812434</azimuthTime>
        <slantRangeTime>5.673901939958336e-03</slantRangeTime>
        <line>6543</line>
        <pixel>21597</pixel>
        <latitude>3.206737461505988e+01</latitude>
        <longitude>-1.157456652734846e+02</longitude>
        <height>3.588010934163285e+02</height>
        <incidenceAngle>3.681177090431645e+01</incidenceAngle>
        <elevationAngle>3.267934865880433e+01</elevationAngle>
```

**Comment by Xiaohua-Eric-Xu** [comment]
I know there are, so what's the question?

**Comment by mobigroup** [comment]
Why we still need these ascii and binary output inconsistency when we are able to determine the required DEM area by fast way before? I think the entire output could be enabled by '-debug' command line argument for an example but the different outputs are not helpful but requires to spend time for the validation...

**Comment by Xiaohua-Eric-Xu** [comment]
Well, that's not the only case this code is used. Like in organize_files_tops.csh, and many other scripts, the ASCII output is piped through shell commands to help determine things. Why adding a special -debug when the default is handy to use? e.g. For a given point in geocoordinates, I want to extract the data in radar coordinates, this could be done with one line shell command using the ASCII output.

**Comment by mobigroup** [comment]
Thanks, got it. Please add the note to the output to simplify the tool usage.
