### ISSUE TITLE
[Help]: interfrogram creation

### ISSUE THREAD

**Issue by hamidkhura** [gmtsar/gmtsar#229]
**Describe the problem you met**
I get an error when I try to execute the intf_tops_parallel.csh command.

**OS and software version**
ubuntu 20.04 
GMTSAR version: 6

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
> intf_tops_parallel.csh intf.in batch_tops.config 6
reading topo topo_ra.grd
 xdim 25184, ydim 12196 
 Can't open filter  
conv [ERROR]: File amp1_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  amp1_tmp.grd=bf 
 Can't open filter  
conv [ERROR]: File amp2_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  amp2_tmp.grd=bf 
 Can't open filter  
conv [ERROR]: File real_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real_tmp.grd=bf 
 Can't open filter  
conv [ERROR]: File imag_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag_tmp.grd=bf 
grdmath [ERROR]: Syntax error: realfilt.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
grdinfo [ERROR]: Error for input file: No such file (display_amp.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grd2cpt [ERROR]: Error for input file: No such file (display_amp.grd)
grd2cpt [ERROR]: Syntax error -L option: Cannot decode limits
grd2cpt [ERROR]: Syntax error -L option: min_limit must be less than max_limit.
grdimage [ERROR]: Error for input file: No such file (display_amp.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse display_amp.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rdisplay_amp.grd
psconvert [ERROR]: The file display_amp.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
grdmath [ERROR]: Syntax error: amp1.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: tmp.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
 Can't open filter  
grdimage [ERROR]: Error for input file: No such file (corr.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse corr.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

**Comment by Xiaohua-Eric-Xu** [comment]
Have you guys figured out the problem?
The error come from these lines in conv.c
```
186     /* open and filter file */
187     if ((f_filter = fopen(argv[3], "r")) == NULL)
188         die("Can't open filter", "");
```
The filter files are stored at location popped by `gmtsar_sharedir.csh`. 
Could you check whether those files are readable by the user account?

**Comment by KsanaGSI** [comment]
Hi,
I also get the same error  **Can't open filter**  on  CentOS 8.4.2105 and GMTSAR version: 6:

INTF.CSH, FILTER.CSH - START
intf.csh
running phasediff...
reading topo topo_ra.grd
 xdim 24536, ydim 12188 
/usr/local/GMTSAR/gmtsar/csh/gmtsar_sharedir.csh: Permission denied.
gauss_300 4 8 (1 2)
making amplitudes...
 **Can't open filter**  
conv [ERROR]: Cannot find file amp1_tmp.grd
conv [ERROR]: Cannot find file amp1_tmp.grd
conv [ERROR]: File amp1_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  amp1_tmp.grd=bf 
.....

File gmtsar_sharedir.csh. content only one raw:
# Just report the GMTSAR share directory
echo "/usr/local/GMTSAR/share/gmtsar"

[CantOpenFilter.txt](https://github.com/gmtsar/gmtsar/files/7537816/CantOpenFilter.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
This is a really strange error. The returning output from the C-code is simple from failure of opening the filter file. And a supecious line is here 
```
/usr/local/GMTSAR/gmtsar/csh/gmtsar_sharedir.csh: Permission denied.
```
as this script only contains an echo command. 
Could you change ownership of the GMTSAR directory and it's contents to you and re-run the script?
