### ISSUE TITLE
[Help]: run merge_batch.csh error 

### ISSUE THREAD

**Issue by 501756347** [gmtsar/gmtsar#230]
Hi XiaoHua
I recently had some trouble running gmtsar.My merge_batch.csh could not run through, I set up the file as required, but it always error that "can't open  S1_20180322_ALL_F3.PRM"  when I run it, 
grdinfo [ERROR]: Cannot find file phasefilt.grd
grdinfo [ERROR]: Must specify one or more input files
I am sure that the file is in that path and confirmed it many times,I have no idea right now, I look forward to your answers.
![sendpix0](https://user-images.githubusercontent.com/73731090/135193375-4edfa31e-730d-41d0-b536-53c75dfd652a.jpg)
![sendpix1](https://user-images.githubusercontent.com/73731090/135193387-ed8cac45-206c-4c93-9f35-58b3d17e6982.jpg)
![sendpix2](https://user-images.githubusercontent.com/73731090/135193392-4a9ee4a0-4ff5-463a-9304-4775e6965da0.jpg)

**Comment by 501756347** [comment]
> The merging failed as it says images have non-persistent PRFs, which is really strange. Please double check that in the PRM files. Also, do you have a tmp_mergelist in one of the folders in side merge directory? Please attach that.
There are only these three files in the merge folder
![sendpix0](https://user-images.githubusercontent.com/73731090/136485370-6f1f9dc0-5e93-4e17-b7e5-aa10ae9a7997.jpg
![sendpix1](https://user-images.githubusercontent.com/73731090/136485430-89fa45a4-bad9-445e-872d-0b88c6c1a5dd.jpg)
)

**Comment by 501756347** [comment]
> So there is no folder named as 2018080_2019327 created in your merge directory?

It will be created automatically after running the command "merge_batch.csh merge_list batch_tops.config", but an error will be reported
![2021-10-09 12-57-00 的屏幕截图](https://user-images.githubusercontent.com/73731090/136644665-2f21a3ae-349a-4684-9ec8-49f85329149d.png)
.

**Comment by Xiaohua-Eric-Xu** [comment]
So what's inside the day1_day2 folder? Should there be a few text input files for merge_swath? 
For the PRM files listed inside, what are their PRFs? `grep PRF your_PRM_file`
