### ISSUE TITLE
[Feature]: PyGMTSAR available

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#233]
@dsandwell @Xiaohua-Eric-Xu
I've completed some of my suggestions and now PyGMTSAR can process the example S1A_Stack_CPGF_T173 completely. Use the link to try it in your browser right now on [Google Colab: PyGMTSAR example S1A_Stack_CPGF_T173](https://colab.research.google.com/drive/1iUfn9ZVMFCh0n9O0LBtmENLmeCeP0mN8?usp=sharing) By the way, on 4 cores server it's 3 times faster than GMTSAR and SBAS velocity result is clean from atmosphere noise while it still uses GMTSAR SBAS calculation command line tool. 

<img width="1280" alt="Screenshot 2021-10-04 at 14 59 20" src="https://user-images.githubusercontent.com/7342379/135814732-aa0eb142-ae54-4a57-b271-c33b5174a28e.png">

<img width="1280" alt="Screenshot 2021-10-03 at 15 43 26" src="https://user-images.githubusercontent.com/7342379/135747009-13cac2fa-8bc5-4a90-ba52-9e7b490afd0f.png">

<img width="1280" alt="Screenshot 2021-10-03 at 15 43 37" src="https://user-images.githubusercontent.com/7342379/135747025-62ba17ab-c741-4ee3-972b-a9ec103e61ed.png">

<img width="1280" alt="Screenshot 2021-10-03 at 15 43 48" src="https://user-images.githubusercontent.com/7342379/135747034-a6358a0e-c037-4532-bd2d-042d6a45bfd0.png">

<img width="1280" alt="Screenshot 2021-10-03 at 15 44 00" src="https://user-images.githubusercontent.com/7342379/135747037-7857a58f-8411-45f1-9b28-45ad2e819830.png">

<img width="1280" alt="Screenshot 2021-10-04 at 14 54 12" src="https://user-images.githubusercontent.com/7342379/135814064-1bcc7baa-7eec-4c8a-b989-1033ba9c6e43.png">

**Comment by mobigroup** [comment]
Now we can auto detect interferograms with atmosphere disturbance issues. Obviously, these effects produce false correlation between connected pairs, see on the picture below:

![image](https://user-images.githubusercontent.com/7342379/135873654-2140f3cb-b1d3-4d03-8f79-5f9e3b418df2.png)

Here we see that image for 2014-04-27 is affected and the correlation between all the interferograms with it is always higher 0.7

**Comment by simonst7** [comment]
Thanks for sharing @mobigroup !! It could be really helpful, I will try to make an example with this.

**Comment by mobigroup** [comment]
One more example for Persistent Scatters Interferometry (PSI) for Yamchi Dam, North Iran. Reference area selected as most stable area with small movements (equal to the well-known regional trend) to subtract solid Earth's tides and their aliasing from the results. See the [Live Jupyter Notebook on Google Colab](https://colab.research.google.com/drive/1KnMxiBRWzKQKQFmYYKIqO_TMllj22fki?usp=sharing)

![append](https://user-images.githubusercontent.com/7342379/143826953-987c115e-21d7-4396-a1b2-3ecff85dad7e.jpg)

**Comment by mobigroup** [comment]
See live Google Colab example for atmospheric delay detection approaches using spatial spectrum and correlation analyses: [Live Example S1A_Stack_CPGF_T173 Plus on Google Colab](https://colab.research.google.com/drive/1nzRml3SFEq26yNX4IL1Ubn55KUDAjuY2?usp=sharing). Explanation article on Russian available by this link: [Оценка и устранение атмосферных помех спутниковой интерферометрии](https://habr.com/ru/post/647781/) Brief summary: we don't need to assume small linear surface movements but just the constant Earth's volume and numerical stability.

![abc](https://user-images.githubusercontent.com/7342379/151154446-0368abf2-14ac-44b8-a958-36c63c6c5584.jpg)
