### ISSUE TITLE
[Help]: a fatal error while install gmtsar

### ISSUE THREAD

**Issue by beistudy** [gmtsar/gmtsar#236]
I want to install gmtsar on my computer with ubuntu 18 os system.
I tried step by step according to the GMTSAR Wiki Page, but it appeared a fatal error while I ran the next step:
: make
I do not know why. could you please help me?
The error report is :
 /usr/bin/ld: cannot find -lgmtsar
collect2: error: ld returned 1 exit status
Makefile:44: recipe for target 'envi_slc_decode' failed
make[2]: *** [envi_slc_decode] Error 1
make[2]: Leaving directory '/usr/local/GMTSAR/preproc/ENVI_preproc/ENVI_SLC_decode'
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/local/GMTSAR/preproc/ENVI_preproc'
Makefile:37: recipe for target 'preprocess' failed
make: *** [preprocess] Error 2

**Comment by beistudy** [comment]
Here it i
[log.log](https://github.com/gmtsar/gmtsar/files/7393917/log.log)
s.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Sorry for getting back to you late. The log file you attached is a re-ran of `make`. Could you first `make spotless` and then `autoconf` `./configure ...` `make ` and `make install` and send the complete log?

**Comment by beistudy** [comment]
I am sorry. I found that it is something wrong with my computer. @Xiaohua-Eric-Xu

**Comment by Xiaohua-Eric-Xu** [comment]
Errr, may I ask what was it?...

**Comment by beistudy** [comment]
I reinstalled the operating system. Then, it works.
