### ISSUE TITLE
[Help]: Operation not permitted

### ISSUE THREAD

**Issue by aramfathian** [gmtsar/gmtsar#237]
**Describe the problem you met**
I am trying running p2p_S1_TOPS_Frame.csh for a two-pass processing, but I receive errors indicating an operation permission issue: 
"ln: failed to create symbolic link './dem.grd': Operation not permitted"

**OS and software version**
If applicable, what operating system and software version you are using?
OS: Ubuntu subsystem running on Window10
GMTSAR version: 

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your cas
[log.txt](https://github.com/gmtsar/gmtsar/files/7377543/log.txt)
e

**Comment by Xiaohua-Eric-Xu** [comment]
Could you reformat the disk?
