### ISSUE TITLE
[Help]: Error of postseismic displacement  based on SBAS

### ISSUE THREAD

**Issue by Xiongwei789** [gmtsar/gmtsar#239]
**Describe the problem you met**
After an InSAR time series Sentinel-1 TOPS data, the strange thing is that the deformation from dis*.grd (subfigure a) and residuals from rms.grd (subfigure b) in the north are very large. I have checked the dem.grd that has a enough coverage. Is this caused by the atmospheric phase? And How should I remove this phase?
![atm 1](https://user-images.githubusercontent.com/92964720/138404647-7831e890-fecf-4821-9783-57e2ea8ddd97.png)
![2021-10-22 14-29-18屏幕截图](https://user-images.githubusercontent.com/92964720/138405232-634d6cfb-88a0-4252-82ec-0e9c5743b94b.png)

**Comment by Xiaohua-Eric-Xu** [comment]
If you think it is atmospheric noise, you could try to mitigate it with
1) atmospheric model. There is a recent update in user-contributions that takes in GACOS correction.
2) elevation dependent correction.
3) turn on the -atm option in sbas.
4) tie the interferogram to GNSS stations over the region.

**Comment by Xiongwei789** [comment]
Thank you for your reply!
I still have some questions want to to figure out.
1. To mitigate atmospheric noise, should I choose one or more of the above processes.
2. Actually, I have tried to turn on the -atm option in sbas (see the figure).  How to determine the suitable value for atm and what does a larger value of atm mean? 
3. What does the output rms .grd mean? Does a larger rms value indicate that the solution is unreliable?

**Comment by Xiongwei789** [comment]
![InSAR](https://user-images.githubusercontent.com/92964720/140082081-09878cf6-a5af-4f72-b1e1-9124a6536fc3.png)

**Comment by Xiaohua-Eric-Xu** [comment]
> Thank you for your reply! I still have some questions want to to figure out.
> 
> 1. To mitigate atmospheric noise, should I choose one or more of the above processes.
> 2. Actually, I have tried to turn on the -atm option in sbas (see the figure).  How to determine the suitable value for atm and what does a larger value of atm mean?
> 3. What does the output rms .grd mean? Does a larger rms value indicate that the solution is unreliable?

1. You could run multiples together.
2. The number after -atm is the number of iterations to run, usually 3 or 4 is a good number.
3. the rms.grd is not really root mean square misfit, but uncertainty of velocity estimate from linear regressing the time-series.

**Comment by Xiongwei789** [comment]
> > Thank you for your reply! I still have some questions want to to figure out.
> > 
> > 1. To mitigate atmospheric noise, should I choose one or more of the above processes.
> > 2. Actually, I have tried to turn on the -atm option in sbas (see the figure).  How to determine the suitable value for atm and what does a larger value of atm mean?
> > 3. What does the output rms .grd mean? Does a larger rms value indicate that the solution is unreliable?
> 
>     1. You could run multiples together.
> 
>     2. The number after -atm is the number of iterations to run, usually 3 or 4 is a good number.
> 
>     3. the rms.grd is not really root mean square misfit, but uncertainty of velocity estimate from linear regressing the time-series.

1. I am trying to use CACOS to mitigate atmospheric noise. However, I don't know how to do elevation dependent correction. 
2.  The big uncertainty does not mean a poor result, right?  What is its role?

**Comment by Xiongwei789** [comment]
![InSAR](https://user-images.githubusercontent.com/92964720/140458507-783cc40a-7704-43d3-b72e-af0e4e6fdb88.png)
After performing CACOS correction, the result seems to be more reliable. Is it enough to be used for  inversion?

**Comment by Xiaohua-Eric-Xu** [comment]
1. Please see here: https://github.com/gmtsar/gmtsar/issues/98
2. Not necessarily, strong seasonal signals will give larger uncertainties in linear regressed velocities.

**Comment by Xiongwei789** [comment]
Thank you very much for your reply.
