### ISSUE TITLE
[Help]: There is no cshrc file in the ubuntu system HOME folder on my computer. What should I do?

### ISSUE THREAD

**Issue by sase1997** [gmtsar/gmtsar#240]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

**Comment by Xiaohua-Eric-Xu** [comment]
Simply create one. You could use `vi` `gedit` or any other text editor to do so.
