### ISSUE TITLE
configure.ac incorrectly adds '/lib' to end of --with-tiff-lib arg

### ISSUE THREAD

**Issue by michaelkarlcoleman** [gmtsar/gmtsar#241]
This is inconsistent with its doc and standard usage, and also makes it impossible to specify a lib directory not named 'lib'.

https://github.com/gmtsar/gmtsar/blob/94006f393bf534186eef1abb0c39df6f3d71cae2/configure.ac#L205

**Comment by Xiaohua-Eric-Xu** [comment]
Do you want to make some changes with a pull request?
