### ISSUE TITLE
[Help]: Image clipping

### ISSUE THREAD

**Issue by sase1997** [gmtsar/gmtsar#243]
When I set the latitude and longitude information of pins.ll file, I can extract the burst of the coverage area, but I want to cut it to a smaller area. What should I do? This is not covered in the instruction manual!

**Comment by Xiaohua-Eric-Xu** [comment]
Hi the processor of Sentinel-1 TOPS mode data (i.e. make_s1a_tops) could only deal with bursts of data. If you want to further cut it down to a very small area, consider using `cut_slc`.

**Comment by Xiaohua-Eric-Xu** [comment]
As you may have noticed we are trying to build a documentation site with Sphinx. Hopefully it'll come out soon.
