### ISSUE TITLE
[Help]: I find some lines in the phase.pdf.

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#245]
Hi，
I find some lines in the phase.pdf for 2017301-2017314.
Looks misaligned but they aligned 2017003.
![mmexport1635944967546](https://user-images.githubusercontent.com/86451834/140065902-15fc3266-89b2-48fc-892d-8ed6973c4741.jpg
)
Is it because I use a different frame？
![mmexport1635944960582](https://user-images.githubusercontent.com/86451834/140066150-a12422f7-2a74-4240-898b-51691e4d23db.jpg)
)
（2017003 is below but other is up）
Is there any way to solve this problem?
Thanks，very much.

**Comment by Xiaohua-Eric-Xu** [comment]
You could try using ESD to remove it. For pair-wise processing, turn-on the ESD (in config file, make spec_div = 1).

**Comment by swjiaotong-jyliu** [comment]
Thanks，I got it。
