### ISSUE TITLE
[Help]: Size of unwrap_ll.grd files is not same!

### ISSUE THREAD

**Issue by mohammadnia11** [gmtsar/gmtsar#247]
Hello
I need the outputs of interferograms and they have to be in the same shape, but I checked the size of "unwrap_ll.grd" files in the intf_all folder and found out the size of them is not the same. 
For example, the properties of two unwrap_ll files have been attached. 
(  _region_cut = 2000/15000/6500/10000_ in the batch_tops.config)
![shape](https://user-images.githubusercontent.com/47507196/140624407-17307045-28f2-43c3-a49b-a6b83e3890a8.jpg)
Could you please explain how can I convert them to the same size?

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, this is because GMT removes all NaNs and re-calculate the boundaries. You could 
1) perform all analysis in radar coordinates and then geocode with proj_ra2ll.csh
2) use grdcut to get the common area.

**Comment by mohammadnia11** [comment]
Hi Eric
Thank you for your suggestion. I used grdsample for resizing files to the identical shape but I think grdcut would be a better option.
