### ISSUE TITLE
[Help]: landmask_ra.grd wrong size

### ISSUE THREAD

**Issue by edszyman** [gmtsar/gmtsar#248]
When using the command "landmask.csh `gmt grdinfo phasefilt.grd -I- | cut -c3-20` " to generate a land mask for unwrapping, the file landmask_ra.grd is truncating the range direction for some reason I have not been able to figure out.

 
grid info for phasefilt.grd:
<img width="808" alt="Screen Shot 2021-11-09 at 3 47 01 PM" src="https://user-images.githubusercontent.com/44045691/141004528-131d313e-09d9-486c-81c0-e8b46434a669.png">

grid info for landmask_ra.grd:
<img width="867" alt="Screen Shot 2021-11-09 at 3 46 31 PM" src="https://user-images.githubusercontent.com/44045691/141004635-59bdb256-bca5-4987-876a-fd180ab27a4b.png">

This is interfering with my ability to unwrap the interferogram. The SNAPHU routine is giving me the error seen here that the grid files are not the same size.

<img width="1032" alt="Screen Shot 2021-11-09 at 3 45 56 PM" src="https://user-images.githubusercontent.com/44045691/141004897-7dcdcbb4-cde3-429b-b8cb-dfbb73b6cb55.png">

If you could help me figure out what is causing the mismatched sizes or a possible work around that would be great! Thanks!

**Comment by Xiaohua-Eric-Xu** [comment]
@PaulWessel Actually I met this before as well. I fixed it by manually running landmask.csh with a larger range, e.g. for your case, instead of 0/67560/0/14468, use maybe -20/67580/-16/14488. But it's good to know why GMT reduced the bounds so I am copying this to Paul.

**Comment by PaulWessel** [comment]
I need to see how landmask_ra.grd was created prior to that grdsample command, i.e., what was the region then.

**Comment by Xiaohua-Eric-Xu** [comment]
The landmask.csh says 
```
gmt grdlandmask -Glandmask.grd `gmt grdinfo -I- dem.grd` `gmt grdinfo -I dem.grd`  $V -NNaN/1 -Df
proj_ll2ra.csh trans.dat landmask.grd landmask_ra.grd
gmt grd2xyz landmask_ra.grd -bo > landmask_ra.xyz
gmt xyz2grd landmask_ra.xyz -bi -r -R$1 `gmt grdinfo -I landmask_ra.grd` -Gtmp.grd
```
So I assume the mismatch is generated during proj_ll2ra.csh, which forces a -I32/64 sampling? Though I am not sure where that 4 come from. i.e.
```
gmt xyz2grd rap `gmt gmtinfo rap -I32/64 -bi3f` -I32/64 -r -G$3 -bi3f
```

**Comment by PaulWessel** [comment]
Hm, maybe some round off.  Here is a shorter _projection_ll2ra.csh_ script that should be faster and less prone to rounding (use 5m and 3s instead of truncated series).  Also, avoids making multiple I/o on large files to create temp files.  You should make sure it works though before updating the repo (i.e., to ensure the grdtrack command works as it should).

```
gmt set FORMAT_GEO_OUT D
gmt grd2xyz $2 -s -bo3f -fg > llp
#
#   make grids of longitude and latitude versus range and azimuth
#
set R5m = `gmt gmtinfo llp -I5m -bi3f`
gmt surface $1 -i3,4,0 -bi5d $R5m -I3s -T.50 -Gllr.grd $V
gmt surface $1 -i3,4,1 -bi5d $R5m -I3s -T.50 -Glla.grd $V
#
gmt grdtrack llp -Gllr.grd -Glla.grd -bi3f -bo3f -nl -o3,4,2 > rap
#
# Grid the range, azimuth, phase columns
#
gmt xyz2grd rap `gmt gmtinfo rap -I32/64 -bi3f` -I32/64 -r -G$3 -bi3f
```
