### ISSUE TITLE
[Help]: preproc_batch_tops.csh

### ISSUE THREAD

**Issue by mcontk** [gmtsar/gmtsar#249]
After prepared "data.in" I have errors during aligning Secondary Images to Reference Image  in mode 2:

~/Insar/des3/F1/raw> preproc_batch_tops.csh data.in dem.grd 1    
rm: No existe correspondencia.
rm: no se puede borrar 'baseline_table.dat': No existe el fichero o el directorio
Reading in 5567 lines of info from XML...
Writing 17 lines for orbit...
Writing 47 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5581 lines of info from XML...
Writing 17 lines for orbit...
Writing 47 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5567 lines of info from XML...
Writing 16 lines for orbit...
Writing 47 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5581 lines of info from XML...
Writing 17 lines for orbit...
Writing 47 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5609 lines of info from XML...
Writing 17 lines for orbit...
Writing 47 lines of precise orbit for the LED file...
Successfully opened junk1 
(base) cyclo@geop:~/Insar/des3/F1/raw> 
(base) cyclo@geop:~/Insar/des3/F1/raw> 
(base) cyclo@geop:~/Insar/des3/F1/raw> 
(base) cyclo@geop:~/Insar/des3/F1/raw> mv baseline_table.dat ../
(base) cyclo@geop:~/Insar/des3/F1/raw> 
(base) cyclo@geop:~/Insar/des3/F1/raw> 
(base) cyclo@geop:~/Insar/des3/F1/raw> vi data.in 
(base) cyclo@geop:~/Insar/des3/F1/raw> 
(base) cyclo@geop:~/Insar/des3/F1/raw> 
(base) cyclo@geop:~/Insar/des3/F1/raw> 
(base) cyclo@geop:~/Insar/des3/F1/raw> preproc_batch_tops.csh data.in dem.grd 2
grdfilter (gmtapi_alloc_grid): Could not reallocate memory [174385.32 Gb, 46811201728816 items of 4 bytes]
grd2xyz [ERROR]: Cannot find file flt.grd
grd2xyz [ERROR]: Cannot find file flt.grd
grd2xyz [ERROR]: File flt.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
rm: No existe correspondencia.
Reading in 5567 lines of info from XML...
Writing 17 lines for orbit...
Writing SLC..Image Size: 24568 X 10852...
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8
number of points clipped to short int 1 
Writing 47 lines of precise orbit for the LED file...
Writing 47 lines of precise orbit for the LED file...
Successfully opened junk1 
rm: No existe correspondencia.
Reading in 5581 lines of info from XML...
Writing 17 lines for orbit...
Writing 47 lines of precise orbit for the LED file...
Shifting the master PRM by 0 lines...
Successfully opened junk1.PRM 
Successfully opened junk2.PRM 
Successfully opened junk1 
Successfully opened junk1 
[1] 43634
[2] 43635
[2]  + Fin                           SAT_llt2rat S1_20200112_100421_F1.PRM 1 < topo.llt > tmp1.dat
[1]  + Fin                           SAT_llt2rat tmp.PRM 1 < topo.llt > tmpm.dat
blockmedian [WARNING]: No data records found; no output produced
blockmedian [WARNING]: No data records found; no output produced
[1] 43852
[2] 43853
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [ERROR]: No datapoints inside region, aborting
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [ERROR]: No datapoints inside region, aborting
[2]    Finalizado 79                       gmt surface atmp.xyz -bi3d -R0/24568/0/10852 -I8/4 -Gatmp.grd -T0.5 -N1000 -r
[1]  + Finalizado 79                       gmt surface rtmp.xyz -bi3d -R0/24568/0/10852 -I8/4 -Grtmp.grd -T0.5 -N1000 -r
grdmath [ERROR]: rtmp.grd is not a number, operator or file name
grdmath [ERROR]: atmp.grd is not a number, operator or file name
Reading in 5581 lines of info from XML...
Writing 17 lines for orbit...
Reading in range and azimuth shifts table...
make_s1a_tops [ERROR]: Cannot find file r.grd
make_s1a_tops [ERROR]: Cannot find file r.grd
make_s1a_tops [ERROR]: File r.grd not found
[Session make_s1a_tops (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open range shift tables r.grd 
Writing 47 lines of precise orbit for the LED file...
Error de bus (se ha creado un `core')
mv: no se puede efectuar `stat' sobre 'S1_20200112_ALL_F1.PRMresamp': No existe el fichero o el directorio
Successfully opened junk1 
Reading in 5567 lines of info from XML...
Writing 16 lines for orbit...
Writing 47 lines of precise orbit for the LED file...
Shifting the master PRM by 0 lines...
Successfully opened junk1.PRM 
Successfully opened junk2.PRM 
Successfully opened junk1 
Successfully opened junk1 
[1] 45246
[2] 45247
[2]  + Fin                           SAT_llt2rat S1_20200124_100420_F1.PRM 1 < topo.llt > tmp1.dat
[1]  + Fin                           SAT_llt2rat tmp.PRM 1 < topo.llt > tmpm.dat
blockmedian [WARNING]: No data records found; no output produced
blockmedian [WARNING]: No data records found; no output produced
[1] 45464
[2] 45465
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [ERROR]: No datapoints inside region, aborting
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [ERROR]: No datapoints inside region, aborting
[2]    Finalizado 79                       gmt surface atmp.xyz -bi3d -R0/24568/0/10852 -I8/4 -Gatmp.grd -T0.5 -N1000 -r
[1]  + Finalizado 79                       gmt surface rtmp.xyz -bi3d -R0/24568/0/10852 -I8/4 -Grtmp.grd -T0.5 -N1000 -r
grdmath [ERROR]: rtmp.grd is not a number, operator or file name
grdmath [ERROR]: atmp.grd is not a number, operator or file name
Reading in 5567 lines of info from XML...
Writing 16 lines for orbit...
Reading in range and azimuth shifts table...
make_s1a_tops [ERROR]: Cannot find file r.grd
make_s1a_tops [ERROR]: Cannot find file r.grd
make_s1a_tops [ERROR]: File r.grd not found
[Session make_s1a_tops (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open range shift tables r.grd 
Writing 47 lines of precise orbit for the LED file...
Error de bus (se ha creado un `core')
mv: no se puede efectuar `stat' sobre 'S1_20200124_ALL_F1.PRMresamp': No existe el fichero o el directorio
Successfully opened junk1 
Reading in 5581 lines of info from XML...
Writing 17 lines for orbit...
Writing 47 lines of precise orbit for the LED file...
Shifting the master PRM by 0 lines...
Successfully opened junk1.PRM 
Successfully opened junk2.PRM 
Successfully opened junk1 
Successfully opened junk1 
[1] 46858
[2] 46859
[2]    Fin                           SAT_llt2rat S1_20200217_100420_F1.PRM 1 < topo.llt > tmp1.dat
[1]  + Fin                           SAT_llt2rat tmp.PRM 1 < topo.llt > tmpm.dat
blockmedian [WARNING]: No data records found; no output produced
blockmedian [WARNING]: No data records found; no output produced
[1] 47076
[2] 47077
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [ERROR]: No datapoints inside region, aborting
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [ERROR]: No datapoints inside region, aborting
[2]    Finalizado 79                       gmt surface atmp.xyz -bi3d -R0/24568/0/10852 -I8/4 -Gatmp.grd -T0.5 -N1000 -r
[1]  + Finalizado 79                       gmt surface rtmp.xyz -bi3d -R0/24568/0/10852 -I8/4 -Grtmp.grd -T0.5 -N1000 -r
grdmath [ERROR]: rtmp.grd is not a number, operator or file name
grdmath [ERROR]: atmp.grd is not a number, operator or file name
Reading in 5581 lines of info from XML...
Writing 17 lines for orbit...
Reading in range and azimuth shifts table...
make_s1a_tops [ERROR]: Cannot find file r.grd
make_s1a_tops [ERROR]: Cannot find file r.grd
make_s1a_tops [ERROR]: File r.grd not found
[Session make_s1a_tops (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open range shift tables r.grd 
Writing 47 lines of precise orbit for the LED file...
Error de bus (se ha creado un `core')
mv: no se puede efectuar `stat' sobre 'S1_20200217_ALL_F1.PRMresamp': No existe el fichero o el directorio
Successfully opened junk1 
Reading in 5609 lines of info from XML...
Writing 17 lines for orbit...
Writing 47 lines of precise orbit for the LED file...
Shifting the master PRM by 0 lines...
Successfully opened junk1.PRM 
Successfully opened junk2.PRM 
Successfully opened junk1 
Successfully opened junk1 
[1] 48490
[2] 48491
[2]    Fin                           SAT_llt2rat S1_20200229_100419_F1.PRM 1 < topo.llt > tmp1.dat
[1]  + Fin                           SAT_llt2rat tmp.PRM 1 < topo.llt > tmpm.dat
blockmedian [WARNING]: No data records found; no output produced
blockmedian [WARNING]: No data records found; no output produced
[1] 48748
[2] 48749
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [ERROR]: No datapoints inside region, aborting
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [ERROR]: No datapoints inside region, aborting
[2]    Finalizado 79                       gmt surface atmp.xyz -bi3d -R0/24568/0/10852 -I8/4 -Gatmp.grd -T0.5 -N1000 -r
[1]  + Finalizado 79                       gmt surface rtmp.xyz -bi3d -R0/24568/0/10852 -I8/4 -Grtmp.grd -T0.5 -N1000 -r
grdmath [ERROR]: rtmp.grd is not a number, operator or file name
grdmath [ERROR]: atmp.grd is not a number, operator or file name
Reading in 5609 lines of info from XML...
Writing 17 lines for orbit...
Reading in range and azimuth shifts table...
make_s1a_tops [ERROR]: Cannot find file r.grd
make_s1a_tops [ERROR]: Cannot find file r.grd
make_s1a_tops [ERROR]: File r.grd not found
[Session make_s1a_tops (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open range shift tables r.grd 
Writing 47 lines of precise orbit for the LED file...
Error de bus (se ha creado un `core')
mv: no se puede efectuar `stat' sobre 'S1_20200229_ALL_F1.PRMresamp': No existe el fichero o el directorio
Successfully opened junk1 
rm: no se puede borrar 'flt.grd': No existe el fichero o el directorio
(base) cyclo@geop:~/Insar/des3/F1/raw> 

**OS and software version**
If applicable, what operating system and software version you are using?
OS: linux x64   (opensuse leap15.3)

GMTSAR version: 6.1

**Comment by vintingb** [comment]
grdfilter (gmtapi_alloc_grid): Could not reallocate memory [174385.32 Gb, 46811201728816 items of 4 bytes]

try to use smaller dem.grd

**Comment by mcontk** [comment]
Thank you very much, your suggestion solved the problem. Good day!!

**Comment by Xiaohua-Eric-Xu** [comment]
I am wondering how big of a DEM could ask for 17,000+ GB memory.
