### ISSUE TITLE
Problems about SBAS: output vel.grd

### ISSUE THREAD

**Issue by jiang1880023** [gmtsar/gmtsar#25]
Hello Eric,
When I process the SBAS with command:

sbas intf.tab scene.tab 8 5 5788 2309 -range 898971 -incidence 37 -wavelength 0.0554658 -smooth 0.1 -rms -dem

The output files (dem.grd, disp_0000000.grd, rms.grd, vel.grd) contain only zero values.
I noticed your answer in [http://gmt.soest.hawaii.edu/boards/6/topics/7951?r=8288#message-8288].But the problem is still not solved after I do unwrap with the mask_def.grd. And I think many pixel have values in all images after  I did this.
I do not know where the problem lies on. I wonder if you could help me with this. 
Thank you.

Best
Jiang

mask_def:0.075 
snaphu_interp.csh 0.001

sbas log:
compute RMS misfit
compute DEM error

setting smoothing to   0.100 
setting radar wavelength to   0.055 m 
setting radar incidence angle to  37.000 degree 
setting range to 898971.000 m 
Memory Allocation Successful...
read table file ...
number of SAR scenes is 5 
number of interferograms is 8 
read phase and correlation grids ...
0.100000 0.000419 0.000000 -33.408131
fill the G matrix ...
run least-squares problem over 5788 by 2309 pixel (0) ...
matrix is rank-deficient: 
write output ...

[intf (复件).tab.txt](https://github.com/gmtsar/gmtsar/files/4865669/intf.tab.txt)
[scene (复件).tab.txt](https://github.com/gmtsar/gmtsar/files/4865670/scene.tab.txt)
![2019159_2019219](https://user-images.githubusercontent.com/65638654/86389099-690a8680-bcc8-11ea-8a97-f1e30d8c4729.png)
![2019351_2020058](https://user-images.githubusercontent.com/65638654/86389103-6a3bb380-bcc8-11ea-8375-b65c0fc94ef6.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Jiang,
When you unwarp with mask_def.grd, you probably need to use a very low threshold for snaphu.csh, as pixels are supposed to be masked by the defined mask only.
i.e. snaphu.csh 0.0001 0 [rng_min/rng_max/azi_min/azi_max]
Xiaohua(Eric)

**Comment by jiang1880023** [comment]
Hello Eric,
Thanks for your help. Beacause the processing takes too long so I try the command :
snaphu_interp.csh .0001 0 24000/30000/3100/3800.
But I find the dimension between corr.grd and unwrap.grd is difference. And it causes a error when I do SBAS processing.What can I do to fix this?
Thanks a lot
BEST
Jiang

corr.grd：5788 x 2309    unwrap.grd：750 x 350

**Comment by jiang1880023** [comment]
Hello Eric,
I solved the dimensions error by using the corr_batch.grd to replace corr.grd. But it is still all zero value in vel.grd. I have used the command:
snaphu_interp.csh .0001 0 24000/30000/3100/3800.
And for most of pixels, it seems like there is values in every image. Is there any other possible cause for this error? 
Thanks
BEST
Jiang

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Jiang,
Could you change your columns of dates to numbers only? e.g. S1_20190609_ALL to 2019195. In both tab files.
Cheers,
Xiaohua(Eric)

**Comment by jiang1880023** [comment]
Hi Eric,
I really appreciate your help. It works.
Thank you very much.
BEST
Jiang
