### ISSUE TITLE
[Help]: How to downsample the unwarpped_ll.grd for inversion

### ISSUE THREAD

**Issue by Xiongwei789** [gmtsar/gmtsar#250]
Hello everyone，
I have obtained the unwrapped.grd file. The displacement is related to an earthquake. Now I want to extract the deformation information as close to the fault as possible. The quadtree algorithm may be a suitable method to downsample for fast and stable inversions. There are some codes published on Github, but they can not identify the format of GMTSAR output. 
So is there a downsampling program suitable for GMTSAR? 
Xiongwei

**Comment by Xiaohua-Eric-Xu** [comment]
There is no downsampling program in GMTSAR other than `grdsample`. You could however, convert the output grid to any format you want using GMT.

**Comment by Xiongwei789** [comment]
Thank you.
