### ISSUE TITLE
[Help]: High-pass filter

### ISSUE THREAD

**Issue by TakaNgc** [gmtsar/gmtsar#251]
I am using [p2p_processing.csh] to analyze displacements that occur over a small area, such as a landslide.
For this purpose, I would like to use a high-pass filter to remove the noise that occurs at spatially long wavelengths (e.g., 1000m scale).
Is there a high-pass filter in GMTSAR's functions?

**Comment by Xiaohua-Eric-Xu** [comment]
You could high-pass filter the results with gmt grdfilter. Also note if you want to do this, you probably need to define very small filter-wavelength and decimation factors. And for projection, you need to experiment with the needed gauss_xxx file to specify the correct sampling for geocoding.

**Comment by TakaNgc** [comment]
Thank you for your answer.

I am using p2p_processing.csh to analyze the ALOS2 data.
Could you please tell me about the parameter file (config.alos.txt) for applying the high-pass filter?

The default value of config.alos.txt is as follows.
-------------------------------------------------------------------------------
####################################################
# parameters for make and filter interferograms #
# - intf.csh #
# - filter.csh #
####################################################
# switch the master and slave when doing intf. 
# put "1" if assume master as repeat and slave as reference 
# put "0" if assume master as reference and slave as repeat [Default].
# phase = repeat phase - reference phase
switch_master = 0

# set the filter wavelength in meters (default is 200m)
# this is the wavelength where the filter has a gain of 0.5
# the images will be sampled at 1/4 wavelength or smaller
filter_wavelength = 200

# decimation of images 
# decimation control the size of the amplitude and phase images. It is either 1 or 2.
# Set the decimation to be 1 if you want higher resolution images.
# Set the decimation to be 2 if you want images with smaller file size.
# Set the decimation to be 2 if you want images with smaller file size. 
dec_factor = 2
-------------------------------------------------------------------------------

When I apply a high-pass filter to remove noise at wavelengths higher than 1000m, what values should I set for [filter_wavelength] and [dec_factor]?
