### ISSUE TITLE
[Help]: prep_data_linux.csh url_root error

### ISSUE THREAD

**Issue by aramfathian** [gmtsar/gmtsar#253]
Hi,

Running `prep_data_linux.csh` to creat "data.in" file ends up with the following url_root error:

`rm: cannot remove 'data.in': No such file or directory
Looping over all the lines
Setting a new name for rec
Writing record 20170612
url_root: Undefined variable.`

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, could you delete orbits.list and then try again?

**Comment by aramfathian** [comment]
now I have the following error:

> rm: cannot remove 'data.in': No such file or directory
> to: Command not found.
> grep: orbits.html: No such file or directory
> rm: cannot remove 'orbits.html': No such file or directory
> Looping over all the lines
> Setting a new name for rec
> Writing record 20170612
> if: Missing file name.

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, strange below. Did you change the script?
``` 
to: Command not found.
```

**Comment by aramfathian** [comment]
Yes, I tried to solve the url_root variables.
I just reinstalled GMTSAR.; `to: Command not found.` is gone, but the error still exists:
`rm: cannot remove 'data.in': No such file or directory
Looping over all the lines
Setting a new name for rec
Writing record 20170612
if: Missing file name.`

**Comment by Xiaohua-Eric-Xu** [comment]
1) Did you modify as described in the script to alias at the beginning of the script?
2) Did the script manage to download orbits.list? Does it contain valid records?

**Comment by aramfathian** [comment]
1. Yes, I added the alias wgetasf and the credentials to the prep_data_linux.csh
2. in the first run it could manage to generate the orbit.list. After deleting the orbit.list, now it only generates an empty orbit.list

**Comment by Xiaohua-Eric-Xu** [comment]
If you run the following command, could you get an orbits.list?
```
set url_root = "https://s1qc.asf.alaska.edu/aux_poeorb/"
wget $url_root -O orbits.html
grep EOF orbits.html | awk -F'"' '{print $2}' > orbits.list
```

**Comment by aramfathian** [comment]
`wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.`

**Comment by aramfathian** [comment]
`wget: missing URL`
`Usage: wget [OPTION]... [URL]...`

**Comment by Xiaohua-Eric-Xu** [comment]
I am confused. Did this line fail? You probably need to switch to csh first.
```
set url_root = "https://s1qc.asf.alaska.edu/aux_poeorb/"
```

**Comment by aramfathian** [comment]
the `wget $url_root -O orbits.html` fails.
I reinstalled GMTSAR again. No further changes compared to the last installation, but this time it generated the data.in

**Comment by aramfathian** [comment]
Now I am stuck in the next stage: preproc_batch_tops.csh, mode 1
I have cropped the data using pins via organize_files_tops_linux.csh, and imported only swath1 to the raw folder. Not sure if I am doing it right,
[log.txt](https://github.com/gmtsar/gmtsar/files/7610906/log.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
It says it could not open the xml file. May you check the access permissions of the files?
```
 Couldn't open xml file: 
 s1b-iw1-slc-vv-20170612t140301-20170612t140312-006018-00a901-004.xml 
```

**Comment by aramfathian** [comment]
running through either owner account and root yields the same error. 
Tried to change the owner of the files to root, but chown/sudo chown doesn't change the owner
