### ISSUE TITLE
[Help]: Surface [WARNING]: Unusable Points, Should Pre-process data, etc.

### ISSUE THREAD

**Issue by lumirinc** [gmtsar/gmtsar#254]
Hi, 

While p2p processing, I am getting the following warnings. I was trying to understand these warnings, the first warning is probably due to a very small threshold value. Does this make any impact on the final outcome?

p2p_S1_TOPS_Frame.csh S1A_IW_SLC__1SDV_20210928T012454_20210928T012521_039875_04B7BB_B74A.SAFE S1A_OPER_AUX_POEORB_OPOD_20211018T122536_V20210927T225942_20210929T005942.EOF S1A_IW_SLC__1SDV_20211010T012454_20211010T012521_040050_04BDC3_A61C.SAFE S1A_OPER_AUX_POEORB_OPOD_20211030T122629_V20211009T225942_20211011T005942.EOF S1_config.txt vv 1 > log.txt
Number of Files to be merged is 3 
Number of Files to be merged is 3 
Number of Files to be merged is 3 
phase_patch.grd landmask_ra_patch.grd MUL = phase_patch.grdWorking on line 6535 ...
unwrap.grd landmask_ra_patch.grd MUL = tmp.grdsurface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [WARNING]: 4512437 unusable points were supplied; these will be ignored.
surface [WARNING]: You should have pre-processed the data with block-mean, -median, or -mode.
surface [WARNING]: Check that previous processing steps write results with enough decimals.
surface [WARNING]: Possibly some data were half-way between nodes and subject to IEEE 754 rounding.
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [WARNING]: 4512437 unusable points were supplied; these will be ignored.
surface [WARNING]: You should have pre-processed the data with block-mean, -median, or -mode.
surface [WARNING]: Check that previous processing steps write results with enough decimals.
surface [WARNING]: Possibly some data were half-way between nodes and subject to IEEE 754 rounding.
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=pngalpha  -g5171x3541 -r1800 -sOutputFile='phasefilt_ll.png' './psconvert_16128d.eps'
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=pngalpha  -g5171x3541 -r1800 -sOutputFile='phasefilt_mask_ll.png' './psconvert_16188d.eps'
grdimage [WARNING]: Your image is grayscale only but -Q requires 24-bit; image will be expanded to 24-bit.
PSL: Colormap of 252 colors created
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=pngalpha  -g5171x3541 -r1800 -sOutputFile='corr_ll.png' './psconvert_16214d.eps'
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=pngalpha  -g5171x3541 -r1800 -sOutputFile='unwrap_mask_ll.png' './psconvert_16352d.eps'
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=pngalpha  -g5171x3541 -r1800 -sOutputFile='unwrap_ll.png' './psconvert_16386d.eps'
rm: No match.

**Comment by lumirinc** [comment]
After the above process, I got unwrapped interferogram however on geocoding I got these errors.

gmtsar-user@gmtsarVB:~/InSAR/Balochistan_07Oct2021_EQ5p9/asc/merge$ geocode.csh 0.01 unwrap.grd 
corr.grd 0.01 GE 0 NAN mask.grd MUL = mask2.grdgrdmath [ERROR]: Syntax error: phase.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phase_mask.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phase_mask.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphase_mask.grd
psconvert [ERROR]: The file phase_mask.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
Masked phase map: phase_mask.pdf
Unwrapped masked phase map: unwrap_mask.pdf
Filtered masked phase map: phasefilt_mask.pdf
Line-of-sight map: los.pdf
geocode.csh
project correlation, phase, unwrapped and amplitude back to lon lat coordinates
remarked is by gmtsar-user on Thu 25 Nov 2021 03:56:16 PM KST with geocode.csh
proj_ra2ll.csh
Sampling in geocoordinates with 50 meter pixels ...
proj_ra2ll.csh
Sampling in geocoordinates with 50 meter pixels ...
proj_ra2ll.csh
grd2xyz [ERROR]: File phase_mask.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
Sampling in geocoordinates with 50 meter pixels ...
gmtinfo [ERROR]: No input data found!
range: Subscript out of range.
gmtmath [ERROR]: Syntax error: Operation "DIV" requires 2 operands
gmtmath [ERROR]: Syntax error: Operation "MUL" requires 2 operands
gmtinfo [ERROR]: No input data found!
blockmedian [ERROR]: Unable to decode  as a floating point number
xyz2grd [ERROR]: Unable to decode  as a floating point number
grdedit [ERROR]: Error for input file: No such file (phase_mask_ll.grd)
proj_ra2ll.csh
grd2xyz [ERROR]: File display_amp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
Sampling in geocoordinates with 50 meter pixels ...
gmtinfo [ERROR]: No input data found!
range: Subscript out of range.
gmtmath [ERROR]: Syntax error: Operation "DIV" requires 2 operands
gmtmath [ERROR]: Syntax error: Operation "MUL" requires 2 operands
gmtinfo [ERROR]: No input data found!
blockmedian [ERROR]: Unable to decode  as a floating point number
xyz2grd [ERROR]: Unable to decode  as a floating point number
grdedit [ERROR]: Error for input file: No such file (display_amp_ll.grd)
proj_ra2ll.csh
Sampling in geocoordinates with 50 meter pixels ...
proj_ra2ll.csh
Sampling in geocoordinates with 50 meter pixels ...
proj_ra2ll.csh
Sampling in geocoordinates with 50 meter pixels ...
geocode.csh
make the KML files for Google Earth
grdinfo [ERROR]: Error for input file: No such file (display_amp_ll.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
gmtmath [ERROR]: Syntax error: Operation "INV" requires 1 operands
grdimage [ERROR]: Error for input file: No such file (display_amp_ll.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
Make display_amp_ll.kml and display_amp_ll.png
psconvert [ERROR]: The file display_amp_ll.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
grdimage [WARNING]: Your image is grayscale only but -Q requires 24-bit; image will be expanded to 24-bit.
PSL: Colormap of 252 colors created
Make corr_ll.kml and corr_ll.png
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=pngalpha  -g5171x3541 -r1800 -sOutputFile='corr_ll.png' './psconvert_16890d.eps'
grdinfo [ERROR]: Error for input file: No such file (phase_mask_ll.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
gmtmath [ERROR]: Syntax error: Operation "INV" requires 1 operands
grdimage [ERROR]: Error for input file: No such file (phase_mask_ll.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
Make phase_mask_ll.kml and phase_mask_ll.png
psconvert [ERROR]: The file phase_mask_ll.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
Make phasefilt_mask_ll.kml and phasefilt_mask_ll.png
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=pngalpha  -g5171x3541 -r1800 -sOutputFile='phasefilt_mask_ll.png' './psconvert_16936d.eps'
Make unwrap_mask_ll.kml and unwrap_mask_ll.png
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=pngalpha  -g5171x3541 -r1800 -sOutputFile='unwrap_mask_ll.png' './psconvert_16965d.eps'
Make phasefilt_mask_ll.kml and phasefilt_mask_ll.png
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=pngalpha  -g5171x3541 -r1800 -sOutputFile='phasefilt_mask_ll.png' './psconvert_16991d.eps'
Make los_ll.kml and los_ll.png
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=pngalpha  -g5171x3541 -r1800 -sOutputFile='los_ll.png' './psconvert_17024d.eps'

**Comment by Xiaohua-Eric-Xu** [comment]
Hi I think geocode.csh could not run properly in merge directory. If you look inside the script, it'll geocode a list of files and not all of them are produced in the merge folder. I would try proj_ra2ll.csh to geocode individual needed files. You probably need to copy over the gauss_xxx file over. 
Another question is did the p2p script produce geocoded product? Why is another round of geocoding needed?
