### ISSUE TITLE
[Help]: Different Doppler Centroids in Align

### ISSUE THREAD

**Issue by sase1988** [gmtsar/gmtsar#256]
Hello,

I am trying to run align_ALOS_SLC.csh with a pair formed between a SAOCOM-1A and a SAOCOM-1B images.

When I run slc2amp.csh to check the results I see the images are shifted in azimuth direction. What I also note is that the Doppler Centroid between SAO1A and SAO1B is quite different (I attach the PRM files). Can this affect the align process, or the slc2amp.csh that I use to visualize the results?

Note: I don't get this problem in paris where I use only SAO1A or SAO1B, between the which there are not important differences in Doppler Centroid

Thank you
Santiago

[PRMs.zip](https://github.com/gmtsar/gmtsar/files/7610233/PRMs.zip)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Santiago,
The doppler centroid affect the position along azimuth and that part of calculation could be found in SAT_llt2rat.c. You need to have that specified in PRM in order to let things work properly.
Doppler difference are common for earlier satellites like ERS. As long as the spectrum has enough overlap, the processing should be fine. It might be better to focus them to a specific doppler in between (this needs to be done manually I think). Actually, yours don't look too far away and focusing directly to zero doppler should work.  
I am not sure why slc2amp.csh will cause azimuth shift as it is just taking in the SLC and convolve it with a filter to get amplitude image. 
Xiaohua(Eric)

**Comment by Xiaohua-Eric-Xu** [comment]
Oh, I think I may understand what you meant. So after slc2amp.csh on the two images, the same feature has different position in azimuth. You probably need to focus them to the same doppler centroid before alignment?

**Comment by sase1988** [comment]
Hi Xiaohua,

I normally have no access to the L0 images, but I will ask CONAE if they can re-process them in order to focus them to similar DC. Yesterday I manually changed fd1 and fdd1 in the SAO1B PRM file to make it similar to the SAO1A one, and the alignment worked correctly.

However I still have a doubt and it is when is SAT_llt2rat used when running align_ALOS_SLC.csh? I found the latter calls SAT_baseline but could not find another reference to  SAT_llt2rat inside it.

Thank you
Santiago

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Santiago,
You could also try the geocode_slc.c and check on the amplitude to see whether they are at the right location. 
SAT_llt2rat is not used in align_ALOS_SLC.csh. I mean doppler is considered when doing geocoding. 
Cheers,
Xiaohua(Eric)

**Comment by sase1988** [comment]
I'm sorry Xiaohua, I mean why does the difference in fd1 and fdd1 values causes a mis-alignment in azimuth after the coregistration? I have tried the alignment (coregistration) with the same pair in ISCE and it has no trouble despite this difference.

Cheers,
Santiago

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Santiago,
I don't think it should affect the coregistration. The script is really simple that it uses xcorr outputs to estimate the needed affine transformation parameter and then resampled the repeat image with those parameters. It was designed to work with ALOS SLC data, and there are parts that could be tuned, (e.g. fitoffset.csh a b data [SNR], a b and SNR will affect the results.) but I am not sure how much difference it'll make.
One question is when you say the image is shifted in azimuth, how large is that shift? Could you show the image so I could rule out some cases?
Also after resampling, the repeat PRM should contain the offset parameters estimated. Could you send that PRM as well?
Cheers,
Xiaohua(Eric)

**Comment by sase1988** [comment]
Hi Xiaohua

The shift in az is about 137 lines, I enclose an example. SAO1A is the reference and SAO1B is the repeat image.
I also enclose the PRM files for that example, the repeat PRM has the ashift and rshift computed. You will see the ashift seems quite big but between SAO1A images this has not been a problem in the past.

Cheers
Santiago


![az_shift](https://user-images.githubusercontent.com/36776334/144156844-7bae96f0-0cdd-42ff-a722-b70606249daa.png)
[SAO1_PRMs.zip](https://github.com/gmtsar/gmtsar/files/7630048/SAO1_PRMs.zip)

**Comment by Xiaohua-Eric-Xu** [comment]
OK. When you run SAT_baseline on the radar image, is it giving you a large shift? The PRM says 4717 along azimuth
xcorr will initially estimate the offset based on that shift and search for optimal offset within a search window. Then a more accurate set of shift parameters are updated based on the results from xcorr. 
I suspect the search window size for xcorr is not able to handle that much amount of shift. (current window size in align_ALOS_SLC.csh is 64). If you increase that to 256 or even larger, does that help? 
If that doesn't help, could you send the SLC, PRM and LED files in your raw directory and I can make a test here?

**Comment by sase1988** [comment]
Yes, it worked by increasing the window size!

Indeed SAT_baseline gave an initial ashift of -4685
However, the problem is also present with other pairs with smaller ashift. Por example SAO1A_20211112 vs SAO1B_20211120 (initial ashift 1007). I could also align them correctly by increasing the window size.

I leave you a raw data directory in this [link](https://drive.google.com/drive/folders/1vLRJkZAggVDCk1BF9eCrF6n4rd9yGUFv?usp=sharing) in case you want to try anything else

Cheers

**Comment by Xiaohua-Eric-Xu** [comment]
Glad it worked out! We should get an individual setup for SAOCOM.

**Comment by sase1988** [comment]
Yes! Anyways I think CONAE should focus the images to similar DC

Thanks for your help!
Santiago

**Comment by dsandwell** [comment]
I have been following this discussion.  Now that you know the azimuth shift that aligns the images, please try the following.

1) Set all the shifts in both PRM files to zero but make sure the fd1 is correct for both images.  They should be different.

2) Run SAT_baseline and note the predicted a_shift.  This should be within a few pixels of the actual a_shift.  

If they are not close we need to fix the GMTSAR code.  This could be an issue of the start time or the orbit file being wrong.


> On Dec 1, 2021, at 9:23 AM, sase1988 ***@***.***> wrote:
> 
> 
> Yes! Anyways I think CONAE should focus the images to similar DC
> 
> Thanks for your help!
> Santiago
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by sase1988** [comment]
Hi David,

SAT_baseline gives me an ashift of -4686. The actual one should be around -4838

As an additional test i forced manually fd1 to be similar and after that SAT_baseline gave me an ashift of -4832

Best

**Comment by dsandwell** [comment]
What happens if you force both fd1 to zero?  If that works then the only issue will be how the topo_ra.grd aligns with the reference image.  If the topography_ra.grd is aligned with the amplitude images then the solution is to set the fd1 to zero in the pre-processing code.  They could report on the Doppler centroid but then actually focus the image at zero Doppler.

If that works there is a parameter in the config.txt file called

shift_topo

Try this with both 0 and 1.  

The data are L-band so you may need a slight range shift to get better alignment.


> On Dec 1, 2021, at 11:02 AM, sase1988 ***@***.***> wrote:
> 
> 
> Hi David,
> 
> SAT_baseline gives me an ashift of -4686. The actual one should be around -4838
> 
> As an additional test i forced manually fd1 to be similar and after that SAT_baseline gave me an ashift of -4832
> 
> Best
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by sase1988** [comment]
If I force both fd1 to 0 I also get ashit = -4832 which is  ok.

However, last year I did set fd1 and fdd1 to 0 and this gave me problems at the moment of   geocoding, as we discussed here with Xiaouxua: http://gmt.soest.hawaii.edu/boards/6/topics/8477. So I had to start computing them.

**Comment by sase1988** [comment]
Hello David and Xiaouxua,

I went on yesterday and I built an interferogram for a pair but I believe this difference in DC causes a degradation in the coherence. I made some comparisons with the processing with ISCE and I got the results I enclose. Both plots are scaled to the same values, and both grids have been multilooked using the same factor.

Do you believe that once I get the images re-processed to the same DC the coherence might improve?

Best,
Santiago

![histCorr](https://user-images.githubusercontent.com/36776334/144445121-e2b7331e-6927-4ba7-abe6-8262e30232c4.png)
![corr](https://user-images.githubusercontent.com/36776334/144445125-7bc6048b-2f70-40da-bb51-c6e07950ad09.png)

**Comment by dsandwell** [comment]
Hi Santiago,

These results look good.  I do not think the difference in coherence is caused by the different DC.  We have compared coherence between ISCE and GMTSAR abd they are always different even in cases where the phase is identical. GMTSAR always has lower coherence but I don not think this has any effects on the phase noise.  I believe ISCE has two different ways of computing coherence.

So I think your results are good.  It would be interesting to compare the phase from the two softwares as well as the unwrapped phase.

David

> On Dec 2, 2021, at 6:49 AM, sase1988 ***@***.***> wrote:
> 
> 
> Hello David and Xiaouxua,
> 
> I went on yesterday and I built an interferogram for a pair but I believe this difference in DC causes a degradation in the coherence. I made some comparisons with the processing with ISCE and I got the results I enclose. Both plots are scaled to the same values, and both grids have been multilooked using the same factor.
> 
> Do you believe that once I get the images re-processed to the same DC the coherence might improve?
> 
> Best,
> Santiago
> 
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by sase1988** [comment]
Hi Eric,

I know it is difficult to compare since they are different times, but my 16-day interferograms with SAO1A images having similar DC show much better coherence compared to these ones. That is why I think this difference might be affecting the quality of coregistration and therefore the coherence.

Best,


![dc_comp](https://user-images.githubusercontent.com/36776334/145053661-3b428d02-614e-4dae-9f46-552d8a0a3318.png)
