### ISSUE TITLE
[Help]: snaphu MAT

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#257]
I put 2  iw to run snaphu.
The program takes a long time.（3-4days and no unwrap.grd）
Is it not converge？
Thanks.

**Comment by Xiaohua-Eric-Xu** [comment]
SNPHU is really non-linear, with the run-time depend on 1) size of your image; 2) how decorrelated it is; Do you mind sending your coherence image and the output from `gmt grdinfo phasefilt.grd`

**Comment by swjiaotong-jyliu** [comment]
Thanks for your reply.
This is phasefilt.grd.
![KX%W3WUS72@}UFM14`P9$1F](https://user-images.githubusercontent.com/86451834/144701241-36a3df87-e763-4f59-a80e-edf8bf06e1cb.png)
Is it because he has relatively low relevance.

Besides,good inter couple like this.
![@R_`M 2`_W({U IK5 D6}3P](https://user-images.githubusercontent.com/86451834/144701330-2263aa74-bfb3-45e3-bd42-c847a3e97b42.png)
But when i choose a region to snaphu.
The water region may have values.
![C(@J51 9M2HNY0GOTR4A6LR](https://user-images.githubusercontent.com/86451834/144701439-95ccb7b5-413c-4c0c-84a3-68335ae30301.png)
 
I use mask_water = 1
It seems that the merge_batch.csh does not use him


Thanks again for your reply

**Comment by Xiaohua-Eric-Xu** [comment]
Could be related to this issue that mask_water is not working properly due to the not up-to-date script that uses GMT. I haven't got time to update this. https://github.com/gmtsar/gmtsar/issues/248

**Comment by Xiaohua-Eric-Xu** [comment]
SNAPHU will waste its time on wet region in this case.

**Comment by swjiaotong-jyliu** [comment]
Thanks for your reply. I understand why this happens in every August per year. I used to think the reason is poor relevance. May it's seasonal rain now. Is there any good way to solve it？ I want to get the unwarp.grd Thanks for your reply.

**Comment by Xiaohua-Eric-Xu** [comment]
My personal solution is to 1) determine the boundaries of your grid using `gmt grdinfo -I- phasefilt.grd`
then run `landmask.csh` with a range larger than what you get, e.g. extend your region by 100.

**Comment by swjiaotong-jyliu** [comment]
Thanks，I will try.
