### ISSUE TITLE
Merge problem 

### ISSUE THREAD

**Issue by sunzhe-96** [gmtsar/gmtsar#259]
Dear all
 Hello,Eric, If I don’t want to merge fille, can I unwrap it directly in the intf_all file?

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, you can. But for geocoding use the trans.dat that goes with the subswath. i.e. F?/topo/trans.dat

**Comment by Xiaohua-Eric-Xu** [comment]
Also, for such kind of general questions. You could try our new Discussion page here on Github, which is supposed to be more interactive. https://github.com/gmtsar/gmtsar/discussions

**Comment by sunzhe-96** [comment]
> Also, for such kind of general questions. You could try our new Discussion page here on Github, which is supposed to be more interactive. https://github.com/gmtsar/gmtsar/discussions

OK，Eric, thanks for your reply.
