### ISSUE TITLE
Gaps in merged swaths

### ISSUE THREAD

**Issue by Mieszko-Fydrych** [gmtsar/gmtsar#26]
Hello,

After running the unwrap_int.csh command, I checked the unwrap.pdf files of a few merges and they all have gaps between the swaths. Example:
[unwrap.pdf](https://github.com/gmtsar/gmtsar/files/4881198/unwrap.pdf)

Looking at the phasefilt.grd files, most of them appear fine but some have gaps.
Example:
![Screenshot from 2020-07-06 17-12-37](https://user-images.githubusercontent.com/61254441/86644973-fd683800-bfab-11ea-88d5-b7496fd10b90.png)

What could be causing this issue?

Thanks,
Mieszko

**Comment by dsandwell** [comment]
Hi Mieszko,

I believe these small gaps are real.  During the operation of the satellite, the near-range is adjusted to accommodate the changes in altitude due to the elliptical shape of the Earth.  In this case the adjustment was not quite accurate.  

Does the merging in radar coordinated work?  Can you unwrap the phase across this gap?

David

> On Jul 6, 2020, at 2:16 PM, Mieszko-Fydrych <notifications@github.com> wrote:
> 
> 
> Hello,
> 
> After running the unwrap_int.csh command, I checked the unwrap.pdf files of a few merges and they all have gaps between the swaths. Example:
> unwrap.pdf
> 
> Looking at the phasefilt.grd files, most of them appear fine but some have gaps.
> Example:
> 
> 
> What could be causing this issue?
> 
> Thanks,
> Mieszko
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by Mieszko-Fydrych** [comment]
Hello David,

I was able to unwrap the phase across the gap. I was actually able to produce final results even with the gap, as shown here:
![Screenshot from 2020-07-07 12-37-55](https://user-images.githubusercontent.com/61254441/86813913-b8e1a880-c04e-11ea-9bc3-5cc9335ca046.png)

What is interesting to me, is that the gap is not consistent. For example, the image shown above was created using the dates 2016021 and 2016033. Checking other filtered phase images created using 2016033, some of them have gaps while others do not.
A merge between 2016009 and 2016033 shows a gap, but 2016033 and 2016045 when merged does not.

2016009_2016003 phasefilt.grd:

![Screenshot from 2020-07-07 12-47-19](https://user-images.githubusercontent.com/61254441/86815078-407be700-c050-11ea-99d2-9c3f023b2bcb.png)


2016033_2016045 phasefilt.grd:

![Screenshot from 2020-07-07 12-47-30](https://user-images.githubusercontent.com/61254441/86815123-4c67a900-c050-11ea-992a-c7cb8c166e8a.png)

And when I check another filtered phase image using 2016009, I also do not see a gap. So it does not seem like a particular scene is consistently causing this issue.

Do you have any recommendations for dealing with this?

Thanks a lot,
Mieszko

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Mieszko,
There is a parameter in merge_swath.c (n1 and n2), theoretically you could tune these two numbers to merge seamlessly. However, I have seen cases that the burst could not connect no matter what (a pair of the Idaho earthquake). For now, these two parameters are set close to the middle of the overlapping area. The reason could be that the burst has unstable first_valid_sample/last_valid_sample. This also happens when you process a very long interferogram and the valid_samples sometimes shift along the orbit.
Cheers,
Xiaohua(Eric)

**Comment by Mieszko-Fydrych** [comment]
Hello Xiaohua,

I will try to tune the numbers and see what results I can get. Would it perhaps just be better to find the images causing the issues and remove them from the data set?

Thanks,
Mieszko

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Mieszko,
Sorry I didn't realize your last sentence was a question. Yes, you could, or manually set a number that could work with it and simply re-run the merging.
Cheers,
Xiaohua(Eric)

**Comment by Gigi-gugu** [comment]
![IW2](https://user-images.githubusercontent.com/92804122/181351976-ef55a870-fcb9-44e5-876c-149ec87f9b95.jpg)
![IW3](https://user-images.githubusercontent.com/92804122/181351983-780e3f29-bbe3-4e52-8eef-509e14ac0cf1.jpg)
![merge](https://user-images.githubusercontent.com/92804122/181351988-b4092743-027e-44d6-a471-2dabeb465ce6.jpg)

Hello, Eric

For sentinel data, when I merge iw2 and iw3, there is also a gap problem. How can I solve this problem? The following is the crop region of my iw2 and iw3.
IW2, region_cut = 15000/25000/500/2000
IW3,region_cut = 500/10000/1400/3000

**Comment by Xiaohua-Eric-Xu** [comment]
I would not cut the last (may be a couple of hundreds of ) columns on IW2 and first 500 columns on IW3. 

Another parameter you could turn on is the det_stitch for merge_unwrap_geocode_tops.csh or merge_batch.csh

**Comment by Gigi-gugu** [comment]
The problem has been solved. Thank you. If I want to get the last column of iw2, in the region_ Cut = 15000/25000/500/2000. How to get the maximum value of the second parameter? I didn't do this. I set 25200

**Comment by Xiaohua-Eric-Xu** [comment]
It could be get from the num_rng_bins in your master PRM file.

**Comment by CUMT530849827** [comment]
@Xiaohua-Eric-Xu Hello, professor, when I used GMTSAR to process S1A and S1B, there was a gap in all the results. When I tried to splice with merge_swath, the following error was reported. But I know my computer has enough memory
![image](https://user-images.githubusercontent.com/49933485/205321899-3a764c1b-4574-415f-a5a9-f5dd7a2c2f05.png)
![image](https://user-images.githubusercontent.com/49933485/205322012-d5b587e4-ecb7-4b33-86aa-a2b6b8a470f0.png)
![image](https://user-images.githubusercontent.com/49933485/205322422-b1eee970-6e3b-4999-9539-7273eb40a1a2.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Try turning on `det_stitch = 1` in your config file.
