### ISSUE TITLE
[Help]: error in region_cut and filter processing (something strange in the edge of the image)

### ISSUE THREAD

**Issue by ijnokmp** [gmtsar/gmtsar#261]
Dear GMTSAR developers and users,

when I cut a small region to process one subswath of S1 TOPS data (fill the region_cut in the configure file), it seems that something went wrong in the filter processing. The phase_mask_ll.png looks nice but there is something strange in the edge of phasefilt_mask_ll.png. I also tried align_tops_esd.csh and the strange edge became narrow but still exists. Therefore the following unwrapping processing can not be carried out. 

Another question, the error "hermite: interpolation not in center interval"  always came in the pre_proc.csh processing. I have tried the method mentioned in the github and also in the GMTSAR forum, I used GMTSAR 6.1 and the right orbit data and tried to make a relative large area (three bursts in every subswath) but it did not work.

P.S. OS: CentOS Linux release 8.4.2105

Could you give me any suggestion on these? Looking forward to hearing from you!

Thanks!

![phase_mask_ll](https://user-images.githubusercontent.com/96293813/146543571-5f7a86e8-b5e2-4e2a-95ad-f31391ff6e7e.png)
![phasefilt_mask_ll](https://user-images.githubusercontent.com/96293813/146543586-fde0ae76-9f31-4c43-9c94-c783b16fd5c7.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi The edges are from phasefilt, which uses a spectral filter. The edge is related to the patch size I think. But I am not sure what you mean that the following unwrapping could not be carried out. 
Could you send a log file that records the terminal output when you see that error?

**Comment by ijnokmp** [comment]
Attached is the log file of p2p_processing.csh. What I mean is that the unwrapping comes to errors due to the strange edge produced by filter and the unwrapping results can not be generated. It would be nice you can also give me advice on the hermite error.

And another question, what is the optimal way you think to cut a small AOI which covers two subswaths? What I am trying to do is processing data and cutting the AOI of each subswath and merging them, but I have no idea if I can merge them due to the strange edge. Thank you!

[p2p_processing.log](https://github.com/gmtsar/gmtsar/files/7736660/p2p_processing.log)

**Comment by ijnokmp** [comment]
> 

Hi Eric,

The reported unwrapping errors are as followings,

SNAPHU.CSH - START
threshold_snaphu: 0.2
grdcut [ERROR]: Requested subset is entirely to the left or to the right of the current data region
grdcut [ERROR]: Requested subset is entirely to the left or to the right of the current data region
grdcut [ERROR]: Requested subset is entirely to the left or to the right of the current data region
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files
grdmath [INFORMATION]: Perform reverse Polish notation calculations on grids
grdmath [ERROR]: phase_patch.grd is not a number, operator or file name
grdmath [ERROR]: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: mask2_patch.grd is not a number, operator or file name
grdmath [ERROR]: mask2_patch.grd is not a number, operator or file name
nearest_grid [ERROR]: Cannot find file phase_tmp.grd
nearest_grid [ERROR]: Cannot find file phase_tmp.grd
nearest_grid [ERROR]: File phase_tmp.grd not found
[Session nearest_grid (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open grdfile phase_tmp.grd 
Setting search radius to be 300 ...
Reading in original grid...
mv: cannot stat 'tmp.grd': No such file or directory
grd2xyz [ERROR]: Cannot find file phase_tmp.grd
grd2xyz [ERROR]: Cannot find file phase_tmp.grd
grd2xyz [ERROR]: File phase_tmp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
grd2xyz [ERROR]: Cannot find file corr_tmp.grd
grd2xyz [ERROR]: Cannot find file corr_tmp.grd
grd2xyz [ERROR]: File corr_tmp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
unwrapping phase with snaphu - higher threshold for faster unwrapping 
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files
...

But the cut region was set before aligning and the filtering can be carried out. Is this error related to the strange edge generated by the filtering? This situation appeared in many interferograms. Could you give me some suggestions that how to avoid these kinds of edges and unwrapping errors? 

Thank you in advance. Looking forward to hearing from you!

**Comment by Xiaohua-Eric-Xu** [comment]
I see. This might be a bug from the p2p_processing.csh where it cut the SLC with region_cut directly and then applied another region_cut at stage 5. I made a change deleting the second one 51d5b3c0e1f245736647d5eb043192a54e203faf .
Do you mind helping us test it on your case?

**Comment by ijnokmp** [comment]
Thank you! It works well for my case after modifying the code you suggested. But there are still strange edges in the filtering and unwrapping results. Could you also give me any suggestions on this?
![20211028_20211103_phasefilt_mask_ll](https://user-images.githubusercontent.com/96293813/148295695-b28b9174-86da-4405-8107-371eff6e0882.png)
![20211028_20211103_unwrap_mask_ll](https://user-images.githubusercontent.com/96293813/148295644-a1c16d3b-5b8b-48e9-b9bd-43a8d2b80d45.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Yeah. Like I said, it comes from the Goldstein filter program. You could use phase.grd to replace phasefilt.grd if you don't want that filter. Or you could perform a secondary grdcut to remove the edges.

**Comment by ijnokmp** [comment]
Ok, thank you so much for your suggestions!

**Comment by weibangding** [comment]
> Dear GMTSAR developers and users,
> 
> when I cut a small region to process one subswath of S1 TOPS data (fill the region_cut in the configure file), it seems that something went wrong in the filter processing. The phase_mask_ll.png looks nice but there is something strange in the edge of phasefilt_mask_ll.png. I also tried align_tops_esd.csh and the strange edge became narrow but still exists. Therefore the following unwrapping processing can not be carried out.
> 
> Another question, the error "hermite: interpolation not in center interval" always came in the pre_proc.csh processing. I have tried the method mentioned in the github and also in the GMTSAR forum, I used GMTSAR 6.1 and the right orbit data and tried to make a relative large area (three bursts in every subswath) but it did not work.
> 
> P.S. OS: CentOS Linux release 8.4.2105
> 
> Could you give me any suggestion on these? Looking forward to hearing from you!
> 
> Thanks!
> 
> ![phase_mask_ll](https://user-images.githubusercontent.com/96293813/146543571-5f7a86e8-b5e2-4e2a-95ad-f31391ff6e7e.png) ![phasefilt_mask_ll](https://user-images.githubusercontent.com/96293813/146543586-fde0ae76-9f31-4c43-9c94-c783b16fd5c7.png)

Hello! I'd like to ask about the second question. Have you solved it? In the preprocessing stage, I have cropped and generated a new * saef file through organize_files_tops_linux. csh safe_filelist.. / reframed / pins. ll 2. Later, when I execute the preproc_batch_tops. csh data. in dem. grd 2 command, there is an error of "inherit: interpolation not in center interval". Would you mind telling me the reason?

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure of the cause as seems @ijnokmp was able to pass the processing stage. Usually for that case, I would check the DEM file to see whether it has some strange numbers in it. But I am not sure.

**Comment by hillgrey** [comment]
<img width="771" alt="phasefilt" src="https://user-images.githubusercontent.com/108720969/232972517-f01adf61-6249-4d0c-ad26-29280bfcbea1.png">
<img width="771" alt="unwrap" src="https://user-images.githubusercontent.com/108720969/232972538-acab36c5-f41d-4ba0-be58-1db49691569e.png">

I met the same problem with the V6.2.2 version of GMTSAR. When setting the region_cut parameter, the filtered products will contain this strange boundaries randomly, sometimes on the left-right side while sometimes on the top-bottom. Please see the attached 'phasefilt.png' and 'unwrap.png' (screenshot of  'phasefilt.grd' and 'unwrap.grd', respectively), seems there are unwrapping errors in the unwrap.grd.

I understand that this issue is related to the filter, as posted by Eric.

My 2 questions are:
1: Could the boundary effects be somehow elimited? Maybe change the default Gaussian filter?
2: When performing the further SBAS calculation, could these boundary error cause problems in the SBAS  atmospheric correction (CSS method)? As the CSS APS correction use the unwrap.grd as input, and calculate the phase features, I am not sure if the error signals in the boundary would introduce extra errors, and lead to failure for the whole SBAS processing.

Cheers,
Hillgrey

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @hillgrey, It seems related with the Goldstein filter program in GMTSAR. One way of course is to abandon the bounds by running a grdcut. I believe these boundaries are always at far range/azimuth, not really random, so not affecting atm correction in sbas. The size of the boundaries may be related to the `-psize` option in `phasefilt`.

Actually I do have a concern as these boundaries may have shifted the results somehow in range/azimuth, but I need to check with Rob Mellor before changing anything in the code.

**Comment by hillgrey** [comment]
> 

Hi Eric, thanks for sharing your opinions. Glad to hear that these odd phase features at boundaries do not disturb the APS correction. Then, I can run a 'grdcut' command to discard these boundaries for better visualization, without worrying that systematic or global errors were introduced into the final SBAS products through the -atm option.  
The concern that you just mentioned sounds quite reasonable and interesting. Would be nice to hear further suggestions.
