### ISSUE TITLE
SBAS Error

### ISSUE THREAD

**Issue by sunzhe-96** [gmtsar/gmtsar#263]
Dear all
Hello,everyone I made this mistake when I was taking sBAS, does anyone know what happened
![捕获](https://user-images.githubusercontent.com/89780038/147546491-14f757bb-a966-4d31-b0d4-8667be7f1ca2.JPG)

**Comment by Xiaohua-Eric-Xu** [comment]
You need more memory (RAM), or it might be better to reduce the amount of pixels in the images. 
We are currently developing a detour for the atm correction + sbas module, so in the future it'll take disk space rather than RAM for temporary storage of the data.

**Comment by sunzhe-96** [comment]
> 

Thanks for your reply,Eric,I'll try to cut the image.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, could you try update to the newest master branch and give it a test. @dsandwell and I changed the code to `mmap` disk space for less use of memory. ad93d5cb0df351c2fb5add9a2bb4564273f9f498

**Comment by sunzhe-96** [comment]
> Hi, could you try update to the newest master branch and give it a test. @dsandwell and I changed the code to `mmap` disk space for less use of memory. [ad93d5c](https://github.com/gmtsar/gmtsar/commit/ad93d5cb0df351c2fb5add9a2bb4564273f9f498)

Thank you Eric, that's useful for me! I'll try.
