### ISSUE TITLE
Problem with ERS-2(E2) in Envisat format processing

### ISSUE THREAD

**Issue by Sgzanjani1367** [gmtsar/gmtsar#264]
Hi all
I want to process ERS data in Envisat format (SAR_IMS_1PNESA19981003_064848_00000018A036_00163_18053_0000.E2) in GMTSAR.
and according to the instructions that I have attached I use p2p_processing.csh ENVI_SLC.
but it seems that E2 does not to be known.

gmtsar-user@gmtsarVB:$ p2p_processing.csh ENVI_SLC SAR_IMS_1PNESA19981003_064848_00000018A036_00163_18053_0000 SAR_IMS_1PNESA19990605_064848_00000018A043_00163_21560_0000

PREPROCESS - START

Working on images SAR_IMS_1PNESA19981003_064848_00000018A036_00163_18053_0000 SAR_IMS_1PNESA19990605_064848_00000018A043_00163_21560_0000 ...
 no file  raw/SAR_IMS_1PNESA19981003_064848_00000018A036_00163_18053_0000.N1

[README.txt.txt](https://github.com/gmtsar/gmtsar/files/7788384/README.txt.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
I made a fix in the master branch in p2p_processing.csh to let it examine ERS files. 1d490fe6d59504606c0e6615072d9961aecb0bac 99779d16692243866affff7b98a163d1d38f1fe0 Could you update to the master branch and give it another test?

**Comment by Sgzanjani1367** [comment]
Thanks, Eric 

It works but It has another problem
![gmtsar](https://user-images.githubusercontent.com/94073038/148071534-3de7befc-ab2c-420f-b65c-ce3a2673308f.PNG)

ALIGN.CSH - START

cp: cannot stat 'SAR_IMS_1PNESA19990605_064848_00000018A043_00163_21560_0000.PRM': No such file or directory
 Can't open prmfile  SAR_IMS_1PNESA19990605_064848_00000018A043_00163_21560_0000.PRM0 
 setting xsearch to 128
 setting nx_corr to 256
 setting ysearch to 128
 setting ny_corr to 256
 setting nx to 20
 setting ny to 50
 Cannot open SLC_file XXXXXXXX� 
freq_xcorr.dat: No such file or directory.
freq_xcorr.dat: No such file or directory.
wc: freq_xcorr.dat: No such file or directory
wc: r.xyz: No such file or directory
 can't open %s for reading XXXXXXXX��Sq 
mv: cannot stat 'SAR_IMS_1PNESA19990605_064848_00000018A043_00163_21560_0000.SLCresamp': No such file or directory
cp: cannot stat 'SAR_IMS_1PNESA19990605_064848_00000018A043_00163_21560_0000.PRMresamp': No such file or directory

ALIGN.CSH - END

**Comment by Xiaohua-Eric-Xu** [comment]
The error comes from 
ENVI_SLC_pre_process -> calc_dop_orb.c -> ldr_orbit.c
I am not particularly sure as the error below says the orbit does not properly cover the data. 
```
interpolation point outside data constraints ...
```
Could you check on the .LED file and the clock parameters?
Also do you mind sharing the two files so I could test it on my end?

**Comment by Sgzanjani1367** [comment]
Yes sure
The .LED file just contains 0 1998 276  30.

Which two files I would share with you?

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, strange. Then it means it did not successfully extract the orbit. 
Could you share these two files? 
SAR_IMS_1PNESA19981003_064848_00000018A036_00163_18053_0000
SAR_IMS_1PNESA19990605_064848_00000018A043_00163_21560_0000

**Comment by Sgzanjani1367** [comment]
here you are.
https://drive.google.com/file/d/1_Rsm8wg9Tfmt5WdZmD3d1Lulon2kuVGV/view?usp=sharing

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, I ran through without having any error. 
![phasefilt_mask_ll](https://user-images.githubusercontent.com/16844111/148309526-d1319485-1772-402a-988b-8c9e69dcfff5.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Here's the log file
[log.txt](https://github.com/gmtsar/gmtsar/files/7818589/log.txt)

Could you check whether the orbit files at /usr/local/orbits/ers are readable to you?

**Comment by Sgzanjani1367** [comment]
Many thanks for your help.

**Comment by Xiaohua-Eric-Xu** [comment]
Were you able to get the orbit file extracted?

**Comment by Xiaohua-Eric-Xu** [comment]
Great!
