### ISSUE TITLE
[Bug]: assemble tops bug

### ISSUE THREAD

**Issue by insar-dev** [gmtsar/gmtsar#265]
**Describe the bug**

when i assembled the following data, the program crashed
data1: S1A_IW_SLC__1SDV_20210526T103358_20210526T103426_038058_047DDD_A895.SAFE
data2: S1A_IW_SLC__1SDV_20210526T103424_20210526T103439_038058_047DDD_ABA4.SAFE

it crashed at the code:

![image](https://user-images.githubusercontent.com/1676595/147757147-392aa6de-2997-42b6-a8f1-76ab508aa586.png)

![image](https://user-images.githubusercontent.com/1676595/147757194-d8d25fcb-64c5-42ba-9f8f-0ace3554fda5.png)

i find that data1's orbit time range contain data2's orbit time range,  so var kk2 will be -1, then app crashed.

**Comment by Xiaohua-Eric-Xu** [comment]
I don't remember exactly what I did, but it should be looking for the closest next one that has larger time? Do you mean data2 is completely covered by data1, and it failed looping through the end?

**Comment by insar-dev** [comment]
yes, data2 orbit list is completely covered by data1.
data1 orbit list:
![image](https://user-images.githubusercontent.com/1676595/147794489-4e56369e-5f6d-4faa-85ec-18cacc502a7c.png)

data2 orbit list:
![image](https://user-images.githubusercontent.com/1676595/147794523-abcb1475-afd9-485f-a589-4e106a31a039.png)


data2 is much smaller than data1:
![image](https://user-images.githubusercontent.com/1676595/147794694-f3636c1b-f37e-46c5-b1dd-ccc93578455a.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, strange. Didn't see that coming. The data looks consecutive but one orbit records are fully covered by the other. 
I changed the code in the master branch to avoid doing anything in that case. But I haven't tested it. Could you give it a test?

**Comment by insar-dev** [comment]
hi Eric,
i have tested the code ,it still  crashed.
could you use the following code:

while (t2 - 1e-6 / 86400.0 < t1) {
			kk2 = T[0][kk2].sibr;
                        if(kk2 == -1) break;
			t2 = time2double(T[0][T[0][T[0][T[0][kk2].firstchild].sibr].firstchild].name);
			ct++;
		}
if (kk2 != -1) {
            // append the records from ct's record, otherwise don't do anything. 
		    T[0][kk1].sibr = kk2;
		    kk2 = T[0][ii2 + nlmx * qq * 5].firstchild;
		    for (jj2 = 1; jj2 < nn2 - ct; jj2++) {
			    T[0][kk2].parent = ii1;
			    kk2 = T[0][kk2].sibr;
		    }
		    T[0][kk2].parent = ii1;
		    sprintf(tmp_c, "%s count=\"%d\"", term, nn1 + nn2 - ct);
		    strcpy(T[0][ii1].name, tmp_c);
        }

**Comment by Xiaohua-Eric-Xu** [comment]
Just did. 0a34fe4d6075e9b3b68385e229bc9cc1008a1f31
Could you give it another test?

**Comment by insar-dev** [comment]
i have tested it. it is ok now.  thank you.

**Comment by Xiaohua-Eric-Xu** [comment]
Thanks!
