### ISSUE TITLE
[Help]: stack smashing error in GMTSAR v6.1 

### ISSUE THREAD

**Issue by Nitheshnirmal** [gmtsar/gmtsar#269]
Unmatched '''.
--2022-01-10 22:58:09--  https://s1qc.asf.alaska.edu/aux_poeorb
Resolving s1qc.asf.alaska.edu (s1qc.asf.alaska.edu)... 137.229.87.163, 137.229.87.170
Connecting to s1qc.asf.alaska.edu (s1qc.asf.alaska.edu)|137.229.87.163|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://s1qc.asf.alaska.edu/aux_poeorb/ [following]
--2022-01-10 22:58:10--  https://s1qc.asf.alaska.edu/aux_poeorb/
Reusing existing connection to s1qc.asf.alaska.edu:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘orbits.html’

orbits.html             [    <=>             ]   1.48M  1.49MB/s    in 1.0s    

2022-01-10 22:58:14 (1.49 MB/s) - ‘orbits.html’ saved [1550161]

Combing /data/local/MSc_res/GMTSAR/asc/data/S1A_IW_SLC__1SDV_20160823T072219_20160823T072249_012724_01403F_8C86.SAFE ...
20160822 20160824 S1A_OPER_AUX_POEORB_OPOD_20210313T124815_V20160822T225943_20160824T005943.EOF
/opt/spark/python/lib/py4j-0.10.9.2-src.zip/wgetasf: Not a directory.
Reading in 5018 lines of info from XML...
Writing 17 lines for orbit...
 Couldn't open xml file: 
 S1A_OPER_AUX_POEORB_OPOD_20210313T124815_V20160822T225943_20160824T005943.EOF 
*** stack smashing detected ***: terminated
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: cmd. line:1: {printf("%d",$2+0.5 + )}
awk: cmd. line:1:                       ^ syntax error
*** stack smashing detected ***: terminated

I got the following error when I tried to download precise orbits using Organize_files_tops_linux.csh with safelist and pin.ll

Please kindly help me this issue.

Thank you
Nithesh

**Comment by Xiaohua-Eric-Xu** [comment]
I assume you are using Ubuntu16.0+, please see this issue https://github.com/gmtsar/gmtsar/issues/12.
You'll need to change config.mk so the compiler no-longer tries to detect stack smashing. We did went through the code and it didn't seem there should be any overflow.

**Comment by Nitheshnirmal** [comment]
Thank you Xiaohua for your quick reply.
Yes, the system I'm using is Ubuntu 18.04. I will see to the issue 12.

**Comment by Nitheshnirmal** [comment]
@Xiaohua-Eric-Xu 
I got the following message when I tried to source ~/.cshrc after inserting the wgetasf alias using vi ~/.cshrc. Please let me know if it has anything do with the above problem. Thank you

bash: alias: wgetasf: not found
bash: alias: `wget --http-user': invalid alias name

**Comment by Nitheshnirmal** [comment]
The orbits got downloaded and Fxxxx_Fxxxx folder has been created by doing the changes in config.mk and reinstalling GMTSAR as per issue #12.

Thank you for the help.

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu I got the following message when I tried to source ~/.cshrc after inserting the wgetasf alias using vi ~/.cshrc. Please let me know if it has anything do with the above problem. Thank you
> 
> bash: alias: wgetasf: not found bash: alias: `wget --http-user': invalid alias name

You sourced .cshrc but are executing things in bash.

**Comment by Nitheshnirmal** [comment]
Ohk I'm sorry for that. Should I include alias wgetasf in bash? 
Please let me know

**Comment by Nitheshnirmal** [comment]
Thank you so much for your help @Xiaohua-Eric-Xu

**Comment by Nitheshnirmal** [comment]
Hi @Xiaohua-Eric-Xu,

I got the following phase in the interferogram formation step but don't know if it's correct.

Please let me know.

![image](https://user-images.githubusercontent.com/55835235/150881261-23882055-9806-4e5e-9486-1e8185ff227d.png)

**Comment by Nitheshnirmal** [comment]
And while I run create_merge_input.csh I get the following,

**(base) jovyan@7356452b843a:/data/local/MSc_res/GMTSAR/asc/merge$ create_merge_input.csh inftlist .. 2 >merge_list
awk: fatal: cannot open file `inftlist' for reading (No such file or directory)**

However, I made inftlist in both F2 and F3 swaths as attached. But create_merge_input.csh is showing the above error. Please let me know what I can do to resolve this error. Thank you

![image](https://user-images.githubusercontent.com/55835235/150882127-119ce4bb-ca1a-44ba-8d1f-43f70d7f651f.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @Nitheshnirmal , I think you need to have that list local or specify the path in front of it, so the script could read in the text inside.

**Comment by Nitheshnirmal** [comment]
Dear @Xiaohua-Eric-Xu,

Thanks, I got it. It's working now.

Also, I will post my issues in this thread.

**Comment by Nitheshnirmal** [comment]
Hi @Xiaohua-Eric-Xu,

The dimension of corr.grd and unwrap.grd are different and I get the following error while I run sbas program.

![image](https://user-images.githubusercontent.com/55835235/152152578-81c023ee-eabe-48f8-a6d5-49bcc05ea34f.png)

![image](https://user-images.githubusercontent.com/55835235/152152789-a7501e36-1baa-4d39-b5cd-3c4b5a4eff4a.png)

![image](https://user-images.githubusercontent.com/55835235/152152906-55381d29-72fd-4ade-8018-e472fe04c1fe.png)

please let me know how to change the dimensions of corr.grd to that of unwrap.grd.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @Nitheshnirmal, I believe you further cut the image when unwrapping the phase. For sbas, you then could cut your corr.grd to the same size with `gmt grdcut corr.grd -Runwrap.grd -Gcorr_cut.grd`.

**Comment by Nitheshnirmal** [comment]
Dear @Xiaohua-Eric-Xu, Thank you very much for helping me.

**Comment by Nitheshnirmal** [comment]
Dear @Xiaohua-Eric-Xu, Thank you for your help with corr.grd. 
I ran sbas but I am confused with my result. I have attached them below.
![image](https://user-images.githubusercontent.com/55835235/152364338-209b00e7-ede7-498c-a719-33048a30d0e9.png)
This is an example of unwrapped interferogram.

![image](https://user-images.githubusercontent.com/55835235/152364571-785959f5-74ff-4ab6-8a2c-0896f9f2d4b9.png)
I don't think this result is correct. Please let me know what you think would went wrong.

**Comment by Nitheshnirmal** [comment]
Dear @Xiaohua-Eric-Xu 
Also, I am interested in using the Correlation grd generated from GMTSAR during interferogram formation. Can I convert corr.grd to tiff format for my analysis. Can I please know how to do it. Please kindly point in that direction.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @Nitheshnirmal, looks like there are lots of elevation dependent atmospheric noise. You could try the gacos correction https://github.com/gmtsar/user-contributions/tree/main/gacos-correction.
Yes, you could use grd2geotiff.csh (for raster file) or simply gdal for convertion (grid data).

**Comment by Nitheshnirmal** [comment]
Dear @Xiaohua-Eric-Xu,
Thanks for your suggestion. I will try it out and update it here.

**Comment by Nitheshnirmal** [comment]
Hi @Xiaohua-Eric-Xu,
Today, I ran into a problem while running SBAS. 

In the first displacement grid created by the SBAS command,  when I run gmt grdinfo I get the following v_min and v_max


![image](https://user-images.githubusercontent.com/55835235/162594318-4803127b-f01c-4fad-b5d2-29d7c5425177.png)
and when I tried to open it with ncview, the image only had no data.


while the rest of displacement grids had data in them. I didn't know at which point it would have gone wrong. 

Can you please help me identify the problem.

**Comment by Xiaohua-Eric-Xu** [comment]
what's the threshold you used for phase unwrapping?

**Comment by Nitheshnirmal** [comment]
Hi @Xiaohua-Eric-Xu,
I gave a correlation threshold of 0.001 for phase unwrapping. 
![image](https://user-images.githubusercontent.com/55835235/162607646-e6cbe94c-10e6-40f5-afdf-fc0e7760d615.png)

**Comment by Nitheshnirmal** [comment]
I will rerun phase unwrapping for those particular dates. May be it could fix the issue.

**Comment by Nitheshnirmal** [comment]
I reran the phase unwrapping for those dates associated with displacement grid and ran SBAS again. But still I am getting the same error.

**Comment by Xiaohua-Eric-Xu** [comment]
Do all the input unwrap.grd-s come with valid data? I want to make sure whether it is an sbas issue or input data issue.

**Comment by Nitheshnirmal** [comment]
Hi @Xiaohua-Eric-Xu,

yes, I checked all the 111 interferograms, it was with valid data. However, I don't understand what gone wrong. 

I deleted all the files and started generating the interferograms again. I think it will finish within tonight and I will report if SBAS works this time.

Thanks @Xiaohua-Eric-Xu

**Comment by Nitheshnirmal** [comment]
Hi @Xiaohua-Eric-Xu 
I have regenerated the whole workflow from scratch about the same problem occurs again.

**Comment by Nitheshnirmal** [comment]
![image](https://user-images.githubusercontent.com/55835235/162947748-0ee947a3-6ead-4ac5-95ae-f201cdaccd5a.png)

2014300_2014324
![image](https://user-images.githubusercontent.com/55835235/162947890-f0685038-e8ea-45b3-b3e6-a3f57062e0e9.png)

2014300_2014348
![image](https://user-images.githubusercontent.com/55835235/162948186-0ca74d78-4ae4-4dbf-8e51-46066cacac1f.png)

2014300_2015007
![image](https://user-images.githubusercontent.com/55835235/162948343-664e9e22-cf34-4f37-bc41-968eb07fe660.png)

But their associated displacement grd is as follows:
![image](https://user-images.githubusercontent.com/55835235/162948620-60b30550-bd02-4171-bad5-07a74f25b43d.png)

However all other displacement grds have valid data like follows;
![image](https://user-images.githubusercontent.com/55835235/162948856-6f42be8f-0391-4ea5-a519-bde80f589c79.png)

Please kindly let me know how to troubleshoot this problem.

**Comment by Xiaohua-Eric-Xu** [comment]
This is strange. If the input area with NaNs come out as 0-s, that's no good (as they are supposed to be NaNs). I suspect the input file did not have the right grids with them, but I am not sure. Also the first date are set to zero automatically (starting point), so you may want to check on a few others? If all others are zeros, could you send your intf.tab and scene.tab and the log of your sbas run.

**Comment by Nitheshnirmal** [comment]
Hi @Xiaohua-Eric-Xu,
Thanks for the message. The v_min and max is 0 in the first date (starting point). other than the first displacement grids all other grids have data. So, is what i did is correct? Please let me know.

I have attached the intf.tab and scene.tab. I think it's correct.

intf.tab

![image](https://user-images.githubusercontent.com/55835235/163008406-2b1b0f0e-9dd0-4db0-afa8-bb4dc4dd91c7.png)

scene.tab

![image](https://user-images.githubusercontent.com/55835235/163008592-d292ea6d-840d-4c8c-98d3-ead8e1c9e6b7.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Oh wait, you said all other grids looks OK? Then you should be fine as the first grid are just filled with 0-s as a starting grid.

**Comment by Nitheshnirmal** [comment]
Yeah, the first grd has 0s and all the other grds has values. Thank you very much @Xiaohua-Eric-Xu ! for your help : )..

I will continue with gacos_correction.

**Comment by Nitheshnirmal** [comment]
Sure, I will try it out. 

But while doing sbas, I haven't given any value for -atm ni --iteration. So, in default I skipped doing atm correction.

Can you please suggest me a value for atm ni for creating an aps__xxxx.grd.

Thanks @Xiaohua-Eric-Xu

**Comment by Nitheshnirmal** [comment]
Thanks @Xiaohua-Eric-Xu . I will try it out.

**Comment by Nitheshnirmal** [comment]
Hi @Xiaohua-Eric-Xu,

When I convert grd file to tif, I feel there's a shift ( please see the attached fig below)

![image](https://user-images.githubusercontent.com/55835235/163246021-f2062ea9-92b0-499c-a469-62b77c4ddfaa.png)

can you please let me know how to solve this issue.

**Comment by Xiaohua-Eric-Xu** [comment]
what if you open the the kml file? or use grd2kml.csh to convert it?

**Comment by Nitheshnirmal** [comment]
I face the same problem when I convert it to kml file

**Comment by Xiaohua-Eric-Xu** [comment]
Which trans.dat file did you use? (from the merge directory?)

**Comment by Nitheshnirmal** [comment]
yes I used (ln -s ../merge/trans.dat) to get the trans.dat file from merge

**Comment by Nitheshnirmal** [comment]
I will try it once again

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure. This is a likely a projection error. You'll need to let me know the exact steps you did (and log) so as to help me find the cause.

**Comment by matlabCPU** [comment]
> 嗨，我认为您需要将该列表放在本地或指定其前面的路径，以便脚本可以在内部文本中读取。

Dear Teacher Xu
After I created the merge_list file, I found that the first row did not contain the main image I selected, did I need to manually adjust the main image to the first line, or did I have a problem with my previous operation
![image](https://github.com/gmtsar/gmtsar/assets/118905130/1493537c-b3ed-4675-a126-e7d954c2d15a)

**Comment by Xiaohua-Eric-Xu** [comment]
@matlabCPU I believe so.
