### ISSUE TITLE
[Help]: problem with create_merge_input.csh

### ISSUE THREAD

**Issue by Nitheshnirmal** [gmtsar/gmtsar#270]
**Describe the problem you met**
I made a intflist in F2 and F3 directory and tried to make a merge_list using,
 **>create_merge_input.csh intflist .. 2 > merge_list**
but I get the following error:

**(base) jovyan@57ecbab6e50e:/data/local/MSc_res/GMTSAR/asc/merge$ create_merge_input.csh intflist .. 2 > merge_list**
**awk: fatal: cannot open file `intflist' for reading (No such file or directory)**

I'm running the GMTSAR program using bash, is it a problem?

**OS and software version**

OS: linux 18.04
GMTSAR version: 6

Please help me with this. 

Thank you

**Comment by Xiaohua-Eric-Xu** [comment]
I made a response here https://github.com/gmtsar/gmtsar/issues/269#event-5952376756. Let's continue there.
