### ISSUE TITLE
[Help]: How do we update the old GMTSAR to new one version?

### ISSUE THREAD

**Issue by khakim** [gmtsar/gmtsar#273]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @khakim , do you have any log files that can tell us what happened after you run intf_tops.csh?
For update, you just need to run a `git pull` for your version or `git checkout [branchname]` for switching to a newer version.

**Comment by khakim** [comment]
Hi Eric.  Sorry I did not anything to update GMTSAR.  My pc system is ubuntu 18.04 version. I worry if the system cannot support the newest version of GMTSAR.

**Comment by Xiaohua-Eric-Xu** [comment]
I my self am using ubuntu 18.04 and things run fine.

**Comment by khakim** [comment]
Dear Eric,

I will continue updating GMTSAR installed in my pc. I read the information mentioned in the file of BASICSGIT.TXT. But I don't understand steps to update it using git pull in commad line.

Is it true if I use the following command line?

cd /usr/local
git clone https://github.com/gmtsar/gmtsar GMTSAR_master
#
git clone --branch 5.7 https://github.com/gmtsar/gmtsar GMTSAR_5.7
#
#  update your repository before making any changes
#
git pull
#
#   make changes to an existing repository 
#
cd /usr/local/gmtsar
vi README.md
git add README.md
git commit -m"changed README.md file"
git push 
#
#  delete a file from an existing repository
#
git rm BASICSVN.txt
git commit -m"removed the SVN instructions"
git push 

Thank you very much for help in advance.

**Comment by Xiaohua-Eric-Xu** [comment]
Go to your installation directory (e.g. /usr/local/GMTSAR). Run `git checkout 6.1`. Then `make spotless`, `autoconf`, `./configure`, `make` and `make install`.

**Comment by khakim** [comment]
Thank you very much...

**Comment by Xiaohua-Eric-Xu** [comment]
Sorry for the late response. This seems to be warning from earlier versions of GMTSAR. It does not affect processing and should be gone for version 5.9 or later.
