### ISSUE TITLE
[Help]: organize_files_tops_linux.csh error

### ISSUE THREAD

**Issue by shivmore-NGRI** [gmtsar/gmtsar#274]
while organizing data I got an error 
I have run this "organize_files_tops_linux.csh SAFE_filelist ../reframed/pins.ll 1"
I got only orbits. list file and .EOF files are not download

organize_files_tops_linux.csh SAFE_filelist ../reframed/pins.ll 1
--2022-02-07 15:35:50--  https://s1qc.asf.alaska.edu/aux_poeorb
Resolving s1qc.asf.alaska.edu (s1qc.asf.alaska.edu)... 137.229.87.163, 137.229.87.170
Connecting to s1qc.asf.alaska.edu (s1qc.asf.alaska.edu)|137.229.87.163|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://s1qc.asf.alaska.edu/aux_poeorb/ [following]
--2022-02-07 15:35:51--  https://s1qc.asf.alaska.edu/aux_poeorb/
Reusing existing connection to s1qc.asf.alaska.edu:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘orbits.html’

orbits.html                                            [          <=>                                                                                                   ]   1.49M   594KB/s    in 2.6s    

2022-02-07 15:35:56 (594 KB/s) - ‘orbits.html’ saved [1559849]

Combing /home/grace/InSAR_data/Lucknow/Ascending/data/S1A_IW_SLC__1SDV_20210105T123824_20210105T123852_036003_0437CD_1CE5.SAFE ...
20210104 20210106 S1A_OPER_AUX_POEORB_OPOD_20210125T121545_V20210104T225942_20210106T005942.EOF S1A_OPER_AUX_POEORB_OPOD_20210319T035014_V20210104T225942_20210106T005942.EOF
if: Expression Syntax.

**Comment by Xiaohua-Eric-Xu** [comment]
Do you mind telling us which version of GMTSAR you are using?

**Comment by shivmore-NGRI** [comment]
I checked datasets are available and I downloaded the EOF file now I get a file missing an error
![Screenshot from 2022-02-08 13-49-08](https://user-images.githubusercontent.com/55309577/152946632-b50d957d-f0c5-4264-993c-df51e29ce030.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Could you check the orbits.lits file, if it has the needed orbit file names there? If not, try delete it and re-run the command.

**Comment by shivmore-NGRI** [comment]
As you suggested  I have deleted orbits.list file  and re-run the command but sill error is showing
![Screenshot from 2022-02-09 13-24-37](https://user-images.githubusercontent.com/55309577/153148735-3751b0c0-e993-4793-9c0d-2a36e564db3a.png)

**Comment by Xiaohua-Eric-Xu** [comment]
This feels like a but in the earlier version of GMTSAR. It should have been fixed in 6.1 and master. So same question again, which version of GMTSAR you are using?
