### ISSUE TITLE
[Help]: Unwraping Error grdmath [ERROR]: Syntax error: corr_patch.grd is not a number, operator or file name

### ISSUE THREAD

**Issue by ivvnnnn** [gmtsar/gmtsar#277]
**Problem**
Unwraping Error grdmath [ERROR]: Syntax error: corr_patch.grd is not a number, operator or file name

**OS and software version**
OS: Ubuntu 20.0
GMTSAR version: GMTSAR 6.1

**Reproduce the problem**
Hello! I have a problem with unwraping process. I created interferograms for one swath of Sentinel-1 image. Since I  need to process only one swath, i did not merge the swaths. I run unwrap_intf.csh from the interferogram directory ../F1/intf_all. The script looked like script in the instruction: 
cd $1
ln -s ../landmask_ra.grd .
snaphu_interp.csh 0.01 40
cd ..

However, I encountered the error, described in the log

**Log file**
unwrap_intf.csh /media/gmtsar-user/disk3/GMTSAR_Proj/dec/F1/intf_all/
grdmath [ERROR]: Syntax error: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: mask2_patch.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: mask2_patch.grd is not a number, operator or file name
Setting search radius to be 300 ...
Reading in original grid...
nearest_grid [ERROR]: File phase_tmp.grd not found
[Session nearest_grid (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open grdfile phase_tmp.grd 
mv: cannot stat 'tmp.grd': No such file or directory
grd2xyz [ERROR]: File phase_tmp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
grd2xyz [ERROR]: File corr_tmp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
unwrapping phase with snaphu - higher threshold for faster unwrapping 
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files

snaphu v2.0.1
32 parameters input from file snaphu.conf.brief (297 lines total)
not enough input arguments.  type snaphu -h for help
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
xyz2grd [ERROR]: Error for input file: No such file (unwrap.out)
xyz2grd [ERROR]: Syntax error: Must specify -R option
xyz2grd [ERROR]: Syntax error -I option: Must specify positive increment(s)
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
xyz2grd [ERROR]: Error for input file: No such file (conncomp.out)
xyz2grd [ERROR]: Syntax error: Must specify -R option
xyz2grd [ERROR]: Syntax error -I option: Must specify positive increment(s)
grdmath [ERROR]: Syntax error: tmp.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdgradient [ERROR]: Error for input file: No such file (unwrap.grd)
grdgradient [ERROR]: Syntax error: Must specify input file
grdinfo [ERROR]: Error for input file: No such file (unwrap.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
makecpt [ERROR]: Syntax error -T: Must specify valid min[/max[/inc[<unit>|+n]]] option
grdinfo [ERROR]: Error for input file: No such file (unwrap.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdinfo [ERROR]: Error for input file: No such file (unwrap.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdimage [ERROR]: Error for input file: No such file (unwrap.grd)
grdimage [ERROR]: Syntax error -I: Requires a valid grid file or a constant
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
grdimage [ERROR]: Syntax error -I option: Must specify intensity file, value, or modifiers
psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Runwrap.grd
psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
Unwrapped phase map: unwrap.pdf

**Screenshot**
![Screenshot from 2022-02-17 02-09-19](https://user-images.githubusercontent.com/99873993/154454107-7c86f408-8072-4540-a217-a50e4a948706.png)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
Could you do a `gmt grdinfo landmask_ra.grd`?

**Comment by ivvnnnn** [comment]
> 
Ohh, sorry. My code looks without the first line since i didn't make a mask
My code:
#!/bin/csh -f
# intflist contains a list of all date1_date2 directories.
cd $1
snaphu_interp.csh 0.01 40
cd ..

**Comment by Xiaohua-Eric-Xu** [comment]
Did it work?

**Comment by ivvnnnn** [comment]
@No((

**Comment by ivvnnnn** [comment]
@Xiaohua-Eric-Xu No((

**Comment by ivvnnnn** [comment]
@Xiaohua-Eric-Xu Thanks for the response! Does it need to be run from F1/intf_all folder? If I enter command rm *patch* it gives message: rm: cannot remove '*patch*': No such file or directory. I'm sorry, maybe you mean something else by command "*patch*"? I'm just  new to GMTSAR and Linux, and some things are still not entirely clear for me

**Comment by Xiaohua-Eric-Xu** [comment]
Could you go to `/media/gmtsar-user/disk3/GMTSAR_Proj/dec/F1/intf_all/`, do a `ls -l`. Send outputs from terminal.

Then run `snaphu_interp.csh 0.1 40`. Send the outputs from terminal.

**Comment by ivvnnnn** [comment]
I got this output
total 124
drwxrwxr-x 3 gmtsar-user gmtsar-user  4096 Feb 24 06:42 2018202_2018214
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:43 2018202_2018226
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:43 2018202_2018238
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:43 2018202_2018250
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:43 2018214_2018226
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:43 2018214_2018238
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:43 2018214_2018250
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:43 2018214_2018262
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:43 2018226_2018238
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:43 2018226_2018250
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:44 2018226_2018262
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:44 2018226_2018274
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:44 2018238_2018250
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:44 2018238_2018262
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:44 2018238_2018274
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:44 2018238_2018286
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:44 2018250_2018262
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:45 2018250_2018274
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:45 2018250_2018286
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:45 2018250_2018298
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:45 2018262_2018274
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:45 2018262_2018286
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:45 2018262_2018310
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:45 2018274_2018286
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:40 2018286_2018298
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:42 2018286_2018310
drwxrwxr-x 2 gmtsar-user gmtsar-user  4096 Feb 24 06:45 2018298_2018310
-rw-rw-r-- 1 gmtsar-user gmtsar-user   127 Mar  2 00:44 gmt.history
lrwxrwxrwx 1 gmtsar-user gmtsar-user    13 Mar  2 00:44 phasefilt_interp.grd -> phasefilt.grd
-rw-rw-r-- 1 gmtsar-user gmtsar-user 10908 Mar  2 00:44 snaphu.conf.brief
-rw-rw-r-- 1 gmtsar-user gmtsar-user     0 Mar  2 00:44 unwrap.cpt
-rw-rw-r-- 1 gmtsar-user gmtsar-user     0 Mar  2 00:44 unwrap.ps

**Comment by ivvnnnn** [comment]
I also noticed that the first folder has one more file. Maybe it's all about this?
![image](https://user-images.githubusercontent.com/99873993/156354011-181da389-8bb0-4815-b6e9-7bf1a9fe73b9.png)

**Comment by ivvnnnn** [comment]
Thank you! It seems to have worked! These files have been added to the folder:
![image](https://user-images.githubusercontent.com/99873993/156523674-9bf7bfbb-6b19-4ee1-a103-a6881aa42b1e.png)

And this is unwrap.pdf output: 
![image](https://user-images.githubusercontent.com/99873993/156523798-d7954976-492f-49f8-9b9f-d7e9d3ff744c.png)
