### ISSUE TITLE
Problem with merge of subwath

### ISSUE THREAD

**Issue by Fabiangeo95** [gmtsar/gmtsar#28]
Hi, use merge_batch.csh to merge two subwaths, but there is a separation between them, which becomes evident when viewing the correlation and unwrap, this only happens with some interferograms of the stack, also in the terminal no processing error is registered.
![unwrap_ll](https://user-images.githubusercontent.com/68412610/87749349-72b2e480-c7c6-11ea-94a7-3bab3eaa6c55.png)
cheers.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Fabiangeo,
I believe this is similar issue as #26. I probably will have some time to look into this after our workshop. I am thinking of adding a shift option behind merge_swath so when this happens, one could make a tune easily.
Cheers,
Xiaohua(Eric)

**Comment by Fabiangeo95** [comment]
thanks for your answer, now I have another problem, I joined images using "create_frame_tops.csh", but when doing the interferogram the phase looks like this. I made sure the dem and orbit were fine. What could be causing the problem?

![Captura de pantalla de 2020-07-27 02-55-24](https://user-images.githubusercontent.com/68412610/88512499-ae169580-cfb4-11ea-8c95-2dd5fefb87b5.png)
