### ISSUE TITLE
organize_files_linux_tops.csh error 

### ISSUE THREAD

**Issue by misha0402** [gmtsar/gmtsar#280]
I am trying to trim and organise the .safe files and facing the following error:

organize_files_tops_linux.csh SAFE_filelist ../reframed/pins.ll 1
Unmatched '''.
--2022-02-22 13:18:33--  https://s1qc.asf.alaska.edu/aux_poeorb
Resolving s1qc.asf.alaska.edu (s1qc.asf.alaska.edu)... 137.229.87.170, 137.229.87.163
Connecting to s1qc.asf.alaska.edu (s1qc.asf.alaska.edu)|137.229.87.170|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://s1qc.asf.alaska.edu/aux_poeorb/ [following]
--2022-02-22 13:18:39--  https://s1qc.asf.alaska.edu/aux_poeorb/
Reusing existing connection to s1qc.asf.alaska.edu:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘orbits.html’

orbits.html             [       <=>          ]   1.49M   523KB/s    in 2.9s    

2022-02-22 13:18:44 (523 KB/s) - ‘orbits.html’ saved [1565039]

Combing /media/iirs/'New date: invalid date ‘/med/ia//i rs:/':Ne’
date: invalid date ‘/med/ia//i rs:/':Ne’
...
date: invalid date ‘/media/iirs/'New - 1 day’
date: invalid date ‘/media/iirs/'New + 1 day’
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.

if: Missing file name.

**Comment by Xiaohua-Eric-Xu** [comment]
What's in your SAFE_list?

**Comment by misha0402** [comment]
location and name of all the . SAFE files:
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20161121T005215_20161121T005242_014033_0169FE_6602.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20161203T005214_20161203T005241_014208_016F6A_1924.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20161227T005214_20161227T005241_014558_017A6A_A87A.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20170108T005212_20170108T005239_014733_017FBC_CC7C.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20170120T005212_20170120T005239_014908_01853D_2A37.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20170201T005211_20170201T005238_015083_018A82_E40B.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20170213T005211_20170213T005238_015258_019001_60C3.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20170309T005213_20170309T005240_015608_019AA7_5C8D.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20170321T005213_20170321T005240_015783_019FDB_D2EB.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20170402T005214_20170402T005241_015958_01A50A_31B2.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20170414T005214_20170414T005241_016133_01AA5B_390E.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20170508T005215_20170508T005242_016483_01B506_58C7.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20170520T005216_20170520T005243_016658_01BA60_51FB.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20171104T005223_20171104T005250_019108_020540_3E3C.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20171128T005222_20171128T005249_019458_02103B_471D.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20171210T005222_20171210T005249_019633_0215B4_895B.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20180103T005221_20180103T005248_019983_02209D_96FF.SAFE
/media/iirs/'New Volume'/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20180115T005220_20180115T005247_020158_022624_D9EC.SAFE

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure the script could handle this `'New Volume'` with a space in the middle.  You could 
1) change it to `New\ Volume` 
2) don't use space in names
I suggest 2)

**Comment by misha0402** [comment]
its the name of the mounted disk and I dont have administrative rights to modify its name. I will try using first

**Comment by misha0402** [comment]
I tried with the backslash but got an error:

Unmatched '''.
Combing /media/iirs/New\ date: invalid date ‘/med/ia//i rs:/N:ew’
date: invalid date ‘/med/ia//i rs:/N:ew’
...
date: invalid date ‘/media/iirs/New\\ - 1 day’
date: invalid date ‘/media/iirs/New\\ + 1 day’
grep: Trailing backslash
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure how the `\ `characters are handled, but it did not got parsed to the script. It's always a pain to have spaces in file names. Maybe consider double quoting the whole thing? e.g.
 `"/media/iirs/New Volume/Pratibha/batch/des/data/S1A_IW_SLC__1SDV_20161121T005215_20161121T005242_014033_0169FE_6602.SAFE"`
