### ISSUE TITLE
[Help]: organize_files_tops_linux.csh - Missing }

### ISSUE THREAD

**Issue by lumirinc** [gmtsar/gmtsar#281]
Hello Everyone, 

While processing time series analysis. I am facing strange error that only state "Missing }" when I execute organize_files_tops_linux.csh. Is there any idea where's the issue? 

(base) lumir@lumir:/backup/InSAR/Pakistan/Karachi/asc/2019/data$ organize_files_tops_linux.csh SAFE_filelist ../reframed/pins.ll 1
Missing }.

Regards

**Comment by Xiaohua-Eric-Xu** [comment]
So it didn't execute anything really. Could you delete orbits.list and re-run the command? Send the logfile, your SAFE_filelist and your pins.ll.

**Comment by lumirinc** [comment]
Thank you very much for your kind response. Below kindly find the content of **pins.ll** and **SAFE_filelis**. I tried re-running the code however it's not generating **orbit.list** file. 

**### pins.ll**
66.953996 24.702188
66.988465 25.033054

**### SAFE_filelist**:
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190103T133517_20190103T133545_025314_02CD00_4004.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190115T133517_20190115T133545_025489_02D351_8598.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190127T133517_20190127T133544_025664_02D9BC_0423.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190208T133516_20190208T133544_025839_02E003_F7DC.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190220T133516_20190220T133544_026014_02E63D_8A61.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190304T133516_20190304T133544_026189_02EC88_57F5.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190316T133516_20190316T133544_026364_02F2F4_CF21.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190328T133516_20190328T133544_026539_02F95C_2CCC.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190409T133516_20190409T133544_026714_02FFCF_DEF7.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190421T133517_20190421T133545_026889_03061B_6AC6.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190503T133517_20190503T133545_027064_030C7F_E239.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190515T133518_20190515T133546_027239_031236_D150.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190527T133519_20190527T133546_027414_0317A9_C974.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190608T133519_20190608T133547_027589_031D0A_4E61.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190620T133520_20190620T133548_027764_032244_CF87.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190702T133521_20190702T133549_027939_03278C_E7DE.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190714T133521_20190714T133549_028114_032CD6_8DD5.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190726T133522_20190726T133550_028289_03322A_08DD.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190807T133523_20190807T133551_028464_033782_603D.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190819T133524_20190819T133552_028639_033D8F_E5FA.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190831T133524_20190831T133552_028814_0343AD_62FF.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190912T133525_20190912T133553_028989_0349C0_479E.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20190924T133525_20190924T133553_029164_034FB9_AD48.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20191006T133526_20191006T133553_029339_0355C4_C681.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20191018T133526_20191018T133553_029514_035BC9_5C27.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20191030T133526_20191030T133553_029689_0361E1_7A07.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20191111T133526_20191111T133554_029864_036801_04FF.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20191123T133525_20191123T133553_030039_036E0E_BE2E.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20191205T133525_20191205T133553_030214_03741C_53A5.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20191217T133524_20191217T133552_030389_037A2A_FEBE.SAFE
/backup/InSAR/Pakistan/Karachi/asc/2019/data/S1A_IW_SLC__1SDV_20191229T133524_20191229T133552_030564_03802E_3E34.SAFE

**Comment by lumirinc** [comment]
I also tried to download orbit files using sentineleof python package and run organize_files_tops_linux.csh SAFE_filelist ../reframed/pins.ll 2 but still get same error "**Missing }**"

**Comment by Xiaohua-Eric-Xu** [comment]
Are you able to execute this command and get orbits.html?
```
wget "https://s1qc.asf.alaska.edu/aux_poeorb" -O orbits.html
```

**Comment by lumirinc** [comment]
Yes by using the above command I get orbit.hmtl

**Comment by Xiaohua-Eric-Xu** [comment]
If it works, orbits.list should be generated. Attached are those lines in the code, where `$url_root` is `"https://s1qc.asf.alaska.edu/aux_poeorb"`
```
 42   if (! -f orbits.list) then
 43     wget $url_root -O orbits.html
 44     grep EOF orbits.html | awk -F'"' '{print $2}' > orbits.list
 45     rm orbits.html
 46   endif
```
Or you could follow above and create orbits.list and then run the command to see whether things run through.

**Comment by lumirinc** [comment]
The issue is still the same. After generating orbit.html file, when I run the command it gives the same "Missing }" error.

**Comment by Xiaohua-Eric-Xu** [comment]
Do you mean the following line does not run through? i.e. no orbits.list generated? Could you do it manually and check on the results?
```
grep EOF orbits.html | awk -F'"' '{print $2}' > orbits.list
```

**Comment by lumirinc** [comment]
The command runs and create an orbit list. 

grep EOF orbits.html | awk -F'"' '{print $2}' > orbits.list

However to proceed with organize_files_tops_linux.csh SAFE_filelist ../reframed/pins.ll 1 don't run. It still gives "Missing }".

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, this is strange. I could not reproduce this error on my end. What your test mean is that the script did not execute the lines in the script and no orbits.list is generated. But when you run them manually, the commands ran OK. 

Are you able to locate the error in any ways, i.e. which line in the script? You could get there by adding a few "echo 1" to the script. It should be between line 40 and line 70.

And could you send me your version of organize_files_tops_linux.csh? Or let me know which version of GMTSAR you are using?

**Comment by lumirinc** [comment]
Kindly find organize_files_tops_linux.csh I change the extension to txt so the file could be uploaded here. I am using GMTSAR 6.1. Meanwhile, I am also trying to locate the line as suggested between line 40 and 70.

[organize_files_tops_linux.txt](https://github.com/gmtsar/gmtsar/files/8128827/organize_files_tops_linux.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
The script looks OK to me. Is there anything in your .cshrc file that give the error? What if you delete that `source ~/.cshrc` line. (this is already deleted in the master branch)

**Comment by lumirinc** [comment]
I tried several times and couldn't understand the issue. A fresh installation of GMTSAR worked for me.
