### ISSUE TITLE
[Help]: free(): invalid pointer

### ISSUE THREAD

**Issue by mcontk** [gmtsar/gmtsar#285]
Hello, when creating the first interferogram (mode 1) with :
intf_tops.csh one.in batch_tops.config

I get the message :  
free(): invalid pointer
Abortar (se ha creado un `core')

----------------------
START FORM A STACK OF INTERFEROGRAMS

INTF.CSH, FILTER.CSH - START
Cutting SLC image to 3130/27070/5360/12130
Number of lines is set to a multiple of 4
Number of range pixels is set to a multiple of 4
New PRM file written ...
Writing image (23940 x 6768) ...
free(): invalid pointer
Abortar (se ha creado un `core')
Number of lines is set to a multiple of 4
Number of range pixels is set to a multiple of 4
New PRM file written ...
Writing image (23940 x 6768) ...
free(): invalid pointer
Abortar (se ha creado un `core')
......master LED file S1_20190112_ALL_F2.LED 
.........aligned LED file S1_20190124_ALL_F2.LED 
......master LED file S1_20190112_ALL_F2.LED 
.........aligned LED file S1_20190112_ALL_F2.LED 
intf.csh
running phasediff...
reading topo topo_ra.grd
 xdim 23940, ydim 6768 
filter.csh
setting range_dec = 8, azimuth_dec = 2
gauss_60 2 4 (1 2)
making amplitudes...
filtering interferogram...
making amplitude...
making correlation...
making phase...
filtering phase...
phasefilt: Generating new FFTW Wisdom, be patient...
phasefilt: Generating new FFTW Wisdom, be patient...
INTF.CSH, FILTER.CSH - END

SKIP UNWRAP PHASE

GEOCODE.CSH - START
SKIP GEOCODING

END STACK OF TOPS INTERFEROGRAMS

OS: Linux (openSuSE Leap 15.3)
GMTSAR version: 6.1

**Comment by Xiaohua-Eric-Xu** [comment]
Seems something went wrong with cut_slc.c. What's num_rng_bins and num_lines in your PRM files?

**Comment by mcontk** [comment]
In my master.PRM I have

num_rng_bins		= 23940
num_lines		= 6768

**Comment by Xiaohua-Eric-Xu** [comment]
I mean the PRM files in the raw directory. This is a strange error related to these lines below in cut_slc.c, I think, which is confusing to me. 
```
...
102         buf_in = (short *)malloc(pp.num_rng_bins * 2 * sizeof(short));
...
141         buf_out = (short *)malloc(pp.num_rng_bins * 2 * sizeof(short));
...
159     free(buf_out);
160     free(buf_in);
...
```

**Comment by mcontk** [comment]
... For example S1_20190430_ALL_F2.PRM
num_rng_bins		= 28088
num_lines		= 12192

**Comment by Xiaohua-Eric-Xu** [comment]
If you don't specify region_cut (leave it blank), will things run through?

**Comment by mcontk** [comment]
Yes, the same creates the interferograms without cutting the region of interest, but without the message : " free(): invalid pointer"
Then I try the cut again and the message appears again.

---- region_cut (leave it blank) ---
intf_tops.csh one.in batch_tops.config 

clean up topo/ folder

 
DEM2TOPOPHASE.CSH - START
USER SHOULD PROVIDE DEM FILE
 range decimation is:  2
blockmedian: Provides 3, expects 3-column binary data
blockmedian: Processing input table data
blockmedian: W: 0 E: 28320 S: 0 N: 12192 n_columns: 14160 n_rows: 6096
blockmedian: Input 3 columns via binary records using format ddd
blockmedian: Output 3 columns via binary records using format ddd
blockmedian: N read: 1997918 N used: 1993438 outside_area: 4480 N cells filled: 1989834
surface: Provides 3, expects 3-column binary data
surface: Grid domain: W: -240 E: 28560 S: -48 N: 12240 n_columns: 14400 n_rows: 6144 [pixel registration]
surface: Processing input table data
surface: Input 3 columns via binary records using format ddd
surface: Minimum value of your dataset x,y,z at: surface: 18314.9511719 11033.9638672 356.547454834
surface: Maximum value of your dataset x,y,z at: surface: 4924.65380859 7698.47949219 4083.41088867
surface: LS plane determined: z = 2329.93 + (-0.08154 * col) + (-0.115881 * row)
surface: Grid	Mode	Iteration	Max Change	Conv Limit	Total Iterations
surface:  192	D	   15214	0.000176114596067	0.00017681266607	     15214
surface:   64	I	      50	0.00049713342382	0.000530437998209	     15264
surface:   64	D	   64000	0.000774105560823	0.000530437998209	     79264
surface:   32	I	      28	0.000787576968132	0.00106087599642	     79292
surface:   32	D	   32000	0.00432070375005	0.00106087599642	    111292
surface:   16	I	      25	0.00174707916513	0.00212175199283	    111317
surface:   16	D	   16000	0.00418244861969	0.00212175199283	    127317
surface:    8	I	      23	0.00352631409864	0.00424350398567	    127340
surface:    8	D	    8000	0.0101310949784	0.00424350398567	    135340
surface:    4	I	      21	0.0067766567939	0.00848700797134	    135361
surface:    4	D	    4000	0.0134957329432	0.00848700797134	    139361
surface:    2	I	      20	0.0113960408915	0.0169740159427	    139381
surface:    2	D	    2000	0.0627231809129	0.0169740159427	    141381
surface:    1	I	      18	0.0274822869933	0.0339480318854	    141399
surface:    1	D	    1000	0.0423303952836	0.0339480318854	    142399
surface: Fit info: N data points  N nodes	mean error	rms error	curvature
surface: 	 1989834	88494145	2.38466572021e-07	0.0147721676022	136181.329157
grd2cpt: Processing input grid(s)
grd2cpt: Mean and S.D. of data are 1445.44495353 546.990410984
grdimage: Allocates memory and read data file topo_ra.grd
grdimage: Evaluate image pixel colors
grdimage: Creating 8-bit grayshade image
Topo range/azimuth map: topo_ra.pdf
DEM2TOPOPHASE.CSH - END
NO TOPOPHASE SHIFT 

START FORM A STACK OF INTERFEROGRAMS


INTF.CSH, FILTER.CSH - START
......master LED file S1_20190112_ALL_F2.LED 
.........aligned LED file S1_20190124_ALL_F2.LED 
......master LED file S1_20190112_ALL_F2.LED 
.........aligned LED file S1_20190112_ALL_F2.LED 
intf.csh
running phasediff...
reading topo topo_ra.grd
 xdim 28320, ydim 12192 
filter.csh
setting range_dec = 8, azimuth_dec = 2
gauss_120 2 4 (1 2)
making amplitudes...
filtering interferogram...
making amplitude...
making correlation...
making phase...
filtering phase...
INTF.CSH, FILTER.CSH - END

SKIP UNWRAP PHASE

GEOCODE.CSH - START
SKIP GEOCODING

END STACK OF TOPS INTERFEROGRAMS

**Comment by Xiaohua-Eric-Xu** [comment]
I don't really know the reason. Honestly openSuSE is one of the systems we don't have access to, so it's possible that certain codes does not run smoothly on that. Could you run cut_slc over some of the aligned SLCs and see how things go?

**Comment by mcontk** [comment]
cut_slc S1_20211203_ALL_F2.PRM test 3420/26820/5415/12129

Number of lines is set to a multiple of 4
Number of range pixels is set to a multiple of 4
New PRM file written ...
Writing image (23400 x 6712) ...
free(): invalid pointer
Abortado (`core' generado)

Then test.PRM and test.SLC were generated
( https://www.dropbox.com/sh/04tk14301kp334o/AACy2Nl5BWUIUmMhIxlWBG9La?dl=0  )

**Comment by Xiaohua-Eric-Xu** [comment]
That's the part I don't understand. Both variables `buf_in` and `buf_out` are from `malloc`, and then `free`-ing them cause `invalid pointer` error. How come the program does not think it as heap memory?

One way is to not malloc, but rather assign an array in the program to replace `buf_in` and `buf_out`. They are not super large anyways.

Funny thing is this is already at the end of the `cut_slc` program and everything's done. Should not affect the processing though.

**Comment by mcontk** [comment]
Well, the products are obtained but I was disturbed by the message regarding the pointer.  Thank you very much for your attention to my inquiry.

googling I found this :
https://www.delftstack.com/howto/c/c-free-invalid-pointer-error

**Comment by Xiaohua-Eric-Xu** [comment]
Following what you found, they are dynamically allocated, so not case 1. And they were never freed before line 159-160, so not case 2. I wish they could be that simple though.

**Comment by mcontk** [comment]
Ok, thanks again. I will continue with my process... be well!
