### ISSUE TITLE
[Help]: gawk: command line: 1: (filename = - FNR = 1) fatal error: trying to divide 0

### ISSUE THREAD

**Issue by Gigi-gugu** [gmtsar/gmtsar#286]
Dear Professor, when I use the `[align_tops_esd.csh]` command to align the image, 'mv: unable to' tmp coef 'moves to' rm coef ': text file busy'

I want to ask, what is the reason for this? Is the permission of Linux insufficient? Thank you in advance for your help.

gmtsar-user@gmtsarVB:/media/sf_windowshare/YuLinSENTINEL/F2/raw$ align_tops_esd.csh s1a-iw2-slc-vv-20191009t104203-20191009t104228-029381-03572e-005 s1a-iw2-slc-vv-20191009t104203-20191009t104228-029381-03572e-005.EOF s1a-iw2-slc-vv-20191021t104203-20191021t104228-029556-035d3c-005 s1a-iw2-slc-vv-20191021t104203-20191021t104228-029556-035d3c-005.EOF dem.grd
S1_20191009_104203_F2
S1_20191021_104203_F2
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Writing 52 lines of precise orbit for the LED file...
Successfully opened S1_20191009_104203_F2.PRM 
Successfully opened S1_20191021_104203_F2.PRM 
[1] 10280
[2] 10281
[2]    Done                   SAT_llt2rat S1_20191021_104203_F2.PRM 1 < topo.llt > aligned.ratll
[1]  + Done                   SAT_llt2rat S1_20191009_104203_F2.PRM 1 < topo.llt > master.ratll
[1] 10297
[2] 10298
[2]  + Done                   gmt surface atmp.xyz -bi3d -R0/25616/0/12192 -I16/8 -T0.3 -Gatmp.grd -N1000 -r
[1]  + Done                   gmt surface rtmp.xyz -bi3d -R0/25616/0/12192 -I16/8 -T0.3 -Grtmp.grd -N1000 -r
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Writing SLCL & SLCH..
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 1 
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Reading in range and azimuth shifts table...
Writing SLCL & SLCH..
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 6 
Running Spectral Diversity...
Updating azimuth shift with a constant...(medain 0.00537226)
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Writing SLC..Image Size: 25616 X 12188...
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 1 
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Reading in range and azimuth shifts table...
Writing SLC..Image Size: 25616 X 12192...
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 6 
mv: 无法将'tmp.coef' 移动至'rm.coef': 文本文件忙
mv: 无法将'tmp.coef' 移动至'am.coef': 文本文件忙
gawk: 命令行:1: (FILENAME=- FNR=1) 致命错误： 试图除0
gawk: 命令行:1: (FILENAME=- FNR=1) 致命错误： 试图除0
gawk: 命令行:1: (FILENAME=- FNR=1) 致命错误： 试图除0
gawk: 命令行:1: (FILENAME=- FNR=1) 致命错误： 试图除0
Writing 52 lines of precise orbit for the LED file...
Writing 52 lines of precise orbit for the LED file...
Successfully opened S1_20191009_104203_F2.PRM 
Successfully opened S1_20191021_104203_F2.PRM

**Comment by weibangding** [comment]
By the way, I used the sample data S1A_Stack_CPGF_T173  again. There is no correct for elevation antenna pattern change. The above problem also occurs when I use preproc_batch_tops_esd.csh data. in dem. grd 2. Will this affect the result?
[log.txt](https://github.com/gmtsar/gmtsar/files/8146572/log.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
The error is probably from this command. Could you try it in your raw directory?
```
fitoffset.csh 3 3 offset.dat
```

**Comment by Gigi-gugu** [comment]
Thank you very much for your reply. I tried your suggestion and ran the command.
gmtsar-user@gmtsarVB:/media/sf_windowshare/test/raw$ fitoffset.csh 3 3 offset.dat
rshift =  25 
sub_int_r =  0.8663 
stretch_r =  9.90568e-05 
a_stretch_r =  -3.38393e-05 
ashift =  -8 
sub_int_a =  0.17265 
stretch_a =  4.67161e-06 
a_stretch_a =  8.23918e-06

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, these error should be from that actually. Inside fitoffset.csh it is basically fitting a trend to the records with gmt.  

Are you able to reproduce the error with the right offset.dat and send that over? Seems all except the last acquisition will give you this error based on the log.txt you sent.

**Comment by Gigi-gugu** [comment]
> Hmmm, these error should be from that actually. Inside fitoffset.csh it is basically fitting a trend to the records with gmt.
> 
> Are you able to reproduce the error with the right offset.dat and send that over? Seems all except the last acquisition will give you this error based on the log.txt you sent.

right offset.dat? Is it offset.dat in the raw directory? What command should I execute to check it? I'm sorry I'm a little confused.

**Comment by Xiaohua-Eric-Xu** [comment]
Please run the command from you posted `align_tops_esd.csh s1a-iw2-slc-vv-20191009t104203-20191009t104228-029381-03572e-005 s1a-iw2-slc-vv-20191009t104203-20191009t104228-029381-03572e-005.EOF s1a-iw2-slc-vv-20191021t104203-20191021t104228-029556-035d3c-005 s1a-iw2-slc-vv-20191021t104203-20191021t104228-029556-035d3c-005.EOF dem.grd` and send the offset.dat from that command.

**Comment by Gigi-gugu** [comment]
According to your suggestion, I run `fitoffset.csh` to get `offset.dat`, and then run `align_tops_esd. csh` to get the result. There is no problem.  Thank you very much for your help.


gmtsar-user@gmtsarVB:/media/sf_windowshare/YuLinSENTINEL/F2/raw$ fitoffset.csh 3 3 offset.dat
rshift =  6 
sub_int_r =  0.16348 
stretch_r =  1.25679e-05 
a_stretch_r =  4.79405e-05 
ashift =  -1 
sub_int_a =  0.724861 
stretch_a =  -2.57164e-06 
a_stretch_a =  1.74739e-06 
gmtsar-user@gmtsarVB:/media/sf_windowshare/YuLinSENTINEL/F2/raw$ align_tops_esd.csh s1a-iw2-slc-vv-20191009t104203-20191009t104228-029381-03572e-005 s1a-iw2-slc-vv-20191009t104203-20191009t104228-029381-03572e-005.EOF s1a-iw2-slc-vv-20191021t104203-20191021t104228-029556-035d3c-005 s1a-iw2-slc-vv-20191021t104203-20191021t104228-029556-035d3c-005.EOF dem.grd
S1_20191009_104203_F2
S1_20191021_104203_F2
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Writing 52 lines of precise orbit for the LED file...
Successfully opened S1_20191009_104203_F2.PRM 
Successfully opened S1_20191021_104203_F2.PRM 
[1] 7241
[2] 7242
[2]  + Done                   SAT_llt2rat S1_20191021_104203_F2.PRM 1 < topo.llt > aligned.ratll
[1]  + Done                   SAT_llt2rat S1_20191009_104203_F2.PRM 1 < topo.llt > master.ratll
[1] 7263
[2] 7264
[2]  + Done                   gmt surface atmp.xyz -bi3d -R0/25616/0/12192 -I16/8 -T0.3 -Gatmp.grd -N1000 -r
[1]  + Done                   gmt surface rtmp.xyz -bi3d -R0/25616/0/12192 -I16/8 -T0.3 -Grtmp.grd -N1000 -r
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Writing SLCL & SLCH..
Working on burst  #1 #2 #3    
 #4 #5 #6 #7 #8 #9
number of points clipped to short int 1 
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Reading in range and azimuth shifts table...
Writing SLCL & SLCH..
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 6 
Running Spectral Diversity...
Updating azimuth shift with a constant...(medain 0.00537226)
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Writing SLC..Image Size: 25616 X 12188...
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 1 
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Reading in range and azimuth shifts table...
Writing SLC..Image Size: 25616 X 12192...
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 6 
Writing 52 lines of precise orbit for the LED file...
Writing 52 lines of precise orbit for the LED file...
Successfully opened S1_20191009_104203_F2.PRM 
Successfully opened S1_20191021_104203_F2.PRM 
gmtsar-user@gmtsarVB:/media/sf_windowshare/YuLinSENTINEL/F2/raw$

**Comment by Gigi-gugu** [comment]
According to your suggestion, I run `fitoffset.csh` to get `offset.dat`, and then run `align_tops_esd. csh` to get the result. There is no problem.  Thank you very much for your help.


gmtsar-user@gmtsarVB:/media/sf_windowshare/YuLinSENTINEL/F2/raw$ fitoffset.csh 3 3 offset.dat
rshift =  6 
sub_int_r =  0.16348 
stretch_r =  1.25679e-05 
a_stretch_r =  4.79405e-05 
ashift =  -1 
sub_int_a =  0.724861 
stretch_a =  -2.57164e-06 
a_stretch_a =  1.74739e-06 
gmtsar-user@gmtsarVB:/media/sf_windowshare/YuLinSENTINEL/F2/raw$ align_tops_esd.csh s1a-iw2-slc-vv-20191009t104203-20191009t104228-029381-03572e-005 s1a-iw2-slc-vv-20191009t104203-20191009t104228-029381-03572e-005.EOF s1a-iw2-slc-vv-20191021t104203-20191021t104228-029556-035d3c-005 s1a-iw2-slc-vv-20191021t104203-20191021t104228-029556-035d3c-005.EOF dem.grd
S1_20191009_104203_F2
S1_20191021_104203_F2
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Writing 52 lines of precise orbit for the LED file...
Successfully opened S1_20191009_104203_F2.PRM 
Successfully opened S1_20191021_104203_F2.PRM 
[1] 7241
[2] 7242
[2]  + Done                   SAT_llt2rat S1_20191021_104203_F2.PRM 1 < topo.llt > aligned.ratll
[1]  + Done                   SAT_llt2rat S1_20191009_104203_F2.PRM 1 < topo.llt > master.ratll
[1] 7263
[2] 7264
[2]  + Done                   gmt surface atmp.xyz -bi3d -R0/25616/0/12192 -I16/8 -T0.3 -Gatmp.grd -N1000 -r
[1]  + Done                   gmt surface rtmp.xyz -bi3d -R0/25616/0/12192 -I16/8 -T0.3 -Grtmp.grd -N1000 -r
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Writing SLCL & SLCH..
Working on burst  #1 #2 #3    
 #4 #5 #6 #7 #8 #9
number of points clipped to short int 1 
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Reading in range and azimuth shifts table...
Writing SLCL & SLCH..
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 6 
Running Spectral Diversity...
Updating azimuth shift with a constant...(medain 0.00537226)
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Writing SLC..Image Size: 25616 X 12188...
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 1 
Reading in 5305 lines of info from XML...
Writing 16 lines for orbit...
Reading in range and azimuth shifts table...
Writing SLC..Image Size: 25616 X 12192...
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 6 
Writing 52 lines of precise orbit for the LED file...
Writing 52 lines of precise orbit for the LED file...
Successfully opened S1_20191009_104203_F2.PRM 
Successfully opened S1_20191021_104203_F2.PRM

**Comment by Xiaohua-Eric-Xu** [comment]
Wait what? I am happy to see the error disappeared. But that should not be the solution though. `fitoffset.csh 3 3 offset.dat` is a line inside `align_tops_esd.csh` that produced the error. I guess I am really confused.

**Comment by Gigi-gugu** [comment]
> Wait what? I am happy to see the error disappeared. But that should not be the solution though. `[fitoffset.csh 3 3 offset.dat](url)` is a line inside `align_tops_esd.csh` that produced the error. I guess I am really confused.
I guess I am really confused.
I now encounter a new problem. There is no problem when I deal with iw3 strip, but there is a problem when I deal with iw2. It reports that make_slc_s1a_tops does not work, but there is no problem before and after. The log file is shown below.
x-special/nautilus-clipboard
copy
file:///home/zhoulv/%E6%A1%8C%E9%9D%A2/log.txt

**Comment by Gigi-gugu** [comment]
I guess I am really confused too. 

> Wait what? I am happy to see the error disappeared. But that should not be the solution though. `fitoffset.csh 3 3 offset.dat` is a line inside `align_tops_esd.csh` that produced the error. I guess I am really confused.

I guess I am really confused too.
I'm very sorry to bother you again
 But I now encounter a new problem. There is no problem when I deal with iw3 strip, but there is a problem when I deal with iw2. It reports that make_slc_s1a_tops does not work, but there is no problem before and after. The log file is shown below.
[log.txt](https://github.com/gmtsar/gmtsar/files/8184017/log.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
OK, that's one date that failed which is the one after 20180721. Could you send your data.in?

**Comment by Gigi-gugu** [comment]
> OK, that's one date that failed which is the one after 20180721. Could you send your data.in?
Sorry for the late reply. In order to upload the file, I changed the suffix name to txt.

[datain.txt](https://github.com/gmtsar/gmtsar/files/8192594/datain.txt)
