### ISSUE TITLE
[Help]: Problems to generate topo_ra

### ISSUE THREAD

**Issue by jlseco** [gmtsar/gmtsar#289]
Hello,
I have a problem when I try to make a dem topo_ra using the command dem2topo_ra.chs master.PRM dem.grd. I am attaching below the topo_ra.pdf which I got using two different dem, and both showed some problems.
I downloaded the others from the REMA page (https://www.pgc.umn.edu/data/rema/) and from the GMTSAR generate dem (https://topex.ucsd.edu/gmtsar/demgen/).

I also attached, just in case, a link where you can find the dems (REMA and ASTER) and the master image.

Do you know why it happens?

**OS and software version**

OS: Ubuntu 20.04.4
GMTSAR version: 6.0.0

**Log file**
[topo_ra_ASTER.pdf](https://github.com/gmtsar/gmtsar/files/8172171/topo_ra_ASTER.pdf)
[topo_ra_REMA.pdf](https://github.com/gmtsar/gmtsar/files/8172173/topo_ra_REMA.pdf)
https://drive.google.com/drive/folders/1RUzZnfwzEPc3-mo9CA_LzAj8RFuPkznS?usp=sharing

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure. Maybe @dsandwell knows more. 
The REMA data you use need to be converted to DEM above WGS84 ellipsoid in meters. To me the plot from REMA has much larger values than expected. 
![image](https://user-images.githubusercontent.com/16844111/156488342-6b1d07a7-2c5a-47e8-8967-a76cc8655569.png)
