### ISSUE TITLE
Error while installing GMTSAR

### ISSUE THREAD

**Issue by ptimsina-tech** [gmtsar/gmtsar#29]
I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any.
![error_make](https://user-images.githubusercontent.com/62301243/87785738-f73e4b00-c838-11ea-960f-aec9b7910934.png)

**Comment by dsandwell** [comment]
Dear Ptimsina,

The makefile was unable to find library gmtsar.  Could you send the entire log file from the make command

make >$ log.txt

It is likely that there is an error in making libgmtsar.a.  That could be due to any number of things.

David


> On Jul 17, 2020, at 5:23 AM, ptimsina-tech <notifications@github.com> wrote:
> 
> 
> I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any.
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by ptimsina-tech** [comment]
> Dear Ptimsina, The makefile was unable to find library gmtsar. Could you send the entire log file from the make command make >$ log.txt It is likely that there is an error in making libgmtsar.a. That could be due to any number of things. David
> On Jul 17, 2020, at 5:23 AM, ptimsina-tech ***@***.***> wrote: I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037

This is my log file from the make command:
[log.txt](https://github.com/gmtsar/gmtsar/files/4938450/log.txt)

**Comment by dsandwell** [comment]
OK this is only part of the log.  Please do a make clean first and then a make.

> On Jul 17, 2020, at 7:53 AM, ptimsina-tech <notifications@github.com> wrote:
> 
> 
> Dear Ptimsina, The makefile was unable to find library gmtsar. Could you send the entire log file from the make command make >$ log.txt It is likely that there is an error in making libgmtsar.a. That could be due to any number of things. David
> On Jul 17, 2020, at 5:23 AM, ptimsina-tech @.***> wrote: I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037
> 
> This is my log file from the make command:
> log.txt
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by ptimsina-tech** [comment]
> OK this is only part of the log. Please do a make clean first and then a make.
> On Jul 17, 2020, at 7:53 AM, ptimsina-tech ***@***.***> wrote: Dear Ptimsina, The makefile was unable to find library gmtsar. Could you send the entire log file from the make command make >$ log.txt It is likely that there is an error in making libgmtsar.a. That could be due to any number of things. David On Jul 17, 2020, at 5:23 AM, ptimsina-tech @.***> wrote: I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 This is my log file from the make command: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037

I think this is the complete log:
[log.txt](https://github.com/gmtsar/gmtsar/files/4938953/log.txt)

**Comment by dsandwell** [comment]
OK now I don’t see any errors.  There are two things you can do.

1) type make install and test the code.

2) do a 

make spotless
autoconf
autoconf
./configure --with-orbits-dir=/usr/local/orbits >& log.txt
makea >>& log.txt
make install >>& log.txt

This log.txt file should have everything.



> On Jul 17, 2020, at 9:32 AM, ptimsina-tech <notifications@github.com> wrote:
> 
> 
> OK this is only part of the log. Please do a make clean first and then a make.
> On Jul 17, 2020, at 7:53 AM, ptimsina-tech @.> wrote: Dear Ptimsina, The makefile was unable to find library gmtsar. Could you send the entire log file from the make command make >$ log.txt It is likely that there is an error in making libgmtsar.a. That could be due to any number of things. David On Jul 17, 2020, at 5:23 AM, ptimsina-tech @.> wrote: I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 This is my log file from the make command: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037
> 
> I think this is the complete log:
> log.txt
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by ptimsina-tech** [comment]
> OK now I don’t see any errors. There are two things you can do. 1) type make install and test the code. 2) do a make spotless autoconf autoconf ./configure --with-orbits-dir=/usr/local/orbits >& log.txt makea >>& log.txt make install >>& log.txt This log.txt file should have everything.
> On Jul 17, 2020, at 9:32 AM, ptimsina-tech ***@***.***> wrote: OK this is only part of the log. Please do a make clean first and then a make. On Jul 17, 2020, at 7:53 AM, ptimsina-tech @.> wrote: Dear Ptimsina, The makefile was unable to find library gmtsar. Could you send the entire log file from the make command make >$ log.txt It is likely that there is an error in making libgmtsar.a. That could be due to any number of things. David On Jul 17, 2020, at 5:23 AM, ptimsina-tech @.> wrote: I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 This is my log file from the make command: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I think this is the complete log: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037

I did that and also add path in .bashrc file. Now, how to check whether GMTSAR is installed or not. 
Actually, Its pretty amazing why log file doesnot print the error that displayed in terminal...here I screenshot the selected errors...
![e1](https://user-images.githubusercontent.com/62301243/87812127-05ec2880-c860-11ea-8ceb-825c0229835e.png)
![e2](https://user-images.githubusercontent.com/62301243/87812142-0a184600-c860-11ea-8030-bd752f04476e.png)
![e3](https://user-images.githubusercontent.com/62301243/87812159-0c7aa000-c860-11ea-9ab9-a8668a86c6ed.png)
![e4](https://user-images.githubusercontent.com/62301243/87812177-12708100-c860-11ea-9f04-71b13f5a171a.png)

**Comment by dsandwell** [comment]
Great.  The fundamental error is that gmt.h was not found.

When you install GMT how was that done?  This looks like UBUNTU  so you may use apt-get.  


> On Jul 17, 2020, at 10:02 AM, ptimsina-tech <notifications@github.com> wrote:
> 
> 
> OK now I don’t see any errors. There are two things you can do. 1) type make install and test the code. 2) do a make spotless autoconf autoconf ./configure --with-orbits-dir=/usr/local/orbits >& log.txt makea >>& log.txt make install >>& log.txt This log.txt file should have everything.
> On Jul 17, 2020, at 9:32 AM, ptimsina-tech @.***> wrote: OK this is only part of the log. Please do a make clean first and then a make. On Jul 17, 2020, at 7:53 AM, ptimsina-tech @.> wrote: Dear Ptimsina, The makefile was unable to find library gmtsar. Could you send the entire log file from the make command make >$ log.txt It is likely that there is an error in making libgmtsar.a. That could be due to any number of things. David On Jul 17, 2020, at 5:23 AM, ptimsina-tech @.> wrote: I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 This is my log file from the make command: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I think this is the complete log: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037
> 
> I did that and also add path in .bashrc file. Now, how to check whether GMTSAR is installed or not.
> Actually, Its pretty amazing why log file doesnot print the error that displayed in terminal...here I screenshot the selected errors...
> 
> 
> 
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by ptimsina-tech** [comment]
> Great. The fundamental error is that gmt.h was not found. When you install GMT how was that done? This looks like UBUNTU so you may use apt-get.
> On Jul 17, 2020, at 10:02 AM, ptimsina-tech ***@***.***> wrote: OK now I don’t see any errors. There are two things you can do. 1) type make install and test the code. 2) do a make spotless autoconf autoconf ./configure --with-orbits-dir=/usr/local/orbits >& log.txt makea >>& log.txt make install >>& log.txt This log.txt file should have everything. On Jul 17, 2020, at 9:32 AM, ptimsina-tech @.***> wrote: OK this is only part of the log. Please do a make clean first and then a make. On Jul 17, 2020, at 7:53 AM, ptimsina-tech @.> wrote: Dear Ptimsina, The makefile was unable to find library gmtsar. Could you send the entire log file from the make command make >$ log.txt It is likely that there is an error in making libgmtsar.a. That could be due to any number of things. David On Jul 17, 2020, at 5:23 AM, ptimsina-tech @.> wrote: I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 This is my log file from the make command: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I think this is the complete log: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I did that and also add path in .bashrc file. Now, how to check whether GMTSAR is installed or not. Actually, Its pretty amazing why log file doesnot print the error that displayed in terminal...here I screenshot the selected errors... — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037

I intalled version 6.1.0 using conda.

**Comment by dsandwell** [comment]
OK that is the problem.  The ./configure script for GMTSAR does not look for the GMT stuff in a users home directory where conda puts GMT.  This was a miscommunication between the GMT developers and the GMTSAR developers.

Please try the following from the WIKI.  You can keep your GMT6.0 in the conda area but may need to set your path correctly.

sudo apt-get install csh subversion autoconf libtiff5-dev libhdf5-dev
sudo apt-get install liblapack-dev
sudo apt-get install gfortran
sudo apt-get install g++
sudo apt-get install libgmt-dev
sudo apt-get install gmt gmt-dcw gmt-gshhg
sudo apt-get install gmt

sudo -i
cd /usr/local
git clone --branch 6.0 https://github.com/gmtsar/gmtsar GMTSAR
or
checkout the master version for more new but not stable features. 
git clone https://github.com/gmtsar/gmtsar GMTSAR
or for UBUNTU 14, 16 use V5.8
git clone --branch 5.8 https://github.com/gmtsar/gmtsar GMTSAR


cd GMTSAR
autoconf
./configure --with-orbits-dir=/usr/local/orbits
make
make install


> On Jul 17, 2020, at 11:32 AM, ptimsina-tech <notifications@github.com> wrote:
> 
> 
> Great. The fundamental error is that gmt.h was not found. When you install GMT how was that done? This looks like UBUNTU so you may use apt-get.
> On Jul 17, 2020, at 10:02 AM, ptimsina-tech @.> wrote: OK now I don’t see any errors. There are two things you can do. 1) type make install and test the code. 2) do a make spotless autoconf autoconf ./configure --with-orbits-dir=/usr/local/orbits >& log.txt makea >>& log.txt make install >>& log.txt This log.txt file should have everything. On Jul 17, 2020, at 9:32 AM, ptimsina-tech @.> wrote: OK this is only part of the log. Please do a make clean first and then a make. On Jul 17, 2020, at 7:53 AM, ptimsina-tech @.> wrote: Dear Ptimsina, The makefile was unable to find library gmtsar. Could you send the entire log file from the make command make >$ log.txt It is likely that there is an error in making libgmtsar.a. That could be due to any number of things. David On Jul 17, 2020, at 5:23 AM, ptimsina-tech @.> wrote: I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 This is my log file from the make command: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I think this is the complete log: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I did that and also add path in .bashrc file. Now, how to check whether GMTSAR is installed or not. Actually, Its pretty amazing why log file doesnot print the error that displayed in terminal...here I screenshot the selected errors... — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037
> 
> I intalled version 6.1.0 using conda.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by ptimsina-tech** [comment]
> OK that is the problem. The ./configure script for GMTSAR does not look for the GMT stuff in a users home directory where conda puts GMT. This was a miscommunication between the GMT developers and the GMTSAR developers. Please try the following from the WIKI. You can keep your GMT6.0 in the conda area but may need to set your path correctly. sudo apt-get install csh subversion autoconf libtiff5-dev libhdf5-dev sudo apt-get install liblapack-dev sudo apt-get install gfortran sudo apt-get install g++ sudo apt-get install libgmt-dev sudo apt-get install gmt gmt-dcw gmt-gshhg sudo apt-get install gmt sudo -i cd /usr/local git clone --branch 6.0 https://github.com/gmtsar/gmtsar GMTSAR or checkout the master version for more new but not stable features. git clone https://github.com/gmtsar/gmtsar GMTSAR or for UBUNTU 14, 16 use V5.8 git clone --branch 5.8 https://github.com/gmtsar/gmtsar GMTSAR cd GMTSAR autoconf ./configure --with-orbits-dir=/usr/local/orbits make make install
> On Jul 17, 2020, at 11:32 AM, ptimsina-tech ***@***.***> wrote: Great. The fundamental error is that gmt.h was not found. When you install GMT how was that done? This looks like UBUNTU so you may use apt-get. On Jul 17, 2020, at 10:02 AM, ptimsina-tech @.> wrote: OK now I don’t see any errors. There are two things you can do. 1) type make install and test the code. 2) do a make spotless autoconf autoconf ./configure --with-orbits-dir=/usr/local/orbits >& log.txt makea >>& log.txt make install >>& log.txt This log.txt file should have everything. On Jul 17, 2020, at 9:32 AM, ptimsina-tech @.> wrote: OK this is only part of the log. Please do a make clean first and then a make. On Jul 17, 2020, at 7:53 AM, ptimsina-tech @.> wrote: Dear Ptimsina, The makefile was unable to find library gmtsar. Could you send the entire log file from the make command make >$ log.txt It is likely that there is an error in making libgmtsar.a. That could be due to any number of things. David On Jul 17, 2020, at 5:23 AM, ptimsina-tech @.> wrote: I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 This is my log file from the make command: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I think this is the complete log: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I did that and also add path in .bashrc file. Now, how to check whether GMTSAR is installed or not. Actually, Its pretty amazing why log file doesnot print the error that displayed in terminal...here I screenshot the selected errors... — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I intalled version 6.1.0 using conda. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037

Thanks. I think now it installed correctly. By the way, how to check GMTSAR...installed or not?

**Comment by ptimsina-tech** [comment]
> > OK that is the problem. The ./configure script for GMTSAR does not look for the GMT stuff in a users home directory where conda puts GMT. This was a miscommunication between the GMT developers and the GMTSAR developers. Please try the following from the WIKI. You can keep your GMT6.0 in the conda area but may need to set your path correctly. sudo apt-get install csh subversion autoconf libtiff5-dev libhdf5-dev sudo apt-get install liblapack-dev sudo apt-get install gfortran sudo apt-get install g++ sudo apt-get install libgmt-dev sudo apt-get install gmt gmt-dcw gmt-gshhg sudo apt-get install gmt sudo -i cd /usr/local git clone --branch 6.0 https://github.com/gmtsar/gmtsar GMTSAR or checkout the master version for more new but not stable features. git clone https://github.com/gmtsar/gmtsar GMTSAR or for UBUNTU 14, 16 use V5.8 git clone --branch 5.8 https://github.com/gmtsar/gmtsar GMTSAR cd GMTSAR autoconf ./configure --with-orbits-dir=/usr/local/orbits make make install
> > On Jul 17, 2020, at 11:32 AM, ptimsina-tech _**@**_.***> wrote: Great. The fundamental error is that gmt.h was not found. When you install GMT how was that done? This looks like UBUNTU so you may use apt-get. On Jul 17, 2020, at 10:02 AM, ptimsina-tech @.> wrote: OK now I don’t see any errors. There are two things you can do. 1) type make install and test the code. 2) do a make spotless autoconf autoconf ./configure --with-orbits-dir=/usr/local/orbits >& log.txt makea >>& log.txt make install >>& log.txt This log.txt file should have everything. On Jul 17, 2020, at 9:32 AM, ptimsina-tech @.> wrote: OK this is only part of the log. Please do a make clean first and then a make. On Jul 17, 2020, at 7:53 AM, ptimsina-tech @.> wrote: Dear Ptimsina, The makefile was unable to find library gmtsar. Could you send the entire log file from the make command make >$ log.txt It is likely that there is an error in making libgmtsar.a. That could be due to any number of things. David On Jul 17, 2020, at 5:23 AM, ptimsina-tech @.> wrote: I got an error message as attached herewith while doing make after configuring the software GMTSAR. Kindly suggest the way to resolve it if any. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 This is my log file from the make command: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I think this is the complete log: log.txt — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I did that and also add path in .bashrc file. Now, how to check whether GMTSAR is installed or not. Actually, Its pretty amazing why log file doesnot print the error that displayed in terminal...here I screenshot the selected errors... — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037 I intalled version 6.1.0 using conda. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037
> 
> Thanks. I think now it installed correctly. By the way, how to check GMTSAR...installed or not?

I checked using the test code suggested in HW2, which runs fine. Thanks.

**Comment by alejobeap** [comment]
Dear
I Have problem with:

(base) pespin@lpvulc:~$ sudo apt-get install csh subversion autoconf libtiff5-dev libhdf5-dev
[sudo] password for pespin: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-11).
The following packages were automatically installed and are no longer required:
  libexttextcat-2.0-0 libexttextcat-data libmhash2 libmythes-1.2-0
  libneon27-gnutls liborcus-0.13-0 libraptor2-0 librasqal3 librdf0 libyajl2
  uno-libs3 ure
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  hdf5-helpers libaec-dev libapr1 libaprutil1 libhdf5-cpp-100 libjbig-dev
  libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblzma-dev libserf-1-1 libsvn1
  libtiffxx5
Suggested packages:
  libhdf5-doc liblzma-doc db5.3-util libapache2-mod-svn subversion-tools
The following NEW packages will be installed:
  csh hdf5-helpers libaec-dev libapr1 libaprutil1 libhdf5-cpp-100 libhdf5-dev
  libjbig-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblzma-dev
  libserf-1-1 libsvn1 libtiff5-dev libtiffxx5 subversion
0 upgraded, 17 newly installed, 0 to remove and 0 not upgraded.
Need to get 231 kB/5.751 kB of archives.
After this operation, 25,2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://security.ubuntu.com/ubuntu bionic-security/main amd64 libjpeg-turbo8-dev amd64 1.5.2-0ubuntu5.18.04.4
  Connection failed [IP: 2001:67c:1360:8001::23 80]
Err:2 http://security.ubuntu.com/ubuntu bionic-security/main amd64 libtiffxx5 amd64 4.0.9-5ubuntu0.3
  Connection failed [IP: 2001:67c:1562::18 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8-dev_1.5.2-0ubuntu5.18.04.4_amd64.deb  Connection failed [IP: 2001:67c:1360:8001::23 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/t/tiff/libtiffxx5_4.0.9-5ubuntu0.3_amd64.deb  Connection failed [IP: 2001:67c:1562::18 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Is possible to help me 
Thanks

Pedro

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Pedro,
Yes, please try to update. Seems like a connection problem.
Cheers,
Xiaohua(Eric)

**Comment by alejobeap** [comment]
Dear
Thanks
But I tryied some times and I had the same problem
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/t/tiff/libtiffxx5_4.0.9-5ubuntu0.3_amd64.deb  Connection failed [IP: 2001:67c:1562::15 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, please check whether you are having the same issue as indicated by this page.
https://askubuntu.com/questions/540168/connection-failed-during-sudo-apt-get-update
