### ISSUE TITLE
[Help]: Can i Extract Point Velocities/Displacements from InSAR LOS Grids generated from sbas in GMTSAR?

### ISSUE THREAD

**Issue by misha0402** [gmtsar/gmtsar#290]
I have generated displacement and velocity grd files and would like to generate a time series of velocity and displacements at point locations. Thus, I want to extract the point velocities.

Anyway I can do that?

**Comment by Xiaohua-Eric-Xu** [comment]
There is a script called `extract_one_time_series.csh`

**Comment by omarwater98** [comment]
> There is a script called `extract_one_time_series.csh`

Hi Teacher Xiaohua, these GNSS points (coordinates) have to be downloads from one of the pages the manual says?
cause i have points with one displayment registered like this:
![GNSS](https://user-images.githubusercontent.com/113547446/196835883-be78b57a-b52b-4c5d-9bcb-10717e2823a3.png)
i created this file using 
cat > GNSS.ll
but aplaying the comand: 
gmt grdtrack GNSS.ll -G../topo/dem.grd > GNSS.llh
not generated nothing

And runing the 
./extract_one_time_series.csh -100.9013 22.1715 S1_20200619_ALL_F1.PRM dem.grd scene.tab 5 5


extracting at position range  and azimuth  ...
grid xinc: 8, yinc: 2; average half samp: 2 2 ...
sampling over 2/12/-2147483647/-2147483647 ...
Working on date disp_2018000.grd
grdcut [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file

**Comment by Xiaohua-Eric-Xu** [comment]
If you run a `gmt grdinfo` on your dem.grd，what does it say?

**Comment by Xiaohua-Eric-Xu** [comment]
As the Remark says it is the "DEM error estimated from SBAS(m)", not really the dem.grd in your topo directory.

**Comment by omarwater98** [comment]
> As the Remark says it is the "DEM error estimated from SBAS(m)", not really the dem.grd in your topo directory.

the final result off vel.grd are mm/year?

**Comment by Xiaohua-Eric-Xu** [comment]
> the final result off vel.grd are mm/year?

Yes.

**Comment by omarwater98** [comment]
> Como dice el comentario, es el "error DEM estimado a partir de SBAS (m)", no realmente el dem.grd en su directorio topo.

does it mean that when I do the SBAS all the DEMs are converted to an error?

**Comment by Xiaohua-Eric-Xu** [comment]
Artifact from DEM (the component proportional to perpendicular baseline) are estimated and removed, but I can't guarantee all are "converted to error".

**Comment by Xiaohua-Eric-Xu** [comment]
Make sure that the dates listed in your scene.tab actually exists in your sbas directory. Seems you are running things in your topo directory.

**Comment by Xiaohua-Eric-Xu** [comment]
First determine over how large of an area do you want to average as output (e.g x meters by x meters). Then determine n_rng/n_azi with, e.g., x/rng_pixel_size/rng_dec.

**Comment by kjz1997** [comment]
Can I understand that I want the deformation of a certain latitude and longitude, but this point deformation is calculated based on the deformation of all points within the n_ran and n_azi? Standard deviation is to assess the mass of this point deformation?

发自我的iPhone

**Comment by Xiaohua-Eric-Xu** [comment]
Yup

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu @kjz1997 @misha0402 @omarwater98 @leouieda 
![image](https://github.com/gmtsar/gmtsar/assets/114629377/a45581e9-0bf1-4e8f-9657-fd3286140902)

**Comment by Xiaohua-Eric-Xu** [comment]
@Luvina0503 , you should be using an actual DEM (dem.grd) not the DEM error (dem_err.grd) output from sbas.
