### ISSUE TITLE
[Feature]: GMTSAR on Windows !

### ISSUE THREAD

**Issue by vintingb** [gmtsar/gmtsar#292]
https://github.com/vintingb/gmtsar/tree/debug

I tried to install GMTSAR on windows, and after solving the dependencies of libtiff and lapack, the installation was successful.
I'm happy, but I haven't tested it yet.
1. - [x] build successful
2. - [ ] test
3. - [ ] write cmd or bash (GNU bash) to replace csh

**Comment by Xiaohua-Eric-Xu** [comment]
I actually tried it on the Ubuntu subsystem on Windows 10. It worked fine! And yes, like you said, it does require to locate the tiff-lib and lapack manually. 

The only thing that bugged me was to find where the subsystem is writing stuffs under windows paths so as to view the results.
