### ISSUE TITLE
[Help]: Same dimension, error！

### ISSUE THREAD

**Issue by Gigi-gugu** [gmtsar/gmtsar#293]
Dear Eric, I'm sorry to bother you. Why are my corr.grd and unwrap.grd dimensions the same, still can't run SBAS, or the reported error dimensions don't match.
Thank you in advance.

unbuntu20.04
GMTSAR version:6.0.0

![log](https://user-images.githubusercontent.com/92804122/158003556-29193ff3-a6bf-498a-be01-1ea345122859.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
Well, the dimensions you feed to sbas are different from the actual dimensions of the grids.
