### ISSUE TITLE
[Help]: Range Sampling rate differ issue while ALOS 1.0 processing

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#294]
After prec processing of data, in align_batch.csh command the error show  "Range Sampling rate differ".
The study region has 7 scenes of ALOS in which range sampling rates of files is different which is creating error in align (coregistration) step.
As some ALOS files have (HH + VV) polarisation while others have only HH which has doubled the size of raw file in HH as compared to (HH + VV).
Please suggest a way that can align the range sampling rate of all the files to the same magnitude. 

<img width="878" alt="Screenshot 2022-03-14 172622" src="https://user-images.githubusercontent.com/88940973/158167483-50903259-4be0-4852-a9e2-b77f9f296d13.png">

<img width="697" alt="1" src="https://user-images.githubusercontent.com/88940973/158167621-e69ca0b9-04aa-4e89-8445-c90a9d914eb4.png">
<img width="463" alt="2" src="https://user-images.githubusercontent.com/88940973/158167625-ab9b28b6-91c3-4ec4-ae55-38afe9020cf0.png">

**Comment by Xiaohua-Eric-Xu** [comment]
There's a program called ALOS_fbd2fbs to handle such situation. Also for pre_proc_batch.csh, you need to select a FBS image as master image, so fbd2fbs is performed automatically.

**Comment by shivamthescienceguy** [comment]
Thanks for the reply
after ALOS_fbd2fbs command, it creates two outputs as PRM file and and a raw file but no new file of only 0__A (e.g IMG-HH-ALPSRP076240590-H1.0__A)  format are formed. So will the software take previous 365Mb Dual polarised data files of 0__A format, when will give the input in data.in, intf.in and align,.in files which may create errors.
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/88940973/160078681-2f818691-8f2e-4aad-bb05-49c00c67ef6d.png">

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @shivamthescienceguy, that is supposed to be the case. The program runs on .raw data and produces .raw data. You may have noticed there is a Single.raw file as you put the output name as Single.PRM
I am not sure I understand your second part. If you meant batch processing, the conversion will be done automatically if you select a FBS image as master image (put as first line in your .in file). Details can be found in pre_proc_batch.csh

**Comment by shivamthescienceguy** [comment]
Thanks for your timely reply.

So the automatic conversion is not converting by selecting FBS image as master so I am manually doing it by using the ALOS_fbd2fbs command but that is only creating .raw and .PRM files but in data.in files the input should be in 0__A  format ( e.g. IMG-HH-ALPSRP076240590-H1.0__A) which is not created by ALOS_fbd2fbs so it will take the dual polarised data in the process which will create errors.
So what should be the name of input files in data.in after conversion as I dont have single polarised 0__A file for the input.
Thanks a lot for responding to my queries.

![dd](https://user-images.githubusercontent.com/88940973/160235397-c408bdaf-346f-443b-9a4b-e518f7592ce6.png)

**Comment by Xiaohua-Eric-Xu** [comment]
The data.in should be input for pre_proc_batch.csh. If you take a look into pre_proch_batch.csh, the fbd2fbs was done after pre_procsess-ing the .0__A files. So you are not supposed to re-pre_process them. The original 0__A files shall remain intact.

**Comment by shivamthescienceguy** [comment]
hie @Xiaohua-Eric-Xu , I am able to successfully form deformation map from on FBS datas and FBS datas separately. But when its about combining the two datas  is becoming a problem for me.
So, Selecting FBS image as master in data.in file it is doing the conversion operation but the range sampling rates are not changing so I have manually ran ALOS_fbd2fbs command which created the .raw and .PRM files.
But in the align_batch.csh it is showing range sampling rate differ.

Please guide me what I am doing wrong.
<img width="964" alt="q1" src="https://user-images.githubusercontent.com/88940973/160760791-1fecc008-c871-4869-aa9a-7a201a8af546.png">

<img width="1008" alt="q2" src="https://user-images.githubusercontent.com/88940973/160760807-79eb174c-29ca-4327-a75f-1eeb8eadec73.png">

**Comment by shivamthescienceguy** [comment]
Thanks for you replies,
Now the issue is different. aligning is done properly but the intf of dual polarised with single polarised data formed are blank.
The data taken of ALOS contained 3 scenes, 2 scenes of single polarised and one scene of Dual polarised data which is converted to single polarised with ALOS_fbd2fbs command.

First command ALOS_pre_process (successfully done)
Second pre_process_batch.csh ALOS data.in batch.config
Third ALOS fbd2fbs in the dual POL data folder which produced .raw and .PRM file
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/88940973/161375927-5e11bd87-163e-4998-96fc-466ee0744532.png">

Followed by align_batch.csh ALOS align.in 
Then int batch.csh ALOS intf.in intf.config which produced good intf in in combination of single POL but intf was blank in DUAL and SINGLE Polarisation intf 
<img width="1079" alt="1" src="https://user-images.githubusercontent.com/88940973/161376041-768e5348-75bd-4681-88d4-17fddd66abdd.png">

INTF folder with similar polarisation
<img width="1045" alt="3" src="https://user-images.githubusercontent.com/88940973/161376324-d9e591c8-ecba-4f28-bed8-edc11fcdd24f.png">

INTF folder with combination of different polarisation
<img width="1055" alt="4" src="https://user-images.githubusercontent.com/88940973/161376358-a62b1ce7-7813-4f2c-aa6e-d5d9b9800f93.png">

LOG files of align and intf command
[log.txt](https://github.com/gmtsar/gmtsar/files/8402217/log.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what step is missing here. Theoretically, you don't really need the third step as the fbd2fbs should've been done during the second step. Since there's no log files for them, I could not tell whether they were ran correctly. 
Do you mind sharing this dataset so I can give it a test and get back to you?

**Comment by shivamthescienceguy** [comment]
Sure, Thanks alot, that would be great.
Here is the Python script created from ASF Alaksa site,It contains 7 scenes of my region out of which 4 datas are single polarised and 3 datas are dual polarised.
Thanks for the help again.

[ALOS_7_datas_Punjab.zip](https://github.com/gmtsar/gmtsar/files/8408182/ALOS_7_datas_Punjab.zip)

**Comment by Xiaohua-Eric-Xu** [comment]
I think I found the problem. The baseline you pick to generate interferogram is too large. You should not expect anything to come out of > 1000m baselines.

[log_file_ALOS_fbd2fbs.txt](https://github.com/gmtsar/gmtsar/files/8411632/log_file_ALOS_fbd2fbs.txt)

**Comment by shivamthescienceguy** [comment]
Thanks for the help. 
Could you able to generate intf for other combinations?
Because the thing is I was able to generate the intf from these two combinations (04940 and 05611) having >1000m baseline, intf folder of which is shown in the above comments.
The problem was with the interference of different polarization datasets which was creating blank interferograms.

**Comment by Xiaohua-Eric-Xu** [comment]
> Thanks for the help. Could you able to generate intf for other combinations? Because the thing is I was able to generate the intf from these two combinations (04940 and 05611) having >1000m baseline, intf folder of which is shown in the above comments. The problem was with the interference of different polarization datasets which was creating blank interferograms, like 04940 with 07524).

Also, 04940 and 07620 won't be able to interfere as they have a baseline of ~1800m. 05611 and -4940 may be able to interfere as they are really close in time.

**Comment by shivamthescienceguy** [comment]
Thanks a lot your log file proved to be very helpful.
Now I can process data with different sampling rates.
Thanks again for the help.
