### ISSUE TITLE
[Help]: snaphu don't work in different  */asc/F1/*_*

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#298]
Hi Eric

# I run same process
but _different interest region_ 、 _guess_150_ or _guess_200_ and _0/4000/0/4000_  or _0/3000/0/3000_

# one is this
[jyliu@localhost 2017002_2017026]$ snaphu_interp.csh 0.2 200 0/4000/0/4000
Setting search radius to be 300 ...
Reading in original grid...
Interpolating to nearest neighbour...
Working on line 4000 ...
  1075952 number of searches used ...
WRITING GRID IMAGE: Width x Heihgt = 1000 x 4000...
unwrapping phase with snaphu - higher threshold for faster unwrapping 

snaphu v2.0.1
32 parameters input from file snaphu.conf.brief (297 lines total)
defomax exceeds range of short int for given nshortcycle
xyz2grd: Error for input file: No such file (unwrap.out)
grdmath: Syntax error: tmp.grd is not a number, operator or file name

# other one

[jyliu@localhost 2017139_2017163]$ snaphu_interp.csh 0.2 150 0/3000/0/3000
Setting search radius to be 300 ...
Reading in original grid...
Interpolating to nearest neighbour...
Working on line 3000 ...
  10644451 number of searches used ...
WRITING GRID IMAGE: Width x Heihgt = 750 x 3000...
unwrapping phase with snaphu - higher threshold for faster unwrapping 

snaphu v2.0.1
32 parameters input from file snaphu.conf.brief (297 lines total)
Reading wrapped phase from file phase.in
No weight file specified.  Assuming uniform weights
Reading correlation data from file corr.in
Calculating deformation-mode cost parameters
Building range cost arrays
Building azimuth cost arrays
Initializing flows with MST algorithm
Running approximate minimum spanning tree solver
Running nonlinear network flow optimizer
Maximum flow on network: 2
Number of nodes in network: 2246252
Flow increment: 1  (Total improvements: 0)
Found 1 valid set(s) of connected pixels
Source 0 row, col = -2, -2
Treesize: 2246252    Pivots: 680         Improvements: 17         
Maximum valid flow on network: 2
Flow increment: 2  (Total improvements: 17)
Found 1 valid set(s) of connected pixels
Source 0 row, col = -2, -2
Treesize: 2246252    Pivots: 0           Improvements: 0          
Maximum flow on network: 2
Total solution cost: 1113809
Integrating phase
Writing output to file unwrap.out
Program snaphu done
Elapsed processor time:   0:00:07.57
Elapsed wall clock time:  0:00:08
Unwrapped phase map: unwrap.pdf

# is ram ?  #277  
or other reason? 

Thanks for your reading!!!

**Comment by swjiaotong-jyliu** [comment]
two progress‘ filter_wavelength and region cut are same with snaphu_interp.csh 0.2 filter_wavelength region cut

**Comment by swjiaotong-jyliu** [comment]
I didn’t change parameters in progressing.

**Comment by swjiaotong-jyliu** [comment]
I try to go back to **intf_tops.csh one.in batch_tops.config and set proc_stage = 1** and reset  **filter_wavelength** and **region cut**.I don't know if that's right.

**Comment by swjiaotong-jyliu** [comment]
In addition, **get_baseline_table.csh prmlist S1_20180508_ALL_F1.PRM**
S1_20180508_ALL_F1.PRM is Supermaster.PRM?  I didn't find Supermaster.PRM,only master.PRM。

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @swjiaotong-jyliu, This is the error message:
`defomax exceeds range of short int for given nshortcycle`
You probably need to set a smaller defo_max, e.g. 40. Do you have a specific reason for setting this large number? Usually you want to set it somewhere around the maximum expected discontinuity in your map.

**Comment by swjiaotong-jyliu** [comment]
Thanks.I cheak it and defo_max = 0.
Should I try some number？  40？

**Comment by Xiaohua-Eric-Xu** [comment]
Your previous command was `snaphu_interp.csh 0.2 200 0/4000/0/4000`, where `200` was your defo_max.
Try something like `snaphu_interp.csh 0.2 40 0/4000/0/4000`. If you are aiming a continuous deformation field, use `snaphu_interp.csh 0.2 0 0/4000/0/4000`

**Comment by swjiaotong-jyliu** [comment]
Thanks.I am sorry to think 200 is filter。Thanks for your help。
