### ISSUE TITLE
[Help]: hermite: interpolation not in center interval GMTSAR

### ISSUE THREAD

**Issue by misha0402** [gmtsar/gmtsar#299]
whille using preproc_batch_tops.csh data.in dem.grd 2 command I am getting the above mentioned error. I have taken the entire subswath IW3 for the region. All the orbit files downloaded are covering the area.  It can be seen below from the Data.in filellist.

s1a-iw3-slc-vv-20180414t010108-20180414t010133-021456-024f36-006:S1A_OPER_AUX_POEORB_OPOD_20210307T033757_V20180413T225942_20180415T005942.EOF
s1a-iw3-slc-vv-20161208t010109-20161208t010135-014281-0171be-006:S1A_OPER_AUX_POEORB_OPOD_20210314T232123_V20161207T225943_20161209T005943.EOF
s1a-iw3-slc-vv-20161220t010109-20161220t010134-014456-01773c-006:S1A_OPER_AUX_POEORB_OPOD_20210315T031357_V20161219T225943_20161221T005943.EOF
s1a-iw3-slc-vv-20170125t010107-20170125t010132-014981-018762-006:S1A_OPER_AUX_POEORB_OPOD_20210315T144616_V20170124T225942_20170126T005942.EOF
s1a-iw3-slc-vv-20170206t010106-20170206t010132-015156-018cbf-006:S1A_OPER_AUX_POEORB_OPOD_20210315T183710_V20170205T225942_20170207T005942.EOF
s1a-iw3-slc-vv-20170326t010101-20170326t010126-015856-01a20b-006:S1A_OPER_AUX_POEORB_OPOD_20210302T003244_V20170325T225942_20170327T005942.EOF
s1a-iw3-slc-vv-20170407t010101-20170407t010127-016031-01a740-006:S1A_OPER_AUX_POEORB_OPOD_20210302T042514_V20170406T225942_20170408T005942.EOF
s1a-iw3-slc-vv-20170419t010102-20170419t010127-016206-01aca2-006:S1A_OPER_AUX_POEORB_OPOD_20210302T081723_V20170418T225942_20170420T005942.EOF
s1a-iw3-slc-vv-20170525t010104-20170525t010129-016731-01bc9e-006:S1A_OPER_AUX_POEORB_OPOD_20210302T194651_V20170524T225942_20170526T005942.EOF
s1a-iw3-slc-vv-20171109t010110-20171109t010135-019181-020779-006:S1A_OPER_AUX_POEORB_OPOD_20210305T014237_V20171108T225942_20171110T005942.EOF
s1a-iw3-slc-vv-20171121t010110-20171121t010135-019356-020cfb-006:S1A_OPER_AUX_POEORB_OPOD_20210305T053524_V20171120T225942_20171122T005942.EOF
s1a-iw3-slc-vv-20171203t010110-20171203t010135-019531-021272-006:S1A_OPER_AUX_POEORB_OPOD_20210305T092640_V20171202T225942_20171204T005942.EOF
s1a-iw3-slc-vv-20171215t010109-20171215t010135-019706-0217e9-006:S1A_OPER_AUX_POEORB_OPOD_20210305T131535_V20171214T225942_20171216T005942.EOF
s1a-iw3-slc-vv-20171227t010109-20171227t010134-019881-021d54-006:S1A_OPER_AUX_POEORB_OPOD_20210305T170909_V20171226T225942_20171228T005942.EOF
s1a-iw3-slc-vv-20180108t010108-20180108t010133-020056-0222d5-006:S1A_OPER_AUX_POEORB_OPOD_20210305T210024_V20180107T225942_20180109T005942.EOF
s1a-iw3-slc-vv-20180120t010108-20180120t010133-020231-022861-006:S1A_OPER_AUX_POEORB_OPOD_20210306T004928_V20180119T225942_20180121T005942.EOF
s1a-iw3-slc-vv-20180201t010107-20180201t010133-020406-022df1-006:S1A_OPER_AUX_POEORB_OPOD_20210306T043917_V20180131T225942_20180202T005942.EOF
s1a-iw3-slc-vv-20180213t010107-20180213t010133-020581-023391-006:S1A_OPER_AUX_POEORB_OPOD_20210306T082939_V20180212T225942_20180214T005942.EOF
s1a-iw3-slc-vv-20180225t010107-20180225t010132-020756-023926-006:S1A_OPER_AUX_POEORB_OPOD_20210306T122347_V20180224T225942_20180226T005942.EOF
s1a-iw3-slc-vv-20180309t010107-20180309t010132-020931-023eac-006:S1A_OPER_AUX_POEORB_OPOD_20210306T160740_V20180308T225942_20180310T005942.EOF
s1a-iw3-slc-vv-20180321t010107-20180321t010133-021106-02443a-006:S1A_OPER_AUX_POEORB_OPOD_20210306T195919_V20180320T225942_20180322T005942.EOF
s1a-iw3-slc-vv-20180402t010108-20180402t010133-021281-0249c1-006:S1A_OPER_AUX_POEORB_OPOD_20210306T234227_V20180401T225942_20180403T005942.EOF
s1a-iw3-slc-vv-20180426t010109-20180426t010134-021631-0254a8-006:S1A_OPER_AUX_POEORB_OPOD_20210307T072649_V20180425T225942_20180427T005942.EOF
s1a-iw3-slc-vv-20180508t010109-20180508t010134-021806-025a36-006:S1A_OPER_AUX_POEORB_OPOD_20210307T111715_V20180507T225942_20180509T005942.EOF
s1a-iw3-slc-vv-20180520t010110-20180520t010135-021981-025fc9-006:S1A_OPER_AUX_POEORB_OPOD_20210307T150614_V20180519T225942_20180521T005942.EOF
s1a-iw3-slc-vv-20181128t010116-20181128t010141-024781-02ba40-006:S1A_OPER_AUX_POEORB_OPOD_20210310T043748_V20181127T225942_20181129T005942.EOF
s1a-iw3-slc-vv-20181222t010113-20181222t010138-025131-02c66e-006:S1A_OPER_AUX_POEORB_OPOD_20210310T122455_V20181221T225942_20181223T005942.EOF
s1a-iw3-slc-vv-20190127t010114-20190127t010140-025656-02d975-006:S1A_OPER_AUX_POEORB_OPOD_20210310T235711_V20190126T225942_20190128T005942.EOF
s1a-iw3-slc-vv-20190503t010115-20190503t010140-027056-030c37-006:S1A_OPER_AUX_POEORB_OPOD_20210312T060026_V20190502T225942_20190504T005942.EOF
s1a-iw3-slc-vv-20190515t010116-20190515t010141-027231-0311f7-006:S1A_OPER_AUX_POEORB_OPOD_20210312T094953_V20190514T225942_20190516T005942.EOF
s1a-iw3-slc-vv-20190527t010116-20190527t010142-027406-031769-006:S1A_OPER_AUX_POEORB_OPOD_20210312T141334_V20190526T225942_20190528T005942.EOF
s1a-iw3-slc-vv-20191123t010123-20191123t010148-030031-036dc6-006:S1A_OPER_AUX_POEORB_OPOD_20210315T034504_V20191122T225942_20191124T005942.EOF
s1a-iw3-slc-vv-20191205t010123-20191205t010148-030206-0373d9-006:S1A_OPER_AUX_POEORB_OPOD_20210315T073853_V20191204T225942_20191206T005942.EOF
s1a-iw3-slc-vv-20191229t010122-20191229t010147-030556-037fea-006:S1A_OPER_AUX_POEORB_OPOD_20210315T151358_V20191228T225942_20191230T005942.EOF
s1a-iw3-slc-vv-20200110t010121-20200110t010146-030731-0385f7-006:S1A_OPER_AUX_POEORB_OPOD_20210316T211354_V20200109T225942_20200111T005942.EOF
s1a-iw3-slc-vv-20200122t010121-20200122t010146-030906-038c1f-006:S1A_OPER_AUX_POEORB_OPOD_20210317T010452_V20200121T225942_20200123T005942.EOF
s1a-iw3-slc-vv-20200227t010120-20200227t010145-031431-039e55-006:S1A_OPER_AUX_POEORB_OPOD_20210317T124041_V20200226T225942_20200228T005942.EOF
s1a-iw3-slc-vv-20200310t010120-20200310t010145-031606-03a466-006:S1A_OPER_AUX_POEORB_OPOD_20210317T162432_V20200309T225942_20200311T005942.EOF

**Comment by dsandwell** [comment]
THis error occurs because one of the orbit files does not cover the time interval of the data file.  This could be the time does not overlap or the needed orbit data are for s1b and you have only s1a data.
We need to change the error message to alert the user that the orbit does not overlap te data. 

> On Mar 17, 2022, at 4:10 AM, misha0402 ***@***.***> wrote:
> 
> 
> whille using preproc_batch_tops.csh data.in dem.grd 2 command I am getting the above mentioned error. I have taken the entire subswath IW3 for the region. All the orbit files downloaded are covering the area. It can be seen below from the Data.in filellist.
> 
> s1a-iw3-slc-vv-20180414t010108-20180414t010133-021456-024f36-006:S1A_OPER_AUX_POEORB_OPOD_20210307T033757_V20180413T225942_20180415T005942.EOF
> s1a-iw3-slc-vv-20161208t010109-20161208t010135-014281-0171be-006:S1A_OPER_AUX_POEORB_OPOD_20210314T232123_V20161207T225943_20161209T005943.EOF
> s1a-iw3-slc-vv-20161220t010109-20161220t010134-014456-01773c-006:S1A_OPER_AUX_POEORB_OPOD_20210315T031357_V20161219T225943_20161221T005943.EOF
> s1a-iw3-slc-vv-20170125t010107-20170125t010132-014981-018762-006:S1A_OPER_AUX_POEORB_OPOD_20210315T144616_V20170124T225942_20170126T005942.EOF
> s1a-iw3-slc-vv-20170206t010106-20170206t010132-015156-018cbf-006:S1A_OPER_AUX_POEORB_OPOD_20210315T183710_V20170205T225942_20170207T005942.EOF
> s1a-iw3-slc-vv-20170326t010101-20170326t010126-015856-01a20b-006:S1A_OPER_AUX_POEORB_OPOD_20210302T003244_V20170325T225942_20170327T005942.EOF
> s1a-iw3-slc-vv-20170407t010101-20170407t010127-016031-01a740-006:S1A_OPER_AUX_POEORB_OPOD_20210302T042514_V20170406T225942_20170408T005942.EOF
> s1a-iw3-slc-vv-20170419t010102-20170419t010127-016206-01aca2-006:S1A_OPER_AUX_POEORB_OPOD_20210302T081723_V20170418T225942_20170420T005942.EOF
> s1a-iw3-slc-vv-20170525t010104-20170525t010129-016731-01bc9e-006:S1A_OPER_AUX_POEORB_OPOD_20210302T194651_V20170524T225942_20170526T005942.EOF
> s1a-iw3-slc-vv-20171109t010110-20171109t010135-019181-020779-006:S1A_OPER_AUX_POEORB_OPOD_20210305T014237_V20171108T225942_20171110T005942.EOF
> s1a-iw3-slc-vv-20171121t010110-20171121t010135-019356-020cfb-006:S1A_OPER_AUX_POEORB_OPOD_20210305T053524_V20171120T225942_20171122T005942.EOF
> s1a-iw3-slc-vv-20171203t010110-20171203t010135-019531-021272-006:S1A_OPER_AUX_POEORB_OPOD_20210305T092640_V20171202T225942_20171204T005942.EOF
> s1a-iw3-slc-vv-20171215t010109-20171215t010135-019706-0217e9-006:S1A_OPER_AUX_POEORB_OPOD_20210305T131535_V20171214T225942_20171216T005942.EOF
> s1a-iw3-slc-vv-20171227t010109-20171227t010134-019881-021d54-006:S1A_OPER_AUX_POEORB_OPOD_20210305T170909_V20171226T225942_20171228T005942.EOF
> s1a-iw3-slc-vv-20180108t010108-20180108t010133-020056-0222d5-006:S1A_OPER_AUX_POEORB_OPOD_20210305T210024_V20180107T225942_20180109T005942.EOF
> s1a-iw3-slc-vv-20180120t010108-20180120t010133-020231-022861-006:S1A_OPER_AUX_POEORB_OPOD_20210306T004928_V20180119T225942_20180121T005942.EOF
> s1a-iw3-slc-vv-20180201t010107-20180201t010133-020406-022df1-006:S1A_OPER_AUX_POEORB_OPOD_20210306T043917_V20180131T225942_20180202T005942.EOF
> s1a-iw3-slc-vv-20180213t010107-20180213t010133-020581-023391-006:S1A_OPER_AUX_POEORB_OPOD_20210306T082939_V20180212T225942_20180214T005942.EOF
> s1a-iw3-slc-vv-20180225t010107-20180225t010132-020756-023926-006:S1A_OPER_AUX_POEORB_OPOD_20210306T122347_V20180224T225942_20180226T005942.EOF
> s1a-iw3-slc-vv-20180309t010107-20180309t010132-020931-023eac-006:S1A_OPER_AUX_POEORB_OPOD_20210306T160740_V20180308T225942_20180310T005942.EOF
> s1a-iw3-slc-vv-20180321t010107-20180321t010133-021106-02443a-006:S1A_OPER_AUX_POEORB_OPOD_20210306T195919_V20180320T225942_20180322T005942.EOF
> s1a-iw3-slc-vv-20180402t010108-20180402t010133-021281-0249c1-006:S1A_OPER_AUX_POEORB_OPOD_20210306T234227_V20180401T225942_20180403T005942.EOF
> s1a-iw3-slc-vv-20180426t010109-20180426t010134-021631-0254a8-006:S1A_OPER_AUX_POEORB_OPOD_20210307T072649_V20180425T225942_20180427T005942.EOF
> s1a-iw3-slc-vv-20180508t010109-20180508t010134-021806-025a36-006:S1A_OPER_AUX_POEORB_OPOD_20210307T111715_V20180507T225942_20180509T005942.EOF
> s1a-iw3-slc-vv-20180520t010110-20180520t010135-021981-025fc9-006:S1A_OPER_AUX_POEORB_OPOD_20210307T150614_V20180519T225942_20180521T005942.EOF
> s1a-iw3-slc-vv-20181128t010116-20181128t010141-024781-02ba40-006:S1A_OPER_AUX_POEORB_OPOD_20210310T043748_V20181127T225942_20181129T005942.EOF
> s1a-iw3-slc-vv-20181222t010113-20181222t010138-025131-02c66e-006:S1A_OPER_AUX_POEORB_OPOD_20210310T122455_V20181221T225942_20181223T005942.EOF
> s1a-iw3-slc-vv-20190127t010114-20190127t010140-025656-02d975-006:S1A_OPER_AUX_POEORB_OPOD_20210310T235711_V20190126T225942_20190128T005942.EOF
> s1a-iw3-slc-vv-20190503t010115-20190503t010140-027056-030c37-006:S1A_OPER_AUX_POEORB_OPOD_20210312T060026_V20190502T225942_20190504T005942.EOF
> s1a-iw3-slc-vv-20190515t010116-20190515t010141-027231-0311f7-006:S1A_OPER_AUX_POEORB_OPOD_20210312T094953_V20190514T225942_20190516T005942.EOF
> s1a-iw3-slc-vv-20190527t010116-20190527t010142-027406-031769-006:S1A_OPER_AUX_POEORB_OPOD_20210312T141334_V20190526T225942_20190528T005942.EOF
> s1a-iw3-slc-vv-20191123t010123-20191123t010148-030031-036dc6-006:S1A_OPER_AUX_POEORB_OPOD_20210315T034504_V20191122T225942_20191124T005942.EOF
> s1a-iw3-slc-vv-20191205t010123-20191205t010148-030206-0373d9-006:S1A_OPER_AUX_POEORB_OPOD_20210315T073853_V20191204T225942_20191206T005942.EOF
> s1a-iw3-slc-vv-20191229t010122-20191229t010147-030556-037fea-006:S1A_OPER_AUX_POEORB_OPOD_20210315T151358_V20191228T225942_20191230T005942.EOF
> s1a-iw3-slc-vv-20200110t010121-20200110t010146-030731-0385f7-006:S1A_OPER_AUX_POEORB_OPOD_20210316T211354_V20200109T225942_20200111T005942.EOF
> s1a-iw3-slc-vv-20200122t010121-20200122t010146-030906-038c1f-006:S1A_OPER_AUX_POEORB_OPOD_20210317T010452_V20200121T225942_20200123T005942.EOF
> s1a-iw3-slc-vv-20200227t010120-20200227t010145-031431-039e55-006:S1A_OPER_AUX_POEORB_OPOD_20210317T124041_V20200226T225942_20200228T005942.EOF
> s1a-iw3-slc-vv-20200310t010120-20200310t010145-031606-03a466-006:S1A_OPER_AUX_POEORB_OPOD_20210317T162432_V20200309T225942_20200311T005942.EOF
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you are subscribed to this thread.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by misha0402** [comment]
I have downloaded all the orbits correctly and even for another dataset I am getting the same error

**Comment by misha0402** [comment]
I am doing this  for entire subswath with the correct orbit files

**Comment by Xiaohua-Eric-Xu** [comment]
Could it be your DEM file not covering the data area?

**Comment by misha0402** [comment]
[DEMand SAR Overlay.pdf](https://github.com/gmtsar/gmtsar/files/8321195/DEMand.SAR.Overlay.pd
[data.in.pdf](https://github.com/gmtsar/gmtsar/files/8321205/data.in.pdf)
f)

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure this is the reason. Seems you only want to process a small area. You could 
1) use a larger DEM that covers the whole area, process and then cut. Or
2) reassemble the data using organize_files_tops[_linux].csh or create_frame_tops.csh so the new dataset has one or two bursts in them.

Also if your dem does not cover the data at all, there will be problem. i.e. your dem partially covers iw2 but your former data.in is iw3.

**Comment by misha0402** [comment]
Thanks Sir, The interpolation problem solved but now after running intf_tops.csh one.in batch_tops.config command, the results I got had no interferograms , the filtered phase and correlation images were blank

**Comment by misha0402** [comment]
I tried for a different  region for which earlier I have got the results, but it gave blank files. Below I have attached the PRM file of master image and outputs that I
[baseline_table.dat.txt](https://github.com/gmtsar/gmtsar/files/8340276/baseline_table.dat.txt)
 got.
[S1_20170201_ALL_F2.PRM.txt](https://github.com/gmtsar
[phasefilt_mask.pdf](https://github.com/gmtsar/gmtsar/files/8340
[unwrap.pdf](https://github.com/gmtsar/gmtsar/files/8340284/unwrap.pdf)
283/phasefilt_mask.pdf)
[unwrap_mask.pdf](https://github.com/gmtsar/gmtsar/files/8340285/unwrap_mask.pdf)

/gmtsar/files/8340271/S1_20170201_ALL_F2.PRM.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
The links seems broken somehow. Do you have the "terminal outputs" recorded as a text file? That'll help a lot as usually there should be some error messages there.

**Comment by rofiaini** [comment]
> Thanks Sir, The interpolation problem solved but now after running intf_tops.csh one.in batch_tops.config command, the results I got had no interferograms , the filtered phase and correlation images were blank

Hi, how you solved the problem?
