### ISSUE TITLE
[Help]: problem with merge of Amplitude dispersion index image

### ISSUE THREAD

**Issue by Jacksonqwq** [gmtsar/gmtsar#300]
Dear all
Hi,Eric,i want to merge two scatter_SM.grd of F2 and F3 when i used INSAR_G2S.But the result of merge_swath has obvious problems.

**Screenshot**
F2  scatter_SM.grd
<img width="472" alt="ad_1" src="https://user-images.githubusercontent.com/101538057/159424481-a2d17f4e-f4fd-4b0c-a41a-d71f9d8ab974.png">
F3  scatter_SM.grd
<img width="482" alt="ad_2" src="https://user-images.githubusercontent.com/101538057/159424576-e172142d-b43f-4524-9428-d62a734bf25a.png">
the  result 
<img width="470" alt="ad_3" src="https://user-images.githubusercontent.com/101538057/159424641-206ab080-f350-4e30-bef1-d7bcbdcf60c0.png">
inputfile
<img width="1065" alt="input" src="https://user-images.githubusercontent.com/101538057/159424714-67e42ff4-1d7c-412f-afdd-244dc586cada.png">

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, the merge_swath code are written to merge data in the same coordinates as phasefilt.grd, and well defined with the PRM file. Also there might be a FLIPUD one has to do before merging. If it's OK, you could send me the grids and PRM files and I could give them a try.

**Comment by Jacksonqwq** [comment]
Thanks for your reply and how do i send the data to you?

**Comment by Jacksonqwq** [comment]
> Hi, the merge_swath code are written to merge data in the same coordinates as phasefilt.grd, and well defined with the PRM file. Also there might be a FLIPUD one has to do before merging. If it's OK, you could send me the grids and PRM files and I could give them a try.

Thanks for your reply and how do i send the data to you?

**Comment by Xiaohua-Eric-Xu** [comment]
Maybe put it on a drive and send me a link?

**Comment by Jacksonqwq** [comment]
> Maybe put it on a drive and send me a link?

The grids and PRM files are here,please let me know if other documents are required.
链接：https://pan.baidu.com/s/1i52SAQrCqg1v9Ms-JTy48A?pwd=pjr5 
提取码：pjr5

**Comment by Jacksonqwq** [comment]
> Maybe put it on a drive and send me a link?

The grids and PRM files are here and please let me know if other documents are required.
https://drive.google.com/file/d/1VG5DNav8qj24Mi-UsALrcFoYlmTJlyDR/view?usp=sharing

**Comment by Jacksonqwq** [comment]
> One quick question, the scatter_SM_F2.grd you sent seems to have some problem. ![image](https://user-images.githubusercontent.com/16844111/159978120-cdf0f956-d427-4e79-920b-6241641eae0b.png)

I'm sorry for not checking that file and reposted new files.
https://drive.google.com/file/d/1sKb5t-Tgs-zIZ0uC12ZqSODCRj6z8zb5/view?usp=sharing

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @Jacksonqwq , the prm file you sent does not match your grid file. The PRM seems to be the original PRM from raw folder while the grid was cut to a smaller region. See below your x_min and x_max, y_min and y_max, but in your F2 prm file, the num_rng_bins is 25508 and num_lines is 8164.
```
xiaohua% gmt grdinfo scatter_SM_F2.grd 
scatter_SM_F2.grd: Title: Produced by grdmath
scatter_SM_F2.grd: Command: grdmath scatter_SM_fp.grd FLIPUD = scatter.grd
scatter_SM_F2.grd: Remark: 
scatter_SM_F2.grd: Pixel node registration used [Cartesian grid]
scatter_SM_F2.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
scatter_SM_F2.grd: x_min: 9000 x_max: 25508 x_inc: 1 name: x n_columns: 16508
scatter_SM_F2.grd: y_min: 1000 y_max: 8000 y_inc: 1 name: y n_rows: 7000
scatter_SM_F2.grd: v_min: 0.121096484363 v_max: 10.5830354691 name: z
scatter_SM_F2.grd: scale_factor: 1 add_offset: 0
scatter_SM_F2.grd: format: netCDF-4 chunk_size: 129,130 shuffle: on deflation_level: 3
xiaohua%
```

**Comment by Xiaohua-Eric-Xu** [comment]
Seems OK after I changed the parameters in your F2 PRM file. I changed SC_clock_start clock_start, num_lines, num_rng_bins, etc., according to the grd file you sent. So presumably if you are using the right PRM file, the merging should work OK.
![image](https://user-images.githubusercontent.com/16844111/160041298-24f3ba97-e816-4766-a36b-1d02f6ad6aea.png)

**Comment by Jacksonqwq** [comment]
> Seems OK after I changed the parameters in your F2 PRM file. I changed SC_clock_start clock_start, num_lines, num_rng_bins, etc., according to the grd file you sent. So presumably if you are using the right PRM file, the merging should work OK. ![image](https://user-images.githubusercontent.com/16844111/160041298-24f3ba97-e816-4766-a36b-1d02f6ad6aea.png)

Thank you for your help,I will modify my PRM files.
