### ISSUE TITLE
[Bug]: make_a_offset.csh yields different coverage of results given different parameters

### ISSUE THREAD

**Issue by LiChiehLin** [gmtsar/gmtsar#301]
Hi GMTSAR group,
I'm using make_a_offset.csh to produce azimuth offset from ALOS-2 images for the 2018 Hualien earthquake. 
There are two parameters: 1.nx ny, 2. xsearch search
When I use 2000 4000 32 32 or 2000 4000 64 64, The coverage of the results is fine. However, when I use 4000 8000 64 64, only a small portion was made.
This same error happened with Sentinel-1 images as well for the 2021 Maduo earthquake.
By the way, there were no error messages from both wrong results.

Is there a way to avoid this error? Thank you in advance!

- 2000 4000 32 32
![azioff_ll](https://user-images.githubusercontent.com/86345753/159851572-687803c8-253b-4697-8f50-92f307431f1c.png)

- 2000 4000 64 64
![azioff_ll](https://user-images.githubusercontent.com/86345753/159851383-312c64d5-2579-4bbe-9895-52f996c5fc0e.png)

- 4000 8000 32 32
![azioff_ll](https://user-images.githubusercontent.com/86345753/159851308-26bf6cb3-cbd9-4145-a7a3-382ad6f9e9bf.png)

- 4000 8000 64 64 (buggy)
![azioff_ll](https://user-images.githubusercontent.com/86345753/159851238-679a9e61-ab6f-4567-8278-2490e462fc67.png)

**System and software version:**
- OS: MacOS
- GMTSAR: 6.0

**Comment by Xiaohua-Eric-Xu** [comment]
@dsandwell may have a different answer.

**Comment by LiChiehLin** [comment]
Thank you!
I'll check it up and maybe cut it to a smaller region!

**Comment by LiChiehLin** [comment]
Hi, @Xiaohua-Eric-Xu 
It's been a month and I tried 4000 8000 128 128 to see if this would happen again and it did.
![azioff_ll](https://user-images.githubusercontent.com/86345753/165889813-2534e7c8-d8de-4599-9461-182680c625b1.png)

I checked the PRM and I think both nx+xsearch and ny+ysearch are not larger than the columns and rows. 
Attached is the slave PRM used in make_a_offset.csh
<img width="662" alt="螢幕快照 2022-04-29 下午1 28 42" src="https://user-images.githubusercontent.com/86345753/165889514-96a35d09-b778-42dd-9e69-875f7e3ffa86.png">
If I'm not mistaking things, is num_valid_az the columns (Azimuth/ny) and num_rng_bins the rows (Range/nx)?
Thanks for your help!!

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @LiChiehLin , you are right that the rows are num_lines and columns are num_rng_bins. I checked a bit and xcorr will run starting at window_width to end - window_width. The search will be set within the window so each side actually has a window_width/2 + window_width/2 buffer. Usually when it gets to small numbers, e.g. 1 or 2 increment, things may become sensitive (as you have shown), e.g. if your nx+x_search*2 < num_rng_bins/2, then it'll give an increment of 1 I think. It might be better to test a bit with the input, as xcorr will output the desired increment x_inc and y_inc. You could check on those before it runs forever.

**Comment by LiChiehLin** [comment]
I'm sorry I didn't quite understand the window_width buffer there. So if I want to avoid the above-mentioned bug, the nx+xsearch should be smaller than num_rng_bin/2 and ny+ysearch smaller than num_valid_az/2. Because I think that's probably the reason why this bug ocurred.
And also, how do you cut to a smaller region before processing make_a_offset.csh. I tried `cut_slc` but somehow it did not cut to the region that I wanted.
Thanks!

**Comment by Xiaohua-Eric-Xu** [comment]
`cut_slc` works with co-registered SLC images. So you'll need to run that with the dat in the SLC directory I think. Also, you'll need to cut in radar coordinates (range/azimuth). You can use `slc2amp.csh` to check on the SLC data you produced.

**Comment by LiChiehLin** [comment]
OK, thanks! I'll go try them out.
I'm sorry but what about the bug if I want to avoid it from happening. Is it the nx+nsearch approaching num_rng_bins/2 that induces this error?
Thanks!

**Comment by Xiaohua-Eric-Xu** [comment]
I am not particularly sure. The original xcorr is written to do co-registration estimates I think. It is able to do pixel tracking but one'll have to tune these numbers to let it work properly. Once ran, xcorr will output the increment in x and y, you'll need to check whether that's the output you wanted. Below are two examples. Seems the formula is `nx = nxl * x_inc + 6 * xsearch`.
```
[IG-A49515:geocoded_slc/ENVISAT/SLC] xiaohua% xcorr ASA_IMS_1PNESA20100328_175017_000000182088_00084_42222_0000.PRM ASA_IMS_1PNESA20100502_175015_000000182089_00084_42723_0000.PRM -xsearch 128 -nx 2208
 setting xsearch to 128
 setting nx_corr to 256
 setting nx to 2208
 5191 30316 5191 30316 0 0 0.000000
 locations  n 70656 nx 5191 nyl 32 nxl 2208 **x_inc 2** y_inc 907
[IG-A49515:geocoded_slc/ENVISAT/SLC] xiaohua% xcorr ASA_IMS_1PNESA20100328_175017_000000182088_00084_42222_0000.PRM ASA_IMS_1PNESA20100502_175015_000000182089_00084_42723_0000.PRM -xsearch 128 -nx 2209
 setting xsearch to 128
 setting nx_corr to 256
 setting nx to 2209
 5191 30316 5191 30316 0 0 0.000000
 locations  n 70688 nx 5191 nyl 32 nxl 2209 **x_inc 1** y_inc 907
[IG-A49515:geocoded_slc/ENVISAT/SLC] xiaohua% 
```

**Comment by LiChiehLin** [comment]
Thanks! Really appreciated the examples you did for this! I'll do some try-and-error to figure this out.
I'm just wondering is there a written code that does the pixel tracking in GMTSAR?

**Comment by Xiaohua-Eric-Xu** [comment]
I guess I am a bit confused. What specific code are you looking for?

**Comment by LiChiehLin** [comment]
Oh I'm sorry. I mean other than make_a_offset.csh, is there another written code for pixel tracking?

**Comment by Xiaohua-Eric-Xu** [comment]
Oh, I am afraid there's no other code to do so in GMTSAR for the moment. If you are willing to experiment on that and contribute, we'd be more than happy to put the better version into the distribution.

**Comment by LiChiehLin** [comment]
Got it! Thanks for your encouragement!
