### ISSUE TITLE
[Help]: Is it possible to install into Ubuntu18 system?

### ISSUE THREAD

**Issue by yukun80** [gmtsar/gmtsar#302]
I am using Ubuntu system version 18.0.4, is it possible to install GMTSAR into it? 
I can't find the appropriate installation command on the wiki page. Thanks!

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, I installed it on ubuntu 18.0.4 myself using apt for libs. Try the 20.0 commands. I am not sure GMT will be the newer version there but you could always install GMT from the source.
