### ISSUE TITLE
Problem with dense interferogram fringes from S1-SLC

### ISSUE THREAD

**Issue by dhy158** [gmtsar/gmtsar#303]
Dear, Xiaohua
     I've met some problems recently and i have some questons. The first problem is that many interferograms have very dense interference fringes after generated phasefilt.grd. Blow is  two pics of my all phasefilt.grd, This area is poor coherence, If only because of low coherence, there should be many noise points instead of such dense interference fringes. I have no idea with this problem.Is this a problem of S1-SLC raw data or my processing method?
![2020008_2020032_phasefilt](https://user-images.githubusercontent.com/78248213/160348550-f3e48a13-89c4-4a97-9f09-577749f8cddf.png)
![2020020_2020044_phasefilt](https://user-images.githubusercontent.com/78248213/160348618-1d3a9437-55d2-42fa-81a6-d96d322c58ff.png)
     The second question is the vel.grd calculated by SBAS in another area have large standard deviation(~70), I noticed the standard deviation of previous normal results is relatively small, Is this a bad result?

**Comment by Xiaohua-Eric-Xu** [comment]
Sorry, seems I missed this issue post. I apologize.
Do you have a plot of your dem.grd you used for correcting topographic phase?

**Comment by dhy158** [comment]
Thanks for your reply! This is picture of dem.grd.
![dem](https://user-images.githubusercontent.com/78248213/165884807-1d6e42a1-3711-4484-9dfa-26cd948703ef.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
Looks OK to me. Do you have a log file of the processing you ran? If you used p2p_S1_TOPS_Frame.csh with mode 1 (parallel), then also attach the log file from each subswath.

**Comment by dhy158** [comment]
Thank you again for your timely reply.
It's a pity that I didn't keep the log file, and I deleted the F123 folder to save disk space. I'll process this area again and give you an answer in three days.

**Comment by Xiaohua-Eric-Xu** [comment]
I kind of suspect they are just topographic phase. Will look for your log file :).

**Comment by dhy158** [comment]
Dear Xiaohua,
     I had finished merge and unwrap job, the result is normal so far , and I finded out what the problem is.
     As you think, the problem is the dem file. The dem plot I updated before just downloaded yesterday, not the dem file in my first processing, the bad dem plot is blow.
![微信截图_20220430194048](https://user-images.githubusercontent.com/78248213/166104021-707b7600-a7e4-44f1-88cc-d0c85ba03d34.png)
     Please forgive my carelessness. I didn't even check that the dem file is normal because the file size and elevation range is same in two download. Now it seems that there may be some problem with downloading DEM files on GMTSAR website.

**Comment by dhy158** [comment]
Thank you again for your reply. Your reminder solved my problem.
