### ISSUE TITLE
[Help]: How can i measure the displacement value in specific point?

### ISSUE THREAD

**Issue by ivvnnnn** [gmtsar/gmtsar#305]
**Describe the problem you met**
Hello, everyone! I want to measure a displacement value in a specific point with given coordinates. 
I decided to create a file GNSS.ll  with coordinates in the format:
latitude longitude height
For one point I made a file with a time series (to simulate an GNSS obsrevations) GNSS_vel.enu in the format:

date north_displ east_displ height_displ
date north_displ east_displ height_displ
date north_displ east_displ height_displ
   ....
Further in the instructions it it says that I need a file supermaster.PRM from the interferogram directories. But i can't find it((

At what stage is this file created? Is it possible to create it now, or do i need to do whole cycle again?

Maybe there is a way to measure value in point in some other way?

**OS and software version**
Ubuntu 20.0
OS:
GMTSAR version: 6.1

**Comment by Xiaohua-Eric-Xu** [comment]
You could use the one (master image PRM) you set for alignment. supermaster.PRM is created during merging subswaths from a stack of TOPS data. For other satellites or non-batch mode, use the master image PRM.

**Comment by ivvnnnn** [comment]
@Xiaohua-Eric-Xu Thank you! It work!

**Comment by ivvnnnn** [comment]
Hello, @Xiaohua-Eric-Xu
I tried to measure LOS values at points where is no displacement. However, in the results I get a fairly strange values on the graphs. What could be causing such an behavior? Is it possible at some stage to detect this error and correct it?
Examples of graphs:
![image](https://user-images.githubusercontent.com/99873993/163573850-63fa6bd6-7cde-464f-b5c6-a2893a51e08a.png)
![image](https://user-images.githubusercontent.com/99873993/163573927-e702caab-a808-4f05-bb1d-8e99035cfa5a.png)
![image](https://user-images.githubusercontent.com/99873993/163574403-276a60cb-6ec6-4702-a19d-05ee7ac4c638.png)
![image](https://user-images.githubusercontent.com/99873993/163574462-a42b604c-285f-4514-9a41-753c328f4e39.png)

The first two graphs were obtained from the southwestern part of the observed area, and the third and fourth from the northeastern part

**Comment by Xiaohua-Eric-Xu** [comment]
Atmospheric artifacts? If you AOI is small and localized, try detrending all the unwarp.grd-s before running sbas. You could also use GNSS for correction.

**Comment by ivvnnnn** [comment]
Hello, @Xiaohua-Eric-Xu ! Thanks for the answer! What do you mean by detrending. Is it possible to somehow do this in GMTSAR?

**Comment by Xiaohua-Eric-Xu** [comment]
This could be done with GMT as `gmt grdtrend -N3r unwrap.grd -Dunwrap_dtr.grd`. Here -N3 is a 3 parameter plane, r means a robust fit.

**Comment by ivvnnnn** [comment]
@Xiaohua-Eric-Xu Thank you! I'll try to do it
