### ISSUE TITLE
EAP Correction

### ISSUE THREAD

**Issue by Mpierro14** [gmtsar/gmtsar#306]
Hi Professor,
I apologize in advance for the disturbance, first of all I want to thank you for your availability.
I read on GMTSAR Guide that we need to perform EAP correction for data before March 2015 with IPF version prior to 2.43.
In the Sentinel-1 TOPS Time Series tutorial, EAP correction is performed for all images, with either previous and next IPF version 2.43. Why? 
Thanks again.
Best regards.

**Comment by dsandwell** [comment]
Hi,

This correction is needed for the early versions of the data.  You should ask Xiaohua.  That may be an error in the time series document.

David


> On Apr 8, 2022, at 2:18 AM, Mpierro14 ***@***.***> wrote:
> 
> 
> Hi Professor,
> I apologize in advance for the disturbance, first of all I want to thank you for your availability.
> I read on GMTSAR Guide that we need to perform EAP correction for data before March 2015 with IPF version prior to 2.43.
> In the Sentinel-1 TOPS Time Series tutorial, EAP correction is performed for all images, with either previous and next IPF version 2.43. Why?
> Thanks again.
> Best regards.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by Xiaohua-Eric-Xu** [comment]
Which specific version of the time-series document are you referring to? I don't think we really mentioned that in the newer document. 
Nonetheless, you don't need this correction if the IPF version is later than 2.43. You can find that info in the manifest.safe file in the data. Also, ESA has reprocessed some of the early data and in that case, you don't need this correction either.

**Comment by Mpierro14** [comment]
Hi,
Thank you so much for the reply.
In Sentinel-1 TOPS Time Series I found 'README_prep.txt' where correction is also performed for images 20150403, 20150427, 20150521.
Thank you in advance
Best regards.

**Comment by Xiaohua-Eric-Xu** [comment]
When we prepared those examples, it contains data from former IPF version (early data). So we did the EAP correction in the README_prep.txt file. Check on this later documents if your data are newer. http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_4.pdf

**Comment by Mpierro14** [comment]
Hi,
Thank you for the reply.
Best regards.
