### ISSUE TITLE
[Help]: geocode.csh don`t work after merge、unwrap and grdsample

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#307]
grdmath: Perform reverse Polish notation calculations on grids
grdmath: corr.grd 0.2 GE 0 NAN mask.grd MUL = mask2.grd
grdmath: Syntax error: phase.grd is not a number, operator or file name
grdimage: Error for input file: No such file (phase_mask.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
psscale: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale: Offending option phase_mask.grd
psconvert: Error: The file phase_mask.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
Masked phase map: phase_mask.pdf
Unwrapped masked phase map: unwrap_mask.pdf
grdimage: Error: Cannot open color palette table /opt/GMT-5.3.3/share/cpt/phase.cpt
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
psscale: Error: Cannot open color palette table /opt/GMT-5.3.3/share/cpt/phase.cpt
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
psconvert: phasefilt_mask.ps: GMT PS format detected but file is not finalized. Maybe a -K in excess? phasefilt_mask.pdf could be messed up.
Filtered masked phase map: phasefilt_mask.pdf
Line-of-sight map: los.pdf
geocode.csh
project correlation, phase, unwrapped and amplitude back to lon lat coordinates
remarked is by jyliu on 2022年 04月 10日 星期日 22:08:05 CST with geocode.csh
proj_ra2ll.csh
surface: Error for input file: No such file (trans.dat)
surface: Provides 5, expects 3-column binary data
surface: Error for input file: No such file (trans.dat)
surface: Provides 5, expects 3-column binary data
grdtrack: Error for input file: No such file (raln.grd)
grdtrack: Error for input file: No such file (ralt.grd)
grdtrack: Syntax error: Must specify -G at least once
gmtconvert: Selection led to no output columns.
ls: No match.
Sampling in geocoordinates with deault (60 meter) pixel size ...
gmtinfo: No input data found!
range: Subscript out of range.
gmtmath: Syntax error: Operation "DIV" requires 2 operands
gmtmath: Syntax error: Operation "MUL" requires 2 operands
gmtinfo: No input data found!
blockmedian: Error: Unable to decode  as a floating point number
xyz2grd: Error: Unable to decode  as a floating point number
grdedit: Error for input file: No such file (corr_ll.grd)
proj_ra2ll.csh
surface: Error for input file: No such file (trans.dat)
surface: Provides 5, expects 3-column binary data
surface: Error for input file: No such file (trans.dat)
surface: Provides 5, expects 3-column binary data
grdtrack: Error for input file: No such file (raln.grd)
grdtrack: Error for input file: No such file (ralt.grd)
grdtrack: Syntax error: Must specify -G at least once
gmtconvert: Selection led to no output columns.
ls: No match.
Sampling in geocoordinates with deault (60 meter) pixel size ...
gmtinfo: No input data found!
range: Subscript out of range.
gmtmath: Syntax error: Operation "DIV" requires 2 operands
gmtmath: Syntax error: Operation "MUL" requires 2 operands
gmtinfo: No input data found!
blockmedian: Error: Unable to decode  as a floating point number
xyz2grd: Error: Unable to decode  as a floating point number
grdedit: Error for input file: No such file (phasefilt_ll.grd)
proj_ra2ll.csh
grd2xyz: File phase_mask.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
gmtinfo: No input data found!
surface: Error for input file: No such file (trans.dat)
surface: Syntax error: Must specify -R option
surface: Provides 5, expects 3-column binary data
surface: Error for input file: No such file (trans.dat)
surface: Syntax error: Must specify -R option
surface: Provides 5, expects 3-column binary data
grdtrack: Error for input file: No such file (raln.grd)
grdtrack: Error for input file: No such file (ralt.grd)
grdtrack: Syntax error: Must specify -G at least once
gmtconvert: Selection led to no output columns.
ls: No match.
Sampling in geocoordinates with deault (60 meter) pixel size ...
gmtinfo: No input data found!
range: Subscript out of range.
gmtmath: Syntax error: Operation "DIV" requires 2 operands
gmtmath: Syntax error: Operation "MUL" requires 2 operands
gmtinfo: No input data found!
blockmedian: Error: Unable to decode  as a floating point number
xyz2grd: Error: Unable to decode  as a floating point number
grdedit: Error for input file: No such file (phase_mask_ll.grd)
proj_ra2ll.csh
grd2xyz: File display_amp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
gmtinfo: No input data found!
surface: Error for input file: No such file (trans.dat)
surface: Syntax error: Must specify -R option
surface: Provides 5, expects 3-column binary data
surface: Error for input file: No such file (trans.dat)
surface: Syntax error: Must specify -R option
surface: Provides 5, expects 3-column binary data
grdtrack: Error for input file: No such file (raln.grd)
grdtrack: Error for input file: No such file (ralt.grd)
grdtrack: Syntax error: Must specify -G at least once
gmtconvert: Selection led to no output columns.
ls: No match.
Sampling in geocoordinates with deault (60 meter) pixel size ...
gmtinfo: No input data found!
range: Subscript out of range.
gmtmath: Syntax error: Operation "DIV" requires 2 operands
gmtmath: Syntax error: Operation "MUL" requires 2 operands
gmtinfo: No input data found!
blockmedian: Error: Unable to decode  as a floating point number
xyz2grd: Error: Unable to decode  as a floating point number
grdedit: Error for input file: No such file (display_amp_ll.grd)
proj_ra2ll.csh
surface: Error for input file: No such file (trans.dat)
surface: Provides 5, expects 3-column binary data
surface: Error for input file: No such file (trans.dat)
surface: Provides 5, expects 3-column binary data
grdtrack: Error for input file: No such file (raln.grd)
grdtrack: Error for input file: No such file (ralt.grd)
grdtrack: Syntax error: Must specify -G at least once
gmtconvert: Selection led to no output columns.
ls: No match.
Sampling in geocoordinates with deault (60 meter) pixel size ...
gmtinfo: No input data found!
range: Subscript out of range.
gmtmath: Syntax error: Operation "DIV" requires 2 operands
gmtmath: Syntax error: Operation "MUL" requires 2 operands
gmtinfo: No input data found!
blockmedian: Error: Unable to decode  as a floating point number
xyz2grd: Error: Unable to decode  as a floating point number
grdedit: Error for input file: No such file (unwrap_mask_ll.grd)
proj_ra2ll.csh
surface: Error for input file: No such file (trans.dat)
surface: Provides 5, expects 3-column binary data
surface: Error for input file: No such file (trans.dat)
surface: Provides 5, expects 3-column binary data
grdtrack: Error for input file: No such file (raln.grd)
grdtrack: Error for input file: No such file (ralt.grd)
grdtrack: Syntax error: Must specify -G at least once
gmtconvert: Selection led to no output columns.
ls: No match.
Sampling in geocoordinates with deault (60 meter) pixel size ...
gmtinfo: No input data found!
range: Subscript out of range.
gmtmath: Syntax error: Operation "DIV" requires 2 operands
gmtmath: Syntax error: Operation "MUL" requires 2 operands
gmtinfo: No input data found!
blockmedian: Error: Unable to decode  as a floating point number
xyz2grd: Error: Unable to decode  as a floating point number
grdedit: Error for input file: No such file (unwrap_ll.grd)
proj_ra2ll.csh
surface: Error for input file: No such file (trans.dat)
surface: Provides 5, expects 3-column binary data
surface: Error for input file: No such file (trans.dat)
surface: Provides 5, expects 3-column binary data
grdtrack: Error for input file: No such file (raln.grd)
grdtrack: Error for input file: No such file (ralt.grd)
grdtrack: Syntax error: Must specify -G at least once
gmtconvert: Selection led to no output columns.
ls: No match.
Sampling in geocoordinates with deault (60 meter) pixel size ...
gmtinfo: No input data found!
range: Subscript out of range.
gmtmath: Syntax error: Operation "DIV" requires 2 operands
gmtmath: Syntax error: Operation "MUL" requires 2 operands
gmtinfo: No input data found!
blockmedian: Error: Unable to decode  as a floating point number
xyz2grd: Error: Unable to decode  as a floating point number
grdedit: Error for input file: No such file (phasefilt_mask_ll.grd)
geocode.csh
make the KML files for Google Earth
grdinfo: Error for input file: No such file (display_amp_ll.grd)
grdinfo: Syntax error: Must specify one or more input files
gmtmath: Syntax error: Operation "INV" requires 1 operands
grdimage: Error for input file: No such file (display_amp_ll.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
Make display_amp_ll.kml and display_amp_ll.png
psconvert: Processing display_amp_ll.ps...
psconvert: Error: The file display_amp_ll.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
grdinfo: Error for input file: No such file (corr_ll.grd)
grdinfo: Syntax error: Must specify one or more input files
gmtmath: Syntax error: Operation "INV" requires 1 operands
grdimage: Error for input file: No such file (corr_ll.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
Make corr_ll.kml and corr_ll.png
psconvert: Processing corr_ll.ps...
psconvert: Error: The file corr_ll.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
grdinfo: Error for input file: No such file (phase_mask_ll.grd)
grdinfo: Syntax error: Must specify one or more input files
gmtmath: Syntax error: Operation "INV" requires 1 operands
grdimage: Error for input file: No such file (phase_mask_ll.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
Make phase_mask_ll.kml and phase_mask_ll.png
psconvert: Processing phase_mask_ll.ps...
psconvert: Error: The file phase_mask_ll.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
grdinfo: Error for input file: No such file (phasefilt_mask_ll.grd)
grdinfo: Syntax error: Must specify one or more input files
gmtmath: Syntax error: Operation "INV" requires 1 operands
grdimage: Error for input file: No such file (phasefilt_mask_ll.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
Make phasefilt_mask_ll.kml and phasefilt_mask_ll.png
psconvert: Processing phasefilt_mask_ll.ps...
psconvert: Error: The file phasefilt_mask_ll.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.

**Comment by swjiaotong-jyliu** [comment]
trans.dat error

**Comment by Xiaohua-Eric-Xu** [comment]
This is the key I think `grdmath: Syntax error: phase.grd is not a number, operator or file name`, which indicate phase.grd was not generated.

**Comment by swjiaotong-jyliu** [comment]
YES
phase.grd was not generated.
I will try gmt grdpaste to create a phase.grd incloud F1 F2 and F3.

Before
My solution was 
cp ../F1/topo/trans.date in merge/20*_20* directory
It works.

**Comment by KIKINEO** [comment]
@Xiaohua-Eric-Xu Hello, Professor Xu, I also had the same error when I used geocode.csh to encode the result. The following is the specific situation I used:
GMTSAR version: 6.2
GMT version: 6.4
Ubuntu version: 20.04
the steps i use
First use p2p_S1_TOPS_Frame.csh to do interference processing on the image, and choose to skip unwrapping and encoding in config
Then use snaphu.csh for unwrapping. The correlation threshold is set to 0.12 and the maximum discontinuity is set to 20.
Finally geocode with geocode.csh
In the above process, only errors occurred during the geocoding process. The initial error was also an error message like ‘grdmath: phase.grd is not a number, operator or file name’.
Attached is the log file I uploaded (log123 is the log file under the F123 folder, terminal1 is the terminal display when encoding is executed), can you help me point out the problem, this problem has troubled me for a long time, I look forward to your feedback reply，thank you very much~
[https://github.com/KIKINEO/log/blob/main/log1](url)
[https://github.com/KIKINEO/log/blob/main/log2](url)
[https://github.com/KIKINEO/log/blob/main/log3](url)
[https://github.com/KIKINEO/log/blob/main/terminal1](url)

**Comment by Xiaohua-Eric-Xu** [comment]
You probably want to use proj_ra2ll.csh for geocoding as geocode.csh is written for p2p_processing.csh. The files may not be exactly the same in the merge directory.

**Comment by KIKINEO** [comment]
> You probably want to use proj_ra2ll.csh for geocoding as geocode.csh is written for p2p_processing.csh. The files may not be exactly the same in the merge directory.

I will go back and continue to try，thanks a lot ~
