### ISSUE TITLE
error installing GMTSAR: no file tiffio.h

### ISSUE THREAD

**Issue by mshastings18** [gmtsar/gmtsar#31]
I am trying to install GMTSAR but I am running into a problem at the "make" step. It seems that there is no file or directory "tiffio.h". 

I tried to use apt to install libtiff and it says that it cannot be found. I have version 5.4.3 of gmt installed with apt, and I am on Ubuntu 18.04. 

Any help is appreciated!

Cheers,

Mitch

![tiffio_error](https://user-images.githubusercontent.com/31482314/87882703-fee42800-c9cf-11ea-87d5-f214c42b4c10.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Mitch,
Seems your tiff libs were not found. Could you check GMTSAR/config.mk to see whether the configuration found the library?
Xiaohua(Eric)

**Comment by mshastings18** [comment]
Oh my gosh I am so sorry, I missed the libtiff5-dev library from the wiki. I installed that and it all installed fine. I apologize!

Mitch

**Comment by Xiaohua-Eric-Xu** [comment]
No problem. This happens!
