### ISSUE TITLE
[Help]: ALOS_pre_process_SLC can not produce a right PRM file

### ISSUE THREAD

**Issue by JianBo17** [gmtsar/gmtsar#310]
When I use the p2p_ALOS2_SCAN_SLC.csh to process the ALOS2 data, a problem occurred. The ALOS_pre_process_SLC can't produce a right PRM file. The image contains 5 parts(F1-F5),the F1 and F2 could produce the right PRM file. But some error occurred when I produce the other image. The F3 warning me that the record_length is too large and notice me to use the -swap option. But the -swap option couldn't help. The F4 and F5 warning me that `***** warning sdr.record_length error -991297792 
 missing line: n, seq# 114358 -1003029236`. And the PRM of F4 is empty or just have four lines of parameters( and it is wrong).

**OS and software version**
If applicable, what operating system and software version you are using?
OS: Ubuntu
GMTSAR version: 6.3

[IMG-HH-ALOS2116444100-160719-WBDR1.1__D-F4.PRM.txt](https://github.com/gmtsar/gmtsar/files/8479509/IMG-HH-ALOS2116444100-160719-WBDR1.1__D-F4.PRM.txt)
[IMG-HH-ALOS2116444100-160719-WBDR1.1__D-F1.PRM.txt](https://github.com/gmtsar/gmtsar/files/8479514/IMG-HH-ALOS2116444100-160719-WBDR1.1__D-F1.PRM.txt)

**Comment by JianBo17** [comment]
And the example of p2p_ALOS2_SCAN_Frame.csh provided by [gmt5sar](https://topex.ucsd.edu/gmtsar/downloads/) couldn't work too. The problem is same as my own data. And the PRM file of master image is right, but the PRM file of slave image is wrong.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi I think we only have released 6.1. Are you using the master branch? 
The only apparent error I can see is the SLC_scale being set to 80000. And would be great if you could attach a log file on what you did and the output from terminal.

**Comment by JianBo17** [comment]
Thanks for replying,
I am using the master branch.
Where can I reset the SLC_scale? The SLC_factor of the config file is set to 4.0.I am sorry that I just start to use the gmtsar and I am not familiar with it.
Thank you.

---Original---
From: "Xiaohua(Eric) ***@***.***&gt;
Date: Wed, Apr 13, 2022 23:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gmtsar/gmtsar] [Help]: ALOS_pre_process_SLC can not produce aright PRM file (Issue #310)




 
Hi I think we only have released 6.1. Are you using the master branch?
 The only apparent error I can see is the SLC_scale being set to 80000. And would be great if you could attach a log file on what you did and the output from terminal.

**Comment by Xiaohua-Eric-Xu** [comment]
It is in the config file called SLC_factor? Also the master branch is the branch under development and is not well tested, though it may have more new features. Attaching a log would help a lot.

**Comment by JianBo17** [comment]
It is a parameter called SLC_factor in the config file called 'config.alos2.scan'. My laptop has run out of battery，so I can't provide a log. And I'm a student living in China, so I can't provide it for&nbsp; about 8 hours. I'm sorry about that. I will provide it when I can use my computer again.
&nbsp;

---Original---
From: "Xiaohua(Eric) ***@***.***&gt;
Date: Thu, Apr 14, 2022 00:16 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gmtsar/gmtsar] [Help]: ALOS_pre_process_SLC can not produce aright PRM file (Issue #310)




 
It is in the config file called SLC_factor? Also the master branch is the branch under development and is not well tested, though it may have more new features. Attaching a log would help a lot.

**Comment by JianBo17** [comment]
I restall the gmtsar with version 6.0. But it not work.I attach the logfile in my email.



---Original---
From: "Xiaohua(Eric) ***@***.***&gt;
Date: Thu, Apr 14, 2022 00:16 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gmtsar/gmtsar] [Help]: ALOS_pre_process_SLC can not produce aright PRM file (Issue #310)




 
It is in the config file called SLC_factor? Also the master branch is the branch under development and is not well tested, though it may have more new features. Attaching a log would help a lot.

**Comment by JianBo17** [comment]
[LED.log](https://github.com/gmtsar/gmtsar/files/8490555/LED.log)
The part of error code is 
`.... reading sarleader 28
Warning: number of attitude points 62 != 22
`
` ***** warning sdr.record_length error 1116972775 
 missing line: n, seq# 101174 -1012318786 
 ***** warning sdr.record_length error 1132163451 
 missing line: n, seq# 101175 1102035559 
 ***** warning sdr.record_length error -1025453111 
 missing line: n, seq# 101176 1114177898 
 end: shift exceeds data window 262238920 
 exitting `

When I use the ALOS_pre_process_SLC, it warning that I should set the SLC_factor closer to 0.000. But even I set the SLC_factor as 0.0001, it still not work and warning me to reset the SLC_factor closer to 0.000.

**Comment by Xiaohua-Eric-Xu** [comment]
I am not particularly sure. Is there a way that you could share your F4 data? I'll probably have to re-produce the error in order to know what really happened. Or you could provide the full terminal output after you ran p2p_processing.csh over F4. I suspect there might be an error occurred even before this. Also it would be great if you can compress `IMG-HH-ALOS2116444100-160719-WBDR1.1__D-F1, IMG-HH-ALOS2116444100-160719-WBDR1.1__D-F4, and LED-ALOS2116444100-160719-WBDR1.1__D` into a tarball, and make it available through a net disk (e.g. dropbox)?

**Comment by JianBo17** [comment]
I'm sorry that I can't provide the raw data.It belongs to my tutor, I can only use it. 
It occurred when I try to use the p2p_ALOS2_SCAN_SLC.csh to process the data. The error code is 
`ALIGN.CSH - STARTWARNING:Range_sampling_rate is not consistant.You need to do FBD/FBS conversion. Can't open ldrfile'

The Range_sampling_rate is the quotient of rng_samp_rate of two PRM file. But one of the PRM file is empty. So I guss some error happened while the ALOS_pre_process_SLC running.

**Comment by JianBo17** [comment]
[log.txt](https://github.com/gmtsar/gmtsar/files/8490936/log.txt)

**Comment by JianBo17** [comment]
I could run the ALOS_pre_peocess.csh with all 5 sub image of another ALOS2 ScanSAR image. So it seems that there are some errors in the raw date. But my tutor could process the date about 5years ago. He used the p2p_ALOS_SCAN_SLC.csh too. So it seems that there is no problem about the data. So I really don’t know why the problem occurred and how to solve it.
Thanks for your patient answer.

**Comment by Xiaohua-Eric-Xu** [comment]
The log you sent says `skipping stage 1`. Then it says `Range_sampling_rate is not consistant.` Could you run it from the beginning?

**Comment by JianBo17** [comment]
[p2p.log](https://github.com/gmtsar/gmtsar/files/8493929/p2p.log)

**Comment by JianBo17** [comment]
Today I use another ALOS2 ScanSAR data to run the p2p_ALOS2_SCAN_Frame. The same problem occurs.F1 and F2 could produce the phase.pdf, but couldn't geocode. The phase image of F3 only have part of phase(~5%). And F4 and F5 couldn't produce phase image files. Does the program have any hardware requirements?

**Comment by dsandwell** [comment]
Please test you code with the example you can download.  If that does not work then there is an install problem.  Note these ALOS2 scansar data require a large computer and lots of processing time and disk space.  You may be running out of disk space.

> On Apr 15, 2022, at 12:03 AM, JianBo17 ***@***.***> wrote:
> 
> 
> Today I use another ALOS2 ScanSAR data to run the p2p_ALOS2_SCAN_Frame. The same problem occurs.F1 and F2 could produce the phase.pdf, but couldn't geocode. The phase image of F3 only have part of phase(~5%). And F4 and F5 couldn't produce phase image files. Does the program have any hardware requirements?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by JianBo17** [comment]
Thanks for your advice. I will try it.

**Comment by JianBo17** [comment]
I use a large computer to test the code with the example download from the gmt5sar today. But it can't run correctly too.

**Comment by JianBo17** [comment]
[ALOS2_SCAN_log(1).txt](https://github.com/gmtsar/gmtsar/files/8500188/ALOS2_SCAN_log.1.txt)

**Comment by JianBo17** [comment]
It seems that some part of the p2p_ALOS2_SCAN_Fram.csh code is not run correctly. The log files of F1/F2/F3/F4/F5 show that the process can't find the freq_xcorr.dat、tmp.dat、freq_alos2.dat files. It seems that some error occurred in the 462 lines to 480 lines of the p2p_processing.csh. It can't produce the files correctly.

**Comment by JianBo17** [comment]
I can use the p2p_processing.csh to process the ALOS1 image. But there are some errors when I use it to process the ALOS2_ScanSAR data. I reinstall the GMTSAR with 6.0 branch. But it has no effect.

**Comment by Xiaohua-Eric-Xu** [comment]
Could you attach the log files from the subswaths?

**Comment by JianBo17** [comment]
The 'log.txt' file I attached 2 days ago.

**Comment by Xiaohua-Eric-Xu** [comment]
> 

The log you attached has step one skipped. Plus the second log you attached was empty.

**Comment by Xiaohua-Eric-Xu** [comment]
Never mind I couldn't open the log but now I can. It's these errors.
```
missing line: n, seq# 114099 -987823549 
 ***** warning sdr.record_length error -1013811923 
```

**Comment by Xiaohua-Eric-Xu** [comment]
Are you able to share part of the dataset with us so we could test it on our end?

**Comment by JianBo17** [comment]
`# process data
#   
  if ($seq == 0) then
    foreach swath (1 2 3 4 5)
      cd F$swath
      sed "s/.*skip_stage.*/skip_stage = 2,3,4,5,6/g" $3 > tmp_config
      p2p_processing.csh ALOS2_SCAN $1"-F"$swath $2"-F"$swath tmp_config
      cd raw 
      samp_slc.csh $1"-F"$swath 3350 0
      samp_slc.csh $2"-F"$swath 3350 0
      cd ..
      sed "s/.*skip_stage.*/skip_stage = 1/g" $3 > tmp_config
      p2p_processing.csh ALOS2_SCAN $1"-F"$swath $2"-F"$swath tmp_config
      rm tmp_config
      cd ..
    end
  else if ($seq == 1) then
    foreach swath (1 2 3 4 5)
      cd F$swath
      sed "s/.*skip_stage.*/skip_stage = 2,3,4,5,6/g" $3 > tmp_config
      p2p_processing.csh ALOS2_SCAN $1"-F"$swath $2"-F"$swath tmp_config >&log&
      cd ..
    end
    wait 

    foreach swath (1 2 3 4 5)
      cd F$swath/raw
      samp_slc.csh $1"-F"$swath 3350 0 
      samp_slc.csh $2"-F"$swath 3350 0
      cd ../..
    end 
    wait 

    foreach swath (1 2 3 4 5)
      cd F$swath
      sed "s/.*skip_stage.*/skip_stage = 1/g" $3 > tmp_config
      p2p_processing.csh ALOS2_SCAN $1"-F"$swath $2"-F"$swath tmp_config >&log&
      cd ..
    end 
    wait 

  else
    echo "Invalid parallel mode"
    exit 1
  endif`

**Comment by JianBo17** [comment]
That is code of the csh. It process the step_1 for 5 subswath. Then it process the rest of step and it will skip the step_1.

**Comment by JianBo17** [comment]
The log file has been rewrote when it process step_2 and the rest of step. When it process the step_1 , I check the log file, there is no error.Do you mean the config file?

**Comment by Xiaohua-Eric-Xu** [comment]
I got the log file from two days ago. Two questions here:
1) Are you able to share part of the dataset with us so we could test it on our end?
2) Did you download burst-by-burst data or frame wise data? The former format is not supported by GMTSAR at the moment.

**Comment by JianBo17** [comment]
I use the config file from the example download from gmt5sar

**Comment by JianBo17** [comment]
I am sorry that I don't know which date format it is. I will reply you later after I ask my tutor.

**Comment by JianBo17** [comment]
Hi
I run the process `p2p_ALOS2_SCAN_Frame.csh` with the example data download from the GMTSAR. But it can't process correctly too. The log file is attached. I think there are some errors in line 45 to line 55. The process `xcorr` can't run. 
Please look the 'log_bin' file as attached. I reinstall the GMT and GMTSAR again today. I can use the other functions as `update_PRM`. But I can't use the `xcorr` function, it even does not send me the usage. I don't know why. Are there some errors in the `xcorr` function or it is a install problem. 

[log_bin.txt](https://github.com/gmtsar/gmtsar/files/8504374/log_bin.txt)
[log_p2p_ALOS2_Frame_example.txt](https://github.com/gmtsar/gmtsar/files/8504355/log_p2p_ALOS2_Frame_example.txt)

**Comment by JianBo17** [comment]
I add a line of code to `xcorr.c` that `The program is OK` and the make install again. 
`int main(int argc, char **argv) {
	printf("The program is OK\n");
	int input_flag, nfiles;
	struct xcorr *xc;
	clock_t start, end;
	double cpu_time;
	void *API = NULL; /* GMT API control structure */
`
It could be print. 
So I think it is not a install problem. It probably is the problem with the raw code.It can't produce the freq_xcorr.dat file and it even can't send the USAGE information.
![Screenshot from 2022-04-18 18-25-16](https://user-images.githubusercontent.com/49815131/163795548-8aae99ce-c441-4e8b-8e19-23175c68f980.png)
![Screenshot from 2022-04-18 18-26-45](https://user-images.githubusercontent.com/49815131/163795705-a8b3b90e-0210-430c-92d6-33fb7852b8b0.png)

**Comment by JianBo17** [comment]
I add a line of code to `xcorr.c` that `The program is OK` and the make install again.
`int main(int argc, char **argv)
 { printf("The program is OK\n"); 
int input_flag, nfiles;
 struct xcorr *xc; clock_t start, end; 
double cpu_time; 
void *API = NULL; /* GMT API control structure */`
It could be print.
So I think it is not a install problem. It probably is the problem with the raw code.It can't produce the `freq_xcorr.dat` file and it even can't send the USAGE information.
![QQ图片20220418192603](https://user-images.githubusercontent.com/49815131/163801724-2e915d15-a7c5-4e4e-893e-1d1efd2807b6.jpg)
![QQ图片20220418192608](https://user-images.githubusercontent.com/49815131/163801730-498bfd4d-ba25-4663-92bf-b304e63b2426.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
Did the former problem gets solved? 
```
missing line: n, seq# 114099 -987823549 
 ***** warning sdr.record_length error -1013811923 
```
I am not sure why it could not run. The only command before outputing usage is creating a GMT session. Was your GMT install successful? Some package managers require libgmt-dev.

**Comment by JianBo17** [comment]
The problem of PRM files is solved. I change a computer to process it.But the new computer can't run the xcorr.c function. More confused is that my old computer can sucessfully run the xcorr.c function, but can't run the ALOS_pre_procrss.csh and geocode.csh.
I use the same way to install the GMTSAR in both two computer. And I use the same date(SAFF example) and same process(p2p_ALOS2_SCAN_Frame.csh). But the problem is different. That is so strange.
I will check the installation step later.
Thanks for your reply.



---Original---
From: "Xiaohua(Eric) ***@***.***&gt;
Date: Tue, Apr 19, 2022 00:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gmtsar/gmtsar] [Help]: ALOS_pre_process_SLC can not produce aright PRM file (Issue #310)




 
Did the former problem gets solved?
 missing line: n, seq# 114099 -987823549   ***** warning sdr.record_length error -1013811923   
I am not sure why it could not run. The only command before outputing usage is creating a GMT session. Was your GMT install successful? Some package managers require libgmt-dev.

**Comment by Xiaohua-Eric-Xu** [comment]
You could reproduce the scenario by experimenting with that "GMT session create" line. Just want to make sure that's the cause, and if so, we could ask the GMT gurus for help.

**Comment by JianBo17** [comment]
`make[1]: 进入目录“/usr/local/GMTSAR/gmtsar”
gcc -O2 -Wall  -fPIC -fno-strict-aliasing -std=c99  -I./ -I/usr/local/include    -c -o xcorr.o xcorr.c
xcorr.c: In function ‘main’:
xcorr.c:272:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  272 |  if ((API = GMT_Create_Session(argv[0], 0U, 0U, NULL)) == NULL)
      |  ^~
xcorr.c:274:3: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  274 |   return EXIT_FAILURE;
      |   ^~~~~~
`

**Comment by JianBo17** [comment]
Hi, I can run the process correctly.
But I think the result is not correct.
![phasefilt_ll](https://user-images.githubusercontent.com/49815131/164463380-b8ebe67a-4bca-40e8-90e4-d6bee11fe5d1.jpg)
[config.alos2.txt](https://github.com/gmtsar/gmtsar/files/8531175/config.alos2.txt)
I think some parameters  are not set right, especially F3 and F5.

**Comment by JianBo17** [comment]
[phasefilt.pdf](https://github.com/gmtsar/gmtsar/files/8531240/phasefilt.pdf)
![Screenshot from 2022-04-21 21-12-34](https://user-images.githubusercontent.com/49815131/164465626-2c5a334a-733e-43f3-9a95-7d837b1622ba.png)

**Comment by Xiaohua-Eric-Xu** [comment]
What if you turn off the ionospheric correction? It is not automatic for ALOS2 momentarily. One has to tune the parameters and correct for different range starting time in order to let it work.

**Comment by Xiaohua-Eric-Xu** [comment]
There is a recent paper that used GMTSAR to correct ionosphere for ALOS-2 data. https://www.essoar.org/doi/abs/10.1002/essoar.10508106.1 (Figure S4)

**Comment by Xiaohua-Eric-Xu** [comment]
If you checkout the current master branch, the ionospheric correction for a pair of ALOS-2 interferogram is implemented. The filtering parameter needs to be tuned though, e.g. 4 for azimuth and 8 for range.

**Comment by JianBo17** [comment]
Hey, Xiaohua
I install the GMT-6.3.0 and GMTSAR-master in a new computer. The same error ` ***** warning sdr.record_length error -1003471810 
 missing line: n, seq# 85672 -1006539634 ` was occurred again when I use the `ALOS_pre_process_SLC.csh` to preprocess the ALOS2_SCANSAR data. I am not sure what I did exactly to solve the problem last time, but I probably is a install problem. Are there some special requirements when installing GMT or GMTSAR ?
By the way, I can use the `ALOS_pre_process_SLC.csh` to produce another raw data. Only a few data can't be processed correctly.

**Comment by Xiaohua-Eric-Xu** [comment]
I don't think there is any special requirement to install GMT and GMTSAR. Make sure you downloaded full-aperture data, not burst-by-burst data. @dsandwell, is there any thing that you can recall in `ALOS_pre_process_SLC`, which may cause this error below inconsistently for ScanSAR data? 
```
***** warning sdr.record_length error -1003471810 
 missing line: n, seq# 85672 -1006539634
```

**Comment by JianBo17** [comment]
I am sure that it is the full-aperture data, cause I can process the data in another computer.



---Original---
From: "Xiaohua(Eric) ***@***.***&gt;
Date: Tue, May 24, 2022 10:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gmtsar/gmtsar] [Help]: ALOS_pre_process_SLC can not produce aright PRM file (Issue #310)




 
I don't think there is any special requirement to install GMT and GMTSAR. Make sure you downloaded full-aperture data, not burst-by-burst data. @dsandwell, is there any thing that you can recall in ALOS_pre_process_SLC, which may cause this error below inconsistently for ScanSAR data?
 ***** warning sdr.record_length error -1003471810   missing line: n, seq# 85672 -1006539634

**Comment by JianBo17** [comment]
I reinstall the Ubuntu and GMTSAR and copy the raw data from old computer. The problem is solved.

**Comment by JianBo17** [comment]
It is same as the subwaths log file I have attached before.



---Original---
From: "Xiaohua(Eric) ***@***.***&gt;
Date: Sun, Apr 17, 2022 00:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gmtsar/gmtsar] [Help]: ALOS_pre_process_SLC can not produce aright PRM file (Issue #310)




 
Could you attach the log files from the subswaths?
