### ISSUE TITLE
[Help]: View .grd files in Matlab or Python

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#314]
Hie,
Could you please tell me how to view the outputs of disp.grd and vel.grd in Matlab or Python as my system cant recognize the format of these files when sent to windows?
And is there any way I can convert the displacement values in grd files into a excel sheet for better visualisation.
Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
For matlab, use `ncread` to read in the data. I am sure similar things exist in Python. The netcdf format should be the same across platforms. I think there is a script called `extract_one_time_series.csh` that could product a point time-series.

**Comment by shivamthescienceguy** [comment]
Thanks Eric, 
Also is there a option to make Legend for velocity and frame of Lat Long around our deformation map in GMTSAR or we have to do it using another software?

**Comment by Xiaohua-Eric-Xu** [comment]
Sorry for the late response. You'll need to customize the plotting with GMT.

**Comment by chintals** [comment]
If visualization is the key, then you can use python, but depending on the grd file size, it can be memory intensive process. See below for sample python code.  
You could also install QGIS (https://qgis.org/en/site/) and read in as raster files. Raster manipulation (for qualitative purposes) is also easy on QGIS. 

`import netCDF4 as nc, numpy as np, pandas as pd, matplotlib.pyplot as plt
from matplotlib import cm

grd_file = "filepath to the grdfile"
grd = nc.Dataset(grd_file)
key_list = list(grd.variables.keys())

# assign data as numpy arrays - assuming grd file is either lon/lat or radar coords
x = np.array(grd.variables[key_list[0]][:]) # lon or x
y = np.array(grd.variables[key_list[1]][:]) # lat or y
xx, yy = np.meshgrid(x,y)

zz = np.array(grd.variables[key_list[2]][:]) # phase

# plotting
fig, ax = plt.subplots()
# set up contour levels min, max, contour_levels
levels = np.linspace(np.nanmin(zz), np.nanmax(zz), 100)
CS = ax.contour(xx, yy, zz, cmap=cm.coolwarm, levels=levels)
CB = fig.colorbar(CS, shrink=0.8)
ax.clabel(CS, inline=True, fontsize=10)
plt.show()
# plt.savefig('filepath for png', dpi = 'figure')`

**Comment by mobigroup** [comment]
Python xarray+dask libraries allow to easy process huge NetCDF files (.grd) locally and on even distributed clusters. See live examples: https://github.com/mobigroup/gmtsar
