### ISSUE TITLE
[Help]: A question about the LOS displacement processed by GMTSAR

### ISSUE THREAD

**Issue by Uncleyyyyy** [gmtsar/gmtsar#315]
Currently I'm processing the data from an earthquake occured at Menyuan on Jan.8, and the outcome is as below
![los_out](https://user-images.githubusercontent.com/46470946/163821850-3daeb7d3-5b20-437f-a739-4162d6d72fb9.png)
It seems ok, and the LOS displacement of ascending and descending orbits is relatively consistent. However, after I read some articles about this earthquake, I find out that the LOS displacement the other researchers have worked out is about 56cm in south and 62cm in north. I wonder why this difference would take place. By the way, the researchers get the LOS displacement by GAMMA in the articles I read.
And also, the LOS displacement of descending orbit is somewhat wrong at the fault. A place should get close to the satellite, but it shows a negative value.
I cannot appreciate it more if you can take a look at my problems!

**Comment by Xiaohua-Eric-Xu** [comment]
1) the units here in your plots are in mm and the color is really saturated.
2) to avoid phase unwrapping errors, you could either mask the data near rupture (throw them away), or use some technique to guide the rupture. In the supplements of the attached paper, Figure S3e is likely your case, and Figure S3f is from proposed approach. 
Xu, X., Tong, X., Sandwell, D. T., Milliner, C. W., Dolan, J. F., Hollingsworth, J., ... & Ayoub, F. (2016). Refining the shallow slip deficit. Geophysical Journal International, 204(3), 1867-1886.

**Comment by Uncleyyyyy** [comment]
> 1. the units here in your plots are in mm and the color is really saturated.
> 2. to avoid phase unwrapping errors, you could either mask the data near rupture (throw them away), or use some technique to guide the rupture. In the supplements of the attached paper, Figure S3e is likely your case, and Figure S3f is from proposed approach.
>    Xu, X., Tong, X., Sandwell, D. T., Milliner, C. W., Dolan, J. F., Hollingsworth, J., ... & Ayoub, F. (2016). Refining the shallow slip deficit. Geophysical Journal International, 204(3), 1867-1886.

1. So shouldn't my LOS displacement be about -560mm to 620mm? 
2. I will give it a try. Thanks for your reminder!

**Comment by Xiaohua-Eric-Xu** [comment]
In the plot, the color is really saturated. You'll need to tune the colorscale to let real amplitude show up.

**Comment by Uncleyyyyy** [comment]
> In the plot, the color is really saturated. You'll need to tune the colorscale to let real amplitude show up.

Shouldn't the colorscale be set automatically according to the range of the calculated LOS displacement value? I mean, does the colorscale mean the maximum and minimum I calculate are about 220mm and -120mm? How can I tune it manully?

**Comment by Xiaohua-Eric-Xu** [comment]
Well, the plotting in GMTSAR is based on GMT. If you read geocode.csh, the color scale is set to mean+/-2std. You could easily re-plot the image with a few lines of GMT code. e.g.
```
gmt makecpt -Cpolar -Z -D -T$low/$high/$inc > los.cpt 
gmt grdimage los.grd -Clos.cpt -Bxaf+lRange -Byaf+lAzimuth -BWSen -JX6.5i -X1.3i -Y3i -P -K > los.ps
gmt psscale -Rlos.grd -J -DJTC+w5i/0.2i+h+e -Clos.cpt -Bxaf+l"LOS displacement" -By+lmm -O >> los.ps
```
If you want shading, you'll need to run grdgradient first and use -I in grdimage to shade (illuminate) your image.

**Comment by Uncleyyyyy** [comment]
> Well, the plotting in GMTSAR is based on GMT. If you read geocode.csh, the color scale is set to mean+/-2std. You could easily re-plot the image with a few lines of GMT code. e.g.
> 
> ```
> gmt makecpt -Cpolar -Z -D -T$low/$high/$inc > los.cpt 
> gmt grdimage los.grd -Clos.cpt -Bxaf+lRange -Byaf+lAzimuth -BWSen -JX6.5i -X1.3i -Y3i -P -K > los.ps
> gmt psscale -Rlos.grd -J -DJTC+w5i/0.2i+h+e -Clos.cpt -Bxaf+l"LOS displacement" -By+lmm -O >> los.ps
> ```
> 
> If you want shading, you'll need to run grdgradient first and use -I in grdimage to shade (illuminate) your image.

Thanks for your advise! I have plotted the image again and get a good result. 
Now, I have another question that how I can get three looks file (N, E, U). Because I notice that there are only one composited los file after unwrapping, and I still need three looks file for my study. Could you please help me take a look at this question?

**Comment by dsandwell** [comment]
InSAR provides only 2 components of deformation in the line of sight of the ascending and descending passes.  One can run SAT_look to get the look vector in each case.
Because there are only two components measures one can not decompose the two LOS into three N E U.  However in your case you could assume there is no N-S motion and make a decomposition.

Here are a couple of references.

https://topex.ucsd.edu/sandwell/publications/90.pdf
https://topex.ucsd.edu/sandwell/publications/186_Xu_SRL_Ridgecrest.pdf



> On Apr 20, 2022, at 6:00 AM, Uncleyyyyy ***@***.***> wrote:
> 
> 
> Well, the plotting in GMTSAR is based on GMT. If you read geocode.csh, the color scale is set to mean+/-2std. You could easily re-plot the image with a few lines of GMT code. e.g.
> 
> gmt makecpt -Cpolar -Z -D -T$low/$high/$inc > los.cpt 
> gmt grdimage los.grd -Clos.cpt -Bxaf+lRange -Byaf+lAzimuth -BWSen -JX6.5i -X1.3i -Y3i -P -K > los.ps
> gmt psscale -Rlos.grd -J -DJTC+w5i/0.2i+h+e -Clos.cpt -Bxaf+l"LOS displacement" -By+lmm -O >> los.ps
> 
> If you want shading, you'll need to run grdgradient first and use -I in grdimage to shade (illuminate) your image.
> 
> Thanks for your advise! I have plotted the image again and get a good result.
> Now, I have another question that how I can get three looks file (N, E, U). Because I notice that there are only one composited los file after unwrapping, and I still need three looks file for my study. Could you please help me take a look at this question?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by dsandwell** [comment]
Looks great! Three recommendations:

1 the units are mm so the amplitude is ok

2 set the defomax in the config file to something like 50 . Then the across fault phase unwrapping will be smaller.

3 use grdmath to subtract the two los files and divide by 2 to get the EW component

4 try the phase gradient by setting it in the config, set the decimation to 1. Set the filter wavelength to 80.

You may need to work with a sub area.

Sent from my iPhone

On Apr 18, 2022, at 7:42 AM, Uncleyyyyy ***@***.***> wrote:

﻿
Currently I'm processing the data from an earthquake occured at Menyuan on Jan.8, and the outcome is as below

It seems ok, and the LOS displacement of ascending and descending orbits is relatively consistent. However, after I read some articles about this earthquake, I find out that the LOS displacement the other researchers have worked out is about 56cm in south and 62cm in north. I wonder why this difference would take place. By the way, the researchers get the LOS displacement by GAMMA in the articles I read.
And also, the LOS displacement of descending orbit is somewhat wrong at the fault. A place should get close to the satellite, but it shows a negative value.
I cannot appreciate it more if you can take a look at my problems!

**Comment by Uncleyyyyy** [comment]
Oh thanks for these new advice! I've tried these parameters and it turns out better than before! 
Now I'm attempting to acquire the post-seimic deformation of the same case, but the result is not very reasonable. I think it's may because my parameters are not all optimal. If I want to detect post-seismic long-term deformation, could you please give me some advise about it?
Figure1 are my results of the first 12days after the earthquake. I set filter wavelength to 200, and snaphu threshold to 0.2 to mask out the low coherence area. However as you can see, in the northern part of this figure, there are some abnormal subsidence signal, while the southern part's displacement makes no sense, neither. I couldn't appreciate it more if you can  take a look on it.
![figure1](https://user-images.githubusercontent.com/46470946/195251429-1b879fba-f9d4-4841-8b9c-9f9b429bf67d.png)
