### ISSUE TITLE
[Help]: About SBAS , the results of displacement before earthquake also have displacement like coseismic displacement.

### ISSUE THREAD

**Issue by ThreeIcug** [gmtsar/gmtsar#316]
**Describe the problem you met**
Recently, I process the data of earthquake. Time from 20210107 to 20220304, the earthquake time is 20210521.  
The SBAS results of displacement before earthquake also have displacement like coseismic displacement（the color figure is the time 20210520, which is before the earthquake.  In theory, this should not happen ). And I extract point displacements from displacement grids. It looks like doing a smooth in the result( the point and line figure， the blue is GPS_los, the red is InSAR_los). But the result which is introduced in Refined _TimeSeries_Document, it is so good.   Secondly, I want to combine the S1A and S1B to increase the temporal resolution, but when i merge the F1/2/3 the result which contain S1B data always have gap between each subswath. My parameters reference to the  Refined _TimeSeries_Document. 
![disp_2021139 grd](https://user-images.githubusercontent.com/47657302/164249527-8e754d0f-e0d6-4723-9f2e-9b5ab3e92468.png)
![GNSS_los](https://user-images.githubusercontent.com/47657302/164250494-d358f8b7-5d06-4c63-8e5a-44f64a1470fd.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
In theory, you should not be smoothing a time-series that has an earthquake in it. You could checkout our recent paper on how to deal with a timeseries that spans an earthquake: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=ME1EfdsAAAAJ&sortby=pubdate&citation_for_view=ME1EfdsAAAAJ:b0M2c_1WBrUC
Also, S1B could be treated exactly the same as S1A data for time-series analysis. So there is no "combination" step in the document I think. Maybe double check on the parameters you used or provide more details on what you did.

**Comment by ThreeIcug** [comment]
Thank you, I read your article seriously, which solved my confusion of the timeseries processing. 
Other,  there is no distinction between  S1A and S1B data in time series processing. Before doing merge_batch.csh, there are not many parameter settings, except for designating the master and move it to first line of data. The processing parameters in batch_tops.config file is same as the Refined _TimeSeries_Document. 
Proc_stage = 1
shift_topo = 0
filter_wavelength = 200
range_dec = 8
azimuth_dec = 2
threshold_snaphu = 0
threshold_geocode = 0

But my result is like this,
![image](https://user-images.githubusercontent.com/47657302/164578378-66a53a50-b1fb-4c46-a840-417e67902025.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I think we implemented an option to estimate the shift of images and deal with these types of gaps. It is the [det_stitch] in `merge_unwrap_geocode_tops.csh` or `merge_batch.csh`. You could give it a try or play with the n1/n2 parameters for merge_swath.

**Comment by Xiaohua-Eric-Xu** [comment]
You'll need to grab them from the master branch though.

**Comment by ThreeIcug** [comment]
Thank you,That's very kind of you. Under your guidance,the problem has  been solved.
