### ISSUE TITLE
Error in preproc_batch_tops.csh data.in

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#318]
I am taking 3 scenes of Sentinel for processing.
When running the preproc_batch_tops.csh command it says interpolation point outside of data constraints.
What could be the reason for such error?
Beacuse in the running of intf formation in the later steps it is showing errors so if this (interpolation out of constraint) is the reason for the errors?
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/88940973/165289258-ddad5df2-d9f3-456b-a480-5d06909f684e.png">

Thanks in advance

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @shivamthescienceguy , it says `NO orbit coverage in the selected file`. So maybe check your orbit file to see whether it covers the data.

**Comment by shivamthescienceguy** [comment]
Thanks for the reply @Xiaohua-Eric-Xu But here are the orbit files and I think they are fine.
Can you please comment?
<img width="743" alt="image" src="https://user-images.githubusercontent.com/88940973/165441681-56ced237-388c-47cc-8400-a51c9204d985.png">

**Comment by Xiaohua-Eric-Xu** [comment]
You need to have the "correct" orbit file I think. e.g. the first orbit is for 09/25, while your first data is on 09/26.

**Comment by shivamthescienceguy** [comment]
Thanks alot.
Problem Solved.
