### ISSUE TITLE
[Help]: The interference fringe is not continuous in the Sentinel-1 image.

### ISSUE THREAD

**Issue by JianBo17** [gmtsar/gmtsar#319]
**Describe the problem you met**
When I use the `p2p_S1_TOPS_Frame.csh` to process the example data from GMTSAR, the phase image seems not normal.

**OS and software version**
If applicable, what operating system and software version you are using?
OS: Ubuntu 20
GMTSAR version: 6.1

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
[log.txt](https://github.com/gmtsar/gmtsar/files/8568453/log.txt)
Here is the config file
[config.s1a.txt](https://github.com/gmtsar/gmtsar/files/8568525/config.s1a.txt)

**Screenshot**
![Screenshot from 2022-04-27 11-21-58](https://user-images.githubusercontent.com/49815131/165433443-4e371aa8-06e7-4cb5-b768-eb2a72ad4072.png)
![Screenshot from 2022-04-27 11-28-19](https://user-images.githubusercontent.com/49815131/165434082-1313dbb4-2f49-4579-a37c-e37df8f363b8.png)
The image after merge.
![Screenshot from 2022-04-27 11-30-33](https://user-images.githubusercontent.com/49815131/165434310-7b6d3b8b-3418-4d02-ad2c-76f518296da0.png)

[Please note that if no new responses are made over six months from users, the issue will get closed]

The streaks look not continuous. But the coherence is continuous. And I wonder how to produce the better interferometry images.

**Comment by dsandwell** [comment]
If this is ice flowing with motion greater than about 15 cm between the images then this answer is correct.  The discontinuities between burst can be used to measure the ice displacement.  There are probably some good papers on this topic.

> On Apr 26, 2022, at 8:34 PM, JianBo17 ***@***.***> wrote:
> 
> 
> Describe the problem you met
> When I use the p2p_S1_TOPS_Frame.csh to process the example data from GMTSAR, the phase image seems not normal.
> 
> OS and software version
> If applicable, what operating system and software version you are using?
> OS: Ubuntu 20
> GMTSAR version: 6.1
> 
> Reproduce the problem
> If applicable, how to reproduce the problem from scratch?
> 
> Log file
> log.txt
> Here is the config file
> config.s1a.txt
> 
> Screenshot
> 
> 
> The image after merge.
> 
> 
> [Please note that if no new responses are made over six months from users, the issue will get closed]
> 
> The streaks look not continuous. But the coherence is continuous. And I wonder how to produce the better interferometry images.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by JianBo17** [comment]
![1651009297(1)](https://user-images.githubusercontent.com/49815131/165448788-5c8461ae-4470-4600-8480-17d4a29597ca.jpg)

The image is belong to Chile. I think there is no ice. But it still seems not good, especially the bottom of the image.

**Comment by Xiaohua-Eric-Xu** [comment]
These top plot is the example we have for TOPS ionosphere correction on topex.ucsd.edu/gmtsar. You could download our example and run the command inside to get ionosphere corrected (master branch recommended as I made a number of fixes recently). During the correction there will be BESD to correct the discontinuities caused by the ionospheric perturbation. The bottom on looks like a similar case that could be solved by turning on the ionospheric correction. However, if the perturbation is too strong, the current module may fail as the ESD phase may wrap and one will need to unwrap the phase to acquire better correction. That is rare though.

**Comment by Xiaohua-Eric-Xu** [comment]
You should be able to get a config file with the version using `pop_config.csh`. For this specific case you need to make `correct_iono = 1`. Anyways, attached is a config file I used for the example.
[config.s1a.txt](https://github.com/gmtsar/gmtsar/files/8573637/config.s1a.txt)

**Comment by JianBo17** [comment]
Thanks, I will try it later.



---Original---
From: "Xiaohua(Eric) ***@***.***&gt;
Date: Thu, Apr 28, 2022 00:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gmtsar/gmtsar] [Help]: The interference fringe is not continuousin the Sentinel-1 image. (Issue #319)




 
You should be able to get a config file with the version using pop_config.csh. For this specific case you need to make correct_iono = 1. Anyways, attached is a config file I used for the example.
 config.s1a.txt
