### ISSUE TITLE
libgmt

### ISSUE THREAD

**Issue by MahsaAfra** [gmtsar/gmtsar#32]
Hello
I installed GMT 6.1 and GMTSAR. The test for gmt worked well, but when i try the following commands to test GMTSAR, it doesnot work. 

% esarp

% SAT_baseline

% p2p_ALOS.csh

I receive the following error:

mahsaafra@mahsaafra-Latitude-5400 DING!:~> esarp
esarp: error while loading shared libraries: libgmt.so.6: cannot open shared object file: No such file or directory

It seems there is something wrong with libgmt ...

 (also 
![Screenshot from 2020-07-19 18-09-23](https://user-images.githubusercontent.com/43547301/87886590-7758e200-c9ec-11ea-86f0-b839730da63a.png)
see attached file)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi MahsaAfra,
Could you find your libgmt.so.6 and make sure it is readable and executable. 
Cheers,
Xiaohua(Eric)

**Comment by MahsaAfra** [comment]
would you please let me know where can I find this file?
Mahsa
________________________________

**Comment by Xiaohua-Eric-Xu** [comment]
If you look inside your GMTSAR/config.mk, the GMT_LIB has a path for you to find the gmt library.

**Comment by MahsaAfra** [comment]
I found the attached. Take a look please
________________________________

**Comment by Xiaohua-Eric-Xu** [comment]
Hi MahsaAfra,
Seems I did not get any attached file.
Xiaohua(Eric)

**Comment by MahsaAfra** [comment]
Cant you see the attached file?!
________________________________

**Comment by Xiaohua-Eric-Xu** [comment]
Please go to the github page and attach your file.

**Comment by Xiaohua-Eric-Xu** [comment]
moved to #35
