### ISSUE TITLE
[Help]: stack smashing detected ***: terminated

### ISSUE THREAD

**Issue by Gigi-gugu** [gmtsar/gmtsar#322]
ubuntu 20.0
gmtsar 6.0

Dear Professor,
Sorry to bother you! I can solve this problem before, but #12  method doesn't seem to work? According to that method, the result is still "stack smashing detected * * *: terminated"
Hope to get your reply, thank you in advance!

![1](https://user-images.githubusercontent.com/92804122/167303394-af5bf252-9dfc-4ca5-894c-d202d5baad5b.jpg)

**Comment by Gigi-gugu** [comment]
![Uploading 2.jpg…]()

**Comment by Xiaohua-Eric-Xu** [comment]
Are you using the virtual machine on topex.ucsd.edu/gmtsar/downloads? 
Also, you'll need to make spotless first, and then 1) autoconf, 2) ./configure ...., 3) change config.mk, then 4) make and make install

**Comment by Gigi-gugu** [comment]
Yes, the problem has been solved. I need to delete the GMTSAR file and do the following work to be effective.

**Comment by Gigi-gugu** [comment]
I also want to ask a question. When I process data, I often report an error "hermite: interpolation not in center interval" when I run the "preproc_batch_tops.csh data.in dem.grd 2" command, but I have no problem checking my track file and DEM. The following figure shows the problems I encountered in the process of processing. However, to do Hermite interpolation, you need 7 records at least.I feel that this condition has been met. I am still very confused and hope to get your answer very much
![log1](https://user-images.githubusercontent.com/92804122/168205892-88b157f6-de32-445c-88aa-d84e0c132742.jpg)
![log2](https://user-images.githubusercontent.com/92804122/168205921-175b5453-cc53-48e4-8334-3fc4aecfeb7a.jpg)
.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @Gigi-gugu, there could be a couple of reasons. 
1) DEM has strange values, e.g. -9999 for no data.
2) Orbit is too short or too long. Your case might be too short. I made a quick fix in the master branch and let me know if this fix the problem you met. f734e7b4a385ef07503eaba992b615af489b1b4a
Cheers,
Xiaohua(Eric)

**Comment by Gigi-gugu** [comment]
Thank you very much for your timely reply. I will revise and re cut it according to your suggestions. The problem has not been solved. What else should I do? As an example, I just want to cut a small area of interest.
e.g. Attach DEM GRD information and modified code.
![Uploading image.png…]()
![log1](https://user-images.githubusercontent.com/92804122/168328418-6ac0db7c-950b-41b4-8f36-b65d1de27c33.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
Did you try updating the code in the master branch and re-compile?

**Comment by Gigi-gugu** [comment]
I directly modified _ext_orb_s1a. C_  and saved it. Do I need to do other work?

**Comment by Gigi-gugu** [comment]
Oh! I don't have make and make install. I have done this step, and the problem has not appeared. Thank you very much for your warm help! By the way, is the clipping range at least two bursts?
