### ISSUE TITLE
[Help]: Trying to merge ALOS PALSAR interferograms then got Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by m0080782** [gmtsar/gmtsar#323]
this step is successfully merges 2 interferograms of Sentinel 1. 
![Capture](https://user-images.githubusercontent.com/79082273/167341690-0f829a02-c33c-40dc-a229-18c78b91b7b6.PNG)

then when I try to merge 2 interferograms of alos palsar using that step, i got this error:
![image](https://user-images.githubusercontent.com/79082273/167342326-862abcb6-7c82-4212-aaee-81e14daf9276.png)
![image](https://user-images.githubusercontent.com/79082273/167343229-8a7b578d-b256-4767-a1ec-d0a9e1679915.png)
![image](https://user-images.githubusercontent.com/79082273/167343263-74efc911-178c-46f0-a648-4f4ac6086171.png)

can you suggest to me how to solve this error ? or let me know another way to merge 2 alos palsar interferogram ?
thank you

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @m0080782 , the merging script is used to merge TOPS data in the range direction. For ALOS-1 raw data (if not ScanSAR), you are probably dealing with merging along-track. You'll need to use `ALOS_merge` on the raw data. 

If you have processed them to SLC level, you could try stitch_tops to connect all SLC files together. However, do note that this requires very accurate timing of the data, and may not work for ALOS-1. 

You could also manually calculate the stitching line and stitch things together along track after they are processed to interferograms (i.e. .grd files).

**Comment by m0080782** [comment]
I try to find alos_merge on the raw data but it doesn't exist, and also the stitch_tops. I just got this :

![image](https://user-images.githubusercontent.com/79082273/167541679-437887c6-d4a8-487b-a8cc-7285374687f9.png)

where I can get it? are the ALOS_merge and stitch_tops should have been installed when installing gmtsar?

**Comment by Xiaohua-Eric-Xu** [comment]
Well, they should exist in your bin directory where you installed GMTSAR.  if you type `which ALOS_merge`, your shell should tell you where it is.

**Comment by Xiaohua-Eric-Xu** [comment]
What's the size of the original IMG-HH-ALPSRP074917120-H1.0__A.raw? Should be half of the original IMG-HH-ALPSRP074917120-H1.0__A.

**Comment by m0080782** [comment]
this is the original data,

![image](https://user-images.githubusercontent.com/79082273/168081692-3941f9cc-8a81-4bb1-ad75-a4bb09e6316c.png)

what's the problem? is it because of the data or maybe the wrong command or the other thing?

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what happened. Do you want to try putting 7120 before 7130 and redo the merging, as frame numbers should increase with time?

**Comment by Xiaohua-Eric-Xu** [comment]
Looks good. Usually the frames have some overlap so you don't expect the size to double after merging. The .raw file is the raw data from SAR. You'll need to process it in order to convert it to an (amplitude or phase) image.

**Comment by m0080782** [comment]
oh i see. how to convert it? I think the command for converting it will be different from the way I make the interferogram

**Comment by Xiaohua-Eric-Xu** [comment]
Once you merged the acquisitions from two dates, you could process it the same way with p2p_processing.csh but with `start_stage = 2` in your config file.

**Comment by m0080782** [comment]
okay, but how about the content on the raw folder? when I process the data to interferogram I need to put .0__A and  .LED format file onto it, then after processing done .PRM dan .raw file will appear. But now I have the .PRM and .raw file (from ALOS_merge) first, before I process the data to the interferogram. How then? I am a little bit confused about the concept.

**Comment by m0080782** [comment]
got it! is the calculation using use calc_dop_orb mandatory? 

I have tried to convert the output of the merge processing using p2p_processing.csh, the result is visible but the top area is missing, I think cause I got this :
![image](https://user-images.githubusercontent.com/79082273/169588481-e0219b70-3060-4a03-a2b2-f7507b88f847.png)

what does this mean?
\ surface [WARNING]: You should have pre-processed the data with block-mean, -median, or -mode. \
and this one : 
\ surface [WARNING]: Check that previous processing steps write results with enough decimals. \
is that telling to add any specific parameter like doppler centroid?

**Comment by Xiaohua-Eric-Xu** [comment]
Do you have a figure or png product to attach so as to explain `the top area is missing`? My suspicion is the DEM.

**Comment by m0080782** [comment]
the left side is the top area and the right side is the bottom area
![image](https://user-images.githubusercontent.com/79082273/169634100-38f8dd80-9ce2-468a-b671-a04440dd56ab.png)

and this is the result of the converting processing
![image](https://user-images.githubusercontent.com/79082273/169634108-f72e11b2-5e13-4bc4-8c05-d373e9a6f177.png)

this the area of DEM, i think it's covers the observation area already
![image](https://user-images.githubusercontent.com/79082273/169634181-04b98d47-966d-4157-a35a-dfd6b84576cc.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure. Could you send a log file of the commands you ran and the output from terminal?

**Comment by m0080782** [comment]
do you mean this file?
![image](https://user-images.githubusercontent.com/79082273/169681344-f3bb0aeb-6719-4d94-9957-6e1aaec5f79a.png)

this is the output from the terminal :
[output.txt](https://github.com/gmtsar/gmtsar/files/8748859/output.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi the log file looks good. I guess I am still a bit confused. After merging, there should be just one phasefilt_mask_ll.grd produced, right? Did you put the right number of patches in the config file? There seems to be only 3 patches processed from the log. Maybe change it to something like 5? A typical process to merge ALOS product is
1) pre_process the images
2) run ALOS_merge to combine the .raw files.
3) re-name the output so the PRM and raw files have the right name (including the input_*** names in the PRM).
4) run p2p_processing.csh from stage = 2 with the right re-named file names.

**Comment by m0080782** [comment]
that's right, just one phasefilt_mask_ll.grd produced. But the output of the terminal says that some points missing (i thought that's the data of the top area) because the phasefilt_mask_ll.png show that it's only covered on the bottom area. I think the merge process is not successful.
how do I change the patch? 

I am a bit confused about the process of combining the .raw files using ALOS_merge. this is the instruction of ALOS_merge 
Usage:
ALOS_merge PRMfile1 PRMfile2 [-output outfile] [-V] [-nodopp]
example: ALOS_merge IMG-HH-ALPSRP057130830-H1.0__A.PRM IMG-HH-ALPSRP057130840-H1.0__A.PRM -output foo -V

the name of the first and second prm files just have different digits in the last 2 numbers. I assume that both of the data must be 2 master data or 2 slave data. is it right? I am confused because I think the merge processing should be using 1 prm file of master + 1 prm file of slave, and it would produce 1 grd, isn't it? but that is using 2 master data or 2 slave data. 
meanwhile, i have 2 prm for each imagery (2 prm of master data and 2 prm of slave data from the pre_processing). then if i follow the instruction i will do the merge process twice, isn't it? the first one for the master data and the second one for the slave data, and this will give me 2 grd file. After having 2 grd files i have to merge it again? is that right?

**Comment by Xiaohua-Eric-Xu** [comment]
If you are able to share the data, I could get back to you with an example.

**Comment by m0080782** [comment]
you can download the data here : https://drive.google.com/drive/folders/18FUHzv-SNyy22MFgHrZ1E4VDX9iJVtuq?usp=sharing

**Comment by Xiaohua-Eric-Xu** [comment]
Could you also upload the LED-* files in the raw directory?

**Comment by m0080782** [comment]
yes, i already send it, is it correct?
![image](https://user-images.githubusercontent.com/79082273/169946620-d4da88ca-3589-48e1-b606-bb1e08624921.png)

**Comment by Xiaohua-Eric-Xu** [comment]
These are the ones after pre-processing. I'll need the original LED files, e.g. LED-ALPSRP088337102-H1.0__A, to run ALOS_pre_process.

**Comment by m0080782** [comment]
It looks great, I've tried to follow your steps based on the log_file but I still got the warning message like this one
https://github.com/gmtsar/gmtsar/issues/323#issuecomment-1133189494

I noticed that you are using ALOS_pre_process to preprocess the data instead of using p2p_processing.csh which needs a config file. then when I need to manipulate the ionosphere parameter how do I setting it? can I manipulate it when I process the data from stage 2?

**Comment by Xiaohua-Eric-Xu** [comment]
Yes you can. The first stage is really just to convert things into a format that GMTSAR can recognize. The current p2p_processing.csh deals with a pair of interferogram and the merging has to be done with each dates outside the script. The example we put out is also merged data (4 frames) (http://topex.ucsd.edu/gmtsar/tar/ALOS-ionosphere-correction.tar). You could try the parameters in that config file, especially `iono_filt_rng`, `iono_filt_azi` and `iono_dsamp`.

**Comment by m0080782** [comment]
I see. I have tried to make 2 interferograms, the first 1 using the default parameter and the other using the ionosphere parameter. but when I check the LOS data is not produced in the folder of the first interferogram. then I run: geocode.csh to check it, and the log doesn't say any error. then how do get the LOS data? 
Also, I noticed a different view from the second interferogram (using ionospheric parameters), the entire area appears to be more enlarged than in the first interferogram. Is this an effect of ionospheric parameters, then is this result fine? then how to change it so the view looks like the first interferogram?
![image](https://user-images.githubusercontent.com/79082273/170731652-04909790-3117-4b44-a700-fc53072603e6.png)

**Comment by Xiaohua-Eric-Xu** [comment]
To get LOS, you'll need to unwrap the results first with snaphu.csh and then when you geocode, I think the program will calculate a LOS grid for you. 
I am not sure what you mean by "enlarged". Normally you'll get kml files in the intf/day1_day2 directory and if you open them with Google Earth, you'll find their right size, etc. 
You'll need to check the results in the iono folder to see whether the correction were performed properly. You'll need to play with the filtering parameters.

**Comment by m0080782** [comment]
got it! but then I noticed this : 
![image](https://user-images.githubusercontent.com/79082273/171098825-eee28676-982d-46b9-9d10-05d289608b76.png)
 that file is one of the results in intf folder from merging 2 interferograms. the LED file is 0kb, is it correct?
