### ISSUE TITLE
[Help]: atm option not recognized

### ISSUE THREAD

**Issue by mdavid3** [gmtsar/gmtsar#325]
The problem occurs when I run the following code in terminal.
How can I solve it ?

![error](https://user-images.githubusercontent.com/101168839/168772989-6d03e590-8d5b-4b53-9f8a-b14ab2d212e9.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
This is strange, as the USAGE shows you have the version that is able to do atm correction. Could it be that you typed a different `-` in the command? There are in total 3 types of `-`, each of which looks a little different.

**Comment by mdavid3** [comment]
> KULLANIM'ın gösterdiği gibi, atm düzeltmesi yapabilen sürüme sahip olduğunuzu gösteriyor. Komutta farklı bir şey yazmış olabilir misiniz `-`? `-`Her biri biraz farklı görünen toplam 3 tür vardır .

thank you for your help. 
Solved.
