### ISSUE TITLE
[Bug]: Git tags for versions other than 6.1

### ISSUE THREAD

**Issue by ryandesign** [gmtsar/gmtsar#326]
The file GMTSAR_V6.2.tar was posted at https://topex.ucsd.edu/gmtsar/tar/ on 2022-04-21 however there is no tag corresponding to that version in this GitHub repository. Is 6.2 a stable released version? If so (or even if it is an unstable version intended for testing) can a tag please be created for it?

In fact this GitHub repository contains only a single tag, for version 6.1. Where are the tags for all previously released versions?

**Comment by dsandwell** [comment]
Hi Xiaohua,

Should we clone the master branch into V6.2?  I can do more end-to-end testing.  We have a version 6.2 made for homebrew with the changes needed for the M1 chip. 
Also I think it is too soon to replace surface with the faster algorithm because bugs may surface.

David


> On May 18, 2022, at 7:43 PM, Ryan Schmidt ***@***.***> wrote:
> 
> 
> The file GMTSAR_V6.2.tar was posted at https://topex.ucsd.edu/gmtsar/tar/ on 202204-21 however there is no tag corresponding to that version in this GitHub repository. Is 6.2 a stable released version? If so, can a tag please be created for it?
> 
> In fact this GitHub repository contains only a single tag, for version 6.1. Where are the tags for all previously released versions?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by ryandesign** [comment]
I see that a v6.2 tag has now been created in this repository but it corresponds to the state of the code on May 19, 2022, which is not the same as the 6.2 that was released on April 21, 2022 on https://topex.ucsd.edu/gmtsar/tar/ . Why the discrepancy? New code should receive a new version number.

**Comment by dsandwell** [comment]
Yes you are correct.  The V6.2 on https://topex.ucsd.edu/gmtsar/tar/ was a quick fix for the M1 chip and passed testing.  The version we are trying to release for the GMTSAR short course has additional features so we’ll call it V6.3.  However, this latest version still has a bug(s) so does not pass all the tests and we are working on that.  

Testing is done on 23 different flavors of satellite data and at least 4 OS’s so it takes a while.  Moreover the OS’s keep changing.

I would stick to 6.1 until we sort this all out.

> On May 22, 2022, at 3:23 AM, Ryan Schmidt ***@***.***> wrote:
> 
> 
> I see that a v6.2 tag has now been created in this repository but it corresponds to the state of the code on May 19, 2022, which is not the same as the 6.2 that was released on April 21, 2022 on https://topex.ucsd.edu/gmtsar/tar/ . Why the discrepancy? New code should receive a new version number.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037
