### ISSUE TITLE
GMTSAR, gmtlib 

### ISSUE THREAD

**Issue by MahsaAfra** [gmtsar/gmtsar#33]
Hi
You told me to chech 
inside your GMTSAR/config.mk, the GMT_LIB has a path for you to find the gmt library.

I found the attached, but I dont know what shuld i do next
![Screenshot from 2020-07-20 10-14-34](https://user-images.githubusercontent.com/43547301/87985431-98333d00-caa9-11ea-90fd-bb8690f31200.png)

—

**Comment by Xiaohua-Eric-Xu** [comment]
If you go to /usr/lib/x86_64-linux-gnu, do a ls -ltG. Check whether your gmt library is set as executable.

**Comment by Xiaohua-Eric-Xu** [comment]
If you need to include an attachment, do not directly reply with your email. Get to this GitHub page https://github.com/gmtsar/gmtsar/issues/33 and make a comment.

**Comment by Xiaohua-Eric-Xu** [comment]
moved to #35
