### ISSUE TITLE
[Help]: p2p_ALOS2_SCAN_Frame.csh error

### ISSUE THREAD

**Issue by JianBo17** [gmtsar/gmtsar#331]
**Describe the problem you met**
When I run the `p2p_ALOS2_SCAN_Frame.csh`, some errors occurred. The first error is `merge_swath[ERROR]: Cannot find file ../../F1/iono_phase/intf_h/phasefilt.grd`. 
![Screenshot from 2022-05-27 10-38-48 (2)](https://user-images.githubusercontent.com/49815131/170619245-dee3ead4-c7d2-4595-8fa2-1c3a49d1f6b8.png)
Then I check the file and there is no such file. So I guess there are some errors when it runs the  `p2p_processing.csh`. Its first error is `filter.csh
setting range_dec = 0, azimuth_dec = 0
gauss_500 0 0 (4 1)
making amplitudes...
 idec and jdec should be positive integers.  
 idec and jdec should be positive integers.  
filtering interferogram...
 idec and jdec should be positive integers.  
 idec and jdec should be positive integers.  
making amplitude...
grdmath [ERROR]: realfilt.grd is not a number, operator or file name`
It seems that the `filter.csh` not run correctly in line 833. The range_dec and azimuth_dec are right before it set new_incx and new_incy in line 820 and 821, `gauss_400 16 8 (4 1)`. After reset, it becomes zero. The code is `set new_incx = `echo $range_dec $iono_dsamp | awk '{print $1*$2}'``. The range_dec is 4 and iono_dsamp is 1 in the config file. But the new_incx is 0. So it can't process the data correctly.

The log file and config file are attached as follows.
**OS and software version**
OS: Ubuntu 20
GMTSAR version: master

**Log file**
[p2p_ALOS2_Frame_log.txt](https://github.com/gmtsar/gmtsar/files/8783519/p2p_ALOS2_Frame_log.txt)
[p2p_processing_log.txt](https://github.com/gmtsar/gmtsar/files/8783520/p2p_processing_log.txt)
[tmp_config.txt](https://github.com/gmtsar/gmtsar/files/8783612/tmp_config.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
You'll need to set range_dec and azimuth_dec I think, other wise the iono_dsamp parameter will fail. Not just this, if those two parameters are missing, you wouldn't be able to merge properly later on.

**Comment by JianBo17** [comment]
But the range_dec and azimuth are already set in line 115 and 116 in the `p2p_processing.csh`. The `filter.csh` before set `new_incx` and `new_incy` in line 820 and 821.

**Comment by Xiaohua-Eric-Xu** [comment]
Well, they are read from the config file. If not specified, likely you'll get a strange number like the `0 0 (4 1)`below. 
```
intf.csh
running phasediff...
reading topo topo_ra.grd
 xdim 4790, ydim 174176 
filter.csh
setting range_dec = 0, azimuth_dec = 0
gauss_500 0 0 (4 1)
making amplitudes...
```

**Comment by JianBo17** [comment]
I got it. I will try it later.



---Original---
From: "Xiaohua(Eric) ***@***.***&gt;
Date: Fri, May 27, 2022 11:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gmtsar/gmtsar] [Help]: p2p_ALOS2_SCAN_Frame.csh error (Issue#331)




 
Well, they are read from the config file. If not specified, likely you'll get a strange number like the 0 0 (4 1)below.
 intf.csh running phasediff... reading topo topo_ra.grd  xdim 4790, ydim 174176  filter.csh setting range_dec = 0, azimuth_dec = 0 gauss_500 0 0 (4 1) making amplitudes...

**Comment by JianBo17** [comment]
Hi,
I used `pop_config.csh` to generate the config file, so I guess the `pop_config.csh` need be updated.

**Comment by JianBo17** [comment]
Hi,
The `p2p_ALOS2_SCAN_Frame.csh` merge the original phase image of each swath before ionospheric estimate. However, the result seems not good. So I estimate the ionospheric phase for all swathes and I wonder to know how to merge the corrected phase images.

![ph_iono (2)](https://user-images.githubusercontent.com/49815131/173787499-a23c74d2-836d-4655-a6ff-29d6e1abcccf.jpg)
![ph0 (2)](https://user-images.githubusercontent.com/49815131/173787526-70398b82-7221-46dc-aa76-0f608770889a.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @JianBo17, this is a bug from using incorrect tension when running `gmt surface`. I made a fix recently using -T0.1 in the estimate_ionospheric_phase.csh script. Try that and see whether this still exist.

**Comment by Xiaohua-Eric-Xu** [comment]
> But the range_dec and azimuth are already set in line 115 and 116 in the `p2p_processing.csh`. The `filter.csh` before set `new_incx` and `new_incy` in line 820 and 821 can run correctly.

I missed this one, if you use `pop_config.csh ALOS2_SCAN`, you'll have the two parameter specified. I guess you used `pop_config.csh ALOS2`, which is for stripmap data.
