### ISSUE TITLE
[Help]: AUTOCONF is not working during installation of GMTSAR

### ISSUE THREAD

**Issue by dalalprohelika** [gmtsar/gmtsar#335]
**Describe the problem you met**
autoconf is not working. I also couldnot find AC_HAVE_LIBRARY in the configure.ac file. HDF5 library is already installed.
**OS and software version**
OS:Ubuntu 20.0
GMTSAR version:6.2.2

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
 
![Screenshot from 2022-06-01 12-21-39](https://user-images.githubusercontent.com/96712513/171345093-7bc777d2-fdf5-48fb-8fb7-813d7af1f1b8.png)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
Are you able to continue regardless of the warning? e.g. ./configure, make, make install ...

**Comment by dalalprohelika** [comment]
![Screenshot from 2022-06-02 09-38-37](https://user-images.githubusercontent.com/96712513/171551229-eea6a0ec-6be1-48cd-89ca-655161f1e8c1.png)
No. Those are not working as well. I am getting error as shown in above image after running make.

**Comment by raviexplorer** [comment]
i am facing the same problem. autoconf is not working. I added -z muldefs as suggested but it didn't work. Please help with this installation.

**Comment by dsandwell** [comment]
I had the same problem with Ubuntu 20 but there was a simple issue that I don’t exactly remember.  The instructions say run autoupdate but it may hae been the wrong shell (use bash) or the user was not the owner and have the correct path.

If you find the issue I’ll add some notes to the wiki page.

> On Jun 3, 2022, at 5:43 AM, raviexplorer ***@***.***> wrote:
> 
> 
> i am facing the same problem. autoconf is not working. I added -z muldefs as suggested but it didn't work. Please help with this installation.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by raviexplorer** [comment]
I tried using gcc-9 but it didn't worked. problem is coming with autoconf.

**Comment by Xiaohua-Eric-Xu** [comment]
Please attach a log file of what you did and the terminal output.

**Comment by Xiaohua-Eric-Xu** [comment]
I mean, what about afterwards? `./configure`, `make` and `make install`?

**Comment by dsandwell** [comment]
I think the issue is running this as root.  Try changing the ownership to a normal user and then exit root and start bash as that normal user.

> On Jun 3, 2022, at 9:43 AM, raviexplorer ***@***.***> wrote:
> 
> 
> ***@***.***:/usr/local/GMTSAR# autoconf
> configure.ac:39: warning: m4_warn([obsolete],
> configure.ac:39: [m4_warn([obsolete],
> configure.ac:39: [AC_CYGWIN is obsolete: use AC_CANONICAL_HOST and check if $host_os
> configure.ac:39: matches cygwin])dnl
> configure.ac:39: AC_CANONICAL_HOST
> configure.ac:39: case $host_os in
> configure.ac:39: cygwin ) CYGWIN=yes;;
> configure.ac:39: * ) CYGWIN=no;;
> configure.ac:39: esac
> 
> this is the terminal output I am getting.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by raviexplorer** [comment]
[Errors.txt](https://github.com/gmtsar/gmtsar/files/8835407/Errors.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Did you add the `-z muldefs`? Or picked a differenct complier? I didn't see that in the log.

**Comment by raviexplorer** [comment]
> 

I tried it. it is not solving the problem.

**Comment by raviexplorer** [comment]
> Did you add the `-z muldefs`? Or picked a differenct complier? I didn't see that in the log.

I don't know how to compile with gcc-9. But I added -z muldefs.

**Comment by Xiaohua-Eric-Xu** [comment]
Could you send your config.mk file?

**Comment by raviexplorer** [comment]
> Could you send your config.mk file?
I am not able to send it here

**Comment by Xiaohua-Eric-Xu** [comment]
> I think the issue is running this as root. Try changing the ownership to a normal user and then exit root and start bash as that normal user.
> On Jun 3, 2022, at 9:43 AM, raviexplorer ***@***.***> wrote: ***@***.***:/usr/local/GMTSAR# autoconf configure.ac:39: warning: m4_warn([obsolete], configure.ac:39: [m4_warn([obsolete], configure.ac:39: [AC_CYGWIN is obsolete: use AC_CANONICAL_HOST and check if $host_os configure.ac:39: matches cygwin])dnl configure.ac:39: AC_CANONICAL_HOST configure.ac:39: case $host_os in configure.ac:39: cygwin ) CYGWIN=yes;; configure.ac:39: * ) CYGWIN=no;; configure.ac:39: esac this is the terminal output I am getting. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.
> David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037

I kind of remember similar issue when using homebrew but am not sure that's the cause for this one. It only happens with the newer systems that has newer complier installed.

**Comment by Xiaohua-Eric-Xu** [comment]
> > Could you send your config.mk file?
> > I am not able to send it here

rename it to config.mk.txt and you should be able to send it over.

**Comment by raviexplorer** [comment]
[config.mk.txt](https://github.com/gmtsar/gmtsar/files/8835496/config.mk.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Hmm, this is strange. You LEFLAGS in config.mk are `-m64 -s -Wl,-rpath,/usr/lib/x86_64-linux-gnu -z muldefs`, but the errors.txt you sent does not have the same flags as in config.mk. 
```
gcc -m64 -s -Wl,-rpath,/usr/lib/x86_64-linux-gnu bperp.o -L/usr/local/GMTSAR/gmtsar -lgmtsar -L/usr/lib/x86_64-linux-gnu -lgmt -llapack -lblas -lm   -L/usr/local/lib -ltiff -lm -o bperp
```
Any chance you didn't update that after running `./configure` but before running `make`?

**Comment by raviexplorer** [comment]
yes , i updated it later. But I have tried again. it is still not working

**Comment by raviexplorer** [comment]
I followed exact these steps right now, But GMTSAR not installed. 
Is GMT software needed for the installation of GMTSAR?

**Comment by Xiaohua-Eric-Xu** [comment]
Did the former issue gets resolved?
Yes, you need to have GMT installed (https://github.com/gmtsar/gmtsar/wiki/GMTSAR-Wiki-Page).

**Comment by raviexplorer** [comment]
no, former issue didn't get solved. 
I have been following exactly the same link to install gmtsar

**Comment by Xiaohua-Eric-Xu** [comment]
let's see what we can do over zoom. https://utexas.zoom.us/j/91879226811?pwd=c2xNWEp5ZzZVNjdXcFY4VVlnR3pVdz09

**Comment by raviexplorer** [comment]
okay, i am installing zoom. Please wait

**Comment by raviexplorer** [comment]
zoom is asking for the meeting passcode

**Comment by raviexplorer** [comment]
https://meet.google.com/oca-gxka-sda

**Comment by raviexplorer** [comment]
> let's see what we can do over zoom. https://utexas.zoom.us/j/91879226811?pwd=c2xNWEp5ZzZVNjdXcFY4VVlnR3pVdz09
Thanks a lot.

**Comment by dalalprohelika** [comment]
I am having the same errors. And yes, I recently reset my system. Earlier I was not having this kind of issue.  If you got any solution on your zoom meeting please mention it here.

**Comment by raviexplorer** [comment]
While installing I removed the ownership of GMTSAR directory, so I was not able to install it properly. Make sure you have full access of GMTSAR.

**Comment by raviexplorer** [comment]
Use chown command to make yourself owner

**Comment by dalalprohelika** [comment]
still i am getting the same error
![Screenshot from 2022-06-04 10-12-49](https://user-images.githubusercontent.com/96712513/171983443-32716a3f-cecc-447b-81ff-4e75c9f6f873.png)

**Comment by raviexplorer** [comment]
> I think you may need to follow the exact steps. 1) make spotless, 2) autoconf, 3) ./configure, 4) update config.mk with the change in flags, 5) make and make install.
> 
> The first a few steps will overwrite config.mk and thus the changes did not get reflected when you run make.

Now follow this step

**Comment by dalalprohelika** [comment]
![Screenshot from 2022-06-04 10-32-50](https://user-images.githubusercontent.com/96712513/171984195-388162ce-36eb-490c-821f-a8fc0aa8febc.png)

**Comment by raviexplorer** [comment]
This error will come but continue with the next steps,  ultimately it gets installed.
