### ISSUE TITLE
Problems with run_tops.sh command

### ISSUE THREAD

**Issue by RenzoAnc** [gmtsar/gmtsar#337]
Dear everyone. I have a question about DInSAR processing with GMTSAR. I'm trying to form an interferogram following a tutorial that I found on the website:
https://www.researchgate.net/publication/354780485_GMTSAR_installation_and_processing_Guide_-_Practical_InSAR_handbook_series
but I can't run **run_tops.sh** command. 
When I execute this command on a Linux terminal, initially it runs, but it doesn't continue running when it arrives at this line: "range decimation is: 2" (You can see it in the figure below). 
This problem is similar to executing _cat_ command on a Linux terminal. 

![Terminal_Command2F](https://user-images.githubusercontent.com/105986961/171967785-a8930cb5-f095-4579-aeea-446b9fcc8171.PNG)

I understand interferograms can be formed using two commands: **run_preproc_align.sh** and **run_tops.sh**. I think the first command works well (./run_preproc_align.sh) because I didn't get any errors on it. I send a file where you can find the results of the first command ([Results1.txt](https://github.com/gmtsar/gmtsar/files/8836210/Results1.txt)). But when I execute the second command (run_tops.sh), it just runs a few lines. 

I'm using the following:
Virtual Machine: VMWare 
OS: Ubuntu 20.04.4 LTS x86_64

To form the interferogram, the first step is realized with this command ([run_preproc_align.txt](https://github.com/gmtsar/gmtsar/files/8836200/run_preproc_align.txt)):

**./run_preproc_align.sh**  S1B_IW_SLC__1SDV_20201221T103040_20201221T103108_024799_02F34A_6F94.SAFE 
S1B_IW_SLC__1SDV_20210114T103039_20210114T103107_025149_02FE8B_3C81.SAFE
S1B_OPER_AUX_POEORB_OPOD_20210110T111519_V20201220T225942_20201222T005942.EOF
S1B_OPER_AUX_POEORB_OPOD_20210203T112353_V20210113T225942_20210115T005942.EOF 

The second step is realized with this command **run_tops.sh**: [run_tops.txt](https://github.com/gmtsar/gmtsar/files/8836203/run_tops.txt). Because my Area Of Interest is located in IW1 subswath, I execute this command after I delete F2 and F3 folders formed with run_preproc_align.sh.

The **config.s1a.txt** is:       
[config.s1a.txt](https://github.com/gmtsar/gmtsar/files/8836208/config.s1a.txt)

I will appreciate all advice you can give me. Thanks in advance.

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure of script used by others, but there is an automated script to process a pair of Sentinel-1 frame-wise interferogram called p2p_S1_TOPS_Frame.csh. The one you sent seems not doing any merging afterwards.

**Comment by RenzoAnc** [comment]
> I am not sure of script used by others, but there is an automated script to process a pair of Sentinel-1 frame-wise interferogram called p2p_S1_TOPS_Frame.csh. The one you sent seems not doing any merging afterwards.

Thank you for your reply, Xiaohua-Eric-Xu. Do you know where I can find the script  p2p_S1_TOPS_Frame.csh?. I am grateful to you if you send me a link to find it. Regards.

**Comment by Xiaohua-Eric-Xu** [comment]
It is in GMTSAR/gmtsar/csh. You may need to update to a newer version though.

**Comment by RenzoAnc** [comment]
> It is in GMTSAR/gmtsar/csh. You may need to update to a newer version though.

Thank you, Xiaohua. I'll use this command to produce interferograms. Regards.
