### ISSUE TITLE
grdfilter [ERROR]: (x_max-x_min) must equal

### ISSUE THREAD

**Issue by demark4** [gmtsar/gmtsar#340]
Hello,
It's my first time using GMTSAR and I want to make sure I'm going right. When I ran the code preproc_batch_tops.csh data.in dem.grd 2 I got the following error.
Where did I go wrong?

demark-fujitsu:/home/demark/Desktop/SAR/train/F2/raw> preproc_batch_tops.csh data.in dem.grd 2
grdfilter [ERROR]: (x_max-x_min) must equal (NX + eps) * x_inc), where NX is an integer and |eps| <= 0.0001.
grdfilter (gmtlib_read_grd_info): Use grdedit -A on your grid file to make region and increments compatible [dem.grd]
rm: No match.
Reading in 5224 lines of info from XML...
Writing 17 lines for orbit...
Writing SLC..Image Size: 25824 X 12192...
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 0 
Writing 53 lines of precise orbit for the LED file...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
rm: No match.
Reading in 4711 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Shifting the master PRM by 0 lines...
Successfully opened junk1.PRM 
Successfully opened junk2.PRM 
......master LED file S1_20200101_154221_F2.LED 
.........aligned LED file S1_20180111_154207_F2.LED 
......master LED file S1_20200101_154221_F2.LED 
.........aligned LED file S1_20180111_154207_F2.LED 
Successfully opened junk1 
Successfully opened junk1

**Comment by chintals** [comment]
@demark4 the error is happening when you sample the dem.grd in the code.

Can you try this command (in terminal) in a directory (/topo) that contains the dem.grd file, even with the error you should see a new file called flt.grd  
`gmt grdfilter dem.grd -D2 -Fg2 -I12s -Gflt.grd`

If you see the flt.grd, then the command `preproc_batch_tops.csh data.in dem.grd 2` is executed successfully.

I do have a few questions:
1. Did you generate dem.grd using GMTSAR demgen? 
2.  Which version of GMT are you using?  type `gmt --help` in terminal
3.  Can you paste the output from` gmt grdinfo dem.grd`

**Comment by demark4** [comment]
Hi @chintals 
Thank you for your reply.
When I ran the "gmt grdfilter dem.grd -D2 -Fg2 -I12s -Gflt.grd" command, the error didn't occur.
Now preproc_batch_tops.csh data.in dem.grd 2 command works without errors.
But what is the source of this error? May I know where did I go wrong?

Answer your questions
1. Yes.
2. GMT - The Generic Mapping Tools, Version 6.0.0 [64-bit] [40 cores]
3.  demark-fujitsu:/home/demark/Desktop/SAR/train/F2/topo$ gmt grdinfo dem.grd
dem.grd: Title: Produced by grdmath
dem.grd: Command: grdmath dem_ortho.grd egm96.grd ADD = dem.grd
dem.grd: Remark: 
dem.grd: Gridline node registration used [Geographic grid]
dem.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
dem.grd: x_min: 33.9636 x_max: 34.3213 x_inc: 0.000277717391304 name: longitude [degrees_east] n_columns: 1289
dem.grd: y_min: 37.9768 y_max: 38.2253 y_inc: 0.000277653631285 name: latitude [degrees_north] n_rows: 896
dem.grd: z_min: 1012.84741211 z_max: 3296.52734375 name: z
dem.grd: scale_factor: 1 add_offset: 0
dem.grd: format: netCDF-4 chunk_size: 129,128 shuffle: on deflation_level: 3

**Comment by chintals** [comment]
@demark4 I believe the error is not due to GMTSAR code, but could be an update/edit/fix on GMT. 

@Xiaohua-Eric-Xu Did any changes happen with GMTSAR demgen recently?  The x_inc, and y_inc doesn't show (1 sec) and I believe old demgen was outputting x_inc and y_inc  ~ 0.277777778. I think GMT netCDF is on CF-1.7 format.
