### ISSUE TITLE
Regarding Coherence Threshold in Sentinel processing

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#341]
Hie Eric,
I have one doubt regarding the threshold value of coherence stack as in the sentinel documentation itself we are taking threshold as 0.075 which is very low I think. Does this mean that most of the areas have threshold below 0.1.

![image](https://user-images.githubusercontent.com/88940973/173174168-c17c9463-2682-4b89-b43d-027c28d35350.png)

As what we do, is we generally consider < 0.3 pixels as noisy pixels. So in this case all the pixels are noise.
So is it significant to use threshold of 0.075 for deformation signals?

In my study area also, 0.075 is giving me good number of pixels but threshold of 0.3 is mostly blank. So I am concerned whether I am taking threshold too low and considering noisy pixels too.

Thanks

**Comment by chintals** [comment]
@shivamthescienceguy  GMTSAR computes coherence in a different way than other codes (lower coherence value than other codes). Typically a coherence cutoff of 0.1 can be used. If you want to get a good idea for a cutoff, you can generate histogram of corr_stack.grd and preview the grd file to identify a good threshold.

**Comment by Xiaohua-Eric-Xu** [comment]
The definition of coherence changes from software to software. It kind of depends on what definition you are using. GMTSAR only uses the most primitive definition without any further changes like removal of a plane, etc. Also multi-looking may increase coherence as well. https://github.com/gmtsar/gmtsar/issues/86

**Comment by demark4** [comment]
hi @Xiaohua-Eric-Xu,
1) “Can you explain to me the Unwrap threshold and smoothing factor values in the unwrap_intf.csh file?
2) Why do we take 0.1 as general acceptance here?
3) How is the Unwrap threshold calculated in GMTSAR?

**Comment by Xiaohua-Eric-Xu** [comment]
If you are thinking of using the sbas program in GMTSAR, then pick a small threshold (e.g. 0.001) or create a common coherence mask over a stacked coherence grid. The sbas program will abandon the pixel if any date appears decorrelated (NaN). As @chintals mentioned, 0.1 is a reasonable number for most cases we met, but it's really user dependent. You could do a histogram like @chintals said and pick a threshold based on that.
