### ISSUE TITLE
select_pairs.csh baseline_table.dat if: Expression Syntax

### ISSUE THREAD

**Issue by demark4** [gmtsar/gmtsar#342]
Dear @Xiaohua-Eric-Xu . I have a question about SBAS processing with GMTSAR. 

When I run the command "select_pairs.csh baseline_table.dat 100 50" I get an error.

Can you suggest to me how to solve this error ? 
Ubuntu 20.04.4 LTS
GMTSAR 6.2

![ss](https://user-images.githubusercontent.com/107100805/173203710-2b0adeb8-e593-4fd7-896c-38afa5116c36.jpg)
![2](https://user-images.githubusercontent.com/107100805/173203726-4d64f906-4d23-4ace-a6b9-679705466bf3.jpg)

**Comment by chintals** [comment]
Hi @demark4 can you show us your baseline table as an attachment? 

You are specifying a temporal baseline of 100 and perp baseline as 50. Are you getting the error when you run the same command again? if yes, can you run the command with a higher perpendicular baseline, say 100?

**Comment by demark4** [comment]
I installed Ubuntu 18.04 and GMTSAR 6.2 and the error disappeared.

![sss](https://user-images.githubusercontent.com/107100805/173396289-e7d39d8c-5b6f-4bf7-8435-264bf05c7a13.jpg)

**Comment by chintals** [comment]
@demark4 I don't think Ubuntu 20.04 is causing this issue. Is HDD3 a traditional harddrive?

Do you still have the copy of the failed baseline table and failed intf.in file? 

Perhaps adding a wait statement after gmt psxy command could help, since the code is updating the post script file at every iteration in the for loop.

**Comment by demark4** [comment]
Yes HDD3 traditional hard drives.
Sorry the files are not available.
I thought such an error occurred because the last lines were not shown. But now there is no error.
Thank you so much @chintals.

**Comment by demark4** [comment]
> Ubuntu 18.04'te hatanın olmadığını bilmek güzel. Çalıştığından emin olmak için csh betiğindeki for döngüsündeki wait ifadesini test etmek iyi olurdu.
> 
> Başarısız intf.in dosyasını istememin nedeni, çökmeden önce kaç tane intf çifti tanımladığı konusunda size bir fikir verebilirdi, ancak başarısız ağın ekran görüntüsü de bu bilgiyi gösteriyor.

60 pairs.
gmt --version
5.4.3

**Comment by demark4** [comment]
After the analyzes are finished, I can reinstall 20.04 if you want. After the analyzes are finished, I can reinstall 20.04 if you want. I want to know where is the error.

**Comment by Xiaohua-Eric-Xu** [comment]
Such `if syntax error` are likely from weird characters getting into your input file. It's hard to debug as even if you check on the file (e.g. your baseline_table.dat), sometimes it just does not show up. Sometimes it's related to input method, some are from specific systems (e.g. windows).

**Comment by demark4** [comment]
> Such `if syntax error` are likely from weird characters getting into your input file. It's hard to debug as even if you check on the file (e.g. your baseline_table.dat), sometimes it just does not show up. Sometimes it's related to input method, some are from specific systems (e.g. windows).

hi @Xiaohua-Eric-Xu 
Thank you for the answer.
When I did the same operations on ubuntu 18.04, the error did not occur. How do we eliminate this error? Because I want to install ubuntu 21.04.

**Comment by Xiaohua-Eric-Xu** [comment]
There shouldn't be a difference with respect to ubuntu 18 or 21. How did you generate baseline_table.dat? Did you edit it after using a specific command?

**Comment by demark4** [comment]
> There shouldn't be a difference with respect to ubuntu 18 or 21. How did you generate baseline_table.dat? Did you edit it after using a specific command?

I generated it after command. I didn't edit.

**Comment by Xiaohua-Eric-Xu** [comment]
Hmm, that's strange. We do have an ubuntu 21.04 virtual machine distributed here http://topex.ucsd.edu/gmtsar/tar/Ubuntu21.04_gmt6.1_gmtsar6.2.ova Feel free to try it to see whether the error persists.

**Comment by demark4** [comment]
> Hmm, that's strange. We do have an ubuntu 21.04 virtual machine distributed here http://topex.ucsd.edu/gmtsar/tar/Ubuntu21.04_gmt6.1_gmtsar6.2.ova Feel free to try it to see whether the error persists.

I will try right away. Thank you so much @Xiaohua-Eric-Xu

**Comment by chintals** [comment]
@Xiaohua-Eric-Xu All the times I have used GMTSAR, the only time I got the above error was when I was doing intensive IO operations during select_pairs step, which executed without creating all the intf pair.  I added a wait statement in select_pairs.csh (after `gmt psxy` command in the loop) and it ran fine and completed all the intf pairs (with no external IO on the SSD, on Ubuntu 20.04 LTS, GMTSAR 6.2). That is the reason why I was wondering if write speed of the hard-disk (in this case an traditional HDD, is slower than the execution of the for loop as its generating many pairs and updating the postscript file in the loop.  If harddisk speed is an issue, the wait command would solve the problem.

**Comment by demark4** [comment]
> @Xiaohua-Eric-Xu All the times I have used GMTSAR, the only time I got the above error was when I was doing intensive IO operations during select_pairs step, which executed without creating all the intf pair. I added a wait statement in select_pairs.csh (after `gmt psxy` command in the loop) and it ran fine and completed all the intf pairs (with no external IO on the SSD, on Ubuntu 20.04 LTS, GMTSAR 6.2). That is the reason why I was wondering if write speed of the hard-disk (in this case a traditional HDD, is much slower than the execution of the for loop -as its generating many pairs and updating the postscript file in the loop. If harddisk speed is an issue, the wait command would solve the problem.

I would like to try the select_pairs.csh file you edited.

**Comment by chintals** [comment]
[select_pairs.zip](https://github.com/gmtsar/gmtsar/files/8900555/select_pairs.zip). Let me know if it helps.

**Comment by demark4** [comment]
Hi @ericlindsey @chintals
I am getting the following error while unwrapping. Can you help me ?
![1](https://user-images.githubusercontent.com/107100805/173694127-9f2e513e-e88b-4b0f-81a3-6b7714986c8e.jpg)
![2](https://user-images.githubusercontent.com/107100805/173694134-06e3a890-19df-443b-bf06-412ee2401f2f.jpg)
![3](https://user-images.githubusercontent.com/107100805/173694137-b99de237-5b2d-4bb9-a2d5-ea4634ce69a1.jpg)
![4](https://user-images.githubusercontent.com/107100805/173694138-a24f763e-b01e-4462-b67a-401cecfb09d4.jpg)
![5](https://user-images.githubusercontent.com/107100805/173694140-b98806ca-1404-461f-9641-cef228ef8dd0.jpg)
![6](https://user-images.githubusercontent.com/107100805/173694141-f15a3072-f6ea-43a8-89e9-5ecab416c6d2.jpg)

**Comment by ericlindsey** [comment]
It looks to me like there is an interferogram folder that failed at an earlier step, resulting in the missing corr_patch.grd. In your directory listing, you can see that there is no corr.grd, and many of the other files have zero file size. Check the earlier steps where interferograms were created, it seems to have failed at that earlier step.

**Comment by shivamthescienceguy** [comment]
I got the same error,
running command  tcsh followed by the select_pairs command works in my case.
Tell me if it works in your case. @demark4

**Comment by demark4** [comment]
> I got the same error, running command tcsh followed by the select_pairs command works in my case. Tell me if it works in your case. @demark4

working

**Comment by demark4** [comment]
Hi @chintals,
I am using Ubuntu 20.04.4 LTS and GMT 6.0. There are currently no problems.

**Comment by mcollinssfd** [comment]
Hi @Xiaohua-Eric-Xu @chintals,
I'm getting the same error. how can i solve ?

![ss](https://user-images.githubusercontent.com/117281341/201466223-a921fb3d-04c6-4220-8ca3-a81dba224842.jpg)
[baseline_table.txt](https://github.com/gmtsar/gmtsar/files/9994536/baseline_table.txt)
