### ISSUE TITLE
[Help]:How to get a good sbas result? 

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#344]
Hi! Eric-Xu
I run SBAS and do `gmt grdtrack` got  point `LOS_InSAR.disp`
But it looks not well.
![ed129dfa721c1c45deb08e0079eb91d](https://user-images.githubusercontent.com/86451834/173608580-1d2ba7b3-9626-431c-8465-3a3ce7433ce4.png)
perpul line and orange line use same date
but perpul has more intf-cup(as down)
![ef8b5e41bdd7cdd2a6edf74908e9429](https://user-images.githubusercontent.com/86451834/173608634-ad663ae7-65a9-4068-849a-a71f1d657ef0.png)
![ef8b5e41bdd7cdd2a6edf74908e9429](https://user-images.githubusercontent.com/86451834/173608963-ae854aef-4420-4b1b-b933-f72d1242075c.png)

Should I choose more intf-cup??

By the way

Before I run sbas.
I set `filter_wavelength = 200`
I run gmt grdsample `range_dec = 16 azimuth_dec = 4`
and `master_image = S1_20170520_ALL_F1`(I choose first image just for convenient)
I choose first image and last three in intf.in.
like
S1_20180508_ALL_F1:S1_20180514_ALL_F1
S1_20180508_ALL_F1:S1_20180526_ALL_F1
S1_20180508_ALL_F1:S1_20180520_ALL_F1
Do you have some advice?
Thanks.

**Comment by swjiaotong-jyliu** [comment]
This is orange 
![fecbe66b8161a88581e70c8f099749f](https://user-images.githubusercontent.com/86451834/173610994-cad3e854-f4cb-451b-a5fc-dfd6cd35ebad.png)

**Comment by swjiaotong-jyliu** [comment]
I run Gacos before.
whole code is:
>nohup sbas intf.tab scene.tab 32 33 4281 3264 -range 839132 -incidence 38.877 -wavelength 0.0554658 -smooth 5.0 -rms -dem -atm 10 &
>nohup sbas intf.tab scene.tab 93 33 4281 3264 -range 839132 -incidence 38.877 -wavelength 0.0554658 -smooth 5.0 -rms -dem -atm 10 &

**Comment by Xiaohua-Eric-Xu** [comment]
A couple of things to try here.
1) Did you pin to a reference position?
2) For detection of localized signal, you could just detrend the interferogram to reduce artifact from atmosphere. 
3) Use longer time-series, to reduce the edge effect from the atm correction algorithm built in sbas.

**Comment by swjiaotong-jyliu** [comment]
1:Yes I choose same GPS position.

2:I use  `gacos_operation.csh`
>gmt grdtrend unwrap_GACOS_corrected.grd -N3r -Dunwrap_GACOS_corrected_detrended.grd
I'm not sure if it is useful。

3：I  use longer time-series，but it is caculating。

I noticed that orange line is quickly than pink line.
Does it mean that increased interference is bad?
Or because the time is too short, both results are bad？

**Comment by Xiaohua-Eric-Xu** [comment]
The command is resampling. To pin to a location ,use `grdcut` to get that area, run `grdinfo -C` to get the mean value, then use `grdmath` to shift your unwrapped interferogram so the location is roughly zero.

**Comment by swjiaotong-jyliu** [comment]
REFERENCE POINT is 118.000000 39.000000 
I set it in the center dem.grd,while GPS point is 117.1	39.38



>#REFERENCE POINT
>set ref_value = `gmt grdtrack $reference_point -Gresample_zpddm.grd -Z`
>gmt grdmath resample_zpddm.grd $ref_value SUB = szpddm.grd
>
>#FROM METER TO PHASE
>gmt grdmath szpddm.grd 4 MUL $pi MUL $wavelength DIV = szpddm_phase.grd
>
>#PROJECTION FROM ZENITH VIEW TO LOS
>gmt grdmath szpddm_phase.grd $incidence COSD DIV = szpddm_phase_LOS.grd
>
>#CORRECTION WITH GACOS DATA
>gmt grdmath unwrap.grd szpddm_phase_LOS.grd SUB = unwrap_GACOS_corrected.grd
>
>#DETRENDING
>gmt grdtrend unwrap_GACOS_corrected.grd -N3r -Dunwrap_GACOS_corrected_detrended.grd

**Comment by swjiaotong-jyliu** [comment]
He shift gacos interferogram.Should i do it for my unwrap.grd?

**Comment by Xiaohua-Eric-Xu** [comment]
What is resample_zpddm.grd?
Seem you subtracted it from unwrap.grd already. Would be good to make a few plots just to make sure things are running as expected.

**Comment by swjiaotong-jyliu** [comment]
resample_zpddm.grd is gacos data
>gmt grdmath unwrap.grd szpddm_phase_LOS.grd SUB = unwrap_GACOS_corrected.grd

by the code delete gacos phase
#DETRENDING
gmt grdtrend unwrap_GACOS_corrected.grd -N3r -Dunwrap_GACOS_corrected_detrended.grd
and i do snaphu again

then  i do sbas

I pin  to TJBH
![555](https://user-images.githubusercontent.com/86451834/174428820-a78a149f-469f-4dfe-a240-0239050e0c36.png)
or
![45](https://user-images.githubusercontent.com/86451834/174428823-c3db70b2-454b-497b-ba43-7e697dd8acb7.png)
but the other point looks not good.
