### ISSUE TITLE
[Help]: Regarding corr_stack.grd and mask_def.grd results.

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#345]
Hie Eric,
I am using 175 images for sentinel for subsidence mapping of my area.
It could generate 738 interfeograms and after deleting the bad interferogram (showing bursts and decorrelated ones) , I am left with 638 interferograms.
The concern is :
1) My mask_def.grd now also shows lines of bursts (mostly in the F1 burst) which is a matter of concern I think. So what could be the reason for this one provided I have excluded all the bad intf with bursts visible?

**Image with threshold of 0.095**
![0 095](https://user-images.githubusercontent.com/88940973/173802230-496cd863-d5d0-44a8-941e-4a40c33c727c.png)

Thanks in advance

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @shivamthescienceguy , burst discontinuity and lower coherence are two different issue. Burst discontinuities are from mis-registration, e.g. orbit, azimuthal motion, etc. They are part of the reason but not the determining factor for the burst lines you see there. These likes are from burst shifts which means over that line, one SLC is from forward looking while the other is from backward looking. If you really don't want to have these in your solution, 1) figure out a coordinates that's right on one of the line, 2) run grdtrack through all the unwrap.grd over that coordinates (they should be nan when such line exists) or corr.grd (that has small numbers). 3) you'll find out that those interferogram are associated with a few specific dates. 4) exclude them from your stack and run the rest.

**Comment by shivamthescienceguy** [comment]
Hie Eric thanks for all the help.
I have successfully processed 175 images. The thing is unwrapping the whole 3 bursts was a never ending time.
So I took selected intfs from F1 only and cut the corr.grd file by gmt grdcut and unwrapped my area of interest only.
In this case unwrapping took only 4 hours for 175 scenes.
After SBAS processing, my SBAS png was all blue. 
And all the pixels are showing similar subsidence trend so it is quiet weird .
Could you please tell me where I may have gone wrong during processing?. As I chose using only the F1 burst and cut the corr.grd by gmt grdcut otherwise everything was according to the manual.
![vel_ll](https://user-images.githubusercontent.com/88940973/177537514-da6622a9-08a6-44f4-9d90-702dfc763088.png)

**Comment by shivamthescienceguy** [comment]
Hie Eric,
I could not understand how to plot [mean-2std, mean+2std]
The following are the results for gmt grdinfo -L2
**rms is also 86.**
![image](https://user-images.githubusercontent.com/88940973/178238245-cd2e485e-bd93-470b-8a64-282622f83ecf.png)

Could you please guide me where I may have gone wrong as also plotting of all 175 disp.grd files shows similar subsidence trend of each pixel.

**Comment by Xiaohua-Eric-Xu** [comment]
You probably want a cpt file such as `gmt makecpt -Cturbo -T-93/-79/1 -Z -D > vel.cpt` and use it for plotting. I noticed that your results have all negative values. Did you pin to a point or detrend your data before running sbas?

**Comment by shivamthescienceguy** [comment]
Thanks for the reply Eric,

Yeah but Where is the step before sbas to pin point the reference point?
I think that would solve the problem.

**Comment by Xiaohua-Eric-Xu** [comment]
To detrend, simply run `gmt grdtrend unwrap.grd -N3r -Gunwrap_dtr.grd` in each interferogram directory in the merge folder.
To pin, 1) go to each interferogram directory, use gmt grdcut to take out a small region to pin.
2) run gmt grdinfo to get the mean value over the region.
3) run gmt grdmath to shift the unwrap.grd so the selected small region has zero mean.

Since quite a number of users asked this before, I'll write a script and put it to GMTSAR/csh.

**Comment by shivamthescienceguy** [comment]
Yeah thanks,
Could you elaborate the steps for pinning as it is not mentioned in the
manual.
Being new to gmt makes it little challenging.
So, After cutting and finding mean how to I select it as pin and how will
sbas take this pin value?
Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
e.g. in cshell
```
ls 20* > dirs.txt
foreach folder (`cat dirs.txt`)
    cd $folder
    gmt grdcut unwrap.grd -R100/120/2000/2020 -Gtmp.grd
    set a = `gmt grdinfo tmp.grd -L2 -C | awk '{print $12}'`
    gmt grdmath unwrap.grd $a SUB = unwrap_pin.grd
    rm tmp.grd
end
```
you'll need to figure out the region to pin to replace the `-R100/120/2000/2020`

**Comment by shivamthescienceguy** [comment]
Thanks for the reply,
One thing if I want to pin location of a stable area say an airport and I know only the latitude and longitude, how will I know the radar coordinates of this.
We have raln.grd and ralt.grd as look up table to convert the same but I am not able to understand as to how?
Do we have any code or tool to convert out lat long to radar coordinate in gmt?

Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
You could 1) figure out lon, lat, elevation, 2) run SAT_llt2rat to convert it to range, azimuth

**Comment by shivamthescienceguy** [comment]
Thanks Eric but how do I find the elevation. Will the SRTM data downloaded from gmtsar will be used If yes then how?

**Comment by Xiaohua-Eric-Xu** [comment]
Yes. I think you could use the new make_dem.csh to get a dem (STRM15+) from the Hawaii site hosted by the GMT software. The script will add EGM 96 geoid.

**Comment by shivamthescienceguy** [comment]
Thanks Eric but this script gives the DEM I think but I need to know the elevation of my pin to use SAT_llt2rat?
How to do that to know the radar coordinate of my pin?
So that I can know which structure on the ground I am doing the pinning for.
Thanks

> You could 1) figure out lon, lat, elevation, 2) run SAT_llt2rat to convert it to range, azimuth

**Comment by Xiaohua-Eric-Xu** [comment]
Assume you have lon lat, then use `gmt grdtrack` to get the elevation using the DEM file. Then run `SAT_llt2rat` to get radar coordinates.

**Comment by shivamthescienceguy** [comment]
Thanks Eric, That worked well.
