### ISSUE TITLE
intf_tops_parallel

### ISSUE THREAD

**Issue by demark4** [gmtsar/gmtsar#347]
Hi @Xiaohua-Eric-Xu,
When I run "intf_tops_parallel.csh intf.in batch_tops.config 6"
[Error.txt](https://github.com/gmtsar/gmtsar/files/8916872/Error.txt)
 command I get the following error.

oos@oos:/media/oos/HDD3/SAR/F2$ tcsh
oos:/media/oos/HDD3/SAR/F2> intf_tops_parallel.csh intf.in batch_tops.config 6
cut: you must specify a list of bytes, characters, or fields
Try 'cut --help' for more information.
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180204_ALL_F2.LED 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180111_ALL_F2.LED 
reading topo topo_ra.grd
 xdim 25824, ydim 12192 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180405_ALL_F2.LED 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180111_ALL_F2.LED 
reading topo topo_ra.grd
 xdim 25824, ydim 12192 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180312_ALL_F2.LED 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180111_ALL_F2.LED 
reading topo topo_ra.grd
 xdim 25824, ydim 12192 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180216_ALL_F2.LED 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180111_ALL_F2.LED 
reading topo topo_ra.grd
 xdim 25824, ydim 12192 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180324_ALL_F2.LED 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180111_ALL_F2.LED 
reading topo topo_ra.grd
 xdim 25824, ydim 12192 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180228_ALL_F2.LED 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180111_ALL_F2.LED 
reading topo topo_ra.grd
 xdim 25824, ydim 12192 
grep: ./raw/.PRM: No such file or directory
cp: cannot stat '../../raw/.PRM': No such file or directory
cp: cannot stat '.PRM': No such file or directory

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1_20180123_ALL_F2.LED 
.........aligned LED file XXXXXXXX 
 Can't open ldrfile %s XXXXXXXX 
......master LED file S1_20180123_ALL_F2.LED 
.........aligned LED file S1_20180123_ALL_F2.LED 
reading topo topo_ra.grd
 baseline < -9000 not set ?  
mv: cannot stat '.PRM0': No such file or directory
 Can't open input data  XXXXXXXX PFACE 
conv: File amp2_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  amp2_tmp.grd=bf 
conv: File real.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real.grd=bf 
conv: File real_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real_tmp.grd=bf 
conv: File imag.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag.grd=bf 
conv: File imag_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag_tmp.grd=bf 
grdmath: Syntax error: realfilt.grd is not a number, operator or file name
grdmath: Syntax error: amp.grd is not a number, operator or file name
grdinfo: Error for input file: No such file (display_amp.grd)
grdinfo: Syntax error: Must specify one or more input files
grd2cpt: Error for input file: No such file (display_amp.grd)
grd2cpt: Syntax error -L option: Cannot decode limits
grd2cpt: Syntax error -L option: min_limit must be less than max_limit.
grdimage: Error for input file: No such file (display_amp.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
psscale: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale: Offending option display_amp.grd
psconvert: Error: The file display_amp.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
grdmath: Syntax error: amp2.grd is not a number, operator or file name
grdmath: Syntax error: tmp.grd is not a number, operator or file name
grdmath: Syntax error: amp.grd is not a number, operator or file name
conv: File tmp2.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  tmp2.grd=bf 
grdimage: Error for input file: No such file (corr.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
psscale: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale: Offending option corr.grd
psconvert: Error: The file corr.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
grdmath: Syntax error: imagfilt.grd is not a number, operator or file name
grdimage: Error for input file: No such file (phase.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
psscale: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale: Offending option phase.grd
psconvert: Error: The file phase.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
phasefilt: File imagfilt.grd not found
[Session phasefilt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 error reading file imagfilt.grd 
grdinfo: Error for input file: No such file (mask.grd)
grdinfo: Syntax error: Must specify one or more input files
grdedit: Error for input file: No such file (filtphase.grd)
grdmath: Syntax error: filtphase.grd is not a number, operator or file name
grdimage: Error for input file: No such file (phasefilt.grd)
grdimage: Syntax error: Must specify one (or three) input file(s)
psscale: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale: Offending option phasefilt.grd
psconvert: Error: The file phasefilt.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
mv: cannot stat 'mask.grd': No such file or directory
grdmath: Syntax error: tmp.grd is not a number, operator or file name
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180417_ALL_F2.LED 
......master LED file S1_20180111_ALL_F2.LED 
.........aligned LED file S1_20180111_ALL_F2.LED 
reading topo topo_ra.grd
 xdim 25824, ydim 12192 
......master LED file S1_20180123_ALL_F2.LED 
.........aligned LED file S1_20180204_ALL_F2.LED 
......master LED file S1_20180123_ALL_F2.LED 
.........aligned LED file S1_20180123_ALL_F2.LED

**Comment by chintals** [comment]
@demark4 how many physical cores do you have on your machine?

Can you run the the command with 2 cores?
`intf_tops_parallel.csh intf.in batch_tops.config 2`

**Comment by demark4** [comment]
> @demark4 how many physical cores do you have on your machine?
> 
> Can you run the command with 2 cores? `intf_tops_parallel.csh intf.in batch_tops.config 2`

Hi @chintals 
40 cores and 64 GB RAM.
I ran the command with 2 cores. Not completed yet.

**Comment by chintals** [comment]
@demark4 
Do you see the completed interferograms folder in the F*/intf_all/ directory? Even while the parallel command is still running?

**Comment by Xiaohua-Eric-Xu** [comment]
I was suspecting the same thing as @chintals, until I saw these a few lines, which indicate there being some strange characters in the intf.in file. I noticed that these are sometimes hard to find. e.g.  https://github.com/gmtsar/gmtsar/issues/330
```
grep: ./raw/.PRM: No such file or directory
cp: cannot stat '../../raw/.PRM': No such file or directory
cp: cannot stat '.PRM': No such file or directory
```

**Comment by demark4** [comment]
hi @chintals @Xiaohua-Eric-Xu 
The command completed without errors with 2 cores. I'm doing the unwraping now.
Why does such an error occur even though it has 40 cores and 64 GB of RAM ?

**Comment by chintals** [comment]
hi @demark4 

I suspect that even with 40 cores and 64 GB RAM, your setup with HDD does not have enough throughput to simultaneously read/write large grd files using GMT library. I have noticed when GMT commands that output files typically fail during heavy IO operations (more parallel operations lead to more hard disk IO). 

You could test your system, by running 3 or 4 cores till the HDD cannot handle more data read/write.  Another issue is low swap space..

**Comment by demark4** [comment]
thank you so much @chintals
