### ISSUE TITLE
[Help]: GMT not properly installed and problem in generating corr_stack.grd

### ISSUE THREAD

**Issue by raviexplorer** [gmtsar/gmtsar#349]
I installed GMT but while typing "grdinfo" in terminal , it says command not found. 
But When I type "gmt" it works.
I need grdinfo to process certain images using GMTSAR . 
Can anyone help?

**Comment by raviexplorer** [comment]
When I try to create corr_stack.grd then I get errors. I am attaching error log for both methods
[error.txt](https://github.com/gmtsar/gmtsar/files/8936065/error.txt)

**Comment by dsandwell** [comment]
GMT uses the syntax

gmt grdinfo


> On Jun 19, 2022, at 10:32 AM, raviexplorer ***@***.***> wrote:
> 
> 
> I installed GMT but while typing "grdinfo" in terminal , it says command not found.
> But When I type "gmt" it works.
> I need grdinfo to process certain images using GMTSAR .
> Can anyone help?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037
