### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by raviexplorer** [gmtsar/gmtsar#350]
When I try to create corr_stack.grd then I get errors. I am attaching error log for both methods.
I have ubuntu 20.04
[error.txt](https://github.com/gmtsar/gmtsar/files/8938653/error.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Oops, seems your gmt could not recognize the grid files. I am not fully sure, but maybe they are generated under one netcdf/hdf5 version and now reading with another?
