### ISSUE TITLE
[Feature]: Restituted orbit auto download

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#351]
Is there any plan to automatically download Sentinel-1 Restituted Orbits automatically for missing POE files in acquisitions younger than 20 days?

**Comment by SteffanDavies** [comment]
The current Sentinel-1 recipe uses organize_files_tops_linux to prepare data and download orbits. Perhaps  download_sentinel_orbits[_linux].csh could be integrated in the previous script? This would resolve the restriction to using precise orbits when following the recipe.

**Comment by Xiaohua-Eric-Xu** [comment]
I think the same command used in that script has been implemented in to the organize_files scripts. In the newer version though (master or 6.2).

**Comment by mobigroup** [comment]
@SteffanDavies There is the related Python library and command-line tool to download all the orbits. Install it as
```
python3 -m pip install sentineleof
```
Optionally, you'd check it:
```
eio selfcheck
```
And just enter the command at any directory with your packed (zip files) or unpacked (.SAFE directories) scenes location to obtain the both kind of orbit files:
```
eof
```
