### ISSUE TITLE
[Help]: how to get land subsidence in mm/yr 

### ISSUE THREAD

**Issue by raviexplorer** [gmtsar/gmtsar#353]
I have processed sentinel 1 images and finally I have vel_ll.kml . How to i get land subsidence in mm/ yr?

**Comment by Xiaohua-Eric-Xu** [comment]
That should be produced by a grid from vel_ll.grd? And if your vel_ll.grd is projected from vel.grd that is produced from sbas, then it should be already in mm/yr.

**Comment by raviexplorer** [comment]
i can see color bar on the image. How can i know the mm/yr information?

**Comment by Xiaohua-Eric-Xu** [comment]
You could 1) plot or load data with GMT; or 2) load the grid into Matlab or Python and plot there; or 3) use other softwares like ncview.

**Comment by raviexplorer** [comment]
okay, how can I plot or load it with gmt ?

**Comment by Xiaohua-Eric-Xu** [comment]
https://docs.generic-mapping-tools.org/latest/grdimage.html
https://docs.generic-mapping-tools.org/latest/colorbar.html
https://docs.generic-mapping-tools.org/latest/grdtrack.html

**Comment by raviexplorer** [comment]
Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
Might be good to learn GMT. There are some recordings from last year here: https://www.unavco.org/event/2021-short-course-gmt-for-geodesy
