### ISSUE TITLE
sbas processing is failed to creat displacement and velocity map

### ISSUE THREAD

**Issue by taqidaqiq** [gmtsar/gmtsar#356]
The following is my script: 
sbas intf.tab scene.tab 188 57 3164 6766 -range 860629 -incidence 40 -wavelength 0.0554658 -smooth 5.0 -rms -dem
but after few minutes the processing is stoping and the following is error: 

taqi@taqi-VirtualBox:~/Documents/asce/sbas$ sbas intf.tab scene.tab 188 57 3164 6766 -range 860629 -incidence 40 -wavelength 0.0554658 -smooth 5.0 -rms -dem

compute RMS misfit
compute DEM error

setting smoothing to   5.000 
setting radar wavelength to   0.055 m 
setting radar incidence angle to  40.000 degree 
setting range to 860629.000 m 
Memory Allocation Successful...
read table file ...
number of SAR scenes is 57 
number of interferograms is 188 
read phase and correlation grids ...
Killed
taqi@taqi-VirtualBox:~/Documents/asce/sbas$

![image](https://user-images.githubusercontent.com/71912698/176381659-fa018b9a-b8f6-403f-bb75-55103b1889e4.png)

**Comment by taqidaqiq** [comment]
@Xiaohua-Eric-Xu 
please help me if you have any idea.

**Comment by dsandwell** [comment]
The program tried to allocate more memory than available in your computer.  You can try the -mmap option or reduce the size of the input grids.  When you run this program run the unix top command to monitor the use of the memory as well as the CPU usage.  The -mmap option uses the disk for memory so can be slow.

> On Jun 29, 2022, at 12:56 AM, taqidaqiq ***@***.***> wrote:
> 
> 
> @Xiaohua-Eric-Xu
> please help me if you have any idea.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by chintals** [comment]
If your area of interest is much smaller than the interferograms, you can use gmt grdcut to reduce the domain size of the unwrapped interferograms (and corr.grd) before sbas processing.

`gmt grdcut unwrap.grd -Rxmin/xmax/ymin/ymax -Gnew_unwrap.grd`

**Comment by taqidaqiq** [comment]
> The program tried to allocate more memory than available in your computer. You can try the -mmap option or reduce the size of the input grids. When you run this program run the unix top command to monitor the use of the memory as well as the CPU usage. The -mmap option uses the disk for memory so can be slow.
> On Jun 29, 2022, at 12:56 AM, taqidaqiq ***@***.***> wrote: @Xiaohua-Eric-Xu please help me if you have any idea. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.
> David T. Sandwell IGPP 0225 Scripps Inst. of Oceanography La Jolla, CA 92093-0225 Ph. 858 534-7109 Cell 858 663-9426 http://topex.ucsd.edu Express Mail Address: 8795 Biological Grade Room 1102 La Jolla, CA 92037

Thank you so much sir for your kind advice. 
I decreased the numbers of interferograms, so now it is working.

**Comment by taqidaqiq** [comment]
@chintals 
thank you for your advice as well.

**Comment by omarwater98** [comment]
> El siguiente es mi script: sbas intf.tab scene.tab 188 57 3164 6766 -range 860629 -incidence 40 -wavelength 0.0554658 -smooth 5.0 -rms -dem pero después de unos minutos el procesamiento se detiene y el siguiente es un error:
> 
> taqi@taqi-VirtualBox:~/Documentos/asce/sbas$ sbas intf.tab scene.tab 188 57 3164 6766 -rango 860629 -incidencia 40 -longitud de onda 0.0554658 -suave 5.0 -rms -dem
> 
> calcular RMS inadaptado calcular DEM error
> 
> ajustando el suavizado a 5.000 ajustando la longitud de onda del radar a 0.055 m ajustando el ángulo de incidencia del radar a 40.000 grados ajustando el rango a 860629.000 m Asignación de memoria exitosa... leer el archivo de la tabla... el número de escenas SAR es 57 el número de interferogramas es 188 leer cuadrículas de fase y correlación ... Mató a taqi@taqi-VirtualBox:~/Documents/asce/sbas$
> 
> ![imagen](https://user-images.githubusercontent.com/71912698/176381659-fa018b9a-b8f6-403f-bb75-55103b1889e4.png)

excelente pregunta, me paso lo mismo, intentare cortar los archivos unwrap.grd y corr.grd

**Comment by omarwater98** [comment]
> Si su área de interés es mucho más pequeña que los interferogramas, puede usar gmt grdcut para reducir el tamaño del dominio de los interferogramas no envueltos (y corr.grd) antes del procesamiento de sbas.
> 
> `gmt grdcut unwrap.grd -Rxmin/xmax/ymin/ymax -Gnew_unwrap.grd`

How to crop the area inside the interferogram if you don't know the space.

**Comment by omarwater98** [comment]
> El programa trató de asignar más memoria que la disponible en su computadora. Puede probar la opción -mmap o reducir el tamaño de las cuadrículas de entrada. Cuando ejecute este programa, ejecute el comando superior de Unix para monitorear el uso de la memoria y el uso de la CPU. La opción -mmap usa el disco como memoria, por lo que puede ser lenta.
> El 29 de junio de 2022 a las 00:56, taqidaqiq ***@***.***> escribió: @Xiaohua-Eric-Xu , por favor, ayúdenme si tienen alguna idea. — Responda a este correo electrónico directamente, véalo en GitHub o cancele la suscripción. Estás recibiendo esto porque estás suscrito a este hilo.
> David T. Sandwell IGPP 0225 Instituto Scripps. of Oceanography La Jolla, CA 92093-0225 Tel. 858 534-7109 Celular 858 663-9426 http://topex.ucsd.edu Dirección de correo urgente: 8795 Biological Grade Room 1102 La Jolla, CA 92037
i Have the same error and marks this:
![SBAS no funciona](https://user-images.githubusercontent.com/113547446/203185385-fd3df9b9-277e-4561-96f0-655083cf48dd.png)


compute RMS misfit
compute DEM error

setting smoothing to   5.000 
setting radar wavelength to   0.055 m 
setting radar incidence angle to  40.000 degree 
setting range to 901295.000 m 
number of SAR scenes is 22 
number of interferograms is 21 
 dimension don't match! ../merge/2014295_2015062/corr.grd 
Memory Allocation Successful...
read table file ...
read phase and correlation grids ...

**Comment by Xiaohua-Eric-Xu** [comment]
> How to crop the area inside the interferogram if you don't know the space.

You may 1) locate a point (long, lat, elevation) as a corner for cropping; 2) run `SAT_llt2rat` to find the corresponding range, azimuth; 3) repeat 1) for other corners and do the cropping with `gmt grdcut`.

**Comment by omarwater98** [comment]
> > How to crop the area inside the interferogram if you don't know the space.
> 
> You may 1) locate a point (long, lat, elevation) as a corner for cropping; 2) run `SAT_llt2rat` to find the corresponding range, azimuth; 3) repeat 1) for other corners and do the cropping with `gmt grdcut`.

Thanks by the way. Teacher
