### ISSUE TITLE
[Help]: CSV file

### ISSUE THREAD

**Issue by demark4** [gmtsar/gmtsar#357]
Hi @Xiaohua-Eric-Xu 
Can we save latitude/longitude and mean velocity values of SBAS results as csv file?

**Comment by chintals** [comment]
you can use the above gmt grd2xyz command to create vel.xyz file, and use data import in excel with space delimiter. The file size can be huge and could render excel unresponsive.

You can also create the csv file using python. An example is here https://github.com/gmtsar/gmtsar/issues/314#issuecomment-1130501243 and flatten the 2d array, and export using numpy csv or pandas csv command

**Comment by demark4** [comment]
Thank you so much @dsandwell @chintals

**Comment by demark4** [comment]
Why am I getting the following warnings ?

oos@oos:/media/oos/HDD3/SAR/F2/SBAS$ tcsh
oos:/media/oos/HDD3/SAR/F2/SBAS> ln -s ../topo/trans.dat 
oos:/media/oos/HDD3/SAR/F2/SBAS> ln -s ../intf_all/2018010_2018034/gauss_*
oos:/media/oos/HDD3/SAR/F2/SBAS> proj_ra2ll.csh trans.dat vel.grd vel_ll.grd
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [WARNING]: 1078086 unusable points were supplied; these will be ignored.
surface [WARNING]: You should have pre-processed the data with block-mean, -median, or -mode.
surface [WARNING]: Check that previous processing steps write results with enough decimals.
surface [WARNING]: Possibly some data were half-way between nodes and subject to IEEE 754 rounding.
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [WARNING]: 1078086 unusable points were supplied; these will be ignored.
surface [WARNING]: You should have pre-processed the data with block-mean, -median, or -mode.
surface [WARNING]: Check that previous processing steps write results with enough decimals.
surface [WARNING]: Possibly some data were half-way between nodes and subject to IEEE 754 rounding.
Sampling in geocoordinates with 50 meter pixels ...
oos:/media/oos/HDD3/SAR/F2/SBAS> gmt makecpt -Cjet -T1000/3200/100 -Z -D > vel_ll.cpt
oos:/media/oos/HDD3/SAR/F2/SBAS> grd2kml.csh vel_ll vel_ll.cpt
PSL: Colormap of 2 colors created
PSL: Image depth reduced to 1 bits
Make vel_ll.kml and vel_ll.png
gs -q -dNOPAUSE -dBATCH -dNOSAFER -dSCANCONVERTERTYPE=2 -dMaxBitmap=2147483647 -dUseFastColor=true -dGraphicsAlphaBits=2 -dTextAlphaBits=4 -sDEVICE=pngalpha  -g2420x2776 -r1800 -sOutputFile='vel_ll.png' './psconvert_3167d.eps'

**Comment by Xiaohua-Eric-Xu** [comment]
It's a new GMT "feature" I think. Doesn't affect the results or processing I believe.
