### ISSUE TITLE
[Help]: Fails in grdcut.

### ISSUE THREAD

**Issue by RenzoAnc** [gmtsar/gmtsar#358]
Hello everyone. I've running the p2p_S1_TOPS_Frame.csh to form an interferogram, but I'm having problems with landmask_ra.grd in merge part. Script runs well for all subfringes, but it fails when it executes landmask.csh in snaphu part (merge). I think the problem is grdcut (when I add region_cut in config.s1a.txt, script fails).
When I commented lines about grdmask in snaphu section, p2p_S1_TOPS_Frame.csh run well, but now I sometimes have problems in unwrapping phase.

When I use landmask_ra.grd:

![Error](https://user-images.githubusercontent.com/105986961/176479936-47b870b0-1bc9-4cf8-bfe6-db5b8efc5a3a.png)

When I comment lines about landmask_ra.grd, in unwrapping phase section:

![Snaphu_part](https://user-images.githubusercontent.com/105986961/176486030-5fb54886-cb36-4c9f-bf2f-dc3bbd41b1a4.png)

![Error_2](https://user-images.githubusercontent.com/105986961/176479969-db15e9d9-b75d-49a4-916c-2f30dc8960b4.png)

I used region_cut = 13000/20000/4000/7000.

![Area](https://user-images.githubusercontent.com/105986961/176479989-73c7a033-5be3-4342-a87e-e5dc088f2238.png)

I've read grdcut sometimes has problems because of a bug (https://githubhot.com/repo/gmtsar/gmtsar/issues/261). Should I update my GMTSAR?. 
I've installed GMTSAR with this command:

...
git clone --branch 6.0 https://github.com/gmtsar/gmtsar GMTSAR
...

OS: Ubuntu 20.04.4 LTS x86_64
Kernel: 5.13.0-51-generic
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz
Processor: min 2.8 max 4.7 GHz
Memory: 2403MiB / 7674MiB 

Configuration file: [config.s1a.txt](https://github.com/gmtsar/gmtsar/files/9012015/config.s1a.txt)
Result: [Results.txt](https://github.com/gmtsar/gmtsar/files/9012116/Results.txt)

Thanks in advance.

**Comment by Xiaohua-Eric-Xu** [comment]
I think your dem2topo_ra.csh got killed over the `gmt surface` step.  The newer version of GMTSAR has this fixed but not that I remember anything could cause this `Killed` over your terminal. Try `git switch 6.4` or `git switch master` and re-compile the code. Hopefully this helps.

**Comment by RenzoAnc** [comment]
> I think your dem2topo_ra.csh got killed over the `gmt surface` step. The newer version of GMTSAR has this fixed but not that I remember anything could cause this `Killed` over your terminal. Try `git switch 6.4` or `git switch master` and re-compile the code. Hopefully this helps.

Thank you for your reply, Xiaohua-Eric-Xu. I have a doubt about the update. 
I've read in previous issues update is done following these steps and executing these commands:

1.- Go to installation directory (e.g. /usr/local/GMTSAR)

2.- Execute these commands in Linux Terminal:

- git checkout 6.4 (or git switch 6.4)
- make spotless
- autoconf
- ./configure
- make 
- make install

Are they the correct steps?. I make this question because I don't know much about git commands. Thank you.

**Comment by Xiaohua-Eric-Xu** [comment]
Yes they are.

**Comment by RenzoAnc** [comment]
Thank you so much, professor Xiaohua-Eric-Xu.

**Comment by RenzoAnc** [comment]
Hello, professor @Xiaohua-Eric-Xu. I've just updated GMTSAR (git clone --branch 6.2 https://github.com/gmtsar/gmtsar GMTSAR) and compiled a script which form an interferogram of a subswath (see [Prueba_cont.txt](https://github.com/gmtsar/gmtsar/files/9042029/Prueba_cont.txt)). In the terminal, some "Warnings" appears which didn't appear in the old GMTSAR. Possibly GMT version is the problem because I was using GMTv. 5.4.5 with the old GMTSAR, so I had to update both GMTSAR and GMT (6.2.0).
I'll show the warnings and errors:
Warnings:
![Warning1](https://user-images.githubusercontent.com/105986961/177216272-a45b2a7f-6ef7-4390-867c-4ffc6a845323.png)
![Warning2](https://user-images.githubusercontent.com/105986961/177216278-c6f24aae-a876-4a17-871f-ffeb91f824b0.png)
![Warning3](https://user-images.githubusercontent.com/105986961/177216284-6b95bec2-27ab-4220-8fe4-32adc393dda2.png)

Errors:

![Error](https://user-images.githubusercontent.com/105986961/177216290-eb102b7f-7804-4591-8089-ee71599b5dc7.png)


The config.s1a.txt is: [config.s1a.txt](https://github.com/gmtsar/gmtsar/files/9042022/config.s1a.txt)


The results are: [Results.txt](https://github.com/gmtsar/gmtsar/files/9042024/Results.txt)

How can I see the GMTSAR version?, Can I see GMTSAR version with a linux command or in a file inside of GMTSAR folder?. To verify if there is a problem between GMTSAR version and GMT version. Regards.

**Comment by Xiaohua-Eric-Xu** [comment]
Seems you have GMT5 installed on your system. Are you able to update that to 6.0 or later as well?

**Comment by RenzoAnc** [comment]
Thank you for your reply, professor @Xiaohua-Eric-Xu. I've updated GMT 6.2.0. I think the problem is gmt-dcw because Ubuntu 20.04 LTS only allows to install gmt-dcw 1.1.4., but gmt sometimes requires a gmt-dcw specific version to works. For example, gmt-dcw  2.1.1 (available for Ubuntu 22.04) requires GMT 6.1.1 or later (page https://www.generic-mapping-tools.org/download/). I add images which prove gmt v. 6.2.0 is installed:


![gmt](https://user-images.githubusercontent.com/105986961/177217951-a5bac509-554b-4343-9047-018a69fd427c.png)
![grdinfo](https://user-images.githubusercontent.com/105986961/177217953-3b46060f-f08a-411e-96d7-9f9dd057ab7d.png)

Maybe  5.4.5 and 6.2.0 gmt packages are mixing, but I don't know how uninstall gmt. I've installed gmt manually:

- tar -xvf gmt-5.4.5-src.tar.gz (In this case, tar -xvf gmt-6.2.0-src.tar.gz)
-  cd gmt-6.2.0
- cp cmake/ConfigUserTemplate.cmake cmake/ConfigUser.cmake
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=/usr/local -
DCMAKE_BUILD_TYPE=RelWithDebInfo ..
- cmake ..
- make
- sudo make install

It's possible I didn’t uninstall version GMT 5.4.5 properly prior to installing version 6.2.0. I didn't eliminate gmt-5.4.5 to install gmt-6.2.0 because I don't know so much about Linux. I thought old files would be eliminated by new ones.

Regards.

**Comment by Xiaohua-Eric-Xu** [comment]
That's likely. You'll probably need to find the right path for gmt6 libs and put that to config.mk and run `make clean`, `make` and `make install`.

**Comment by RenzoAnc** [comment]
Hi, professor @Xiaohua-Eric-Xu. Thank you for your reply. Based on his recommendations, I tried to fix the problem compatibility between GMTSAR and GMT. Fortunately, it worked. So, I'm grateful to you. To make it, I had to install both GMTSAR and GMT again. Now, I don't have problems in intf.csh and filter.csh part. I'll show you the results.



![Superado1](https://user-images.githubusercontent.com/105986961/177415630-533146c2-e35d-4f8b-8f6f-3fdd740fe6b6.png)



Despite this result, I still have problems with "Warnings" messages. Moreover, I have an error in landmask.csh part (MAKE LANDMASK -- START).


![ErrorLM](https://user-images.githubusercontent.com/105986961/177415707-f086f9da-5ab7-4c98-a393-61028cbc611c.png)






I've been analysing what the problem is (about error), and I found the following command is "killed":


gmt gmtconvert llpra -bi5f -bo3f -o3,4,2 > rap


when proj_ll2ra.csh script runs. Because of the problem with this command, landmask_ra.grd isn't created. I think landmask.grd isn't the problem because it's created succesfully:


![landmask](https://user-images.githubusercontent.com/105986961/177416339-7c3627c4-b29d-4305-9abb-ef6b04c0d8cb.png)





Possibly "Warnings" are the problems because it appears when the following commands run (they're also in proj_ll2ra.csh script):

gmt surface llr `gmt gmtinfo llp -I0.08333333333 -bi3f` -bi3f -I.00083333333333 -T.50 -Gllr.grd $V
gmt surface lla `gmt gmtinfo llp -I0.08333333333 -bi3f` -bi3f -I.00083333333333 -T.50 -Glla.grd $V


This is the compiling result: [Results.txt](https://github.com/gmtsar/gmtsar/files/9049686/Results.txt). I hope these warnings don't affect the results. All "warnings" are in "results.txt" file. I'll be grateful if you can read this file.

This is the proj_ll2ra.csh: [proj_ll2ra.txt](https://github.com/gmtsar/gmtsar/files/9049746/proj_ll2ra.txt)


I had this error founded in landmask part with old GMTSAR too. That's the reason I updated GMTSAR. Unfortunately, it didn't work. What could be the problem?.

Thanks in advance.

**Comment by Xiaohua-Eric-Xu** [comment]
Just from the log, I think the error is from this line
`57 gmt gmtconvert llpra -bi5f -bo3f -o3,4,2 > rap`
However, I don't really understand what'll cause the program `Killed`. 
Could you 
1) modify proj_ll2ra.csh in your GMTSAR/bin directory to not remove ll* at the end.
2) run from proc_stage = 5 in your F1 directory.
3) check on the input file llpra (size, values etc). 
If you have this file, we can ask the GMT gurus for help here.

**Comment by chintals** [comment]
I suspect the llr.grd and lla.grd are fine (because they are derived from trans.dat file).  The issue could with grdtrack and generating llpr and llpra files.

After you generate landmask.grd, can you run this one command (in the directory where landmask.grd file is located)

`gmt grdedit landmask.grd -L+p`

And then run this command. 

`proj_ll2ra.csh trans.dat landmask.grd landmask_ra.grd`

**Comment by chintals** [comment]
@Xiaohua-Eric-Xu From what I saw in the https://github.com/gmtsar/gmtsar/files/9049686/Results.txt provided, the landmark range is -180~180, but the dem seems to be in the 0~360 range since the topo_ra.grd and trans.dat are generated using the dem.grd, I figured a quick test would be to change the range of landmask.grd to 0~360.

Ideally, I would suggest changing dem to -180~180 and then go through processing.

**Comment by chintals** [comment]
@RenzoAnc Glad it worked!

I believe the sample error is due to the GMT 6.2 upgrade, and it doesn't affect the processing.

**Comment by RenzoAnc** [comment]
> @RenzoAnc Glad it worked!
> 
> Just to clarify, if your dem.grd bounds was -R-75.37/-72.65/-13.5/-11.7 and If the landmask.csh was creating a landmask.grd with -R284.63/287.35/-13.5/-11.7 then the command to add the csh would be (no need for +p) to shift the landmask bounds. `gmt grdedit landmask.grd -L`
> 
> I believe the grd sample warnings is due to the GMT 6.2 upgrade, and it doesn't affect the processing.

Thanks a lot, @chintals.
