### ISSUE TITLE
[Help]: **Script "organize_files_tops_linux.csh" is not providing appropriate results**. the data directory named Fxxxx_Fxxxx created but containing single newly trimmed file in it. I am using Ubuntu 20.04 and latest GMTSAR version.

### ISSUE THREAD

**Issue by bhardwajalok** [gmtsar/gmtsar#359]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by bhardwajalok** [comment]
As i am using organize_files_tops_linux.csh with mode 2, the created Fxxxx_Fxxxx folder containing single .SAFE file. There were 5 scenes that i was using for trial run.

**Comment by Xiaohua-Eric-Xu** [comment]
Do you have a log file that you can send over? (terminal output)

**Comment by bhardwajalok** [comment]
[oft_mode1.log](https://github.com/gmtsar/gmtsar/files/9034148/oft_mode1.log)
[oft_mode2.log](https://github.com/gmtsar/gmtsar/files/9034149/oft_mode2.log)
these both files were created with mode1 and 2

**Comment by Xiaohua-Eric-Xu** [comment]
I see, this many need to 1) `make clean`, 2) add -fno-stack-protector to the cfalgs in config.mk, and then 3)`make` and `make install`
https://github.com/gmtsar/gmtsar/issues/12

**Comment by bhardwajalok** [comment]
As config.mk is in a zip file named "config.5ssl.gz", So, should i go for unzip it and add -fno-stack-protector to the cfalgs in config.mk? or anyother way to do it!

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure of "config.5ssl.gz". You should be able to find a config.mk file in your GMTSAR directory and edit it with any text editor.

**Comment by bhardwajalok** [comment]
[oft_mode1.log](https://github.com/gmtsar/gmtsar/files/9071244/oft_mode1.log)
[oft_mode2.log](https://github.com/gmtsar/gmtsar/files/9071246/oft_mode2.log)
Still same problem!

**Comment by Xiaohua-Eric-Xu** [comment]
Did you re-compile the code after changing config.mk? i.e. `make clean`, `make` and `make install`.

**Comment by bhardwajalok** [comment]
[pbt_mode2.log](https://github.com/gmtsar/gmtsar/files/9099155/pbt_mode2.log)
preproc_batch_tops.csh data.in dem.grd 2 &> pbt_mode2.log &
Results are not fine now with this script!
