### ISSUE TITLE
/bin/bash: line 1: download_sentinel_orbits.csh: command not found

### ISSUE THREAD

**Issue by zelalemshi** [gmtsar/gmtsar#360]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is, with what dataset, ...

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Note**
Feature requests usually mean writing codes/scripts, so expect this to be solved in the long-run. Meanwhile the issue will remain open until it is addressed one way or another.

**Comment by SteffanDavies** [comment]
Did you add GMTSAR and the bin folder to $PATH?
