### ISSUE TITLE
[Help]:  What are the SBAS measurementes in reference to?

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#361]
I have just completed a SBAS dataset and the output vel_ll.png is entirely blue.

The vel_ll.grd file has the following information:

```
vel_ll.grd: Title: z
vel_ll.grd: Command: xyz2grd llpb -R350.872222222/351.272222222/38.8458333333/39.0958333333 -I2s/1.5s -r -fg -Gvel_ll.grd -bi3f
vel_ll.grd: Remark: 
vel_ll.grd: Pixel node registration used [Geographic grid]
vel_ll.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
vel_ll.grd: x_min: 350.872222222 x_max: 351.272222222 x_inc: 0.000555555555556 (2 sec) name: longitude n_columns: 720
vel_ll.grd: y_min: 38.8458333333 y_max: 39.0958333333 y_inc: 0.000416666666667 name: latitude n_rows: 600
vel_ll.grd: z_min: -259.561920166 z_max: -102.120681763 name: z
vel_ll.grd: scale_factor: 1 add_offset: 0
vel_ll.grd: format: netCDF-4 chunk_size: 144,150 shuffle: on deflation_level: 3
```

Z values are between 259 and 102. This is an area with some significant subsidence but my questions are the following:

1. What is the reference of these values? Why is min and max not below and above zero respectively? Does GMTSAR use a mean of all points as reference?

2. Is it normal to have these kinds of values?

3. Is it possible to define a reference point (or area)?

**Comment by Xiaohua-Eric-Xu** [comment]
InSAR is usually considered as relative measurement mainly because the radar phase comes in wrapped solution and after unwrapping, it has integer number of 2pi ambiguities with the solution. Without further calibration, likely you'll end up with some velocity that's non-zero even over steady regions. A couple of ways that may help.
1) detrend your unwrapped phase (if your AOI is quite localized, this usually works OK)
2) pin to a point with grdcut, grdinfo and grdmath (this helps bring everything to that reference point, but atm noise may look funny)
3) pin to GNSS using the script in GMTSAR (I think this is the best but requires a good network of GNSS), https://github.com/gmtsar/2022-unavco-course-gmtsar/blob/main/Jupyter/gmtsar_correcting_intf_with_gps_example.ipynb
Hopefully these help a bit.
4)

**Comment by SteffanDavies** [comment]
I have some experience with StaMPS. By default StaMPS will use mean of all points when no reference is selected, thus the value of any single point will be in reference to the mean value of all points. It is also possible to select a point (or a number of points) by passing a centre and radius for circular selection or two coordinates for area / rectangular selection. 
Given this reasoning I am not aware of any case in StaMPS where the minimum and maximum value of average velocity for a given dataset can be anything but below and above 0 (mean) respectively.

**Comment by Xiaohua-Eric-Xu** [comment]
Taking out the mean value of all points is similar to pinning to an unknown position. If you do that, the results will for sure change. I think you could try pinning to a reference point and re-run sbas. Typically I would select a small box, run grdcut over that box, run grdinfo to get the mean value, then use grdmath to subtract that value from the unwrapped phase.

**Comment by SteffanDavies** [comment]
@Xiaohua-Eric-Xu I assume there won't be any difference in the results in pinning to a reference point before or after running SBAS, correct?

**Comment by Xiaohua-Eric-Xu** [comment]
It definitely affect time-series. For velocity, I am not so sure. A major concern is that without this type of reference, the radar phase may not close to zero (~0, not exact after filtering) if you sum around a triangular loop among your interferometric pairs. This'll introduce some jump-like features in the time-series (2n-pi). See fig 4 in https://doi.org/10.1109/TGRS.2019.2940207 . This effect may get beaten down if the 2pi ambiguities are random and you have redundant connections among your acquisitions.

**Comment by Gigi-gugu** [comment]
> Taking out the mean value of all points is similar to pinning to an unknown position. If you do that, the results will for sure change. I think you could try pinning to a reference point and re-run sbas. Typically I would select a small box, run grdcut over that box, run grdinfo to get the mean value, then use grdmath to subtract that value from the unwrapped phase.

Hello Professor Xu! 
My problem is the same as his, both are negative values. I would like to inquire about how to do grdcut, grdinfo, and grdmath specifically? Looking forward to your reply very much.

**Comment by Gigi-gugu** [comment]
Or how should I choose the box range?

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what you mean by box range? If you meant for pinning the time-series, a few pixels around might be good, e.g., 5.
