### ISSUE TITLE
[Help]: Strange results: Unwrapped Phase and Displacement map

### ISSUE THREAD

**Issue by RenzoAnc** [gmtsar/gmtsar#364]
Hello, everyone.

I'd like to ask you about a processing what I'm doing with DInSAR technique (Chile Earthquake, 8.3 Mw). The results (displacement map and unwrapped phase) what I got are strange. I've compared displacement map and unwrapped phase of F2 (complete subswath) and F3 (subset) subswaths, but the pixel values don't seem to be the same in the overlapping region between images.

I think problem is generated when snaphu.csh is executed (in the phase unwrapping) because the pixel values of the images don't concur when it's done (based on *.kml and *.pdf results). It can be seen observing the displacement and unwrapped values and the *.kml files on Google Earth.

**a) Filtered interferograms** (phasefilt.pdf , similar values in overlapping region.):

Smaller area:

![Phasefilt_pf](https://user-images.githubusercontent.com/105986961/178149342-11adf6ba-8223-4246-9222-a1bcd6062bcd.png)

Bigger area:

![Phasefilt_gf](https://user-images.githubusercontent.com/105986961/178149346-fab305c6-b917-4d87-b106-2dadb5ff85d4.png)

observed in Google Earth (phasefilt_mask_ll.kml):

![Phasefilt_pgGE](https://user-images.githubusercontent.com/105986961/178149499-53d4c646-b754-479f-8102-2c99283fee7a.png)

**b) Unwrapped Phases** (unwrap.pdf, F2 and F3, differente values in overlapping region.):
Smaller area:

![UP_pf](https://user-images.githubusercontent.com/105986961/178150981-adc8f093-e519-49f5-aa0e-99f800da5e1a.png)

Bigger area:

![UP_gf](https://user-images.githubusercontent.com/105986961/178151041-24e84450-8c7b-44b0-85ae-162b23cda461.png)

observed in Google Earth (unwrap_mask_ll.kml):

![UP_pgGE](https://user-images.githubusercontent.com/105986961/178151094-1b8b36d7-3536-44fa-9b64-0a4d009c29fb.png)

In the overlapping region, the smaller area (F3, subset) has green and blue colors, while bigger area has a red color. They represent different values.
Unwrapped phase values:
Green and blue: 0 - 50 (based on unwrapped phase values of F3 subswath [smaller area])
Red: ~ 150 (based on  unwrapped phase values of F2 subswath [bigger area])

**c) Displacement maps** (los.pdf, differente values in overlapping region.)

Smaller area:

![LOS_pf](https://user-images.githubusercontent.com/105986961/178151153-e9d84c92-e91c-4df2-98e5-17fbe672d74c.png)

Bigger area:

![LOS_gf](https://user-images.githubusercontent.com/105986961/178151160-db778443-503d-4361-9bd8-5cbe63627e25.png)

observed in Google Earth (los_ll.kml):

![MD_pgGE](https://user-images.githubusercontent.com/105986961/178151242-eba8b906-d7d2-4e2d-847e-7df024064610.png)

In the overlapping region, the smaller area (F3, subset) has a red color, while bigger area has a blue color. They represent different values.
Displacement values:

Red: ~ -200 mm (subsidence in LOS direction, based on displacement values  of F3 subswath [smaller area])
Blue: ~ -600 mm (subsidence in LOS direction, based on displacement values of F2 subswath [bigger area])

What could be the problem?.

Regards.

**Comment by Xiaohua-Eric-Xu** [comment]
A couple of things to notice here:
1) you need to merge before doing phase unwrapping. Try p2p_S1_TOPS_Frame.csh for frame-wise processing.
2) the discontinuities are from real earthquake deformation (azimuthal motion that caused mis-registration). If you really don't like it, try mode 2 for a interpolated ESD (BESD) as correction.

**Comment by RenzoAnc** [comment]
Hello, professor @Xiaohua-Eric-Xu. Thanks a lot for your reply. Following your recommendations, I've applied ESD and got a better interferogram:

![PhasefiltESD](https://user-images.githubusercontent.com/105986961/178616977-da396adb-5a34-400c-a051-8cccf17e75b3.png)

Regarding the subswaths merge (p2p_S1_TOPS_Frame.csh), I'm not sure if it's possible to do with my computer because it only has 8 GB (RAM). It failed in "phase unwrapping" section.

I have other questions, ¿is it possible to apply SBAS technique with 8 GB memory? and ¿how could I get the deformation value of each pixel (for InSAR results, p2p_S1_TOPS_Frame.csh)?. I mean, is there a way to get these information: lat, lon and deformation (in each "los.pdf" file pixel)?. Thanks in advance.

**Comment by Xiaohua-Eric-Xu** [comment]
Great, but do note that you have some azimuthal motion accounted for during the processing.

I think it is doable if you run things sequentially (mode 0). 

I do not recommend so though it is doable with the -mmap option in sbas.

**Comment by Xiaohua-Eric-Xu** [comment]
@RenzoAnc not really. the mmap function in sbas and sbas_parallel is implemented to overcome memory usage problems. e.g. one has fast disk but not enough memory to read in all the grids for calculation using sbas. There is a extract_one_time_series.csh script I think that'll get solution from a pixel (column).

**Comment by RenzoAnc** [comment]
Thank you, professor @Xiaohua-Eric-Xu . I'll keep it in mind.
