### ISSUE TITLE
atm[ni] parameter [Help]: SBAS Script 

### ISSUE THREAD

**Issue by KumarKrishan** [gmtsar/gmtsar#366]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by KumarKrishan** [comment]
@ericlindsey if i want to apply some parameter with atm[ni], Define the criteria to use it!
Usage: sbas intf.tab scene.tab N S xdim ydim [-atm ni] [-smooth sf]
[-wavelength wl] [-incidence inc] [-range -rng] [-rms] [-dem]

**Comment by ericlindsey** [comment]
Hi @KumarKrishan , the [ni] parameter refers to the number of interferograms to use in the atmospheric correction. Check out this paper that describes the method - https://sioviz.ucsd.edu/~fialko/papers/Tymofyeyeva_JGR15.pdf. I believe the parameter [ni] is equal to the value N in figure 1 of this paper.

**Comment by Xiaohua-Eric-Xu** [comment]
I would usually use a number ranging from 3 to 5. More is better but will cost longer.

**Comment by KumarKrishan** [comment]
Thank you! @ericlindsey @Xiaohua-Eric-Xu

**Comment by Gigi-gugu** [comment]
> I would usually use a number ranging from 3 to 5. More is better but will cost longer.

What are the main functions of atm and smooth? I want to know the basis for setting 3 to 5? Could you explain it to me? thank you.

**Comment by Xiaohua-Eric-Xu** [comment]
Check out this paper 
Tymofyeyeva, E., & Fialko, Y. (2015). Mitigation of atmospheric phase delays in InSAR data, with application to the eastern California shear zone. Journal of Geophysical Research: Solid Earth, 120(8), 5952-5963.
There is an exponential decay on smoothness set in the program suggested by Fialko that may take in more variations to the time-series other than just assuming a linear initial estimate. But if you set the iterations to too large of a number, it may end up leaking too much to the initial estimate thus atm correction won't work properly.

**Comment by Gigi-gugu** [comment]
Thank you.

**Comment by raviexplorer** [comment]
> I would usually use a number ranging from 3 to 5. More is better but will cost longer.

How much longer it takes? I have 563 interferograms with dimension 3050 x 3100 . I have 65gb of RAM. The sbas process is running for more than 15 hours. I have given smooth value 5.0

**Comment by Xiaohua-Eric-Xu** [comment]
Each iteration takes longer linearly I think.

**Comment by omarwater98** [comment]
in the command of  c. Post-SBAS Results: Projecting into Latitude/Longitude

on the part 

gmt grd2cpt vel_ll.grd -T= -Z -Cjet > vel_ll.cpt
grd2kml.csh vel_ll vel_ll.cpt

throws the error 

Z-slice with dz=0 

how can i correct that?

**Comment by omarwater98** [comment]
![Screenshot from 2022-09-26 14-06-38](https://user-images.githubusercontent.com/113547446/192381359-955dc21f-b668-4380-8a71-e59a347b256c.png)
only has z elevation

**Comment by Xiaohua-Eric-Xu** [comment]
I think the values are all NaNs. Did you unwrap with a high coherence threshold or your area has strong decorrelation?

**Comment by omarwater98** [comment]
yes i unwrap with good coherence, but what is decorrelation exactly ?

![Phase](https://user-images.githubusercontent.com/113547446/192568268-6d48e61c-c63d-438f-aca5-e0a5ed13bd46.png)
these are my unwrapping phase, two of my images looks wierd

**Comment by omarwater98** [comment]
![Baseline](https://user-images.githubusercontent.com/113547446/192582277-445fb125-7725-493c-bf73-4f6f7f7e76de.png)
 
This is my Baseline.ps, i used 1500 day and 125 m of baseline

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, the phase unwrapping looks problematic, but as long as you have solutions everywhere, sbas should give you something. 

Decorrelation means the radar signals of the same pixel does not look like before and could not properly interfere with previous observations. 

I am not exactly sure what's the problem. You'll have to provide more details on what you did, with specific commands and their corresponding log files. Could it be that you selected a small dem.grd that does not fully cover your data?

**Comment by omarwater98** [comment]
yes, my dem.grd is very small, should it be the size of the whole image?
![recorte](https://user-images.githubusercontent.com/113547446/192653961-7c5627f3-ed0f-4da0-a963-850382f83c5e.png)
the red box is the downloaded image

also, in the part where the intf.in was created, I deleted many pairs thinking that only the interferograms that had the master image could be generated

**Comment by Xiaohua-Eric-Xu** [comment]
Seems your dem.grd does not cover second subswath anyways, so why bother processing it?

p.s. I don't think you need to do landmasking as there's no real water bodies in your area.

It says rank is zero so probably something's incorrect with your scene.tab and intf.tab. Mind share them?

**Comment by omarwater98** [comment]
I deleted everything and I'm doing it again

**Comment by omarwater98** [comment]
hi @Xiaohua-Eric-Xu 

p.s. I don't think you need to do landmasking as there's no real water bodies in your area.

Ok, but how could i use the 

#!/bin/csh -f
intflist contains a list of all date1_date2

directories.
cd $1
ln -s ../landmask_ra.grd .
snaphu_interp.csh 0.01 40
cd ..

if i dont have an landmask_ra.grd

and, if i have only F1 swath i could not do the merge so unwrap in the F1/intf_all directory?

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, run the unwrap_parallel.csh script in your F1/intf_all directory and comment out this line below with a #, i.e.
```
# ln -s ../landmask_ra.grd .
```

**Comment by omarwater98** [comment]
![unwrap](https://user-images.githubusercontent.com/113547446/194180017-b67e2f25-5507-4777-a88c-36d0962c0853.png)
 Just like this?

**Comment by Xiaohua-Eric-Xu** [comment]
Hmm, seems your unwrap_parallel.csh could not find the unwrap_intf.csh in the current directory. Could it be that ./ is not in your $PATH? either add that or change unwrap_intf.csh to ./unwrap_intf.csh in the unwrap_parallel.csh script.

**Comment by omarwater98** [comment]
![unwrap_intf](https://user-images.githubusercontent.com/113547446/194441078-28c13e77-52e0-4233-bb08-059a9325cce6.png)

i dont know how this could work but makes me all the unwrappings one by one, 12 interferograms in less of an hour.

later of that i could run 

iii. prep_sbas.csh intf.in baseline_table.dat ../intf_all unwrap.grd corr.grd

![prepr SABAS](https://user-images.githubusercontent.com/113547446/194441482-5cea4716-c694-4bbf-81c3-8ba85e853e60.png)

b. RUN SBAS

i.  sbas intf.tab scene.tab 194 34 4612 3300 -range 888122 -incidence 40 -wavelength 0.0554658 -smooth 5.0 -rms -dem &> sbas.log &

but the program did not create me vel_ll.grd

**Comment by Xiaohua-Eric-Xu** [comment]
vel_ll.grd feels like a geocoded velocity grid. Did it give you a vel.grd and a bunch of disp*.grd-s?

What's in your sbas.log?

**Comment by omarwater98** [comment]
> vel_ll.grd feels like a geocoded velocity grid. Did it give you a vel.grd and a bunch of disp*.grd-s?
> 
> What's in your sbas.log?

Yes i have the vel.grd and disp*.grd but for the command:
proj_ra2ll.csh trans.dat vel.grd vel.ll.grd 
It have missing vel.ll.grd 
![16651809195062227293885654828896](https://user-images.githubusercontent.com/113547446/194670078-548317b4-de71-49a3-8f88-c918f9631785.jpg)
This is my sbas.log

**Comment by Xiaohua-Eric-Xu** [comment]
The log looks good to me! 

What's the output after you ran `proj_ra2ll.csh trans.dat vel.grd vel.ll.grd`? i.e. terminal output.

**Comment by omarwater98** [comment]
![Uploading 16651813084972986039504846383139.jpg…]()

**Comment by omarwater98** [comment]
> The log looks good to me!
> 
> What's the output after you ran `proj_ra2ll.csh trans.dat vel.grd vel.ll.grd`? i.e. terminal output.
Only
Sampling in geocoordinates with 50 meters pixels ...

**Comment by Xiaohua-Eric-Xu** [comment]
Hmm, strange. Could you delete the two files called raln.grd and ralt.grd and then re-run the command?

**Comment by omarwater98** [comment]
Sure, the command sbas right?

**Comment by Xiaohua-Eric-Xu** [comment]
No, the proj_ra2ll.csh command.

**Comment by omarwater98** [comment]
![16651819877625547011343353848735](https://user-images.githubusercontent.com/113547446/194671513-0c9f7b2b-5e96-47a8-8b92-7a85ca5091ea.jpg)


> No, the proj_ra2ll.csh command.

Its the same 
Maybe is the cause doesnt exist vel_ll.grd ?

**Comment by Xiaohua-Eric-Xu** [comment]
what's in your directory? are you running this in the sbas directory?

**Comment by omarwater98** [comment]
No im runing in the intf_all directory



> what's in your directory? are you running this in the sbas directory?

![16651822528667106675126153515564](https://user-images.githubusercontent.com/113547446/194671806-13de91ef-fb3d-46cc-a66e-f2f564c29b46.jpg)
![Uploading 16651822780127602257113027634924.jpg…]()

**Comment by omarwater98** [comment]
Bro a jus have to seen the vel_ll.grd

**Comment by omarwater98** [comment]
I swear it just work what you say
