### ISSUE TITLE
S1A problm error -  could not open file S1_20200616_150043_F1.PRM 

### ISSUE THREAD

**Issue by mahmudku** [gmtsar/gmtsar#37]

**Comment by Xiaohua-Eric-Xu** [comment]
You need to attach a log or describe what you did, so we know what happened. The error you see may not be the first error that broke your processing.

**Comment by mahmudku** [comment]
> You need to attach a log or describe what you did, so we know what happened. The error you see may not be the first error that broke your processing.

Dear Eric,
It seems that I have problem with downloading orbit files. I just realized some times there are more than one precise orbit file available. now its on progress. it seems this time works
