### ISSUE TITLE
[Help]: How to improve the postseismic deformation based on SBAS

### ISSUE THREAD

**Issue by Xiongwei789** [gmtsar/gmtsar#371]
Hello everyone,
When I use SBAS to obtain postseismic deformation associated with 2022 Menyuan Mw6.6  earthquake (20220108).
Data: Sentinel 1( ascending : 20220110 - 20220615; descending: 20220110 - 20220615)
We first used all the images and found that the interference is affected by temperature after May. Therefore, we used the images before 28th April. We followed the sentinel_time_series_4, eliminated the tropospheric delay with GACOS and detrended with GMT. However, we didn't find obvious postseismic deformation (See figure below). I wanted  to know what I can do to improve my results.
Ascending : 20220110 - 20220122
_sbas intf.tab scene.tab 16 9 $xn $yn -wavelength 0.0554658 -smooth 5.0 -range 920051.2865649252 -incidence 37 -rms -dem -atm 3_
![InSAR](https://user-images.githubusercontent.com/92964720/178958616-69e61e4e-f105-44cc-a862-0332b3e74f07.png)
Descending: 20220110 - 20220122, 20220110 - 20220416, rms
_sbas intf.tab scene.tab 38 13  3250 2500  -wavelength 0.0554658 -smooth 5.0 -range 832839.7402076268 -incidence 41 -rms -dem -atm 3_
![InSAR](https://user-images.githubusercontent.com/92964720/178959314-2fbc9066-b6d8-42f0-9944-627373ea67ca.png)

**Comment by Xiaohua-Eric-Xu** [comment]
A couple of things that may help.
1) mask out the target (deforming) area and run elevation dependent correction (remove a trend as well).
2) turn off the atm correction as a) your time-series is short, and b) the deformation could be very non-linear.
3) use a smaller smoothness such as 1.0.

**Comment by Xiongwei789** [comment]
Thank you for your reply,
I didn't find examples about the first suggestion. Can you tell me how to achieve it ?
Thanks again

**Comment by Xiaohua-Eric-Xu** [comment]
1) draw a polygon on Google earth to cover your deformation area, save to kml format. 
2) use `gmt kml2gmt` to convert to text format
3) use `gmt grdmask` to create a mask.
4) apply the mask to your grids and then fit the remaining grid to topography (linear).
5) estimate the topographically correlated signal using the fitting parameter and remove it from your grid.

**Comment by Xiongwei789** [comment]
Thanks for your detailed explain,
This is difficult for me. Are there relevant examples and codes for Step 4 and 5 here for reference?

**Comment by Xiaohua-Eric-Xu** [comment]
https://github.com/gmtsar/gmtsar/issues/98

**Comment by Xiongwei789** [comment]
> #98

I have tired it with Python. But the value of model is very small.  The simple code is as follows:
import numpy as np
_# I transformed the 'unwrap.grd' file to xyz file with 'gmt grd2xyz' 
# and obtained the corresponding elevation with 'gmt grdtrack'.
# g.txt includes three columns, x, y,(coordinates of the pixels) and h (elevation) 
G = np.loadtxt('g.txt')
x=G[:,0]
y=G[:,1]
h=G[:,2]
# p :the unwrapped phase 
phi=np.loadtxt('p.txt')
mm=np.linalg.pinv(G)*phi
a=mm[0]
b=mm[1]
c=mm[2]
d=mm[3]
model=a*x+b*y+c*h+d
np.savetxt('model.txt',model,fmt='%0.8f')_

**Comment by Xiongwei789** [comment]
> #98

I have tired it with Python. But the value of model is very small. The simple code is as follows:
import numpy as np
# I transformed the 'unwrap.grd' file to xyz file with 'gmt grd2xyz'
#and obtained the corresponding elevation with 'gmt grdtrack'.
#g.txt includes three columns, x, y,(coordinates of the pixels) and h (elevation)

G = np.loadtxt('g.txt')
x=G[:,0]
y=G[:,1]
h=G[:,2]
# p :the unwrapped phase

phi=np.loadtxt('p.txt')
mm=np.linalg.pinv(G)phi
a=mm[0]
b=mm[1]
c=mm[2]
d=mm[3]
model=ax+by+ch+d
np.savetxt('model.txt',model,fmt='%0.8f')

**Comment by Xiongwei789** [comment]
> #98
I have tired it with Python. But the value of model is very small. The simple code is as follows:
import numpy as np
  # I transformed the 'unwrap.grd' file to xyz file with 'gmt grd2xyz'
  #and obtained the corresponding elevation with 'gmt grdtrack'.
  #g.txt includes three columns, x, y,(coordinates of the pixels) and h (elevation)
G = np.loadtxt('g.txt')
x=G[:,0]
y=G[:,1]
h=G[:,2]
   #p :the unwrapped phase
phi=np.loadtxt('p.txt')
mm=np.linalg.pinv(G)phi
a=mm[0]
b=mm[1]
c=mm[2]
d=mm[3]
model=ax+by+ch+d
np.savetxt('model.txt',model,fmt='%0.8f')

**Comment by Xiongwei789** [comment]
> #98

  I have tried it with Python. But the value of the model is very small. The simple code is as follows:
  I transformed the 'unwrap.grd' file to xyz file with 'gmt grd2xyz' and obtained the corresponding elevation with 'gmt grdtrack'. g.txt    includes three columns, x, y,(coordinates of the pixels) and h (elevation)
G = np.loadtxt('g.txt')
x=G[:,0]
y=G[:,1]
h=G[:,2]
#p :the unwrapped phase
phi=np.loadtxt('p.txt')
mm=np.linalg.pinv(G)phi
a=mm[0]
b=mm[1]
c=mm[2]
d=mm[3]
model=ax+by+ch+d
np.savetxt('model.txt',model,fmt='%0.8f')

**Comment by Xiaohua-Eric-Xu** [comment]
> model=ax+by+ch+d

I am not a Python expert, but you don't need `*` to do multiplication? Also, the script is just for an idea, not in the sense it'll work perfectly. The last line is incorrect for sure as it should have more terms `model=P(1)*dem.*x+P(2)*dem.*y+P(3)*dem+P(4)+P(5)*xx+P(6)*yy`

**Comment by Xiaohua-Eric-Xu** [comment]
I guess the questions should be where is the column of 1-s?

**Comment by Xiongwei789** [comment]
> I guess the questions should be where is the column of 1-s?
I don't know what does the column of 1-s mean?

**Comment by Xiaohua-Eric-Xu** [comment]
> The G matrix contains only four columns, which are x,y,h,1.

You mentioned you have four columns in G, but the program you sent has three.

> G = np.loadtxt('g.txt')
> x=G[:,0]
> y=G[:,1]
> h=G[:,2]

**Comment by Xiongwei789** [comment]
> > The G matrix contains only four columns, which are x,y,h,1.
> 
> You mentioned you have four columns in G, but the program you sent has three.
> 
> > G = np.loadtxt('g.txt')
> > x=G[:,0]
> > y=G[:,1]
> > h=G[:,2]

I added the fourth column　to the G matrix with 'awk'.   
The following command just reads the information in the G matrix．
> > x=G[:,0]
> > y=G[:,1]
> > h=G[:,2]

**Comment by Xiaohua-Eric-Xu** [comment]
If everything's correct, then it may indicate your results have not much elevation dependency.

**Comment by Xiongwei789** [comment]
> If everything's correct, then it may indicate your results have not much elevation dependency.
Thank you for your reply. I will check it again.

**Comment by Xiaohua-Eric-Xu** [comment]
Also, post-seismic deformation sometimes may not be very significant or even detectable, especially for smaller size earthquakes, such as in this paper. https://www.sciencedirect.com/science/article/pii/S0273117721002258

**Comment by Xiongwei789** [comment]
> Also, post-seismic deformation sometimes may not be very significant or even detectable, especially for smaller size earthquakes, such as in this paper. https://www.sciencedirect.com/science/article/pii/S0273117721002258

Yes, I also read this article. But the postseismic deformation associated with the 2022 Ms6.9 Ｍenyuan earthquake should be more obvious.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Could you explain the nature of the "elevation dependent correction"? Is it related to atmospheric flows determined by a relief? I'm testing different ways to detect and exclude too noisy images (vs your approach to correct them using linear deformation model).

**Comment by Xiaohua-Eric-Xu** [comment]
Likely it is layered water vapor at near surface such it creates elevation dependent phase. The atmospheric noise are composed of two parts generally, a stratified component (related to topography) and a turbulent component (red spectrum). There are folks who use GNSS wet delay to estimate such components.

**Comment by mobigroup** [comment]
Ah, thanks, these are two independent factors, understand now. And for the turbulent component we can use just gaussian filtering to drop the long-wavelength spectrum components I suppose. As I see in estimate_ionospheric_phase.csh script the related filter wavelength is 20 km but I often see much smaller artefacts, for the example GMTSAR S1A_Stack_CPGF_T173 test set below. Does it mean the stripes are related to the DEM-dependent water vapor but not the turbulence?

![Unknown](https://user-images.githubusercontent.com/7342379/184221632-1de5b9da-1b3a-4edb-8a9d-482ccdca6ffa.png)

**Comment by Xiaohua-Eric-Xu** [comment]
The 20km filter is actually an arbitrary one to smooth out the ionospheric phase as usually it is smooth and with longer wavelength. One could however, tune the factor to achieve the correction they want. The one you saw are tropospheric artifact which is different from ionospheric phase. It has components over all wavelengths though the spectrum has larger components at longer wavelengths too. 

Specifically the strips you see are likely atmospheric turbulence triggered when the atmospheric currents hit elevation and form gravity waves. Here's some literature https://www.weather.gov/source/zhu/ZHU_Training_Page/Miscellaneous/gravity_wave/gravity_wave.html

**Comment by mobigroup** [comment]
Great, this is a 3rd factor :) Of course we can't remove the narrow stripes by gaussian filter 20+ km.
Please suggest how do you see "tune the factor to achieve the correction they want"? What is the criteria to select the right cut-off wavelength? It'd be insightful to analyze spatial spectrum of the interferograms but I didn't see a good explanation how to detect different atmospheric produced effects on the spectrum. Maybe do you have some thoughts and publications about it? For now, I use SBAS trigrams to estimate uncertainties and to found unreasonably hight correlation (when an image is correlated to DEM all the interferograms with this image will be overcorrelated). Also, it looks promising to estimate a fractality dimention because it's constant for a selected area and clouds distort it. By the way, you use mean value to detrend the results (1st moment) and gaussian filter to denoise red noise (2nd moment) and a fractality estimation is based on the 3rd moment (and detects non-gaussianity). Well, there are a lot of technical ways to exclude affected images. But that's looks more as art how to correct the images to produce some kind of "true enough" results and it'd be nice if you can share some practical cases.

**Comment by Xiaohua-Eric-Xu** [comment]
Gomba, G., Parizzi, A., De Zan, F., Eineder, M., & Bamler, R. (2015). Toward operational compensation of ionospheric effects in SAR interferograms: The split-spectrum method. IEEE Transactions on Geoscience and Remote Sensing, 54(3), 1446-1461.
This paper has an example of over-filtered, under-filtered examples. Generally this is an arbitrary number to set. 

As for topographically correlated results, one case I can think of is that if you have a large deformation area in your region (e.g. subsidence in central valley or earthquake), you'll need to exclude it before fitting things to topography. Otherwise, you'll get over-fitting or biased fitting.

And indeed it's hard to know whether the correction is working functionally without knowing the ground truth. You'll need other sources as a reference (such as GPS, or other ground measurement).

**Comment by mobigroup** [comment]
Thanks, I'm already checking the same case:
![Unknown](https://user-images.githubusercontent.com/7342379/184470939-9795f52f-4eba-4156-a365-78fe2c5bcf5a.png)

Correlation to DEM is ~15% and it's unchanged when the blue area removed. And for the example dataset Stack_CPGF_T173 we have the minimal correlation ~10%. For me it looks as a remainder from a topography removing step for interferogram processing rather than the atmosphere effect. Do you have some thoughts maybe?

Unfortunately, ground truth is unavailable everywhere when I have some interest :) I'm looking for non-linear deformations for natural resources exploration in mainly wild areas.

**Comment by Xiaohua-Eric-Xu** [comment]
Maybe filter the DEM to the same wavelength of your interferogram? 

I am not sure how much this'll help though. If you have a sharp DEM but filtered interferogram, it may actually insert some sharp features as an under-fit.

**Comment by mobigroup** [comment]
I see some improvement by removing also topography multiplied by coordinates as you suggested in the other ticket. The highlighted areas (brown on top and blue at bottom in radar coordinates) can be detrended as (y * topo) component. And that’s  correct to have less movements far away of an epicenter.
![3B98C1D4-3360-4867-ACB5-7FE813DE5828](https://user-images.githubusercontent.com/7342379/184857135-721b5e9c-e1c2-47f1-bbf8-57b63156895a.jpeg)

**Comment by mobigroup** [comment]
> Maybe filter the DEM to the same wavelength of your interferogram?

Aha, that’s an interesting point. By my experience additive white noise can improve regression accuracy (using as analytical as iteration solutions). At the same time, some kind of noise can be bad for any solution. I think we don’t need to care about the interferogram filter wavelength but we’d decimate topo_ra grid and apply gaussian filter using sigma equals to 1 or 2 pixels. I use this technique for all the topography related operations.

**Comment by mobigroup** [comment]
@esrivas17 you could easily check the different combination using PyGMTSAR detrending, see https://github.com/mobigroup/gmtsar/blob/5bbe897efde21cbf591cd132a894633862216bb0/pygmtsar/pygmtsar/SBAS_detrend.py#L132
Define your combination instead of this line “np.column_stack([zys, zxs, ys, xs, zs])” and compare the results. For my tests, this is enough and higher degrees and their combinations are useless. In case you need more filtering just apply Gaussian filter.

**Comment by Xiaohua-Eric-Xu** [comment]
> Hi Eric... One question about the model. Since this comes from the model posted here: #98 Taking into account the model you mentioned: _ax + by + cxH + dyH + eH + f_, where H is the heigh/dem/topography then the design matrix should be A = [x, y, xH, yH, H, ones], and we get 6 coefficients. What could you comment about different models? Do all depend on my data? I would need to check the results to choose the correct model for my case? models like: _ax + by + cxy + (dx + ey + fxy +g)H + h_, where H is the topography and there are simpler models like: Δϕtropo = KΔϕh + Δϕ0; this comes from: 2015, D.P.S. Bekaert, R.J. Walters, T.J. Wright, A.J. Hooper, D.J. Parker, Statistical comparison of InSAR tropospheric correction techniques. How to asses their effectiveness?

This is a good question. Honestly I am not sure which model is the best. It might be useful to check the correlation coefficient with topography after removal. For a small region, usually this type of assumption does not matter as much, but when it comes to a very large area, things may become challenging, as you could get water vapor from a variety of sources. One example is in Baja California, where on the west side it has effects from the Pacific but to the east it is the Gulf.  There are studies that use other methods like K-means to cluster these coefficients and divide the region to sub-regions for a fit to topography. Hope this helps.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu I remember some papers where the 3rd degree of topography fit, but it doesn’t work for me anywhere. Tiling (dividing into sub-regions) works better when we have some overlapping, similar to SNAPHU unwrapping. Maybe do you have some references? Would be interesting to check for the details.

**Comment by Xiaohua-Eric-Xu** [comment]
This is a pretty interesting paper on clustered coefficients: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9130090. 
Original dependency is here: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2008GL033659
An early assessment on InSAR noise (mostly atmospheric I think): https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2004GC000841
Another assessment paper: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2002JB001781
GACOS method is here: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2017JB015305
