### ISSUE TITLE
[Help]: How to concatenate three and more frames

### ISSUE THREAD

**Issue by Twcumtb** [gmtsar/gmtsar#375]
Hi Xiaohua,
  My area of interest covers three Sentinel-1 frames but currently the script create_frame_tops.csh only for two frames. How can I concatenate more frames to cover a larger area?

**Comment by Xiaohua-Eric-Xu** [comment]
Just add more to your input file list. It should be able to handle multiple frames but do note TIFF format could only generate files <4GB. Less than 30 bursts should be safe. 

Also you don't have to stay with a single frame for processing the data stack-wise. preproc_batch_tops.csh can handle multiple frames as well.
