### ISSUE TITLE
[Help]:correct_insar_with_gnss.csh error

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#377]
Hi Xiaohua,
**may because:I did gmt grdresample?**

**code :**
correct_insar_with_gnss.csh S1_20170503_ALL_F1.PRM unwrap_fill2_GACOS_detrended.grd gnss_los.rad 40000
correct_insar_with_gnss.csh supermaster.PRM unwrap_fill2_GACOS_detrended.grd gnss_los.rad 40000
**output:**
correct_insar_with_gnss.csh
Preparing grid characteristics...
Computing the correction grid...
Elapsed time 00:02:31.220 | (grdfilter) | 
Applying Gaussian filter to correction grid...
...this may take ~1 minute...
Elapsed time 00:00:00.070 | (grdfilter) | 
Correcting the interferogram...
grdmath: grid files not of same size!
Something went wrong -- intf not corrected 

**gmt grdinfo unwrap_fill2_GACOS_detrended.grd**
unwrap_fill2_GACOS_detrended.grd: Title: Produced by grdmath
unwrap_fill2_GACOS_detrended.grd: Command: gmt grdtrend unwrap_fill2_GACOS.grd -N3r -Dunwrap_fill2_GACOS_detrended.grd
unwrap_fill2_GACOS_detrended.grd: Remark: trend residuals
unwrap_fill2_GACOS_detrended.grd: Pixel node registration used [Cartesian grid]
unwrap_fill2_GACOS_detrended.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
unwrap_fill2_GACOS_detrended.grd: x_min: 0 x_max: 68496 x_inc: 16 name: x n_columns: 4281
unwrap_fill2_GACOS_detrended.grd: y_min: 0 y_max: 13056 y_inc: 4 name: y n_rows: 3264
unwrap_fill2_GACOS_detrended.grd: z_min: -21.0269088745 z_max: 25.3661422729 name: z
unwrap_fill2_GACOS_detrended.grd: scale_factor: 1 add_offset: 0
unwrap_fill2_GACOS_detrended.grd: format: classic

**gnss_los.rad**
5901.756976135          1985.701643456      1.152235589260
42426.204513592        10516.696275364    4.891823710630
24928.024992683        5981.839520759      1.774891909080
21762.985565827        11158.692115319    2.32631249085

**supermaster.PRM**
num_valid_az   	= 13056 
nrows   		= 13056 
first_line   		= 1 
deskew   		= n 
caltone   		= 0.000000 
st_rng_bin   		= 1 
Flip_iq   		= n 
offset_video   	= n 
az_res   		= 0.000000 
nlooks   		= 1 
chirp_ext   		= 0 
scnd_rng_mig   	= 0 
rng_spec_wgt   	= 1.000000 
rm_rng_band   		= 0.200000 
rm_az_band   		= 0.000000 
rshift  		= -11 
ashift  	 	= 0 
stretch_r   		= 0 
stretch_a   		= 0 
a_stretch_r   	= 0 
a_stretch_a   	= 0 
first_sample   	= 754 
SC_identity   		= 10 
rng_samp_rate   	= 64345238.125714 
input_file		= S1_20170503_ALL_F1.raw 
num_rng_bins		= 68496 
bytes_per_line		= 273984 
good_bytes_per_line	= 273984 
PRF			= 486.486310 
pulse_dur		= 5.240481e-05 
near_range		= 799213.420612 
num_lines		= 13056 
num_patches		= 1 
SC_clock_start		= 2017122.4201655609 
SC_clock_stop		= 2017122.4204761784 
clock_start		= 122.420165561106 
clock_stop			= 122.420476178503 
led_file		= S1_20170503_ALL_F1.LED 
orbdir	= A 
lookdir	= R 
radar_wavelength	= 0.0554658 
chirp_slope	= 1.07815e+12 
rng_samp_rate		= 64345238.125714 
I_mean			= 0 
Q_mean			= 0 
SC_vel			= 7158.493169 
earth_radius		= 6369968.919539 
equatorial_radius	= 6378137.000000 
polar_radius		= 6356752.310000 
SC_height		= 700540.637096 
SC_height_start	= 700668.449513 
SC_height_end	= 700413.513147 
fd1			= 0.000000 
fdd1			= 0.000000 
fddd1			= 0.000000 
sub_int_r               = 0.000000 
sub_int_a               = 0.000000 
SLC_file               = S1_20170503_ALL_F1.SLC 
dtype			= a 
SLC_scale               = 1.000000 

**supermaster.PRM**
num_valid_az   	= 12188 
nrows   		= 12188 
first_line   		= 1 
deskew   		= n 
caltone   		= 0.000000 
st_rng_bin   		= 1 
Flip_iq   		= n 
offset_video   	= n 
az_res   		= 0.000000 
nlooks   		= 1 
chirp_ext   		= 0 
scnd_rng_mig   	= 0 
rng_spec_wgt   	= 1.000000 
rm_rng_band   		= 0.200000 
rm_az_band   		= 0.000000 
rshift  		= 0 
ashift  	 	= 0 
stretch_r   		= 0 
stretch_a   		= 0 
a_stretch_r   	= 0 
a_stretch_a   	= 0 
first_sample   	= 754 
SC_identity   		= 10 
rng_samp_rate   	= 64345238.125714 
input_file		= S1_20170503_ALL_F1.raw 
num_rng_bins		= 21660 
bytes_per_line		= 86640 
good_bytes_per_line	= 86640 
PRF			= 486.486310 
pulse_dur		= 5.240481e-05 
near_range		= 799213.420612 
num_lines		= 12188 
num_patches		= 1 
SC_clock_start		= 2017122.4201751726 
SC_clock_stop		= 2017122.4204651392 
clock_start		= 122.420175172735 
clock_stop			= 122.420465139403 
led_file		= S1_20170503_ALL_F1.LED 
orbdir	= A 
lookdir	= R 
radar_wavelength	= 0.0554658 
chirp_slope	= 1.07815e+12 
rng_samp_rate		= 64345238.125714 
I_mean			= 0 
Q_mean			= 0 
equatorial_radius	= 6378137.000000 
polar_radius		= 6356752.310000 
fdd1			= 0.000000 
fddd1			= 0.000000 
sub_int_r               = 0.000000 
sub_int_a               = 0.000000 
SLC_file               = S1_20170503_ALL_F1.SLC 
dtype			= a 
SLC_scale               = 1.000000 
SC_vel                  = 7158.493169 
earth_radius            = 6369968.919539 
SC_height               = 700540.637096 
SC_height_start         = 700668.449513 
SC_height_end           = 700413.513147 
fd1                     = 0.000000

please help

**Comment by Xiaohua-Eric-Xu** [comment]
Probably your unwrap_fill2_GACOS_detrended.grd has a different registration type? Add a -T or -r when you generate this grid and see whether the script will work.

**Comment by swjiaotong-jyliu** [comment]
gmt grdinfo correction.grd
correction.grd: Title: 
correction.grd: Remark: 
correction.grd: Pixel node registration used [Cartesian grid]
correction.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
correction.grd: x_min: 0 x_max: 68496 x_inc: 16 name: x n_columns: 4282
correction.grd: y_min: 0 y_max: 13056 y_inc: 4 name: y n_rows: 3265
correction.grd: z_min: -5.11888933182 z_max: 9.66596317291 name: z
correction.grd: scale_factor: 1 add_offset: 0
correction.grd: format: classic

grdsample correction.grd -Gcorrection.grd -R0/68496/0/13056 -I16/4 -r
