### ISSUE TITLE
[Help]: Why there are ten times more dy  than dx

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#378]
Hi 
In [correct_insar_with_gnss.csh](https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/correct_insar_with_gnss.csh)
#
  set x_inc = `gmt grdinfo $insar | grep x_inc | awk 'NR == 1 {printf("%d", $7+.5)}'`
  set y_inc = `gmt grdinfo $insar | grep y_inc | awk 'NR == 1 {printf("%d", $7+.5)}'`
# echo $x_inc, $y_inc
#
# the actual pixel size is
#
  set dx = `echo 'scale=3;' $x_inc '*' $rng_px_size | bc `
  **set dy = `echo 'scale=3;' $y_inc '*' $azi_px_size | bc `0**

I deleted 0.
Do you have any suggestion about this?

**Comment by Xiaohua-Eric-Xu** [comment]
I am a bit unsure of what you are trying to do here.
