### ISSUE TITLE
[Help]: Do I have to stitch frames for slightly offset S1A & S1B products

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#379]
Assuming I want to process the entire available area (no AOI), do I have to stich these frames together? Or will GMTSAR work properly if I just download orbits without defining pins?

![image](https://user-images.githubusercontent.com/50405969/180062866-5cdc53a9-e648-4a08-b269-88be0e17b4f3.png)

Frames are 123 (S1B) and 124 (S1A)

**Comment by Xiaohua-Eric-Xu** [comment]
The program is able to handle such situation. However, the results are likely only viable over minimal common area, as the frames starts and ends at different places.

**Comment by SteffanDavies** [comment]
> The program is able to handle such situation. However, the results are likely only viable over minimal common area, as the frames starts and ends at different places.

That's great Eric thanks!
