### ISSUE TITLE
prep_data_linux.csh working in F1 and F2 but not F3

### ISSUE THREAD

**Issue by nwpulver** [gmtsar/gmtsar#38]
Hello all, 

I have been working on a small time series for GMTSAR practice and I am getting a strange error. I am up to the point in which I need to merge the subswaths for F1 and F2. When I try to get things rolling in the F3 directory with prep_data_linux.csh the script ends early. Here is the ouput of the script
~~~
(base) nathan@nathan-MS-7A93:/media/nathan/massstorage/GMTSAR_DATA/Salton_sea_proc/F3/raw$ prep_data_linux.csh 
rm: cannot remove 'data.in': No such file or directory
--2020-07-28 15:28:46--  https://s1qc.asf.alaska.edu/aux_poeorb/
Resolving s1qc.asf.alaska.edu (s1qc.asf.alaska.edu)... 137.229.87.170, 137.229.87.163
Connecting to s1qc.asf.alaska.edu (s1qc.asf.alaska.edu)|137.229.87.170|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2020-07-28 15:28:47 ERROR 503: Service Unavailable.

Looping over all the lines
Setting a new name for rec
Writing record 20191003
if: Missing file name.
~~~
[F3_ls.txt](https://github.com/gmtsar/gmtsar/files/4991533/F3_ls.txt)

Here is the contents of my directory. Notice that the orbits.list and text.dat is created, but never removed. Now, I do not have wgetasf set up, but this was not a problem in the previous directories that have the exact same setup. I also added the hacky script I have to set up the directories in case that reveals anything. 
[create_dirs.txt](https://github.com/gmtsar/gmtsar/files/4991542/create_dirs.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Please make sure you are able to download orbit data from ASF with your user name and password. i.e. in some version of this script, it requires you to create an alias named `wgetasf`

**Comment by nwpulver** [comment]
Ok, I will try that later. My linux system is being buggy now because it has very low disk space, so I am waiting for a new hard drive to arrive to install my linux partition on. 

The only comment I have on that is, as I said prep_data_linux.csh worked completley fine in F1 and F2 so it seems strange that it would need the ~~~wgetasf~~~ alias only for the F3 directory, right?

**Comment by Xiaohua-Eric-Xu** [comment]
If you have the orbit in the directory, it will not download from ASF.

**Comment by nwpulver** [comment]
I did have my orbits in the directory already. I ended up having to reinstall Ubuntu and all of my packages. I re-ran it and it worked just fine. Not sure why it was not before. Maybe it had to do with storage issues on Ubuntu, but all of this work was being done on a separate hard drive with plenty of space.

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, at the workshop things were a bit strange with many of our students who have newer Ubuntu systems. Did not figure out why as they appear and disappear somehow, sometimes even without doing anything.
