### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by gongzhiqiang97** [gmtsar/gmtsar#380]
**Describe the problem you met**
hi every one. recently, I use GMTSAR to obtain deformation associated with shanghai area. Data: Sentinel 1( ascending : 20211119-20220613) . and eliminated the tropospheric delay with GACOS (and detrended).  
the results are not satisfied. i can`t analysis it from the deformation velocity. what should i do to improve it 
some parameters: atm 5, smooth 1, snaphu.csh 0.12 0
![image](https://user-images.githubusercontent.com/109721761/180153667-6f509b2c-c9df-4e33-aab3-4640af5d14da.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @gongzhiqiang97, on what aspect would you like things to be improved? Do note this is about a half-year long time-series. For better quality, you may want to extend the length?

**Comment by gongzhiqiang97** [comment]
hi @Xiaohua-Eric-Xu ,thanks for your reply. I set the colorbar from -50 to 20 (mm/y). however the results shows that there are significant atmosphere influence (the red part in the picture , caused by the coast water vapor ?), can not fit well with leveling results. what should i do to get better results ? you mean that i should do a long time series (one year or two)?

**Comment by Xiaohua-Eric-Xu** [comment]
Yes getting a longer time-series will definitely help. I think you may have over 7-years data from Sentinel-1?

**Comment by gongzhiqiang97** [comment]
@Xiaohua-Eric-Xu  thanks, that sounds good. i will do it with more data later. once i get the result ,how can i get this half-year (from 2021-11 to 2022-06) deformation velocity ( maybe this is a stupid question, but i just want to get better advices from you)

**Comment by Xiaohua-Eric-Xu** [comment]
Depending on the type of deformation really. If it is a steady rate over the years, then I would recommend just use the overall velocity. If you are targeting a specific transient event, you could take your period out of the longer time-series and do a separate velocity estimate.

**Comment by gongzhiqiang97** [comment]
> Depending on the type of deformation really. If it is a steady rate over the years, then I would recommend just use the overall velocity. If you are targeting a specific transient event, you could take your period out of the longer time-series and do a separate velocity estimate.
 Thank you very much for your advice.
