### ISSUE TITLE
[Help]: how to improve result

### ISSUE THREAD

**Issue by gongzhiqiang97** [gmtsar/gmtsar#381]
Hi every one. recently, I use GMTSAR to obtain deformation associated with shanghai area. Data: Sentinel 1( ascending : 20211119-20220613) .use GACOS to eliminated the tropospheric delay (and detrended).  
the results are not satisfied. i can`t analysis it from the deformation velocity. what should i do to improve it 
some parameters: atm 5 (atm 3 tried), smooth 1, snaphu.csh 0.12 0 
![image](https://user-images.githubusercontent.com/109721761/180153976-777ef30e-af87-443a-9f04-4e6585f6161e.png)

**Comment by ericlindsey** [comment]
This result looks pretty good to me. I recognize the urban part of Shanghai in red, seems like it is sinking quickly. Can you describe in more detail the problem that you would like to improve?

**Comment by gongzhiqiang97** [comment]
hi @ericlindsey, i do not think the result matches the actual situation (the red part in picture). maybe there are significant atmosphere influence? how can i remove it or do something with parameters?
