### ISSUE TITLE
[Help]: why flip top to bottom in dem2topo_ra.csh?

### ISSUE THREAD

**Issue by chyklo** [gmtsar/gmtsar#382]
Hi, Xu! When I processed my data, I find the topo_ra.grd is fliped top to bottom. It is just reversed comparing to the unwrap.grd(as shown in the following figure). Is it right? Whether it will affect the result of topographic phase correction?
![Screenshot from 2022-07-21 16-24-02](https://user-images.githubusercontent.com/48400766/180166950-c2e09736-f116-4386-a7fe-e8d9f0fe2244.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You probably don't want to do that as it was flipped on purpose to match the data read in from the .SLC files. This is relate to how the data are stored in .grd and .SLC files.

**Comment by SteffanDavies** [comment]
Is your data descending? Your DEM was reprojected to radar line-of sight. SAR is right looking and pixels are arranged according to distance from the sensor, so the radar product will be acquired from North -> South with the left bottom pixel corresponding to the North-East of your study area.

![image](https://user-images.githubusercontent.com/50405969/181259375-5c149d78-7cef-48fa-aae5-dcb5c1ace108.png)
