### ISSUE TITLE
[Bug]: ALOS_merge alignment issues

### ISSUE THREAD

**Issue by ericlindsey** [gmtsar/gmtsar#383]
I'm working on processing some ALOS-1 data; I merged two frames along-track using ALOS_merge and it seemed to work fine. However, almost all the interferograms have an odd topo-correlated phase in the northern part of the image like the attached examples. I don't think my DEM is missing, and the error seems to gradually appear along the azimuth direction.

I used the default alignment parameters, and am now wondering whether I should have changed some of the xcorr parameters, or possibly done something else different in that step? Another thing that occurs to me is that the LED file was simply taken from the first (southern) frame, so possibly it could also cause an error in the northern part, like a baseline estimation error? Any advice on where to troubleshoot would be a big help - thanks!

![example_ifgs](https://user-images.githubusercontent.com/6587183/180324198-a0130454-c382-4447-9be6-a936a1df40a2.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
I also met such case in this example http://topex.ucsd.edu/gmtsar/tar/ALOS-ionosphere-correction.tar.
Similarly, the last half of a frame has such issue which sometimes bias the ionosphere correction (unwrapping error). Could it be always the last half acquisition? What if you add another frame to the north or process the two frames individually? I am not sure an orbit error will give such abrupt changes in radar phase and ALOS orbit.
@dsandwell any thoughts?

**Comment by dsandwell** [comment]
Definitely not the orbit file.  However maybe the trans.dat file is incorrect.  Oh yes the algorithm that computes the trans.dat file runs the satellite orbit over a certain distance.  If it is not long enough then the trans.dat will be all messed up.   Look in the SAT_llt2rat program or it may be called ALOS_llt2rat.  You could re-compile with a longer orbit extension.

> On Jul 21, 2022, at 5:10 PM, Xiaohua(Eric) Xu ***@***.***> wrote:
> 
> 
> I also met such case in this example http://topex.ucsd.edu/gmtsar/tar/ALOS-ionosphere-correction.tar.
> Similarly, the last half of a frame has such issue which sometimes bias the ionosphere correction (unwrapping error). Could it be always the last half acquisition? What if you add another frame to the north or process the two frames individually? I am not sure an orbit error will give such abrupt changes in radar phase and ALOS orbit.
> @dsandwell any thoughts?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037
