### ISSUE TITLE
[Bug]: complicated and copy-pasted code in create_frame_tops.csh

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#384]
create_frame_tops.csh includes the same subswath processing code 3 times for the each subswath:

```
# work on the first subswath
...
# wrok on the second subswath
...
# wrok on the third subswath
...
```

The code is produced by just a copy-past operation because we see the same spelling error "wrok" twice.

Also, I think the code is too complicated:
```
  set tmpazi = `echo "$ll1 0" | SAT_llt2rat tmp1.PRM 1 | awk '{print $2}'`
  shift_atime_PRM.csh tmp1.PRM $tmpazi
  set azi1 = `echo "$ll1 0" | SAT_llt2rat tmp1.PRM 1 | awk '{printf("%d",$2+0.5 + '$tmpazi')}'`
  set azi2 = `echo "$ll2 0" | SAT_llt2rat tmp1.PRM 1 | awk '{printf("%d",$2+0.5 + '$tmpazi')}'`
```
Here "azi1" is a rounded "tmpazi" value for positive azimuth and incorrectly rounded value for negative azimuth. Anyway, we don't need to care about negative shifts because the actual shift is limited between 0 and the maximum azimuth. 

And there is a frustrating case when the pins are placed outside of the orbit file definition area. That would be nice to use the scene corners instead of the pins for this case.

In addition, the user-defined pins are meaningful for master image only because we don't need to have areas outside of the master frame for alined images.

Note: two calls of "SAT_llt2rat" could be merged into one because SAT_llt2rat tool allows multiline input.

**Comment by Xiaohua-Eric-Xu** [comment]
I fixed the typo. And yes they are copy pasted and I am just being lazy on writing a for loop. 
The pins has to be designed as inside (it was this case at the beginning) as otherwise, you may get extra bursts that are not available on the master date or the dates with less bursts are also gonna get organized. 
Also the scene corner is not quite accurate in the metadata and I am not sure how you could place a pin outside orbit definition as the orbit products are usually long enough.

**Comment by mobigroup** [comment]
Actually, the assemble wrapper Python code is very short:
```
self.make_s1a_tops(date, debug)

prm = PRM.from_file(old_filename+'.PRM')
azi1 = prm.SAT_llt2rat([self.pins[0], self.pins[1], 0], precise=1)[1]
azi2 = prm.SAT_llt2rat([self.pins[2], self.pins[3], 0], precise=1)[1]
#print ('azi1', azi1, 'azi2', azi2)
prm.shift_atime(azi1, inplace=True).update()

# Working on bursts covering $azi1 ($ll1) - $azi2 ($ll2)...
self.assemble_tops(date, azi1, azi2, debug)
```
It can be even shorter merging the both prm.SAT_llt2rat to one. But the pins validation code is complicated :) I've tried idea to calculate the exact scene area using a grid like to 50x50 and SAT_llt2rat in the approximate scene boundaries but there are no any advantages from it. A minimum rectangle around the ground control points with buffer 0.02 degree covers the real scene for my tests. I'm not sure if it's enough for any scene and so I added nearest interpolation for missed DEM points to be sure the whole frame has DEM. As I understand, GMTSAR users select "large enough" DEM area manually.

**Comment by Xiaohua-Eric-Xu** [comment]
@mobigroup the "large enough" DEM is for correcting topographic phase later. For coregistration purpose, you could use an "incomplete" dem (with no NaNs), I think. But phase outside your DEM may contain lots of topographic fringes. 

We just uploaded a dem generator tool (a new make_dem.csh) using GMT server. And if you have access to GMT6.4 or later, there is a new interpolation option that'll speed up the topo_ra process.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Yes, I mean a DEM without NaNs. That's not a problem to download SRTM 30 and 90m in Python.
