### ISSUE TITLE
[Help]: unwrap_intf error - "grid files not the same size"

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#386]
Processing 64 SLC with no defined pins (full product). Merged all subswaths. 

When running unwrapping about 40 of 200 interferograms seem to unwrap successfuly while all others give following error:

`grdsample [WARNING]: Output sampling interval in x exceeds input interval and may lead to aliasing.
grdmath [INFORMATION]: Perform reverse Polish notation calculations on grids
grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: phase_patch.grd grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: Reading grid from file phase_patch.grd
grdmath [INFORMATION]: Cartesian input grid
grdmath [INFORMATION]: gmt_grd_BC_set: Set boundary condition for all edges: natural
grdmath [INFORMATION]: gmt_grd_BC_set: Set boundary condition for left   edge: natural
grdmath [INFORMATION]: gmt_grd_BC_set: Set boundary condition for right  edge: natural
grdmath [INFORMATION]: gmt_grd_BC_set: Set boundary condition for bottom edge: natural
grdmath [INFORMATION]: gmt_grd_BC_set: Set boundary condition for top    edge: natural
landmask_ra_patch.grd grdmath [INFORMATION]: Cartesian input grid
grdmath [ERROR]: grid files not of same size!
Setting search radius to be 300 ...
Reading in original grid...
Interpolating to nearest neighbour...
Working on line 6537 ...
  388721049 number of searches used ...
WRITING GRID IMAGE: Width x Heihgt = 8587 x 6537...
unwrapping phase with snaphu - higher threshold for faster unwrapping `

phasefilt.grd:
![image](https://user-images.githubusercontent.com/50405969/180630527-9abfb71f-675a-49f9-a53d-9adf0779e8f1.png)

landmask_ra.grd
![image](https://user-images.githubusercontent.com/50405969/180630513-335cc753-adfb-4955-80bd-95e77b1aafb4.png)

Could it be because landmask_ra.grd y_min is not 0?

Region for landmask was 0/68696/0/13074

**Comment by SteffanDavies** [comment]
Padding the landmask seems to of solved the issue:

landmask.csh $(($x_min-32))/$(($x_max+32))/$(($y_min-32))/$(($y_max+32))

However now a fewer number of products are generating the following error:

![image](https://user-images.githubusercontent.com/50405969/180670278-1c63f854-f0b3-43a8-9a7c-8892b7a2641d.png)

**Comment by SteffanDavies** [comment]
I am currently running parallel unwrapping with fewer cores to make sure this is not related no lack of RAM. I was using a 64 core machine with 256GB RAM but this was not enough as memory usage was > 100%.

**Comment by Xiaohua-Eric-Xu** [comment]
This is an issue of GMT rounding the increment to the grid range. The newer version of GMTSAR should've taken care of such issue. Or you could replace the landmask.csh command with a larger size e.g. -100/rng_max/-100/azi_max and then resample to the actual phasefile.grd size.

**Comment by SteffanDavies** [comment]
> This is an issue of GMT rounding the increment to the grid range. The newer version of GMTSAR should've taken care of such issue. Or you could replace the landmask.csh command with a larger size e.g. -100/rng_max/-100/azi_max and then resample to the actual phasefile.grd size.

I am using the latest version of GMTSAR (main branch)

**Comment by Xiaohua-Eric-Xu** [comment]
Could it be diskspace?

**Comment by SteffanDavies** [comment]
> Could it be diskspace?

No, I have 9tb

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, I am not sure. Were you running these in parallel? @chintals mentioned a while ago that there being an issue on number of I/Os but I am not sure whether this is the case.

**Comment by SteffanDavies** [comment]
> Hmmm, I am not sure. Were you running these in parallel? @chintals mentioned a while ago that there being an issue on number of I/Os but I am not sure whether this is the case.

Yes I was unwrapping in parallel, however I have 24 SSDs in raid 0 (9TB)

**Comment by Xiaohua-Eric-Xu** [comment]
OK, please give the ones with the "cannot find phase_patch.grd" ones another try. If the errors persist, pack one example with corr.grd mask.grd phasefilt.grd and landmask_ra.grd. I could give it a try locally. And also send the snaphu command you used.

**Comment by SteffanDavies** [comment]
> OK, please give the ones with the "cannot find phase_patch.grd" error another try. If the errors persist, pack one example with corr.grd mask.grd phasefilt.grd and landmask_ra.grd. I could give it a try locally. And also send the snaphu command you used.

Do you mean I should pack the folders without corr.grd mask.grd phasefilt.grd and landmask_ra.grd with copies of these files from another interferogram folder? Aren't these files different for every interferogram folder?

**Comment by Xiaohua-Eric-Xu** [comment]
They are different except landmask_ra.grd. So I'd like a copy of one example that failed, and try it here locally.

**Comment by SteffanDavies** [comment]
> They are different except landmask_ra.grd. So I'd like a copy of one example that failed, and try it here locally.

Sure thing. I'll wait till unwrapping has finished with less cores and if I get the same error I will send you a copy of a failed interferogram. Thanks.

**Comment by SteffanDavies** [comment]
> They are different except landmask_ra.grd. So I'd like a copy of one example that failed, and try it here locally.

I can confirm the first error was fixed by padding the landmask, while the second error is likely due to insufficient RAM. All interferograms seem to have unwrapped successfully. I would look into the padding issue as it maybe isn't working correctly unless values are padded manually (I used minus and plus 32 in x and y min and max respectively).

**Comment by chintals** [comment]
How many parallel instances are you running? If you suspect its a RAM issue, you can confirm that by increasing the swap size.
You can check in terminal `swapon -s` or using system monitor.

What is your GMT version? `gmt --ver`
