### ISSUE TITLE
[Help]:  How can I estimate the velocity from a series of disp8*.grd using grdmath or other tools?

### ISSUE THREAD

**Issue by sglzy** [gmtsar/gmtsar#387]
I want to estimate a velocity field in a specified time period after SBAS. How can I estimate the velocity from a series of disp*.grd using grdmath? or other tools?

**Comment by Xiaohua-Eric-Xu** [comment]
Easiest way is to read in grids to Matlab or Python and do a linear regression. GMT has a regression tool `gmt gmtregress`, but it works on tables I think.
