### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by KamogeloBaloyi** [gmtsar/gmtsar#388]
**Describe the problem you met**
 I think I did something wrong with the GMTSAR installation.This the response I get when I try the 'autoconf" command. 

If applicable, what operating system and software version you are using?
OS: Ubuntu 22.04
GMTSAR version: Not really sure but I downloaded it using the guide on the GMTSAR Wiki Page

![Screenshot from 2022-07-25 09-25-22](https://user-images.githubusercontent.com/108740453/180727010-458e6e98-387d-4ff2-bfcd-01109204490f.png)

**Comment by KamogeloBaloyi** [comment]
No, I am not

**Comment by Xiaohua-Eric-Xu** [comment]
What commands did you ran afterwards and what are the errors? Any log file?

**Comment by KamogeloBaloyi** [comment]
![image](https://user-images.githubusercontent.com/108740453/180941636-73d6c80c-cf39-405e-b49c-6210af9e57da.png)

I'm new to the Linux systems, so I'm not really sure how to access the log files. I went to the /var/log but I don't really know what I'm looking for.

**Comment by KamogeloBaloyi** [comment]
![image](https://user-images.githubusercontent.com/108740453/180946704-ce75dcaa-036f-4fb4-8121-18c01899e5c6.png)

**Comment by KamogeloBaloyi** [comment]
![image](https://user-images.githubusercontent.com/108740453/180959624-c4d38525-7d03-470e-b4d1-f57ef59cb63b.png)
I think the problem starts here

**Comment by chintals** [comment]
Checking to see if you installed all the necessary dependencies?

```
sudo apt install csh subversion autoconf libtiff5-dev libhdf5-dev wget
sudo apt install liblapack-dev
sudo apt install gfortran
sudo apt install g++
sudo apt install libgmt-dev
sudo apt install gmt-dcw gmt-gshhg
sudo apt install gmt
```

**Comment by Xiaohua-Eric-Xu** [comment]
Also, after you run `autoconf`, continue the list of commands, `./configure`, `make` and `make install`. The screenshots are just warnings. Won't really affect installation as you are using Ubuntu.

**Comment by KamogeloBaloyi** [comment]
![Screenshot from 2022-07-27 09-34-35](https://user-images.githubusercontent.com/108740453/181188993-c2131670-a73d-481c-9163-c2de9dd5a7a5.png)
![Screenshot from 2022-07-27 09-23-55](https://user-images.githubusercontent.com/108740453/181189003-1338b62e-abfa-456d-8526-2b324877381e.png)
Thank you. I still cannot get past the "Test installation" part though.

**Comment by SteffanDavies** [comment]
I believe I also got the same warnings. You should be able to proceed with the compilation process. 

If you don't provide a prefix to ./configure then it should compile straight into the "bin" folder in the same directory. Please list the contents of the /GMTSAR/bin folder to make sure you have the executables.

Once you have the executables you have to update your ~/.bashrc file and add the GMTSAR/bin folder to your PATH. I am assuming you are using a bash terminal. 

After editing your ~/.bashrc and adding GMTSAR/bin to the PATH, you either have to open a new terminal or source ~/.bashrc to call GMTSAR binaries outside of the GMTSAR/bin folder.

**Comment by SteffanDavies** [comment]
@Xiaohua-Eric-Xu would it be a good idea to add -z muldefs to config.mk by default to ensure compatibility with more recent versions of Ubuntu?

**Comment by Xiaohua-Eric-Xu** [comment]
@SteffanDavies Let me give it a try on a few other systems just to make sure things are OK there before updating the changes.

**Comment by Xiaohua-Eric-Xu** [comment]
@SteffanDavies OK, these two flags does not work on my Mac.
```
clang: warning: -z muldefs: 'linker' input unused [-Wunused-command-line-argument]
...
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by KamogeloBaloyi** [comment]
I tried the -z muldefs flag but got the same result. 

[IMG_20220729_142042.jpg](https://user-images.githubusercontent.com/108740453/181757274-33aa2d2a-9249-4b2e-835a-7238faf77053.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
Please follow the exact steps here https://github.com/gmtsar/gmtsar/issues/12. You'll need to first `make clean` and then re-do the `make` and `make install` after changing the config.mk file.

**Comment by KamogeloBaloyi** [comment]
![image](https://user-images.githubusercontent.com/108740453/182122794-0303594e-174b-47d6-b976-fe9988892969.png)
I am still getting the same results for "esarp"

**Comment by SteffanDavies** [comment]
> ![image](https://user-images.githubusercontent.com/108740453/182122794-0303594e-174b-47d6-b976-fe9988892969.png) I am still getting the same results for "esarp"

Is esarp in bin folder? If it is, did you add bin to PATH?

**Comment by Xiaohua-Eric-Xu** [comment]
> fe9988892969.png) I am still getting the same results for "esarp"

Please do exactly as suggested.
1) make spotless
2) autoconf and ./configure
3) modify config.mk and add the -z muldefs flags
4) make and make install

**Comment by KamogeloBaloyi** [comment]
I added the - z muldefs flag and the solution from #12 and succeeded. Thank you so much!
