### ISSUE TITLE
Get bounding box coordinates for Sentinel data

### ISSUE THREAD

**Issue by Esteban82** [gmtsar/gmtsar#389]
I share below a (shell script) that get the bounding box region of the Sentinel data that could be use to create the supporting DEM. 

This script could avoid the neccesary to open the preview map_overlay.kml image on Google Earth (as described here: https://github.com/gmtsar/2022-unavco-course-gmtsar/blob/main/Jupyter/gmtsar_download_prep_sentinel-1_data.ipynb). 

I test it on Ubuntu 20.04 and for Sentinel data. I couldn't find a way to extract the geographic info for the other satelital data (ENVI, ALOS, ENVISAT, etc). 

```
# Extract bounding box region (to create DEM) for Sentinel Data
# Esteban F.D. July 2022
# 
# In the manifest.safe files of the sentinel there is geographic info about the coverage area.
#
# Steps to follow
# 1. Use find to get the paths of all the manifest.safe files in the directory and subdirectories. 
# 2. Use grep to extract the lines which contains the geographic data (are those which includes the text "<gml:coordinates>").
# 3. Use cut to only keep the string with the longitude and latitude values (characters 127 to 213)
# 4. Use a loop to separate all the data and organized it on two columns (lat and long) and save it on a temporary file (tmp_geo.txt)
# 5. Use gmt info to get the bounding box region of the data in the tmp file. 

# NOTE: The script MUST be used in the parent directory (just outside the raw directory where the sentinel data is saved). Otherwise, the step 3 will probably fail (maybe that step could be improved). 

# 1 to 4:
ll=$(grep "<gml:coordinates>" $(find -name manifest.safe) | cut -c127-213)

for value in $ll
do
    echo $value >> tmp_geo.txt
done

# 5. Extraer region for the DEM
echo "Exact region:"
gmt info tmp_geo.txt -: -I0

echo "Round region up to 0.125"
gmt info tmp_geo.txt -: -I0.125

echo "Output para make_dem.csh:"
gmt info tmp_geo.txt -: -C -I0.125

# Remove the tmp file
rm tmp_geo.txt
```

The output on the terminal should look like this:

```
Exact region:
-R-69.17942/-64.238289/-56.304008/-53.709305
Round region up to 0.125:
-R-69.25/-64.125/-56.375/-53.625
Output para make_dem.csh:
-69.17942	-64.238289	-56.304008	-53.709305
-69.25	-64.125	-56.375	-53.625

```

**Comment by Xiaohua-Eric-Xu** [comment]
We actually thought about writing similar kind of a program, but manifest.safe may not be the best option, as 
1) one may re-organize the data and assemble a certain number of bursts from multiple frames of data.
2) not all satellite data come with such file.
3) for a more common program that may work with other satellites, more or less we need back-geocoding to do geocoding. But back-geocoding needs a DEM, now things are in a loop.
I thought about writing a global search and compare with `num_rng_bins` and `num_lines` but once the position goes beyond the orbit file, SAT_llt2rat will pop out lots of errors/warnings and kills the job. So I stopped and haven't moved anywhere on this. 
Maybe I should use the phl2xyz/xyz2phl (in GMTSAR/gmtsar) to get a rough location of the orbit area and then do the estimates? It'll take some time to write it up.

**Comment by mobigroup** [comment]
@Esteban82 @Xiaohua-Eric-Xu 
Sentinel-1 GeoTIF files include GCP attributes to provide the approximate scene location. Minimal rotated rectangle around it is the good estimation with accuracy about 0.02 degree. I think that's similar for other satellites too because all of them available to preview on ASF portal and other maps. I use this approach already to map all the subswaths for pinning and to download the required DEM:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/7342379/182834960-ad04a588-0b93-4f3e-968f-0b5b0e5baf4f.png">

See the notebook on Google Colab: [ASF_Downloading_2020_Ardabil_Earthquake.ipynb ](https://colab.research.google.com/drive/1gr6pHFu1_gRltjfSuGLGoYqgwDQHNl5M?usp=sharing)

P.S. New make_dem.csh is nice!
