### ISSUE TITLE
Error in organize_files_tops_linux.csh

### ISSUE THREAD

**Issue by geofis** [gmtsar/gmtsar#39]
Hello.

I tried to run the recipe "[Sentinel Time Series Recipe](https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series.pdf)", and found and error in the `organize_files_tops_linux.csh` script. I used the following command:

`tcsh -x /usr/local/GMTSAR/bin/organize_files_tops_linux.csh SAFE_filelist pins.ll 1`

The resulting output log is attached. The content of `SAFE_filelist` is included below (ascending track frames):

```
/media/jose/HD-PNTU3/radar/gmtsar_course/processed/ts_sd/asc/data/S1A_IW_SLC__1SDV_20190806T224456_20190806T224523_028455_033731_BD53.SAFE
/media/jose/HD-PNTU3/radar/gmtsar_course/processed/ts_sd/asc/data/S1A_IW_SLC__1SDV_20191017T224459_20191017T224526_029505_035B79_CEBA.SAFE
/media/jose/HD-PNTU3/radar/gmtsar_course/processed/ts_sd/asc/data/S1A_IW_SLC__1SDV_20191204T224458_20191204T224525_030205_0373D1_7BCE.SAFE
/media/jose/HD-PNTU3/radar/gmtsar_course/processed/ts_sd/asc/data/S1A_IW_SLC__1SDV_20200214T224455_20200214T224522_031255_039842_87A2.SAFE
/media/jose/HD-PNTU3/radar/gmtsar_course/processed/ts_sd/asc/data/S1A_IW_SLC__1SDV_20200402T224456_20200402T224523_031955_03B0A7_A5B5.SAFE
/media/jose/HD-PNTU3/radar/gmtsar_course/processed/ts_sd/asc/data/S1A_IW_SLC__1SDV_20200613T224459_20200613T224526_033005_03D2AA_1436.SAFE
```

And this is the content of `pins.ll`:

```
-70.033945 18.285100
-70.122071 18.569698
```

As you may notice in the log file, the script informed that only the last scence in the `SAFE_filelist` file `... will be re-organized`, while for the remaining scenes it returned the message `SKIP ######, as it does not have enough scenes`. So I decided to run the same command using a `SAFE_filelist` with only the first scene in it, and the script returned "Frames on date 20190806 will be re-organized...". I guess that it is a bug related with how the `SAFE_filelist` is built, which impacts the foreach loop.

I'm running GMTSAR on Ubuntu 18.04.

Thanks in advance.

[logfile_organize_issue.txt](https://github.com/gmtsar/gmtsar/files/5013048/logfile_organize_issue.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
I think the error is from SAT_llt2rat. You could refer to this page to find out why. https://github.com/gmtsar/gmtsar/issues/12

**Comment by geofis** [comment]
Thanks. Will give it a try.
