### ISSUE TITLE
[Help]: sbas_parallel.c compilation on Ubuntu systems

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#391]
sbas_parallel.c doesn't compile properly on Ubuntu 22. Is this script only compatible with Mac?

**Comment by Xiaohua-Eric-Xu** [comment]
I am not aware of this script. Is it from the GMTSAR package or from somewhere else?

**Comment by SteffanDavies** [comment]
> I am not aware of this script. Is it from the GMTSAR package or from somewhere else?

I meant sbas_parallel.c, sorry.

https://github.com/gmtsar/gmtsar/blob/master/gmtsar/sbas_parallel.c

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @SteffanDavies, this is kind of system dependent as some c-compilers does not really support openmp, and the lapack lib comes with different settings (e.g. Mac -framework accelerate). The best way is to use homebrew to install gcc-11 (or 10 or 9 or whatever), and locate that compiler. Then when you compile GMTSAR normally, you'll get two lines of code after you run `make` and `make install` that is related to compiling sbas.c (one each). Simply add the needed -fopenmp flag and use the exact same command you get to compile sbas_parallel.c.

**Comment by SteffanDavies** [comment]
@Xiaohua-Eric-Xu I'm having trouble finding this line of code.

The output of make install is this:

`for d in gmtsar snaphu/src; do \
	(cd $d; make install); \
done
make[1]: Entering directory '/home/steffanclentdavies/software/gmtsar2/gmtsar'
/usr/bin/install -c -d /home/steffanclentdavies/software/gmtsar2/bin
/usr/bin/install -c bperp calc_dop_orb conv esarp offset_topo phase2topo phasediff phasefilt resamp xcorr extend_orbit update_PRM get_PRM SAT_llt2rat SAT_look SAT_baseline make_gaussian_filter sbas nearest_grid fitoffset solid_tide p_scatter split_spectrum cut_slc split_aperture phasediff_get_topo_phase geocode_slc /home/steffanclentdavies/software/gmtsar2/bin
ls csh/*.csh csh/*.sh csh/*.py > /tmp/t.lis
/usr/bin/install -c `cat /tmp/t.lis` /home/steffanclentdavies/software/gmtsar2/bin
rm -f /tmp/t.lis
make[1]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/gmtsar'
make[1]: Entering directory '/home/steffanclentdavies/software/gmtsar2/snaphu/src'
/usr/bin/install -c -d /home/steffanclentdavies/software/gmtsar2/bin
/usr/bin/install -c snaphu /home/steffanclentdavies/software/gmtsar2/bin
make[1]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/snaphu/src'
/usr/bin/install -c -d /home/steffanclentdavies/software/gmtsar2/share/gmtsar
/usr/bin/install -c -d /home/steffanclentdavies/software/gmtsar2/share/gmtsar/filters
/usr/bin/install -c -d /home/steffanclentdavies/software/gmtsar2/share/gmtsar/snaphu/config
/usr/bin/install -c gmtsar/filters/[bfgsxy]* /home/steffanclentdavies/software/gmtsar2/share/gmtsar/filters
/usr/bin/install -c gmtsar/csh/snaphu.conf.* /home/steffanclentdavies/software/gmtsar2/share/gmtsar/snaphu/config
/usr/bin/install -c gmtsar/*.grd /home/steffanclentdavies/software/gmtsar2/share/gmtsar
for d in ALOS ERS S1A CSK TSX RS2 ENVI; do \
	(cd preproc/${d}_preproc; make install); \
done
make[1]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc'
for d in ALOS_pre_process ALOS_merge ALOS_fbd2fbs ALOS_fbd2fbs_SLC ALOS_fbd2ss ALOS_baseline ALOS_pre_process_SLC ALOS_mosaic_ss ALOS_look ALOS_mosaic_ss ALOS_mosaic_ss_2frames ALOS_pre_process_SS; do \
	(cd $d; make all); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_merge'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_merge'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2fbs'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2fbs'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2fbs_SLC'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2fbs_SLC'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2ss'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2ss'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_baseline'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_baseline'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process_SLC'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process_SLC'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_look'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_look'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss_2frames'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss_2frames'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process_SS'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process_SS'
for d in ALOS_pre_process ALOS_merge ALOS_fbd2fbs ALOS_fbd2fbs_SLC ALOS_fbd2ss ALOS_baseline ALOS_pre_process_SLC ALOS_mosaic_ss ALOS_look ALOS_mosaic_ss ALOS_mosaic_ss_2frames ALOS_pre_process_SS; do \
	(cd $d; make install); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process'
/usr/bin/install -c ALOS_pre_process /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_merge'
/usr/bin/install -c ALOS_merge /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_merge'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2fbs'
/usr/bin/install -c ALOS_fbd2fbs /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2fbs'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2fbs_SLC'
/usr/bin/install -c ALOS_fbd2fbs_SLC /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2fbs_SLC'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2ss'
/usr/bin/install -c ALOS_fbd2ss /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_fbd2ss'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_baseline'
mv ALOS_baseline /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_baseline'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process_SLC'
/usr/bin/install -c ALOS_pre_process_SLC /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process_SLC'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss'
/usr/bin/install -c ALOS_mosaic_ss /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_look'
/usr/bin/install -c ALOS_look /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_look'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss'
/usr/bin/install -c ALOS_mosaic_ss /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss_2frames'
/usr/bin/install -c ALOS_mosaic_ss_2frames /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_mosaic_ss_2frames'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process_SS'
/usr/bin/install -c ALOS_pre_process_SS /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc/ALOS_pre_process_SS'
make[1]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ALOS_preproc'
make[1]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc'
for d in ers_line_fixer read_data_file_dpaf read_data_file_ccrs read_sarleader_dpaf; do \
	(cd $d; make all); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/ers_line_fixer'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/ers_line_fixer'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_data_file_dpaf'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_data_file_dpaf'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_data_file_ccrs'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_data_file_ccrs'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_sarleader_dpaf'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_sarleader_dpaf'
for d in ers_line_fixer read_data_file_dpaf read_data_file_ccrs read_sarleader_dpaf; do \
	(cd $d; make install); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/ers_line_fixer'
/usr/bin/install -c ers_line_fixer /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/ers_line_fixer'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_data_file_dpaf'
/usr/bin/install -c read_data_file_dpaf /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_data_file_dpaf'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_data_file_ccrs'
/usr/bin/install -c read_data_file_ccrs /home/steffanclentdavies/software/gmtsar2/bin/read_data_file_ccrs
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_data_file_ccrs'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_sarleader_dpaf'
/usr/bin/install -c read_sarleader_dpaf /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc/read_sarleader_dpaf'
/usr/bin/install -c scripts/dump_orbit_ers.pl /home/steffanclentdavies/software/gmtsar2/bin
/usr/bin/install -c scripts/ERS_pre_process /home/steffanclentdavies/software/gmtsar2/bin
make[1]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ERS_preproc'
make[1]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc'
ln -s -f ../S1A_preproc/include include
ln -s -f ../S1A_preproc/lib lib
for d in lib src_swath src_tops src_orbit src_stitch src_spec_div src_assembly; do \
	(cd $d; make all); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_swath'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_swath'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_tops'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_tops'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_orbit'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_orbit'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_stitch'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_stitch'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_spec_div'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_spec_div'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_assembly'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_assembly'
for d in lib src_swath src_tops src_orbit src_stitch src_spec_div src_assembly; do \
	(cd $d; make install); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_swath'
/usr/bin/install -c make_slc_s1a /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_swath'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_tops'
/usr/bin/install -c make_s1a_tops /home/steffanclentdavies/software/gmtsar2/bin
/usr/bin/install -c make_s1a_tops_6par /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_tops'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_orbit'
/usr/bin/install -c ext_orb_s1a /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_orbit'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_stitch'
/usr/bin/install -c stitch_tops /home/steffanclentdavies/software/gmtsar2/bin
/usr/bin/install -c merge_swath /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_stitch'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_spec_div'
/usr/bin/install -c spectral_diversity /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_spec_div'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_assembly'
/usr/bin/install -c assemble_tops /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/src_assembly'
make[1]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc'
make[1]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/CSK_preproc'
ln -s -f ../S1A_preproc/include include
ln -s -f ../S1A_preproc/lib lib
for d in src_slc src_raw; do \
	(cd $d; make all); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/CSK_preproc/src_slc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/CSK_preproc/src_slc'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/CSK_preproc/src_raw'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/CSK_preproc/src_raw'
for d in src_slc src_raw; do \
	(cd $d; make install); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/CSK_preproc/src_slc'
/usr/bin/install -c make_slc_csk /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/CSK_preproc/src_slc'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/CSK_preproc/src_raw'
/usr/bin/install -c make_raw_csk /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/CSK_preproc/src_raw'
make[1]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/CSK_preproc'
make[1]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/TSX_preproc'
ln -s -f ../S1A_preproc/include include
ln -s -f ../S1A_preproc/lib lib
for d in lib src; do \
	(cd $d; make all); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/TSX_preproc/src'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/TSX_preproc/src'
for d in lib src; do \
	(cd $d; make install); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/TSX_preproc/src'
/usr/bin/install -c make_slc_tsx /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/TSX_preproc/src'
make[1]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/TSX_preproc'
make[1]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/RS2_preproc'
ln -s -f ../S1A_preproc/include include
ln -s -f ../S1A_preproc/lib lib
for d in lib src; do \
	(cd $d; make all); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/RS2_preproc/src'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/RS2_preproc/src'
for d in lib src; do \
	(cd $d; make install); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Nothing to be done for 'install'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/S1A_preproc/lib'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/RS2_preproc/src'
/usr/bin/install -c make_slc_rs2 /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/RS2_preproc/src'
make[1]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/RS2_preproc'
make[1]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc'
mkdir -p lib
(cd lib_src; make all)
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/lib_src'
/usr/bin/install -c *.a ../lib
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/lib_src'
for d in ASA_CAT Dop_orbit ENVI_decode ENVI_SLC_decode; do \
	(cd $d; make all); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ASA_CAT'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ASA_CAT'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/Dop_orbit'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/Dop_orbit'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ENVI_decode'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ENVI_decode'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ENVI_SLC_decode'
(cd epr_api-2.3/src/; make)
make[3]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ENVI_SLC_decode/epr_api-2.3/src'
echo "objects created done"
objects created done
make[3]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ENVI_SLC_decode/epr_api-2.3/src'
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ENVI_SLC_decode'
for d in ASA_CAT Dop_orbit ENVI_decode ENVI_SLC_decode; do \
	(cd $d; make install); \
done
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ASA_CAT'
/usr/bin/install -c asa_cat /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ASA_CAT'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/Dop_orbit'
/usr/bin/install -c calc_dop_orb_envi /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/Dop_orbit'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ENVI_decode'
/usr/bin/install -c asa_im_decode /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ENVI_decode'
make[2]: Entering directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ENVI_SLC_decode'
/usr/bin/install -c envi_slc_decode /home/steffanclentdavies/software/gmtsar2/bin
/usr/bin/install -c envisat_dump_data /home/steffanclentdavies/software/gmtsar2/bin
/usr/bin/install -c envisat_dump_header /home/steffanclentdavies/software/gmtsar2/bin
make[2]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc/ENVI_SLC_decode'
/usr/bin/install -c scripts/dump_orbit_envi.pl /home/steffanclentdavies/software/gmtsar2/bin
/usr/bin/install -c scripts/dump_time_envi.pl /home/steffanclentdavies/software/gmtsar2/bin
/usr/bin/install -c scripts/find_auxi.pl /home/steffanclentdavies/software/gmtsar2/bin
/usr/bin/install -c scripts/ENVI_pre_process /home/steffanclentdavies/software/gmtsar2/bin
/usr/bin/install -c scripts/ENVI_SLC_pre_process /home/steffanclentdavies/software/gmtsar2/bin
make[1]: Leaving directory '/home/steffanclentdavies/software/gmtsar2/preproc/ENVI_preproc'
/usr/bin/install -c preproc/ERS_preproc/scripts/virgin.PRM /home/steffanclentdavies/software/gmtsar2/share/gmtsar
/usr/bin/install -c preproc/ENVI_preproc/scripts/virgin_envisat.PRM /home/steffanclentdavies/software/gmtsar2/share/gmtsar
`

**Comment by SteffanDavies** [comment]
Nevermind, I had to `make clean` first.

I used the following command and it seems to have compiled:

`gcc -fopenmp -O2 -Wall -m64 -fPIC -fno-strict-aliasing -std=c99 -z muldefs -I/usr/include/gmt -I./ -I/usr/local/include    -c -o sbas_parallel.o sbas_parallel.c`

and then:

`gcc -fopenmp -m64 -s -Wl,-rpath,/usr/lib/x86_64-linux-gnu -z muldefs sbas_parallel.o -L/home/steffanclentdavies/software/gmtsar2/gmtsar -lgmtsar -L/usr/lib/x86_64-linux-gnu -lgmt -llapack -lblas -lm   -L/usr/local/lib -ltiff -lm -o sbas_parallel`

**Comment by Luvina0503** [comment]
> Nevermind, I had to `make clean` first.
> 
> I used the following command and it seems to have compiled:
> 
> `gcc -fopenmp -O2 -Wall -m64 -fPIC -fno-strict-aliasing -std=c99 -z muldefs -I/usr/include/gmt -I./ -I/usr/local/include -c -o sbas_parallel.o sbas_parallel.c`
> 
> and then:
> 
> `gcc -fopenmp -m64 -s -Wl,-rpath,/usr/lib/x86_64-linux-gnu -z muldefs sbas_parallel.o -L/home/steffanclentdavies/software/gmtsar2/gmtsar -lgmtsar -L/usr/lib/x86_64-linux-gnu -lgmt -llapack -lblas -lm -L/usr/local/lib -ltiff -lm -o sbas_parallel`

@SteffanDavies 
![0$X$UX29GC~3C3I{MBWN)AR](https://user-images.githubusercontent.com/114629377/204457057-b2231a88-7f30-42ee-9004-d78b888d8470.png)

**Comment by SteffanDavies** [comment]
> > Nevermind, I had to `make clean` first.
> > I used the following command and it seems to have compiled:
> > `gcc -fopenmp -O2 -Wall -m64 -fPIC -fno-strict-aliasing -std=c99 -z muldefs -I/usr/include/gmt -I./ -I/usr/local/include -c -o sbas_parallel.o sbas_parallel.c`
> > and then:
> > `gcc -fopenmp -m64 -s -Wl,-rpath,/usr/lib/x86_64-linux-gnu -z muldefs sbas_parallel.o -L/home/steffanclentdavies/software/gmtsar2/gmtsar -lgmtsar -L/usr/lib/x86_64-linux-gnu -lgmt -llapack -lblas -lm -L/usr/local/lib -ltiff -lm -o sbas_parallel`
> 
> @SteffanDavies ![0$X$UX29GC~3C3I{MBWN)AR](https://user-images.githubusercontent.com/114629377/204457057-b2231a88-7f30-42ee-9004-d78b888d8470.png)

You copied my path, replace with your own path.

**Comment by Luvina0503** [comment]
@SteffanDavies 
command:sbas_parallel
![image](https://user-images.githubusercontent.com/114629377/204698796-a8990473-1a13-4faf-bf36-5eb47311ead7.png)

and then
![image](https://user-images.githubusercontent.com/114629377/204698936-e91ec0eb-9cf1-4b91-a2bc-45d6d2f4747e.png)
 
How should I solve this problem?

**Comment by SteffanDavies** [comment]
Maybe @Xiaohua-Eric-Xu can help you with the missing parameter.

**Comment by Luvina0503** [comment]
The sbas-mmap issue has been resolved. Thanks for your patience

**Comment by SteffanDavies** [comment]
> The sbas-mmap issue has been resolved. Thanks for your patience

What was the problem?

**Comment by Xiaohua-Eric-Xu** [comment]
I think he/she's using an earlier version of sbas_parallel when we haven't implemented the -mmap option.

**Comment by Luvina0503** [comment]
My sbas_parallel is not complete. Download sbas_parallel.c written by Xiaohua-Eric-Xu from code and it will work.
