### ISSUE TITLE
[Help] Can we geocode all the unwrap.grd first, then use sbas on the unwrap_ll.grd ?

### ISSUE THREAD

**Issue by SiyuanZhao1** [gmtsar/gmtsar#392]
Hi,
Can we geocode all the unwrap.grd first, then use sbas.csh on the all the unwrap_ll.grd results for the time-series analysis? I use GACOS to mitigate the tropospheric delay, but what I did was geocode all the unwrap.grd with range/azimuth coordinates first, and perform GACOS on all the lon/lat based unwrap_ll.grd results. But it seems sbas.csh can only be used on range/azimuth file? I try to use proj_ll2ra.csh to transfer the coordinates, but the xy_ min, xy_max, xy_inc, and n_columns value I got are totally different from the original unwrap.grd. Could you give me some suggestions

Thanks very much.

**Comment by Xiaohua-Eric-Xu** [comment]
You could, but you'll need to cut them to the same size first. The geocoding of GMTSAR place boundaries based on whether there are valid data on the pixels. The interferograms, after geocoding, may cover different area due to the shift of acquisitions. Nontheless, the xy_inc should be the same.

**Comment by SiyuanZhao1** [comment]
Hi Eric, thanks for replying. So we still use the sbas function:

"sbas intf.tab scene.tab N S xdim ydim [-atm ni] [-smooth sf] [-wavelength wl] [-incidence inc] [-range -rng] [-rms] [-dem]"
to do the time series? Do we need to change the settings for some parameters for the lon/lat interferograms time series processing? Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
I don't think you'll need to change other things specifically for geocoded products.
