### ISSUE TITLE
[Help]: Question about proj_ll2ra.csh 

### ISSUE THREAD

**Issue by SiyuanZhao1** [gmtsar/gmtsar#393]
When I use the proj_ra2ll.csh, I can transfer the unwrap.grd with range/azimuth coordinates to unwrap_ll.grd with lon/lat coordinates. But when I try to use proj_ll2ra.csh to transfer the file back, I found that the result I got are totally different from the orginal file:

Original unwrap.grd:
<img width="542" alt="original" src="https://user-images.githubusercontent.com/51397425/182010138-ea4bf23f-0397-4d0e-a6ff-ac715b138e11.png">

After using proj_ra2ll:
<img width="961" alt="After_transfer" src="https://user-images.githubusercontent.com/51397425/182010163-d4d13eb5-edf0-4506-9dd3-0d22a3f0d33b.png">

After using proj_ll2ra to transfer back:
<img width="961" alt="Transfer back" src="https://user-images.githubusercontent.com/51397425/182010171-036bd39c-45b4-4ae4-933d-4f7d5cfca7ef.png">

Could you give me some help, thanks very much.

**Comment by Xiaohua-Eric-Xu** [comment]
The projection is basically a re-mosiacing. You won't be able to get the exact same if you geocode and transfer back. Plus there is a pretty strong downsampling built in the proj_ll2ra.csh. You'll need to manually change the sampling interval to get a good result.

**Comment by SiyuanZhao1** [comment]
I see, thanks very much.
