### ISSUE TITLE
[Help]: Error when execute “preproc_batch_tops.csh” in raw folder

### ISSUE THREAD

**Issue by gxw112** [gmtsar/gmtsar#394]
When I execute the following command “preproc_batch_tops.csh”in the terminal, I get an error warning
GMTSAR version:6.2.2
**Log file**
(base) amax@amax:/data/gxw/shiyan/yz_sbas_gmtsar/F3/raw$ tcsh
amax:/data/gxw/shiyan/yz_sbas_gmtsar/F3/raw> preproc_batch_tops.csh data.in dem.grd 1
rm: No match.
rm: 无法删除'baseline_table.dat': 没有那个文件或目录
 Couldn't open xml file: 
 1.xml 
 Couldn't open xml file: 
 1 
cp: 无法获取'S1__ALL_F.PRM' 的文件状态(stat): 没有那个文件或目录
 Can't open  junk1 
cat: junk1: 没有那个文件或目录
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk1': 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4720 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 2.xml 
 Couldn't open xml file: 
 2 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4706 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 3.xml 
 Couldn't open xml file: 
 3 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4706 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 4.xml 
 Couldn't open xml file: 
 4 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4720 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 5.xml 
 Couldn't open xml file: 
 5 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4706 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 6.xml 
 Couldn't open xml file: 
 6 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4706 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 7.xml 
 Couldn't open xml file: 
 7 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4706 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 8.xml 
 Couldn't open xml file: 
 8 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4706 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 9.xml 
 Couldn't open xml file: 
 9 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4706 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 10.xml 
 Couldn't open xml file: 
 10 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4706 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 11.xml 
 Couldn't open xml file: 
 11 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4706 lines of info from XML...
Writing 16 lines for orbit...
NO orbit coverage in the selected file...
Successfully opened junk1 
interpolation point outside of data constraints, 37701.286168 0.000000 0.000000
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
 Couldn't open xml file: 
 12.xml 
 Couldn't open xml file: 
 12 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4706 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 13.xml 
 Couldn't open xml file: 
 13 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4706 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
 Couldn't open xml file: 
 14.xml 
 Couldn't open xml file: 
 14 
Successfully opened junk1 
 can't open  S1__ALL_F.LED 
cat: junk2: 没有那个文件或目录
rm: 无法删除'junk2': 没有那个文件或目录
Reading in 4734 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 
......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 
YR: Undefined variable.
......master LED file S1__ALL_F.LED 
 Can't open ldrfile %s S1__ALL_F.LED 
YR: Undefined variable.
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
pstext [ERROR]: Text record line 0 is NULL! Skipped but this is trouble)
amax:/data/gxw/shiyan/yz_sbas_gmtsar/F3/raw>

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure why your xml files has the name of `1`. Could you share your data.in file?

**Comment by gxw112** [comment]
Dear Xiaohua-Eric-Xu,
Thanks for your reply,below is the content of my data.in file:
1 s1a-iw3-slc-vv-20170319t102813-20170319t102838-015760-019f24-006:S1A_OPER_AUX_POEORB_OPOD_20170408T121512_V20170318T225942_20170320T005942.EOF
2 s1a-iw3-slc-vv-20170412t102814-20170412t102839-016110-01a9a5-006:S1A_OPER_AUX_POEORB_OPOD_20170502T121602_V20170411T225942_20170413T005942.EOF
3 s1a-iw3-slc-vv-20170506t102815-20170506t102840-016460-01b44a-006:S1A_OPER_AUX_POEORB_OPOD_20170526T121637_V20170505T225942_20170507T005942.EOF
4 s1a-iw3-slc-vv-20170611t102817-20170611t102842-016985-01c474-006:S1A_OPER_AUX_POEORB_OPOD_20170701T121752_V20170610T225942_20170612T005942.EOF
5 s1a-iw3-slc-vv-20170705t102818-20170705t102844-017335-01cf18-006:S1A_OPER_AUX_POEORB_OPOD_20170725T121713_V20170704T225942_20170706T005942.EOF
6 s1a-iw3-slc-vv-20170810t102821-20170810t102846-017860-01df17-006:S1A_OPER_AUX_POEORB_OPOD_20170830T121622_V20170809T225942_20170811T005942.EOF
7 s1a-iw3-slc-vv-20170903t102822-20170903t102847-018210-01e9ad-006:S1A_OPER_AUX_POEORB_OPOD_20170923T121556_V20170902T225942_20170904T005942.EOF
8 s1a-iw3-slc-vv-20171009t102823-20171009t102848-018735-01f9cc-006:S1A_OPER_AUX_POEORB_OPOD_20171029T121542_V20171008T225942_20171010T005942.EOF
9 s1a-iw3-slc-vv-20171102t102823-20171102t102848-019085-020480-006:S1A_OPER_AUX_POEORB_OPOD_20171122T121910_V20171101T225942_20171103T005942.EOF
10 s1a-iw3-slc-vv-20171208t102822-20171208t102847-019610-0214f2-006:S1A_OPER_AUX_POEORB_OPOD_20171228T121153_V20171207T225942_20171209T005942.EOF
11 s1a-iw3-slc-vv-20180101t102821-20180101t102846-019960-021fd7-006:S1A_OPER_AUX_POEORB_OPOD_20190121T120754_V20181231T225942_20190102T005942.EOF
12 s1a-iw3-slc-vv-20180206t102820-20180206t102845-020485-023082-006:S1A_OPER_AUX_POEORB_OPOD_20180226T120555_V20180205T225942_20180207T005942.EOF
13 s1a-iw3-slc-vv-20180302t102820-20180302t102845-020835-023ba4-006:S1A_OPER_AUX_POEORB_OPOD_20180322T120724_V20180301T225942_20180303T005942.EOF
14 s1a-iw3-slc-vv-20180407t102820-20180407t102845-021360-024c3c-006:S1A_OPER_AUX_POEORB_OPOD_20180427T120800_V20180406T225942_20180408T005942.EOF

**Comment by Xiaohua-Eric-Xu** [comment]
please remove the numbers ahead of each record and re-run the script.

**Comment by gxw112** [comment]
thanks a lot,the problem is solved

**Comment by gxw112** [comment]
Dear Xiaohua-Eric-Xu:
I'm sorry to bother you again,when I execute the command 'unwrap_intf.csh' in my intf_all folder,I get the error as:
amax:/data/gxw/shiyan/yz_sbas_gmtsar/F3/intf_all> unwrap_intf.csh intflist
foreach: Words not parenthesized.
amax:/data/gxw/shiyan/yz_sbas_gmtsar/F3/intf_all>

and the content of unwrap_intf.csh file is:
#!/bin/csh -f
# intflist contains a list of all date1_date2 directories.
foreach line (`awk '{print $1}' intflist`)
 cd $line
 snaphu_interp.csh 0.10
 cd ..
end

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what's wrong with foreach as it looks OK to me. But for snaphu_interp.csh you'll need `0.1  0` separated.

**Comment by gxw112** [comment]
Thanks for your reply,I'll check it
