### ISSUE TITLE
[Help]: Some doubts in Correcting InSAR Interferograms with GNSS Displacements

### ISSUE THREAD

**Issue by sglzy** [gmtsar/gmtsar#399]
We utilize the correct_insar_with_gnss.csh script for the purpose of GPS displacement (LOS) correcting low frequency atmospheric errors in intfs. Where filter_wavelength=30000 is set. We draw correction.grd, and the result is shown in the figure. We found that this correction is a plane, not a surface. The correction process we understand is to calculate the residual between InSARS and GNSS (LOS), then spatially interpolate the residual, and then perform 30km spatial filtering(i.e. the correction.grd). Finally, the filtered residual is deducted from the InSAR interference phase to obtain the corrected phase value.　Shouldn't this correction.grd be a 30km Gaussian filtered surface　rather than a plane(ax+by+c=z)?  Moreover, in the upper left corner of correction. grd image（figure1), there is obvious regular grid noise, and the corrected image also has similar noise(figure2）.  The filter wavelength = 45,000 was also tried, with similar results.

The black dot in the figure is the gps station.  The first figure is correction.grd, not detrend. The title is wrong. The second figrue is the corrected phase. The third picture is the original unwrapped phase.　

![图片](https://user-images.githubusercontent.com/109898248/183608945-a7e8e839-c90f-4be9-a05e-9bb065412fa2.png)
![gnss_corrected_only_intf](https://user-images.githubusercontent.com/109898248/183611498-1103aa85-df0b-40eb-95ec-8a3f662f167c.jpg)

![unwrap](https://user-images.githubusercontent.com/109898248/183613384-8f8dd6f1-8412-474b-be5c-a7628a1d93ad.jpg)

**Comment by sglzy** [comment]
The first figure is correction.grd, not detrend. The title is wrong. The second figrue is the corrected phase. The third picture is the original unwrapped phase.

**Comment by sglzy** [comment]
I used ncview to make a profile of correction.grd, and found that there are high frequency fluctuation signals in space. Why? 
![图片](https://user-images.githubusercontent.com/109898248/183661599-35c89da6-90ee-4393-84ff-85dc40b66039.png)

**Comment by Xiaohua-Eric-Xu** [comment]
This high fluctuation is likely from `gmt surface` without applying enough tension. I would use -T0.1 as 0.25 is for smooth data. Also make sure your input gnsslos.rad is in millimeters.

@kguns32 wrote this script and maybe able to answer more on the filtering, but generally you could tune the wavelength for best results.

**Comment by kguns32** [comment]
Hi, yes you are explaining the process correctly! Another factor in this is that the residuals between InSAR and GNSS are surfaced and filtered while it is a lower resolution grid, then the final filtered solution is upsampled to the resolution of the InSAR grid. For your correction grid, I’m a little surprised to see such high values in your scale — where is this location? I'd also suggest double checking that your gnss_los.rad file is in millimeters just to rule that out.

From Xiaohua’s suggestion, you can edit the surface command in line 101 in correct_insar_with_gnss.csh , and add a -T flag with a value of 0.1 - 0.25 to help fix the fluctuations issue.

**Comment by sglzy** [comment]
Thanks for your responses.   The purpose of surface line 101 in the script is to grid the discrete insar-gps. I modify the parameter -T, which has little effect on the result.
The error is not here. The tmp1.grd generated by line 101 has no problem. In line 113, tmp1.grd is Gaussian filtered (17 pixels, approximately equal to the set filter radius) to generate tmp2.grd, and then tmp2.grd is resampled to get tmp3.grd (what is the purpose?　tmp3.grd minus tmp2.grd results in 0, no difference between them.). Finally, in line 118, the tmp3 .grd for upsampling (gmt grd2xyz tmp3.grd | gmt surface -R$insar -T0.2 -Gcorrection.grd), I found that distortion occurred during this upsampling.　 Can grdsample be used here instead of surface?

fig1-4 are tmp1.grd tmp2.grd tmp3.grd and correction.grd.  


![tmp1 grd](https://user-images.githubusercontent.com/109898248/183791248-e5afed11-2824-4f72-986e-07c05d0b4320.png)
![tmp2 grd](https://user-images.githubusercontent.com/109898248/183791461-0eba1c19-2fec-400a-9650-3c7e82f272bb.png)
![tmp3 grd](https://user-images.githubusercontent.com/109898248/183791550-813d91c7-0b74-4c36-a0e1-b7783db28354.png)
![correction grd](https://user-images.githubusercontent.com/109898248/183791946-668da970-049e-472a-9366-c31d46d4e5a4.png)

**Comment by kguns32** [comment]
Ah I see -- that is my bad, I was looking at an edited version of this script for reference. Yes that second surface command is the issue for sure, and absolutely, you can use grdsample to simply upsample that grid to the resolution of your interferogram grid. 

I'll explore whether we should just update the csh script to avoid this in the future too (and to remove that tmp3 copy, that does seem unnecessary, thanks for pointing that out)

**Comment by Congzhangg** [comment]
@Xiaohua-Eric-Xu Dear Professor, as you mentioned above, I'd like to ask you some questions

- if GNSS data is used to correct the interferogram, does -atm and -smooth not need to be set during SBAS analysis?  

- If GNSS is not used for correction, is -atm still needed for SBAS analysis after atmospheric correction with GACOS? 

- SBAS analysis uses -atm for atmospheric iteration, its parameters are generally set between 3-5, and the parameter value of -smooth, what do you think is appropriate to set? In addition, what is the meaning of "smooth"

 @kguns32  
- I have seen how to use GNSS to correct interferogram. There are 15 GNSS sites in my research area. Is it necessary to use 15 GNSS to generate a gnsslos. rad file? What is the file format?

- The example is dealing with one interference pair. If I'm dealing with hundreds of interference pairs, do I need to write a loop script on top of that?

Looking forward to hearing from you. Thanks

**Comment by kguns32** [comment]
Hi -- I will let Xiaohua answer those, but using GNSS to correct your interferogram helps with long-wavelength atmospheric errors, but there will likely be more atmospheric noise that can be removed using the -atm correction in SBAS (I would use both). 

Yes, if you have many pairs, and want to correct them to produce a time series, you will need to create a for loop. I would advise creating a shell script that just loops through your list pairs and calls the necessary scripts to correct one by one. 

If you are only interested in GNSS-corrected InSAR velocities, you could just correct your final time-series produced velocity field with GNSS velocities, but if you want GNSS-corrected InSAR displacement time series, you need to correct all interferograms that go into the time series processing.

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu Dear Professor, as you mentioned above, I'd like to ask you some questions
> 
> * if GNSS data is used to correct the interferogram, does -atm and -smooth not need to be set during SBAS analysis?
> * If GNSS correction is not used, does -atm need to be set after atmospheric correction with GACOS?
> * In SBAS analysis, smooth exists to smooth what? What is the usual setting?
> 
1. You could still use -atm and -smooth. GNSS is not the magic solution to everything.
2. If you think the corrections are perfect and does not need any other correction, yes, turn it off. 
3. Smooth the time-series, or suppress noise in the time-series.
