### ISSUE TITLE
CMake fails due to missing source files

### ISSUE THREAD

**Issue by ikselven** [gmtsar/gmtsar#4]
Hi, I'm trying to compile GMTSAR on Debian 10 (Debian Buster). I've installed all dependencies necessary for compiling GMTSAR. When running `cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=RelWithDebInfo ..`, cmake fails in the end with:
```
~~~ Output shortened ~~~

*  Options:
*  GMT library                : /usr/lib/x86_64-linux-gnu/libgmt.so
*  GMT include dir            : /usr/include/gmt
*  TIFF library               : /usr/lib/x86_64-linux-gnu/libtiff.so
*  LAPACK library             : /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libblas.so /usr/lib/x86_64-linux-gnu/liblapack.so
*
*  Locations:
*  Installing GMTSAR in       : /usr/local

-- Configuring done
CMake Error at preproc/ALOS_preproc/CMakeLists.txt:42 (add_executable):
  Cannot find source file:

    ALOS_filter_SLC/ALOS_filter_SLC.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at preproc/ALOS_preproc/CMakeLists.txt:42 (add_executable):
  No SOURCES given to target: ALOS_filter_SLC


-- Build files have been written to: /home/user/projects/gmtsar/build
```

**Comment by dsandwell** [comment]
Hi Felix,

That is a bug in the CMake file.  We delted that program ALOS_filter_SLC.c but did not update the CMake

GMTSAR/preproc/ALOS_preproc/CMakeLists.txt

None of the other systems complained.

I just fixed it in the master.  Please test and let me know if the problem is not solved.

Thanks,

David


> On Aug 28, 2019, at 7:37 AM, Felix Glaser <notifications@github.com> wrote:
> 
> Hi, I'm trying to compile GMTSAR on Debian 10 (Debian Buster). I've installed all dependencies necessary for compiling GMTSAR. When running cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=RelWithDebInfo .., cmake fails in the end with:
> 
> ~~~ Output shortened ~~~
> 
> *  Options:
> *  GMT library                : /usr/lib/x86_64-linux-gnu/libgmt.so
> *  GMT include dir            : /usr/include/gmt
> *  TIFF library               : /usr/lib/x86_64-linux-gnu/libtiff.so
> *  LAPACK library             : /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libblas.so /usr/lib/x86_64-linux-gnu/liblapack.so
> *
> *  Locations:
> *  Installing GMTSAR in       : /usr/local
> 
> -- Configuring done
> CMake Error at preproc/ALOS_preproc/CMakeLists.txt:42 (add_executable):
>   Cannot find source file:
> 
>     ALOS_filter_SLC/ALOS_filter_SLC.c
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
>   .hpp .hxx .in .txx
> 
> 
> CMake Error at preproc/ALOS_preproc/CMakeLists.txt:42 (add_executable):
>   No SOURCES given to target: ALOS_filter_SLC
> 
> 
> -- Build files have been written to: /home/user/projects/gmtsar/build
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by ikselven** [comment]
Yes, the problem is solved. Thanks :)
