### ISSUE TITLE
Error when defining region_cut in intf_tops.csh...and possible solution

### ISSUE THREAD

**Issue by geofis** [gmtsar/gmtsar#40]
I needed to batch generate interferogram and unwrapped phase grids for a small region of a single subswath, so I tried to run `intf_tops.csh` using the `region_cut` parameter. For this, I calculated the radar coordinates of an AOI defined by lon/lat/height using `SAT_llt2rat`. The script performed well until it reached the snaphu part, which returned an error regarding an invalid region. I guess the error was due to the fact that the same `region_cut` parameter defined in the config file, applied also to the snaphu processing, so when snaphu tried to unwrap the phase of the already cut image, the region was no longer valid. 

In order to continue with the workflow, I tried a solution but I am not sure if it's consistent. [I forked the gmtsar repo](https://github.com/geofis/gmtsar-1/commit/3c96b1f8f3e8eb8ef794ba5aa9bae1aa7a1fbb01) and there I added a new parameter called `region_cut_snaphu` to both `intf_tops.csh` and `batch_tops.config` files (in the latter, I left it blank). I'm not sure if this is a consistent solution, or if it will "play well" with the rest of the scripts, but at least in my case I could unwrap the phase of all my interferograms.

Any feedback would be greatly appreaciated.

**Comment by Xiaohua-Eric-Xu** [comment]
Could you attach a log file? I need to see the error.

**Comment by geofis** [comment]
Sorry. Attaching the log as well as the config file used.

Log:
[log_config_1.log](https://github.com/gmtsar/gmtsar/files/5018142/log_config_1.log)

Config:
[batch_tops.config.txt](https://github.com/gmtsar/gmtsar/files/5018146/batch_tops.config.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Could you do a `gmt grdinfo` on your phasefilt.grd? This might be a bug in the intf_tops.csh script.

**Comment by geofis** [comment]
Sure.

`gmt grdinfo phasefilt.grd`

> phasefilt.grd: Title: Produced by grdmath
> phasefilt.grd: Command: grdmath filtphase.grd mask.grd MUL FLIPUD = phasefilt.grd
> phasefilt.grd: Remark: phase
> phasefilt.grd: Pixel node registration used [Cartesian grid]
> phasefilt.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
> phasefilt.grd: x_min: 0 x_max: 7264 x_inc: 8 name: x n_columns: 908
> phasefilt.grd: y_min: 0 y_max: 2368 y_inc: 2 name: y n_rows: 1184
> phasefilt.grd: z_min: -3.14158439636 z_max: 3.14159059525 name: z
> phasefilt.grd: scale_factor: 1 add_offset: 0
> phasefilt.grd: format: classic

**Comment by Xiaohua-Eric-Xu** [comment]
OK. I made a temporary fix on the master branch. I have not tested it in any form. Do you mind giving it a try?

**Comment by geofis** [comment]
Sure. I'll give a try and let you know the results. I guess it will work, since deleting the `region_cut==""` condition, as well as the variable, will let snaphu process the image resulting from the previous steps.

**Comment by geofis** [comment]
Tested the current version of intf_tops.csh in the master branch. Everything worked fine.

Log file attached (supressed some outputs from snaphu).

[log_config_1_edited.log](https://github.com/gmtsar/gmtsar/files/5018784/log_config_1_edited.log)

**Comment by Xiaohua-Eric-Xu** [comment]
Great! Thanks!

**Comment by geofis** [comment]
Thank you Eric.
