### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by Sneha90901** [gmtsar/gmtsar#405]
Hello, @Xiaohua-Eric-Xu 
In "Run One Interferogram to Test Settings" part, I was run this command "intf_tops.csh one.in batch_tops.config" it showed this "no config file: batch_tops.config" as a output. Pls help why it shows this error.
Thank you

**Comment by Xiaohua-Eric-Xu** [comment]
Please consider running a pair of interferogram from topex.ucsd.edu/gmtsar/downloads for testing purpose.

**Comment by omarwater98** [comment]
hi @Xiaohua-Eric-Xu , Cheers,
I am running the individual interferogram test but it does not generate anything, not even the topo_ra.pdf or topo_ra.grd.

![interferograma test](https://user-images.githubusercontent.com/113547446/193709126-73efb800-117b-4963-b6db-27e717b914f6.png)


uso GMTSAR 6.00
Linux VM

- abother question
- For use

**Comment by Xiaohua-Eric-Xu** [comment]
I think there should be a README file with a recommended command to process the data. and the following command does not look correct to me. 

> * For use ./p2p_processing.csh S1_TOPS S1_20180101_ALL_F1 S1_20180314_ALL_F1 confg   its correct how i used?

**Comment by Xiaohua-Eric-Xu** [comment]
you should, 1) place .SAFE and .EOF files in a raw directory. 2) place dem.grd in a topo directory. then 3) run p2p_S1_TOPS_Frame.csh at where your raw and topo directories are.
