### ISSUE TITLE
[Help]:  How to determine the optimal number of iterations in the SBAS

### ISSUE THREAD

**Issue by sglzy** [gmtsar/gmtsar#406]
In the SBAS calculation, we set atm = 0, 3 and 6, respectively, and obtained 3 sets of time series, (smooth is set to 0, and all interference pairs are corrected by GPS, using the script of  correct_insar_with_gnss.csh ). However, the results did not meet expectations. My  understanding is that the more iterations, the more reliable the results. When atm=3, the time series is the smoothest, and the best fit with GPS, and when atm=6, the time series dispersion is the largest. Why? How to determine the optimal number of iterations?

In the figure below, the black point is the GPS daily solution; the red pentagram is atm=0; the blue pentagram is atm=3; the green pentagram is atm=6;

Another phenomenon is that some sites are in good agreement with GPS, such as YC01 (the average coherence coefficient of this point is 0.43); while some sites will deviate, such as SW01 (the average coherence coefficient of this point is 0.57). What is the reason for this?
![YC01](https://user-images.githubusercontent.com/109898248/184505687-7fea58bd-5956-47cb-8ac4-25bbff564310.jpg)
![SW01](https://user-images.githubusercontent.com/109898248/184505695-013c6c16-7420-4034-b99e-44c208ed3240.jpg)
![XUZZ](https://user-images.githubusercontent.com/109898248/184505709-d6385a94-5941-4c33-947e-ab380b312527.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
This is an interesting phenomenon. We have a gradually loosen constraint on the smoothness of time-series estimates through the iterations of atmospheric correction, and I suspect that's the reason why it fails this way. If you set smoothness to zero and apply atm correction, the smooth factor may not be set correctly through the iterations. If you really don't want any smoothness, try a very small number like 0.01.

As for the deviation. This could be from phase unwrapping errors, see this paper below: Xu, X., & Sandwell, D. T. (2019). Toward absolute phase change recovery with InSAR: Correcting for earth tides and phase unwrapping ambiguities. IEEE Transactions on Geoscience and Remote Sensing, 58(1), 726-733.

Or it could be from a large scale velocity bias, e.g. from plate motion. You'll need to estimate the motion and remove it. https://www.essoar.org/doi/10.1002/essoar.10511538.2. Or long term atmospheric changes such as ionospheric cycle (11 years). Or some other bias.

**Comment by sglzy** [comment]
Thanks for your response @Xiaohua-Eric-Xu .  We will try small smooth parameters. 
Regarding the offset of the time series, you mentioned three reasons, one is the unwrapping error, the other is the rigid motion of the plate, and the third is the long-period atmospheric error. Following the link you recommended, long wave deformation gradients due to plate motion can be eliminated (attenuated) when integrating GPS and InSAR. Before integration, our GPS data were deducted from large-scale plate motion using a rigid block rotation model, resulting in a time series of internal relative deformations. What can I do about unwrapping errors and long-period atmospheric errors? Are there any packages in the GMTSAR tool to suppress these errors?

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, if you have GNSS to correct the interferograms/time-series, there should not be such differences. i.e. all of these three should be addressed after integration with GNSS. There are cases where InSAR and GNSS are not essentially measuring the same thing (GNSS has deeper coupling depth of course). What method did you use for integration? What are the differences after this integration?

**Comment by sglzy** [comment]
Thanks for your response @Xiaohua-Eric-Xu .  we corrected the InSAR interferograms using 31 GPS with the script of correct_insar_with_gnss.csh.  The correction process we posted in the topics of #399.

**Comment by sglzy** [comment]
Back to atmospheric iterations. Referring to your comments, we set the smooth parameter to 2 and the number of iterations to 1, 3, and 7, respectively. The result is not as expected. The fluctuation of atm=7 is the largest.  （sbas_parallel intf.tab scene.tab  722 158 5688 3048 -range 825732.8 -incidence 37 -wavelength 0.0554658  -rms -dem  -atm 7 -smooth 2）. The red, green and blue in the figure below are iterations 1, 3, and 7, respectively
![CH01](https://user-images.githubusercontent.com/109898248/185334177-6393ad02-e6f0-4769-874d-6e971e1091b5.jpg)
![YC01](https://user-images.githubusercontent.com/109898248/185334248-067d55db-0851-43c0-99c4-15271a5593b4.jpg)
![XUZZ](https://user-images.githubusercontent.com/109898248/185334276-b2455ce7-30a6-430c-997e-e6daeea05c7f.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
This could be from the later implemented exponential smooth factor changes. Originally, the smooth factor for estimating the long term changes are set to a very large number so as to takeout the well-determined part of deformation (See Tymofyeyeva and Fialko 2015). However, in order to take in more short-term changes such as seasonal, we changed the algorithm to exponentially decrease the smooth factor (from 1000.0) to the input factor thus with each iteration there are more short-term changes getting into the time-series. However, this relies on the assumption that even the second from last smooth factor is large enough to not produce any scattered deformation time-series. This is true when the number of iteration is not too large (with 7 iterations your second from last might be 5-ish). I usually use between 3 and 5.

**Comment by sglzy** [comment]
thanks

**Comment by Luvina0503** [comment]
@sglzy 
May I ask how to draw this picture after sbas processing
![image](https://user-images.githubusercontent.com/114629377/200157706-2debaad7-f246-4196-8e08-c5fb9bff7e74.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You could use `gmt psxy` or `gmt plot`

**Comment by Luvina0503** [comment]
OK. i will try

**Comment by Xiaohua-Eric-Xu** [comment]
https://docs.generic-mapping-tools.org/latest/psxy.html
