### ISSUE TITLE
[Bug]: For descending orbit radar coordinates DEM looks flipped vs interferogram (example S1A_Stack_CPGF_T173.tar.gz)

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#407]
The same feature is recognizable on the both pictures but it's flipped:

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/7342379/184532242-cd311374-c7df-4f77-a811-221e951cd1df.png">

The interferogram is right due to the scene geometry:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/7342379/184532406-0a5edd61-01c3-4265-b016-5a47fb730144.png">

**Comment by Xiaohua-Eric-Xu** [comment]
topo_ra.grd is flipped in order to match the storage in the SLCs. In the old days when eveything's slow, you want to read things forward instead of backward I think.
![image](https://user-images.githubusercontent.com/16844111/184694440-fea21d85-c5e8-4960-a896-1309e6b90154.png)

**Comment by mobigroup** [comment]
The plot is wrong because this is not the DEM in radar coordinates as it titled. The plot is frustrating I think and it’s not related to the processing but to its visualization.

**Comment by Xiaohua-Eric-Xu** [comment]
Well, the plot shows what the grid is. If you want to plot thing in radar coordinates, just flip it back. 

GMT by default stores things as top-left being the first element. Thus in order for the array to be read sequentially, topo_ra.grd is flipped. If you want to plot thing in radar coordinates, just flip it back.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu @dsandwell 
Sorry, for me it doesn't sense because vertical axis labeled as "Azimuth" is reverted azimuth! Please don't measure topography in kilograms and  don't label inverted azimuth as azimuth... And even more on the interferogram plot the same label "azimuth" means absolutly different thing and so that's a big inconsistency between the plots. That's make GMTSAR plots untrustable as these are misconsistent.

**Comment by Xiaohua-Eric-Xu** [comment]
Changed label to "Reversed Azimuth"
bdf594a30a174c81671ec3c43407cbb1fd471316

**Comment by mobigroup** [comment]
Great, thanks!
