### ISSUE TITLE
Problems with generation files

### ISSUE THREAD

**Issue by simonst7** [gmtsar/gmtsar#41]
Dear developers, 
 I have a strange problem with GMTSAR. I changed my SO to Ubuntu 20.04 LTS and installed the GMT 6.0 and GMTSAR branch 6, both building the code with cmake. So everything is working, but when I process my data in intf.csh make a error _hermite: interpolation not in center interval_ , then the ifgs are bad. The same process with the same SAR images in a cluster with Ubuntu 18.04 is correct. I also noticed that the baseline.ps is wrong in batch process: 
![baseline_wrong](https://user-images.githubusercontent.com/53209067/89222969-f54bea00-d5a3-11ea-8b1c-42cf16e8e5ce.png)
That's still happened with select_pairs.csh, so i see the text created for select_pairs and noticed that date is write with "," and not with "." like a select_pairs in cluster 
![text](https://user-images.githubusercontent.com/53209067/89223223-6c817e00-d5a4-11ea-9606-8f00be0bcc3c.png)
So when i write manually the first line  _awk '{print 2014+$3/365.25, $5, $1}' < baseline_table.dat_  the results is with "," 
![console_pc](https://user-images.githubusercontent.com/53209067/89223498-e3b71200-d5a4-11ea-8d48-014cfa98bdae.png)
And for example in cluster with other time series is this 
![console_cluste](https://user-images.githubusercontent.com/53209067/89223581-06e1c180-d5a5-11ea-89b9-1f824e4d5540.png)
So I think that some mathematics operation with the system is changed from "." to "," then is the wrong interpolation with ifg? or you think that is other issue?. Thanks.

**Comment by Xiaohua-Eric-Xu** [comment]
Normally this type of error is from the orbit file. You probably need to attach a log so we know what happened. Also, depending on what data you are using, you may need to use intf_tops.csh.

**Comment by simonst7** [comment]
This process is with ENVISAT SLC data. I attached the same process (p2p_processing ENVI_SLC) in same image pairs to see the difference (on the right  with the cluster and left my pc with error)
![log1](https://user-images.githubusercontent.com/53209067/89227832-668f9b00-d5ac-11ea-96f9-052582ef65f4.png)
![log2](https://user-images.githubusercontent.com/53209067/89227862-74452080-d5ac-11ea-8ed5-07e61698bd4d.png)
![log3](https://user-images.githubusercontent.com/53209067/89227897-83c46980-d5ac-11ea-9206-13fe90d2e90f.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Maybe I missed something. Where is the interpolation error?

**Comment by simonst7** [comment]
To the left side (My pc). The right side is good (cluster)
![log3](https://user-images.githubusercontent.com/53209067/89229112-d69f2080-d5ae-11ea-8484-ed9f21c7af97.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I am a bit surprised that it happened only once. Seems to be related to SAT_baseline. Do you mind try running a SAT_baseline in your intf/day1_day2 folder?

**Comment by simonst7** [comment]
Yes, the same error with SAT_baseline 
![sat_baseline](https://user-images.githubusercontent.com/53209067/89229990-81fca500-d5b0-11ea-931a-a72c9cda0604.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Could you check your LED files. What's inside them?

**Comment by simonst7** [comment]
![led](https://user-images.githubusercontent.com/53209067/89230508-6e9e0980-d5b1-11ea-899c-294f8f7f9437.png)
the left is the secondary LED and right is the Reference LED.

**Comment by Xiaohua-Eric-Xu** [comment]
Do you mind sending me your PRMs and LEDs so I could give it a try?

**Comment by simonst7** [comment]
Okay, I changed the extension to upload the files
[ASA_IMS_1PNESA20071105_141259_000000182063_00096_29709_0000_prm.txt](https://github.com/gmtsar/gmtsar/files/5018930/ASA_IMS_1PNESA20071105_141259_000000182063_00096_29709_0000_prm.txt)
[ASA_IMS_1PNESA20071210_141256_000000182064_00096_30210_0000_prm.txt](https://github.com/gmtsar/gmtsar/files/5018931/ASA_IMS_1PNESA20071210_141256_000000182064_00096_30210_0000_prm.txt)

[ASA_IMS_1PNESA20071105_141259_000000182063_00096_29709_0000_led.txt](https://github.com/gmtsar/gmtsar/files/5018939/ASA_IMS_1PNESA20071105_141259_000000182063_00096_29709_0000_led.txt)
[ASA_IMS_1PNESA20071210_141256_000000182064_00096_30210_0000_led.txt](https://github.com/gmtsar/gmtsar/files/5018940/ASA_IMS_1PNESA20071210_141256_000000182064_00096_30210_0000_led.txt)

p.s. I noticed the rshift and azhift is 0

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure how sub_int_r and sub_int_a in your Secondary/Aligned PRM is -nan. Do you know when this happened? You could find out by checking the PRMs in raw/SLC/intf

**Comment by simonst7** [comment]
raw prm
![raw_prm](https://user-images.githubusercontent.com/53209067/89233049-c7bc6c00-d5b6-11ea-87ae-c2fdb1ccda65.png)
slc prm 
![slc_prm](https://user-images.githubusercontent.com/53209067/89233068-d6a31e80-d5b6-11ea-86a7-bb9b8b518b74.png)
intf prm 
![intf_prm](https://user-images.githubusercontent.com/53209067/89233088-df93f000-d5b6-11ea-82fb-5e00c035dfb5.png)

**Comment by simonst7** [comment]
In raw folder is fine, maybe in the alignment happened but in log file not show nothing strange
![align](https://user-images.githubusercontent.com/53209067/89233500-b2940d00-d5b7-11ea-8eb6-19d22bf43dbc.png)

**Comment by Xiaohua-Eric-Xu** [comment]
These parameters are probably from xcorr. Could you run a `fitoffset.csh 3 3 freq_xcorr.dat` in the SLC folder? What's the output?

**Comment by simonst7** [comment]
This is the output 
`rshift =  -nan 
sub_int_r =  -nan 
stretch_r =  inf 
a_stretch_r =  -nan 
ashift =  -nan 
sub_int_a =  -nan 
stretch_a =  inf`

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, strange. When I run, this is what I got.
[nisar:~/Downloads/testing] xix016% fitoffset.csh 3 3 freq_xcorr.txt 
rshift =  -6 
sub_int_r =  0.82283 
stretch_r =  -0.000468761 
a_stretch_r =  -2.06248e-05 
ashift =  349 
sub_int_a =  0.391 
stretch_a =  0.000565718 
a_stretch_a =  -6.71085e-06

**Comment by Xiaohua-Eric-Xu** [comment]
But this is used in both p2p scripts. Not sure how come one is working and the other one fails.

**Comment by simonst7** [comment]
I got the same that you in cluster 

> (base) sorrego@cn1:~/Tocopilla_2007/96_4059/SLC$ fitoffset.csh 3 3 freq_xcorr.dat 
rshift =  -6 
sub_int_r =  0.82283 
stretch_r =  -0.000468761 
a_stretch_r =  -2.06248e-05 
ashift =  349 
sub_int_a =  0.391 
stretch_a =  0.000565718 
a_stretch_a =  -6.71085e-06

**Comment by simonst7** [comment]
It could be a change in the mathematical process in the ubuntu system, because I did the installation in a cluster and no problem occurred, but on my PC it is strange, and I only change the OS (ubuntu 18.04 in a cluster to ubuntu 20.04 on my pc ).

**Comment by Xiaohua-Eric-Xu** [comment]
Do you mind deleting a few `rm` commands in that fitoffset.csh script to help us figure out which line exactly went wrong? A few files you could check are r.xyz, a.xyz, rm.coef and am.coef. @PaulWessel mentioned that awk could be a bit different under certain systems. Maybe we should go with gawk.

**Comment by simonst7** [comment]
Yes, I modified the fitoffset.csh to gawk and work fine

> (base) simon@simon-hp:~/Escritorio/Tocopilla2007/GMTSAR/Envisat/Track_96/frame_4059/SLC$ ./fitoffset_test.csh 3 3 freq_xcorr.dat 
rshift =  -6 
sub_int_r =  0.82283 
stretch_r =  -0.000468761 
a_stretch_r =  -2.06248e-05 
ashift =  349 
sub_int_a =  0.391 
stretch_a =  0.000565718 
a_stretch_a =  -6.71085e-06

**Comment by simonst7** [comment]
Now Work everything also with `awk ` , I only installed `gawk` and launch the fitoffset modified with `gawk` hahah. Thank you for the support @Xiaohua-Eric-Xu

**Comment by PaulWessel** [comment]
I believe installing gawk sets the symbolic link for awk.  Nobody wants to use the broken awk anyway.
