### ISSUE TITLE
[Help]: Validation of results - SBAS

### ISSUE THREAD

**Issue by RenzoAnc** [gmtsar/gmtsar#410]
Hello, everyone.

I've finished the SBAS processing with GMTSAR and I'm analyzing the results. I have a question about them. 

I understand pixel values of vel.grd are obtained with a lineal regression of pixel values of dis_*.grd. I've plotted this values on Octave software and I got these results.

Image 1:

![Script](https://user-images.githubusercontent.com/105986961/185436378-e8212972-e729-49f6-bcf4-e4a95e06337a.png)

Image 2:

![Resultado](https://user-images.githubusercontent.com/105986961/185436392-ef7736d5-0f8c-4c5f-90d5-6a6d5fddb19e.png)

The graph is (Image 3): 

![Graph](https://user-images.githubusercontent.com/105986961/185436434-34e64f0b-90ee-46fd-8b38-070453b0b18e.png)

This is the scene.tab: [scene.tab.txt](https://github.com/gmtsar/gmtsar/files/9375430/scene.tab.txt) , which helps me to plot the results (It gives me the values of 't' array).

A value of disp for each _disp*.grd_ result was obtained with **echo 500 500 | gmt grdtrack disp_*.grd ...**  and the same value of vel_grd was obtained with **echo 500 500 | gmt grdtrack vel.grd**.

Image 4:

![gmtgrdtrack](https://user-images.githubusercontent.com/105986961/185436717-3ec36b3a-6c5b-4422-b7fa-a2b7ff315f1b.png)

Comparing the results (Image 2 and Image 4), you can see they don't coincide (-22.459 /= -71.329).

What would be the problem?.

Regards.

**Comment by Xiaohua-Eric-Xu** [comment]
The first a few and last a few pixels (I don't remember how many exactly, maybe 2) are not used because the atm correction require constraints from both sides. Think it as removing non-reliable measurements.

**Comment by RenzoAnc** [comment]
Hello, professor @Xiaohua-Eric-Xu. Should I remove the same quantity of values in both sides? (in 'disp' and 't' arrays), or they can be different quantities. I use -atm 2 and smooth 1.0 in sbas.

**Comment by Xiaohua-Eric-Xu** [comment]
I think it is two on each side.

**Comment by RenzoAnc** [comment]
Hi, professor @Xiaohua-Eric-Xu. I've proved to eliminate 2 values on each side, but it didn't work. I continued to eliminate other values and I got the correct velocity when I eliminated the values positionated in [1 2 3 9 10 12 13 14].

The initial values were: d =  [0 17.8371690862	25.2771983427	25.5902969136	21.7855607201	9.73591692307	0.195002974833 -2.91726966465	-19.0628648646	-7.73521740296	-8.00048685074 -7.20870427524 9.59506371442 7.73999705034]

The final values are: d = [25.5902969136	21.7855607201	9.73591692307	0.195002974833	-2.91726966465 -8.00048685074]

![R1](https://user-images.githubusercontent.com/105986961/185757561-30c8b531-94a7-432d-ae70-6c6511ea114e.png)


![R2](https://user-images.githubusercontent.com/105986961/185757570-99dc2a1a-6d30-478e-b8c1-6d467990bee0.png)



Based on the results, I could say the more important results of SBAS processing would be vel.grd and vel_ll.grd  files if **I use -atm # =/ 0**, as some disp*.grd files (in this case, 1 2 3 9 10 12 13 14) would contain non-reliable measurements. Am I right?. I think it's correct because if I use more images (for example, 40), the incorrect disp*.grd files will be more difficult to find. 

I don't know if gacos correction produces the same problems, but I'll try it later.

**Comment by Xiaohua-Eric-Xu** [comment]
Your matlab script got -71.329, and the solution from sbas (from the screenshot) was -71.329. I assume this is correct, isn't it?

> as some disp*.grd files (in this case, 1 2 3 9 10 12 13 14) would contain non-reliable measurements. Am I right?.

Why are these non-reliable?

**Comment by RenzoAnc** [comment]
Hello, professor. I think it because I had to eliminate the values of some disp_*.grd files (1, 2, 3, 9, 10, 12, 13, 14) to get the correct velocity with the MATLAB script (-71.329 mm/yr). If I use all displacement values, I get a wrong result (-22.459 mm/yr).

**Comment by Xiaohua-Eric-Xu** [comment]
There might be a bug (or feature) when you have atm correction turned on but not enough acquisitions for estimate it for a specific date. Below are how they are computed. See that if atm_rms == 0 (i.e. no atm correction available for that date), the velocity estimate will skip that record). Maybe we should setup a flag for that.

```
392     count = 0;
393     for (i = 0; i < S; i++)
394         if (atm_rms[i] != 0.0 && i != 0 && i != 1 && i != S - 1 && i != S - 2)
395             count++;
...
484                 if (count > 2) {
485                     for (i = 2; i < S - 2; i++) {
486                         if (atm_rms[i] != 0.0) {
487                             sumxy = sumxy + time[i] * disp[i * xdim * ydim + j * ydim + k];
488                             sumxx = sumxx + time[i] * time[i];
489                             sumy = sumy + disp[i * xdim * ydim + j * ydim + k];
490                             sumx = sumx + time[i];
491                         }
492                     }
493                     vel[j + xdim * k] = -79.58 * wl * (count * sumxy - sumx * sumy) / (count * sumxx - sumx * sumx) * 365.0;
```

**Comment by RenzoAnc** [comment]
Possibly it's the problem. I tried the case without -atm command (and -smooth 0):

**sbas intf.tab scene.tab 18 14 375 1100 -smooth 0 -wavelength 0.0554658 -incidence 38 -range 857110 -rms -dem**

and I didn't have problems to relation between displacement and velocity values. I found the lineal regression of all displacement values  (disp_*.grd) of one position [500, 500] coincide with velocity value (vel.grd) of the same position. In this case, I didn't have to eliminate any value.

I'll show the results:

![R4](https://user-images.githubusercontent.com/105986961/185808393-50a773b6-65cd-4ea6-b735-4595455af6a3.png)

![R1](https://user-images.githubusercontent.com/105986961/185808338-ff71d645-698e-47cc-832d-48939032a1dc.png)

![Series-Tiempo](https://user-images.githubusercontent.com/105986961/185808341-38354378-2df8-4dad-8154-5ad23a58091e.png)

I hope more images improve the relation between displacement and velocity results (for case with -atm).

**Comment by Xiaohua-Eric-Xu** [comment]
I just added an option called -robust https://github.com/gmtsar/gmtsar/commits/master
If you turn it on, it'll calculate as before (ignoring all without available atm correction). If you don't turn it on, it'll calculate all records to get velocity. 
Feel free to try it out.

**Comment by RenzoAnc** [comment]
Thank you for your answer, professor. I'll take into account your last advice. I'd like to ask you another question. It's about relation between disp_*.grd and disp_**_ll.grd.

I know If I want to get disp_*.grd and vel.grd files in lat/lon coordinates, I need to apply:

ln -s ../topo/trans.dat
ln -s ../intf_all_/date1_date2/gauss_*
proj_ra2ll.csh trans.dat vel.grd vel_ll.grd (the same to disp_*.grd)
...
...

, but there's a problem because I can't get the same value from disp_*.grd and disp_*_ll.grd when I use gmt grdtrack for GNSS.llh and GNSS.rahll.

For example, with lon = -75.03755 and lat = -12.42965 (in GNSS.ll)
![P1](https://user-images.githubusercontent.com/105986961/185809462-db8b27b1-3fbd-445e-903e-9f37b1162e92.png)


, I've obtained GNSS.llh with gmt grdtrack GNSS.ll -G ../topo/dem.grd > GNSS.llh.
![P2](https://user-images.githubusercontent.com/105986961/185809468-16462056-3809-498e-b688-999bfc69c2b8.png)



After that, I obtained LOS value with gmt grdtrack GNSS.llh -G../SBAS/disp_2021038_ll.grd > LOS_InSAR.disp:

![P3](https://user-images.githubusercontent.com/105986961/185809372-67fdf376-4fa6-4087-a2e3-644a3bce5423.png)

If I do the same with range = 1452.153058403, azimuth = 1773.536862421 (the same position, but in radar coordinates) storaged in GNSS.rahll:

![P4](https://user-images.githubusercontent.com/105986961/185809477-e7ad9576-7164-4635-9691-45ec0e134e46.png)



, which was generated with SAT_llt2rat master.PRM 1  < GNSS.llh > GNSS.rahll (master.PRM was in topo directory), I obtain:


![P5](https://user-images.githubusercontent.com/105986961/185809482-a78e947e-e5d2-4a60-8d7c-a1df21c61f18.png)


I got it executing gmt grdtrack GNSS.rahll -G../SBAS/disp_2021038.grd > LOS_InSAR2.disp.

You can see there's a difference between values obtained with  disp_*.grd and disp_*_ll.grd (lon = -75.03755 and lat = -12.42965 or range = 1452.153058403, azimuth = 1773.536862421): 9.45649010101 /= 9.14545360437.


Am I executing the right steps?.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @RenzoAnc, the geocoding part involves re-mosaicing the data. In GMTSAR, we use a block median to get the data value inside each pixel (or box) in geocoordinates. The values will be a bit different but should be close enough if you use grdcut + grdinfo, instead of grdtrack to get the value.

**Comment by RenzoAnc** [comment]
Thank you so much for your help, professor @Xiaohua-Eric-Xu.  I really appreciate it.
 
Regards.
