### ISSUE TITLE
[Help]: example S1A_Stack_CPGF_T173.tar.gz

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#411]
Below we see all the example interferograms where turbulent ones marked by "X" and can be excluded automatically and two others with significant atmospheric effects marked by "?":
![image](https://user-images.githubusercontent.com/7342379/185611162-1fe3a3ee-d8aa-48a8-b5fd-55733e7a3467.png)

Detrending results excluding X marked look strange for the "?" interferograms:
![image](https://user-images.githubusercontent.com/7342379/185611641-303341ee-faec-4c84-938e-fd7347eba2ee.png)

I suppose we need to remove the "?" items before detrending. Is there any way to detect them automatically or even better crop invalid areas? While the detrending results for "?" look wrong that's hard to formalize. I know about GMTSAR SBAS processing but I look for more universal and robust way suitable for non-linear deformations analysis and the fist 3 interferogram on the last picture look correct for the future analysis. Maybe is there some well-known way to exclude the noisy results? And of course I have some ideas like to spatial spectrum and fractality estimations if that is terra incognita.

**Comment by mobigroup** [comment]
And this is the correlation map:

![image](https://user-images.githubusercontent.com/7342379/185634192-523d91c5-b796-4172-830a-528f4a905c3a.png)

**Comment by mobigroup** [comment]
And the interferograms:

![image](https://user-images.githubusercontent.com/7342379/185668759-f62f8b87-eb96-4187-981a-cc455030e73c.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I am unaware of an algorithm that can deterministically say whether an interferogram is good or bad. This is really a user choice. I would not just exclude interferograms due to atmospheric noise, as atm noise are usually associated with specific acquisitions (i.e. dates). With your exclusion, 04/27 will be gone. Some measurement is better than none, especially for the earlier satellite systems such as ERS/ENVISAT/ALOS.

**Comment by mobigroup** [comment]
@dsandwell @Xiaohua-Eric-Xu @ericlindsey
Actually, we can remove ionospheric noise on unwrapped interferograms using long wave gaussian filtering (hmm, by some reason make_gaussian_filter.c disables input arguments to generate 20 km wavelength filter) plus detrending. That's a bit tricky because we have NODATA pixels here so we need to re-weight the gaussian filter for the correct convolution. Split-spectrum method operates by the same way on the original interferograms as I understand (low-coherence noisy pixels processing too but it's not a problem for 20 km gaussian filter of course). For the pair 2015-04-03 - 2015-05-21 we have:

![image](https://user-images.githubusercontent.com/7342379/185958274-62ce75e0-c44c-4e07-84c3-6e5230e029d1.png)

As discussed before, detrending with DEM fitting allows to remove topography component well visible on the filtered picture above:
![image](https://user-images.githubusercontent.com/7342379/185958937-a43b1f09-b86a-4828-b179-982588d0b45c.png)

On the filtered and detrended picture we can see known underground water reservoirs. Do you have some suggestions maybe as this example is the official one to GMTSAR? If that's ok I'll add the new functions to PyGMTSAR and enhance the Jupyter notebook on Google Colab to share the processing pipeline.

**Comment by Xiaohua-Eric-Xu** [comment]
I think this is what people used to do until [10.1109/LGRS.2006.882148](https://doi.org/10.1109/LGRS.2006.882148).
Also tropospheric noise has the components over long wavelength too.The problem of removing all long wavelength signals is that it'll remove large-scale tectonic deformation as well. 
For such purpose in GMTSAR, you could run `gmt grdfiler` with `-I` decimating the data and then run `gmt surface` to interpolate things back to higher sampling.

**Comment by mobigroup** [comment]
Thanks for the link and that’s the interesting question about large-scale tectonic deformations. As soon as topography has fractal spatial spectrum for wide scales range we can’t remove the deformations by gaussian filtering. The Earth’s crust (producing the surface fractality) thickness is up to 70 km and so the related wavelengths have strong spatial spectrum up to 100km (70*sqrt(2)). We are able to filter DEM with 20 km+ filter and still calculate exactly the same fractality index. Consequently, I think gaussian filtering for wavelengths 20+ km is safe for any kind of large-scale deformation observations with an obvious exclusion. Yes, solid earth tides will be filtered by this way but practically we don’t interested in these predictable movements I think.
If you have some example we’d check it. I used to specialized in hologram (interferogram) analytical and numerical modeling and laser-induced writing in photopolymers and this subject looks interesting for me.

**Comment by mobigroup** [comment]
> For such purpose in GMTSAR, you could run gmt grdfiler with -I decimating the data and then run gmt surface to interpolate things back to higher sampling.

But the decimation coefficients are limited too. For my tests I changed decimation limits to 64 and wavelength to 100000:
```
git diff make_gaussian_filter.c 
diff --git a/gmtsar/make_gaussian_filter.c b/gmtsar/make_gaussian_filter.c
index fd6563a..5ffa394 100644
--- a/gmtsar/make_gaussian_filter.c
+++ b/gmtsar/make_gaussian_filter.c
@@ -45,11 +45,11 @@ int main(int argc, char **argv) {
        rng_dec = (int)str2double(argv[2]);
        azi_dec = (int)str2double(argv[3]);
        w = (int)str2double(argv[4]);
-       if (rng_dec < 1 || rng_dec > 4)
+       if (rng_dec < 1 || rng_dec > 64)^M
                die("Incorrect range decimation factor: \n", argv[2]);
-       if (azi_dec < 1 || azi_dec > 4)
+       if (azi_dec < 1 || azi_dec > 64)^M
                die("Incorrect azimuth decimation factor: \n", argv[3]);
-       if (w < 2 || w > 10000)
+       if (w < 2 || w > 100000)^M
                die("Incorrect wavelength: \n", argv[4]);
 
        // get the prm
```

Is there any reason to use so small limits here? It looks as the right tool for post processing when decimation and wavelength can be large values.

**Comment by ericlindsey** [comment]
Here is an example of InSAR in an area where topography and deformation (uplift) rates are almost perfectly correlated at very long spatial scales - more than 100km - the Himalayas https://doi.org/10.1130/G33154.1 . Filtering out the atmospheric noise signal that is proportional to topography here would almost certainly remove the tectonic signal also. There are also short-wavelength examples, like 5-20km width anticlines that are uplifting in the interseismic period due to fault creep - there are some good examples of this in Iran in particular. So unfortunately it's not a good idea to assume that topography and tectonic signals occur at separate spatial scales in general, unless you know this is true for your particular area already. Still, if you are more interested in other types of signals (e.g. hydrologic or oil-related), this can be a good way to approach the filtering.

**Comment by ericlindsey** [comment]
About the 'make_gaussian_filter.c' - The narrow limits on the sizes were probably added because nobody thought of using that code to do long-wavelength filtering in the post-processing step like you propose; we just always use 'gmt grdfilter' as Xiaohua suggests. In principle there's no reason why you couldn't use the more manual version, but grdfilter might be simpler.

**Comment by mobigroup** [comment]
@ericlindsey 
> the Himalayas https://doi.org/10.1130/G33154.1

That's a nice example how even on the extreme topography exist small areas of uplift (one red plus one yellow inside the left frame on the picture):

<img width="583" alt="image" src="https://user-images.githubusercontent.com/7342379/186089970-b72dabbc-2737-4b0b-bd2f-c62b1776b46c.png">

The uplift areas separated well and the scale is about ~20 kilometers so that's absolutely safe to use gaussian filter 20+ km here. And the uplift areas are not correlated to topography because the green areas have about the same elevation as the red and yellow ones:
<img width="960" alt="Screen Shot 2022-08-23 at 14 01 06 small" src="https://user-images.githubusercontent.com/7342379/186092463-2f019fa0-4372-4f95-a51d-4a8531c11168.png">

Here is no problem to use DEM-related detrending for the framed area and any smaller areas too. Actually, InSAR velocities are proportional to derivative of topography heights (related to faults) but not to topography itself:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/7342379/186094815-396c4c9f-4050-43e9-91a5-2b224cf73945.png">

> we just always use 'gmt grdfilter' as Xiaohua suggests

Sorry, I don't understand how could you use the original make_gaussian_filter.c to generate large-scale filters with defined scale in meters when it doesn't support large decimations and wavelengths. Do you mean you manually change PRM file to rewrite all the required parameters instead of the filter limits increasing?..

**Comment by Xiaohua-Eric-Xu** [comment]
make_gaussian_filter is written to work in radar coordinates which has a limited size of 50 built in, and I don't remember why it was set to that number. I changed it to 1024*1024. Yet still, filtering after you have unwrapped phase with grdfilter or other filtering approach may get you a solution faster, as gmt does the filtering in spatial domain (to account for change in latitude I think).

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Thanks, this change is mandatory for small decimation and large wavelength! Filtering in radar coordinates is better due to a rectangular area vs producing an elliptical area with low accuracy corner values in geographic coordinates. As an interferogram is relatively small 2D dataset it can be processed fast even as irregular points dataset (FYI, I shared a planet-scale gaussian processing on Sandwell and Smith global gravity dataset: https://github.com/mobigroup/ellipsoid).

Please increase the limits too. I suppose the values below are reasonable. Decimation coefficient 64 is more than enough even for test purposes and wavelength 100000m is about a half of a scene size:
```
git diff make_gaussian_filter.c 
diff --git a/gmtsar/make_gaussian_filter.c b/gmtsar/make_gaussian_filter.c
index fd6563a..5ffa394 100644
--- a/gmtsar/make_gaussian_filter.c
+++ b/gmtsar/make_gaussian_filter.c
@@ -45,11 +45,11 @@ int main(int argc, char **argv) {
        rng_dec = (int)str2double(argv[2]);
        azi_dec = (int)str2double(argv[3]);
        w = (int)str2double(argv[4]);
-       if (rng_dec < 1 || rng_dec > 4)
+       if (rng_dec < 1 || rng_dec > 64)^M
                die("Incorrect range decimation factor: \n", argv[2]);
-       if (azi_dec < 1 || azi_dec > 4)
+       if (azi_dec < 1 || azi_dec > 64)^M
                die("Incorrect azimuth decimation factor: \n", argv[3]);
-       if (w < 2 || w > 10000)
+       if (w < 2 || w > 100000)^M
                die("Incorrect wavelength: \n", argv[4]);
 
        // get the prm
```

**Comment by mobigroup** [comment]
make_gaussian_filter returns strange results for large wavelengths and decimations like to 128 32 10000 and 128 32 40000:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/7342379/186700784-ef1bb135-8996-4630-a5fd-6e3d4be65b3b.png">

**Comment by mobigroup** [comment]
And for the standalone 200m gaussian filter:

```
cat S1_20150310_ALL_F1.PRM | PATH=$PATH:/usr/local/GMTSAR/bin make_gaussian_filter /dev/stdin 1 1 200 /dev/stdout
 1 4 
37 11
...
```
While I'm not sure how the output decimation factor processing but for range coordinate the input and output decimation is 1 (no decimation) and so we have ~37x4m = 148m for wavelength=200m.

**Comment by ericlindsey** [comment]
I agree it would be nice to get make_gaussian_filter working for any size, but in the meantime, what about trying 'gmt grdfilter -Dp -Fwidth1/width2'? I expect it will be less buggy and possibly faster as well.

**Comment by mobigroup** [comment]
@ericlindsey But how are you going to define a gaussian filter in radar coordinates for specified in meters wavelength using gmt?

**Comment by mobigroup** [comment]
There is a hard-coded constant "5.3" in the code make_gaussian_filter.c:
```
        sig_azi = w / 5.3 / azi_px_size;
        sig_rng = w / 5.3 / rng_px_size;
```
I'm confused what does this constant mean... maybe should it be 6.3 (2PI) instead?. Also, I see the filter window radius is just 2 sigma (instead of 3 or 4 as it's usual in todays applications):
```
        n_azi = (int)(sig_azi * 4);
        n_rng = (int)(sig_rng * 4);
```
Is it safe to have so small filter window?

**Comment by Xiaohua-Eric-Xu** [comment]
> Please increase the limits too. I suppose the values below are reasonable. Decimation coefficient 64 is more than enough even for test purposes and wavelength 100000m is about a half of a scene size:

Hi Alexey, GMTSAR does two step filtering to make things run faster. i.e. convolution of two gaussian filters is equivalent to one gaussian filter with larger size. The initial filters are dec_rng dependent (see filter.csh) and thus the later make_gaussian_filter will produce one that match the initial decimation.  In other words, this filter is applied to initial-filtered (1/2/4 rng_dec and 1/2/4 azi_dec, which is the input for make_gaussian_filter by the way) images. If you want it to apply to original image, use 1/1 decimation as input. 

The hard-coded 5.3 is to ensure half-gain at filter_wavelength. One'll need to cut off at some point. Larger size will improve the quality slightly but cost much longer processing time.

**Comment by Xiaohua-Eric-Xu** [comment]
> I agree it would be nice to get make_gaussian_filter working for any size, but in the meantime, what about trying 'gmt grdfilter -Dp -Fwidth1/width2'? I expect it will be less buggy and possibly faster as well.

I agree with @ericlindsey. The reason we have this written up is because we use conv.c to run things over the SLC data (which is a big chunk of binary numbers). If you already have a grid (netcdf file), using `gmt grdfilter` is much simpler.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu @ericlindsey 

Ok, let's check GMT capabilities for square gaussian filter on a small grid:
```
gmt grdinfo F1_20150121_20150310_phasefilt.grd
...
F1_20150121_20150310_phasefilt.grd: x_min: 0 x_max: 21568 x_inc: 16 name: x n_columns: 1348
F1_20150121_20150310_phasefilt.grd: y_min: 0 y_max: 5484 y_inc: 4 name: y n_rows: 1371
```
GMT results (here flag -Np means standalone approach when "...p which will force the filtered value to be NaN if any grid-nodes with NaN-values are found inside the filter circle"):
```
time gmt grdfilter F1_20150121_20150310_phasefilt.grd -Dp -Fg201/51 -Np -Gout.grd 
149.41s user 0.34s system 99% cpu 2:30.02 total
```
vs Python results (GMT uses filter size instead of standalone sigma):
```
%%time
from scipy.ndimage import gaussian_filter
phase_filtered = gaussian_filter(phasefilts[0], sigma=34, truncate=3.0)
CPU times: user 291 ms, sys: 2.33 ms, total: 293 ms
Wall time: 291 ms
```

The results are the same as you see on the plots below:

![image](https://user-images.githubusercontent.com/7342379/186846957-bab54000-90df-4d16-a049-d9752f3442f1.png)

So GMT is  149.41s/0.291s > 500 times slow for this case and even worst for larger filters. The reasons are easy (did you check GMT codes? I checked when I rewrote all the required GMT functions for PyGMTSAR): GMT doesn't use code vectorization (which supported even on your smartphone for 10+ years) and for this case it's obviously uses a generic 2D convolution instead of two 1D convolutions for gaussian filter. As always, GMT uses non-standalone processing options and it's extremely slow.

@Xiaohua-Eric-Xu 
Thanks, in case the two filters are related and for this cut-off wavelength definition I understand it now. That's really interesting trick for old hardware. And I still surprised why do you think that larger gaussian filter convolution should be slow for today? As I suppose two 1D convolutions even for larger window will work much faster than current GMTSAR realization for a single 2D convolution with smaller filter.

```
cat S1_20150310_ALL_F1.PRM | PATH=$PATH:/usr/local/GMTSAR/bin make_gaussian_filter /dev/stdin 2 1 200 /dev/stdout
 1 2 
19 11
...
```
Here is the single matrix 19 x 11 (209 coefficients) instead of two vectors with size 19 and 11 (30 coefficients in total).

**Comment by mobigroup** [comment]
At the end of the day with long wave gaussian filtering and detrending (fitting to topography after short wave gaussian filtering to prevent overfitting) the results look much better even for hard atmospheric noise conditions. The original pictures:

![image](https://user-images.githubusercontent.com/7342379/186945272-1cbd11d0-4fd7-4031-a0dd-85a33f35f556.png)

And the processed ones:

![image](https://user-images.githubusercontent.com/7342379/186945425-8160d9a6-7801-4223-8073-f3db8910dbba.png)

Following the GMTSAR book there is а subsiding area (overused underground water reservoir?) at the middle which is visible on the all pictures as red area. And for now we are able to use correlation-weighted least-squares displacements estimation on the SBAS series. Even non-linear movements should be detectable I hope.

**Comment by ericlindsey** [comment]
I'm amazed that the grdfilter command is so slow! Definitely sounds like it could use a modernization. The results for your case look excellent - nice work!

**Comment by mobigroup** [comment]
@ericlindsey thanks! My idea is to enhance separate interferograms to detect any kind of displacement on the series vs GMTSAR approach to enhance the entire series to detect linear movements only. With all the tests above it looks possible!

**Comment by mobigroup** [comment]
These are the SBAS displacements calculated using coherency-weighted least-squares method:

![image](https://user-images.githubusercontent.com/7342379/187041635-5c41654e-9cc4-4500-8d72-c2fe4a35dac6.png)

And the total displacements (cumulative sum per date axis):

![image](https://user-images.githubusercontent.com/7342379/187041714-52f3520a-6a6e-41c1-9aa3-ed1bda39bea0.png)

The central reservoir looks very similar to GMTSAR SBAS results with manually removed bad interferograms:

![image](https://user-images.githubusercontent.com/7342379/187041792-1d337b16-279c-4ad6-ab2a-f726b3dc477f.png)

Here GMTSAR SBAS displacement amplitude is unreasonably high and the approach above returns ~2 times smaller values like to GMTSAR SBAS with nonzero atmospheric correction parameter (which is magic because there is no way to calculate it using just interferometry results).

**Comment by mobigroup** [comment]
GMTSAR SBAS with parameter smooth=2 and one manually exclude  (top picture) returns very similar results while the displacement ranges are offset a bit:
![append2](https://user-images.githubusercontent.com/7342379/187060923-cefa23b8-8e99-46c7-b145-4b201ebeeb5b.jpg)

Actually, coherency between the 1st and last images is good enough and we are able to check the results easy. The GMTSAR SBAS result for the same parameters and the full timeseries looks incorrect:

![image](https://user-images.githubusercontent.com/7342379/187061154-8ac97278-4f80-48f0-ba3f-fef5db51f123.png)

And using the GMTSAR SBAS atmospheric correction (-atm 2) it produces even worse results:

![image](https://user-images.githubusercontent.com/7342379/187061316-f87c2e92-47d7-40f3-bbd0-0806fe27f715.png)

@Xiaohua-Eric-Xu @ericlindsey
Maybe did I miss something? I can't produce a good enough results using GMTSAR SBAS for this example dataset using any parameters combination. Only filtering some interferograms manually we are able to obtain the reasonable displacements. The new approach discussed above returns the result without any manual manipulations but using only a common wavelength range to filter ionospheric delay (turbulence effects excluded by coherency-weighted least-squares on the SBAS series). I'm surprised why all the approaches are already discussed in the tickets before and these work great  but there is no the complete solution right out of the box.

**Comment by mobigroup** [comment]
See the new approach and the results in the updated Google Colab Live example notebook: https://colab.research.google.com/drive/1S7qJzn-1CFv02yU9NE8ohyDli1JM11cl?usp=sharing

**Comment by Xiaohua-Eric-Xu** [comment]
> I'm amazed that the grdfilter command is so slow! Definitely sounds like it could use a modernization. The results for your case look excellent - nice work!

@ericlindsey it is expected as GMT does filtering in spatial domain. I think the main reason is that people does a fixed wavelength filtering on a spherical earth grid and the weighs usually need to be calculated with latitude. I am not 100% sure. Maybe we should ask @PaulWessel

**Comment by Xiaohua-Eric-Xu** [comment]
> GMTSAR SBAS with parameter smooth=2 and one manually exclude (top picture) returns very similar results while the displacement ranges are offset a bit: ![append2](https://user-images.githubusercontent.com/7342379/187060923-cefa23b8-8e99-46c7-b145-4b201ebeeb5b.jpg)
> 
> Actually, coherency between the 1st and last images is good enough and we are able to check the results easy. The GMTSAR SBAS result for the same parameters and the full timeseries looks incorrect:
> 
> ![image](https://user-images.githubusercontent.com/7342379/187061154-8ac97278-4f80-48f0-ba3f-fef5db51f123.png)
> 
> And using the GMTSAR SBAS atmospheric correction (-atm 2) it produces even worse results:
> 
> ![image](https://user-images.githubusercontent.com/7342379/187061316-f87c2e92-47d7-40f3-bbd0-0806fe27f715.png)
> 
> @Xiaohua-Eric-Xu @ericlindsey Maybe did I miss something? I can't produce a good enough results using GMTSAR SBAS for this example dataset using any parameters combination. Only filtering some interferograms manually we are able to obtain the reasonable displacements. The new approach discussed above returns the result without any manual manipulations but using only a common wavelength range to filter ionospheric delay (turbulence effects excluded by coherency-weighted least-squares on the SBAS series). I'm surprised why all the approaches are already discussed in the tickets before and these work great but there is no the complete solution right out of the box.

The atm correction does not work or will make things worse when you have only a few images. The algorithm requires lots of acquisitions with regular interval, i.e. for correction on t, you need data on t-1, t-2, t-3 and t+1 t+2, t+3. Plus, when you turn on -atm, the old sbas will remove the first and last two or three records as they will never have good atm correction.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Thanks, I’m aware about the GMTSAR SBAS atmospheric correction details. The question is how do you suggest to process this one example using GMTSAR to produce the results comparable to ones shared in the GMTSAR book? This is a reference GMTSAR example and it needs to provide reproducible and valuable results, isn’t it?

**Comment by PaulWessel** [comment]
If you want faster FFT-based convolution filtering then look at grdfft.

**Comment by mobigroup** [comment]
@PaulWessel We just need faster matrix convolution for gaussian kernel (two 1D convolutions actually). ~1000 times GMT slowdown on the common task is terrible I sure. Actually, gaussian filtering on irregular grid in PostgreSQL database can be faster! FFT-based convolution is not applicable for grids with NODATA values and has some numerical artifacts.

**Comment by PaulWessel** [comment]
Yes, **grdfilter** is slow and was written a very long time ago and specifically to be capable of filtering geospatial data on a spherical Earth.  It was never written to be fast.  However, I think if you gilt it with OpenMP you will at least realize some speedup but not 500-1000 of course. You would have to write an entirely new **grdcartfilter** module using your convolution scheme.  Contributions are welcome!

**Comment by mobigroup** [comment]
@PaulWessel I think GMT grdfilter is problematic by design and it can’t be enhanced effectively. It mixes regular and irregular distance calculations and so uses 2D gaussian kernel convolution on a regular grid. And why we need to enhance this tool when even pure-Python filtering is much faster? For gaussian convolution on an irregular grid (like to on the Globe processing) we combine spatial indexing (to find all the nearest points in the specified radius) and distance calculation (simple for the spherical case) and gaussian weights calculation for all the distances or pre-defined weights table for some speedup… actually, that’s just some lines of Python code using existing libraries (and I shared Python and even PostgreSQL based realizations on GitHub). The situation looks similar to GMT tension surfaces which are physically incorrect by design and produces worst spatial spectrum ever possible while any interpolation with first derivative smoothness control produces good enough results. I suppose GMT is visualization toolkit mainly and that’s misusing to apply it for the data processing tasks. By my tests GMTSAR produces much better results as soon as we removing all the GMT calls completely (as PyGMTSAR does). At the same time, GMT allows us to download SRTM DEM as fast as easy.

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu Thanks, I’m aware about the GMTSAR SBAS atmospheric correction details. The question is how do you suggest to process this one example using GMTSAR to produce the results comparable to ones shared in the GMTSAR book? This is a reference GMTSAR example and it needs to provide reproducible and valuable results, isn’t it?

Short answer is, you will not be able to produce a time-series of 32 acquisitions (in the documentation) with only 5. Time-series quality improves with its length. This dataset is put together to showcase the processing steps, not exactly to get you a valid time-series. You may need to download extra data in order to re-produce the time-series in the documentation.

By the way, did you reference your data to a point or specific reference frame?  Detrending or filtering (like you did) is of-course, one way.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Thanks, understand. But that’s hard or impossible to process a long series on Google Colab because the resources limited by 2 cores and 90 minutes of user inactivity (so user needs to move his mouse or print something to save the processing session). This example looks as challenging due to atmospheric conditions as easy to validate because of the water reservoir well-recognizable movement pattern. Anyway, the reproducible Google Colab notebook for the example is already available and I’ll be happy to find new ways for the results improvement.

I think referencing can’t work here because the atmospheric delay areas are placed differently on the interferograms. Constant offset removing between the interferograms is a linear operating and so it’s useless for non-linear noise removing.

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu Thanks, understand. But that’s hard or impossible to process a long series on Google Colab because the resources limited by 2 cores and 90 minutes of user inactivity (so user needs to move his mouse or print something to save the processing session). This example looks as challenging due to atmospheric conditions as easy to validate because of the water reservoir well-recognizable movement pattern. Anyway, the reproducible Google Colab notebook for the example is already available and I’ll be happy to find new ways for the results improvement.
> 
> I think referencing can’t work here because the atmospheric delay areas are placed differently on the interferograms. Constant offset removing between the interferograms is a linear operating and so it’s useless for non-linear noise removing.

Hi @mobigroup, the atm correction algorithm assumes a closed phase among interferograms, thus referencing will at least remove some ambiguities in the stack of data. I agree it'll probably not help in this specific case as there are too few of acquisitions. As for the GMTSAR sbas results, it should produce the similar results (if the input are the same) as your coherence weighed time-series with -atm turned off and detrend the data.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Sure, GMTSAR SBAS tool is well documented in your papers and it looks straightforward with some tricks like to “-atm” correction (I write “tricks” because some assumptions as linear deformation model required). I’m experienced in fundamental physics and mathematics and numerical calculations but I have very limited InSAR practice. So in case if you have some suggestions how to improve the results I can try. And all the results will be shared as ready to use notebooks on Google Colab to allow everyone to reproduce the results.

**Comment by Xiaohua-Eric-Xu** [comment]
This was your comparison, and I am quoting it to show to another user. Oops, I placed it at the wrong thread.
