### ISSUE TITLE
[Help]: Different number of points in vel.grd and disp*.grd files (sbas)

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#415]
Is there any reason why my vel.grd file has many more points with values than my disp*.grd files?

After projecting to lat/lon, converting to csv and analyzing with pandas:

vel.grd has 661200 rows (with NA rows) and 78478 rows (after dropping NA rows).

all disp*.grd have 136400 rows (with NA rows) and 21026  (after dropping NA rows).

I'm attempting to concatenate the columns but this is making things much harder as the rows don't match.

It seems like the mismatch in number of points happens after projecting to lat/lon. I'm using the same command and trans.dat file for both operations.

![Screenshot from 2022-08-24 14-20-31](https://user-images.githubusercontent.com/50405969/186429062-d9bd03b2-caf3-4d65-839e-9f90311efc98.png)

**Comment by SteffanDavies** [comment]
The problem seems to be related when running proj_ra2ll.csh in parallel. It is using different regions to cut the files:

Command: xyz2grd llpb -R350.841666667/351.052777778/38.7444444444/38.9861111111 -I1s/1s -r -fg -Gdisp_2018199_ll.grd -bi3f

vel_ll.grd: Command: xyz2grd llpb -R350.841666667/351.052777778/38.7444444444/38.9861111111 -I1s/1s -r -fg -Gvel_ll.grd -bi3f

disp_2019062_ll.grd: Command: xyz2grd llpb -R350.840277778/351.055555556/38.7444444444/38.9888888889 -I2.5s/2s -r -fg -Gdisp_2019062_ll.grd -bi3f

**Comment by SteffanDavies** [comment]
I have identified the problem after reading GMTSAR source code. 

`proj_ra2ll.csh` requires a gauss file for pixel sampling. This wasn't very explicit as the only inputs are trans.dat and the grd file. Copying gauss_* to the temporary folder fixed the problem. 

Suggestion: adding the gauss file as an optional argument to `proj_ra2ll.csh `

**Comment by Xiaohua-Eric-Xu** [comment]
Added a filt_wavelength parameter to the master branch so now proj_ra2ll.csh does not really require a gauss_xxx file.

**Comment by SteffanDavies** [comment]
@Xiaohua-Eric-Xu will this break existing code depending on a existing gauss file to determine spacing?

**Comment by Xiaohua-Eric-Xu** [comment]
Nope, it is taken in as an option and can be ignored. But it is not tested yet.
```
Usage: proj_ra2ll.csh trans.dat phase.grd phase_ll.grd [filter_wavelength]
        trans.dat    - file generated by llt_grid2rat  (r a topo lon lat)
        phase_ra.grd - a GRD file of phase or anything
        phase_ll.grd - output file in lon/lat-coordinates
        filter_wavelength - will sample every 1/4 wavelength (in meters) 
```
