### ISSUE TITLE
[Help]: How to obtain residual height of points?

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#416]
As far as I'm aware, Sarproz software allows to extract information about PS residual height (height of scatterer after subtracting DEM), which can be very useful to not only view in 3D but also to understand what part of an infrastructure is being measured (such as top of bridge vs bottom, roof vs road, etc).

Is it possible to obtain this info in GMTSAR?

**Comment by Xiaohua-Eric-Xu** [comment]
We don't have a PS analysis tool in GMTSAR. The overall goal of the software is InSAR data processing, not exactly time-series analysis though it has a built in sbas program. I would use stamps to do so. There is a gmtsar2stamps repository somewhere on Github I think.

**Comment by SteffanDavies** [comment]
So it's not possible to obtain residual height for SBAS analysis?

**Comment by Xiaohua-Eric-Xu** [comment]
If you mean dem error that is proportional to baseline, the -dem will give you a dem.grd in the end. But I am not sure whether that's your target.

**Comment by SteffanDavies** [comment]
Quoting the Sarproz forum:

`Removing an external DEM should reduce the unknown height (with “unknown height” I mean the source of the topographic component of the interferometric phase). Removing an external DEM is particularly useful in mountainous areas (the external DEM can decrease significantly the range of the unknown height). It may be useless in urban areas. In fact, #most of the geometric component of the phase in a urban area is usually generated by the height of buildings, and usually an external DEM is not detailed enough to give you the building height.`

Thus, the residual height is the geometric component of the phase after removal of the topographic component. In urban areas, this allows estimation of point height from the surface.

I remember a study of the Morandi bridge collapse in Italy where residual height was used to distinguish points on the bridge to those at the bottom.

See this example here:
![images (1)](https://user-images.githubusercontent.com/50405969/187298025-a9b266b7-f6ee-45b0-9b5e-42b4a0c4d3a7.jpeg)

**Comment by mobigroup** [comment]
@SteffanDavies 
> Removing an external DEM is particularly useful in mountainous areas (the external DEM can decrease significantly the range of the unknown height). It may be useless in urban areas. 

It's not truth. Computed interferogram on an flat area on 1 km (for example) height without DEM has large plane shift (1-2 km depending of the incidence angle). As I remember to fix the residual heights GMTSAR uses plane removal for interferogram calculation. You could save the residual values to calculate the corresponding heights I think.
