### ISSUE TITLE
[Help]: How to recify geocoding in vel_ll.grd fiel

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#418]
Hie Eric , What if the processed results distorted in the following manner as you can see the vel_ll.grd is now at the right place(cities)?

How can we rectify this error in geolcoding in gmt or on another platform like matlab?
Thanks
![wrong_geocoding_map](https://user-images.githubusercontent.com/88940973/187372123-927dbd6e-6ce3-49de-8b5a-50314bbc571c.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
This seems like a geolocation error. You may be using the wrong trans.dat file for making the projection. If you have merged the product, you'll need to use the trans.dat file in the merge directory. Otherwise, you may get a shift in azimuth or range sometimes.

**Comment by shivamthescienceguy** [comment]
Thanks Eric.
One more thing I was not able to look at the sbas code using vi.
Could you tell me how can I visualise this one?

**Comment by shivamthescienceguy** [comment]
Thanks Eric.
Found It.
