### ISSUE TITLE
[HELP]: help ！is something wrong in my intf process there are too much errors  in my intf.log

### ISSUE THREAD

**Issue by jerry7nol** [gmtsar/gmtsar#419]
grdmath [ERROR]: Syntax error: filtphase.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phasefilt.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phasefilt.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphasefilt.grd
psconvert [ERROR]: The file phasefilt.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
INTF.CSH, FILTER.CSH - END

SKIP UNWRAP PHASE

GEOCODE.CSH - START
rm: cannot remove 'trans.dat': No such file or directory
threshold_geocode: 

Usage: geocode.csh correlation_threshold

 phase is masked when correlation is less than correlation_threshold

Example: geocode.csh .12

INTF.CSH, FILTER.CSH - START
......master LED file S1_20220330_ALL_F1.LED 
.........aligned LED file S1_20220423_ALL_F1.LED 
......master LED file S1_20220330_ALL_F1.LED 
.........aligned LED file S1_20220330_ALL_F1.LED 
intf.csh
running phasediff...
reading topo topo_ra.grd
phasediff [ERROR]: File topo_ra.grd not found
[Session phasediff (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open topofile topo_ra.grd 
filter.csh
setting range_dec = 8, azimuth_dec = 2
gauss_200 2 4 (1 2)
making amplitudes...
filtering interferogram...
conv [ERROR]: File real.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real.grd=bf 
conv [ERROR]: File real_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real_tmp.grd=bf 
conv [ERROR]: File imag.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag.grd=bf 
conv [ERROR]: File imag_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag_tmp.grd=bf 
making amplitude...
grdmath [ERROR]: Syntax error: realfilt.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
grdinfo [ERROR]: Error for input file: No such file (display_amp.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grd2cpt [ERROR]: Error for input file: No such file (display_amp.grd)
grd2cpt [ERROR]: Syntax error -L option: Cannot decode limits
grd2cpt [ERROR]: Syntax error -L option: min_limit must be less than max_limit.
grdimage [ERROR]: Error for input file: No such file (display_amp.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse display_amp.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rdisplay_amp.grd
psconvert [ERROR]: The file display_amp.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making correlation...
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
conv [ERROR]: File tmp2.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  tmp2.grd=bf 
grdimage [ERROR]: Error for input file: No such file (corr.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse corr.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rcorr.grd
psconvert [ERROR]: The file corr.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making phase...
grdmath [ERROR]: Syntax error: imagfilt.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phase.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phase.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphase.grd
psconvert [ERROR]: The file phase.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
filtering phase...
phasefilt [ERROR]: File imagfilt.grd not found
[Session phasefilt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 error reading file imagfilt.grd 
grdedit [ERROR]: Error for input file: No such file (filtphase.grd)
grdmath [ERROR]: Syntax error: filtphase.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phasefilt.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phasefilt.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphasefilt.grd
psconvert [ERROR]: The file phasefilt.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
INTF.CSH, FILTER.CSH - END

SKIP UNWRAP PHASE

GEOCODE.CSH - START
rm: cannot remove 'trans.dat': No such file or directory
threshold_geocode: 

Usage: geocode.csh correlation_threshold

 phase is masked when correlation is less than correlation_threshold

Example: geocode.csh .12

INTF.CSH, FILTER.CSH - START
......master LED file S1_20220330_ALL_F1.LED 
.........aligned LED file S1_20220505_ALL_F1.LED 
......master LED file S1_20220330_ALL_F1.LED 
.........aligned LED file S1_20220330_ALL_F1.LED 
intf.csh
running phasediff...
reading topo topo_ra.grd
phasediff [ERROR]: File topo_ra.grd not found
[Session phasediff (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open topofile topo_ra.grd 
filter.csh
setting range_dec = 8, azimuth_dec = 2
gauss_200 2 4 (1 2)
making amplitudes...
filtering interferogram...
conv [ERROR]: File real.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real.grd=bf 
conv [ERROR]: File real_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real_tmp.grd=bf 
conv [ERROR]: File imag.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag.grd=bf 
conv [ERROR]: File imag_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag_tmp.grd=bf 
making amplitude...
grdmath [ERROR]: Syntax error: realfilt.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
grdinfo [ERROR]: Error for input file: No such file (display_amp.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grd2cpt [ERROR]: Error for input file: No such file (display_amp.grd)
grd2cpt [ERROR]: Syntax error -L option: Cannot decode limits
grd2cpt [ERROR]: Syntax error -L option: min_limit must be less than max_limit.
grdimage [ERROR]: Error for input file: No such file (display_amp.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse display_amp.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rdisplay_amp.grd
psconvert [ERROR]: The file display_amp.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making correlation...
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
conv [ERROR]: File tmp2.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  tmp2.grd=bf 
grdimage [ERROR]: Error for input file: No such file (corr.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse corr.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rcorr.grd
psconvert [ERROR]: The file corr.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making phase...
grdmath [ERROR]: Syntax error: imagfilt.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phase.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phase.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphase.grd
psconvert [ERROR]: The file phase.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
filtering phase...
phasefilt [ERROR]: File imagfilt.grd not found
[Session phasefilt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 error reading file imagfilt.grd 
grdedit [ERROR]: Error for input file: No such file (filtphase.grd)
grdmath [ERROR]: Syntax error: filtphase.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phasefilt.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phasefilt.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphasefilt.grd
psconvert [ERROR]: The file phasefilt.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
INTF.CSH, FILTER.CSH - END

SKIP UNWRAP PHASE

GEOCODE.CSH - START
rm: cannot remove 'trans.dat': No such file or directory
threshold_geocode: 

Usage: geocode.csh correlation_threshold

 phase is masked when correlation is less than correlation_threshold

Example: geocode.csh .12

INTF.CSH, FILTER.CSH - START
......master LED file S1_20220411_ALL_F1.LED 
.........aligned LED file S1_20220423_ALL_F1.LED 
......master LED file S1_20220411_ALL_F1.LED 
.........aligned LED file S1_20220411_ALL_F1.LED 
intf.csh
running phasediff...
reading topo topo_ra.grd
phasediff [ERROR]: File topo_ra.grd not found
[Session phasediff (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open topofile topo_ra.grd 
filter.csh
setting range_dec = 8, azimuth_dec = 2
gauss_200 2 4 (1 2)
making amplitudes...
filtering interferogram...
conv [ERROR]: File real.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real.grd=bf 
conv [ERROR]: File real_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real_tmp.grd=bf 
conv [ERROR]: File imag.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag.grd=bf 
conv [ERROR]: File imag_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag_tmp.grd=bf 
making amplitude...
grdmath [ERROR]: Syntax error: realfilt.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
grdinfo [ERROR]: Error for input file: No such file (display_amp.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grd2cpt [ERROR]: Error for input file: No such file (display_amp.grd)
grd2cpt [ERROR]: Syntax error -L option: Cannot decode limits
grd2cpt [ERROR]: Syntax error -L option: min_limit must be less than max_limit.
grdimage [ERROR]: Error for input file: No such file (display_amp.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse display_amp.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rdisplay_amp.grd
psconvert [ERROR]: The file display_amp.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making correlation...
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
conv [ERROR]: File tmp2.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  tmp2.grd=bf 
grdimage [ERROR]: Error for input file: No such file (corr.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse corr.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rcorr.grd
psconvert [ERROR]: The file corr.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making phase...
grdmath [ERROR]: Syntax error: imagfilt.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phase.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phase.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphase.grd
psconvert [ERROR]: The file phase.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
filtering phase...
phasefilt [ERROR]: File imagfilt.grd not found
[Session phasefilt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 error reading file imagfilt.grd 
grdedit [ERROR]: Error for input file: No such file (filtphase.grd)
grdmath [ERROR]: Syntax error: filtphase.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phasefilt.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phasefilt.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphasefilt.grd
psconvert [ERROR]: The file phasefilt.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
INTF.CSH, FILTER.CSH - END

SKIP UNWRAP PHASE

GEOCODE.CSH - START
rm: cannot remove 'trans.dat': No such file or directory
threshold_geocode: 

Usage: geocode.csh correlation_threshold

 phase is masked when correlation is less than correlation_threshold

Example: geocode.csh .12

INTF.CSH, FILTER.CSH - START
......master LED file S1_20220411_ALL_F1.LED 
.........aligned LED file S1_20220505_ALL_F1.LED 
......master LED file S1_20220411_ALL_F1.LED 
.........aligned LED file S1_20220411_ALL_F1.LED 
intf.csh
running phasediff...
reading topo topo_ra.grd
phasediff [ERROR]: File topo_ra.grd not found
[Session phasediff (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open topofile topo_ra.grd 
filter.csh
setting range_dec = 8, azimuth_dec = 2
gauss_200 2 4 (1 2)
making amplitudes...
filtering interferogram...
conv [ERROR]: File real.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real.grd=bf 
conv [ERROR]: File real_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real_tmp.grd=bf 
conv [ERROR]: File imag.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag.grd=bf 
conv [ERROR]: File imag_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag_tmp.grd=bf 
making amplitude...
grdmath [ERROR]: Syntax error: realfilt.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
grdinfo [ERROR]: Error for input file: No such file (display_amp.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grd2cpt [ERROR]: Error for input file: No such file (display_amp.grd)
grd2cpt [ERROR]: Syntax error -L option: Cannot decode limits
grd2cpt [ERROR]: Syntax error -L option: min_limit must be less than max_limit.
grdimage [ERROR]: Error for input file: No such file (display_amp.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse display_amp.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rdisplay_amp.grd
psconvert [ERROR]: The file display_amp.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making correlation...
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
conv [ERROR]: File tmp2.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  tmp2.grd=bf 
grdimage [ERROR]: Error for input file: No such file (corr.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse corr.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rcorr.grd
psconvert [ERROR]: The file corr.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making phase...
grdmath [ERROR]: Syntax error: imagfilt.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phase.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phase.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphase.grd
psconvert [ERROR]: The file phase.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
filtering phase...
phasefilt [ERROR]: File imagfilt.grd not found
[Session phasefilt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 error reading file imagfilt.grd 
grdedit [ERROR]: Error for input file: No such file (filtphase.grd)
grdmath [ERROR]: Syntax error: filtphase.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phasefilt.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phasefilt.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphasefilt.grd
psconvert [ERROR]: The file phasefilt.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
INTF.CSH, FILTER.CSH - END

SKIP UNWRAP PHASE

GEOCODE.CSH - START
rm: cannot remove 'trans.dat': No such file or directory
threshold_geocode: 

Usage: geocode.csh correlation_threshold

 phase is masked when correlation is less than correlation_threshold

Example: geocode.csh .12

END STACK OF TOPS INTERFEROGRAMS

**Comment by Xiaohua-Eric-Xu** [comment]
This is the line to look at `phasediff [ERROR]: File topo_ra.grd not found`.

Seems something went wrong in your prior step of generating topography in radar coordinates (back geocoding).

**Comment by joejoe03050709** [comment]
is topo-ra.grd generating after intf? and afrer intf there is two topo_ra.grd. one was linked well,one not in the anthor folder that have same name  with frist folder

![ZGHN3RN{VN0BEKS6CDUVVM0](https://user-images.githubusercontent.com/111356557/187808842-adee2e43-5874-4c06-a2da-8e4ae649d396.png)
![SSXIILYK~C8BS15C1~W_T%U](https://user-images.githubusercontent.com/111356557/187808843-cafcca76-c036-4bac-94ce-18b23613b586.png)

**Comment by joejoe03050709** [comment]
> This is the line to look at `phasediff [ERROR]: File topo_ra.grd not found`.
> 
> Seems something went wrong in your prior step of generating topography in radar coordinates (back geocoding).

there was a problem when i frist genaration in intf, but i fixer it by change path of intf.in and batch_tops.config to F* raw, maybe it is the source of problem , what should i do sir
![3Q)}2E8U2}(HQZN 8BFP391](https://user-images.githubusercontent.com/111356557/187833015-5301e1d1-9d83-436e-ad9d-a5fa54708bab.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Please check whether there is a valid topo_ra.grd in your topo directory. Once you have that, run with proc_stage = 2 for intf_tops.csh.

**Comment by joejoe03050709** [comment]
ok. i get it. thank you very much



---Original---
From: "Xiaohua(Eric) ***@***.***&gt;
Date: Fri, Sep 2, 2022 09:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gmtsar/gmtsar] [HELP]: help ！is something wrong in my intf process there are too much errors  in my intf.log (Issue #419)




 
Please check whether there is a valid topo_ra.grd in your topo directory. Once you have that, run with proc_stage = 2 for intf_tops.csh.

**Comment by joejoe03050709** [comment]
> Please check whether there is a valid topo_ra.grd in your topo directory. Once you have that, run with proc_stage = 2 for intf_tops.csh.

sr
GODFM`BS5](https://user-images.githubusercontent.com/111356557/188045745-427c2f00-1fba-456b-977f-f1580545cb78.png)
y，sir，here is error again，it is my frist time to use GMTSAR.
is it wrong for my path？

**Comment by Xiaohua-Eric-Xu** [comment]
This error is could be from your prior run. In other words, 1) you did not generate a valid topo_ra.grd --> 2) interferogram failed in F1/intf_all, F2/intf_all and F3/intf_all --> 3) merge/day1_day2 could not produce merged product.

Now that you fixed 2), you'll need to re-do the merging before running phase unwrapping.

**Comment by joejoe03050709** [comment]
thanks，i am going to try now

**Comment by joejoe03050709** [comment]
> This error is could be from your prior run. In other words, 1) you did not generate a valid topo_ra.grd --> 2) interferogram failed in F1/intf_all, F2/intf_all and F3/intf_all --> 3) merge/day1_day2 could not produce merged product.
> 
> Now that you fixed 2), you'll need to re-do the merging before running phase unwrapping.
sir, there is a under folder in the every first interfergram folder in F*, and links are wrong in these folds, they look like products by intf text ：head -1 intf.in > one.in intf_tops.csh one.in batch_tops.config
![R3D`A10B@3B(6G_~1AXQ55N](https://user-images.githubusercontent.com/111356557/188050689-66168d69-8c88-433c-be82-d5313756c3c8.png)
![JWO) PH0ZJ}S W~AV%Z5PSG](https://user-images.githubusercontent.com/111356557/188050703-25126da6-65cd-42bb-8e87-fa7400afd10d.png)
that is the problem？and in the merge stage
![Y(WT3UHN1M5 KEFXV1OP2Q5](https://user-images.githubusercontent.com/111356557/188050830-00855254-aa57-4561-977f-d523ba6e3077.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Oh, you probably need to delete intf_all directory first before running another intf_tops.csh. Or you could mv the stuffs outside that folder and replace everything in the intf_all/day1_day2 directory.

**Comment by joejoe03050709** [comment]
god，thank you very much

**Comment by joejoe03050709** [comment]
> Oh, you probably need to delete intf_all directory first before running another intf_tops.csh. Or you could mv the stuffs outside that folder and replace everything in the intf_all/day1_day2 directory.
could i miss the intf_tops.csh one, run another intf_tops.csh directly?
