### ISSUE TITLE
Orbits files for ENVISAT 

### ISSUE THREAD

**Issue by nwpulver** [gmtsar/gmtsar#42]
I am not sure if this is an appropriate place to ask for this kind of help as it is not an issue with the code. If it is not, I will delete this post. 

I was hoping someone knew where I could find the orbit files for ENVISAT. I can find the data through SSARA pretty easily, but I have not found a download for the orbits. 

On another note, if someone has any pointers on processing with ENVISAT data I would gladly take any notes. 

Nathan

**Comment by Xiaohua-Eric-Xu** [comment]
Please find the orbit files here. https://topex.ucsd.edu/gmtsar/downloads/, If you are using GMTSAR, simply make the configuration with ./configure --with-orbit-dir=.

**Comment by nwpulver** [comment]
Oh I had already done that, I did not realize it had the ENVISAT orbits in it. Thank you Eric.
