### ISSUE TITLE
[Help]: Missing line in baseline_table.dat

### ISSUE THREAD

**Issue by raviexplorer** [gmtsar/gmtsar#421]
I am working on ubuntu 22.04 
While creating baseline_table.dat using  "  preproc_batch_tops.csh data.in dem.grd 1 " , I am getting following errors and one of the file does not appear in baseline table. 

TIFFFetchDirectory: Can not read TIFF directory count.
TIFFReadDirectory: Failed to read directory at offset 1387278208.
 Couldn't open tiff file: 
 s1a-iw2-slc-vv-20191007t123821-20191007t123846-029353-035641-005.tiff 
 Couldn't open xml file: 
 S1_20191007_ALL_F2.PRM 
cp: cannot stat 'S1_20191007_ALL_F2.PRM': No such file or directory
 Can't open  junk1 
cat: junk1: No such file or directory
cat: junk2: No such file or directory

WARNING:
Range_sampling_rate is not consistant.
You need to do FBD/FBS conversion.

 Can't open ldrfile %s  
YR: Undefined variable.

Please help

**Comment by Xiaohua-Eric-Xu** [comment]
I am not particularly sure. Either it is the data getting corrupted or the data was not readable to you (permision).
