### ISSUE TITLE
[Help]: Recognise correlation and phase features vs issues

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#424]
I'm testing detrending and gaussian filtering on an area with multiple low coherency areas and hard atmospheric conditions (turbulence plus ionospheric delay). Here is a lake at the middle of the area and dam on it marked as "case green". The water surface excluded using stack correlation threshold 0.15. The dam has good enough correlation and it's surrounded by lots of low-coherent areas. As I suppose the trend detection works well here but we still see some issues. What can mean when low and high coherency areas have square artefacts ("case red")? Also, the detrended LOS displacement looks incorrect probably due to wrong unwrapped phase for low-coherency areas. Is it the best way to increase the correlation threshold to fix? SBAS analysis results have the same issues because these are repeated on many interferograms. Maybe this case should be resolved by removing the modeling phase (trend) before unwrapping?
![Unknown](https://user-images.githubusercontent.com/7342379/187991343-824233e5-0aa2-482a-b013-e4058304b687.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
Did you try near neighbor interpolate through the low coherence area? The speckle in the interferogram, if with good coherence, could be due to strong reflective target with motion. Once filtered, it'll spread to its nearby pixels. This is just my guessing, and you'll need to verify by looking at the amplitude images produced with `slc2amp.csh`. I am not really an expert in this, but maybe de-speckle before filtering (clipping)? I am not sure.

**Comment by mobigroup** [comment]
Thanks, the amplitude images analysis looks promising. Could you explain why do you ask about the interpolation? It doesn't related to unwrapping of course and it can't enhance the results. Using higher stack coherency threshold 0.3 the output looks better:
![image](https://user-images.githubusercontent.com/7342379/188068514-cd6ccc3f-bf6e-4066-9720-dde761dee0cb.png)
I think the extracted trend using gaussian filtering on sparse grid is still correct here (gaussian filtering shouldn't be used on a nearest neighbour interpolated grid). We see the red dot again and a part of the dam is blue meaning subsiding about 2mm - we see it on the unfiltered unwrapped phase too so it's ok.

That's interesting to compare this result to a different one for the same area:
![image](https://user-images.githubusercontent.com/7342379/188069962-434b4779-5dcf-429d-8035-7e0b29644c09.png)
Occasionally, the total coherence for the area is much less. How is it possible? Does it mean hard atmospheric conditions maybe? Or could it be related to a some seismic movements (this area is techtonically active)? That's not surprising we see strong inconsistencies at the top left corner of the images where coherency is low. I suppose this is a "breathing" underground  hot water reservoir at this place but there is the questing how to detect the movements accurately when the coherency is low for the times when the events happening. Maybe seismic-induced surface micro-tremor is the source of the low coherency. Is there any method to work on the areas when coherency is too low sometimes while it's high usually?

**Comment by Xiaohua-Eric-Xu** [comment]
> The dam has good enough correlation and it's surrounded by lots of low-coherent areas.

This is the reason I asked about interpolation. You target seems to be very close to the dam so I thought maybe interpolation could help avoid unwrapping errors. 

> Occasionally, the total coherence for the area is much less. How is it possible? Does it mean hard atmospheric conditions maybe?

Could it be due to larger perpendicular baseline or longer time-span? Sometimes a strong rain event could also cause a drop in coherence but comes back with time. The top left corner looks like phase unwrapping error to me.  You should be able to get rid of such with near-neighbor interpolation over low coherence pixels. 

> Is there any method to work on the areas when coherency is too low sometimes while it's high usually?

Weight the data with coherence so some pairs have lower contribution to the final velocity or time-series.

**Comment by mobigroup** [comment]
Thanks for the insights! Without decimation and using two different correlation thresholds (0.2 for stack correlation mask and 0.1 for unwrapping threshold for each separate interferogram) the results look better while the calculations are hard. Your idea about a rain is very interesting because it explains how an average scene correlation could be affected. About unwrapping errors - sure we see some of them but sometimes persistent scatters detected occasionally moving far outside of the main trend. Maybe that’s related to cars or other small not stationary metallic objects.

**Comment by mobigroup** [comment]
See below the same results without decimation and lower coherency threshold:
![image](https://user-images.githubusercontent.com/7342379/188365618-3ea5d441-5683-47f3-ae59-1cf4bec88596.png)

![image](https://user-images.githubusercontent.com/7342379/188365084-4a51e282-9e9d-4bab-bd9a-da112ac67723.png)

The top picture looks strange a bit but let's pay attention to the small scale. Actually, it's ok:

![image](https://user-images.githubusercontent.com/7342379/188367924-aaa4a55b-2e6d-4ec4-8bc7-7ca536f8fc08.png)

Maybe do you have some suggestions how to enhance the unwrapped results? Are these millimeter-scale displacements real or just numerical artefacts? I can't find fine-scale interferometric displacements analysis explaining the nature of all the patterns. In the GMTSAR book the scale is not so fine as it used above.

**Comment by Xiaohua-Eric-Xu** [comment]
Maybe residual atmospheric noise? You removed large scale feature, which likely is the low-wavenumber part of the atmospheric spectrum. The hight-wavenumber part is smaller, but still considerable.

**Comment by mobigroup** [comment]
Yes, it's highly likely we see a lots of the residuals. That's not a problem of course because these can be compensated on a timeseries. Maybe we see an influence from low-height turbulence flows because the scale is small (from hundreds of meters and up to some kilometers) which are by the nature overfitted to topography. At the same time it looks interesting to detect some other dependencies if that's possible. Some circle patterns look related to correlation map and I suppose it's possible in case of vertical hot air flows (high coherency rocky areas have higher temperature while forested areas with low coherency have low temperature). Anyway, all the effects highly likely are not prezented on the sufrace but in the air only.
