### ISSUE TITLE
Error detected! Stitching multiple frames and/or cropping one frame to define a smaller region.

### ISSUE THREAD

**Issue by KumarKrishan** [gmtsar/gmtsar#425]
Script "organize_files_tops_linux.csh with mode 1 and 2, is not responding accordingly. Plz take a look.

[oft_mode1.log](https://github.com/gmtsar/gmtsar/files/9476437/oft_mode1.log)
[oft_mode2.log](https://github.com/gmtsar/gmtsar/files/9476438/oft_mode2.log)

**Comment by Xiaohua-Eric-Xu** [comment]
A few things to be concerned here
1) did you output the errors as well with `>&` ?
2) `azi_2 has to be larger than azi_1  ` this seems to be indicating you have the two pins in an incorrect order.

**Comment by KumarKrishan** [comment]
Yes, i have 
bash: syntax error near unexpected token `newline'
I have putted the both pins in correct order for Ascending, as i am using Ascending data.

**Comment by Xiaohua-Eric-Xu** [comment]
The error comes from these lines below in organize_files_tops.csh. So likely something's incorrect with your pin, e.g. you swapped lon lat? or giving it an incorrect values, etc.
```
135         set tmpazi = `echo $pin1 | awk '{print $1,$2,0}' | SAT_llt2rat tmp2.PRM 1 | awk '{printf("%d",$2+0.5)}'`
...
137         shift_atime_PRM.csh tmp2.PRM $tmpazi
```

**Comment by KumarKrishan** [comment]
I want to stitch two consecutive frame, have same date of acquisition.
Then, crop for a smaller region.
I have successfully gained the results when i have area covered by single frame. In that, pins order was set for ascending. I run the throughout process for ascending successfully.
Now, i am having the area covering two frames and getting the issue.

[oft_mode1.log](https://github.com/gmtsar/gmtsar/files/9503874/oft_mode1.log)
[oft_mode2.log](https://github.com/gmtsar/gmtsar/files/9503875/oft_mode2.log)
After swapping
[oft_mode1.log](https://github.com/gmtsar/gmtsar/files/9503933/oft_mode1.log)
[oft_mode2.log](https://github.com/gmtsar/gmtsar/files/9503934/oft_mode2.log)

**Comment by Xiaohua-Eric-Xu** [comment]
Could you share your inputfiles? pins.ll and filelist. 

What's the operating system of your machine?

**Comment by KumarKrishan** [comment]
[SAFE_filelist.pdf](https://github.com/gmtsar/gmtsar/files/9523702/SAFE_filelist.pdf)
[pins.ll.pdf](https://github.com/gmtsar/gmtsar/files/9523703/pins.ll.pdf)

Ubuntu 20.04.5 LTS

**Comment by Xiaohua-Eric-Xu** [comment]
You said that this is for ascending data right? However, the first pin's latitude is 30.54 while the second is 30.18. This is the order for descending scenario I think. Ascending tracks usually goes southeast to northwest.

**Comment by KumarKrishan** [comment]
Thank you @Xiaohua-Eric-Xu !
It's done. Exactly the problem was with pins.ll, i tried it 6-7 times and now, i successfully completed it. 
Again, thank you so much.
