### ISSUE TITLE
[Help]: merge_batch.csh error

### ISSUE THREAD

**Issue by raviexplorer** [gmtsar/gmtsar#426]
I am trying to merge sub -swaths but I am getting this error. I am attaching my merge_list as txt file. Can anyone help me resolve this? 

merge_batch.csh merge_list batch_tops.config
cd: Too many arguments.
cd: Too many arguments.

[merge_list.txt](https://github.com/gmtsar/gmtsar/files/9479315/merge_list.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure. What's in your merge/day1_day2 folder? Anything generated there?

**Comment by raviexplorer** [comment]
Only the folder corresponding to the first line of merge list got generated. Then this error occurs and processing stops.

**Comment by raviexplorer** [comment]
batch_tops.config  dem.grd  supermaster.PRM  tmp.filelist
These are the files on the first day1_day2 folder

**Comment by raviexplorer** [comment]
Please help me, I can't find any solution to this

**Comment by Xiaohua-Eric-Xu** [comment]
I think the first one did not got ran either. The error likely comes from this line in merge_batch.csh
```
 55     cd $dir_name
```
could you run the command again with `csh -x`, and send the log?

**Comment by raviexplorer** [comment]
Thank you Eric for your suggestion but my error already got resolved. The problem was a space in my hard disk name.

**Comment by raviexplorer** [comment]
Thanks
