### ISSUE TITLE
[Help]: Couldn't open master.PRM

### ISSUE THREAD

**Issue by Uncleyyyyy** [gmtsar/gmtsar#427]
When using organize_files_tops_linux.csh stitching my frames together, it fails and reports that:

_Working on subswath 1 ...
ln: failed to create symbolic link './s1a-iw1-slc-vh-20220117t111101-20220117t111126-041500-04ef67-001': File exists
 Couldn't open xml file: 
 tmp1.PRM 
couldn't open master.PRM_ 

**System and software version:**
 - OS: Ubuntu 20.04 LTS
 - GMTSAR version: 6.2

**Comment by Xiaohua-Eric-Xu** [comment]
1. check whether the files are readable to you.
2. remove the symbolic link before you run as it may be created from previous run and could be broken already.

**Comment by Uncleyyyyy** [comment]
> 

The *SAFE directories have both read and write permissons for all users, but I still can't run this script successfully. And before I run this script, I just unzipped the .zip files to the .SAFE files, so there should be no any sym links I think.

**Comment by Xiaohua-Eric-Xu** [comment]
Did that happen in the middle of the processing or it happened at the start? Also, if you didn't create any link, the system would not be warning you about `File exists`, right?
`ln: failed to create symbolic link './s1a-iw1-slc-vh-20220117t111101-20220117t111126-041500-04ef67-001': File exists`
Other things to check is your permission to write at the directory you are running organize_files_tops.csh, and whether you have enough storage. 

You could also check by trying to edit this file s1a-iw1-slc-vh-20220117t111101-20220117t111126-041500-04ef67-001.xml. It has to be related to the permission issue as other wise the program wouldn't say `Couldn't open xml file:` (this calls fopen in C).

```
 122     if ((XML_FILE = fopen(argv[1], "r")) == NULL)
 123         die("Couldn't open xml file: \n", argv[1]);
```

**Comment by Uncleyyyyy** [comment]
I noticed that it happened at the very start, and I can open and edit the .xml file manually, so I think the permission is not the reason. Maybe I should attach the whole error log for you to have a check. Thanks for helping!
[log_S1A_041405.txt](https://github.com/gmtsar/gmtsar/files/9553979/log_S1A_041405.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Could you share the command you ran? Also your filelist, your pins.ll.

**Comment by Uncleyyyyy** [comment]
> Could you share the command you ran? Also your filelist, your pins.ll.

I think there is nothing wrong with my filelist or pinlist, so I have modified my code. After trying some times, I find if I run oft_linux.csh with mode 2 directly instead of mode 1, the process will go on well. The polarizetion of my data is VV+VH, and I think this is the reason why mode 1 can't work. Am I right?

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, I don't think the polarization mode will affect the script. The error above is not dependent on whether it's vv or hh as long as you specify the right observation_mode (i.e. vv, hh, vh or hv). 

> You could also check by trying to edit this file s1a-iw1-slc-vh-20220117t111101-20220117t111126-041500-04ef67-001.xml. It has to be related to the permission issue as other wise the program wouldn't say `Couldn't open xml file:` (this calls fopen in C).
> 
> ```
>  122     if ((XML_FILE = fopen(argv[1], "r")) == NULL)
>  123         die("Couldn't open xml file: \n", argv[1]);
> ```

**Comment by july-H** [comment]
Have you solved the problem? I have also encountered the same problem as you

**Comment by Xiaohua-Eric-Xu** [comment]
Please share the command you used and a log file too.

**Comment by geo-james-wilson** [comment]
I had a similar error where the raw .xml and .tiff files could not be located when running create_frame_tops.csh. I had to specify the version in /gmtsar/csh/create_frame_tops.csh. The command "which create_frame_tops.csh" returns the version in /bin. I'm running Ubuntu 22.04. Not sure what causes the issue, but it fails to append the ".xml" or ".tiff" to the basename so it can't find the source files.

original_cmd = 'create_frame_tops.csh SAFE.list %s %s 1'%(local_eof, llpins)
new_cmd = '/usr/local/GMTSAR/gmtsar/csh/create_frame_tops.csh SAFE.list %s %s vv'%(local_eof, llpins)

**Comment by Xiaohua-Eric-Xu** [comment]
This is strange, i just could not imagine why a specific shell script could locate files while others couldn't.
