### ISSUE TITLE
[Help]: my ymax of landmask always not fit，but i really input ymax from grd file

### ISSUE THREAD

**Issue by jerry7nol** [gmtsar/gmtsar#428]

**Comment by joejoe03050709** [comment]
![@PLHWDDJLAND82SQQB`)DWL](https://user-images.githubusercontent.com/111356557/188589457-a55c2cde-aad2-4c89-b864-a651cb7655ee.png)

**Comment by Xiaohua-Eric-Xu** [comment]
To create a landmask, you need to have a dem that fully cover your image. See below the lines in landmask.csh.
```
 28 gmt grdlandmask -Glandmask.grd `gmt grdinfo -I- dem.grd` `gmt grdinfo -I dem.grd`  $V -NNaN/1 -Df
 29 proj_ll2ra.csh trans.dat landmask.grd landmask_ra.grd
 30 gmt grdsample landmask_ra.grd -Gtmp.grd -R$1 -I4/8 -nl+t0.1
```

**Comment by joejoe03050709** [comment]
oh, thanks sir

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu hi sir, emmmm,i changed the dem that full cover(more than 10 times), but it just changed y to x, do it about steps without right dem before ?

**Comment by Xiaohua-Eric-Xu** [comment]
Any log that I can refer to?

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu sir ，there is step and AI and dem

![1PCSP({7P 4(V FPIC9XUBH](https://user-images.githubusercontent.com/111356557/189005283-e7c05456-7674-4b27-a2fb-6a6f6f8d7210.png)
![Y2OVY{`35UYM{`3GB 8YH`I](https://user-images.githubusercontent.com/111356557/189005300-4ce54ef5-daea-4995-8056-eb58c229f025.png)
![F)5@M%VJ{@%~7AL}`ALZ`PI](https://user-images.githubusercontent.com/111356557/189005317-5f0ff65c-d599-40a7-a5f0-33f62073fe77.png)

**Comment by joejoe03050709** [comment]
![Y2OVY{`35UYM{`3GB 8YH`I](https://user-images.githubusercontent.com/111356557/189005491-4dac5b4b-42b5-4213-ba5b-20a0126b2895.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Do you have a trans.dat file with decent size in the merge directory?

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu yeah，there is, but i can't display it.. i think, my problem source from steps before without right dem.
and another question sir. if i chose a threshold in landmask unwrapping ，do this  equal to mask_def.grd

**Comment by Xiaohua-Eric-Xu** [comment]
Not really. mask_def.grd acts a bit differently for snaphu.csh and snaphu_interp.csh. In snaphu.csh it masks on coherence only and in snaphu_interp.csh it masks both coherence and phase. Landmask works on both phase and coherence, and so is the threshold. They overlap sometimes.

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu yeah，there is, but i can't display it.. i think, my problem source from steps before without right dem.
> and another question sir. if i chose a threshold in landmask unwrapping ，do this equal to mask_def.grd

Maybe you selected a trans.dat file from one of the subswaths? When doing merging, there should be a new trans.dat computed for merged product. I am not sure what's wrong here. Or maybe you could try re-producing the trans.dat file in the merge directory.

**Comment by joejoe03050709** [comment]
ok, sir ,it's worked when i use two swath to make landmask



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaohua(Eric) ***@***.***&gt;; 
发送时间: 2022年9月11日(星期天) 凌晨5:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gmtsar/gmtsar] [Help]: my ymax of landmask always not fit，but i really input ymax from grd file (Issue #428)






@Xiaohua-Eric-Xu是的，有，但我不能显示它..我想，我的问题来源于之前没有正确的步骤。
还有一个问题，先生。如果我选择了一个阈值在landmask展开#这样做等于mask_def.grd

也许你选择了一个trans.dat文件从一个sub swath？当进行合并时，应该为合并的产品计算一个新的trans.dat。我不知道这里出了什么问题。或者您可以尝试在merge目录中重新生成trans.dat文件。

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by joejoe03050709** [comment]
i think i get it, thank you so much sir




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaohua(Eric) ***@***.***&gt;; 
发送时间: 2022年9月11日(星期天) 凌晨5:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gmtsar/gmtsar] [Help]: my ymax of landmask always not fit，but i really input ymax from grd file (Issue #428)





 
Not really. mask_def.grd acts a bit differently for snaphu.csh and snaphu_interp.csh. In snaphu.csh it masks on coherence only and in snaphu_interp.csh it masks both coherence and phase. Landmask works on both phase and coherence, and so is the threshold. They overlap sometimes.

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu  sir, i have a question here. in the tutorial, i should mv baseline_table.dat to raw after preproc_batch_tops.csh 1. should mv new baseline_table.dat too after preproc_batch_tops.csh2 ?

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, you can do that. In fact I think you only need the new one if it is generated after with mode 2. It is used for pair selection later on but should not produce different results.

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu thank you so much sir, and ,where is toturial about atmosphere correction in GMTSAR i can found?

**Comment by Xiaohua-Eric-Xu** [comment]
I don't think we have a tutorial but generally it follows this paper below (with `-atm num_iteration` in `sbas`):
Tymofyeyeva, E., & Fialko, Y. (2015). Mitigation of atmospheric phase delays in InSAR data, with application to the eastern California shear zone. Journal of Geophysical Research: Solid Earth, 120(8), 5952-5963.

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu thanks, sir. i will learn it

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu sir, i have questions, can i tranlate just a unwrapping gram in radians  to in mm and NSWE directions？and which one step we chosed fixed points like PS, in mask? or we don't?

**Comment by Xiaohua-Eric-Xu** [comment]
To convert to LOS, try the attached script below. It basically contains just one line of GMT code.
[unwrap2los.csh.txt](https://github.com/gmtsar/gmtsar/files/9609813/unwrap2los.csh.txt)

**Comment by joejoe03050709** [comment]
thank you very much，sir

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu sir, sry for bother you, some interferograms of one of my subwath are do not well in deburst,, but some are good in same subwath, how to explain it, deburt is in preproc_batch_tops.csh mode2,right?

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu sir, and my parallel unwrap like in cycle, is it right? my csh is same tutorial and just add parallel tool.
![7}V8 GA)Z@E4V8@UMS BXQD](https://user-images.githubusercontent.com/111356557/191528671-08b1636f-a307-4352-93df-33dd83e9f9b5.png)

**Comment by Xiaohua-Eric-Xu** [comment]
> my parallel unwrap like in cycle

what do you mean by unwrap like in cycle? These messages are the same for every directory which means you have linked landmask_ra.grd over to each of them before. As long as you produced unwrap.grd for each directory correctly, these messages should not be a problem.

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu sir, sry for bother you, some interferograms of one of my subwaths are do not well in deburst,, but some are good in same subwath, how to explain it, deburst is in preproc_batch_tops.csh mode2,right?

I am not sure I get what you mean. You'll have to provide a bit more details for me to understand what really happened.

**Comment by joejoe03050709** [comment]
> I am not sure I get what you mean. You'll have to provide a bit more details for me to understand what really happened.
 my poor English，sry . i mean that deburst of some interferograms not well done 

![98O(8VMAX~H60`T%M1F)1%M](https://user-images.githubusercontent.com/111356557/191631519-5c1c59e3-54a5-4f7a-bc5d-aee3a08dc465.png)
how do i adjust

**Comment by joejoe03050709** [comment]
> I am not sure I get what you mean. You'll have to provide a bit more details for me to understand what really happened.
sir, i finished sbas step, is reference of all interferograms the first one? or the previous pair of each picture？
![03DV8)JHFLN(MC5%ES)K0Y1](https://user-images.githubusercontent.com/111356557/191652524-3de873bf-abbd-4697-b87b-0c72c521df97.png)

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu sry, i have too much questions, shouldn't places with a mask of NaN not appear?
i did a corr.mask, but result of unwrapping look like not good campare with landmask
![YYE3W_Q6LRDP7S HL`QD7EV](https://user-images.githubusercontent.com/111356557/191730355-c66c06b4-d1b4-4816-9d8b-d81df5c54088.png)
![WSU6R 2T{WP~}Q`$%{ZA%_I](https://user-images.githubusercontent.com/111356557/191730330-c3960ec2-0d5a-48c2-982f-42ba60d0cae0.png)

**Comment by Xiaohua-Eric-Xu** [comment]
If you would like to remove any burst discontinuities, you could use preproc_batch_tops_esd.csh, or turn on `spec_div` in the config file for p2p_processing.csh/p2p_S1_TOPS_Frame.csh.

**Comment by Xiaohua-Eric-Xu** [comment]
This is not related to deburst, but co-registration. Spectral diversity will help address such situation.

**Comment by joejoe03050709** [comment]
> If you would like to remove any burst discontinuities, you could use preproc_batch_tops_esd.csh, or turn on in the config file for p2p_processing.csh/p2p_S1_TOPS_Frame.csh.`spec_div` 
after preproc mode2？ ok, thanks sir, i am trying

**Comment by joejoe03050709** [comment]
https://github.com/gmtsar/gmtsar/issues/428#issuecomment-1254869350 
![YYE3W_Q6LRDP7S HL`QD7EV](https://user-images.githubusercontent.com/111356557/191874519-5afd50f4-5938-436f-8d0b-6943a6629fcb.png)
and this is my corr.mask

**Comment by joejoe03050709** [comment]
> If you would like to remove any burst discontinuities, you could use preproc_batch_tops_esd.csh, or turn on in the config file for p2p_processing.csh/p2p_S1_TOPS_Frame.csh.`spec_div`

thank you sir, i recover preproc_batch_tops.csh look like doesn't output align_table.ra.  any csh you recommond can replace that ？

**Comment by Xiaohua-Eric-Xu** [comment]
Oops, that's a remainder in the usage info from prior development of the script. Should've got deleted. Sorry about that. fe9c397c1d5aa3d6c95abe5b0e097cf7462991e9

**Comment by joejoe03050709** [comment]
> Oops, that's a remainder in the usage info from prior development of the script. Should've got deleted. Sorry about that. [fe9c397](https://github.com/gmtsar/gmtsar/commit/fe9c397c1d5aa3d6c95abe5b0e097cf7462991e9)

yeah，sir， it can't work, but doesn't matter, i am a newbie to insar. So what should i do for solving  burst discontinuities, or it not impact my quality？

**Comment by joejoe03050709** [comment]
> Oops, that's a remainder in the usage info from prior development of the script. Should've got deleted. Sorry about that. [fe9c397](https://github.com/gmtsar/gmtsar/commit/fe9c397c1d5aa3d6c95abe5b0e097cf7462991e9)

yeah,sir, it's not work, but it's doesn''t matter. i'm  a newbie to InSAR. So could i solve burst  discontinuities by turn on spec_div in the config file for p2p_processing.csh/p2p_S1_TOPS_Frame.csh or some ways else?

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, you can. Here's an example dataset where you can turn on spec_div and ionospheric correction to remove burst discontinuities and ionospheric phase for TOPS data. http://topex.ucsd.edu/gmtsar/tar/S1_ionosphere.tar
![image](https://user-images.githubusercontent.com/16844111/192363341-35f77ee5-ad85-44cf-8f61-e2e540ecb08d.png)

**Comment by joejoe03050709** [comment]
> Yes, you can. Here's an example dataset where you can turn on spec_div and ionospheric correction to remove burst discontinuities and ionospheric phase for TOPS data. http://topex.ucsd.edu/gmtsar/tar/S1_ionosphere.tar ![image](https://user-images.githubusercontent.com/16844111/192363341-35f77ee5-ad85-44cf-8f61-e2e540ecb08d.png)

Thank you very much sir.

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu  sry sir ,im too stupid to find righy way, spec_div,look like it's in config.
[batch_tops.config.txt](https://github.com/gmtsar/gmtsar/files/9653782/batch_tops.config.txt)
isn't it??there are all config in gmtsar/csh
![B69FDK_26 $D2~J70LAE)KA](https://user-images.githubusercontent.com/111356557/192480568-b1f048a2-d4e5-4daa-85f1-117ea6392bc1.png)

**Comment by joejoe03050709** [comment]
> Hi, for batch processing with ESD, use . For pair-wise processing with ESD, specify spec_div in config file and use . You could generate a config file with .`preproc_batch_tops_esd.csh``p2p_processing.csh``pop_config.csh`

thank you sir， i think i understand
