### ISSUE TITLE
Suggested improvement

### ISSUE THREAD

**Issue by geofis** [gmtsar/gmtsar#43]
On multiple occasions, while running some of the scripts of GMTSAR (e.g. intf_tops.csh), I receive the error "If expression syntax". I recently realized that this is because I use to edit one parameter while preserving a copy of it commented in the config file. For example, something like this:

```
#region_cut = 20/30/100/110
region_cut = 10/20/90/100
```

I guess that the easy solution is avoid adding copies of the parameters. However, I guess that adding a "^" symbol before the current pattern of grep expressions, would prevent many errors like the one commented (hopefully) without  affecting the rest of the code. For example, in intf_tops.csh, the grep expression that captures the `region_cut` parameter could be rewritten to something like this:

```
set region_cut = `grep '^region_cut' $2 | awk '{print $3}'`
```

**Comment by Xiaohua-Eric-Xu** [comment]
Thanks for the suggestion. We thought about that, and then realize someone will still continue commenting stuff by adding "#", such as `#^region_cut = 10/20/90/110`. Would be best if things are written in shell and called, but then it's actually less flexible, or as in Python/Matlab to set up variables easily. It is some old stuff we have to bear with shells.

**Comment by geofis** [comment]
Thanks Eric.

At least, I guess that a warning at the beginning of the default config file like "Please avoid commenting on parameters, such as '#region_cut = 20/30/100/110'" would be of help.

**Comment by Xiaohua-Eric-Xu** [comment]
Great! I'll add that line to pop_config.csh and update all the other config files.

**Comment by Xiaohua-Eric-Xu** [comment]
Done in 3a61944fa3fd5a1128afe7763103d053f0a5f6a7

**Comment by geofis** [comment]
Great! Thank you.

José
