### ISSUE TITLE
[Help]: To increase number of points in final deformation map.

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#430]
hie eric,
A recently published article talks about the comparison of GMTSAR and LicSABAS.
I am really enjoying working on GMTSAR as its has many advantages of parallel processing etc.
But how can we rectify this following problem as I also get few points in deformation map of my study region.
_In the implementation of the SBAS algorithm by GMTSAR, whenever there is one NaN value in any of the unwrapped phases, it will skip the whole column before doing the inversion and hence the pixel gets masked out._

https://www.nature.com/articles/s41598-022-17438-y
Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @shivamthescienceguy, here's how we usually handle the processing. 1) create a common coherence mask using a stacked coherence grid. 2) create a mask_def.grd using that coherence mask. 3) when unwrapping, use snaphu_interp.csh with a very low coherence threshold (e.g. 0.001) after linking mask_def.grd to your date1_date2 directory. 

These are to ensure that you mask on fixed number of pixels that are usually subject to random decorrelation. I tried to re-create G matrix for every pixel once, but that brings two problems. First is that it'll significantly slow down the sbas program. Second is that the atmospheric phase correction algorithm requires existence of nearby acquisitions (in time). Missing pixels will fundamentally change the logic and the assumption needed to perform that analysis will be violated. 

Nonetheless, one could easily produce i-sbas or n-sbas approach using Python or MATLAB. The only advantage of the c-program is that it runs faster for a given size problem. And we don't really want to give up that.

**Comment by mobigroup** [comment]
@shivamthescienceguy There is one more way to fill the missed values using nearest neighbor interpolation or some other. At the same time @Xiaohua-Eric-Xu propose more robust approach.
