### ISSUE TITLE
[Help]: How to read the aligned *.SLC into MATLAB workspace?

### ISSUE THREAD

**Issue by Twcumtb** [gmtsar/gmtsar#431]
Hi, 
   All the Sentinel-1 images have been aligned and I want to read the *.SLC into MATLAB workspace for further analysis. Does it have any Matlab scripts to do that?

**Comment by Xiaohua-Eric-Xu** [comment]
The .SLC file is a large chunk of binary short integers, set as real, imag, real, image. with the size being num_rng_bins x num_lines. These two parameters can be read from the aligned PRM file.
