### ISSUE TITLE
[Help]: p2p_S1_TOPS_Frame.csh not finish with RESORB

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#432]
**Describe the problem you met**
## I run

nohup 
p2p_S1_TOPS_Frame.csh 
S1A_IW_SLC__1SDV_20220826**T111711**_20220826T111739_044723_055705_8CCD.SAFE 
S1A_OPER_AUX_RESORB_OPOD_20220826T145219_V20220826**T110917**_20220826T142647.EOF 
S1A_IW_SLC__1SDV_20220907**T111712**_20220907T111739_044898_055CE8_151D.SAFE 
S1A_OPER_AUX_RESORB_OPOD_20220907T145215_V20220907**T110918**_20220907T142648.EOF 
config.s1a.txt vv 1

## then

[1] 104603
[2] 104604
[3] 104605
[3]    Done                          p2p_processing.csh S1_TOPS s1a-iw3-slc-vv-20220826t111713-20220826t111739-044723-055705-006 s1a-iw3-slc-vv-20220907t111714-20220907t111739-044898-055ce8-006 config.s1a.txt >& log
[2]  - Done                          p2p_processing.csh S1_TOPS s1a-iw2-slc-vv-20220826t111712-20220826t111738-044723-055705-005 s1a-iw2-slc-vv-20220907t111713-20220907t111738-044898-055ce8-005 config.s1a.txt >& log
[1]  + Done                          p2p_processing.csh S1_TOPS s1a-iw1-slc-vv-20220826t111711-20220826t111737-044723-055705-004 s1a-iw1-slc-vv-20220907t111712-20220907t111738-044898-055ce8-004 config.s1a.txt >& log
ln: No match.
ls: No match.
ls: No match.
ls: No match.
grep: S1_20220907_111712_F1.PRM: 没有那个文件或目录
grep: S1_20220826_111711_F1.PRM: 没有那个文件或目录
grep: S1_20220907_111712_F1.PRM: 没有那个文件或目录
cp: 无法获取"S1_20220826_111711_F1.PRM" 的文件状态(stat): 没有那个文件或目录

 error -  could not open file tmp.PRM 

grep: S1_20220907_111713_F2.PRM: 没有那个文件或目录
grep: S1_20220826_111712_F2.PRM: 没有那个文件或目录
grep: S1_20220907_111713_F2.PRM: 没有那个文件或目录
cp: 无法获取"S1_20220826_111712_F2.PRM" 的文件状态(stat): 没有那个文件或目录

 error -  could not open file tmp.PRM 

grep: S1_20220907_111714_F3.PRM: 没有那个文件或目录
grep: S1_20220826_111713_F3.PRM: 没有那个文件或目录
grep: S1_20220907_111714_F3.PRM: 没有那个文件或目录
cp: 无法获取"S1_20220826_111713_F3.PRM" 的文件状态(stat): 没有那个文件或目录

 error -  could not open file tmp.PRM 

Merging START
Number of Files to be merged is 3 
 Couldn't open PRM file: 
 tmp.PRM 
Number of Files to be merged is 3 
 Couldn't open PRM file: 
 tmp.PRM 
Number of Files to be merged is 3 
 Couldn't open PRM file: 
 tmp.PRM 
Merging END

grep: S1_20220826_111711_F1.PRM: 没有那个文件或目录
cp: 在"." 后缺少了要操作的目标文件
Try 'cp --help' for more information.
Recomputing the projection LUT...
grep: S1_20220826_111711_F1.PRM: 没有那个文件或目录

 error -  could not open file S1_20220826_111711_F1.PRM 

couldn't open master.PRM 
 
 Usage: SAT_llt2rat master.PRM prec [-bo[s|d]] < inputfile > outputfile  

             master.PRM   -  parameter file for master image and points to LED orbit file 
             precise      -  (0) standard back geocoding, (1) - polynomial refinenent (slower) 
             inputfile    -  lon, lat, elevation [ASCII] 
             outputfile   -  range, azimuth, elevation(ref to radius in PRM), lon, lat [ASCII default] 
             -bos or -bod -  binary single or double precision output (only output results within 
                             data coverage, PRM num_lines, num_rng_bins ) 
 
 example: SAT_llt2rat master.PRM 0 < topo.llt > topo.ratll    

 error -  could not open file S1_20220826_111711_F1.PRM 

MAKE LANDMASK -- START
REQUIRE FULL RESOLUTION COASTLINE FROM GMT

grdlandmask: GSHHG version 2.3.6
Derived from World Vector Shoreline, CIA WDB-II, and Atlas of the Cryosphere
Processed by Paul Wessel and Walter H. F. Smith, 1994-2016
grdlandmask: Nodes in water will be set to NaN
grdlandmask: Nodes on land will be set to 1
grdlandmask: Done!ng on block # 22062
gmtconvert: Selection led to no output columns.
gmtconvert: Selection led to no output columns.

## Did I choose the error orbit?

**Comment by swjiaotong-jyliu** [comment]
I found organize_files_tops.csh and create_frame_tops.csh.

**Comment by Xiaohua-Eric-Xu** [comment]
Do you have a log file from the F1/F2/F3 directories? They should be able to tell you what happened when each subswaths got processed and what are the associated error.
