### ISSUE TITLE
[Feature]:  Will the gmtsar support csk second product?

### ISSUE THREAD

**Issue by insar-dev** [gmtsar/gmtsar#433]
Will the gmtsar support csk second product?

**Comment by Xiaohua-Eric-Xu** [comment]
What specific product do you want to process? Currently it supports both raw and SLC format.

**Comment by insar-dev** [comment]
Does the gmtsar support Cosmo-SkyMed **Second** Generation now?

https://www.thalesgroup.com/en/worldwide/space/press_release/second-generation-cosmo-skymed-satellite-successfully-launched#:~:text=The%20second%2Dgeneration%20COSMO%2DSkyMed,the%20Italian%20Ministry%20of%20Defence.

**Comment by Xiaohua-Eric-Xu** [comment]
Wow, great, a new satellite! I am not sure since we haven't got any data. But if the format is the same (hdf5 as before), it should be supported. Or if there are changes, we can update based on that too. Do you know how to get some new CSK data?

**Comment by insar-dev** [comment]
hi, I have uploaded some data to google drive.
Two CSG data and one CSK data.
The format of CSG is hdf5,  there are some changes.
And I want to know whether csg and csk can create interferogram? Thanks.

**Comment by insar-dev** [comment]
google drive :https://drive.google.com/drive/folders/18x_UOTAU6w8DsCTVaPZlym6JgzCE3dd2?usp=sharing
