### ISSUE TITLE
[Help]: Data.in How to make it

### ISSUE THREAD

**Issue by omarwater98** [gmtsar/gmtsar#435]
I made a data.in file and copy from the measurement folder the name of the subswath 3 with the polarization "vv" of the 10 images that I am going to use, each one with its orbit file as indicated by ":" the manual in the page 14, but when running the command:

preproc_batch_tops.csh data.in dem.grd 1 &> pbt_mode1.log &

nothing is generated in the baseline_table.dat file

How can i create correctly the data.in manual form???

**Comment by Xiaohua-Eric-Xu** [comment]
Will be answered in the discussion page you opened earlier.
