### ISSUE TITLE
[Help]: how to evaluate correction.grd quality

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#439]
Dear Sir and Madam.

I run
···
correct_insar_with_gnss.csh S1_$fst_date'_ALL_F1'.PRM unwrap_GACOS_detrended.grd gnss_los.rad 25000
···

<img width="253" alt="image" src="https://user-images.githubusercontent.com/86451834/190460613-0b562baf-e097-4315-916d-55682c77effa.png">

Is 25000  too big? 

I turn it down 10000
it seem error.
![SZOZ XC{M CT6(R)7ZD9K9](https://user-images.githubusercontent.com/86451834/190469007-40a37205-97b7-4c81-a850-71fe61e26e7a.png)

<img width="475" alt="image" src="https://user-images.githubusercontent.com/86451834/190467637-9c8d1009-5960-429d-9214-e6d57cebe5fb.png">

I counted the phase after corecction of the  time1_time2 + the time2_time3 phase.grd -time1_time3 phase.grd

mostly 0

Does it mean that the fitting is successful?

thanks for your help.

**Comment by swjiaotong-jyliu** [comment]
<img width="187" alt="image" src="https://user-images.githubusercontent.com/86451834/190469350-a163eaf0-c594-4e6e-9487-2d5ade2a183b.png">


gnss_los.rad
```
13881.000867561	6390.640071473 0.202

31694.176818783	9542.834482556 0.985

15920.569945589	2800.748079460 0.860

19998.652601627	5015.493710744 1.275

5900.957725209	1985.701914395 0.852

6828.950966194	5816.162592806 1.625

26548.742352637	13998.023636942 0.543

25849.393121087	15003.756986095 0.860

25847.381259941	5289.061320867 0.305

7720.077787460	5602.517340764 1.313

13243.727545149	9420.396698275 1.647

27383.704089125	7966.544072405 1.457

21653.707458298	8249.775253117 1.161

11292.288704764	7666.239223003 1.797

6068.919489664	3918.175354018 1.330

19342.908865615	11525.120924882 2.301

21760.672721624	11158.692964383 0.908

24925.437440420	5981.840470406 1.537

13817.991466468	8984.339425297 0.953

9791.269772376	10260.028404518 1.368

14354.389367192	6122.167970674 0.899

12106.691664796	3250.376259496 1.032
```


Maybe reference points are too much . It looks discontinuous.

**Comment by Xiaohua-Eric-Xu** [comment]
The filter-wavelength parameter basically determines to what level you'll trust GNSS data. If the station distribution is averagely 20km spaced in your region, then you could use 40km to be safe. 10km may be too small for any known condition.

**Comment by omarwater98** [comment]
.
