### ISSUE TITLE
GPS observations to compare displacement

### ISSUE THREAD

**Issue by geofis** [gmtsar/gmtsar#44]
Hello.

This is more of a question than an issue. Sorry to post this here, but after reading the GMTSAR documentation and the associated papers, I couldn't figure out how to proceed.

I want to use GPS observations to compare the displacement obtained from a SBAS workflow of Santo Domingo city (velocity map below; I have the displacement maps too). I also attached the workflow followed, which might help someone else.

I generated the velocity map processing 13 S1 scenes from the period 2019 (August) to 2020 (June). I only have 3 GPS observations of the time period analyzed, and I'm aware that they aren't enough for validation, but those observations are the only ground data I have. My question is: How can I use my GPS data to perform a minimum comparison? I read in one of the SBAS reference papers that the points need to be converted to LOS, so I guess I'll need to use proj_ll2ra_ascii.csh, but I'm not fully aware on how to proceed.

Any insights would be greatly appreciated.

![bare_result_4](https://user-images.githubusercontent.com/13460617/89715136-c8b41b80-d971-11ea-8331-eaad14c4f8de.jpg)

[executed.txt](https://github.com/gmtsar/gmtsar/files/5045580/executed.txt)

**Comment by dsandwell** [comment]
Hi Jose,

Look like an interesting map with some isolated subsidence areas perhaps related to groundwater pumping.

1) Get the three positions of the GPS sites 

lon, lat, height.

The value for the height is not critical and zero will work.

2) In the int/*/ directory run these three points through

SAT_look  master.PRM < GPS.llh > GPS.llhenu

This will provide a look vector for each point.  They will be very similar look vectors

3) Write a script to take the dot product of the look vector and the GPS time series to get an LOS time series.

4) Run grdtrack on the *_ll.grd files to extract LOS displavement or velocity and compare.

The three GPS points could be used to find the overall trend error in the LOS data.

We should add some documentation on how to do this.

David




> On Aug 8, 2020, at 9:27 AM, José Ramón Martínez Batlle <notifications@github.com> wrote:
> 
> 
> Hello.
> 
> This is more of a question than an issue. Sorry to post this here, but after reading the GMTSAR documentation and the associated papers, I couldn't figure out how to proceed.
> 
> I want to use GPS observations to compare the displacement obtained from a SBAS workflow of Santo Domingo city (velocity map below; I have the displacement maps too). I also attached the workflow followed, which might help someone else.
> 
> I generated the velocity map processing 13 S1 scenes from the period 2019 (August) to 2020 (June). I only have 3 GPS observations of the time period analyzed, and I'm aware that they aren't enough for validation, but those observations are the only ground data I have. My question is: How can I use my GPS data to perform a minimum comparison? I read in one of the SBAS reference papers that the points need to be converted to LOS, so I guess I'll need to use proj_ll2ra_ascii.csh, but I'm not fully aware on how to proceed.
> 
> Any insights would be greatly appreciated.
> 
> 
> executed.txt
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by geofis** [comment]
Hi David,

Thank you for you response. I appreciate the detailed explanation about how to calculate the LOS displacement/velocity from my GPS data. I will try it out.

Regarding the map, I also appreciate your insights. Since there is not much information publicly available on groundwater pumping, I will do a more in-depth search, perhaps visiting the water utility. I am not too optimistic about finding significant data, but at least I will try.

Some of the subsidence areas in the NE are possibly related to the construction of the boarding stations and the towers of a recent cableway infrastructure.

Best regards.

José Martínez
Researcher,
Autonomous University of Santo Domingo

**Comment by geofis** [comment]
Hi David.

I projected the CORS displacements onto the satellite LOS following the procedure suggested by you. I generated the coordinates of each day using moving average and trying several window widths (7, 14, 30 days). I performed my computations in R using the [.pos files from RDSD CORS](https://www.unavco.org/instrumentation/networks/status/nota/data/RDSD). I can share my script if needed. Below is a screenshot of a data frame showing the comparisons (all units in mm, *rms = 9.6*):

![image](https://user-images.githubusercontent.com/13460617/89828028-749e6800-db26-11ea-982f-02147b7395e1.png)

![image](https://user-images.githubusercontent.com/13460617/89830069-9e0cc300-db29-11ea-9b34-a07fbf535e15.png)

I guess that I hit a snag, or perhaps there is preliminary evidence to discourage the use of this CORS station for confirmation purposes. I was already aware of the errors in the height value of the CORS. In intervals of a few days, in fact from one day to another, differences in height can reach up to 20 mm. In addition, many positions of the timespan analyzed were obtained from suppf solutions. Thus, I guess that SBAS vertical displacement is more accurate than the corresponding CORS value, at least in my case.

I would appreciate any insights.

Best.

**Comment by geofis** [comment]
I made some progress on the comparison of the SBAS results with the GNSS data. Using the atmospheric correction algorithm (with 5 iterations), the displacement maps look much better.

The magnitude of the GNSS vectors (projected onto LOS vector) and that of the SBAS displacement vectors, show a significant correlation. In addition, the mean of the differences between both vectors are not significant.

I noticed that the atmospheric correction algorithm reduced errors in two scenes (one in late 2019 and one in early 2020).

Below I included the table showing the comparison, and further down I pasted the results from the comparison.

![image](https://user-images.githubusercontent.com/13460617/90035616-ffe73d00-dc8f-11ea-8823-63d668114bb4.png)

```
> t.test(comparison$disp_gps_projected_onto_los, comparison$disp_los_pixel, paired = T)

	Paired t-test

data:  comparison$disp_gps_projected_onto_los and comparison$disp_los_pixel
t = 1.5957, df = 12, p-value = 0.1365
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -1.017559  6.586812
sample estimates:
mean of the differences 
               2.784627 

> t.test(comparison$disp_gps_projected_onto_los, comparison$disp_los_pixel)

	Welch Two Sample t-test

data:  comparison$disp_gps_projected_onto_los and comparison$disp_los_pixel
t = 1.1242, df = 20.883, p-value = 0.2737
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -2.368170  7.937423
sample estimates:
mean of x mean of y 
-10.82489 -13.60952 

> cor.test(comparison$disp_gps_projected_onto_los, comparison$disp_los_pixel)

	Pearson's product-moment correlation

data:  comparison$disp_gps_projected_onto_los and comparison$disp_los_pixel
t = 2.1617, df = 11, p-value = 0.05355
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.007089131  0.843303186
sample estimates:
     cor 
0.546029 

> plot(comparison$disp_gps_projected_onto_los, comparison$disp_los_pixel)
```

**Comment by dsandwell** [comment]
Hi Jose,

The results look good.  I’m not sure how to read all the tables.  When you do the atmospheric correction, the 2 dates at the start and the end of the InSAR time series won’t have a good correction.  You could add 5 scenes at the start of the time series before the GNSS data start to provide a better correction for the starting scene.  Of course you will need to subtract the displacement from the first scene from all the others to match the GNSS epoch.

David

> On Aug 12, 2020, at 8:53 AM, José Ramón Martínez Batlle <notifications@github.com> wrote:
> 
> 
> I made some progress on the comparison of the SBAS results with the GNSS data. Using the atmospheric correction algorithm (with 5 iterations), the displacement maps look much better.
> 
> The magnitude of the GNSS vectors (projected onto LOS vector) and that of the SBAS displacement vectors, show a significant correlation. In addition, the mean of the differences between both vectors are not significant.
> 
> I noticed that the atmospheric correction algorithm reduced errors in two scenes (one in late 2019 and one in early 2020).
> 
> Below I included the table showing the comparison, and further down I pasted the results from the comparison.
> 
> 
> > t.test(comparison$disp_gps_projected_onto_los, comparison$disp_los_pixel, paired = T)
> 
> 	Paired t-test
> 
> data:  comparison$disp_gps_projected_onto_los and comparison$disp_los_pixel
> t = 1.5957, df = 12, p-value = 0.1365
> alternative hypothesis: true difference in means is not equal to 0
> 95 percent confidence interval:
>  -1.017559  6.586812
> sample estimates:
> mean of the differences 
>                2.784627 
> 
> > t.test(comparison$disp_gps_projected_onto_los, comparison$disp_los_pixel)
> 
> 	Welch Two Sample t-test
> 
> data:  comparison$disp_gps_projected_onto_los and comparison$disp_los_pixel
> t = 1.1242, df = 20.883, p-value = 0.2737
> alternative hypothesis: true difference in means is not equal to 0
> 95 percent confidence interval:
>  -2.368170  7.937423
> sample estimates:
> mean of x mean of y 
> -10.82489 -13.60952 
> 
> > cor.test(comparison$disp_gps_projected_onto_los, comparison$disp_los_pixel)
> 
> 	Pearson's product-moment correlation
> 
> data:  comparison$disp_gps_projected_onto_los and comparison$disp_los_pixel
> t = 2.1617, df = 11, p-value = 0.05355
> alternative hypothesis: true correlation is not equal to 0
> 95 percent confidence interval:
>  -0.007089131  0.843303186
> sample estimates:
>      cor 
> 0.546029 
> 
> > plot(comparison$disp_gps_projected_onto_los, comparison$disp_los_pixel)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by geofis** [comment]
Thanks, David.

I appreciate your suggestions.

**Comment by LaMarcha** [comment]
Hello!

Interesting post. In your "executed.txt" file, may I ask what you did exactly in your "pin_to_zero.csh" script?
Is this about getting the value of an stable area and subtract it from the unwrap phase map?

**Comment by geofis** [comment]
Hello @esrivas17 

Answering your question, yes, the script `pin_to_zero.csh` (included below, inspired in an script written by Eric), cuts an area defined in radar coordinates from the unwrapped phase map, extracts the mean of that area, and then substracts it from the unwrapped phase to generate a pinned map in each directory located inside `intf_all`.

```
#!/bin/csh -f
# Run in parent directory

  foreach directory (`ls -d intf_all/*/ | awk '{print $1}'`)
    cd $directory
#    gmt grdcut unwrap.grd -R3512/3520/8296/8298 -Gtmp.grd
    gmt grdcut unwrap.grd -R4360/4368/4338/4340 -Gtmp.grd
    set mean = `gmt grdinfo tmp.grd -L | grep mean | awk '{print $3}'`
    echo "I am pinning unwrapped phase of $directory, which has a mean of $mean..."
    gmt grdmath unwrap.grd $mean SUB = unwrap_pin.grd
    cd ../../
  end
```

**Comment by esrivas17** [comment]
Thank you very much!

That's very useful!
