### ISSUE TITLE
[Help]: SBAS processing taking a lot of time

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#441]
Hie Eric,
One thing for which I am confused is that  sbas is taking more than 2 days and is still not complete for 175 images with 638 intf. Although it is taking 80 percent of the memory from my 64 gb ram system?
What could be the reason for the same?
How can we decrease the time for the same? Will having more RAM will help the sbas inversion process?

![Screenshot from 2022-09-21 13-11-20](https://user-images.githubusercontent.com/88940973/191445490-0adc4a1b-ae6b-4c7b-bde6-9b2a70aa3535.png)

Thanks.

**Comment by SteffanDavies** [comment]
Use sbas_parallel
