### ISSUE TITLE
[Bug]: Ubuntu 22.04 compilation issue

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#442]
How about Ubuntu 22.04 compilation? It doesn't work for me using GitHub CI runners while it's ok for Ubuntu 20.04 and Ubuntu 18.04.

**Comment by Xiaohua-Eric-Xu** [comment]
What's the bug message you got?

**Comment by mobigroup** [comment]
The log is available here: https://github.com/mobigroup/gmtsar/actions/runs/3095914832/jobs/5010856460 for the 1st (failed) test "S1A_Stack_CPGF_T173 (ubuntu-22.04, 3.7)" on step "Compile GMTSAR".

P.S. The continuous integration (CI) tests install GMTSAR on different Ubuntu versions and use different Python versions to compute results for S1A_Stack_CPGF_T173 example dataset using PyGMTSAR Python library. I'd send a pull request if you are ready to add CI tests to the project to have all the test results as badges on main page of the repository (and on any other page too):
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/7342379/191660444-8a5e4c68-9783-4387-994a-99a337640efd.png">

**Comment by simonst7** [comment]
Hi @mobigroup , the problem seems to be the the gcc compilation in ubuntu 22 . I installed time ago GMTSAR in a based ubuntu 22 OS and it worked well adding the flag `-z muldefs` to the config.mk (created with autoconf) in your `CFLAGS` and `LDFLAGS` variables. I remember that @Xiaohua-Eric-Xu  or something else wrote that solution before. Basically it allows multiple definitions when a symbol is defined multiple times.

**Comment by mobigroup** [comment]
@simonst7 Thanks for the information, in this case the problem should be fixed because it doesn't follow the documented installation. Also, it looks as a single problem against continuous integration (CI) tests.

**Comment by Xiaohua-Eric-Xu** [comment]
I was thinking of adding some of these flags (suggested by @SteffanDavies ) but they are not needed or not available for certain c-compliers. It seems only related to ubuntu systems later than 21.04.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu That's possible to resolve using "#ifndef" directive for conditional import in the code.

**Comment by mobigroup** [comment]
By the way, configure.ac includes outdated options:

```
...
configure.ac:39: warning: The macro `AC_CYGWIN' is obsolete.
[15](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:16)
configure.ac:39: You should run autoupdate.
[16](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:17)
./lib/autoconf/specific.m4:319: AC_CYGWIN is expanded from...
[17](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:18)
configure.ac:39: the top level
[18](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:19)
configure.ac:40: warning: The macro `AC_CANONICAL_SYSTEM' is obsolete.
[19](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:20)
configure.ac:40: You should run autoupdate.
[20](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:21)
./lib/autoconf/general.m4:2081: AC_CANONICAL_SYSTEM is expanded from...
[21](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:22)
configure.ac:40: the top level
[22](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:23)
configure.ac:42: warning: The macro `AC_LANG_C' is obsolete.
[23](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:24)
configure.ac:42: You should run autoupdate.
[24](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:25)
./lib/autoconf/c.m4:72: AC_LANG_C is expanded from...
[25](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:26)
configure.ac:42: the top level
[26](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:27)
configure.ac:156: warning: The macro `AC_HAVE_LIBRARY' is obsolete.
[27](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:28)
configure.ac:156: You should run autoupdate.
[28](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:29)
./lib/autoconf/libs.m4:138: AC_HAVE_LIBRARY is expanded from...
[29](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:30)
ax_lib_hdf5.m4:89: AX_LIB_HDF5 is expanded from...
[30](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:31)
configure.ac:156: the top level
[31](https://github.com/mobigroup/gmtsar/actions/runs/3110553562/jobs/5041857173#step:5:32)
configure.ac:414: warning: AC_OUTPUT should be used without arguments.
...
```

**Comment by mobigroup** [comment]
As a workaround this installation works on Ubuntu 18.04, 20.04, 22.04:
```
autoconf
./configure --with-orbits-dir=/tmp CFLAGS='-z muldefs' LDFLAGS='-z muldefs'
make CFLAGS='-z muldefs' LDFLAGS='-z muldefs'
make install
```

Please update the documentation because the manual edition of autogenerated files should not be recommended to anyone: it's not a safe way and it's mostly impossible on cloud (including CI testing) environments.

Also, my CI tests for MacOS and Ubuntu available here: https://github.com/mobigroup/gmtsar/tree/master/.github/workflows Ubuntu 18.04 will be unavailable from 1 Apr 2023 but it's still used for Google Colab environment so we need to have the tests on it. By the way, PyPI tests use PyGMTSAR library from PyPI and so will work as is for GMTSAR GitHub repository.

**Comment by SteffanDavies** [comment]
> As a workaround this installation works on Ubuntu 18.04, 20.04, 22.04:
> 
> ```
> autoconf
> ./configure --with-orbits-dir=/tmp CFLAGS='-z muldefs' LDFLAGS='-z muldefs'
> make CFLAGS='-z muldefs' LDFLAGS='-z muldefs'
> make install
> ```
> 
> Please update the documentation because the manual edition of autogenerated files should not be recommended to anyone: it's not a safe way and it's mostly impossible on cloud (including CI testing) environments.
> 
> Also, my CI tests for MacOS and Ubuntu available here: https://github.com/mobigroup/gmtsar/tree/master/.github/workflows Ubuntu 18.04 will be unavailable from 1 Apr 2023 but it's still used for Google Colab environment so we need to have the tests on it. By the way, PyPI tests use PyGMTSAR library from PyPI and so will work as is for GMTSAR GitHub repository.

I've been compiling GMTSAR on the cloud without any problems. I think I used sed sed to update the values inside a script to avoid human error from doing it in nano.

**Comment by mobigroup** [comment]
@SteffanDavies That’s not easy when you have no ssh access to the host and can only load the batch command config like to this one: https://github.com/mobigroup/gmtsar/blob/master/.github/workflows/ubuntu.yml
and check the log output. Otherwise what prevents you to make the CI tests to GMTSAR if it’s so easy for you?

**Comment by SteffanDavies** [comment]
> @SteffanDavies That’s not easy when you have no ssh access to the host and can only load the batch command config like to this one: https://github.com/mobigroup/gmtsar/blob/master/.github/workflows/ubuntu.yml and check the log output. Otherwise what prevents you to make the CI tests to GMTSAR if it’s so easy for you?

While I agree doing it manually is silly, what prevents you from putting two sed substitution commands after configure step of compilation? It seems your solution of adding cflags to make is much more simple though.

**Comment by mobigroup** [comment]
@SteffanDavies How to add the sed substitutions for the autogenerated file while you don’t have this file? To do it you need to run the cloud processing pipeline up to the configure command and copy the autogenerated config out by some way (and find and read GitHub documentation how to do it using artifacts, if we speak about GitHub Actions environment… on other ones there are different ways) and make the sed script and create the new processing pipeline… And maybe find that sed on your host is not compatible to the cloud one and you need to modify your sed script and repeat all the steps. Using the flags you follow the common way to manage your software on different architectures and operation systems and it works without lots of additional hassles.

**Comment by SteffanDavies** [comment]
> @SteffanDavies How to add the sed substitutions for the autogenerated file while you don’t have this file? To do it you need to run the cloud processing pipeline up to the configure command and copy the autogenerated config out by some way (and find and read GitHub documentation how to do it using artifacts, if we speak about GitHub Actions environment… on other ones there are different ways) and make the sed script and create the new processing pipeline… And maybe find that sed on your host is not compatible to the cloud one and you need to modify your sed script and repeat all the steps. Using the flags you follow the common way to manage your software on different architectures and operation systems and it works without lots of additional hassles.

I see. My experience on the cloud has been mostly using VMs with SSH but I understand your problem now.

**Comment by mobigroup** [comment]
@SteffanDavies I think it’s OUR problem when GMTSAR has no CI tests and documentation is not exact :)

**Comment by Xiaohua-Eric-Xu** [comment]
> By the way, configure.ac includes outdated options:

You may get rid of a number of them by running autoupdate or a newer version of GMTSAR. We are thinking of getting rid of CYGWIN stuffs but haven't done so yet.

Indeed CI testing is important, but as you may have noticed, we are a really small team with members having their own research projects. We were only able to test on Mac and certain versions of Ubuntu (used to have fedora too). That's why we rely on you guys to report to us what may fail the code. Or if anyone's willing to help with the testing, we are in big gratitude.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu That’s the reason to use CI tests on all commits instead of limited manual testing sometimes. I work single and I don’t have or need any Ubuntu host but I have the Ubuntu (and MacOS too) tests results always. CI testing on GitHub is extremely simple: we just add a so-named workflow file to describe a CI pipeline. In addition to testing it resolves the incomplete documentation issues when you really don’t know and remember how exactly to install the software on different OSes and architectures.

**Comment by mobigroup** [comment]
#447

**Comment by mobigroup** [comment]
For now you'd add the CI test results indicator to README.md (or any other markdown page). The real-time CI test indicator allows anyone to know the results (to prevent cloning the repo in failed state): 

[![GMTSAR](https://github.com/gmtsar/gmtsar/actions/workflows/gmtsar.yml/badge.svg)](https://github.com/gmtsar/gmtsar/actions/workflows/gmtsar.yml)

See below screenshots how to find the indicator markdown code:

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/7342379/192701152-c764f897-7690-4b64-868a-c9dbf36bb774.png">

<img width="445" alt="image" src="https://user-images.githubusercontent.com/7342379/192701263-35fcf5b1-c0e3-4700-b44d-b05b6c9b612d.png">

Also, I think it's helpful to add the link
https://github.com/gmtsar/gmtsar/blob/master/.github/workflows/gmtsar.yml
to the documentation for the complete compilation instructions for MacOS and Ubuntu. We can forgot to update our documentation but we always see when we need to update our CI scripts (thanks to the status badges).

**Comment by SteffanDavies** [comment]
Note that sbas_parallel script will not compile on Linux, extra steps are necessary after make install:

gcc -fopenmp -O2 -Wall -m64 -fPIC -fno-strict-aliasing -std=c99 -z muldefs -I/usr/include/gmt -I./ -I/usr/local/include -c -o sbas_parallel.o sbas_parallel.c
gcc -fopenmp -m64 -s -Wl,-rpath,/usr/lib/x86_64-linux-gnu -z muldefs sbas_parallel.o -L$PWD -lgmtsar -L/usr/lib/x86_64-linux-gnu -lgmt -llapack -lblas -lm -L/usr/local/lib -ltiff -lm -o sbas_parallel

**Comment by mobigroup** [comment]
@SteffanDavies Thanks for the addition, it should be documented of course. Note: S1A_Stack_CPGF_T173.tar.gz example uses "sbas" tool (but not "sbas_parallel").

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, you'll need to find a c-complier that supports openmp. The default gcc on Mac does not.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Is the sbas_parallel tool useful for now? I didn’t use it but I see error reports that it doesn’t work for a large interferograms stack even on well grade hardware. At the same time we can compute weighted least-squares solution for any stack even on 10 years old hardware using Python (actually every pixel can be computed separately so we have no RAM limitations).

**Comment by SteffanDavies** [comment]
> @Xiaohua-Eric-Xu Is the sbas_parallel tool useful for now? I didn’t use it but I see error reports that it doesn’t work for a large interferograms stack even on well grade hardware. At the same time we can compute weighted least-squares solution for any stack even on 10 years old hardware using Python (actually every pixel can be computed separately so we have no RAM limitations).

I use it all the time, otherwise SBAS and APS takes days (!). Thus I use a 64 core machine to reduce that to hours. Memory consumption can be over 200GB but I use -mmap in those cases to offload to the disk.

That separate pixel calculation and least squares method sounds amazing,, but I'm not a mathematician or signals expert so what's the concrete difference in the results for least-squares?

**Comment by mobigroup** [comment]
@SteffanDavies But how long timeseries do you mean? I tested PyGMTSAR on ~800 single subswath Sentinel-1 interferograms (3208x6094 grid) and it takes a few hours on Apple iMac (8 cores and 16 GB RAM). Using some decimation it will be ~1 hour or less.

See the example Jupyter notebook on Google Colab to compare GMTSAR SBAS results and PyGMTSAR solution: [GMTSAR example dataset S1A_Stack_CPGF_T173](https://colab.research.google.com/drive/1sljxm2jAMGXynq4EYam6Siz8OLcPLN0h?usp=sharing)

**Comment by Xiaohua-Eric-Xu** [comment]
Ideally, every round of least-square could be computed with the separate & compute approach. However, the atm-correction is a scene-based calculation which requires summing/subtracting the whole interferogram. Or in other words, the proposed approach will deteriorate the spatial correlation of atmospheric noise if -atm is turned on.

**Comment by SteffanDavies** [comment]
> @SteffanDavies But how long timeseries do you mean? I tested PyGMTSAR on ~800 single subswath Sentinel-1 interferograms (3208x6094 grid) and it takes a few hours on Apple iMac (8 cores and 16 GB RAM). Using some decimation it will be ~1 hour or less.
> 
> See the example Jupyter notebook on Google Colab to compare GMTSAR SBAS results and PyGMTSAR solution: [GMTSAR example dataset S1A_Stack_CPGF_T173](https://colab.research.google.com/drive/1sljxm2jAMGXynq4EYam6Siz8OLcPLN0h?usp=sharing)

I work with datasets spanning 6 months to 5 years, it really depends on if I'm performing continuos monitoring (6 months to a year every two weeks with new data) or historical study (longer time-series spanning years). 

I believe for 2 years of SLC in a single frame (maybe around 350 interferograms) with 4/1 decimation (minimum decimation for square grid) at 100m wavelength (25m spacing),  it took many hours to compute final sbas_parallel step with -atm at 3 on a 64 core machine. I don't even want to imagine how many days it would take without parallel computing...

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Spatial filtering for the atmospheric correction can be done on the each separate interferogram. After that we just need to compute the least-squares solution for the pixels timeseries.

**Comment by Xiaohua-Eric-Xu** [comment]
> @SteffanDavies But how long timeseries do you mean? I tested PyGMTSAR on ~800 single subswath Sentinel-1 interferograms (3208x6094 grid) and it takes a few hours on Apple iMac (8 cores and 16 GB RAM). Using some decimation it will be ~1 hour or less.

Based on my experiences, I don't think 8-core 16 RAM is enough to finish that job in < 1 hour. The RAM is not enough to takin the data. And calculation time is nowhere near close. If you mean running 8-interferogram for 100 times, that's different situation as the time-cost is n^2.

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu Spatial filtering for the atmospheric correction can be done on the each separate interferogram. After that we just need to compute the least-squares solution for the pixels timeseries.

Spatial filtering can, but the atm algorithm (in GMTSAR) could not. It requires a network if you read the details of the algorithm and they were done on a specific ranking related to the estimated atm noise level on each date. We thought about what you mentioned above a long time ago but did not move toward that direction.

**Comment by mobigroup** [comment]
The test notebooks shared here: https://github.com/mobigroup/YamchiDam/tree/main/notebooks
We don’t need to have 400 GB RAM to process 400 GB data of course. Use lazy computations to process data by chunks 256x256 pixels (with some overlapping when needed).

**Comment by mobigroup** [comment]
About -atm correction do you see any advantages of the used algorithm vs spatial filtering plus correlation-weighted least squares solution? As I remember your -atm algorithm can be split to a set of grid-based plus series-based operations but I didn’t try it because the algorithm limitations are too strong for me (the most interesting are nonlinear trends and movements).

**Comment by Xiaohua-Eric-Xu** [comment]
About large spatial filtering (what you did), it is not a universal tool to use for all cases. If you only care about short wavelength stuffs, go ahead and use it. Others, I don't recommend. A simple example is the subsidence in Central Valley, or any tectonic motion.

**Comment by mobigroup** [comment]
I don't think so. See https://en.wikipedia.org/wiki/Central_Valley_(California)
> Topography, major regions, and cities of the Central Valley
Length: 450 mi (720 km)
Width 40 to 60 mi (64 to 97 km)

Maximum widths is ~100km and the subsidence profile is not linear of course so long-wavelength spatial filtering 20+ km will work. For an inverse example you use short-wavelength 200m gaussian filter for interferogram calculation but still have some pixel-size outliers. Also, we can miss the spatial filtering step and use just classic trend removal as we discussed before. For the -atm correction you actually fit the timeseries to a linear trend and in border case it's the same as just linearly interpolate all the values between the first and the last points. Median filtering do the same even better because there are no issues on the start and end points and much faster of course plus even non-linear movements should be saved. When applied accurately the spatial filtering reduces amplitude of LOS changes and saves the trend in rolling window. There are a wide range of signal processing algorithms applicable to the pixel movements timeseries. For an example, seasonal movements produces easy detectable polyspectral responses almost independently of the signal noise level. Non-linear distrance correlation allows to find synchronous movements and so on. Actually, I'm interested in the explained above analyses but it was too hard to do with GMTSAR and I spend some time to build the easy and fast Python API suitable to process 5+ years Sentinel-1 SBAS series on a common laptop.
