### ISSUE TITLE
[Help]: Regarding SBAS parallel step

### ISSUE THREAD

**Issue by AmiraZakii** [gmtsar/gmtsar#443]
Hello, 
I started to use the pygmtsar and try to test the script you provide on my machine.  I was stuck in the SBAS parallel processing step due to an encoding error. should I change the SBAS.py can you help me, please?
![error1](https://user-images.githubusercontent.com/89259389/191532668-050bd553-f0a6-4662-b460-334bb7e62e77.JPG)
![error_2](https://user-images.githubusercontent.com/89259389/191532708-4b57c298-007a-4861-b6bb-12daa5dcaa1d.JPG)

**Comment by AmiraZakii** [comment]
Thanks Steffan, I will

**Comment by Xiaohua-Eric-Xu** [comment]
This specific python implementation is not done by us, so you'll have to contact the author of that repository.

**Comment by mobigroup** [comment]
@AmiraZakii Steffan and Eric are right, that's related to other GitHub project. Anyway, the error looks as attempt to use outdated Python 2.7 or similar. Use Python 3.7+ for the processing because older Python versions deprecated.
