### ISSUE TITLE
[help]: use different filter type

### ISSUE THREAD

**Issue by edszyman** [gmtsar/gmtsar#444]
I'm sure there is a simple solution to this, I just want to make sure I'm doing it as correctly as possible. I would like to use a kaiser filter, as opposed to the Gaussian filter, for TOPS processing. How would I go about making changes to filter.csh to implement the kaiser filter, or any filter for that matter. Thanks!

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, I am not sure whether there is an easy solution. But generally, after intf.csh, you'll get two file called real.grd and imag.grd (they get deleted after filter.csh). Then you can skip filter.csh and filter the data by yourself using `conv` I think (directly on real.grd, imag.grd to get realfilt.grd and imagfilt.grd, and on SLCs to get amp1.grd and amp2.grd). Then you'll be able to compute coherence, amplitude, phase, and phasefilt, etc. The grdmath commands could be find in filter.csh.

**Comment by edszyman** [comment]
So in filter.csh there are lines (121-122 & 132-133) where I am convolving a custom filter with the amplitudes and then the real and imaginary grids. The uncommented `conv` lines are my own, the original code is commented out in the lines above each set. The variable `custom_filter` is directed to an ascii file for a kaiser5x3 filter I made and placed in the ./share/filters directory, I formatted it to match what I saw in the gaussian filter files. 

I'm not sure whether or not I should be changing the `$az_lks` and `$dec_rng` variables to match the filter order or if I should leave them alone and let them be set through the config file and the p2p_S1_TOPS_Frame.csh command.

The current code is running and I'm waiting for the results, sorry I can't share them yet.

Thanks for your help!

<img width="721" alt="Screen Shot 2022-09-21 at 3 23 41 PM" src="https://user-images.githubusercontent.com/44045691/191593217-a73a2ac0-8e5a-482e-8aed-4063c964d0f8.png">

**Comment by Xiaohua-Eric-Xu** [comment]
$az_lks and $dec_rng are initial filters to donwsize the data. Basically convolving two gaussian filters will produce the same results as convolving on larger gaussian filter, but runs faster I think. 

Go ahead and complete the process. Would be interesting to learn what you find out.

**Comment by mobigroup** [comment]
> Basically convolving two gaussian filters will produce the same results as convolving on larger gaussian filter, but runs faster I think.

Actually, 2D Gaussian filter can be replaced by 2 1D gaussian filters applied sequentially and it's faster than the 2 2D filters combination. 

@edszyman GMTSAR applies gaussian filter kernel defined in meters (200m by default) using the two filters. Did you calculate the correct kernel matrix for your filter?

**Comment by edszyman** [comment]
@mobigroup I'm trying to apply a Kaiser filter instead of the Gaussian filter. The Kaiser filter is parameterized by a filter length and a shape parameter beta, as opposed to a length scale parameter in the Gaussian. I wrote a quick python script to create 2-D anisotropic Kaiser filters by taking the outer product of two independent 1-D Kaiser filters and formatting them to match GMTSAR filters. I'm pretty sure I'm computing the kernel matrix correct, but here is a sample 5x5:

<img width="735" alt="Screen Shot 2022-09-22 at 11 43 38 AM" src="https://user-images.githubusercontent.com/44045691/191793718-4d3239b8-4d44-47f5-b7cf-7ccf713fb1b1.png">

I believe I should be able to follow your advice about applying sequential 1-D filters to each coordinate since the Kaiser filter is symmetric and separable though.

**Comment by mobigroup** [comment]
@edszyman The filter is asymmetrical because the radar coordinates grid resolution is about 16m x 4m. So you define the filter kernel as 80m x 20m matrix.

**Comment by edszyman** [comment]
@mogigroup I'm decimating the interferogram 1x4 prior to filtering. But I feel like you're not really addressing the question and just nit picking minor points without providing any instruction whatsoever. So please include guidance in your next reply or I would prefer that you skip the reply all together.

**Comment by mobigroup** [comment]
@edszyman Ok, if you know all better, this is PyGMTSAR code to replace by your filter: https://github.com/mobigroup/gmtsar/blob/master/pygmtsar/pygmtsar/PRM.py#L1011-L1024
