### ISSUE TITLE
[Bug]: GF3

### ISSUE THREAD

**Issue by zhangdabao2020** [gmtsar/gmtsar#449]
**Describe the bug**
On line 122 of the file gmtsar/preproc/GF3_preproc/src/make_slc_gf3.c, the variable, width, should be assigned a value before being used.
On line 10 of the file gmtsar/Makefile, GF3 should be added at the end

**System and software version:**
 - GMTSAR version:v6.2.2

**Comment by Xiaohua-Eric-Xu** [comment]
Fixed by swapping line 122 and 123. 9b3a5dd036b7d34058538899f12362cb0ade2edf
Let me know if this is correct.
