### ISSUE TITLE
[Feature]:create_merge_input.csh 

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#452]
Hi, Professors!
I'd like to ask you a question.
root@gmtsar:/media/gmtsar/Elements/sar/merge# create_merge_input.csh intflist .. 2 >merge_list
ls: No match.
ls: No match.
ls: No match.
ls: No match.
ls: No match.
ls: No match.
ls: No match.
ls: No match.
ls: No match.
ls: No match.
How can I solve this problem, please

**Comment by Luvina0503** [comment]
I have solved the problem, thank you

**Comment by WY-SVG** [comment]
Hello, about running the script create_merge_input.csh, can you provide your specific command.
I would appreciate your reply very much.

**Comment by WY-SVG** [comment]
Hello, I also have such a problem, may I ask how you solve it?

> 我已经解决了问题，谢谢

**Comment by WY-SVG** [comment]
Hello, I also have such a problem, may I ask how you solve it?

> 我已经解决了问题，谢谢

**Comment by Xiaohua-Eric-Xu** [comment]
Could you check whether files in side your F2/intf_all/day1_day2 and F3/intf_all/day1_day2 directories? Could it be that some files did not got generated during your processing?
