### ISSUE TITLE
[Feature]: unwrap_intf.csh

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#453]
Hi! Dear Professors  
I had some problems with the unwrap process
I created a unwrap_intf.csh

#!/bin/csh -f
# intflist contains a list of all date1_date2 directories
foreach line (`awk '{print}' intflist`)
cd ${line}
snaphu.csh 0.1
cd ..
end

My research area does not need clipping, so there is no clipping range.
When I run this command, it shows that snaphu.csh is not formatted correctly
root@gmtsar:/media/gmtsar/Elements/sar/merge# unwrap_intf.csh intflist.

How should this problem be solved, thank you

**Comment by SteffanDavies** [comment]
Could you link a screenshot of the error?

**Comment by Luvina0503** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gmtsar/gmtsar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 晚上9:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gmtsar/gmtsar] [Feature]: unwrap_intf.csh (Issue #453)





 
Could you link a screenshot of the error?

**Comment by SteffanDavies** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gmtsar/gmtsar" ***@***.***&gt;; 发送时间:&nbsp;2022年9月29日(星期四) 晚上9:19 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gmtsar/gmtsar] [Feature]: unwrap_intf.csh (Issue #453) Could you link a screenshot of the error? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

There is something wrong with your comment. Also I can't read Chinese, sorry.

**Comment by Luvina0503** [comment]
![$S69ZIXUC{T$)(SXX@_ATON](https://user-images.githubusercontent.com/114629377/193049004-e019b636-f69c-4763-a812-77750a4b844e.png)

![G4CT I%~H47MS~ 9$14QEN6](https://user-images.githubusercontent.com/114629377/193049146-cc37e353-aea9-4610-b0a0-870b080c7c9c.png)

**Comment by SteffanDavies** [comment]
Try adding maximum discontinuity:

snaphu.csh 0.1 0
or
snaphu_interp.csh 0.1 0

**Comment by Luvina0503** [comment]
ok. i get it. thank you very much

**Comment by SteffanDavies** [comment]
Did it work then?

**Comment by Luvina0503** [comment]
Yes.

**Comment by SteffanDavies** [comment]
> Yes.

Great, you can close the issue now.
