### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by MohamedAbdrabou2022** [gmtsar/gmtsar#454]
Hi All,

I just installed the Ubuntu virtual machine with GMTSAR pre-installed and reached to this step after writing the codes below

sudo apt install csh subversion autoconf libtiff5-dev libhdf5-dev wget
sudo apt install liblapack-dev
sudo apt install gfortran
sudo apt install g++
sudo apt install libgmt-dev
sudo apt install gmt-dcw gmt-gshhg
sudo apt install gmt

After that I reached to the following screen shot.
![Capture](https://user-images.githubusercontent.com/113559504/193132209-56d8da5b-d09f-401e-81dd-3207ff1340ba.JPG)

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

gmt is already the newest version (6.1.1+dfsg-1build1).

0 upgraded, 0 newly installed, 0 to remove and 73 not upgraded.

What I must do to go for:
1- how to download data?
2-How to run processing to get awesome interferograms?

By chance I am using Ubuntu21.04
Thanks in advance,
Mohamed

**Comment by Xiaohua-Eric-Xu** [comment]
For data download, check ASF https://search.asf.alaska.edu
For processing dataset, try one of our examples first on topex: https://topex.ucsd.edu/gmtsar/downloads

**Comment by MohamedAbdrabou2022** [comment]
After I downloaded that data how to run...I mean which codes I must write on the Ubuntu?

**Comment by MohamedAbdrabou2022** [comment]
I must write these codes 
![image](https://user-images.githubusercontent.com/113559504/193141507-45f2591e-0f13-4633-962e-b2a2214ba29b.png)

**Comment by MohamedAbdrabou2022** [comment]
![2](https://user-images.githubusercontent.com/113559504/193141706-ed69bed1-3b41-42ef-b1d3-fe9c2fc135b7.JPG)
before making processing?

**Comment by Xiaohua-Eric-Xu** [comment]
These are the commands to install GMTSAR. Since you are using the ubuntu virtual machine that has GMTSAR installed, you don't need to to any of these I think.

**Comment by MohamedAbdrabou2022** [comment]
Ok
Now, I must go for readme file and write the commands only?

Thanks for your efforts!

**Comment by MohamedAbdrabou2022** [comment]
GMT is required to be setted up on Ubuntu.

**Comment by MohamedAbdrabou2022** [comment]
?????

**Comment by MohamedAbdrabou2022** [comment]
I  am here ....

What I must do now?
![v1](https://user-images.githubusercontent.com/113559504/193367311-a6becc1b-316b-47a9-a831-37ce59d6e664.JPG)

**Comment by MohamedAbdrabou2022** [comment]
![n](https://user-images.githubusercontent.com/113559504/193369357-3d0fc0a5-82a2-4a3a-89db-074d8d23ee63.JPG)

**Comment by Xiaohua-Eric-Xu** [comment]
> GMT is required to be setted up on Ubuntu.

GMTSAR depends on GMT. So if it has GMTSAR installed, it has GMT installed as well.

**Comment by Xiaohua-Eric-Xu** [comment]
> I am here ....
> 
> What I must do now? ![v1](https://user-images.githubusercontent.com/113559504/193367311-a6becc1b-316b-47a9-a831-37ce59d6e664.JPG)

I am not sure what you are doing. You'll need to provide more details rather than a screenshot, at least on what you are planning to do.

**Comment by MohamedAbdrabou2022** [comment]
I made a set up of UBUNTU GMTSAR on the virtual machine and after I open it I see give password...I write gmtsar.

After that I go through the recipe pdf to apply the first interferometry.

How can I proceed?

Do I must use write codes to install something before typing the same commands in the pdf on the Ubuntu virtual machine?

**Comment by Xiaohua-Eric-Xu** [comment]
No, you should be able to directly execute commands without doing any further installation. GMTSAR and GMT are installed on the virtual machine already.
