### ISSUE TITLE
[Bug]: Sentinel-1 merge_swath sometimes produces weird error "Image PRFs are not consistent"

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#458]
For multithreading processing on MacOS Apple Silicon one of input PFRs sometimes parse as "-99999.999900" while all the input files exist and correct. "merge_swath" utility code changed to print the detailed error messages:

```
        if (prm1.prf != prm2.prf){
                fprintf(stderr, "PRFs %f != %f \n", prm1.prf, prm2.prf);
                fprintf(stderr, "PRMs %s, %s \n", stem[0], stem[1]);
                die("Image PRFs are not consistent", "");
        }
```
and the debug output:
```
merge_swath Number of Files to be merged is 2 
PRFs 486.486310 != -99999.999900 
PRMs raw_desc/S1_20170204_ALL_F1_phasefilt.PRM, raw_desc/S1_20170204_ALL_F2_phasefilt.PRM 
 Image PRFs are not consistent  
```
and check the PRM files are correct:
```
grep PRF raw_desc/S1_20170204_ALL_F1_phasefilt.PRM raw_desc/S1_20170204_ALL_F2_phasefilt.PRM 
raw_desc/S1_20170204_ALL_F1_phasefilt.PRM:PRF = 486.48631
raw_desc/S1_20170204_ALL_F2_phasefilt.PRM:PRF = 486.48631
```

The issue is hard to detect because sometimes hundreds of merges can be processed without the issue even using 8, 16 or 32 parallel threads. On the same test dataset it occurs randomly on different files and sometimes all the files can be processed well. At the same time for a single-threaded processing I can't reproduce the issue. And the problem persists in case of defined environment variable GMT_SESSION_NOHISTORY too.

**Comment by Xiaohua-Eric-Xu** [comment]
https://github.com/gmtsar/gmtsar/issues/347#issuecomment-1159168099 
Could this be the situation?

**Comment by mobigroup** [comment]
Wow, it’s the same, thanks! On 2 cores it works for me too but not on 4+ cores. That’s really strange to have the GMT issue on fast modern SSD like to old HDD.

**Comment by chintals** [comment]
@mobigroup @Xiaohua-Eric-Xu 
Upon further digging it is not that GMT read/write is failing, it is actually the way GMT writes/reads current/future commands via gmt.history file. Too many parallel instances causes simultaneous read/writes from the single history file and causes processing issues during any portions of the GMTSAR csh scripts

**Comment by mobigroup** [comment]
@chintals I think you missed that I disabled the history file writing using GMT_SESSION_NOHISTORY environment variable as it's documented for GMT toolset.  If you mean GMT doesn't follow the documentation and writes the disabled history file it's obviously GMT bug.

**Comment by chintals** [comment]
@mobigroup 
I didn't realize that you had disabled gmt.history, I misread your last comment. I had tested by disabling GMT history in gmt conf using gmtset command (not session history).  From my side I have seen that setting the history off still doesnt help when the number of parallel instances go up by 6 or so, and get inconsistent processing errors.

**Comment by mobigroup** [comment]
@chintals I have the same issue - the parallel processing is always safe for 1 and 2 threads and fails randomly for 8 threads and it doesn’t relate to GMT settings. For a modern SSD it looks inappropriate I think. Ok, that’s just one more GMT problem and the reason to exclude it completely.

**Comment by Xiaohua-Eric-Xu** [comment]
I never had an issue like this with Mac or the Dell Precision Tower (Ubuntu 18), even up to 40 threads of processing. Just FYI. Not sure what's the fix here though.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu That’s interesting. Are you sure you run merge_swath in parallel mode on many cores vs sequential processing?

**Comment by Xiaohua-Eric-Xu** [comment]
@mobigroup I see, for merging I only used a few threads as it is mostly spending time reading and writing. Maybe @PaulWessel can give us a suggestion?

**Comment by chintals** [comment]
@Xiaohua-Eric-Xu I had posted a similar question on parallel processing issues on GMT forum and Paul's response is here:
https://forum.generic-mapping-tools.org/t/parallel-gmt-operations-fail-to-output-results-files-in-some-instances/3315

I have noticed that disabling history trigger errors in script where -R flag is used (for example with psxy command etc). The other alternate could be to have unique sub-directory for each parallel instance, and move files after parallel processing is done.

**Comment by mobigroup** [comment]
@chintals That’s not related to merge_swath because it uses GMT library and there are no “hidden” files created. Even more, we can run 8+ parallel instances of other GMT-related GMTSAR tools in the same directory without this issue. And again, the incorrect PRF value ”-99999.999900“ is not produced by GMT library of course.

**Comment by PaulWessel** [comment]
The GMT history of command stuff did not consider parallel executions, so the only solution is to use workarounds:

Do not rely on the history by spelling out the common options like -Rw/e/s/n and not leave them empty (like -R -J), and use the **GMT_HISTORY** setting to turn off writing the history. Do not use any **gmt set** commands which will write to gmt.conf which might occur when another thread is trying to read it.

**or**

Have each thread do work in a unique temp directory so that each thread can do its own gmt.history read/write in that directory. Start with a gmt set command to create a fresh gmt.conf file in that directory which then will be used by that thread.

gmt.history and gmt.conf are the only configuration files GMT will both write and read so I think (or hope) that preventing those clashes should avoid problems with parallel execution.

Note that gmtcommand1 | gmtcommand2 | gmtcommand3 via piping is susceptible to exactly the same trouble since we have no control over how these processes are started and they do run in parallel.

**Comment by Xiaohua-Eric-Xu** [comment]
> -99999.999900

I don't think there's any place in the code where we set PRF to that value. They are initialized as NULL and then replaced by values from the PRM.  The function called there is null_sio_struct and get_sio_struct which are both in gmtsar/sio_struct.c

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Yes, I didn’t find this value in the sources. Also, you use the same functions to parse PRM files everywhere in the code but all other binaries don’t produce this issue. At the same time, phasediff and/or conv tools have hard memory leaks I think and that’s difficult to identify too (for parallel execution from Python we need to kill the work process and create the new one for every execution). Sure, we don’t see any of the problems in the mostly sequential shell based pipeline. In case if nobody can detect the issues that looks more easy to rewrite all the tools from the scratch in the future than spend a lot of time to debug them.
