### ISSUE TITLE
[Help]: why corr.mask doesn't give NAN to places where cor lower than threshold  like landmask.

### ISSUE THREAD

**Issue by jerry7nol** [gmtsar/gmtsar#460]
unwrapping
![WSU6R 2T{WP~}Q`$%{ZA%_I](https://user-images.githubusercontent.com/111356557/193487273-b1d22420-8761-4954-9f5b-f6616cb661ac.png)

corr.mask
![YYE3W_Q6LRDP7S HL`QD7EV](https://user-images.githubusercontent.com/111356557/193487294-ad220c7c-3198-48a8-851c-58a72a0cea45.png)

**Comment by chintals** [comment]
mask_def.grd is actually created from correlation (is the mean of all correlation grd files from individual interferograms directories) and uses the user threshold for computing the mask_def.grd. Mask made from landmask is called landmask_ra.grd

**Comment by Xiaohua-Eric-Xu** [comment]
It also depends on whether you are using snaphu.csh or snaphu_interp.csh. The second does the masking I think. The first does not mainly to deal with fault ruptures (we don't really want to throw away pixels near fault).

**Comment by joejoe03050709** [comment]
> Actually mask_def is created in merge directory and then connected to each intf dir using symbolic_link. Can you check if you see mask_def is in each intf directory?
yeah, i created it in merge,then ln -s by csh

**Comment by joejoe03050709** [comment]
> It also depends on whether you are using snaphu.csh or snaphu_interp.csh. The second does the masking I think. The first does not mainly to deal with fault ruptures (we don't really want to throw away pixels near fault).

i used snaphu_interp.csh 0.01 40, but it doesn't work .

**Comment by chintals** [comment]
Can you show us a screenshot of one of the intf folder with the mask_def.grd file and also can you check snaphu_interp.csh (GMTSAR/bin/) around line 118 under comment user defined mask if the code is
`if (-f mask_def.grd) then` or `if (-e mask_def.grd) then`

**Comment by joejoe03050709** [comment]
> Can you show us a screenshot of one of the intf folder with the mask_def.grd file and also can you check snaphu_interp.csh (GMTSAR/bin/) around line 118 under comment user defined mask if the code is `if (-f mask_def.grd) then` or `if (-e mask_def.grd) then`

sorry,i  deleted all example but
![image](https://user-images.githubusercontent.com/111356557/194055474-8c98644d-cac2-47dd-ad4b-e1b6b29752e2.png)
and i checked snaphu_interp.csh , line 118 is **if (-f mask_def.grd) then**

**Comment by chintals** [comment]
Ok, good with the code. Can you click/open one of the mask_def.grd in anyof the intf folder? I just want to confirm that that symbolic link is not broken by chance?

**Comment by joejoe03050709** [comment]
> Ok, good with the code. Can you click/open one of the mask_def.grd in anyof the intf folder? I just want to confirm that that symbolic link is not broken by chance?
i think i just open grd file by ncview, sorry my deleted my texts using corr.mask, i will try later.

**Comment by joejoe03050709** [comment]
@chintals sir, this is my unwrap.csh
[unwrap_intf.txt](https://github.com/gmtsar/gmtsar/files/9731282/unwrap_intf.txt)
and this is my mask_def.grd opened by ncview
![1665124856458](https://user-images.githubusercontent.com/111356557/194484018-1d6dd120-a2cf-4b9e-bca6-49a2328a93b8.png)
i can''t open by clicking.

**Comment by Xiongwei789** [comment]
Hi,
Ｉhave the same problem. Have you solved it？

**Comment by Xiaohua-Eric-Xu** [comment]
> @chintals sir, this is my unwrap.csh [unwrap_intf.txt](https://github.com/gmtsar/gmtsar/files/9731282/unwrap_intf.txt) and this is my mask_def.grd opened by ncview ![1665124856458](https://user-images.githubusercontent.com/111356557/194484018-1d6dd120-a2cf-4b9e-bca6-49a2328a93b8.png) i can''t open by clicking.

I think your mask looks pretty good.
