### ISSUE TITLE
[Help]: Error during aligning in preproc_batch_tops.csh in mode 2 in Sentinel

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#461]
Hie Eric,
I have successfully processed a region with asc 175 data, I am processing over the same region with descending 170 data.
But I am encountering the weird error of Segmentation fault during step of preproc_batch_tops.csh in mode 2.
Below is the picture of my test data.in file and size of SLC which is coming zero in most of the cases, what could be the reason for this one.
![Screenshot from 2022-10-03 15-48-53](https://user-images.githubusercontent.com/88940973/193554981-f1e2ca81-21f9-4bb6-9362-149bb1dbc20d.png)

![Screenshot from 2022-10-03 15-49-21](https://user-images.githubusercontent.com/88940973/193555042-5f138266-51f5-428b-aab0-b3fb881cf361.png)

And this is the log file of the same error.
[aligning.txt](https://github.com/gmtsar/gmtsar/files/9696656/aligning.txt)
Thanks in advance

**Comment by Xiaohua-Eric-Xu** [comment]
The error is likely because gmt surface did not produce a.grd and r.grd with these two commands below 
```
gmt surface atmp.xyz -bi3d -R0/21008/0/12192 -I8/4 -Gatmp.grd -T0.5 -N1000 -r
gmt surface rtmp.xyz -bi3d -R0/21008/0/12192 -I8/4 -Grtmp.grd -T0.5 -N1000 -r
```
But I am not sure why.  Could you re-compile GMT? Sometimes, netcdf and hdf5 libs get broken.

**Comment by Xiaohua-Eric-Xu** [comment]
Did you re-compile GMTSAR after re-compiling GMT? This looks very much like a broken library thing to me. 
```
/usr/local/lib/libgmt.so.5(sig_handler+0x2ab)[0x7fdb4e83b29b]
```
The size of the EOF looks good to me by the way.
