### ISSUE TITLE
[Feature]: GACOS_correction.csh

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#462]
Hi. Dear Professors,I'd like to ask you a few questions about this command.

GACOS.csh list_interferograms full_path_to_GACOS_data full_path_topo reference_point incidence_angle

1. Does the start date of data downloaded from the official website of GACOS need to be the same as the start time of Sentinel data?

2. Are list_interferograms referred to the previous IntFLIST?

3, Reference_point and incidence_angle should be found in the same file?
Thank you!

**Comment by Xiaohua-Eric-Xu** [comment]
[@esr](https://github.com/gmtsar/user-contributions/commits?author=esrivas17) developed this so I am trying to @ him here.

**Comment by Luvina0503** [comment]
> [@esr](https://github.com/gmtsar/user-contributions/commits?author=esrivas17) developed this so I am trying to @ him here. (https://github.com/esrivas17) Or maybe you could directly send him a message?

OK. Thank you

**Comment by chintals** [comment]
@Luvina0503 
I haven't used this particular GACOS correction script, but

> 1. Does the start date of data downloaded from the official website of GACOS need to be the same as the start time of Sentinel data? 

The GACOS correction script is mapping the intf dates YYYYDAY to YYYYMMDD by looking at SLC file names. you can get that from baseline_table dat as well. All those SLC dates need to be in the gacos directory. Regardless of the time you specify on GACOS website, the files you download will be labelled as YYYYMMDD.ztd, YYYYMMDD.ztd.rsc. You can should use the time specified in Sentinel SAFE filename or get acq time from xml as well.

> 2. Are list_interferograms referred to the previous IntFLIST?

yes

> 3, Reference_point and incidence_angle should be found in the same file?

reference point i beileve is a text file with lon lat. The reference point should be the same one used to set reference for unwrap grd. And the user sets the reference point for each case.

incidence angle, you can find the by using the SAT_look with reference point as inputfile to get you enu vector and determine the angle. Or you can get the midswath incidence angle or mean of incidence angle count from the master SLC xml file.

**Comment by Luvina0503** [comment]
@chintals 
If I have a large number of SAFE files, is there a script that automatically downloads the GACOS data？

**Comment by chintals** [comment]
No automation scripts on GMTSAR git, but you can  20 SLC files  at every request on the GACOS site.

**Comment by Luvina0503** [comment]
OK. Thank you
