### ISSUE TITLE
[Help]: organize_files_tops_linux.csh

### ISSUE THREAD

**Issue by 674111501** [gmtsar/gmtsar#464]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through
Dear Prof. Xu,when I try to use the last version,I find there are some problem in organize_files_tops_linux.csh.When I try to run it, I will be told I have the wrong usrname/password?Is there any solutions?
**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version: the last

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case
![image](https://user-images.githubusercontent.com/69631148/193713099-9c65fd47-a8c1-4af7-ad6e-4642bfba53b4.png)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
Not sure how the query could fail because of username and password issue. It uses the `gnssguest`, which should be the suggested one for downloading the orbits. Are you able to run download_sentinel_orbits_linux.csh to get the orbits?

**Comment by 674111501** [comment]
I have tried the “wget” command，and when the url is "https://scihub.copernicus.eu/gnss/search?q=beginPosition:[2020-05-28T00:00:00.000Z TO 2020-05-30T23:59:59.999Z] AND endPosition:[2020-05-28T00:00:00.000Z TO 2020-05-30T23:59:59.999Z] AND platformname:Sentinel-1 AND filename:S1A_* AND producttype:AUX_POEORB" ,it will wrong.When the url is "https://scihub.copernicus.eu/gnss/#/home",it will right.
![屏幕截图 2022-10-05 110235](https://user-images.githubusercontent.com/69631148/193972058-48f6975c-c62e-4c93-a0de-7ff4a7a68d7f.png)

![屏幕截图 2022-10-05 110411](https://user-images.githubusercontent.com/69631148/193972171-cb4ff25c-d18e-4571-979e-59505f7e11b2.png)
Maybe there are something wrong with url

**Comment by 674111501** [comment]
but the usrname and password is right

**Comment by Xiaohua-Eric-Xu** [comment]
Yes they use the same query commands. I saw that it says username/password failure, but I am not sure why. And you need the timestamp to get the right orbit file. @kguns32 may know more on this.

**Comment by kguns32** [comment]
Interesting! I just checked the most recent download_sentinel_orbits_linux.csh version on our main linux machine and it worked just fine. Just to check, what linux system are your running? Even if you downloaded the orbitquery.txt file, was it empty? (You need to specify somehow, what time frame you're trying to download orbits for, as Xiaohua said)

**Comment by 674111501** [comment]
The problem have been solved. I try to change the systom from Ubuntu 16.04 to Ubuntu 20.04. And the orbit data are downloaded successfully.

**Comment by 674111501** [comment]
@kguns32 @Xiaohua-Eric-Xu Thank you for your help.
