### ISSUE TITLE
[Bug]: Segmentation fault make_gaussian_filter

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#469]
make_gaussian_filter doesn't work on Ubuntu 22.04 ARM64 platform:

```
$ uname -a
Linux 42c3f1eeb741 5.10.124-linuxkit #1 SMP PREEMPT Thu Jun 30 08:18:26 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

$ make_gaussian_filter
Segmentation fault
```

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, didn't even pop out the Usage? There's literally no real code before this.
```
 43     if (argc < 4)
 44         die(USAGE, "");
```

**Comment by mobigroup** [comment]
That's actually a problem with recursive includes (there are no #ifndef conditions to prevent repeated including of a single file). I've found a fix using "configure" with the options and "make" without the options "CFLAGS='-z muldefs' LDFLAGS='-z muldefs'".

**Comment by Xiaohua-Eric-Xu** [comment]
I see. That's a problem with lots of earlier codes having one function in the library and one extra local definition. Fixing that is a big job.

**Comment by mobigroup** [comment]
Yes, agree. Fortunately, it’s fixable by the building options. I use the arm64 build to provide PyGMTSAR as Docker image for Apple Silicone hosts: https://github.com/mobigroup/gmtsar/blob/master/docker/Dockerfile The complete image available on DockerHub (like to GitHub for Docker projects): https://hub.docker.com/r/mobigroup/pygmtsar
It looks as easy to start on Linux/MacOS/Windows virtual environment with pre-installed GMTSAR binaries, Python 3.10 with all the libraries and PyGMTSAR itself plus the same example Jupyter notebooks as on Google Colab. That’s way to distribution for someones who don’t use it intensively and/or don’t worry about (affordable) performance gap. Just use these 3 commands to start the JupyterLab web server to obtain web interface like to Google Colab:

```
docker pull mobigroup/pygmtsar
docker run -dp 8888:8888 --name pygmtsar docker.io/mobigroup/pygmtsar
docker logs pygmtsar
```

Maybe do we need to have Docker images for GMTSAR too? It’d look as ready to use Ubuntu 18.04/20.04/22.04 image for multiple platforms and it’s easy to obtain from DockerHub server or build yourself (using the small text Dockerfile as the one linked above)  and it’s small enough (just about 1GB). I can prepare it. I hope it could resolve some user issues with GMTSAR installation because Docker is available almost everywhere for now.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu I've shared the Docker image with GMTSAR installed: https://hub.docker.com/repository/docker/mobigroup/gmtsar
By some reason SBAS processing doesn't work for example S1A_Stack_CPGF_T173.tar.gz #481

**Comment by Xiaohua-Eric-Xu** [comment]
I made a reply here: https://github.com/gmtsar/gmtsar/issues/481#issuecomment-1275285570. Not sure whether you pasted the command incorrectly to github, or that's really the situation, i.e. not specifying dimensions in the sbas command.
