### ISSUE TITLE
Workflow for ENVI SLC stacking

### ISSUE THREAD

**Issue by nwpulver** [gmtsar/gmtsar#47]
Hello on the website https://topex.ucsd.edu/gmtsar/downloads/ there are examples for ENVISAT, ENVISAT SLCs and stack ENVI, but no ENVI_SLC stack. It seems the workflow shown in the ENVI stack does not work for the ENVISAT_SLC. Is it possible to stack or do SBAS time series on SLC  with GMTSAR? If so, does someone have an example work flow? 

- Nathan

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Nathan,

Hi Koorosh,

We are kind of slow on this as most people turned to Sentinel-1 these days.

The coregistration of SLC product is fairly simple in GMTSAR. Mainly it follows the following steps. 

A) imagine you have two images $master and $aligned, acquired by ENVI_SLC_pre_process.

1) xcorr to get the shift parameters
xcorr $master.PRM $aligned.PRM -xsearch 128 -ysearch 128 -nx 20 -ny 50

2) get coregistration parameters from the xcorr results (you can use different number of parameters, the default is 2,2, chose 3 3 for a better coregistration)
fitoffset.csh 2 2 freq_xcorr.dat 18 >> $aligned.PRM

3) resample the aligned image to perform coregistration
resamp $master.PRM $aligned.PRM $aligned.PRMresamp $aligned.SLCresamp 4

4) rename the files before the next step (interferometry)
rm $aligned.SLC
mv $aligned.SLCresamp $aligned.SLC
cp $aligned.PRMresamp $aligned.PRM

B) For ENVISAT, sometimes the baseline is too big and you have to perform secondary alignment just like for ALOS data. You could simply achieve this with performing the steps above 
First, between $master and $secondary_master and then between $secondary_master and $slave. After that, perform interferometry between $secondary_master and $slave

You can always perform B) to achieve better coherence. 

After you get aligned SLCs, you could create interferogram with intf_batch.csh or intf_tops.csh if you want to cut a small region for processing.

Cheers,
Xiaohua(Eric)

**Comment by nwpulver** [comment]
So I would align each SLC individually to the reference slc correct? How would I go about getting a baseline plot to determine the master? 

Would you suggest just using L0 products? 

Nathan

**Comment by Xiaohua-Eric-Xu** [comment]
Once you get all PRM, SLC, LEDs with ENVI_SLC_pre_process, use get_baseline_table.csh to create a baseline_table.dat. Then you could plot the baseline with GMT and select your master image. 
There are no fundamental differences between SLCs and raw data, unless 1) you want a larger area with chirp extension or 2) you want to focus at non-zero doppler so the image quality is better.

**Comment by nwpulver** [comment]
Ok, it seems I am having a hard time finding the raw data, so I wrote a couple scripts to handle this workflow up to the intf_batch processing. Would it be helpful for the developers to share this? 

- Nathan

**Comment by Xiaohua-Eric-Xu** [comment]
Do you want to make a pull request? I can give it a review and put it to the distribution. We could go back and forth and exchange ideas this way.

**Comment by nwpulver** [comment]
I have never done a pull request before on git, but I would be happy to sort out how that is done at some point. I started classes again and have gotten quite busy so it may be a little bit before I can devote time to it. I did quickly upload my scripts to my github if that is at all helpful. I think I will definitely need some input  from you so a pull request is a great idea, I just need some more time. 

Nathan

**Comment by Xiaohua-Eric-Xu** [comment]
Oh, great, no hurry on this. Here's a link on how you could make a pull request. I would recommend making on the most up-to-date master branch. https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by nwpulver** [comment]
I am currently getting errors when running all of these steps when running intf_batch.csh and I cannot figure out why. The errors start at OFFSET_TOPO phase with the error: `Can't open input data  ASA_IMS_1PNESA20030207_175248_000000182013_00356_04919_0000.SLC 
grdmath [ERROR]: amp-ASA_IMS_1PNESA20030207_175248_000000182013_00356_04919_0000.grd is not a number, operator or file name` then errors continue throughout. Am I missing something with the steps? if i run gmt grdinfo on amp-ASA_ ... then it outputs a max and min of a grid and the correct file format, so it is not an empty .grd file there. I am not sure why it is saying it cannot open the SLC file either.
