### ISSUE TITLE
[Feature]: Atmospheric correction parameter

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#471]
Hi. Dear professors,
i want to ask some questions.
I would like to ask where can I find the data of reference point and indicence angle in the following picture, but can't find the two files lon lat coordinates and SAT_look.
![69S(CS SXR@`NK2QCQBD I](https://user-images.githubusercontent.com/114629377/194567575-c8aaf90c-dea1-4c36-95f1-731a23148859.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Is this from which script? 

Typically you can get the look angel by `echo $lon $lat | gmt grdtrack -Gdem.grd | SAT_look your_PRM_file`

**Comment by Luvina0503** [comment]
> Is this from which script?
> 
> Typically you can get the look angel by `echo $lon $lat | gmt grdtrack -Gdem.grd | SAT_look your_PRM_file`

This picture is from GACOS_correction.csh.
i want to ask a question about GACOS correction. 
Should I do GACOS atmospheric correction first or phase unwrap first？

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
But when I type this command in the terminal, nothing is displayed and text is generated

**Comment by Xiaohua-Eric-Xu** [comment]
>  Should I do GACOS atmospheric correction first or phase unwrap first？

You could pick either way.



> But when I type this command in the terminal, nothing is displayed and text is generated

What exact command did you run? Did you set $lon and $lat?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
How do I set  $lon and $lat?

**Comment by Xiaohua-Eric-Xu** [comment]
Just replace them with numbers in the command. If you are interested in learning some unix basics (e.g., https://www.tutorialspoint.com/unix/index.htm), it might become much easier to use.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
OK.Thank you!

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
Looking at the manifest file, there are four latitude and longitude coordinates. 
![T1URX`ZSZY1X1KTILS}SE37](https://user-images.githubusercontent.com/114629377/196028706-b9d7f5af-f837-44c3-95fc-f04d27a6efe1.png)
When executing the GACOS.csh script command, do you choose one of the longitude and latitude coordinates as the reference point in the command or do you need to perform other calculations?
![XR_K S0R(ZCYP{ZSR5OD$V5](https://user-images.githubusercontent.com/114629377/196028712-bd382298-20ac-4f57-8440-ce54dc9e5a6e.png)
May I ask if this number is a set of coordinates for the four coordinates in the first picture？

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
For the unwrapped phase map, how should I view the longitude, latitude, elevation of each point in the phase map and export the data? Second, I still couldn't figure out the Angle of incident from your instructions.

**Comment by Xiaohua-Eric-Xu** [comment]
If you have run `geocode.csh` or `proj_ra2ll.csh`, you'll get some grids named as *_ll.grd which means results in geo-coordinates. 

To find incidence angle, use `SAT_look`.

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu @Luvina0503 
can i choose any point to input that be a point of reference.
and what is correspondant .LED .
![1667012860938](https://user-images.githubusercontent.com/111356557/198795693-3a47556c-8444-4e9c-bdc2-5f1303f6dd77.png)
is it LED file in the subwaths? should i choose one of three that F1.LED F2.LED F3.LED?

**Comment by joejoe03050709** [comment]
> @Xiaohua-Eric-Xu @Luvina0503 can i choose any point to input that be a point of reference. and what is correspondant .LED . ![1667012860938](https://user-images.githubusercontent.com/111356557/198795693-3a47556c-8444-4e9c-bdc2-5f1303f6dd77.png) is it LED file in the subwaths? should i choose one of three that F1.LED F2.LED F3.LED?
and angle of incident by SAT_look look like indicate to one point?

**Comment by Xiaohua-Eric-Xu** [comment]
The last three columns are the look cosines. You could simply calculate one with them I think.

**Comment by jerry7nol** [comment]
> The last three columns are the look cosines. You could simply calculate one with them I think.

do you mean this just calculate by arccos, like  arc-0.114195=96.5°，so it's incidence angel to tihs point is 83.5° , this is one corner of my image. is it right?

**Comment by Xiaohua-Eric-Xu** [comment]
The three columns, if you type `SAT_look` in your terminal, are look_east, look_north and look_up. So it should be `atand(0.720964) = 35.79`
```
% SAT_look
 
 Usage: SAT_look master.PRM [-bo[s|d]] < inputfile > outputfile  

             master.PRM   -  parameter file for master image and points to LED orbit file 
             inputfile    -  lon, lat, elevation [ASCII] 
             outputfile   -  lon, lat, elevation look_E look_N look_U [ASCII default] 
             -bos or -bod -  binary single or double precision output 

  example: SAT_look master.PRM < topo.llt > topo.lltn    

  Note that the output elevation is the one above reference radius specified in the PRM file
```

**Comment by jerry7nol** [comment]
> The three columns, if you type `SAT_look` in your terminal, are look_east, look_north and look_up. So it should be `atand(0.720964) = 35.79`
> 
> ```
> % SAT_look
>  
>  Usage: SAT_look master.PRM [-bo[s|d]] < inputfile > outputfile  
> 
>              master.PRM   -  parameter file for master image and points to LED orbit file 
>              inputfile    -  lon, lat, elevation [ASCII] 
>              outputfile   -  lon, lat, elevation look_E look_N look_U [ASCII default] 
>              -bos or -bod -  binary single or double precision output 
> 
>   example: SAT_look master.PRM < topo.llt > topo.lltn    
> 
>   Note that the output elevation is the one above reference radius specified in the PRM file
> ```

oh, i looked wrong order.thank you very much sir
