### ISSUE TITLE
[Help]: In the script pre_proc.csh, “set the num_lines to be the min of the master and aligned” caused a problem

### ISSUE THREAD

**Issue by zhangdabao2020** [gmtsar/gmtsar#472]
**Describe the problem you met**
hello xu：
First of all, I don't quite understand why do I need  to set the num_lines to be the min of the master and aligned.
When I set this variable _num_valid_az_ to the minimum value between the two,a problem was caused   in the next step "calc_dop_orb $master.PRM0 $master.log $RAD 0". 
 The error message is:  interpolation point outside of data constraints.

**OS and software version**

GMTSAR version: V6.2.2

**Screenshot**
By debugging the code, I found out that it was because t2 was less than pt[max-1]
In addition, the dimensions of the master image are:12692 * 29238, the dimensions of the aligned image are:13000* 21947
How do I fix it, thanks!!
![image](https://user-images.githubusercontent.com/33653803/194568472-e60da75f-e805-48a5-a9d4-18db59a0207b.png)

![image](https://user-images.githubusercontent.com/33653803/194569185-fa6dbc35-56c1-4c33-8ba5-4ca381e6d9d9.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I am a bit confuse by your description. num_valid_az should be read/set from the program not hard set by users I think. 

Also after alignment, the number of lines in the aligned image should be smaller than the master image (in the PRM file). The SLCs should be matching the size set in the PRM file. One reason for this error `interpolation point outside of data constraints.` could also be due to the orbit file being not long enough to do the interpolation. 

You'll have to provide more details for me to guess. e.g. what satellite data, what are the prior steps before running calc_dop_orb, etc.

**Comment by zhangdabao2020** [comment]
> I am a bit confuse by your description. num_valid_az should be read/set from the program not hard set by users I think.
> 
> Also after alignment, the number of lines in the aligned image should be smaller than the master image (in the PRM file). The SLCs should be matching the size set in the PRM file. One reason for this error `interpolation point outside of data constraints.` could also be due to the orbit file being not long enough to do the interpolation.
> 
> You'll have to provide more details for me to guess. e.g. what satellite data, what are the prior steps before running calc_dop_orb, etc.

Hi , Xiaohua. I'm sorry I didn't make it clear what I meant.  Here are my steps to reproduce the problem.
`make_slc_gf3 $master.xml $master.tiff $master`
`make_slc_gf3 $aligned.xml $aligned.tiff $aligned`
`# set the num_lines to be the min of the master and aligned`
      `@ m_lines  = grep num_lines ../raw/$master.PRM | awk '{printf("%d",int($3))}' `
      `@ s_lines  = grep num_lines ../raw/$aligned.PRM | awk '{printf("%d",int($3))}' `
     ` if($s_lines <  $m_lines) then`
       `  update_PRM $master.PRM num_lines $s_lines`
      `   update_PRM $master.PRM num_valid_az $s_lines`
      `   update_PRM $master.PRM nrows $s_lines`
    `  else`
      `   update_PRM $aligned.PRM num_lines $m_lines`
       `  update_PRM $aligned.PRM num_valid_az $m_lines`
      `   update_PRM $aligned.PRM nrows $m_lines`
      `endif`
` calc_dop_orb $master.PRM0 $master.log $RAD 0 `
Then the problem happened.
By debugging the code, I found out that it was because t2 was larger than pt[len -1](The last element of the array) that caused the problem.
![image](https://user-images.githubusercontent.com/33653803/194682329-5ae8c7c8-229f-4222-848f-9d00f7d42b88.png)
![image](https://user-images.githubusercontent.com/33653803/194682392-ac90221e-4e90-466f-b743-ebd728ae13c3.png)
![image](https://user-images.githubusercontent.com/33653803/194682668-4dffc91c-3942-4c8a-a7f0-7c1574a81ee8.png)

**Comment by zhangdabao2020** [comment]
The reason for this error interpolation point outside of data constraints is due to the orbit file being not long enough to do the interpolation. thanks xiaohua!

**Comment by Xiaohua-Eric-Xu** [comment]
I think you don't really need to update num_valid_az to do calc_dop_orb. But let me know if I missed anything writing up the code.
