### ISSUE TITLE
[Help]: SBAS. GMTSAR

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#474]
Hello Everyone
I hope All doing well.

The study area is an oil field, but this oil field is located in a tectonically stable field .  The aim of the study is to calculate the subsidence of this field.  So I took a set of data and SBAS made it by GMTSAR.  But the end result of the displacement turned out like this
![image](https://user-images.githubusercontent.com/108739411/194694123-7d2d90bc-e6ef-40a0-80b3-718cb2d623ea.jpeg)
![image](https://user-images.githubusercontent.com/108739411/194694126-87943dd9-2c23-487c-9dea-57b7670b7803.jpeg)

Is this result correct (los)?  Why is the displacement meter not showing? how do I show it.  
How do I calculate displacement for each year.

**Comment by SteffanDavies** [comment]
Does your area has very low coherence? Did you use a stacked coherence mask or a snaphu coherence threshold? Use a relatively low value like 0.1 for your stacked coherence mask and run snaphu command with a very low value such as 0.001 so it doesn't discard any more pixels.
