### ISSUE TITLE
[Help]:a

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#479]
Hi
I need this script

prep_sbas.csh

**Comment by Alzaidy1** [comment]
> https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/prep_sbas.csh

Thank you a lot

**Comment by SteffanDavies** [comment]
If you correctly installed GMTSAR and added the bin folder to PATH it should be available like all the other scripts directly from the terminal.
