### ISSUE TITLE
[Help]: .xml with .EOF

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#480]
Hello 

I hope All doing well

What is the script that does this step?

![image](https://user-images.githubusercontent.com/108739411/195010274-ed57b8cb-7703-4300-a870-36cd14715e3b.jpeg)

**Comment by chintals** [comment]
prep_data.csh( for mac) or prep_data_linux.csh (for linux)

For future reference you can review the sentinel time series document, https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf

**Comment by Alzaidy1** [comment]
> prep_data.csh( for mac) or prep_data_linux.csh (for linux)
> 
> 
> 
> For future reference you can review the sentinel time series document, https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf

thank you A Lot Mr.chintals 
well I followed this document step-by-step but this script it not run. 

![image](https://user-images.githubusercontent.com/108739411/195176194-a23d444a-3d3d-4283-a78a-9137fe8b8099.jpeg)

**Comment by chintals** [comment]
Before you enter preproc_batch_tops.csh command, can you type in `prep_data_linux.csh` in the raw directory. This should create the data.in file

**Comment by Alzaidy1** [comment]
> Before you enter preproc_batch_tops.csh command, can you type in `prep_data_linux.csh` in the raw directory. This should create the data.in file

What is Aps_toolbox


![image](https://user-images.githubusercontent.com/108739411/195180268-ccf9be11-186d-4ace-8d40-781df33e7f2d.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
I don't think we ever set a variable called APS_toolbox in the script. Could it be that there being another script that has the same name?

And, could you try the command below:
```
which prep_data_linux.csh
```

And do a `ls` in your raw directory.

**Comment by Alzaidy1** [comment]
> I don't think we ever set a variable called APS_toolbox in the script. Could it be that there being another script that has the same name?
> 
> 
> 
> And, could you try the command below:
> 
> ```
> 
> which prep_data_linux.csh
> 
> ```
> 
> 
> 
> And do a `ls` in your raw directory.

This

![image](https://user-images.githubusercontent.com/108739411/195206389-2861694e-b724-4022-8223-a6d8eca91a49.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
Did you set any environment variable in your .tcshrc file that potentially has APS_toolbox in it? This is really strange...

**Comment by Alzaidy1** [comment]
> Did you set any environment variable in your .tcshrc file that potentially has APS_toolbox in it? This is really strange...

This .tcshrc

![image](https://user-images.githubusercontent.com/108739411/195207267-b4dc619e-f45d-4c4e-9654-7dcaa023e481.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, I don't know. It feels like something not related to the GMTSAR script. Maybe uninstall and reinstall GMTSAR? Not sure that'll fix this though.

**Comment by Alzaidy1** [comment]
> Hmmm, I don't know. It feels like something not related to the GMTSAR script. Maybe uninstall and reinstall GMTSAR? Not sure that'll fix this though.

I tried it on my second laptop and same problem😞

**Comment by Xiaohua-Eric-Xu** [comment]
It's a bit hard to debug such error as we could not reproduce it. One way however, is to copy this script to a test directory, figure out which lines went wrong by adding a bunch of print commands (e.g. echo "Lalalalala") in the script. It's dummy but should work.

**Comment by Alzaidy1** [comment]
> It's a bit hard to debug such error as we could not reproduce it. One way however, is to copy this script to a test directory, figure out which lines went wrong by adding a bunch of print commands (e.g. echo "Lalalalala") in the script. It's dummy but should work. 

Can you get into my laptop by anydisk to solve this problems ?
I will be grateful for that

**Comment by chintals** [comment]
Its odd that the APS_toolbox error is triggered by prep_data_linux.csh and not by any other csh like preproc_batch_tops

**Comment by mobigroup** [comment]
You’d try a clean environment like to Docker container to exclude side effects: #484

**Comment by Xiaohua-Eric-Xu** [comment]
Or alternatively maybe try one of the virtual machine that has GMTSAR pre-installed? http://topex.ucsd.edu/gmtsar/tar/Ubuntu21.04_gmt6.1_gmtsar6.2.ova

**Comment by Xiaohua-Eric-Xu** [comment]
APS_toolbox feels like a variable from StaMPS/TRAIN.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Please pay attention the virtual machine is targeted for a single platform (amd64 I suppose) and it works slow in a processor emulator software on Apple Silicon arm64 and other computers on non-amd64 architecture. At the same time, Docker uses emulator to build the images for target platforms and DockerHub shares the ready to use native images for different platforms. So Docker images are suitable for hard computations on different platforms (and we have near to native performance on amd64/arm64/etc. Linux hosts).

**Comment by Xiaohua-Eric-Xu** [comment]
You may have realized that it's using a combination of softwares not just GMTSAR. I am not sure how things will work out when things are mixed together. I think it'll be good to use for more advanced users as they may fix things on the way. But to get started, it's better to stick with one set of softwares.

![image](https://user-images.githubusercontent.com/16844111/195655402-19a5d3c7-add9-4b40-8d52-7ea7fd985295.png)
