### ISSUE TITLE
[Help]: why dem always doesn't fit

### ISSUE THREAD

**Issue by jerry7nol** [gmtsar/gmtsar#482]
i use p2p_S1_TOPS_Frame.csh to run a interferogram  to merge step finished. Then i want to make a landmask, but it always tell me dem doesn't fit.
![image](https://user-images.githubusercontent.com/111356557/195264423-a7d9203f-1c2c-42a9-8583-bf3cdf715f03.png)
 and i checked dem , i can't find question.
![422f2577e6401f745fb5b5f5025edc7](https://user-images.githubusercontent.com/111356557/195264468-50ea08f3-860b-46fe-b49c-bd76039572d3.png)

**Comment by SteffanDavies** [comment]
Coold you please share gmt grdinfo of your phasefilt.grd file

**Comment by Xiaohua-Eric-Xu** [comment]
One way that can help us debug this error is that if you 1) copy landmask.csh to your local directory 2) add the following line between line 29 and 30 `gmt grdinfo landmask_ra.grd`. Then re-run the command and check on the output from this grdinfo command.

**Comment by joejoe03050709** [comment]
> Coold you please share of your phasefilt.grd file`gmt grdinfo`

![1665626784494](https://user-images.githubusercontent.com/111356557/195482117-5d98770f-40e8-4bbc-8651-8c1b2357bbea.png)
sir this is

**Comment by joejoe03050709** [comment]
> One way that can help us debug this error is that if you 1) copy landmask.csh to your local directory 2) add the following line between line 29 and 30 . Then re-run the command and check on the output from this grdinfo command.`gmt grdinfo landmask_ra.grd`
do you mean /usr/local/ or present directory, sir . i added gmt grdinfo landmask_ra.grd. and puted landmask..csh in merge directory  and  the error is changed.
![1665626989939](https://user-images.githubusercontent.com/111356557/195483155-88156a79-d9f4-406f-b3d0-2e4a4ad833ca.png)

**Comment by Xiaohua-Eric-Xu** [comment]
OK, the first landmask_ra.grd is produced with these two commands.
```
 28 gmt grdlandmask -Glandmask.grd `gmt grdinfo -I- dem.grd` `gmt grdinfo -I dem.grd`  $V -NNaN/1 -Df
 29 proj_ll2ra.csh trans.dat landmask.grd landmask_ra.grd
```
While yours seems to be within range of `-R-13472/82624/-6400/11136`, but the command you use has range of `0/67784/0/13534`, which means it's not covering the far azimuth or southern end of your data.

**Comment by joejoe03050709** [comment]
> OK, the first landmask_ra.grd is produced with these two commands.
> 
> ```
>  28 gmt grdlandmask -Glandmask.grd `gmt grdinfo -I- dem.grd` `gmt grdinfo -I dem.grd`  $V -NNaN/1 -Df
>  29 proj_ll2ra.csh trans.dat landmask.grd landmask_ra.grd
> ```
> 
> While yours seems to be within range of `-R-13472/82624/-6400/11136`, but the command you use has range of `0/67784/0/13534`, which means it's not covering the far azimuth or southern end of your data.
but range played by grdinfo is 0/67784/0/13534

**Comment by Xiaohua-Eric-Xu** [comment]
That's the info for phasefilt.grd not the landmask_ra.grd produced in middle of the script. The smaller azimuth indicate DEM being not large enough. But I am not sure why as the DEM you showed seems to cover your data.

**Comment by joejoe03050709** [comment]
> That's the info for phasefilt.grd not the landmask_ra.grd produced in middle of the script. The smaller azimuth indicate DEM being not large enough. But I am not sure why as the DEM you showed seems to cover your data.

sir, it's look like a bug, i download data again and reinstall GMTSAR,but get same result.  but it can well work.  because although it plays error,  it get right landmask..ra.grd, and like work in unwrap.

**Comment by Xiaohua-Eric-Xu** [comment]
I don't think this is a bug. The output from the code tells what happened. You data in radar coordinates has the range of 0/67784/0/13534. However, in middle of producing the landmask, the script reads in your area of dem.grd and used that to create a landmask with gmt and then ran proj_ll2ra.csh to convert things to radar coordinates. I asked you to add one line in the script to output the range of the landmask info in radar coordinates and from your screenshot, it says the range of the landmask is -13472/82624/-6400/11136. Compare the two you'll find that your far azimuth (last number) of the landmask_ra.grd (range related to dem) is smaller than your phasefilt.grd (data). The later grdsample error verified this hypothesis saying "exceeds the Y-boundaries". Based on these numbers, I could only guess that it's your DEM not covering your data at far azimuth.

**Comment by joejoe03050709** [comment]
> I don't think this is a bug. The output from the code tells what happened. You data in radar coordinates has the range of 0/67784/0/13534. However, in middle of producing the landmask, the script reads in your area of dem.grd and used that to create a landmask with gmt and then ran proj_ll2ra.csh to convert things to radar coordinates. I asked you to add one line in the script to output the range of the landmask info in radar coordinates and from your screenshot, it says the range of the landmask is -13472/82624/-6400/11136. Compare the two you'll find that your far azimuth (last number) of the landmask_ra.grd (range related to dem) is smaller than your phasefilt.grd (data). The later grdsample error verified this hypothesis saying "exceeds the Y-boundaries". Based on these numbers, I could only guess that it's your DEM not covering your data at far azimuth.
i am changed dem data many times sir, and make sure it cover my data on the Google Earth. and the others areas like this too. i 
will try again on my Virtual Machine with my Virtual Machine.

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu sir, i can't find p2p_S1_TOPS.csh, so i run p2p_S1_TOPS_Frame.csh to automatically generate just one interfergram, then use unwrap steps that i learned from time series like landmask. does it ok.

**Comment by joejoe03050709** [comment]
@Xiaohua-Eric-Xu and i remerber that the situation of dem doesn't fit is met after i used p2p_S1_TOPS_Frame.csh what ever virtual machine or Physical machine. the situation appeared even i back to follow steps of time series too

**Comment by Xiaohua-Eric-Xu** [comment]
I am not exactly sure what happened that made it fail/work. But looks like the results are somewhat OK. One potential improvement is to use snaphu_interp.csh to mask out certain low coherence pixels and unwrap more smoothly.

**Comment by joejoe03050709** [comment]
> I am not exactly sure what happened that made it fail/work. But looks like the results are somewhat OK. One potential improvement is to use snaphu_interp.csh to mask out certain low coherence pixels and unwrap more smoothly.

ok sir, i will try .thank you very much.
