### ISSUE TITLE
[Feature]: Improve atmospheric correction results

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#483]
Hi.Dear professors,
I would like to ask if there is any way to improve the result of GACOS atmospheric correction. Or what can be modified in the process to improve the results？

**Comment by Xiaohua-Eric-Xu** [comment]
The GACOS is mainly limited by its temporal resolution. The troposphere changes quite rapidly thus the hour-level resolution is not enough to capture all details of it. 

You could try with your own GNSS wet delay to estimate parameters for stratified and turbulent component following their formula. Or there are other ways to mitigate the atmospheric effect, such as the common-scene stacking approach built in GMTSAR. Or an elevation dependent correction may help in some cases too.

**Comment by Luvina0503** [comment]
OK.thank you
