### ISSUE TITLE
[Feature]: GMTSAR Docker image Ubuntu 22.04

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#484]
[![Docker](https://badgen.net/badge/icon/docker?icon=docker&label)](https://hub.docker.com/r/mobigroup/gmtsar)

## Docker Image

Download and launch the Docker image to open "ubuntu" user terminal using the commands below:
```
docker pull mobigroup/gmtsar
docker run -it --name gmtsar docker.io/mobigroup/gmtsar
```

or built the image yourself locally using Docker file inside the repository and open the terminal: 
```
docker build --no-cache -t gmtsar . -f gmtsar.Dockerfile
docker run -it --name gmtsar docker.io/library/gmtsar
```
To download orbit data for ERS and Envisat (6 GB) enter this command:
```
download_orbits.sh
```

Note: use no-password "sudo" for all operations requiring "root" user access.

Note: to build the images and share them to DockerHub  use the command below with your own repository name:

```
docker buildx build . -f gmtsar.Dockerfile \
    --platform linux/amd64,linux/arm64 
    --tag mobigroup/gmtsar:2022-10-11 \
    --tag mobigroup/gmtsar:latest \
    --pull --push --no-cache
```

## Run Examples

Run example "Sentinel-1 TOPS Time Series" from https://topex.ucsd.edu/gmtsar/downloads/ using the commands:

```
wget -c http://topex.ucsd.edu/gmtsar/tar/S1A_Stack_CPGF_T173.tar.gz
tar xvzf S1A_Stack_CPGF_T173.tar.gz -C .
./README_prep.txt
./README_proc.txt
./README_sbas.txt
```

## View Results

View the results in the terminal window using terminal image viewer:

```
chafa intf_all/2015020_2015068/phasefilt_mask_ll.png
```
<img src="https://user-images.githubusercontent.com/7342379/195099112-6bccc8e5-a57c-4189-ad94-c3fa9a10b891.jpg" width="60%" />

View the results in Docket Desktop CLI using terminal image viewer:

```
chafa intf_all/2015020_2015068/phasefilt_mask.pdf
```
<img src="https://user-images.githubusercontent.com/7342379/195099102-738f404d-8a80-426b-8c53-9cbe0d4a7ec2.jpg" width="60%" />

```
chafa SBAS/vel_ll.png
```
<img src="https://user-images.githubusercontent.com/7342379/195388458-80112ce8-3c87-470e-ae77-99f8a45894c4.png" width="60%" />

## Use Python scripts and Jupyter Notebooks

See Docker image [PyGMTSAR (Python GMTSAR) - Sentinel-1 Satellite Interferometry for everyone](https://hub.docker.com/repository/docker/mobigroup/pygmtsar) and [PyPI Python library](https://pypi.org/project/pygmtsar/).

**Comment by Xiaohua-Eric-Xu** [comment]
Anything that I can help? :)

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Please just continue your work on GMTSAR! :)

**Comment by mobigroup** [comment]
Update: NASA operator [Alaska Satellite Facility](https://www.linkedin.com/company/aksatellite/) has installed GMTSAR on OpenSarLab (OSL). Now you can run PyGMTSAR out of the box right after starting OSL.
https://www.linkedin.com/feed/update/urn:li:activity:6987024568028708864/
