### ISSUE TITLE
[Help]: stitching frame

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#485]
Hi everyone 

How can I stitching frame between two scenes?
Is there any script to solve this problem?

Best regards 
![image](https://user-images.githubusercontent.com/108739411/195407200-14e26ee7-9c6e-49c8-97a6-3ca322a64e96.jpeg)

**Comment by mobigroup** [comment]
The stitching works exactly as cropping, see the example on Google Colab (hint: place two or more scenes for the both dates to the data directory and define the pins locations if you need to crop the stitched frame):
https://colab.research.google.com/drive/1ZBVwlkiXMhSDS96oojpWrzTyRFIxv8Rp?usp=sharing
or read this manual:
https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series.pdf

**Comment by Xiaohua-Eric-Xu** [comment]
Try organize_files_tops[_linux].csh or create_frame_tops.csh or more deeper level assemble_tops.c. In fact, the current preproc_batch_tops.csh are able to handle multiple frames of data and does not care where the frames are defined. But organizing data first will save some computation time and storage too.

**Comment by Xiaohua-Eric-Xu** [comment]
Have you checked on this recipe? http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf

It has sections of downloading data and doing stitching, etc.
