### ISSUE TITLE
[Help]: Add scale 

### ISSUE THREAD

**Issue by Obaida777** [gmtsar/gmtsar#488]
I have been Run this command as last one.
gmt grdimage vel_ll.grd -JM6i -P -Ba -Cvel_ll.cpt -V -K > los_ll.ps

- The result is ![IMG_20221015_182501_398.jpg](https://user-images.githubusercontent.com/111499416/195994855-3ae09b1b-b2d1-4eb4-8b3f-ed28dba9a32e.jpg)

Without scale i need it to be like this how i can make it appear.![Screenshot_20221015-183840_Telegram.jpg](https://user-images.githubusercontent.com/111499416/195995131-805b7042-741c-48a1-bbf5-979af9fcf638.jpg)

**Comment by omarwater98** [comment]
> I have been Run this command as last one. gmt grdimage vel_ll.grd -JM6i -P -Ba -Cvel_ll.cpt -V -K > los_ll.ps
> 
> * The result is ![IMG_20221015_182501_398.jpg](https://user-images.githubusercontent.com/111499416/195994855-3ae09b1b-b2d1-4eb4-8b3f-ed28dba9a32e.jpg)
> 
> Without scale i need it to be like this how i can make it appear.![Screenshot_20221015-183840_Telegram.jpg](https://user-images.githubusercontent.com/111499416/195995131-805b7042-741c-48a1-bbf5-979af9fcf638.jpg)

i have the same question, how make a bar will appear with the unevenness

**Comment by Xiaohua-Eric-Xu** [comment]
You'll need to manually produce vel_ll.cpt with e.g., `gmt makcpt -Cpolar -T-110/95/10 -Z -D > vel_ll.cpt`, I think. And then run the same grdimage command again.

**Comment by Obaida777** [comment]
Thanks dear Eric

**Comment by omarwater98** [comment]
> He sido Ejecutar este comando como el último. gmt grdimage vel_ll.grd -JM6i -P -Ba -Cvel_ll.cpt -V -K > los_ll.ps
> 
> * El resultado es![IMG_20221015_182501_398.jpg](https://user-images.githubusercontent.com/111499416/195994855-3ae09b1b-b2d1-4eb4-8b3f-ed28dba9a32e.jpg)
> 
> Sin escala, necesito que sea así, cómo puedo hacer que aparezca.![Captura de pantalla_20221015-183840_Telegrama.jpg](https://user-images.githubusercontent.com/111499416/195995131-805b7042-741c-48a1-bbf5-979af9fcf638.jpg)

@Obaida777 Hi Obaida, i cant appear the scale, Could you help me with that?

**Comment by Obaida777** [comment]
Dear Omer the scale will not appear  so you need to use Qgis or surfer or GMT.

**Comment by omarwater98** [comment]
> Dear Omer the scale will not appear so you need to use Qgis or surfer or GMT.

how did you made the convertion to QGIS file ? or what did you do?

**Comment by Obaida777** [comment]
Qgis take file.grd

**Comment by omarwater98** [comment]
> Qgis take file.grd

How did you interpret the result? Mm/year? Or mm/period of interferogram?
