### ISSUE TITLE
[Bug]: trans.dat design problem

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#489]
@Xiaohua-Eric-Xu @SteffanDavies
For 2 full scenes (2 x 3 subswaths in total) the trans.dat file has ~20 GB size. That's problematic to process it effectively on 8 GB or even 16 GB RAM host. What is the reason this file is binary instead of NetCDF chunked dataset like to other data?

I'm trying to make an example in limited resources environment like to Docker container and the binary trans.dat looks as a big pain. What is the minimum RAM consumption on swapless host for 2 full scenes GMTSAR processing?

Following our previous discussion #478 I've rewritten gaussian filtering and detrending (fit to coordinates, DEM and removing average value) processing to work on 8-16 GB RAM for this case so only trans.dat blocks the low-RAM processing for merged scenes I think.

**Comment by mobigroup** [comment]
It might be processed by chunks using all the processing cores and a small RAM amount (about 4 GB RAM on 8 core CPU host). The lazy object has the exact shape 26187x20269x5 (SAT_llt2rat returns 5 values: range, azimuth, elevation, lon, lat [ASCII default]) where the values are not calculated and we can plot the big lazy object effectively:
<img width="547" alt="Screenshot 2022-10-17 at 13 05 49" src="https://user-images.githubusercontent.com/7342379/196101215-f229ddc4-ddc3-4f2f-af65-34c63af600e0.png">

Looking at distributed computing dashboard we see 3.7 GB RAM used for the processing when we call SAT_llt2rat for a separate chunks chunks 512x512 pixels:
<img width="828" alt="Screenshot 2022-10-17 at 12 44 52" src="https://user-images.githubusercontent.com/7342379/196101663-86106409-26e0-4d80-bdf4-54723f91827d.png">

<img width="1920" alt="Screenshot 2022-10-17 at 12 45 20" src="https://user-images.githubusercontent.com/7342379/196102058-be6f0b37-2b24-4a2a-9e87-530e10cadca1.png">

We miss all the chunk-based processing advantages using binary file trans.dat with missed values for pixels outside of the radar scene extent. That's impossible to effectively work on non-uniform data chunks produced by SAT_llt2rat in binary mode. Using SAT_llt2rat text mode we spend ~12% more CPU time but using all the available cores in case when we limit the DEM extent using the scene control points extent with small buffer. NeTCDF file allows to write the calculated chunks separately so we don't need to hold the full grid in RAM. Binary trans.dat can't be written by this way when we don't know the exact chunk sizes and so the cursor positioning  inside the file to write the chunks is not possible.

I think that's a big problem when we can't process 2+ stitched scenes even on a top tier hardware like to MacBook Pro 16 GB with price 5-6 k$ (see 8 TB SSD configuration)!

**Comment by Xiaohua-Eric-Xu** [comment]
> For 2 full scenes (2 x 3 subswaths in total) the trans.dat file has ~20 GB size. That's problematic to process it effectively on 8 GB or even 16 GB RAM host. What is the reason this file is binary instead of NetCDF chunked dataset like to other data?

trans.dat is basically a look-up table. The size of it depends on two factor. 1) the area of your DEM, 2) the resolution of your dem. So basically, it has the number of records that matches whatever is from your input dem.grd. To reduce the size, one could cut things to a smaller area. For very large scale processing, it's better to use a cluster or workstation, rather than a laptop. 

> We miss all the chunk-based processing advantages using binary file trans.dat with missed values for pixels outside of the radar scene extent. That's impossible to effectively work on non-uniform data chunks produced by SAT_llt2rat in binary mode. Using SAT_llt2rat text mode we spend ~12% more CPU time but using all the available cores in case when we limit the DEM extent using the scene control points extent with small buffer. NeTCDF file allows to write the calculated chunks separately so we don't need to hold the full grid in RAM.

If I understand correctly, you mean to cut things to pieces and run them through. Essentially the binary chunk of data could be converted to several grids i.e. llr.grd, lla.grd, and llt.grd. This'll require change to several scripts and core-modules that use trans.dat for making projection. Apart from that I think the real limit still is how much data a single program in GMTSAR/GMT reads in.

**Comment by mobigroup** [comment]
> For very large scale processing, it's better to use a cluster or workstation, rather than a laptop.

20 GB is not a large scale processing of course. As I remember, 15 years ago I worked on 100+ GB GIS databases on 1 GB RAM host (well, SQLite3 required some patches and bugfixes for my tasks and I spent some time on that). Also, 2 stitched scenes interferogram processing requires about 5-8 GB RAM by my measurements but the trans.dat file processing consumes much more while it’s much simpler. Actually, GMTSAR is based on NetCDF grids and only trans.dat is sparse raw binary file. Even more, the full translation table on DEM grid allows to geocode interferograms very easy and fast (just map every DEM lat/lon pixel with defined azimuth/range to the corresponding interferogram pixel value).

**Comment by Xiaohua-Eric-Xu** [comment]
Could it be that we are using the `|` that's taking a lot of memory? As I remember SAT_llt2rat only reads in one line at a time and output calculation results. Adding a intermediate product could reduce memory cost?

**Comment by mobigroup** [comment]
SAT_ll2rat works fine and we can split the input coordinates to call multiple SAT_ll2rat instances in parallel. But we have no way to work on the trans.dat file using a small amount of RAM because it’s unstructured and can’t be chinked properly. Using SAT_ll2rat in text mode that’s possible to obtain the output for the all input coordinates and build the same output grid as input DEM grid (5 output coordinates can be stored as 3rd dimension). This grid is the complete geocoding table and usi g it we can geocode every interferogram in a part of a second. I suppose the basic problem is that you don’t limits your DEM extent and it’s defined by user manually so the raster can be huge - as the solution we need to crop the scene area by some way. For the scene extent calculation I use Sentinel-1 ground reference points from the tiff files, also we can use Sentinel-1 bursts map and time/orbit information. I’m not sure about the exact way for other satellites while we are able to view them on online portals like to ASF and so there are some ways to map the scene extents too. At the same time, the defined scenes extent required to download the DEM automatically.

**Comment by mobigroup** [comment]
About scene coordinates I suppose all missions include them of course. For one example see ALOS PALSAR book, page 7, 8, 9 for as geographic as projected scene extent coordinates: https://earth.esa.int/eogateway/documents/20142/37627/ALOS-PALSAR-Product-Format-Description-Level-1-1.5.pdf Actually, that’s the basic requirement for any geospatial GeoTIFF and HDF/NetCDF file and ASF doesn’t have its own crystal ball to find the scenes extent :)
