### ISSUE TITLE
How to extract point values of deformation and plot them as a time series in gmt?

### ISSUE THREAD

**Issue by khakim** [gmtsar/gmtsar#49]
Dear Xiaohua,

I want to create a graph of time-series deformation from output of sbas processing. How do we extract point values of the deformation and plot them as time-series graph?

I appreciate your help.

**Comment by Xiaohua-Eric-Xu** [comment]
If you are familiar with shell, you could write a `foreach` loop and then cut out a small piece in the grid files with `gmt grdcut`, then get the value with `gmt grdinfo -L2` and then plot with `gmt psxy`. Or if you prefer Matlab/Python, I am sure there are ways to read in the netcdf files (e.g. for Matlab `ncread`). To determine which pixel to extract in radar coordinates, you could use `SAT_llt2rat` to project points in lon lat to radar coordinates. Or you could also geocode the results with `proj_ra2ll.csh`

**Comment by khakim** [comment]
I am not so familiar with shell, could you please provide me an example of the shell script?
