### ISSUE TITLE
[Feature]: how to correct by using CSS atmospheric correction method in GMTSAR 

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#491]
Hi, dear professors,
i want to know that how to use CSS atmospheric correction method in GTMSAR. But i not find information about that is there steps for that.
thank you in advance.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
I'm sorry. I don't know what that means. Is the correction method in running sbas CSS correction?

**Comment by Xiaohua-Eric-Xu** [comment]
Yes.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
When I run sbas, does it automatically turn on the option -atm3?

**Comment by hillgrey** [comment]
I am also curious about the meaning of the -atm and the -smooth parameters.
What does the parameter "3" in the option -atm 3? What is the unit, does it mean iterations? Maybe kind of like the spatial filter in the traditional SBAS method?
Same to the parameter "5" in the -smooth 5. To my understanding, this is a temporal smoother, kind of like the temporal filter, and the number 5 means "5 months", right?

**Comment by hillgrey** [comment]
> @Xiaohua-Eric-Xu When I run sbas, does it automatically turn on the option -atm3?

Dear Luvina0503, it dose NOT turn on the option "-atm 3" automatically . If you do not type anything  related with -atm, the program will skip atm correction by default.
You can just type "sbas" in your command window and check the information printed on the screen, there are usages about this issue. Thanks.

**Comment by Luvina0503** [comment]
@hillgrey 
OK.I have a try. thank you

**Comment by Xiaohua-Eric-Xu** [comment]
The -atm means to apply common-scene stacking approach to mitigate atmospheric effect. The following number means the number of iterations to run. Usually 3-5 is good enough to capture the turbulent component. Too small of a number have seasonal component absorbed in atm phase screens (aps_*.grd) and too large of a number may leave much of the atmospheric phase in the time-series. The smooth parameter is the relative weigh between smooth constraints and sbas time-series inversion. A larger smoothness parameter will give, of course, more smooth time-series solution.

**Comment by Xiaohua-Eric-Xu** [comment]
The smooth constraint is a laplacian operator on the time-series.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu @hillgrey 
I would like to ask where to download the sbas script file？

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what script you mean.

**Comment by Luvina0503** [comment]
> When running `sbas`, turn on the option `-atm 3` and it'll work on doing the correction. It'll cost much longer to run though.

@Xiaohua-Eric-Xu 
I can't find this sbas script

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
I only found Sbas. c and sbas.h, but I couldn't use the sbas script in the terminal. So I want to ask where to download the sbas script

**Comment by Luvina0503** [comment]
> When running `sbas`, turn on the option `-atm 3` and it'll work on doing the correction. It'll cost much longer to run though.
@Xiaohua-Eric-Xu 
I can't find this sbas script
![image](https://user-images.githubusercontent.com/114629377/198793913-8c914f3a-df60-4b75-9c4a-d521889cbb8b.png)

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
I found the sbas, but the operation is wrong.Why?
![image](https://user-images.githubusercontent.com/114629377/198968218-2d0c1d77-8115-4769-94a0-58faf596eba3.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You need to look for it at GMTSAR/bin. That's where all the executables are.
