### ISSUE TITLE
[Help]: Unwrapping threshold

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#492]
Hi 

I hope All doing well

What are the best values ​​that can be 
chosen 

Unwrapping threshold ?
Smoothing factor?

if the study area is sandy desert and flat land

And What is meant by smoothing factor?

and why you are using smoothing factor 40

![image](https://user-images.githubusercontent.com/108739411/196361081-34c3d5fd-2828-4c9f-9b62-169204ee5dcf.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
For sandy desert I am not sure as it should easily get decorrelated there. For flat land, if you are processing a pair, you could use 0.1, for time-series, use a common coherence mask and set a small threshold like 0.001.

**Comment by Xiaohua-Eric-Xu** [comment]
Anything between 0.1 to 10 should work. It'll apply a laplacian smoothness to the displacement time-series.
