### ISSUE TITLE
[Feature]: GACOS_correction.csh

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#494]
When I run the script, I get the following error.
![H}ZF$ _L)UD$V4GNNV16J1D](https://user-images.githubusercontent.com/114629377/196439338-b359bd1b-0e63-44be-a861-c5afc12e7bc3.png)
![Q$Z1~SPR_O5Z47L}W UAZT7](https://user-images.githubusercontent.com/114629377/196439413-08dd489f-ad1f-434c-a42d-fe8ff9e4ddce.png)

Is my command input format wrong or my ref_point wrong?
![image](https://user-images.githubusercontent.com/114629377/196439540-861faf23-4eeb-4954-bc79-668d75aebfa0.png)

**Comment by Xiaohua-Eric-Xu** [comment]
This is not a script written by us I think. You'll need to contact the author.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
I contacted the author half a month ago, but he hasn't answered my message yet.

**Comment by chintals** [comment]
I took a closer look at the GACOS_correction script. The author of the script intended for the GACOS correction to be done for each subswath. The directory to execute the script would be F*/intf_all/


If you prefer not to modify the csh script, I suggest copying the associated .SLC files from F*/intf_all/ to merge intf folders and then run GACOS correction script

**Comment by Luvina0503** [comment]
@chintals 
I see what you mean. I would like to know whether  GACOS correction script is performed before or after unwrapping?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu @chintals 
When I run this script, I can't seem to read the data from the reference file, resulting in the resulting empty ref.llh and out.ratll files.Why?

**Comment by chintals** [comment]
I haven't used the Gacos script but I believe the ref_point file should be one line

`118.084442 32.317413`

**Comment by Luvina0503** [comment]
@chintals 
I set it to one line, but I still can't read the data.

**Comment by chintals** [comment]
https://github.com/gmtsar/gmtsar/issues/506#issuecomment-1290553851

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu @chintals 
When I run the GACOS script, the problem still occurs in the reference file, resulting in an empty file. When I run the gmt grdtrack command alone, the resulting file is still empty.Why?
![36560f20554b01667083403cd0706e8](https://user-images.githubusercontent.com/114629377/197925944-5f3b2f3d-2179-4d70-9285-a66faf14cc08.jpg)
![98fc6d31d0d51c4eac49f4213f75126](https://user-images.githubusercontent.com/114629377/197925962-5eae052e-737d-45ba-afa8-dd5b0e157457.jpg)

The other problems mentioned earlier have been solved, so this is the only problem left.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu @chintals
When I run the GACOS script, the problem still occurs in the reference file, resulting in an empty file. When I run the gmt grdtrack command alone, the resulting file is still empty.Why?
![image](https://user-images.githubusercontent.com/114629377/197926482-1d63c27c-237f-4d29-961a-42405ed68ceb.png)

![image](https://user-images.githubusercontent.com/114629377/197926136-e23b4ef4-91ff-4bba-9784-ac85d3a98b9e.png)
![image](https://user-images.githubusercontent.com/114629377/197926159-78c03296-8530-44db-ab08-ce7375056d76.png)

The other problems mentioned earlier have been solved, so this is the only problem left.
