### ISSUE TITLE
[Help]: Relationship between interferogram decimation, filter wavelength and sbas grid spacing.

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#495]
I have been processing Sentinel-1 with a decimation factor of 4/1 and running sbas with a filter wavelength of 100m. Output grid spacing is 25m. I would like to obtain a denser grid with the "natural" pixel spacing of Sentinel-1 IW SLC.

If I want to have measurement points with maximum resolution of Sentinel-1, what options should I choose for both interferogram decimation and filter wavelength?

**Comment by Xiaohua-Eric-Xu** [comment]
Filter wavelength 60m and 4/1 may give you the max in geo-coordinates ~15m (azimuth sampling ~12-14m for Sentinel-1). But do note less filtering (smaller wavelength) may result in more residues in the interferogram and longer phase-unwrapping.

**Comment by SteffanDavies** [comment]
> Filter wavelength 60m and 4/1 may give you the max in geo-coordinates ~15m (azimuth sampling ~12-14m for Sentinel-1). But do note less filtering (smaller wavelength) may result in more residues in the interferogram and longer phase-unwrapping.

Any way of achieving 15x5m spacing?

**Comment by Xiaohua-Eric-Xu** [comment]
Then you need to manually change the script to do so. The sampling is done using a m2s.csh with output set to a variable to be used for sampling (line 74-76). 

Also do note the projection precision depends on the dem. If you have a high precision dem, you may want to change the sampling of raln.grd and ralt.grd as well (line 47-48).

**Comment by mobigroup** [comment]
@SteffanDavies Could you explain what advantages do you look for? We need to apply some filters (Gaussian, Goldstein) which are obviously should be larger than a single pixel matrix. Gaussian filter 100m produces noisy interferograms. Also, unwrapping is a kind of filtering too. In case when you have too small persistent scatters all of them will be dropped on the unwrapping phase as a single-pixel outliers.

**Comment by SteffanDavies** [comment]
@mobigroup I was looking to reproduce something along the lines of EGMS. 

![image](https://user-images.githubusercontent.com/50405969/197860070-0f5f56e6-d9c0-48f6-a8bc-dbc78383bd31.png)

This is an example from descending Sentinel-1 orbit. They have natural pixel spacing and while there are some noisy pixels, it is sufficient to understand local deformation. They also have a vertical products derived from asc+dsc combination on a 60m grid.

![image](https://user-images.githubusercontent.com/50405969/197860634-9a337a1c-ae3f-46e0-b820-26f8ea3d674d.png)

Thoughts?

**Comment by mobigroup** [comment]
@SteffanDavies Here RMSE is much better for 60m grid (1.2 mm vs 4.5mm). For the natural spacing case we see the high error (RMSE 4.5 mm) on 5 years timeseries for coherence 0.59. I think you might use lower coherence threshold for 30m spacing to produce the same pixels density and with the same error. Actually, you don’t have more information on the natural spacing grid and even seasonal changes are not well recognizable on it. It can be valuable to use 5m spacing to analyze 5m wide road due to spatial selectivity but for your highway it’s not the case. Also, 3 times more RMSE means you need to have 10 times longer timeseries for the same result accuracy and when we see that the pixels is stable for the last 2 years on 60m grid we can’t estimate it behavior on the natural grid.

**Comment by SteffanDavies** [comment]
@mobigroup I'm currently using a stacked coherence threshold of 0.1 but I think this may be far too low considering the time it takes to unwrap. Does PyGMTSAR allow to export pixel temporal coherence and RMSE value along with cumulative displacement and velocity? EGMS uses a third order polynomial with seasonal component to estimate these values:

![image](https://user-images.githubusercontent.com/50405969/197921143-e7e47b97-ce07-4085-af6f-9068354aec94.png)

Actually I am working with many smaller roads too so 5m spacing can be important.

**Comment by mobigroup** [comment]
@SteffanDavies we have the coherence stack and so that's easy to select the pixel coherence timeseries. RMSE calculation is straightforward too for any model. I'm going to add some nonlinear trend calculation examples and this one looks promising. 

I think 5m spatial resolution is worthless using the current GMTSAR approach based on sequential Gaussian filters for speedup. For wavelength=60m we have this filters sequence:

```
# phasediff calculation

# convolution with decimation 1 2
$ cat /usr/local/GMTSAR/share/gmtsar/filters/gauss5x5
5 5
   1.8315638888734179e-02   8.2084998623898800e-02   1.3533528323661270e-01   8.2084998623898800e-02   1.8315638888734179e-02
   8.2084998623898800e-02   3.6787944117144233e-01   6.0653065971263342e-01   3.6787944117144233e-01   8.2084998623898800e-02
   1.3533528323661270e-01   6.0653065971263342e-01   1.0000000000000000e+00   6.0653065971263342e-01   1.3533528323661270e-01
   8.2084998623898800e-02   3.6787944117144233e-01   6.0653065971263342e-01   3.6787944117144233e-01   8.2084998623898800e-02
   1.8315638888734179e-02   8.2084998623898800e-02   1.3533528323661270e-01   8.2084998623898800e-02   1.8315638888734179e-02

$ make_gaussian_filter raw_desc/S1_20220322_ALL_F1.PRM 2 1 60 /dev/stdout
 1 1 
5 3
	1.5640024738258806e-01	3.5531995734231492e-01	4.6710407546911287e-01	3.5531995734231492e-01	1.5640024738258806e-01
	3.3482954997880332e-01	7.6068691326545790e-01	1.0000000000000000e+00	7.6068691326545790e-01	3.3482954997880332e-01
	1.5640024738258806e-01	3.5531995734231492e-01	4.6710407546911287e-01	3.5531995734231492e-01	1.5640024738258806e-01

# calculate phasefilt using Goldstein filter

# one more time filter correlation
$ cat /usr/local/GMTSAR/share/gmtsar/filters/fill.3x3
3	3

	1	2	1
	2	4	2
	1	2	1

```

As you see actually we don't process the every pixel and the filters are not correct for the natural resolution. Here I'm not sure why the additional correlation filtering required... maybe @Xiaohua-Eric-Xu could explain? To produce valid results we need to apply the single Gaussian filter with the specified wavelength without decimation. Let's compare the decimated and no decimated Gaussian filters for 60m wavelength:
```
$ make_gaussian_filter raw_desc/S1_20220322_ALL_F1.PRM 2 1 60 /dev/stdout
 1 1 
5 3
	1.5640024738258806e-01	3.5531995734231492e-01	4.6710407546911287e-01	3.5531995734231492e-01	1.5640024738258806e-01
	3.3482954997880332e-01	7.6068691326545790e-01	1.0000000000000000e+00	7.6068691326545790e-01	3.3482954997880332e-01
	1.5640024738258806e-01	3.5531995734231492e-01	4.6710407546911287e-01	3.5531995734231492e-01	1.5640024738258806e-01

$ make_gaussian_filter raw_desc/S1_20220322_ALL_F1.PRM 1 1 60 /dev/stdout
 1 1 
11 3
	8.4518311356868797e-02	1.5640024738258806e-01	2.5242190052287594e-01	3.5531995734231492e-01	4.3622961182330766e-01	4.6710407546911287e-01	4.3622961182330766e-01	3.5531995734231492e-01	2.5242190052287594e-01	1.5640024738258806e-01	8.4518311356868797e-02
	1.8094107029999043e-01	3.3482954997880332e-01	5.4039755544707779e-01	7.6068691326545790e-01	9.3390238863833941e-01	1.0000000000000000e+00	9.3390238863833941e-01	7.6068691326545790e-01	5.4039755544707779e-01	3.3482954997880332e-01	1.8094107029999043e-01
	8.4518311356868797e-02	1.5640024738258806e-01	2.5242190052287594e-01	3.5531995734231492e-01	4.3622961182330766e-01	4.6710407546911287e-01	4.3622961182330766e-01	3.5531995734231492e-01	2.5242190052287594e-01	1.5640024738258806e-01	8.4518311356868797e-02
```

It'd be interesting to rewrite phasediff & phasefilt tools on Python and use the exact Gaussian filter (it should be even faster combining 2 one-dimensional Gaussian filters) but I don't have enough time right now. By the way, Python library dask_image.ndfilters calculates 2D Gaussian filter very fast and using lazy computations so in theory you'd be able to process a whole orbit interferogram on Apple Air :) Also, we could use the source GeoTIFF files directly because GeoTIFF is tiled format too (like to NetCDF) and it can be processed much more effectively than the binary SLC files. Maybe it'd be more valuable for you than just adding some option to GMTSAR shell scripts :)

P.S. And how about to use SNAPHU masking to unwrap your roads with some buffer only? I suppose you don't need to process the full area and spend a lot of time on that.

**Comment by SteffanDavies** [comment]
> @SteffanDavies we have the coherence stack and so that's easy to select the pixel coherence timeseries. RMSE calculation is straightforward too for any model. I'm going to add some nonlinear trend calculation examples and this one looks promising.
> 
> I think 5m spatial resolution is worthless using the current GMTSAR approach based on sequential Gaussian filters for speedup. For wavelength=60m we have this filters sequence:
> 
> ```
> # phasediff calculation
> 
> # convolution with decimation 1 2
> $ cat /usr/local/GMTSAR/share/gmtsar/filters/gauss5x5
> 5 5
>    1.8315638888734179e-02   8.2084998623898800e-02   1.3533528323661270e-01   8.2084998623898800e-02   1.8315638888734179e-02
>    8.2084998623898800e-02   3.6787944117144233e-01   6.0653065971263342e-01   3.6787944117144233e-01   8.2084998623898800e-02
>    1.3533528323661270e-01   6.0653065971263342e-01   1.0000000000000000e+00   6.0653065971263342e-01   1.3533528323661270e-01
>    8.2084998623898800e-02   3.6787944117144233e-01   6.0653065971263342e-01   3.6787944117144233e-01   8.2084998623898800e-02
>    1.8315638888734179e-02   8.2084998623898800e-02   1.3533528323661270e-01   8.2084998623898800e-02   1.8315638888734179e-02
> 
> $ make_gaussian_filter raw_desc/S1_20220322_ALL_F1.PRM 2 1 60 /dev/stdout
>  1 1 
> 5 3
> 	1.5640024738258806e-01	3.5531995734231492e-01	4.6710407546911287e-01	3.5531995734231492e-01	1.5640024738258806e-01
> 	3.3482954997880332e-01	7.6068691326545790e-01	1.0000000000000000e+00	7.6068691326545790e-01	3.3482954997880332e-01
> 	1.5640024738258806e-01	3.5531995734231492e-01	4.6710407546911287e-01	3.5531995734231492e-01	1.5640024738258806e-01
> 
> # calculate phasefilt using Goldstein filter
> 
> # one more time filter correlation
> $ cat /usr/local/GMTSAR/share/gmtsar/filters/fill.3x3
> 3	3
> 
> 	1	2	1
> 	2	4	2
> 	1	2	1
> ```
> 
> As you see actually we don't process the every pixel and the filters are not correct for the natural resolution. Here I'm not sure why the additional correlation filtering required... maybe @Xiaohua-Eric-Xu could explain? To produce valid results we need to apply the single Gaussian filter with the specified wavelength without decimation. Let's compare the decimated and no decimated Gaussian filters for 60m wavelength:
> 
> ```
> $ make_gaussian_filter raw_desc/S1_20220322_ALL_F1.PRM 2 1 60 /dev/stdout
>  1 1 
> 5 3
> 	1.5640024738258806e-01	3.5531995734231492e-01	4.6710407546911287e-01	3.5531995734231492e-01	1.5640024738258806e-01
> 	3.3482954997880332e-01	7.6068691326545790e-01	1.0000000000000000e+00	7.6068691326545790e-01	3.3482954997880332e-01
> 	1.5640024738258806e-01	3.5531995734231492e-01	4.6710407546911287e-01	3.5531995734231492e-01	1.5640024738258806e-01
> 
> $ make_gaussian_filter raw_desc/S1_20220322_ALL_F1.PRM 1 1 60 /dev/stdout
>  1 1 
> 11 3
> 	8.4518311356868797e-02	1.5640024738258806e-01	2.5242190052287594e-01	3.5531995734231492e-01	4.3622961182330766e-01	4.6710407546911287e-01	4.3622961182330766e-01	3.5531995734231492e-01	2.5242190052287594e-01	1.5640024738258806e-01	8.4518311356868797e-02
> 	1.8094107029999043e-01	3.3482954997880332e-01	5.4039755544707779e-01	7.6068691326545790e-01	9.3390238863833941e-01	1.0000000000000000e+00	9.3390238863833941e-01	7.6068691326545790e-01	5.4039755544707779e-01	3.3482954997880332e-01	1.8094107029999043e-01
> 	8.4518311356868797e-02	1.5640024738258806e-01	2.5242190052287594e-01	3.5531995734231492e-01	4.3622961182330766e-01	4.6710407546911287e-01	4.3622961182330766e-01	3.5531995734231492e-01	2.5242190052287594e-01	1.5640024738258806e-01	8.4518311356868797e-02
> ```
> 
> It'd be interesting to rewrite phasediff & phasefilt tools on Python and use the exact Gaussian filter (it should be even faster combining 2 one-dimensional Gaussian filters) but I don't have enough time right now. By the way, Python library dask_image.ndfilters calculates 2D Gaussian filter very fast and using lazy computations so in theory you'd be able to process a whole orbit interferogram on Apple Air :) Also, we could use the source GeoTIFF files directly because GeoTIFF is tiled format too (like to NetCDF) and it can be processed much more effectively than the binary SLC files. Maybe it'd be more valuable for you than just adding some option to GMTSAR shell scripts :)
> 
> P.S. And how about to use SNAPHU masking to unwrap your roads with some buffer only? I suppose you don't need to process the full area and spend a lot of time on that.

You mean like a binary mask for Snaphu? I could try making one in Qgis and save as GeoTiff. I noticed you use binary masking in one of your notebooks so I'll have to read with some attention. A 1km buffer should be more than enough and reduce unwrapping times significantly. Road vector data can be obtained easily using OSM.

**Comment by mobigroup** [comment]
@SteffanDavies Maybe do you need some example how to obtain OSM data and create the SNAPHU mask using Python only? That’s easy but I didn’t share the examples yet.
