### ISSUE TITLE
Master's Choice

### ISSUE THREAD

**Issue by Obaida777** [gmtsar/gmtsar#496]
Dear All,

What is the best way to choice master image in GMTSAR (SBAS)?

1- Take the Oldest one.
2- Using SNAP to Choice in it.
3- other conditions. 

Best Regards 
@Xiaohua-Eric-Xu 
@mobigroup 
@dsandwell 
@chintals

**Comment by Xiaohua-Eric-Xu** [comment]
For the newer generation of satellites which have excellent orbit control, picking master image is not as critical. Finding someone in the middle of the baseline time plot should be the simplest way. For certain approach such as PS (as for StaMPS), you may want to pick one in middle of time too.

**Comment by Obaida777** [comment]
So Your suggestion in my Case for land Subsidence (SBAS), I should Choice my Master in the middle by Using SNAP Software?

**Comment by Xiaohua-Eric-Xu** [comment]
Doesn't have to rely on any software I think. Just pick one.
