### ISSUE TITLE
[Help]: SBAS error  vel.grd = 0

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#497]
gmt grdinfo vel.grd
vel.grd: Title: Mean Line-Of-Sight velocity from SBAS
vel.grd: Command: sbas_parallel intf.tab scene.tab 285 144 4274 3267 -range 879139 -incidence 43 -wavelength 0.0554658 -smooth 5.0 -rms -dem -atm 1 
vel.grd: Remark: Mean LOS velocity from SBAS (mm/yr)
vel.grd: Pixel node registration used [Cartesian grid]
vel.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
vel.grd: x_min: 0 x_max: 68384 x_inc: 16 name: x n_columns: 4274
vel.grd: y_min: 0 y_max: 13068 y_inc: 4 name: y n_rows: 3267
vel.grd: v_min: 0 v_max: 0 name: z
vel.grd: scale_factor: 1 add_offset: 0
vel.grd: format: netCDF-4 chunk_size: 130,131 shuffle: on deflation_level: 3
vel.grd: Default CPT: 

compute RMS misfit
compute DEM error

setting smoothing to   5.000 
setting radar wavelength to   0.055 m 
setting radar incidence angle to  43.000 degree 
setting range to 879139.000 m 
number of SAR scenes is 144 
number of interferograms is 285 

Applying atmospheric correction by common point stacking...

Hit Matrix:
2017139 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
2017163 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
...
2022101 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 
2022113 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by chintals** [comment]
Can you type ncview vel.grd in terminal?  Sometimes the z info does not show up for grd files,

**Comment by Xiaohua-Eric-Xu** [comment]
Or could it be that you didn't apply a common coherence mask when doing phase unwrapping so things decorrelate here and there inconsistently through time and in the end leaving the whole area blank (nan)? 

A funny thing I realize is that the second atm correction gives you all zero estimates on RMS of the atmospheric phase screens. Something's incorrect but I am not sure what's the probable cause (except the one above). FYI, sbas_parallel was updated a couple of times earlier this year to get rid of a memory leakage problem.

**Comment by swjiaotong-jyliu** [comment]
Thanks for your reply, I used an average mask of 0.35, but the latest calculation of sbas_parallel.csh still assigns atm_noise a value of 0.

This is average corr.grd。
![image](https://user-images.githubusercontent.com/86451834/197103391-41367231-117b-44d2-b88a-cfd8ef95a12f.png)

**Comment by swjiaotong-jyliu** [comment]
I used 0.35 GE 0 NAN 
and snaphu 0.01 then.

**Comment by swjiaotong-jyliu** [comment]
And I use the nlatest sbas_parallel

![image](https://user-images.githubusercontent.com/86451834/197132507-127f3498-2d4b-4cc2-b231-e7e4943a1ce4.png)

I get same output.
May set snaphu 0.2?

**Comment by Xiaohua-Eric-Xu** [comment]
So if I understand correctly, you set 0.35 for masking with mask_def.grd and then ran snaphu_interp.csh 0.01. If that's the case, you should get valid results. Could you try turning off -atm 1 and re-run sbas?

The line below is also a bit alarming as
```
```

**Comment by swjiaotong-jyliu** [comment]
Thanks for your advise，and it is really useful。
And
I set reference point as below
（thanks for [Xiaohua-Eric-Xu]`s advice I use gmtcut and gmtmath set gps surroundingregion to gps）

![43cf5498a97890be0dbd781cbc057ee](https://user-images.githubusercontent.com/86451834/198066245-5dfd0710-1058-49be-996d-3acd99ebe07d.jpg)
Orenge is for insar and bluw is GPS

then I contrast in another point.

![ef116fb709206de166710b00fc210df](https://user-images.githubusercontent.com/86451834/198066529-238e5527-4c47-4d66-85e2-324f05fdc6dc.jpg)

How to see the difference between them？

**Comment by swjiaotong-jyliu** [comment]
Because only two GPS point are useful in this Frame in north China.

**Comment by Xiaohua-Eric-Xu** [comment]
Looks great, beautiful seasonal. I would just reference to both of them (i.e. remove a plane with minimal RMS). Of course, three would be much better. InSAR are more affected by atmospheric noise at larger wavelength.

**Comment by Luvina0503** [comment]
@swjiaotong-jyliu 
Hello, where did you download your sbas script

**Comment by Luvina0503** [comment]
@swjiaotong-jyliu 
How did you generate this comparison chart？
