### ISSUE TITLE
preproc_batch_tops_esd.csh doesn't work

### ISSUE THREAD

**Issue by khakim** [gmtsar/gmtsar#50]
Dear Xiaohua,
Due to clear burst boundaries when using preproc_batch_tops.csh, I used preproc_batch_tops_esd.csh. Unfortunately the preproc_batch_tops_esd.csh doesn't work. I used the same input files as preproc_batch_tops.csh.
How to fix this problem.
Below the processing history:
preproc_batch_tops_esd.csh data.in dem.grd 2

Usage: preproc_tops_batch.csh data.in dem.grd mode esd_mode
  preprocess and align a set of tops images in data.in, precise orbits required

  format of data.in:
    image_name:orbit_name

  example of data.in
    s1a-iw1-slc-vv-20150626...001:s1a-iw1-slc-vv-20150626...001:s1a-iw1-slc-vv-20150626...001:S1A_OPER_AUX_POEORB_V20150601_20150603.EOF
    s1a-iw1-slc-vv-20150715...001:s1a-iw1-slc-vv-20150715...001:s1a-iw1-slc-vv-20150715...001:S1A_OPER_AUX_POEORB_V20150625_20150627.EOF

  outputs:
    baseline.ps align_table.ra (contains info for precise geomatric alignment)
    *.PRM *.LED *.SLC(mode 2)

  esd_mode:
    0 for average, 1 for median, 2 for interpolation

  Note:
    The names must be in time order in each line to be stitched together

**Comment by Xiaohua-Eric-Xu** [comment]
I think I made a fix to the master.
