### ISSUE TITLE
[Help]: Invalid dates running organize_files_tops_linux.csh

### ISSUE THREAD

**Issue by Tijn-Nederstigt** [gmtsar/gmtsar#500]
Hi,

I have started my first test run wit GMTSAR and I am encountering a problem running organize_files_tops_linux.csh. I have shared my logfile as well as the pin.ll file and SAFE_filelist. 

I have tried slashing the spaces in my directory names as was proposed in a previous Issue, but to no avail. I would be really curious to hear if anyone here has encountered this problem and knows of a solution.

Problem details as follows:

OS: WSL 2 on Windows 10
GMTSAR version: 6.2.2

log: [oft_mode2.log](https://github.com/gmtsar/gmtsar/files/9832580/oft_mode2.log)
SAFE_filelist: [SAFE_filelist.txt](https://github.com/gmtsar/gmtsar/files/9832593/SAFE_filelist.txt)
PINS: [pins.ll.txt](https://github.com/gmtsar/gmtsar/files/9832638/pins.ll.txt)

![image](https://user-images.githubusercontent.com/116302194/197019408-07441151-3808-49e4-b9fd-8cacd6af4e28.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I think it's because your names has spaces in them but are not properly represented in the filelist. Either delete the space or use backslash space (not sure it'll work though).

**Comment by Tijn-Nederstigt** [comment]
Dear Xiaohua,

Thanks for your reply. I have removed the spaces (see updated FILE_list, and even though this might result in problems later on in the script, the program seems to extract a date from each line.

[SAFE_filelist.txt](https://github.com/gmtsar/gmtsar/files/9836314/SAFE_filelist.txt)

The problem is that the dates the program extracts are off by one character, this means that the program always returns an error because the dates are not found in the ESA database. See below:

[oft_mode2.log](https://github.com/gmtsar/gmtsar/files/9836319/oft_mode2.log)

My question is two-fold:
1) has to problem to due with my SAFE_filelist, or could it just be solved by offsetting the substring by one character in:
set date1 = `echo $file1 | awk '{print substr($1,length($1)-54,8)}'`

2) even with backslashes or quotation marks, my tmprecord still breaks off the path at /mnt/c/Users/veege/Veegeo_ . Is it possible to adjust the line 

set file1 = `echo $line | awk -F"," '{print $1}'` 

in a way, to properly represent the spaces in the output?

**Comment by Xiaohua-Eric-Xu** [comment]
For the error in your oft_mode2.log, I suspect you have some pending characters like `^M` in your input that's causing the failure. Not so much related to the space representation for the moment. 
![image](https://user-images.githubusercontent.com/16844111/197359591-c9293808-48cf-4e97-bc41-259e6495ed8a.png)

**Comment by Tijn-Nederstigt** [comment]
Hi Eric,

Due to the problem of the drive name with the space, I wasn't able to continue with this program for I while. I now have a new computer allowing me to run the program in paths without spaces. Yet the same problem of invalid dates persists. The program seems to scan for the data substring one character too late.

Could you have a look and see whether you see a problem?

[oft_mode1.log](https://github.com/gmtsar/gmtsar/files/10287216/oft_mode1.log)
[SAFE_filelist.txt](https://github.com/gmtsar/gmtsar/files/10287215/SAFE_filelist.txt)

Kind regards,
Tijn

**Comment by Tijn-Nederstigt** [comment]
I found the solution to this error. The cause is MS-DOS line endings which are not read correctly by the program. This was the result of preparing the input files for the code in a Windows environment. By changing the line endings of SAFE_filelist to "\n", the program executed correctly.

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, windows would append an extra character at the end of each line which causes trouble. Usually I would just use `ls -d $PATH_TO_YOUR_SAFE_FILES/*.SAFE > SAFE_list` to get the input list for the script.
