### ISSUE TITLE
[Help]: Swath lines visible in Sentinel Descending pass in unwrap.pdf

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#501]
Hie Eric,
I have processed my AOI but I have lines of swaths in my descending path in unwrap.pdf, but the same area in Ascending is continuous and smooth,
According to you what could be the reason for this one?
![Screenshot from 2022-10-21 11-22-56](https://user-images.githubusercontent.com/88940973/197123222-d440c311-fd6d-4bfa-b4e4-59ac94d8b583.png)

and also could you please tell me if unwrapping is giving this Warning, is this a matter of concern?

_grdsample: Warning: (s - y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdsample: Warning: s reset from 2500 to 2503.61689106
grdsample: Warning: (n - y_min) must equal (NY + eps) * y_inc), where NY is an integer and |eps| <= 0.0001.
grdsample: Warning: n reset from 8500 to 8502.69889841_

**Comment by Xiaohua-Eric-Xu** [comment]
You'll need to let me know what you did (more details). Does the phasefilt.grd-s in your merge/day1_day2 directories have similar issue? If so this is from merging or potentially using wrong PRM files.
