### ISSUE TITLE
[Help]: landmask

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#503]
Hello everyone 🌹

I hope All doing well

When I run this script 
gmt gridinfo phasefilt.grd 
to show minX/maxX/minY/maxY for landmask, 
these values ​​are not shown in the terminals

![image](https://user-images.githubusercontent.com/108739411/197503176-836942dd-7408-4471-bd25-c364f11b84a5.jpeg)

How can i show it?

And this is the study area. Do I have to make a landmask for it?

![image](https://user-images.githubusercontent.com/108739411/197503939-9ead355b-de6c-4dcb-bcb9-cd9d4eecf7d8.jpeg)

**Comment by chintals** [comment]
the command should be `grdinfo `not `gridinfo`

`gmt grdinfo phasefilt.grd`
