### ISSUE TITLE
[Help]: cd : too many arguments 

### ISSUE THREAD

**Issue by Obaida777** [gmtsar/gmtsar#504]
Dear All,
I hope this message finds you well. 

When I'm trying to Run this command in merge directory

 (merge_batch.csh merge_list batch_tops.config)

I get (cd : too many arguments)
Like the picture below how i can Avoid this issue, please any Solution. 
![IMG_20221024_181921_175.jpg](https://user-images.githubusercontent.com/111499416/197563063-a59c89f1-d745-4314-8903-44ab033541b4.jpg)

@chintals @Xiaohua-Eric-Xu @kguns32 

Best Regards

**Comment by Xiaohua-Eric-Xu** [comment]
Same as @chintals, what's in your merge_list file? Especially does your path has any space in it that's not properly presented?

**Comment by Obaida777** [comment]
@chintals off course it Is an experiment sample to my work 
[merge_list.TXT](https://github.com/gmtsar/gmtsar/files/9855285/merge_list.TXT)

**Comment by Obaida777** [comment]
@Xiaohua-Eric-Xu Dear Dr.Eric this is full path for merge_list  (/media/insar/B604D1A404D167BF/Rumaila 2/asc/merge/merge_list)
![Screenshot from 2022-10-24 23-42-48](https://user-images.githubusercontent.com/111499416/197627701-5e7efe04-aad1-412d-a831-b924c8108081.png)

Couple Days from now it work very well, today when i try to run again i get this issue.

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, strange. Did any directories get generated after you ran merge_batch.csh? e.g. `2017153_2017249`

**Comment by Obaida777** [comment]
@Xiaohua-Eric-Xu Thank you Dear problem Solved.

**Comment by Xiaohua-Eric-Xu** [comment]
I still don't know how it get solved but glad it's working.

**Comment by Obaida777** [comment]
There was a space in my External Hard Path.

**Comment by Xiaohua-Eric-Xu** [comment]
Ah, that should be it! Cheers.

**Comment by Obaida777** [comment]
Cheers
