### ISSUE TITLE
[Help]: Convert GRD from Azimuth to coordinates on Longitude and Latitude

### ISSUE THREAD

**Issue by omarwater98** [gmtsar/gmtsar#505]
Hi EveryOne im trying to project a .grd file from Azimuth and Range to Latitude and Longitud or UTM coordinates, did someone know how to do this?

![Projectar un archivo grd a utm](https://user-images.githubusercontent.com/113547446/197648967-c0730017-3dac-490c-a9b9-a8ca518d82ef.png)

**Comment by omarwater98** [comment]
[proj_ll2ra.csh](https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/proj_ll2ra.csh)
[Improve grdimage plots, produce PDF rather than PS](https://github.com/gmtsar/gmtsar/commit/0661de2553a4a0db7d40b20ecf76969099f8e3dc)

**Comment by Xiaohua-Eric-Xu** [comment]
I think you mean `proj_ra2ll.csh`. It'll convert your grid in radar coordinates to geo-coordinates using a file called `trans.dat`.
