### ISSUE TITLE
[Feature]: GACOS data problem

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#506]
Hi.Dear professors,
This is the data I downloaded from the GACOS website.
I would like to ask why there is no *.ztD. rsc format in it? This format is required for GACOS atmospheric correction.
![image](https://user-images.githubusercontent.com/114629377/197716046-dd43ae83-8262-418c-80b6-e5a53cae6f04.png)

**Comment by chintals** [comment]
You need to select and download binary grid file for gacos request
![image](https://user-images.githubusercontent.com/25990795/197785944-eef0531f-f7a3-4188-b596-0356bd45a1f8.png)

**Comment by Luvina0503** [comment]
OK.Thank you
