### ISSUE TITLE
[Help]: Selection of good interferograms before SBAS

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#507]
Hie Eric,
I have processed my AOI with GMTSAR during that one I have selected the good intf with matlab code but this reading phase.grd file process is very heavy on matlab.
Can we do something to visualise the intf in gmt and then selected intf can form a list of ref_id_rep_id dir?
And also if we can check whether discarding the intf have impacted in missing the number of scenes or not.
Before going for unwrapping and sbas and make this process streamline the current existing recipe?

Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
I always use a program called `ncview` to do a rough visualization on netcdf files. To check the existing scenes, try `awk '{printf("%.7d\n%.7d\n", $3,$4)}' intf.tab | sort -n | uniq`
