### ISSUE TITLE
[Feature]: gmt grdtrack

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#508]
Hi. Dear professors,
I would like to ask why the test file is empty when I run this command？
![image](https://user-images.githubusercontent.com/114629377/197924336-485036b4-06f2-4c93-9c52-43714a0d6979.png)
![image](https://user-images.githubusercontent.com/114629377/197924371-48d92b36-0d79-436a-8b41-8eb704b4344b.png)

**Comment by Xiaohua-Eric-Xu** [comment]
If you do a `gmt grdinfo` on your dem.grd, what does it say?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
![image](https://user-images.githubusercontent.com/114629377/198178738-540425c7-0e4e-4f3c-88ea-3c582f7e31cb.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You may have noticed that 118.08 is smaller than your x_min 118.339. This reference point is not inside the region of your dem.grd. Also 32.32 is larger than your y_max 32.248, as well.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
Should I choose the corner of dem.grd as the reference point? I started with a corner of SAFE as the reference point.I do not know how to select the reference point is correct, will have other effects on the later process

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
Can the generated grd file be viewed as a picture？

**Comment by Xiaohua-Eric-Xu** [comment]
You'll need to pick a point that's covered by your data. If you don't have data at a point, how are you gonna make it a reference?

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu Can the generated grd file be viewed as a picture？

Yes, you could plot the netcdf file with `gmt` or use `ncview` for a quick display. You could also use `ncread` in matlab to read the data and plot it.

**Comment by Luvina0503** [comment]
> ou'll need to pick a point that's covered by your data. If you don't have data at a point, how are you gonna make it a reference?
@Xiaohua-Eric-Xu 

I'll take the middle point as the reference point, okay? The data at the middle point is calculated

**Comment by Xiaohua-Eric-Xu** [comment]
That'll be fine as long as there is no very active deformation there.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
I also don't know if there are active deformation areas, how to check?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
![image](https://user-images.githubusercontent.com/114629377/198476112-99a169a8-8126-4488-844b-e953530954e9.png)
This is my result after GACOS atmospheric correction, how to see the correction effect？

**Comment by Xiaohua-Eric-Xu** [comment]
You seemed to have masked out lots of pixels. That's fine as long as it gives you what you want. Here "no very active deformation" means not your area of interest and no known large activities going on like a volcano.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
My study area is not in the volcanic area. This is an image that I used ncview to view
