### ISSUE TITLE
detrend_before_unwrap.csh

### ISSUE THREAD

**Issue by khakim** [gmtsar/gmtsar#51]
Dear all,

I would like to use "detrend_before_unwrap.csh". I used the command line as 
 detrend_before_unwrap.csh S1_20170222_ALL_F2 1-5 0/2375/0/1800.

I got a message "F1-5/intf/*/: No match."

I am wondering about input parameters below
detrend_before_unwrap.csh master #  bounds

I really appreciate our help.

Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
I think that script was written by Eric Lindsey for ALOS-2 ScanSAR data. If you want to detrend your unwrapped interferogram, simply use `gmt grdtrend`.

**Comment by LaMarcha** [comment]
Dear Eric,

One quick question.
So if I detrend my unwrap phase with "detrend_before_unwrap.csh" or with gmt grdtrend.
Do we have also to set a reference area as zero?
Or this reference is no longer necessary after detrending?

Thank you
