### ISSUE TITLE
[Help]:gmt

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#511]
Hi 

how can I convert any disp……grd to jpg and add scale like this

![image](https://user-images.githubusercontent.com/108739411/198094811-53546958-4aeb-42ea-8cfb-60f6fecf28dd.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
You could use the `GMT` software, e.g. `gmt grdimage`. Or use matlab `ncread` to read in the data and then make plots. I believe for Python you could do the same.
