### ISSUE TITLE
clarification about Poor coherence AOI 

### ISSUE THREAD

**Issue by Obaida777** [gmtsar/gmtsar#512]
Good evening For All,

Q/1
I'm just trying to understand and dealing with the number in the script  below( sentinel_time_series_5.pdf=page 25) and what it (0.075, GE, 0)  mean?

(gmt grdmath corr_stack.grd 0.075 GE 0 NAN = mask_def.grd)

@Xiaohua-Eric-Xu 
@chintals 
Best Regards

**Comment by Xiaohua-Eric-Xu** [comment]
This is a math format called `reverse polish notation`. In other words, you take the operator works with its operands in front. For that specific line, it means `if (pixel >= 0.075) pixel = 1 else pixel = 0` and then `if (pixel == 0) pixel = NaN`, here pixel is in corr_stack.grd. Check this page too: https://docs.generic-mapping-tools.org/dev/grdmath.html.

**Comment by Obaida777** [comment]
@Xiaohua-Eric-Xu Thank you Mr. Eric
