### ISSUE TITLE
[Help]: Georeferencing Intfs

### ISSUE THREAD

**Issue by krkrueger** [gmtsar/gmtsar#513]
Running a few intfs after a few months off from doing any (relatively new to the process). Having an issue where it seems like the _ll georeferenced files seems to be shifted by a few miles from other WGS 1984 data. (Using sentinel-1 images)  It is hard for me to debug, so just figured I would check to make sure there wasn't anything real simple that I missed, like a setting in one of the steps that helps with alignment.

**Comment by omarwater98** [comment]
The same thing happens to me, I know that the file is exported with the longitude and latitude coordinates but it does not contain a coordinate system and it shows domain errors. That is, the indefinite spatial unit.
![z sistemad de coordenadas](https://user-images.githubusercontent.com/113547446/198418001-321c20c6-a5e9-43bb-9f09-89a854f4495e.png)
![zError de dominio](https://user-images.githubusercontent.com/113547446/198418002-9db8b411-9f71-4376-93c5-8c664fa8e8a7.png)

**Comment by Xiaohua-Eric-Xu** [comment]
> Running a few intfs after a few months off from doing any (relatively new to the process). Having an issue where it seems like the _ll georeferenced files seems to be shifted by a few miles from other WGS 1984 data. (Using sentinel-1 images) It is hard for me to debug, so just figured I would check to make sure there wasn't anything real simple that I missed, like a setting in one of the steps that helps with alignment.

Any examples showing the offset? I want to make sure whether this is a geocoding issue or displaying issue.

**Comment by Xiaohua-Eric-Xu** [comment]
> The same thing happens to me, I know that the file is exported with the longitude and latitude coordinates but it does not contain a coordinate system and it shows domain errors. That is, the indefinite spatial unit.
> 
> Me looks like its called the terrain correction !

Forgive me if I am getting this incorrectly,  but isn't longitude/latitude a coordinate system? You could easily transfer to others like UTM with `gmt mapproject` I assume.

**Comment by krkrueger** [comment]
Ok I got it figured out, and no one will probably have the same issue as I created it myself.  I was using some auto_gmtsar scripts that Eric wrote to get some of the parallel processing to work, snaphu_parallel in particular which I could not get to work with the standard scripts. But the code did not handle the merge.  So I added the merge step in myself, but the problem was I forgot to add in the trans.dat file recreation after the merge.  So for example after merge, unwrap and geocode, it was able to complete by just using the trans.dat from F1, instead of the one created between F1 and F2.  It was dangerous because everything looked right, and it was almost geolocated correctly, but not quite.  When I made sure to create the new trans.dat during the merge, and use the merge version, everything went where it was supposed to. 

Thanks for the response, I will see myself out...

**Comment by omarwater98** [comment]
> > Ejecutando algunos intfs después de unos meses sin hacer nada (relativamente nuevo en el proceso). Tener un problema en el que parece que todos los archivos georreferenciados parecen estar desplazados unas pocas millas de otros datos WGS 1984. (Usando imágenes de Sentinel-1) Es difícil para mí depurar, así que pensé en verificar para asegurarme de que no había nada realmente simple que me perdiera, como una configuración en uno de los pasos que ayuda con la alineación.
> 
> ¿Algún ejemplo que muestre el desplazamiento? Quiero asegurarme de si se trata de un problema de codificación geográfica o de visualización.

Let's say WGS-84: World Geodetic System [Default] (1984) is the default coordinate system that uses GMT for conversions from Azimuth and Range and the units it uses are latitude/longitude in degrees.

After applying proj_ra2ll.csh to a file for example los_grad.grd a logical location for the study area I am using would be: Longitude -100.3, Latitude 23.5 as shown in the DEM.grd file downloaded from the https:// page topex.ucsd.edu/gmtsar/demgen/
![z dem topex](https://user-images.githubusercontent.com/113547446/198696715-55c16485-afb9-4830-b938-b0cda29439b6.png)

On the other hand, the new product file, continuing with the example: los_grad_ll.grd, shows us a result with coordinates like these:
Length 259.705555556
Latitude 23.5124999996
Out of range for length.
![z dem convertido](https://user-images.githubusercontent.com/113547446/198696742-49ecd5dd-b979-4a97-b5f4-14ff08ce7e0a.png)

Since the intention is to assign a coordinate system, it seems that in reality it does not have one, because it does not respect the DEFAULT which is WGS-84.

**Comment by Xiaohua-Eric-Xu** [comment]
> On the other hand, the new product file, continuing with the example: los_grad_ll.grd, shows us a result with coordinates like these:
> Length 259.705555556
> Latitude 23.5124999996
> Out of range for length.

This is due to your GMT default setup. For geo-coordinates, it could be 0~360 or -180~180. You can change your gmt.conf if you wanna switch between them I think. https://docs.generic-mapping-tools.org/6.2/gmtdefaults.html#:~:text=There%20are%20three%20ways%20to,run%20gmtdefaults%20%2DD%20%3E%20gmt.
