### ISSUE TITLE
[Feature]: SBAS

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#517]
I generated two grd file after GACOS correction. May I ask which corrected grd file should be used in SBAS processing？

![image](https://user-images.githubusercontent.com/114629377/198480811-4c174312-9037-46bd-9209-e5c4900b9ac9.png)
![image](https://user-images.githubusercontent.com/114629377/198480315-38d94c21-fd1c-4fcd-aa86-a4eac65ed2bb.png)
![image](https://user-images.githubusercontent.com/114629377/198480645-bbca02d3-52f0-4232-9cae-659c8da1aa27.png)

**Comment by Luvina0503** [comment]
@Alzaidy1 
You need to download the data from the GACOS website, put it in the F*/intf_all file, and run GACOS_correction.csh

**Comment by Luvina0503** [comment]
No.Because the GACOS_correction.csh script requires an unwrap file, unwrap must be executed first

**Comment by Luvina0503** [comment]
@Alzaidy1 
No.Because the GACOS_correction.csh script requires an unwrap file, unwrap must be executed first

**Comment by Luvina0503** [comment]
@Alzaidy1 
That's something I don't understand yet. I don't even know how effective this correction is, but it's still under study.

**Comment by Luvina0503** [comment]
@zth1015 
The problem error should be in the red box. The main reason is that your reference points are out of the maximum range of resample_zpdd.grd. You can check the x_max/y_max value of resample_zpdd.grd at gmt grfinfo. And then run it again
![JJL)Y)3BA D4MOD9S} N67](https://user-images.githubusercontent.com/114629377/200267894-7ea3f500-ec0f-42f5-b284-4787cb53df15.png)

**Comment by zth1015** [comment]
@Luvina0503 
Thank you very much for your reply.
But I looked for it and there wasn't "resample_zpdd.grd".

**Comment by Luvina0503** [comment]
@zth1015 
Switch to the directory where gacos_operation.csh is stored and run sudo gedit gacos_operation.csh. Once the csh file is open, modify the last few lines of the command (as shown below), and click Save. Re-run the GACOS_correction.csh command. resample_zpddm.grd will appear in the interference file.
![D9{0T(ZLV@@@ 1PKQ_AZ4](https://user-images.githubusercontent.com/114629377/200273673-ed6b1ec1-7c39-4f61-97a1-dd6df7bb3946.png)

Command:
cd /usr/local/GMTSAR/bin/
sudo gedit  gacos_operation.csh
proj_ra2ll.csh trans.dat resample_zpddm.grd 1.grd   (Radar coordinates to latitude and longitude coordinates)
gmt grdinfo 1.grd

**Comment by zth1015** [comment]
@Luvina0503 
Thank you very much for your reply.
According to what you said, after the modification is completed, the same mistake is still reported as before. There is no running result at the end. I don't know what to do. 
Could you please help me check if there is a problem with my file format?
Thanks.
![微信图片_20221107173633](https://user-images.githubusercontent.com/116501665/200277187-8b43fd20-bf78-468f-8959-7131b0a795e7.png)

**Comment by Luvina0503** [comment]
@zth1015 
I don't see anything wrong with that. You can open the gacos_operation.csh and GACOS_correction.csh files to see where your error went wrong in the text, and then debug and correct it
