### ISSUE TITLE
[Help]: if: Badly formed number.

### ISSUE THREAD

**Issue by Baiys2000** [gmtsar/gmtsar#519]
**Describe the problem you met**

When I run <intf_tops.csh one.in batch_tops.config> , it shows <if : Badly formed number.>
**OS and software version**

OS: Ubuntu 20.04.5 LTS

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?
I am trying to make a serise of interference by three .SAFE of a same place,. i follow a course which could work every steps untill this step:  intf_tops.csh one.in batch_tops.config
**Log file**

**Screenshot**
If applicable, attach a Screenshot to help us understand your case
![1UC1H2KHYB)VWR_YZUJ E`1](https://user-images.githubusercontent.com/96607590/198507618-56005415-2584-49df-a918-1d3ad9ec0bb7.png)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
I've seen this error happening for a while and most of the cases it is some pending characters in your input file (here maybe one.in). Please check whether there are any strange characters like `^M` in your input text file.

**Comment by Baiys2000** [comment]
> I've seen this error happening for a while and most of the cases it is some pending characters in your input file (here maybe one.in). Please check whether there are any strange characters like `^M` in your input text file.

sorry, I have check it many times,but it still doesn't work,
![TG)CHT)C0MWPDP1 ``WG8IS](https://user-images.githubusercontent.com/96607590/198815373-bcaa8183-9a4b-4f7c-93be-78fa4ee87b93.png)
is it the number of SLCs causing the problem?, I only slect three SLCs for testing?

**Comment by Xiaohua-Eric-Xu** [comment]
You may need to open it in linux with vim. Windows does not tell the difference I think.

**Comment by Baiys2000** [comment]
sorry for disturbing you @Xiaohua-Eric-Xu  ,this time i try 24 SLCs 
i check many times
however , the same problem appear again:
![D@CM4~OLTXSXXYIJP I@WMW](https://user-images.githubusercontent.com/96607590/199457221-c0877c47-cab0-4d25-8333-77f3ff474a02.png)

![9XVW$0_WE8KC2K2W)~C}D$P](https://user-images.githubusercontent.com/96607590/199457248-c05126d2-2ff8-442b-bb05-821d09a6055d.png)

![49}ATLC{K5250)~NVZZ5SQQ](https://user-images.githubusercontent.com/96607590/199457265-fc230d45-8bd8-42a7-bb22-2ded1e8f6f93.png)

**Comment by Baiys2000** [comment]
another problem i met is that:
![X2GIQCEOHUJL8DSSF99 $Z1](https://user-images.githubusercontent.com/96607590/199465780-3c9baa7a-f345-4c52-8720-a726f837b0ef.png)

when i do 
![7} RAJIJ D%Z}D$GA%~UGB0](https://user-images.githubusercontent.com/96607590/199465956-5d4707bb-d656-4fbc-94ca-f72339cf9e1e.png)

i don't know  the reason either

**Comment by Xiaohua-Eric-Xu** [comment]
What if you replace your one.in with `echo "S1_20210706_ALL_F1:S1_20210916_ALL_F1" > one.in` and re-run the command? And could you share your batch_tops.config file?

The "Couldn't open" error could be from a few cases, e.g. the file is not readable to you.

**Comment by Baiys2000** [comment]
dear doctor, i try it again, and i do all steps in linux, which make it sucessful. i think that the reason of bug  is that i creat .in and .configfiles in windows and deliver them to server.
however, there maybe some wrong in my data, some oribit data couldn't be used as shown before.
thank you for your advice again.

**Comment by Xiaohua-Eric-Xu** [comment]
Yes, sometimes windows would attach a `^M` at the end of a line, which will cause an unrecognized character for shell script.
