### ISSUE TITLE
[Help]: GNSS

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#521]
Hello everyone 

What should I do if the area does not contain stations and there is no GNSS or GPS for the area, how will I calculate the deformation, knowing that the study area located in Iraq/Basra

![image](https://user-images.githubusercontent.com/108739411/198884305-1d0af4ed-2f8e-4eac-991f-b2607c1106b5.jpeg)

**Comment by omarwater98** [comment]
I like your questi

**Comment by Xiaohua-Eric-Xu** [comment]
With no GNSS, you could choose to reference your measurement to a position in your deformation map.

**Comment by Xiaohua-Eric-Xu** [comment]
You could 1) select a point you'd like to reference to in your deformation map; 2) shift each interferogram so unwrapped phase is zero at your selected point (do that with GMT or the way you like); 3) run sbas to get deformation time-series and velocity maps.

**Comment by Obaida777** [comment]
1) the point you are suggesting to be as Reference, in what conditions should be in( subsidence areas, or in areas that it had be good coherence and i must be checked the area before).
2) what you mean by (shifting each interferogram in GMT).

**Comment by omarwater98** [comment]
> 1. the point you are suggesting to be as Reference, in what conditions should be in( subsidence areas, or in areas that it had be good coherence and i must be checked the area before).
> 2. what you mean by (shifting each interferogram in GMT).

On Subsidence area, its supose you wanna know the tendence there

**Comment by Xiaohua-Eric-Xu** [comment]
> 1. the point you are suggesting to be as Reference, in what conditions should be in( subsidence areas, or in areas that it had be good coherence and i must be checked the area before).
> 2. what you mean by (shifting each interferogram in GMT).

1. I think you should select a point without known significant deformation.
2. `gmt grdmath your_interferogram a_number SUB = your_interferogram_shifted`. Use gmt or others to make that point zero.

**Comment by Luvina0503** [comment]
@Alzaidy1 
Have you solved the problem? I had the same problem. And how is GNSS.ll obtained?
