### ISSUE TITLE
[Feature]: sbas script

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#522]
Hi. Dear professors,
Does anyone know where the sbas script in the picture can be downloaded？
Thank you
![image](https://user-images.githubusercontent.com/114629377/198866005-aefd5b45-6403-4da4-9753-07c68bf3c672.png)

**Comment by Luvina0503** [comment]
I found the sbas, but the operation is wrong.Why?
![image](https://user-images.githubusercontent.com/114629377/198967809-2dfaa22f-60bc-4bef-8698-6013d3649f61.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You should be looking for it at GMTSAR/bin.
