### ISSUE TITLE
[Help]: error in merge_batch.csh merge_list batch_tops.config

### ISSUE THREAD

**Issue by zeinabtooshe** [gmtsar/gmtsar#523]
Hi
I want to merge frames iw1 and iw2,
When I run "merge_batch.csh merge_list batch_tops.config"
command I get the following :

mkdir: cannot create directory ‘2018011_2018023’: File exists
cp: omitting directory '../../F1'
grep: ../../F1: Is a directory
Segmentation fault (core dumped)
grep: ../../F1: Is a directory
ln: failed to create symbolic link './dem.grd': File exists
ln: failed to create symbolic link './batch_tops.config': File exists

And it doesn't end

**Comment by zeinabtooshe** [comment]
I run the command from the Merge directory

![zeinab](https://user-images.githubusercontent.com/97591776/198963649-b78cb55e-5ab7-4154-922d-4d92ac3e6fb9.PNG)

**Comment by zeinabtooshe** [comment]
I run the command from the Merge directory

![image](https://user-images.githubusercontent.com/97591776/198965498-fe34dd8f-0bab-41a7-8678-b78f0ada1c8c.png)

**Comment by omarwater98** [comment]
Could you show a capture of your merge_list?

**Comment by omarwater98** [comment]
i cant see all your panorama better make me a video call robot156herrera@gmail.com

**Comment by omarwater98** [comment]
lo

> ![image](https://user-images.githubusercontent.com/97591776/199238093-b3e5fc0c-a507-4f21-97ff-f517fe5bfcaa.png)
> 
> This processing is a test with two images

looks like the 
,./F2/intf_all/2018011 must be F2 and this doesnt found the other folder what needed

**Comment by omarwater98** [comment]
remember make the command 
./create_merge_input.csh intfflist ../F*/intf_all/20* 1 > merge_list

**Comment by zeinabtooshe** [comment]
> remember make the command ./create_merge_input.csh intflist ../F*/intf_all/20* 1 > merge_list Try this

thanks for your help.
I did the Merge steps until the end, but in the end, the amount of displacement is very high and strange.
What do you think is the problem?

![image](https://user-images.githubusercontent.com/97591776/204074870-805ed54a-cc5b-43e5-baec-e3319aa1a0b7.png)

This is the result for 4 images.

**Comment by omarwater98** [comment]
> > remember make the command ./create_merge_input.csh intflist ../F*/intf_all/20* 1 > merge_list Try this
> 
> thanks for your help. I did the Merge steps until the end, but in the end, the amount of displacement is very high and strange. What do you think is the problem?
> 
> ![image](https://user-images.githubusercontent.com/97591776/204074870-805ed54a-cc5b-43e5-baec-e3319aa1a0b7.png)
> 
> This is the result for 4 images.

what is these?

**Comment by Xiaohua-Eric-Xu** [comment]
Did you generate a time-series with 4 images?

**Comment by zeinabtooshe** [comment]
This file is a vel_ll.grd file, which has been converted to txt and its NANs have been removed.

**Comment by zeinabtooshe** [comment]
> > > remember make the command ./create_merge_input.csh intflist ../F*/intf_all/20* 1 > merge_list Try this
> > 
> > 
> > thanks for your help. I did the Merge steps until the end, but in the end, the amount of displacement is very high and strange. What do you think is the problem?
> > ![image](https://user-images.githubusercontent.com/97591776/204074870-805ed54a-cc5b-43e5-baec-e3319aa1a0b7.png)
> > This is the result for 4 images.
> 
> what's the meaning of these numbers? Wich is the neame of the file?

This file is a vel_ll.grd file, which has been converted to txt and its NANs have been removed.

**Comment by zeinabtooshe** [comment]
> Did you generate a time-series with 4 images?

yes.

**Comment by Xiaohua-Eric-Xu** [comment]
> > Did you generate a time-series with 4 images?
> 
> yes.

Then I wouldn't be surprised by any numbers. It is too short to give you anything. p.s. you may not remove trend or select a reference location I assume.
