### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#524]
HI.Dear professors,
How to perform land subsidence analysis on sentinel data?

**Comment by omarwater98** [comment]
Hello Luna, you mean how to know the magnitude of sinking at the end of a processing?

![Cual de estos](https://user-images.githubusercontent.com/113547446/199081362-55793ff1-e6f6-414d-bd5d-1ca9878d5fd6.png)
Your question is which of these ones files give it the result?

**Comment by Xiaohua-Eric-Xu** [comment]
Do a time-series analysis. https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf

**Comment by Luvina0503** [comment]
OK.Thank you
