### ISSUE TITLE
[Feature]: gmt grdpaste

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#525]
Hi.Dear professors,
May I ask how to eliminate the gaps in the stitching results？
![WMXD%LS)RDE3K)J~EO6@OC1](https://user-images.githubusercontent.com/114629377/199154461-ee9a8863-fcd3-4fe9-b767-0c46e2f6c47c.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Please describe how you stitched your DEM. Sources, commands, etc.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
Command and dem_data:
![R@71RXJJ3%9AQYIAK30KDVY](https://user-images.githubusercontent.com/114629377/199374584-aae0b261-8398-473b-a8ca-d14b66e5a420.png)

Result:
![L_OHFY0LE5IHVVKF75HHCWN](https://user-images.githubusercontent.com/114629377/199374623-b60e776c-ddf3-4e18-9358-6afe6d3e3914.png)

**Comment by Xiaohua-Eric-Xu** [comment]
What if you ncview each dem files individually? Just want to make sure the original grids are filled with values.

**Comment by Luvina0503** [comment]
![}DGW3~L3DUNPVUODF%I8ETN](https://user-images.githubusercontent.com/114629377/199651598-7c87ef69-1d81-450d-a4fd-4f874471c07f.png)
![YDNJ~CUQB2@`$EHHB5)P9_S](https://user-images.githubusercontent.com/114629377/199651620-de6af1d8-da1c-4020-b2d5-83c72ef1b054.png)

**Comment by Xiaohua-Eric-Xu** [comment]
OK, this looks like a problem from dem generation. I am not particularly sure why. If you do integer boundaries (e.g. 116-119 and then 119-122), will the blank area get filled?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
Yes，you're right. The borders need to be integers so that there are no gaps when splicing.
This problem has been solved, thank you

**Comment by Xiaohua-Eric-Xu** [comment]
It's bit weird why that's the case for the on-line tool. It usually works fine on our local computer though.

**Comment by Luvina0503** [comment]
Thank you for your patience

**Comment by KIKINEO** [comment]
> Hi.Dear professors, May I ask how to eliminate the gaps in the stitching results？ ![WMXD%LS)RDE3K)J~EO6@OC1](https://user-images.githubusercontent.com/114629377/199154461-ee9a8863-fcd3-4fe9-b767-0c46e2f6c47c.png)

Hello friend, I saw the picture you uploaded, did you display the file in dem.grd format by drawing, or open it directly on your computer, if possible, can you tell me what method you use to open the grd format file, thank you very much~

**Comment by Xiaohua-Eric-Xu** [comment]
Try `ncview`.

**Comment by KIKINEO** [comment]
> Try `ncview`.

Dear Professor Xu, thank you very much for your reply~
