### ISSUE TITLE
[Feature]: organize_files_tops_linux.csh

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#527]
When I run this script, I get the following error.
![@50A2704RB_W~))%3OQ VZK](https://user-images.githubusercontent.com/114629377/199421049-c035fe2e-42f2-4123-9f96-b76820163282.png)
why?

**Comment by spacefan** [comment]
Maybe, you should install csh/zcsh with:

```shell
$ sudo apt install csh zcsh -y
```

**Comment by Luvina0503** [comment]
@spacefan 
![)QAWX@6(CA@N)MP`5KTP00J](https://user-images.githubusercontent.com/114629377/199442702-b9c20c53-1a30-4cb9-9cc3-211d48d3571a.png)

**Comment by spacefan** [comment]
Sorry, please replace `zcsh` with `tcsh`. In fact `csh` is enough for GMTSAR.

**Comment by Luvina0503** [comment]
@spacefan 
The problem still occurs when tcsh and csh are installed.
![image](https://user-images.githubusercontent.com/114629377/199624243-cf403696-4850-429b-a08e-59716666da1f.png)

**Comment by Luvina0503** [comment]
@spacefan @Xiaohua-Eric-Xu 
DATA：15 scene sentinel data
I've created.cSHRc, how do I configure it? Currently, the cshrc configuration is as follows:

set history=1000
set PATH="/usr/local/GMTSAR/bin:/usr/local/GMTSAR/gmtsar:/usr/local/bin:$path"

Command:
organize_files_tops_linux.csh SAFE_filelist .. /pins.ll 1
organize_files_tops_linux.csh SAFE_filelist .. /pins.ll 2

After entering the above two commands, you get a cropped folder. But there's only a crop of the last scene.Why?

**Comment by spacefan** [comment]
Maybe, you should read and follow this doc carefully：http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf

**Comment by Luvina0503** [comment]
The problem has been solved.thank you
