### ISSUE TITLE
[Help]: IW1-IW2 merge

### ISSUE THREAD

**Issue by mcollinssfd** [gmtsar/gmtsar#529]
I've done SBAS analysis before, but for the first time, my study area falls between IW1 and IW2. So I don't know what to do now. Could you please write it descriptively?

**Comment by Xiaohua-Eric-Xu** [comment]
You could use merge_batch.csh to combine swaths. Here's an example: http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf
