### ISSUE TITLE
How to change to highest resolution in proj_ra2ll.csh instead of 60m default?

### ISSUE THREAD

**Issue by CFEgildan71** [gmtsar/gmtsar#53]
Hello @Xiaohua-Eric-Xu 

I need to project vel.grd but the default spatial resolution is 60m, Is there any option to change to the highest resolution for Sentinel-1?

Thank you.
Daniel Hermosillo

**Comment by Xiaohua-Eric-Xu** [comment]
The script reads in the number in the name of the file "gauss_xxx". Change that to set a desired resolution. However, you need to set the range_dec and azimuth_dec in config file to get full resolution images.

**Comment by CFEgildan71** [comment]
I found the file 'gauss_100' in each interferogram's directory, you mean I need to change the name for each file for example to 'gauss_15' if I want to get a 15m resolution? I processed 280 interferograms. 

Before running the intf_tops.csh file, I set:

dec_factor = 1 
range_dec = 8 
azimuth_dec = 2


Thank you for your support, Eric.

**Comment by dsandwell** [comment]
Hi Daniel,

The azimuth spacing of the raw Sentinel-1 data is 15 m so the shortest wavelength possible is 30 m.  
The geocoding is done at 1/4 wavelength so a 60 m wavelength filter will have geocoding 15 m in range and 15 m in azimuth.


Try this:
filter_wavelength = 60
dec_factor = 1
range_dec = 2
azimuth_dec = 1

Note that all the files will be 8 times larger.  I would try a few to look at the differences.  You could cut back to 

range_dec = 4 with this filter and still retain everything.

David

> On Sep 14, 2020, at 10:31 AM, Daniel Hermosillo <notifications@github.com> wrote:
> 
> 
> I found the file 'gauss_100' in each interferogram's directory, you mean I need to change the name for each file for example to 'gauss_15' if I want to get a 15m resolution? I processed 280 interferograms.
> 
> Before running the intf_tops.csh file, I set:
> 
> dec_factor = 1
> range_dec = 8
> azimuth_dec = 2
> 
> Thank you for your support, Eric.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by CFEgildan71** [comment]
Hi @dsandwell 

Thank you very much David, I will process following your suggestions, I'm trying to identify slopes unstable over two Dams in Chiapas, México, where there was I big landslide in 2007.


Daniel Hermosillo

**Comment by CFEgildan71** [comment]
Hello David.

I couldn't process my time series, I ran: 
sbas intf.tab scene.tab 280 111 3500 4500 -smooth 3 -wavelength 0.0554658 -incidence 33 -range 845000.000333025 -rms -dem -atm 1, 

and I get killed, even processing with my 64Gb-RAM computer. I guess I have to reduce the resolution but I don't want to lose any possible unstable slope signal. Would you recommend me to set 0 defomax parameter into batch_tops.config file or set it to 65 to find possible unstable slope areas? and range_dec and azimuth_dec parameters works like multi-looking? if yes, How would you set it for processing in a 64Gb-RAM computer?

I know this forum is for report issues. but I can't register on GMTSAR forum.
I really appreciate your comments and support. Thank you.

**Comment by dsandwell** [comment]
Hi Daniel,

Yes the killed means you are out of memory.    Can you run a grdcut on all the interferograms to really focus on the dam area?  You don’t need to reprocess everything just cut them all in a script and try the SBAS again.

David

> On Sep 24, 2020, at 7:22 AM, Daniel Hermosillo <notifications@github.com> wrote:
> 
> 
> Hello David.
> 
> I couldn't process my time series, I ran:
> sbas intf.tab scene.tab 280 111 3500 4500 -smooth 3 -wavelength 0.0554658 -incidence 33 -range 845000.000333025 -rms -dem -atm 1,
> 
> and I get killed, even processing with my 64Gb-RAM computer. I guess I have to reduce the resolution but I don't want to lose any possible unstable slope signal. Would you recommend me to set 0 defomax parameter into batch_tops.config file or set it to 65 to find possible unstable slope areas? and range_dec and azimuth_dec parameters works like multi-looking? if yes, How would you set it for processing in a 64Gb-RAM computer?
> 
> I know this forum is for report issues. but I can't register on GMTSAR forum.
> I really appreciate your comments and support. Thank you.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by CFEgildan71** [comment]
Hello David.

I have processed with your parameters suggested and focused just on the dams and now I finished the SBAS step but it is still projecting with 60m pixel resolution (default parameter).
Could you tell me what I'm doing wrong?
![Screenshot from 2020-10-04 15-17-46](https://user-images.githubusercontent.com/38848954/95034027-d3471480-0685-11eb-807f-2d704e3b0a7f.png)

Thank you.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Daniel,
The proj_ra2ll.csh will look for the gauss_xxx file to make projection. Usually, it'll be a quarter of that number. Essentially you could rename that file with a different wavelength to get higher resolution. However, for projection, one has to be careful about the downsampling made when generating interferograms, so the output grid has solution(s) inside each pixel.
Cheers,
Xiaohua(Eric)

**Comment by CFEgildan71** [comment]
Hi Erick.
I will search that file and I'm gonna try your suggestion. 

Thank you.
