### ISSUE TITLE
merging 2bands from middle of input_merg does not work when run again

### ISSUE THREAD

**Issue by coralraha1234** [gmtsar/gmtsar#530]
I undersood that merging proccess  for 2 bands(1&2) working but the result is not correct I checked all interfrograms in band1 and band 2 and extract  and delete one not equal interfrogram in band 1 but yet my result in step3.. (merging)  is not correct (after deleting input_merge multiple first rows to start again )

**OS and software version**
slc iw  images s1a (asfdata)

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by coralraha1234** [comment]
Hi I should mention that phasefilt.png just in first merging shows one image (one band ) after deleting input merge and then it worked correctly again

**Comment by Xiaohua-Eric-Xu** [comment]
I am a bit confused by the description, but glad it's working for you!
