### ISSUE TITLE
[Help]:  to generate a swath profile 

### ISSUE THREAD

**Issue by Sgzanjani1367** [gmtsar/gmtsar#531]
Hi there 
I want to plot a swath profile like the image that I attached.
How can I do that?

I would appreciate it if anyone helps me.

![1](https://user-images.githubusercontent.com/94073038/199728249-dd59d262-24fa-4a0d-bdc8-ef21ebbbdd80.PNG)
![2](https://user-images.githubusercontent.com/94073038/199728291-7a3b31b9-6cd1-4832-b742-95c1328467ce.PNG)

**Comment by Xiaohua-Eric-Xu** [comment]
I guess you could get it with `gmt grdtrack`?
