### ISSUE TITLE
[Feature]: download GACOS_data

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#532]
HI.Dear professors,
After the Sentinel data is trimmed, how to download the data from the official website of GACOS according to the latitude and longitude? How to obtain the latitude and longitude data required by GACOS?

The trimmed sentinel-1A data:
![675E530%AKY` }}1_(9XKC6](https://user-images.githubusercontent.com/114629377/199919419-46875c57-83e4-423a-a513-a2a77d7c5ef9.png)

Cut out file：
![_E3AG _5J`M8_3ZY%1ZUCAO](https://user-images.githubusercontent.com/114629377/199919558-3b09bcfb-cc2a-4949-95e3-320c722aed4d.png)

download GACOS:
![}TGPJF@W1Q0MP_P@}T6TOWT](https://user-images.githubusercontent.com/114629377/199919666-06e525bf-ade2-4cce-af08-601efde29d6b.png)

**Comment by Xiaohua-Eric-Xu** [comment]
For the original data, you could figure out by checking the rough coordinates in the manifest.safe file. If you re-organized the data afterwards, you probably already know your AOI to be requested.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
Could you please tell me whether the coordinate range of GACOS data should be consistent with the trimmed SAFE coordinate range? Or should the coordinate range of the GACOS data include the trimmed SAFE range?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
![3F74BB546641C07849EA82DAFE4F663B](https://user-images.githubusercontent.com/114629377/200107057-a4e59249-9fda-4fae-8709-93cdd74d208d.jpg)
Is this relationship right？

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
downloaded gacos_data:
![$EI}$GBANKYQ0289B{FFPFA](https://user-images.githubusercontent.com/114629377/200110289-1a7f531c-77ae-432b-92b4-080efce04b4f.png)
corr.pdf in intf_all:
![D5}IO2DE 8NJD`@D5HI`$YO](https://user-images.githubusercontent.com/114629377/200110306-ed9aed6b-2dd2-4a3f-bd4c-78c8428cfd29.png)

Is this gacos data range OK? Can we do atmospheric correction？

**Comment by Xiaohua-Eric-Xu** [comment]
They are in different coordinates. Could you geocode with `proj_ra2ll.csh trans.dat corr.grd corr_ll.grd` and then make a comparison?

**Comment by Luvina0503** [comment]
![41GUJHEX1OC$4DYXRBT(L21](https://user-images.githubusercontent.com/114629377/200150383-fe7f62db-f28c-4c28-a6b7-23a2c4c49af4.png)

**Comment by Xiaohua-Eric-Xu** [comment]
If you run a `gmt grdinfo corr_ll.grd`, then you can check whether the bounds are within your GACOS coverage.

**Comment by Luvina0503** [comment]
OK.thank you
