### ISSUE TITLE
[Feature]: unwrap_GACOS_corrected.grd and unwrap_GACOS_corrected_detrended.grd

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#534]
HI.Dear professors,
I would like to ask about the following sbas processing, which data should I use: unwrap_GACOS_corrected.grd or unwrap_GACOS_corrected_detrended.grd?
![P%)VRH@`NZT~(%_ } O%OXE](https://user-images.githubusercontent.com/114629377/200150050-faa19955-5f88-4876-b5a8-69ce83f18a52.png)

**Comment by zth1015** [comment]
Hi，please how to write "list.txt"? why does the run end at "Outputs: unwrap phases corrected and added as additional products in each interferogram folder"? I am looking forward to your reply, thanks.
![2022-11-06](https://user-images.githubusercontent.com/116501665/200176872-30e3790a-7b2f-4c3d-b7ed-95bd504c2445.png)

**Comment by Xiaohua-Eric-Xu** [comment]
It would be better to hear from the author of the script. @esrivas17.

**Comment by esrivas17** [comment]
> HI.Dear professors, I would like to ask about the following sbas processing, which data should I use: unwrap_GACOS_corrected.grd or unwrap_GACOS_corrected_detrended.grd? ![P%)VRH@`NZT~(%_ } O%OXE](https://user-images.githubusercontent.com/114629377/200150050-faa19955-5f88-4876-b5a8-69ce83f18a52.png)

Hi, I would say that it depends on your study case. In my experience, the detrended data was the best for small deformation signals such as subsidence, etc. It's not recommended to remove a plane from your data when the signal is expected to be large as the case of Earthquakes. But certainly you must be careful to detrend your data since you might filter out part of the deformation signal.

**Comment by esrivas17** [comment]
> Hi， please how to write "list_interferograms"? why does the run end at "Outputs: unwrap phases corrected and added as additional products in each interferogram folder"? I am looking forward to your reply, thanks. ![2022-11-06](https://user-images.githubusercontent.com/116501665/200176872-30e3790a-7b2f-4c3d-b7ed-95bd504c2445.png)

List of interferograms can be created using linux commands such as: `ls -d 20* >> list.txt `(within the intf_all directory) if you want to create a list with full path the command would be `ls -d $PWD/20*` or `ls -d $PWD` depending on your current location.

The script is not running until you provide the correct inputs. Here, it is simply displaying information to the user.

**Comment by Luvina0503** [comment]
> > HI.Dear professors, I would like to ask about the following sbas processing, which data should I use: unwrap_GACOS_corrected.grd or unwrap_GACOS_corrected_detrended.grd? ![P%)VRH@`NZT~(%_ } O%OXE](https://user-images.githubusercontent.com/114629377/200150050-faa19955-5f88-4876-b5a8-69ce83f18a52.png)
> 
> Hi, I would say that it depends on your study case. In my experience, the detrended data was the best for small deformation signals such as subsidence, etc. It's not recommended to remove a plane from your data when the signal is expected to be large as the case of Earthquakes. But certainly you must be careful to detrend your data since you might filter out part of the deformation signal.
> 
> EDIT: To detrend grids I use the gmt command grdtrend: `gmt grdtrend phase_GACOS_corrected_phs.grd -N3r -Dphase_GACOS_corrected_phs_detrended.grd` https://docs.generic-mapping-tools.org/dev/grdtrend.html

@esrivas17 
I do subsidence and deformation analysis. Should I use unwrap_GACOS_detrended.grd?

**Comment by Luvina0503** [comment]
@esrivas17 
Sentinel data：15 scene
Number of interference pairs：69
I would like to ask you a question. GACOS correction is performed in the interference pair folder, and the number of correction graphs obtained is the number of interference pairs. Can we go further and get the correction image of each scene? It is convenient for subsequent comparison and analysis with the correction results obtained by sbas-atm.

**Comment by esrivas17** [comment]
> @esrivas17 Sentinel data：15 scene Number of interference pairs：69 I would like to ask you a question. GACOS correction is performed in the interference pair folder, and the number of correction graphs obtained is the number of interference pairs. Can we go further and get the correction image of each scene? It is convenient for subsequent comparison and analysis with the correction results obtained by sbas-atm.

Yes, if you comment `rm szpddm_phase_LOS.grd` at the end of the script, you will also get in each folder the szpddm_phase_LOS.grd which is the correction in the LOS direction after time and space differencing in phase dimensions. 

The -atm option in SBAS is based in a numerical method called Common Scene Stacking (CSS). It is very powerful and works very well specially if you create a very dense network of interferograms, since the method relies on redundancy of measurements. 
However, the CSS method also makes some assumptions in your data that might not be completely accurate. I feel the corrections in the first and last dates using -atm would not be comparable since you won't have enough connections in your dates.  GACOS relies in a model of the troposphere. I wouldn't expect to get very similar corrections when using -atm in comparison with GACOS.  I recommend to check this article, it is explained how SBAS mitigates the atmospheric phase. 
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015JB011886

But I do feel that applying -atm option after GACOS might improve the results.

**Comment by esrivas17** [comment]
> > > HI.Dear professors, I would like to ask about the following sbas processing, which data should I use: unwrap_GACOS_corrected.grd or unwrap_GACOS_corrected_detrended.grd? ![P%)VRH@`NZT~(%_ } O%OXE](https://user-images.githubusercontent.com/114629377/200150050-faa19955-5f88-4876-b5a8-69ce83f18a52.png)
> > 
> > 
> > Hi, I would say that it depends on your study case. In my experience, the detrended data was the best for small deformation signals such as subsidence, etc. It's not recommended to remove a plane from your data when the signal is expected to be large as the case of Earthquakes. But certainly you must be careful to detrend your data since you might filter out part of the deformation signal.
> > EDIT: To detrend grids I use the gmt command grdtrend: `gmt grdtrend phase_GACOS_corrected_phs.grd -N3r -Dphase_GACOS_corrected_phs_detrended.grd` https://docs.generic-mapping-tools.org/dev/grdtrend.html
> 
> @esrivas17 I do subsidence and deformation analysis. Should I use unwrap_GACOS_detrended.grd?

If it's a subsidence case I believe that the detrended data is the best before inverting the time series with SBAS.

**Comment by Luvina0503** [comment]
@esrivas17 
My interference pair folder has grd, but the number of unwrap_GACOS.grd is not consistent with the number of sbas-atm corrected graph. How to compare and analyze the correction results?

**Comment by Luvina0503** [comment]
@esrivas17
My interference pair folder has the szpddm_phase_LOS.gr, but the number of unwrap_GACOS.grd is not consistent with the number of sbas-atm corrected graph. How to compare and analyze the correction results?

**Comment by esrivas17** [comment]
> @esrivas17 My interference pair folder has the szpddm_phase_LOS.gr, but the number of unwrap_GACOS.grd is not consistent with the number of sbas-atm corrected graph. How to compare and analyze the correction results?

What do you mean the number is not consistent? You should have unwrap_GACOS grids as number of interferograms.

**Comment by Luvina0503** [comment]
@esrivas17 
Sentinel data：15 scene
There are 69 interference files, each containing a GACOS corrected result (unwrap_GACOS_corrected_detrended. However, only 15 CSS correction results (aps_*.grd) were obtained after SBAS-ATM processing under my sbas directory. I mean the numbers of these two are not consistent. How to make a comparative analysis of the results of atmospheric correction? How can analyzing CSS improve results?

**Comment by esrivas17** [comment]
> @esrivas17 Sentinel data：15 scene There are 69 interference files, each containing a GACOS corrected result (unwrap_GACOS_corrected_detrended. However, only 15 CSS correction results (aps_*.grd) were obtained after SBAS-ATM processing under my sbas directory. I mean the numbers of these two are not consistent. How to make a comparative analysis of the results of atmospheric correction? How can analyzing CSS improve results?

The number of GACOS corrections should match the number of interferograms, since the corrections occur over interferograms. The CSS algorithm works differently and models or approximates the atmospheric contribution for each day based on the amount of interferograms connected to a certain date. That's why it matches the number of images you got. I would recommend to check the article by Tymofyeyeva and Fialko, 2015

**Comment by Luvina0503** [comment]
OK. thank you

**Comment by zth1015** [comment]
> 

I am very lucky to get your answer. Thank you very much.

**Comment by zth1015** [comment]
@esrivas17 I am very lucky to get your answer. Thank you very much.

**Comment by zth1015** [comment]
@esrivas17 @Luvina0503 Hi,
How should I set "Reference point in lon lat coordinates" and "Indicence angle in degrees from SAT_look " and in which folder should I store them? Could you please give a detailed tutorial, I run GACOS_correction.csh is just in error.
Thank you very much.

**Comment by esrivas17** [comment]
> @esrivas17 @Luvina0503 Hi, How should I set "Reference point in lon lat coordinates" and "Indicence angle in degrees from SAT_look " and in which folder should I store them? Could you please give a detailed tutorial, I run GACOS_correction.csh is just in error. Thank you very much.

The reference point should be a text file. The incidence angle should be a number. I included some checks before performing the correction in the last commit, so I recommend to make a git pull.
I doesn't matter where you store those as long as you provide the correct path when you call the script

**Comment by zth1015** [comment]
> > @esrivas17 @Luvina0503 Hi, How should I set "Reference point in lon lat coordinates" and "Indicence angle in degrees from SAT_look " and in which folder should I store them? Could you please give a detailed tutorial, I run GACOS_correction.csh is just in error. Thank you very much.
> 
> The reference point should be a text file. The incidence angle should be a number. I included some checks before performing the correction in the last commit, so I recommend to make a git pull. I doesn't matter where you store those as long as you provide the correct path when you call the script

I used your newly modified csh, but kept having problems generating "unwrap_GACOS_corrected.grd", as shown in the figure.
![eb437663dfd64d251d547cb8f081f55](https://user-images.githubusercontent.com/116501665/204789894-1eee9987-e01c-4896-8505-a993674b71da.png)
![e7678d3af0f73035b80e93306614c79](https://user-images.githubusercontent.com/116501665/204789922-d059f6d7-7aea-461d-b1a6-5793a0bafe6e.png)

**Comment by esrivas17** [comment]
May you open the operation.csh file you are using and share line 87 where the detrending occurs?

**Comment by zth1015** [comment]
> May you open the operation.csh file you are using and share line 87 where the detrending occurs?

And ref.llh, out.ratll, ref point.ra is empty.
![f2ca644d330f9696c160fd4eaeea301](https://user-images.githubusercontent.com/116501665/204797471-36b73c96-3403-463a-aea8-7f9e6c8ea042.png)
![51f5627b9362ae18674afffa650d8e8](https://user-images.githubusercontent.com/116501665/204797491-c4d70fcb-8b41-4342-bd17-0169ee75aad7.png)

**Comment by esrivas17** [comment]
Please work with the last updated version of the script. This version is old and not totally correct. Make a git pull and try again to see what you get.

**Comment by esrivas17** [comment]
or in the command line you can simply make: `git clone https://github.com/esrivas17/gacos_correction_for_GMTSAR.git`
and work with that version.

**Comment by zth1015** [comment]
> https://github.com/esrivas17/gacos_correction_for_GMTSAR.git

Thank you very much. The problem was solved.
