### ISSUE TITLE
[Help]: Boundary with different SBAS results

### ISSUE THREAD

**Issue by swjiaotong-jyliu** [gmtsar/gmtsar#538]
Hi 
![a18cff5e210961911dede8b23067acd](https://user-images.githubusercontent.com/86451834/200169592-18e94716-b4ee-4696-bef9-a7b00b4639fd.jpg)
Can I add or subtract a systematic error to the vel?

**Comment by Xiaohua-Eric-Xu** [comment]
What is the systematic error you mentioned above?

**Comment by swjiaotong-jyliu** [comment]
@Xiaohua-Eric-Xu   Is there a way to avoid causing different settling rates in overlapping or edge areas, as shown in this figure

**Comment by swjiaotong-jyliu** [comment]
![7a7ce0ccd4d744a2](https://user-images.githubusercontent.com/86451834/220236893-fb718b71-d8cf-418c-bd30-aef3286454a0.jpg)

There is a very clear inconsistency at the edges.
The right two frames is obviously brighter.

**Comment by Xiaohua-Eric-Xu** [comment]
The look angle is different from on track to another I believe. So it is normal for deformation value to be different across track as they have different amount mapped into line of sight.

**Comment by swjiaotong-jyliu** [comment]
@Xiaohua-Eric-Xu  Thanks


In organize_files_tops.csh I run
```
set tt = `echo $line2 | awk '{print substr($1,length($1)-54,15)}'`
set t1 = `date -jf "%Y%m%dT%H%M%S" $tt +%s`
```
but 
```
date Invalid option  -- j
Try 'date --help' for more information.
```

I searched it in date --help,but i can`t find it? 
```
set n1 = `date -v-1d -jf "%Y%m%d" $date0 +%Y%m%d`
set n1 = `date -d $date0"-1 day" +"%Y%m%d"`（I only can use it）
```
