### ISSUE TITLE
[Help]: Vertical Velocity form ASC and DES data of Sentinel on GMTSAR

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#539]
Hie Eric,
I have successfully processed Asc and Des data of Sentinel over my AOI. I dont have GPS in my AOI so I want to combine the Asc and Des for vertical velocity for which I am using code on matlab.
I need to know that where can I get _Heading Angle_  on GMTSAR for my sentinel files, as in .PRM file nor in supermaster.PRM the heading angle or related file is not there.

Is it the angle which I mentioned during my sbas command?

Thanks

**Comment by cumtbzxj** [comment]
In your F1 F2 F3 folder, you can find *.xml files ,search "platformHeading"

![2022-11-07 16-48-36屏幕截图](https://user-images.githubusercontent.com/117634107/200266319-a85339cd-2edf-4d2b-9708-5ba2d6e723a9.png)

**Comment by Xiaohua-Eric-Xu** [comment]
For other satellites, I usually just run SAT_look and compute one.

**Comment by mobigroup** [comment]
Incidence angle is not a constant so we need to compute it using SAT_look tool. See the example below for Sentinel-1 scene:
![](https://user-images.githubusercontent.com/7342379/183816622-1dacce7e-6a2f-46b9-8e67-d701f55bdd30.png)
East-west and vertical components calculations using the incidence angle available in PyGMTSAR Python code:
https://github.com/mobigroup/gmtsar/blob/master/pygmtsar/pygmtsar/SBAS_incidence.py
