### ISSUE TITLE
[Help]: merge_swath [ERROR] when using p2p_S1_TOPS_Frame.csh

### ISSUE THREAD

**Issue by Moxiaoxxx** [gmtsar/gmtsar#542]
Hi，when I use p2p_S1_TOPS_Frame.csh,some errors happened.The first error is merge_swath [ERROR].The operation process is as follows.Hope you can help me,sir.

p2p_S1_TOPS_Frame.csh S1A_IW_SLC__1SDV_20220105T111059_20220105T111126_041325_04E9B1_F077.SAFE S1A_OPER_AUX_POEORB_OPOD_20220105T121555_V20211215T225942_20211217T005942.EOF S1A_IW_SLC__1SDV_20220117T111059_20220117T111126_041500_04EF67_CDCA.SAFE S1A_OPER_AUX_POEORB_OPOD_20220117T121552_V20211227T225942_20211229T005942.EOF config.s1a.txt vv 1
vv
1
Linking files for Subswath 1 ...
Linking files for Subswath 2 ...
Linking files for Subswath 3 ...
[1] 5131
[2] 5132
[3] 5133
[3]    Done                   p2p_processing.csh S1_TOPS  ...
[2]  - Done                   p2p_processing.csh S1_TOPS  ...
[1]  + Done                   p2p_processing.csh S1_TOPS  ...
grep: S1A_IW_SLC__1SDV_20220117T111059_20220117T111126_041500_04EF67_CDCA.SAFE: No such file or directory
grep: S1A_IW_SLC__1SDV_20220117T111059_20220117T111126_041500_04EF67_CDCA.SAFE: No such file or directory
grep: S1A_IW_SLC__1SDV_20220117T111059_20220117T111126_041500_04EF67_CDCA.SAFE: No such file or directory

Merging START
Number of Files to be merged is 3
merge_swath [ERROR]: Cannot find file ../F1/intf/2022004_2022016/phasefilt.grd
merge_swath [ERROR]: Cannot find file ../F1/intf/2022004_2022016/phasefilt.grd
merge_swath [ERROR]: File ../F1/intf/2022004_2022016/phasefilt.grd not found
[Session merge_swath (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open grids ../F1/intf/2022004_2022016/phasefilt.grd
Number of Files to be merged is 3
merge_swath [ERROR]: Cannot find file ../F1/intf/2022004_2022016/corr.grd
merge_swath [ERROR]: Cannot find file ../F1/intf/2022004_2022016/corr.grd
merge_swath [ERROR]: File ../F1/intf/2022004_2022016/corr.grd not found
[Session merge_swath (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open grids ../F1/intf/2022004_2022016/corr.grd
Number of Files to be merged is 3
merge_swath [ERROR]: Cannot find file ../F1/intf/2022004_2022016/mask.grd
merge_swath [ERROR]: Cannot find file ../F1/intf/2022004_2022016/mask.grd
merge_swath [ERROR]: File ../F1/intf/2022004_2022016/mask.grd not found
[Session merge_swath (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open grids ../F1/intf/2022004_2022016/mask.grd
Merging END

Recomputing the projection LUT...
grep: S1_20220105_111101_F1.PRM: No such file or directory

 error -  could not open file S1_20220105_111101_F1.PRM

couldn't open master.PRM

 Usage: SAT_llt2rat master.PRM prec [-bo[s|d]] < inputfile > outputfile

             master.PRM   -  parameter file for master image and points to LED orbit file
             precise      -  (0) standard back geocoding, (1) - polynomial refinenent (slower)
             inputfile    -  lon, lat, elevation [ASCII]
             outputfile   -  range, azimuth, elevation(ref to radius in PRM), lon, lat [ASCII default]
             -bos or -bod -  binary single or double precision output (only output results within
                             data coverage, PRM num_lines, num_rng_bins )

 example: SAT_llt2rat master.PRM 0 < topo.llt > topo.ratll

 error -  could not open file S1_20220105_111101_F1.PRM

grdinfo [ERROR]: Cannot find file phasefilt.grd
grdinfo [ERROR]: Must specify one or more input files

Usage: landmask.csh region_cut[0/10600/0/27648]

    make a landmask in radar coordinates
NOTE: The region_cut can be specified in batch.config file

SNAPHU.CSH - START
threshold_snaphu: 0.12
grdmath [ERROR]: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: mask2_patch.grd is not a number, operator or file name
grdmath [ERROR]: mask2_patch.grd is not a number, operator or file name
Setting search radius to be 300 ...
Reading in original grid...
nearest_grid [ERROR]: Cannot find file phase_tmp.grd
nearest_grid [ERROR]: Cannot find file phase_tmp.grd
nearest_grid [ERROR]: File phase_tmp.grd not found
[Session nearest_grid (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open grdfile phase_tmp.grd
mv: cannot stat 'tmp.grd': No such file or directory
grd2xyz [ERROR]: Cannot find file phase_tmp.grd
grd2xyz [ERROR]: Cannot find file phase_tmp.grd
grd2xyz [ERROR]: File phase_tmp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
grd2xyz [ERROR]: Cannot find file corr_tmp.grd
grd2xyz [ERROR]: Cannot find file corr_tmp.grd
grd2xyz [ERROR]: File corr_tmp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
unwrapping phase with snaphu - higher threshold for faster unwrapping
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files

snaphu v2.0.4
32 parameters input from file snaphu.conf.brief (297 lines total)
not enough input arguments.  type snaphu -h for help
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files
xyz2grd [ERROR]: Cannot find file unwrap.out
xyz2grd [ERROR]: Must specify -R option
xyz2grd [ERROR]: Option -I: Must specify positive increment(s)
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files
grdinfo [ERROR]: Cannot find file phase_patch.grd
grdinfo [ERROR]: Must specify one or more input files
xyz2grd [ERROR]: Cannot find file conncomp.out
xyz2grd [ERROR]: Must specify -R option
xyz2grd [ERROR]: Option -I: Must specify positive increment(s)
grdmath [ERROR]: tmp.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdgradient [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
makecpt [ERROR]: Option T: Must specify valid min[/max[/inc[<unit>|+n]]] option
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdimage [ERROR]: Cannot find file unwrap.grd
grdimage [ERROR]: Option -I: Must specify intensity file, value, or modifiers
psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:

  -R<west>/<east>/<south>/<north>[+r]
     Specify the min/max coordinates of your data region in user units. Use dd:mm[:ss] for regions given in arc
     degrees, minutes [and seconds]. Use -R<xmin>/<xmax>/<ymin>/<ymax>[+u<unit>] for regions given in projected
     coordinates, with <unit> selected from e|f|k|M|n|u. [e] Use [yyyy[-mm[-dd]]]T[hh[:mm[:ss[.xxx]]]] format for time
     axes. Append +r if -R specifies the coordinates of the lower left and upper right corners of a rectangular area.
     Alternatively, use -R<code><x0>/<y0>/<n_columns>/<n_rows> for origin and grid dimensions, where <code> is a 2-
     char combo from [T|M|B][L|C|R] (top/middle/bottom/left/center/right) and grid spacing must be specified via
     -I<dx>[/<dy>] (also see -r).
psscale [ERROR]: Offending option -Runwrap.grd
psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
Unwrapped phase map: unwrap.pdf
SNAPHU.CSH - END

GEOCODE-START
proj_ra2ll.csh
grd2xyz [ERROR]: Cannot find file phasefilt.grd
grd2xyz [ERROR]: Cannot find file phasefilt.grd
grd2xyz [ERROR]: File phasefilt.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
gmtinfo [ERROR]: No input data found!
surface [ERROR]: Must specify -R option
surface [INFORMATION]: Provides 5, expects 3-column binary data
surface [ERROR]: Must specify -R option
surface [INFORMATION]: Provides 5, expects 3-column binary data
grdtrack [ERROR]: Cannot find file raln.grd
grdtrack [ERROR]: Cannot find file ralt.grd
grdtrack [ERROR]: Must specify -G at least once
gmtconvert [WARNING]: File <stdin> is empty!
gmtconvert [WARNING]: No data records provided
Sampling in geocoordinates with 50 meter pixels ...
gmtinfo [ERROR]: No input data found!
range: Subscript out of range.
gmtmath [ERROR]: Operation "DIV" requires 2 operands
gmtmath [ERROR]: Operation "MUL" requires 2 operands
gmtinfo [ERROR]: No input data found!
blockmedian [ERROR]: Unable to decode  as a floating point number
blockmedian [ERROR]: Option -I parsing failure.  Correct syntax:

  -I<xinc>[+e|n][/<yinc>[+e|n]]
     Specify increment(s) and optionally append units or modifiers. For geographic regions in degrees you can
     optionally append units from this list: (d)egree [Default], (m)inute, (s)econd, m(e)ter, (f)oot, (k)ilometer,
     (M)ile, (n)autical mile, s(u)rvey foot.
       +e Adjust the region to fit increments [Adjust increment to fit domain].
       +n Increment specifies the number of nodes instead. Then, the actual increments are calculated from the given
          domain and node-registration settings (see Appendix B for details).
     Note: If -R<grdfile> was used then -I (and -R and maybe -r) have been set; use -I to override those increments.
blockmedian [ERROR]: Must specify -R option
blockmedian [ERROR]: Option -I: Must specify positive increment(s)
blockmedian [INFORMATION]: Provides 3, expects 3-column binary data
xyz2grd [ERROR]: Unable to decode  as a floating point number
xyz2grd [ERROR]: Option -I parsing failure.  Correct syntax:

  -I<xinc>[+e|n][/<yinc>[+e|n]]
     Specify increment(s) and optionally append units or modifiers. For geographic regions in degrees you can
     optionally append units from this list: (d)egree [Default], (m)inute, (s)econd, m(e)ter, (f)oot, (k)ilometer,
     (M)ile, (n)autical mile, s(u)rvey foot.
       +e Adjust the region to fit increments [Adjust increment to fit domain].
       +n Increment specifies the number of nodes instead. Then, the actual increments are calculated from the given
          domain and node-registration settings (see Appendix B for details).
     Note: If -R<grdfile> was used then -I (and -R and maybe -r) have been set; use -I to override those increments.
xyz2grd [ERROR]: Must specify -R option
xyz2grd [ERROR]: Option -I: Must specify positive increment(s)
grdmath [ERROR]: corr.grd is not a number, operator or file name
grdmath [ERROR]: phasefilt.grd is not a number, operator or file name
proj_ra2ll.csh
grd2xyz [ERROR]: Cannot find file phasefilt_mask.grd
grd2xyz [ERROR]: Cannot find file phasefilt_mask.grd
grd2xyz [ERROR]: File phasefilt_mask.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
gmtinfo [ERROR]: No input data found!
surface [ERROR]: Must specify -R option
surface [INFORMATION]: Provides 5, expects 3-column binary data
surface [ERROR]: Must specify -R option
surface [INFORMATION]: Provides 5, expects 3-column binary data
grdtrack [ERROR]: Cannot find file raln.grd
grdtrack [ERROR]: Cannot find file ralt.grd
grdtrack [ERROR]: Must specify -G at least once
gmtconvert [WARNING]: File <stdin> is empty!
gmtconvert [WARNING]: No data records provided
Sampling in geocoordinates with 50 meter pixels ...
gmtinfo [ERROR]: No input data found!
range: Subscript out of range.
gmtmath [ERROR]: Operation "DIV" requires 2 operands
gmtmath [ERROR]: Operation "MUL" requires 2 operands
gmtinfo [ERROR]: No input data found!
blockmedian [ERROR]: Unable to decode  as a floating point number
blockmedian [ERROR]: Option -I parsing failure.  Correct syntax:

  -I<xinc>[+e|n][/<yinc>[+e|n]]
     Specify increment(s) and optionally append units or modifiers. For geographic regions in degrees you can
     optionally append units from this list: (d)egree [Default], (m)inute, (s)econd, m(e)ter, (f)oot, (k)ilometer,
     (M)ile, (n)autical mile, s(u)rvey foot.
       +e Adjust the region to fit increments [Adjust increment to fit domain].
       +n Increment specifies the number of nodes instead. Then, the actual increments are calculated from the given
          domain and node-registration settings (see Appendix B for details).
     Note: If -R<grdfile> was used then -I (and -R and maybe -r) have been set; use -I to override those increments.
blockmedian [ERROR]: Must specify -R option
blockmedian [ERROR]: Option -I: Must specify positive increment(s)
blockmedian [INFORMATION]: Provides 3, expects 3-column binary data
xyz2grd [ERROR]: Unable to decode  as a floating point number
xyz2grd [ERROR]: Option -I parsing failure.  Correct syntax:

  -I<xinc>[+e|n][/<yinc>[+e|n]]
     Specify increment(s) and optionally append units or modifiers. For geographic regions in degrees you can
     optionally append units from this list: (d)egree [Default], (m)inute, (s)econd, m(e)ter, (f)oot, (k)ilometer,
     (M)ile, (n)autical mile, s(u)rvey foot.
       +e Adjust the region to fit increments [Adjust increment to fit domain].
       +n Increment specifies the number of nodes instead. Then, the actual increments are calculated from the given
          domain and node-registration settings (see Appendix B for details).
     Note: If -R<grdfile> was used then -I (and -R and maybe -r) have been set; use -I to override those increments.
xyz2grd [ERROR]: Must specify -R option
xyz2grd [ERROR]: Option -I: Must specify positive increment(s)
proj_ra2ll.csh
grd2xyz [ERROR]: Cannot find file corr.grd
grd2xyz [ERROR]: Cannot find file corr.grd
grd2xyz [ERROR]: File corr.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
gmtinfo [ERROR]: No input data found!
surface [ERROR]: Must specify -R option
surface [INFORMATION]: Provides 5, expects 3-column binary data
surface [ERROR]: Must specify -R option
surface [INFORMATION]: Provides 5, expects 3-column binary data
grdtrack [ERROR]: Cannot find file raln.grd
grdtrack [ERROR]: Cannot find file ralt.grd
grdtrack [ERROR]: Must specify -G at least once
gmtconvert [WARNING]: File <stdin> is empty!
gmtconvert [WARNING]: No data records provided
Sampling in geocoordinates with 50 meter pixels ...
gmtinfo [ERROR]: No input data found!
range: Subscript out of range.
gmtmath [ERROR]: Operation "DIV" requires 2 operands
gmtmath [ERROR]: Operation "MUL" requires 2 operands
gmtinfo [ERROR]: No input data found!
blockmedian [ERROR]: Unable to decode  as a floating point number
blockmedian [ERROR]: Option -I parsing failure.  Correct syntax:

  -I<xinc>[+e|n][/<yinc>[+e|n]]
     Specify increment(s) and optionally append units or modifiers. For geographic regions in degrees you can
     optionally append units from this list: (d)egree [Default], (m)inute, (s)econd, m(e)ter, (f)oot, (k)ilometer,
     (M)ile, (n)autical mile, s(u)rvey foot.
       +e Adjust the region to fit increments [Adjust increment to fit domain].
       +n Increment specifies the number of nodes instead. Then, the actual increments are calculated from the given
          domain and node-registration settings (see Appendix B for details).
     Note: If -R<grdfile> was used then -I (and -R and maybe -r) have been set; use -I to override those increments.
blockmedian [ERROR]: Must specify -R option
blockmedian [ERROR]: Option -I: Must specify positive increment(s)
blockmedian [INFORMATION]: Provides 3, expects 3-column binary data
xyz2grd [ERROR]: Unable to decode  as a floating point number
xyz2grd [ERROR]: Option -I parsing failure.  Correct syntax:

  -I<xinc>[+e|n][/<yinc>[+e|n]]
     Specify increment(s) and optionally append units or modifiers. For geographic regions in degrees you can
     optionally append units from this list: (d)egree [Default], (m)inute, (s)econd, m(e)ter, (f)oot, (k)ilometer,
     (M)ile, (n)autical mile, s(u)rvey foot.
       +e Adjust the region to fit increments [Adjust increment to fit domain].
       +n Increment specifies the number of nodes instead. Then, the actual increments are calculated from the given
          domain and node-registration settings (see Appendix B for details).
     Note: If -R<grdfile> was used then -I (and -R and maybe -r) have been set; use -I to override those increments.
xyz2grd [ERROR]: Must specify -R option
xyz2grd [ERROR]: Option -I: Must specify positive increment(s)
grdinfo [ERROR]: Cannot find file corr.grd
grdinfo [ERROR]: Must specify one or more input files
makecpt [ERROR]: Option T: Must specify valid min/max/inc[<unit>|+n] option
grdinfo [ERROR]: Cannot find file phasefilt_ll.grd
grdinfo [ERROR]: Must specify one or more input files
gmtmath [ERROR]: Operation "INV" requires 1 operands
grdimage [ERROR]: Cannot find file phasefilt_ll.grd
Make phasefilt_ll.kml and phasefilt_ll.png
psconvert [INFORMATION]: Processing phasefilt_ll.ps...
psconvert [INFORMATION]: Find HiResBoundingBox ...
psconvert [ERROR]: The file phasefilt_ll.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
grdinfo [ERROR]: Cannot find file phasefilt_mask_ll.grd
grdinfo [ERROR]: Must specify one or more input files
gmtmath [ERROR]: Operation "INV" requires 1 operands
grdimage [ERROR]: Cannot find file phasefilt_mask_ll.grd
Make phasefilt_mask_ll.kml and phasefilt_mask_ll.png
psconvert [INFORMATION]: Processing phasefilt_mask_ll.ps...
psconvert [INFORMATION]: Find HiResBoundingBox ...
psconvert [ERROR]: The file phasefilt_mask_ll.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
grdinfo [ERROR]: Cannot find file corr_ll.grd
grdinfo [ERROR]: Must specify one or more input files
gmtmath [ERROR]: Operation "INV" requires 1 operands
grdimage [ERROR]: Cannot find file corr_ll.grd
Make corr_ll.kml and corr_ll.png
psconvert [INFORMATION]: Processing corr_ll.ps...
psconvert [INFORMATION]: Find HiResBoundingBox ...
psconvert [ERROR]: The file corr_ll.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
GEOCODE END
rm: No match.SAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
> merge_swath [ERROR]: Cannot find file ../F1/intf/2022004_2022016/phasefilt.grd

This means something went wrong with the interferogram processing in F1 directory. Could you send the log file inside F1?

**Comment by Moxiaoxxx** [comment]
> 
I found that I used the mismatched EOF file. After I corrected it, the program ran normally.Thank you very much,sir.

**Comment by Moxiaoxxx** [comment]
> Open the dem.kml and one of your preview .kml image on google earth and show us a capture please

Thank you,I found that the error was caused by my use of mismatched EOF files.

**Comment by Moxiaoxxx** [comment]
> > merge_swath [ERROR]: Cannot find file ../F1/intf/2022004_2022016/phasefilt.grd
> 
> This means something went wrong with the interferogram processing in F1 directory. Could you send the log file inside F1?

Thank you,I found that the error was caused by my use of mismatched EOF files.

**Comment by Yaoshangheng** [comment]
> 
Hi，
I have the same situation with you.It's ture mismatched EOF files course this error.
Here is my problem：1、I download aux_poeorb file on：https://s1qc.asf.alaska.edu/aux_poeorb/   chose the file data time by .SAFE name. But it goes wrong.figure1.
2、While when I download aux_poeorb file on https://scihub.copernicus.eu/gnss/#/home chose the file data time by .SAFE name.Sensing period I choose the day before and after one day.The process is OK.

How to get right aux_poeorb file on：https://s1qc.asf.alaska.edu/aux_poeorb/. When useing p2p_S1_TOPS_Frame.csh？

figure1
![error](https://user-images.githubusercontent.com/20898434/203206956-9dd8fa57-5675-4fb7-acb7-67533aac14d7.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
I think you used the wrong EOF files, the orbit covers between its second and third dates in the file name.

**Comment by Xiaohua-Eric-Xu** [comment]
I think you used the wrong EOF files, the orbit covers between its second and third dates in the file name.

**Comment by Yaoshangheng** [comment]
> 

Yes，its true.need to use right EOF files.I was wondering is there a way do not use EOF files while doing p2p_S1_TOPS_Frame.csh due to Sentinel-1 orbits is relatively stable？

**Comment by Xiaohua-Eric-Xu** [comment]
There is a script to download orbit files in GMTSAR called `download_sentinel_orbits[_linux].csh`.

**Comment by Xiaohua-Eric-Xu** [comment]
And you have to use precise orbit. `stable != same`.

**Comment by Yaoshangheng** [comment]
> 
Yup，I got it.Then I need to wait for precise orbit released after earthquake occurs aften 21days later so I can use precise orbit to study it.

**Comment by Xiaohua-Eric-Xu** [comment]
You could use restituted orbits that'll be available hours after the acquisition. The quality is slightly less accurate but it is usable as an option for the downloading script I think.
