### ISSUE TITLE
[Feature]: sbas -atm

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#545]
Hi.Dear professors,
I'd like to ask you a question. How do I know the optimal number of iterations when executing the sbas-atm 3 command? How do you make a graph like this?
![K%G74J2)D6NXA)P 1 { $J5](https://user-images.githubusercontent.com/114629377/200973978-5f374035-47bd-47e6-9d72-1f2d342dbb33.png)

**Comment by Luvina0503** [comment]
This is a reference to the answer to this question. #406

**Comment by Xiaohua-Eric-Xu** [comment]
I think 3 is typically a good number with the current built-in setup of exponential relaxation on smoothness for this common-scene stacking approach.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
What information do you need? I mainly want to compare the correction results after sbas-atm with those of GACOS, as well as the correction effects of different iterations

**Comment by Luvina0503** [comment]
Because I'm not sure if I need to do common-scene stacking, I need to compare the results with GACOS correction

**Comment by Xiaohua-Eric-Xu** [comment]
> Because I'm not sure if I need to do common-scene stacking, I need to compare the results with GACOS correction

I guess you'll know after the comparison?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
By comparing the results of the two with the results of GNSS, can we draw a conclusion? So what I want to do is I want to draw the graph that I proposed

**Comment by Xiaohua-Eric-Xu** [comment]
It could be a regional conclusion for a period of time, since the correction (GACOS) relies on weather data too.
