### ISSUE TITLE
[Feature]: sbas -atm 3 result

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#546]
Run the sbas-atm 3 command to obtain the following result: However, the grd file cannot be opened through ncview. How to check the correction result?
![73H(4QVI0RM{%YZDIK9 1M1](https://user-images.githubusercontent.com/114629377/200997979-138777d4-a858-4b37-9b04-926d2c3cd27a.png)
![Q6$ KHPP09 `CB1W6~WVT P](https://user-images.githubusercontent.com/114629377/200998000-64119d98-a4db-4ffe-bdc6-2fc8b969d1c6.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You'll need to provide more details e.g. a log file of your sbas run, so that we could understand what happened.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
Only aps_2021005.grd cannot be viewed with ncview, because the elevation is 0~0. The remaining GRDS can be viewed. Why is that?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
[sbas.log.txt](https://github.com/gmtsar/gmtsar/files/9996316/sbas.log.txt)
 this is a log file of my sbas run

**Comment by Xiaohua-Eric-Xu** [comment]
The following line means the first (NO.0) and last (NO.14) does not have APS estimates.

```
 atm_noise(NO.0) = 0.000000
 atm_noise(NO.14) = 0.000000
```

The algorithm requires interferogram connection on both sides of the acquisition date.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
So how do I connect the interferogram  on both sides of the acquisition date?

**Comment by Luvina0503** [comment]
I'm not sure I know what you mean

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu So how do I connect the interferogram on both sides of the acquisition date?

You'll need to use other methods. The algorithm used in GMTSAR is documented in this paper.
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015JB011886

And all methods have their limitations.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
OK.thank you

**Comment by Xiongwei789** [comment]
> > @Xiaohua-Eric-Xu So how do I connect the interferogram on both sides of the acquisition date?
> 
> You'll need to use other methods. The algorithm used in GMTSAR is documented in this paper. https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015JB011886
> 
> And all methods have their limitations.

Hi Eric,
Does this mean that this method is not suitable for short-term post-seismic deformation, because there is no acquisition on the side of the co-seismic image?

**Comment by Xiaohua-Eric-Xu** [comment]
> > > @Xiaohua-Eric-Xu So how do I connect the interferogram on both sides of the acquisition date?
> > 
> > 
> > You'll need to use other methods. The algorithm used in GMTSAR is documented in this paper. https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015JB011886
> > And all methods have their limitations.
> 
> Hi Eric, Does this mean that this method is not suitable for short-term post-seismic deformation, because there is no acquisition on the side of the co-seismic image?

Not really. Check out this paper on dealing with jumps, transients, and other tectonic motions while dealing with atm noise using CSS, similar as what GNSS's doing. https://academic.oup.com/gji/article/230/2/1358/6554548

**Comment by Xiaohua-Eric-Xu** [comment]
In fact, you could model and remove the known non-linear motion and then apply CSS, iteratively, you could let both parts absorb their components from the time-series.
