### ISSUE TITLE
[Feature]: Track splicing

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#549]
Hi.Dear professors,i want to ask a question.I get the deformation results of different orbits. How to splice the deformation results of adjacent orbits?

**Comment by Xiaohua-Eric-Xu** [comment]
I don't think you could directly fuse the data from multiple tracks, as they have different look angles. However, there are ways to interpolate the data and incidence angle, which I am not sure that's what you need.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu After I finished the sbas analysis of each small area, I could not get the result of the whole large area. What to do about it？

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu After I finished the sbas analysis of each small area, I could not get the result of the whole large area. What to do about it？

If you could attach a few plots/figures to explain the problem you met, that'll help a lot. Otherwise, replies are purely based on my guesses.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
For example,I downloaded the sentry data of 142_111 and 142_106 and processed the sbas through GMTSAR respectively to get the type variable results of these two areas. But how do I stitch these two areas together seamlessly?
![M~DPBCZ}K_CQT K$S1(VTFV](https://user-images.githubusercontent.com/114629377/202936526-3f26bfde-5609-450b-a7d5-69490333837e.png)

**Comment by Xiaohua-Eric-Xu** [comment]
> I don't think you could directly fuse the data from multiple tracks, as they have different look angles. However, there are ways to interpolate the data and incidence angle, which I am not sure that's what you need.

I think you could publish a paper if you are able to find a good way to do a seamless stitch without losing information. Usually one could do seamless decomposition with some help from other data or assuming no north deformation.
