### ISSUE TITLE
Generate DEM error

### ISSUE THREAD

**Issue by maulanarachmat** [gmtsar/gmtsar#55]
I have an area which cross 0 Latitude,
When I try to generate DEM from https://topex.ucsd.edu/gmtsar/demgen/ as the instruction says, 
It gives me an error which says on the status "Error, Area cannot cross 0 Latitude"

How to solve this? Is there any workaround for this?
Thank You

**Comment by dsandwell** [comment]
Hi Rachmat,

Sorry about that challenge.

Use the site to select an area to the left of 0 and then to the right.  When you are done use 

gmt grdpaste demL.grd demR.grd -Gdem.grd

This is also the solution to the case where you need a very large dem.grd

David

> On Sep 19, 2020, at 10:56 PM, Rachmat Maulana <notifications@github.com> wrote:
> 
> 
> I have an area which cross 0 Latitude,
> When I try to generate DEM from https://topex.ucsd.edu/gmtsar/demgen/ as the instruction says,
> It gives me an error which says on the status "Error, Area cannot cross 0 Latitude"
> 
> How to solve this? Is there any workaround for this?
> Thank You
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037
