### ISSUE TITLE
[Feature]: sbas_parallel

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#550]
![5LDP1087H)K~48AD3~3CFYA](https://user-images.githubusercontent.com/114629377/201501084-9d820047-e379-4d0d-ae8f-adb85bcd5642.jpg)
Hi.Dear professors,
There is only sbas_parallel.c in my script. I cannot execute sbas_parallel command. What is the reason?

**Comment by Xiaohua-Eric-Xu** [comment]
You'll need to install it manually as not all c-compliers support `openmp`.

https://github.com/gmtsar/gmtsar/wiki/parallel-sbas-code

**Comment by Luvina0503** [comment]
OK.thank you
