### ISSUE TITLE
Cumulative deformation result：disp_12_ll.grd

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#552]
Hi.Dear professors,
This is the cumulative shape variable result obtained after sbas processing by unwrap_GACOS_detrended.grd. The first picture is the result of not executing -atm, and the second picture is the result of executing sbas-atm 3. Comparing the two images, I feel that the result without CSS correction is better. Why?
the result of not executing -atm:
![KW_NCX3M05A9F21HU5%KJ3K](https://user-images.githubusercontent.com/114629377/201554679-73f3ac0a-a6a9-454e-bd36-4b4d9ffbc693.png)
the result of sbas -atm 3:
![}W7F`F3%LI_{@_(RA)H@KVX](https://user-images.githubusercontent.com/114629377/201554696-5dace2b7-f40d-4664-9618-0206f0976cad.png)
@Xiaohua-Eric-Xu @esrivas17

**Comment by Xiaohua-Eric-Xu** [comment]
You are showing disp_12_ll.grd so I assume your time-series have 12 acquisitions? This is too short of a time-series to beat down atmospheric noise.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
That is to say, sbas-atm is more suitable for long time series sedimentation observation, right?

**Comment by Xiaohua-Eric-Xu** [comment]
Not just atm correction, velocity will be more robust with longer time-series. To solve for a robust velocity estimate, for Sentinel-1, our experience is that you may need about 6 year's data to beat down atmospheric noise to 1mm/yr in California.

**Comment by Luvina0503** [comment]
Ok.I see what you mean. thank you
