### ISSUE TITLE
[Feature]: Adjacent track splicing

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#556]
Hi.Dear professors,
I want to ask a question. After I finished the sbas processing of the provincial data, I got the deformation map disp_ * grd。 What method should I use to splice the deformation results of adjacent orbits together to get a complete deformation map of the province?

**Comment by Xiaohua-Eric-Xu** [comment]
Answering here: https://github.com/gmtsar/gmtsar/issues/549
