### ISSUE TITLE
SBAS Algorithm Types 

### ISSUE THREAD

**Issue by Obaida777** [gmtsar/gmtsar#558]
Dear All 

I Hope everyone doing well, 

1-Kindly, When I'm Running SBAS Command in the last stage in my Processing, which type of SBAS I'm getting (CSBAS, PSBAS, MC SBAS, TCP INSAR, PO SBAS, CPTA....)?

2-how i can choose , and there are any Processing Ways to choose how ever you want to go with?

3-at least how i can process my
 data with CSBAS way?

Best Regards 

@Xiaohua-Eric-Xu 
@chintals
 @kguns32 
@mobigroup

**Comment by Xiaohua-Eric-Xu** [comment]
1. Coherence weighted sbas. 
2. Currently there's not an option to choose which type of sbas to run in gmtsar, though the underlying algorithm should be simple to build in MATLAB/Python.
3. You may need to describe your definition of CSBAS.

**Comment by Obaida777** [comment]
@Xiaohua-Eric-Xu  Thank you very much

**Comment by Obaida777** [comment]
Dear Dr. @Xiaohua-Eric-Xu  
I want to give a Reference for (Coherence weighted sbas) but i don't find a research. Can you provide me more information please. 

Regards
