### ISSUE TITLE
[Help]: SBAS error using unwrap_intf.csh 

### ISSUE THREAD

**Issue by Yaoshangheng** [gmtsar/gmtsar#561]
**Describe the problem you met**
Hi，
I am doing SBAS，after .I running unwrap_intf.csh for my timeseries data. I have 14 interference folders ,I run one of commond like this:'unwrap_intf.csh 2018212_2018224'. one by one.While some of unwrap shows ERROR to me.
'
upwrap_intf.csh. shows:
#!/bin/csh -f
# intflist contains a list of all date1_date2
directories.
cd $1
ln -s ../landmask_ra.grd .
snaphu_interp.csh 0.01 40
cd ..

(anaconda3-4.4.0) [yaoyuan@localhost merge]$ unwrap_intf.csh 2018212_2018224
directories.: Command not found.
Setting search radius to be 300 ...
Reading in original grid...
Interpolating to nearest neighbour...
Working on line 6769 ...
  -852916343 number of searches used ...
WRITING GRID IMAGE: Width x Heihgt = 8547 x 6769...
unwrapping phase with snaphu - higher threshold for faster unwrapping 

snaphu v2.0.4
32 parameters input from file snaphu.conf.brief (297 lines total)
Reading wrapped phase from file phase.in
No weight file specified.  Assuming uniform weights
Reading correlation data from file corr.in
Calculating deformation-mode cost parameters
Building range cost arrays
Building azimuth cost arrays
Initializing flows with MST algorithm
Running approximate minimum spanning tree solver
Running nonlinear network flow optimizer
Maximum flow on network: 12
Number of nodes in network: 57839329
Flow increment: 1  (Total improvements: 0)
Found 1 valid set(s) of connected pixels
Source 0 row, col = -2, -2
Treesize: 13511425   Pivots: 6835319     Improvements: 22816      Killed
xyz2grd [ERROR]: Cannot find file unwrap.out
xyz2grd [ERROR]: Cannot find file conncomp.out
grdmath [ERROR]: tmp.grd is not a number, operator or file name
mv: cannot stat ‘tmp.grd’: No such file or directory
grdgradient [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
makecpt [ERROR]: Option T: min >= max
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdinfo [ERROR]: Cannot find file unwrap.grd
grdinfo [ERROR]: Must specify one or more input files
grdimage [ERROR]: Cannot find file unwrap.grd
grdimage [ERROR]: Option -I: Must specify intensity file, value, or modifiers
psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append +r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Runwrap.grd
psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
Unwrapped phase map: unwrap.pdf
'
So there is nothing in unwrap.pdf

**OS and software version**
If applicable, what operating system and software version you are using?
OS:Centos7
GMTSAR version:6.0

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Comment by Xiaohua-Eric-Xu** [comment]
two suspicious lines 

```
directories.: Command not found.
...
Killed
``` 
`Killed` could be from a number of causes but mostly it is due to lack of RAM here.

**Comment by Xiaohua-Eric-Xu** [comment]
If you are running on a workstation or supercomputer, it could be from the settings of the machine too.

**Comment by Yaoshangheng** [comment]
Thank you！I will try.I am running on a VMware virtual machine with 30GB RAM and 16 lines of CPU.

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, that's more than enough to run your current 8000x6000 grid. Then I am unsure. Could you try cutting the grid with appending a 1000/2000/1000/2000 option, i.e. `snaphu_interp.csh 0.01 40 1000/2000/1000/2000`. This'll cut the image and run snaphu. Just want to make sure whether it is from the software or system.

**Comment by Yaoshangheng** [comment]
“snaphu_interp.csh 0.01 40 1000/2000/1000/2000”，works! Previously，the way I did before，I runed 14 snaphu_interp.csh command at the same time，I think it matters.

**Comment by Xiaohua-Eric-Xu** [comment]
Ahh, yeah, I guess 14 snaphu requires ~ 100GB RAM.

**Comment by Luvina0503** [comment]
> `Killed` could be from a number of causes but mostly it is due to lack of RAM here.
@Yaoshangheng 
How do I set up and view RAM?

**Comment by Luvina0503** [comment]
![QQ截图20221206155939](https://user-images.githubusercontent.com/114629377/205854019-492c74f8-8af0-4ff8-81f9-9b8efcba1a4a.png)
![QQ截图20221206160110](https://user-images.githubusercontent.com/114629377/205854261-aff9e8f0-e3d9-4ec2-a3e6-9743e000b89d.png)

I use a desktop computer

**Comment by Xiaohua-Eric-Xu** [comment]
The newer sbas in GMTSAR could provide a RAM cost estimates. Or if your disk speed is fast enough, you could use -mmap to reduce RAM cost. Or you could run sbas_parallel to make things run faster.
