### ISSUE TITLE
[Bug]: merge_swath requires unlimited memory

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#562]
For 2 full scenes (6 subswaths) using resolution 15m the tool "merge_swath" requires 15 GB RAM. Actually, it's not scalable so we need 30 GB RAM for 4 scenes and 60 GB for 8 scenes and so on. At the same time, the interferograms processing requires about 2 times less RAM than just the merging tool.

**Comment by Xiaohua-Eric-Xu** [comment]
What is the size of your original grid? I think the program only reads in the data with GMT_Read_Data (for at most 3 subswaths) and creates one output file with GMT_Create_Data. Not sure how 6 subswaths are merged directly.

**Comment by mobigroup** [comment]
The grid size is not related to the processing memory but the chunk size only: "netCDF-4 chunk_size: 129,129". NetCDF file can be written chunk-by-chunk and we need to have enough memory to manage one chunk.
```
gmt grdinfo raw_desc/F123_20220214_20220226_phasefilt.grd
...
raw_desc/F123_20220214_20220226_phasefilt.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
raw_desc/F123_20220214_20220226_phasefilt.grd: x_min: 0 x_max: 68116 x_inc: 4 name: x n_columns: 17029
raw_desc/F123_20220214_20220226_phasefilt.grd: y_min: 0 y_max: 25613 y_inc: 1 name: y n_rows: 25613
...
raw_desc/F123_20220214_20220226_phasefilt.grd: format: netCDF-4 chunk_size: 129,129 shuffle: on deflation_level: 3
```

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure about the reading in GMT since I only used their API to implement the IO, but I guess your grid is about 16G size? Plus the writing is done line by line scanning the input grid and writing to the output grid. Not sure whether this changes how the program writes stuff though.

**Comment by mobigroup** [comment]
The file size is relatively small just about 1.5 GB. Even without compression: 17029 x 25613 x 4 bytes (32-bit float) = 1.7 GB. I'm not sure if GMTSAR is able to perform geocoding for the grid. As I remember, you monitor large California area using multiple stitched scenes for 40+ years - how is it possible? Maybe do you use low resolution to do it?

**Comment by Xiaohua-Eric-Xu** [comment]
Hmm, that's strange. I did use lower resolution (i.e. 8/2 initially), however, if a merging uses 16GB memory, it should've failed on my laptop. I once merged phase-gradient product (1/1) for an earthquake. 

I just tested it on my mac for total size of 8548x12369, the total RAM cost came up to ~815 MB which makes sense to me as it is about 8548x12369x4/1024/1024 x 2.

**Comment by mobigroup** [comment]
Mac uses RAM compressing and unlimited swap so it works. In Docker container RAM size and swap are strictly limited. It looks curious because we can do very complex processing to build multi-burst interferograms (2 stitched scenes have about 20 bursts) but we can't merge them in the same container.

**Comment by mobigroup** [comment]
I'm preparing Docker image (90 GB) for 2 stitched scenes and all 3 subswaths 34 interferograms SBAS analysis and it works in 16 GB RAM Docker container. I suppose it need to work well even on 8 GB RAM but merge_swath tool blocks it. The other problem is it uses only one or two cores for GMTSAR binaries so the processing requires about 2 days. At the same time, @SteffanDavies wrote about weeks of the processing for ~200 interferograms #478 (~1 week on 512 GB RAM 32 cores host + ~1 week on 256 GB RAM 16 cores host as I understand) so the processing time looks appropriate (but it could be much faster).

**Comment by Xiaohua-Eric-Xu** [comment]
> Mac uses RAM compressing and unlimited swap so it works. In Docker container RAM size and swap are strictly limited. It looks curious because we can do very complex processing to build multi-burst interferograms (2 stitched scenes have about 20 bursts) but we can't merge them in the same container.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/16844111/203047195-38fda2d1-7dee-400e-8a63-824f314b797e.png">

I think it did not use any compressed memory since the memory usage is not significant.

**Comment by mobigroup** [comment]
Could you check the related virtual memory size?

**Comment by mobigroup** [comment]
htop console program shows virtual memory on Linux and Mac hosts. We can’t have virtual memory size larger than RAM+swap even when we use just a part of it.

**Comment by Xiaohua-Eric-Xu** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/16844111/203198423-7c6be655-c3c8-4c77-a05c-ee42fd33a91f.png">

Here are the outputs.

**Comment by mobigroup** [comment]
Hmm, it doesn't make sense. I've checked on my Apple Silicon host and I see the same issue for virtual memory.

I think we can check it easy using some process with well-defined RAM consumption. For now, I'm using Docker container with 16 GB RAM:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/7342379/203228764-24e3f36b-6824-42bc-ba12-87f81bad09c6.png">

And stop "RES" memory reported as 2 GB (8 times less):

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/7342379/203228538-7207050f-dc51-4031-9e12-6f7b313f3087.png">

And system application "Activity Monitor.app" shows relevant results (16 GB RAM):

<img width="738" alt="image" src="https://user-images.githubusercontent.com/7342379/203228689-b245f737-3a07-4446-b750-e5e2f70b477e.png">

> I just tested it on my mac for total size of 8548x12369, the total RAM cost came up to ~815 MB

Using the factor 8 (see above) we have ~8*820 MB = 6.5 GB real RAM consumption for your case. For the two stitched scenes grid 17029x25613 (4.125 times larger) we need ~6.5 GB * 4.125 = 27 GB RAM. For my test in Docker container actually it requires 14-15 GB RAM. I suppose you use float64 values vs float32 for my test, right? If that assumption is correct, we have the almost exactly proportion as expected.

Also, we are able to process larger grids too when you have unlimited swap. Docker container swap is strictly limited. While that's possible to add some swap space I use default parameters for reproducibility reasons.

**Comment by mobigroup** [comment]
By the way, SNAP processing didn't work for me even on a single scene and one pair of images on 8 GB and 16 GB hosts with unlimited swap - actually, it requires 32 GB RAM plus some specific video acceleration and so on. GMTSAR works nice on my ~10 years old MacBook 8 GB RAM and only the available disk space 512 GB limits the processing :) At the same time, Docker (and other) containers provides limited enviroment but the higthest reproducibility on any platform at any time and in case we can perform the full-resolution and full-scene SBAS processing for long timeseries in 8 GB RAM container and even 2 stitched scenes processing in 16 GB RAM container the pre-defined containers look valuable I think. It'd be more easy to maintain the same container configuration (8 GB RAM) for 2+ stitched scenes processing with the full resolution while it's not a problem for most of users of course.

**Comment by Xiaohua-Eric-Xu** [comment]
> Using the factor 8 (see above) we have ~8*820 MB = 6.5 GB real RAM consumption for your case.

I am not sure I understand Docker very well. Why there is a factor 8? Is there anything we can do to reduce this cost (in the code)?

**Comment by mobigroup** [comment]
I mean your processes manager shows 8 times less memory consumption than Apple’s “Activity Monitor.app” (you’d open it to monitor your RAM). And we can limit resources by many ways and Docker containers is just one of them.
NetCDF allows to manage its chunks separately without memory mapping the full file but I’m not sure if GMT can do it correct. mmap is wrong way to work with NetCDF.

**Comment by mobigroup** [comment]
It doesn’t look reasonable. On my host (recent MacOS on Apple Silicon) Activity Monitor reports accurate RAM consumption because it’s equal to the same one inside containers where I know exactly the available RAM.

That’s possible to limit RAM without Docker of course, see some ways here: https://unix.stackexchange.com/questions/44985/limit-memory-usage-for-a-single-linux-process

**Comment by mobigroup** [comment]
Please disable your swap and try to process a grid larger than the physical RAM size. I suppose GMT uses mmap for NetCDF grids which requires enough address space available (limited by your RAM size).

**Comment by mobigroup** [comment]
That's easy to check using GMT command line tools. The command below creates 1.8 GB SRTM grid and it works well on my Mac:

```
$ gmt grdcut @earth_relief_01s -R-5/5/-5/5 -Gortho.grd -V
ls -lh ortho.grd
-rw-r--r--  1 mbg  staff   1.8G Nov 23 17:19 ortho.grd
```

For the test I use Docker Desktop software and [Docker GMTSAR](https://hub.docker.com/r/mobigroup/gmtsar) container with minimal resources 1 GB RAM plus 0.5 GB swap (sure, we can define more precision limits using command-line Docker interface but that's not required for the test) so the total available memory (1 GB + 0.5 GB = 1.5 GB) a little bit less than the test SRTM grid:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/7342379/203521567-a1e0ca94-27b4-4d49-b6dc-18f7301bb667.png">

Now we can try to download SRTM grids:

```
$ gmt grdcut @earth_relief_03s -R-5/5/-5/5 -Gortho.grd -V
$ ls -lh ortho.grd
-rw-r--r-- 1 ubuntu ubuntu 247M Nov 23 10:13 ortho.grd

$ gmt grdcut @earth_relief_01s -R-5/5/-5/5 -Gortho.grd -V
grdsample [INFORMATION]: Processing input grid
Killed
```

As you see, we can process 0.25 GB grid but not 1.8 GB one using GMT on 1.5 GB RAM host. Sure, GMT uses mmap technique invalidating all the NetCDF advantages of chunk-based data storage. By design we can manage terabyte-scale NetCDF files on 8 GB RAM host using NetCDF Python libraries. And GDAL tools do it well but GMT as usual does not. For GDAL tools see my repo https://github.com/mobigroup/geo-earthengine where dataset "[WorldPop Global Project Population Data: Estimated Residential Population per 100x100m Grid Square](https://developers.google.com/earth-engine/datasets/catalog/WorldPop_GP_100m_pop)" is huge and it's easy to process using GDAL on any host. GMT is suitable to process maybe 1/100 of it.

**Comment by Xiaohua-Eric-Xu** [comment]
> Please disable your swap and try to process a grid larger than the physical RAM size. I suppose GMT uses mmap for NetCDF grids which requires enough address space available (limited by your RAM size).

I don't think they do as I grepped over their entire source code and found no string that matches "mmap".

**Comment by mobigroup** [comment]
It exists in the configure script:
```
grep -r mmap .                              
./cmake/modules/ConfigureChecks.cmake:#check_function_exists (mmap HAVE_MMAP)
```
I can't find brk()/mmap()/mremap() in C files but it can be defined by some macroses or using other way. Or maybe GMT allocates dynamic memory block for the total amount of RAM and that is even worst. Anyway, GMT is strictly limited by physical RAM and it doesn't work for real world. Users don't ready to buy Mac Pro for 50k$ when the same task is easy to resolve even on MacBook Air using other software.

**Comment by Xiaohua-Eric-Xu** [comment]
The line is commented out so is not used I guess.

Forgive me as I am still a bit confused. Does this problem only occur on Docker or it happens to your laptop as well? I never tried to read in a grid that's larger than my physical RAM on my laptop. If that is your target I don't think I have the knowledge to help here. 

I thought the initial question for this thread is "merge_swath using 8 times more memory than it should be". Did that get solved or not?

**Comment by mobigroup** [comment]
The problem is we need 16 GB RAM to build 1.7 GB output grid using merge_swath. That's the same for Docker container or a physical host with limited swap when RAM+swap < 16 GB. And the same problem for any GMT-based script - we need to have unlimited RAM+swap for large grid processing. Also, as reported before, we have problem for parallel runs - maybe it's related to the huge GMT memory consumption when even 16 GB RAM plus unlimited swap on a real host are not enough. Actually, GMT-based tools work on sample data but don't work for real cases (stitched frames processing). On 4 GB host we can't even process a single scene (3 subswaths) using the full resolution 15m. Maybe for some scenes (with more than usual bursts) we even can't do it on 8 GB RAM host.

**Comment by Xiaohua-Eric-Xu** [comment]
@PaulWessel I think I need some help here to understand why a 1.7GB output grid could use 16GB RAM.

**Comment by PaulWessel** [comment]
I had a quick look at merge_swath.c.  I dont know what arguments you used in this case but I see you are reading in all the grids given (which are 2 or 3 it seems).  Then you create the output grid.  So you have 3 or 4 full grids in memory.  If these are in fact the same size as in N by M then you are using (3 or 4) times N*M*4 bytes of memory.

Looking at the workflow it seems you are only accessing the G1 and G2 (and G3) data in separate loops so you should be able to do something like this instead:

1. Just read the headers for all the grids.
2. Allocate the output grid
3. Loop over the 2-3 input grids and read one at the time, process it, then call GMT_Destroy_Data to free that memory.

I dont know what merge_swath does to suggest more memory savings but at least that would take you from a possible factor of 4 to just 2?

It seems given your typical large grids for this type of work that you may want to restructure the code to only keep the grids you must have in memory and then read/free other temporary items.

**Comment by Xiaohua-Eric-Xu** [comment]
Thanks @PaulWessel, that's the part I think I understand. 
However, it seems that when the total RAM need is, e.g. ~800MB (which is shown in both htop and my activity monitor as ~800MB), @mobigroup suggests that the actual memory usage is 8 times that. This is the part that confuses me.

**Comment by PaulWessel** [comment]
I have no explanation for that.  There is no other GMT calls that read and write and create here and there is no hidden 8x factor doing anything in GMT.  Perhaps it is reporting the sum of 8 jobs running in parallel?

**Comment by mobigroup** [comment]
@PaulWessel Thanks for the suggestion, if we can limit RAM consumption 1.5 times (output grid for 3 subswaths plus just 1 input instead of all the 3 subswaths in RAM) it'd be 12 GB vs 16 GB for now. As minimum, it allows to use the Docker container with 12 GB RAM on 16 GB host much more comfortably.

Maybe could you explain why GMT can't process the 1.7 GB grid on 1.5 GB RAM host?
```
$ gmt grdcut @earth_relief_01s -R-5/5/-5/5 -Gortho.grd -V
grdsample [INFORMATION]: Processing input grid
Killed
```

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu merge_swath requires 14-15 GB RAM to process the 2 stitched scenes and all 3 subswaths grid (1.7 GB). It means ~8 times more RAM than the grid size.

**Comment by PaulWessel** [comment]
> Maybe could you explain why GMT can't process the 1.7 GB grid on 1.5 GB RAM host?
```

$ gmt grdcut @earth_relief_01s -R-5/5/-5/5 -Gortho.grd -V
grdsample [INFORMATION]: Processing input grid
Killed
```

Hm, let's see.  You are requesting a 10 x 10 degree grid at 1 arc second.  There are 3600 arc seconds per degree so dimensions are 36000 by 36000 which at 4 bytes per node is 4.87 Gb.  I do not understand why you say this grid is 1.7 Gb?

**grdcut** will call **grdblend** which will create that 4.87 Gb grid.  It will then open each of the many tiles, one at the time, and read one row at the time, hence none of those tiles are actually read into memory, just one row at the time.  So the memory consumption should be almost entirely dictated by the final desired grid size.  And that is 4.87 Gb, no?

**Comment by mobigroup** [comment]
@PaulWessel You'd download it and check the NetCDF compressed grid size yourself. As I attached above:
```
$ gmt grdcut @earth_relief_01s -R-5/5/-5/5 -Gortho.grd -V
ls -lh ortho.grd
-rw-r--r--  1 mbg  staff   1.8G Nov 23 17:19 ortho.grd
```

**Comment by PaulWessel** [comment]
What does a compressed file size have to do with the RAM requirement to hold the grid in memory? Are you imagining that compressed grids stay compressed in the computer memory?

**Comment by PaulWessel** [comment]
Yes I understand you wish that GMT had a different development philosophy where we were more concerned about memory and disk limitations.  But we made explicit decisions decades ago to never worry about limitations on RAM and hard disk space since a few years later those have doubled.  This means applications like the ones you are doing may not work well unless you have excessive amounts of RAM and space available.  That is just how we designed it.  We did this to keep the development simple, not to make it overly complicated to optimise memory use etc.  There is nothing wrong with coding it to be memory conservative and clearly lots of tools like GDAL and various python libs have.  But I hope you understand I am not spending my weekends doing that sort of coding just because there are situations where GMT may not be the most practical tool for your task.  We wrote GMT to do what we needed to do for our research and that also covers lots of other people.  But not all, obviously. And yes, GMT treats any grid as a 2-D uncompressed matrix and all take the same RAM regardless of disk compression.  Nothing is kept compressed in memory.

**Comment by mobigroup** [comment]
@PaulWessel Thanks for the clarification. Ok, GMT requires enough memory to hold the output grid plus just one of the three input grids if we do it the best. My initial ticket is about the GMTSAR tool based on GMT where grids merging uses ~8 times more RAM that the output grid (17029 x 25613 x 4 bytes (32-bit float) = 1.7 GB uncompressed grid size and 14-15 GB RAM). If I understood you correct, GMT requires 1.7*4/3=2.3 GB RAM for this case. Even for all the input and the output grid it’s equal just to 1.7*2=3.4 GB but that’s far less 14-15 GB measured memory consumption. So we still have no the answer why so much memory required for the processing.

**Comment by PaulWessel** [comment]
Yes, I cannot answer that.  All I can say is that GMT is not allocating that amount. But, if the netCDF lib is doing something under the hood then perhaps there is stull being allocated there that we have no control over.

**Comment by mobigroup** [comment]
As I attached above GMT downloads and merges the grids well on 1.5 RAM + swap host (uncompressed output grid size is about 0.5 GB):

gmt grdcut @earth_relief_03s -R-5/5/-5/5 -Gortho.grd -V

At the same time, merge_swath requires much more memory for the same or similar merging.

**Comment by PaulWessel** [comment]
Since **merge_swath** actually reads in the entire 2-3 input grids then that is the difference.  **grdblend** (via **grdcut**) only reads one row at the time.  Both allocate the output grid.  grdblend is the only tool in GMT that actually uses the row-by-row reading we implemented.

**Comment by mobigroup** [comment]
For this case GMT doesn't work as you think. Let's try a bit different grid processing in the same container 1 GB RAM + 0.5 GB swap:
```
gmt grdcut @earth_relief_03s -R-5/5/-5/10 -Gortho.grd -V
Killed
```
The uncompressed output grid size should be 0.8 GB and we have more than enough memory for it. But actually we need 2 times more RAM (because for 0.55 GB output grid it works) for just a single (output) grid because the input grids should not be loaded in RAM completely using the the row-by-row reading.

**Comment by PaulWessel** [comment]
Running debug now to see memory load throughout the job.

**Comment by PaulWessel** [comment]
Max memory allocation hit 915 Mb (this includes the output grid and all other bits and pieces GMT caries along).  This is running in debug mode in Xcode on macOS and I see the live total memory used as function of time.  It had to download 55 tiles first and that at the end used a few tens of Mb to store info about those tiles and one row array each, but then it jumped to 915 Mb upon allocating the large output grid and then it was just processing and finally writing it out and freeing the memory.  If you see it consuming over 1 Gb then I have absolutely no idea of what is happening on your system.  Perhaps you might be able to run in debug and see what might cause it.

**Comment by mobigroup** [comment]
See the output log below:
```
gmt grdcut @earth_relief_03s -R-5/5/-5/10 -Gortho.grd -V
...
grdblend [WARNING]: File @N00E000.earth_relief_15s_p.nc coordinates are phase-shifted w.r.t. the output grid - must resample
grdblend [INFORMATION]: Resample @N00E000.earth_relief_15s_p.nc via grdsample @N00E000.earth_relief_15s_p.nc -rg -I0.000833333333333/0.000833333333333 -R3.20923843056e-16/5/3.20923843056e-16/9.99583333333 -G/tmp/grdblend_resampled_GkNPmi.nc -Ve -fg --GMT_HISTORY=readonly
grdsample [INFORMATION]: Processing input grid
grdsample [INFORMATION]: Input  grid (0/10/1.38777878078e-16/10) n_columns = 2400 n_rows = 2400 dx = 0.00416666666667 dy = 0.00416666666667 registration = 1
grdsample [INFORMATION]: Output grid (0/5/3.20923843056e-16/9.99583333333) n_columns = 6001 n_rows = 11996 dx = 0.000833333333333 dy = 0.000833333333333 registration = 0
grdsample [INFORMATION]: Reading grid from file /home/ubuntu/.gmt/server/earth/earth_relief/earth_relief_15s_p/N00E000.earth_relief_15s_p.nc
grdsample [INFORMATION]: gmt_grd_BC_set: Set boundary condition for left   edge: natural
grdsample [INFORMATION]: gmt_grd_BC_set: Set boundary condition for bottom edge: natural
grdsample [INFORMATION]: gmt_grd_BC_set: Set boundary condition for top    edge: natural
grdsample [INFORMATION]: Output grid extrema [-6067.33/952.741] exceeds extrema of input grid [-5671.5/949]; to clip output use -n...+c
grdsample [INFORMATION]: Writing grid to file /tmp/grdblend_resampled_GkNPmi.nc
grdblend [INFORMATION]: Blend file /tmp/grdblend_resampled_GkNPmi.nc in 0/10/1.38777878078e-16/10 with normal weight 1 [5-12000]
grdblend [INFORMATION]: Processing input grids
Killed
```

**Comment by PaulWessel** [comment]
I see "Killed" but dont see any message about memory use.  I cannot see what goes wrong based on this.

**Comment by PaulWessel** [comment]
Never tested on soapless host.  My laptop has 64 Gb RAM.  As we agree, the actual memory allocation is < 1.0 Gb.  If OOM says it is out of memory then it clearly does not have the 915 Mb free memory available when running.  Other things on the system also takes up memory, no?  I cannot debug this on Linux but I can guarantee you that GMT only allocates 915 Mb in this case.  That may be too much for your system but that is because 915 Mb is available.

**Comment by mobigroup** [comment]
Even using system monitor visually on MacOS I see 1.1 GB RAM consumption:
![Screenshot_2022-11-24_at_22_31_44](https://user-images.githubusercontent.com/7342379/203821206-43189b9b-037d-43c5-b0c1-012ac554680b.jpg)
Probably the peak memory consumption is more. You never tested your software for the real memory consumption but you sure you don't need to do it...

**Comment by PaulWessel** [comment]
Interesting.  When I used Activity Monitor it said real memory at peak was 1.6 Gb but private memory was like yours 871 Mb.  But GMT also keeps track of what it allocates if GMT_MEMORY_TRACK is defined, and I got

```
# Max total memory allocated was 825.550 Mb [865651584 bytes]
# Single largest allocation was 824.547 Mb [864600100 bytes]
```

So I cannot account for those extra 0.6-7 Gb.

**Comment by mobigroup** [comment]
I suppose that's related to shared system libraries. That's interesting to check if the additional memory constant or depends of the application memory (easy to do but the both my hosts are busy right now).
