### ISSUE TITLE
[Help]: How to convert Latitude/Longitude coordinate to radar coordinate

### ISSUE THREAD

**Issue by Yaoshangheng** [gmtsar/gmtsar#563]
Hi，
When I am using snaphu_interp.csh,how can I get bounding box with known Latitude/Longitude coordinate；that mean how to convert Latitude/Longitude coordinate to radar coordinate on my study region？

Best wish！

**Comment by Xiaohua-Eric-Xu** [comment]
You could 1) drop a pin (lon lat elevation) and 2) use `SAT_llt2rat` to compute the correpsonding range and azimuth.

**Comment by Yaoshangheng** [comment]
> 

Thanks!It's worked.
