### ISSUE TITLE
GMTSAR  step by step 

### ISSUE THREAD

**Issue by CUMT530849827** [gmtsar/gmtsar#565]
Hello, Professor

I wanted to read a bit about GMTSAR S1A data processing earthquakes which is distributed rather than batch. I've run some examples from the website and read some scripts about it. But I want to run it step by step and really understand how it works and the algorithms involved. 
Thank you very much

**Comment by Xiaohua-Eric-Xu** [comment]
You could 1) go to a subswath (e.g. F1), then use the config file to control which step to run p2p_processing.csh. 

Another option is to break things down manually and run step by step, though this's require some knowledge of the software before hand. e.g. https://github.com/gmtsar/2022-unavco-course-gmtsar/blob/main/Jupyter/gmtsar_rs2_demo.ipynb

**Comment by CUMT530849827** [comment]
I am very lucky to get your answer. Thank you very much, professor

**Comment by Congzhangg** [comment]
@Xiaohua-Eric-Xu I have read the examples you recommended, and I think they are very good. Among them, I have some questions to ask you:

1) What is the difference between proj_ra2ll.csh and geocode.csh? It looks like everything is going from radar to geographic coordinates, except that deocode.csh can set the correlation coefficient threshold.

2) GMTSAR is a radar coordinate system at the stage of data preparation. I think it can be converted to geodesic coordinate system in two places: first, to convert the interferogram in the interference stage; Second, all the work is processed in the radar coordinate system, and finally the result vel_.grd is converted; Do I understand you correctly? Why is the example geocoding after unwrapping?

3) There is a -atm parameter in sbas analysis, which can be seen from the material as the number of atmospheric correction iterations. If it is set, can atmospheric correction be carried out without GACOS and other auxiliary data?
Looking forward to your reply~

**Comment by Xiaohua-Eric-Xu** [comment]
1. geocode.csh calls proj_ra2ll.csh to do geocoding, while applying some masking.
2. projection will lose some resolution as it basically re-mosaics data, so geocoding is the last step. There are proposed `geocode_slc` (geocoded SLC) but I suspect it'll cause some loss of data/coherence too.
3. Depends on what's available to you, we don't use GACOS correction, e.g. https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2021JB022579
