### ISSUE TITLE
[Help]: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kjz1997** [gmtsar/gmtsar#566]
Hi professor：
When I use the sbas command, I suddenly report an error
```
gmtsar-user@gmtsarVB:/media/gmtsar-user/Seagate/series/F1/SBAS$ sbas intf.tab scenes.tab 6 5 2699 2740 -atm 2 -smooth 1.0 -rms -dem

compute RMS misfit
compute DEM error

setting smoothing to   1.000 
setting radar wavelength to   0.236 m 
setting radar incidence angle to  37.000 degree 
setting range to 866000.000 m 
Required Memory Usage is 0.854044 GB ...
Memory Allocation Successful...
read table file ...
number of SAR scenes is 5 
number of interferograms is 6 
read phase and correlation grids ...
1.000000 0.000102 0.000000 90.333054


Applying atmospheric correction by common point stacking...




Hit Matrix:
0 1 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 


Applying exponential relaxation on smoothing parameters

Setting smoothing parameter to 1000.000000...
fill the G matrix ...
Computing deformation time-series...
run least-squares problem over 2699 by 2740 pixel (0) ...
Removing deformation time-series from original unwrapped phase...
Segmentation fault (core dumped)
```

**Comment by kjz1997** [comment]
This is the information of the core file

 `[New LWP 739916]
Core was generated by `sbas intf.tab scenes.tab 6 5 2699 2740 -atm 2 -smooth 1.0 -rms -dem'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055f1ec03fce4 in ?? ()
(gdb) `

**Comment by Xiaohua-Eric-Xu** [comment]
```
Hit Matrix:
0 1 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
```

This seem to indicate that you have only one pair of interferogram as input. What's in your intf.tab and scene.tab?

**Comment by kjz1997** [comment]
> ```
> Hit Matrix:
> 0 1 0 0 0 0 
> 0 0 0 0 0 0 
> 0 0 0 0 0 0 
> 0 0 0 0 0 0 
> 0 0 0 0 0 0 
> ```
> 
> This seem to indicate that you have only one pair of interferogram as input. What's in your intf.tab and scene.tab?

Too bad. Because of my carelessness, I just checked my scene.tab and found that the data in it was wrong. Thanks！

**Comment by Xiaohua-Eric-Xu** [comment]
Glad that you found the problem, is it working now?

**Comment by kjz1997** [comment]
> Glad that you found the problem, is it working now?

yes，thanks！
