### ISSUE TITLE
Vertical displacement vector with LOS of ascending and descending orbit 

### ISSUE THREAD

**Issue by Fabiangeo95** [gmtsar/gmtsar#57]
Hi. I have investigated ways to calculate the vertical displacement vector using the LOS data of both orbits, but I have not seen any solution to the inversion of the matrices that are proposed in the articles.
Wen S., et al. 2016 talks about a simpler solution but the document is in Chinese. Do you have any suggestion?

**Comment by Xiaohua-Eric-Xu** [comment]
Essentially, you could not derive 3-D displacement from 2 look directions. From the look vector (SAT_look), one could largely get East-West (subtract / 2) and Up/South-Down/North (add / 2). The latter is coupled. If you know that the source is producing mostly vertical deformation, the latter could be converted to vertical with the vertical look cosine. The satellite is not very sensitive to North-South anyways.

**Comment by Fabiangeo95** [comment]
thank you very much for your help.
Do you happen to have experience making models with PCAIM using InSAR data or do you know someone I can consult about it?

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure as GNSS data have both space and time to do that. I tried a similar method following the spectral approach in Bob Parker's Geophysical Inverse Theory book. Things work fine except it's hard to put in positivity/negativity constraint. (https://academic.oup.com/gji/article-abstract/212/1/400/4209971 )
