### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by cxinlong** [gmtsar/gmtsar#570]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through
When I installed GMTSAR6.2, the following error occurred when I made and installed the make step of GATSAR

**OS and software version**
If applicable, what operating system and software version you are using?
OS:ubuntu16.04
GMTSAR version:6.2

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case
![2022-11-24 10-22-39屏幕截图](https://user-images.githubusercontent.com/118950056/203682387-32e0ba1d-8b9f-46bc-b96d-bb79719db839.png)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
You'll need to attach the full log as the real error may occur before here.

**Comment by cxinlong** [comment]
Hello, Professor. May I ask why the SBAS I got in this area are empty? The number of points that are extracted is very small? May I ask what the reason is? Looking forward to your   @Xiaohua-Eric-Xu 
![1677394783994](https://user-images.githubusercontent.com/118950056/221396934-e539b183-b71b-48ba-ad1b-a4ae8a283c72.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hmm, saw a message here but it's gone.

**Comment by cxinlong** [comment]
Because I already found the solution to the problem, I deleted it. Thanks!
