### ISSUE TITLE
[Help]: How to use SBAS in regions of poor coherence

### ISSUE THREAD

**Issue by Xiongwei789** [gmtsar/gmtsar#571]
Hi,
When I tried to use SBAS to obtain the time series of postseismic deformation. But I found low coherence in this region. And I wanted to follow the file "sentinel_time_series5" to create a corr_stack.grd using stack.csh. Here are some of my questions:
1. "gmt grdmath corr_stack.grd 0.075 GE 0 NAN = mask_def.grd", How should we set the threshold (here 0.075)?  If we want to mask low coherence (blue region), why we choose a high threshold and mask low coherence (blue region) on the island (for example left in Figure 2 ).
![Figure 2](https://user-images.githubusercontent.com/92964720/203687575-f2082249-ab47-4d4f-ab59-c48d94233e05.png)
![Figure 1](https://user-images.githubusercontent.com/92964720/203687580-fdafbe7b-8c68-40ef-98ca-51eb7998a4b5.png)
2.  I obtained the corr_stack.grd using stack.csh. However, very few points have high coherence. If I choose a high threshold to extract postseismic series time of these points in the red circle, is this reliable?
![Figure 3](https://user-images.githubusercontent.com/92964720/203687777-5c8c1e71-fa50-49aa-99cc-7315d7db2f4d.png)
Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
The threshold is usually determined by 1) how many pixels you'd like to keep and 2) do they look reliable? Essentially the masking step could be replaced with PS (or good pixel) selections.

**Comment by Xiongwei789** [comment]
In my example, specifically, which areas are reliable ?

**Comment by Xiaohua-Eric-Xu** [comment]
You could pick out any that's larger than 0.1, make a mask and see whether that supplies your needs.

**Comment by SteffanDavies** [comment]
For many of my cases 0.1 can actually be too low and doesn't mask pixels above water (especially rivers). This will depend on you case study but 0.2 would probably be better for removing pixels over water and vegetation.

**Comment by Xiongwei789** [comment]
> 0.2 will mask most regions in this cases. I want to ask that can  i mask <0.2 region and use SBAS to derive postseismic deformation of remaining areas.

![test2](https://user-images.githubusercontent.com/92964720/204078358-c0c51922-f75a-4e85-accc-4a399860edf2.png)

**Comment by Xiaohua-Eric-Xu** [comment]
@SteffanDavies your case works well with 0.2 as your targets are infrastructures. @Xiongwei789 is looking for signals from post-seismic deformation, where keeping a bit more pixels may help. I would run `grd2xyz -s` to output the positions of them and plot with `psxy` with larger marker size. As sometimes the "good" pixels are too scattered to be well seen in the image. If you plot them larger, they may be able to help provide a pattern for your post-seismic analysis.

**Comment by Xiongwei789** [comment]
> @SteffanDavies your case works well with 0.2 as your targets are infrastructures. @Xiongwei789 is looking for signals from post-seismic deformation, where keeping a bit more pixels may help. I would run `grd2xyz -s` to output the positions of them and plot with `psxy` with larger marker size. As sometimes the "good" pixels are too scattered to be well seen in the image. If you plot them larger, they may be able to help provide a pattern for your post-seismic analysis.

Thank you for your reply. And I want to ask another question. How to determine the spatial and  temporal baselines for postseismic deformation in half a year. Here  the spatial and temporal baselines are  50 and 100, respectively. And  I get about 31 interference pairs. While I find that many studies chose large spatial and temporal baselines to get more pairs. I don't know if I should choose them according to the quality of coherence.

**Comment by Xiaohua-Eric-Xu** [comment]
You could be a bit more brave with spatial baselines, below 200m makes not much difference though there are other parameters that'll affect the coherence.
