### ISSUE TITLE
[Help]: The dimensions of azimuth do not match [ERROR] when using intf_tops.csh one.in batch_tops.config

### ISSUE THREAD

**Issue by CHUhao-FENG** [gmtsar/gmtsar#572]
Dear doctor,
   when I use  intf_tops.csh one.in batch_tops.config ,some errors happened,and i can not get the normal results of intf .The operation process is as follows.Hope you can help me,sir.

START FORM A STACK OF INTERFEROGRAMS

INTF.CSH, FILTER.CSH - START

......master LED file S1_20211017_ALL_F2.LED 

.........aligned LED file S1_20211029_ALL_F2.LED 

......master LED file S1_20211017_ALL_F2.LED 

.........aligned LED file S1_20211017_ALL_F2.LED 

intf.csh

running phasediff...

reading topo topo_ra.grd

The dimensions of azimuth do not match

filter.csh

setting range_dec = 8, azimuth_dec = 2

gauss_200 2 4 (1 2)

making amplitudes...

filtering interferogram...

conv [ERROR]: Cannot find file real.grd

conv [ERROR]: Cannot find file real.grd

conv [ERROR]: File real.grd not found

[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)

 Can't open  real.grd=bf 

conv [ERROR]: Cannot find file real_tmp.grd

conv [ERROR]: Cannot find file real_tmp.grd

conv [ERROR]: File real_tmp.grd not found

[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)

 Can't open  real_tmp.grd=bf 

conv [ERROR]: Cannot find file imag.grd

conv [ERROR]: Cannot find file imag.grd

conv [ERROR]: File imag.grd not found

[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)

 Can't open  imag.grd=bf 

conv [ERROR]: Cannot find file imag_tmp.grd

conv [ERROR]: Cannot find file imag_tmp.grd

conv [ERROR]: File imag_tmp.grd not found

[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)

 Can't open  imag_tmp.grd=bf 

making amplitude...

grdmath [ERROR]: realfilt.grd is not a number, operator or file name

grdmath [ERROR]: amp.grd is not a number, operator or file name

grdinfo [ERROR]: Cannot find file display_amp.grd

grdinfo [ERROR]: Must specify one or more input files

grd2cpt [ERROR]: Cannot find file display_amp.grd

grd2cpt [ERROR]: Option -L: Cannot decode limits

grd2cpt [ERROR]: Option -L: min_limit must be less than max_limit.

grdimage [ERROR]: Cannot find file display_amp.grd

psscale [ERROR]: Could not parse display_amp.grd into Geographical, Cartesian, or Temporal coordinates!

psscale [ERROR]: Option -R parsing failure. Correct syntax:

	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]

	  Append +r if giving lower left and upper right coordinates

	-Rg or -Rd for global domain

	-R<grdfile> to take the domain from a grid file

psscale [ERROR]: Offending option -Rdisplay_amp.grd

psconvert [ERROR]: The file display_amp.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.

making correlation...

grdmath [ERROR]: grid files not of same size!

grdmath [ERROR]: tmp.grd is not a number, operator or file name

grdmath [ERROR]: amp.grd is not a number, operator or file name

conv [ERROR]: Cannot find file tmp2.grd

conv [ERROR]: Cannot find file tmp2.grd

conv [ERROR]: File tmp2.grd not found

[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)

 Can't open  tmp2.grd=bf 

grdimage [ERROR]: Cannot find file corr.grd

psscale [ERROR]: Could not parse corr.grd into Geographical, Cartesian, or Temporal coordinates!

psscale [ERROR]: Option -R parsing failure. Correct syntax:

	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]

	  Append +r if giving lower left and upper right coordinates

	-Rg or -Rd for global domain

	-R<grdfile> to take the domain from a grid file

psscale [ERROR]: Offending option -Rcorr.grd

psconvert [ERROR]: The file corr.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.

making phase...

grdmath [ERROR]: imagfilt.grd is not a number, operator or file name

grdimage [ERROR]: Cannot find file phase.grd

psscale [ERROR]: Could not parse phase.grd into Geographical, Cartesian, or Temporal coordinates!

psscale [ERROR]: Option -R parsing failure. Correct syntax:

	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]

	  Append +r if giving lower left and upper right coordinates

	-Rg or -Rd for global domain

	-R<grdfile> to take the domain from a grid file

psscale [ERROR]: Offending option -Rphase.grd

psconvert [ERROR]: The file phase.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.

filtering phase...

phasefilt [ERROR]: Cannot find file imagfilt.grd

phasefilt [ERROR]: Cannot find file imagfilt.grd

phasefilt [ERROR]: File imagfilt.grd not found

[Session phasefilt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)

 error reading file imagfilt.grd 

grdinfo [ERROR]: Cannot find file mask.grd

grdinfo [ERROR]: Must specify one or more input files

grdedit [ERROR]: Cannot find file filtphase.grd

grdmath [ERROR]: filtphase.grd is not a number, operator or file name

grdimage [ERROR]: Cannot find file phasefilt.grd

psscale [ERROR]: Could not parse phasefilt.grd into Geographical, Cartesian, or Temporal coordinates!

psscale [ERROR]: Option -R parsing failure. Correct syntax:

	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]

	  Append +r if giving lower left and upper right coordinates

	-Rg or -Rd for global domain

	-R<grdfile> to take the domain from a grid file

psscale [ERROR]: Offending option -Rphasefilt.grd

psconvert [ERROR]: The file phasefilt.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.

mv: 无法获取'mask.grd' 的文件状态(stat): 没有那个文件或目录

grdmath [ERROR]: tmp.grd is not a number, operator or file name

INTF.CSH, FILTER.CSH - END

SKIP UNWRAP PHASE

GEOCODE.CSH - START

SKIP GEOCODING

END STACK OF TOPS INTERFEROGRAMS

**Comment by Xiaohua-Eric-Xu** [comment]
> The dimensions of azimuth do not match

Did you set your master_image in the batch_tops.config file correctly? This seem to indicate you have produced topo_ra.grd in the coordinates of another image (not master image).

**Comment by CHUhao-FENG** [comment]
> > The dimensions of azimuth do not match
> 
> Did you set your master_image in the batch_tops.config file correctly? This seem to indicate you have produced topo_ra.grd in the coordinates of another image (not master image).

Thanks for your reply，but  my master_image in the batch_tops.config file seems to be correctly.The situation is as follows.Could it have been caused by something else？or maybe I made a mistake somewhere.Thank you once again.



![batch_tops config](https://user-images.githubusercontent.com/116044341/203733167-8c492a21-7f29-49f3-85d7-ddbb3cbbb90c.png)
![baseline](https://user-images.githubusercontent.com/116044341/203733177-3e279ae1-0f21-4766-8647-4c902b812bc2.png)
![one in](https://user-images.githubusercontent.com/116044341/203733199-3399e499-1d3b-49df-b67d-c993a8e08619.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Could you send your master.PRM in your F2/topo directory?

**Comment by Xiaohua-Eric-Xu** [comment]
The PRM file looks normal to me. What if you go to your F2/raw and do a `ls -l *SLC`?

**Comment by CHUhao-FENG** [comment]
ok，F2/raw/*SLC is as follow.

-rw-rw-r-- 1 gmtsar-user gmtsar-user          0 11月 21 18:39 S1_20210830_ALL_F2.SLC

-rw-rw-r-- 1 gmtsar-user gmtsar-user          0 11月 21 18:39 S1_20210911_ALL_F2.SLC

-rw-rw-r-- 1 gmtsar-user gmtsar-user          0 11月 21 18:39 S1_20210923_ALL_F2.SLC

-rw-rw-r-- 1 gmtsar-user gmtsar-user 1248070656 11月 21 18:39 S1_20211017_ALL_F2.SLC

-rw-rw-r-- 1 gmtsar-user gmtsar-user          0 11月 21 18:39 S1_20211029_ALL_F2.SLC

-rw-rw-r-- 1 gmtsar-user gmtsar-user          0 11月 21 18:39 S1_20211110_ALL_F2.SLC

-rw-rw-r-- 1 gmtsar-user gmtsar-user          0 11月 21 18:39 S1_20211122_ALL_F2.SLC

-rw-rw-r-- 1 gmtsar-user gmtsar-user          0 11月 21 18:39 S1_20211204_ALL_F2.SLC

**Comment by Xiaohua-Eric-Xu** [comment]
This is strange as all your SLCs have 0 size. So I suspect something went wrong with the alignment step. i.e. preproc_batch_tops.csh.

**Comment by CHUhao-FENG** [comment]
> This is strange as all your SLCs have 0 size. So I suspect something went wrong with the alignment step. i.e. preproc_batch_tops.csh.
As you said,the process went wrong with the alignment step,I rerun the script,preproc_batch_tops.csh(mod = 1),and I got the expected result.Thank you very much for your help！Best wishes！
![Snipaste_2022-11-25_15-37-20](https://user-images.githubusercontent.com/116044341/203926412-31e4661a-52b6-4f22-ba79-9657efc57211.png)
