### ISSUE TITLE
[Bug]: Recent changes broke the processing

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#574]
@dsandwell Your recent commits added some inconsistency. Could you explain what means the error below introduced by the latest commits? The processing dataset is your upstream S1A_Stack_CPGF_T173.tar.gz.
```
phasediff reading topo F1_topo_ra.grd
 xdim 21572, ydim 5484 
 The dimension SLC must be multiplication factor of the topo_ra F1_topo_ra.grd 
```

**Comment by Xiaohua-Eric-Xu** [comment]
1) could you provide a size check on topo_ra.grd and the SLC size from the two PRM files? so that I can get an initial guess.
2) are you able to locate which commit caused this failure?

**Comment by mobigroup** [comment]
Ah, let me explain the situation. I'm re-running some saved states and don't understand what changes are made and what incompatibility I have. I don't run a usual full processing but some tests only. I just need to understand your changes and make only required updates in my processing. I don't see any regressions in the commits but some inconsistency in my tests as result of the changes.

**Comment by Xiaohua-Eric-Xu** [comment]
Is the problem solved? I just tested a simple case here with the most recent master branch and it worked just fine.

**Comment by mobigroup** [comment]
Thanks, that's not related to the changes (but to a used 3rd-party Python library changes). But I still don't understand why align_batch.csh updated without similar changes in preproc_batch_tops[_esd].csh?

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure which commit you are referring to. They are two separate alignment code. TOPS(Sentinel-1) data are in different observation mode and are already focused.
