### ISSUE TITLE
cut image

### ISSUE THREAD

**Issue by kjz1997** [gmtsar/gmtsar#575]
Hello, Professor.

I wonder if there is a script that can cut the image separately?

**Comment by SteffanDavies** [comment]
You mean like gmt grdcut?

gmt grdcut file_precut.grd -Gfile_cut.grd -R$cut_x_min/$cut_x_max/$cut_y_min/$cut_y_max -V

**Comment by kjz1997** [comment]
> You mean like gmt grdcut?
> 
> gmt grdcut file_precut.grd -Gfile_cut.grd -R$cut_x_min/$cut_x_max/$cut_y_min/$cut_y_max -V

I want to know whether this command can use the shp file as the clipping range? Because my research area is on the border of the country, I want to use the shp file to crop along the border

**Comment by SteffanDavies** [comment]
Convert your grd to lat Lon and cut it by the extents of the Shapefile.

**Comment by Xiaohua-Eric-Xu** [comment]
Or use your border shape (text lon, lat) to create a mask with `gmt grdmask` and then apply the mask to your data, if I understand correctly.
