### ISSUE TITLE
grd2kml

### ISSUE THREAD

**Issue by kjz1997** [gmtsar/gmtsar#576]
Hello, Professor.
When I use this script to convert the grd file, it tells me that I cannot generate the cpt file
<img width="836" alt="cpt" src="https://user-images.githubusercontent.com/89446964/203957679-45c50d9f-7078-440b-8734-860c30c9137a.PNG">

**Comment by SteffanDavies** [comment]
Try running this first:

`gmt grd2cpt disp_20150310.grd -T= -Z -Cjet > disp_20150310.cpt`

**Comment by kjz1997** [comment]
> Try running this first:
> 
> `gmt grd2cpt disp_20150310_ll.grd -T= -Z -Cjet > disp_20150310_ll.cpt`

Another error
<img width="599" alt="捕获" src="https://user-images.githubusercontent.com/89446964/204071893-552b6268-5130-4765-b329-7e650af46bfe.PNG">

**Comment by Xiaohua-Eric-Xu** [comment]
Alternatively, you could run `gmt grdinfo disp_20150310_ll.grd` to find `z_min` and `z_max`. The run `gmt grd2cpt disp_20150310_ll.grd -T$z_min/$z_max/$inc -Z -Cjet > disp_20150310_ll.cpt`. You'll need to replace the $xxx with actual numbers or setup these variables.
