### ISSUE TITLE
How to stores the data in netcdf3 format

### ISSUE THREAD

**Issue by Yaoshangheng** [gmtsar/gmtsar#578]
Hi,
Recently，I am useing pyrocko kite softeware for InSAR displacement analysis and postprocessing which input file is unwrap_ll.grd.

Here is the problem kite do not support NetCDF4 format.Only NetCDF3.https://github.com/pyrocko/kite/issues/73

After,we use "snaphu_interp.csh"command got unwrap.grd file then I use "proj_ra2ll.csh trans.dat unwrap.grd unwrap_ll.grd", to get unwrap_ll.grd. However，This  unwrap_ll.grd file is NetCDF4 format.

Can we have anyway to make NetCDF3 format？maybe use gmt5？

Thanks

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:6
gmt 6.1.0

**Comment by Xiaohua-Eric-Xu** [comment]
This seems to be a general question related to GMT file formats. @PaulWessel

**Comment by PaulWessel** [comment]
I think if you set **IO_NC4_DEFLATION_LEVEL** = 0 in the gmt.conf then you get nonxeflated netcdf 3 formats.

**Comment by Yaoshangheng** [comment]
> I think if you set **IO_NC4_DEFLATION_LEVEL** = 0 in the gmt.conf then you get nonxeflated netcdf 3 formats.

Thanks，I'll try it.

**Comment by Yaoshangheng** [comment]
Hi，Professor，
It's quite interesting，I am useing GMTSAR6&GMT6.2.0 while doing D-InSAR under TOPS model with p2p_S1A_TOPS.csh.
everything is fine.
But, I noticed that .grd file format in F1/intf、F2/intf 、F3/intf folder （NetCDF3）was different from merge folder's .grd format（NetCDF4）.
I can do unwrap in F1/intf、F2/intf 、F3/intf folder，separately. and the unwrap.grd result still maintain NetCDF3 format.
However，after merged the unwrap.grd format truns out to be NetCDF4.I think something change while doing merge process.
Since，I haven't set IO_NC4_DEFLATION_LEVEL = 0 in the gmt.conf.
It's there somebody have the same situation with me？

Have a good day

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure as merge_swath.c only creates netcdf file using GMT API. I am not sure whether gmt.conf also controls api.
```
197     if ((GOUT = GMT_Create_Data(API, GMT_IS_GRID, GMT_IS_SURFACE, GMT_GRID_ALL, NULL, wesn, inc, GMT_GRID_PIXEL_REG, 0, NULL)) ==
198         NULL)

```
Maybe you could run a `gmt grdmath unwrap.grd 0 ADD = unwrap.grd` and see whether that gives you a netcdf3 output.

**Comment by PaulWessel** [comment]
IT is the call to _GMT_Create_Session_ that initialises GMT via gmt.conf so it should set things there.  Default is **IO_NC4_DEFLATION_LEVEL** = 3.

**Comment by Xiaohua-Eric-Xu** [comment]
I've met scenarios of multiple GMT-s installed and while GMTSAR is compiled with one version of GMT, users are actually running another GMT.
