### ISSUE TITLE
[Feature]:  memory allocation

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#579]
Hi.Dear professor,
The following problem occurs when I run the sbas command.
command：
root@gmtsar:/media/gmtsar/Elements/Work/171106/F1/sbas0# sbas intf.tab scene.tab 207 60 2650 6094 -wavelength 0.0554658 -incidence 39.86 -range 811995 -smooth 1.0 -rms -dem

compute RMS misfit
compute DEM error

setting smoothing to   1.000 
setting radar wavelength to   0.055 m 
setting radar incidence angle to  39.860 degree 
setting range to 811995.000 m 
 memory allocation! phi 
root@gmtsar:/media/gmtsar/Elements/Work/171106/F1/sbas0# 

why?

**Comment by Luvina0503** [comment]
I have tested the data and found that the ydim value in the figure cannot be too large. However, by using the gmt grdinfo corr.grd command, ydim is 6094. How should I solve this problem?

![image](https://user-images.githubusercontent.com/114629377/204119045-19c8fa9e-50df-4e0c-9d17-6cdb169fe7ba.png)


root@gmtsar:/media/gmtsar/Elements/Work/171106/F1/intf_all/2020186_2020198# gmt grdinfo unwrap.grd
unwrap.grd: Title: Produced by grdmath
unwrap.grd: Command: grdmath tmp.grd mask2_patch.grd MUL = tmp.grd
unwrap.grd: Remark: 
unwrap.grd: Pixel node registration used [Cartesian grid]
unwrap.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
unwrap.grd: x_min: 0 x_max: 21200 x_inc: 8 name: x n_columns: 2650
unwrap.grd: y_min: 0 y_max: 12188 y_inc: 2 name: y n_rows: 6094
unwrap.grd: z_min: -10.4989929199 z_max: 41.0503845215 name: z
unwrap.grd: scale_factor: 1 add_offset: 0
unwrap.grd: format: classic
root@gmtsar:/media/gmtsar/Elements/Work/171106/F1/intf_all/2020186_2020198#

**Comment by Xiaohua-Eric-Xu** [comment]
The newer sbas will output the needed memory. 

To solve the memory problem, you could either 1) downsample or cut your data before running sbas; 2) increase the RAM of your computer; or 3) turn on -mmap option to swap disk space for memory usage (will slow down the program depending on your disk speed). 

You could also combine 3) with sbas_parallel so things will run faster.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
how to increase the RAM of my computer?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
How do I check how much RAM I have? And how do you know how much RAM sbas need?

**Comment by Xiaohua-Eric-Xu** [comment]
`free -h`?

**Comment by Xiaohua-Eric-Xu** [comment]
If you update your GMTSAR to a newer version, SBAS will output how much memory you'll need.

**Comment by Luvina0503** [comment]
![image](https://user-images.githubusercontent.com/114629377/204430370-21d04ffe-970d-4679-a13a-c1c45463f4bd.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Try with -mmap option with sbas. It'll take longer to run though.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
this question is solved. Thank you for your patient answer!

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
But there's a new problem. What's the reason?
![image](https://user-images.githubusercontent.com/114629377/204431463-6f583616-f820-460f-80e0-0104383ae60b.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Looks like you are using a laptop. For such analysis, it's usually better to use a workstation or a desktop.

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu But there's a new problem. What's the reason? 

Maybe you cut your unwrap.grd using an option with snaph.csh but did not cut your corr.grd accordingly?

**Comment by Luvina0503** [comment]
![image](https://user-images.githubusercontent.com/114629377/204431874-e0693bb5-952d-4eae-86a9-7a93d473a839.png)

**Comment by Luvina0503** [comment]
> Try with -mmap option with sbas. It'll take longer to run though.

command: sbas -mmap ?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
But when I run sbas_parallel, I still have the following problem. How to solve it?
![image](https://user-images.githubusercontent.com/114629377/204689226-2c8d69de-8305-49d1-a50b-753287775094.png)

**Comment by Luvina0503** [comment]
![image](https://user-images.githubusercontent.com/114629377/204689548-fd1cfade-3143-4fec-b98e-bfcb8a66d99b.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You probably need a newer version of GMTSAR. The version you have probably does not get the -mmap implemented yet.
