### ISSUE TITLE
How impact range value in sbas processing

### ISSUE THREAD

**Issue by CFEgildan71** [gmtsar/gmtsar#58]
Hello.

How impacts in sbas processing the range value?

reading the sentinel_time_series.pdf I see how to calculate this parameter:

((speed of light) / (rng_samp_rate) / (**x_min+x_max**)) + 845000

But every time I extract, x_min, and x_max values, using **gmt grdinfo unwrap.grd**, the x_min value is 0, then every time that I do the calculation, I just extract **x_max**.

I'm doing that correctly?

I'm sorry for doing this kind of post here, I know here is for post issues, but I don't know if there is a forum to share experiences and results using GMTSAR. I think it's necessary to create an official forum.

Regards

**Comment by Xiaohua-Eric-Xu** [comment]
Hi,
We are about to post a new time-series document. I think it is OK. However, there are scenarios when folks are only interested in a smaller are and interferograms are cut to a range like 5000/15000.
There is an unofficial forum here, http://gmt.soest.hawaii.edu/projects/gmt5sar/boards/6 . We are seeking to create a better one but have not yet gone very far on that.
Cheers,
Xiaohua(Eric)

**Comment by CFEgildan71** [comment]
Hello Eric,

I can't register, it doesn't accept people anymore?

Thanks.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, Yes, but also note that there is a later number (near_range) in the formula.
x_min is zero because the cut was done on the SLC (probably). If you perform a cut on the .grd files, then it'll not be zero.
Xiaohua(Eric)
