### ISSUE TITLE
[Help]: automatic download

### ISSUE THREAD

**Issue by steveen9** [gmtsar/gmtsar#580]
How can using this script to download
In my study area 
@Xiaohua-Eric-Xu 

 ![image](https://user-images.githubusercontent.com/118799806/204224623-02bb1d7a-76ce-4351-bf3d-7729a714307e.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
The above command gets you a data.list. You could also chose on ASF your area of interest and export your cart as a csv file.

**Comment by steveen9** [comment]
> The above command gets you a data.list. You could also chose on ASF your area of interest and export your cart as a csv file. 

when I running this script it give me empty 
Data.list why?

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure, what exact command did you ran?

**Comment by SteffanDavies** [comment]
> The above command gets you a data.list. You could also chose on ASF your area of interest and export your cart as a csv file.

Better off using vertex API and downloading in parallel instead of sequential.

**Comment by steveen9** [comment]
> I am not sure, what exact command did you run?

I run this script 
![image](https://user-images.githubusercontent.com/118799806/204993956-2e8b0314-d3fe-4525-81f4-e8b54b2eada2.jpeg)
![image](https://user-images.githubusercontent.com/118799806/204993999-b52cf15c-795b-4a35-b34c-89bd3ec2b60d.jpeg)

**Comment by steveen9** [comment]
> Better off using vertex API and downloading in parallel instead of sequential.


Can you explain with more steps please

**Comment by SteffanDavies** [comment]
> > Better off using vertex API and downloading in parallel instead of sequential.
> 
> Can you explain with more steps please

Use the Python API to query and download.

https://docs.asf.alaska.edu/api/basics/

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure but try this in `bash`.
```
bash-3.2$ cmd="https://api.daac.asf.alaska.edu/services/search/param?platform=Sentinel-1A,Sentinel-1B&polygon=-155.64625964,19.3937790141,-155.52834329,19.1922612441,-154.994620338,19.4236985176,-155.135252149,19.645334611,-155.64625964,19.3937790141&processingLevel=SLC&relativeOrbit=124&output=csv"
bash-3.2$ echo $cmd | xargs curl > asf.csv
bash-3.2$ head asf.csv 
"Granule Name","Platform","Sensor","Beam Mode","Beam Mode Description","Orbit","Path Number","Frame Number","Acquisition Date","Processing Date","Processing Level","Start Time","End Time","Center Lat","Center Lon","Near Start Lat","Near Start Lon","Far Start Lat","Far Start Lon","Near End Lat","Near End Lon","Far End Lat","Far End Lon","Faraday Rotation","Ascending or Descending?","URL","Size (MB)","Off Nadir Angle","Stack Size","Doppler","GroupID","Pointing Angle"
"S1A_IW_SLC__1SDV_20221125T043056_20221125T043126_046046_0582DA_9D1F","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","46046","124","56","2022-11-25T04:31:26.000000","2022-11-25T04:30:56.000000","SLC","2022-11-25T04:30:56.000000","2022-11-25T04:31:26.000000","19.0389","-155.5318","17.921457","-156.516602","18.349255","-154.181778","19.723141","-156.892136","20.147007","-154.530655","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20221125T043056_20221125T043126_046046_0582DA_9D1F.zip","4333.999086380005","None","None","0","S1A_IWDV_0057_0063_046046_124",""
"S1A_IW_SLC__1SDV_20221113T043056_20221113T043126_045871_057CF3_11EA","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","45871","124","56","2022-11-13T04:31:26.000000","2022-11-13T04:30:56.000000","SLC","2022-11-13T04:30:56.000000","2022-11-13T04:31:26.000000","19.0383","-155.5301","17.921068","-156.514954","18.348917","-154.180099","19.722248","-156.890427","20.146168","-154.528931","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20221113T043056_20221113T043126_045871_057CF3_11EA.zip","4125.674902915955","None","None","0","S1A_IWDV_0057_0063_045871_124",""
"S1A_IW_SLC__1SDV_20221101T043056_20221101T043126_045696_057707_4EA7","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","45696","124","56","2022-11-01T04:31:26.000000","2022-11-01T04:30:56.000000","SLC","2022-11-01T04:30:56.000000","2022-11-01T04:31:26.000000","19.0387","-155.5301","17.921305","-156.514938","18.349138","-154.180206","19.722742","-156.890457","20.146645","-154.529083","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20221101T043056_20221101T043126_045696_057707_4EA7.zip","4279.861266136169","None","None","0","S1A_IWDV_0057_0063_045696_124",""
"S1A_IW_SLC__1SDV_20221020T043056_20221020T043126_045521_057135_9108","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","45521","124","56","2022-10-20T04:31:26.000000","2022-10-20T04:30:56.000000","SLC","2022-10-20T04:30:56.000000","2022-10-20T04:31:26.000000","19.0382","-155.5288","17.920452","-156.51355","18.34828","-154.178848","19.722641","-156.889206","20.146536","-154.527863","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20221020T043056_20221020T043126_045521_057135_9108.zip","3813.5137491226196","None","None","0","S1A_IWDV_0057_0063_045521_124",""
"S1A_IW_SLC__1SDV_20221008T043056_20221008T043126_045346_056BF0_A4A0","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","45346","124","56","2022-10-08T04:31:26.000000","2022-10-08T04:30:56.000000","SLC","2022-10-08T04:30:56.000000","2022-10-08T04:31:26.000000","19.0387","-155.5292","17.921295","-156.513962","18.349094","-154.179245","19.722866","-156.889481","20.146732","-154.528107","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20221008T043056_20221008T043126_045346_056BF0_A4A0.zip","4095.479179382324","None","None","0","S1A_IWDV_0057_0063_045346_124",""
"S1A_IW_SLC__1SDV_20220926T043056_20220926T043126_045171_056617_E499","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","45171","124","56","2022-09-26T04:31:26.000000","2022-09-26T04:30:56.000000","SLC","2022-09-26T04:30:56.000000","2022-09-26T04:31:26.000000","19.0385","-155.5285","17.921133","-156.513306","18.348923","-154.178574","19.722582","-156.888779","20.146441","-154.527405","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20220926T043056_20220926T043126_045171_056617_E499.zip","4155.756009101868","None","None","0","S1A_IWDV_0057_0063_045171_124",""
"S1A_IW_SLC__1SDV_20220914T043056_20220914T043126_044996_05602E_28CC","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","44996","124","56","2022-09-14T04:31:26.000000","2022-09-14T04:30:56.000000","SLC","2022-09-14T04:30:56.000000","2022-09-14T04:31:26.000000","19.0382","-155.5305","17.920816","-156.515228","18.348591","-154.180649","19.722277","-156.890701","20.146118","-154.529495","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20220914T043056_20220914T043126_044996_05602E_28CC.zip","4242.661123275757","None","None","0","S1A_IWDV_0057_0063_044996_124",""
"S1A_IW_SLC__1SDV_20220902T043056_20220902T043125_044821_055A4F_0B28","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","44821","124","56","2022-09-02T04:31:25.000000","2022-09-02T04:30:56.000000","SLC","2022-09-02T04:30:56.000000","2022-09-02T04:31:25.000000","19.0385","-155.5317","17.921129","-156.516449","18.348951","-154.181793","19.722582","-156.891953","20.146469","-154.530655","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20220902T043056_20220902T043125_044821_055A4F_0B28.zip","4223.5840854644775","None","None","0","S1A_IWDV_0057_0063_044821_124",""
"S1A_IW_SLC__1SDV_20220821T043055_20220821T043125_044646_055468_86C0","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","44646","124","56","2022-08-21T04:31:25.000000","2022-08-21T04:30:55.000000","SLC","2022-08-21T04:30:55.000000","2022-08-21T04:31:25.000000","19.0383","-155.5301","17.920784","-156.514832","18.348558","-154.180267","19.722618","-156.890381","20.14646","-154.529175","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20220821T043055_20220821T043125_044646_055468_86C0.zip","4275.422497749329","None","None","0","S1A_IWDV_0057_0063_044646_124",""
```

**Comment by steveen9** [comment]
> I am not sure but try this in `bash`.
> 
> ```
> 
> bash-3.2$ cmd="https://api.daac.asf.alaska.edu/services/search/param?platform=Sentinel-1A,Sentinel-1B&polygon=-155.64625964,19.3937790141,-155.52834329,19.1922612441,-154.994620338,19.4236985176,-155.135252149,19.645334611,-155.64625964,19.3937790141&processingLevel=SLC&relativeOrbit=124&output=csv"
> 
> bash-3.2$ echo $cmd | xargs curl > asf.csv
> 
> bash-3.2$ head asf.csv 
> 
> "Granule Name","Platform","Sensor","Beam Mode","Beam Mode Description","Orbit","Path Number","Frame Number","Acquisition Date","Processing Date","Processing Level","Start Time","End Time","Center Lat","Center Lon","Near Start Lat","Near Start Lon","Far Start Lat","Far Start Lon","Near End Lat","Near End Lon","Far End Lat","Far End Lon","Faraday Rotation","Ascending or Descending?","URL","Size (MB)","Off Nadir Angle","Stack Size","Doppler","GroupID","Pointing Angle"
> 
> "S1A_IW_SLC__1SDV_20221125T043056_20221125T043126_046046_0582DA_9D1F","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","46046","124","56","2022-11-25T04:31:26.000000","2022-11-25T04:30:56.000000","SLC","2022-11-25T04:30:56.000000","2022-11-25T04:31:26.000000","19.0389","-155.5318","17.921457","-156.516602","18.349255","-154.181778","19.723141","-156.892136","20.147007","-154.530655","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20221125T043056_20221125T043126_046046_0582DA_9D1F.zip","4333.999086380005","None","None","0","S1A_IWDV_0057_0063_046046_124",""
> 
> "S1A_IW_SLC__1SDV_20221113T043056_20221113T043126_045871_057CF3_11EA","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","45871","124","56","2022-11-13T04:31:26.000000","2022-11-13T04:30:56.000000","SLC","2022-11-13T04:30:56.000000","2022-11-13T04:31:26.000000","19.0383","-155.5301","17.921068","-156.514954","18.348917","-154.180099","19.722248","-156.890427","20.146168","-154.528931","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20221113T043056_20221113T043126_045871_057CF3_11EA.zip","4125.674902915955","None","None","0","S1A_IWDV_0057_0063_045871_124",""
> 
> "S1A_IW_SLC__1SDV_20221101T043056_20221101T043126_045696_057707_4EA7","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","45696","124","56","2022-11-01T04:31:26.000000","2022-11-01T04:30:56.000000","SLC","2022-11-01T04:30:56.000000","2022-11-01T04:31:26.000000","19.0387","-155.5301","17.921305","-156.514938","18.349138","-154.180206","19.722742","-156.890457","20.146645","-154.529083","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20221101T043056_20221101T043126_045696_057707_4EA7.zip","4279.861266136169","None","None","0","S1A_IWDV_0057_0063_045696_124",""
> 
> "S1A_IW_SLC__1SDV_20221020T043056_20221020T043126_045521_057135_9108","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","45521","124","56","2022-10-20T04:31:26.000000","2022-10-20T04:30:56.000000","SLC","2022-10-20T04:30:56.000000","2022-10-20T04:31:26.000000","19.0382","-155.5288","17.920452","-156.51355","18.34828","-154.178848","19.722641","-156.889206","20.146536","-154.527863","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20221020T043056_20221020T043126_045521_057135_9108.zip","3813.5137491226196","None","None","0","S1A_IWDV_0057_0063_045521_124",""
> 
> "S1A_IW_SLC__1SDV_20221008T043056_20221008T043126_045346_056BF0_A4A0","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","45346","124","56","2022-10-08T04:31:26.000000","2022-10-08T04:30:56.000000","SLC","2022-10-08T04:30:56.000000","2022-10-08T04:31:26.000000","19.0387","-155.5292","17.921295","-156.513962","18.349094","-154.179245","19.722866","-156.889481","20.146732","-154.528107","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20221008T043056_20221008T043126_045346_056BF0_A4A0.zip","4095.479179382324","None","None","0","S1A_IWDV_0057_0063_045346_124",""
> 
> "S1A_IW_SLC__1SDV_20220926T043056_20220926T043126_045171_056617_E499","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","45171","124","56","2022-09-26T04:31:26.000000","2022-09-26T04:30:56.000000","SLC","2022-09-26T04:30:56.000000","2022-09-26T04:31:26.000000","19.0385","-155.5285","17.921133","-156.513306","18.348923","-154.178574","19.722582","-156.888779","20.146441","-154.527405","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20220926T043056_20220926T043126_045171_056617_E499.zip","4155.756009101868","None","None","0","S1A_IWDV_0057_0063_045171_124",""
> 
> "S1A_IW_SLC__1SDV_20220914T043056_20220914T043126_044996_05602E_28CC","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","44996","124","56","2022-09-14T04:31:26.000000","2022-09-14T04:30:56.000000","SLC","2022-09-14T04:30:56.000000","2022-09-14T04:31:26.000000","19.0382","-155.5305","17.920816","-156.515228","18.348591","-154.180649","19.722277","-156.890701","20.146118","-154.529495","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20220914T043056_20220914T043126_044996_05602E_28CC.zip","4242.661123275757","None","None","0","S1A_IWDV_0057_0063_044996_124",""
> 
> "S1A_IW_SLC__1SDV_20220902T043056_20220902T043125_044821_055A4F_0B28","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","44821","124","56","2022-09-02T04:31:25.000000","2022-09-02T04:30:56.000000","SLC","2022-09-02T04:30:56.000000","2022-09-02T04:31:25.000000","19.0385","-155.5317","17.921129","-156.516449","18.348951","-154.181793","19.722582","-156.891953","20.146469","-154.530655","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20220902T043056_20220902T043125_044821_055A4F_0B28.zip","4223.5840854644775","None","None","0","S1A_IWDV_0057_0063_044821_124",""
> 
> "S1A_IW_SLC__1SDV_20220821T043055_20220821T043125_044646_055468_86C0","Sentinel-1A","C-SAR","IW","Interferometric Wide. 250 km swath, 5 m x 20 m spatial resolution and burst synchronization for interferometry. IW is considered to be the standard mode over land masses.","44646","124","56","2022-08-21T04:31:25.000000","2022-08-21T04:30:55.000000","SLC","2022-08-21T04:30:55.000000","2022-08-21T04:31:25.000000","19.0383","-155.5301","17.920784","-156.514832","18.348558","-154.180267","19.722618","-156.890381","20.14646","-154.529175","None","ASCENDING","https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20220821T043055_20220821T043125_044646_055468_86C0.zip","4275.422497749329","None","None","0","S1A_IWDV_0057_0063_044646_124",""
> 
> ```


Thank you all for helping me

This script is correct but when I adding the polygon for my study area It shows me an error
So how can I adding polygon
And relativeOrbit=

**Comment by steveen9** [comment]
@Xiaohua-Eric-Xu ??

**Comment by Xiaohua-Eric-Xu** [comment]
This is basically the polygon "-155.64625964,19.3937790141,-155.52834329,19.1922612441,-154.994620338,19.4236985176,-155.135252149,19.645334611,-155.64625964,19.3937790141"
Note the first and last records should be the same to close the polygon.
