### ISSUE TITLE
prep_data_linux.csh  error “/root/.cshrc: No such file or directory.”

### ISSUE THREAD

**Issue by CUMT530849827** [gmtsar/gmtsar#582]
Hello professor,
           when I am working with SBAS, I want to automatically generate data.in file, but my prep_data_linux.csh report does not exist under .cshrc, and my other commands can be run. My runtime environment is ubuntu 18.04.
![image](https://user-images.githubusercontent.com/49933485/204295492-f9f012cb-cc4b-46e5-bc68-89a047cebf6f.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Comment out that line or add a ~/.cshrc file.
```
12 source ~/.cshrc
```

**Comment by CUMT530849827** [comment]
Thanks professor ，It works
