### ISSUE TITLE
[Help]: For instructions

### ISSUE THREAD

**Issue by cxinlong** [gmtsar/gmtsar#583]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through
Hello, do you have more detailed instructions on sentinel data processing？I have some questions in processing.

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
Here is one: http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf

**Comment by cxinlong** [comment]
> Here is one: http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf

OK，thank  you for your help.

**Comment by cxinlong** [comment]
> Here is one: http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf
Hello Eric.I have obtained the results after sbas processing, vel_ll.grd, kml files and png files. How to pull out the color bar to further intuitively analyze its displacement .

**Comment by Xiaohua-Eric-Xu** [comment]
I would use GMT to plot the results. The kml files are for a quick view or inspection over the landsaat images in Google Earth or other earth engines.

**Comment by cxinlong** [comment]
> I would use GMT to plot the results. The kml files are for a quick view or inspection over the landsaat images in Google Earth or other earth engines.

Ok, thank you for your patience. I also have a question about whether GMT can map county lines. According to the instructions, it seems not.

**Comment by Xiaohua-Eric-Xu** [comment]
What do you mean by county lines? like a map of California?

**Comment by Xiaohua-Eric-Xu** [comment]
I don't think GMT has those data built in. But if you have the shape as a table (e.g. lon lat), you could plot with `gmt psxy`.

**Comment by cxinlong** [comment]
> I don't think GMT has those data built in. But if you have the shape as a table (e.g. lon lat), you could plot with `gmt psxy`.

Ok, thank you very much for your valuable advice, wish you a happy life!
