### ISSUE TITLE
[Feature]: sbas_parallel.c

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#584]
Hi.dear professors,
command:
gcc -fopenmp -w sbas_parallel.c -I/usr/local/include/gmt -I/usr/local/GMTSAR/gmtsar -I/usr/local/include -L/usr/local/GMTSAR/gmtsar -lgmtsar -llapack -L/usr/local/lib -lgmt -L/usr/local/lib -ltiff -lm -o sbas_parallel
gcc --version:10.2.0
ubuntu:18.04   

The following problems occur：
![}DN_~UQ8H)46 M)31 _9}8](https://user-images.githubusercontent.com/114629377/204492232-61ec342b-d408-48b2-b81c-43ec8a924a64.png)
 
How did you solve the problem?

**Comment by Luvina0503** [comment]
gmt --version:5.4.3

**Comment by Xiaohua-Eric-Xu** [comment]
Update your GMT and GMTSAR should solve the problem. Also, for different system, the installation may not be at the exact path. Please follow the instructions on installing sbas_parallel instead of copying the command.
