### ISSUE TITLE
[Help]: Matlab

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#585]
Is there any script to show the results using matlab and add scale to it

![image](https://user-images.githubusercontent.com/108739411/204600139-461babc7-a6fd-44c2-8af0-fecda6f441be.jpeg)

Like this

![image](https://user-images.githubusercontent.com/108739411/204600558-272c2922-9022-443f-94b6-691750f3bdb9.jpeg)

**Comment by Xiaohua-Eric-Xu** [comment]
Try `ncread` and `imagesc`.
