### ISSUE TITLE
[Help]: D-InSAR、p2p_S1_TOPS_Frame.csh

### ISSUE THREAD

**Issue by zth1015** [gmtsar/gmtsar#586]
Dear professor, 
when I was doing D-InSAR, many errors occurred after I inputed the command "p2p_S1_TOPS_Frame.csh S1A_IW_SLC__1SDV_20171210T235237_20171210T235304_019647_021620_0A02.SAFE S1A_OPER_AUX_POEORB_OPOD_20210305T114028_V20171209T225942_20171211T005942.EOF S1A_IW_SLC__1SDV_20180103T235236_20180103T235304_019997_022104_092D.SAFE S1A_OPER_AUX_POEORB_OPOD_20210305T192437_V20180102T225942_20180104T005942.EOF config.s1a.txt vv 1" (as shown in the figure). 
Finally, only phase filtering results were generated in F1, F2 and F3, and no settlement results were found. 
May I ask how to solve the problem?  
p2p_S1_TOPS_Frame.csh is for processing three subswaths, but my study area is only located in one subswath（only F1）, could you please tell me if it is possible to process only one subswath? If so, how to process only one subswath? 
Looking forward to your reply.
![2022-11-30 (3)](https://user-images.githubusercontent.com/116501665/204721163-3031b16f-297b-4f95-851d-8774a230f7dd.png)
![2022-11-30 (4)](https://user-images.githubusercontent.com/116501665/204721183-44f8e7c6-fc4f-457c-8618-2b79e4e1065f.png)
![2022-11-30 (5)](https://user-images.githubusercontent.com/116501665/204721193-3dfd15b1-b0c2-4d61-ac41-cc5cd954965b.png)
![2022-11-30 (2)](https://user-images.githubusercontent.com/116501665/204721212-98591fc7-00e6-45b9-a5f6-013691675a2a.png)
![2022-11-30](https://user-images.githubusercontent.com/116501665/204721229-f006fe67-d963-4559-8e33-7031215bb130.png)
![2022-11-30 (1)](https://user-images.githubusercontent.com/116501665/204721243-55b92e4f-636a-4280-940b-7b19c8b535d2.png)
log in the F1 folder:
[log_F1.txt](https://github.com/gmtsar/gmtsar/files/10120054/log_F1.txt)
log in the F2 folder:
[log_F2.txt](https://github.com/gmtsar/gmtsar/files/10120055/log_F2.txt)
log in the F3 folder:
[log_F3.txt](https://github.com/gmtsar/gmtsar/files/10120056/log_F3.txt)
log in the merge folder:
[merge_log.txt](https://github.com/gmtsar/gmtsar/files/10120059/merge_log.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Did you turn on ionospheric correction or not? Seems the p2p_S1_TOPS_Frame.csh think it has turned on but your log says it was not turned on. 

Try turn it off and run things through first.

**Comment by zth1015** [comment]
> Did you turn on ionospheric correction or not? Seems the p2p_S1_TOPS_Frame.csh think it has turned on but your log says it was not turned on.
> 
> Try turn it off and run things through first.

I saw that ionospheric correction is included in the csh script, and I did not change the script. I would like to ask how to turn off ionospheric correction.
![5b16c410efea1497afd6f9dde35dccd](https://user-images.githubusercontent.com/116501665/204949947-785644cc-882e-4546-b8fe-e6d3c3407842.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You could control that within the config file. i.e. your config.s1a.txt

**Comment by zth1015** [comment]
> You could control that within the config file. i.e. your config.s1a.txt
Thank you for your reply, I am trying.
I have another question for you. When making SBAS, I conducted atmospheric correction on "phasefilt.grd", then how to use the corrected phasefilt.grd to unwrap and SBAS? I checked the script to unwrap and SBAS, but I didn't find any code that could continue to run with the corrected phasefilt.grd.

**Comment by zth1015** [comment]
> You could control that within the config file. i.e. your config.s1a.txt

Hi, I tried to turn off the ionospheric correction, but it's still going wrong.
I have another question for you. When making SBAS, I conducted atmospheric correction on filtering phase (phasefilt.grd), then how to unwrap filtering phase and SBAS after correction? I have checked the script of understanding entangling and SBAS. No code was found to continue running with the corrected phasefilt.grd

**Comment by Xiaohua-Eric-Xu** [comment]
> Hi, I tried to turn off the ionospheric correction, but it's still going wrong.

Could you send a log file and your config.s1a.txt?

**Comment by Xiaohua-Eric-Xu** [comment]
> then how to unwrap filtering phase and SBAS after correction? I have checked the script of understanding entangling and SBAS. No code was found to continue running with the corrected phasefilt.grd

If you mean time-series analysis, here's a tutorial. http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf

**Comment by zth1015** [comment]
> > then how to unwrap filtering phase and SBAS after correction? I have checked the script of understanding entangling and SBAS. No code was found to continue running with the corrected phasefilt.grd
> 
> If you mean time-series analysis, here's a tutorial. http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf

When unwrapping, should snaphu_interp.csh or snaphu.csh be used in unwrap_intf.csh? I noticed that there are two csh scripts of snaphu. 
Mine is the Qinghai-Tibet Plateau, there is no earthquake, may I ask the second value in "snaphu_interp.csh 0.01 0" should be set to what is appropriate?
![image](https://user-images.githubusercontent.com/116501665/205234298-8d1a7031-c725-4ad7-bb33-a0440384b45b.png)

**Comment by Xiaohua-Eric-Xu** [comment]
For your case, first create a mask_def.grd using stacked coherence grids, and then run `snaphu_interp.csh 0.001 0`.

**Comment by zth1015** [comment]
> > Hi, I tried to turn off the ionospheric correction, but it's still going wrong.
> 
> Could you send a log file and your config.s1a.txt?
[correct_config.s1a.txt](https://github.com/gmtsar/gmtsar/files/10139166/correct_config.s1a.txt)
[F1_log.txt](https://github.com/gmtsar/gmtsar/files/10139167/F1_log.txt)
[F2_log.txt](https://github.com/gmtsar/gmtsar/files/10139168/F2_log.txt)
[F3_log.txt](https://github.com/gmtsar/gmtsar/files/10139170/F3_log.txt)
[merge_log.txt](https://github.com/gmtsar/gmtsar/files/10139172/merge_log.txt)
[merge_log_corr.txt](https://github.com/gmtsar/gmtsar/files/10139174/merge_log_corr.txt)
[merge_log_mask.txt](https://github.com/gmtsar/gmtsar/files/10139177/merge_log_mask.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Do you have terminal outputs after the processes inside F1/2/3 are done? i.e. `Merging START ...` and so on.

**Comment by zth1015** [comment]
> Do you have terminal outputs after the processes inside F1/2/3 are done? i.e. `Merging START ...` and so on.

This is the terminal output
![image](https://user-images.githubusercontent.com/116501665/205246363-8ae6505f-697b-478b-846f-2c5d808f8e41.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Feels like things are running normal. What's the error?

**Comment by zth1015** [comment]
> Feels like things are running normal. What's the error?

I don't know what to do. I can't find the problem.

**Comment by Xiaohua-Eric-Xu** [comment]
Well, if you don't know what problem to find, at least you can tell what you want?

**Comment by zth1015** [comment]
> Well, if you don't know what problem to find, at least you can tell what you want?

I want the final deformation result, but right now I only have the interference result.

**Comment by Xiaohua-Eric-Xu** [comment]
Since you skipped phase unwrapping in the config file, it is not doing phase unwrapping in the merge directory. You could
either 1) turn on snaphu_threshold = 0.1, or 2) go to the merge directory and run `snaphu.csh 0.1 0`.
Similar for geocoding, either turn on geocode_threshold = 0.1 or 2) go to the merge directory and run `proj_ra2ll.csh trans.dat your_grid your_grid_in_lon_lat`

**Comment by zth1015** [comment]
> Since you skipped phase unwrapping in the config file, it is not doing phase unwrapping in the merge directory. You could either 1) turn on snaphu_threshold = 0.1, or 2) go to the merge directory and run `snaphu.csh 0.1 0`. Similar for geocoding, either turn on geocode_threshold = 0.1 or 2) go to the merge directory and run `proj_ra2ll.csh trans.dat your_grid your_grid_in_lon_lat`

Yesterday, I set snaphu_threshold and geocode_threshold to non-0, but finally I also made an error. I've tried it again now and it's still running. I'll get back to you later.
I go to the merge directory and run snaphu.csh 0.1 0, the unwrap diagram is obtained, but the deformation diagram cannot be obtained. What I need is the final deformation of D-insar.
