### ISSUE TITLE
[Help]: merging

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#587]
Hi

How can i merging between two .grd file ?

Rang/azimuth with rang/azimuth 

And

Lat/long  with lat/long

@mobigroup 
@Xiaohua-Eric-Xu

**Comment by SteffanDavies** [comment]
You can merge/stitch products in the same orbit, is that what you are looking for?

**Comment by Xiaohua-Eric-Xu** [comment]
`merge_swath` for grd files.

**Comment by SteffanDavies** [comment]
> > You can merge/stitch products in the same orbit, is that what you are looking for?
> 
> I need to merging the final results for two scene
> 
> For example In scene 1 I have swath 2,3 And in scene 2 I have swath 2,3

Same orbit? You can use organize_files_tops_linux.csh. I believe it stitches products.

**Comment by mobigroup** [comment]
@Alzaidy1 To merge geocoded images use https://gdal.org/programs/gdal_merge.html

**Comment by Xiaohua-Eric-Xu** [comment]
> @Alzaidy1 To merge geocoded images use https://gdal.org/programs/gdal_merge.html

He mentioned his product in radar coordinates.

**Comment by Xiaohua-Eric-Xu** [comment]
> > You can merge/stitch products in the same orbit, is that what you are looking for?
> 
> I need to merging the final results for two scene
> 
> For example In scene 1 I have swath 2,3 And in scene 2 I have swath 2,3

merge_swath could handle either 2 or 3 inputs.

**Comment by mobigroup** [comment]
@CUMT530849827 merge_swath processes grids in radar coordinates only but you are trying to use grids in geographic coordinates instead.

**Comment by Xiaohua-Eric-Xu** [comment]
@CUMT530849827 turn on det_stitch in your config file. 

@mobigroup what program could merge in geo-coordinates? I used to use `grdblend` in gmt, but the data may yield slightly different values as it goes to the edge of a subswath. Any example?

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu As I’ve noticed above gdal_merge is the tool.

**Comment by KIKINEO** [comment]
> 
Dear Professor Xu, is there any way to splicing and merging the two interferograms, or the final dinsar los to deformation results? Just like the picture  @Xiaohua-Eric-Xu Best regards~
![ask](https://github.com/gmtsar/gmtsar/assets/107243861/b77dba8a-d9cc-455e-af2e-c4800b23de20)

**Comment by mobigroup** [comment]
@KIKINEO that’s called stitching using pins in GMTSAR. You can find interactive example for this area 3 scenes processing on Google Colab: https://colab.research.google.com/drive/1H652deK0W7nujEky9j9K20729vywntuD?usp=sharing

**Comment by Xiaohua-Eric-Xu** [comment]
If you are running Sentinel-1 data, try `organize_files_tops[_linux].csh` or simply `create_fraem_tops.csh` or even `assemble_tops.c` to stitch data together before running processing. If (in any case), you are running ALOS-2 ScanSAR or other datasets, due to change in near_range and other parameters (as we could not un-focus the data), you may want to process the data to interferogram level and then use `stitch_ra_product.csh` to stitch things together.
