### ISSUE TITLE
Distribution of parallel code via Docker/Kubernetes

### ISSUE THREAD

**Issue by davidbernat** [gmtsar/gmtsar#59]
The unwrapping phase `snaphu_interp.csh` is generally by far the slowest part of the pipeline for me. For Sentinel-1, using three months of S1A data (8 SLCs), I have a data set in which 22 baselines are generated. Each baseline takes about 2 hours to process. My Mac has 16GB RAM, which means I can run with about 2 thread. But I have found the processing time per thread to be highly unpredictable. For instance, some times I run 8 threads and complete in 4 hours. Other times the same conditions will take hours. Anyway...

I plan to Dockerize your GMTSAR package and handle this step with a parallelization using a cluster on Google Cloud Platform. Have you investigated this yet?

Hopefully this will be useful for anyone who finds this thread via Google.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi David,
I think we have not yet tried anything with that. Unwrapping is quite non-linear. Generally, those with low coherence will take significantly longer time to compute (more residues to deal with). Please keep us noted on your findings.
Xiaohua(Eric)
