### ISSUE TITLE
snaphu_interp.csh

### ISSUE THREAD

**Issue by kjz1997** [gmtsar/gmtsar#590]
Hi professfor
After I unwrapped the image using the snaphu_interp.csh 0.25 20 -R(this is the region  I want to cut) script, I ran the sbas script, but the following error was reported:
`dimension don't match! ../intf_all/2019040_2019052/corr.grd `
I use gmt grdinfo corr.grd, gmt grdinfo unwrap.grd, I found that Corr.grd  was not cut when unwrap

**Comment by omarwater98** [comment]
you can cut yourself with
gmt grdcut corr.grd -Gnew_corr.grd -RX_min/X_max/Y_min/Y_max
X_min/X_max/Y_min/Y_max = gmt grdinfo unwrap.grd

**Comment by Xiaohua-Eric-Xu** [comment]
The newer snaphu.csh/snaphu_interp.csh (in the master branch) will keep the correlation file after cut.
