### ISSUE TITLE
sbas error

### ISSUE THREAD

**Issue by CUMT530849827** [gmtsar/gmtsar#591]
Hello professor, when I am doing SBAS processing When interfering with each strip, only the intf_all in the F1 file is complete, and the other files F2 and F3 have the errors shown on the figure below, and some files under the intf_all do not generate differential interferogram and other files. But this has not happened before
F1/intf_all /:
![image](https://user-images.githubusercontent.com/49933485/205774974-b015f0e9-416c-4b2f-9523-e4f71ee0b4bd.png)
F2/intf_all/
![image](https://user-images.githubusercontent.com/49933485/205775093-aa3699ac-73bc-47e9-9a15-1c0a4ed7ae66.png)
![image](https://user-images.githubusercontent.com/49933485/205775176-13dc9f2d-2bdb-49e9-851b-6a375c357716.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You'll have to provide a log file (terminal output) for your processing. F2 and F3

**Comment by CUMT530849827** [comment]
Dear professor, I have tried again, but the same error still occurs. When running interference, F1 results are all running completely, but F2 is still not running completely. The following is the result of F1 and F2 running and the run log of F2

![image](https://user-images.githubusercontent.com/49933485/208271111-416d0bcd-ea60-4416-972d-d850b2b66370.png)
![image](https://user-images.githubusercontent.com/49933485/208271122-81f6b49c-f7fe-4540-ae83-a414bbffd7c3.png)
![image](https://user-images.githubusercontent.com/49933485/208271701-896b8e49-66e7-44f8-bff3-4f3346f607f7.png)

[F2 SBAS ERROR.txt](https://github.com/gmtsar/gmtsar/files/10252973/F2.SBAS.ERROR.txt)

**Comment by CUMT530849827** [comment]
@Xiaohua-Eric-Xu

**Comment by Xiaohua-Eric-Xu** [comment]
`Warning: Your gmt.conf file (gmt.conf) may not be GMT 5 compatible`
Could this be the reason? How did you install GMT and GMTSAR? Or first of all, which version of GMT and GMTSAR did you install?

**Comment by CUMT530849827** [comment]
Yes, professor, I previously installed a version that is not the latest gmtsar, then I installed gmt6.2, after your prompt, I reinstalled gmtsar 6.2 and then tested SBAS and it worked fine. Thank you, professor
