### ISSUE TITLE
[Help]: size of aps.grd inconsistent

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#592]
Hie Eric,
Hope you are doing well.
for my AOI
i ran _sbas intf.tab scene.tab 574 170 3000 3000 -range 860172.76141805244961932000  -incidence 38 -wavelength 0.0554658 -smooth 5.0 -atm 3.0 -rms_
but the size of the aps.grd file formed are not equal.
![image](https://user-images.githubusercontent.com/88940973/205831168-def0eb6f-5145-4bf8-99ea-4b6c5ff8b9ed.png)

as some files hava aorund 3Mb and some have 249kb
What could be the reason for this one?

Waiting for your reply.

Thanks and Regards

**Comment by Xiaohua-Eric-Xu** [comment]
GMT automatically compresses grids. If you check on those that are tiny, they are probably all zeros. That's because for those dates there are not enough interferograms connected on each side to provide an APS estimates.

**Comment by shivamthescienceguy** [comment]
Perfect, That makes sense.
Thanks Eric.

**Comment by shivamthescienceguy** [comment]
Hie Eric,
I tried with a test of _-atm 1.0_ 
Again the sizes of the aps.grd are inconsistent similarly as when I tried with _atm -3.0_
But logically  with 1 image is connected to atleast 1 surrounding image.
So the sizes should be consistent Right?. 
What could be the reason for this one?

**Comment by Xiaohua-Eric-Xu** [comment]
> I tried with a test of _-atm 1.0_
> Again the sizes of the aps.grd are inconsistent similarly as when I tried with _atm -3.0_

Changing the number of iteration will not affect which date gets aps estimate. The aps estimates are done only when a date has an interferogram that connect to a date before and an interferogram that connect to a date later and, very importantly, the two interferogram has equal time-span, e.g., both 12-day.

**Comment by shivamthescienceguy** [comment]
So I cant correct this one unless I dont change my baseline plot map and do the intf generation processing again and make sure every image has an intf before and an intf after it.
Because for time series I need values in all the aps.grd.

__Interestingly Eric, there was not much difference in the maximum value of subsidence in with and without APS corrected vel.grd_. just a difference of 1mm/year_

**Comment by Xiaohua-Eric-Xu** [comment]
> Because for time series I need values in all the aps.grd.

Why is that?

> Interestingly Eric, there was not much difference in the maximum value of subsidence in with and without APS corrected vel.grd_. just a difference of 1mm/year

The rate will not be affected much by the -atm option. The time-series however, will be affected. So is the uncertainty.
