### ISSUE TITLE
[Feature]: sbas

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#593]
Hi,dear professors,
When I execute the sbas command, the following problem occurs. How to solve it?
![QQ截图20221206155110](https://user-images.githubusercontent.com/114629377/205852726-fb04084f-7da9-4277-a099-d4d834c68c7c.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Killed usually means the program got interrupted by the system. But I am not sure why. Memory problem?

**Comment by kjz1997** [comment]
> Killed usually means the program got interrupted by the system. But I am not sure why. Memory problem?
I also encountered such problems，here is my computer
Name: 	DESKTOP-LR50O3T
Processor：	AMD Ryzen 7 5800U with Radeon Graphics  1.90 GHz
RAM：	16.0 GB (15.3 GB 可用)
System：X64

**Comment by Xiaohua-Eric-Xu** [comment]
What was the terminal output from your sbas command? Any RAM estimates spitting out?

**Comment by Xiaohua-Eric-Xu** [comment]
Could you download a new sbas.c from the current master branch? and then recompile the code ant try it again?

**Comment by kjz1997** [comment]
I've found a problem, processing 23 scenes, 70 interference pairs requires 17G of memory, and my computer only has 16G, so it is terminated. I would like to ask if there is a way to reduce memory usage？

发自我的iPhone

**Comment by Xiaohua-Eric-Xu** [comment]
turn on -mmap to swap disk space as memory.

**Comment by Xiaohua-Eric-Xu** [comment]
Or simply downsample or cut your data.
