### ISSUE TITLE
[Help]: unwrap_intf.csh

### ISSUE THREAD

**Issue by c-rutland** [gmtsar/gmtsar#594]
**Describe the problem you met**
I am trying to unwrap multiple interferograms, and have have created the unwrap_intf.csh script as in the timeseries recipe, but when I run:

_unwrap_intf.csh intflist_

I get the error _"intflist: Not a directory"_

My files are:

**unwrap_intf.csh**

#!/bin/csh -f
#intflist contains a list of all date1_date2 directories.
cd $1
#ln -s ../landmask_ra.grd .
snaphu_interp.csh 0.1 30
cd ..

**intflist**

2022168_2022252
2022180_2022252
2022192_2022252
2022204_2022252
2022216_2022252

and I am running this in the _intf_all_ directory, where the _intflist_ directories are found.

**Comment by Xiaohua-Eric-Xu** [comment]
I guess you need to run e.g., `unwrap_parallel.csh intflist 2` ?

**Comment by Pavithra-4pi** [comment]
where did u keep the unwrap_intf.csh file for executing in intf_all...

**Comment by Xiaohua-Eric-Xu** [comment]
You could either 1) put it in to a directory that's in your $PATH, or 2) move it to the directory you are executing unwrap_parallel.csh.
