### ISSUE TITLE
[Feature]: phase and phasefilt 

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#595]
Hi,dear professors,
Figure 1 is phase.pdf, Figure 2 is phasefilt.pdf, and Figure 3 is umwrap.pdf, filter_wavelength=300 in batch_tops.config. I'd like to ask you a question. Will my filter_wavelength value need to be adjusted after the phase vs. phasefilt comparison? Isn't that a good result?

figure 1:
![XZ8)5@`W59GTP4LD17$}K3Y](https://user-images.githubusercontent.com/114629377/206663447-a278d8c9-19ea-4276-968c-c593c0be10f5.png)
figure 2:
![FNXJZ4DO$7KPJQ%0469@9Y0](https://user-images.githubusercontent.com/114629377/206663536-8bdd3ac2-3cae-4a20-a84d-b2ed9228b66a.png)
figure 3:
![OLE@JY8QX(@AD H(GLX@_T5](https://user-images.githubusercontent.com/114629377/206663585-04671d2c-de03-4033-a0fa-95ad83b460dd.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Looks pretty good. Also the filter_wavelength parameter affects the gaussian filter part which is included in both phase.grd and phasefilt.grd. The difference between the two is that phasefilt.grd has the Goldstein (spectral) filter applied.
