### ISSUE TITLE
[Feature]: phase and phasefilt

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#596]
Hi,dear professors,
Figure 1 is phase.pdf and Figure 2 is the result phasefilt.pdf with a filter value of 200. Does my filter value need to be adjusted according to the comparison? for example 300?
figure1:
![FP$0TDOW_U)(E)% 5F{SR0R](https://user-images.githubusercontent.com/114629377/206896523-4e0097b3-3856-4548-9297-16bd07e8c3c9.png)
figure2:
![{}$NG7ZH@8 0U01A)MWKR{S](https://user-images.githubusercontent.com/114629377/206896529-886a0907-fa1a-43b4-87be-f3407a9d2a1b.png)

**Comment by Luvina0503** [comment]
wavelength=700
![7{8S{GAXUVC~)6YUOHN@0J8](https://user-images.githubusercontent.com/114629377/206896566-ed5a39d0-7300-4a00-a49b-c9a80dbc56a6.png)

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu  
What I want to do next is land subsidence analysis

**Comment by Xiaohua-Eric-Xu** [comment]
1) this comparison (about Goldstein filtering) does not tell you anything about subsidence analysis.
2) then it depends on the size of the area you would like to analyze. Larger filter_wavelength will make solution more smooth in space.

**Comment by Luvina0503** [comment]
OK.thank you
