### ISSUE TITLE
[Feature]: select_pairs.csh

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#597]
Hi,dear professors,
Why does my F1/intf.in have 206 lines, F2/intf.in 210 lines and F3/intf.in 214 lines? Why do the three strips have different number of interference pairs? Is there a problem? Or is this result OK and you can do strip merge?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
YES.I use select_pairs.csh for  each subswath. So what should I do? Use select_pairs.csh in F1, then replace intf.in in F1 directly in F2 and F3. Is that right?

**Comment by Xiaohua-Eric-Xu** [comment]
Do it with your F2 directory, copy the intf.in to your F1/F3 directories, and then use awk to change all F2 in intf.in to F1 and F3.

**Comment by Xiaohua-Eric-Xu** [comment]
This could be done easily with `:%s/F1/F2/g`

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
I would like to ask you a question.
There are a lot of midpoints in unwrap.grd, but the vel.grd result from sbas command has much less midpoint data, and my deformation area is gone.
figure1:(unwrap.grd)
![21a5abe3664a34959c39cc3bf6483c9](https://user-images.githubusercontent.com/114629377/206953855-5290bb17-84e6-42fc-9144-02646c963741.jpg)
figure2:(vel.grd)
![5456d9b6b271662b973eab9f68f394c](https://user-images.githubusercontent.com/114629377/206953982-1f41252d-5872-4441-ba2e-de7b46a264f1.png)

**Comment by Xiaohua-Eric-Xu** [comment]
This has been answered many times over the issue pages. Decorrelation is not consistent through space and time. A single pair of interferogram will have some decorrelation, but when combined with lots of others in the sbas program, the area will grow, in the sense that the program will consider the column as nan when there is a single pair being nan.

**Comment by Xiaohua-Eric-Xu** [comment]
We seek a fast solution so would like not to implement i-sbas or n-sbas and instead select pixels before piping them into sbas, either with PS or a common coherence mask.

**Comment by Luvina0503** [comment]
> We seek a fast solution so would like not to implement i-sbas or n-sbas and instead select pixels before piping them into sbas, either with PS or a common coherence mask.
@Xiaohua-Eric-Xu  What do you mean I should do before sbas? I don't quite understand what you mean by this sentence. Could you be more specific? thank you

**Comment by Xiaohua-Eric-Xu** [comment]
@Luvina0503 Could you let me know which specific part you don't understand?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu What I want to say is should I abandon some interference pair and then conduct sbas again? Does that guarantee my results? In order to get a better result, how do I find the interferogram of NAN and then delete them?

**Comment by Xiaohua-Eric-Xu** [comment]
For most InSAR data processing scenarios, there is no magic that will guarantee you a good result. You'll have to adapt certain skills for your specific target. For you case, I would just create a common coherence mask and unwrap with very low coherence threshold. Then run sbas again to produce time-series.

**Comment by Xiaohua-Eric-Xu** [comment]
I recently put a script called stack_coherence_mask.csh, which is here https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/stack_coherence_mask.csh . Do you mind giving it a try?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu Let me try. Is this executed before sbas? What do grid_list and average_corr_threshold refer to? What does this script do?

**Comment by Xiaohua-Eric-Xu** [comment]
With the script you'll be able to create a mask_def.grd. Link that to every directory you'll be unwrapping phase (e.g. snaphu_interp.csh 0.001 0), then snaphu will read in the mask and create a mask applied to your radar phase. With the very small coherence threshold (e.g. 0.001), all other pixels are likely preserved. This is similar as PS selection but with DS selected simply with coherence. Then you can run sbas again to produce a time-series with customized coverage (with mask_def.grd).

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu But my coherence threshold is 0.1. Will this script work? And I did GACOS correction after unwinding.

**Comment by Xiaohua-Eric-Xu** [comment]
The two factor you mentioned is really not related to the problem. See this for more details. http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf

**Comment by Luvina0503** [comment]
> I recently put a script called stack_coherence_mask.csh, which is here https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/stack_coherence_mask.csh . Do you mind giving it a try?

@Xiaohua-Eric-Xu  
What file does average_corr_threshold refer to in this command? Does grid_list refer to the file directory where corr.grd is stored?
![image](https://user-images.githubusercontent.com/114629377/217749339-1925588c-4e2b-4c89-9b0b-726f7f40d09e.png)

**Comment by Xiaohua-Eric-Xu** [comment]
the $average_corr_threshold means if the average coherence of a pixel is smaller than that, the created mask_def.grd will give that pixel NaN, otherwise it'll be 1.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
How to determine whether the average coherence of a pixel is less than this value? Or is this always going to be 1?

**Comment by Xiaohua-Eric-Xu** [comment]
The script will stack the corr.grd-s in the grid list you provide, and calculate the average I believe. Then it will use `gmt grdmath` to compare the grid with the threshold value you input, and create a mask_def.grd as a result.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
However, according to the code in this script, there is no mask_def.grd file in my corr_list. Running this script will cause an error in the red box in the figure.
![image](https://user-images.githubusercontent.com/114629377/218634697-99934a8c-a610-4eda-a392-de68937e0bed.png)
![image](https://user-images.githubusercontent.com/114629377/218634879-a5123b14-69de-4009-928d-38b32bfa3c50.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure I understand what you mean. The line in the red box will copy your first corr.grd to the directory and name it as mask_def.grd. You should be running this script in the merge directory by the way.

**Comment by Xiaohua-Eric-Xu** [comment]
It's just a list of file names, either relative or absolute. An easy command to get that is `ls 20*/corr.grd > grd_list`.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
This is what I saw when I read the manual. I see that you use a combination of the two methods. So when you run it, you just need to link mask_def.grd from the merge directory to each intervention directory, right?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
According to the two methods described in the manual, which method is best used for the study area of Jiangsu Province?
![image](https://user-images.githubusercontent.com/114629377/219238555-db29abef-dad5-4313-bd5a-9d2d775bbcff.png)

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu Does using stack_coherence_mask.csh correspond to processing corr grd in each interference file to get mask_def.grd? Do I use masdk_def.grd file for subsequent unwrapping?

Link mask_def.grd to each of your interferogram directory and then run `snaphu_interp.csh 0.001 0`.

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu
> 
> I have a question. According to your code, the code in the red box is in the merge directory, shouldn't it be in the $line? And for subsequent unwrapping, it should be mask_def.grd in each interference directory, right? This is just my understanding. Please point out any mistakes ![image](https://user-images.githubusercontent.com/114629377/219058388-a1a6ea80-1ffa-426a-92fd-88d1363842b1.png)

This is just to create mask_def.grd. Whether to use it for phase unwrapping or other processing depends on what you do later. So it is not put in to each $line directly. When you see a script, please don't just consider for one specific processing scenario, as it may be used for other occasions as well.

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu This is what I saw when I read the manual. I see that you use a combination of the two methods. So when you run it, you just need to link mask_def.grd from the merge directory to each intervention directory, right?

I believe so.

**Comment by Luvina0503** [comment]
i got it .thank you

**Comment by Xiaohua-Eric-Xu** [comment]
> @Xiaohua-Eric-Xu According to the two methods described in the manual, which method is best used for the study area of Jiangsu Province? ![image](https://user-images.githubusercontent.com/114629377/219238555-db29abef-dad5-4313-bd5a-9d2d775bbcff.png)

I never processed any data at your AOI, so could not directly answer this question. InSAR processing usually takes a few round to get good results as every time you may find something to improve. It'll be much better to try things out yourself than relying on other folks "experiences", as you are probably the person that knows best about the area you are working on.

**Comment by Luvina0503** [comment]
OK.Thank you very much for your patient answer

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
Figure 1 is mask_def.grd when I run it from the script you provided.https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/stack_coherence_mask.csh 
Figure 2 is mask_def.grd when I run it by the maunual.
https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf
Why does it feel different? Or is the result the same?

figure1 ：
![N}Q(XG1A5MLZO _%@B9(F}U](https://user-images.githubusercontent.com/114629377/220875411-5e7a3175-ae7d-46b0-b3b9-2996148810bd.png)
figure2：
![7F9H$%4K4BNR78J%}OLP$NY](https://user-images.githubusercontent.com/114629377/220875470-99fc910c-98bb-4b54-bc37-d81c164b6cd0.png)
figure3:https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf
![image](https://user-images.githubusercontent.com/114629377/220875670-e85c11e4-9500-4a77-983c-fecc5dc18c77.png)

**Comment by Xiaohua-Eric-Xu** [comment]
What's the command you use with `stack_coherence_mask.csh`?

**Comment by Luvina0503** [comment]
https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/stack_coherence_mask.csh

**Comment by Xiaohua-Eric-Xu** [comment]
I mean the command, not the script.

**Comment by Luvina0503** [comment]
stack_coherence_maks.csh corr_list 0,.075

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, that's strange as I just tried the script it works just fine providing me something like your second plot. Could it be that you have a `,` in your `0,.075` so GMT could not recognize that number?

**Comment by Luvina0503** [comment]
For urban areas (non-coastal areas), what is the mask threshold in general? Is the point density in FIG. 1 (mask threshold 0.075) too dense? Is the threshold too low?

**Comment by Luvina0503** [comment]
![2LJW@XX_(KK3$}4Y36GK5NO](https://user-images.githubusercontent.com/114629377/230393390-b271635b-9b97-473a-a6b4-69de2325949f.png)

**Comment by Xiaohua-Eric-Xu** [comment]
It really depends on what you think are stable pixels. A higher threshold will give you pixels with higher average coherence, but you'll end up with less pixels. I think the mask you created looks good.
