### ISSUE TITLE
 gnss_enu2los

### ISSUE THREAD

**Issue by kjz1997** [gmtsar/gmtsar#598]
Hello, teacher

When I use this script to convert the GPS deformation to the LOS direction, it reports this error

<img width="676" alt="捕获" src="https://user-images.githubusercontent.com/89446964/206965649-622c1288-6b3c-41cc-bfac-dce4d7841f3e.PNG">

This is the format of my data（station：BKMS. The time range is 2019.1-2019.12. The coverage of SAR time is 2019.4-2019.12 ）

[gnss.txt](https://github.com/gmtsar/gmtsar/files/10204749/gnss.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Not sure, but seems the usage says the first column of your input gnss.sllenu is site name, while yours start with longitude.

**Comment by kjz1997** [comment]
> Not sure, but seems the usage says the first column of your input gnss.sllenu is site name, while yours start with longitude.

Hello, teacher.

I have modified the first column according to the format in usage, but it still reports the same error

**Comment by Xiaohua-Eric-Xu** [comment]
Please attach an error log and your gnss.txt.

**Comment by Xiaohua-Eric-Xu** [comment]
And also the output please.

**Comment by Xiaohua-Eric-Xu** [comment]
For your gnss.txt, maybe you wanna delete the first line before using as an input for the script?

**Comment by kjz1997** [comment]
> For your gnss.txt, maybe you wanna delete the first line before using as an input for the script?

Thank you very much, teacher. I get the results. 
I have another question, how to get the coherence of the rate point？

**Comment by Xiaohua-Eric-Xu** [comment]
For every interferogram, the coherence is in the corresponding corr.grd. If you want the average coherence, try stack_corr.csh

**Comment by kjz1997** [comment]
> For every interferogram, the coherence is in the corresponding corr.grd. If you want the average coherence, try stack_corr.csh

Thank you very much, teacher

**Comment by kjz1997** [comment]
> For every interferogram, the coherence is in the corresponding corr.grd. If you want the average coherence, try stack_corr.csh

Hello, teacher.

I used this script to get the coherence value, but I found that the longitude and latitude coverage of the coherence file is inconsistent with that of the vel.grd file, and the points in the vel.grd file cannot be found in the coherence file. What causes this? The size of the two files is the same in range and azimuth.

<img width="748" alt="捕获" src="https://user-images.githubusercontent.com/89446964/209135720-c17761ab-4c79-4992-b3f2-845ee4f15e7f.PNG">

**Comment by Xiaohua-Eric-Xu** [comment]
What you showed in the screenshot are grids in radar coordinates. 

> but I found that the longitude and latitude coverage of the coherence file is inconsistent with that of the vel.grd file

I am not sure I understand what you meant here. Do you have an example of this inconsistency?

**Comment by kjz1997** [comment]
> What you showed in the screenshot are grids in radar coordinates.
> 
> > but I found that the longitude and latitude coverage of the coherence file is inconsistent with that of the vel.grd file
> 
> I am not sure I understand what you meant here. Do you have an example of this inconsistency?

Thank you for your reply. I have solved it

**Comment by omarwater98** [comment]
Hi @Xiaohua-Eric-Xu how to get the LOS_GNSS_vel? 

What do you mean by file 1 and file 2?
and awk?

how i can write the command? paste file1 file2 | awk ‘{print [multiplying  e with e, n with n, up with up and then adding them]}’ > LOS_GNSS.vel

**Comment by Xiaohua-Eric-Xu** [comment]
Please use `gnss_enu2los.csh master.PRM master.LED gnss.sllenu dem.grd`. You may need an extra column of station names or just make something up.

**Comment by omarwater98** [comment]
> Por favor use `gnss_enu2los.csh master.PRM master.LED gnss.sllenu dem.grd`. Es posible que necesite una columna adicional de nombres de estaciones o simplemente invente algo.

so the gnss_los.rad file is the result?

It is normal for the content to be something like this:
20987.310814047         7970.412959058         2403901.222499587573
Range                        Azimuth                     Distance?

**Comment by Xiaohua-Eric-Xu** [comment]
The three columns should be range, azimuth and los displacement. The number in the third column does not look correct to me. Note the input gnss.sllenu should have 6 columns, i.e., station_name, lon, lat, east, north, up.

**Comment by omarwater98** [comment]
> The three columns should be range, azimuth and los displacement. The number in the third column does not look correct to me. Note the input gnss.sllenu should have 6 columns, i.e., station_name, lon, lat, east, north, up.

Thanks Xi yes it change the los displacement. this los displacement is in metros? or mm?

20987.310814047 7970.412959058 0.999999641897  

now to aply the correct_insar_with_gnss.csh i have to doit in every unwrap.grd file on my merge's directorys with this los displacement?

**Comment by Xiaohua-Eric-Xu** [comment]
I think they are in mm as said in the usage
```
 gnss.llenu**      -  GNSS displacements (Stat | Lon | Lat | E | N | U) in millimeters
```

**Comment by Xiaohua-Eric-Xu** [comment]
> now to aply the correct_insar_with_gnss.csh i have to doit in every unwrap.grd file on my merge's directorys with this los displacement and repeat the sbas?

I believe so. You could write a simple cshell command such as 
```
foreach folder (`ls -d 20*`)
  cd $folder
  gnss_enu2los.csh ......
  correct_insar_with_gnss.csh ......
  cd ..
end
```

**Comment by omarwater98** [comment]
> > now to aply the correct_insar_with_gnss.csh i have to doit in every unwrap.grd file on my merge's directorys with this los displacement and repeat the sbas?
> 
> I believe so. You could write a simple cshell command such as
> 
> ```
> foreach folder (`ls -d 20*`)
>   cd $folder
>   gnss_enu2los.csh ......
>   correct_insar_with_gnss.csh ......
>   cd ..
> end
> ```

![Error de correct insar](https://user-images.githubusercontent.com/113547446/218887619-deadc76d-8a11-43d7-93e5-f7a6d1fc29c0.png)

Hi Teacher Xi, i have continue with this error to apply the correct_insar_with_gnss.csh

These are the output to gnss_enu2los.csh

20987.310814047 7970.412959058 0.999999641897
19690.922146933 7748.289700471 0.999999881305

**Comment by Xiaohua-Eric-Xu** [comment]
Could you share your input files so I can reproduce the error?

**Comment by omarwater98** [comment]
> Could you share your input files so I can reproduce the error?

[Input_files.zip](https://github.com/gmtsar/gmtsar/files/10745708/Input_files.zip)

**Comment by omarwater98** [comment]
> Could you share your input files so I can reproduce the error?



> Could you share your input files so I can reproduce the error?

[input_files2gnss.zip](https://github.com/gmtsar/gmtsar/files/10746028/input_files2gnss.zip)

**Comment by Xiaohua-Eric-Xu** [comment]
I found the error, I think the filter_wavelength you used is too small (smaller than an increment?). Do note the unit is meters.

**Comment by Xiaohua-Eric-Xu** [comment]
Try something like 20000.

**Comment by omarwater98** [comment]
> Try something like 20000.

Thank you very much Professor, yes it worked. does it make sense to use this same gnss_los.rad file to correct the offset of all interferograms in my merge directory? Or would I have to generate a new file with each supermaster.PRM and each S1_*_ALL.LED of each interferogram generated from the F1 directory?

**Comment by omarwater98** [comment]
> > now to aply the correct_insar_with_gnss.csh i have to doit in every unwrap.grd file on my merge's directorys with this los displacement and repeat the sbas?
> 
> I believe so. You could write a simple cshell command such as
> 
> ```
> foreach folder (`ls -d 20*`)
>   cd $folder
>   gnss_enu2los.csh ......
>   correct_insar_with_gnss.csh ......
>   cd ..
> end
> ```

![aplicar_mismo_algoritmo_seguido_de_gnss](https://user-images.githubusercontent.com/113547446/219518733-22568241-acc0-44f3-8716-9fbf2888082d.png)

i made the script called correc_phase_all.csh and it gave me this error.

**Comment by Xiaohua-Eric-Xu** [comment]
if you are running a cshell script in bash, you may want to start your script with 
```
#!/bin/csh -f
foreach ...
```

**Comment by Luvina0503** [comment]
@kjz1997 
Hello, I'd like to ask you a question. If the GACOS correction results require GNSS data to verify. So where should this GPS data be downloaded from? What are the requirements of the GPS site selected? Can you directly process GPS data with a script in GMTSAR?

**Comment by Xiaohua-Eric-Xu** [comment]
> @kjz1997 Hello, I'd like to ask you a question. If the GACOS correction results require GNSS data to verify. So where should this GPS data be downloaded from? What are the requirements of the GPS site selected? Can you directly process GPS data with a script in GMTSAR?

To process GPS data, you may need a whole new software such as GAMIT.

**Comment by Luvina0503** [comment]
> Hello, teacher
> 
> When I use this script to convert the GPS deformation to the LOS direction, it reports this error
> 
> <img alt="捕获" width="676" src="https://user-images.githubusercontent.com/89446964/206965649-622c1288-6b3c-41cc-bfac-dce4d7841f3e.PNG">
> 
> This is the format of my data（station：BKMS. The time range is 2019.1-2019.12. The coverage of SAR time is 2019.4-2019.12 ）
> 
> [gnss.txt](https://github.com/gmtsar/gmtsar/files/10204749/gnss.txt)

@Xiaohua-Eric-Xu 
What I would like to ask is how to obtain such gnss data? Where can I download it?

**Comment by Xiaohua-Eric-Xu** [comment]
Somewhere like UNAVCO, UNR or SOPAC?

**Comment by kjz1997** [comment]
> @kjz1997 Hello, I'd like to ask you a question. If the GACOS correction results require GNSS data to verify. So where should this GPS data be downloaded from? What are the requirements of the GPS site selected? Can you directly process GPS data with a script in GMTSAR?

If the region you are processing is located in Chinese Mainland, GPS data cannot be obtained. If the region you are processing is Europe and the United States, data can be obtained from the following website http://geodesy.unr.edu/NGLStationPages/gpsnetmap/GPSNetMap.html or http://sopac-csrc.ucsd.edu/index.php/displacements/

**Comment by debvrat** [comment]
> Please use `gnss_enu2los.csh master.PRM master.LED gnss.sllenu dem.grd`. You may need an extra column of station names or just make something up.

Do we have to run this for every pair of dates, where gnss.sllenu would have displacement values between two dates?

**Comment by debvrat** [comment]
> > Try something like 20000.
> 
> Thank you very much Professor, yes it worked. does it make sense to use this same gnss_los.rad file to correct the offset of all interferograms in my merge directory? Or would I have to generate a new file with each supermaster.PRM and each S1_*_ALL.LED of each interferogram generated from the F1 directory?

Looking for the answer to the last question as well

**Comment by Xiaohua-Eric-Xu** [comment]
You only need to project with the same supermaster.PRM and LED file. But for each interferogram, you'll need to create one gnss_los.rad for later correction. The gnss data has daily solutions, so the prior step is to extract data corresponds to the acquisition dates of the interferogram.

**Comment by Gigi-gugu** [comment]
> The gnss data has daily solutions, so the prior step is to extract data corresponds to the acquisition dates of the interferogram.



> You only need to project with the same supermaster.PRM and LED file. But for each interferogram, you'll need to create one gnss_los.rad for later correction. The gnss data has daily solutions, so the prior step is to extract data corresponds to the acquisition dates of the interferogram.

Hello Professor Xu! I have two doubts. 1. I have data from 10 GNSS stations from 2010 to 2021, with the reference framework being IGS14. My SAR time span is 2019-2022. How can I use these 10 GNSS displacement data to correct InSAR interferograms? I understand that the ENU needs to be projected onto the LOS direction first, using the gnss_deu2los.csh script. 2. My InSAR and GNSS data only overlap partially, and some may completely overlap with InSAR data. How should I preprocess my GNSS time data? That is to say, you mentioned the sentence _**The GNSS data has daily solutions', so the prior step is to extract data corresponds to the acquisition dates of the interferogram**_.

**Comment by Xiaohua-Eric-Xu** [comment]
Usually the reference frame does not change that rapidly through time. As the Sentinel-1 orbit product are also in ITRF 14, I believe you could directly apply the GNSS data as an correction. 

For partial coverage in time. The script will use whatever exists to do the correction. i.e., if a data point is missing, it'll not be used. 

>> How should I preprocess my GNSS time data? That is to say, you mentioned the sentence The GNSS data has daily solutions', so the prior step is to extract data corresponds to the acquisition dates of the interferogram.

Yes.

**Comment by Gigi-gugu** [comment]
> Usually the reference frame does not change that rapidly through time. As the Sentinel-1 orbit product are also in ITRF 14, I believe you could directly apply the GNSS data as an correction.
> 
> For partial coverage in time. The script will use whatever exists to do the correction. i.e., if a data point is missing, it'll not be used.
> 
> > How should I preprocess my GNSS time data? That is to say, you mentioned the sentence The GNSS data has daily solutions', so the prior step is to extract data corresponds to the acquisition dates of the interferogram.
> 
> Yes.

Thank you for your reply. Wishing you a happy life!
