### ISSUE TITLE
open *.grd

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#599]
hi,dear professors,
i want to ask a quesiton.
unwrap_GACOS_corrected_ll.grd is the result after GACOS atmospheric correction.
Figure 1 is the result of ncview unwrap_GACOS_corrected_ll.grd
![3C2 5D_ $(QZ5X_$HVYD B2](https://user-images.githubusercontent.com/114629377/206985384-af6e9afc-a1f7-4fc6-9e6a-b243568c2a8c.png)
Figure 2 shows the png generated by grd2cpt and grd2kml.csh
![image](https://user-images.githubusercontent.com/114629377/206986047-2551e521-ba2a-47bc-af83-8e7494d659ba.png)
Figure 3 is the result of opening unwrap_GACOS_corrected_ll.grd with arcgis
![)A UZCW@ RTF WSKCPCMIA0](https://user-images.githubusercontent.com/114629377/206985657-dbad9a05-45a5-441d-a502-b69d00aa285d.png)
Why are the results so different between the three methods?

**Comment by Luvina0503** [comment]
Does this problem lead to problem#600?

**Comment by Luvina0503** [comment]
Does this problem lead to problem  #600 ?

**Comment by Xiaohua-Eric-Xu** [comment]
1) it does not lead to problem #600.
2) the three look identical except you used difference colormap and colorscale to plot them.
