### ISSUE TITLE
Generate DEM files for use with GMTSAR

### ISSUE THREAD

**Issue by davidbernat** [gmtsar/gmtsar#60]
Hi Eric,

I have downloaded the SRTMGL1.003 DEM granules from EarthData, and I have code to perform a simple crop on a set of bounds. As far as I can tell, this ought to be the same as the function you perform on this [page](https://topex.ucsd.edu/gmtsar/demgen/) here. Can you confirm that this is identical to the dem.grd file that service creates, or can you open up to what other steps will need to be taken for the data to be GMTSAR ready?  Thanks.

**Comment by dsandwell** [comment]
Hi David,

The page that makes the dem.grd executes the GMTSAR command make_dem.csh.  One need to add a grid of EGM96 to the SRTM data to get height above the ellipsoid. The file you need is here.

https://topex.ucsd.edu/gmtsar/tar/geoid.egm96.grd

David

> On Oct 11, 2020, at 8:58 AM, David Bernat <notifications@github.com> wrote:
> 
> 
> Hi Eric,
> 
> I have downloaded the SRTMGL1.003 DEM granules from EarthData, and I have code to perform a simple crop on a set of bounds. As far as I can tell, this ought to be the same as the function you perform on this page here. Can you confirm that this is identical to the dem.grd file that service creates, or can you open up to what other steps will need to be taken for the data to be GMTSAR ready? Thanks.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037
