### ISSUE TITLE
[Feature]: sbas result

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#600]
hi,dear professors,
I would like to ask you a question.
There are a lot of midpoints in unwrap.grd, but the vel.grd result from sbas command has much less midpoint data, and my deformation area is gone.
figure1:(unwrap.grd)
![21a5abe3664a34959c39cc3bf6483c9](https://user-images.githubusercontent.com/114629377/206987126-1fbedb7e-54ad-450a-afb0-29612a5282e1.jpg)
figure2:(vel.grd)
![5456d9b6b271662b973eab9f68f394c](https://user-images.githubusercontent.com/114629377/206987184-35a5293d-f859-424d-b991-ef8f338ed68a.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Answered here https://github.com/gmtsar/gmtsar/issues/597#issuecomment-1350431454
