### ISSUE TITLE
[Help]: combined

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#601]
Hello everyone 

how can I combining between ascending and descending path. I don’t need theory I need the steps to do that. 

Best regards

**Comment by Xiaohua-Eric-Xu** [comment]
1) Prepare asc_ll.grd and des_ll.grd which are LOS deformation in ascending and descending orbit. 
2) Use `gmt grdsample asc_ll.grd -R$lon_min/$lon_max/l$at_min/$lat_max -I$inc -Gasc_resamp_ll.grd` and `gmt grdsample des_ll.grd -R$lon_min/$lon_max/l$at_min/$lat_max -I$inc -Gdes_resamp_ll.grd`. Here $ mean variables that needs to be defined, and the area from the `-R` option needs to be a common area between the two grids.
3) Pic a middle point in the area defined by the `-R` option, and run `echo $lon $lat | gmt grdtrack -Gdem.grd | SAT_look asc.PRM` and `echo $lon $lat | gmt grdtrack -Gdem.grd | SAT_look des.PRM` to get two look vectors. You could compute their corresponding look angles with `acosd(look_U)`.
4) Now you have two options: if you assume the two look angle are largely symmetric (e.g. both from F2 of TOPS data), and the north component is negligible, you could use `gmt grdmath des_resamp_ll.grd asc_resamp_ll.grd ADD 2 DIV look_U DIV = vertical_ll.grd` and `gmt grdmath des_resamp_ll.grd asc_resamp_ll.grd SUB 2 DIV look_E DIV = east_ll.grd`; if you don't like the assumption of symmetry, you could write it as an inverse problem which is documented by lots of publications already. Basically it is a least square problem.
