### ISSUE TITLE
[Feature]: preproc_batch_tops_esd.csh

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#602]
command:preproc_batch_tops_esd.csh data.in dem.grd 2 2
error:
![image](https://user-images.githubusercontent.com/114629377/208124102-dfdae765-79ab-4678-80c3-064c293d25b9.png)

**Comment by Luvina0503** [comment]
When the preproc_batch_tops_esd.csh command is executed, other data is correct except one data scene. What's the reason?
[log.txt](https://github.com/gmtsar/gmtsar/files/10246943/log.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
I think the error comes from a line above 
```
Working on burst  #1 #2 #3 #4 #5 #6Bus error (core dumped)
```

And I don't really know what happened with this `Bus error`. Could the program somehow get killed or the data's corrupted? Bus error is hard to deal with.

**Comment by Luvina0503** [comment]
Should I discard this scene data?

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure. Either 1) redownload the data and try process this specific dataset (with your master image) or 2) just ignore this date for the moment.

**Comment by Luvina0503** [comment]
ok.i will try.thank you
