### ISSUE TITLE
[Help]: error while install gmtsar

### ISSUE THREAD

**Issue by blnikan** [gmtsar/gmtsar#604]
Hey!
Unfortunately I have problems with the installation. :(
I want to install gmtsar on my computer with ubuntu 22.04 .

As far as I know, I installed all the necessary libraries (which are written in your wiki).
I did everything as it is written on your wiki page.
I also took into account that for gmt version 6 you need "git clone --branch 6.0 https://github.com/gmtsar/gmtsar" as it was written on this page - https://github.com/gmtsar/gmtsar/issues/34

The first problems I have are on the 4th step of documentation. 
When I write 
``` 
autoconf
```
[Issue autoconf .txt](https://github.com/gmtsar/gmtsar/files/10255247/Issue.autoconf.txt)

<br>
<br>

If I go to the next steps, I get the following errors:
on the page (https://github.com/gmtsar/gmtsar/issues/236 ) you asked to start with the line "make spotless" so I'm including that too

[Issue make spotless log.txt](https://github.com/gmtsar/gmtsar/files/10255251/Issue.make.spotless.log.txt)
[Issue make log.txt](https://github.com/gmtsar/gmtsar/files/10255181/Issue.make.log.txt)

<br>

<br>

I will be very grateful for your help!!

**Comment by Xiaohua-Eric-Xu** [comment]
The warning you saw are because certain macros bring abandoned by autoconf (i.e. cgwin). You could ignore these ant continue, and we will remove this in configure.ac in the next distribution hopefully.

**Comment by blnikan** [comment]
Thank you for your answer!!
<br>

But unfortunately it doesn't work  pic. 1
![image](https://user-images.githubusercontent.com/65826674/208421295-1f75fc1b-b638-4311-9f36-13ae88e63c98.png)
<br>
structure of .bashrc on pic.2 (I'm talking about the fact that I added the necessary lines "export GMTSAR ...")
![image](https://user-images.githubusercontent.com/65826674/208422505-19991f15-2f22-487b-8967-8f4494709457.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Did you source your .bashrc file or open a new terminal?

**Comment by Xiaohua-Eric-Xu** [comment]
What's in your bin directory?

**Comment by blnikan** [comment]
@Xiaohua-Eric-Xu 
![image](https://user-images.githubusercontent.com/65826674/208439872-81bed4cd-7d88-4263-8fd4-95741f9bcb18.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I think you didn't compile the code. You should run `make` and then `make install` I believe.

**Comment by blnikan** [comment]
from the beginning I repeated only  ```make``` and ```make install``` but it did not give any results.
<br>
after which I repeated the installation and did all the steps that are written in the wiki. But it also didn't give any results.
<br>
could it be because i have ubuntu 22.04 ?

**Comment by Xiaohua-Eric-Xu** [comment]
Could it be this multiple definition issue? https://github.com/gmtsar/gmtsar/issues/165

**Comment by blnikan** [comment]
YES!! NOW IT WORKS!!!
THANK YOU VERY MUCH!!
![image](https://user-images.githubusercontent.com/65826674/209000547-ffc3f144-8d69-48da-813d-de28ee8a2a1e.png)
![image](https://user-images.githubusercontent.com/65826674/209000800-ea6437eb-e227-45e6-bd0a-60aeb532604d.png)
