### ISSUE TITLE
Regarding correcting InSAR with GNSS[Help]: 

### ISSUE THREAD

**Issue by AmiraZakii** [gmtsar/gmtsar#605]
Hello,
I have a question regarding this code: correct_insar_with_gnss.csh master.PRM phase.grd gnsslos.rad filter_wavelength
What phase.grd indicates? unwrapped phase for each interferogram or phasefilter.grd for each interferogram before unwrapping or the displacement.grd or the final velocity?
Thank you

**Comment by Xiaohua-Eric-Xu** [comment]
I think it should be unwrapped phase.

**Comment by Congzhangg** [comment]
@Xiaohua-Eric-Xu  Could you use this command to correct the rate graph with GNSS data?

**Comment by Xiaohua-Eric-Xu** [comment]
I don't think so unless you change the units some how. Do note here phase.grd are in radians, while the GNSS are in mm. The velocity from sbas are in mm/yr so you may need to convert it to radian/yr, correct with GNSS velocities in mm, and the convert from radian/yr back to mm/yr. This is a similar conversion from phase to LOS deformation as in geocode.csh line 77.
