### ISSUE TITLE
[Help]: Any reason why we are working with C Shell instead of Bash?

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#606]
C Shell seems relatively limited and outdated compared to using Bash. Even Z shell would probably be a superior choice. I assume it's because some developers here are using Mac?

For example, csh doesn't even support functions, you need aliases as a workaround. I believe it's the same for zsh but I have never worked with that shell.

In any case, would GMTSAR repo accept new bash scripts?

**Comment by SteffanDavies** [comment]
@Xiaohua-Eric-Xu I have parallelized merge_batch.csh by rewriting it in bash.

It works much faster assuming you are using an SSD. I can add it to the repo if you think it's appropriate.

**Comment by Xiaohua-Eric-Xu** [comment]
I think having a bash script is totally fine. It's just that we are more familiar with one of them.  

Do you want to make a pull request and maybe name it as merge_batch_parallel.sh? I could help read through and make the approval. It'll be in the repo for a while before we run it over enough cases and advertise it to the users/students.

**Comment by SteffanDavies** [comment]
Would you like me to place in in a "sh" folder in the [gmtsar](https://github.com/gmtsar/gmtsar)/gmtsar/ directory?

**Comment by Xiaohua-Eric-Xu** [comment]
Please put it to the GMTSAR/gmtsar/csh directory for the moment.
