### ISSUE TITLE
[Feature]: preproc_batch_tops_esd.csh data.in dem.grd 1 2

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#607]
command ：preproc_batch_tops_esd.csh data.in dem.grd 1 2
error：
![W NZ3J}CS3Q%4OC}E}R 6RB](https://user-images.githubusercontent.com/114629377/209455167-2f49f753-8262-49b3-b2cf-871be6557455.png)
Only one scene has the following problem. I re-downloaded the data and processed it separately, but the problem still occurred. Why is that?

**Comment by Xiaohua-Eric-Xu** [comment]
This rarely happens. Feels like some problem with a specific xml file. This error is showing that the de-burst part of the sentinel-1 processor could not find a certain parameter in the xml file. Could you check on that? i.e. whether the downloaded data is complete.

**Comment by Xiaohua-Eric-Xu** [comment]
preproc_batch_tops_esd.csh will run Enhanced Spectral Diversity to further remove phase discontinuities at burst boundaries. The three modes are 0 for average and 1 for median which respectively will take the mean, median for the double difference phase at burst overlaps for computing residual phase, and 2 for interpolation, which means it'll interpolate through the residual phase and calculate a map of residual azimuthal shift. 0 and 1 are good for orbit error, and 2 is more suitable for ionospheric phase correction.
