### ISSUE TITLE
[Help]: running sbas_parallel.c

### ISSUE THREAD

**Issue by cxinlong** [gmtsar/gmtsar#608]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through
Is it normal that the interface lasts at least 48 hours when running the sbas_parallel command?
**OS and software version**
If applicable, what operating system and software version you are using?
OS:Ubuntu 20.04
GMTSAR version:the latest one

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case
![Uploading 2022-12-27 09-06-44 的屏幕截图.png…]()

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by cxinlong** [comment]
![2022-12-27 09-06-44 的屏幕截图](https://user-images.githubusercontent.com/118950056/209604879-8df1f52b-f731-4c65-a990-47de0a4a71f9.png)

**Comment by Xiaohua-Eric-Xu** [comment]
A couple of things to check here:
1. Do you have ~24GB RAM to run sbas_parallel? The strange part is that you turned on -mmap which is supposed to use less memory but yet the program still says it needs ~23.5GB. 
2. Did you specify the number of threads? I don't see the problem getting divided to multiple threads.
3. If you run `top`, do you see sbas_parallel taking decent amount of cpu?

**Comment by cxinlong** [comment]
I have examined these questions carefully.
1、My RAM is 16+8, which meets the requirement of 24G.
2、I don't know how to set the number of threads.Can you give me a demonstration？
3、When I run the top command, I find that the cpu usage is about 14%.

**Comment by Xiaohua-Eric-Xu** [comment]
> 1、My RAM is 16+8, which meets the requirement of 24G.

It's barely on the verge, and considering your system needs memory to run, this may not be enough.

> 2、I don't know how to set the number of threads.Can you give me a demonstration？

For cshell, it should be like `setenv OMP_NUM_THREADS 10`. You may need to use `export` for bash.

> 3、When I run the top command, I find that the cpu usage is about 14%.

I am not really sure, but is that 14% being used by sbas_parallel? What if you run `ps -ax | grep sbas_parallel`

**Comment by cxinlong** [comment]
Thank you very much for your careful answer. How much memory do you think I should need to run this step？

**Comment by Xiaohua-Eric-Xu** [comment]
If -mmap is working fine, it should not use that much amount of memory. Could you download the newest version of sbas_parallel.c and try with the -mmap option again?

**Comment by Xiaohua-Eric-Xu** [comment]
Could you tell a bit on how you compiled sbas_parallel.c and the output from the new sbas_parallel command?

**Comment by cxinlong** [comment]
I compiled it by following the steps in the image below.
![1672975237892](https://user-images.githubusercontent.com/118950056/210923570-f2584f4f-6204-4eba-a147-6ca4004108b6.png)
The output of the new command is the same as below.
![1672975611879](https://user-images.githubusercontent.com/118950056/210924166-cb79a5fb-dd8d-4f42-a2ae-03c3e88c1ca3.png)

**Comment by Xiaohua-Eric-Xu** [comment]
What if you delete the -mmap? Will the Memory Usage change?

**Comment by cxinlong** [comment]
Yes, the memory usage will become about 140G.

**Comment by Xiaohua-Eric-Xu** [comment]
Never mind, the minimum usage is correct. As the least amount is needed for outputing the data which is xdim*ydim*S*4 + etc, and that ended up being ~22GB already. So I guess you have to either downsample your data or get more memory for your machine.

**Comment by cxinlong** [comment]
OK，emmm,how do I downsample my data?What should I do？

**Comment by Xiaohua-Eric-Xu** [comment]
One way of downsampling is to use `gmt grdsample input_grid -Ix_inc/y_inc -Goutput_grid`. e.g. `gmt grdsample unwrap.grd -I32/8 -Gunwrap_dsamp.grd`. You may need to downsample both phase and correlation grids.

**Comment by cxinlong** [comment]
Thank you very much for your help. The problem has been solved.

**Comment by cxinlong** [comment]
Sorry to bother you again. I'm downsampling for the first time, and this command says that 8 G of memory was needed, and I get the result. However, the points were too sparse, so I resampled the points at one time and increased the number of points. When I ran the sbas_parallel command and opened the -mmap option, I was prompted that 12G memory was needed, but I had 20G available memory, could you please tell me why it still didn't work?
![2023-01-10 09-26-28 的屏幕截图](https://user-images.githubusercontent.com/118950056/211441878-0179a908-e913-4b94-97ec-a1851b99124e.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Do you see sbas_parallel running in the background (e.g. with `top` command)? Using -mmap option will slow down the process a bit as it needs to swap disk space and use as memory. Your problem size seems big so it may take quite a while to run.

Also the strange part is that sbas_parallel did not output any threads initialization, and I am not sure why.

**Comment by cxinlong** [comment]
I used the ps-aux command to see that the process in the background is D+, which seems to be hibernated. Is the process running, but it just takes time?

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure why it's hibernated. Could you improve the priority of the program with nice?

**Comment by cxinlong** [comment]
I used the nice command to set it to highest priority, and its background state changed to R and D toggle back and forth. If I wanted to expand RAM, how much would I need to expand it? Can you give me a reference?

**Comment by Xiaohua-Eric-Xu** [comment]
How about doing a little experiment before extending your memory? Just to make sure sbas_parallel could work on your system. 
1. downsample your data (unwrap.grd and corr.grd) to a minisize with `gmt grdsample -I256/64 -Gyour_data_dsamp.grd`.
2. use these grids as input for sbas parallel, this should only cost a small fraction of RAM. Check whether you see the threads getting initialized properly.

**Comment by cxinlong** [comment]
Hello, Professor. Sorry to trouble you again. I have another question about GMTSAR. I want to know the principle of using GMTSAR for SBAS. Looking forward to your reply, thank you.

**Comment by Xiaohua-Eric-Xu** [comment]
If you mean building a time-series, there is a document here: http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf.

If you mean just the sbas program. You probably need to be a bit more specific on what signal you are targeting.

**Comment by cxinlong** [comment]
emmm,I mean I want to know the principle of the SBAS algorithm in GMTSAR, like in StaMps the principle of the SBAS algorithm is based on Hooper in his paper.

**Comment by Xiaohua-Eric-Xu** [comment]
I see. 

If you type `sbas` in your terminal, there'll be a couple of references:

These two are the original SBAS algorithm paper
```
Berardino P., G. Fornaro, R. Lanari, and E. Sansosti, “A new algorithm for surface deformation monitoring based on small baseline differential SAR interferograms,” IEEE Trans. Geosci. Remote Sensing, vol. 40, pp. 2375–2383, Nov. 2002. 

Schmidt, D. A., and R. Bürgmann 2003, Time-dependent land uplift and subsidence in the Santa Clara valley, California, from a large interferometric synthetic aperture radar data set, J. Geophys. Res., 108, 2416, doi:10.1029/2002JB002267, B9. 
```

This one is coherence based SBAS which uses coherence as weights for time-series inversion
```
Tong, X. and Schmidt, D., 2016. Active movement of the Cascade landslide complex in Washington from a coherence-based InSAR time series method. Remote Sensing of Environment, 186, pp.405-415. 
```

Then this one tells about the atmospheric correction algorithm (-atm) built in the program, which is called common scene stacking
```
Tymofyeyeva, E. and Fialko, Y., 2015. Mitigation of atmospheric phase delays in InSAR data, with application to the eastern California shear zone. Journal of Geophysical Research: Solid Earth, 120(8), pp.5952-5963.
```

Then finally this paper shows when the two algorithms above were implemented together, mainly targeting Sentinel-1 TOPS data processing
```
Xu, X., Sandwell, D. T., Tymofyeyeva, E., González-Ortega, A., & Tong, X.(2017). Tectonic and anthropogenic deformation at the Cerro Prietogeothermal step-over revealed by Sentinel-1A InSAR. IEEE Transactions onGeoscience and Remote Sensing, 55(9), 5284-5292.
```

**Comment by cxinlong** [comment]
Ok, thank you very much for your answer.

**Comment by cxinlong** [comment]
![2023-02-16 16-22-27 的屏幕截图](https://user-images.githubusercontent.com/118950056/219308249-12f4feb9-6f9c-441f-8840-bca200fad37f.png)
Hello, I have been running this step for a week, but I still can't get the result. My RAM is 48G, and the terminal display needs 25G, I think this should meet the conditions. But with no output, I wonder if this command is running and just needs time, or just can't handle big data.
These are the only outputs in the folder.
![2023-02-16 16-20-38 的屏幕截图](https://user-images.githubusercontent.com/118950056/219308546-f514fd9e-cb4e-4bdd-ad95-a0f5dfb84ffc.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You could check how its running in the background with `top`. I have to remind you the size of your interferogram is very large (8k x 10k). Please consider downsampling. Usually before running a large job like yours, I would first downsample the grids with (for TOPS data) `gmt grdsample unwrap.grd -I256/64 -Gunwrap_dsamp.grd` and `gmt grdsample corr.grd -I256/64 -Gcorr_dsamp.grd`. Then make a new intf.tab with the right file names and run the small job and see how it goes. I would tweak the parameters until the downsampled job looks good and then run the processing at high resolution.

**Comment by cxinlong** [comment]
I entered the top command and found that the running state of the sbas_parallel command has been D for a week. Is it just that you can't handle large amounts of data? I have tried the method of down-sampling, grdsample-I32/8 can get the result, but the resolution is very low, the velosity  result is almost blank. @Xiaohua-Eric-Xu

**Comment by Xiaohua-Eric-Xu** [comment]
> the velosity result is almost blank.

You may want to use common coherence mask for doing phase unwrapping as in http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf to avoid blank velocity results. 

> sbas_parallel command has been D for a week.

What is the cpu usage for sbas_parallel?

**Comment by cxinlong** [comment]
CPU is about 3.5%.

**Comment by Xiaohua-Eric-Xu** [comment]
That's barely running. I would expect things going to thousands of percentage on CPU. I am not sure why it is with so low priority. Maybe try nice or renice?

**Comment by cxinlong** [comment]
I have set the priority 20, but still no response.

**Comment by Xiaohua-Eric-Xu** [comment]
Then I am really not sure. Could it be that you are running it on a very slow disk with -mmap? The performance of -mmap depends on your disk I/O speed.

**Comment by cxinlong** [comment]
Thank you for your reply!Yes, I used the data from my portable hard drive and turned on the -mmap option. Does the portable hard drive respond slowly?

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, that could be the reason. It's better to use an external drive (not a portable one). If you have a rack of SSD, that's even better.

**Comment by cxinlong** [comment]
OK，thank you very much！
