### ISSUE TITLE
[Help]: KML value raster 

### ISSUE THREAD

**Issue by psibathd** [gmtsar/gmtsar#609]
I have a trouble with the output of SBAS. The vel_ll.kml raster value not the same as the vel_ll.grd. 
![image](https://user-images.githubusercontent.com/121473849/209611767-4f56e19e-6e37-499a-97e8-6dd1b16cfc10.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I guess the raster values are just numbers that represent colors (i.e. 0-255 RGB)?

**Comment by SteffanDavies** [comment]
You can always convert the grd to csv and work with the values directy in QGIS. You can also apply a custom colour.
