### ISSUE TITLE
Problem with batch processing using ALOS-1 1.0

### ISSUE THREAD

**Issue by CFEgildan71** [gmtsar/gmtsar#61]
**Hello.

I'm trying to do a time series using ALOS-1 1.0. I'm following the GMTSAR documentation:**

1. Preprocess all the images independently and examine the PRM files for median values of Doppler centroid (fd1), near range (near range), and earth radius (earth radius). An example command is:
ALOS pre_process IMG-HH-ALPSRP022200660-H1.0 A LED-ALPSRP022200660-H1.0 A

**To do the first step, I wrote a script:**

**for line in $(ls -d ALP*);do

echo  "I'm working on $line..."
cd $line 
basename IMG-HH-* > image_name.txt
basename LED* > LED_name.txt
var1=`cat image_name.txt`
var2=`cat LED_name.txt`

ALOS_pre_process $var1 $var2
cd ..
done**

**After processing, I joined all files in a raw folder.**

2. Based on this analysis one preprocesses all the images using the batch processing command.
pre proc batch.csh ALOS data.in

The file data.in defines the zero-baseline image and the common parameters for the stack.

IMG-HH-ALPSRP055750660-H1.0__A  -near 846567 -radius 6371902.401705 -fd1 100
IMG-HH-ALPSRP022200660-H1.0
IMG-HH-ALPSRP028910660-H1.0
MG-HH-ALPSRP035620660-H1.0

This command will also create a baseline versus time plot as shown in Figure 6.

**I created data.in and config.ALOS.txt but nothing happened when I run _**pre_pro_batch.csh ALOS data.in**_**

I attached the _**data.in, config.txt**_ files also _**baseline_table.dat**_

Could you help me to figure out why I don't get the baseline_plot.ps and the correct pre-proc?

Thank you.
[baseline_table.txt](https://github.com/gmtsar/gmtsar/files/5381898/baseline_table.txt)
[config.ALOS.txt](https://github.com/gmtsar/gmtsar/files/5381900/config.ALOS.txt)
[data.txt](https://github.com/gmtsar/gmtsar/files/5381901/data.txt)
![Screenshot from 2020-10-14 20-24-11](https://user-images.githubusercontent.com/38848954/96062588-aea82500-0e5b-11eb-99e2-56213c1eddea.png)
![Screenshot from 2020-10-14 20-25-58](https://user-images.githubusercontent.com/38848954/96062595-b1a31580-0e5b-11eb-867e-a9929a930979.png)

**Comment by Xiaohua-Eric-Xu** [comment]
It says that you need to use an image with FBD mode (one with larger size) as the master image.
