### ISSUE TITLE
Lines of brusts problem

### ISSUE THREAD

**Issue by AmiraZakii** [gmtsar/gmtsar#616]
Hello,
Could you please tell me how I can solve the problem of these lines between bursts appearing in unwrapped interferograms? how I can remove them?
![Capture2](https://user-images.githubusercontent.com/89259389/211209099-ee7eb863-e793-48f9-a1c3-86bee2ee4995.JPG)
![Capture](https://user-images.githubusercontent.com/89259389/211209178-9f394914-3406-4239-9dd3-5240aa4b3048.JPG)

**Comment by Xiaohua-Eric-Xu** [comment]
These are burst discontinuities from either ionospheric perturbation or orbital error. You could turn on ESD (enhanced spectral diversity) with setting `spec_div = 1` in the config file to remove these lines.

**Comment by AmiraZakii** [comment]
Hi @Xiaohua-Eric-Xu 
Do you mean in batch_tops.config file we use to generate interferograms? Or another file because this option is not in batch_tops.config file. 
Thank you

**Comment by Xiaohua-Eric-Xu** [comment]
Oh, seems you are doing batch processing? since you are using batch_top.config. If that's the case, when doing pre-processing, use preproc_batch_tops_esd.csh instead of preproc_batch_tops.csh.

**Comment by AmiraZakii** [comment]
Hi @Xiaohua-Eric-Xu, thank you. This problem is solved :)
I have another question; is it usual for SBAS analysis to take a long time, longer than three days, and still in the first step? The number of interferograms is 558, and the number of images is 158. Is this normal, or did I do something wrong?
![1](https://user-images.githubusercontent.com/89259389/214258166-b2dde3b4-c1de-4473-97f5-ce31876ee6f3.JPG)
![2](https://user-images.githubusercontent.com/89259389/214258172-fc3495bb-a6ac-420d-92be-03580452be44.JPG)

**Comment by Xiaohua-Eric-Xu** [comment]
It might be better to use sbas_parallel instead. Here's a brief description on how to use it. https://github.com/gmtsar/gmtsar/wiki/parallel-sbas-code

**Comment by cxinlong** [comment]
> Hi @Xiaohua-Eric-Xu, thank you. This problem is solved :) I have another question; is it usual for SBAS analysis to take a long time, longer than three days, and still in the first step? The number of interferograms is 558, and the number of images is 158. Is this normal, or did I do something wrong? ![1](https://user-images.githubusercontent.com/89259389/214258166-b2dde3b4-c1de-4473-97f5-ce31876ee6f3.JPG) ![2](https://user-images.githubusercontent.com/89259389/214258172-fc3495bb-a6ac-420d-92be-03580452be44.JPG)

Hello, May I ask you how many days did you run this step to get the result？

**Comment by cxinlong** [comment]
> Hi @Xiaohua-Eric-Xu, thank you. This problem is solved :) I have another question; is it usual for SBAS analysis to take a long time, longer than three days, and still in the first step? The number of interferograms is 558, and the number of images is 158. Is this normal, or did I do something wrong? ![1](https://user-images.githubusercontent.com/89259389/214258166-b2dde3b4-c1de-4473-97f5-ce31876ee6f3.JPG) ![2](https://user-images.githubusercontent.com/89259389/214258172-fc3495bb-a6ac-420d-92be-03580452be44.JPG)

@AmiraZakii Hello, May I ask you how many days did you run this step to get the result？
