### ISSUE TITLE
[Help]: intf_tops.csh, topo_ra.grd not found

### ISSUE THREAD

**Issue by geodesico** [gmtsar/gmtsar#617]
I am working on an SBAS processing, using a similar (if I'm not mistaken) procedure of the previous successful processing. However, in the topo folder, I'm missing topo_ra.grd file. 

The error appears as: 

`START FORM A STACK OF INTERFEROGRAMS

INTF.CSH, FILTER.CSH - START
......master LED file S1_20170608_ALL_F3.LED
.........aligned LED file S1_20170620_ALL_F3.LED
......master LED file S1_20170608_ALL_F3.LED
.........aligned LED file S1_20170608_ALL_F3.LED
intf.csh
running phasediff...
reading topo topo_ra.grd
phasediff [ERROR]: File topo_ra.grd not found
[Session phasediff (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open topofile topo_ra.grd
filter.csh
setting range_dec = 8, azimuth_dec = 2
gauss_400 2 4 (1 2)
making amplitudes...
filtering interferogram...
conv [ERROR]: File real.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real.grd=bf
conv [ERROR]: File real_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real_tmp.grd=bf
conv [ERROR]: File imag.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag.grd=bf
conv [ERROR]: File imag_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag_tmp.grd=bf
making amplitude...
grdmath [ERROR]: Syntax error: realfilt.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
grdinfo [ERROR]: Error for input file: No such file (display_amp.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grd2cpt [ERROR]: Error for input file: No such file (display_amp.grd)
grd2cpt [ERROR]: Syntax error -L option: Cannot decode limits
grd2cpt [ERROR]: Syntax error -L option: min_limit must be less than max_limit.
grdimage [ERROR]: Error for input file: No such file (display_amp.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse display_amp.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
        -R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
          Append r if giving lower left and upper right coordinates
        -Rg or -Rd for global domain
        -R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rdisplay_amp.grd
psconvert [ERROR]: The file display_amp.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making correlation...
grdmath [ERROR]: Syntax error: amp.grd is not a number, operator or file name
conv [ERROR]: File tmp2.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  tmp2.grd=bf
grdimage [ERROR]: Error for input file: No such file (corr.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse corr.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
        -R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
          Append r if giving lower left and upper right coordinates
        -Rg or -Rd for global domain
        -R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rcorr.grd
psconvert [ERROR]: The file corr.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making phase...
grdmath [ERROR]: Syntax error: imagfilt.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phase.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phase.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
        -R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
          Append r if giving lower left and upper right coordinates
        -Rg or -Rd for global domain
        -R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphase.grd
psconvert [ERROR]: The file phase.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
filtering phase...
phasefilt [ERROR]: File imagfilt.grd not found
[Session phasefilt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 error reading file imagfilt.grd
grdedit [ERROR]: Error for input file: No such file (filtphase.grd)
grdmath [ERROR]: Syntax error: filtphase.grd is not a number, operator or file name
grdimage [ERROR]: Error for input file: No such file (phasefilt.grd)
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
psscale [ERROR]: Could not parse phasefilt.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
        -R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
          Append r if giving lower left and upper right coordinates
        -Rg or -Rd for global domain
        -R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Rphasefilt.grd
psconvert [ERROR]: The file phasefilt.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
INTF.CSH, FILTER.CSH - END

SNAPHU.CSH - START
threshold_snaphu: 0.05
grdmath [ERROR]: Syntax error: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: mask2_patch.grd is not a number, operator or file name
grd2xyz [ERROR]: File phase_patch.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
grd2xyz [ERROR]: File corr_tmp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
unwrapping phase with snaphu - higher threshold for faster unwrapping
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files

snaphu v2.0.4
32 parameters input from file /usr/local/GMTSAR/share/gmtsar/snaphu/config/snaphu.conf.brief (297 lines total)
not enough input arguments.  type snaphu -h for help
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
xyz2grd [ERROR]: Error for input file: No such file (unwrap.out)
xyz2grd [ERROR]: Syntax error: Must specify -R option
xyz2grd [ERROR]: Syntax error -I option: Must specify positive increment(s)
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
xyz2grd [ERROR]: Error for input file: No such file (conncomp.out)
xyz2grd [ERROR]: Syntax error: Must specify -R option
xyz2grd [ERROR]: Syntax error -I option: Must specify positive increment(s)
grdmath [ERROR]: Syntax error: tmp.grd is not a number, operator or file name
mv: cannot stat 'tmp.grd': No such file or directory
grdgradient [ERROR]: Error for input file: No such file (unwrap.grd)
grdgradient [ERROR]: Syntax error: Must specify input file
grdinfo [ERROR]: Error for input file: No such file (unwrap.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
makecpt [ERROR]: Syntax error -T: Must specify valid min[/max[/inc[<unit>|+n]]] option
grdimage [ERROR]: Error for input file: No such file (unwrap.grd)
grdimage [ERROR]: Syntax error -I: Requires a valid grid file or a constant
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
grdimage [ERROR]: Syntax error -I option: Must specify intensity file, value, or modifiers
psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
        -R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
          Append r if giving lower left and upper right coordinates
        -Rg or -Rd for global domain
        -R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Runwrap.grd
psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
Unwrapped phase map: unwrap.pdf
SNAPHU.CSH - END

GEOCODE.CSH - START
SKIP GEOCODING
`

**Comment by geodesico** [comment]
I am using S1 data and cut a small patch. The processing is on the iw3 segment.

**Comment by Xiaohua-Eric-Xu** [comment]
Do you have the log of step 3, i.e. when running dem2topo_ra.csh? Maybe there is an error producing topo_ra.grd?

**Comment by geodesico** [comment]
Unfortunately, I don't have any log of the processing. I have not run dem2topo_ra.csh manually. I guess it has been run as a built-in command in one of the following steps I have been through. The stages and commands I used:

1- using the pins, I applied "organize_files_tops_linux.csh" and cut the data, then moved the iw3 to raw_orig.
2- prep_data_linux.csh
3- preproc_batch_tops.csh data.in dem.grd 1 (the supermaster was selected and moved to the top of data.in)
4- preproc_batch_tops.csh data.in dem.grd 2
5- get_baseline_table.csh prmlist S1_20200920_ALL_F3.PRM
6- select_pairs.csh baseline_table.dat 60 150 (intf.in was edited to add more pairs)
7- wc -l intf.in
8- intf_tops.csh intf.in batch_tops.config (here the error appears)

**Comment by Xiaohua-Eric-Xu** [comment]
Hmm, feels like you may have started with step 2. Could you check your batch_tops.config, i.e., `proc_stage = `? Or just send your batch_tops.config file.

**Comment by geodesico** [comment]
Yes. You are correct. In the batch_tops.config the `proc_stage = 2`

**Comment by geodesico** [comment]
But, I think it has been set firstly as 1, and then updated automatically to 2

**Comment by geodesico** [comment]
I just figured out the reason for this issue. Most likely, I have linked dem.grd in a topo folder in the upper directory. i.e, `ln -s ../../topo/dem.grd .` instead of `ln -s ../topo/dem.grd .` 
since the topo folder was in the upper directory, I got the error, and the `proc_stage = ` has been updated from 1 to 2

**Comment by Xiaohua-Eric-Xu** [comment]
In that case, correct your link, and the set proc_stage = 1. Re-run intf_tops.csh and make sure topo_ra.grd is generated before it enters the stage of generating interferograms.

**Comment by cyloveyou** [comment]
I also encountered this problem, I tried everything you guys said, but still not solved, I would like to ask how you finally solved it, thank you very much!

**Comment by Xiaohua-Eric-Xu** [comment]
Please open a new issue and describe what you did in details.
