### ISSUE TITLE
Problems using Areas of Interest (AOIs/ROIs) smaller than one sub-swath for Sentinel-1 TOPS.

### ISSUE THREAD

**Issue by davidbernat** [gmtsar/gmtsar#62]
Hi Xiaohua,

Got GMTSAR up and running nicely. It's a great package. 

I'm optimizing now by using region_cut as much as possible from a user chosen lat-lon set of polygon bounds.

`proj_ra2ll_ascii` requires the trans.dat file.But trans.dat is created within `dem2topo_ra.csh` on its call of `line 95` of `intf_tops.csh`. The setup to that call actually accepts `region_cut` as an input, the inclusion of which would speed up processing a lot. But how can I get lat-lon into the ra coordinates of `region_cut` earlier than this call? Otherwise how do I make the conversion before this step?

Thanks!

**Comment by Xiaohua-Eric-Xu** [comment]
Hi David,
If you get longitude, latitude and elevation (m above ellipsoid), you could use SAT_llt2rat to convert the coordinates to range, azimuth and elevation (above local ref radius). Basically, trans.dat is computing this.
Cheers,
Xiaohua(Eric)

**Comment by davidbernat** [comment]
Hi Eric,

That makes sense. More broadly, however, this is in pursuit of a more
categorical feature. The user provides a lat-long boundary at the
initiation of the process and wants to minimize the processing.

The dem file can be generated for the minimal necessary boundary, so that
is set.

Translating lat-long to ra suffers from several geometric considerations
that limit its ease. For instance, even with trans.dat, setting the four
lat-long corners of the boundary can cause ll2ra_ascii to fail to convert
several of the points because of how it constructs its conversation map at
the onset of the process. This is because the azimuthal axis does not align
with the latitude or longitude (not surprisingly) and so two coordinates
fall outside of its construction map.  I remedy this by feeding two sets of
coordinates into the process, the desired boundaries and a second set of
coordinates from a boundary which is larger and encompasses the desired
boundaries. This works, though because of its ad hoc nature could fail. A
complete solution would require considering the geometry of the orbit.

Using SAT_llt2rat would seem to have a similar issue. I can use the dem
file to get elevation. Technically, SAT_llt2rat should be run on the
master.PRM. But preproc_batch_tops mode=1 is required before selecting the
master.PRM. But preproc_batch_tops is itself a slow process, and could be
sped up by performing the process only on the region of interest. For
Sentinel TOPS, which does not use xcorr to do co-registration this is
especially true. Correct?

After preproc_batch_tops mode=1, a master.PRM will have been chosen and a
conversation can be made. Even still, it seems like the ambiguity of
elevation is somewhat indeterminate. A higher or lower elevation at the
boundaries will change the transformation. Would it make sense to make the
calculation for a range of elevations for each lat-long (such as the
highest and lowest elevation of the region), and use the largest possible
range-azimuth boundaries? To make the system most failsafe.

Thanks!

**Comment by Xiaohua-Eric-Xu** [comment]
Hi David,
I am not sure what you mean there is an issue. The dem has to be decently larger than the dataset and I don't understand why the conversion will fail. The lon lat corners do not really make a box in radar coordinates. Here's how I usually do:
`cat lon_lat.txt | gmt grdtrack -Gdem.grd | SAT_llt2rat master.PRM 1`
I think for a smaller region of interest, one could run the organize_files_tops[_linux].csh to re-assemble the data first. And defining which bursts will cover the AOI is not hard. e.g. for descending cases, use NE and SW corner of your box as pins to feed the script will probably work.
Xiaohua

Also: the two lines probably can't be done as one as later a 3 column table is needed by surface. You could `|` though.

**Comment by davidbernat** [comment]
Hi Eric,

Thanks, let me explain.

The radar coordinates produced for the lon-lat region of interest will be
slightly different for each PRM, including for each of the three master.PRM
files for the TOPS bursts.
Furthermore, if the conversion is done before a master is chosen, using
SAT_llt2rat, the answer is dependent on elevation.

When I said indeterminate, I meant in the mathematics sense, in that
multiple output values are possible; i.e., there is no one 'correct'
solution. For small regions of interest, I could imagine the radar
coordinates of one conversation won't be appropriate for another, and,
therefore could be problematic.

Here's a great example:
I have 7 .SAFE observations for a small region of interest (about 0.02 x
0.02 in lon-lat size at latitude 30 degrees).

Running preproc_batch_tops.csh (which iterates over the 7 observations)
fails for 6 of the 7 operations for F1, indicating that for 6 of the 7
bursts, the region of interest is outside the burst, but for 1 of the 7,
the region of interest is inside the burst. This edge case arises because
radar coordinates are different for each orbit, and it so happens that the
region of interest only is within F1 bursts once. Fine. But that is an
example of what I mean by indeterminate.

Question 1: I can run preproc_batch_tops.csh and detect this case by
iterating through the .SLC files it creates and seeing that 6 out of 7 are
of size zero bytes; and one is several hundred MB.

Question 2: File size seems large, considering the small size. My hunch is
that the SLC file is only cut along azimuth coordinates, and not truncated
in range. Any way to change this?

Continuing the example: preproc_batch_tops.csh produces 7 out of 7
non-trivial SLC files for F2 and F3. Great.

Question 3: In a moment, I will run intf_tops.csh using only data from F2
and F3 in the intf.in file. I looked over the code and this should work.
What do you expect?

Question 4: Regarding F1, let's assume 2 out of 7 SLC files were formed,
but neither is the master chosen for F2 and F3. Can I process this baseline
using a different master, without affecting the later quality of the merge
and creation of interferograms?

Thanks! I will pay you back some how.

**Comment by Xiaohua-Eric-Xu** [comment]
OK, I am still a bit confused, as these things you mentioned were never a problem for me. How come that your AOI is covered by acquisitions from some dates but not others? If it's missing data, we can't help in any sense. If you meant that SAFE files have inconsistent bursts, try organize_files_tops.csh to re-assemble your own SAFE files. There is a cut_slc program but only works when you already have a SLC. We currently do not have a program that will cut the tiff files directly. You need to specify a common master image for all subswaths.

**Comment by davidbernat** [comment]
Are you saying that under no circumstances would an AOI be in one burst at
time1, and not necessarily be in that same burst at time2?

If so, somehow my data was corrupted...

**Comment by Xiaohua-Eric-Xu** [comment]
Not sure I understand you correctly. Sentinel-1 is very well coregistered, if in any case, the area belongs to two different burst, the squint angle along azimuth will make everything decorrelate.  Here, for the same burst, I mean they cover the same area, not having the sequential count in a tiff file, as the Sentinel-1 data contain inconsistent number of bursts all the time.

**Comment by davidbernat** [comment]
Let me describe it this way:

The Sentinel .SAFE data is decomposed into 3 processing sub-swaths,
processed independently in (default) directories F1, F2, F3, then merged.
Each of these three sub-swaths observe different (though slightly
overlapping) regions of the Earth. When I have an AOI which is smaller than
the .SAFE region, that AOI will fall within one, two, or three of those
sub-swaths.

What you are saying is that the co-registration of those sub-swaths are
very accurate for Sentinel-1, and therefore, when that region is observed
again and again at different times, the footprint of each of those
sub-swaths should be identical.

Therefore, if any AOI falls within a sub-swath at a particular time, then
it should be expected to fall within that sub-swath at all subsequent
observations.

Now that I write that out, yes, that is what I expect as well. So, the fact
that the AOI was found within sub-swath 1 of my .SAFE data at one epoch,
but not at the other epochs, means that something went wrong. Either the
.SAFE data was corrupted, or the software ran through a sequence of
processing steps different than what I understand. OK. Makes sense. Will
debug.

**Comment by davidbernat** [comment]
Hm. There is something in preproc_batch_tops.csh that will create a
non-empty SLC file for the chosen master image (the first line of data.in),
even if the AOI is not within that sub-swath. All the other SLC files will
be zero bytes. But the master image SLC will be non-zero.

I have looked through the code. But I am not able to find where in the code
this file is created.

**Comment by Xiaohua-Eric-Xu** [comment]
Here are a few things to check. 1) open *.SAFE/preview/map-overlay.kml files and make sure for each date, there are enough data that cover your AOI. 2) make sure you have the correct data.in file. 3) attach your log when you run the script.

**Comment by davidbernat** [comment]
Hi Eric,

1. The .SAFE files are correct. The AOI is firmly within sub-swaths 2 and 3. The code operates as expected for sub-swaths 2 and 3. For sub-swath 1, however, a non-empty .SLC file is created by `preproc_batch_tops.csh` for the one date which is chosen as the master. Somewhere within `preproc_batch_tops.csh` and the way the code treats the master differently, a different outcome is being made when that code is run with `mode=2`.

It is not a blocker. But it does create an unexpected outcome for the user.

Here is the `data.in` file. The date `20200113` is chosen as master.
<img width="1021" alt="Screen Shot 2020-11-03 at 5 49 38 PM" src="https://user-images.githubusercontent.com/5396131/98049096-08699280-1dfd-11eb-83e0-ed7d9bb9ba63.png">

Here is the log of `preproc_batch_tops.csh` `mode=2`. To reiterate, the AOI is *not* inside this subswath. The failures to find points within the region are expected.
[log.txt](https://github.com/gmtsar/gmtsar/files/5484493/log.txt)

However, here you can see that the .SLC related to the master is not of size zero bytes, though the others are.
<img width="551" alt="Screen Shot 2020-11-03 at 5 49 04 PM" src="https://user-images.githubusercontent.com/5396131/98049208-3b138b00-1dfd-11eb-9a4a-8efd492e4221.png">

**Comment by Xiaohua-Eric-Xu** [comment]
Here's the key error:
INFO:utils.subprocess:[48519-0][17:44:57][00010]:blockmedian [WARNING]: No data records found; no output produced
Probably your dem does not cover F1 at all. Thus no coregistration grids will be generated and thus SLCs won't be generated properly.

**Comment by davidbernat** [comment]
The `dem.grd` does not cover F1 at all. That is because the AOI is not
within F1. So that is expected. +1

But, to be clear, a user would expect no .SLCs would be created for F1,
right? But, there is one, for the master.

**Comment by Xiaohua-Eric-Xu** [comment]
The master image does not need to be coregistered as its the reference for all the rest. So it does not need elevation info.

**Comment by davidbernat** [comment]
Perfect. Thank you. Makes sense now. Case closed.
