### ISSUE TITLE
[Help]: Range and Azimuth to Asc and dec for Barren land without terrain.

### ISSUE THREAD

**Issue by Obaida777** [gmtsar/gmtsar#621]
Dear All 
@Xiaohua-Eric-Xu @chintals @kguns32 

My Study Area is Barren land without terrain so what are the best parameters Number for Range and Azimuth to use in config file.

Best Regards

**Comment by Xiaohua-Eric-Xu** [comment]
Do you mean the decimation factor? i.e. range_dec and azimuth_dec. For TOPS data, the default is 8 and 2 I think. The choice of decimation factor really depends on what signal you are targeting.

**Comment by Obaida777** [comment]
Dr.@Xiaohua-Eric-Xu Thank you for responding. 

decimation factor yes that what i meant,the signal for substance/IW/SLC/VV. So what is the best decimation factor for it?

**Comment by Xiaohua-Eric-Xu** [comment]
Then I would just use the default 8/2 unless the subsidence you are looking at are associated with infrastructures or your AOI is very small.

**Comment by Obaida777** [comment]
@Xiaohua-Eric-Xu thank you for your reply.
