### ISSUE TITLE
SBAS time consuming

### ISSUE THREAD

**Issue by AmiraZakii** [gmtsar/gmtsar#623]
Hello,
I tried SBAS before with 125 interferograms and it takes hours to finish. Is it usual for SBAS analysis to take a very long time if the interferogram number increased? longer than five days and still in the first step? The number of interferograms is 558, and the number of images is 158. Is this normal, or did I do something wrong?
![1](https://user-images.githubusercontent.com/89259389/214880220-ea22941d-9134-428e-967d-541338247af7.JPG)
![2](https://user-images.githubusercontent.com/89259389/214880237-7d8f8411-baad-4a1e-abf3-9d0781dce1ab.JPG)

**Comment by Xiaohua-Eric-Xu** [comment]
The time-cost is not linear with number of interferograms. This is due to the fact that the size of Green's matrix is N x M, which is the product of number of acquisitions and number of interferograms. I would recommend to use sbas_parallel.c to speed up the solution, as sbas.c is a single core program.

**Comment by cxinlong** [comment]
Hello, May I ask you how many days did you run this step to get the result？ @AmiraZakii

**Comment by Xiaohua-Eric-Xu** [comment]
> Hi~ I am doing SBAS analysis. While my study area is small， Do I need to cut off the study area data for interference or do the whole F1、F2、F3 subswath？ It looks like one F1/intf_all/2019003_2019015 folder size is 1.2-1.5GB.(same as F2、F3)，one merge/2019003_2019015 folder size is 1.5-1.8GB. The size of the storage space depends on the number of interferograms.When I do 81 interferograms about（1.2GB*3+1.5GB）*81=243GB .It seems i need at least 250GB on my computer？

The merge/intf directory will contain lots of other files I assume. When you run sbas, there will be a line popping out to terminal telling how much memory is expected to be used.
