### ISSUE TITLE
[Help]: convert

### ISSUE THREAD

**Issue by steveen9** [gmtsar/gmtsar#624]
Hello all
How can I convert cpt file to svg file?

**Comment by Xiaohua-Eric-Xu** [comment]
www.converthelper.net/cpt-to-svg

**Comment by steveen9** [comment]
This website can't convert from cpt to svg I want to convert phasefilt in order to open it in qgis

**Comment by Xiaohua-Eric-Xu** [comment]
I guess what you meant is to convert netcdf to svg? If your purpose is to view a netcdf file in QGIS, maybe this is what you need? https://ereefs.aims.gov.au/ereefs-aims/help/how-to-open-a-NetCDF-file-with-ArcMap-and-QGIS
