### ISSUE TITLE
[Help]: DEM resolution

### ISSUE THREAD

**Issue by Yaoshangheng** [gmtsar/gmtsar#625]
How should I choose DEM resolution when I do D-InSAR calculation？
What is the different between 30 m resolution and 90 m resolution？
Download DEM data from：https://topex.ucsd.edu/gmtsar/demgen/

**Comment by Xiaohua-Eric-Xu** [comment]
It depends on your target resolution. If you are looking at very high-resolution deformation/topography, then use 30-m or even better DEM may give you better topographic correction. However, if you are looking at km level deformation field, there's no reason to use very high-resolution dem as the results are probably the same after filtering.

**Comment by Yaoshangheng** [comment]
Thanks proffesor
