### ISSUE TITLE
[Feature]: Check whether the F1/F2 folder can be deleted？

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#627]
Hi,dear professors,
I'd like to ask you a question. After merging F1 and F2 strips, I obtain the merge folder, and then unwrap the merge folder. Then can I delete my F1 and F2 folders? Will it affect my subsequent operations? The whole process takes place on your hard drive, but because you're running out of space and memory, consider deleting some of the folders you don't need.
![image](https://user-images.githubusercontent.com/114629377/216799084-9e2dfe79-5d86-437f-8b8e-e201d97d4f31.png)

**Comment by Xiaohua-Eric-Xu** [comment]
If you are sure that the merged product are exactly what you need for building a time-series, then yes you can. I would usually keep them until I am satisfied with the time-series though.

**Comment by Luvina0503** [comment]
OK.thank you

**Comment by chintals** [comment]
Prior to deleting the F* folders, I would make a copy of baseline_table.dat, intf.in (if you haven't run sbas or if you plan on re-running sbas) and baseline.ps plot to keep a visual of your sbas network

**Comment by chintals** [comment]
If space is an issue, you can also delete the data folder, if you have passed the image alignment step or after merge is complete

**Comment by Luvina0503** [comment]
ok.Thank you!
