### ISSUE TITLE
Best practices for consistent range-azimuth coordinates throughout GMTSAR

### ISSUE THREAD

**Issue by davidbernat** [gmtsar/gmtsar#63]
Hi Eric,

I noticed crashing the code various points by trying to configure the system with a user defined long-lat AOI at the process onset. There are times the code self-determines its region to process by using the boundaries of the dem.grd file. There are other times when using `proj_ll2ra` and master.PRM fails to convert from long-lat to ra because of particulars of the GMT code which uses. There is also a crash point in `intf_tops`. I am hoping this thread can resolve those dis-similarities in one place, and may be useful for people who arrive here by Googling. I haven't found a single point reference yet, so if you already wrote one, I would love to read it.

_In `intf_tops`: Here is the scenario._
I used `make_dem` to generate a `dem.grd` file with an AOI bounding box in long-lat space. Works great, small size. The small size of `dem.grd` makes other processing points, which use `dem.grd` for their de-facto AOI, more efficient. `preproc_batch_tops` is one such case, so I would like to keep `dem.grd` as small as possible.

Prior to running `intf_tops` I am using `master.PRM` to convert from long-lat-height to r-a-elevation to set `region_cut` to `rMAX/rMIN/aMAX/aMIN`. Makes sense. Those two values (height and elevation) are, I believe, different quantities, although they are sometimes used interchangeable as 'elevation.'

To get long-lat-height, I open the netcdf4 file and read the closest elevation points. For concreteness, here is what I have, which I put in a file `lle.txt`:
```
30.717581 30.091516 129.37167
31.117581 30.091516 30.911259
31.117581 30.391516 22.616167
30.717581 30.391516 49.873413
30.717581 30.091516 129.37167
```
The command:
`cat lle.txt | gmt grdtrack -G../topo/dem.grd  | SAT_llt2rat S1_20200113_ALL_F1.PRM 1`

Fails:
```
54210.901230165 3466.555587731 -138.028632024 30.717581000 30.091516000 
interpolation point outside of data constraints, 1030636.587159 1050652.000000 1050822.000000
```

If instead, I get rid of elevation (remove the third column from `lle.txt`), the process works:
```
54210.790707148 3466.555554090 -137.672768546 30.717581000 30.091516000 
43206.379926507 2989.260343394 -236.311084104 31.117581000 30.091516000 
44873.463087962 639.860798956 -340.916913769 31.117581000 30.391516000 
55933.363914814 1113.649997656 -314.108668286 30.717581000 30.391516000 
54210.790707148 3466.555554090 -137.672768546 30.717581000 30.091516000 
``` 

Q: I assume this is because by using elevation I am somehow projecting just a little bit out of bounds of what was truncated out of the `master.PRM` file. Though this is speculation.  Do you know the cause?

------------------------------------------------------

While running `intf_tops` I now get an error when `region_cut` is used to `slc_cut` the `master.PRM` file.
Using `region_cut = 43206.379926507/55933.363914814/639.860798956/3466.55555409` the code fails on Line 95 of `intf_tops`: `cut_slc master.PRM junk $region_cut 1`

This failure is related to the question above, since within using elevation, the lon-lat are being transformed to r-a coordinates that are outside the truncated `master.PRM` file. So this solution should be solved when the conversion above is solved, right?

**Comment by Xiaohua-Eric-Xu** [comment]
I suspect your orbit is not long enough to be interpolated. Make sure you have the right LED file extracted with `ext_orb_s1a` on a precise orbit product.
