### ISSUE TITLE
[Help]: merge_batch.csh

### ISSUE THREAD

**Issue by kjz1997** [gmtsar/gmtsar#632]
Hello ,teacher
When I used the "merge_batch. csh" script to splice "IW1, IW2", the script reported an error of "Segmentation fault (core dumped)"
Code:
`merge_batch.csh merge_list batch_tops.config `
![image](https://user-images.githubusercontent.com/89446964/218241550-43b7d015-9033-4264-a518-07209e55660b.png)
File:
The suffix of the file is "txt" added to meet the upload format
[merge_list.txt](https://github.com/gmtsar/gmtsar/files/10712664/merge_list.txt)
[batch_tops.config.txt](https://github.com/gmtsar/gmtsar/files/10712668/batch_tops.config.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
I guess you need to delete the `,::` at the end of each line. You don't have F3 to be merged so there shouldn't be a third column.

**Comment by kjz1997** [comment]
Thank you, it works.
Sorry, I just checked. I entered the mode incorrectly
