### ISSUE TITLE
[Help]: coseismic deformation of the 2023 Turkey-Syria earthquake

### ISSUE THREAD

**Issue by Xiongwei789** [gmtsar/gmtsar#633]
Hello everyone,
Dose anyone use Sentinel-1 data to obtain the coseismic deformation of the 2023 Turkey-Syria earthquake?
I encountered some problems, when I perform it with GMTSAR.
It seems caused by data?
![12](https://user-images.githubusercontent.com/92964720/218293842-5bfe6cc8-2d2f-4cd5-8c1f-4f4dccc2f2b3.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Yes. ESA somehow added a few empty lines to the orbit file and thus caused some problem to the xml lib in GMTSAR. I've made an update to fix that (see here https://github.com/gmtsar/gmtsar/discussions/629 and 19470ecd0ade4e47d9e8b453eea4af7b4a73ccb1). Just update the code, and recompile. The problem should be gone.

**Comment by Xiongwei789** [comment]
Thank you. It worked.
