### ISSUE TITLE
[Bug]: Error "Not an well formatted XML file...-1, -1" for valid XML files

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#636]
Tools compiled with S1A_preproc/lib/xml.c do not work for valid XML orbit files including empty lines:

```
ext_orb_s1a \
    S1_20230210_033427_F1.PRM \
    S1A_OPER_AUX_RESORB_OPOD_20230210T065503_V20230210T025531_20230210T061301.EOF \
    S1_20230210_033427_F1

Not an well formatted XML file...-1, -1
Unable to find designated string...after 0 searches..
...
```

Please pay attention the new orbit files include empty lines and header definition line is changed too.

P.S. That's not safe to use some internal xml parsing library due to extremely complicated formatting and unicode rules.

**Comment by Viecgg** [comment]
Could this issue be fixed? I just encounterd same problem so that I can't do my interferogram correctly.

**Comment by Xiaohua-Eric-Xu** [comment]
> P.S. That's not safe to use some internal xml parsing library due to extremely complicated formatting and unicode rules.

All things come with a cost. Personally I think it's a choice of whether you prefer things being a bit more robust or something less but under your own control. Like for this bug, I got the someone telling me it failed in the morning, and 10 min later the update can be made to get things running. If the same thing happens to an external lib, it will be much more complicated, unless someone can guarantee external libs never fail.

**Comment by mobigroup** [comment]
> Personally I think it's a choice of whether you prefer things being a bit more robust or something less but under your own control.

Ah, sorry, it’s hard to understand to me! You use weird GMT codes like to tension surfaces processing based on invalid concepts for the most important tasks but spend your time for the text parsing library…

And thanks for the fix of course.

**Comment by Xiaohua-Eric-Xu** [comment]
> Ah, sorry, it’s hard to understand to me! You use weird GMT codes like to tension surfaces processing based on invalid concepts for the most important tasks but spend your time for the text parsing library…
> 
> 

You may know that we work closely with the GMT folks on implementing stuffs, which may include surface, greenspline, grdfill, etc. The surface approach is slow but deals well with terrain overlays or shadowing effects when mapping things to radar coordinates(like you said, most important task). If you need fast back geocoding, there are triangulate options. I am not sure of what invalid concepts you mean, and why you believe surface is a weird code. If you meant the bug that gave wiggles in topo_ra.grd, that's more of an error introduced to Sentinel-1 processing, not so much of surface itself.

**Comment by mobigroup** [comment]
GMT is great visualization software but is not a physically correct one. Physically valid surface requires controlling its derivatives otherwise we have discontinuities (delta functions) and infinite spectrum and infinite power. That’s pain to see GMT processed surfaces spatial spectrums - and that’s impossible to work on the spectrums. The topo_ra.grd issue is just a result of physically invalid approach in this visualization software. Also, some GMT algorithms swapping often and with no check of these correctness by just copy-pasting from internet. I’m really terrified by this code: https://github.com/GenericMappingTools/gmt/blob/master/src/trend2d.c Do you believe to its correctness? I found here some special math functions use non-common edge conditions checks. By the way, the equal Python code in PyGMTSAR is just 50 lines long, and it is straightforward: https://github.com/mobigroup/gmtsar/blob/master/pygmtsar/pygmtsar/PRM.py#L16-L78 It's easy to read and easy to check.

20+ years ago I had been developing math theory and software for arbitrary hologram creation in photopolymers. That’s possible to do on your desktop using ultraviolet light. And my well-checked math equations did not work for the software... just because to quasi-random micron-scale density distribution in the modeling medium. Solidification of the polymer results from growing of nano-scale meshes inside the liquid medium and it requires the correct density distribution for the numerical modeling. 3D Gaussian noise with a spatial scale in microns and dozens of microns created by the software quasi-random generator using limited spectrum on every step resolved the issue and I got successfully the holograms in the software and on practice.

Of course, there are a lot of other examples how pure programming conceptions like to randomly generated density distribution or surfaces with discontinuities of all the scales having infinite spectrum do not work for a physical world numerical modeling. Maybe GMT processing would be well suitable for some planet without atmospheric and water erosion and real ruptures of all the spatial scales but not for the Earth where it is physically impossible. And yes, we have the real issues applying GMTSAR results for spectrum processing and fractality analysis and maching learning pipelines when the spatial spectrum is broken. I see the issues often in my tests and always that's related to GMT results but not to GMTSAR codes itself.
