### ISSUE TITLE
[Help]: GMTSAR tcsh and esarp undefined veriable

### ISSUE THREAD

**Issue by Mubbashra** [gmtsar/gmtsar#638]
I have installed GMTSAR, but when I try to check the tcsh or esarp it says undefined variable. 
Please help me solve the problem. 
![help](https://user-images.githubusercontent.com/48666637/218680747-4e4a446a-fef7-43bc-a0a4-06ea270a5788.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You may need to put GMTSAR/bin to your $PATH in your ~/.bash_profile or ~/.cshrc . And open a new terminal window so it knows the PATH is updated.
