### ISSUE TITLE
[Feature]: ref_point

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#640]
Running GACOS_correction.csh shows this error. I changed several reference points. How to select reference points?
![image](https://user-images.githubusercontent.com/114629377/218986053-abfcdd4d-89e3-40ed-8ddd-7e9ec5a53bae.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I could not see the full log but likely it's because your downloaded GACOS area does not fully cover your radar acquisition.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
So GACOS data must override sentinel data?

**Comment by Xiaohua-Eric-Xu** [comment]
I believe that how the script is written. Or you may cut your data before running GACOS_correction.csh

**Comment by Luvina0503** [comment]
OK.i will try.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
I found that my GACOS data overrides radar data.

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what you mean. GACOS is a correction so will be subtracted or added to your unwrapped data through that script I think. It will not overwrite your data.

**Comment by Luvina0503** [comment]
I'm going to do GACOS correction first and then unwrap

**Comment by Luvina0503** [comment]
And the unwrap.grd file is not used in GACOS_correction.csh and operation.csh

**Comment by Luvina0503** [comment]
@esrivas17 
I see you updated your code with phasefilt.grd data in red. Can I interpret it this way: do GACOS correction first and then unwrap the correction result?
![image](https://user-images.githubusercontent.com/114629377/219053368-c6c85e49-53c4-47d7-bd1b-d4021bfdfe4f.png)

**Comment by esrivas17** [comment]
> @esrivas17 I see you updated your code with phasefilt.grd data in red. Can I interpret it this way: do GACOS correction first and then unwrap the correction result? ![image](https://user-images.githubusercontent.com/114629377/219053368-c6c85e49-53c4-47d7-bd1b-d4021bfdfe4f.png)

Hi, 
Yes, I tried to stick to the matlab example you find in the GACOS website.
And I think applying GACOS after unwrapping wouldn't work.

**Comment by esrivas17** [comment]
Just for the record, the script does not overwrite any file created by GMTSAR. 
At the end you would need to take the wrapped-GACOS-corrected-phase files to do the unwrapping and then the time series inversion

**Comment by Luvina0503** [comment]
@esrivas17 
I would like to ask you a question.
Command:
root@gmt:/media/gmt/Elements/Work/69109/merge# GACOS_correction.csh intflist /media/gmt/Elements/Work/69109/gacosdata/ /media/gmt/Elements/Work/69109/F2/topo/ ref_point 36.47
surface: Provides 3, expects 3-column binary data
surface: Grid domain: W: 116.999999995 E: 120.916666662 S: 33.333333332 N: 35.9999999986 n_columns: 4700 n_rows: 3200 [gridline registration]
surface: Processing input table data
surface: Input 3 columns via binary records using format fff
surface: Minimum value of your dataset x,y,z at: surface: 118.373336792 35.124168396 -9.9909954071
surface: Maximum value of your dataset x,y,z at: surface: 119.600830078 34.2924995422 25569.9960938
surface: LS plane determined: z = -43378.4 + (20.3626 * col) + (4.40879 * row)
surface: Grid	Mode	Iteration	Max Change	Conv Limit	Total Iterations
surface:  100	D	    6874	0.000119560033189	0.000121079547312	      6874
surface:   20	I	      71	0.000582684135835	0.000605397736558	      6945
surface:   20	D	   10000	0.00213187326639	0.000605397736558	     16945
surface:    4	I	      55	0.00289469995658	0.00302698868279	     17000
surface:    4	D	    1594	0.00302436365454	0.00302698868279	     18594
surface:    2	I	      16	0.00517012945997	0.00605397736558	     18610
surface:    2	D	     285	0.00605041125305	0.00605397736558	     18895
surface:    1	I	      13	0.0100817734963	0.0121079547312	     18908
surface:    1	D	     127	0.0120048376908	0.0121079547312	     19035
surface: Fit info: N data points  N nodes	mean error	rms error	curvature
surface: 	 1991797	15047901	0	0	3554.08804127
surface: Provides 3, expects 3-column binary data
surface: Grid domain: W: 116.999999995 E: 120.916666662 S: 33.333333332 N: 35.9999999986 n_columns: 4700 n_rows: 3200 [gridline registration]
surface: Processing input table data
surface: Input 3 columns via binary records using format fff
surface: Minimum value of your dataset x,y,z at: surface: 118.745834351 33.9500007629 -19.9934482574
surface: Maximum value of your dataset x,y,z at: surface: 118.329170227 35.3300018311 11262.7626953
surface: LS plane determined: z = -2853.34 + (-0.956872 * col) + (6.52866 * row)
surface: Grid	Mode	Iteration	Max Change	Conv Limit	Total Iterations
surface:  100	D	    6432	3.07432701012e-06	3.20364275295e-06	      6432
surface:   20	I	      91	1.53716350577e-05	1.60182137648e-05	      6523
surface:   20	D	   10000	0.00073489782208	1.60182137648e-05	     16523
surface:    4	I	      58	7.95315031145e-05	8.00910688238e-05	     16581
surface:    4	D	    2000	0.000153560406436	8.00910688238e-05	     18581
surface:    2	I	      11	0.000149439026024	0.000160182137648	     18592
surface:    2	D	     230	0.000159419449948	0.000160182137648	     18822
surface:    1	I	       9	0.000195063821091	0.000320364275295	     18831
surface:    1	D	      75	0.000320220119275	0.000320364275295	     18906
surface: Fit info: N data points  N nodes	mean error	rms error	curvature
surface: 	 1991797	15047901	0	0	1239.99241806
grdsample: Error: Selected region exceeds the X-boundaries of the grid file by more than one x-increment!
grdtrack: Error for input file: No such file (resample_zpddm.grd)
grdtrack: Syntax error: Must specify -G at least once
grdmath: Syntax error: resample_zpddm.grd is not a number, operator or file name
Problems with the reference point. Is the reference point within the AOI?
ln: 无法创建符号链接'./trans.dat': 文件已存在
^C
root@gmt:/media/gmt/Elements/Work/69109/merge# cd ../merge1

What causes this? I changed multiple reference points and still reported the same error

**Comment by Luvina0503** [comment]
@esrivas17 

![image](https://user-images.githubusercontent.com/114629377/219062127-2725206e-f599-4005-82b9-610563d77013.png)

Looking forward to receiving your reply.thank you

**Comment by esrivas17** [comment]
> @esrivas17 Then when I unwrap, I should use the corrected grd file in red, not phasefilt.grd. Because it's already corrected in GACOS
> 
> ![image](https://user-images.githubusercontent.com/114629377/219060405-194a3eef-2a8d-4a06-9238-e813275f6f4e.png)

yes, you shouldn't take the phasefilt.grd's 
I think there is another way to unwrap a stack of interferograms.
you can find it in the Sentinel-1 time series manual for GMTSAR

**Comment by Luvina0503** [comment]
@esrivas17 
The snaphu.csh script is used in Sentinel-1 time series manual for GMTSAR, but you should also need to replace the phasefilt.grd with a corrected grd. There is no mention of GACOS correction in Sentinel-1 time series manual for GMTSAR, so it uses phasefilt.grd directly.

![image](https://user-images.githubusercontent.com/114629377/219063892-0416d9d5-dec2-4632-85e7-af7a18827032.png)
![image](https://user-images.githubusercontent.com/114629377/219064070-e0063354-ef86-40fd-8c3d-50cfa50c5295.png)

**Comment by esrivas17** [comment]
mmm not sure, 
may you share the value of you reference point and the: gmt grdinfo 

> @esrivas17 I would like to ask you a question. Command: root@gmt:/media/gmt/Elements/Work/69109/merge# GACOS_correction.csh intflist /media/gmt/Elements/Work/69109/gacosdata/ /media/gmt/Elements/Work/69109/F2/topo/ ref_point 36.47 surface: Provides 3, expects 3-column binary data surface: Grid domain: W: 116.999999995 E: 120.916666662 S: 33.333333332 N: 35.9999999986 n_columns: 4700 n_rows: 3200 [gridline registration] surface: Processing input table data surface: Input 3 columns via binary records using format fff surface: Minimum value of your dataset x,y,z at: surface: 118.373336792 35.124168396 -9.9909954071 surface: Maximum value of your dataset x,y,z at: surface: 119.600830078 34.2924995422 25569.9960938 surface: LS plane determined: z = -43378.4 + (20.3626 * col) + (4.40879 * row) surface: Grid Mode Iteration Max Change Conv Limit Total Iterations surface: 100 D 6874 0.000119560033189 0.000121079547312 6874 surface: 20 I 71 0.000582684135835 0.000605397736558 6945 surface: 20 D 10000 0.00213187326639 0.000605397736558 16945 surface: 4 I 55 0.00289469995658 0.00302698868279 17000 surface: 4 D 1594 0.00302436365454 0.00302698868279 18594 surface: 2 I 16 0.00517012945997 0.00605397736558 18610 surface: 2 D 285 0.00605041125305 0.00605397736558 18895 surface: 1 I 13 0.0100817734963 0.0121079547312 18908 surface: 1 D 127 0.0120048376908 0.0121079547312 19035 surface: Fit info: N data points N nodes mean error rms error curvature surface: 1991797 15047901 0 0 3554.08804127 surface: Provides 3, expects 3-column binary data surface: Grid domain: W: 116.999999995 E: 120.916666662 S: 33.333333332 N: 35.9999999986 n_columns: 4700 n_rows: 3200 [gridline registration] surface: Processing input table data surface: Input 3 columns via binary records using format fff surface: Minimum value of your dataset x,y,z at: surface: 118.745834351 33.9500007629 -19.9934482574 surface: Maximum value of your dataset x,y,z at: surface: 118.329170227 35.3300018311 11262.7626953 surface: LS plane determined: z = -2853.34 + (-0.956872 * col) + (6.52866 * row) surface: Grid Mode Iteration Max Change Conv Limit Total Iterations surface: 100 D 6432 3.07432701012e-06 3.20364275295e-06 6432 surface: 20 I 91 1.53716350577e-05 1.60182137648e-05 6523 surface: 20 D 10000 0.00073489782208 1.60182137648e-05 16523 surface: 4 I 58 7.95315031145e-05 8.00910688238e-05 16581 surface: 4 D 2000 0.000153560406436 8.00910688238e-05 18581 surface: 2 I 11 0.000149439026024 0.000160182137648 18592 surface: 2 D 230 0.000159419449948 0.000160182137648 18822 surface: 1 I 9 0.000195063821091 0.000320364275295 18831 surface: 1 D 75 0.000320220119275 0.000320364275295 18906 surface: Fit info: N data points N nodes mean error rms error curvature surface: 1991797 15047901 0 0 1239.99241806 grdsample: Error: Selected region exceeds the X-boundaries of the grid file by more than one x-increment! grdtrack: Error for input file: No such file (resample_zpddm.grd) grdtrack: Syntax error: Must specify -G at least once grdmath: Syntax error: resample_zpddm.grd is not a number, operator or file name Problems with the reference point. Is the reference point within the AOI? ln: 无法创建符号链接'./trans.dat': 文件已存在 ^C root@gmt:/media/gmt/Elements/Work/69109/merge# cd ../merge1
> 
> What causes this? I changed multiple reference points and still reported the same error


mmm did you make sure your AOI is within the DEM?
you can take a look at that by running gmt grdinfo dem.grd and gmt grdinfo resample_zpddm.grd
the resample grid must be contained in the dem boundaries.
(if you dont find resample_zpddm.grd in your folder, then go to operation.csh, comment out line 98 and run again, but I think you must have it)

**Comment by esrivas17** [comment]
> @esrivas17 The snaphu.csh script is used in Sentinel-1 time series manual for GMTSAR, but you should also need to replace the phasefilt.grd with a corrected grd. There is no mention of GACOS correction in Sentinel-1 time series manual for GMTSAR, so it uses phasefilt.grd directly.
> 
> ![image](https://user-images.githubusercontent.com/114629377/219063892-0416d9d5-dec2-4632-85e7-af7a18827032.png) ![image](https://user-images.githubusercontent.com/114629377/219064070-e0063354-ef86-40fd-8c3d-50cfa50c5295.png)

yes the GACOS step is not there.
But prob you are right. So editing the code pointing to the right filename should work

**Comment by Luvina0503** [comment]
> > @esrivas17 The snaphu.csh script is used in Sentinel-1 time series manual for GMTSAR, but you should also need to replace the phasefilt.grd with a corrected grd. There is no mention of GACOS correction in Sentinel-1 time series manual for GMTSAR, so it uses phasefilt.grd directly.
> > ![image](https://user-images.githubusercontent.com/114629377/219063892-0416d9d5-dec2-4632-85e7-af7a18827032.png) ![image](https://user-images.githubusercontent.com/114629377/219064070-e0063354-ef86-40fd-8c3d-50cfa50c5295.png)
> 
> yes the GACOS step is not there. But prob you are right. So editing the code pointing to the right filename should work

OK.I'll try to run it and see if I get the right result. Thank you

**Comment by Luvina0503** [comment]
> mmm not sure, may you share the value of you reference point and the: gmt grdinfo
> 
> > @esrivas17 I would like to ask you a question. Command: root@gmt:/media/gmt/Elements/Work/69109/merge# GACOS_correction.csh intflist /media/gmt/Elements/Work/69109/gacosdata/ /media/gmt/Elements/Work/69109/F2/topo/ ref_point 36.47 surface: Provides 3, expects 3-column binary data surface: Grid domain: W: 116.999999995 E: 120.916666662 S: 33.333333332 N: 35.9999999986 n_columns: 4700 n_rows: 3200 [gridline registration] surface: Processing input table data surface: Input 3 columns via binary records using format fff surface: Minimum value of your dataset x,y,z at: surface: 118.373336792 35.124168396 -9.9909954071 surface: Maximum value of your dataset x,y,z at: surface: 119.600830078 34.2924995422 25569.9960938 surface: LS plane determined: z = -43378.4 + (20.3626 * col) + (4.40879 * row) surface: Grid Mode Iteration Max Change Conv Limit Total Iterations surface: 100 D 6874 0.000119560033189 0.000121079547312 6874 surface: 20 I 71 0.000582684135835 0.000605397736558 6945 surface: 20 D 10000 0.00213187326639 0.000605397736558 16945 surface: 4 I 55 0.00289469995658 0.00302698868279 17000 surface: 4 D 1594 0.00302436365454 0.00302698868279 18594 surface: 2 I 16 0.00517012945997 0.00605397736558 18610 surface: 2 D 285 0.00605041125305 0.00605397736558 18895 surface: 1 I 13 0.0100817734963 0.0121079547312 18908 surface: 1 D 127 0.0120048376908 0.0121079547312 19035 surface: Fit info: N data points N nodes mean error rms error curvature surface: 1991797 15047901 0 0 3554.08804127 surface: Provides 3, expects 3-column binary data surface: Grid domain: W: 116.999999995 E: 120.916666662 S: 33.333333332 N: 35.9999999986 n_columns: 4700 n_rows: 3200 [gridline registration] surface: Processing input table data surface: Input 3 columns via binary records using format fff surface: Minimum value of your dataset x,y,z at: surface: 118.745834351 33.9500007629 -19.9934482574 surface: Maximum value of your dataset x,y,z at: surface: 118.329170227 35.3300018311 11262.7626953 surface: LS plane determined: z = -2853.34 + (-0.956872 * col) + (6.52866 * row) surface: Grid Mode Iteration Max Change Conv Limit Total Iterations surface: 100 D 6432 3.07432701012e-06 3.20364275295e-06 6432 surface: 20 I 91 1.53716350577e-05 1.60182137648e-05 6523 surface: 20 D 10000 0.00073489782208 1.60182137648e-05 16523 surface: 4 I 58 7.95315031145e-05 8.00910688238e-05 16581 surface: 4 D 2000 0.000153560406436 8.00910688238e-05 18581 surface: 2 I 11 0.000149439026024 0.000160182137648 18592 surface: 2 D 230 0.000159419449948 0.000160182137648 18822 surface: 1 I 9 0.000195063821091 0.000320364275295 18831 surface: 1 D 75 0.000320220119275 0.000320364275295 18906 surface: Fit info: N data points N nodes mean error rms error curvature surface: 1991797 15047901 0 0 1239.99241806 grdsample: Error: Selected region exceeds the X-boundaries of the grid file by more than one x-increment! grdtrack: Error for input file: No such file (resample_zpddm.grd) grdtrack: Syntax error: Must specify -G at least once grdmath: Syntax error: resample_zpddm.grd is not a number, operator or file name Problems with the reference point. Is the reference point within the AOI? ln: 无法创建符号链接'./trans.dat': 文件已存在 ^C root@gmt:/media/gmt/Elements/Work/69109/merge# cd ../merge1
> > What causes this? I changed multiple reference points and still reported the same error
> 
> mmm did you make sure your AOI is within the DEM? you can take a look at that by running gmt grdinfo dem.grd and gmt grdinfo resample_zpddm.grd the resample grid must be contained in the dem boundaries. (if you dont find resample_zpddm.grd in your folder, then go to operation.csh, comment out line 98 and run again, but I think you must have it)

I didn't get the resample_zpddm.grd, only the zpddm.grd.
![image](https://user-images.githubusercontent.com/114629377/219073969-8e8341cd-26f6-4b9e-b9eb-c16b97da0ddc.png)
![image](https://user-images.githubusercontent.com/114629377/219074125-e39eb621-b6ee-4862-a953-94ce741d0307.png)

**Comment by esrivas17** [comment]
yes you right, my bad
may you share the log of: gmt grdinfo dem.grd, gmt grdinfo zpddm.grd, and show your reference point value?

**Comment by Luvina0503** [comment]
@esrivas17 

root@gmt:/media/gmt/Elements/Work/69109/merge/2020191_2020203# gmt grdinfo zpddm.grd
zpddm.grd: Title: Produced by grdmath
zpddm.grd: Command: grdmath date2_ztd.grd date1_ztd.grd SUB = zpddm.grd
zpddm.grd: Remark: 
zpddm.grd: Pixel node registration used [Cartesian grid]
zpddm.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
zpddm.grd: x_min: 117.005339 x_max: 120.834505651 x_inc: 0.00083333333 name: x n_columns: 4595
zpddm.grd: y_min: 33.3676603439 y_max: 35.996827 y_inc: 0.00083333333 name: y n_rows: 3155
zpddm.grd: z_min: -0.0897119045258 z_max: 0.232968568802 name: z
zpddm.grd: scale_factor: 1 add_offset: 0
zpddm.grd: format: netCDF-4 chunk_size: 132,132 shuffle: on deflation_level: 3
root@gmt:/media/gmt/Elements/Work/69109/merge/2020191_2020203# gmt grdinfo dem.grd
dem.grd: Title: 44
dem.grd: Command: 
dem.grd: Remark: 
dem.grd: Gridline node registration used [Geographic grid]
dem.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
dem.grd: x_min: 116 x_max: 121.949999998 x_inc: 0.000833333333006 name: longitude coordinate [degrees_east] n_columns: 7141
dem.grd: y_min: 30.7500000018 y_max: 35.33 y_inc: 0.000833333332999 name: latitude coordinate [degrees_north] n_rows: 5497
dem.grd: z_min: NaN z_max: NaN name: 44 [Degree]
dem.grd: scale_factor: 1 add_offset: 0
dem.grd: format: netCDF-4 chunk_size: 256,16 shuffle: off deflation_level: 0
root@gmt:/media/gmt/Elements/Work/69109/merge/2020191_2020203#

![CW%}9_DP64G7N98_DLPCWP7](https://user-images.githubusercontent.com/114629377/219077008-eb79e2e8-ef9e-44b4-90d2-247d35d2669e.png)

**Comment by esrivas17** [comment]
ok it seems that your dem is not large enough.
choose a larger one. making sure that the xmin/ymin is smaller than zpddm.grd and xmax/ymax larger than zpddm.grd
you ref point seems to be ok.

**Comment by Luvina0503** [comment]
@esrivas17 
Since dem.grd was used in the previous intervention and other steps, can I narrow down the GACOS data a bit? Just make sure the research area I need is within that range. Is that OK?

**Comment by esrivas17** [comment]
oh yes right, definitely. the only condition is that the AOI is contained in the DEM.
then just pick an smaller GACOS correction area and it should work as well.

**Comment by Luvina0503** [comment]
@esrivas17 
What is AOI? How do I know if it's in dem.grd?

**Comment by esrivas17** [comment]
> @esrivas17 What is AOI? How do I know if it's in dem.grd?

I mean the Area Of Interest (AOI).
CHoosing a smaller GACOS area should work.

**Comment by Luvina0503** [comment]
@esrivas17 
OK.I see what you mean. I will download the GACOS data again and run it again. Thank you very much for your patient answer

**Comment by esrivas17** [comment]
> @esrivas17 OK.I see what you mean. I will download the GACOS data again and run it again. Thank you very much for your patient answer

No worries, best of luck.

**Comment by Luvina0503** [comment]
> ok it seems that your dem is not large enough. choose a larger one. making sure that the xmin/ymin is smaller than zpddm.grd and xmax/ymax larger than zpddm.grd your ref point seems to be ok.


I re-downloaded the GACOS data, but still reported the same error.

error:
root@gmt:/media/gmt/Elements/Work/69109/merge/2020191_2020203# gmt grdinfo zpddm.grd
zpddm.grd: Title: Produced by grdmath
zpddm.grd: Command: grdmath date2_ztd.grd date1_ztd.grd SUB = zpddm.grd
zpddm.grd: Remark: 
zpddm.grd: Pixel node registration used [Cartesian grid]
zpddm.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
zpddm.grd: x_min: 117.366943 x_max: 120.718609653 x_inc: 0.00083333333 name: x n_columns: 4022
zpddm.grd: y_min: 33.3448780074 y_max: 35.197378 y_inc: 0.00083333333 name: y n_rows: 2223
zpddm.grd: z_min: -0.0827775001526 z_max: 0.259484291077 name: z
zpddm.grd: scale_factor: 1 add_offset: 0
zpddm.grd: format: netCDF-4 chunk_size: 130,131 shuffle: on deflation_level: 3
root@gmt:/media/gmt/Elements/Work/69109/merge/2020191_2020203# gmt grdinfo dem.grd
dem.grd: Title: 44
dem.grd: Command: 
dem.grd: Remark: 
dem.grd: Gridline node registration used [Geographic grid]
dem.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
dem.grd: x_min: 116 x_max: 121.949999998 x_inc: 0.000833333333006 name: longitude coordinate [degrees_east] n_columns: 7141
dem.grd: y_min: 30.7500000018 y_max: 35.33 y_inc: 0.000833333332999 name: latitude coordinate [degrees_north] n_rows: 5497
dem.grd: z_min: NaN z_max: NaN name: 44 [Degree]
dem.grd: scale_factor: 1 add_offset: 0
dem.grd: format: netCDF-4 chunk_size: 256,16 shuffle: off deflation_level: 0
root@gmt:/media/gmt/Elements/Work/69109/merge/2020191_2020203#

![image](https://user-images.githubusercontent.com/114629377/219242690-38b184b2-30c4-4a13-b45f-e12db7732318.png)

**Comment by Luvina0503** [comment]
@esrivas17 
There is a small difference in the content of the error: one is x-increment, one is y-increment.

![image](https://user-images.githubusercontent.com/114629377/219243821-f2abebbd-5427-4b2a-bea7-4e36790fe600.png)

**Comment by Luvina0503** [comment]
@esrivas17 
I used the same GACOS data to process another interference file, which also ran with an error, but it was a little better than the one mentioned above. Because in this interference file the correction results come out. What causes this?
![image](https://user-images.githubusercontent.com/114629377/219272100-5b2259bb-634a-495a-9a47-6c32bdf4cb19.png)
![image](https://user-images.githubusercontent.com/114629377/219272179-e667c77b-1eae-4bb7-8b94-5efe7838abc4.png)

**Comment by Luvina0503** [comment]
zpddm.grd is transformed into zpddm_ra.grd by proj_ll2ra.csh. GACOS_correction.csh operation error:
![NS52_$E9PQ GLM69P7BTB~7](https://user-images.githubusercontent.com/114629377/219297521-3a089aab-8cad-417d-a720-98d4ae35f497.png)

I tested this line of command separately, and it showed an error:
![6%NNV ~4Y6M`4XFREZICC$4](https://user-images.githubusercontent.com/114629377/219297565-ea7b2ed0-c211-42ee-ad6f-1916b2b97700.png)

**Comment by Luvina0503** [comment]
This is the parameter for zpddm.grd and zpddm_ra.grd.
![J7M8}V`C$(`~N~1Q 6~63PH](https://user-images.githubusercontent.com/114629377/219297786-b4d93d1d-b592-4087-a923-3bcf7bceba30.png)
![H` EDEN7 AE}W$ZZ~QAT3MD](https://user-images.githubusercontent.com/114629377/219297809-1658102e-d2ff-4e7a-8c3d-b3147842259b.png)

**Comment by Luvina0503** [comment]
zpddm.grd is transformed into zpddm_ra.grd by proj_ll2ra.csh. GACOS_correction.csh operation error:
![image](https://user-images.githubusercontent.com/114629377/219311219-eb388229-4bc9-453e-aa69-671727589784.png)

I tested this line of command separately, and it showed an error:
![image](https://user-images.githubusercontent.com/114629377/219311301-f22fa5b2-c48a-4323-925f-a8adf78cc27d.png)

**Comment by Luvina0503** [comment]
zpddm.grd is transformed into zpddm_ra.grd by proj_ll2ra.csh. GACOS_correction.csh operation error:
![image](https://user-images.githubusercontent.com/114629377/219311534-d9edab71-5d03-4231-a484-64e6b2a6e469.png)

I tested this line of command separately, and it showed an error:
![image](https://user-images.githubusercontent.com/114629377/219311704-b5496672-8a73-4c7f-acaf-ee06a6bd36fb.png)

**Comment by esrivas17** [comment]
mmmm may you share the output of gmt grdinfo phasefilt.grd and gmt grdinfo zpddm.grd?

**Comment by Luvina0503** [comment]
Why can't I drag my phasefilt.grd into the answer box?

**Comment by esrivas17** [comment]
not sure what you mean but there might be the case with the precision of proj_ll2ra.csh, so even in your grids in lon/lat are ok, it can be the case that after the reprojection one of the gacos boundaries lies outside the dem boundaries. if that makes sense.
That's what Im trying to see

**Comment by Luvina0503** [comment]
I've found my problem and I'm working on it. But it is not clear how this figure should be adjusted.

zpddm_ra.grd:
xmin:-11744   xmax:79520
ymin:-6144    ymax:12288
phasefilt.grd
xmin:0   xmax:68496
ymin:0   ymax:13064

The problem is that y_max in zpddm_ra.grd is smaller than y_max in phasefilt.grd.
GACOS_data:
MinLat = 33.34
MaxLat = 35.19
MinLon = 117.36
MaxLon = 120.71

So how should I adjust my GACOS data selection area?

**Comment by esrivas17** [comment]
yeah good spot. I would say ( and if you can still have your area of interest inside) make the GACOS even smaller in the Y-Axis
so your dem Max_Lat is 35.33 and your GACOS grids Max_Lat is 35.19. Maybe can you make this difference up to 1? Being GACOS Max_Lat =< 34.33. just to make sure there is no issue when you project to radar coordinates

**Comment by Luvina0503** [comment]
Give me a few minutes. Let me test it out

**Comment by Luvina0503** [comment]
I feel like I need to start all over again. No amount of adjustment can satisfy the condition. Only the dem.grd range has been expanded

**Comment by Xiaohua-Eric-Xu** [comment]
> not sure what you mean but there might be the case with the precision of proj_ll2ra.csh, so even in your grids in lon/lat are ok, it can be the case that after the reprojection one of the gacos boundaries lies outside the dem boundaries (in radar coordinates). if that makes sense. That's what Im trying to see

@esrivas17, proj_ll2ra.csh only does a rough projection so it could be missing near the bounds if the selected GACOS grid barely covers the phase grid. So instead of getting a smaller GACOS grid, could the solution be, a larger one? e.g., 0.1 degree buffer would be safe.

**Comment by Luvina0503** [comment]
Yes. I'm expanding the grid

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
When I expand the grid, does that mean I need to re-register and interfere?

**Comment by Xiaohua-Eric-Xu** [comment]
I am thinking that maybe you just need to download a larger GACOS grid.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
If you expand the scope of GACOS, the following problems arise:
An error is still reported; GACOS data range is out of dem.grd range;
What I feel best about is expanding the dem.grd range.

**Comment by Xiaohua-Eric-Xu** [comment]
I guess the solution is: your dem.grd > GACOS > your_interferogram.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu @esrivas17 
This problem has been solved. Thank you for your patient answer. I would like to ask you a question. Is there a sequence of GACOS correction and cravings? Which order is best?

**Comment by Xiaohua-Eric-Xu** [comment]
> Is there a sequence of GACOS correction and cravings? Which order is best?

I guess I am really confused by this question.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu @esrivas17 
Figure 1 is the result graph after the advanced GACOS and the unwinding of the correction result.
Figure 2 shows the result of phasefilt.grd unwinding and then GACOS correction.
Figure 3 is the result of GACOS >>stack_coherence_mask.csh >>unwrap.csh.
What I want to ask is whether the stack_coherence_mask.csh script you provided is effective by comparing these pictures with each other. Is it clear that the order in which GACOS untangles affects the final result?

figure1:
![OA1S{~IU%(XE62)TDXHBA3M](https://user-images.githubusercontent.com/114629377/220128050-fb2b1010-9d77-49f7-a2f0-0bf11b24821f.png)
figure 2:
![TGHS(KZ_46BEH HHZHKM8~M](https://user-images.githubusercontent.com/114629377/220128132-ff765a5a-fb13-4067-9d1d-35156d0abcd3.png)
figure 3:
![S}`7WD1%NOYPDC61`ZY@) O](https://user-images.githubusercontent.com/114629377/220128165-3fc7bb58-df1c-4915-9b14-b52459670c05.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I think GACOS works well or not depends on the atmospheric condition. It'a hard to say which is better or things get significantly improved without ground trough.

**Comment by Gigi-gugu** [comment]
> @Xiaohua-Eric-Xu @esrivas17 This problem has been solved. Thank you for your patient answer. I would like to ask you a question. Is there a sequence of GACOS correction and cravings? Which order is best?

Excuse me, are you expanding the DEM range? If so, do the previous steps (registration, interference) need to be redone?
