### ISSUE TITLE
[Feature]: gacos_corrected results

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#641]
Hi.dear professors,
I'd like to ask you a question. This is GACOS_correction.csh correction. Is this an ideal outcome? Can you see that? If so, how should it be analyzed?

![9ON41V5`M59(Z )7OLAC~TC](https://user-images.githubusercontent.com/114629377/219395623-438bcedf-c6d7-433a-8360-d901449507ff.png)
![O~9@9V69DCR)8Q)REMWQ`}D](https://user-images.githubusercontent.com/114629377/219395667-2150b32e-5e4a-4c67-bac6-6dab1ff3f1aa.png)

**Comment by Xiaohua-Eric-Xu** [comment]
> Hi.dear professors, I'd like to ask you a question. This is GACOS_correction.csh correction. Is this an ideal outcome? Can you see that? If so, how should it be analyzed?
> 
> ![9ON41V5M59(Z )7OLAC~TC](https://user-images.githubusercontent.com/114629377/219395623-438bcedf-c6d7-433a-8360-d901449507ff.png) ![O~9@9V69DCR)8Q)REMWQ}D](https://user-images.githubusercontent.com/114629377/219395667-2150b32e-5e4a-4c67-bac6-6dab1ff3f1aa.png)

This is a really good question for the GACOS folks. If you have a GNSS station to compare with, that might tell you something?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
Then, if there is no GNSS station, can we only analyze and compare the results of subsequent unwinding and settlement?

**Comment by Luvina0503** [comment]
Then, is it necessary for me to expand and process the sbas?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu @esrivas17
This is the result graph (unwrap.pdf) obtained by using the GACOS corrected graph (snaphu_interp.csh) above, where the unwrapping threshold is 0.1. Do I feel that there are a few relevant points in unwrap.pdf? Will it lead to unsatisfactory settlement map analyzed by my sbas?

**Comment by Xiaohua-Eric-Xu** [comment]
If you have a large set of acquisitions (e.g., 100+), the velocity you get should be rather stable if everything is ran as guided in the time-series document. The atmospheric correction will reduce the turbulence in your time-series but not so much on the velocity. I am not sure what you are looking at with the data, so I am not sure what you mean by "satisfactory settlement".
