### ISSUE TITLE
[Help]: what is wrong when i select baselines

### ISSUE THREAD

**Issue by jerry7nol** [gmtsar/gmtsar#642]
my baseline_table.dat maybe wrong, but i don't know how to solve it  even i used 

```
 ls *ALL*PRM > prmlist (this creates the prmlist input file)
get_baseline_table.csh prmlist S1_20180508_ALL_F1.PRM
```

![WT~E62X}QALX_W(}S4QZK4J](https://user-images.githubusercontent.com/111356557/219591097-e2c637bb-95f9-4bb9-a997-960dcb63dd87.png)

because my orbits data is not poeorb orbits?

**Comment by jerry7nol** [comment]
S1_20230128_ALL_F1 2023027.6486165824 3312 0.000000000000 0.000000000000
S1_20230209_ALL_F1 2023039.6486048813 3324
 this is my baseline_table.dat

**Comment by Xiaohua-Eric-Xu** [comment]
Could you produce a new one with `get_baseline_table.csh`?

**Comment by jerry7nol** [comment]
> S1_20230128_ALL_F1 2023027.6486165824 3312 0.000000000000 0.000000000000 S1_20230209_ALL_F1 2023039.6486048813 3324 this is my baseline_table.dat

the product of `get_baseline_table.csh` same as before

**Comment by Xiaohua-Eric-Xu** [comment]
Please describe what you did in details and attach a log.

**Comment by jerry7nol** [comment]
i followed the tutorial about GMTSAR time series that i did before.
![`_%{WKC($RA3 DTKB1H}V31](https://user-images.githubusercontent.com/111356557/219596056-491584a0-b4f6-4a5c-affb-fe52a53c9720.png)
downloaded SLC data, resorb orbits data and dem,  make directions, make soft links ,gedit data.in,then finished 
```
preproc_batch_tops.csh data.in dem.grd 1 &> pbt_mode1.log &
preproc_batch_tops.csh data.in dem.grd 2 &> pbt_mode2.log &
```
my baseline.ps doesn't right too maybe 
![LLJXB5))ZO{O)C277X2OXF](https://user-images.githubusercontent.com/111356557/219597079-2bcf16b5-0498-4414-811a-6b3bd430b1f5.png)

**Comment by Xiaohua-Eric-Xu** [comment]
What's the command you ran with `get_baseline_table.csh`? And what is in your prmlist?

**Comment by jerry7nol** [comment]
> What's the command you ran with `get_baseline_table.csh`? And what is in your prmlist?

I ran `select_pairs.csh baseline_table.dat 50 100` and baseline_table.dat look like doesn't right, because it doesn't display the slave image baseline range to master image. but i don't know what is wrong with it
![IUAFTC1GBC}D~%~~KKW3IVQ](https://user-images.githubusercontent.com/111356557/220035721-eb24dfa6-3a28-4ab9-bbf6-4fac29ccadcb.png)

**Comment by Xiaohua-Eric-Xu** [comment]
The problem is not with `select_pairs.csh`, but rather is with your baseline_table.dat. `get_baseline_table.csh` will help you produce a new one, so that's why I was asking 

> What's the command you ran with `get_baseline_table.csh`?

**Comment by jerry7nol** [comment]
oh！i ran `get_baseline_table.csh prmlist S1_20230128_ALL_F1.PRM`
```
S1_20230128_ALL_F1.PRM
S1_20230209_ALL_F1.PRM
```is in my prmlist

**Comment by Xiaohua-Eric-Xu** [comment]
And the screen shots is what you get from the command above? 

Could you send the two PRM and their corresponding LED files so I can re-produce what you got?

**Comment by jerry7nol** [comment]
i got baseline_table.dat like before.
this is PRM and LED i have
[Desktop.zip](https://github.com/gmtsar/gmtsar/files/10781978/Desktop.zip)

**Comment by Xiaohua-Eric-Xu** [comment]
The second orbit file you sent me is empty. Could it be this problem? https://github.com/gmtsar/gmtsar/discussions/629

**Comment by jerry7nol** [comment]
maybe, but i don't know why,  although my orbits data is sort of resorb,but their are well.
i ran `p2p_S1_TOPS_Frame.csh ` and got LED of the second is empty too.  i will try to  redownload orbit data. thank you

**Comment by Xiaohua-Eric-Xu** [comment]
It could be a bad orbit file, if you have updated the GMTSAR code. Then you may choose the other restituted orbit file to cover your data.

**Comment by jerry7nol** [comment]
it work, thank you very much
