### ISSUE TITLE
[Help]: The corr.grd and phase.grd has the geocoding? 

### ISSUE THREAD

**Issue by moment-maker** [gmtsar/gmtsar#644]
**Describe the problem you met**
Hello experts, I'm new to the GMTSAR. Now I have a few questions that I'd like you to answer. Thank u.
1. When I set the time threshold and construct the interference pair, two SAR images interfere with each other but do not connect with other images. Will there be a solution error in the sbas step? What if, in order to be able to take advantage of these isolated images, I connect them with other images at a longer time interval, and remove the interference pairs (bad coherence) that are connected because the time threshold is raised. Is that going to lead to good results?

2. Do corr.grd and phase.grd have geocoding? There is no geocoding when I open it in arcgis. And if not, what do I do, I use ncview to look at it.

**Screenshot**
![image](https://user-images.githubusercontent.com/66958429/219685750-e1dbccba-a9b6-4946-8ff5-d6a947280392.png)

**Comment by Xiaohua-Eric-Xu** [comment]
There are two parameters in select_paris.csh, one is perpendicular baseline and the other is temporal baseline. I guess you selected a rather small perpendicular baseline. The problem with that is you may lose connection from one subset of interferograms to another and have to predict the deformation with smoothing (regularization). I would recommend connecting more as the baseline for Sentinel-1 is rather small.

**Comment by moment-maker** [comment]
Hi, Xu, thank you for your answer. I've solved the geocoding problem now. select_paris.csh I set the time baseline of 50 and the space baseline of 100. Because the region with low coherence loses its coherence over a long period of time, it may affect the results of the future solution. As many reports have mentioned that the orbit control of S1 satellite is very accurate, basically within 100 meters, so I set it this way. I would change the space baseline to 150 or 200 etc.

In addition, I would like to ask you that I set a low threshold when I was doing the mask step. By observing the mask_def.grd file, I can be seen that the selected points can basically cover the study area, also, scattered points will appear at sea. The question is, is there any reason why the grid coverage in the final result (vel_mask_ll.grd) is less extensive or even less extensive than that in mask_def.grd?

This is mask_def.grd
![image](https://user-images.githubusercontent.com/66958429/220040350-f82c5f23-f1d9-46d3-ad4e-7472e1b51626.png)

this is one of interferograms (12day)
![image](https://user-images.githubusercontent.com/66958429/220040199-5fcd7ac1-5972-442f-a8c0-7d5d0bcc2282.png)

this is the vel_mask_ll.grd
![image](https://user-images.githubusercontent.com/66958429/220042610-c8b19812-c82f-4976-91a1-47bf4159fb3c.png)
There seems to be a problem with the geocoding of vel_mask_l.grd, I will check it. So why is the range of the grid not consistent. Looking forward to your reply.

**Comment by Xiaohua-Eric-Xu** [comment]
> scattered points will appear at sea.

You can create a landmask_ra.grd with `landmask.csh` then snaphu[_interp].csh will apply that mask before doing phase unwrapping and remove any pixel in water.  

> Because the region with low coherence loses its coherence over a long period of time

Since temporal decorrelation is the major reason, what baseline decorrelation adds to that is negligible, so I would recommend to maintain connection between acquisitions rather than selecting minimal baseline. 

> So why is the range of the grid not consistent.

I am not sure, but usually geocoding "error" are likely associated with the trans.dat file used. Your interferogram looks good so maybe use the same trans.dat file for geocoding? (You may want to delete raln.grd and ralt.grd to recompute the mapping grids.)

**Comment by moment-maker** [comment]
Hello, Xu, thank you for your timely answer. I will modify the above parameters. I will check the geocoding later. The main problem I'm facing right now is that the results in vel_mask_ll.grd don't have as wide a range as they do in mask_def.grd. Is there something wrong with my understanding? In fact, not all points in the mask will show up in vel_mask_ll.grd, okay? Looking forward to your reply.

**Comment by Xiaohua-Eric-Xu** [comment]
You should be using `proj_ra2ll.csh` for geocoding rather than `geocode.csh`. The latter calls the former while applying further coherence masking.

**Comment by moment-maker** [comment]
yes, I used the proj_ra2ll.csh to do geocoding

**Comment by Xiaohua-Eric-Xu** [comment]
You'll need to project vel.grd rather than vel_mask.grd which is coherence masked by geocode.csh.

**Comment by moment-maker** [comment]
haha, I mean, the current confusion is already in the geocoding step. The main problem is that the result of the final vel.grd covers a relatively small area. Maybe I didn't describe it very clearly, or maybe I didn't understand it properly.

**Comment by Xiaohua-Eric-Xu** [comment]
I think you need to run proj_ra2ll.csh trans.dat vel.grd vel_ll.grd and then check on the output vel_ll.grd instead of vel_mask_ll.grd.
