### ISSUE TITLE
The sbas-mmap issue has been resolved. Thanks for your patience

### ISSUE THREAD

**Issue by behshidkhodaei** [gmtsar/gmtsar#647]
The sbas-mmap issue has been resolved. Thanks for your patience

_Originally posted by @Luvina0503 in https://github.com/gmtsar/gmtsar/issues/413#issuecomment-1333019309_

**Comment by Xiaohua-Eric-Xu** [comment]
Did you download a version that has mmap enabled? What's the exact command you ran?
