### ISSUE TITLE
HELP ME INSTALL GMTSAR

### ISSUE THREAD

**Issue by neda2133** [gmtsar/gmtsar#65]
dear all, My problem in installing GMTSAR is that when I enter the:

svn checkout svn://gmtserver.soest.hawaii .edu/GMTSAR/branches/5.4 GMTSAR command,
 it gives me the following error: 
svn: E170013: unable to connect to a repository at URL 'svn://gmtserver.soest.hawaii.edu/GMTSAR/branches/5.4 GMTSAR 
I need your help dear friends

**Comment by Xiaohua-Eric-Xu** [comment]
Please use the github server to install GMTSAR. (https://github.com/gmtsar/gmtsar/wiki)

**Comment by neda2133** [comment]
> Please use the github server to install GMTSAR. (https://github.com/gmtsar/gmtsar/wiki)

Hi xiaohua, I also used this site
https://github.com/gmtsar/gmtsar/wiki
 but it gave me an error and GMTSAR was not installed

**Comment by Xiaohua-Eric-Xu** [comment]
Which step did you get an error?

**Comment by neda2133** [comment]
my gmt version is gmt 5.4.5

**Comment by neda2133** [comment]
I typed the following command
git clone --branches 5.8 https://github.com/gmtsar GMTSAR
 ERROR IS:
command not found

**Comment by Xiaohua-Eric-Xu** [comment]
Sorry, but you need to install `git` first. https://github.com/git-guides/install-git

**Comment by neda2133** [comment]
dear eric

> Sorry, but you need to install `git` first. https://github.com/git-guides/install-git

dear Eric
I did all the installation steps but it does not install. Where can the problem come from? i use gmt 5.4.5
and gmtsar5.8

**Comment by neda2133** [comment]
> Sorry, but you need to install `git` first. https://github.com/git-guides/install-git

All installation steps are successful but the installation is not complete
Thank you for your help

**Comment by neda2133** [comment]
I downloaded GMTSAR  successfully from the site 
https://github.com/gmtsar
and did all the installation steps,
 but the installation is not complete

**Comment by Xiaohua-Eric-Xu** [comment]
When you say "not complete", you need to tell us at what step it failed. How are we supposed to magically know what happened with the installation?

**Comment by neda2133** [comment]
> When you say "not complete", you need to tell us at what step it failed. How are we supposed to magically know what happened with the installation?

You are right .
This is the first time I have installed this software, so I can not figure out exactly what the problem is. Maybe it would be better to check it again from the first step.
Excuse me, I have another question
What script should be run to uninstall GMTSAR?

**Comment by Xiaohua-Eric-Xu** [comment]
You could follow the wiki page to install all the libraries and then GMTSAR. I am not sure what you mean by "run a script".

**Comment by neda2133** [comment]
> You could follow the wiki page to install all the libraries and then GMTSAR. I am not sure what you mean by "run a script".
dear eric
thank you
