### ISSUE TITLE
[Feature]: interferogram

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#650]
Hi，dear professors,
I'd like to ask you a question. The units obtained in GMTSAR are the rad. How to get the shape variable in the graph, in m.

![image](https://user-images.githubusercontent.com/114629377/220225018-4458f375-2cc3-4146-b6ed-106e4c12dcf5.png)

**Comment by igps-ftk** [comment]
From the geocode.csh, to convert unwrapped phase to displacement:
`gmt grdmath unwrap_mask.grd $wavel MUL -79.58 MUL = los.grd`
where wavel=0.0554658 for Sentinel-1 data.
The result is in millimeter (mm).

More information e.g.,
[https://asf.alaska.edu/how-to/data-recipes/interpreting-an-unwrapped-interferogram-creating-a-deformation-map/](url)

Cheers,
Yunfeng Tian

**Comment by Luvina0503** [comment]
@igps-ftk 
My unwrapping result only contains unwrap.grd, not unwrap_mask.grd. Is this the same thing? Is that what you get when you unwrap?

**Comment by Xiaohua-Eric-Xu** [comment]
unwrap_mask.grd is created during geocode.csh, if I remember correctly.

**Comment by Luvina0503** [comment]
> 

What does -79.58 mean? Or is this a fixed value?

**Comment by Xiaohua-Eric-Xu** [comment]
That's probably -1000/4pi?

**Comment by Luvina0503** [comment]
OK.thank you
