### ISSUE TITLE
[Help]: Convert asc + dsc LOS to NEU component

### ISSUE THREAD

**Issue by sefatheking** [gmtsar/gmtsar#651]
Hello all,
I know this question has been asked a lot and it is boring for you. So I'm sorry for taking up your time. While we have LOS values with asc and dsc mode in a region, I have a question about how to convert these values to North, East and Up components. I browsed the forum generally and read the procedure recommended by Eric (https://github.com/gmtsar/gmtsar/issues/520). However, I had some questions: 
1) Eric says: firstly to coregister asc and dsc mod data with gmt grd sample. I did this with gmt grdcut for the same region (with -R option). does a problem occur? Unfortunately, I don't know how to do this with gmt grdsample. Can you write a line as an example?
2) A code was expressed by Eric as follows:

`gmt grdmath asc.grd des.grd ADD 2 DIV $cos_v DIV = vert.grd`

I'm confused as to what the term $cos_v in the line above is. It is said that this value can be obtained with the SAT_look. 
**17.575833 22.758125 195.492163 -0.605048 -0.109000 0.788693**
A sample sat_look output is below. Is cos_v value = 0.788693? Or is that the v value? How to calculate looking angle and incidence angle with the output of the sat_look function?
3) Finally, I see that in some articles, deformation values in the North-South direction are calculated e. Is there a way to do this with GMTSAR?

Thanks a lot.

**Comment by Xiaohua-Eric-Xu** [comment]
> 1. Eric says: firstly to coregister asc and dsc mod data with gmt grd sample. I did this with gmt grdcut for the same region (with -R option). does a problem occur? Unfortunately, I don't know how to do this with gmt grdsample. Can you write a line as an example?

First of all, you could not derive E N U (3 components) with asc and des (2 components). You could only assume North to be negligible due to the insensitivity of the satellite look direction (or orbit). 

> Is cos_v value = 0.788693? Or is that the v value? 

That's the cos_v value.

> How to calculate looking angle and incidence angle with the output of the sat_look function?

You have three cosines from SAT_look so should be able to calculate the angle?

> 3) Finally, I see that in some articles, deformation values in the North-South direction are calculated e. Is there a way to do this with GMTSAR?

If you have in total 3 look directions (i.e. 2 asc and 1 des or vice versa), or you could derive azimuthal motion, either from cross-correlation or MAI, then yes of course. You could write a simple inversion that's documented a lot in the literature to do a decomposition.

**Comment by mobigroup** [comment]
@sefatheking See here live example notebooks on Google Colab where incidence angle and vertical/west-east components are computed and visualized: https://github.com/mobigroup/gmtsar For two orbits just sum the results (descending vertical component + ascending vertical component, and the same for west-east).

**Comment by Xiaohua-Eric-Xu** [comment]
You don't have to pick one. You could writ in a format of inversion like below
```
| look_ed  look_ud |   | d_e |  = | d_d |
| look_ea  look_ua |   | d_u |     | d_a |
```
and then solve for `d_e` and `d_u`.
