### ISSUE TITLE
[Help]: The coverage of the final calculation is rare? Look forward for help

### ISSUE THREAD

**Issue by moment-maker** [gmtsar/gmtsar#652]
Hello, experts, I now have a question that I hope you can answer. I calculated the average coherence graph of all the interferograms and made the mask case by changing the threshold (the threshold is 0.068). Then I performed the phase unwrapping. Here I forgot to change the correlation_threshold in sanphu_title.csh in the unwrapping step, which is still the default 0.075. Finally, I performed the SBAS step to get the deformation rate graph.
  My question is that the number of coherent points after the mask is obtained and the final result cannot achieve a good and complete coverage effect, is it because of the threshold in snaphu script? After I modified the threshold value of the mask to 0.075, the two still could not completely or almost coincide. If I change the correlation_threshold in snaphu to a lower value in the future, can 
  I obtain wider coverage effect in the final deformation rate result?
There is also a question as to how the final sbas step works, is there a threshold where the coherence is greater than certain values, but the result cannot be solved?

This is the average coherence coefficient plot.
![image](https://user-images.githubusercontent.com/66958429/220535405-9c724db4-e3b9-46ac-8675-c78791840e85.png)
This is the legend of the coherence diagram above.
![image](https://user-images.githubusercontent.com/66958429/220535740-82259124-acc9-4f14-a16d-dbbe331fa6db.png)

This is the final deformation rate diagram,
![image](https://user-images.githubusercontent.com/66958429/220535908-41f11589-8c39-4161-8450-d0eba0b2c224.png)
![image](https://user-images.githubusercontent.com/66958429/220535956-0a255edf-640d-4567-9aea-a0723d9cc568.png)
Will not all points above the threshold be counted, and is it feasible for me to set such a small threshold?
Looking forward to your reply, Thank u.

**Comment by Xiaohua-Eric-Xu** [comment]
> If I change the correlation_threshold in snaphu to a lower value in the future, can I obtain wider coverage effect in the final deformation rate result?

Yes, but not wider, just more pixels will stay. 


> There is also a question as to how the final sbas step works, is there a threshold where the coherence is greater than certain values, but the result cannot be solved?

sbas does not care how low the coherence is, it simply solves what't put in. But if you put in one nan number, it may ruin that pixel. It is left this way intentionally in order to make the -atm option work.

**Comment by moment-maker** [comment]
Well, thank u for your prompt and patient answers, Xu!
