### ISSUE TITLE
[Help]: when  I run tail -f pbt_mode1.log, it has been stuck on this interface and will not run down

### ISSUE THREAD

**Issue by wangshuaicumt** [gmtsar/gmtsar#654]
ws@ws:/media/ws/MyBook/wangshuai/41-140/asc/F2/raw$ tail -f '/media/ws/MyBook/wangshuai/41-140/asc/F2/raw/pbt_mode1.log' 
Reading in 4834 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 4848 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 4848 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 4834 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5492 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5492 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5492 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5478 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5492 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5492 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 6119 lines of info from XML...
Writing 17 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 6105 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 6105 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 6105 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 6105 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 6119 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 6105 lines of info from XML...
Writing 16 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 6105 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170326_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170326_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170419_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170419_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170513_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170513_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170606_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170606_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170630_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170630_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170724_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170724_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170817_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170817_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170910_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20170910_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20171004_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20171004_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20171028_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20171028_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20171121_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20171121_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20171215_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20171215_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180108_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180108_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180201_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180201_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180225_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180225_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180321_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180321_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180414_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180414_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180508_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180508_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180601_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180601_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180625_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180625_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180719_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180719_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180812_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180812_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180905_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180905_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180929_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20180929_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20181023_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20181023_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20181116_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20181116_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20181210_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20181210_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190103_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190103_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190127_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190127_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190220_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190220_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190316_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190316_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190409_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190409_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190503_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190503_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190527_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190527_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190620_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190620_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190714_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190714_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190807_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190807_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190831_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190831_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190924_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20190924_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20191018_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20191018_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20191111_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20191111_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20191205_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20191205_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20191229_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20191229_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200122_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200122_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200215_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200215_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200310_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200310_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200403_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200403_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200427_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200427_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200521_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200521_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200614_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200614_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200708_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200708_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200801_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200801_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200825_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200825_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200918_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20200918_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20201012_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20201012_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20201105_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20201105_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20201129_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20201129_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20201223_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20201223_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210116_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210116_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210209_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210209_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210305_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210305_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210329_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210329_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210422_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210422_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210516_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210516_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210609_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210609_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210703_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210703_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210727_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210727_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210820_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210820_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210913_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20210913_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20211007_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20211007_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20211031_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20211031_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20211124_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20211124_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20211218_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20211218_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220111_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220111_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220204_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220204_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220228_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220228_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220324_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220324_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220417_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220417_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220511_ALL_F2.LED 
......master LED file S1_20170326_ALL_F2.LED 
.........aligned LED file S1_20220511_ALL_F2.LED

**Comment by igps-ftk** [comment]
This is how it (the -f option) was supposed to do. Use Ctrl+C to interrupt it.  Do not add the -f option if you do not want to monitor new lines added to the file.

Cheers,
Yunfeng Tian

**Comment by wangshuaicumt** [comment]
thanks


> This is how it (the -f option) was supposed to do. Use Ctrl+C to interrupt it. Do not add the -f option if you do not want to monitor new lines added to the file.
> 
> Cheers, Yunfeng Tian
