### ISSUE TITLE
[Bug]: SAT_llt2rat processing stopped due to invalid coordinates for one of input points

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#656]
For 8 stitched scenes SAT_llt2rat tool does not work for end scene coordinates. For the point inside the last scene boundaries it generates the error:

```
echo 36.2 28.2 0 | SAT_llt2rat S1_20230129_033404_F2.PRM 1
Error: SAT_llt2rat processing stopped due to invalid coordinates for one of input points
```
<img width="542" alt="Screenshot 2023-02-23 at 14 16 41" src="https://user-images.githubusercontent.com/7342379/220854564-c40c3154-9bf1-4cd9-a539-5d9303ae3257.png">

**Comment by Xiaohua-Eric-Xu** [comment]
Hmm, this is strange, I could not locate this error message in the code. Do you know where this line of error message come from?

**Comment by mobigroup** [comment]
I think it is related to this code in hermite_c.c:
```
fprintf(stderr, "interpolation point outside of data constraints, %f %f %f\n", xp, x[0], x[nmax - 1]);
```

**Comment by Xiaohua-Eric-Xu** [comment]
Usually this is caused because on every side there's less than 3 or 4 records to be interpolated with. How many records are in your corresponding LED file?

Another alternative is the orbit being too long that wraps the earth around.

**Comment by mobigroup** [comment]
52 records plus one header line:
```
$ head -n3 S1_20230129_033403_F1.LED
52 2023 28 12602.000000 10.000 
2023 28 12602.000000 2752259.474156 3172802.296705 5684853.064703 5435.97942800 3053.93746700 -4325.71622800 
2023 28 12612.000000 2806486.274485 3203123.820994 5641275.966211 5409.26862800 3010.31710900 -4389.62183000 
```

**Comment by mobigroup** [comment]
Interesting, when re-run I see the different message and and the output coordinates are almost the same for the all subswaths:

```
echo 36.2 28.2 0 | SAT_llt2rat S1_20230129_033403_F1.PRM 1
interpolation point outside of data constraints, 2432419.687296 2431802.000000 2432312.000000

echo 36.2 28.2 0 | SAT_llt2rat S1_20230129_033404_F2.PRM 1
interpolation point outside of data constraints, 2432415.775074 2431802.000000 2432312.000000

echo 36.2 28.2 0 | SAT_llt2rat S1_20230129_033402_F3.PRM 1                               
interpolation point outside of data constraints, 2432423.177916 2431792.000000 2432312.000000

```

Near to the frame start we have different coordinates as expected:

```
echo 38 40 0 | SAT_llt2rat S1_20230129_033403_F1.PRM 1
28164.347247437 1748.807645733 6369345.861503410 38.000000000 40.000000000 

echo 38 40 0 | SAT_llt2rat S1_20230129_033404_F2.PRM 1
8218.347247494 1285.507004897 6369345.861503410 38.000000000 40.000000000 

echo 38 40 0 | SAT_llt2rat S1_20230129_033402_F3.PRM 1                               
-15654.652752684 2159.304244716 6369345.861503410 38.000000000 40.000000000 
```

and to check
```
grep num_rng_bins S1_20230129_033403_F1.PRM  
num_rng_bins = 22244

grep num_rng_bins S1_20230129_033404_F2.PRM 
num_rng_bins = 26084

grep num_rng_bins S1_20230129_033402_F3.PRM 
num_rng_bins = 25132
```

I think that is ok for the frame start. 22244(sw1 offset) + 8218...(sw2) ~= 30000 and with overlapping ~2000 it is similar to 28164... and 8218... (sw2) - 26084(sw2 offset) ~= -18000 and with overlapping ~2000 it is similar to -15654.

**Comment by Xiaohua-Eric-Xu** [comment]
> Interesting, when re-run I see the different message and and the output coordinates are almost the same for the all subswaths:

Those when it says an error, the three numbers are the resulting(after search), start and end of seconds. For when it does not say an error, the results are range, azimuth ...

You could check orbit (in the LED) coverage by computing third record divided by 86400.0, and the fractional part of clock_start clock_stop in the PRM file. You usually need extra 3 or 4 records beyond the clock to do hermite interpolation.

**Comment by Xiaohua-Eric-Xu** [comment]
> echo 38 40 0 | SAT_llt2rat S1_20230129_033403_F1.PRM 1
> 28164.347247437 1748.807645733 6369345.861503410 38.000000000 40.000000000 
> 
> echo 38 40 0 | SAT_llt2rat S1_20230129_033404_F2.PRM 1
> 8218.347247494 1285.507004897 6369345.861503410 38.000000000 40.000000000 
> 
> echo 38 40 0 | SAT_llt2rat S1_20230129_033402_F3.PRM 1                               
> -15654.652752684 2159.304244716 6369345.861503410 38.000000000 40.000000000

For each subswath, it has different starting range and starting time, so it's normal that they have different coords after projection.

**Comment by mobigroup** [comment]
> For each subswath, it has different starting range and starting time, so it's normal that they have different coords after projection.

Sure! But why for 8 stitched scenes near to the frame end the coordinates are the same for all the subswaths?
```
echo 36.2 28.2 0 | SAT_llt2rat S1_20230129_033403_F1.PRM 1
interpolation point outside of data constraints, 2432419.687296 2431802.000000 2432312.000000

echo 36.2 28.2 0 | SAT_llt2rat S1_20230129_033404_F2.PRM 1
interpolation point outside of data constraints, 2432415.775074 2431802.000000 2432312.000000

echo 36.2 28.2 0 | SAT_llt2rat S1_20230129_033402_F3.PRM 1                               
interpolation point outside of data constraints, 2432423.177916 2431792.000000 2432312.000000
```

**Comment by Xiaohua-Eric-Xu** [comment]
I think I explained above that these numbers are not coordinates, they are seconds at the searching location, start and end of the LED file. I am not sure why the LED file is not long enough, as the script, when running `ext_orb_s1a` should've extracted much longer orbit file.

**Comment by mobigroup** [comment]
Ah, so SAT_llt2rat in the case of error returns not coordinates values, ok. I think GMTSAR never creates LED files for over 52 records...

**Comment by Xiaohua-Eric-Xu** [comment]
52 records sounds much like an orbit extracted for one frame (or 9-11 bursts ish). ext_orb_s1a by default gives 10 times more length (of the acquisition) on each side so for your case (70-ish bursts), I was worried that it may loop the Earth. 

How did you generate the LED file by the way?

**Comment by mobigroup** [comment]
For the 1st scene from the stitching ones:

```
!cd raw && make_s1a_tops \
    ../data/s1a-iw1-slc-vv-20230129t033403-20230129t033428-046993-05a2fe-004.xml \
    ../data/s1a-iw1-slc-vv-20230129t033403-20230129t033428-046993-05a2fe-004.tiff \
    S1_20230129_033403_F1 \
    0

Reading in 5995 lines of info from XML...
Writing 17 lines for orbit...

!cd raw && ext_orb_s1a \
    S1_20230129_033403_F1.PRM \
    ../data/S1A_OPER_AUX_POEORB_OPOD_20230218T080751_V20230128T225942_20230130T005942.EOF \
    S1_20230129_033403_F1

Writing 52 lines of precise orbit for the LED file...
```

I've checked ext_orb_s1a.c and there is the condition to limit the output lines using PRM SC_clock_start & SC_clock_stop. So the tool generates limited LED file for a single scene! That's enough for about 7 full scenes, but not more. Did you try to stitch over 7 scenes?

**Comment by Xiaohua-Eric-Xu** [comment]
If you are processing the stitched results, then the limit should be 10 times the length too. The other limit is to deal with 1 burst scenario which is not related to this specific case. Did you use p2p_processing.csh or preproc_batch_tops.csh? I suspect somehow the LED file of a specific frame is used rather than the LED for the stitched data.

**Comment by mobigroup** [comment]
To build the stitched frame we use assemble_tops binary. To call it we need to define the azimuths using create_frame_tops.csh And inside the script:
```
  cd new.SAFE
  make_s1a_tops $f0.xml $f0.tiff tmp1 0
  ext_orb_s1a tmp1.PRM ../$orb tmp1

  set ll1 = `awk NR==1'{print $1,$2}' ../$tps`
  set ll2 = `awk NR==2'{print $1,$2}' ../$tps`
    
  set tmpazi = `echo "$ll1 0" | SAT_llt2rat tmp1.PRM 1 | awk '{print $2}'`
  shift_atime_PRM.csh tmp1.PRM $tmpazi
  set azi1 = `echo "$ll1 0" | SAT_llt2rat tmp1.PRM 1 | awk '{printf("%d",$2+0.5 + '$tmpazi')}'`
  set azi2 = `echo "$ll2 0" | SAT_llt2rat tmp1.PRM 1 | awk '{printf("%d",$2+0.5 + '$tmpazi')}'`
  
  echo "Working on bursts covering $azi1 ($ll1) - $azi2 ($ll2)..."
  
  assemble_tops $azi1 $azi2 $a new
```

Please explain how are you going to define the azimuths for 8+ scenes using a single PRM and 52 records in the LED file!

**Comment by mobigroup** [comment]
This magic is the problem in ext_orb_s1a.c:

```
    // revising t1 and t2 in case only one burst is used.
    // if smaller than 2 burst, extract more
      t1 = prm.SC_clock_start - 10 * (prm.SC_clock_stop - prm.SC_clock_start);
      t2 = prm.SC_clock_stop + 10 * (prm.SC_clock_stop - prm.SC_clock_start);
    if (fabs(t2-t1) < 1/86400.0*150) {
        t1 = prm.SC_clock_start - 20 * (prm.SC_clock_stop - prm.SC_clock_start);
        t2 = prm.SC_clock_stop + 20 * (prm.SC_clock_stop - prm.SC_clock_start);
    }
```

How about to unify the code and allow to produce more LED records (203 lines):

```
      t1 = prm.SC_clock_start - 40 * (prm.SC_clock_stop - prm.SC_clock_start);
      t2 = prm.SC_clock_stop + 40 * (prm.SC_clock_stop - prm.SC_clock_start);
```

That’s enough for 27 scenes and I think we have no more sequential Sentinel-1 scenes (I saw 23 scenes, seems to be for India). And ext_orb_s1a processing time is exactly the same (with 1% measurement accuracy). I’m surprised what is the reason to limit the LED file records and the amount of stitching scenes? It’s declared as a big advantage (and it is) of GMTSAR to process and unwrap the complete interferogram at once, but it does not work for all the cases. Even the more, I perform the 7 stitched scenes processing very easy and fast on Apple Air (and Apple Macbook Pro 2013 13" is ok too) and on a modern desktop we can process 23 stitched scenes without hassle.

**Comment by Xiaohua-Eric-Xu** [comment]
> Please explain how are you going to define the azimuths for 8+ scenes using a single PRM and 52 records in the LED file!

I don't think I mentioned anything about this line above. 

> I’m surprised what is the reason to limit the LED file records and the amount of stitching scenes?

I think you may have misunderstood what I meant. You maynot want to make the orbit very long that loop the earth. It may confuse the searching of nearest point on the orbit that corresponds to zero doppler. 

It does not matter how many scenes you have, and the lines you pasted above did not answer my earlier question, i.e., how did you generate the LED file. Both preproc_batch_tops.csh and p2p_processing.csh should've generated new LED file (unless there's a bug somewhere) that corresponds to 10 times your stitched data rather than just for one frame (52 records).

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Sorry, I don't understand what do you mean. I shared the exact commands how to generate the LED and PRM files for the scenes stitching azimuths calculation:

```
!cd raw && make_s1a_tops \
    ../data/s1a-iw1-slc-vv-20230129t033403-20230129t033428-046993-05a2fe-004.xml \
    ../data/s1a-iw1-slc-vv-20230129t033403-20230129t033428-046993-05a2fe-004.tiff \
    S1_20230129_033403_F1 \
    0

Reading in 5995 lines of info from XML...
Writing 17 lines for orbit...

!cd raw && ext_orb_s1a \
    S1_20230129_033403_F1.PRM \
    ../data/S1A_OPER_AUX_POEORB_OPOD_20230218T080751_V20230128T225942_20230130T005942.EOF \
    S1_20230129_033403_F1

Writing 52 lines of precise orbit for the LED file...

echo "39 40 0" | SAT_llt2rat S1_20230129_033403_F1.PRM 1
interpolation point outside of data constraints, 2431861.040358 2432157.609805 2432307.609805
```

Using the patch above it works:
```
echo "39 40 0" | SAT_llt2rat S1_20230129_033403_F1.PRM 1
278901.640267297 -174063.862867619 6369345.861503410 39.000000000 40.000000000 
```

and we can call assemble_tops stitching tool with the defined azimuths.

But how do you suppose to stitch scenes using preproc_batch_tops.csh or p2p_processing.csh when these scripts even do not include assemble_tops call?

**Comment by Xiaohua-Eric-Xu** [comment]
Is S1_20230129_033403_F1.PRM the PRM after stitching? The data name has time of 033403-033428, which is about 25 seconds, that corresponds to 25/2.8 = ~ 9 bursts. So if the LED file is generated with that PRM, then it should have only 52 records. 

I think the file name will get changed after stitching (create_frame_tops.csh) right? 

Do note from what you attached earlier (lines in ext_orb_s1a.c), the clock_start and clock_stop will change after stitching as well. So if you stitched, e.g. 5 frames of data, then the clock will also change correspondingly.  And if you use the new PRM to create the LED file, it will have longer length for sure.

**Comment by Xiaohua-Eric-Xu** [comment]
> But how do you suppose to stitch scenes using preproc_batch_tops.csh or p2p_processing.csh when these scripts even do not include assemble_tops call?

preproc_batch_tops.csh is written before we have assemble tops and could take in multiple frames and stitch the resulting SLCs together with stitch_tops(.c). for p2p_processing.csh, one would assume they have run assemble_tops already as it only deals with a single frame.

**Comment by mobigroup** [comment]
Hmm, we still speak about different things. This is the pipeline:

0. Create "data" and "raw" subdirectories,
1. Download SLC zip files for the scenes,
2. Unpack the archives to "data" subdirectory,
3. Run the commands
```
!cd raw && make_s1a_tops \
    ../data/s1a-iw1-slc-vv-20230129t033403-20230129t033428-046993-05a2fe-004.xml \
    ../data/s1a-iw1-slc-vv-20230129t033403-20230129t033428-046993-05a2fe-004.tiff \
    S1_20230129_033403_F1 \
    0

!cd raw && ext_orb_s1a \
    S1_20230129_033403_F1.PRM \
    ../data/S1A_OPER_AUX_POEORB_OPOD_20230218T080751_V20230128T225942_20230130T005942.EOF \
    S1_20230129_033403_F1

echo "39 40 0" | SAT_llt2rat S1_20230129_033403_F1.PRM 1
interpolation point outside of data constraints, 2431861.040358 2432157.609805 2432307.609805
```
4. Stitch the scenes into one frame using the azimuths computed above and "assemble_tops" tool. Ops. The azimuths are not computed above!

**Comment by Xiaohua-Eric-Xu** [comment]
Ahh I think I understand what's the problem now. The DEM is covering everything so the orbit from the first frame has to cover that in order to proceed though the southern part of DEM is not useful to the first frame. A temporary fix could be to hard code the orbit length to be half the circular orbit (~2800s i.e., 6400 * pi/2 /7 on each side) (f76b01a31ad448b105e18285f14c4125046d9d20). It may slightly increase the computation time for SAT_llt2rat but should resolve the situation here. I don't really like the multiple of total length idea as it may cause problem when the "Frame" is very long. 

Do you mind giving it another try?

**Comment by mobigroup** [comment]
Great, now it works well outside of the 8 scenes frame:
```
ext_orb_s1a ...
Writing 282 lines of precise orbit for the LED file...

echo 38 40 0 | SAT_llt2rat S1_20230129_033403_F1.PRM 1                                                                  
28164.347247438 2057.592445827 6369345.861503410 38.000000000 40.000000000 

echo 34 22 0 | SAT_llt2rat S1_20230129_033403_F1.PRM 1
2650832.352887891 639133.571716667 6375158.676630517 34.000000000 22.000000000 

echo 42 56 0 | SAT_llt2rat S1_20230129_033403_F1.PRM 1
-2684317.383263673 -504738.136674443 6363478.883077914 42.000000000 56.000000000 
```

So it should be enough or almost enough for 23 scenes in India in case we use middle scene PRM. Is not 3/4 the orbit safe too? I mean ±2100.0/86400.0 instead of ±1400.0/86400.0 to be sure we have no limitations to process the full sequential orbit everywhere.

**Comment by Xiaohua-Eric-Xu** [comment]
That sounds bold but I am not sure. You could try the even longer orbit. Do note as I mentioned above, this may increase computation time for SAT_llt2rat by a bit.

**Comment by mobigroup** [comment]
Ok, np. I think we already have the great progress with the recent change.

**Comment by Xiaohua-Eric-Xu** [comment]
Fingers crossed, but there will always be another bug.

**Comment by mobigroup** [comment]
Ah, another bug is always possible even without new changes:)
