### ISSUE TITLE
[Feature]: GPS data verification

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#657]
Hello, I'd like to ask you a question. If the GACOS correction results require GNSS data to verify. So where should this GPS data be downloaded from? What are the requirements of the GPS site selected? Can you directly process GPS data with a script in GMTSAR?

**Comment by Luvina0503** [comment]
I downloaded it from the MGViz-ESESES website, but there is no click in my study area

**Comment by Luvina0503** [comment]
Second, after downloading a *.neu file in SOPAC, how to deal with it in GMTSAR and how to get GNSS.ll

**Comment by Luvina0503** [comment]
![image](https://user-images.githubusercontent.com/114629377/221559150-245a184e-f79b-466c-ad69-46c91f6c5632.png)
The UNR website cannot be opened

**Comment by Xiaohua-Eric-Xu** [comment]
You may need to contact someone who studies GNSS locally to get the data there. Sadly, that's something we could not provide here.
