### ISSUE TITLE
organize_files_tops_linux.csh error

### ISSUE THREAD

**Issue by cxinlong** [gmtsar/gmtsar#660]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through
May I ask why this error occurs when organizing files?SKIP 20200517, as it does not have enough scenes ...
![2023-02-23 20-32-00 的屏幕截图](https://user-images.githubusercontent.com/118950056/220906536-0033a3cf-96fa-4cc5-bcc5-f3b6cbf162ac.png)

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
This line `SKIP ...` usually means your pins are outside your coverage, or you have non-consecutive acquisitions. Try to move your pins inward or examine in each *.SAFE/preview/map-overlay.kml to check whether you have enough coverage.
