### ISSUE TITLE
[Help]: Why is the nodata area the same and Why is there no value for areas that are not nodata?

### ISSUE THREAD

**Issue by moment-maker** [gmtsar/gmtsar#662]
**Describe the problem you met**
Hello, experts. I found some problems when using GMTSAR software. I'd like to ask you about it. In the process of interference, it is found that for the same SAR main image, the pixels covered by the nodata region shown in the coherence coefficient image in 12 days and the nodata region in the coherence coefficient image in 24 days are basically the same, and there may be little change. At the same time, the pixels covered by nodata in the coherence coefficient map obtained by using different main images and different time intervals are basically the same. May I ask if you have encountered this problem and what is the reason?

The second problem is that I got Professor Xu's explanation in the last question (especially thanks to Xu!!!), there is no threshold set in the sbas step, but one occurrence of a pixel in the entire time series nodata will destroy the entire pixel, which is reflected in the end that the pixel has no deformation rate result. But there are not so many pixels of nodata in my experiment, why is the final result of deformation rate so small? Look forward to your reply, thank you!

this is the Coherence coefficient diagram of 12d(20220102_20220114),I've only shown a few details, where I've shown the nodata section in red.
![12天](https://user-images.githubusercontent.com/66958429/221132529-0f04bd69-0e36-4a2c-ac8c-fca46cbc8c83.png)

This is the Coherence coefficient diagram of 24d(20220102_20220126),I've only shown a few details, where I've shown the nodata section in red
![24天](https://user-images.githubusercontent.com/66958429/221132939-46fd9c09-07fc-41ba-8ec1-41aa815e23e2.png)
I used the same ribbon for the result above. You can see that different time intervals show similar nodata areas.

This is the coherence coefficient diagram of 12d(20220114_20220227),Compared to the above two, different main images are used, but the final nodata area is basically the same
![12——2](https://user-images.githubusercontent.com/66958429/221133784-35db8982-a29c-43c7-bd9e-7ee193157c9c.png)

Then there are so many non-nodata pixels in the image, and the threshold when I unwrap is not very high. Why are there so few pixels with deformation rate in the end? as the next vel_ll.grd shows.
![屏幕截图 2023-02-24 170315](https://user-images.githubusercontent.com/66958429/221137200-0d8fb37c-1d27-4be7-88fd-f2a62bbb87de.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @moment-maker , the problem is when you have lots of lots of interferograms, the decorrelation may happen slightly inconsistently from one interferogram to another. So even though they look about the same (with small changes), the final masking (consider it as masking) may exclude lots of pixels. A better way to handle this situation is to create a common coherence mask with stack_coherence_mask.csh and use the resulting mask_def.grd for phase unwrapping with a tiny coherence threshold, e.g. 0.001.
