### ISSUE TITLE
[Help]: GMT Installation Error

### ISSUE THREAD

**Issue by Atif5100** [gmtsar/gmtsar#663]
Hi,
I am going to work in new environment of GMT and GMTSAR i am initially trying to install GMT in Virtual machine with 22.04.1 ubuntu but i am getting this error while running command “sudo make install” and unable to find solution yet. can anyone help with it?
thanks
![Screenshot 2023-02-24 095530](https://user-images.githubusercontent.com/57218215/221172156-615a213f-47ac-4306-964e-53cf43d25f9c.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I think you should be asking this question at https://github.com/GenericMappingTools/gmt/issues. But my suggestion is to build gmt 6.1 or later, instead of gmt 5.4.5 which is not updated anymore.

**Comment by Atif5100** [comment]
Got it. Thankyou. i have updated it and it worked now.
