### ISSUE TITLE
[Help]: unwrap_intf.csh

### ISSUE THREAD

**Issue by wangshuaicumt** [gmtsar/gmtsar#664]
ws@ws:/media/ws/MyBook/wangshuai/41-140/asc/merge$ unwrap_intf.csh
ln: 无法创建符号链接 './landmask_ra.grd': 文件已存在
grdmath [ERROR]: Syntax error: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: corr_patch.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: mask2_patch.grd is not a number, operator or file name
grdmath [ERROR]: Syntax error: mask2_patch.grd is not a number, operator or file name
Setting search radius to be 300 ...
Reading in original grid...
nearest_grid [ERROR]: File phase_tmp.grd not found
[Session nearest_grid (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open grdfile phase_tmp.grd 
mv: 无法获取'tmp.grd' 的文件状态(stat): 没有那个文件或目录
grd2xyz [ERROR]: File phase_tmp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
grd2xyz [ERROR]: File corr_tmp.grd not found
[Session gmt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
unwrapping phase with snaphu - higher threshold for faster unwrapping 
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files

snaphu v2.0.4
32 parameters input from file snaphu.conf.brief (297 lines total)
not enough input arguments.  type snaphu -h for help
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
xyz2grd [ERROR]: Error for input file: No such file (unwrap.out)
xyz2grd [ERROR]: Syntax error: Must specify -R option
xyz2grd [ERROR]: Syntax error -I option: Must specify positive increment(s)
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdinfo [ERROR]: Error for input file: No such file (phase_patch.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
xyz2grd [ERROR]: Error for input file: No such file (conncomp.out)
xyz2grd [ERROR]: Syntax error: Must specify -R option
xyz2grd [ERROR]: Syntax error -I option: Must specify positive increment(s)
grdmath [ERROR]: Syntax error: tmp.grd is not a number, operator or file name
mv: 无法获取'tmp.grd' 的文件状态(stat): 没有那个文件或目录
grdgradient [ERROR]: Error for input file: No such file (unwrap.grd)
grdgradient [ERROR]: Syntax error: Must specify input file
grdinfo [ERROR]: Error for input file: No such file (unwrap.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
makecpt [ERROR]: Syntax error -T: Must specify valid min[/max[/inc[<unit>|+n]]] option
grdinfo [ERROR]: Error for input file: No such file (unwrap.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdinfo [ERROR]: Error for input file: No such file (unwrap.grd)
grdinfo [ERROR]: Syntax error: Must specify one or more input files
grdimage [ERROR]: Error for input file: No such file (unwrap.grd)
grdimage [ERROR]: Syntax error -I: Requires a valid grid file or a constant
grdimage [ERROR]: Syntax error: Must specify one (or three) input file(s)
grdimage [ERROR]: Syntax error -I option: Must specify intensity file, value, or modifiers
psscale [ERROR]: Could not parse nwrap.grd into Geographical, Cartesian, or Temporal coordinates!psscale [ERROR]: Syntax error -R option. Correct syntax:
	-R<xmin>/<xmax>/<ymin>/<ymax>[/<zmin>/<zmax>]
	  Append r if giving lower left and upper right coordinates
	-Rg or -Rd for global domain
	-R<grdfile> to take the domain from a grid file
psscale [ERROR]: Offending option -Runwrap.grd
psconvert [ERROR]: The file unwrap.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
Unwrapped phase map: unwrap.pdf

**Comment by Xiaohua-Eric-Xu** [comment]
I think you may need to run `snaphu[_interp].csh`?

**Comment by wangshuaicumt** [comment]
thanks


&nbsp;


清风清纯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaohua(Eric) ***@***.***&gt;; 
发送时间: 2023年2月27日(星期一) 晚上8:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [gmtsar/gmtsar] [Help]: unwrap_intf.csh (Issue #664)





 
I think you may need to run snaphu[_interp].csh?
