### ISSUE TITLE
[Help]: There is obvious jump at the junction of two iws. How can I solve it？

### ISSUE THREAD

**Issue by wangshuaicumt** [gmtsar/gmtsar#665]
There is obvious jump at the junction of two iws. How can I solve it？

**Comment by Xiaohua-Eric-Xu** [comment]
Please attach a plot to describe the situation.

**Comment by wangshuaicumt** [comment]
thanks,my problem has been solved
&nbsp;


清风清纯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaohua(Eric) ***@***.***&gt;; 
发送时间: 2023年2月27日(星期一) 晚上7:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [gmtsar/gmtsar] [Help]: There is obvious jump at the junction of two iws. How can I solve it？ (Issue #665)





 
Please attach a plot to describe the situation.
