### ISSUE TITLE
[Help]: Two swaths are spliced, and the result shows obvious jump，how to solve it?

### ISSUE THREAD

**Issue by wangshuaicumt** [gmtsar/gmtsar#667]
![01](https://user-images.githubusercontent.com/117328108/221389989-f3666885-e49f-4f57-9ac1-0ed0b8521af9.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Please describe how you got this result. Could it be that you used a config file not for TOPS data? i.e. no range_dec and azimuth_dec specified.

**Comment by wangshuaicumt** [comment]
Thanks，my problem has been solved!


清风清纯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gmtsar/gmtsar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月27日(星期一) 晚上8:11
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [gmtsar/gmtsar] [Help]: Two swaths are spliced, and the result shows obvious jump，how to solve it? (Issue #667)





 
Please describe how you got this result. Could it be that you used a config file not for TOPS data? i.e. no range_dec and azimuth_dec specified.
