### ISSUE TITLE
[Help]:  Couldn't open xml file: 

### ISSUE THREAD

**Issue by wangshuaicumt** [gmtsar/gmtsar#668]
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 35 
Reading in 5464 lines of info from XML...
Writing 16 lines for orbit...
Writing SLC..Image Size: 25836 X 12192...
 Couldn't open xml file: 
 S1A_OPER_AUX_POEORB_OPOD_20210314T162101_V20191017T225942_20191019T005942.EOF 
 Couldn't open xml file: 
 S1A_OPER_AUX_POEORB_OPOD_20210314T162101_V20191017T225942_20191019T005942.EOF 
Successfully opened junk1 
rm: No match.
Reading in 4834 lines of info from XML...
Writing 16 lines for orbit...
 Couldn't open xml file: 
 S1A_OPER_AUX_POEORB_OPOD_20210302T003244_V20170325T225942_20170327T005942.EOF 
Shifting the master PRM by 0 lines...
Successfully opened junk1.PRM 
Successfully opened junk2.PRM 
......master LED file S1_20191018_120156_F2.LED 
.........aligned LED file S1_20170326_120134_F2.LED 
......master LED file S1_20191018_120156_F2.LED 
.........aligned LED file S1_20170326_120134_F2.LED

**Comment by Xiaohua-Eric-Xu** [comment]
Not sure why but maybe change the ownership of the orbit files to yourself?

**Comment by wangshuaicumt** [comment]
thanks,my problem has been solved

&nbsp;


清风清纯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaohua(Eric) ***@***.***&gt;; 
发送时间: 2023年2月27日(星期一) 晚上8:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [gmtsar/gmtsar] [Help]:  Couldn&#39;t open xml file:  (Issue #668)





 
Not sure why but maybe change the ownership of the orbit files to yourself?
