### ISSUE TITLE
[Help]: Can GMTSAR do  pixel offset？

### ISSUE THREAD

**Issue by Xiongwei789** [gmtsar/gmtsar#669]
Hi, 
Pixel offset images can be used to determine fault surface traces, especially for areas with severe decoherence, such as the 2023 Turkey Mw7.8 and Mw7.5 doublet. Pixel offset images are clear (See the figure below). 
![000247474](https://user-images.githubusercontent.com/92964720/221591525-59f07dca-042f-4aa1-a859-60a8333e8fb6.png)

So, Can GMTSAR do  pixel offset？I have tried with "make_a_offset.csh", for exmaple:
make_a_offset.csh S1_20230129_033427_F1.PRM S1_20230210_033427_F1.PRM  618 1200 16 16 1
make_a_offset.csh S1_20230129_033428_F2.PRM S1_20230210_033427_F2.PRM  725 1125 16 16 1
make_a_offset.csh S1_20230129_033427_F3.PRM S1_20230210_033426_F3.PRM 698 1200 16 16 1
But the results is strange. Can you give me some suggestions?
![offset](https://user-images.githubusercontent.com/92964720/221592089-e144859e-8776-4f41-bdb8-e6761a628ba2.png)

**Comment by Xiaohua-Eric-Xu** [comment]
You probably need to increase nx and ny so the merging could work properly. I used 512x3072 for every subswath. To get more stable solution, you'll have to use larger search window size. It may take quite a while to run but I think someone published a SRL paper on paralleling GMTSAR's xcorr and implemented GPU version too.

**Comment by Xiongwei789** [comment]
> You probably need to increase nx and ny so the merging could work properly. I used 512x3072 for every subswath. To get more stable solution, you'll have to use larger search window size. It may take quite a while to run but I think someone published a SRL paper on paralleling GMTSAR's xcorr and implemented GPU version too.

Yeah, it took a lot of time. There is another problem. There is only one output file named "azi_off.grd". Whether it means shift along the azimuth. How can I get the range shift?

**Comment by Xiaohua-Eric-Xu** [comment]
You'll neeed to use the output freq_xcorr.dat to create a range offset grid. Similar to what's in make_a_offset.csh. Then use c_speed/rng_samp_rate/2 to calculate rng pixel size and convert the shift in pixels to shift in meters.

**Comment by Xiaohua-Eric-Xu** [comment]
We didn't implement this to the script as usually people would use phase rather than range pixel tracking, as the latter is noisier though less affected by decorrelation.

**Comment by Xiongwei789** [comment]
Ok, Thank you. I will try it.

**Comment by Xiongwei789** [comment]
> You'll neeed to use the output freq_xcorr.dat to create a range offset grid. Similar to what's in make_a_offset.csh. Then use c_speed/rng_samp_rate/2 to calculate rng pixel size and convert the shift in pixels to shift in meters.

Hi professor，
Can you provide me with your code? I lack knowledge in this area and would like to refer to it.
Thank you

**Comment by Xiaohua-Eric-Xu** [comment]
Here's some script to start with. Modify the parameters at the beginning and then convert freq_xcorr.dat to a grid. 
[make_xcorr_plot.csh.txt](https://github.com/gmtsar/gmtsar/files/10954822/make_xcorr_plot.csh.txt)

**Comment by Xiongwei789** [comment]
Thank you. I'll try.

**Comment by Xiongwei789** [comment]
Thank you. I'll try.

**Comment by Xiongwei789** [comment]
Dear Xiaohua,
Based on your code, I obtained pixel offsets for the 2023 Turkey earthquake. The maximum value along the range are over 10 m (Figure1). However,  your and some results show the maximum values are ~4m (Figure 2).  

![Figure 1](https://user-images.githubusercontent.com/92964720/226108889-7acc8ae5-546e-4a43-b732-83802d9bbda2.png)
![Figure 2](https://user-images.githubusercontent.com/92964720/226108892-d5e72c64-2b35-4c21-8d87-7443c270b320.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Could you add a colorbar for your plot? Or simply share your grids? The results look quite similar to each other.

**Comment by Xiongwei789** [comment]
Yes, the colorbar is below the figure. It may be too close. The unit is m.
![image](https://user-images.githubusercontent.com/92964720/226262997-8d5adc92-d939-4883-a926-dff93880edbe.png)

**Comment by Xiongwei789** [comment]
Here is scripts and modules I used.  
make_a_offset.csh S1_20230129_033427_F3.PRM S1_20230210_033426_F3.PRM  512 3072 64 64 1
[make_range.txt](https://github.com/gmtsar/gmtsar/files/11014737/make_range.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
problem might be from this line?
```
gmt grdmath roff_ll.grd $azi_size MUL = rg_offset_ll.grd
```

**Comment by Elcappo2019** [comment]
Can you share me the full steps that enable me to create the Pixel-Offset Tracking method with scripts that you used. I stucked many times about this mission ? @Xiongwei789

**Comment by HuyBi711** [comment]
@Xiongwei789  hi, can i ask you a question?
i followed your instructions to create a pixel-offset image of the noto earthquake in japan. it seems like the result i got is wrong and i don't know why. can you give me some hints?

![Image](https://github.com/user-attachments/assets/77dedc14-4f1c-4d69-bf5b-80001cdcc85c)
![Image](https://github.com/user-attachments/assets/093b3d6b-9132-4083-974a-08b6fb700bcd)
![Image](https://github.com/user-attachments/assets/6618af5c-6481-4e7f-8321-603f71c2aaa8)
![Image](https://github.com/user-attachments/assets/82cecb78-d47a-430d-98a7-004996e58f61)

**Comment by Xiongwei789** [comment]
> [@Xiongwei789](https://github.com/Xiongwei789) hi, can i ask you a question? i followed your instructions to create a pixel-offset image of the noto earthquake in japan. it seems like the result i got is wrong and i don't know why. can you give me some hints?
> 
> ![Image](https://github.com/user-attachments/assets/77dedc14-4f1c-4d69-bf5b-80001cdcc85c) ![Image](https://github.com/user-attachments/assets/093b3d6b-9132-4083-974a-08b6fb700bcd) ![Image](https://github.com/user-attachments/assets/6618af5c-6481-4e7f-8321-603f71c2aaa8) ![Image](https://github.com/user-attachments/assets/82cecb78-d47a-430d-98a7-004996e58f61)

I'm sorry. I'm not sure why that's happening. I primarily work with Sentinel-1 data for POT processing, and I don't have experience with ALOS-2.

**Comment by Xiaohua-Eric-Xu** [comment]
I used make_a_offset.csh and the script above to produce these maps. You may give it a try? https://x.com/XiaohuaXu1/status/1745355913987490041 .

**Comment by Xiaohua-Eric-Xu** [comment]
You may need to tune the nx, ny, xsearch, ysearch parameters though.

**Comment by HuyBi711** [comment]
> > [@Xiongwei789](https://github.com/Xiongwei789) hi, can i ask you a question? i followed your instructions to create a pixel-offset image of the noto earthquake in japan. it seems like the result i got is wrong and i don't know why. can you give me some hints?
> I'm sorry. I'm not sure why that's happening. I primarily work with Sentinel-1 data for POT processing, and I don't have experience with ALOS-2.

Thank you so much. I wonder if you use sentinel-1 dataset what software did you use to process the data?

**Comment by HuyBi711** [comment]
> I used make_a_offset.csh and the script above to produce these maps. You may give it a try? https://x.com/XiaohuaXu1/status/1745355913987490041 .

@Xiaohua-Eric-Xu I saw your results in the post on X and it was a so great result. Can you explain a little more about the workflow you followed to process the data?

**Comment by Xiaohua-Eric-Xu** [comment]
I just ran with nx and ny being a bit larger, created the map grids and then filtered the results with gmt grdfilter. You probably want to rule out some very large values first or maybe median filter the map.

**Comment by HuyBi711** [comment]
this is my using program. 
i am new to gmtsar so it would be great if you could take some time to look through the code and give me some advice? i would appreciate it!
[make_pot.txt](https://github.com/user-attachments/files/18795674/make_pot.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
It might be better to show your results so that I target to a specific question. 

> this is my using program. i am new to gmtsar so it would be great if you could take some time to look through the code and give me some advice? i would really appreciate it! [make_pot.txt](https://github.com/user-attachments/files/18795674/make_pot.txt)

**Comment by HuyBi711** [comment]
> > > > [@Xiongwei789](https://github.com/Xiongwei789) hi, can i ask you a question? i followed your instructions to create a pixel-offset image of the noto earthquake in japan. it seems like the result i got is wrong and i don't know why. can you give me some hints?
> > > > I'm sorry. I'm not sure why that's happening. I primarily work with Sentinel-1 data for POT processing, and I don't have experience with ALOS-2.
> > 
> > 
> > Thank you so much. I wonder if you use sentinel-1 dataset what software did you use to process the data?
> > I used GMTSAR to process the Sentinel-1 for the earthquake doublet. And I used ISCE2 to process ALOS-2 for the Note earthquake.

Thank you so much!!!

**Comment by nailra** [comment]
> > It might be better to show your results so that I target to a specific question.
> > > this is my using program. i am new to gmtsar so it would be great if you could take some time to look through the code and give me some advice? i would really appreciate it! [make_pot.txt](https://github.com/user-attachments/files/18795674/make_pot.txt)
> 
> I found the mistake and fixed it. And I got the desired result. I made a mistake in the image preprocessing part when using the command p2p_processing.csh ALOS2 IMG-HH-ALOS2487932830-230606-UBSL1.1__D IMG-HH-ALOS2518982830-240102-UBSL1.1__D This command outputs file [config.ALOS2.txt](https://github.com/user-attachments/files/18882428/config.ALOS2.txt) and I had mis-tuned the "proc_stage" variable in this file which resulted in the data not being pre-processed properly. The reason i didn't get results is not program make_a_pot.csh, but anyway thank you so much for your advices.
> 
> ![Image](https://github.com/user-attachments/assets/b55ced97-4dc5-4a29-9b12-b3eb6df3613d) ![Image](https://github.com/user-attachments/assets/8cc48aa0-81ed-406f-af53-74f6acad7ef5)

Hello @HuyBi711 can I ask you a question, I am new to GMTSAR and I also process ALOS-2 in Noto area with the same dataset as yours. I have done the interferogram processing with p2p_processing.csh, and now I want to do the pixel offset calculation.
I tried make_a_offset.csh IMG-HH-ALOS2487932830-230606-UBSL1.1__D.PRM IMG-HH-ALOS2518982830-240102-UBSL1.1__D.PRM 2048 2048 32 32 1
however, the process is taking much time to run (until I write this comment, it is still not done yet), do you know how can I set the an ideal parameter of nx ny xsearch ysearch to speed up the process? Thank you.

**Comment by Xiaohua-Eric-Xu** [comment]
The speed of xcorr heavily depend on how good of a fftw lib is used. My personal experience is that Mac performs much faster calculation than Ubuntu.

**Comment by Xiaohua-Eric-Xu** [comment]
You may also try a paralleled version of xcorr https://github.com/cuihaoleo/gmtsar_optimize

**Comment by nailra** [comment]
@Xiaohua-Eric-Xu thank you very much for your suggestion. I was able to run the process much faster with gmtsar_optimize.

**Comment by HuyBi711** [comment]
> > > It might be better to show your results so that I target to a specific question.
> > > > this is my using program. i am new to gmtsar so it would be great if you could take some time to look through the code and give me some advice? i would really appreciate it! [make_pot.txt](https://github.com/user-attachments/files/18795674/make_pot.txt)
> > 
> > 
> > I found the mistake and fixed it. And I got the desired result. I made a mistake in the image preprocessing part when using the command p2p_processing.csh ALOS2 IMG-HH-ALOS2487932830-230606-UBSL1.1__D IMG-HH-ALOS2518982830-240102-UBSL1.1__D This command outputs file [config.ALOS2.txt](https://github.com/user-attachments/files/18882428/config.ALOS2.txt) and I had mis-tuned the "proc_stage" variable in this file which resulted in the data not being pre-processed properly. The reason i didn't get results is not program make_a_pot.csh, but anyway thank you so much for your advices.
> > ![Image](https://github.com/user-attachments/assets/b55ced97-4dc5-4a29-9b12-b3eb6df3613d) ![Image](https://private-user-images.githubusercontent.com/179721175/415056743-8cc48aa0-81ed-406f-af53-74f6acad7ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEwNTA3NzMsIm5iZiI6MTc0MTA1MDQ3MywicGF0aCI6Ii8xNzk3MjExNzUvNDE1MDU2NzQzLThjYzQ4YWEwLTgxZWQtNDA2Zi1hZjUzLTc0ZjZhY2FkN2VmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMwNFQwMTA3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDMxYjMyNjk0ODQ0ZjAzNDFhNDg1ZjJkNjdkOTY3OTMxNjkzMDU0ZWM1YmVjN2I3YzA5OTcwZGMzNGFmZTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LG6g-Wj0UIGSnvhT1ezFBaPVCy4zdPDB0IRDkcCxhkg)
> 
> Hello [@HuyBi711](https://github.com/HuyBi711) can I ask you a question, I am new to GMTSAR and I also process ALOS-2 in Noto area with the same dataset as yours. I have done the interferogram processing with p2p_processing.csh, and now I want to do the pixel offset calculation. I tried make_a_offset.csh IMG-HH-ALOS2487932830-230606-UBSL1.1__D.PRM IMG-HH-ALOS2518982830-240102-UBSL1.1__D.PRM 2048 2048 32 32 1 however, the process is taking much time to run (until I write this comment, it is still not done yet), do you know how can I set the an ideal parameter of nx ny xsearch ysearch to speed up the process? Thank you.

Hi @nailra ,
I think the processing speed does not depend on the values of the variables nx and ny. I process the data on Ubuntu, and it takes me about 1.5 to 2 hours.
In the make_a_offset script that you used, there is the following line:
if ($do_xcorr == 1 ) xcorr $master $aligned -nx $nx -ny $ny -xsearch $xsearch -ysearch $ysearch -noshift
In this command, xcorr is a program that performs cross-correlation between two SAR images. However, this version is quite slow, so you can use a faster version called xcorr2_cl. You can refer to the link below for more details.
https://github.com/cuihaoleo/gmtsar_optimize 
After installing xcorr2_cl, replace xcorr in the above command with xcorr2_cl and try running it again:
if ($do_xcorr == 1 ) xcorr2_cl $master $aligned -nx $nx -ny $ny -xsearch $xsearch -ysearch $ysearch -noshift

good luck!
