### ISSUE TITLE
[Feature]: track

### ISSUE THREAD

**Issue by wangshuaicumt** [gmtsar/gmtsar#670]
Can the current GMTSAR realize the splicing of two adjacent tracks？

**Comment by wangshuaicumt** [comment]
Emm, For example, because my research area is large and distributed on two tracks, I use GMTSAR to process the data of each track and get the deformation rate. Can I use GMTSAR for data fusion？

**Comment by Xiaohua-Eric-Xu** [comment]
We don't have a ready script to do so. You could chose to combine during modeling, or fuse the LOS, or decompose your data to ENU, etc. Most of them are simple to implement.

**Comment by wangshuaicumt** [comment]
I'm sorry, but I don't understand it because my talent is shallow. Could you be more specific? thank you！

**Comment by Xiaohua-Eric-Xu** [comment]
In short it depends on what you need to do with the data. If you are doing earthquake slip inversion, or other modeling, you don't have to fuse the data. Simply model every track of data. By doing decomposition, you are essentially combining the dataset to provide a single ENU solution to each pixel. Fusing LOS is mostly just for viewing purpose.

**Comment by wangshuaicumt** [comment]
Thanks
