### ISSUE TITLE
[Help]: The relationship between image resolution and surface deformation

### ISSUE THREAD

**Issue by KIKINEO** [gmtsar/gmtsar#671]
Hello, professors and teachers, as a beginner of insar, I have some questions about image resolution, and I hope to get your answers:
1. I want to use the image of Sentinel-1 satellite to use the pixel offset technology to obtain the deformation of the ground surface in the satellite azimuth and line of sight. Can this step be realized on gmtsar?
2. I have read some literature. The accuracy of the pixel offset technology is about one-tenth of the resolution of a pixel. The azimuth resolution of the Sentinel-1 satellite is about 15-20m, so the pixel offset Is the accuracy 1.5m-2m? That is to say, when the deformation of the ground is greater than 2m, the offset estimation using the Sentinel-1 satellite image will be displayed? Why can achieve the accuracy of one-tenth of the image resolution, I can not understand the accuracy of one-tenth, is this achieved through resampling? @dsandwell @leouieda @ericlindsey @mobigroup @Xiaohua-Eric-Xu

**Comment by Xiaohua-Eric-Xu** [comment]
You could use make_a_offset.csh to get xcorr estimates. The precision is roughly 1/10 pixel but it depends on the data quality and the approach too. xcorr in GMTSAR is a simple form of correlation calculation on spectral domain and will pop out results regardless of amplitude of shift (larger or smaller) or quality. There is a SNR(fake) number at the 5th column of outputs, which you could use to assess the quality.

**Comment by KIKINEO** [comment]
> You could use make_a_offset.csh to get xcorr estimates. The precision is roughly 1/10 pixel but it depends on the data quality and the approach too. xcorr in GMTSAR is a simple form of correlation calculation on spectral domain and will pop out results regardless of amplitude of shift (larger or smaller) or quality. There is a SNR(fake) number at the 5th column of outputs, which you could use to assess the quality.

Thank you Professor Xu for your help. Could you please explain to me why the accuracy can reach up to one-tenth of a pixel? I really appreciate it.

**Comment by Xiaohua-Eric-Xu** [comment]
When doing pixel tracking, there is interpolation so you could get to below a pixel.

**Comment by KIKINEO** [comment]
> When doing pixel tracking, there is interpolation so you could get to below a pixel.

many thanks~
