### ISSUE TITLE
[Help]: How to set a reference point to unwrap Interferograms

### ISSUE THREAD

**Issue by Rick0219** [gmtsar/gmtsar#672]
Hello, professors,I have a question for unwrapping Interferograms.
I have a reference point coordinate of latitude and longitude, how should I set it to use this reference point to  unwrap Interferograms？

**Comment by igps-ftk** [comment]
First convert longitude and latitude of the reference point to radar coordinates using proj_ll2ra_ascii.csh. Then subtract the value of that point from the whole interferogram using GMT grdmath command.

**Comment by PickleRickrx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by PickleRickrx** [comment]
> First convert longitude and latitude of the reference point to radar coordinates using proj_ll2ra_ascii.csh. Then subtract the value of that point from the whole interferogram using GMT grdmath command.

Thanks for your reply.But in the interferogram there are a lot of areas where the phase value is 0（like the phasefilter.png I post）, is it feasible for me to set a point to be 0?

![phasefilter](https://user-images.githubusercontent.com/93982725/222365138-37bee455-7b55-4052-808e-091277fb35b5.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I think it is only meaningful to set a point to zero after phase unwrapping. Radar phase comes as wrapped cycles from -pi to pi.
