### ISSUE TITLE
[Help]: SBAS data

### ISSUE THREAD

**Issue by wangshuaicumt** [gmtsar/gmtsar#673]
I got the SBAS result. I want to know the specific numerical data, but I can't read the *. grd file in the SBAS result using Python. Could you help me solve it？
thanks！

**Comment by Xiaohua-Eric-Xu** [comment]
I think Python has its netcdf library. Use that to read in the data for processing or viewing should be simple to do.

**Comment by wangshuaicumt** [comment]
Yeah, thanks. I think I should have done it., is it right?

<xarray.DataArray 'z' (lat: 1180, lon: 1910)>
[2253800 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 116.2 116.2 116.2 116.2 ... 117.2 117.2 117.2 117.2
  * lat      (lat) float64 35.48 35.48 35.48 35.48 ... 35.97 35.97 35.97 35.97
Attributes:
    long_name:     z
    actual_range:  [-153.15245056  136.86753845]

**Comment by wangshuaicumt** [comment]
> Yeah, thanks. I think I should have done it., is it right?
> 
> <xarray.DataArray 'z' (lat: 1180, lon: 1910)> [2253800 values with dtype=float32] Coordinates:
> 
> * lon      (lon) float64 116.2 116.2 116.2 116.2 ... 117.2 117.2 117.2 117.2
> * lat      (lat) float64 35.48 35.48 35.48 35.48 ... 35.97 35.97 35.97 35.97
>   Attributes:
>   long_name:     z
>   actual_range:  [-153.15245056  136.86753845]

Yeah, thanks. I think I should have done it., is it right?

<xarray.DataArray 'z' (lat: 1180, lon: 1910)>
[2253800 values with dtype=float32]
Coordinates:

lon (lon) float64 116.2 116.2 116.2 116.2 ... 117.2 117.2 117.2 117.2
lat (lat) float64 35.48 35.48 35.48 35.48 ... 35.97 35.97 35.97 35.97
Attributes:
long_name: z
actual_range: [-153.15245056 136.86753845]

**Comment by Xiaohua-Eric-Xu** [comment]
I am not a Python expert but if you are able to plot it out with matplotlib, then it should be right.

**Comment by wangshuaicumt** [comment]
> I am not a Python expert but if you are able to plot it out with matplotlib, then it should be right.

Yeah, thanks a lot. Have o good day!

**Comment by wangshuaicumt** [comment]
> I am not a Python expert but if you are able to plot it out with matplotlib, then it should be right.

I got the graph, but I feel like it's just trend and not real value.
![Figure_1](https://user-images.githubusercontent.com/117328108/222410967-bb275c09-dd29-41f9-b318-dc564baf5c82.png)

**Comment by Xiaohua-Eric-Xu** [comment]
There could be a large ramp in the solution due to 1) atmospheric noise. 2) plate motion. 3) unwrapping errors. 4) or not selecting a reference position. I would start with 4) and see how that'll change the solution.

**Comment by wangshuaicumt** [comment]
> There could be a large ramp in the solution due to 1) atmospheric noise. 2) plate motion. 3) unwrapping errors. 4) or not selecting a reference position. I would start with 4) and see how that'll change the solution.

Thanks, I will try.
