### ISSUE TITLE
[Help]: geocode.csh reported an error

### ISSUE THREAD

**Issue by KIKINEO** [gmtsar/gmtsar#674]
Hello, Professors,When I was performing geographic encoding on the unwrapped image, an error occurred. The first error message that popped up was 'grdmath: phase.grd is not a number, operator or file name.' Here are the specific details of my situation:
**OS and software version**
GMTSAR version: 6.2
GMT version: 6.4
Ubuntu version: 20.04
**Specific processing steps**

First use p2p_S1_TOPS_Frame.csh to do interference processing on the image, and choose to skip unwrapping and encoding in config
Then use snaphu.csh for unwrapping. The correlation threshold is set to 0.12 and the maximum discontinuity is set to 20.
Finally geocode with geocode.csh
In the above process, only errors occurred during the geocoding process. The initial error was also an error message like ‘grdmath: phase.grd is not a number, operator or file name’.
Attached is the log file I uploaded (log123 is the log file under the F123 folder, terminal1 is the terminal display when encoding is executed), can you help me point out the problem, this problem has troubled me for a long time, I look forward to your feedback reply，thank you very much~
[log1.txt](https://github.com/gmtsar/gmtsar/files/10867049/log1.txt)
[log2.txt](https://github.com/gmtsar/gmtsar/files/10867050/log2.txt)
[log3.txt](https://github.com/gmtsar/gmtsar/files/10867051/log3.txt)
[terminal1.txt](https://github.com/gmtsar/gmtsar/files/10867052/terminal1.txt)
@leouieda @ericlindsey @mobigroup @dsandwell @ikselven @Xiaohua-Eric-Xu

**Comment by mobigroup** [comment]
@KIKINEO You would try Python interface PyGMTSAR which is much easier for beginners and includes live Google Colab examples and Docker images available in just one click: https://github.com/mobigroup/gmtsar There is no installation required.

**Comment by wangshuaicumt** [comment]
> @KIKINEO You would try Python interface PyGMTSAR which is much easier for beginners and includes live Google Colab examples and Docker images available in just one click: https://github.com/mobigroup/gmtsar There is no installation required.

Emmm，thanks. And I want to ask, can we use PyGMTSAR to process the SBAS results that have been processed with GMTSAR？

**Comment by mobigroup** [comment]
@wangshuaicumt Potentially it is possible, but you need to write some code to load GMTSAR results and produce the geocoding matrices. Usually it is useless because PyGMTSAR provides powerful detrending and fast SBAS. The recommended way is to perform the full processing using PyGMTSAR, the ready-to-use recipes available on Google Colab and in Docker images and you need just to replace the source datasets with your own one.

See the live comparision between GMTSAR SBAS and PyGMTSAR SBAS results: https://colab.research.google.com/drive/1sljxm2jAMGXynq4EYam6Siz8OLcPLN0h?usp=sharing

```
# GMTSAR SBAS using "smooth" parameter
sbas.sbas(baseline_pairs, smooth=1)
```
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/7342379/222336966-c8e00aa0-7dea-4b77-a1d3-9d9ab8a89365.png">

```
# PyGMTSAR detrending plus Gaussian filtering 12000m
sbas.detrend_parallel(pairs, wavelength=12000)
# PyGMTSAR SBAS
sbas.sbas_parallel(pairs)
```
<img width="996" alt="image" src="https://user-images.githubusercontent.com/7342379/222337022-3443a73c-24fd-4d8b-b185-f125b2d10d40.png">

**Comment by wangshuaicumt** [comment]
> @wangshuaicumt Potentially it is possible, but you need to write some code to load GMTSAR results and produce the geocoding matrices. Usually it is useless because PyGMTSAR provides powerful detrending and fast SBAS. The recommended way is to perform the full processing using PyGMTSAR, the ready-to-use recipes available on Google Colab and in Docker images and you need just to replace the source datasets with your own one.
> 
> See the live comparision between GMTSAR SBAS and PyGMTSAR SBAS results: https://colab.research.google.com/drive/1sljxm2jAMGXynq4EYam6Siz8OLcPLN0h?usp=sharing
> 
> ```
> # GMTSAR SBAS using "smooth" parameter
> sbas.sbas(baseline_pairs, smooth=1)
> ```
> 
> <img alt="image" width="1019" src="https://user-images.githubusercontent.com/7342379/222336966-c8e00aa0-7dea-4b77-a1d3-9d9ab8a89365.png">
> 
> ```
> # PyGMTSAR detrending plus Gaussian filtering 12000m
> sbas.detrend_parallel(pairs, wavelength=12000)
> # PyGMTSAR SBAS
> sbas.sbas_parallel(pairs)
> ```
> 
> <img alt="image" width="996" src="https://user-images.githubusercontent.com/7342379/222337022-3443a73c-24fd-4d8b-b185-f125b2d10d40.png">

Thanks, and my research area is distributed on two tracks. I need to use PyGMTSAR to process the SBAS results one by one. Do PyGMTSAR support merging the SBAS results of the two tracks?

**Comment by mobigroup** [comment]
@wangshuaicumt I suppose you mean two orbits? Yes, we need to process them separately. GMTSAR/PyGMTSAR allows to merge subswaths and sequential orbit scenes only.

**Comment by wangshuaicumt** [comment]
> @wangshuaicumt I suppose you mean two orbits? Yes, we need to process them separately. GMTSAR/PyGMTSAR allows to merge subswaths and sequential orbit scenes only.

Thanks, yes, that's what I want to say. Do sequential orbit refer to tracks with continuous serial numbers? For example, 140 orbit and 141 orbit, is that right? If so, how to deal with the non-sequential orbits, such as orbit 40 and orbit 143?

**Comment by mobigroup** [comment]
@wangshuaicumt Only sequential scenes and sequential subswaths (12, 23, 123) for the same orbit (desc/asc) and path can be processed as a single frame (path 40 descending orbit for the case):

<img width="361" alt="image" src="https://user-images.githubusercontent.com/7342379/222348570-02a5d4d9-8455-430f-8cdf-3d6746e54fb4.png">
<img width="412" alt="image" src="https://user-images.githubusercontent.com/7342379/222348713-67a9dc3b-79f1-4572-8bf4-75a898442f6a.png">

Different orbits and paths cannot be processed together.

**Comment by wangshuaicumt** [comment]
> @wangshuaicumt Only sequential scenes and sequential subswaths (12, 23, 123) for the same orbit (desc/asc) and path can be processed as a single frame (path 40 descending orbit for the case):
> 
> <img alt="image" width="361" src="https://user-images.githubusercontent.com/7342379/222348570-02a5d4d9-8455-430f-8cdf-3d6746e54fb4.png">
> 
> <img alt="image" width="412" src="https://user-images.githubusercontent.com/7342379/222348713-67a9dc3b-79f1-4572-8bf4-75a898442f6a.png">
> 
> Different orbits and paths cannot be processed together.
Thanks, yes, I think I should do it programmatically, such as using Python language, to fuse the SBAS data of the two tracks through benchmark unification and data fusion, etc., but, in the SBAS folder, I don't know which data file to use The original data for track splicing. Before that, I used the vel_ll.grd file, but I couldn’t read its data in Python. I can only get a graphic when I open it with Surfer software. Is it possible to use vel_ll. grd as my raw data or something else?

**Comment by mobigroup** [comment]
That's easy to read NetCDF file vel_ll.grd:
```
import xarray as xr
da = xr.open_dataarray('vel_ll.grd')
da
```

and plot
```
da.plot()
```

**Comment by wangshuaicumt** [comment]
> That's easy to read NetCDF file vel_ll.grd:
> 
> ```
> import xarray as xr
> da = xr.open_dataarray('vel_ll.grd')
> da
> ```
> 
> and plot
> 
> ```
> da.plot()
> ```

Thanks a lot, I will try. Have a good day!

**Comment by wangshuaicumt** [comment]
> That's easy to read NetCDF file vel_ll.grd:
> 
> ```
> import xarray as xr
> da = xr.open_dataarray('vel_ll.grd')
> da
> ```
> 
> and plot
> 
> ```
> da.plot()
> ```

Hello,  the result I run is as follows, but did not draw a picture.

<xarray.DataArray 'z' (lat: 1180, lon: 1910)>
[2253800 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 116.2 116.2 116.2 116.2 ... 117.2 117.2 117.2 117.2
  * lat      (lat) float64 35.48 35.48 35.48 35.48 ... 35.97 35.97 35.97 35.97
Attributes:
    long_name:     z
    actual_range:  [-153.15245056  136.86753845]

**Comment by mobigroup** [comment]
Let’s try to define the actual data range for the plot (as printed).

**Comment by wangshuaicumt** [comment]
> Let’s try to define the actual data range for the plot (as printed).

Thanks, but I'm sorry to understand these results,  could you give me some tips?

**Comment by wangshuaicumt** [comment]
> Let’s try to define the actual data range for the plot (as printed).

Thanks a lot. I think I should have done it.
![image](https://user-images.githubusercontent.com/117328108/222388180-66412126-a6a4-4780-a78b-ceb9da4aea3a.png)

**Comment by mobigroup** [comment]
@wangshuaicumt I see only trend here and there is no useful information. You need to detrend your unwrapped phase grids before SBAS processing. Check the ticket #98

**Comment by wangshuaicumt** [comment]
> @wangshuaicumt I see only trend here and there is no useful information. You need to detrend your unwrapped phase grids before SBAS processing. Check the ticket #98

Thanks a lot. I will study.

**Comment by leouieda** [comment]
@KIKINEO please stop pinging a lot of individual people in the issues. This bypasses any configuration we set for notifications in GitHub and is considered a bit rude. Reserve that when you really do need the input of a particular person. Otherwise, people who want to answer questions here should be subscribed to this repository.

**Comment by KIKINEO** [comment]
> @KIKINEO please stop pinging a lot of individual people in the issues. This bypasses any configuration we set for notifications in GitHub and is considered a bit rude. Reserve that when you really do need the input of a particular person. Otherwise, people who want to answer questions here should be subscribed to this repository.

Sorry for my rudeness. I'll pay attention next time

**Comment by wangshuaicumt** [comment]
> @wangshuaicumt I see only trend here and there is no useful information. You need to detrend your unwrapped phase grids before SBAS processing. Check the ticket #98

Hello, may I ask if there are specific values in the vel_ll.grd obtained after SBAS processing? Why can't I get the value of each PS point after I read vel_ll.grd and draw it as a graph, it shows 'nan' on the terminal, what should I do?

**Comment by Xiaohua-Eric-Xu** [comment]
Try extract_one_time_series.csh in your SBAS directory. vel_ll.grd is a grid of line-of-sight velocities.
