### ISSUE TITLE
[Feature]: grdcut

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#675]
hi,dear professors,
I'd like to ask you a question. The settlement map I obtained is a rectangular map, but I only need the settlement results for the area I studied (irregular area). How to get it? grdcut can only crop rectangular areas. I want to get the graph shown below.
![image](https://user-images.githubusercontent.com/114629377/222439924-29eacb9c-74f5-4018-a452-23e1afb656da.png)

**Comment by PickleRickrx** [comment]
Maybe it shows like that just because geocoding?

**Comment by igps-ftk** [comment]
This is a GMT issue, not GMTSAR.
You should create a mask grid from your irregular polygon (use grdmask command), then mask out areas that you don't want. 
If you want GMTSAR to remove results over water body in interferograms, set the following in configuration file (e.g. batch_tops.config):
#use landmask (1 -- yes; else -- no)
switch_land = 1

Cheers,
Yunfeng Tian

**Comment by Luvina0503** [comment]
ok.i will try.thank you

**Comment by Luvina0503** [comment]
@igps-ftk @PickleRickrx 
If it's all land, what should I do if I want to block or remove some irregular land?

**Comment by Xiaohua-Eric-Xu** [comment]
Create a mask in geo-coordinates (lon, lat, elevation). Use `SAT_llt2rat` to project into radar coordinates (range, azimuth). Use `gmt grdmask` to create the mask in radar coordinates.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
command:gmt grdmask dempoint.txt -Rphasefilt.grd -I1 -N0/0/1 -Glandmask.grd -V
phasefilt.grd:
![image](https://user-images.githubusercontent.com/114629377/223436403-45ac61be-ff7f-4dc5-9bdb-0a6908a3458f.png)
dempoint.txt(Study area boundary point coordinates):
![image](https://user-images.githubusercontent.com/114629377/223436582-b92e1638-d204-44ff-a37b-5fb7babef9cd.png)

May I ask what is wrong with this order? The resulting landmask.grd file cannot be opened with ncview.

**Comment by Luvina0503** [comment]
command:ncview landmask.grd
error:
![image](https://user-images.githubusercontent.com/114629377/223439737-80b411d7-d08c-47eb-ae1c-a3beded274d8.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Did you use landmask.csh to generate the mask? If so you need to run that at a location where trans.dat file exists, I think.
