### ISSUE TITLE
[Help]: SBAS result

### ISSUE THREAD

**Issue by wangshuaicumt** [gmtsar/gmtsar#677]
![vel_ll - 副本](https://user-images.githubusercontent.com/117328108/223032233-258e65c6-2822-4f28-bccd-09841c9e5028.png)
In the vel_ll.grd file generated by SBAS, the part in the lower left corner is not particularly complete. What is the reason for this? is this result correct?

**Comment by Xiaohua-Eric-Xu** [comment]
Could it be the elevation? A square in radar coordinates is not a square in geocoordiantes. e.g. for the lower left corner, it could be that the elevation is higher so the same near_range actually looks further away from the satellite. You could check this by turning on the topography on Google Earth or *GIS.

**Comment by wangshuaicumt** [comment]
> Could it be the elevation? A square in radar coordinates is not a square in geocoordiantes. e.g. for the lower left corner, it could be that the elevation is higher so the same near_range actually looks further away from the satellite. You could check this by turning on the topography on Google Earth or *GIS.

Yeah. That piece is a snow mountain

**Comment by wangshuaicumt** [comment]
> Could it be the elevation? A square in radar coordinates is not a square in geocoordiantes. e.g. for the lower left corner, it could be that the elevation is higher so the same near_range actually looks further away from the satellite. You could check this by turning on the topography on Google Earth or *GIS.

Hello, May I ask if the color of this picture of vel_ll.grd can be light or dark?
