### ISSUE TITLE
Use a extract_one_time_series.csh script to extract the time series occurrence values of points

### ISSUE THREAD

**Issue by CUMT530849827** [gmtsar/gmtsar#679]
Hello professor, when I run this command in the SBAS folder, I get a null value I don't know how to solve this problem, can you solve it

![image](https://user-images.githubusercontent.com/49933485/223293815-a3c88428-ae32-4e72-abf8-750c6a4ba8ec.png)
![image](https://user-images.githubusercontent.com/49933485/223294073-eb66b416-2c39-47b3-8dd4-6d2f2209ff6e.png)
![image](https://user-images.githubusercontent.com/49933485/223294122-c2bb9b0a-fdf1-470b-aa19-fb7e6d35cc8d.png)
![image](https://user-images.githubusercontent.com/49933485/223294152-435531c6-9a52-48cc-92fa-a138770b267d.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Is 77.0498 37.1517 in an area with data? Maybe try a position in the middle of your vel_ll.grd.

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, strange. Could it be that that point happens to be NaN? If you run `gmt grdinfo vel_ll.grd`, what does it say? Could you try a few other locations too?
