### ISSUE TITLE
Unwrap_ll and LOS_ll    are not generated  in GMTSAR5.7

### ISSUE THREAD

**Issue by danni-sar** [gmtsar/gmtsar#68]
Dear all, 

When I run the command:

p2p_S1_TOPS_Frame.csh S1A_IW_SLC__1SDV_20200802T173712_20200802T173742_033731_03E8D6_BB95.SAFE S1A_OPER_AUX_RESORB_OPOD_20200802T210414_V20200802T154850_20200802T190620.EOF S1B_IW_SLC__1SDV_20200808T173642_20200808T173712_022835_02B578_8F40.SAFE  S1B_OPER_AUX_RESORB_OPOD_20200808T211425_V20200808T154808_20200808T190538.EOF config.s1a.txt vv 1

 I don't get the unwrap_mask_ll.grd  and  los_ll.grd  in the Merge Folder ..what's going wrong!!!!!

I need your suggestions please.

Cheers.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Danni,

Probably becasue I did not write in the script to produce los_ll.grd in the merge folder. If you want, you could look inside geocode.csh to see how those were generated. 
The mask was generated based on coherence, e.g. `gmt grdmath corr.grd 0.01 GE 0 NAN mask.grd MUL = mask2.grd `
Then the file need to be masked with the mask, e.g. `gmt grdmath unwrap.grd mask2.grd MUL = unwrap_mask.grd`
Then make projection, e.g. `proj_ra2ll.csh trans.dat unwrap_mask.grd unwrap_mask_ll.grd`
Then convert it to LOS, e.g. `gmt grdmath unwrap_mask_ll.grd $wave MUL -79.58 MUL = los_mask_ll.grd`
Cheers,
Xiaohua(Eric)

**Comment by danni-sar** [comment]
Hi Xiaohua,

Thanks for your reply , 

These commands work for me, but the ideal when it run automatically. Could I have the good script (geocode.csh) for GMTSAR5.7.

Best Regards.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi, geocode.csh is written for swath-wise interferogram. Essentially if all product exists in the merge folder, it'll run correctly. However, that means more merged product need to be generated. I'll try to add them to the master branch, maybe later this year.

**Comment by IamTariqAshraf** [comment]
Have a nice day Mr. Xiaohua-Eric-Xu, Hope everything is going good. I am trying to use GMTSAR process data in Mintpy. However I believe GMTSAR V5.8 s not generating corr.grd, corr_ll.grd , unwrap.grd and unwrap_ll.grd files. Any idea how to generate these files ?
Best Regards

**Comment by Xiaohua-Eric-Xu** [comment]
Did you install GMTSAR 5.8 with which version of GMT? It is recommended to use GMT6.x with GMTSAR 6.x or master.

**Comment by IamTariqAshraf** [comment]
Thank you so very much Mr.Xiaohua-Eric-Xu for your kind response. Since I am using ubuntu 16.04 version I installed gmt5. Maybe I have to upgrade the system. Sorry to bother you again but can you provide little insight about GAMMA processed files to be used in mintpy. Since I cant uderstand few of them. especially 
sim_20040207_4rlks.utm.dem.par    is it the .mli.par file? 
filt_20030329_20030503_4rlks.cor is it the filtered coherence file ? 
Much thanks. 
Best regards

**Comment by Xiaohua-Eric-Xu** [comment]
@IamTariqAshraf You probably need to contact @yununz for more details on this issue.

**Comment by IamTariqAshraf** [comment]
Thanks @Xiaohua-Eric-Xu, the issue was solved after several attempts. Thank you for your valuable insights about GMTSAR.
