### ISSUE TITLE
[Help]: vel_ll.grd data

### ISSUE THREAD

**Issue by wangshuaicumt** [gmtsar/gmtsar#680]
May I ask if there are specific values in the vel_ll.grd obtained after SBAS processing? Why can't I get the value of each PS point after I read vel_ll.grd and draw it as a graph, it shows 'nan' on the terminal, what should I do?

**Comment by Xiaohua-Eric-Xu** [comment]
Answered here: https://github.com/gmtsar/gmtsar/issues/674#issuecomment-1458061439.

BTW, I am not sure why you are asking the exact same question three times.

**Comment by wangshuaicumt** [comment]
Thanks for your answer. Sorry, maybe I'm a noob to github.




清风清纯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gmtsar/gmtsar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月7日(星期二) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gmtsar/gmtsar] [Help]: vel_ll.grd data (Issue #680)





 
Answered here: #674 (comment).
 
BTW, I am not sure why you are asking the exact same question three times.

**Comment by Xiaohua-Eric-Xu** [comment]
If you don't feel comfortable using Github, we have our contacts listed here: https://topex.ucsd.edu/gmtsar/contact.

**Comment by wangshuaicumt** [comment]
> If you don't feel comfortable using Github, we have our contacts listed here: https://topex.ucsd.edu/gmtsar/contact.

Thanks.
