### ISSUE TITLE
[Help]: landmask

### ISSUE THREAD

**Issue by wangshuaicumt** [gmtsar/gmtsar#681]
I need to process one swath, I needn't to merge, then how to use landmask.csh?

**Comment by Xiaohua-Eric-Xu** [comment]
Go to that subswath, e.g. F2 that has raw and topo directories in it, with the right files for processing. Simply run p2p_processing.csh to get the results. Use the config file to control the creation of landmask. I think the parameter is mask_water.

**Comment by debvrat** [comment]
The p2p_processing.csh requires a master and an aligned image. How do I know which is the aligned image; as there are multiple images that my master is paired with?

**Comment by debvrat** [comment]
> Go to that subswath, e.g. F2 that has raw and topo directories in it, with the right files for processing. Simply run p2p_processing.csh to get the results. Use the config file to control the creation of landmask. I think the parameter is mask_water.

The p2p_processing.csh looks for a variable called "switch_master" in the batch_tops.config file, which is not present.

**Comment by Xiaohua-Eric-Xu** [comment]
Sounds like you are doing a stack of images? The master image is the one you chose ahead of time. You may use preproc_batch_tops[_esd].csh to process the data and select a master image. Once you have an aligned stack, you can produce interferograms between any of them (theoretically). See this documentation for more details on how to cook a sentinel-1 time-series http://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf, you may ignore the merging part as you are only dealing with one subswath.
