### ISSUE TITLE
[Bug]: Hermite interpolation error on S1A_Stack_CPGF_T173 using example scripts

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#682]
Downloaded S1A_Stack_CPGF_T173 and ran README_prep.txt:

`./README_prep.txt > >(tee -a stdout.log) 2> >(tee -a stderr.log >&2)`

> hermite: interpolation not in center interval
> nan!

[stdout.log](https://github.com/gmtsar/gmtsar/files/10933194/stdout.log)
[stderr.log](https://github.com/gmtsar/gmtsar/files/10933196/stderr.log)

**Comment by Xiaohua-Eric-Xu** [comment]
Were you using the newest master branch or 6.2?

**Comment by mobigroup** [comment]
@SteffanDavies The example works in the GMTSAR Docker image: https://hub.docker.com/r/mobigroup/gmtsar
