### ISSUE TITLE
[Feature]: merge

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#683]
hi,dear professors,
i want to ask a question.
command:proj_ra2ll.csh trans.dat corr.grd corr_ll.grd

figure1：
![G6$1}$AG710X`}7TCQX70~I](https://user-images.githubusercontent.com/114629377/224336912-a5ed2bc9-7ef9-4686-a91d-de32ca462fc7.png)
figure 2:
![3673KHE12A7FPEO@8@F6CP](https://user-images.githubusercontent.com/114629377/224337237-6087e32c-368f-490b-9d13-a3cd16975c6d.png)

Figure 1 shows corr.grd in the F3 directory and Figure 2 shows corr.grd in the merge directory.
A problem is found in the figure: the corr_ll.grd coordinates coincide with the boundary before merging, but do not coincide with the boundary after merging. Why is that?

**Comment by Xiaohua-Eric-Xu** [comment]
Did you use the trans.dat in the merge directory? or trans.dat from F?/topo directory? The latter may give you geolocation errors after projection. Also it sometimes causes trouble if one do not set up range_dec and azimuth_dec in the config file for TOPS processing.

**Comment by Luvina0503** [comment]
this problem is solved.thank you
