### ISSUE TITLE
The return result of “organize_files_tops.csh” is org_mod: Undefined variable.

### ISSUE THREAD

**Issue by toma1li** [gmtsar/gmtsar#684]
My computer is a mac of m1
The log is as follows
organize_files_tops.csh SAFE_filelist ../reframed/pins.ll 1
org_mod: Undefined variable.

The pins.ll is
116.53 32.78
116.50 32.82

I guess the contents of pins.ll are wrong. What should be correct

**Comment by Xiaohua-Eric-Xu** [comment]
Feels like a bug from a specific version in the master branch? Maybe update the code or just that script from the newer commits? https://github.com/gmtsar/gmtsar/blob/master/gmtsar/csh/organize_files_tops.csh

**Comment by toma1li** [comment]
Thank you very much. It seems to work.But he prompted the following information, please tell me whether it will affect the follow-up results
==========================================
Checking query for existing orbit file...
...orbit file already exists...
 
make_s1a_tops: No match.
 Couldn't open xml file: 
 tmp2.PRM 
couldn't open master.PRM 
 
 Usage: SAT_llt2rat master.PRM prec [-bo[s|d]] < inputfile > outputfile  

             master.PRM   -  parameter file for master image and points to LED orbit file 
             precise      -  (0) standard back geocoding, (1) - polynomial refinenent (slower) 
             inputfile    -  lon, lat, elevation [ASCII] 
             outputfile   -  range, azimuth, elevation(ref to radius in PRM), lon, lat [ASCII default] 
             -bos or -bod -  binary single or double precision output (only output results within 
                             data coverage, PRM num_lines, num_rng_bins ) 
 
 example: SAT_llt2rat master.PRM 0 < topo.llt > topo.ratll    

 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: syntax error at source line 1
 context is
	{printf("%d",$2+0.5 + >>>  ) <<< 
awk: illegal statement at source line 1
make_s1a_tops: No match.
couldn't open master.PRM 
 
 Usage: SAT_llt2rat master.PRM prec [-bo[s|d]] < inputfile > outputfile  

             master.PRM   -  parameter file for master image and points to LED orbit file 
             precise      -  (0) standard back geocoding, (1) - polynomial refinenent (slower) 
             inputfile    -  lon, lat, elevation [ASCII] 
             outputfile   -  range, azimuth, elevation(ref to radius in PRM), lon, lat [ASCII default] 
             -bos or -bod -  binary single or double precision output (only output results within 
                             data coverage, PRM num_lines, num_rng_bins ) 
 
 example: SAT_llt2rat master.PRM 0 < topo.llt > topo.ratll    

 Couldn't open xml file: 
 tmp2.PRM 
couldn't open master.PRM 
 
 Usage: SAT_llt2rat master.PRM prec [-bo[s|d]] < inputfile > outputfile  

             master.PRM   -  parameter file for master image and points to LED orbit file 
             precise      -  (0) standard back geocoding, (1) - polynomial refinenent (slower) 
             inputfile    -  lon, lat, elevation [ASCII] 
             outputfile   -  range, azimuth, elevation(ref to radius in PRM), lon, lat [ASCII default] 
             -bos or -bod -  binary single or double precision output (only output results within 
                             data coverage, PRM num_lines, num_rng_bins ) 
 
 example: SAT_llt2rat master.PRM 0 < topo.llt > topo.ratll    

 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: syntax error at source line 1
 context is
	{printf("%d",$2+0.5 + >>>  ) <<< 
awk: illegal statement at source line 1
grep: tmp2.PRM: No such file or directory
if: Expression Syntax.
li@Updebijibendiannao data % couldn't open master.PRM 
 
 Usage: SAT_llt2rat master.PRM prec [-bo[s|d]] < inputfile > outputfile  

             master.PRM   -  parameter file for master image and points to LED orbit file 
             precise      -  (0) standard back geocoding, (1) - polynomial refinenent (slower) 
             inputfile    -  lon, lat, elevation [ASCII] 
             outputfile   -  range, azimuth, elevation(ref to radius in PRM), lon, lat [ASCII default] 
             -bos or -bod -  binary single or double precision output (only output results within 
                             data coverage, PRM num_lines, num_rng_bins ) 
 
 example: SAT_llt2rat master.PRM 0 < topo.llt > topo.ratll

**Comment by toma1li** [comment]
Thank you very much. It seems to have worked.But he prompted the following information, please tell me whether it will affect the follow-up results.
=======================================
Checking query for existing orbit file...
...orbit file already exists...
 
make_s1a_tops: No match.
 Couldn't open xml file: 
 tmp2.PRM 
couldn't open master.PRM 
 
 Usage: SAT_llt2rat master.PRM prec [-bo[s|d]] < inputfile > outputfile  

             master.PRM   -  parameter file for master image and points to LED orbit file 
             precise      -  (0) standard back geocoding, (1) - polynomial refinenent (slower) 
             inputfile    -  lon, lat, elevation [ASCII] 
             outputfile   -  range, azimuth, elevation(ref to radius in PRM), lon, lat [ASCII default] 
             -bos or -bod -  binary single or double precision output (only output results within 
                             data coverage, PRM num_lines, num_rng_bins ) 
 
 example: SAT_llt2rat master.PRM 0 < topo.llt > topo.ratll    

 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: syntax error at source line 1
 context is
	{printf("%d",$2+0.5 + >>>  ) <<< 
awk: illegal statement at source line 1
make_s1a_tops: No match.
couldn't open master.PRM 
 
 Usage: SAT_llt2rat master.PRM prec [-bo[s|d]] < inputfile > outputfile  

             master.PRM   -  parameter file for master image and points to LED orbit file 
             precise      -  (0) standard back geocoding, (1) - polynomial refinenent (slower) 
             inputfile    -  lon, lat, elevation [ASCII] 
             outputfile   -  range, azimuth, elevation(ref to radius in PRM), lon, lat [ASCII default] 
             -bos or -bod -  binary single or double precision output (only output results within 
                             data coverage, PRM num_lines, num_rng_bins ) 
 
 example: SAT_llt2rat master.PRM 0 < topo.llt > topo.ratll    

 Couldn't open xml file: 
 tmp2.PRM 
couldn't open master.PRM 
 
 Usage: SAT_llt2rat master.PRM prec [-bo[s|d]] < inputfile > outputfile  

             master.PRM   -  parameter file for master image and points to LED orbit file 
             precise      -  (0) standard back geocoding, (1) - polynomial refinenent (slower) 
             inputfile    -  lon, lat, elevation [ASCII] 
             outputfile   -  range, azimuth, elevation(ref to radius in PRM), lon, lat [ASCII default] 
             -bos or -bod -  binary single or double precision output (only output results within 
                             data coverage, PRM num_lines, num_rng_bins ) 
 
 example: SAT_llt2rat master.PRM 0 < topo.llt > topo.ratll    

 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: syntax error at source line 1
 context is
	{printf("%d",$2+0.5 + >>>  ) <<< 
awk: illegal statement at source line 1
grep: tmp2.PRM: No such file or directory
if: Expression Syntax.
li@Updebijibendiannao data % couldn't open master.PRM 
 
 Usage: SAT_llt2rat master.PRM prec [-bo[s|d]] < inputfile > outputfile  

             master.PRM   -  parameter file for master image and points to LED orbit file 
             precise      -  (0) standard back geocoding, (1) - polynomial refinenent (slower) 
             inputfile    -  lon, lat, elevation [ASCII] 
             outputfile   -  range, azimuth, elevation(ref to radius in PRM), lon, lat [ASCII default] 
             -bos or -bod -  binary single or double precision output (only output results within 
                             data coverage, PRM num_lines, num_rng_bins ) 
 
 example: SAT_llt2rat master.PRM 0 < topo.llt > topo.ratll

**Comment by toma1li** [comment]
Thank you very much, it works
