### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by Atif5100** [gmtsar/gmtsar#687]
**Describe the problem you met**hello i am running scripts on  1 year dataset of Sentinel 1  using GMTSAR while running step 5 "Selecting a Reference Image from a Baseline Plot" it is giving same error for F1,F2 and F3 directory can anyone help on it thank you.

Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.gmtsar-user@gmtsarVB:/media/gmtsar-user/WORKDIR/asc/F1/raw$ ln -s ../../data/F*/*.SAFE/*/*iw1*vv*xml .

ln -s ../../data/F*/*.SAFE/*/*iw1*vv*tiff .

ln -s ../../data/*EOF .

ln -s ../topo/dem.grd

ln: failed to create symbolic link './*iw1*vv*xml': Invalid argument

ln: failed to create symbolic link './*iw1*vv*tiff': Invalid argument

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210308T152922_V20180803T225942_20180805T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210308T191955_V20180815T225942_20180817T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210308T231002_V20180827T225942_20180829T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210309T030104_V20180908T225942_20180910T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210309T065020_V20180920T225942_20180922T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210309T104046_V20181002T225942_20181004T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210309T142830_V20181014T225942_20181016T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210309T220819_V20181107T225942_20181109T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210310T020256_V20181119T225942_20181121T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210310T055425_V20181201T225942_20181203T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210310T095253_V20181213T225942_20181215T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210310T134152_V20181225T225942_20181227T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210310T173415_V20190106T225942_20190108T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210310T212321_V20190118T225942_20190120T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210311T011420_V20190130T225942_20190201T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210311T051016_V20190211T225942_20190213T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210311T090313_V20190223T225942_20190225T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210311T125124_V20190307T225942_20190309T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210311T162022_V20190319T225942_20190321T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210311T200631_V20190331T225942_20190402T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210311T235241_V20190412T225942_20190414T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210312T032929_V20190424T225942_20190426T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210312T071612_V20190506T225942_20190508T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210312T110705_V20190518T225942_20190520T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210312T155101_V20190530T225942_20190601T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210330T151430_V20190611T225942_20190613T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210330T191728_V20190623T225942_20190625T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210330T231303_V20190705T225942_20190707T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210331T031532_V20190717T225942_20190719T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210331T071513_V20190729T225942_20190731T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210331T112646_V20190810T225942_20190812T005942.EOF': File exists

ln: failed to create symbolic link './S1A_OPER_AUX_POEORB_OPOD_20210331T153511_V20190822T225942_20190824T005942.EOF': File exists

ln: failed to create symbolic link './dem.grd': File exists

gmtsar-user@gmtsarVB:/media/gmtsar-user/WORKDIR/asc/F1/raw$ 

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
` ln -s ../../data/F*/.SAFE//iw1vv*xml .` 
Should it be 
` ln -s ../../data/F*/*.SAFE/*iw1*vv*xml .`

**Comment by Atif5100** [comment]
It worked Thankyou
