### ISSUE TITLE
[Help]: When i run "dem2topo_ra.csh", the terminal show “psconvert [ERROR]: Cannot execute Ghostscript (gs).”

### ISSUE THREAD

**Issue by toma1li** [gmtsar/gmtsar#689]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/127527357/224878164-f3f5af1e-a89e-4636-9a01-6d92d9796cc0.png">

**Comment by toma1li** [comment]
After installing the software, it can work
<img width="579" alt="image" src="https://user-images.githubusercontent.com/127527357/224880383-3337fdeb-2780-4fe5-9721-ea27a9000306.png">

**Comment by Xiaohua-Eric-Xu** [comment]
This should only affect plotting. Data processing will not get affected. GS should be installed with GMT, not sure how it's missing.
