### ISSUE TITLE
[Help]: How to use gmt to resample the two ascending and descending images processed by gmtsar to the same range

### ISSUE THREAD

**Issue by KIKINEO** [gmtsar/gmtsar#692]
Hello, professors, after a long time of processing, I have obtained the deformation results of the two ascending and descending orbits in the research area. I wonder if there is a function in gmt that can realize the transformation of the two images under the same coordinate system The image is resampled to the same range, how to achieve it, I will be very grateful for your help and comments~

**Comment by Xiaohua-Eric-Xu** [comment]
You'll need to first figure out their common range with `gmt grdinfo -I- $your_grid`. Then run `gmt grdsample $your_grid -R$xmin/$xmax/$ymin/$ymax -I$inc -G$output_grid`. Here every $ is associated with something that needs your input. $inc specifically means the spatial sampling spacing.

**Comment by KIKINEO** [comment]
> You'll need to first figure out their common range with `gmt grdinfo -I- $your_grid`. Then run `gmt grdsample $your_grid -R$xmin/$xmax/$ymin/$ymax -I$inc -G$output_grid`. Here every $ is associated with something that needs your input. $inc specifically means the spatial sampling spacing.

Dear Professor Xu, thank you for your suggestion. In addition, I still have a small question I want to ask for your help, that is how to download the DEM over 4°: Since my research area is roughly 4°×5° Therefore, it cannot be downloaded directly from the official website[https://topex.ucsd.edu/gmtsar/demgen/](url)。

**Comment by Xiaohua-Eric-Xu** [comment]
> Dear Professor Xu, thank you for your suggestion. In addition, I still have a small question I want to ask for your help, that is how to download the DEM over 4°: Since my research area is roughly 4°×5° Therefore, it cannot be downloaded directly from the official website[https://topex.ucsd.edu/gmtsar/demgen/](x-webdoc://DEC7E987-45C2-46BB-B49C-FDA4D6F42F18/url)。

Saw this in email but somehow here it is missing. You could run `make_dem.csh` which will acquire 1-s DEM data from U-Hawaii.

**Comment by KIKINEO** [comment]
Dear Professor Xu,Forgive my late reply，i get it , thank you very much for your help

**Comment by KIKINEO** [comment]
> > Dear Professor Xu, thank you for your suggestion. In addition, I still have a small question I want to ask for your help, that is how to download the DEM over 4°: Since my research area is roughly 4°×5° Therefore, it cannot be downloaded directly from the official websitehttps://topex.ucsd.edu/gmtsar/demgen/。
> 
> Saw this in email but somehow here it is missing. You could run `make_dem.csh` which will acquire 1-arcsecond DEM data from U-Hawaii.

Hello, Professor Xu, I tried to use the `make_dem.csh` script to get the dem, but I encountered some problems, can I ask you for advice?
1. First of all, is the dem obtained from 
different from the dem obtained from [topex](https://topex.ucsd.edu/gmtsar/demgen/) in terms of elevation information, the picture below is the same one I intercepted The elevation information of the two dem obtained in different ways in the region, will these two different elevation information cause differences in the results when processing the sar data?
2. There is another request to use `grd2kml.csh`, my original intention is to get the same kml file provided by [topex](https://topex.ucsd.edu/gmtsar/demgen/) can be displayed in The result on Google Earth, then I started to try to use `grd2kml.csh` to achieve it, I first used `gmt makecpt -Cgeo -Tmin/max >dem.cpt` to get the cpt file, and then in `grd2kml.csh `I made an input on Google Earth, but the result displayed on Google Earth is not ideal, as shown in the picture below, I would like to ask you how I can get the ideal sum [topex](https://topex.ucsd.edu/gmtsar /demgen/) has the same effect as the kml file, thank you very much~
![topex](https://user-images.githubusercontent.com/107243861/229102057-19c5f204-a251-4559-a19f-b8e52b040f01.png)
![U-Hawaii](https://user-images.githubusercontent.com/107243861/229102061-15cf33a8-2cb1-4fbe-89e2-6a5575a7affb.png)
![kml](https://user-images.githubusercontent.com/107243861/229102052-96c0ba83-a7f9-424e-9616-e4531c94b384.png)

**Comment by Xiaohua-Eric-Xu** [comment]
> 2\. gmt makecpt -Cgeo -Tmin/max >dem.cpt

Did you define min and max? 

Also which one is top and which one is bottom? The second one might be wrong as I don't think the z values range from 23-37 for a DEM. If you run `gmt grdmath dem.grd 0 ADD = dem.grd`, it may recalculate these numbers for the grid. Another way is to ncview both of them and check on the differences.

**Comment by KIKINEO** [comment]
> > 2. gmt makecpt -Cgeo -Tmin/max >dem.cpt
> 
> Did you define min and max?
> 
> Also which one is top and which one is bottom? The second one might be wrong as I don't think the z values range from 23-37 for a DEM. If you run `gmt grdmath dem.grd 0 ADD = dem.grd`, it may recalculate these numbers for the grid. Another way is to ncview both of them and check on the differences.

Hello, Professor Xu, you are right, the above is what I downloaded from topex, and the bottom is what I got by using `make_dem.csh`, after using the command `gmt grdmath dem.grd 0 ADD = dem.grd` for the following dem , the z value still hasn't changed, I'm trying to do a self-test to see what's wrong. In addition, if the value I got is within the normal range, should the value of the dem be consistent with the one downloaded from topex? Thank you for your timely reply~

**Comment by Xiaohua-Eric-Xu** [comment]
Your grid looks like geoid. Could it be that the download from the Hawaii site failed somehow? The lot looks OK to me. @PaulWessel Any idea what went wrong?

**Comment by PaulWessel** [comment]
Sorry, not sure what make_dem.csh might do but cannot understand if it would pick a geoid data set instead of DEM?

**Comment by Xiaohua-Eric-Xu** [comment]
What it does is really simple, cut the 1s earth relief, sample the geoid and add them together. 
```
gmt grdcut @earth_relief_01s $R -Gdem_ortho.grd -V
gmt grdsample $sharedir/geoid_egm96_icgem.grd -Rdem_ortho.grd -Ggeoid_resamp.grd -V
gmt grdmath -V dem_ortho.grd geoid_resamp.grd ADD = dem.grd
```
I just ran the command locally and it worked fine. My suspicion is the prior download may failed and left a ghost relief grid stored locally but I am not sure. Is there a way to clean up the local copy of the remote grids? Maybe just delete everything at /Users/usr_name/.gmt/server/earth/earth_relief/earth_relief_01s_g/*.nc

**Comment by KIKINEO** [comment]
> What it does is really simple, cut the 1s earth relief, sample the geoid and add them together.
> 
> ```
> gmt grdcut @earth_relief_01s $R -Gdem_ortho.grd -V
> gmt grdsample $sharedir/geoid_egm96_icgem.grd -Rdem_ortho.grd -Ggeoid_resamp.grd -V
> gmt grdmath -V dem_ortho.grd geoid_resamp.grd ADD = dem.grd
> ```
> 
> I just ran the command locally and it worked fine. My suspicion is the prior download may failed and left a ghost relief grid stored locally but I am not sure. Is there a way to clean up the local copy of the remote grids? Maybe just delete everything at /Users/usr_name/.gmt/server/earth/earth_relief/earth_relief_01s_g/*.nc
> 
> ![image](https://user-images.githubusercontent.com/16844111/229663440-4dd4fd58-18ba-467a-a388-e020bbebd10d.png)

Oh my God! Professor Xu, you are right, your advice has solved my problem, thank you very much!
