### ISSUE TITLE
make_dem[Help]: 

### ISSUE THREAD

**Issue by Congzhangg** [gmtsar/gmtsar#693]
Dear frofesser
         When I used the command make_dem.csh, I reported the error as shown in the picture below. Is it the problem of my software?  The GMT version is 6.0.0.
![1679108232556](https://user-images.githubusercontent.com/112800803/226080823-10f2f948-ce9b-4b56-ac85-93cbe78b1dd2.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Since this was implemented after gmt 6.4 or later, maybe try a later version? It'll require downloading the DEM from University of Hawaii so also make sure you have good Internet connection. Otherwise, maybe use the topex site for DEM generation.
