### ISSUE TITLE
[Help]: correct vel.grd with GPS station

### ISSUE THREAD

**Issue by Congzhangg** [gmtsar/gmtsar#694]
@Xiaohua-Eric-Xu @kguns32 
Dear Professor, I have obtained the rate diagram of the research area by using the data of rail ascending and rail descending respectively. Now I want to use GNSS data to correct the results. 
The GNSS station information is shown in Figure 1. I transferred the information to the LOS directions of the ascending and descending rails respectively, and the results were quite different (as shown in Figure 2, the left side is the projection to the ascending rail LOS, while the right side is the descending rail). Is this normal?
![0bbecbbe21e8b35f0ffb2e81d877ae0](https://user-images.githubusercontent.com/112800803/226083130-b089f540-ec66-439d-8397-a9b2f1fe8d67.png)
![image](https://user-images.githubusercontent.com/112800803/226083184-84393b73-8d32-41e7-91a1-fa04c16f00e9.png)

**Comment by Xiaohua-Eric-Xu** [comment]
It depends on what your AOI is. If it has strong horizontal deformation in E/W direction then probably yes. If the area is dominated with vertical then they may have similar sign.

**Comment by Congzhangg** [comment]
Hello, my research area is a mountainous area, Mount Fuji

**Comment by Xiaohua-Eric-Xu** [comment]
Your GNSS data seems to indicate this area's moving southwest ward. So for ascending, the numbers should be negative and for descending the numbers should be positive.

**Comment by Congzhangg** [comment]
OK，thank you for your reply
