### ISSUE TITLE
[Feature]: some questions

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#696]
hi,dear professors,
I'd like to ask you a question.
62 SAR images, with the numbers 1-62 instead.
Figure 1: lonlat is the longitude and latitude of the midpoint of phasefilt.grd, npoints*2;
Figure 2: order is the index of interferogram generation pairs,nintf*2;
Figure 3: PhU is the interferogram after unentanglement, 

figure 1
![mmexport1679278186535](https://user-images.githubusercontent.com/114629377/226232199-25ef064b-b438-4a1f-ba72-bc99de2ff93c.png)
figure 2
![mmexport1679278191981](https://user-images.githubusercontent.com/114629377/226232237-5da08491-aaa8-426e-9544-7477c855c3b4.png)
figure 3
![mmexport1679278195000](https://user-images.githubusercontent.com/114629377/226232259-9852d3cc-5b52-4916-a9e9-86733c30a1ac.png)

What I would like to ask is:
(1) What command can be used to obtain the PhU file in Figure 3 in the terminal? Is the command operation on the unwrap.grd file?
(2) How to obtain the vertical baseline of each interference pair?

I am looking forward to hearing from you.

**Comment by Xiaohua-Eric-Xu** [comment]
To extract a point from a grid, try `gmt grdtrack`. 
To get baseline information, try baseline_table.csh.
