### ISSUE TITLE
sbas_parallel argument to output necessary RAM before processing

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#698]
@Xiaohua-Eric-Xu  Could we have a sbas_parallel argument to estimate RAM usage without jumping to processing? This was it would be possible to choose between -mmap using a script depending on host memory.

**Comment by Xiaohua-Eric-Xu** [comment]
I thought I added that to sbas_parallel.c already. Do you mean to just run a memory estimate and then quit?

```
221    Mem = Mem/1024/1024/1024;
222    printf("Required Memory Usage is %.6f GB ...\n", Mem);
```

**Comment by SteffanDavies** [comment]
> I thought I added that to sbas_parallel.c already. Do you mean to just run a memory estimate and then quit?
> 
> ```
> 221    Mem = Mem/1024/1024/1024;
> 222    printf("Required Memory Usage is %.6f GB ...\n", Mem);
> ```

Yes, is there an option for this?

**Comment by Xiaohua-Eric-Xu** [comment]
Currently it is not an option, sbas_parallel.c will just pop out the message always I think.
