### ISSUE TITLE
[Feature]: sbas result

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#699]
hi,dear professors,
i want to ask some quesitons.
FIG. 1 is the settlement diagram obtained after unwinding under F1/intf_all;
FIG. 2 is the settlement diagram obtained after merging F1 and F2.
The study area is located in the coastal region. At first, I thought that the research area was distributed in both F1 and F2 strips, but later I found that it was only distributed in F1 strips, and F2 strips were all oceans. Therefore, sedimentation analysis is directly carried out on F1 strip.

figure1
![5P`EV56~3QCLFR@{2AW9K)Y](https://user-images.githubusercontent.com/114629377/226783544-2bccf899-ff83-4682-a2b4-239c61d52040.png)

figure 2
![}2M)``Z~ TN EXBD6S}_RH](https://user-images.githubusercontent.com/114629377/226783617-344dee04-1740-4b2d-867a-8283cfd1bedb.png)

By comparing Figure 1 and Figure 2, the following problems can be found:
1. The settlement rate of the two diagrams is different, and the distribution is quite different. What causes this? In this process, the operation steps and parameters are consistent.
2. It is found in Figure 2 that there are obvious errors in the settlement of the lower left corner. What causes this?

**Comment by Xiaohua-Eric-Xu** [comment]
Questions: 1. Did you select a ref location or detrend your interferograms? 2. The rate may not be reflecting only ground deformation. Errors from atmospheric noise, phase unwrapping, could affect the velocity too.

**Comment by Luvina0503** [comment]
1. Create a mask: stack_coherence_mask.csh corr_list 0.075
According to the picture, is this mask a big problem? Do you need to adjust it? Are mask_def.grd and landmask_ra.grd redundant or conflicting?
mask_def.grd:
![6`D_@HY RG7B3HFJ3)%E~LL](https://user-images.githubusercontent.com/114629377/227684385-0c189e68-5cdd-4858-8d9a-7b01eb941b30.png)
landmask_ra.grd:
![K3SA1)LI X92OTCP}~N_HGI](https://user-images.githubusercontent.com/114629377/227684456-4a9d56ae-2146-4b75-b4dd-ada7fafa2377.png)

2. Atmospheric correction command: GACOS_correction.csh intflist /media/gmtsar/Elements/Work/171106/gacosdata/ /media/gmtsar/Elements/Work/171106/F1/topo1/ ref_point 40.04
Correction object: phasefilt.grd
Question: Am I using the wrong reference point based on the incident Angle? I read a review earlier that the Angle of incidence is around 37. So does my Angle of incidence affect my settlement?

3. Unwrap: snaphu_interp.csh 0.01 0
Unwrap object: phasefilt_gacos_correct.grd
Question: Did I set the threshold too small? Or is it because the mask_def.grd above is not selected well, which affects the settlement result of a large area error?

Looking forward to hearing from you! Thank you

**Comment by Xiaohua-Eric-Xu** [comment]
1. I think the mask looks OK.
2. I think you need to manually shift the interferograms to really apply the reference selection. The script you used might be bring the correction to the same reference point rather than really helping you apply the reference selection.
3. If you've used mask_def.grd to apply mask, then the threshold should be as small as possible. 

The difference (I wouldn't call it an error) is likely because you did not select a reference, and the ambiguities from phase unwrapping is acting as a bias to the time-series and velocity product.

**Comment by Luvina0503** [comment]
> 1. I think the mask looks OK.
> 2. I think you need to manually shift the interferograms to really apply the reference selection. The script you used might be bring the correction to the same reference point rather than really helping you apply the reference selection.
> 3. If you've used mask_def.grd to apply mask, then the threshold should be as small as possible.
> 
> The difference (I wouldn't call it an error) is likely because you did not select a reference, and the ambiguities from phase unwrapping is acting as a bias to the time-series and velocity product.

Can you elaborate on what number 2 means? I don't quite see what you mean. Thank you

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
filter=200 in batch_tops.config. Check whether the filter value needs to be adjusted by comparing these two groups of winding phase diagrams.

![IG`UY3~O4$@UCMY086(~SR6](https://user-images.githubusercontent.com/114629377/228707558-cb0f717e-a175-4244-8971-0d2065c7f3da.png)
![ZTMTNWPM%K@M5NDC`587$SJ](https://user-images.githubusercontent.com/114629377/228707590-9c10f018-6ef6-4c52-bb0c-028999547739.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Did you run grdmath to shift your unwrap.grd? i.e., select a reference location, e.g., range = 10000 azimuth = 8000, then run `echo 10000 8000 | gmt grdtrack -G unwrap.grd`, get the value and then run `gmt grdmath unwrap.grd $value SUB = unwrap_pin.grd`?

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
Command: ncview unwrap.grd unwrap_pin-grd
Figure 1:
![A~}730MBD A`G03OWMEG%2Q](https://user-images.githubusercontent.com/114629377/229004422-14f1730c-4657-40f7-a978-408396807f95.png)

The top image in Figure 1 is unwrap.grd, and the bottom image is unwrap_pin-grd via grdmath. I would like to ask a few questions: What does this step mean? What does unwrap_pin.grd do? Should I use the unwrap_pin.grd file with the sbas command? I am looking forward to hearing from you. thank you

**Comment by Xiaohua-Eric-Xu** [comment]
> What does this step mean? What does unwrap_pin.grd do? Should I use the unwrap_pin.grd file with the sbas command? I am looking forward to hearing from you. thank you

This is to reference your data. After this step the signal is considered as relative to that pin (or point or pixel or area) in ITRF. And yes you should use the pined files for sbas. Do note an overall plate motion still partially exist in the data. 

> And does this reference point need to be consistent with the reference points in the GACOS correction?

Yes.

**Comment by Luvina0503** [comment]
ok.thank you! i will try.

**Comment by Luvina0503** [comment]
@Xiaohua-Eric-Xu 
SAR image 10 scenes, interference pair 30
The following is the phasefilt_GACOS_corrected.grd for all interference pairs after GACOS correction.
figure1:
![image](https://user-images.githubusercontent.com/114629377/229965617-c0e724ce-3e48-480a-89c1-01de74cee33c.png)

figure2:
![image](https://user-images.githubusercontent.com/114629377/229965718-84338ac0-4974-4f94-8252-29a0fab25f20.png)

figure3:
![image](https://user-images.githubusercontent.com/114629377/229966653-85427466-6663-42fd-a9ff-29523f310928.png)

I would like to ask: According to Figure 3(sbas/vel_ll.grd), the error of sbas results mainly lies in the lower part of the study area. Correspondingly, according to the comparison between Figure 1 and Figure 2, do I need to discard some interference pairs before proceeding with sbas? So which interference pairs in FIG. 1 and FIG. 2 should I better discard?
I look forward to hearing from you. thank you

**Comment by Luvina0503** [comment]
This is the corresponding unwrap.grd.
![image](https://user-images.githubusercontent.com/114629377/229968559-51dad51a-5ef6-4725-983a-416c4aed3102.png)

**Comment by Luvina0503** [comment]
This is the corresponding unwrap.grd.
![image](https://user-images.githubusercontent.com/114629377/229979830-d83296eb-2a8c-4948-b270-b724b370db48.png)
![image](https://user-images.githubusercontent.com/114629377/229979852-d29e92ee-eaf8-47ac-ad67-34e6d5775b22.png)
![image](https://user-images.githubusercontent.com/114629377/229979873-01a0a8e2-6b76-4f56-8933-59cd14a8848f.png)

**Comment by Xiaohua-Eric-Xu** [comment]
> So which interference pairs in FIG. 1 and FIG. 2 should I better discard?

You may need to let us know what Fig 1 and Fig 2 are.

I don't think you should discard any of the data, but rather try figure out a way to get useful information out of the data. Usually atmospheric noise are associated with specific dates. If you do discard, then all interferograms associated with that date may be gone. You could check on the aps_****.grd produced by sbas and see whether that give you a good estimate of atmospheric noise.

**Comment by Luvina0503** [comment]
Figures 1 and 2 is phasefilt_gacos_correct.grd.

**Comment by Luvina0503** [comment]
You're right. I shouldn't throw out some interferogram. I think I should set an appropriate mask threshold, hide the low coherence points, keep the high coherence points, and then unwrap. Is that right?

**Comment by Xiaohua-Eric-Xu** [comment]
That's one way, but overall the resulting velocity grid should contain more than just localized deformation (e.g. subsidence from ground water withdraw). You may also get, mid-large scale deformation, residual topographic error, seasonally varying water vapor, etc.

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu 
> Do note an overall plate motion still partially exist in the data.

Maybe do you know a good visualization for it? That’s not so easy to illustrate how significantly constant plate motion affects LOS displacement when we are looking for varying local deformations in presence of noise.

**Comment by Xiaohua-Eric-Xu** [comment]
Maybe this is what you are looking for? https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2022GL099835

**Comment by mobigroup** [comment]
Thanks, it helps!
