### ISSUE TITLE
something maybe wrong in swatch1?

### ISSUE THREAD

**Issue by insar-dev** [gmtsar/gmtsar#70]
i have run app use the following data:
1. S1A_IW_SLC__1SDV_20180225T115820_20180225T115847_020763_02395C_6609.SAFE
2. S1A_IW_SLC__1SDV_20200227T115832_20200227T115859_031438_039E8E_8A14.SAFE
3.S1A_OPER_AUX_POEORB_OPOD_20180317T120849_V20180224T225942_20180226T005942.EOF
4.S1A_OPER_AUX_POEORB_OPOD_20200318T120955_V20200226T225942_20200228T005942.EOF

after processed swatch1, i found the phase result is wrong，
i have also processed swath2, the result is ok.
is there something wrong in data or app? 
thanks.
![image](https://user-images.githubusercontent.com/1676595/99139352-d2d16e80-2672-11eb-8468-05ef46e500da.png)

**Comment by insar-dev** [comment]
swatch2 phase:
![image](https://user-images.githubusercontent.com/1676595/99140088-52623c00-2679-11eb-9006-334b64ee431b.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Does turning on the ESD option in the config file fix the problem?

**Comment by insar-dev** [comment]
i first use the script "preproc_batch_tops_esd.csh", then use "intf_tops.csh",could you tell me where to turn on the ESD option.
thanks for your help.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @insar-dev , if you ran preproc_batch_tops_esd.csh, it should ran the ESD. What mode did you specify? Usually we use median, or, in condition of varying a_shift (potentially from ionosphere), interpolation.

**Comment by insar-dev** [comment]
I specified average mode, i will try other modes.
thank you very much.
