### ISSUE TITLE
[Help]: Installation problem on Ubuntu 20.04

### ISSUE THREAD

**Issue by janardanroy** [gmtsar/gmtsar#700]
I am getting the following error,
**_ERROR: Could not find a version that satisfies the requirement pygmtsar (from versions: none)
ERROR: No matching distribution found for pygmtsar_**

I am following these steps:
[link](https://mobigroup.github.io/gmtsar/)

**My machine configuration:**
ubuntu 20.04
Python 3.6.13
16 GB RAM
Please let me know how to overcome this problem.

**Comment by Xiaohua-Eric-Xu** [comment]
You seem to be using a user developed processing chain based on GMTSAR. So you probably need to contact the author at his/her repository instead of posting an issue here.

**Comment by mobigroup** [comment]
@janardanroy The right place for PyGMTSAR related questions is here: https://github.com/mobigroup/gmtsar/issues
