### ISSUE TITLE
[Feature]: grd2xyz

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#701]
To get the.xyz text via grd2xyz, I would like to ask you a few questions:
1. The third column is elevation. What is its unit? Is that what the elevation is or does it need to be *10^3?
grd2xyz is applied to corr_ll.grd, phasefilt_ll.grd, and unwrap_ll.grd to obtain xyz files (corr_ll.xyz, phasefilt_ll.xyz, and unwrap_LL.xyz) respectively. The longitude and latitude values in the corr_ll.xyz, phasefilt_ll.xyz, and unwrap_ll.xyz files are the same, but the Z values of the same point are different. What is the cause? If I need to use the elevation value, which of these files should I use to get the Z value?
3. What does the third column in xyz file contain NaN? Should I delete its row?
4. Figure 2 is the xyz file obtained from grd2xyz dem.grd. Comparison findings: The data in the third column are quite different. What's the difference? Which one is right?

figure1:
![$P`07G_Z`ERFE_PAT4(M{KS](https://user-images.githubusercontent.com/114629377/227184833-f9a549b5-7023-4e27-9489-d8b32295ccbc.png)
figure2:
![FSG M6`NQU)3%CY8B4}M_XN](https://user-images.githubusercontent.com/114629377/227201400-e0a47163-1e11-4933-a9c5-7e58936150e1.png)

**Comment by Xiaohua-Eric-Xu** [comment]
The three files have different names so you probably already know they are different products and you should be expecting the values in them are different, right? corr means coherence/correlation, no unit. phase and unwrap mean radar phase and unwrapped phase, both of which are in radian.

To get elevation, you'll need to find them in your dem.grd (in your topo directory). 

 Nan means no valid measurement. As you probably noticed, in radar coordinates the pixels are pretty much filled with values, but after projection the grid square is not along East/North. So thare are NaNs surrounding the data. If you don't want them, simply add `-s` with `gmt grd2xyz`.

**Comment by Luvina0503** [comment]
ok.thank you
