### ISSUE TITLE
Error with intf_tops_parallel.csh

### ISSUE THREAD

**Issue by AmiraZakii** [gmtsar/gmtsar#702]
Hello, 
can you help me please with this error, I tried to apply intf_tops_parallel.csh one.in batch_tops.config 2 to run one interferograme with mode = 1 in in batch_tops.config and I have this error :
![Screenshot from 2023-03-28 16-21-20](https://user-images.githubusercontent.com/89259389/228269206-3a855595-1b58-41d1-8902-92404a84b8e4.png)
![Screenshot from 2023-03-28 16-22-57](https://user-images.githubusercontent.com/89259389/228269526-5a664955-8474-487a-a6e0-2d8d76a60a02.png)
![Screenshot from 2023-03-28 16-23-46](https://user-images.githubusercontent.com/89259389/228269719-546e8107-c773-4ca8-a056-c4924d920661.png)
![Screenshot from 2023-03-28 16-24-16](https://user-images.githubusercontent.com/89259389/228269879-aada875b-345c-4fbe-af70-80a53fe2987a.png)
![Screenshot from 2023-03-28 16-24-58](https://user-images.githubusercontent.com/89259389/228270148-f8a8fc54-13c3-412e-b023-b95dedcb627e.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Send your batch_tops.config. My suspicion is that you started every thread with proc_stage = 1 but I could be wrong.
