### ISSUE TITLE
[Help]: Problem with SBAS - last disps have same values

### ISSUE THREAD

**Issue by SteffanDavies** [gmtsar/gmtsar#703]
I have recently run sbas_parallel on a 5 year long dataset, without smoothing or atm and with mmap. The last 5 disps have exactly the same values. Any idea why?

![image](https://user-images.githubusercontent.com/50405969/228723732-acd8d57b-b27c-4f61-a87d-0583033e21e9.png)

**Comment by SteffanDavies** [comment]
@Xiaohua-Eric-Xu 
![image](https://user-images.githubusercontent.com/50405969/228724248-0ee7c8c0-fa20-4a67-bd09-c7989de2f7c3.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I could think of two scenarios, one is about whether you have scene.tab correctly listing the dates in the chronological order. The second is whether you have connections among all interferograms. If there are missing connections and you did not turn-on enough smoothness, then the last a few dates may stay the same. It is recommended to put in even just a little smoothness, just to stabilize the inverse problem.
