### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xt-xc-123** [gmtsar/gmtsar#704]
Hello, there is an error showed "interpolation point outside of data constraints, 1506141.743892 0.000000 0.000000" when I ran preproc_batch_tops.csh a step of SBAS-InSAR. The DEM fully covers the data and I used the precise orbit for the  image . Could you give me any suggestion on the error? Thanks! I'm looking forward your help.
P.S. GMTSAR version 6.0

Here is the output:
preproc_batch_tops.csh data.in dem.grd 1
Reading in 5633 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5647 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5633 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5633 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5633 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5633 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5633 lines of info from XML...
Writing 17 lines for orbit...
Writing 52 lines of precise orbit for the LED file...
Successfully opened junk1 
Reading in 5633 lines of info from XML...
Writing 17 lines for orbit...
Not an well formatted XML file...-1, -1
Unable to find designated string...after 0 searches..
NO orbit coverage in the selected file...
Successfully opened junk1 
interpolation point outside of data constraints, 1506141.743892 0.000000 0.000000
cat: junk2: 没有那个文件或目录
rm: 无法删除 'junk2': 没有那个文件或目录
Reading in 5633 lines of info from XML...
Writing 17 lines for orbit...
Not an well formatted XML file...-1, -1
Unable to find designated string...after 0 searches..
NO orbit coverage in the selected file...
Successfully opened junk1 
interpolation point outside of data constraints, 2542942.116550 0.000000 0.000000
cat: junk2: 没有那个文件或目录
rm: 无法删除 'junk2': 没有那个文件或目录
Reading in 5633 lines of info from XML...
Writing 17 lines for orbit...
Not an well formatted XML file...-1, -1
Unable to find designated string...after 0 searches..
NO orbit coverage in the selected file...
Successfully opened junk1 
interpolation point outside of data constraints, 3579741.472681 0.000000 0.000000
cat: junk2: 没有那个文件或目录
rm: 无法删除 'junk2': 没有那个文件或目录
interpolation point outside of data constraints, 1506166.805234 2822256000.000000 2822256000.000000
interpolation point outside of data constraints, 1506166.805234 2827958400.000000 2827958400.000000
interpolation point outside of data constraints, 2542967.177892 2816726400.000000 2816726400.000000
interpolation point outside of data constraints, 2542967.177892 2811283200.000000 2811283200.000000
interpolation point outside of data constraints, 3579766.534023 2808691200.000000 2808691200.000000
interpolation point outside of data constraints, 3579766.534023 2817331200.000000 2817331200.000000

**Comment by Xiaohua-Eric-Xu** [comment]
Key error is this one "NO orbit coverage in the selected file...", so you may have used a wrong orbit file. Or it could be that your gmtsar is not updated after 1/31/2023, when ESA changed their orbit format a bit and failed the processing. https://github.com/gmtsar/gmtsar/discussions/629

**Comment by xt-xc-123** [comment]
> Key error is this one "NO orbit coverage in the selected file...", so you may have used a wrong orbit file. Or it could be that your gmtsar is not updated after 1/31/2023, when ESA changed their orbit format a bit and failed the processing. #629

Thank you for your suggestion,I'll try them later.
