### ISSUE TITLE
[Bug]: make_gaussian_filter inconsistent results for subswaths

### ISSUE THREAD

**Issue by AlexeyPechnikov** [gmtsar/gmtsar#706]
The results are ok for wavelength=200m but inconsistent for wavelength=400m:
```
make_gaussian_filter S1_20160103_ALL_F1.PRM 2 1 400
2 4

make_gaussian_filter S1_20160103_ALL_F2.PRM 2 1 400
2 5
```

```
cat S1_20160103_ALL_F1.PRM
num_valid_az = 12188
nrows = 12188
first_line = 1
deskew = n
caltone = 0.0
st_rng_bin = 1
Flip_iq = n
offset_video = n
az_res = 0.0
nlooks = 1
chirp_ext = 0
scnd_rng_mig = 0
rng_spec_wgt = 1.0
rm_rng_band = 0.2
rm_az_band = 0.0
rshift = 0
ashift = 0
stretch_r = 0
stretch_a = 0
a_stretch_r = 0
a_stretch_a = 0
first_sample = 539
SC_identity = 10
input_file = S1_20160103_ALL_F1.raw
num_rng_bins = 21512
bytes_per_line = 86048
good_bytes_per_line = 86048
PRF = 486.48631
pulse_dur = 5.240481e-05
near_range = 801901.069685
num_lines = 12188
num_patches = 1
SC_clock_start = 2016002.3482461893
SC_clock_stop = 2016002.348536156
clock_start = 2.348246189659
clock_stop = 2.348536156328
led_file = S1_20160103_ALL_F1.LED
orbdir = D
lookdir = R
radar_wavelength = 0.0554658
chirp_slope = 1078150000000.0
rng_samp_rate = 64345238.125714
I_mean = 0
Q_mean = 0
equatorial_radius = 6378137.0
polar_radius = 6356752.31
fdd1 = 0.0
fddd1 = 0.0
sub_int_r = 0.0
sub_int_a = 0.0
SLC_file = S1_20160103_ALL_F1.SLC
dtype = a
SLC_scale = 1.0
SC_vel = 7181.097364
earth_radius = 6375292.494153
SC_height = 704201.139989
SC_height_start = 704126.339815
SC_height_end = 704274.624131
fd1 = 0.0
```

```
cat S1_20160103_ALL_F2.PRM
num_valid_az = 12188
nrows = 12188
first_line = 1
deskew = n
caltone = 0.0
st_rng_bin = 1
Flip_iq = n
offset_video = n
az_res = 0.0
nlooks = 1
chirp_ext = 0
scnd_rng_mig = 0
rng_spec_wgt = 1.0
rm_rng_band = 0.2
rm_az_band = 0.0
rshift = 0
ashift = 0
stretch_r = 0
stretch_a = 0
a_stretch_r = 0
a_stretch_a = 0
first_sample = 475
SC_identity = 10
input_file = S1_20160103_ALL_F2.raw
num_rng_bins = 25324
bytes_per_line = 101296
good_bytes_per_line = 101296
PRF = 486.48631
pulse_dur = 6.199593e-05
near_range = 847986.796693
num_lines = 12188
num_patches = 1
SC_clock_start = 2016002.3482252767
SC_clock_stop = 2016002.348515244
clock_start = 2.348225277233
clock_stop = 2.348515243902
led_file = S1_20160103_ALL_F2.LED
orbdir = D
lookdir = R
radar_wavelength = 0.0554658
chirp_slope = 779083000000.0
rng_samp_rate = 64345238.125714
I_mean = 0
Q_mean = 0
equatorial_radius = 6378137.0
polar_radius = 6356752.31
fdd1 = 0.0
fddd1 = 0.0
sub_int_r = 0.0
sub_int_a = 0.0
SLC_file = S1_20160103_ALL_F2.SLC
dtype = a
SLC_scale = 1.0
SC_vel = 7183.116705
earth_radius = 6375319.973516
SC_height = 704162.952702
SC_height_start = 704087.962558
SC_height_end = 704236.626547
fd1 = 0.0
```

**Comment by Xiaohua-Eric-Xu** [comment]
Inconsistency does not always mean a bug. 
```
 76     sig_azi = w / 5.3 / azi_px_size;
 77     sig_rng = w / 5.3 / rng_px_size;
```
azi_px_size is the same from subswath to subswath, but rng_px_size changes with range. The two PRM file has different near_range as you may have noticed. And decimation has to be integer so the numbers are rounded.

**Comment by mobigroup** [comment]
Do you mean we cannot use GMTSAR with Sentinel scenes?:) There is no way to merge the subswaths processed with different decimation.

**Comment by Xiaohua-Eric-Xu** [comment]
There are parameters (range_dec and azimuth_dec) to force decimation regardless of decimation provided by make_gaussian_filter.

**Comment by mobigroup** [comment]
Is it necessary to have the option which does not work properly? filter.csh is usually called without the additional parameters:

```
grep filter.csh *csh
MAI_processing.csh:  filter.csh $master.PRM $aligned.PRM $filter $dec $range_dec $azimuth_dec
filter.csh:    echo "Usage: filter.csh master.PRM aligned.PRM filter decimation [rng_dec azi_dec] [compute_phase_gradient]"
filter.csh:    echo "Example: filter.csh IMG-HH-ALPSRP055750660-H1.0__A.PRM IMG-HH-ALPSRP049040660-H1.0__A.PRM 300  2"
filter.csh:  echo "filter.csh"
gmtsar.csh:echo 'filter.csh		- filter the interferogram and make amp, phase and corr'
intf_batch.csh:          filter.csh $ref.PRM $rep.PRM $filter $dec
intf_batch.csh:          filter.csh $ref.PRM $rep.PRM $filter $dec
intf_batch.csh:        filter.csh $ref.PRM $rep.PRM $filter $dec
intf_batch_ALOS2_SCAN.csh:#          filter.csh IMG-HH-$ref-F$subswath.PRM IMG-HH-$rep-F$subswath.PRM $filter $dec 2 8
intf_batch_ALOS2_SCAN.csh:          filter.csh IMG-HH-$ref-F$subswath.PRM IMG-HH-$rep-F$subswath.PRM $filter $dec $range_dec $azimuth_dec
intf_batch_ALOS2_SCAN.csh:#          filter.csh IMG-HH-$ref-F$subswath.PRM IMG-HH-$rep-F$subswath.PRM $filter $dec 2 8
intf_batch_ALOS2_SCAN.csh:          filter.csh IMG-HH-$ref-F$subswath.PRM IMG-HH-$rep-F$subswath.PRM $filter $dec $range_dec $azimuth_dec
intf_batch_ALOS2_SCAN.csh:#        filter.csh IMG-HH-$ref-F$subswath.PRM IMG-HH-$rep-F$subswath.PRM $filter $dec 2 8
intf_batch_ALOS2_SCAN.csh:        filter.csh IMG-HH-$ref-F$subswath.PRM IMG-HH-$rep-F$subswath.PRM $filter $dec $range_dec $azimuth_dec
intf_tops.csh:    filter.csh $ref.PRM $rep.PRM $filter $dec $range_dec $azimuth_dec
p2p_ALOS2_SCAN_SLC.csh:        filter.csh IMG-$ref-$subswath.PRM IMG-$rep-$subswath.PRM $filter $dec 
p2p_ALOS2_SCAN_SLC.csh:        filter.csh IMG-$ref-$subswath.PRM IMG-$rep-$subswath.PRM $filter $dec 
p2p_ALOS2_SCAN_SLC.csh:      filter.csh IMG-$ref-$subswath.PRM IMG-$rep-$subswath.PRM $filter $dec 
p2p_ENVI.csh:        filter.csh $ref.PRM $rep.PRM $filter $dec
p2p_ENVI.csh:        filter.csh $ref.PRM $rep.PRM $filter $dec
p2p_ENVI.csh:      filter.csh $ref.PRM $rep.PRM $filter $dec
p2p_ERS.csh:        filter.csh $ref.PRM $rep.PRM $filter $dec
p2p_ERS.csh:        filter.csh $ref.PRM $rep.PRM $filter $dec
p2p_ERS.csh:      filter.csh $ref.PRM $rep.PRM $filter $dec
p2p_processing.csh:        filter.csh $ref.PRM $rep.PRM $filter $dec $range_dec $azimuth_dec $compute_phase_gradient
p2p_processing.csh:        filter.csh $ref.PRM $rep.PRM $filter $dec $range_dec $azimuth_dec $compute_phase_gradient
p2p_processing.csh:      filter.csh $ref.PRM $rep.PRM $filter $dec $range_dec $azimuth_dec $compute_phase_gradient
p2p_processing.csh:          filter.csh $ref.PRM $rep.PRM 500 $dec $new_incx $new_incy
p2p_processing.csh:          filter.csh $ref.PRM $rep.PRM 500 $dec $new_incx $new_incy
p2p_processing.csh:        filter.csh $ref.PRM $rep.PRM 500 $dec $new_incx $new_incy
p2p_processing.csh:          filter.csh $ref.PRM $rep.PRM 500 $dec $new_incx $new_incy
p2p_processing.csh:          filter.csh $ref.PRM $rep.PRM 500 $dec $new_incx $new_incy
p2p_processing.csh:        filter.csh $ref.PRM $rep.PRM 500 $dec $new_incx $new_incy
p2p_processing.csh:          filter.csh $ref.PRM $rep.PRM 500 $dec $new_incx $new_incy
p2p_processing.csh:          filter.csh $ref.PRM $rep.PRM 500 $dec $new_incx $new_incy
p2p_processing.csh:        filter.csh $ref.PRM $rep.PRM 500 $dec $new_incx $new_incy
```

Actually, only the new script p2p_processing.csh does it.

**Comment by Xiaohua-Eric-Xu** [comment]
Interesting impression. 

Those that does not have this option are more or less because it is not needed for those data, e.g., intf_batch.csh that works with ERS, ENVISAT and ALOS-1 data, all of which either have no Scan SAR mode or has ScanSAR data but does not work functionally due to burst drift issue. Same for p2p_ENVI.csh and p2p_ERS.csh, which are kept there so as to deal with non-zero doppler focusing over the raw data. Then the question becomes, which one of the above do you actually use? :)

**Comment by mobigroup** [comment]
It looks the additional decimation in make_gaussian_filter output is totally useless and we need to block it using the additional parameters for filter.csh. And in case we still try to apply it there is the inconsistency between subswaths.

**Comment by Xiaohua-Eric-Xu** [comment]
The parameter is not additional considering, 

1) not all satellites come in subswaths. 
2) users may not know what's a good decimation number to use initially. 
3) consistency is something that does not exist yet in satellite acquisitions. :(

If you really feel this being necessary, please go ahead and change it in your fork.

**Comment by mobigroup** [comment]
Hmm, maybe I miss the point, but how to use this feature? Actually, decimation is just a deal and has a side-effect of spatial resolution lost so this internal unpredictable decimation option is strange as I think.

**Comment by Xiaohua-Eric-Xu** [comment]
If you neglect range_dec and azimuth_dec, the output is essentially rounded to 1/8 filter wavelength with considering range pixel size, azimuth pixel size, initial decimation, etc.(do note the default geocoding choice is 1/4 wavelength so as to ensure valid data exist in every output pixel) The reason for such choice is that with the filtering applied, there's no way resolving anything below that, and decimating the data will make later processing faster and easier (especially phase unwrapping). Different decimation will change the topology of residues for phase unwrapping and may lead to different results (usually more filtering means more robust solution). Unwrapping in full resolution is almost impossible to finish for a large area with those optimization approaches. 

The reason for this to exist is that for the data that does not have subswaths (ERS1/2, ENVISAT, ALOS-1, and certain modes of Radarsat1/2 and TerraSAR-X), you don't have to guess a decimation that may end up being too dense or sparse after geocoding. As long as the data are from the same satellites that are able to interfere, setting up the parameter will for sure give you the same decimation.

**Comment by mobigroup** [comment]
Ok, thanks. So it’s an easy to do approach instead of SIMD code vectorization to process the required convolutions faster plus window data aggregation (sum) after that. But the signal/noise ratio is affected because N pixels sum has lower noise (proportional to 1/sqrt(N) ) vs a single decimated pixel. Maybe did you estimate the accuracy lost for the decimation based approach (for urban areas)? I mean that looks valuable to exclude the decimations in case we can do the exact processing at the same time using numeric calculations optimizations.
