### ISSUE TITLE
[Feature]: ref_point

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#707]
hi,dear professors,
I would like to ask how to convert the coordinates of reference points (latitude and longitude) into radar coordinates?

**Comment by Luvina0503** [comment]
![image](https://user-images.githubusercontent.com/114629377/229336980-0e7f00c6-2466-4653-b77d-0aa4bc920e7c.png)

**Comment by igps-ftk** [comment]
proj_ll2ra_ascii.csh

**Comment by Luvina0503** [comment]
@igps-ftk 
root@gmtsar:/media/gmtsar/Elements/Work/171106/d1_mask# proj_ll2ra_ascii.csh trans.dat dem.xyz 11.xyz
surface: Provides 3, expects 3-column binary data
surface: Error: Grid must have at least 4 nodes in each direction (you have 3 by 3) - abort.
surface: Provides 3, expects 3-column binary data
surface: Error: Grid must have at least 4 nodes in each direction (you have 3 by 3) - abort.
grdtrack: Error for input file: No such file (llr.grd)
grdtrack: Syntax error: Must specify -G at least once
grdtrack: Error for input file: No such file (lla.grd)
grdtrack: Syntax error: Must specify -G at least once

**Comment by Luvina0503** [comment]
![image](https://user-images.githubusercontent.com/114629377/229398147-3a2b42fc-e8aa-4eb0-898c-c9722a311114.png)

**Comment by Xiaohua-Eric-Xu** [comment]
I think the script needs at least 3 points to work. As a alternative, try `SAT_llt2rat`. You'll need to get the elevation information using `gmt grdtrack` over your dem.grd.

**Comment by Luvina0503** [comment]
But my goal is to convert ref_point in the GACOS step to radar coordinates, so ref_point has only one coordinate point. dem.xyz is just for testing scripts

**Comment by Xiaohua-Eric-Xu** [comment]
Then use `SAT_llt2rat`. You could run `echo $lon $lat | gmt grdtrack -Gdem.grd | SAT_llt2rat $PRM 1`.

**Comment by Luvina0503** [comment]
this problem is solved.thank you
