### ISSUE TITLE
[Help]: Shape of landmask_ra.grd doesn't match corr.grd

### ISSUE THREAD

**Issue by pederao** [gmtsar/gmtsar#709]
**Describe the problem you met**

I'm new to gmtsar and am following the instructions in sentinel_time_series_5.pdf.

When generating the landmask_ra.grd I get a different size array than for corr.grd (see logfile section) and it looks strange to me.  Are the sizes supposed to be different?

If I change the following line in landmask.csh:
> gmt grdsample landmask_ra.grd -Gtmp.grd -R$1 -I4/8 -nl+t0.1
to 
> gmt grdsample landmask_ra.grd -Gtmp.grd -R$1 -I8/2 -nl+t0.1

my landmask_ra.grd gets the same size as my corr.grd file, but I hesitate to make this change before checking here.

**OS and software version**
If applicable, what operating system and software version you are using?
OS: UBUNTU 20.04.1
GMTSAR version: latest I think

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?
Follow instructions in Sentinel_time_series_5.pdf until p. 21.

**Log file**
Attach a log file output from your terminal.

>> gmt grdinfo landmask_ra.grd
landmask_ra.grd: Title:
landmask_ra.grd: Command: gmt xyz2grd landmask_ra.xyz -bi -r -R0/44456/0/12186 -I4/8.00153491942 -Gtmp.grd
landmask_ra.grd: Remark:
landmask_ra.grd: Pixel node registration used [Cartesian grid]
landmask_ra.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
landmask_ra.grd: x_min: 0 x_max: 44456 x_inc: 4 name: x n_columns: 11114
landmask_ra.grd: y_min: 8.881784197e-16 y_max: 12186 y_inc: 8.00131319764 name: y n_rows: 1523
landmask_ra.grd: v_min: 1 v_max: 1 name: z
landmask_ra.grd: scale_factor: 1 add_offset: 0
landmask_ra.grd: format: netCDF-4 chunk_size: 130,139 shuffle: on deflation_level: 3
landmask_ra.grd: Default CPT:

>> gmt grdinfo corr.grd
corr.grd: Title: Produced by grdmath
corr.grd: Command: gmt grdmath corr_patch.grd 0. XOR 1. MIN = corr_patch.grd
corr.grd: Remark:
corr.grd: Pixel node registration used [Cartesian grid]
corr.grd: Grid file format: nf = GMT netCDF format (32-bit float), CF-1.7
corr.grd: x_min: 0 x_max: 44456 x_inc: 8 name: x n_columns: 5557
corr.grd: y_min: 0 y_max: 12186 y_inc: 2 name: y n_rows: 6093
corr.grd: v_min: 0.00614068098366 v_max: 0.992831170559 name: z
corr.grd: scale_factor: 1 add_offset: 0
corr.grd: format: netCDF-4 chunk_size: 130,130 shuffle: on deflation_level: 3
corr.grd: Default CPT:

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @pederao, this is the problem when the increment is not consistent with the bounds. i.e. 12186 is not a multiple of 8. I think I made a fix to proj_ll2ra.csh to avoid such scenario but maybe I didn't get it correctly fixed. Changing the increment to smaller numbers may get the error around occasionally but it maynot be a permanent fix.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Pederao, the 4/8 downsampling were built-in there when the older SAR satellites has smaller azimuthal pixel spacing (4m-ish) compared to range pixel spacing (10m-ish). The landmask_ra.grd is used before phase unwrapping and is resampled to the resolution of phasefilt.grd so whether it is 4/8 or 16/4 should not matter too much unless your targets are quite close to the coastline. Feel free to create your own version of landmask.csh at the moment and we may seek to resolve this issue hopefully before summer.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Pederao, the 4/8 downsampling were built-in there when the older SAR satellites has smaller azimuthal pixel spacing (4m-ish) compared to range pixel spacing (10m-ish). The landmask_ra.grd is used before phase unwrapping and is resampled to the resolution of phasefilt.grd so whether it is 4/8 or 16/4 should not matter too much unless your targets are quite close to the coastline. Feel free to create your own version of landmask.csh at the moment and we may seek to resolve this issue hopefully before summer.

**Comment by pederao** [comment]
> Hi Pederao, the 4/8 downsampling were built-in there when the older SAR satellites has smaller azimuthal pixel spacing (4m-ish) compared to range pixel spacing (10m-ish). The landmask_ra.grd is used before phase unwrapping and is resampled to the resolution of phasefilt.grd so whether it is 4/8 or 16/4 should not matter too much unless your targets are quite close to the coastline. Feel free to create your own version of landmask.csh at the moment and we may seek to resolve this issue hopefully before summer.

Thank you X@Xiaohua-Eric-Xu for the explanation.  This makes sense to me.
