### ISSUE TITLE
[Bug]: Duplicate symbols error when compiling with -fno-common

### ISSUE THREAD

**Issue by rtburns-jpl** [gmtsar/gmtsar#71]
**Describe the bug**
Some variables in headers (e.g. [these](https://github.com/gmtsar/gmtsar/blob/eb41a38fa0a995e9767ec6da2ed95d9bf6f5a408/gmtsar/gmtsar.h#L65-L81)) are defined with external linkage, which may cause linker errors. Older versions of GCC/Clang have implicitly used -fcommon so the duplicated definitions are elided, but when explicitly setting -fno-common or building with newer versions (GCC 10+, Clang 11+) which default to -fno-common, these cause linker errors such as
```
duplicate symbol '_debug' in:
    CMakeFiles/gmtsar.dir/aastretch.c.o
    CMakeFiles/gmtsar.dir/sbas_utils.c.o
duplicate symbol '_quiet_flag' in:
    CMakeFiles/gmtsar.dir/aastretch.c.o
    CMakeFiles/gmtsar.dir/sbas_utils.c.o
[...]
duplicate symbol '_nodata' in:
    CMakeFiles/gmtsar.dir/aastretch.c.o
    CMakeFiles/gmtsar.dir/sbas_utils.c.o
ld: 880 duplicate symbols for architecture x86_64
```

We have some similar code in [ISCE2](https://github.com/isce-framework/isce2) which causes the same issue - see https://github.com/isce-framework/isce2/pull/158 for how I'm resolving this. An alternative approach is to make these variables `static` so each translation unit gets its own copy, if modifications to these variables from one file are not meant to be visible from other files.

**To Reproduce**
Build with GCC 10+ or Clang 11+, or `export CFLAGS="-fno-common"` before configuring with an older compiler

**System and software version:**
 - GCC 10+, Clang 11+, or previous versions with explicit -fno-common flag
 - GMTSAR version: git master

**Comment by Xiaohua-Eric-Xu** [comment]
Please open a new post in case the error persist after adding -z muldefs to CFLAG and LDFLAG in config.mk
