### ISSUE TITLE
[Help]: Abot gacos_correction and unwrap correct_results.grd

### ISSUE THREAD

**Issue by toma1li** [gmtsar/gmtsar#711]
First, i converted radar coordinate systems to latitude and longitudeuse using "proj_ra2ll.csh ../trans.dat ./phasefilt.grd ./phasefilt_ll.grd"

Second, i conducted tacos correction using "../gacos_operation.csh ../GACOS/20190726.ztd ../GACOS/20190726.ztd.rsc ../GACOS/20190807.ztd ../GACOS/20190807.ztd.rsc ./phasefilt_ll.grd ../reference_point 33.86"

At second, i got two results "phase_GACOS_corrected_phs.grd" and "phase_GACOS_corrected_phs_detrended.grd", which should i use?

Third, i converted latitude and longitudeuse to radar coordinate systems using "proj_ll2ra.csh ../trans.dat ./phase_GACOS_corrected_phs.grd ././phasefilt_lll.grd".

At third, i converted for "phase_GACOS_corrected_phs.grd" and "phase_GACOS_corrected_phs_detrended.grd", when i read the coordinate range using “gmt grdinfo ./phasefilt_lll.grd”, the rang has changed. The range show in figure below.

Fourth, i deleted "phasefilt.grd” and changed name of "phasefilt_lll.grd” to "phasefilt.grd”.

Last, i unwrap it using "snaphu_interp.csh 0.1 0.001". The .csh can't work. The wrong show in figure below.
<img width="567" alt="230035485-07a4230c-a8e8-4973-9148-233077dd7c2c" src="https://user-images.githubusercontent.com/127527357/230042523-c25129ee-1b98-408e-bac1-17c94b6b9580.png">
<img width="565" alt="230035741-a8f4330e-202e-4363-b2ff-8b1653d069e9" src="https://user-images.githubusercontent.com/127527357/230042551-83d3db03-6cb9-4d9d-9fa6-4bd8114aa610.png">
<img width="554" alt="230035930-603bb33d-1a6d-4d86-8621-35c27a50aef2" src="https://user-images.githubusercontent.com/127527357/230042571-342fbf82-6d4b-4439-ab98-f21abf10e20e.png">

**Comment by Xiaohua-Eric-Xu** [comment]
This is from https://github.com/gmtsar/user-contributions/commits?author=esrivas17, so maybe message him for some help?

The difference in resolution are likely from the default projection resolution. You could either tune the projection resolution in the script you used or try to unwrap in geo-coordinates.

**Comment by Xiaohua-Eric-Xu** [comment]
Also, I would directly project the GACOS grid to radar coordinates and perform the correction there. Projecting phase back and forth (mosaicing twice) may not be a good idea.

**Comment by toma1li** [comment]
Thank your reply. But ".ztd" and ".ztd.rsc" is not grd file. And projecting them seem difficult.
I change my steps. The implementation object has changed from "phasefilt_ll.grd" to "unwrap.grd".  Finally，i work with no errors. But I don't know if this is feasible？

**Comment by Xiaohua-Eric-Xu** [comment]
It should not matter for phase unwrapping as the correction should not introduce more or less residues.

**Comment by toma1li** [comment]
Thank you very much. After browsing through the relevant issues, I found that correcting "unwrap.grd" did not result in any changes. Excuse me, which ".csh" should I use to correct, after projecting the GACOS grid to radar coordinates.

**Comment by toma1li** [comment]
Thank you very much, dear professor. I have solved the problem and thank you for your help
