### ISSUE TITLE
[Feature]: unwrap

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#712]
hi,dear professors,
Do I need to select points before unwinding? That is, the less relevant points are deleted. What does mask_def.grd do?

**Comment by Xiaohua-Eric-Xu** [comment]
mask_def.grd for snaphu.csh will mask coherence, and for snaphu_interp.csh will mask both phase and coherence. 

I guess snaphu does not have ref point parameter so you probably could not do that.

**Comment by Luvina0503** [comment]
I did grdmath on unwrap.grd using the reference point data, but the settlement results were still too different.
gmt grdmath unwrap.grd $value SUB = unwrap_pin.grd

**Comment by Xiaohua-Eric-Xu** [comment]
You probably need to let us know what are the differences or what you are expecting. If you are not interested in any large scale deformation, you could use `gmt grdtrend` to remove the 1st-order large scale deformation from your interferograms and produce velocity with sbas.

**Comment by Luvina0503** [comment]
That's not what it means.
Processing process: registration - interference - Gacos-unwinding -sbas
What I would like to ask you is that the settlement result processed according to this process is not in line with reality. Normally, the settlement map shows that there should be only a few obvious settlement sites in the study area. In my results, there is obvious settlement in the place of this settlement and the time sequence is good. However, serious settlement also occurs in a large residential area, and the annual average settlement rate is relatively high, reaching -700mm/year. I'm looking for where the problem is.
What I think is wrong:
1. The mask threshold is too low, and points with low coherence are retained in the interferogram. Based on the previous answer combined with the point density of mask_def.grd, it seems that my mask_def.grd has no problem. At what point density should mask_def.grd be appropriate?
Figure ure1(stack_coherence_mask.csh corr_list 0.075):
![GRRZEUZSRKYT86H QO{1N3I](https://user-images.githubusercontent.com/114629377/230553124-5df399c9-1d3b-433c-bad7-bf94553b9fa4.png)

Figure ure2(stack_coherence_mask.csh corr_list 0.12):
 ![2R~C(VTZOD$VHNA84MD3YP1](https://user-images.githubusercontent.com/114629377/230556105-8804987b-6f3a-4dba-8edb-e8c142d32ba0.png)

Figure ure3(stack_coherence_mask.csh corr_list 0.15):
![$BSXM%}ZNZZI$_Z6C10WHS4](https://user-images.githubusercontent.com/114629377/230558631-77f64025-433c-4b9d-84e8-c236161cd2e0.png)

2. GACOS correction is incomplete or the incident Angle is too large.
3. Rejection of interferogram. (This question has already been answered, it is not feasible)
4. No reference points are selected in the interferogram. (Reference points have been selected for processing, but the problem still exists)
That's what I'm thinking. I can't figure out what the problem is.

**Comment by Xiaohua-Eric-Xu** [comment]
I think I mentioned something similar in another thread that the velocity product contains many signals, not just subsidence.  If you are only interested in subsidence, then you could reduce the impact from other component by detrending the interferograms before solving for a time-series with SBAS. But overall, one should not even treat everything measured with InSAR as vertical deformation only.
