### ISSUE TITLE
Preprocessing error regarding H5 file (CSK) [Help]: 

### ISSUE THREAD

**Issue by nusretdemir** [gmtsar/gmtsar#713]
Hi everybody,

I am trying to use GMTSAR the last version, on google colab,
and receiving an error :
![resim](https://user-images.githubusercontent.com/27285421/230596536-8a718aae-efbd-4bc1-b3d8-da99812ec84b.png)

The data is CSK H5, I have tried also the test images provided by GMTSAR, but the same error remains,
The data size is ca 3.5gb,

any idea on a solution is highly appreciated,
Thank you

Nusret

**Comment by nusretdemir** [comment]
Ok, I have found out, the error above was my mistake for pointing the path,
the files should be under /the content folder, that works.

**Comment by Xiaohua-Eric-Xu** [comment]
Glad it's working!
