### ISSUE TITLE
[Help]: little question on unwrapping

### ISSUE THREAD

**Issue by PickleRickrx** [gmtsar/gmtsar#715]
Hi everyone,I have a litttle problem on unwrapping,after I unwrap in regions of good coherence,shoule I do the next step:unwrapping in regions of poor coherence in the same Interferograms?

**Comment by PickleRickrx** [comment]
Or do I just need to do one of these steps?

**Comment by Xiaohua-Eric-Xu** [comment]
I guess I am a bit confused as how did you `unwrap in regions of good coherence`? with a coherence threshold?

**Comment by PickleRickrx** [comment]
Sorry I didn't express myself clearly，I just follow the tutorial（sentinel_time_series_5.pdf）,so I can just do one of the two steps?
![image](https://user-images.githubusercontent.com/93982725/230835893-e0fb8340-02de-407b-8474-f31e6dd717b1.png)
![image](https://user-images.githubusercontent.com/93982725/230835922-9c4f09d7-57c2-4844-aa6f-97f6a9ea44e6.png)


> I guess I am a bit confused as how did you `unwrap in regions of good coherence`? with a coherence threshold?

**Comment by Xiaohua-Eric-Xu** [comment]
I believe so, these are two options. When data are good, you don't need to do any extra stuff to have good results. :)

**Comment by PickleRickrx** [comment]
> I believe so, these are two options. When data's good, you don't need to do any extra stuff to have good results. :)

thank you for your reply！I will try
