### ISSUE TITLE
[Feature]: plot pdf

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#716]
hi,dear professors,
How to generate pdf from grd file(phasefilt_ref_ll.grd) under lonlat coordinates?

root@gmtsar:/media/gmtsar/Elements/Work/171106/G_nounwrap/11# gmt grdinfo phasefilt_ref_ll.grd -L2
phasefilt_ref_ll.grd: Title: Produced by grdmath
phasefilt_ref_ll.grd: Command: grdmath phasefilt_ref_mask_ll.grd 0.0554658 MUL -79.58 MUL 1000 DIV = phasefilt_ref_ll.grd
phasefilt_ref_ll.grd: Remark: by root on 2023年 04月 11日 星期二 17:09:03 CST with geocode_my.csh
phasefilt_ref_ll.grd: Pixel node registration used [Geographic grid]
phasefilt_ref_ll.grd: Grid file format: nf = GMT netCDF format (32-bit float), COARDS, CF-1.5
phasefilt_ref_ll.grd: x_min: 119.661111111 x_max: 120.922222222 x_inc: 0.000555555555507 name: longitude [degrees_east] n_columns: 2270
phasefilt_ref_ll.grd: y_min: 32.9666666667 y_max: 34.625 y_inc: 0.000416666666658 name: latitude [degrees_north] n_rows: 3980
phasefilt_ref_ll.grd: z_min: -0.0122607741505 z_max: 0.0154729411006 name: phase in radians
phasefilt_ref_ll.grd: scale_factor: 1 add_offset: 0
phasefilt_ref_ll.grd: 4656767 nodes (51.5%) set to NaN
phasefilt_ref_ll.grd: mean: -0.00159043984321 stdev: 0.00788430964603 rms: 0.00804312273262
phasefilt_ref_ll.grd: format: netCDF-4 chunk_size: 134,129 shuffle: on deflation_level: 3

**Comment by Xiaohua-Eric-Xu** [comment]
I guess you could use `gmt grdimage`?
