### ISSUE TITLE
 Installation problem on Ubuntu 22.04

### ISSUE THREAD

**Issue by AliRoozban** [gmtsar/gmtsar#718]
How can I edit config.mk and add -z muldefs to my CFLAGS and LDFLAGS?

OS: Ubuntu 22.04
GMTSAR version: GMTSAR 6.2

**Comment by SteffanDavies** [comment]
Try this:

./configure CFLAGS='-z muldefs' LDFLAGS='-z muldefs'

**Comment by AliRoozban** [comment]
Thanks, I made the changes manually and the problem was solved.
