### ISSUE TITLE
[Feature]: question

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#720]
hi,dear professors,
I have a question about atmospheric correction.
As shown in the figure, can only a small part of the middle of the region be GACOS atmospheric correction, and the rest of the region not be atmospheric correction or other correction methods?

**Comment by Xiaohua-Eric-Xu** [comment]
what figure?

**Comment by Luvina0503** [comment]
figure
![image](https://user-images.githubusercontent.com/114629377/231758719-864a0141-4e35-4e30-8acd-065d91999c4a.png)
Can you understand what I mean by this picture? What I mean is that the blue area is GACOS corrected, and the image covering the rest of the area is not GACOS corrected. Finally, an expanded phase diagram is obtained.

**Comment by Xiaohua-Eric-Xu** [comment]
I guess I am bit confused. Why do you want only part of the image corrected? If so, could just cut out the piece of grid and get it corrected I assume.

**Comment by Luvina0503** [comment]
Because what I understand is that, for example, the study area is large, there are a few low mountains and hills in the region, and the other parts are plain. If I use GACOS (terrain dependent) for atmospheric correction, will it introduce unnecessary errors and reduce the inversion results for the plain region?

**Comment by Xiaohua-Eric-Xu** [comment]
OK, could you elaborate a bit more on what you mean by "introduce unnecessary errors and reduce the inversion results for the plain region" ?

**Comment by Luvina0503** [comment]
Number of interference pairs: 30
I performed GACOS correction on a plain area and obtained the standard deviation stdev before and after correction respectively. By comparison, it is found that the stdev of 80% interferogram is increased after correction.

**Comment by Xiaohua-Eric-Xu** [comment]
> By comparison, it is found that the stdev of 80% interferogram is increased after correction.

Could it be a sign error? Addition instead of subtraction?

Usually if atm correction works well, much of the larger scale signals get reduced and some of the elevation dependent part gets smaller.
