### ISSUE TITLE
[Feature]: filter

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#721]
hi,dear professors,
For coastal regions, there may be turbulent mixing delays. Should spatiotemporal filtering be considered? What command is used for spatio-temporal filtering? Is it before or after unwinding?

**Comment by Xiaohua-Eric-Xu** [comment]
I am not sure what specific method you mean here. wavelets?

**Comment by Luvina0503** [comment]
Would the filtering method shown in red work with GMTSAR?
![mmexport1681434661593](https://user-images.githubusercontent.com/114629377/231916049-8fe63adf-1b9a-4add-8499-1ab7ef606399.jpg)

**Comment by Xiaohua-Eric-Xu** [comment]
Do you mean the smooth factor in sbas? + gaussian filtering the image? Do note filtering is a way of suppressing noise, not actually a correction approach.
