### ISSUE TITLE
[Feature]: sbas

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#724]
hi,dear professors,
I would like to ask about the sbas-atm option. Use sbas-atm 3 and sbas-atm 0 (i.e. skip this step) to get vel1.grd and vel2.grd, respectively. What criteria should I use to compare the effect or accuracy analysis before and after atm correction?

**Comment by Xiaohua-Eric-Xu** [comment]
> Use sbas-atm 3 and sbas-atm 0 (i.e. skip this step) to get vel1.grd and vel2.grd, respectively.

1. -atm 0 means no atm correction. You could simply ignore that option when running sbas. 

> What criteria should I use to compare the effect or accuracy analysis before and after atm correction?

2. How noisy the time-series look like?
