### ISSUE TITLE
[Help]: topo_ra.grd of merge file

### ISSUE THREAD

**Issue by PickleRickrx** [gmtsar/gmtsar#725]
Hi,everyone,I want a dem file with the same size as phase.grd in the merge folder，but there is no dem file matching the merged phase , how can I get such data (for example merge topo_ra.grd of F2 and F3 into one grd)

**Comment by Xiaohua-Eric-Xu** [comment]
Maybe this script could help? But do note this is height above the reference radius in your F1 PRM file. It is not height above geoid or ellipsoid. 

[create_topo_ra_full.csh.txt](https://github.com/gmtsar/gmtsar/files/11242158/create_topo_ra_full.csh.txt)

**Comment by PickleRickrx** [comment]
Is it good to use linear elevation phase correction for unwrap.grd using such merged dem?

> 也许这个脚本可以提供帮助？但请注意，这是高于 F1 PRM 文件中参考半径的高度。它的高度不高于大地水准面或椭球体。
> 
> [create_topo_ra_full.csh.txt](https://github.com/gmtsar/gmtsar/files/11242158/create_topo_ra_full.csh.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
You could give it a try and see how much of the elevation dependent signal gets reduced. I did this for our San Andreas work and seems it works OK. Do note the ratio of the dependency may change with space.

**Comment by PickleRickrx** [comment]
Thank you for your advice, sorry I have two more questions:
1. I see your script and if I just need merge the topo_ra of F2 and F3, I just need to do 
```
t2.PRM:t2.grd
t3.PRM:t3.grd
```, right？
2. the topo.grd elevation range in the F2 file is -354 to 2324, and the topo.grd elevation range in the F3 file is -405 to 1061, but the merge dem elevation range is -387 to 1061. Is this the correct output?

![image](https://user-images.githubusercontent.com/93982725/232358352-ab45c8da-9a1c-4e1a-9163-160e0835a194.png)
![image](https://user-images.githubusercontent.com/93982725/232358479-99521648-3ce4-4de6-b6f1-f6a7612bf69f.png)
![image](https://user-images.githubusercontent.com/93982725/232358645-4bb93fad-cc51-4c28-a0ac-ffc7b1ecb3aa.png)

**Comment by PickleRickrx** [comment]
Thanks for your help!,I have checked the output with ncview,but I met the same situation: the topo.grd elevation range in the F3 file is -405m to 1041m,the topo.grd elevation range in the F2 file is -354m to 2281m，and the merge range generated by the script below is from -424m to 1004m.
But when I import the data into matlab, the values look right. Maybe should I resample the topo_ra.grd file?
[create_topo_ra_merge.txt](https://github.com/gmtsar/gmtsar/files/11273943/create_topo_ra_merge.txt)
![_P7W5ZYI~N)J($_ZP(T)CR0](https://user-images.githubusercontent.com/93982725/233100858-92717151-0467-485c-9a71-fbf3269b1bfe.png)
![71$39`E57@5AI27T~ 5DKSJ](https://user-images.githubusercontent.com/93982725/233100891-393cef5e-975a-4b28-95f0-4b330b12b93f.png)
![062~ZTK4J$8$8%599~()GBN](https://user-images.githubusercontent.com/93982725/233100927-e9ab81fb-9b9d-473c-a9cd-dc4db70bdaad.png)

![}2IB38NYUN1@KQD9CC6KTC4](https://user-images.githubusercontent.com/93982725/233100962-a8e78c75-861c-43d4-b55e-fa0fffdb84ff.png)

**Comment by Xiaohua-Eric-Xu** [comment]
This looks good to me! Maybe I forgot to update the parameters for the grid in the code, but the data should be correct.
