### ISSUE TITLE
[Feature]: snaphu -w

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#728]
hi,dear professors,
I'd like to ask you a question. The snaphu -w option specifies a weight file. So if you want to enter this option, what file should the weight file be (can it be the coherence coefficient graph)? What exactly does this option mean?

**Comment by Xiaohua-Eric-Xu** [comment]
I think this is the extra weight you would like to input. By default gmtsar calls snaphu by setting coherence as weights.
