### ISSUE TITLE
[Help]: confused at parallel_sbas.c compiling

### ISSUE THREAD

**Issue by Uncleyyyyy** [gmtsar/gmtsar#729]
Hi Prof. Eric,
I don't quite understand how to compile parallel_sbas.c on my ubuntu 18.0 system. After I installed gcc 10.2.0 and run the code you shared in the wiki page, it went wrong like below: 
![Screenshot from 2023-04-19 21-58-18](https://user-images.githubusercontent.com/46470946/233098461-dbdbedfd-ef9b-48bf-8a2b-ed5b6d63e648.png)
Some paths are modified according to my situation, such as where I install gcc and gmtsar. Could you please check my code and maybe help me fix it?

**Comment by Xiaohua-Eric-Xu** [comment]
Maybe try locate your gcc-10 or 11 or 12? Also the example is done with Mac. Linux does not have -framework Accelerate. You'll need to figure out the correct compiling options during your compiling of sbas.c.

**Comment by Uncleyyyyy** [comment]
> Maybe try locate your gcc-10 or 11 or 12? Also the example is done with Mac. Linux does not have -framework Accelerate. You'll need to figure out the correct compiling options during your compiling of sbas.c.

So I just simply have deleted the '-framework Accelerate' and compiled again, the process is still interupted:
![Screenshot from 2023-04-21 10-20-17](https://user-images.githubusercontent.com/46470946/233526374-9723e682-06c1-4e05-a2ce-9f9117c6dd91.png)

**Comment by Xiaohua-Eric-Xu** [comment]
Like mentioned above, you are compiling on Ubuntu while the code is given for a specific case on Mac. You'll need to figure out the compiling options while running `make` and `make install`. If you don't understand how the compiling is going, please attache your terminal output after you run `make` and `make install`.

**Comment by mobigroup** [comment]
There is GMTSAR Dockerfile in PyGMTSAR project where the sbas_parallel tool compilation works, see https://github.com/mobigroup/gmtsar/blob/pygmtsar/docker/gmtsar.Dockerfile
