### ISSUE TITLE
[Bug]: resamp produce wrong result in windows

### ISSUE THREAD

**Issue by insar-dev** [gmtsar/gmtsar#73]
**Describe the bug**

resamp produce wrong result in windows, because of write mode;
code line:127
code: if ((SLC_file2 = fopen(argv[4], "b")) == NULL)

if i change "b" to "wb", the result is right.

**System and software version:**
 - OS: [e.g. iOS]  windows
 - GMTSAR version: master

**Comment by Xiaohua-Eric-Xu** [comment]
The master version has this line in 120 and "b" was "w". I changed it to "wb" in this commit 1333e211c26c5318ba180cc004c5953bef2c8d9d

**Comment by Xiaohua-Eric-Xu** [comment]
P.S. Let us know if you have a windows installation successful. We could put it to the installation wiki.

**Comment by insar-dev** [comment]
@Xiaohua-Eric-Xu,i have sucessfully built gmtsar in windows, but failed to build snaphu which use special unix API;
