### ISSUE TITLE
[Feature]: sbas -atm and gacos

### ISSUE THREAD

**Issue by Luvina0503** [gmtsar/gmtsar#730]
hi,dear professors,
Figure 1 is the vel.grd obtained by sbas-atm 3; Figure 2 shows the vel.grd after GACOS correction. The average annual settlement rate in Figure 1 is all negative, which indicates that the results obtained by CSS processing are not ideal or wrong. The average annual settlement rate in Figure 2 is reasonable, and the difference between the maximum settlement rate and that of CSS is about 200mm/y. At the same time, I also experimented with other research areas, and they all got the same results.
According to these results, sbas-atm does little, and GACOS correction is more effective.
Figure 1:
![image](https://user-images.githubusercontent.com/114629377/236822294-38297d52-bb4c-4c53-8a07-32fad3b80207.png)

Figure 2:
![image](https://user-images.githubusercontent.com/114629377/236822333-d9ce47af-2311-4dc3-801d-9bd06b3e0027.png)

What I would like to ask is: which step of sbas-atm has not been handled correctly or is it not suitable to use CSS algorithm?

**Comment by igps-ftk** [comment]
How the original (without atmospheric correction) multi-year average velocity map looks like?

**Comment by Xiaohua-Eric-Xu** [comment]
> The average annual settlement rate in Figure 1 is all negative, which indicates that the results obtained by CSS processing are not ideal or wrong.

The algorithm has limitations and requirements. Do you mind showing in details how the processing's done? e.g., what's your baseline time threshold? How long is your time-series? etc.

Also, you may not want to just treat GACOS as the truth as it is also from weather modeling.
