### ISSUE TITLE
[Help]: The SAR compressed package downloaded from ASF failed to decompress！

### ISSUE THREAD

**Issue by qq1779250951** [gmtsar/gmtsar#731]
Dear professor，
        The SAR compressed package downloaded from ASF failed to decompress. The problem is shown in the following picture. [How can this problem be solved?Thanks a lot！
![image](https://github.com/gmtsar/gmtsar/assets/58210679/ad4a6e71-9744-4078-9da1-8ecb15bd88f9)

**Comment by Xiaohua-Eric-Xu** [comment]
It feels like an incomplete download. Please re-downlaod the data from ASF or Sentinel data hub.

**Comment by qq1779250951** [comment]
> It feels like an incomplete download. Please re-downlaod the data from ASF or Sentinel data hub.

Thanks for your reply ! I will do it again as per your opinion.
