### ISSUE TITLE
Ionospheric Correction

### ISSUE THREAD

**Issue by RenzoAnc** [gmtsar/gmtsar#733]
Hello, everyone. I have a question about the ionospheric correction using GMTSAR. I used a pair of images to form an interferogram using ionospheric correction, but I obtained a strange result. The values are better (after correction), but the phasefilt.pdf file looks strange. I'd like to know what is the problem.

What are the better values I need to use when I do ionospheric correction? (for iono_filt_rng, iono_filt_azi and iono_dsamp). 

I used:

spec_div = 1
spec_mode = 1

correct_iono = 1
iono_filt_rng = 1.0
iono_filt_azi = 1.0
iono_dsamp = 1

iono_skip_est = 0

Before ionospheric correction:

![phasefilt1](https://github.com/gmtsar/gmtsar/assets/105986961/da23b2c4-4db1-4aa4-89a8-d51af0df2bce)

After ionospheric correction:

![phasefilt2](https://github.com/gmtsar/gmtsar/assets/105986961/95eae8ab-1bda-4a75-9bae-daee80f95573)

Regards.

**Comment by Xiaohua-Eric-Xu** [comment]
The interpolation depends on downsampling and filtering. Try set
```
iono_filt_rng = 0.5
iono_filt_azi = 0.5
iono_dsamp = 2
```
Also, do note ionospheric correction depends on correct phase unwrapping. I would use p2p_S1_TOPS_Frame.csh to merge things together and then unwrap the phase, as it seems the earthquake cut through the interferogram and phase unwrapping looks challenging here.

**Comment by RenzoAnc** [comment]
> The interpolation depends on downsampling and filtering. Try set
> 
> ```
> iono_filt_rng = 0.5
> iono_filt_azi = 0.5
> iono_dsamp = 2
> ```
> 
> Also, do note ionospheric correction depends on correct phase unwrapping. I would use p2p_S1_TOPS_Frame.csh to merge things together and then unwrap the phase, as it seems the earthquake cut through the interferogram and phase unwrapping looks challenging here.

**Comment by RenzoAnc** [comment]
Thank you, professor Xiaohua. I'll try with the values you recommended me. After some days, I'll show you the results. Regards.
