### ISSUE TITLE
[Help]: intf.in about prep_sbas.csh

### ISSUE THREAD

**Issue by jerry7nol** [gmtsar/gmtsar#734]
something wrong about baseline,it always repeated.
![4877931613dd15e43108def7f532557](https://github.com/gmtsar/gmtsar/assets/111356557/2338a1c8-1d5c-446f-a98b-709457499091)
![b312cbe8614a00316413e5229744f9c](https://github.com/gmtsar/gmtsar/assets/111356557/54c79be7-686a-49c9-ab06-66b5a86f678a)

**Comment by Xiaohua-Eric-Xu** [comment]
If you are working with S1_TOPS data, then try running `get_baseline_table.csh` to produce a new baseline_table.dat and then a new `intf.in` f file.

**Comment by Xiaohua-Eric-Xu** [comment]
get_baseline_table.csh will produce a baseline_table.dat. What's in that?

**Comment by jerry7nol** [comment]
> get_baseline_table.csh

i got new baseline_table.dat, and produced new intf.in.it look like right,but prep_sbas.csh still wrong
![1684135325368](https://github.com/gmtsar/gmtsar/assets/111356557/51cbfd88-7f29-46b9-b0a7-84a38ab6f968)
![1684135345576](https://github.com/gmtsar/gmtsar/assets/111356557/444582a1-348b-4798-89bb-4fa7c6892e1c)

**Comment by Xiaohua-Eric-Xu** [comment]
OK, again, what is in your baseline_table.dat file? As it seems the script could not find the ref_id from the table.

**Comment by jerry7nol** [comment]
> OK, again, what is in your baseline_table.dat file? As it seems the script could not find the ref_id from the table.

afterget_baseline_table.csh, it seem as example in PDF about gmtsar sbas
![1684135733627](https://github.com/gmtsar/gmtsar/assets/111356557/8d7745de-2b81-4f36-a201-be957f0c83bb)
