### ISSUE TITLE
[Help]: preproc_batch_tops.csh data.in dem.grd 2, can't open %s for reading S1_20200124_ALL_F1.SLC

### ISSUE THREAD

**Issue by wangjing1992** [gmtsar/gmtsar#735]
**Describe the problem you met**

When I ran this command "preproc_batch_tops.csh data.in dem.grd 2", it gave an error that the SLC file "S1_20200124_ALL_F1.SLC" was not found and I couldn't find the file in the F1/raw directory，only this file "S1_20200124_100252_F1.SLC" does exist.  
---------------------------------------------------------------------------------------
preproc_batch_tops.csh data.in dem.grd 2
rm: No match.
Reading in 5140 lines of info from XML...
Writing 16 lines for orbit...
Writing SLC..Image Size: 21664 X 12192...
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 4
Writing 53 lines of precise orbit for the LED file...
ls: cannot access '*slc': No such file or directory
Writing 53 lines of precise orbit for the LED file...
Successfully opened junk1
rm: No match.
Reading in 5140 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Shifting the master PRM by 0 lines...
Successfully opened junk1.PRM
Successfully opened junk2.PRM
......master LED file S1_20200112_100252_F1.LED
.........aligned LED file S1_20200124_100252_F1.LED
......master LED file S1_20200112_100252_F1.LED
.........aligned LED file S1_20200124_100252_F1.LED
Successfully opened junk1
Successfully opened junk1
[1] 1301730
[2] 1301731
[2]  + Done                   SAT_llt2rat S1_20200124_100252_F1.PRM 1 < topo.llt > tmp1.dat
[1]  + Done                   SAT_llt2rat tmp.PRM 1 < topo.llt > tmpm.dat
[1] 1301813
[2] 1301814
[2]    Done                   gmt surface atmp.xyz -bi3d -R0/21660/0/12192 -I8/4 -Gatmp.grd -T0.5 -N1000 -r
[1]  + Done                   gmt surface rtmp.xyz -bi3d -R0/21660/0/12192 -I8/4 -Grtmp.grd -T0.5 -N1000 -r
Reading in 5140 lines of info from XML...
Writing 16 lines for orbit...
Reading in range and azimuth shifts table...
Writing SLC..Image Size: 21660 X 12192...
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 26
ls: cannot access '*slc': No such file or directory
ls: cannot access '*slc': No such file or directory
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
ls: cannot access '*slc': No such file or directory
Writing 53 lines of precise orbit for the LED file...
 **can't open %s for reading S1_20200124_ALL_F1.SLC**
ls: cannot access '*slc': No such file or directory
ls: cannot access '*slc': No such file or directory
ls: cannot access '*slc': No such file or directory
ls: cannot access '*slc': No such file or directory
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
Successfully opened junk1
Reading in 5154 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Shifting the master PRM by 0 lines...
Successfully opened junk1.PRM
Successfully opened junk2.PRM
......master LED file S1_20200112_100252_F1.LED
.........aligned LED file S1_20200205_100251_F1.LED
......master LED file S1_20200112_100252_F1.LED
.........aligned LED file S1_20200205_100251_F1.LED
Successfully opened junk1
Successfully opened junk1
[1] 1302948
[2] 1302949
[2]    Done                   SAT_llt2rat S1_20200205_100251_F1.PRM 1 < topo.llt > tmp1.dat
[1]  + Done                   SAT_llt2rat tmp.PRM 1 < topo.llt > tmpm.dat
[1] 1303036
[2] 1303037
[2]  + Done                   gmt surface atmp.xyz -bi3d -R0/21660/0/12188 -I8/4 -Gatmp.grd -T0.5 -N1000 -r
[1]  + Done                   gmt surface rtmp.xyz -bi3d -R0/21660/0/12188 -I8/4 -Grtmp.grd -T0.5 -N1000 -r
Reading in 5154 lines of info from XML...
Writing 16 lines for orbit...
Reading in range and azimuth shifts table...
Writing SLC..Image Size: 21660 X 12188...
Working on burst  #1 #2 #3 #4 #5 #6 #7 #8 #9
number of points clipped to short int 10
ls: cannot access '*slc': No such file or directory
ls: cannot access '*slc': No such file or directory
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
ls: cannot access '*slc': No such file or directory
Writing 53 lines of precise orbit for the LED file...
 can't open %s for reading S1_20200205_ALL_F1.SLC
ls: cannot access '*slc': No such file or directory
ls: cannot access '*slc': No such file or directory
ls: cannot access '*slc': No such file or directory
ls: cannot access '*slc': No such file or directory
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
awk: cmd. line:1: (FILENAME=- FNR=1) fatal: division by zero attempted
Successfully opened junk1
Reading in 5140 lines of info from XML...
Writing 16 lines for orbit...
Writing 53 lines of precise orbit for the LED file...
Shifting the master PRM by 0 lines...
Successfully opened junk1.PRM
Successfully opened junk2.PRM
......master LED file S1_20200112_100252_F1.LED
.........aligned LED file S1_20200217_100251_F1.LED
......master LED file S1_20200112_100252_F1.LED
.........aligned LED file S1_20200217_100251_F1.LED

**Comment by Xiaohua-Eric-Xu** [comment]
`ls: cannot access '*slc': No such file or directory` this seems to indicate that the SLC's not produced properly by make_s1a_tops. Could you do a `ls -lht` in your raw directory and show its content?

**Comment by wangjing1992** [comment]
Thank you very much. It seems to be running now. I checked the script and found that the 'mv' command (mv $tmp_stem.SLC $stem.SLC) cannot be executed without root.
