### ISSUE TITLE
[Feature]: Hermite interpolation is invalid

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#738]
By some reason, GMTSAR uses a peculiar Hermite interpolation code where extrapolation is not possible. Even for the predefined points, we cannot produce the expected results according to the theory. Moreover, this approach is not numerically optimal as it combines the fitting and interpolation stages. It is important to note that the errors observed below are meaningful because in both cases the interpolation results are well-defined:

```
hermite: interpolation not in center interval
Interpolated value at x=48150.000000: 1787734.527925
interpolation point outside of data constraints, 48160.000000 48064.000000 48154.000000
```
and the expected output is
```
Interpolated value at x=48150.0:  1787734.5283203125 (almost the same, while the error message above is wrong)
Interpolated value at x=48160.0:  1768378.997619629 (extrapolation, that's accurate using as values as derivatives)
```

See below my test for GMTSAR hermite_c function:
 
```
#include <stdio.h>
#include <assert.h>
#include <math.h>
#include "gmtsar.h"
#include "lib_functions.h"

void hermite_c(double *x, double *y, double *z, int nmax, int nval, double xp, double *yp, int *ir);

void test_hermite_c() {
    int nval = 6; /* number of points to use in interpolation */
    int nmax = 10; /* number of points in the arrays below */
    
    // Read the LED file and extract the data values
    // orb.isec[:10].values
    double x[] = {
       48064., 48074., 48084., 48094., 48104., 48114., 48124., 48134.,
       48144., 48154.
    };
    // orb.px[:10].values
    double y[] = {
       1941649.304103, 1924925.130555, 1907888.801379, 1890541.842833,
       1872885.827312, 1854922.373199, 1836653.144729, 1818079.851828,
       1799204.249944, 1780028.139872
    };
    // orb.vx[:10].values
    double z[] = {
       -1656.759849, -1688.050184, -1719.190204, -1750.175288,
       -1781.000831, -1811.662241, -1842.15494 , -1872.474369,
       -1902.615983, -1932.575255
    };
    
    double test_x[] = {
        48070.000000, 48078.000000, 48086.000000, 48092.000000, 48102.000000,
        48118.000000, 48128.000000, 48138.000000, 48150.000000, 48160.000000
    };
    
    for (int i = 0; i < nmax; i++) {
        double xp = x[i];
        double yp;
        int ir;

        // Perform the interpolation
        hermite_c(x, y, z, nmax, nval, xp, &yp, &ir);
        printf("Interpolated value at x=%f: %f (error %f)\n", xp, yp, yp - y[i]);
        assert(ir == 0);
    }
    printf("\n");
    for (int i = 0; i < nmax; i++) {
        double xp = test_x[i];
        double yp;
        int ir;

        // Perform the interpolation
        hermite_c(x, y, z, nmax, nval, xp, &yp, &ir);
        printf("Interpolated value at x=%f: %f\n", xp, yp);
    }
}

int main() {
    // Run the test
    test_hermite_c();

    return 0;
}

/*
gcc -I/usr/local/GMTSAR/gmtsar -I/opt/homebrew/Cellar/gmt/6.4.0_5/include/gmt/ hermite_c.c test_hermite_c.c -o test_hermite_c -lm && ./test_hermite_c
Interpolated value at x=48064.000000: 1941649.304103 (error 0.000000)
Interpolated value at x=48074.000000: 1924925.130555 (error 0.000000)
Interpolated value at x=48084.000000: 1907888.801379 (error 0.000000)
Interpolated value at x=48094.000000: 1890541.842833 (error 0.000000)
Interpolated value at x=48104.000000: 1872885.827312 (error 0.000000)
Interpolated value at x=48114.000000: 1854922.373199 (error 0.000000)
Interpolated value at x=48124.000000: 1836653.144729 (error 0.000000)
Interpolated value at x=48134.000000: 1818079.851828 (error 0.000000)
Interpolated value at x=48144.000000: 1799204.249944 (error 0.000000)
hermite: interpolation not in center interval
Interpolated value at x=48154.000000: 1780028.139872 (error 0.000000)

Interpolated value at x=48070.000000: 1931652.342476
Interpolated value at x=48078.000000: 1918147.973109
Interpolated value at x=48086.000000: 1904444.210371
Interpolated value at x=48092.000000: 1894036.010073
Interpolated value at x=48102.000000: 1876441.677945
Interpolated value at x=48118.000000: 1847651.280003
Interpolated value at x=48128.000000: 1829260.218019
Interpolated value at x=48138.000000: 1810565.788336
hermite: interpolation not in center interval
Interpolated value at x=48150.000000: 1787734.527925
interpolation point outside of data constraints, 48160.000000 48064.000000 48154.000000
*/
```

**Comment by Xiaohua-Eric-Xu** [comment]
Hermite interpolation requires 3 nodes on each side to properly constraint the solution. If such nodes does not exist, one could extrapolate the orbit first and then interpolate back (extend_orbit.c). 

For the program you attached, if I understand correctly, you assigned x, y, z and then interpolated at xp (x), the resulting yp is the same as y, which is expected. Then you asigned new xp as test_x, and got new yp. Sorry, what is the expected after that?

Hermite interpolation is one way of interpolating satellite orbit. I am not sure what is the optimal way of interpolating orbit.

**Comment by mobigroup** [comment]
> Hermite interpolation requires 3 nodes on each side to properly constraint the solution.

That's only your code problem because it realizes simplified quasi-Hermite interpolation.

> one could extrapolate the orbit first and then interpolate back (extend_orbit.c).

Actually, Hermite interpolation already allows extrapolation by design using the constructed polynomial.

> Hermite interpolation is one way of interpolating satellite orbit. I am not sure what is the optimal way of interpolating orbit.

Why not, it uses the coordinates and the speeds and provides the exact values in the defined points. I just speak about more accurate realization. 

> Sorry, what is the expected after that?

See the Python code were I calculate all the values using a standalone Hermite interpolation realization:

https://github.com/mobigroup/gmtsar/blob/pygmtsar/todo/orbit/read_orb_hermite.ipynb

**Comment by Xiaohua-Eric-Xu** [comment]
Wait, I thought the hermite program has velocities (derivatives, or z in the code) in it for interpolation. Feels what you mean is that it only uses positions. I forgot why we didn't use hermite for extrapolation though. I only remembered me talking to @dsandwell about what extrapolation methods to use and somehow we chose a specific order polynomial (in extend_orbit.c). It is rarely used though only when the product comes with very short orbit product.

**Comment by mobigroup** [comment]
> Wait, I thought the hermite program has velocities (derivatives, or z in the code) in it for interpolation. Feels what you mean is that it only uses positions

I wrote about “it uses the coordinates and the speeds” where “speed” is the position derivative (you call it “velocity”).

> I forgot why we didn't use hermite for extrapolation though.

Yes, it look’s weird. Your hermite_c.c provides Hermite interpolation in a moving window instead of a global solution, and the extend_orbit.c required to extend the local solution. Maybe is it related to some outdated issues in orbit files? For dozens or hundreds of records in LED files it doesn’t look related to performance reasons because it is fast in any way. Or is it possible to have lots of LED records for some satellites?

**Comment by mobigroup** [comment]
extend_orbit tool produces invalid orbit and the results is not even smooth (see red line). Standalone Hermite interpolation does it well - using a half of the orbit data it extrapolates the full orbit. So the extend_orbit result is useless:
![image](https://github.com/gmtsar/gmtsar/assets/7342379/34ebf876-8575-45be-8107-2fb806b73d53)

I've updated the notebook linked above for this test.

**Comment by Xiaohua-Eric-Xu** [comment]
I think not all orbit product comes as a whole like Sentinel-1. There were cases when one only have 5 orbit records with the data (e.g. RS2 and TSX). 

For extrapolation, it kind of depends on how long of an orbit it is. If it gets too long, the polynominal assumption is invalid. Are you able to extend the orbit with an hermite extrapolator? i.e. produce the black one with the blue one.

**Comment by mobigroup** [comment]
The black line is the extrapolated orbit using the full original orbit, and the blue line is the extrapolated orbit using the center half of the original orbit. As we can see, the blue line is visually identical to the original orbit (green), which suggests that the black line is also accurate. Hermite interpolation is also designed for extrapolation since it constructs a polynomial that can be used for infinite interpolation (although the accuracy may vary).
