### ISSUE TITLE
[Help]: Hi, I can't log in to VM with password : gmtsar noting that the default user is GIPSY. Tnks

### ISSUE THREAD

**Issue by migspace** [gmtsar/gmtsar#739]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, the default user is GIPSY? Did you download the right VM? http://topex.ucsd.edu/gmtsar/tar/Ubuntu21.04_gmt6.1_gmtsar6.2.ova

**Comment by mobigroup** [comment]
There are Docker images for GMTSAR and GMTSAR+PyGMTSAR on DockerHub: https://hub.docker.com/u/mobigroup These are the best for portability and reproducibility while add some overhead for the processing.

**Comment by migspace** [comment]
thank you professor
