### ISSUE TITLE
[Help]: When I use 'preproc_batch_tops.csh data.in dem.grd 2', I get some warnings and problems.

### ISSUE THREAD

**Issue by Xiongwei789** [gmtsar/gmtsar#740]
![image](https://github.com/gmtsar/gmtsar/assets/92964720/b0471759-95d8-47a0-babd-ecc308b0d10e)

**Comment by Xiongwei789** [comment]
[data.in.txt](https://github.com/gmtsar/gmtsar/files/11508410/data.in.txt)
[log.txt](https://github.com/gmtsar/gmtsar/files/11508411/log.txt)
There are data.in and log.txt files.

**Comment by Xiaohua-Eric-Xu** [comment]
Looks like warnings from GMT. Should not affect the processing though.
