### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by Xiongwei789** [gmtsar/gmtsar#742]
Hi everyone,
 I  wanted to use SBAS to derive postseismic deformation. When I used both S1A and S1B, I found that the interference pairs generated by S1A and S1B seem to consist of a ramp-like phase. Please see figures (S1A0908-S1B0914, S1A0908-S1B0926). However, it isn't shown in the interference pairs generated by the same satellite (S1A0908-S1A0920, S1A0908-S1A1002). 
I don't know if that's the truth or if I'm ignored by something
![phase](https://github.com/gmtsar/gmtsar/assets/92964720/6ba2a586-33a5-4bec-a8e6-663b5d53c660)

**Comment by Xiaohua-Eric-Xu** [comment]
It could be just atmospheric phases. S1A and S1B are about the same in terms of producing interferograms.
