### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by Alzaidy1** [gmtsar/gmtsar#743]

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu How about large psize for Goldstein filter? Not the same but comparable result is possible I suppose.

**Comment by Xiaohua-Eric-Xu** [comment]
Increasing the psize will make the result more smooth. However, overall, the Goldstein filter is an adaptive filter that applies stronger filtering for good data while weaker filtering for not-so-good data. Feel free to try it out by changing filter.csh/phasefilt. A major concern for this filter is that it may alter the radar phase significantly.

**Comment by Xiaohua-Eric-Xu** [comment]
Change line 204 in filter.csh in your GMTSAR/bin directory. 
```
204   phasefilt -imag imagfilt.grd -real realfilt.grd -amp1 amp1.grd -amp2 amp2.grd -psize 32
```
