### ISSUE TITLE
[Help]: orbit Decomposition with estimate vertical and horizontal movement

### ISSUE THREAD

**Issue by Obaida777** [gmtsar/gmtsar#747]
Dear All,

I hope you are doing well.

Lately I was writing script for doing Decomposition and estimating vertical and horizontal movement but i been getting error all the time when i have been running the script, please help and advise for any corrections and editing.[#!/bin/bash
 # Step 1: Get asc_los.grd and desc_los.grd from two tracks of measurements
 
 # Assuming you have asc_data.grd and desc_data.grd, convert them to asc_los.grd and desc_los.grd using gmt grdmath
gmt grdmath 1.grd COSD = asc_los.grd
gmt grdmath 2.grd COSD = desc_los.grd
 
 # Step 2: Use grdsample to coregister asc_los.grd and desc_los.grd to the same grid
 
 # Use grdsample to resample asc_los.grd and desc_los.grd
gmt grdsample asc_los.grd -Gasc_los_resampled.grd -I0.005+e/0.005+e
gmt grdsample desc_los.grd -Gdesc_los_resampled.grd -I0.005+e/0.005+e
 
 # Step 3: Perform the decomposition using GMT grdmath
 
 # Calculate average_look_cosine_vertical and average_look_cosine_east (assuming you have them as grd files)
average_look_cosine_vertical=average_look_cosine_vertical.grd
average_look_cosine_east=average_look_cosine_east.grd
 
 # Calculate vertical and horizontal using grdmath
gmt grdmath asc_los_resampled.grd desc_los_resampled.grd ADD 2 DIV $average_look_cosine_vertical DIV = vertical.grd
gmt grdmath desc_los_resampled.grd asc_los_resampled.grd SUB 2 DIV $average_look_cosine_east DIV = horizontal.grd
 
 # Display success message
echo "Decomposition completed successfully."
]()

Best Regards
Obaida
@Xiaohua-Eric-Xu @chintals @ericlindsey @dsandwell

**Comment by Xiaohua-Eric-Xu** [comment]
Not sure this is due to formatting issue, but your post is really hard to read. Maybe share your script by adding a .txt at the end of the file name?

**Comment by mobigroup** [comment]
@Obaida777 there are no real calculations in the script. You need to compute the satellite look vectors and the corresponding incidence angle first. When you have the projected components (vertical and west-east) just calculate an average value between the both orbits. For reference, you can check this example online: https://colab.research.google.com/drive/1PyYcxvuyzhh-g4NQEbKjcfTDQhREZInn?usp=sharing

![](https://user-images.githubusercontent.com/7342379/183816622-1dacce7e-6a2f-46b9-8e67-d701f55bdd30.png)

**Comment by Obaida777** [comment]
> Not sure this is due to formatting issue, but your post is really hard to read. Maybe share your script by adding a .txt at the end of the file name?

[orbit dec.txt](https://github.com/gmtsar/gmtsar/files/11645994/orbit.dec.txt)

**Comment by Obaida777** [comment]
> Not sure this is due to formatting issue, but your post is really hard to read. Maybe share your script by adding a .txt at the end of the file name?

**Comment by mobigroup** [comment]
PyGMTSAR performs the complete processing easily and allows to calculate displacement projections, detect seasonal and long-term trends, and more. In case you prefer to do the same on GMTSAR outputs you can adopt PyGMTSAR Python code or program the missed functions yourself.
