### ISSUE TITLE
[Help]: I  download demo Sentinel-1 TOPS Time Series ,I processed the interferograms as README_sbas.txt,input command  sbas intf.tab scene.tab 9 5 $xdim $ydim -smooth 1.0 -wavelength 0.0554658 -incidence 30 -range 800184.946186 -rms -dem,  errors  show

### ISSUE THREAD

**Issue by wanghengsoft** [gmtsar/gmtsar#748]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
Hmm, seems you attached everything in the title. Could you attach a log in the body instead?

**Comment by wanghengsoft** [comment]
Thank you for your reply.&nbsp;I have solved this problem，Maybe this command line "# set xdim = `gmt grdinfo -C ../intf_all/2015068_2015092/unwrap.grd | awk '{print $10}'`# set ydim = `gmt grdinfo -C ../intf_all/2015068_2015092/unwrap.grd | awk '{print $11}'`"&nbsp; is invalid ,&nbsp; I edit this line "sbas intf.tab scene.tab 9 5 $xdim $ydim -smooth 1.0 -wavelength 0.0554658 -incidence 30 -range 800184.946186 -rms -dem" ,replaced "$xdim $ydim" with "1348 1371"







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gmtsar/gmtsar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月16日(星期五) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gmtsar/gmtsar] [Help]: I  download demo Sentinel-1 TOPS Time Series ,I processed the interferograms as README_sbas.txt,input command  sbas intf.tab scene.tab 9 5 $xdim $ydim -smooth 1.0 -wavelength 0.0554658 -incidence 30 -range 800184.946186 -rms -dem,  errors  show (Issue #748)





 
Hmm, seems you attached everything in the title. Could you attach a log in the body instead?
