### ISSUE TITLE
LOS Deformation decomposition in GMTSAR

### ISSUE THREAD

**Issue by khakim** [gmtsar/gmtsar#75]
Dear Xiaohua(Eric) Xu 

I would like to decompose LOS Deformation  to NE and UD components from ascending and descending dataset in GMTSAR. Any script is in GMTSAR to do this decomposition?

Thanks in advance.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @khakim ,
We don't have a script but normally it could be decomposed by adding (UD) or subtracting (EW) your two-look LOS files and then scale with the look vectors, if their look vectors do not differ by a lot. 
Xiaohua(Eric)
