### ISSUE TITLE
[Help]: accuracy of registration

### ISSUE THREAD

**Issue by zhangdabao2020** [gmtsar/gmtsar#750]
**Describe the problem you met**
Hello, how can I obtain the accuracy of registration during the process of using the GMTSAR tool for image registration?

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @zhangdabao2020 , sorry for the late response. I think the accuracy of registration depends on the accuracy of orbits (for Sentinel-1 TOPS or other satellites if you are using geometric coregistration). e.g., for TOPS, the orbits are ~5cm cross track and 2cm along track. If you are doing xcorr for coregistration, it usually comes as ~0.1 pixel size.
