### ISSUE TITLE
[Help]: Installation on openSUSE OS

### ISSUE THREAD

**Issue by sreeram-radhakrishnan** [gmtsar/gmtsar#752]
**Describe the problem you met**

I have tried to install GMTSAR on openSUSE OS, I tried running commands using "zypper install package" but still I couldn't install GMTSAR, lot of the packages are not provided. give me some ideas and commands to install.

**OS and software version**

OS: OpenSUSE 15.5
GMTSAR version: 6.3 or greater

**Comment by Xiaohua-Eric-Xu** [comment]
Sorry for the late response. Could you provide more details on the output from terminal when you run step 4 here: https://github.com/gmtsar/gmtsar/wiki

**Comment by mobigroup** [comment]
There are Docker images for GMTSAR and GMTSAR+PyGMTSAR on DockerHub: https://hub.docker.com/u/mobigroup These are the best for portability and reproducibility while add some overhead for the processing.
