### ISSUE TITLE
[Feature]: Commands for openSUSE OS 

### ISSUE THREAD

**Issue by sreeram-radhakrishnan** [gmtsar/gmtsar#753]
A clear Description of commands to be used in openSUSE linux OS in the gmtsar Wiki page, now it is only providing commands to ubuntu all versions, Mac OS.

**Comment by adarshpadhi32** [comment]
prep_data_linux.csh  this comand has this response rm: cannot remove ‘data.in’: No such file or directory
ls: No match.
Looping over all the lines
Writing record

**Comment by Xiaohua-Eric-Xu** [comment]
Sorry that we removed the description on how to install on openSUSE. If you have a feasible work-flow (e.g. with fink or other package managers) and could share with us, it'll be much appreciated.

**Comment by sreeram-radhakrishnan** [comment]
Hello, @Xiaohua-Eric-Xu I have a feasible workflow for the installation of GMTSAR on OpenSuSE 15.4. I have attached the document here. Please have a look at it. This flow was suggested by another user in GitHub issues. 
[Installation of GMTSAR on SuSE 15.4.pdf](https://github.com/gmtsar/gmtsar/files/12026743/Installation.of.GMTSAR.on.SuSE.15.4.pdf)
Thank you.

**Comment by Xiaohua-Eric-Xu** [comment]
Updated here:https: //github.com/gmtsar/gmtsar/wiki/Installation-on-OpenSuSE
