### ISSUE TITLE
[Help]: my  prep_data_linux.csh  couldnot run through lunux 

### ISSUE THREAD

**Issue by adarshpadhi32** [gmtsar/gmtsar#755]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
If you can provide a log file, it'll be much much easier for us to know what actually happened.

**Comment by adarshpadhi32** [comment]
awk: cannot open data.in (No such file or directory)
awk: cannot open data.in (No such file or directory)
rm: No match.
rm: cannot remove 'baseline_table.dat': No such file or directory
awk: cannot open data.in (No such file or directory)
ls: No match.
table.gmt: No such file or directory.
gmtinfo [ERROR]: Error for input file: No such file (text)
region: Subscript out of range.
i got this error using this command - preproc_batch_tops.csh data.in dem.grd 1

**Comment by Xiaohua-Eric-Xu** [comment]
Where did you run this command ?

Is this the complete output from your terminal after you run prep_data_linux.csh?
