### ISSUE TITLE
[Help]: Geocode.csh Error

### ISSUE THREAD

**Issue by dr14nium** [gmtsar/gmtsar#756]
**Describe the problem you met**
I did processing the ALOS2 Brazil sample data, but experienced a failure in the geocode.csh section. The previous process has been successfully carried out, for some reason this section still fails. I initially ran on WSL2 with ubuntu version 22.04.02 LTS it worked. Then I tried to install the same version of ubuntu on my computer and I installed GMTSAR in the same way, there were no problems during the installation. But this error appears, please help me.

**OS and software version**
If applicable, what operating system and software version you are using?
OS: Ubuntu 22.04.02 LTS
GMTSAR version: 6.2

**Log file**
Attach a log file output from your terminal.

[sphere@sphere ~DownloadsALOS2_Brazil.txt](https://github.com/gmtsar/gmtsar/files/11883665/sphere%40sphere.DownloadsALOS2_Brazil.txt)

**Comment by mobigroup** [comment]
There are Docker images for GMTSAR and GMTSAR+PyGMTSAR on DockerHub: https://hub.docker.com/u/mobigroup These are the best for portability and reproducibility while add some overhead for the processing.

**Comment by Xiaohua-Eric-Xu** [comment]
This is probably not related to geocoding but this error here
```
hermite: interpolation not in center interval
nan!
```
Are you able to reproduce the error by running SAT_baseline PRM1 PRM2?
