### ISSUE TITLE
Strange image geometry from intf_tops.csh processing[Bug]: 

### ISSUE THREAD

**Issue by Loganator17** [gmtsar/gmtsar#76]
Hi GMTSAR-
I'm not able to login to the GMTSAR forum, so I'm posting my issues here

We are trying to create an InSAR time series from Sentinel-1 SLC data (path 085, frame 484). I've used the intf_tops.csh command on multiple datasets, but have encountered a new problem. We're not sure where it comes from. Basically, all images in the intf_all/*/ directories come out with geometry like the one I've uploaded below. A strange, aximuthal parallel line is observed as part of the images. The images only cover the top half of the subswatch being interfered. This line is seen in all correlation images, display_amp images, phase images, unwrap; .grd, .kml, .png... etc.  

The topo (dem.grd) has been checked to cover the entire image; different "super-master" images have been tested. When we use p2p processing, the images do not have this azimuthal line, but correctly produces the entire image.

Any ideas on where to start my debugging? Thanks!

Logan

![strange_geometry](https://user-images.githubusercontent.com/46734499/102285613-1e31a380-3ee3-11eb-8d3b-1e7140e3c2ba.PNG)

**System and software version:**
 - GMTSAR version: 6.1

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @Loganator17 ,
Here are a few things to check. 1) did you specify region_cut or the strip is extra (out of data coverage)? 2) Do you have a log file of you running intf_tops.csh? 3) if you open topo_ra.grd in the topo folder, anything wrong with that?
Xiaohua(Eric)

**Comment by Loganator17** [comment]
Hi Eric!

1) we want the whole area processed, hence no region_cut was applied
2) output from the processing was directed to an error_report.txt, I've attached it here
3) I just checked the topo_ra.grd, this file seems fine

It's a really strange error, one I've not seen before. I appreciated you looking into this!
[error_report.txt](https://github.com/gmtsar/gmtsar/files/5705455/error_report.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Did you also check the files in radar coordinates? If they have exactly the same issue, we could rule out geocoding error. Another way to check is run slc2amp.csh on the PRM/SLC data, you need to tune the colorscale to make it look reasonable. This could help check on the original data.

**Comment by dsandwell** [comment]
Hi @Loganator17 , https://urldefense.com/v3/__https://github.com/Loganator17__;!!Mih3wA!QFh-iIvZp_0sgnUkG2YHiH0yfdgQLtohEKQxWBXOmM-NN2xMeUbCHV3ux7DO4iGA$

When I looked at the error is seemed to be related to geocoding.  If the images look good in radar coordinates then I would suspect the trans.dat file.  Maybe the typo_ra.grd file has a big cliff somewhere or there could be an error in the orbit file.  Maybe just recompute the trans.dat and see if the new and old files match.

> On Dec 16, 2020, at 2:35 PM, Xiaohua(Eric) Xu <notifications@github.com> wrote:
> 
> 
> Did you also check the files in radar coordinates? If they have exactly the same issue, we could rule out geocoding error. Another way to check is run slc2amp.csh on the PRM/SLC data, you need to tune the colorscale to make it look reasonable. This could help check on the original data.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

David T. Sandwell
IGPP 0225
Scripps Inst. of Oceanography
La Jolla, CA
92093-0225

Ph. 858 534-7109
Cell 858 663-9426
http://topex.ucsd.edu

Express Mail Address:
8795 Biological Grade
Room 1102
La Jolla, CA 92037

**Comment by Loganator17** [comment]
Thank you both for coming to save the day! It appears this is an issue with the data, I think. All .grd files, including those in radar coordinates, are showing the same strange line.

using the slc2amp.csh, I've produced the attached image. Is this indicative of bad data? we have more than 1 path/frame showing similarly strange geometry

I used this code to produce the image, this PRM is from the master
slc2amp.csh S1_20200101_ALL_F2.PRM 2 test.grd

![emily2](https://user-images.githubusercontent.com/46734499/102423540-bb5d0c80-3fb5-11eb-89d4-751d70e1ab99.PNG)

**Comment by Xiaohua-Eric-Xu** [comment]
Do you have the log file when you ran preproc_batch_tops.csh?

**Comment by Loganator17** [comment]
I'm helping a colleague with this issue, I doubt we've saved the log file from preproc_batch_tops.csh. I can rerun it quickly, as we have cut the process down to just a few SAR images in order to diagnose it- unless the log file is automatically saved, and it is in the raw folder?

**Comment by Xiaohua-Eric-Xu** [comment]
Unfortunately, no. Also please record all the outputs from your terminal with >&

**Comment by Loganator17** [comment]
[preproc_2_error.txt](https://github.com/gmtsar/gmtsar/files/5706571/preproc_2_error.txt)
[preproc_1_error.txt](https://github.com/gmtsar/gmtsar/files/5706572/preproc_1_error.txt)

I have one log file from each preproc_batch_tops.csh setting attached.

**Comment by Xiaohua-Eric-Xu** [comment]
Could you show me your data.in you used?

**Comment by Xiaohua-Eric-Xu** [comment]
I guess you mixed data from different sub-swaths.

**Comment by Loganator17** [comment]
[data.txt](https://github.com/gmtsar/gmtsar/files/5706623/data.txt)
I renamed it data.txt for GITHUB

**Comment by Loganator17** [comment]
ok. I'll try using the select_pairs.csh GMTSAR provides, and see if that works better than the script I wrote.

**Comment by Xiaohua-Eric-Xu** [comment]
Yeah, this is the problem. preproc_batch_tops.csh and intf_tops.csh are for processing a subswath of data. Supposingly, one should not put data from different subswaths in to one file and try to process it. 
Here's a document that might help.

**Comment by Xiaohua-Eric-Xu** [comment]
https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_2.pdf
Forgot to attach the link.
