### ISSUE TITLE
[Help]: preproc_batch_tops.csh

### ISSUE THREAD

**Issue by adarshpadhi32** [gmtsar/gmtsar#761]
hi eric, i faced some issue in using this command 'preproc_batch_tops.csh data.in dem.grd 1 > pbt_mode1.log'  and all xml, EOF, tiff files are okay also the data file is alright.  this is how my issue looks like 
![image](https://github.com/gmtsar/gmtsar/assets/137491988/e8f7877d-c2bd-4bf4-b4ad-b9d5f1d9107d)

**Comment by Xiaohua-Eric-Xu** [comment]
Did you install which version of GMTSAR? Could it be this case where you'll need to update to 6.3 or master branch? https://github.com/gmtsar/gmtsar/discussions/629

**Comment by adarshpadhi32** [comment]
I changed orbit files from precise to  restituted for 2023 data ( 2022 data with precise orbit files and 2023 data with restituted orbit files) then, it worked.

**Comment by Xiaohua-Eric-Xu** [comment]
Might be good to update the code in case you want to use precise orbit files. Not sure why ESA introduced a blank line to the orbit data, but the code in GMTSAR now could handle that.

**Comment by adarshpadhi32** [comment]
how to update that ?

**Comment by Xiaohua-Eric-Xu** [comment]
Go to your GMTSAR directory, run `git switch 6.3`, `git pull`, `make clean`, `make` and then `make install`.

**Comment by Xiaohua-Eric-Xu** [comment]
could use `git switch master` too.
