### ISSUE TITLE
[Help]: GNSS displacement 

### ISSUE THREAD

**Issue by omarwater98** [gmtsar/gmtsar#763]
Hello, I am looking to compare the displacements of my time series taken from sentinel-1 images with an antenna near my town. On the Nevada Geodetic Laboratory page, which of the formats and which column should I use for the GNSS antenna offsets?

tenv3, tenv or xyz???

http://geodesy.unr.edu/NGLStationPages/stations/ISLP.sta
![Tenv, tenv3, xyz](https://github.com/gmtsar/gmtsar/assets/113547446/f6bc5b55-6dd9-4877-8ec2-d108fcf0298e)

**Comment by Xiaohua-Eric-Xu** [comment]
This is an GNSS question and unfortunately I don't know the answer. :(
