### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by shivamshuklaz** [gmtsar/gmtsar#764]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through
[config.log](https://github.com/gmtsar/gmtsar/files/12079709/config.log)
I **have already installed GCC, CC, cl.exe and clang but there are showing that Checking for gcc ...no
checking for cc ... no, 
I have also mentioned a snapshot & log file in this attachment. ** 
I am using Jim jellyfish  of ubuntu 20.04 LTS version
**OS and software version**
If applicable, what operating system and software version you are [using?](

> ![WhatsApp Image 2023-07-18 at 4 39 22 PM](https://github.com/gmtsar/gmtsar/assets/75002574/969d9bc4-ecfb-4ba6-8163-59efb856d35d)

)
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by mobigroup** [comment]
There are Docker images for GMTSAR and GMTSAR+PyGMTSAR on DockerHub: https://hub.docker.com/u/mobigroup These are the best for portability and reproducibility while add some overhead for the processing.

**Comment by Xiaohua-Eric-Xu** [comment]
1) Did you ran autoconf first?
2) Did you get a config.mk file produced at /usr/local/GMTSAR after running ./configure?
