### ISSUE TITLE
[Help]: gmtsar2stamps for processing ps-insar

### ISSUE THREAD

**Issue by sreeram-radhakrishnan** [gmtsar/gmtsar#765]
How to convert from interferogram generated using GMTSAR to stamps process for time series analysis (ps-InSAR). Help me in this regard. Thank you.

**Comment by Xiaohua-Eric-Xu** [comment]
Maybe this is the package you are looking for? https://github.com/xiaopengtong/gmtsar2stamps

**Comment by sreeram-radhakrishnan** [comment]
Hello,  I tried with this package, But while running StaMPS process, I'm getting lot of error in sentinel-1 stripmode data. Help me to fix this issue. Is there any other way to work on StaMPS process from GMTSAR as a processor. Thank you.

**Comment by Xiaohua-Eric-Xu** [comment]
Strip mode data are a bit different from TOPS. How did you generate a coregistered stack of SLCs with GMTSAR for Sentinel-1 Stripmap data?

**Comment by sreeram-radhakrishnan** [comment]
Hello @Xiaohua-Eric-Xu  In GMTSAR, I used batch_processing.csh for processing stripmode data.

**Comment by Xiaohua-Eric-Xu** [comment]
OK, if that's the case, it could be that something went wrong during the gmtsar2stamps. But I am not the author of the package so am not sure how to help you debug the process.

**Comment by sreeram-radhakrishnan** [comment]
Thanks @Xiaohua-Eric-Xu . currently I'm trying to work on INSAR_G2S package for stripmode data for working on Ps-InSAR method. Thank you.
