### ISSUE TITLE
Geocoding[Help]: 

### ISSUE THREAD

**Issue by AmiraZakii** [gmtsar/gmtsar#766]
Hello,
I have a question please , I am running GMTSAR for descending images but even after the unwrapping step, the interferograms do not geocode, although for ascending images, they are geocoded. If I will run the SBAS step for the descending images, will the images be geocoded automatically, or do I need to perform a separate step now before SBAS step?
Thank you

**Comment by Xiaohua-Eric-Xu** [comment]
If you set geocode_threshold = 0, then the geocoding step will get skipped. For manual geocoding, run proj_ra2ll.csh.
