### ISSUE TITLE
[Bug]: unwrap_parallel.csh intflist 20

### ISSUE THREAD

**Issue by moment-maker** [gmtsar/gmtsar#768]
Hello, Xu. When I use parallel commands to phase unwrap, the program always stays stuck in one place, that's why? And I'm going to show you the result of my second rerun, which is still stuck here, and it's not going to work all night. Please ignore the "file exists" because this is the second run.
![image](https://github.com/gmtsar/gmtsar/assets/66958429/2fa6b9ec-0cb0-49ee-85b5-d5a8a3be3594)
another question, Why, after running the unwrap command, the program always likes to rebuild the same folder under the interference folder, which has been encountered many times, as shown in the following figure.
![image](https://github.com/gmtsar/gmtsar/assets/66958429/e6877f1e-9d74-4319-8828-5b5ef5a0fcff)
Looking forward to your reply！

**Comment by Xiaohua-Eric-Xu** [comment]
in your unwrap_intf.csh, did it redirect the output to a log file? e.g., snaphu_interp.csh 0.1 0 > log_unwrap
