### ISSUE TITLE
[Help]: fatal error: gmt.h: No such file or directory

### ISSUE THREAD

**Issue by joaoaraujo87** [gmtsar/gmtsar#770]
Hi,

I am trying to install GMTSAR but it fails during make. Tried in two different machines with same OS. On both machines I have GMT installed. I was thinking it could be from GMT paths not well defined so I tried changing GMT_INC and GMT_LIB on config.mk file in /usr/local/GMTSAR installation dir. But still could not solve problem. Anyone has an idea of the issue?

OS: Centos7
GMTSAR version: 6.3

[out.txt](https://github.com/gmtsar/gmtsar/files/12207332/out.txt)

**Comment by joaoaraujo87** [comment]
Solved. Need to build GMT from source. Using sudo yum install gmt did not work.

**Comment by mobigroup** [comment]
There are Docker images for GMTSAR and GMTSAR+PyGMTSAR on DockerHub: https://hub.docker.com/u/mobigroup These are the best for portability and reproducibility while add some overhead for the processing.

**Comment by Xiaohua-Eric-Xu** [comment]
It should give you gmt header and libs if you install libgmt-dev sometimes with yum.

**Comment by joaoaraujo87** [comment]
Thank you Xiaohua,

I looked for that in my second machine but for Centos7 I did not find any repos. Tried RPMs, libgmt-devel.x86_64, etc.

The problem was solved by building GMT 6.4.0 from source and then edit GMT_INC and GMT_LIB paths in config.mk file from GMTSAR.

But now I have other errors that look like this:

error: ‘struct GMT_GRID_HEADER’ has no member named ‘nx’

There is a Q&A for this issue on GMT forum but it was not solved: 
https://forum.generic-mapping-tools.org/t/trouble-building-gmtsar-with-the-most-recent-gmt/582

Here is my terminal output with error messages:
[out2.txt](https://github.com/gmtsar/gmtsar/files/12229945/out2.txt)

Cheers

**Comment by Xiaohua-Eric-Xu** [comment]
It could be that you tried to install GMTSAR 5.x. There is a parameter name change in GMT so GMTSAR changed that accordingly where nx and ny are changed to n_rows and n_columns since nx/ny are abandoned in GMT. Try install GMTSAR 6.x or master and the error should be resolved.
