### ISSUE TITLE
[Help]: preproc_batch_tops.csh

### ISSUE THREAD

**Issue by laxmangeo** [gmtsar/gmtsar#771]
Hi, 
  I am working in WSL,  when i tried to run the preproc_batch_tops.csh command I faced couldn't open xml file error. help me
![xml file](https://github.com/gmtsar/gmtsar/assets/127308214/11ac13bb-cb9b-4f74-bcb2-b04495daa504)

**Comment by Xiaohua-Eric-Xu** [comment]
Looks like a permission issue. You may need to make sure that you have access to all the data and orbit files (.EOF).

**Comment by laxmangeo** [comment]
yes sir you are correct, problem solved
