### ISSUE TITLE
hi. why do we detrend before SBAS

### ISSUE THREAD

**Issue by sonasharma25** [gmtsar/gmtsar#772]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by sonasharma25** [comment]
why do we dtrend before SBAS step in InSAR processing?. how can we detrend?

**Comment by mobigroup** [comment]
See this live interactive Jupyter notebook on Google Colab where are two results (with and without detrending) compared: https://colab.research.google.com/drive/1sljxm2jAMGXynq4EYam6Siz8OLcPLN0h?usp=sharing

**Comment by sonasharma25** [comment]
thank you sir

**Comment by Xiaohua-Eric-Xu** [comment]
In principle, you don't have to. Whether to detrend or not depends your target of interest. For small areas, e.g., mines, dams, city subsidence, etc., you could detrend to mitigate errors from atmosphere or orbits.

**Comment by sonasharma25** [comment]
Thank you.
