### ISSUE TITLE
High time consumption of Snaphu process[Help]: 

### ISSUE THREAD

**Issue by Zeeshanktk1992** [gmtsar/gmtsar#773]
**Describe the problem you met**
I am processing data for landslide monitoring for 5 years. Now I am using SBAS and make paired of 297 interferograms.  The Snaphu v2.0.4 is computing the process and its taking really long time. From around 3 days (72 hours) it only make 2 years yet 295 is processing. What is the possible way to make the process faster. 
I have done the same process for 32 pairs but it didn't take that long time.

**OS and software version**
Ubuntu 20 GMTSAR 6
OS:
GMTSAR version: 6

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Its still processing but for the Snaphu the file used is "snaphu.conf.brief"

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by mobigroup** [comment]
SNAPHU has tiling unwrapping option which can greatly reduce the required time. See the interactive notebook on Google Colab for detals: https://colab.research.google.com/drive/17D53uZu3XcEoWz5T73D__t9Ampzn5l3J?usp=sharing#scrollTo=YKYp_wFcf6yb Pay attention to the custom SNAPHU config and the table for unwrapping times for different tiling.

**Comment by Xiaohua-Eric-Xu** [comment]
Yes tile mode will give you faster solution but do note phase unwarpping is a global solution, and piecing sub-region solutions together may not necessarily grant you the same solution as unwrapping the entire image, though usually it is a fine solution for good quality data.

**Comment by mobigroup** [comment]
Using recommended tile overlaps 200-400 pixels we often have the same solution. Also, single tile optimization option allows to rebuild global solution on the tiled one (it’s much faster but still memory consuming operation).

**Comment by Zeeshanktk1992** [comment]
Thanks for the response. I have reduce the number of interferograms and also the wavelength size from 200 to 400. 
Now i am facing problem in SBAS. I have 205 Interferogram pairs (intf.tab) and 108 (Scene.tab). But i am facing problem of "Segmentation fault core (dumped error)". Although this problem is already discussed in Issue 112, but according to the solution from Issue 112 if we reduce the data then the problem will be resolved. 
But, I have tried multiple times by reducing it again and again. And lastly when i leave only 20 Interferogram with 13 scenes then its work but its not of my use. I want to process whole data together to get annual deformation for 5 years data.

**Comment by mobigroup** [comment]
GMTSAR SBAS is not suitable to process large stacks. If you need to complete the analysis see more powerful InSAR processor PyGMTSAR which can perform SBAS analysis for 2000 interferograms even on Apple Air laptop: https://github.com/mobigroup/gmtsar There are some single-click interactive Google Colab examples including SBAS on the Github page.

**Comment by Zeeshanktk1992** [comment]
Thanks for your suggestion. But their will be definitely some way to process SBAS large data. Because in SBAS 200 pairs is not too big data. I will check the PyGMTSAR. In PyGMTSAR we can now process the same interferograms for further sbas analysis or we need to make all the process from start.

**Comment by Zeeshanktk1992** [comment]
@mobigroup Thanks for your reply. I just want to know that for PyGMTSAR we have to do all the process again from zero or we can process the interferograms for SBAS results? 
@Xiaohua-Eric-Xu Do we have some way to process large data in GMTSAR for SBAS analysis as I have mentioned in my last comment regarding the issue of "Segmentation fault core (dumped error)". I will be thankful for your response.

**Comment by mobigroup** [comment]
The easiest approach is to complete the full processing in PyGMTSAR. It is considerably faster and more accurate than GMTSAR calculations due to superior parallelization and the ability to use correct multi-looking instead of decimation. It also allows for the exclusion of the Goldstein filter when it's not beneficial, among other advantages. Additionally, if you have Python programming skills, you can load the GMTSAR rasters, although I wouldn't recommend this method."

**Comment by mobigroup** [comment]
> Do we have some way to process large data in GMTSAR for SBAS analysis

The sbas_parallel tool is better suited for processing large datasets. However, if it doesn't meet your requirements, I'm afraid there aren't many other options available.
