### ISSUE TITLE
[Help]: problem while using detrend 

### ISSUE THREAD

**Issue by sonasharma25** [gmtsar/gmtsar#774]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by sonasharma25** [comment]
hi. When i use command to detrend, i got this issue. 
![Screenshot from 2023-08-01 16-12-16](https://github.com/gmtsar/gmtsar/assets/140051286/51f51787-6f67-46f1-9f24-5526c3c86ae2)

**Comment by Xiaohua-Eric-Xu** [comment]
This looks like a customized script from a user, so I could not provide much insight. It could be that the user used GMT4 where you don't need to put gmt in front of every command.

**Comment by sonasharma25** [comment]
okay sir. Thank you
