### ISSUE TITLE
how to control resolution[Help]: 

### ISSUE THREAD

**Issue by AmiraZakii** [gmtsar/gmtsar#775]
Hello,
I followed this tutorial, "How to make an InSAR time series from Sentinel-1 TOPS data: Kilauea" but I have a question about how I can control the resolution of pixels to be 100 m?  in which step can I control that? 

Also, in the unwrapping step (snaphu_interp.csh 0.001 40), what 40 refers to?
Thanks in advance 
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
You could set filter_wavelength to 100m so your sampling after geocoding will be likely 25m. For TOPS, you may need to set range_dec = 4 and azimuth_dec = 1 correspondingly. For other satellites/acquisition modes, you may need to compute these numbers.

40 means a maximum of 40 cycles of phase discontinuities are allowed to exist in the unwrapped phase. If you are using snaphu_interp.csh, it is usually recommended to set it to 0 (in the sense that if you believe there is a strong discontinuity in the map, you should not interpolate the data).

**Comment by AmiraZakii** [comment]
@Xiaohua-Eric-Xu Thanks for your reply. So this means if I want to have a pixel resolution of 100 m, set filter_wavelength 100 and if I wish for the pixel resolution to be 30 m, set filter_wavelength 30. Is this the way to control the resolution? 

Also, what do you recommend if the study area does not represent earthquakes or strong deformation; is it usually show small deformation? Is a larger wavelength, like 200 or more, better in this case??

**Comment by Xiaohua-Eric-Xu** [comment]
This is currently how GMTSAR handles resolution, though the sampling could be forced with range_dec and azimuth_dec in the config file. If not set, the sampling will be roughly 1/4 filter_wavelength.

If your target is an earthquake, I would just use 200m which is the default. For area with stronger decorrelation, one could tune up this parameter to reduce the number of residues so phase unwrapping is easier to run.
