### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by matlabCPU** [gmtsar/gmtsar#778]
Create a merge_ list, I am already in intf_ all folder manually created the intflist file, but was using “create_merge_input.csh intflist .. 2 > merge_list” There is still an error during the list command. May I ask if the intflist file was manually created and contains the following content？

![1691047012970](https://github.com/gmtsar/gmtsar/assets/118905130/0742f559-ff79-4388-bda8-aeb30902598e)

**Comment by Xiaohua-Eric-Xu** [comment]
Yes. Could you attach the error you met?

**Comment by matlabCPU** [comment]
> 是的。你能附上你遇到的错误吗？

Thank you very much for your reply, I have fixed this issue, thanks
