### ISSUE TITLE
[Help]: merge_batch.csh error

### ISSUE THREAD

**Issue by matlabCPU** [gmtsar/gmtsar#780]
DEAR PROFESSOR：
I am currently using GMTSAR for Sentinel 1 data processing, but I have encountered some issues during use and find it difficult to resolve.
When I perform a Run merge_ batch.csh, the following error occurred. I am not sure if I also encountered the problem during the previous intervention, intf_ all files in all are as follows. I hope to receive your reply. Thank you

![image](https://github.com/gmtsar/gmtsar/assets/118905130/89cf808a-1bc6-41bf-9d96-8772d99a874f)
![image](https://github.com/gmtsar/gmtsar/assets/118905130/0d025bd3-7d03-4b29-9526-683f6041463b)
![image](https://github.com/gmtsar/gmtsar/assets/118905130/289e7707-1401-4061-ad81-9131c0c8bf41)
![image](https://github.com/gmtsar/gmtsar/assets/118905130/db706ff6-86d0-464b-9303-e5fb7c1b343a)

**Comment by matlabCPU** [comment]
this is itp.log
[itp.log.txt](https://github.com/gmtsar/gmtsar/files/12288346/itp.log.txt)

**Comment by matlabCPU** [comment]
I'm trying a single interferogram
root@gjq:/media/gjq/Gjq/GMT_text/dsc/F1# intf_tops.csh one.in batch_tops.config

START FORM A STACK OF INTERFEROGRAMS


INTF.CSH, FILTER.CSH - START
using command line
......master LED file S1_20220816_ALL_F1.LED 
.........aligned LED file S1_20220828_ALL_F1.LED 
using command line
......master LED file S1_20220816_ALL_F1.LED 
.........aligned LED file S1_20220816_ALL_F1.LED 
intf.csh
running phasediff...
reading topo topo_ra.grd
phasediff [ERROR]: Cannot find file topo_ra.grd
phasediff [ERROR]: Cannot find file topo_ra.grd
phasediff [ERROR]: File topo_ra.grd not found
[Session phasediff (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open topofile topo_ra.grd 
filter.csh
Segmentation fault (core dumped)
setting range_dec = 8, azimuth_dec = 2
gauss_200 2 4 (1 2)
making amplitudes...
 Can't open filter  
 Can't open filter  
filtering interferogram...
conv [ERROR]: Cannot find file real.grd
conv [ERROR]: Cannot find file real.grd
conv [ERROR]: File real.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real.grd=bf 
 Can't open filter  
conv [ERROR]: Cannot find file imag.grd
conv [ERROR]: Cannot find file imag.grd
conv [ERROR]: File imag.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag.grd=bf 
 Can't open filter  
making amplitude...
grdmath [ERROR]: realfilt.grd is not a number, operator or file name
grdmath [ERROR]: amp.grd is not a number, operator or file name
grdinfo [ERROR]: Cannot find file display_amp.grd
grdinfo [ERROR]: Must specify one or more input files
grd2cpt [ERROR]: Cannot find file display_amp.grd
grd2cpt [ERROR]: Option -L: Cannot decode two limits
grdimage [ERROR]: Cannot find file display_amp.grd
psscale [ERROR]: Could not parse display_amp.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:

  -R<west>/<east>/<south>/<north>[+r]
     Specify the min/max coordinates of your data region in user units. Use
     dd:mm[:ss] for regions given in arc degrees, minutes [and seconds]. Use
     -R<xmin>/<xmax>/<ymin>/<ymax>[+u<unit>] for regions given in projected
     coordinates, with <unit> selected from e|f|k|M|n|u. [e] Use
     [yyyy[-mm[-dd]]]T[hh[:mm[:ss[.xxx]]]] format for time axes. Append +r if
     -R specifies the coordinates of the lower left and upper right corners of
     a rectangular area.
     Alternatively, use -R<code><x0>/<y0>/<n_columns>/<n_rows> for origin and
     grid dimensions, where <code> is a 2-char combo from [T|M|B][L|C|R] (top/⏎
     …middle/bottom/left/center/right) and grid spacing must be specified via
     -I<dx>[/<dy>] (also see -r).
psscale [ERROR]: Offending option -Rdisplay_amp.grd
psconvert [ERROR]: The file display_amp.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making correlation...
grdmath [ERROR]: amp1.grd is not a number, operator or file name
grdmath [ERROR]: tmp.grd is not a number, operator or file name
grdmath [ERROR]: amp.grd is not a number, operator or file name
conv [ERROR]: Cannot find file tmp2.grd
conv [ERROR]: Cannot find file tmp2.grd
conv [ERROR]: File tmp2.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  tmp2.grd=bf 
grdimage [ERROR]: Cannot find file corr.grd
psscale [ERROR]: Could not parse corr.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:

  -R<west>/<east>/<south>/<north>[+r]
     Specify the min/max coordinates of your data region in user units. Use
     dd:mm[:ss] for regions given in arc degrees, minutes [and seconds]. Use
     -R<xmin>/<xmax>/<ymin>/<ymax>[+u<unit>] for regions given in projected
     coordinates, with <unit> selected from e|f|k|M|n|u. [e] Use
     [yyyy[-mm[-dd]]]T[hh[:mm[:ss[.xxx]]]] format for time axes. Append +r if
     -R specifies the coordinates of the lower left and upper right corners of
     a rectangular area.
     Alternatively, use -R<code><x0>/<y0>/<n_columns>/<n_rows> for origin and
     grid dimensions, where <code> is a 2-char combo from [T|M|B][L|C|R] (top/⏎
     …middle/bottom/left/center/right) and grid spacing must be specified via
     -I<dx>[/<dy>] (also see -r).
psscale [ERROR]: Offending option -Rcorr.grd
psconvert [ERROR]: The file corr.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making phase...
grdmath [ERROR]: imagfilt.grd is not a number, operator or file name
grdimage [ERROR]: Cannot find file phase.grd
psscale [ERROR]: Could not parse phase.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:

  -R<west>/<east>/<south>/<north>[+r]
     Specify the min/max coordinates of your data region in user units. Use
     dd:mm[:ss] for regions given in arc degrees, minutes [and seconds]. Use
     -R<xmin>/<xmax>/<ymin>/<ymax>[+u<unit>] for regions given in projected
     coordinates, with <unit> selected from e|f|k|M|n|u. [e] Use
     [yyyy[-mm[-dd]]]T[hh[:mm[:ss[.xxx]]]] format for time axes. Append +r if
     -R specifies the coordinates of the lower left and upper right corners of
     a rectangular area.
     Alternatively, use -R<code><x0>/<y0>/<n_columns>/<n_rows> for origin and
     grid dimensions, where <code> is a 2-char combo from [T|M|B][L|C|R] (top/⏎
     …middle/bottom/left/center/right) and grid spacing must be specified via
     -I<dx>[/<dy>] (also see -r).
psscale [ERROR]: Offending option -Rphase.grd
psconvert [ERROR]: The file phase.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
filtering phase...
phasefilt [ERROR]: Cannot find file imagfilt.grd
phasefilt [ERROR]: Cannot find file imagfilt.grd
phasefilt [ERROR]: File imagfilt.grd not found
[Session phasefilt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 error reading file imagfilt.grd 
grdinfo [ERROR]: Cannot find file mask.grd
grdinfo [ERROR]: Must specify one or more input files
grdedit [ERROR]: Cannot find file filtphase.grd
grdmath [ERROR]: filtphase.grd is not a number, operator or file name
grdimage [ERROR]: Cannot find file phasefilt.grd
psscale [ERROR]: Could not parse phasefilt.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:

  -R<west>/<east>/<south>/<north>[+r]
     Specify the min/max coordinates of your data region in user units. Use
     dd:mm[:ss] for regions given in arc degrees, minutes [and seconds]. Use
     -R<xmin>/<xmax>/<ymin>/<ymax>[+u<unit>] for regions given in projected
     coordinates, with <unit> selected from e|f|k|M|n|u. [e] Use
     [yyyy[-mm[-dd]]]T[hh[:mm[:ss[.xxx]]]] format for time axes. Append +r if
     -R specifies the coordinates of the lower left and upper right corners of
     a rectangular area.
     Alternatively, use -R<code><x0>/<y0>/<n_columns>/<n_rows> for origin and
     grid dimensions, where <code> is a 2-char combo from [T|M|B][L|C|R] (top/⏎
     …middle/bottom/left/center/right) and grid spacing must be specified via
     -I<dx>[/<dy>] (also see -r).
psscale [ERROR]: Offending option -Rphasefilt.grd
psconvert [ERROR]: The file phasefilt.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
mv: cannot stat 'mask.grd': No such file or directory
grdmath [ERROR]: tmp.grd is not a number, operator or file name
INTF.CSH, FILTER.CSH - END

SKIP UNWRAP PHASE

GEOCODE.CSH - START
SKIP GEOCODING

END STACK OF TOPS INTERFEROGRAMS

**Comment by Xiaohua-Eric-Xu** [comment]
Did you run step 1 to produce topo_ra.grd before running a GNU-paralleled interferogram generation?
