### ISSUE TITLE
SBAS inversion [Help]: 

### ISSUE THREAD

**Issue by sonasharma25** [gmtsar/gmtsar#781]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by mobigroup** [comment]
You can find the math and illustrations here: https://www.patreon.com/posts/linear-algebra-80283980 and Python realization: https://github.com/mobigroup/gmtsar/blob/pygmtsar/pygmtsar/pygmtsar/SBAS_sbas.py

**Comment by Xiaohua-Eric-Xu** [comment]
A few good papers to read are here (for the sbas program in GMTSAR): 
https://ieeexplore.ieee.org/abstract/document/1166596/
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2002JB002267
https://www.sciencedirect.com/science/article/pii/S0034425716303510
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015JB011886
https://ieeexplore.ieee.org/abstract/document/7938636

**Comment by mobigroup** [comment]
@Xiaohua-Eric-Xu Let me summarize all the links. Is the primary approach based on a non-weighted or correlation-weighted least-squares solution? Are only 3-diagonal matrices (SBAS triangles) being analyzed? Additionally, are all seasonal movements smoothed using the iterative solution in the Tymofyeyeva algorithm?

**Comment by Xiaohua-Eric-Xu** [comment]
Here are some of my answers.

> Is the primary approach based on a non-weighted or correlation-weighted least-squares solution? 

coherence weighted sbas

> Are only 3-diagonal matrices (SBAS triangles) being analyzed? 

Nope, it depends on user's choice of interferograms.

> Additionally, are all seasonal movements smoothed using the iterative solution in the Tymofyeyeva algorithm?

It depends on whether a user chose to turn that on or not.

**Comment by mobigroup** [comment]
> Nope, it depends on user's choice of interferograms.

Please refer to the papers for the full matrix solution. It should provide displacements for wrapped input phases using all the SBAS pair interferograms (such as six interferograms for each reference date).
