### ISSUE TITLE
problem about "gmtsar_rs2_demo"

### ISSUE THREAD

**Issue by HPUdabiao** [gmtsar/gmtsar#782]
when I study the demo.I have a problem with "dem2topo_ra.csh RS220110515.PRM dem.grd 1",show the error above.
![1M47 }O942@1RXSUFUUEZA4](https://github.com/gmtsar/gmtsar/assets/140577628/dd352dee-cc5c-4e5d-8cbc-a5867b281127)

GMTSAR version:6.2 GMT version 6.0
I guass if the gmt version is low?
But in the demo, I use the "p2p_processing.csh RS2 RS220110515 RS220110819 config.txt" ,the result is ok.so I do not how to solve.look forward to your reply.

**Comment by Xin-Wang-520** [comment]
Do you have the  RS220110515.PRM  in your topo folder ? Look at the content of the log file. and whether the scope of the dem is completely covered?

**Comment by Xin-Wang-520** [comment]
> when I study the demo.I have a problem with "dem2topo_ra.csh RS220110515.PRM dem.grd 1",show the error above. ![1M47 }O942@1RXSUFUUEZA4](https://user-images.githubusercontent.com/140577628/259383587-dd352dee-cc5c-4e5d-8cbc-a5867b281127.jpg)
> 
> GMTSAR version:6.2 GMT version 6.0 I guass if the gmt version is low? But in the demo, I use the "p2p_processing.csh RS2 RS220110515 RS220110819 config.txt" ,the result is ok.so I do not how to solve.look forward to your reply.
Do you have the RS220110515.PRM in your topo folder ? Look at the content of the log file. and whether the scope of the dem is completely covered?

**Comment by HPUdabiao** [comment]
yes,I put the  RS220110515.PRM(master PRM file) and  RS220110515.LED  in the topo file.  I am sure that the dem is ok.Becasuse I run the "p2p_processing.csh RS2 RS220110515 RS220110819 config.txt" and the  result is beautiful.

**Comment by HPUdabiao** [comment]
I solve the problem.

I check the "p2p_processing.csh",find that below .
![BHL_RGN C H`Z3P_~((%3D_tmb](https://github.com/gmtsar/gmtsar/assets/140577628/655c54d9-54c4-455c-8990-d03cd022633d)

in the code "if else",when topo_interp_mode = 1,run the dem2topo_ra.csh master.PRM dem.grd 1
but  topo_interp_mode = 0,run the dem2topo_ra.csh master.PRM dem.grd 

then I check the config.txt file and find that the parameter "topo_interp_mode = 0 ".
so I try to run the command with "dem2topo_ra.csh master.PRM dem.grd"(no 1).
the result is beautiful.

thanks for your reply,[Xin-Wang-520](https://github.com/Xin-Wang-520)
