### ISSUE TITLE
[Help]: sbas

### ISSUE THREAD

**Issue by laxmangeo** [gmtsar/gmtsar#783]
Hello sir, 
               how to get the incident angle for sbas analysis

**Comment by laxmangeo** [comment]
Hello sir,
              I working on city subsidence,  i want to do detrend before sbas. How can i do detrend, please explain in detail

**Comment by Xin-Wang-520** [comment]
> Hello sir, how to get the incident angle for sbas analysis

SAT_look .This command yields the enu direction vector. And find the Angle of incidence

**Comment by Xin-Wang-520** [comment]
> Hello sir, I working on city subsidence, i want to do detrend before sbas. How can i do detrend, please explain in detail

You can use the gacos to trend, url is as follows: https://github.com/esrivas17/gacos_correction_for_GMTSAR

**Comment by laxmangeo** [comment]
Thank you, and one more query, when i will do GACOS correction before unwrapping or after unwrapping ?

**Comment by Xin-Wang-520** [comment]
> Thank you, and one more query, when i will do GACOS correction before unwrapping or after unwrapping ?

after unwrapping

**Comment by laxmangeo** [comment]
Hai
when i run sbas, i faced dimension not matched error. Help me
![unwrap](https://github.com/gmtsar/gmtsar/assets/127308214/c3e9c63f-dacf-44b9-8279-108be6a0dbff)
