### ISSUE TITLE
[Help]: Post SBAS running of proj_ra2ll.csh gives ERROR: tables not of same size!

### ISSUE THREAD

**Issue by KsanaGSI** [gmtsar/gmtsar#794]
Dear @Xiaohua-Eric-Xu and GMTSAR team,

I follow the https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf.
I have a problem in stage of vel.grd projecting into Latitude/Longitude:

**[gsi-gnss@Guest-gsi SBAS]$ proj_ra2ll.csh trans.dat vel.grd vel_ll.grd proj_ra2ll.csh**
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [WARNING]: 111179663 unusable points were supplied; these will be ignored.
surface [WARNING]: You should have pre-processed the data with block-mean, -median, or -mode.
surface [WARNING]: Check that previous processing steps write results with enough decimals.
surface [WARNING]: Possibly some data were half-way between nodes and subject to IEEE 754 rounding.
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [WARNING]: 111179663 unusable points were supplied; these will be ignored.
surface [WARNING]: You should have pre-processed the data with block-mean, -median, or -mode.
surface [WARNING]: Check that previous processing steps write results with enough decimals.
surface [WARNING]: Possibly some data were half-way between nodes and subject to IEEE 754 rounding.
Sampling in geocoordinates with 50 meter pixels ...
gmtmath [ERROR]: tables not of same size!
gmtmath [ERROR]: tables not of same size!
gmtmath [ERROR]: Syntax error: Operation "DIV" requires 2 operands
gmtmath [ERROR]: Syntax error: Operation "MUL" requires 2 operands
gmtmath [ERROR]: Syntax error: Operation "MUL" requires 2 operands
gmtinfo [ERROR]: Unable to decode  as a floating point number
blockmedian [ERROR]: Unable to decode  as a floating point number
xyz2grd [ERROR]: Unable to decode  as a floating point number
[gsi-gnss@Guest-gsi SBAS]$ 

What files does it mean here? How can fix it?

**Comment by Xiaohua-Eric-Xu** [comment]
I believe you want to call it this way `proj_ra2ll.csh trans.dat vel.grd vel_ll.grd 200`

**Comment by KsanaGSI** [comment]
Of course, I run proj_ra2ll.csh trans.dat vel.grd vel_ll.grd 200. It did not produce vell_ll.grd however raln.grd and ralt.grd were created. 

[gsi-gnss@Guest-gsi SBAS]$ 
[gsi-gnss@Guest-gsi SBAS]$ proj_ra2ll.csh trans.dat vel.grd vel_ll.grd 200
proj_ra2ll.csh
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [WARNING]: 111179663 unusable points were supplied; these will be ignored.
surface [WARNING]: You should have pre-processed the data with block-mean, -median, or -mode.
surface [WARNING]: Check that previous processing steps write results with enough decimals.
surface [WARNING]: Possibly some data were half-way between nodes and subject to IEEE 754 rounding.
surface [WARNING]: Your grid dimensions are mutually prime.  Convergence is very unlikely.
surface [WARNING]: 111179663 unusable points were supplied; these will be ignored.
surface [WARNING]: You should have pre-processed the data with block-mean, -median, or -mode.
surface [WARNING]: Check that previous processing steps write results with enough decimals.
surface [WARNING]: Possibly some data were half-way between nodes and subject to IEEE 754 rounding.
Sampling in geocoordinates with 50 meter pixels ...
gmtmath [ERROR]: tables not of same size!
gmtmath [ERROR]: tables not of same size!
gmtmath [ERROR]: Syntax error: Operation "DIV" requires 2 operands
gmtmath [ERROR]: Syntax error: Operation "MUL" requires 2 operands
gmtmath [ERROR]: Syntax error: Operation "MUL" requires 2 operands
gmtinfo [ERROR]: Unable to decode  as a floating point number
blockmedian [ERROR]: Unable to decode  as a floating point number
xyz2grd [ERROR]: Unable to decode  as a floating point number
[gsi-gnss@Guest-gsi SBAS]$ 
[gsi-gnss@Guest-gsi SBAS]$ ls
1		    dem_err.grd       disp_2023088.grd	disp_2023136.grd  disp_2023208.grd  intf.tab  sbas.log
2		    disp_2023040.grd  disp_2023100.grd	disp_2023148.grd  gauss_200	    raln.grd  scene.tab
3		    disp_2023052.grd  disp_2023112.grd	disp_2023160.grd  gmt.history	    ralt.grd  trans.dat
baseline_table.dat  disp_2023064.grd  disp_2023124.grd	disp_2023172.grd  intf.in	    rms.grd   vel.grd
[gsi-gnss@Guest-gsi SBAS]$

**Comment by KsanaGSI** [comment]
raln.grd: x_min: 432 x_max: 68000 x_inc: 16 name:  n_columns: 4224
raln.grd: y_min: 0 y_max: 24768 y_inc: 32 name:  n_rows: 775
raln.grd: z_min: 35.5039710999 z_max: 38.9560546875 name: z

ralt.grd: x_min: 432 x_max: 68000 x_inc: 16 name:  n_columns: 4224
ralt.grd: y_min: 0 y_max: 24768 y_inc: 32 name:  n_rows: 775
ralt.grd: z_min: 35.458366394 z_max: 38.9153289795 name: z
