### ISSUE TITLE
gmtsar_sharedir.csh is not generated when building GMTSAR

### ISSUE THREAD

**Issue by ikselven** [gmtsar/gmtsar#8]
This is somewhat related to #5. When building GMTSAR with CMake, the script `gmtsar/csh/gmtsar_sharedir.csh` is not created from its template `gmtsar/csh/gmtsar_sharedir.csh.in`.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Felix,
I just merged the pull request #5 to the master. 
Thanks,
Xiaohua(Eric)
