### ISSUE TITLE
[Help]: unwrap.grd and corr.grd dimensions are not match

### ISSUE THREAD

**Issue by laxmangeo** [gmtsar/gmtsar#800]
Hi,
    i given the region cut in the batch_tops.config (1000/15000/8500/12300) but it will process whole region
and  at the time of unwrapping snaphu_interp.csh 0.001 0 1000/15000/8500/12300. unwrapped.grd and corr.grd dimensions are not equal . when i use sbas it will create a problem. i attached unwrap and phase pdfs
[unwrap.pdf](https://github.com/gmtsar/gmtsar/files/12513225/unwrap.pdf)
[phase_compressed.pdf](https://github.com/gmtsar/gmtsar/files/12513228/phase_compressed.pdf)

**Comment by Xiaohua-Eric-Xu** [comment]
There are two fixes. One is to cut your corr.grd with `gmt grdcut corr.grd -Runwrap.grd -Gcorr_cut.grd`. The other would be to use p2p_processing.csh/batch_processing.csh for processing the data who will take in the parameters and cut the SLCs correspondingly.
