### ISSUE TITLE
[Help]: Post SBAS running of proj_ra2ll.csh

### ISSUE THREAD

**Issue by KsanaGSI** [gmtsar/gmtsar#807]
Hello All,

I follow the https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf with oher input data files.
I have a problem in stage of vel.grd projecting into Latitude/Longitude. It did not produce vell_ll.grd however raln.grd and ralt.grd were created.

[gsi-gnss@Guest-gsi SBAS]$ **proj_ra2ll.csh trans.dat vel.grd vel_ll.grd 200**
proj_ra2ll.csh
surface [WARNING]: Your grid dimensions are mutually prime. Convergence is very unlikely.
surface [WARNING]: 111179663 unusable points were supplied; these will be ignored.
surface [WARNING]: You should have pre-processed the data with block-mean, -median, or -mode.
surface [WARNING]: Check that previous processing steps write results with enough decimals.
surface [WARNING]: Possibly some data were half-way between nodes and subject to IEEE 754 rounding.
surface [WARNING]: Your grid dimensions are mutually prime. Convergence is very unlikely.
surface [WARNING]: 111179663 unusable points were supplied; these will be ignored.
surface [WARNING]: You should have pre-processed the data with block-mean, -median, or -mode.
surface [WARNING]: Check that previous processing steps write results with enough decimals.
surface [WARNING]: Possibly some data were half-way between nodes and subject to IEEE 754 rounding.
Sampling in geocoordinates with 50 meter pixels ...
gmtmath [ERROR]: tables not of same size!
gmtmath [ERROR]: tables not of same size!
gmtmath [ERROR]: Syntax error: Operation "DIV" requires 2 operands
gmtmath [ERROR]: Syntax error: Operation "MUL" requires 2 operands
gmtmath [ERROR]: Syntax error: Operation "MUL" requires 2 operands
gmtinfo [ERROR]: Unable to decode as a floating point number
blockmedian [ERROR]: Unable to decode as a floating point number
xyz2grd [ERROR]: Unable to decode as a floating point number

**Comment by Xiaohua-Eric-Xu** [comment]
OK, I am a bit confused here. Are you using the proj_ra2ll.csh script in GMTSAR or it is a script created by yourself? In proj_ra2ll.csh there's no call on gmtmath. 

Could you share your proj_ra2ll.csh script?

**Comment by Xiaohua-Eric-Xu** [comment]
This is the last part of the script in GMTSAR in master or 6.3 I believe. 
```
 64       set pix_m = `ls gauss_* | awk -F_ '{print $2/4}'` # Use 1/4 the filter width
 65       echo "Sampling in geocoordinates with $pix_m meter pixels ..."
 66   else
 67       set pix_m = 60
 68       echo "Sampling in geocoordinates with deault ($pix_m meter) pixel size ..."
 69   endif
 70 endif
 71 
 72 set incs = `m2s.csh $pix_m llp`           # Get fine and crude grid interval for lookup grids
 73 #
 74 set R =  `gmt gmtinfo llp -I$incs[2] -bi3f `
 75 gmt blockmedian llp $R -bi3f -bo3f -I$incs[1] -r -V > llpb
 76 gmt xyz2grd llpb $R -I$incs[1]  -r -fg -G$3 -bi3f
```

**Comment by KsanaGSI** [comment]
[](url)
[proj_ra2ll.txt](https://github.com/gmtsar/gmtsar/files/12618784/proj_ra2ll.txt)

**Comment by KsanaGSI** [comment]
Is it possible that my problem happened in the sbas running stage? sbas log file is too short.
[sbas.log](https://github.com/gmtsar/gmtsar/files/12618967/sbas.log)

**Comment by Xiaohua-Eric-Xu** [comment]
Sorry for the late response. If you run `gmt gmtinfo llp -bi3f -C`, at line 71, what is the output? I kind of suspect your trans.dat is corrupt but I am not sure. You could also try re-running dem2topo_ra.csh at your topo directory and reproduce your trans.dat.

**Comment by KsanaGSI** [comment]
You are right, my topo/trans.dat file has a 0 size. I will reproduce a new one.
