### ISSUE TITLE
[Help]: InSAR processing

### ISSUE THREAD

**Issue by t3asaka** [gmtsar/gmtsar#81]
Dear All,

I installed GMTSAR 6.0 from Homebrew on macOS 11.1 yesterday.
But, InSAR processing has failed (Please check the attached file).
I hope you can help me.
[errorlog.txt](https://github.com/gmtsar/gmtsar/files/5759942/errorlog.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
This is the error that failed your processing, related with region_cut (module cut_slc).

for 0/23344/0/32512, xl = 0, xh = 23344, yl = 0, yh = 32512. I forgot why I specified nr-1/nl-1. Could be a bug. A temporary fix would be to make the numbers smaller. 

85     if (xl < 0 || xl > xh || xh > nr - 1 || yl < 0 || yl > yh || yh > nl - 1)
86         die("wrong range ", "");

**Comment by t3asaka** [comment]
Hello Xiaohua(Eric),

Thank you for the replay.
But, changing the region cut (0/23344/0/32512 → 0/23340/0/32508) does not improve the situation.
Please check the attached file.
What should I do?
[errorlog2.txt](https://github.com/gmtsar/gmtsar/files/5767512/errorlog2.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
Below is the key error

grdcut (api_import_grid): NetCDF: Attempting netcdf-4 operation on netcdf-3 file [pixel.grd]
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
[Session gmt (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
mv: tmp.grd: No such file or directory

Somehow the grid (pixel.grd) generated by `gmt surface` could not be read by `gmt grdcut`. I am not sure what happened as your gmt, when installed, should depend on the same netcdf library. How did you install gmt and gmtsar?

**Comment by t3asaka** [comment]
I installed GMT using Homebrew on January 1, 2021 when I installed GMTSAR 6.0.
![2021-01-05 11 18 19](https://user-images.githubusercontent.com/53287832/103599238-0a101d80-4f48-11eb-9586-e240d96b2884.jpg)
I think the version of GMT is 5.4.5.

**Comment by Xiaohua-Eric-Xu** [comment]
If you are installing gmtsar 6.0, you should install gmt 6. Otherwise, you could install gmtsar 5.8.

**Comment by t3asaka** [comment]
Hello Xiaohua(Eric),

Thank you for the quick response.
I was able to solve the problem.
I corrected the PATH of zsh and reinstalled GMTSAR 6.0 and GMT 6.1.1.
Many thanks.
