### ISSUE TITLE
[Bug]: Stitching issue (vertical)

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#812]
I see some patches again to fix horizontal offsets. However, I believe it's not helpful because any offsets inside the approximately 2000 overlapped pixels are almost the same for the output. The real issue lies deeper in vertical offsets calculated within the C-coded tool. These lines in merge_swath.c mirror subswath header offsets and produce incorrect results (for descending orbit):

```
	head1 = GOUT->header->n_rows - G1->header->n_rows - head1;
 	head2 = GOUT->header->n_rows - G2->header->n_rows - head2;
 	if (nfile == 3)
 		head3 = GOUT->header->n_rows - G3->header->n_rows - head3;
```

See the output (incorrect):

<img width="1920" alt="Screenshot 2023-09-14 at 22 42 05" src="https://github.com/gmtsar/gmtsar/assets/7342379/83b4d600-d8c2-42d9-a620-6ed3bde83b17">

And the expected results (the code lines above removed):

<img width="1920" alt="Screenshot 2023-09-15 at 11 38 27" src="https://github.com/gmtsar/gmtsar/assets/7342379/0d349c6a-3389-4bf4-a586-1b67be692afb">

By the way, why not stitch the subswaths before processing? This way, we can produce amplitude products, perform PSI and SBAS analyses without the added complexity of managing the subswaths.

**Comment by mobigroup** [comment]
And for ascending orbit without the additional transform:

<img width="1920" alt="Screenshot 2023-09-15 at 13 50 05" src="https://github.com/gmtsar/gmtsar/assets/7342379/74812c05-8657-4f88-b0d0-32014c9345a2">

<img width="1920" alt="Screenshot 2023-09-15 at 13 51 20" src="https://github.com/gmtsar/gmtsar/assets/7342379/ff598e17-3ff6-4728-ad71-bf63bf91df7f">

Vs for the original code:

<img width="1920" alt="Screenshot 2023-09-15 at 14 18 32" src="https://github.com/gmtsar/gmtsar/assets/7342379/bcb0794d-7eac-40d6-98db-62e46bf0821b">

By the way, see GCP burst geometries:

![Unknown](https://github.com/gmtsar/gmtsar/assets/7342379/dac4f4e9-7c7a-4897-bf89-a68f84d06e05)

The phasediff tool produces vertically flipped results, and it seems that the merge_swath tool is fitted to it without flipping, using additional lines of code.

**Comment by mobigroup** [comment]
A more precise ticket will be created for further discussion.

**Comment by Xiaohua-Eric-Xu** [comment]
Will continue in the other ticket.
