### ISSUE TITLE
[Help]: preproc_batch_tops.csh data.in dem.grd 1 

### ISSUE THREAD

**Issue by MahmoudEtman1994** [gmtsar/gmtsar#814]
**preproc_batch_tops.csh data.in dem.grd 1 ,,, preproc_batch_tops.csh: command not found**
mahmoud@mahmoud-Lenovo-ideapad-300-15ISK:/media/mahmoud/Local Disk mahmoud etman/asc/F3/raw$ preproc_batch_tops.csh data.in dem.grd 1
preproc_batch_tops.csh: command not found
mahmoud@mahmoud-Lenovo-ideapad-300-15ISK:/media/mahmoud/Local Disk mahmoud etman/asc/F3/raw$ tcsh
mahmoud-Lenovo-ideapad-300-15ISK:/media/mahmoud/Local Disk mahmoud etman/asc/F3/raw> preproc_batch_tops.csh data.in dem.grd 1
preproc_batch_tops.csh: Command not found.

**Ubuntu 22.04.3 LTS**

**Comment by Xiaohua-Eric-Xu** [comment]
Did you add your GMTSAR/bin directory to your $PATH? (i.e. in your ~/.tcshrc)

**Comment by MahmoudEtman1994** [comment]
thank you xiaohua
