### ISSUE TITLE
Hi, I am working on GMTSAR. I have a query about SBAS outputs. SBAS is giving two types of outputs as displacement maps in .grd format and velocilty.grd. The SBAS command is calling number of scenes and number of interferograms. But in output has been created number of displacement map same as number of number of scenes. In this case I want to clarify (1) Is velocity map is average of all interferograms? (2) What is the master image of each displacement which have the same date as scene (is it super master image or first scene)? 

### ISSUE THREAD

**Issue by anuradhacssteap** [gmtsar/gmtsar#816]
#**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through

**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
Here are some answers:
(1) Is velocity map is average of all interferograms? 
It is not the average. It is calculated by applying a linear regression to the time-series, and then derived velocity and velocity uncertainty (rms.grd, wrong name I know). 
(2) What is the master image of each displacement which have the same date as scene?
The master image is the one you selected when aligning the stack of images. For Sentinel-1 TOPS data, it is the top row of your data.in file.

**Comment by anuradhacssteap** [comment]
Dear Eric,
Thank you so much for your reply. It's very helpful.
