### ISSUE TITLE
[Bug]: calc_dop_orb would produce wrong earth radius

### ISSUE THREAD

**Issue by insar-dev** [gmtsar/gmtsar#82]
**Describe the bug**

pass zero earth_raidus to calc_dop_orb program to calcualte earth radius
the get_sio_struct fill prm struct, at this time,prm.RE is unintialized,so it could be over zero(undefine), then call ldr_orbit function, there are some code as follows:

re = re_c;
if (prm->RE > 0.)
	re = prm->RE;
after finish run this code, re use the unintialized value（prm->RE）
so i think prm->RE should be initialzied to zero before call ldr_orbit .

**System and software version:**
 - OS: [e.g. iOS] Windows
 - GMTSAR version: last

**Comment by Xiaohua-Eric-Xu** [comment]
I think it should be using get_prm instead of get_sio_struct. In get_prm, there is a null_sio_struct that comes first. I added this to all get_sio_struct. 
f2c22e6e4e1edd288b1368257d0a33fb368a44c1
fa0184608e201a64c27c84eb2d10640bfefa540c
