### ISSUE TITLE
[Feature]: Formulas-based InSAR computation

### ISSUE THREAD

**Issue by mobigroup** [gmtsar/gmtsar#824]
GMTSAR currently employs a tool-based UNIX-style approach for processing, which may not be the most optimal method for mathematically intensive computations. What if we shifted to a formula-based processing approach that offers auto-verification and provides complete control at every step? In doing so, we can uncover some hidden GMTSAR transformations that might seem peculiar, such as the recalculation of correlation and additional filtering. Some processes are even inaccurate, like decimation without enhancing signal-to-noise, as multilooking does. The result is not only cleaner processing but also significantly faster. For instance, when processing the example dataset S1A_Stack_CPGF_T173, GMTSAR takes over 40 minutes to produce results, whereas PyGMTSAR accomplishes the same task in just 4 minutes. The notebook below executes in about 40 minutes in a very limited Google Colab environment without any hassle with software installation and data copying - in the same time as GMTSAR on an 8-core Apple Air laptop. A 10x speedup can be a game-changer in the processing!

You can explore this formula-based processing in our interactive Google Colab notebook https://colab.research.google.com/drive/1h4XxJZwFfm7EC8NUzl34cCkOVUG2uJr4?usp=sharing which offers an easy-to-write and understand approach.

```
data = sbas.multilooking(np.abs(sbas.open_data()), wavelength=400, coarsen=(1,4))
phase = sbas.multilooking(sbas.phasediff(pairs), wavelength=400, coarsen=(1,4))
corr = sbas.correlation(phase, data)
# Goldstein filter expects square grid cells produced using multilooking with coarsen=(1,4)
intf_filt = sbas.interferogram(sbas.goldstein(phase, corr, 32))
decimator = sbas.decimator(resolution_meters=60)
tqdm_dask(result := dask.persist(decimator(corr), decimator(intf_filt)), desc='Compute Phase and Correlation')
# unpack results
corr60m, intf60m = result
```

In case you wish to incorporate additional correlation filtering, similar to the approach used in GMTSAR, it's remarkably straightforward:

```
corr3x3 = sbas.multilooking(corr, wavelength=60)
```

There are no concealed 'legacy' transformations or other technical debt buried within numerous scripts and script wrappers from older scripts.

![pygmtsar2](https://github.com/gmtsar/gmtsar/assets/7342379/ba016ea9-5ee0-4b98-a032-ec3c2e78bbcd)

**Comment by Xiaohua-Eric-Xu** [comment]
This is unlikely as your development strategy is not what we would like to do or have the time do to at the moment.

**Comment by Xiaohua-Eric-Xu** [comment]
In fact, I encourage you to take-off from the current GMTSAR software, and start making your own path given you've been working on InSAR analysis for a while :). e.g., you don't really use any gmt in your software, then consider a better name such as "PySAR" or something-py instead.

**Comment by mobigroup** [comment]
Actually, I had been developing physics and math fundamentals and equipment and software for interferometry and holography in liquid photopolymers nearly a quarter of century ago :) That's the reason why I'm totally disappointed in the existing InSAR software, while GMTSAR has the best potential, in my opinion. For now, PyGMTSAR uses only 6 tools from GMTSAR, and I will surely exclude them in the future. About the naming - I've already been thinking about it, and it seems reasonable because I often refer to GMTSAR books, publications, and even codes.
