### ISSUE TITLE
[Help]: hermite: interpolation not in center interval

### ISSUE THREAD

**Issue by a5360983** [gmtsar/gmtsar#829]
Hello everyone,

I encountered difficulties while running SBAS method.
And I used the descending SAR images. 
The system of the computer is Windows 11 and Ubuntu 20.04 (WSL).
I had tried to do the steps on another computer with Windows 10 and Ubuntu 20.04 (WSL) before using Win 11,and it worked successfully.

This is my data.in file (using Win11):

 
s1a-iw2-slc-vv-20210426t215222-20210426t215250-037627-047052-005:S1A_OPER_AUX_POEORB_OPOD_20210516T121722_V20210425T225942_20210427T005942.EOF
s1a-iw2-slc-vv-20200712t215221-20200712t215249-033427-03df94-005:S1A_OPER_AUX_POEORB_OPOD_20200801T120726_V20200711T225942_20200713T005942.EOF
s1a-iw2-slc-vv-20200724t215222-20200724t215249-033602-03e4f2-005:S1A_OPER_AUX_POEORB_OPOD_20200813T120829_V20200723T225942_20200725T005942.EOF
s1a-iw2-slc-vv-20200817t215223-20200817t215251-033952-03f073-005:S1A_OPER_AUX_POEORB_OPOD_20200906T121205_V20200816T225942_20200818T005942.EOF
s1a-iw2-slc-vv-20200829t215224-20200829t215252-034127-03f6a3-005:S1A_OPER_AUX_POEORB_OPOD_20200918T121519_V20200828T225942_20200830T005942.EOF
s1a-iw2-slc-vv-20200910t215224-20200910t215252-034302-03fcbd-005:S1A_OPER_AUX_POEORB_OPOD_20200930T121454_V20200909T225942_20200911T005942.EOF
s1a-iw2-slc-vv-20200922t215224-20200922t215252-034477-040305-005:S1A_OPER_AUX_POEORB_OPOD_20201012T121254_V20200921T225942_20200923T005942.EOF
s1a-iw2-slc-vv-20201004t215225-20201004t215253-034652-040927-005:S1A_OPER_AUX_POEORB_OPOD_20201024T121305_V20201003T225942_20201005T005942.EOF
s1a-iw2-slc-vv-20201016t215225-20201016t215253-034827-040f3a-005:S1A_OPER_AUX_POEORB_OPOD_20201105T121153_V20201015T225942_20201017T005942.EOF
s1a-iw2-slc-vv-20201028t215225-20201028t215253-035002-041542-005:S1A_OPER_AUX_POEORB_OPOD_20201117T121207_V20201027T225942_20201029T005942.EOF
s1a-iw2-slc-vv-20201109t215225-20201109t215253-035177-041b4b-005:S1A_OPER_AUX_POEORB_OPOD_20201129T121152_V20201108T225942_20201110T005942.EOF
s1a-iw2-slc-vv-20201121t215224-20201121t215252-035352-042165-005:S1A_OPER_AUX_POEORB_OPOD_20201211T121150_V20201120T225942_20201122T005942.EOF
s1a-iw2-slc-vv-20201203t215224-20201203t215252-035527-042764-005:S1A_OPER_AUX_POEORB_OPOD_20201223T121431_V20201202T225942_20201204T005942.EOF
s1a-iw2-slc-vv-20201215t215224-20201215t215251-035702-042d73-005:S1A_OPER_AUX_POEORB_OPOD_20210104T121430_V20201214T225942_20201216T005942.EOF
s1a-iw2-slc-vv-20201227t215223-20201227t215251-035877-043387-005:S1A_OPER_AUX_POEORB_OPOD_20210116T121543_V20201226T225942_20201228T005942.EOF
s1a-iw2-slc-vv-20210108t215222-20210108t215250-036052-04399b-005:S1A_OPER_AUX_POEORB_OPOD_20210128T121545_V20210107T225942_20210109T005942.EOF
s1a-iw2-slc-vv-20210120t215222-20210120t215250-036227-043fc3-005:S1A_OPER_AUX_POEORB_OPOD_20210209T121849_V20210119T225942_20210121T005942.EOF
s1a-iw2-slc-vv-20210201t215221-20210201t215249-036402-0445d2-005:S1A_OPER_AUX_POEORB_OPOD_20210221T121758_V20210131T225942_20210202T005942.EOF
s1a-iw2-slc-vv-20210213t215221-20210213t215249-036577-044be5-005:S1A_OPER_AUX_POEORB_OPOD_20210305T121825_V20210212T225942_20210214T005942.EOF
s1a-iw2-slc-vv-20210225t215221-20210225t215249-036752-0451f8-005:S1A_OPER_AUX_POEORB_OPOD_20210317T121451_V20210224T225942_20210226T005942.EOF
s1a-iw2-slc-vv-20210309t215221-20210309t215249-036927-045815-005:S1A_OPER_AUX_POEORB_OPOD_20210329T121954_V20210308T225942_20210310T005942.EOF
s1a-iw2-slc-vv-20210321t215221-20210321t215249-037102-045e34-005:S1A_OPER_AUX_POEORB_OPOD_20210410T121923_V20210320T225942_20210322T005942.EOF
s1a-iw2-slc-vv-20210402t215221-20210402t215249-037277-04643a-005:S1A_OPER_AUX_POEORB_OPOD_20210422T121745_V20210401T225942_20210403T005942.EOF
s1a-iw2-slc-vv-20210414t215222-20210414t215250-037452-046a4a-005:S1A_OPER_AUX_POEORB_OPOD_20210504T121735_V20210413T225942_20210415T005942.EOF
s1a-iw2-slc-vv-20210508t215223-20210508t215251-037802-047631-005:S1A_OPER_AUX_POEORB_OPOD_20210528T121723_V20210507T225942_20210509T005942.EOF
s1a-iw2-slc-vv-20210520t215223-20210520t215251-037977-047b7d-005:S1A_OPER_AUX_POEORB_OPOD_20210609T121911_V20210519T225942_20210521T005942.EOF
s1a-iw2-slc-vv-20210601t215224-20210601t215252-038152-0480c0-005:S1A_OPER_AUX_POEORB_OPOD_20210621T121719_V20210531T225942_20210602T005942.EOF
s1a-iw2-slc-vv-20210613t215225-20210613t215253-038327-0485ee-005:S1A_OPER_AUX_POEORB_OPOD_20210703T121921_V20210612T225942_20210614T005942.EOF
s1a-iw2-slc-vv-20210625t215226-20210625t215253-038502-048b29-005:S1A_OPER_AUX_POEORB_OPOD_20210715T121906_V20210624T225942_20210626T005942.EOF
s1a-iw2-slc-vv-20210707t215226-20210707t215254-038677-04906f-005:S1A_OPER_AUX_POEORB_OPOD_20210727T121840_V20210706T225942_20210708T005942.EOF
s1a-iw2-slc-vv-20210719t215227-20210719t215255-038852-0495ad-005:S1A_OPER_AUX_POEORB_OPOD_20210808T121844_V20210718T225942_20210720T005942.EOF
s1a-iw2-slc-vv-20210731t215228-20210731t215256-039027-049ae0-005:S1A_OPER_AUX_POEORB_OPOD_20210820T121922_V20210730T225942_20210801T005942.EOF
s1a-iw2-slc-vv-20210812t215228-20210812t215256-039202-04a0ac-005:S1A_OPER_AUX_POEORB_OPOD_20210901T122143_V20210811T225942_20210813T005942.EOF
s1a-iw2-slc-vv-20210824t215229-20210824t215257-039377-04a6b6-005:S1A_OPER_AUX_POEORB_OPOD_20210913T121944_V20210823T225942_20210825T005942.EOF
s1a-iw2-slc-vv-20210905t215230-20210905t215258-039552-04acbd-005:S1A_OPER_AUX_POEORB_OPOD_20210925T122022_V20210904T225942_20210906T005942.EOF
s1a-iw2-slc-vv-20210917t215230-20210917t215258-039727-04b2b5-005:S1A_OPER_AUX_POEORB_OPOD_20211007T122020_V20210916T225942_20210918T005942.EOF
s1a-iw2-slc-vv-20210929t215230-20210929t215258-039902-04b8b9-005:S1A_OPER_AUX_POEORB_OPOD_20211019T122320_V20210928T225942_20210930T005942.EOF
s1a-iw2-slc-vv-20211011t215231-20211011t215258-040077-04bebf-005:S1A_OPER_AUX_POEORB_OPOD_20211031T122452_V20211010T225942_20211012T005942.EOF
s1a-iw2-slc-vv-20211023t215231-20211023t215259-040252-04c4d9-005:S1A_OPER_AUX_POEORB_OPOD_20211112T122423_V20211022T225942_20211024T005942.EOF
s1a-iw2-slc-vv-20211104t215230-20211104t215258-040427-04caf1-005:S1A_OPER_AUX_POEORB_OPOD_20211124T122130_V20211103T225942_20211105T005942.EOF
s1a-iw2-slc-vv-20211116t215230-20211116t215258-040602-04d10a-005:S1A_OPER_AUX_POEORB_OPOD_20211206T121842_V20211115T225942_20211117T005942.EOF
s1a-iw2-slc-vv-20211128t215230-20211128t215258-040777-04d710-005:S1A_OPER_AUX_POEORB_OPOD_20211218T121636_V20211127T225942_20211129T005942.EOF
s1a-iw2-slc-vv-20211210t215229-20211210t215257-040952-04dd20-005:S1A_OPER_AUX_POEORB_OPOD_20211230T121611_V20211209T225942_20211211T005942.EOF
s1a-iw2-slc-vv-20220103t215228-20220103t215256-041302-04e8de-005:S1A_OPER_AUX_POEORB_OPOD_20220123T121619_V20220102T225942_20220104T005942.EOF
s1a-iw2-slc-vv-20220208t215227-20220208t215255-041827-04faa3-005:S1A_OPER_AUX_POEORB_OPOD_20220228T081546_V20220207T225942_20220209T005942.EOF

When I executed : preproc_batch_tops.csh data.in dem.grd 1
I got the error message:
...
hermite: interpolation not in center interval.
hermite: interpolation not in center interval.
hermite: interpolation not in center interval.
Reading in 5195 lines of information from XML...
Writing 17 lines for the orbit...
Writing 59 lines of precise orbit for the LED file...
Junk1 successfully opened. 

Although this step failed, subsequent steps can be executed normally.
And I also get *.LED & *.PRM files successfully.
The DEM I used covered SAR image iw1, iw2, and iw3. 

I appreciate your help.
Thank you.

**Comment by Xiaohua-Eric-Xu** [comment]
You probably need to attach a longer log file. I know this should be an error related to orbits but need the prior messages to determine what happened.
