### ISSUE TITLE
[Help]: detrend interferograms

### ISSUE THREAD

**Issue by Alenhasha** [gmtsar/gmtsar#842]
Hello everyone,

I'm seeking guidance on detrending interferograms. Could you please provide insights or methods for effectively detrending my interferograms?

Thank you in advance for your assistance!

**Comment by mobigroup** [comment]
See the last interactive example here: https://github.com/mobigroup/gmtsar

**Comment by Xiaohua-Eric-Xu** [comment]
An easy way is to run `gmt grdtrend your_grid.grd -N?r -Doutput.grd`, here ? is the number of parameters for trend estimates in `m1 + m2*x + m3*y + m4*x*y + m5*x^2 + m6*y^2 + m7*x^3 + m8*x^2*y + m9*x*y^2 + m10*y^3`.

If you have strong signal in your interferogram, e.g., an earthquake. You could create a mask with `gmt grdmask ...` and then remove that part of signal from your data with `gmt grdmath your_grid.grd your_mask.grd MUL = your_grid_masked.grd`, and then estimate a trend from the rest part of your data with `gmt grdtrend your_grid.grd -N?r -Dtrend.grd`. Then you can remove the trend with `gmt grdmath your_grid.grd trend.grd SUB = your_grid_detrended.grd`.

**Comment by Alenhasha** [comment]
Thank you very much

**Comment by mobigroup** [comment]
That's better to apply Gaussian band-pass filtering for detrending. Regression approach does not work well in case then we have a mix of orbital error, tidal and topography-related and turbulence phase. See the interactive online example below for the reference:

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1h4XxJZwFfm7EC8NUzl34cCkOVUG2uJr4?usp=sharing) Imperial Valley SBAS analysis, 2015.

<img src="https://github.com/mobigroup/gmtsar/assets/7342379/bbe0f043-af09-4724-9e50-5549d3f24adc" width="50%"><img src="https://github.com/mobigroup/gmtsar/assets/7342379/cd1d8c33-3488-41af-aece-985b4d4202ae" width="50%">
