### ISSUE TITLE
[Help]: Installation problem

### ISSUE THREAD

**Issue by Asmit-iirs** [gmtsar/gmtsar#848]
**Describe the problem you met**
I am not able to install the GMTSAR software using the instruction on https://github.com/gmtsar/gmtsar/wiki/. I was able to do this previously on Ubuntu 22.04 systems multiple time but this time I am not able to do so. I have tried several times with the exact instructions.

**OS and software version**
If applicable, what operating system and software version you are using?
OS: Ubuntu 22.02
GMTSAR version: 6.3

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
Could you attach a log of your installation? e.g., output from your terminal after you run `make` and `make install`.

**Comment by Asmit-iirs** [comment]
[GMTSAR Install.TXT](https://github.com/gmtsar/gmtsar/files/13447963/GMTSAR.Install.TXT)

I've put all the commands and outputs to the attached file. Kindly check

**Comment by Asmit-iirs** [comment]
Yes I have added the following lines in the .bashrc file in my home directory

export GMTSAR=/usr/local/GMTSAR
export PATH=$GMTSAR/bin:"$PATH"

**Comment by Xiaohua-Eric-Xu** [comment]
And if you type `esarp` in your terminal, what does it say?

**Comment by Asmit-iirs** [comment]
bash: fg: %: no such job

**Comment by Asmit-iirs** [comment]
![image](https://github.com/gmtsar/gmtsar/assets/135256922/885a4623-7ab3-4870-b627-a59e625062b2)

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, that is strange. If you `echo $PATH`, what is the output?

**Comment by Asmit-iirs** [comment]
/home/iirs/miniconda3/bin:/home/iirs/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin

**Comment by Xiaohua-Eric-Xu** [comment]
Apparently, there's no GMTSAR/bin in your PATH, so I think either you did not add GMTSAR/bin to your $PATH or you did not source your bashrc file.

**Comment by Asmit-iirs** [comment]
Kindly check the following screenshot. 

![image](https://github.com/gmtsar/gmtsar/assets/135256922/5ef4c1ad-6e11-482a-a225-d50f564b1e7a)

**Comment by Xiaohua-Eric-Xu** [comment]
OK, if you do a `ls /usr/local/GMTSAR/bin`, are all the executables there?

**Comment by Xiaohua-Eric-Xu** [comment]
Also I am bit unsure why it looks like every time you run something, it tells you to run `fg` in front of it. Are you doing some customized shell scripting in your bashrc or bash_profile?

**Comment by Xiaohua-Eric-Xu** [comment]
Oh, I see, you have a `%` in front of your `esarp`. Could you not type in the `%`?

**Comment by Asmit-iirs** [comment]
Oh yes thanks I get the desired output when I type in esarp without the %

![image](https://github.com/gmtsar/gmtsar/assets/135256922/50baebf2-e7a1-4439-bc33-dd43cac9656f)

**Comment by Asmit-iirs** [comment]
Just to summarize for others if they face any problem. What I encountered is I did not source the .bashrc file which gave the errors. to source the .bashrc file type . ~/.bashrc in terminal. 

Thank you @Xiaohua-Eric-Xu very much

**Comment by Xiaohua-Eric-Xu** [comment]
You are very welcome!
