### ISSUE TITLE
Cut AoI in batch processing

### ISSUE THREAD

**Issue by ditafaith** [gmtsar/gmtsar#859]
@leouieda and everyone,
I successfully tried to process Sentinel as sample data using only 2 SAR images. 
However, if I want to get the desired small area (such as mountains, or cities) how can I do it? 
For example, I want to enter the geographic coordinates of the desired location.

**Comment by MinervaLee0429** [comment]
Hello@ditafaith , I am just doing a similar operation. As for your question, I think you can select two points in Google Map, record their coordinates in a text file named pins.ll, and then use the script ”create_frame_tops.csh“ to cut. This will require you to provide the script with precise orbit data corresponding to the SAR data, see pages 12 and 13 of this document“https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf”. 
![image](https://github.com/gmtsar/gmtsar/assets/147982617/f4ec34be-bba2-41df-b5c4-65907769e5aa)
![image](https://github.com/gmtsar/gmtsar/assets/147982617/077f5fc8-dd99-4917-8247-79d358f55a2e)
The script” organize_files_tops_linux.csh “could have been used, but I wasn't sure why the script wasn't working, so I used another method instead.

**Comment by mobigroup** [comment]
You can simply use a polygon defined in geographic coordinates to crop your desired area, even if it spans across multiple subswaths, by utilizing PyGMTSAR:

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1d9RcqBmWIKQDEwJYo8Dh6M4tMjJtvseC?usp=sharing) La Cumbre Volcano Eruption Interferogram, 2020.

<img src="https://github.com/mobigroup/gmtsar/assets/7342379/93cc9c5c-a654-4cc6-a310-2f3337c95ce2" width="50%"><img src="https://github.com/mobigroup/gmtsar/assets/7342379/fe085c2b-5bd5-4385-a1fe-04144568e1cb" width="50%">

**Comment by ditafaith** [comment]
Hi @MinervaLee0429 
Thanks for sharing your experience and sharing the resource. It helps a lot.

Also, @mobigroup with the pyGMTSAR. It looks powerful. Look for the friendly guidance step-by-step tutorial.

**Comment by mobigroup** [comment]
@ditafaith There are lots of interactive examples available on Google Colab and the explanation book on GitHub and major bookstores. What more tutorials do you mean?

**Comment by ditafaith** [comment]
@mobigroup I meant, if I want to work in my PC, we need to prepare the data, prepare the work directory and put the data inside, running the script as step by step, download the orbit, cut the AoI, until the final results in time series and velocities obtained.

**Comment by mobigroup** [comment]
@ditafaith PyGMTSAR performs all the steps for you; just define your AOI and the scenes list. It downloads the required subswaths and polarization (not the full Sentinel-1 SLC scenes), downloads the orbits, merges bursts and subswaths and scenes as needed and crops the AOI, and so on. Also, PyGMTSAR can produce SBAS and PSI results immediately in your notebook or Python script and extract trend and seasonal trend and calculate the displacement projections.

**Comment by ditafaith** [comment]
Thanks everyone for the response.

As I told earlier that I only proceeded 2 images (D-InSAR).
However, I am looking for the baseline information in the processing result (e.g. baseline.txt) which is usually generated if performed sbas command. is it possible if only for 2 images ?

**Comment by mobigroup** [comment]
Sure, it’s possible.

**Comment by ditafaith** [comment]
> Sure, it’s possible.

I meant, using gmtsar.

**Comment by mobigroup** [comment]
Yes, why not. Technically, the baseline calculated for every scene separately and the difference is the interferogram baseline value. Check GMTSAR’s SAT_baseline tool for the details.  PyGMTSAR provides the baseline results in easy way, if you prefer it. Also, for a single time task you can find the baseline on ASF using their web UI.

**Comment by Xiaohua-Eric-Xu** [comment]
> Thanks everyone for the response.
> 
> As I told earlier that I only proceeded 2 images (D-InSAR). However, I am looking for the baseline information in the processing result (e.g. baseline.txt) which is usually generated if performed sbas command. is it possible if only for 2 images ?

Try `SAT_baseline` to get detailed baseline info for a pair of images.

**Comment by ditafaith** [comment]
> > Thanks everyone for the response.
> > As I told earlier that I only proceeded 2 images (D-InSAR). However, I am looking for the baseline information in the processing result (e.g. baseline.txt) which is usually generated if performed sbas command. is it possible if only for 2 images ?
> 
> Try `SAT_baseline` to get detailed baseline info for a pair of images.

Thanks for the answer. I got it!
