### ISSUE TITLE
[Help]: Analyse incidence angle of each pixel in GMTSAR

### ISSUE THREAD

**Issue by shivamthescienceguy** [gmtsar/gmtsar#860]
Hie Eric,
I want to ask if we can extract the incidence angle of each pixel of Sentinel swaths in gmtsar,
if yes then how

**Comment by mobigroup** [comment]
See this Google Colab notebook for the example: https://colab.research.google.com/drive/1PyYcxvuyzhh-g4NQEbKjcfTDQhREZInn?usp=sharing
<img width="1920" alt="image" src="https://github.com/gmtsar/gmtsar/assets/7342379/b952afc0-e3ab-477e-9c9c-0cce08070e03">

**Comment by shivamthescienceguy** [comment]
Thanks Alexey

**Comment by Xiaohua-Eric-Xu** [comment]
There is a module called SAT_look that'll give you look vectors given lon lat elevation.
