### ISSUE TITLE
ln: failed to create symbolic link './trans.dat': File exists proj_ra2ll.csh ls: No match.

### ISSUE THREAD

**Issue by coralraha1234** [gmtsar/gmtsar#863]
Hi i  noticed that my  result ( vel-ll.grd) after runnig  step4  is in one color and it is not correct so i searched in terminal  and i faced with error :  ....trans,dat...     as i attachad in png please help me to solve it  

![Image](https://github.com/gmtsar/gmtsar/assets/108529065/2f14f07c-3f2c-455a-bff6-4c81290cc0ee)

**Comment by Xiaohua-Eric-Xu** [comment]
Hmm, you probably need to tell us a bit on what's inside step_4.csh. It does not look like from GMTSAR. I would use `ncview` to get a quick dirty view on vel.grd and check on whether the results are valid first.

**Comment by coralraha1234** [comment]
Hi Mr Xiaohua-Eric-Xu
I appreciate your help i was In hurry So i run the step before and repeated  producing interferograms again i m not sure but Before doing this i free more space And if it is not for this matter maybe it Was related to dem And tran File   so it is finished now  but If it is possible Aware me of your opinion of using l band insted of c band in tree or vegetation cover topography land
 as you know these l band images is not free .is the result of c band acceptable or not in such area ?

**Comment by Xiaohua-Eric-Xu** [comment]
If I understand correctly, you could use short time-span c-band interferograms to from a long time-series. The shorter time-span may help improve the overall coherence.

**Comment by coralraha1234** [comment]
Hi 
as you know in  ASF ( with sentinel 1 ,L1 Single Look Complex _(SLC) radar images- vv-vh)   we have 12 days time interval   images . we use 24 days interval time images  for  2  years ( so  it is  about 32 up to 34 images).is it appropriate time-span for getting reliable result in vegetation land?

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @coralraha1234, I don't have much experience on monitoring vegetation with PolSAR, so could not provide any useful suggestion on that. For GPU processing, it is common that certain parts could be speed up, e.g., focusing, geocoding, etc. But if you are able to use up the multi-threads on a server, that'll be quick too.
