### ISSUE TITLE
[Help]: ln: failed to create symbolic link './trans.dat': File exists proj_ra2ll.csh ls: No match

### ISSUE THREAD

**Issue by coralraha1234** [gmtsar/gmtsar#864]
Hi i noticed that my result ( vel-ll.grd) after runnig step4 is in one color and it is not correct so i searched in terminal and i faced with error : ....trans,dat... as i attachad in png please help me to solve it
![m](https://github.com/gmtsar/gmtsar/assets/108529065/63fb1af1-99c2-4c8d-8570-7a010e82a2d0)

**Comment by Xiaohua-Eric-Xu** [comment]
See answers here: https://github.com/gmtsar/gmtsar/issues/863
