### ISSUE TITLE
[Help]: Running SBAS 

### ISSUE THREAD

**Issue by sonasharma25** [gmtsar/gmtsar#889]
Hello sir, 
while merging F1, F2 and F3, i got issue in merging few sets so i removed them from data.in
when i am using this command sbas intf.tab scene.tab N S xdim ydim [-atm ni] [-smooth sf]
[-wavelength wl] [-incidence inc] [-range -rng] [-rms] [-dem] , 
I am getting this error, kindly help
compute RMS misfit
compute DEM error

setting smoothing to   5.000 
setting radar wavelength to   0.055 m 
setting radar incidence angle to  37.000 degree 
setting range to 837458.000 m 
number of SAR scenes is 212 
number of interferograms is 707 
Killed

**Comment by sonasharma25** [comment]
i tried it many a times. I check int.in and intf.tab, made them equal. baseline_table.dat and scene.dat are also same. but I am getting this error again and again

**Comment by kjz1997** [comment]
> i tried it many a times. I check int.in and intf.tab, made them equal. baseline_table.dat and scene.dat are also same. but I am getting this error again and again

maybe because your RAM is too small,

**Comment by sonasharma25** [comment]
okay. I will try with other computer with good memory .
