### ISSUE TITLE
[Help]:  Error with intf_tops.csh

### ISSUE THREAD

**Issue by WY-SVG** [gmtsar/gmtsar#896]
Hello,can you help me please with this error, I tried to apply intf_tops.csh one.in batch_tops.config to run one interferograme with mode = 2  in batch_tops.config and I have this error:
[Uploading 1.txt…]()

**Comment by Xiaohua-Eric-Xu** [comment]
@WY-SVG , I think you need to upload a log file. The link you attached only redirects to this issue webpage.

**Comment by Xiaohua-Eric-Xu** [comment]
I am leaving one open and closing duplicates.

**Comment by WY-SVG** [comment]
> ，我认为您需要上传日志文件。您附加的链接仅重定向到此问题网页。

Thank you for your reply. The problem has been solved.
