### ISSUE TITLE
[Help]: issue with downloading orbit files  

### ISSUE THREAD

**Issue by adarshpadhi32** [gmtsar/gmtsar#900]
i have copied the script mentioned in #852 still id didnt work and then ericc provided with a new script it worked but faced some more issue 
![Screenshot from 2024-04-11 11-45-54](https://github.com/gmtsar/gmtsar/assets/137491988/f4b4b642-7aca-40c0-b7cd-9f4c563b966f)
suggest me with some idea to correct it

**Comment by Xiaohua-Eric-Xu** [comment]
Could it be something related to SAFE_filelist? Some hints are appreciated.
