### ISSUE TITLE
[Help]: Error while using organize_files_tops.csh command.

### ISSUE THREAD

**Issue by adarshpadhi32** [gmtsar/gmtsar#901]
I did followed all the step and downloaded orbit files using new script provided and  still found some errors. i am using gmtsar version 6.2
![Screenshot from 2024-04-12 16-05-58](https://github.com/gmtsar/gmtsar/assets/137491988/57157ae9-47b5-45a3-9f90-c0e05adf67ef)

**Comment by Xiaohua-Eric-Xu** [comment]
You may want to use the older version of the script for the moment (i.e., 6.1) so that it does not try to query the deprecated ESA server. Instead it'll look for local orbit files first.
