### ISSUE TITLE
[Help]: Error while automatically download orbit file

### ISSUE THREAD

**Issue by rofiaini** [gmtsar/gmtsar#902]
**Describe the problem you met**
Error while downloading the orbits file using 'download_sentinel_orbits_linux.csh SAFE_filelist 1', I have been used before and succeed. 
Error :
(base) xxx@MSI:/mnt/e/Land_Subsidence/desc/data$ download_sentinel_orbits_linux.csh SAFE_filelist 1
 Downloading Precise Orbits (POEORB)...

------------------------------------------

Finding orbits for S1A_IW_SLC__1SDV_20170829T223338_20170829T223406_018144_01E7B1_0849.SAFE...
Required orbit file dates: 20170828 to  20170830...
--2024-04-14 20:15:58--  https://step.esa.int/auxdata/orbits/Sentinel-1/POEORB/S1A/2017/08
Resolving step.esa.int (step.esa.int)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘step.esa.int’
if: Missing file name.

**OS and software version**
If applicable, what operating system and software version you are using?
OS: linux
GMTSAR version: 6.4

![SAFE_filelist](https://github.com/gmtsar/gmtsar/assets/163650052/da75646a-72eb-4f00-9d53-61dc001b4ece)

**Comment by adarshpadhi32** [comment]
can check #898

**Comment by rofiaini** [comment]
> can check #898

hi, have you succeeded? I've downloaded the latest one, but still with the same error

**Comment by Xiaohua-Eric-Xu** [comment]
I just queried the link above "https://step.esa.int/auxdata/orbits/Sentinel-1/POEORB/S1A/2017/08", and it was able to provide me with a list of orbit files. Yet your log says "wget: unable to resolve host address ‘step.esa.int’". Internet issues?

**Comment by rofiaini** [comment]
> I just queried the link above "https://step.esa.int/auxdata/orbits/Sentinel-1/POEORB/S1A/2017/08", and it was able to provide me with a list of orbit files. Yet your log says "wget: unable to resolve host address ‘step.esa.int’". Internet issues?

I have been tried another provider, open another website and upload file was fine. I also tried the solution from ubuntu forum for change DNS address, the output still has same error.

**Comment by Xiaohua-Eric-Xu** [comment]
Hmmm, are you able to directly open the link above?

**Comment by rofiaini** [comment]
yes. It turns out that the problem was a setting on the computer that I couldn't find out what it was. I used WSL before. Now using dual boot and now I can download orbits file automatically use download_sentinel_orbits_linux.csh. Thank you for amazing script
