### ISSUE TITLE
No module named unwrap.grd was found.

### ISSUE THREAD

**Issue by shubhayanroychowdhury** [gmtsar/gmtsar#904]
Hi @Xiaohua-Eric-Xu,
When I run gmt unwrap.grd, I got this error. 
![Screenshot from 2024-04-17 10-39-31](https://github.com/gmtsar/gmtsar/assets/129718401/f2b6d131-3551-4195-befe-cb8102377b4e)

And when I go to this folder **intf_all/2022340_2022352,** the unwrap.grd file is there.
![Screenshot from 2024-04-17 10-42-16](https://github.com/gmtsar/gmtsar/assets/129718401/3506c27b-5325-4220-abd8-23393b83f0b2)

Also, I am using gmt 6.4.0 version.
![Screenshot from 2024-04-17 11-06-05](https://github.com/gmtsar/gmtsar/assets/129718401/47d1d198-d0bf-4e11-b488-73939155ee95)

Please look into it and thank you for your time.

**Comment by kjz1997** [comment]
Gmt does not have this command. If you want to use gmt, you can go to the gmt official website to see the operation guide
