### ISSUE TITLE
[Help]: Do the variable "z" respent the value of phase differences?

### ISSUE THREAD

**Issue by abachelor** [gmtsar/gmtsar#92]
Dear everyone:
      
       I tested the example of ERS Hector Mine earthquake，and very excited for success.
       To be convenient analysis, I have opened the .nc file via Matlab .
       I know the "lon","lat" from the "Attributes",
       but  what is the unit about the variable of "z"？

    Best wishes for your response!

```
read_netCDF_TEST
Source:
           D:\ERS_LINUX_OUTPUT\ERS_Hector_EQ\intf\1999258_1999293\unwrap_ll.grd
Format:
           classic
Global Attributes:
           Conventions = 'CF-1.7'
           history     = 'xyz2grd llpb -R243/244.605555556/34.0833333333/35.3041666667 -I2s/1.5s -r -fg -Gunwrap_ll.grd -bi3f'
           GMT_version = '6.0.0 [64-bit]'
           node_offset = 1
           title       = 'PWD:t unwrapped phase'
           description = 'by root on Fri 22 Jan 2021 11:05:59 PM PST with geocode.csh'
Dimensions:
           lon = 2890
           lat = 2930
Variables:
    lon
           Size:       2890x1
           Dimensions: lon
           Datatype:   double
           Attributes:
                       long_name     = 'longitude'
                       units         = 'degrees_east'
                       standard_name = 'longitude'
                       axis          = 'X'
                       actual_range  = [243      244.6056]
    lat
           Size:       2930x1
           Dimensions: lat
           Datatype:   double
           Attributes:
                       long_name     = 'latitude'
                       units         = 'degrees_north'
                       standard_name = 'latitude'
                       axis          = 'Y'
                       actual_range  = [34.0833      35.3042]
    z
           Size:       2890x2930
           Dimensions: lon,lat
           Datatype:   single
           Attributes:
                       long_name    = 'radians'
                       _FillValue   = NaN
                       actual_range = [-233.3058      194.9634]
```

**Comment by Xiaohua-Eric-Xu** [comment]
z is the component of phase (distance) change in radians, with positive defined as the distance between the ground point and the satellite increased. To convert it to mm, you need to do the following `gmt grdmath unwrap_ll.grd 4 PI MUL DIV $wavelength MUL -1000 MUL = los_ll.grd `, or in short `gmt grdmath unwrap_ll.grd -79.57747 MUL $wavelength MUL = los_ll.grd`. Then the los_ll.grd is in mm, with positive defined as the ground moved toward the satellite.

**Comment by abachelor** [comment]
> z is the component of phase (distance) change in radians, with positive defined as the distance between the ground point and the satellite increased. To convert it to mm, you need to do the following `gmt grdmath unwrap_ll.grd 4 PI MUL DIV $wavelength MUL -1000 MUL = los_ll.grd `, or in short `gmt grdmath unwrap_ll.grd -79.57747 MUL $wavelength MUL = los_ll.grd`. Then the los_ll.grd is in mm, with positive defined as the ground moved toward the satellite.

Thanks for your response! I have got it

**Comment by KIKINEO** [comment]
> z is the component of phase (distance) change in radians, with positive defined as the distance between the ground point and the satellite increased. To convert it to mm, you need to do the following `gmt grdmath unwrap_ll.grd 4 PI MUL DIV $wavelength MUL -1000 MUL = los_ll.grd `, or in short `gmt grdmath unwrap_ll.grd -79.57747 MUL $wavelength MUL = los_ll.grd`. Then the los_ll.grd is in mm, with positive defined as the ground moved toward the satellite.

Dear Professor Xu, hello, the `wavelength` here refers to the different wavelengths of each satellite. Can it be understood as the wavelength on the L or C band in the broad sense of Sentinel 1 or ALOS-2? I am here Input the wavelength, so what is the input wavelength unit? If I use the ALOS-2 satellite image as an example, is the `0.00035` I input at wavelength correct? In addition, after using the program `MAI_processing.csh` written by you, I also have the same doubts about the unit of the resulting MAI_inft_filt.grd grid file. Could you please explain it, thank you very much~

**Comment by Xiaohua-Eric-Xu** [comment]
> Can it be understood as the wavelength on the L or C band in the broad sense of Sentinel 1 or ALOS-2?

Yes.

> what is the input wavelength unit?

Meters.

> If I use the ALOS-2 satellite image as an example, is the `0.00035` I input at wavelength correct?

Nope, you should use the wavelength in the PRM file which should be ~0.2xxx.

> I also have the same doubts about the unit of the resulting MAI_inft_filt.grd grid file.

I think it should be meters.
