### ISSUE TITLE
[Help]: Topographic phase removal during execution of intf_tops.csh

### ISSUE THREAD

**Issue by mbadarmunir** [gmtsar/gmtsar#932]
Dear All,

I have followed [Hawaii tutorial](https://topex.ucsd.edu/gmtsar/tar/sentinel_time_series_5.pdf) to get myself acquainted with the SBAS process and GMTSAR. I later tried the same steps for my study area. The process completes successfully and as expected. However, I am now trying to perform additional steps. The problem I am currently facing is topo phase removal. I've also read [this ](https://github.com/gmtsar/gmtsar/issues/790)but wanted to further clarify.

The batch_tops.config file states
![Screenshot 2024-06-12 150231](https://github.com/gmtsar/gmtsar/assets/39032834/a2badfd6-11ae-46fe-8be9-cc5145912026)

If I set topo_phase = 0, intf_tops.csh command and all further steps are completed successfully. But if I set topo_phase = 1 then I get errors starting from

> OFFSET_TOPO - START
>  range decimation is: 4
> file dimensions do not match (must have same width)
> OFFSET_TOPO - END

Complete config file and log files are attached for the reference. So, here are my questions:

1. Why range decimation is being set to 2 at the very start of the execution and set to 4 when starting (probably) the phase removal, while in the config file, its value is set to 8?
2. Does topographic error and topo phase removal mean the same thing? If so, and if it's automatically done during the sbas process using -dem flag then why config file explicitly states the settings for topo phase removal?
3. How to troubleshoot the errors shown in the log file?

[log_1stIFG.txt](https://github.com/user-attachments/files/15825128/log_1stIFG.txt)
[batch_tops.config.txt](https://github.com/user-attachments/files/15825129/batch_tops.config.txt)

**Comment by mattweiuri** [comment]
hi there,

The error you got is related to shift_topo (instead of topo_phase). Try set it to 0 and see if you got any error. shift_topo is usually not needed because the DEM is pretty good. 

Matt

**Comment by mbadarmunir** [comment]
Many thanks for your reply. I'll try it and post the outcome shortly.

**Comment by mbadarmunir** [comment]
That's right on the mark. Setting shift_topo = 0 makes the process run successfully. Thank you very much.
