### ISSUE TITLE
Issue with time series extraction at a particular pixel

### ISSUE THREAD

**Issue by shubhayanroychowdhury** [gmtsar/gmtsar#935]
Hi @Xiaohua-Eric-Xu,
I was trying to get a time-series data at a particular pixel, I got some error. First I applied this command **gmt grd2xyz vel_ll.grd > xyz.txt** and found out the lat, long, and value. It is showing at this lat long, I got a results. 
![image](https://github.com/gmtsar/gmtsar/assets/129718401/b8b38ca3-9c14-4606-91ee-ffb8f3a01cea)

But when I applied this command **extract_one_time_series.csh 76.7002777757 31.709791666 supermaster.PRM dem.grd scene.tab**, I got nothing.
![image](https://github.com/gmtsar/gmtsar/assets/129718401/d48a335b-1502-4b6e-8e57-28f970790612)
Please look into it and thank you for your time and consideration.

when I run **gmt grdinfo vel_ll.grd**, I got this 
![image](https://github.com/gmtsar/gmtsar/assets/129718401/6595a62f-3154-4971-82a6-95ab5a3af8ce)

**Comment by Xiaohua-Eric-Xu** [comment]
I believe the longitude and latitude is swapped when you run extract_one_time_series.csh. Output from gmt grd2xyz is lon, lat, instead of lat, lon.
