### ISSUE TITLE
[Help]: fatal error: gmt.h: No such file or directory

### ISSUE THREAD

**Issue by SadikaSu** [gmtsar/gmtsar#937]
unable to Installation GMTSAR
error on make -->
error : fatal error: gmt.h: No such file or directory
	Line   9:  #include "gmt.h"
<attached log >
**OS and software version**
OS version : Red Hat Enterprise Linux Server - 7.9

GMTSAR version: 6.2.0
GMT version : 5.4.4

**Comment by ericlindsey** [comment]
Can you check the contents of the file configure.mk? Is your ./configure script finding the right location for the GMT libraries? 

Also, that GMT version is pretty old - you may need a newer version of both GMT and GMTSAR. Only GMTSAR version 6.5 currently works with Sentinel-1 orbit downloading, and I believe that version also requires GMT > 6.0.

**Comment by SadikaSu** [comment]
Thank you for your response, I was able to resolve the issue by installing GMT DEV
Steps to resolve : 
yum search GMT
yum install GMT-devel.x86_64
cd /usr/local/GMTSAR/
autoconf
autoupdate
 ./configure --with-orbits-dir=/usr/local/orbits
 sudo make clean
sudo make
sudo make install
