### ISSUE TITLE
[Help]: getting the following error when using 'intf_tops_parallel.csh one.in batch_tops.config 2' command in 'proc_stage = 1'

### ISSUE THREAD

**Issue by shubham-geolearner** [gmtsar/gmtsar#939]
getting the following error when using 'intf_tops_parallel.csh one.in batch_tops.config 2' command in 'proc_stage = 1'

Below is the details of the log file

clean up topo/ folder

 
DEM2TOPOPHASE.CSH - START
USER SHOULD PROVIDE DEM FILE
Working over 0/25348/0/13536 ... 
 range decimation is:  2
Topo range/azimuth map: topo_ra.pdf
DEM2TOPOPHASE.CSH - END
NO TOPOPHASE SHIFT 

START FORM A STACK OF INTERFEROGRAMS

INTF.CSH, FILTER.CSH - START
intf.csh
running phasediff...
filter.csh
Segmentation fault (core dumped)
setting range_dec = 8, azimuth_dec = 2
gauss_200 2 4 (1 2)
making amplitudes...
filtering interferogram...
making amplitude...
making correlation...
making phase...
filtering phase...
INTF.CSH, FILTER.CSH - END

SKIP UNWRAP PHASE

GEOCODE.CSH - START
SKIP GEOCODING

END STACK OF TOPS INTERFEROGRAMS

can some please help me out with this..thank you

**Comment by shubham-geolearner** [comment]
this is what i can see in the terminal

wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
blockmedian [INFORMATION]: Provides 3, expects 3-column binary data
blockmedian [INFORMATION]: Processing input table data
blockmedian [INFORMATION]: Cartesian input grid
blockmedian [INFORMATION]: Cartesian input grid
blockmedian [INFORMATION]: W: 0 E: 25348 S: 0 N: 13536 n_columns: 12674 n_rows: 6768
blockmedian [INFORMATION]: Input 3 columns via binary records using format ddd
blockmedian [INFORMATION]: Output 3 columns via binary records using format ddd
blockmedian [INFORMATION]: Reading Data Table from Standard Input stream
blockmedian [INFORMATION]: Writing Data Table to Standard Output stream
blockmedian [INFORMATION]: Calculating block medians
blockmedian [INFORMATION]: N read: 21199531 N used: 21118889 outside_area: 80642 N cells filled: 19827526
surface [INFORMATION]: Provides 3, expects 3-column binary data
surface [INFORMATION]: Cartesian input grid
surface [INFORMATION]: Cartesian input grid
surface [INFORMATION]: Grid domain: W: -126 E: 25474 S: -144 N: 13680 n_columns: 12800 n_rows: 6912 [pixel registration]
surface [INFORMATION]: Processing input table data
surface [INFORMATION]: Input 3 columns via binary records using format ddd
surface [INFORMATION]: Reading Data Table from file temp.rat
surface [INFORMATION]: Minimum value of your dataset x,y,z at: 25344.4082031 11353.6025391 105.980789185
surface [INFORMATION]: Maximum value of your dataset x,y,z at: 2606.234375 2275.59204102 5927.40576172
surface [INFORMATION]: Eliminate data points that are not nearest a node.
surface [INFORMATION]: Plane fit z = 4823.65 + (-0.145104 * col) + (-0.530893 * row)
surface [INFORMATION]: Normalize detrended data constraints by z rms = 697.995
surface [INFORMATION]: Select default convergence limit of 0.0697995 (100 ppm of L2 scale)
surface [INFORMATION]: Recompute data index for next iteration [stride = 256]
surface [INFORMATION]: ------------------------------------------
surface [INFORMATION]: Memory for data array          :  453.8 Mb
surface [INFORMATION]: Memory for final grid          :  337.9 Mb
surface [INFORMATION]: Memory for Briggs coefficients :  453.8 Mb
surface [INFORMATION]: Memory for node status         :   84.5 Mb
surface [INFORMATION]: ------------------------------------------
surface [INFORMATION]: Total memory use               :    1.3 Gb
surface [INFORMATION]: ==========================================
surface [INFORMATION]: Grid	Mode	Iteration	Max Change	Conv Limit	Total Iterations
surface [INFORMATION]: Set finite-difference coefficients [stride = 256]
surface [INFORMATION]: Determine nearest point and set Briggs coefficients [stride = 256]
surface [INFORMATION]:  256	D	      20	0.000164447447194	0.000272654254302	        20
surface [INFORMATION]: Recompute data index for next iteration [stride = 128]
surface [INFORMATION]: Expand grid by factor of 2 when going from stride = 256 to 128
surface [INFORMATION]: Fill in expanded grid by bilinear interpolation [stride = 128]
surface [INFORMATION]:  128	I	      38	0.000517876089643	0.000545308508604	        58
surface [INFORMATION]: Determine nearest point and set Briggs coefficients [stride = 128]
surface [INFORMATION]:  128	D	      22	0.000459141849128	0.000545308508604	        80
surface [INFORMATION]: Recompute data index for next iteration [stride = 64]
surface [INFORMATION]: Expand grid by factor of 2 when going from stride = 128 to 64
surface [INFORMATION]: Fill in expanded grid by bilinear interpolation [stride = 64]
surface [INFORMATION]:   64	I	      36	0.000951549831261	0.00109061701721	       116
surface [INFORMATION]: Determine nearest point and set Briggs coefficients [stride = 64]
surface [INFORMATION]:   64	D	      17	0.000764601284019	0.00109061701721	       133
surface [INFORMATION]: Recompute data index for next iteration [stride = 32]
surface [INFORMATION]: Expand grid by factor of 2 when going from stride = 64 to 32
surface [INFORMATION]: Fill in expanded grid by bilinear interpolation [stride = 32]
surface [INFORMATION]:   32	I	      33	0.00208353326404	0.00218123403441	       166
surface [INFORMATION]: Determine nearest point and set Briggs coefficients [stride = 32]
surface [INFORMATION]:   32	D	     372	0.002180476756	0.00218123403441	       538
surface [INFORMATION]: Recompute data index for next iteration [stride = 16]
surface [INFORMATION]: Expand grid by factor of 2 when going from stride = 32 to 16
surface [INFORMATION]: Fill in expanded grid by bilinear interpolation [stride = 16]
surface [INFORMATION]:   16	I	      32	0.00357565682239	0.00436246806883	       570
surface [INFORMATION]: Determine nearest point and set Briggs coefficients [stride = 16]
surface [INFORMATION]:   16	D	    2078	0.00435984558636	0.00436246806883	      2648
surface [INFORMATION]: Recompute data index for next iteration [stride = 8]
surface [INFORMATION]: Expand grid by factor of 2 when going from stride = 16 to 8
surface [INFORMATION]: Fill in expanded grid by bilinear interpolation [stride = 8]
surface [INFORMATION]:    8	I	      31	0.00683431831891	0.00872493613766	      2679
surface [INFORMATION]: Determine nearest point and set Briggs coefficients [stride = 8]
surface [INFORMATION]:    8	D	    7309	0.00872333149946	0.00872493613766	      9988
surface [INFORMATION]: Recompute data index for next iteration [stride = 4]
surface [INFORMATION]: Expand grid by factor of 2 when going from stride = 8 to 4
surface [INFORMATION]: Fill in expanded grid by bilinear interpolation [stride = 4]
surface [INFORMATION]:    4	I	      28	0.0138490702386	0.0174498722753	     10016
surface [INFORMATION]: Determine nearest point and set Briggs coefficients [stride = 4]
surface [INFORMATION]:    4	D	    4000	0.0371781851755	0.0174498722753	     14016
surface [INFORMATION]: Recompute data index for next iteration [stride = 2]
surface [INFORMATION]: Expand grid by factor of 2 when going from stride = 4 to 2
surface [INFORMATION]: Fill in expanded grid by bilinear interpolation [stride = 2]
surface [INFORMATION]:    2	I	      23	0.0337426661052	0.0348997445506	     14039
surface [INFORMATION]: Determine nearest point and set Briggs coefficients [stride = 2]
surface [INFORMATION]:    2	D	    2000	0.0643653345298	0.0348997445506	     16039
surface [INFORMATION]: Recompute data index for next iteration [stride = 1]
surface [INFORMATION]: Expand grid by factor of 2 when going from stride = 2 to 1
surface [INFORMATION]: Fill in expanded grid by bilinear interpolation [stride = 1]
surface [INFORMATION]:    1	I	      18	0.0661442673863	0.0697994891013	     16057
surface [INFORMATION]: Determine nearest point and set Briggs coefficients [stride = 1]
surface [INFORMATION]:    1	D	    1000	0.0892668333324	0.0697994891013	     17057
surface [INFORMATION]: Compute rms misfit and curvature.
surface [INFORMATION]: Fit info: N data points  N nodes	mean error	rms error	curvature
surface [INFORMATION]: 	19827526	88493313	1.34043897326e-05	0.0200059703417	356729.975928
surface [INFORMATION]: Writing grid to file pixel.grd
grd2cpt [INFORMATION]: Reading CPT from File /usr/local/share/cpt/gray.cpt
grd2cpt [INFORMATION]: Processing input grid(s)
grd2cpt [INFORMATION]: Cartesian input grid
grd2cpt [INFORMATION]: Reading grid from file topo_ra.grd
grd2cpt [INFORMATION]: Cartesian input grid
grd2cpt [INFORMATION]: gmt_grd_BC_set: Set boundary condition for all edges: natural
grd2cpt [INFORMATION]: gmt_grd_BC_set: Set boundary condition for left   edge: natural
grd2cpt [INFORMATION]: gmt_grd_BC_set: Set boundary condition for right  edge: natural
grd2cpt [INFORMATION]: gmt_grd_BC_set: Set boundary condition for bottom edge: natural
grd2cpt [INFORMATION]: gmt_grd_BC_set: Set boundary condition for top    edge: natural
grd2cpt [INFORMATION]: Mean and S.D. of data are 2066.47862057 1365.81854873
grd2cpt [INFORMATION]: z = 106.219841003 and CDF(z) = 0
grd2cpt [INFORMATION]: z = 316.111721197 and CDF(z) = 0.0509768216844
grd2cpt [INFORMATION]: z = 916.976728751 and CDF(z) = 0.246996166168
grd2cpt [INFORMATION]: z = 1350.24267335 and CDF(z) = 0.385307003874
grd2cpt [INFORMATION]: z = 1720.45244784 and CDF(z) = 0.495936662089
grd2cpt [INFORMATION]: z = 2066.47862057 and CDF(z) = 0.579885623094
grd2cpt [INFORMATION]: z = 2412.5047933 and CDF(z) = 0.646145077147
grd2cpt [INFORMATION]: z = 2782.71456778 and CDF(z) = 0.702745847574
grd2cpt [INFORMATION]: z = 3215.98051238 and CDF(z) = 0.755248743113
grd2cpt [INFORMATION]: z = 3816.84551994 and CDF(z) = 0.838575000981
grd2cpt [INFORMATION]: z = 5947.47851562 and CDF(z) = 1
grd2cpt [INFORMATION]: Write CPT to Stream Standard output stream
grdimage [INFORMATION]: GMT_Parse_Options: Interval-setting -B options were reordered to appear before axis and frame -B options to ensure proper parsing.
grdimage [INFORMATION]: GMT_Parse_Options: New option order: topo_ra.grd -JX7i -P -Ctopo_ra.cpt -V -K -Bxaf+lRange -B"yaf+lReversed Azimuth" -BWSen
grdimage [INFORMATION]: Read header from file topo_ra.grd
grdimage [INFORMATION]: Cartesian input grid
grdimage [INFORMATION]: Linear projection implies y-axis distance exaggeration relative to the x-axis by a factor of 1.87264
grdimage [INFORMATION]: Auto-frame interval for x-axis (item 0): a5000f1000
grdimage [INFORMATION]: Auto-frame interval for y-axis (item 0): a2000f1000
grdimage [INFORMATION]: Map scale is 1.42565 km per cm or 1:142565.
grdimage [INFORMATION]: Allocate and read data from file topo_ra.grd
grdimage [INFORMATION]: Reading grid from file topo_ra.grd
grdimage [INFORMATION]: Cartesian input grid
grdimage [INFORMATION]: gmt_grd_BC_set: Set boundary condition for all edges: natural
grdimage [INFORMATION]: gmt_grd_BC_set: Set boundary condition for left   edge: natural
grdimage [INFORMATION]: gmt_grd_BC_set: Set boundary condition for right  edge: natural
grdimage [INFORMATION]: gmt_grd_BC_set: Set boundary condition for bottom edge: natural
grdimage [INFORMATION]: gmt_grd_BC_set: Set boundary condition for top    edge: natural
grdimage [INFORMATION]: Reading CPT from File topo_ra.cpt
grdimage [INFORMATION]: Evaluate image pixel colors
grdimage [INFORMATION]: Basic z(x,y) -> gray image with no illumination.
grdimage [INFORMATION]: Plotting 8-bit grayshade image
PSL: DEFLATE compressed 85777632 to 14592751 bytes (83.0% savings at compression level 5)
using command line
......master LED file S1_20230407_ALL_F2.LED 
.........aligned LED file S1_20230501_ALL_F2.LED 
using command line
......master LED file S1_20230407_ALL_F2.LED 
.........aligned LED file S1_20230407_ALL_F2.LED 
reading topo topo_ra.grd
 xdim 25348, ydim 13536 
 Can't open filter  
 Can't open filter  
 Can't open filter  
 Can't open filter  
grdmath [ERROR]: realfilt.grd is not a number, operator or file name
grdmath [ERROR]: amp.grd is not a number, operator or file name
grdinfo [ERROR]: Cannot find file display_amp.grd
grdinfo [ERROR]: Must specify one or more input files
grd2cpt [ERROR]: Cannot find file display_amp.grd
grd2cpt [ERROR]: Option -L: Cannot decode two limits
grdimage [ERROR]: Cannot find file display_amp.grd
psscale [ERROR]: Could not parse display_amp.grd into Geographical, Cartesian, or Temporal coordinates!
psscale [ERROR]: Option -R parsing failure. Correct syntax:

**Comment by Xiaohua-Eric-Xu** [comment]
This is strange, it failed reading in the filter file. Could you check on your permissions on them? They should be located at your GMTSAR/share/gmtsar/filters/. Do a ls -l and you should be able to see the permissions.

**Comment by shubham-geolearner** [comment]
these is the result for ls -l
-rw-rw-r-- 1 seismo010 seismo010    49 Jul  1 17:48 box5x3
-rw-rw-r-- 1 seismo010 seismo010    26 Jul  1 17:48 fill.3x3
-rw-rw-r-- 1 seismo010 seismo010  4245 Jul  1 17:48 gauss13x13
-rw-rw-r-- 1 seismo010 seismo010  5646 Jul  1 17:48 gauss15x15
-rw-rw-r-- 1 seismo010 seismo010   740 Jul  1 17:48 gauss15x3
-rw-rw-r-- 1 seismo010 seismo010   357 Jul  1 17:48 gauss15x3.m
-rw-rw-r-- 1 seismo010 seismo010  1220 Jul  1 17:48 gauss15x5
-rw-rw-r-- 1 seismo010 seismo010  1220 Jul  1 17:48 gauss15x5_53km
-rw-rw-r-- 1 seismo010 seismo010   277 Jul  1 17:48 gauss15x5.m
-rw-rw-r-- 1 seismo010 seismo010  7246 Jul  1 17:48 gauss17x17
-rw-rw-r-- 1 seismo010 seismo010  7248 Jul  1 17:48 gauss17x17_2sig
-rw-rw-r-- 1 seismo010 seismo010   873 Jul  1 17:48 gauss17x5
-rw-rw-r-- 1 seismo010 seismo010  9050 Jul  1 17:48 gauss19x19
-rw-rw-r-- 1 seismo010 seismo010    16 Jul  1 17:48 gauss1x1
-rw-rw-r-- 1 seismo010 seismo010 11052 Jul  1 17:48 gauss21x21
-rw-rw-r-- 1 seismo010 seismo010 15656 Jul  1 17:48 gauss25x25
-rw-rw-r-- 1 seismo010 seismo010  2827 Jul  1 17:48 gauss25x7
-rw-rw-r-- 1 seismo010 seismo010 21060 Jul  1 17:48 gauss29x29
-rw-rw-r-- 1 seismo010 seismo010  4214 Jul  1 17:48 gauss29x9
-rw-rw-r-- 1 seismo010 seismo010 27264 Jul  1 17:48 gauss33x33
-rw-rw-r-- 1 seismo010 seismo010  4794 Jul  1 17:48 gauss33x9
-rw-rw-r-- 1 seismo010 seismo010  1583 Jul  1 17:48 gauss3x21
-rw-rw-r-- 1 seismo010 seismo010   221 Jul  1 17:48 gauss5x3
-rw-rw-r-- 1 seismo010 seismo010   634 Jul  1 17:48 gauss5x5
-rw-rw-r-- 1 seismo010 seismo010   239 Jul  1 17:48 gauss5x5.m
-rw-rw-r-- 1 seismo010 seismo010   464 Jul  1 17:48 gauss9x5
-rw-rw-r-- 1 seismo010 seismo010  2040 Jul  1 17:48 gauss9x9
-rw-rw-r-- 1 seismo010 seismo010   634 Jul  1 17:48 gauss_alos_100m
-rw-rw-r-- 1 seismo010 seismo010   368 Jul  1 17:48 gauss_alos_100m.m
-rw-rw-r-- 1 seismo010 seismo010  2038 Jul  1 17:48 gauss_alos_200m
-rw-rw-r-- 1 seismo010 seismo010   368 Jul  1 17:48 gauss_alos_200m.m
-rw-rw-r-- 1 seismo010 seismo010  3042 Jul  1 17:48 gauss_alos_300m
-rw-rw-r-- 1 seismo010 seismo010   369 Jul  1 17:48 gauss_alos_300m.m
-rw-rw-r-- 1 seismo010 seismo010  7252 Jul  1 17:48 gauss_alos_500m
-rw-rw-r-- 1 seismo010 seismo010   368 Jul  1 17:48 gauss_alos_500m.m
-rw-rw-r-- 1 seismo010 seismo010  7249 Jul  1 17:48 gauss_alos_700m
-rw-rw-r-- 1 seismo010 seismo010   367 Jul  1 17:48 gauss_alos_700m.m
-rw-rw-r-- 1 seismo010 seismo010   745 Jul  1 17:48 gauss_dir_azi.m
-rw-rw-r-- 1 seismo010 seismo010   932 Jul  1 17:48 gauss_dir_range.m
-rw-rw-r-- 1 seismo010 seismo010   634 Jul  1 17:48 gauss_ers_100m
-rw-rw-r-- 1 seismo010 seismo010   366 Jul  1 17:48 gauss_ers_100m.m
-rw-rw-r-- 1 seismo010 seismo010  2038 Jul  1 17:48 gauss_ers_200m
-rw-rw-r-- 1 seismo010 seismo010   242 Jul  1 17:48 gaussian.m
-rw-rw-r-- 1 seismo010 seismo010   745 Jul  1 17:48 gauss_tsx_100m
-rw-rw-r-- 1 seismo010 seismo010   353 Jul  1 17:48 gauss_tsx_100m.m
-rw-rw-r-- 1 seismo010 seismo010  2553 Jul  1 17:48 gauss_tsx_200m
-rw-rw-r-- 1 seismo010 seismo010   355 Jul  1 17:48 gauss_tsx_200m.m
-rw-rw-r-- 1 seismo010 seismo010   384 Jul  1 17:48 gauss_tsx_50m
-rw-rw-r-- 1 seismo010 seismo010   352 Jul  1 17:48 gauss_tsx_50m.m
-rw-rw-r-- 1 seismo010 seismo010  1252 Jul  1 17:48 sanandreas11x7
-rw-rw-r-- 1 seismo010 seismo010  1893 Jul  1 17:48 sanandreas13x9
-rw-rw-r-- 1 seismo010 seismo010  4224 Jul  1 17:48 sanandreas2
-rw-rw-r-- 1 seismo010 seismo010    12 Jul  1 17:48 slcfilter
-rw-rw-r-- 1 seismo010 seismo010    97 Jul  1 17:48 smooth3x3
-rw-rw-r-- 1 seismo010 seismo010   447 Jul  1 17:48 xdir
-rw-rw-r-- 1 seismo010 seismo010   447 Jul  1 17:48 ydir

**Comment by shubham-geolearner** [comment]
I tried changing the above permission to 'chmod -R 777' still the same error

**Comment by shubham-geolearner** [comment]
I tried to run filter.csh individually for a specific pair and figured out that the error of 'segmentation fault (core dumped)' is coming due to this 'make_gaussin_filter'. The error is as follows:

(base) seismo010@seismo010:~/Desktop$ make_gaussian_filter 
Segmentation fault (core dumped)

Please help to resolve this issue as why this error

**Comment by Xiaohua-Eric-Xu** [comment]
`Segmentation fault (core dumped)` This is a strange error that we could not reproduce on our end. It occurred to one of our user once and yet we could not figure out what should be done to solve the problem. 

One way is to reinstall the software or maybe turn to our virtual machine https://topex.ucsd.edu/gmtsar/downloads.

**Comment by shubham-geolearner** [comment]
@Xiaohua-Eric-Xu Thankyou for your prompt response... i already did reinstallation but the same issue... probably virtual machine is the only solution..still any solution will be appreciated

**Comment by Xiaohua-Eric-Xu** [comment]
I understand it must be frustrating. It seems to be only related to Ubuntu 22.04 but I cannot produce that on my own Ubuntu 22.04 system.

**Comment by shubham-geolearner** [comment]
My linux version is as follows

(base) seismo010@seismo010:~/Desktop$ cat /etc/issue
Linux Mint 20.3 Una \n \l

**Comment by Xiaohua-Eric-Xu** [comment]
Is it possible to install your Mint system to a virtual machine? Then I might be able to reproduce the error here.

**Comment by shubham-geolearner** [comment]
Hey @Xiaohua-Eric-Xu, I rectified this error with this line-

ulimit -s unlimited


and now segmentation fault error.

Thanks

**Comment by Xiaohua-Eric-Xu** [comment]
That's interesting. I didn't know such a limit even exists.

**Comment by LiJiawei001** [comment]
"ulimit -s unlimited"
I also solved it with this line of code, thank you very much!!!
