### ISSUE TITLE
[Help]: Compilation and installation of sbas_parallel in CentOS system

### ISSUE THREAD

**Issue by MinervaLee0429** [gmtsar/gmtsar#941]
Dear professors and experts, I have a question that I would like to consult, because I found that the memory required for single-thread sbas processing is too large to meet when I was conducting SBAS-INSAR processing recently, so I want to use the script sbas_parallel for parallel processing in CentOS. However, after searching the relevant documents and consultation posts, I found that the relevant installation instructions are about Ubuntu system and mac system, I could not find the installation instructions for CentOS, and there is no reference content for the production of relevant flags, so I want to consult the experts on this problem. I am looking forward to your generous responses from experts and professors.

**Comment by MinervaLee0429** [comment]
@Xiaohua-Eric-Xu @ericlindsey @leouieda @avalentino @AlexeyPechnikov Dear professors and experts, I would like to ask you about the compilation and installation of sbas_parallel. Due to the large scope of my research area and the large amount of computing required, I managed to find the supercomputer resources of centos system. However, I tried to compile and install sbas_parallel once before according to the example of installing and compiling sbas_parallel for Ubuntu system in the help post. However, in the subsequent running process, it was found that this script can only call the memory of one node of the supercomputer, because the memory of a single node is limited, so it quickly failed, so I wonder if it is because I failed to use the installation and compilation method of the centos system, which led to such a result. Therefore, I would like to ask professors about the steps of installing and compiling sbas_parallel in centos system, and how to make flags? Thank you for your generous guidance to me.

**Comment by MinervaLee0429** [comment]
Dear experts, I would like to ask whether our sbas_parallel script can be run across nodes in the cento system supercomputer? If possible, please tell me how to compile and install sbas_parallel script in centos system?

**Comment by ericlindsey** [comment]
Hi @MinervaLee0429 the sbas_parallel program uses openMP to do parallelization, so it cannot run across nodes, only within a single node. I think you can add the flag "-mmap" to your command (sbas or sbas_parallel) so that it will use temporary disk space to expand the memory size if not enough memory is available.

As for installation, this will probably be very specific to your individual system. Do you have IT support staff for your supercomputer who might be able to help advise you on the right compiler flags/paths to add? You may also check the discussion here: https://github.com/gmtsar/gmtsar/wiki/Installing-GMTSAR-on-CentOS7-or-other-old-systems

**Comment by MinervaLee0429** [comment]
@ericlindsey Thank you for your generous reply Professor. The program sbas_parallel needs to be compiled and installed separately, so what I want to ask professor is, should -mmap be added to flags compilation? For example, when we compile sbas_parallel with this, `gcc -fopenmp -w sbas_parallel.c -I/usr/local/include/gmt -I/usr/local/GMTSAR/gmtsar -I/usr/local/include -L/usr/local/GMTSAR/gmtsar -lgmtsar -llapack -L/usr/local/lib -lgmt -L/usr/local/lib -ltiff -lm -o sbas_parallel`，we put -mmap in this flags?

**Comment by ericlindsey** [comment]
No, just add -mmap when running the code, i.e. "sbas_parallel <lots of arguments> -mmap"

**Comment by MinervaLee0429** [comment]
@ericlindsey Professor, after I used the -mmap function to run sbas_parallel, the path where I stored the processing results and the contents under his superior directory all disappeared, not only my supercomputer directory disappeared, I also could not see the directory names of other users, what is the reason for this, is it caused by the mmap function? Or is it something else?

**Comment by MinervaLee0429** [comment]
@ericlindsey Thank you for your response, Professor. I got such a result by adding -mmap under sbas_parallel command, but I didn't know how to deal with and analyze such file, so I expected professor to help me see how to deal with such file.

**Comment by Xiaohua-Eric-Xu** [comment]
These are temporary disk files that is swapped as memory when the problem size is large. You may need to wait for the final disp*.grd and aps*.grd and vel.grd to be produced. By swapping disk space (with -mmap) the reading and writing speed is affected (dependent on your storage type), so will take longer to run.

**Comment by MinervaLee0429** [comment]
@Xiaohua-Eric-Xu @ericlindsey Dear Professor, I would like to ask if our sbas_parallel script is written in parallel. Because supercomputing is special, in the process of processing should be handed over to the platform to schedule the software to control the use and allocation of resources. If the default script carries out such work, it will lead to resource overload. I have used the -mmap function to run the script twice before, but the script has been dead when it runs in general. So, I wanted to ask if our sbas_parallel script was written using the parallel running method?

**Comment by ericlindsey** [comment]
Hi @MinervaLee0429 , sbas_parallel uses OpenMP to parallelize within a single computer using all the available CPUs, but it cannot run across multiple computers or nodes. You may need to work with your HPC system administrators to figure out why the job did not run correctly. Best of luck!

**Comment by AlexeyPechnikov** [comment]
@ericlindsey It would be honest to say that the tool does not work in limited memory environments. Memory mapping is useless and even dangerous on limited and slow disks, such as those found on most university supercomputers, due to the risk of file system or disk corruption from overuse. The sbas_parallel is a single-host solution and requires terabytes of RAM for processing decent datasets.
Notably, it is possible to utilize multi-terabyte RAM Amazon EC2 instances, although this can be costly.

**Comment by MinervaLee0429** [comment]
@ericlindsey @Xiaohua-Eric-Xu @AlexeyPechnikov Dear Professor, I would like to reduce the ram required for operation by reducing interference pairs, so I would like to ask, will this increase the error in the settlement inversion results? Since I used the method of making interference pairs provided in the sbas tutorial before, if the number of interference pairs will affect the accuracy, may I ask how I should choose the right interference pair?

**Comment by AlexeyPechnikov** [comment]
@MinervaLee0429 As I answered to your ticket in PyGMTSAR repository, you might reduce processing resolution and your area to limit RAM consumption. Yes, it is possible to limit number of interferogram and obtain better quality results if these are selected well (I shared a lot of documentation and live examples about best coherence and least deviation interferogram selection, that’s not a nuclear physics at all). Select the best interferogram and resolution and apply them for your processing.

**Comment by Xiaohua-Eric-Xu** [comment]
> @ericlindsey @Xiaohua-Eric-Xu @AlexeyPechnikov Dear Professor, I would like to reduce the ram required for operation by reducing interference pairs, so I would like to ask, will this increase the error in the settlement inversion results? Since I used the method of making interference pairs provided in the sbas tutorial before, if the number of interference pairs will affect the accuracy, may I ask how I should choose the right interference pair?

If you have a mid-level cluster, sbas_paralle is the way to go (as it is changed from sbas specifically for that scenario). If you have a super computer and would like to spread across multiple nodes, you probably need to re-write the part using openmp with mpicc or other parallel compilers. Using cloud computing is great but as Alexey said, it could be costly. The -mmap option is good with fast SSD disks, but it may not be the case for supercomputer or your cluster. 

The remaining options is reducing 1) resolution, 2) number of interferograms, 3) turning off -atm option, etc. The choice of interferograms is best by computing a coherence matrix for your AOI and pick out all that beat a criterion, though it does not guarantee connection among all interferograms. So it is usually combined with e.g., all seq intfs. This is really an user option that cannot be easily generalized and apply to all scenarios.

**Comment by MinervaLee0429** [comment]
@ericlindsey @AlexeyPechnikov @Xiaohua-Eric-Xu Dear professors and experts, the reason why I need a large amount of ram is because I found that the results of my previous sbas-insar processing with gmtsar were not satisfactory, so I want to expand the time and space baseline and increase the interference pairs. I used the same data to process sbas-insar in envi's sarscape before, but I want to get more accurate results, plus what I can see from this article“Coastal subsidence detection and characterization caused by brine mining over the Yellow River Delta using time series InSAR and PCA（https://www.sciencedirect.com/science/article/pii/S1569843222002655）”, By using the range split-spectrum method proposed by Gomba et al in 2016 to estimate the ionospheric phase, and then using the data provided by the GACOS platform to remove Troposphere delays, the standard deviation of the interferogram can be reduced.
![image](https://github.com/user-attachments/assets/2f531981-0ad8-48a3-b187-fbc9f1d39e1c)
 I have also seen in gmtsar that the estimate_ionospheric_phase.csh script uses the approach proposed by Gomba et al, while gacos_operation.csh provides a way to remove Troposphere delays using gacos data. So gmtsar was used to add ionospheric phase removal (estimate_ionospheric_phase.csh was called by batch_processing.csh, so this script was used for sbas processing.) sbas processing and Troposphere delays removal. According to the instructions in this article, the result should be better after removing the two errors, but after calculating the average error of the two results, I found that gmtsar, which used two methods to remove atmospheric phase and ionospheric phase, had a larger error. I wonder if it is because I misunderstood something or omitted important processing steps. Led to the current result.

**Comment by MinervaLee0429** [comment]
@ericlindsey @AlexeyPechnikov @Xiaohua-Eric-Xu Teacher, I used the first three steps of batch_processing.csh to perform the operations before merge step in sbas process. The parameters in my config.txt
[config.txt](https://github.com/user-attachments/files/16277246/config.txt)
 are as follows: Am I using batch_processing.csh to call estimate_ionospheric_phase.csh for ionospheric phase removal because I failed to use a script?

**Comment by MinervaLee0429** [comment]
@ericlindsey @AlexeyPechnikov @Xiaohua-Eric-Xu Dear Professor, I have found that the ionospheric correction step is placed in the fourth step of batch_processing.csh, but I have found that the speed of batch_processing.csh fourth step to generate interferogram is too slow. Even in the supercomputer to generate an interferogram speed needs 4 to 5 hours, for the need for hundreds of interferogram processing, this speed is too slow, and I can not abandon this step, because this step calls estimate_ionospheric_phase.csh script for ionospheric phase extraction work. But this step is already so slow to run in a supercomputer, let alone a regular desktop computer. I don't know if it's because I don't understand what's going on, or if it's simply because the script is running at such a poor speed.

**Comment by Xiaohua-Eric-Xu** [comment]
Hi @MinervaLee0429 , Sorry for the later response. This is an interesting question. You probably need to show us your results so that we can make a guess on what happened or what can be done to improve your results. For C-band data, ionospheric phase is usually not that strong unless you are working between mid and low latitude regions. GCAOS may work sometimes and can potentially make your interferogram worse on specific dates, though it is generally considered good for removing seasonal water vapor signals.

**Comment by Xiaohua-Eric-Xu** [comment]
Also the ionospheric phase correction script is slow as it is using gmt grdfilter, while a more efficient way is to use gmt grdfft. If you are interested in making it faster, do let me know. I can guide you through the needed tests.

**Comment by MinervaLee0429** [comment]
@Xiaohua-Eric-Xu Dear professor, I have used gmt grdfilter to complete the relevant operations. Of course, I also hope to get your guidance for the operation of gmt grdfft, but now I want to solve the problem I am now facing. In order to speed up the operation, I split the image into several images. My idea is to carry out the operation of sbas-insar separately after segmentation. However, I think the result I finally got is not reliable, and it is quite different from the result obtained by other methods. I want to know what kind of mistake I made and what should I do to avoid such mistake?

**Comment by MinervaLee0429** [comment]
@ericlindsey @AlexeyPechnikov @Xiaohua-Eric-Xu @leouieda Dear Professor, I used the tool provided by gmtsar for segmentation and conducted sbas treatment on the partied part, but the final result was very poor. Compared with the settlement result obtained from the original processing with other tools, I found that the gap was too large and many errors in the result were too large. I don't know what caused it. How do I solve this problem?

**Comment by MinervaLee0429** [comment]
@ericlindsey @AlexeyPechnikov @Xiaohua-Eric-Xu @leouieda Dear Professor, in order to speed up gmtsar's ionospheric correction, I split a scene image into several parts and processed gmtsar's sbas separately from the beginning (including ionospheric correction and atmospheric correction using gacos data), but the final result was very poor. Compared with the results obtained by using the complete image for sbas processing, there is a great difference. The range of pixel values has expanded by 5 times, and some areas have also undergone great changes, which indicates that the segmentation results are obviously incorrect. After accuracy verification, it is also found that the error of the results is quite large. I don't know if there is something wrong with my operation, I have been working on this for a long time, and I really hope to find a solution. 
This is the result of a complete image that was originally uncorrected from the ionosphere.
![图片](https://github.com/user-attachments/assets/2c1a9496-88fe-4d18-b1a3-0c7bf4417d45)
This is the result of cutting and running separately.
![图片](https://github.com/user-attachments/assets/2e56509e-09b5-448c-81a9-afef30293bfb)
I really hope to get your help, professor. I have been troubled by this problem for too long, and I urgently hope to get your guidance to solve my problem.

**Comment by ericlindsey** [comment]
Hi @MinervaLee0429, splitting the image can often result in problems because some of the steps like unwrapping work better on the full size image rather than parts. So it's not surprising to me that your original result is better. Ionosphere noise is very long-wavelength (100km or larger) and I do not see evidence of ionospheric problems in the first image above. Therefore, why not simply skip the ionosphere correction if it is the thing causing so many problems? Mostly we do not use ionospheric correction for C-band data anyway unless we see very obvious long-wavelength artifacts (like ramps across the image). In your case the non-deforming areas look fine, they are generally flat without long-wavelength errors, so I would say you can simply use your first result above.

**Comment by MinervaLee0429** [comment]
@ericlindsey Dear professor, I understand what you are saying, but I have also used SARSCAPE for SBAS-INSAR operations and obtained results. However, in order to achieve higher accuracy, I referred to the method mentioned in the article(“Coastal subsidence detection and characterization caused by brine mining over the Yellow River Delta using time series InSAR and PCA（[https://www.sciencedirect.com/science/article/pii/S1569843222002655）”](https://www.sciencedirect.com/science/article/pii/S1569843222002655%EF%BC%89%E2%80%9D)) and performed ionospheric correction while using GACOS data for atmospheric correction. However, after failing to correctly call the ionospheric correction function, I found that the accuracy was worse than before, when no ionospheric correction or GACOS correction was performed, which is the problem I am facing now. I have now found a way to call the ionospheric correction function, but I am concerned about the processing speed. The professor  @Xiaohua-Eric-Xu recommended gmt grdfft to me, but I don't know how to use this function in SBAS to replace the slow gmt grdfft. There has been no response to these questions so far, and I can only wait for the professor's answer.

**Comment by MinervaLee0429** [comment]
@Xiaohua-Eric-Xu Dear Professor, I already know that in order to improve the ionospheric correction processing speed, cropping a complete image into multiple images for sbas-insar processing will result in unsatisfactory results due to some unentanglement steps. You said earlier that gmt grdfft will run faster than gmt grdfilter, so I would like to ask you for guidance on how to replace gmt grdfilter with gmt grdfft.

**Comment by Xiaohua-Eric-Xu** [comment]
This might be a good first issue to be posted for the GMT forum here https://forum.generic-mapping-tools.org/.
