### ISSUE TITLE
[Feature]: Preprocessing individual burst images from ASF

### ISSUE THREAD

**Issue by ericlindsey** [gmtsar/gmtsar#946]
ASF has started providing Sentinel-1 SLC data as individual burst images (https://asf.alaska.edu/datasets/daac/sentinel-1-bursts/). In the ASF data search GUI, they can be viewed by clicking Datasets -> S1 Bursts in the menu bar. The downloads are provided as individual .tiff and .xml files rather than in the standard .zip folder structure.

I know that GMTSAR can already concatenate burst files via organize_files_tops.csh, but the format of these downloads are slightly different, so can we modify the script to add an option for reading these burst files directly?

**Comment by Xiaohua-Eric-Xu** [comment]
I'll check on this new format and see what we can do.

**Comment by ericlindsey** [comment]
I believe the .tiff and .xml files are essentially the same as in the old frame format, just the folder structure is different (individual files instead of in a .zip folder structure). Hopefully it will be relatively easy!

**Comment by Xiaohua-Eric-Xu** [comment]
Check this out https://github.com/gmtsar/gmtsar/discussions/954. Forrest have created a repo to convert burst files to .SAFE format. Do you mind giving that a try?

**Comment by forrestfwilliams** [comment]
Yes, the tool is called [burst2safe](https://github.com/forrestfwilliams/burst2safe) and it can be installed into a python environment using pip or conda. In the future, we plan to make SAFE the default format for our burst data, but we want to make sure it works with the major processors before making the switch.

**Comment by AlexeyPechnikov** [comment]
@ericlindsey @Xiaohua-Eric-Xu, could you please confirm if the ticket is resolved? There are two solutions available (burst2safe and the PyGMTSAR ASF module) for downloading the bursts. Even to exclude excessive downloading traffic from ASF, we need to use this approach. While I cannot estimate for GMTSAR, PyGMTSAR users download more than 3,000 scenes daily from ASF. This amounts to about 12-15 TB of data daily, which can be significantly reduced by using bursts, down to about just 2 TB of daily traffic. This translates to saving about 4 petabytes per year for which NASA ASF pays to Amazon (and the number of daily downloads is only increasing). Additionally, think about how much it helps users by limiting their downloading amount, reducing download time, and saving disk space.

**Comment by ericlindsey** [comment]
@AlexeyPechnikov I'm still waiting on the solution for burst2safe, since the safe files produced by that cause a segmentation fault in my testing (https://github.com/gmtsar/gmtsar/discussions/954). I guess they are missing the offset parameter that you mentioned. 

It's great that PyGMTSAR has a working solution already but that is not the issue here. I think the point of burst2safe is that ASF are going to run it on their full archive so they can start providing those SAFE files for individual bursts. So it's in our interest to make sure those are compatible with GMTSAR as produced, or we won't be able to use them at all.

**Comment by AlexeyPechnikov** [comment]
@ericlindsey burst2safe updates the downloaded TIFF file and recalculates the offset. I’ve checked the offset, and it is correct. Have you tried using PyGMTSAR downloaded bursts? Maybe the problem lies in the GMTSAR shell scripts because the same binaries are used successfully in PyGMTSAR.

**Comment by Xiaohua-Eric-Xu** [comment]
A fix is made here and now make_s1a_tops can extract info correctly from the burst2safe generated xmls.
