### ISSUE TITLE
doris

### ISSUE THREAD

**Issue by zahraforoodi** [gmtsar/gmtsar#948]
I installed ubuntu 20.04.
I installed fftw-3.2.1
I cant install doris.
my problem when I install Doris-5.0.3Beta is bk_messages.hh:214:26: error: invalid conversion from ‘char’ to ‘const char*’ [-fpermissive].
i tried various type of doris, but not installed.

**Comment by Xiaohua-Eric-Xu** [comment]
Well, this is a gmtsar repository. Might be good to open an issue here? https://github.com/TUDelftGeodesy/Doris

**Comment by zahraforoodi** [comment]
> Well, this is a gmtsar repository. Might be good to open an issue here? https://github.com/TUDelftGeodesy/Doris
