### ISSUE TITLE
[Help]: organize_files_tops_linux.csh - grep: tmp2.PRM: No such file or directory

### ISSUE THREAD

**Issue by mirzawaqar** [gmtsar/gmtsar#949]
**Describe the problem you met**
Kindly guide me how to fix this error. 

awk: cmd. line:1: {printf("%d",$2+0.5 + )}
awk: cmd. line:1:                       ^ syntax error
grep: tmp2.PRM: No such file or directory
if: Expression Syntax.

**OS and software version**
OS: Ubuntu20.04 LST
GMTSAR version: 6.2

[log_organize_mode1.txt](https://github.com/user-attachments/files/16155474/log_organize_mode1.txt)

**Comment by Xiaohua-Eric-Xu** [comment]
The newer version of GMTSAR gets a much larger array allocated to read in paths. So maybe updating the software could help solve the problem.
