### ISSUE TITLE
[Help]: calculating a topo_ra.grd file once

### ISSUE THREAD

**Issue by nicolaslecorvec** [gmtsar/gmtsar#953]
**Describe the problem you met**
Going through the Kilauea tutorial. Got to page 19 and running :
```
head -1 intf.in > one.in
intf_tops.csh one.in batch_tops.config
```

**OS and software version**
If applicable, what operating system and software version you are using?
OS: Linux / WSL
GMTSAR version: I downloaded it two weeks ago

**Log file**
Attach a log file output from your terminal.
[message.txt](https://github.com/user-attachments/files/16168357/message.txt)

**Screenshot**
![Capture d'écran 2024-07-10 221216](https://github.com/gmtsar/gmtsar/assets/52047672/1d135dd8-fb6d-4ef5-a52e-93d4fcf1205f)

**Comment by nicolaslecorvec** [comment]
I think I found the problem. I just read in https://gmtsar.github.io/documentation/Quick_Start_Guide.html#step-4-run-p2p-processing
that "Your DEM file must cover the entire area of your SAR image (it is better to cover more area than necessary than to cover too little area)."
I didn't do that i just selected an area that fits with my area of interest

**Comment by Xiaohua-Eric-Xu** [comment]
Glad you figured it out. Sorry that I could not respond in time as I was out in the field for a week.

**Comment by Pavithra-4pi** [comment]
pavithra@Pavithras-MacBook-Pro F1 % intf_tops.csh one.in batch_tops.config

clean up topo/ folder

 
DEM2TOPOPHASE.CSH - START
USER SHOULD PROVIDE DEM FILE
cp: ../raw/S1_20230111_ALL_F1:S1_20230123_ALL_F1.PRM: No such file or directory
grep: master.PRM: No such file or directory
grep: master.PRM: No such file or directory
grep: master.PRM: No such file or directory
grep: master.PRM: No such file or directory
grep: No match.
Working over 0//0/0 ... 
grep: master.PRM: No such file or directory
range sampling rate out of bounds
DEM2TOPOPHASE.CSH - END
NO TOPOPHASE SHIFT 

START FORM A STACK OF INTERFEROGRAMS


INTF.CSH, FILTER.CSH - START
using command line
......master LED file S1_20230111_ALL_F1.LED 
.........aligned LED file S1_20230123_ALL_F1.LED 
using command line
......master LED file S1_20230111_ALL_F1.LED 
.........aligned LED file S1_20230111_ALL_F1.LED 
intf.csh
running phasediff...
reading topo topo_ra.grd
phasediff [ERROR]: Cannot find file topo_ra.grd
phasediff [ERROR]: Cannot find file topo_ra.grd
phasediff [ERROR]: File topo_ra.grd not found
[Session phasediff (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 cannot open topofile topo_ra.grd 
filter.csh
setting range_dec = 8, azimuth_dec = 2
gauss_200 2 4 (1 2)
making amplitudes...
filtering interferogram...
conv [ERROR]: Cannot find file real.grd
conv [ERROR]: Cannot find file real.grd
conv [ERROR]: File real.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real.grd=bf 
conv [ERROR]: Cannot find file real_tmp.grd
conv [ERROR]: Cannot find file real_tmp.grd
conv [ERROR]: File real_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  real_tmp.grd=bf 
conv [ERROR]: Cannot find file imag.grd
conv [ERROR]: Cannot find file imag.grd
conv [ERROR]: File imag.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag.grd=bf 
conv [ERROR]: Cannot find file imag_tmp.grd
conv [ERROR]: Cannot find file imag_tmp.grd
conv [ERROR]: File imag_tmp.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  imag_tmp.grd=bf 
making amplitude...
grdmath [ERROR]: realfilt.grd is not a number, operator or file name
grdmath [ERROR]: amp.grd is not a number, operator or file name
grdinfo [ERROR]: Cannot find file display_amp.grd
grdinfo [ERROR]: Must specify one or more input files
grd2cpt [ERROR]: Cannot find file display_amp.grd
grd2cpt [ERROR]: Option -L: Cannot decode two limits
grdimage [ERROR]: Cannot find file display_amp.grd
psscale [WARNING]: No country code matching display_amp.grd (skipped)
psscale [ERROR]: CPT display_amp.cpt has no z-slices!
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
psconvert [ERROR]: The file display_amp.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making correlation...
grdmath [ERROR]: amp.grd is not a number, operator or file name
conv [ERROR]: Cannot find file tmp2.grd
conv [ERROR]: Cannot find file tmp2.grd
conv [ERROR]: File tmp2.grd not found
[Session conv (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 Can't open  tmp2.grd=bf 
grdimage [ERROR]: Cannot find file corr.grd
psscale [WARNING]: No country code matching corr.grd (skipped)
psscale [ERROR]: South is outside -90 to +90 degree range
psscale [ERROR]: General map projection error
psconvert [ERROR]: The file corr.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
making phase...
grdmath [ERROR]: imagfilt.grd is not a number, operator or file name
grdimage [ERROR]: Cannot find file phase.grd
psscale [WARNING]: No country code matching phase.grd (skipped)
psscale [ERROR]: South is outside -90 to +90 degree range
psscale [ERROR]: General map projection error
psconvert [ERROR]: The file phase.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
filtering phase...
phasefilt [ERROR]: Cannot find file imagfilt.grd
phasefilt [ERROR]: Cannot find file imagfilt.grd
phasefilt [ERROR]: File imagfilt.grd not found
[Session phasefilt (0)]: Error returned from GMT API: GMT_FILE_NOT_FOUND (16)
 error reading file imagfilt.grd 
grdedit [ERROR]: Cannot find file filtphase.grd
grdmath [ERROR]: filtphase.grd is not a number, operator or file name
grdimage [ERROR]: Cannot find file phasefilt.grd
psscale [WARNING]: No country code matching phasefilt.grd (skipped)
psscale [ERROR]: South is outside -90 to +90 degree range
psscale [ERROR]: General map projection error
psconvert [ERROR]: The file phasefilt.ps has no BoundingBox in the first 20 lines or last 256 bytes. Use -A option.
INTF.CSH, FILTER.CSH - END

SKIP UNWRAP PHASE

GEOCODE.CSH - START
SKIP GEOCODING

END STACK OF TOPS INTERFEROGRAMS

I am getting this error.. i cannot figure out in which step does the top_ra file gets done

**Comment by Xiaohua-Eric-Xu** [comment]
You may have set the master_image in your batch_tops.config incorrectly. Should be something like `S1_20230111_ALL_F1` instead of `S1_20230111_ALL_F1:S1_20230123_ALL_F1`
