### ISSUE TITLE
[Help]: baselines_table.dat    awk:  calling undefined function mktime   

### ISSUE THREAD

**Issue by marcontk** [gmtsar/gmtsar#956]
**Describe the problem you met**

baseline_table.dat is not created properly when I run proproc_batch_tops mode 1  

**OS and software version**
OS: macOS  Montery 12.7.5 
GMTSAR version:  6.5

**Reproduce the problem**
preproc_batch_tops.csh data.in dem.grd 1 >& pbt_mode1.log &

**Log file**
Attach a log file output from your terminal.
.
.
.
Reading in 7923 lines of info from XML...
Writing 17 lines for orbit...
Writing 282 lines of precise orbit for the LED file...
Successfully opened junk1 
using command line
......master LED file S1_20220420_ALL_F2.LED 
.........aligned LED file S1_20220420_ALL_F2.LED 
awk: calling undefined function mktime
 input record number 1, file 
 source line number 1
awk: calling undefined function mktime
 input record number 1, file 
 source line number 1
using command line
......master LED file S1_20220420_ALL_F2.LED 
.........aligned LED file S1_20220420_ALL_F2.LED 
.
.
.
Figure showing error over time

![baseline_tw](https://github.com/user-attachments/assets/f98b135c-fb64-46e7-95e4-6fa0d4bcd317)

**Comment by marcontk** [comment]
Solved, install gawk then edit baseline_table.csh and change to "gawk" in all the lines where the "mtkime" function appears.

set t0 = `echo "" | gawk '{print mktime("1992 01 01 00 00 00 00")}'`.

**Comment by Xiaohua-Eric-Xu** [comment]
Glad you figured it out.
