### ISSUE TITLE
[Help]: INSAR_G2S install

### ISSUE THREAD

**Issue by zahraforoodi** [gmtsar/gmtsar#959]
Hi 
I would like to install G2S package.
I wrote these command in terminal.
cd ~
pico .bashrc
![Screenshot from 2024-07-20 12-30-45](https://github.com/user-attachments/assets/4871b84b-5fcd-4e62-bfbc-6ce773db2376)
but, I faced the massage
![Screenshot from 2024-07-20 12-31-54](https://github.com/user-attachments/assets/5fec172d-5f62-4f02-9e01-1d27cbd9376e)

**Comment by Xiaohua-Eric-Xu** [comment]
It might be better to post this at the InSAR_G2S repository rather than here. 

Normally if you could not find a command, it is because it was not in your $PATH.

**Comment by zahraforoodi** [comment]
Thanks for the tip!

‫‪Xiaohua(Eric) Xu‬‏ ***@***.***‬‏> در تاریخ پنجشنبه ۲۲ اوت
۲۰۲۴ ساعت ۱۰:۳۷ نوشت:‬
