### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by WangBingLoveMei** [gmtsar/gmtsar#967]
Hello! Does GMTSAR's SBAS time series processing perform terrain correction? My settlement rate result is shown in the following figure, which is significantly affected by DEM. During the interference process in the official tutorial, when batch_tops. config was set to shift_topo=0, the influence of terrain phase was not removed? How can I solve the problem of terrain correction?
![Uploading DEM影响.png…]()

**Comment by Xiaohua-Eric-Xu** [comment]
By default, it does do a rough DEM error estimate utilizing the baseline info stored in intf.tab. The shift_topo parameter is used only for scenarios when interferogram baseline is large and geolocation is not as accurate (e.g., ALOS-1). The terrain phase you see could be mostly topographically correlated water vapor. 

The attached figure could not be opened BTW.
