### ISSUE TITLE
[Help]: Land_mask

### ISSUE THREAD

**Issue by mdavid3** [gmtsar/gmtsar#971]
Sorry for the simple question but how do I do this ?

" Link the new mask_def.grd to all /date1-date2/ directories "

Do I need to go into each folder in intf_all and write the following code?

`ln -s /mdavid/folders/Mount/F1/intf_all/mask_def.grd .`

![ss](https://github.com/user-attachments/assets/0f0e668c-4768-483e-aba8-4a1ea5586f00)

**Comment by Xiaohua-Eric-Xu** [comment]
You may add that to your unwrap_intf.csh script when doing phase unwrapping.
