### ISSUE TITLE
[Help]: Compilation and installation of sbas_parallel in Ubuntu

### ISSUE THREAD

**Issue by MSSJoud** [gmtsar/gmtsar#974]
**Describe the problem you met**
Hi 

I faced an issue trying to compile the sbas_parallel.c
I have received error records as if there were multiple definition of a few variables. 
The global variables that declared in gmtsar.h
I think thsy should be external some how and included in utils.c but I ma not sure because it ain't solve the issue. 
Then one variable declared double and int i.e. "forced_slope"
Did I miss something? 

Best and thanks 
Mehdi
**OS and software version**
Ubuntu 21

OS:
GMTSAR version:
6.2

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?
gcc -fopenmp -w sbas_parallel.c -I/usr/include/gmt -I/home/mehdi/gmtsar/gmtsar -I/usr/include -L/home/mehdi/gmtsar/gmtsar -lgmtsar -L/usr/lib -lgmt -llapack -lblas -lm -o sbas_parallel

[gcc_output.log](https://github.com/user-attachments/files/16498853/gcc_output.log)
**Log file**
[gcc_output.log](https://github.com/user-attachments/files/16498853/gcc_output.log)
**Screenshot**g
If applicable, attach a Screenshot to help us understand your case

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by MSSJoud** [comment]
![Screenshot from 2024-08-05 16-16-50](https://github.com/user-attachments/assets/d79fd924-7c27-4310-8fce-eb73908dbdef)

**Comment by Xiaohua-Eric-Xu** [comment]
Multiple definition can be fixed by adding -z muldefs to your CFLAGS and LDFLAGS in config.mk before running make.

**Comment by MSSJoud** [comment]
Yes, I have already added the modules!
and they were fixed some but still there are a few. 
The issue comes back when I wanted to replace the scripts for organize_files_tops_linux.csh from the older version as you recommended. 
Is there anyway to fix this issue?

**Comment by KsanaGSI** [comment]
> Multiple definition can be fixed by adding -z muldefs to your CFLAGS and LDFLAGS in config.mk before running make.

What config.mk file did you mean?  I have the same problem in Ubuntu 24.04

**Comment by Xiaohua-Eric-Xu** [comment]
> What config.mk file did you mean? I have the same problem in Ubuntu 24.04

You run autoconf and ./configure, there will be a configuration file generated based on your system settings and libs installed. That is the config.mk file.

**Comment by Xiaohua-Eric-Xu** [comment]
> Yes, I have already added the modules! and they were fixed some but still there are a few. The issue comes back when I wanted to replace the scripts for organize_files_tops_linux.csh from the older version as you recommended. Is there anyway to fix this issue?

I think for the newer version of GMTSAR you don't need to roll back to older script anymore. That was a temporary fix. Try out the new version and see if the problem persist.
