### ISSUE TITLE
[Help]: organize_files_tops_linux.csh's bug

### ISSUE THREAD

**Issue by cxinlong** [gmtsar/gmtsar#976]
**Describe the problem you met**
Write a brief description of the problem you met, e.g. my intf_tops.csh could not run through
I have downloaded the latest version of this script from the official website. However, when running this command, an error occurs as shown in the following figure. How should I solve it?
**OS and software version**
If applicable, what operating system and software version you are using?
OS:
GMTSAR version:

**Reproduce the problem**
If applicable, how to reproduce the problem from scratch?

**Log file**
Attach a log file output from your terminal.

**Screenshot**
If applicable, attach a Screenshot to help us understand your case
![IMG_20240820_220218](https://github.com/user-attachments/assets/4ee5fd98-3ea0-4dec-834a-30ad037e3b10)

[Please note that if no new responses are made over six months from users, the issue will get closed]

[Also if this is a general question that's not particlarly related to GMTSAR, such as "how to correct atmospheric noise" or "how to intepret my interferogram", consider using the discussions page]

**Comment by Xiaohua-Eric-Xu** [comment]
Sorry for the late response. It could be related to file permission or maybe the downloaded data is corrupted.
