### ISSUE TITLE
[Help]: Installing

### ISSUE THREAD

**Issue by mohammadkavehcholcheh** [gmtsar/gmtsar#980]
Is it possible to install gmtsar 6.2 on gmt 6.5?

**Comment by mdavid3** [comment]
Go to your installation directory (..../GMTSAR). 
Run git checkout new version (6.5 or master).
Then make spotless, autoconf, ./configure, make and make install.

source: @Xiaohua-Eric-Xu

**Comment by mdavid3** [comment]
please close issue
