### ISSUE TITLE
[Help]: create_frame_tops.csh

### ISSUE THREAD

**Issue by anas9876** [gmtsar/gmtsar#985]
I am trying to stitch two images using the script create_frames_tops.csh, **which I have successfully used before**. However, this time it is showing "awk syntax error" and I didn't change anything in the script or my system, as you can see in the following details. I would appreciate any guidance on resolving this issue.

command:
create_frame_tops.csh SAFEfile.list S1A_OPER_AUX_POEORB_OPOD_20240215T070741_V20240125T225942_20240127T005942.EOF two_pins.ll
------------------------------------------------------------------------------
SAFEfile.list 
/media/anas/Elements1/InSAR_Project/ascending/data/S1A_IW_SLC__1SDV_20240126T124225_20240126T124252_052278_0651FC_4E86.SAFE
/media/anas/Elements1/InSAR_Project/ascending/data/S1A_IW_SLC__1SDV_20240126T124249_20240126T124316_052278_0651FC_6325.SAFE
------------------------------------------------------------------------------
two_pins.ll
78.90101, 40.37968
78.4514, 42.06249

Error:
------------------------------------------------------------------------------
anas@anas-Precision-3650-Tower:/media/anas/Elements1/InSAR_Project/ascending/reframed$ create_frame_tops.csh SAFEfile.list S1A_OPER_AUX_POEORB_OPOD_20240215T070741_V20240125T225942_20240127T005942.EOF two_pins.ll
Combining vv data...

Working on subswath 1 ...
Reading in 5631 lines of info from XML...
Writing 16 lines for orbit...
Writing 282 lines of precise orbit for the LED file...
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: cmd. line:1: {printf("%d",$2+0.5 + )}
awk: cmd. line:1:                       ^ syntax error
awk: cmd. line:1: {printf("%d",$2+0.5 + )}
awk: cmd. line:1:                       ^ syntax error
Working on bursts covering  (78.4514, 42.06249) -  (78.90101, 40.37968)...

Usage: assemble_tops azi_1 azi_2 name_stem1 name_stem2 ... output_stem

Example: assemble_tops 1685 9732 s1a-iw1-slc-vv-20150706t135900-20150706t135925-006691-008f28-001 s1a-iw1-slc-vv-20150706t135925-20150706t135950-006691-008f28-001 s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001

Output:s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.xml s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.tiff

Note: output files are bursts that covers area between azi_1 and azi_2, set them to 0s to output all bursts
 Error: Incorrect input... 
 
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
mv: cannot stat 'new.xml': No such file or directory
mv: cannot stat 'new.tiff': No such file or directory

Working on subswath 2 ...
Reading in 5637 lines of info from XML...
Writing 16 lines for orbit...
Writing 283 lines of precise orbit for the LED file...
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: cmd. line:1: {printf("%d",$2+0.5 + )}
awk: cmd. line:1:                       ^ syntax error
awk: cmd. line:1: {printf("%d",$2+0.5 + )}
awk: cmd. line:1:                       ^ syntax error
Working on bursts covering  (78.4514, 42.06249) -  (78.90101, 40.37968) ...

Usage: assemble_tops azi_1 azi_2 name_stem1 name_stem2 ... output_stem

Example: assemble_tops 1685 9732 s1a-iw1-slc-vv-20150706t135900-20150706t135925-006691-008f28-001 s1a-iw1-slc-vv-20150706t135925-20150706t135950-006691-008f28-001 s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001

Output:s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.xml s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.tiff

Note: output files are bursts that covers area between azi_1 and azi_2, set them to 0s to output all bursts
 Error: Incorrect input... 
 
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
mv: cannot stat 'new.xml': No such file or directory
mv: cannot stat 'new.tiff': No such file or directory

Working on subswath 3 ...
Reading in 5637 lines of info from XML...
Writing 16 lines for orbit...
Writing 282 lines of precise orbit for the LED file...
 
Usage: shift_aline_PRM.csh file.PRM num_lines 
 
Example: shift_aline_PRM.csh IMG-HH-ALPSRP049040660-H1.0__A.PRM 12365.84726

Note: To shift the PRM file with a given number of lines along azimuth.
awk: cmd. line:1: {printf("%d",$2+0.5 + )}
awk: cmd. line:1:                       ^ syntax error
awk: cmd. line:1: {printf("%d",$2+0.5 + )}
awk: cmd. line:1:                       ^ syntax error
Working on bursts covering  (78.4514, 42.06249) -  (78.90101, 40.37968) ...

Usage: assemble_tops azi_1 azi_2 name_stem1 name_stem2 ... output_stem

Example: assemble_tops 1685 9732 s1a-iw1-slc-vv-20150706t135900-20150706t135925-006691-008f28-001 s1a-iw1-slc-vv-20150706t135925-20150706t135950-006691-008f28-001 s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001

Output:s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.xml s1a-iw1-slc-vv-20150706t135900-20150706t135950-006691-008f28-001.tiff

Note: output files are bursts that covers area between azi_1 and azi_2, set them to 0s to output all bursts
 Error: Incorrect input... 
 
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
grep: new.xml: No such file or directory
mv: cannot stat 'new.xml': No such file or directory
mv: cannot stat 'new.tiff': No such file or directory

Editing name of the new file...
ls: No match.
gmtinfo [ERROR]: No input data found!
ls: No match.
gmtinfo [ERROR]: No input data found!
ls: No match.
gmtinfo [ERROR]: No input data found!

-------------------------------------------------------------------
Thanks in advance for your help!
Anas

**Comment by Xiaohua-Eric-Xu** [comment]
You probably don't need the "," in your pins.ll.

**Comment by anas9876** [comment]
Its fixed now. Thanks a lot, Prof. Eric
