### ISSUE TITLE
[Help]:Installation 

### ISSUE THREAD

**Issue by charanchaganti93** [gmtsar/gmtsar#99]
Hello,

We have a HPC Terminal of RHEL
How can we install GMTSAR in the terminal. Kindly suggest

Thanks
Charan

**Comment by Xiaohua-Eric-Xu** [comment]
Hi Charan,
You could get GMT installed, then all the needed libs are there for GMTSAR.
Here's an installing guide for GMT. https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md
Here's the building guide. https://github.com/GenericMappingTools/gmt/blob/master/BUILDING.md
Cheers,
Xiaohua(Eric)

**Comment by charanchaganti93** [comment]
We have a problem here, due to some security concerns they don't give us the access to root in HPC but we generally do write every command of GMTSAR in the root itself. Is it possible to run it if we install GMTSAR in any other directory instead of usr/local/. 

Thanks 
Charan

**Comment by Xiaohua-Eric-Xu** [comment]
Yes. You could install anywhere you want. It's the same with other libs. Do specify the path of them in config.mk before compiling and it should work.
